function result = main_stage_A4_RNS_1()
%MAIN_STAGE_A4_RNS_1 Run only the recursive numerical-stability milestone.
%
% This entry does not rerun A4-2D-2A, update a state, create runs/<run_id>,
% execute a complete IPM, or advance the stage.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
result = run_stage_a4_rns1_stability_audit(projectRoot);
if result.milestone_status~="PASS"
    fprintf(2,"A4-RNS-1 blocking audit failed:\n");
    if isfield(result,"blocking")
        disp(result.blocking);
    end
    if isfield(result,"fixture")
        disp(result.fixture);
    end
    if isfield(result,"operator_audit")
        disp(result.operator_audit);
    end
end
assert(result.milestone_status=="PASS" && ...
    result.all_blocking_pass && ...
    result.stage_status=="READY" && ...
    result.d2a_original_status_preserved=="FAIL_RETRYABLE" && ...
    ~result.stage_a4_pass_claimed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.d2a_rerun_executed && ...
    ~result.execution.stage_b_entered, ...
    "stageA4:rns1:MainContract", ...
    "A4-RNS-1 did not satisfy its isolated stability contract.");
print_summary(result);
end

function print_summary(result)
actual = result.actual;
fprintf("A4-RNS-1 status=%s; stage=%s / %s\n", ...
    result.milestone_status,result.stage_id,result.stage_status);
fprintf("day17_symmetry=%.17g direction_error=%.17g "+ ...
    "recursive_kkt=%.17g direct_kkt=%.17g margin=%s\n", ...
    actual.day17_response_symmetry_relative, ...
    actual.direction_relative_error, ...
    actual.recursive_full_kkt_relative_residual, ...
    actual.direct_full_kkt_relative_residual, ...
    actual.numerical_margin_status);
fprintf("components xi=%.17g y=%.17g l=%.17g z=%.17g\n", ...
    actual.xi_relative_error,actual.y_relative_error, ...
    actual.l_relative_error,actual.z_relative_error);
disp(result.refinement);
end
