function result = main_stage_A3()
%MAIN_STAGE_A3 Execute the formal seven-day single-direction audit.
% No optimization/IPM loop, parallel work, dispatch, or economic result is
% produced by this entry point.

projectRoot=string(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(projectRoot,"src")));
addpath(fullfile(projectRoot,"tests"));
assert_stage_a3_preflight(projectRoot);
config=load_stage_a3_configuration(projectRoot);
environment=inspect_stage_a3_environment();
[inputHashes,inputHashesPass]=verify_input_hashes(projectRoot);
environmentPass=all(string(environment.status(logical(environment.blocking)))=="PASS");
solverWillExecute=environmentPass&&inputHashesPass;
formalCommand=['matlab -batch "result=main_stage_A3(); ' ...
    'assert(strcmp(char(result.status),''PASS''))"'];
metadata=struct( ...
    "run_purpose",char(config.run_purpose), ...
    "time_scope_type",char(config.time_scope_type), ...
    "day_ids",config.days,"hours",config.hours, ...
    "soc_boundary_mode",char(config.soc_boundary_mode), ...
    "formal_model_soc_boundary", ...
        "full_24_hour_day_fixed_half_energy_no_interday_link", ...
    "expected_full_kkt_dimension",config.expected_full_kkt_dimension, ...
    "expected_day_count",config.expected_day_count, ...
    "expected_daily_chain_dimensions", ...
        config.expected_daily_hourly_chain_dimensions, ...
    "expected_day_response_dimension",config.expected_day_response_dimension, ...
    "expected_global_core_dimension",config.expected_global_core_dimension, ...
    "expected_fixed_zero_count",config.expected_fixed_zero_count, ...
    "aggregation_day_order",config.aggregation_day_order, ...
    "a2_baseline_run_id","20260720_145803_stage_A2_83e04697", ...
    "a2_baseline_status","PASS", ...
    "a2_baseline_git_commit","83e04697412bfea436c7eff10fa193cba70d6052", ...
    "actual_execution_command",formalCommand, ...
    "actual_test_command","NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK", ...
    "newton_direction_count",1,"optimization_executed",false, ...
    "full_ipm_executed",false,"parallel_executed",false, ...
    "a3_solver_executed",false,"physical_dispatch_interpretation",false, ...
    "capacity_planning_interpretation",false, ...
    "economic_interpretation",false, ...
    "water_constraints_enabled",false, ...
    "thermal_second_pass_enabled",false, ...
    "day_response_side_effects","none", ...
    "enabled_components",["OBJ_INVEST","CAP_BOUNDS_GLOBAL", ...
        "DURATION_GLOBAL","DAILY_CAPACITY_COPY","CAPACITY_BINDING", ...
        "HOURLY_POWER_BALANCE","FORMAL_DAILY_SOC"], ...
    "disabled_components",["FULL_IPM","OPTIMIZATION","PARALLEL", ...
        "DAILY_WATER","THERMAL_SECOND_PASS","UC","ECONOMIC_INTERPRETATION"]);
runContext=create_run_context(projectRoot,"stage_A3", ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",config.source_paths.stage, ...
    "ManifestMetadata",metadata);
a3Command="run_stage_A3_tests('EvidenceDirectory','"+ ...
    replace(string(runContext.tests_dir),"'","''")+"')";
a2Directory=fullfile(runContext.tests_dir,"a2_regression");
a2Command="run_stage_A2_tests('EvidenceDirectory','"+ ...
    replace(string(a2Directory),"'","''")+"')";
a1Directory=fullfile(runContext.tests_dir,"a1_regression");
a1Command="run_stage_A1_tests('EvidenceDirectory','"+ ...
    replace(string(a1Directory),"'","''")+"')";

acceptance=table(); issues=new_stage_a3_issue_log(); stagingRoot="";
try
    environmentArtifact=addvars(environment, ...
        repmat(string(runContext.run_id),height(environment),1), ...
        'Before',1,'NewVariableNames','run_id');
    write_new_table(runContext.environment_csv_path,environmentArtifact);
    write_new_table(runContext.input_hashes_csv_path, ...
        input_hash_table(inputHashes,runContext.run_id));
    if ~solverWillExecute
        acceptance=initialize_stage_a3_acceptance(projectRoot);
        for row=1:height(acceptance)
            acceptance=set_stage_a3_acceptance_result(acceptance, ...
                acceptance.test_id(row),"BLOCKED", ...
                "not run because environment/input preflight failed", ...
                "external dependency blocked","environment.csv; input_hashes.csv");
        end
        issues=append_stage_a3_issue(issues,runContext,"PRECHECK-EXTERNAL", ...
            "external_preflight","MATLAB environment or controlled input", ...
            "A3 direction was not executed", ...
            "Environment or input SHA256 failed", ...
            "external environment or controlled input mismatch", ...
            "Restore the required environment/input and create a new run", ...
            "BLOCKED","environment.csv; input_hashes.csv");
        write_new_table(runContext.acceptance_results_path,acceptance);
        write_new_table(runContext.issue_log_path,issues);
        exception=MException("stageA3:external:Blocked", ...
            "A3 was not executed because external preflight failed.");
        report=generate_stage_a3_failure_report(runContext,exception,issues,acceptance);
        hashes=write_stage_a3_evidence_hashes(runContext);
        hashPath=fullfile(runContext.acceptance_dir,"evidence_hashes.csv");
        manifest=finalize_run_manifest(runContext,"BLOCKED_EXTERNAL",struct( ...
            "blocking_acceptance_total",6,"blocking_acceptance_pass",0, ...
            "evidence_hashes","acceptance/evidence_hashes.csv", ...
            "evidence_hashes_sha256",compute_sha256_file(hashPath), ...
            "evidence_file_count",height(hashes), ...
            "reports",struct("failure",relative_run_path(report,runContext.root)), ...
            "first_failed_layer","external_preflight"));
        result=struct("run_id",string(runContext.run_id), ...
            "run_path",string(runContext.root),"status","BLOCKED_EXTERNAL", ...
            "acceptance",acceptance,"issues",issues,"manifest",manifest);
        return
    end

    data=load_project_data(projectRoot);
    record_stage_a3_test_command(runContext,a3Command,a2Command,a1Command);
    a3Tests=run_stage_A3_tests('EvidenceDirectory',runContext.tests_dir, ...
        'CommandText',a3Command);
    a2Tests=run_stage_A2_tests('EvidenceDirectory',a2Directory, ...
        'CommandText',a2Command);
    a1Tests=run_stage_A1_tests('EvidenceDirectory',a1Directory, ...
        'CommandText',a1Command);
    assert(a3Tests.all_pass,"stageA3:tests:A3Failed", ...
        "The fixed A3 test suite did not pass.");
    assert(a2Tests.all_pass&&a2Tests.summary.test_total==32, ...
        "stageA3:tests:A2RegressionFailed", ...
        "All 32 A2 regression tests must pass before A3 execution.");
    assert(a1Tests.all_pass&&a1Tests.summary.test_total==37, ...
        "stageA3:tests:A1RegressionFailed", ...
        "All 37 A1 regression tests must pass before A3 execution.");
    assert(all_required_test_evidence_exists(a3Tests.paths)&& ...
        all_required_test_evidence_exists(a2Tests.paths)&& ...
        all_required_test_evidence_exists(a1Tests.paths), ...
        "stageA3:tests:EvidenceIncomplete", ...
        "A3, A2, and A1 CSV/JUnit/log/command/summary/inventory evidence is required.");

    index=build_stage_a3_index(data,"RunId",string(runContext.run_id));
    mark_stage_a3_solver_execution(runContext);
    verification=run_stage_a3_direction_verification(data,index,config);
    assert(isfinite(verification.audit.full_kkt_relative_residual)&& ...
        verification.audit.full_kkt_relative_residual<=1e-10, ...
        "stageA3:numeric:DirectResidualHardLimit", ...
        "Direct full-KKT relative residual %.17g exceeds 1e-10.", ...
        verification.audit.full_kkt_relative_residual);
    codeScan=scan_stage_a3_forbidden_code(projectRoot,config);
    assert(all(string(codeScan.status)=="PASS"), ...
        "stageA3:scope:ForbiddenCode", ...
        "A3 forbidden-code or parallel scan did not pass.");
    exported=export_stage_a3_artifacts(runContext,data,index,config, ...
        verification.linearization,verification.direct, ...
        verification.recursive,verification.audit, ...
        Environment=environmentArtifact,Tests=a3Tests.summary, ...
        A2Regression=a2Tests.summary,A1Regression=a1Tests.summary, ...
        CodeScan=codeScan,Physical=verification.physical);
    assert(all(exported.artifact_hashes.status=="PASS"), ...
        "stageA3:artifacts:HashFailure", ...
        "One or more numerical artifacts failed SHA256 creation.");
    acceptance=evaluate_stage_a3_acceptance_facts(projectRoot,verification);
    if any(acceptance.status~="PASS")
        raise_first_acceptance_failure(acceptance,verification);
    end
    write_new_table(runContext.issue_log_path,issues);
    assert(height(issues)==0,"stageA3:issues:UnresolvedBlocking", ...
        "Formal PASS requires no unexplained issue-log rows.");
    write_new_table(runContext.acceptance_results_path,acceptance);

    stagingRoot=string(tempname(tempdir)); mkdir(stagingRoot);
    stagedReports=generate_stage_a3_reports(runContext, ...
        'OutputDirectory',stagingRoot,'FinalStatusCandidate',"PASS");
    validate_report_set(stagedReports);
    reportPaths=install_staged_reports(runContext,stagedReports);
    cleanup_staging(stagingRoot); stagingRoot="";
    evidenceHashes=write_stage_a3_evidence_hashes(runContext);
    evidenceHashPath=fullfile(runContext.acceptance_dir,"evidence_hashes.csv");
    updates=manifest_updates(verification,a3Tests,a2Tests,a1Tests, ...
        exported,evidenceHashes,evidenceHashPath,reportPaths);
    manifest=finalize_run_manifest(runContext,"PASS",updates);
    result=struct("run_id",string(runContext.run_id), ...
        "run_path",string(runContext.root),"status","PASS", ...
        "acceptance",acceptance,"issues",issues,"a3_tests",a3Tests, ...
        "a2_regression",a2Tests,"a1_regression",a1Tests, ...
        "verification",verification,"exported",exported, ...
        "evidence_hashes",evidenceHashes,"reports",reportPaths, ...
        "manifest",manifest);
catch exception
    cleanup_staging(stagingRoot);
    preserve_stage_a3_failure(runContext,acceptance,issues,exception);
    rethrow(exception);
end
end

function assert_stage_a3_preflight(projectRoot)
current=string(fileread(fullfile(projectRoot,"CURRENT_STAGE.md")));
assert(contains(current,"`stage_id`: `stage_A3`")&& ...
    contains(current,"`status`: `READY`"), ...
    "stageA3:gate:CurrentStage","CURRENT_STAGE must be stage_A3 / READY.");
[status,branch]=git_command(projectRoot,"branch --show-current");
assert(status==0&&strip(string(branch))=="stage_A3", ...
    "stageA3:gate:Branch","Formal A3 execution requires branch stage_A3.");
[status,tracked]=git_command(projectRoot,"status --porcelain --untracked-files=no");
assert(status==0&&strlength(strip(string(tracked)))==0, ...
    "stageA3:gate:TrackedChanges", ...
    "Formal A3 execution requires no uncommitted tracked changes.");
[status,worktree]=git_command(projectRoot,"status --porcelain --untracked-files=normal");
assert(status==0,"stageA3:gate:GitStatus","Could not inspect Git status.");
lines=splitlines(string(worktree)); lines=strip(lines(strlength(strip(lines))>0));
allowed=[ ...
    "?? runs/20260719_150810_stage_0_6591d873/"; ...
    "?? runs/20260720_131455_stage_A1_705f17da/"; ...
    "?? runs/20260720_145803_stage_A2_83e04697.zip"; ...
    "?? runs/20260720_145803_stage_A2_83e04697/"; ...
    "?? runs/20260721_042551_stage_A3_e9e1d679/"];
unknown=lines(~ismember(lines,allowed));
assert(isempty(unknown),"stageA3:gate:UnknownUntracked", ...
    "Unknown untracked content exists: %s",strjoin(unknown,"; "));
priorA3Root=fullfile(projectRoot,"runs","20260721_042551_stage_A3_e9e1d679");
assert(isfolder(priorA3Root),"stageA3:gate:PriorA3RunMissing", ...
    "The preserved prior A3 run is missing.");
priorA3Manifest=jsondecode(fileread(fullfile(priorA3Root,"run_manifest.json")));
assert(string(priorA3Manifest.run_id)=="20260721_042551_stage_A3_e9e1d679"&& ...
    string(priorA3Manifest.stage_id)=="stage_A3"&& ...
    string(priorA3Manifest.status)=="PASS"&& ...
    string(priorA3Manifest.git_commit)== ...
        "e9e1d679a87a22e484a5abcb12ba1b66d7ca8b29", ...
    "stageA3:gate:PriorA3Identity", ...
    "The preserved prior A3 run identity or terminal state changed.");
verify_historical_evidence_inventory(priorA3Root,priorA3Manifest,"prior A3");
a2Root=fullfile(projectRoot,"runs","20260720_145803_stage_A2_83e04697");
assert(isfolder(a2Root),"stageA3:gate:A2RunMissing", ...
    "Required A2 baseline run is missing.");
a2Manifest=jsondecode(fileread(fullfile(a2Root,"run_manifest.json")));
assert(string(a2Manifest.status)=="PASS"&& ...
    string(a2Manifest.git_commit)=="83e04697412bfea436c7eff10fa193cba70d6052"&& ...
    double(a2Manifest.blocking_acceptance_pass)==6&& ...
    double(a2Manifest.a2_test_passed)==32&& ...
    double(a2Manifest.a1_regression_passed)==37, ...
    "stageA3:gate:A2HistoricalStatus", ...
    "A2 baseline manifest does not prove the required PASS state.");
assert(isfile(fullfile(projectRoot,"runs", ...
    "20260720_145803_stage_A2_83e04697.zip")), ...
    "stageA3:gate:A2ZipMissing","Protected A2 ZIP is missing.");
zipPath=fullfile(projectRoot,"runs","20260720_145803_stage_A2_83e04697.zip");
expectedZip="240F28034E9F8C802AF200F0846825DB18E7E7F9777CA993E4969B504387B69B";
assert(upper(string(compute_sha256_file(zipPath)))==expectedZip, ...
    "stageA3:gate:A2ZipChanged","Protected A2 ZIP SHA256 changed.");
verify_historical_evidence_inventory(a2Root,a2Manifest,"A2 baseline");
end

function verify_historical_evidence_inventory(runRoot,manifest,label)
inventoryPath=fullfile(runRoot,"acceptance","evidence_hashes.csv");
assert(isfile(inventoryPath),"stageA3:gate:HistoricalEvidenceMissing", ...
    "%s evidence hash inventory is missing.",label);
assert(isfield(manifest,"evidence_hashes_sha256")&& ...
    lower(string(compute_sha256_file(inventoryPath)))== ...
        lower(string(manifest.evidence_hashes_sha256)), ...
    "stageA3:gate:HistoricalEvidenceInventoryChanged", ...
    "%s evidence inventory SHA256 differs from its PASS manifest.",label);
inventory=readtable(inventoryPath,'TextType','string');
assert(height(inventory)>0&&all(string(inventory.status)=="PASS")&& ...
    numel(unique(string(inventory.relative_path)))==height(inventory), ...
    "stageA3:gate:HistoricalEvidenceInventoryInvalid", ...
    "%s evidence inventory is empty, duplicated, or not PASS.",label);
for rowNumber=1:height(inventory)
    pathValue=fullfile(runRoot,strrep(inventory.relative_path(rowNumber),'/',filesep));
    assert(isfile(pathValue)&&lower(string(compute_sha256_file(pathValue)))== ...
        lower(string(inventory.sha256(rowNumber))), ...
        "stageA3:gate:HistoricalEvidenceChanged", ...
        "%s evidence changed: %s",label,inventory.relative_path(rowNumber));
end
end

function [status,output]=git_command(root,arguments)
command="git -c safe.directory="+replace(string(root),'\','/')+" "+arguments;
[status,output]=system(char(command));
end
function value=input_hash_object(hashes)
value=struct();
for k=1:height(hashes)
    name=string(hashes.fileName(k));
    if name=="基础参数.xlsx"
        field="base_parameters";
    elseif name=="输入数据.xlsx"
        field="timeseries";
    else
        field=string(matlab.lang.makeValidName(name));
    end
    value.(field)=char(string(hashes.actualSHA256(k)));
end
end
function artifact=input_hash_table(hashes,runId)
n=height(hashes);
artifact=table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    repmat(string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX')),n,1), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status','checked_at'});
end

function raise_first_acceptance_failure(acceptance,verification)
row=find(acceptance.status~="PASS",1,'first');
assert(~isempty(row),"stageA3:acceptance:MissingFailure","Missing failed row.");
id=acceptance.test_id(row);
switch id
    case "SA3-MAT-001"
        layer="matrix_dimension_audit"; object=acceptance.actual_value(row);
    case "SA3-DAY-001"
        layer="daily_response_formation"; object=acceptance.actual_value(row);
    case "SA3-CORE-001"
        layer="global_core_16"; object=acceptance.actual_value(row);
    case "SA3-EQ-001"
        layer="direction_equivalence_comparison";
        object=location_text(verification.audit.maximum_direction_difference.location);
    case "SA3-EQ-002"
        layer="full_kkt_reinsertion";
        object=location_text(verification.audit.maximum_recursive_residual.location);
    case "SA3-SUM-001"
        layer="sorted_day_response_aggregation"; object=acceptance.actual_value(row);
    otherwise
        layer="acceptance_evaluation"; object=acceptance.actual_value(row);
end
error("stageA3:acceptance:BlockingFailure", ...
    "test_id '%s'; layer '%s'; object '%s'; actual '%s'", ...
    id,layer,replace(string(object),"'",""),acceptance.actual_value(row));
end
function value=location_text(location)
try
    value=string(jsonencode(location));
catch
    value=string(location);
end
end
function validate_report_set(paths)
names=fieldnames(paths);
assert(numel(names)==3,"stageA3:report:ReportCount", ...
    "Exactly three A3 reports are required.");
for k=1:numel(names)
    [valid,details]=validate_docx_package(paths.(names{k}));
    assert(valid,"stageA3:report:StructureValidation", ...
        "%s",strjoin(details.errors,"; "));
end
end
function installed=install_staged_reports(context,staged)
installed=struct(); names=fieldnames(staged);
for k=1:numel(names)
    source=string(staged.(names{k})); sourceHash=compute_sha256_file(source);
    [~,base,extension]=fileparts(source);
    target=string(fullfile(context.reports_dir,base+extension));
    assert(~isfile(target)&&~isfolder(target), ...
        "stageA3:report:TargetExists","Refusing to overwrite %s.",target);
    [moved,message]=movefile(source,target);
    assert(moved,"stageA3:report:InstallFailed","%s",message);
    assert(lower(string(compute_sha256_file(target)))==lower(string(sourceHash)), ...
        "stageA3:report:InstalledHash","Installed report hash changed.");
    installed.(names{k})=char(target);
end
end
function updates=manifest_updates(v,a3,a2,a1,exported,evidence,hashPath,reports)
dayChains=zeros(1,numel(v.recursive.daily_partitions));
for k=1:numel(dayChains), dayChains(k)=size(v.recursive.daily_partitions(k).M,1); end
updates=struct( ...
    "a3_test_total",a3.summary.test_total, ...
    "a3_test_passed",a3.summary.test_passed, ...
    "a3_test_failed",a3.summary.test_failed, ...
    "a3_test_incomplete",a3.summary.test_incomplete, ...
    "a2_regression_total",a2.summary.test_total, ...
    "a2_regression_passed",a2.summary.test_passed, ...
    "a2_regression_failed",a2.summary.test_failed, ...
    "a2_regression_incomplete",a2.summary.test_incomplete, ...
    "a1_regression_total",a1.summary.test_total, ...
    "a1_regression_passed",a1.summary.test_passed, ...
    "a1_regression_failed",a1.summary.test_failed, ...
    "a1_regression_incomplete",a1.summary.test_incomplete, ...
    "full_kkt_dimension",v.direct.kkt.dimension, ...
    "reduced_primal_dimension",size(v.recursive.reduced.W,1), ...
    "reduced_system_dimension",size(v.recursive.reduced.saddle,1), ...
    "daily_chain_dimensions",dayChains, ...
    "total_reduced_hourly_chain_dimension",sum(dayChains), ...
    "daily_response_count",numel(v.recursive.daily_responses), ...
    "daily_response_dimension",size(v.recursive.daily_responses(1).S,1), ...
    "global_core_dimension",size(v.recursive.core.matrix,1), ...
    "fixed_zero_count",v.physical.fixed_zero_audit.count, ...
    "fixed_zero_exact",v.physical.fixed_zero_audit.values_exact_zero&& ...
        v.physical.fixed_zero_audit.directions_exact_zero, ...
    "fixed_zero_maximum_absolute_value", ...
        v.physical.fixed_zero_audit.maximum_absolute_value, ...
    "fixed_zero_maximum_absolute_direction", ...
        v.physical.fixed_zero_audit.maximum_absolute_direction, ...
    "direction_relative_error",v.audit.direction_relative_error, ...
    "xi_direction_relative_error",v.audit.component_relative_errors.xi, ...
    "y_direction_relative_error",v.audit.component_relative_errors.y, ...
    "l_direction_relative_error",v.audit.component_relative_errors.l, ...
    "z_direction_relative_error",v.audit.component_relative_errors.z, ...
    "recursive_full_kkt_relative_residual", ...
        v.audit.recursive_kkt_relative_residual, ...
    "direct_full_kkt_relative_residual",v.audit.full_kkt_relative_residual, ...
    "aggregation_S_order_relative_error", ...
        v.recursive.aggregation.order_invariant_S_relative_error, ...
    "aggregation_gamma_order_relative_error", ...
        v.recursive.aggregation.order_invariant_gamma_relative_error, ...
    "linearization_identity",char(v.linearization.identity), ...
    "blocking_acceptance_total",6,"blocking_acceptance_pass",6, ...
    "numerical_artifact_hashes","matrices/numerical_artifact_hashes.csv", ...
    "numerical_artifact_count",height(exported.artifact_hashes), ...
    "evidence_hashes","acceptance/evidence_hashes.csv", ...
    "evidence_hashes_sha256",compute_sha256_file(hashPath), ...
    "evidence_file_count",height(evidence), ...
    "reports",relative_report_paths(reports),"first_failed_layer","none");
end
function value=relative_report_paths(paths)
value=struct(); names=fieldnames(paths);
for k=1:numel(names)
    [~,base,extension]=fileparts(paths.(names{k}));
    value.(names{k})=char("reports/"+string(base)+string(extension));
end
end
function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA3:artifacts:TargetExists","Refusing to overwrite %s.",pathValue);
write_table_csv_17g(pathValue,value);
end
function passed=all_required_test_evidence_exists(paths)
values=string(struct2cell(paths)); passed=numel(values)==6&&all(isfile(values));
end

function preserve_stage_a3_failure(context,acceptance,issues,exception)
hashPath=fullfile(context.acceptance_dir,"evidence_hashes.csv");
preserve_candidate_file(context.acceptance_results_path, ...
    fullfile(context.acceptance_dir,"acceptance_results.pre_failure_candidate.csv"));
preserve_candidate_file(context.issue_log_path, ...
    fullfile(context.issues_dir,"issue_log.pre_failure_candidate.csv"));
try
    if isempty(acceptance)
        acceptance=initialize_stage_a3_acceptance(string(context.project_root));
    end
    failureId=first_failure_test_id(exception);
    if nnz(acceptance.test_id==failureId)==1
        acceptance=set_stage_a3_acceptance_result(acceptance,failureId,"FAIL", ...
            exception.message,"first failing A3 acceptance fact","run_manifest.json");
    end
    for row=1:height(acceptance)
        if acceptance.status(row)=="NOT_RUN"
            acceptance=set_stage_a3_acceptance_result(acceptance, ...
                acceptance.test_id(row),"BLOCKED", ...
                "not completed after "+failureId, ...
                "dependency blocked by first failure","run_manifest.json");
        end
    end
    write_table_csv_17g(context.acceptance_results_path,acceptance);
catch
end
try
    issues=append_stage_a3_issue(issues,context,failureId, ...
        first_failure_layer(exception),first_failure_object(exception), ...
        "Stage A3 formal run failed",exception.message, ...
        "See exception and persisted evidence", ...
        "Fix the first failing layer and create a new unique run", ...
        "OPEN","run_manifest.json");
    write_table_csv_17g(context.issue_log_path,issues);
catch
end
try
    generate_stage_a3_failure_report(context,exception,issues,acceptance);
catch
end
latestHashPath=hashPath; latestHashRelative="acceptance/evidence_hashes.csv";
try
    if ~isfile(hashPath)
        write_stage_a3_evidence_hashes(context);
    else
        write_stage_a3_failure_evidence_addendum(context);
        latestHashPath=fullfile(context.acceptance_dir, ...
            "evidence_hashes_failure_addendum.csv");
        latestHashRelative="acceptance/evidence_hashes_failure_addendum.csv";
    end
catch
end
try
    manifest=jsondecode(fileread(context.run_manifest_path));
    if string(manifest.status)=="RUNNING"
        updates=struct("fatal_error_identifier",exception.identifier, ...
            "fatal_error_message",exception.message, ...
            "first_failed_layer",first_failure_layer(exception), ...
            "first_failed_object",first_failure_object(exception));
        if isfile(latestHashPath)
            updates.evidence_hashes=char(latestHashRelative);
            updates.evidence_hashes_sha256=compute_sha256_file(latestHashPath);
            if ~strcmp(char(latestHashPath),char(hashPath))
                updates.prior_evidence_hashes="acceptance/evidence_hashes.csv";
                updates.prior_evidence_hashes_sha256=compute_sha256_file(hashPath);
            end
        end
        report=fullfile(context.reports_dir,"阶段A3_失败与首层定位报告.docx");
        if isfile(report)
            updates.reports=struct("failure",relative_run_path(report,context.root));
        end
        finalize_run_manifest(context,"FAIL_RETRYABLE",updates);
    end
catch
end
end
function value=first_failure_test_id(exception)
message=string(exception.message);
token=regexp(message,"test_id '([^']+)'",'tokens','once');
if ~isempty(token)
    value=string(token{1});
elseif contains(exception.identifier,"tests")
    value="SA3-TESTS";
elseif contains(exception.identifier,"artifacts")
    value="SA3-ARTIFACTS";
elseif contains(exception.identifier,"report")
    value="SA3-REPORT";
elseif contains(exception.identifier,"numeric")
    value="SA3-EQ-002";
else
    value="SA3-RUN";
end
end
function value=first_failure_layer(exception)
message=string(exception.message);
token=regexp(message,"layer '([^']+)'",'tokens','once');
if ~isempty(token)
    value=string(token{1});
elseif contains(exception.identifier,"tests")
    value="automated_tests";
elseif contains(exception.identifier,"artifacts")
    value="artifact_persistence";
elseif contains(exception.identifier,"report")
    value="report_generation";
else
    value="formal_run_orchestration";
end
end
function value=first_failure_object(exception)
message=string(exception.message);
token=regexp(message,"object '([^']+)'",'tokens','once');
if ~isempty(token)
    value=string(token{1});
else
    value=exception.identifier;
end
end
function value=relative_run_path(pathValue,runRoot)
pathValue=string(char(java.io.File(char(pathValue)).getCanonicalPath()));
runRoot=string(char(java.io.File(char(runRoot)).getCanonicalPath()));
value=replace(extractAfter(pathValue,strlength(runRoot)+1),'\','/');
end
function cleanup_staging(pathValue)
if strlength(string(pathValue))>0&&isfolder(pathValue)
    try
        rmdir(pathValue,'s');
    catch
    end
end
end
function preserve_candidate_file(source,target)
try
    if isfile(source)&&~isfile(target)&&~isfolder(target)
        movefile(source,target);
    end
catch
end
end
