function result = main_stage_A4_3(options)
%MAIN_STAGE_A4_3 Execute the formal seven-day A4 convergence candidate.
%
% This entry creates (or explicitly resumes) one non-overwriting run and
% performs at most 100 accepted primal-dual updates.  It deliberately
% leaves the manifest RUNNING: tests, external DOCX rendering/visual QA,
% evidence hashing, and the single terminal manifest transition occur only
% after the numerical trajectory is complete.  CURRENT_STAGE.md is never
% modified by this entry.

arguments
    options.ResumeRunId (1,1) string = ""
end

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
addpath(fullfile(projectRoot,"tests"));
preflight = assert_stage_a4_3_preflight(projectRoot);
assert(preflight.passed && preflight.stage_id=="stage_A4" && ...
    preflight.stage_status=="READY", ...
    "stageA4:a43:PreflightIdentity", ...
    "The A4-3 preflight identity is inconsistent.");
config = load_stage_a4_3_configuration(projectRoot);
environment = inspect_stage_a4_environment();
[inputHashes,inputHashesPass] = verify_input_hashes(projectRoot);
environmentPass = all(string(environment.status( ...
    logical(environment.blocking)))=="PASS");
assert(environmentPass&&inputHashesPass, ...
    "stageA4:a43:BlockedExternal", ...
    "A4-3 requires MATLAB R2024a, sparse LDL/solve, and both controlled input hashes.");
data = rkkt.data.load(projectRoot);
[forbiddenCodeAudit,dependencyClosure] = ...
    scan_stage_a4_3_forbidden_code(projectRoot,config);
assert(all(forbiddenCodeAudit.status=="PASS"), ...
    "stageA4:a43:ForbiddenExecution", ...
    "A4-3 dependency/config forbidden-factor audit failed.");

postprocessRecovery = false;
persistedPostprocess = struct();
if strlength(strip(options.ResumeRunId))==0
    historicalBefore = snapshot_stage_a4_historical_runs(projectRoot);
    runContext = create_fresh_context(projectRoot,config,inputHashes);
    write_initial_identity_artifacts( ...
        runContext,environment,inputHashes,historicalBefore);
else
    runContext = existing_context(projectRoot,strip(options.ResumeRunId));
    historicalPath = fullfile(runContext.root,"historical_runs_before.csv");
    if isfile(historicalPath)
        historicalBefore = readtable(historicalPath,"TextType","string", ...
            "VariableNamingRule","preserve");
    else
        historicalBefore = snapshot_stage_a4_historical_runs( ...
            projectRoot,"ExcludeRunIds",string(runContext.run_id));
    end
    verify_resume_identity(runContext,preflight,inputHashes,config);
    recover_initial_identity_artifacts(runContext,environment, ...
        inputHashes,historicalBefore);
    resumeManifest = jsondecode(fileread(runContext.run_manifest_path));
    resumePhase = read_postprocess_phase(resumeManifest);
    if resumePhase=="COMPLETE"
        result = completed_postprocess_result(runContext,resumeManifest);
        fprintf("A4-3 run_id=%s postprocessing is already COMPLETE; "+ ...
            "no numerical replay or artifact rewrite was performed.\n", ...
            result.run_id);
        return
    end
    if resumePhase=="IN_PROGRESS"
        % A postprocess interruption must never cause the numerical solver
        % to run again.  Load the already-persisted numerical result first;
        % the recovery transaction below archives only disposable outputs.
        persistedPostprocess = load_persisted_postprocess_result(runContext);
        if ~persistedPostprocess.available
            result = interrupted_postprocess_recovery_result( ...
                runContext,persistedPostprocess.reason);
            update_running_run_manifest(runContext,struct( ...
                "a4_3_run_terminal_state","INTERRUPTED_RECOVERABLE", ...
                "postprocessing_executed",false, ...
                "finalization_pending",true, ...
                "postprocess_recovery_blocked",true, ...
                "postprocess_recovery_reason", ...
                    char(persistedPostprocess.reason), ...
                "resume_command","matlab -batch ""result=main_stage_A4_3("+ ...
                    "ResumeRunId='"+string(runContext.run_id)+"');"""));
            fprintf("A4-3 run_id=%s remains INTERRUPTED_RECOVERABLE: %s\n", ...
                result.run_id,result.recovery_reason);
            return
        end
        try
            prepare_stage_a4_postprocess_resume(runContext);
        catch cause
            reason = "postprocess recovery transaction failed: "+ ...
                string(cause.identifier)+": "+string(cause.message);
            result = interrupted_postprocess_recovery_result(runContext,reason);
            update_running_run_manifest(runContext,struct( ...
                "a4_3_run_terminal_state","INTERRUPTED_RECOVERABLE", ...
                "postprocessing_executed",false, ...
                "finalization_pending",true, ...
                "postprocess_recovery_blocked",true, ...
                "postprocess_recovery_reason",char(reason), ...
                "resume_command","matlab -batch ""result=main_stage_A4_3("+ ...
                    "ResumeRunId='"+string(runContext.run_id)+"');"""));
            fprintf("A4-3 run_id=%s remains INTERRUPTED_RECOVERABLE: %s\n", ...
                result.run_id,result.recovery_reason);
            return
        end
        postprocessRecovery = true;
    end
end

index = rkkt.indexing.build(data,"RunId",string(runContext.run_id));
if postprocessRecovery
    solverResult = rebuild_persisted_postprocess_result( ...
        persistedPostprocess,data,index,config);
else
    solverResult = rkkt.ipm.solve( ...
        data,index,config,runContext,"Resume", ...
        strlength(strip(options.ResumeRunId))>0);
end
if solverResult.run_terminal_state=="INTERRUPTED_RECOVERABLE"
    update_running_run_manifest(runContext,struct( ...
        "a4_3_run_terminal_state","INTERRUPTED_RECOVERABLE", ...
        "finalization_pending",true, ...
        "postprocessing_executed",false, ...
        "resume_command","matlab -batch ""result=main_stage_A4_3("+ ...
        "ResumeRunId='"+string(runContext.run_id)+"');"""));
    result = struct( ...
        "run_id",string(runContext.run_id), ...
        "run_path",string(runContext.root), ...
        "manifest_status","RUNNING", ...
        "run_terminal_state","INTERRUPTED_RECOVERABLE", ...
        "convergence_achieved",false, ...
        "iteration_count",solverResult.iteration_count, ...
        "final_metrics",solverResult.final_metrics, ...
        "execution_audit",solverResult.execution_audit, ...
        "reports_generated",false,"tests_executed",false, ...
        "stage_status","READY","stage_b_entered",false);
    fprintf("A4-3 run_id=%s is INTERRUPTED_RECOVERABLE at revision %d.\n", ...
        result.run_id,result.iteration_count);
    return
end
% Persist the numerical terminal result before any disposable postprocess
% export.  This is the recovery anchor if a later artifact/report write is
% interrupted.  On a postprocess resume the old copy was archived first, so
% the same immutable write creates the replacement anchor.
try
    save_solver_result(runContext,solverResult);
catch cause
    reason = "solver result persistence failed: "+ ...
        string(cause.identifier)+": "+string(cause.message);
    update_running_run_manifest(runContext,struct( ...
        "a4_3_run_terminal_state","INTERRUPTED_RECOVERABLE", ...
        "postprocessing_executed",false, ...
        "finalization_pending",true, ...
        "solver_result_persistence_blocked",true, ...
        "solver_result_persistence_reason",char(reason), ...
        "resume_command","matlab -batch ""result=main_stage_A4_3("+ ...
            "ResumeRunId='"+string(runContext.run_id)+"');"""));
    result = interrupted_postprocess_recovery_result(runContext,reason);
    fprintf("A4-3 run_id=%s remains INTERRUPTED_RECOVERABLE: %s\n", ...
        result.run_id,result.recovery_reason);
    return
end
manifestBeforePostprocess = jsondecode(fileread( ...
    runContext.run_manifest_path));
postprocessPhase = read_postprocess_phase(manifestBeforePostprocess);
assert(ismember(postprocessPhase,["NOT_STARTED","IN_PROGRESS"]), ...
    "stageA4:a43:PostprocessPhase", ...
    "A4-3 postprocessing cannot start from phase %s.",postprocessPhase);
update_running_run_manifest(runContext,struct( ...
    "postprocess_phase","IN_PROGRESS", ...
    "postprocessing_executed",false, ...
    "postprocess_started_at",char(string(datetime("now", ...
        "TimeZone","Asia/Shanghai", ...
        "Format","yyyy-MM-dd'T'HH:mm:ssXXX")))));
forbiddenExecutionAudit = audit_stage_a4_3_forbidden_execution( ...
    solverResult,config,forbiddenCodeAudit,dependencyClosure);
structural = export_stage_a4_3_structural_artifacts( ...
    runContext,data,index,config,solverResult,forbiddenCodeAudit, ...
    forbiddenExecutionAudit,dependencyClosure);
physicalAudit = evaluate_stage_a4_3_physical_audit( ...
    solverResult,index,data,config);
physicalResults = rkkt.artifacts.export( ...
    runContext,data,index,solverResult.final_state,physicalAudit, ...
    "SolvePass","pass_1", ...
    "PhysicalTolerance",config.a4_3.physical_violation_tolerance);
acceptance = evaluate_stage_a4_3_acceptance( ...
    projectRoot,solverResult,physicalAudit);
write_new_table(runContext.acceptance_results_path,acceptance);
[issues,decisions] = make_logs(runContext,solverResult,acceptance);
write_new_table(runContext.issue_log_path,issues);
write_new_table(runContext.decision_log_path,decisions);

historicalAudit = compare_stage_a4_historical_runs( ...
    projectRoot,historicalBefore,string(runContext.run_id));
write_json_file(fullfile(runContext.root,"historical_runs_audit.json"), ...
    historicalAudit);
update_running_run_manifest(runContext,manifest_observations( ...
    solverResult,structural,physicalResults,physicalAudit, ...
    forbiddenCodeAudit,forbiddenExecutionAudit,historicalAudit));

result = struct( ...
    "run_id",string(runContext.run_id), ...
    "run_path",string(runContext.root), ...
    "manifest_status","RUNNING", ...
    "run_terminal_state",solverResult.run_terminal_state, ...
    "convergence_achieved",solverResult.convergence_achieved, ...
    "iteration_count",solverResult.iteration_count, ...
    "final_metrics",solverResult.final_metrics, ...
    "execution_audit",solverResult.execution_audit, ...
    "acceptance",acceptance, ...
    "physical_audit",physicalAudit, ...
    "forbidden_code_audit",forbiddenCodeAudit, ...
    "forbidden_execution_audit",forbiddenExecutionAudit, ...
    "reports_generated",false, ...
    "tests_executed",false, ...
    "stage_status","READY", ...
    "stage_b_entered",false);

fprintf("A4-3 run_id=%s terminal=%s accepted_iterations=%d\n", ...
    result.run_id,result.run_terminal_state,result.iteration_count);
fprintf("Manifest remains RUNNING pending tests, DOCX render/visual QA, "+ ...
    "evidence hashes, and terminalization.\n");
end

function context = create_fresh_context(root,config,inputHashes)
metadata = struct( ...
    "run_purpose",char(config.a4_3.run_purpose), ...
    "authority_starting_head", ...
        "521ea489c2e0fba79fde22f32b5f647167eb637b", ...
    "actual_execution_command", ...
        "matlab -batch ""result=main_stage_A4_3();""", ...
    "convergence_coordinate","positive_scalar_unitized_kkt", ...
    "objective_scale_mode","positive_scalar_unitization", ...
    "objective_scale_source","max_abs_global_capacity_gradient", ...
    "recursive_route",char(config.a4_3.recursive_route), ...
    "recursive_refinement_max_passes",3, ...
    "sigma",config.a4_3.centering_sigma, ...
    "tau",config.a4_3.fraction_to_boundary, ...
    "step_strategy","independent", ...
    "maximum_iterations",config.a4_3.max_iterations, ...
    "day_ids",config.a4_3.days, ...
    "hours",config.a4_3.hours, ...
    "hour_count",numel(config.a4_3.days)*numel(config.a4_3.hours), ...
    "formal_soc_boundary","daily_half_energy_both_ends", ...
    "interday_soc_link",false, ...
    "pcharge_pdischarge_independent",true, ...
    "parallel_executed",false, ...
    "solver_invocation_started",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "physical_dispatch_interpretation",false, ...
    "capacity_planning_interpretation",false, ...
    "economic_interpretation_valid_only_if_converged",true, ...
    "newton_direction_count",0, ...
    "postprocess_phase","NOT_STARTED", ...
    "postprocessing_executed",false, ...
    "stage_b_entered",false, ...
    "annual_scope_executed",false, ...
    "thermal_second_pass_enabled",false, ...
    "water_constraints_enabled",false, ...
    "enabled_components",["OBJ_INVEST_UNITIZED","CAP_BOUNDS_GLOBAL", ...
        "DURATION_GLOBAL","DAILY_CAPACITY_COPY","CAPACITY_BINDING", ...
        "HOURLY_POWER_BALANCE","FORMAL_DAILY_SOC", ...
        "FIRST_PASS_THERMAL","STABLE_V2_RECURSIVE_DIRECTION", ...
        "COMPLETE_KKT_AUDIT_ONLY"], ...
    "disabled_components",["COMMON_STEP","DYNAMIC_SIGMA", ...
        "PREDICTOR_CORRECTOR","LINE_SEARCH","REGULARIZATION", ...
        "AUTOMATIC_SYMMETRIZATION","FULL_KKT_DIRECTION_FALLBACK", ...
        "PARALLEL","DAILY_WATER","THERMAL_SECOND_PASS", ...
        "UC","STAGE_B","ANNUAL_365_DAY"]);
context = create_run_context(root,"stage_A4", ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",config.source_paths.a4_3, ...
    "ManifestMetadata",metadata);
update_running_run_manifest(context,struct( ...
    "thermal_pass","pass_1_zero_to_pmax"));
end

function write_initial_identity_artifacts( ...
        context,environment,inputHashes,historical)
environment = addvars(environment, ...
    repmat(string(context.run_id),height(environment),1), ...
    'Before',1,'NewVariableNames','run_id');
write_table_csv_17g_atomic(context.environment_csv_path,environment);
write_table_csv_17g_atomic(context.input_hashes_csv_path, ...
    input_hash_table(inputHashes,context.run_id));
write_table_csv_17g_atomic( ...
    fullfile(context.root,"historical_runs_before.csv"),historical);
end

function recover_initial_identity_artifacts( ...
        context,environment,inputHashes,historical)
environmentPath = string(context.environment_csv_path);
inputPath = string(context.input_hashes_csv_path);
historyPath = fullfile(context.root,"historical_runs_before.csv");
if isfile(environmentPath)
    observed = readtable(environmentPath,"TextType","string", ...
        "VariableNamingRule","preserve");
    assert(height(observed)==height(environment) && ...
        all(string(observed.run_id)==string(context.run_id)) && ...
        all(ismember(string(observed.status), ...
        ["PASS","NOT_APPLICABLE"])) && ...
        all(string(observed.status(logical(observed.blocking)))=="PASS"), ...
        "stageA4:a43:ResumeEnvironment", ...
        "Persisted environment evidence is inconsistent.");
else
    environment = addvars(environment, ...
        repmat(string(context.run_id),height(environment),1), ...
        'Before',1,'NewVariableNames','run_id');
    write_table_csv_17g_atomic(environmentPath,environment);
end
expectedHashes = input_hash_table(inputHashes,context.run_id);
if isfile(inputPath)
    observed = readtable(inputPath,"TextType","string", ...
        "VariableNamingRule","preserve");
    assert(height(observed)==2 && ...
        all(lower(string(observed.actualSHA256))== ...
        lower(string(expectedHashes.actualSHA256))) && ...
        all(string(observed.status)=="PASS"), ...
        "stageA4:a43:ResumeInputHashes", ...
        "Persisted controlled input hashes are inconsistent.");
else
    write_table_csv_17g_atomic(inputPath,expectedHashes);
end
if ~isfile(historyPath)
    write_table_csv_17g_atomic(historyPath,historical);
    update_running_run_manifest(context,struct( ...
        "historical_before_reconstructed_on_resume",true));
end
end

function context = existing_context(root,runId)
runRoot = fullfile(root,"runs",runId);
assert(isfolder(runRoot),"stageA4:a43:ResumeRunMissing", ...
    "The requested A4-3 run does not exist: %s",runRoot);
context = struct( ...
    "project_root",char(root),"runs_root",char(fullfile(root,"runs")), ...
    "root",char(runRoot),"run_dir",char(runRoot), ...
    "run_id",char(runId),"stage_id","stage_A4", ...
    "iterations_dir",char(fullfile(runRoot,"iterations")), ...
    "indices_dir",char(fullfile(runRoot,"indices")), ...
    "matrices_dir",char(fullfile(runRoot,"matrices")), ...
    "checkpoints_dir",char(fullfile(runRoot,"checkpoints")), ...
    "tests_dir",char(fullfile(runRoot,"tests")), ...
    "issues_dir",char(fullfile(runRoot,"issues")), ...
    "acceptance_dir",char(fullfile(runRoot,"acceptance")), ...
    "reports_dir",char(fullfile(runRoot,"reports")), ...
    "run_manifest_path",char(fullfile(runRoot,"run_manifest.json")), ...
    "environment_csv_path",char(fullfile(runRoot,"environment.csv")), ...
    "input_hashes_csv_path",char(fullfile(runRoot,"input_hashes.csv")), ...
    "effective_config_path",char(fullfile(runRoot,"effective_config.yaml")), ...
    "git_state_path",char(fullfile(runRoot,"git_state.txt")), ...
    "matrix_manifest_path",char(fullfile(runRoot,"matrices", ...
        "matrix_manifest.csv")), ...
    "checkpoint_manifest_path",char(fullfile(runRoot,"checkpoints", ...
        "checkpoint_manifest.csv")), ...
    "issue_log_path",char(fullfile(runRoot,"issues","issue_log.csv")), ...
    "decision_log_path",char(fullfile(runRoot,"issues","decision_log.csv")), ...
    "acceptance_results_path",char(fullfile(runRoot,"acceptance", ...
        "acceptance_results.csv")));
end

function verify_resume_identity(context,preflight,inputHashes,config)
manifest = jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.status)=="RUNNING" && ...
    string(manifest.stage_id)=="stage_A4" && ...
    string(manifest.run_purpose)==config.a4_3.run_purpose && ...
    lower(string(manifest.git_commit))==lower(preflight.git_commit) && ...
    lower(string(manifest.input_hashes.base_parameters))== ...
        lower(string(inputHashes.actualSHA256(1))) && ...
    lower(string(manifest.input_hashes.timeseries))== ...
        lower(string(inputHashes.actualSHA256(2))) && ...
    lower(string(compute_sha256_file(context.effective_config_path)))== ...
        lower(string(compute_sha256_file(config.source_paths.a4_3))), ...
    "stageA4:a43:ResumeIdentity", ...
    "Resume requires identical code, input hashes, and effective config.");
end

function [issues,decisions] = make_logs(context,result,acceptance)
if result.run_terminal_state=="CONVERGED" && ...
        all(acceptance.status(1:6)=="PASS")
    issues = empty_issue_log();
else
    failureId = "A43-"+result.run_terminal_state;
    failedRows = acceptance(acceptance.status=="FAIL",:);
    if isempty(failedRows)
        failedIds = "none";
    else
        failedIds = strjoin(failedRows.test_id,",");
    end
    issues = table(string(context.run_id),failureId,failedIds, ...
        result.run_terminal_state, ...
        "Formal A4-3 candidate did not satisfy every numerical gate.", ...
        "Persisted trajectory, checkpoint, direction and physical evidence retained.", ...
        "No algorithm factor was changed; user decision is required.", ...
        "OPEN","iterations/iteration_summary.csv; acceptance/acceptance_results.csv", ...
        'VariableNames',{'run_id','issue_id','test_id','layer', ...
        'symptom','evidence_preserved','next_action','status', ...
        'evidence_path'});
end
decisions = table(string(context.run_id),"A4-3", ...
    result.run_terminal_state, ...
    "CURRENT_STAGE remains stage_A4 / READY; no Stage B transition.", ...
    result.iteration_count, ...
    "positive_scalar_unitized_kkt", ...
    "independent alpha_primal/alpha_dual; stable-v2 MaxPasses=3", ...
    "issues/issue_log.csv; iterations/iteration_summary.csv", ...
    'VariableNames',{'run_id','milestone','numerical_terminal_state', ...
    'stage_decision','accepted_iteration_count', ...
    'convergence_coordinate','algorithm_contract','evidence_path'});
end

function value = empty_issue_log()
value = table(strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer', ...
    'symptom','evidence_preserved','next_action','status', ...
    'evidence_path'});
end

function updates = manifest_observations( ...
        result,structural,physicalResults,physicalAudit, ...
        forbiddenCode,forbiddenExecution,historical)
% Numerical/structural postprocessing has completed, but reports, external
% tests, static evidence and final hashing are still pending.  Keep the
% phase recoverable until the finalizer performs the single terminal
% transition.
direction = result.direction_audit;
if isempty(direction)
    worstDirection = Inf;
    worstRecursiveResidual = Inf;
    worstDirectResidual = Inf;
else
    worstDirection = max([direction.direction_relative_error; ...
        direction.xi_relative_error;direction.y_relative_error; ...
        direction.l_relative_error;direction.z_relative_error],[],"all");
    worstRecursiveResidual = max( ...
        direction.recursive_full_kkt_relative_residual);
    worstDirectResidual = max(direction.full_kkt_relative_residual);
end
updates = struct( ...
    "a4_3_run_terminal_state",char(result.run_terminal_state), ...
    "convergence_achieved",result.convergence_achieved, ...
    "newton_direction_count",result.iteration_count, ...
    "accepted_state_update_count",result.iteration_count, ...
    "last_attempted_iteration",result.last_attempted_iteration, ...
    "attempted_iteration_count_current_invocation", ...
        result.attempted_iteration_count_current_invocation, ...
    "full_kkt_audit_count",result.full_kkt_audit_count, ...
    "accepted_iteration_full_kkt_audit_count", ...
        result.accepted_iteration_full_kkt_audit_count, ...
    "resume_replay_full_kkt_audit_count", ...
        result.resume_replay_full_kkt_audit_count, ...
    "completed_iteration_evaluation_count_current_invocation", ...
        result.completed_iteration_evaluation_count_current_invocation, ...
    "objective_scale_factor",result.objective_scale_factor, ...
    "final_scaled_metrics",result.final_metrics, ...
    "worst_direction_metric",worstDirection, ...
    "worst_recursive_full_kkt_residual",worstRecursiveResidual, ...
    "worst_complete_kkt_audit_residual",worstDirectResidual, ...
    "strict_positivity_all_accepted", ...
        result.execution_audit.strict_positivity_pass, ...
    "no_full_direction_fallback", ...
        result.execution_audit.no_full_direction_fallback, ...
    "forbidden_execution_pass", ...
        all(forbiddenCode.status=="PASS") && ...
        all(forbiddenExecution.status=="PASS") && ...
        result.execution_audit.forbidden_execution_pass, ...
    "structural_kkt_dimension",structural.kkt_dimension, ...
    "structural_kkt_nnz",structural.kkt_nnz, ...
    "structural_export_direction_solve_count", ...
        structural.additional_direction_solve_count, ...
    "capacity_result_count",height(physicalResults.capacity_results), ...
    "hourly_result_count",height(physicalResults.hourly_dispatch_results), ...
    "physical_audit_pass",all(physicalAudit.status=="PASS"), ...
    "physical_dispatch_interpretation",result.convergence_achieved, ...
    "capacity_planning_interpretation",result.convergence_achieved, ...
    "historical_runs_unchanged",historical.passed, ...
    "reports_generated",false, ...
    "tests_executed",false, ...
    "postprocess_phase","IN_PROGRESS", ...
    "postprocessing_executed",false, ...
    "postprocess_completed_at","", ...
    "finalization_pending",true);
end

function phase = read_postprocess_phase(manifest)
if isfield(manifest,"postprocess_phase")
    phase = string(manifest.postprocess_phase);
else
    phase = "NOT_STARTED";
end
assert(ismember(phase,["NOT_STARTED","IN_PROGRESS","COMPLETE"]), ...
    "stageA4:a43:PostprocessPhase", ...
    "Invalid persisted A4-3 postprocess phase: %s.",phase);
end

function result = completed_postprocess_result(context,manifest)
solverPath = fullfile(context.root,"a4_3_solver_result.mat");
assert(isfile(solverPath),"stageA4:a43:CompletedPostprocessEvidence", ...
    "A COMPLETE postprocess phase requires a4_3_solver_result.mat.");
loaded = load(solverPath,"summary");
assert(isfield(loaded,"summary") && isstruct(loaded.summary), ...
    "stageA4:a43:CompletedPostprocessEvidence", ...
    "The persisted A4-3 solver summary is missing.");
summary = loaded.summary;
acceptance = readtable(context.acceptance_results_path, ...
    "TextType","string","VariableNamingRule","preserve");
result = struct( ...
    "run_id",string(context.run_id), ...
    "run_path",string(context.root), ...
    "manifest_status",string(manifest.status), ...
    "run_terminal_state",string(summary.run_terminal_state), ...
    "convergence_achieved",logical(summary.convergence_achieved), ...
    "iteration_count",double(summary.iteration_count), ...
    "final_metrics",summary.final_metrics, ...
    "execution_audit",summary.execution_audit, ...
    "acceptance",acceptance, ...
    "reports_generated",isfield(manifest,"reports_generated") && ...
        logical(manifest.reports_generated), ...
    "tests_executed",isfield(manifest,"tests_executed") && ...
        logical(manifest.tests_executed), ...
    "postprocess_phase","COMPLETE", ...
    "stage_status","READY", ...
    "stage_b_entered",false);
end

function persisted = load_persisted_postprocess_result(context)
%LOAD_PERSISTED_POSTPROCESS_RESULT Read the immutable numerical result used
% to resume an interrupted postprocess phase.  No solver call is made here.
persisted = struct("available",false,"reason","", ...
    "summary",struct(),"final_state",struct());
pathValue = fullfile(context.root,"a4_3_solver_result.mat");
if ~isfile(pathValue)
    persisted.reason = "a4_3_solver_result.mat is missing";
    return
end
try
    payload = load(pathValue,"summary","final_state");
    required = ["summary","final_state"];
    if ~all(isfield(payload,cellstr(required))) || ...
            ~isstruct(payload.summary) || ~isscalar(payload.summary) || ...
            ~isstruct(payload.final_state) || ~isscalar(payload.final_state)
        persisted.reason = "persisted solver result is incomplete";
        return
    end
    terminal = string(payload.summary.run_terminal_state);
    if ~ismember(terminal,["CONVERGED","MAX_ITERATIONS", ...
            "NUMERICAL_FAILURE"])
        persisted.reason = "persisted numerical terminal state is not complete";
        return
    end
    if ~isfield(payload.final_state,"xi") || ...
            ~isnumeric(payload.final_state.xi) || ...
            ~iscolumn(payload.final_state.xi) || ...
            any(~isfinite(payload.final_state.xi))
        persisted.reason = "persisted final state is missing finite xi";
        return
    end
    persisted.summary = payload.summary;
    persisted.final_state = payload.final_state;
    persisted.available = true;
catch cause
    persisted.reason = "could not load persisted solver result: "+ ...
        string(cause.identifier)+": "+string(cause.message);
end
end

function result = rebuild_persisted_postprocess_result( ...
        persisted,data,index,config)
%REBUILD_PERSISTED_POSTPROCESS_RESULT Recreate only deterministic derived
%objects from the accepted state; never solve or advance a direction.
result = persisted.summary;
result.final_state = persisted.final_state;
result.final_linearization = ...
    build_stage_a4_scaled_objective_linearization( ...
        result.final_state,data,index,config,"A4-3-FORMAL-CANDIDATE");
assert(isfield(result.final_state,"state_revision") && ...
        isfield(result.final_linearization,"diagnostic_objective_chain_id") && ...
        string(result.final_linearization.diagnostic_objective_chain_id)== ...
        "A4-3-FORMAL-CANDIDATE" && ...
        double(result.final_linearization.state.state_revision)== ...
        double(result.final_state.state_revision), ...
    "stageA4:a43:PostprocessRebuildIdentity", ...
    "Rebuilt postprocess linearization does not match the persisted state.");
end

function result = interrupted_postprocess_recovery_result(context,reason)
result = struct( ...
    "run_id",string(context.run_id), ...
    "run_path",string(context.root), ...
    "manifest_status","RUNNING", ...
    "run_terminal_state","INTERRUPTED_RECOVERABLE", ...
    "convergence_achieved",false, ...
    "iteration_count",0, ...
    "final_metrics",struct(), ...
    "execution_audit",struct(), ...
    "reports_generated",false, ...
    "tests_executed",false, ...
    "stage_status","READY", ...
    "stage_b_entered",false, ...
    "recovery_reason",string(reason));
end

function save_solver_result(context,result)
pathValue = fullfile(context.root,"a4_3_solver_result.mat");
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA4:a43:SolverResultExists", ...
    "Refusing to overwrite the A4-3 solver result.");
% R2024a accepts a cell array of character vectors for rmfield.  Using a
% string array here is rejected when a numerical-failure result is persisted,
% which would otherwise hide the real terminal state behind an
% INTERRUPTED_RECOVERABLE persistence error.
summary = rmfield(result,{'final_linearization','final_state'});
save_mat_artifact(pathValue, ...
    "summary",summary,"final_state",result.final_state);
end

function value = input_hash_object(hashes)
value = struct( ...
    "base_parameters",char(string(hashes.actualSHA256(1))), ...
    "timeseries",char(string(hashes.actualSHA256(2))));
end

function artifact = input_hash_table(hashes,runId)
n = height(hashes);
artifact = table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    repmat(string(datetime("now","TimeZone","Asia/Shanghai", ...
    "Format","yyyy-MM-dd'T'HH:mm:ssXXX")),n,1), ...
    'VariableNames',{'run_id','file_name','relative_path', ...
    'expected_bytes','actual_bytes','expectedSHA256','actualSHA256', ...
    'status','checked_at'});
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA4:a43:ArtifactExists", ...
    "Refusing to overwrite A4-3 artifact %s.",pathValue);
write_table_csv_17g(pathValue,value);
end
