function result = main_stage_A4_2D_2A()
%MAIN_STAGE_A4_2D_2A Run the isolated 5/20 objective-scale diagnostic.
%
% No formal A4 run, complete IPM, optimization, stage transition, or model
% interpretation is performed.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
config = load_stage_a4_configuration(projectRoot);
data = load_project_data(projectRoot);
index = build_stage_a4_index( ...
    data,"RunId","A4_2D_2A_OBJECTIVE_UNITIZATION_DIAGNOSTIC");
result = run_stage_a4_objective_unitization_diagnostic( ...
    data,index,config,projectRoot);

assert(ismember(result.milestone_status,["PASS","FAIL_RETRYABLE"]) && ...
    result.stage_status=="READY" && ...
    result.scaled_five.iteration_count==5 && ...
    result.scaled_twenty.requested_iteration_count==20 && ...
    result.execution.total_diagnostic_newton_direction_count== ...
        10+result.scaled_twenty.iteration_count && ...
    ~result.execution.hundred_round_run_executed && ...
    ~result.execution.full_ipm_executed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.stage_b_entered && ...
    ~result.stage_a4_pass_claimed && ...
    ~result.formal_acceptance_metric_changed && ...
    ~result.formal_algorithm_replaced, ...
    "stageA4:a42d2a:MainContract", ...
    "A4-2D-2A violated its isolated 5/20-round diagnostic contract.");
print_summary(result);
end

function print_summary(result)
fprintf("A4-2D-2A objective positive-scalar unitization; "+ ...
    "stage=%s; experiment_status=%s\n", ...
    result.stage_status,result.milestone_status);
fprintf("S=%.17g, source=%s\n",result.objective_scale.factor, ...
    result.objective_scale.scale_source);
fprintf("chain,iteration,objective_original,objective_scaled,r_eq_inf,"+ ...
    "r_ineq_inf,physical_violation,r_dual_scaled_inf,mean_gap_scaled,"+ ...
    "raw_gap_scaled,mu_scaled,eta_dual_scaled,eta_gap_scaled,"+ ...
    "mapped_r_dual_inf,mapped_mean_gap,mapped_raw_gap,"+ ...
    "alpha_primal,alpha_dual,primal_limiter,dual_limiter,min_l,min_z,"+ ...
    "delta_qp5,Bp,Bd,direction_error,recursive_kkt_residual,"+ ...
    "full_kkt_residual,no_fallback\n");
print_chain(result.scaled_five);
print_chain(result.scaled_twenty);
if result.scaled_twenty.failure.present
    fprintf("scaled20_failure iteration=%d identifier=%s message=%s\n", ...
        result.scaled_twenty.failure.attempted_iteration, ...
        result.scaled_twenty.failure.identifier, ...
        result.scaled_twenty.failure.message);
end
fprintf("20-round frozen-threshold audit:\n");
for k = 1:numel(result.convergence_diagnostics.metric_names)
    name = result.convergence_diagnostics.metric_names(k);
    fprintf("%s actual=%.17g threshold=%.17g ratio=%.17g passed=%d\n", ...
        name,result.convergence_diagnostics.actual.(name), ...
        result.convergence_diagnostics.thresholds.(name), ...
        result.convergence_diagnostics.threshold_ratios(k), ...
        result.convergence_diagnostics.metric_passed(k));
end
fprintf("next_single_factor=%s; reason=%s\n", ...
    result.conclusion.next_single_factor,result.conclusion.reason);
fprintf("D1R fixture replay issue=%s (%s)\n", ...
    result.evidence_tail_issue.issue_id,result.evidence_tail_issue.status);
end

function print_chain(chain)
for k = 1:chain.iteration_count
    item = chain.iterations(k);
    metric = item.metrics_after;
    fprintf("%s,%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,"+ ...
        "%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,"+ ...
        "%.17g,%.17g,%s,%s,%.17g,%.17g,%.17g,%.17g,%.17g,"+ ...
        "%.17g,%.17g,%.17g,%d\n", ...
        chain.chain_id,k,metric.objective_original, ...
        metric.objective_scaled,metric.equality_inf, ...
        metric.slack_equality_inf,metric.physical_inequality_violation, ...
        metric.dual_scaled_inf,metric.mean_gap_scaled, ...
        metric.raw_gap_scaled,metric.mu_scaled,metric.eta_dual_scaled, ...
        metric.eta_gap_scaled,metric.mapped_r_dual_inf, ...
        metric.mapped_mean_gap,metric.mapped_raw_gap, ...
        item.applied_alpha_primal,item.applied_alpha_dual, ...
        item.primal_limiter,item.dual_limiter,metric.minimum_l, ...
        metric.minimum_z,item.delta_qp5, ...
        item.cumulative_primal_step_budget, ...
        item.cumulative_dual_step_budget, ...
        item.direction_relative_error, ...
        item.recursive_kkt_relative_residual, ...
        item.full_kkt_relative_residual, ...
        item.no_full_direction_fallback);
end
end
