function result = main_stage_A4_2D_2A_R1()
%MAIN_STAGE_A4_2D_2A_R1 Run the isolated stable-v2 5/20 experiment.
%
% This entry executes exactly 5+5+20 Newton directions and state updates.
% It does not create a formal run, execute 100 rounds, replace the formal
% A4 algorithm, claim convergence, or enter Stage B.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
config = load_stage_a4_configuration(projectRoot);
data = load_project_data(projectRoot);
index = build_stage_a4_index( ...
    data,"RunId","A4_2D_2A_R1_STABLE_V2_DIAGNOSTIC");
result = run_stage_a4_objective_unitization_r1_diagnostic( ...
    data,index,config,projectRoot);

assert(result.milestone_status=="PASS" && result.all_blocking_pass && ...
    result.stage_status=="READY" && ...
    result.execution.total_newton_direction_count==30 && ...
    result.execution.state_update_count==30 && ...
    result.unscaled_five.iteration_count==5 && ...
    result.scaled_five.iteration_count==5 && ...
    result.scaled_twenty.iteration_count==20 && ...
    result.recursive_refinement_max_passes==3 && ...
    ~result.execution.complete_kkt_direction_fallback_used && ...
    ~result.execution.hundred_round_run_executed && ...
    ~result.execution.full_ipm_executed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.stage_b_entered && ...
    ~result.stage_a4_pass_claimed, ...
    "stageA4:r1:MainContract", ...
    "A4-2D-2A-R1 violated its isolated stable-v2 execution contract.");

final = result.scaled_twenty.final_metrics;
round19 = result.scaled_twenty.iterations(19);
round20 = result.scaled_twenty.iterations(20);
fprintf("A4-2D-2A-R1 status=%s, stage=%s, stable-v2 MaxPasses=%d\n", ...
    result.milestone_status,result.stage_status, ...
    result.recursive_refinement_max_passes);
fprintf("Newton/state updates=%d/%d; scaled20=%d/20\n", ...
    result.execution.total_newton_direction_count, ...
    result.execution.state_update_count, ...
    result.scaled_twenty.iteration_count);
fprintf("round20 gap_scaled=%.17g, gap_original_mapped=%.17g, "+ ...
    "r_eq=%.17g, r_ineq=%.17g, r_dual_scaled=%.17g, r_comp=%.17g\n", ...
    final.mean_gap_scaled,final.mapped_mean_gap,final.equality_inf, ...
    final.slack_equality_inf,final.dual_scaled_inf, ...
    final.complementarity_inf);
fprintf("round19 alpha_primal=%.17g alpha_dual=%.17g\n", ...
    round19.applied_alpha_primal,round19.applied_alpha_dual);
fprintf("round20 alpha_primal=%.17g alpha_dual=%.17g\n", ...
    round20.applied_alpha_primal,round20.applied_alpha_dual);
fprintf("convergence_achieved=%d; formal A4 pass claimed=0\n", ...
    result.convergence_achieved);
end
