function result = main_stage_A4_2B()
%MAIN_STAGE_A4_2B Execute the non-formal five-round gap-cause audit.
%
% This entry reproduces the A4-2A official state chain and observes each
% Newton direction. It creates no formal run and changes no solver state,
% parameter, model, or stage-governance file.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
config = load_stage_a4_configuration(projectRoot);
data = load_project_data(projectRoot);
index = build_stage_a4_index(data,"RunId","A4_2B_GAP_CAUSE_AUDIT");
result = run_stage_a4_complementarity_gap_diagnostic(data,index,config);
assert(result.all_pass && result.milestone_status=="PASS" && ...
    result.stage_status=="READY" && result.iteration_count==5 && ...
    result.execution.complementarity_audit_count==5 && ...
    result.execution.counterfactual_evaluation_count==5 && ...
    result.execution.counterfactual_state_update_count==0 && ...
    ~result.execution.counterfactual_consumed_by_official_state && ...
    ~result.execution.a4_2b_additional_dense_condition_number_executed && ...
    ~result.execution.full_ipm_executed && ...
    ~result.execution.optimization_executed && ...
    ~result.execution.parallel_executed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.stage_b_entered, ...
    "stageA4:complementarityAudit:MainContract", ...
    "A4-2B did not satisfy its fixed five-round read-only contract.");
print_audit(result);
end

function print_audit(result)
fprintf('A4-2B five-round complementarity-gap cause audit; stage=%s\n', ...
    result.stage_status);
fprintf(['iteration,gap_before,primal_term,dual_term,cross_term,' ...
    'predicted_gap_after,gap_after,closure_relative_error,' ...
    'largest_positive_term\n']);
for k = 1:result.iteration_count
    d = result.complementarity_audits(k).decomposition;
    fprintf('%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%s\n', ...
        k,d.gap_before,d.alpha_primal_mean_delta_l_times_z, ...
        d.alpha_dual_mean_l_times_delta_z, ...
        d.alpha_primal_alpha_dual_mean_delta_l_times_delta_z, ...
        d.predicted_gap_after,d.gap_after,d.closure_relative_error, ...
        char(d.largest_positive_term));
end

fprintf(['iteration,rank,inequality_index,constraint_global_row,' ...
    'constraint_id,constraint_name,day,hour,asset_type,asset_id,' ...
    'l,z,delta_l,delta_z,alpha_primal,alpha_dual,delta_i\n']);
for k = 1:result.iteration_count
    top = result.complementarity_audits(k).top20;
    decomposition = result.complementarity_audits(k).decomposition;
    fprintf('ROUND %d POSITIVE_CONSTRAINT_COUNT=%d TOP_RECORDED=%d\n', ...
        k,decomposition.positive_constraint_count,height(top));
    for row = 1:height(top)
        fprintf(['%d,%d,%d,%d,%s,%s,%d,%d,%s,%d,' ...
            '%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g\n'], ...
            top.iteration(row),top.rank(row),top.inequality_index(row), ...
            top.constraint_global_row(row),char(top.constraint_id(row)), ...
            char(top.constraint_name(row)),top.day(row),top.hour(row), ...
            char(top.asset_type(row)),top.asset_id(row), ...
            top.l_before(row),top.z_before(row),top.delta_l(row), ...
            top.delta_z(row),top.alpha_primal(row), ...
            top.alpha_dual(row),top.delta_i(row));
    end
end

fprintf(['iteration,alpha_common,common_gap_after,official_gap_after,' ...
    'gap_difference,minimum_l,minimum_z,positive,closure_relative_error\n']);
for k = 1:result.iteration_count
    c = result.complementarity_audits(k).counterfactual;
    officialGap = result.complementarity_audits(k).decomposition.gap_after;
    fprintf('%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%d,%.17g\n', ...
        k,c.alpha_common,c.gap_after,officialGap, ...
        c.gap_difference_from_official,c.minimum_l,c.minimum_z, ...
        c.strictly_positive,c.closure_relative_error);
end

format longG
for k = 1:result.iteration_count
    audit = result.complementarity_audits(k);
    fprintf('ROUND %d CONSTRAINT_FAMILY_SUMMARY\n',k);
    disp(audit.constraint_family_summary);
    fprintf('ROUND %d ASSET_TYPE_SUMMARY\n',k);
    disp(audit.asset_type_summary);
    fprintf('ROUND %d CENTRALITY_STATISTICS\n',k);
    disp(audit.centrality_statistics);
    fprintf('ROUND %d VECTOR_SCALE_STATISTICS\n',k);
    disp(audit.vector_scale_statistics);
    fprintf('ROUND %d RESIDUAL_SCALE_STATISTICS\n',k);
    disp(audit.residual_scale_statistics);
    fprintf('ROUND %d INEQUALITY_FAMILY_SCALE_STATISTICS\n',k);
    disp(audit.inequality_family_scale_statistics);
    fprintf('ROUND %d GROUP_SCALE_STATISTICS\n',k);
    disp(audit.group_scale_statistics);
end
fprintf(['EXECUTION full_ipm=%d optimization=%d parallel=%d formal_run=%d ' ...
    'counterfactual_state_updates=%d stage_b=%d\n'], ...
    result.execution.full_ipm_executed, ...
    result.execution.optimization_executed, ...
    result.execution.parallel_executed, ...
    result.execution.formal_a4_run_created, ...
    result.execution.counterfactual_state_update_count, ...
    result.execution.stage_b_entered);
end
