function result = main_stage_A2()
%MAIN_STAGE_A2 Execute the formal day-14, 24-hour single-direction audit.
% No optimization/IPM loop, parallel work, dispatch, or economic result is
% produced by this entry point.

projectRoot=string(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(projectRoot,"src")));
addpath(fullfile(projectRoot,"tests"));
assert_stage_a2_preflight(projectRoot);
config=load_stage_a2_configuration(projectRoot);
environment=inspect_stage_a2_environment();
[inputHashes,inputHashesPass]=verify_input_hashes(projectRoot);
environmentPass=all(string(environment.status(logical(environment.blocking)))=="PASS");
solverWillExecute=environmentPass && inputHashesPass;
formalCommand=['matlab -batch "result=main_stage_A2(); ' ...
    'assert(strcmp(char(result.status),''PASS''))"'];
metadata=struct( ...
    "run_purpose","stage_A2_formal_day_single_newton_direction_equivalence", ...
    "time_scope_type",char(config.time_scope_type), ...
    "input_day",config.days,"start_hour",config.start_hour, ...
    "terminal_hour",config.terminal_hour, ...
    "soc_boundary_mode",char(config.soc_boundary_mode), ...
    "formal_model_soc_boundary", ...
        "full_24_hour_day_fixed_half_energy_no_interday_link", ...
    "expected_full_kkt_dimension",config.expected_full_kkt_dimension, ...
    "expected_hourly_kkt_block_dimensions", ...
        config.expected_hourly_kkt_block_dimensions, ...
    "expected_hourly_chain_dimension",config.expected_hourly_chain_dimension, ...
    "expected_fixed_zero_count",config.expected_fixed_zero_count, ...
    "expected_day_response_dimension",config.expected_day_response_dimension, ...
    "expected_global_core_dimension",config.expected_global_core_dimension, ...
    "actual_execution_command",formalCommand, ...
    "actual_test_command","NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK", ...
    "newton_direction_count",1,"optimization_executed",false, ...
    "full_ipm_executed",false,"parallel_executed",false, ...
    "a2_solver_executed",false,"physical_dispatch_interpretation",false);
runContext=create_run_context(projectRoot,"stage_A2", ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",config.source_paths.stage, ...
    "ManifestMetadata",metadata);
a2Command="run_stage_A2_tests('EvidenceDirectory','"+ ...
    replace(string(runContext.tests_dir),"'","''")+"')";
a1Directory=fullfile(runContext.tests_dir,"a1_regression");
a1Command="run_stage_A1_tests('EvidenceDirectory','"+ ...
    replace(string(a1Directory),"'","''")+"')";

acceptance=table(); issues=new_stage_a2_issue_log(); stagingRoot="";
try
    environmentArtifact=addvars(environment, ...
        repmat(string(runContext.run_id),height(environment),1), ...
        'Before',1,'NewVariableNames','run_id');
    write_new_table(runContext.environment_csv_path,environmentArtifact);
    write_new_table(runContext.input_hashes_csv_path, ...
        input_hash_table(inputHashes,runContext.run_id));
    if ~solverWillExecute
        acceptance=initialize_stage_a2_acceptance(projectRoot);
        for row=1:height(acceptance)
            acceptance=set_stage_a2_acceptance_result(acceptance, ...
                acceptance.test_id(row),"BLOCKED", ...
                "not run because environment/input preflight failed", ...
                "external dependency blocked","environment.csv; input_hashes.csv");
        end
        issues=append_stage_a2_issue(issues,runContext,"PRECHECK-EXTERNAL", ...
            "external_preflight","MATLAB environment or controlled input", ...
            "A2 direction was not executed","Environment or input SHA256 failed", ...
            "external environment or controlled input mismatch", ...
            "Restore the required environment/input and create a new run", ...
            "BLOCKED","environment.csv; input_hashes.csv");
        write_new_table(runContext.acceptance_results_path,acceptance);
        write_new_table(runContext.issue_log_path,issues);
        exception=MException("stageA2:external:Blocked", ...
            "A2 was not executed because external preflight failed.");
        report=generate_stage_a2_failure_report(runContext,exception,issues,acceptance);
        hashes=write_stage_a2_evidence_hashes(runContext);
        hashPath=fullfile(runContext.acceptance_dir,"evidence_hashes.csv");
        manifest=finalize_run_manifest(runContext,"BLOCKED_EXTERNAL",struct( ...
            "blocking_acceptance_total",6,"blocking_acceptance_pass",0, ...
            "evidence_hashes","acceptance/evidence_hashes.csv", ...
            "evidence_hashes_sha256",compute_sha256_file(hashPath), ...
            "evidence_file_count",height(hashes), ...
            "reports",struct("failure",relative_run_path(report,runContext.root)), ...
            "first_failed_layer","external_preflight"));
        result=struct("run_id",string(runContext.run_id), ...
            "run_path",string(runContext.root),"status","BLOCKED_EXTERNAL", ...
            "acceptance",acceptance,"issues",issues,"manifest",manifest);
        return
    end

    data=load_project_data(projectRoot);
    record_stage_a2_test_command(runContext,a2Command,a1Command);
    a2Tests=run_stage_A2_tests('EvidenceDirectory',runContext.tests_dir, ...
        'CommandText',a2Command);
    a1Tests=run_stage_A1_tests('EvidenceDirectory',a1Directory, ...
        'CommandText',a1Command);
    assert(a2Tests.all_pass,"stageA2:tests:A2Failed", ...
        "The fixed A2 test suite did not pass.");
    assert(a1Tests.all_pass && a1Tests.summary.test_total==37, ...
        "stageA2:tests:A1RegressionFailed", ...
        "All 37 A1 regression tests must pass before A2 execution.");
    assert(all_required_test_evidence_exists(a2Tests.paths) && ...
        all_required_test_evidence_exists(a1Tests.paths), ...
        "stageA2:tests:EvidenceIncomplete", ...
        "Both A2 and A1-regression CSV/JUnit/log/command/summary/inventory evidence are required.");

    index=build_stage_a2_index(data,"RunId",string(runContext.run_id));
    mark_stage_a2_solver_execution(runContext);
    verification=run_stage_a2_direction_verification(data,index,config);
    assert(isfinite(verification.audit.full_kkt_relative_residual) && ...
        verification.audit.full_kkt_relative_residual<=1e-10, ...
        "stageA2:numeric:DirectResidualHardLimit", ...
        "Direct full-KKT relative residual %.17g exceeds 1e-10.", ...
        verification.audit.full_kkt_relative_residual);
    codeScan=scan_stage_a2_forbidden_code(projectRoot,config);
    assert(all(string(codeScan.status)=="PASS"), ...
        "stageA2:scope:ForbiddenCode", ...
        "A2 forbidden-code or parallel scan did not pass.");
    exported=export_stage_a2_artifacts(runContext,data,index,config, ...
        verification.linearization,verification.direct, ...
        verification.recursive,verification.audit, ...
        Environment=environmentArtifact,Tests=a2Tests.summary, ...
        A1Regression=a1Tests.summary,CodeScan=codeScan);
    assert(all(exported.artifact_hashes.status=="PASS"), ...
        "stageA2:artifacts:HashFailure", ...
        "One or more numerical artifacts failed SHA256 creation.");
    acceptance=evaluate_stage_a2_acceptance_facts(projectRoot,data,index,verification);
    if any(acceptance.status~="PASS")
        raise_first_acceptance_failure(acceptance,verification);
    end
    write_new_table(runContext.issue_log_path,issues);
    assert(height(issues)==0,"stageA2:issues:UnresolvedBlocking", ...
        "Formal PASS requires no unexplained issue-log rows.");
    write_new_table(runContext.acceptance_results_path,acceptance);

    stagingRoot=string(tempname(tempdir)); mkdir(stagingRoot);
    stagedReports=generate_stage_a2_reports(runContext, ...
        'OutputDirectory',stagingRoot,'FinalStatusCandidate',"PASS");
    validate_report_set(stagedReports);
    reportPaths=install_staged_reports(runContext,stagedReports);
    cleanup_staging(stagingRoot); stagingRoot="";
    evidenceHashes=write_stage_a2_evidence_hashes(runContext);
    evidenceHashPath=fullfile(runContext.acceptance_dir,"evidence_hashes.csv");
    updates=struct( ...
        "a2_test_total",a2Tests.summary.test_total, ...
        "a2_test_passed",a2Tests.summary.test_passed, ...
        "a2_test_failed",a2Tests.summary.test_failed, ...
        "a2_test_incomplete",a2Tests.summary.test_incomplete, ...
        "a1_regression_total",a1Tests.summary.test_total, ...
        "a1_regression_passed",a1Tests.summary.test_passed, ...
        "a1_regression_failed",a1Tests.summary.test_failed, ...
        "a1_regression_incomplete",a1Tests.summary.test_incomplete, ...
        "full_kkt_dimension",verification.direct.kkt.dimension, ...
        "hourly_kkt_block_dimensions",[verification.recursive.partition.hour.dimension], ...
        "hourly_chain_dimension",size(verification.recursive.partition.M,1), ...
        "day_response_dimension",size(verification.recursive.day_response.S,1), ...
        "global_core_dimension",size(verification.recursive.core.matrix,1), ...
        "fixed_zero_count",verification.physical.fixed_zero_audit.count, ...
        "fixed_zero_exact",verification.physical.fixed_zero_audit.values_exact_zero && ...
            verification.physical.fixed_zero_audit.directions_exact_zero, ...
        "direction_relative_error",verification.audit.direction_relative_error, ...
        "recursive_full_kkt_relative_residual", ...
            verification.audit.recursive_kkt_relative_residual, ...
        "direct_full_kkt_relative_residual",verification.audit.full_kkt_relative_residual, ...
        "linearization_identity",char(verification.linearization.identity), ...
        "blocking_acceptance_total",6,"blocking_acceptance_pass",6, ...
        "numerical_artifact_hashes","matrices/numerical_artifact_hashes.csv", ...
        "evidence_hashes","acceptance/evidence_hashes.csv", ...
        "evidence_hashes_sha256",compute_sha256_file(evidenceHashPath), ...
        "evidence_file_count",height(evidenceHashes), ...
        "reports",relative_report_paths(reportPaths),"first_failed_layer","none");
    manifest=finalize_run_manifest(runContext,"PASS",updates);
    result=struct("run_id",string(runContext.run_id), ...
        "run_path",string(runContext.root),"status","PASS", ...
        "acceptance",acceptance,"issues",issues,"a2_tests",a2Tests, ...
        "a1_regression",a1Tests,"verification",verification, ...
        "exported",exported,"evidence_hashes",evidenceHashes, ...
        "reports",reportPaths,"manifest",manifest);
catch exception
    cleanup_staging(stagingRoot);
    preserve_stage_a2_failure(runContext,acceptance,issues,exception);
    rethrow(exception);
end
end

function assert_stage_a2_preflight(projectRoot)
current=string(fileread(fullfile(projectRoot,"CURRENT_STAGE.md")));
assert(contains(current,"`stage_id`: `stage_A2`") && ...
    contains(current,"`status`: `READY`"), ...
    "stageA2:gate:CurrentStage","CURRENT_STAGE must be stage_A2 / READY.");
[status,branch]=git_command(projectRoot,"branch --show-current");
assert(status==0 && strip(string(branch))=="stage_A2", ...
    "stageA2:gate:Branch","Formal A2 execution requires branch stage_A2.");
[status,tracked]=git_command(projectRoot,"status --porcelain --untracked-files=no");
assert(status==0 && strlength(strip(string(tracked)))==0, ...
    "stageA2:gate:TrackedChanges", ...
    "Formal A2 execution requires no uncommitted tracked changes.");
[status,worktree]=git_command(projectRoot, ...
    "status --porcelain --untracked-files=normal");
assert(status==0,"stageA2:gate:GitStatus","Could not inspect Git status.");
lines=splitlines(string(worktree)); lines=strip(lines(strlength(strip(lines))>0));
allowed=["?? runs/20260718_163832_stage_0_9e12222e.zip"; ...
    "?? runs/20260719_150810_stage_0_6591d873/"; ...
    "?? runs/20260720_131455_stage_A1_705f17da/"];
unknown=lines(~ismember(lines,allowed));
assert(isempty(unknown),"stageA2:gate:UnknownUntracked", ...
    "Unknown untracked content exists: %s",strjoin(unknown,"; "));
for historical=["20260719_150810_stage_0_6591d873", ...
        "20260720_131455_stage_A1_705f17da"]
    assert(isfolder(fullfile(projectRoot,"runs",historical)), ...
        "stageA2:gate:HistoricalRunMissing", ...
        "Required historical run is missing: %s",historical);
end
a1Manifest=jsondecode(fileread(fullfile(projectRoot,"runs", ...
    "20260720_131455_stage_A1_705f17da","run_manifest.json")));
assert(string(a1Manifest.status)=="PASS", ...
    "stageA2:gate:A1HistoricalStatus","Historical A1 manifest is not PASS.");
zipPath=fullfile(projectRoot,"runs","20260718_163832_stage_0_9e12222e.zip");
expected="B44576FD8F20C94F79E631A8D286D709CE4C9D41FEAFB724FA7DD01010FE78D7";
assert(isfile(zipPath) && upper(string(compute_sha256_file(zipPath)))==expected, ...
    "stageA2:gate:ProtectedZip","Protected Stage 0 ZIP is missing or changed.");
end

function [status,output] = git_command(root,arguments)
command="git -c safe.directory="+replace(string(root),'\','/')+" "+arguments;
[status,output]=system(char(command));
end

function value = input_hash_object(hashes)
value=struct();
for k=1:height(hashes)
    name=string(hashes.fileName(k));
    if name=="基础参数.xlsx"
        field="base_parameters";
    elseif name=="输入数据.xlsx"
        field="timeseries";
    else
        field=string(matlab.lang.makeValidName(name));
    end
    value.(field)=char(string(hashes.actualSHA256(k)));
end
end

function artifact = input_hash_table(hashes,runId)
n=height(hashes);
artifact=table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    repmat(string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX')),n,1), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status','checked_at'});
end

function raise_first_acceptance_failure(acceptance,verification)
row=find(acceptance.status~="PASS",1,'first');
assert(~isempty(row),"stageA2:acceptance:MissingFailure","Missing failed row.");
id=acceptance.test_id(row);
switch id
    case "SA2-MAT-001", layer="matrix_dimension_audit"; object=acceptance.actual_value(row);
    case {"SA2-ZERO-001","SA2-ZERO-002"}
        layer="fixed_zero_deletion_and_recovery"; object=acceptance.actual_value(row);
    case "SA2-EQ-001"
        layer="direction_equivalence_comparison";
        object=location_text(verification.audit.maximum_direction_difference.location);
    case "SA2-EQ-002"
        layer="full_kkt_reinsertion";
        object=location_text(verification.audit.maximum_recursive_residual.location);
    case "SA2-PHY-001"
        layer="formal_day_soc_boundary_assembly"; object="day14 hours1-24 SOC equations";
    otherwise, layer="acceptance_evaluation"; object=acceptance.actual_value(row);
end
error("stageA2:acceptance:BlockingFailure", ...
    "test_id '%s'; layer '%s'; object '%s'; actual '%s'", ...
    id,layer,replace(string(object),"'",""),acceptance.actual_value(row));
end

function value = location_text(location)
try
    value=string(jsonencode(location));
catch
    value=string(location);
end
end

function validate_report_set(paths)
names=fieldnames(paths);
assert(numel(names)==3,"stageA2:report:ReportCount", ...
    "Exactly three A2 reports are required.");
for k=1:numel(names)
    [valid,details]=validate_docx_package(paths.(names{k}));
    assert(valid,"stageA2:report:StructureValidation", ...
        "%s",strjoin(details.errors,"; "));
end
end

function installed = install_staged_reports(context,staged)
installed=struct(); names=fieldnames(staged);
for k=1:numel(names)
    source=string(staged.(names{k})); sourceHash=compute_sha256_file(source);
    [~,base,extension]=fileparts(source);
    target=string(fullfile(context.reports_dir,base+extension));
    assert(~isfile(target)&&~isfolder(target), ...
        "stageA2:report:TargetExists","Refusing to overwrite %s.",target);
    [moved,message]=movefile(source,target);
    assert(moved,"stageA2:report:InstallFailed","%s",message);
    assert(lower(string(compute_sha256_file(target)))==lower(string(sourceHash)), ...
        "stageA2:report:InstalledHash","Installed report hash changed.");
    installed.(names{k})=char(target);
end
end

function value = relative_report_paths(paths)
value=struct(); names=fieldnames(paths);
for k=1:numel(names)
    [~,base,extension]=fileparts(paths.(names{k}));
    value.(names{k})=char("reports/"+string(base)+string(extension));
end
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA2:artifacts:TargetExists","Refusing to overwrite %s.",pathValue);
write_table_csv_17g(pathValue,value);
end

function passed = all_required_test_evidence_exists(paths)
values=string(struct2cell(paths));
passed=numel(values)==6 && all(isfile(values));
end

function preserve_stage_a2_failure(context,acceptance,issues,exception)
hashPath=fullfile(context.acceptance_dir,"evidence_hashes.csv");
if isfile(hashPath)
    prior=fullfile(context.acceptance_dir, ...
        "evidence_hashes.pre_failure_candidate.csv");
    try
        if ~isfile(prior)&&~isfolder(prior), movefile(hashPath,prior); end
    catch
    end
end
preserve_candidate_file(context.acceptance_results_path, ...
    fullfile(context.acceptance_dir,"acceptance_results.pre_failure_candidate.csv"));
preserve_candidate_file(context.issue_log_path, ...
    fullfile(context.issues_dir,"issue_log.pre_failure_candidate.csv"));
try
    if isempty(acceptance)
        acceptance=initialize_stage_a2_acceptance(string(context.project_root));
    end
    failureId=first_failure_test_id(exception);
    if nnz(acceptance.test_id==failureId)==1
        acceptance=set_stage_a2_acceptance_result(acceptance,failureId,"FAIL", ...
            exception.message,"first failing A2 acceptance fact","run_manifest.json");
    end
    for row=1:height(acceptance)
        if acceptance.status(row)=="NOT_RUN"
            acceptance=set_stage_a2_acceptance_result(acceptance, ...
                acceptance.test_id(row),"BLOCKED", ...
                "not completed after "+failureId, ...
                "dependency blocked by first failure","run_manifest.json");
        end
    end
    write_table_csv_17g(context.acceptance_results_path,acceptance);
catch
end
try
    issues=append_stage_a2_issue(issues,context,failureId, ...
        first_failure_layer(exception),first_failure_object(exception), ...
        "Stage A2 formal run failed",exception.message, ...
        "See exception and persisted evidence", ...
        "Fix the first failing layer and create a new unique run", ...
        "OPEN","run_manifest.json");
    write_table_csv_17g(context.issue_log_path,issues);
catch
end
try
    generate_stage_a2_failure_report(context,exception,issues,acceptance);
catch
end
try
    if ~isfile(hashPath), write_stage_a2_evidence_hashes(context); end
catch
end
try
    manifest=jsondecode(fileread(context.run_manifest_path));
    if string(manifest.status)=="RUNNING"
        updates=struct("fatal_error_identifier",exception.identifier, ...
            "fatal_error_message",exception.message, ...
            "first_failed_layer",first_failure_layer(exception), ...
            "first_failed_object",first_failure_object(exception));
        if isfile(hashPath)
            updates.evidence_hashes="acceptance/evidence_hashes.csv";
            updates.evidence_hashes_sha256=compute_sha256_file(hashPath);
        end
        report=fullfile(context.reports_dir,"阶段A2_失败与首层定位报告.docx");
        if isfile(report)
            updates.reports=struct("failure",relative_run_path(report,context.root));
        end
        finalize_run_manifest(context,"FAIL_RETRYABLE",updates);
    end
catch
end
end

function value = first_failure_test_id(exception)
token=regexp(exception.message,"test_id '([^']+)'",'tokens','once');
if ~isempty(token)
    value=string(token{1});
    return
end
id=string(exception.identifier);
if contains(id,"FullKktDimension")
    value="SA2-MAT-001";
elseif contains(id,"FixedZero")
    value="SA2-ZERO-001";
elseif contains(id,"Direction") && contains(id,"Equivalent")
    value="SA2-EQ-001";
elseif contains(id,"Recursive") || contains(id,"Reinsertion")
    value="SA2-EQ-002";
elseif contains(id,"Soc") || contains(id,"Boundary")
    value="SA2-PHY-001";
else
    value="NON_ACCEPTANCE-TEST-OR-ARTIFACT";
end
end

function value = first_failure_layer(exception)
token=regexp(exception.message,"layer '([^']+)'",'tokens','once');
if isempty(token)
    value="execution_test_artifact_or_report";
else
    value=string(token{1});
end
end

function value = first_failure_object(exception)
token=regexp(exception.message,"object '([^']*)'",'tokens','once');
if ~isempty(token)
    value=string(token{1});
    return
end
message=string(exception.message);
hourMatch=regexp(message, ...
    "Hour \d+ failed at [^;]+; xi indices=\[[^\]]*\]; equality indices=\[[^\]]*\]; block dimension=\d+", ...
    'match','once');
coreMatch=regexp(message, ...
    "16-by-16 core failed for q indices 1:14 and duration multiplier indices 1:2", ...
    'match','once');
inequalityMatch=regexp(message,"Inequality elimination failed at row \d+", ...
    'match','once');
if ~isempty(hourMatch)
    value=string(hourMatch);
elseif ~isempty(coreMatch)
    value=string(coreMatch);
elseif ~isempty(inequalityMatch)
    value=string(inequalityMatch);
else
    value=string(exception.identifier);
end
if ~isempty(exception.cause)
    value=value+"; cause="+string(exception.cause{1}.identifier);
end
end

function value = relative_run_path(pathValue,runRoot)
value=char(replace(extractAfter(string(pathValue), ...
    strlength(string(runRoot))+1),'\','/'));
end

function cleanup_staging(pathValue)
if strlength(string(pathValue))>0 && isfolder(pathValue)
    try
        rmdir(pathValue,'s');
    catch
    end
end
end

function preserve_candidate_file(source,target)
if ~isfile(source), return; end
try
    if ~isfile(target)&&~isfolder(target), movefile(source,target); end
catch
end
end
