function result = main_stage_A4_2A()
%MAIN_STAGE_A4_2A Execute the non-formal five-iteration A4 diagnostic.
%
% This entry deliberately performs exactly five primal-dual updates.  It
% does not create runs/<run_id>, does not execute the complete A4 IPM, and
% does not change CURRENT_STAGE.md or enter stage_B.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
config = load_stage_a4_configuration(projectRoot);
data = load_project_data(projectRoot);
index = build_stage_a4_index(data,"RunId","A4_2A_FIVE_ITERATION_DIAGNOSTIC");
result = run_stage_a4_five_iteration_diagnostic(data,index,config);
assert(result.all_pass && result.milestone_status=="PASS" && ...
    result.stage_status=="READY" && result.iteration_count==5 && ...
    result.execution.newton_direction_count==5 && ...
    result.execution.state_update_count==5 && ...
    result.execution.full_kkt_audit_count==5 && ...
    result.completed_newton_direction_count==5 && ...
    result.final_state.newton_direction_number==5 && ...
    ~result.execution.full_ipm_executed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.stage_b_entered, ...
    "stageA4:fiveIteration:MainContract", ...
    "A4-2A did not satisfy the exact five-iteration diagnostic contract.");
print_diagnostic_summary(result);
end

function print_diagnostic_summary(result)
fprintf('A4-2A five-iteration diagnostic (stage remains %s):\n', ...
    result.stage_status);
fprintf(['iteration,alpha_primal,alpha_dual,primal_limiter,' ...
    'dual_limiter,eq_before,eq_after,ineq_before,ineq_after,' ...
    'dual_before,dual_after,comp_residual_before,comp_residual_after,' ...
    'gap_before,gap_after,min_l_after,min_z_after,direction_error,' ...
    'xi_error,y_error,l_error,z_error,recursive_kkt_residual,' ...
    'full_kkt_residual\n']);
for k = 1:result.iteration_count
    item = result.iterations(k);
    fprintf(['%d,%.17g,%.17g,%s,%s,%.17g,%.17g,%.17g,%.17g,' ...
        '%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,' ...
        '%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g\n'], ...
        k,item.alpha_primal,item.alpha_dual, ...
        char(item.primal_step.limiting_constraint_id), ...
        char(item.dual_step.limiting_constraint_id), ...
        item.residuals_before.equality_inf, ...
        item.residuals_after.equality_inf, ...
        item.residuals_before.slack_equality_inf, ...
        item.residuals_after.slack_equality_inf, ...
        item.residuals_before.dual_inf,item.residuals_after.dual_inf, ...
        item.residuals_before.complementarity_inf, ...
        item.residuals_after.complementarity_inf, ...
        item.residuals_before.complementarity_gap, ...
        item.residuals_after.complementarity_gap, ...
        item.residuals_after.minimum_l,item.residuals_after.minimum_z, ...
        item.direction_relative_error, ...
        item.component_relative_errors.xi, ...
        item.component_relative_errors.y, ...
        item.component_relative_errors.l, ...
        item.component_relative_errors.z, ...
        item.recursive_kkt_relative_residual, ...
        item.full_kkt_relative_residual);
end
fprintf(['iteration,qp5_before,qp5_direction,qp5_after,' ...
    'lower_l_before,lower_dl,lower_l_after,lower_z_before,lower_dz,' ...
    'lower_z_after,upper_l_before,upper_dl,upper_l_after,' ...
    'upper_z_before,upper_dz,upper_z_after\n']);
for k = 1:result.iteration_count
    item = result.iterations(k);
    q = item.qp5;
    fprintf(['%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,' ...
        '%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g\n'], ...
        k,q.capacity_value_before,q.capacity_direction, ...
        q.capacity_value_after, ...
        q.lower.slack_before,q.lower.slack_direction,q.lower.slack_after, ...
        q.lower.multiplier_before,q.lower.multiplier_direction, ...
        q.lower.multiplier_after, ...
        q.upper.slack_before,q.upper.slack_direction,q.upper.slack_after, ...
        q.upper.multiplier_before,q.upper.multiplier_direction, ...
        q.upper.multiplier_after);
end
fprintf(['iteration,linearization_before,recursive,full_kkt_audit,' ...
    'direction_audit,fraction_steps,state_update,linearization_after,' ...
    'closure_structure,total_seconds\n']);
for k = 1:result.iteration_count
    timing = result.iterations(k).timing;
    fprintf(['%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,' ...
        '%.17g,%.17g\n'],k,timing.linearization_before_seconds, ...
        timing.recursive_seconds,timing.full_kkt_audit_seconds, ...
        timing.direction_equivalence_audit_seconds, ...
        timing.fraction_to_boundary_seconds,timing.state_update_seconds, ...
        timing.linearization_after_seconds, ...
        timing.closure_and_structure_audit_seconds,timing.total_seconds);
end
fprintf(['RECOVERY primal_ratio=%.17g dual_ratio=%.17g ' ...
    'primal_recovered=%d dual_recovered=%d total_seconds=%.17g\n'], ...
    result.step_recovery.primal_later_to_first_ratio, ...
    result.step_recovery.dual_later_to_first_ratio, ...
    result.step_recovery.primal_recovered_after_first, ...
    result.step_recovery.dual_recovered_after_first, ...
    result.timing.total_seconds);
end
