function result = main_stage_B_2B(options)
%MAIN_STAGE_B_2B Run one bordered-recursive/full-KKT direction audit.
%
% This entry computes exactly one Newton direction from one shared B-2B
% linearization.  The recursive bordered LDL/Thomas route is authoritative;
% the raw sparse full KKT is solved independently and only for audit.  No
% state update, IPM loop, optimization, parallelism, or Stage C1 work occurs.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
end
root=options.ProjectRoot;
if strlength(strtrim(root))==0, root=string(fileparts(mfilename("fullpath"))); end
root=string(java.io.File(char(root)).getCanonicalPath());
addpath(genpath(fullfile(root,"src"))); addpath(fullfile(root,"tests"));
config=load_stage_b2b_configuration(root);
assert_clean_implementation_commit(root);
[inputHashes,inputPass]=verify_input_hashes(root);
assert(inputPass,"stageB2B:InputHashMismatch", ...
    "Controlled input SHA256 verification failed.");
commit=git_commit(root); shortCommit=extractBefore(commit,9);
runId=choose_run_id(root,options.RunId,shortCommit);
actualCommand="matlab -batch ""result=main_stage_B_2B(); "+ ...
    "disp(result.run_id); assert(strcmp(char(result.status),'PASS'));""";
metadata=struct("run_purpose",char(config.run_purpose), ...
    "milestone","B-2B","implementation_commit",char(commit), ...
    "parent_run_id","20260803_143208_stage_B_2A_e7f049c9", ...
    "historical_baseline_commit", ...
        "e7f049c9c2f43c1bf111c24f0a86c1e0a46bd405", ...
    "actual_test_command",char(actualCommand), ...
    "data_window_days",config.days,"data_window_hours",config.hours, ...
    "water_inequality_count",56,"water_border_rows_per_day",8, ...
    "newton_direction_count",1,"full_kkt_solved",false, ...
    "full_kkt_role","audit_only","recursive_direction_executed",false, ...
    "no_full_direction_fallback",true,"full_ipm_executed",false, ...
    "optimization_executed",false,"state_update_executed",false, ...
    "parallel_executed",false,"stage_c1_entered",false, ...
    "annual_scope_executed",false,"thermal_second_pass_enabled",false, ...
    "milestone_status","RUNNING","stage_b_complete",false);
context=create_run_context(root,"stage_B","RunId",runId, ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",fullfile(root,"config","stage_B_2B.yaml"), ...
    "ManifestMetadata",metadata);
diagnosticsDir=fullfile(context.root,"diagnostics"); ensure_directory(diagnosticsDir);
result=struct("run_id",string(context.run_id),"run_path",string(context.root), ...
    "status","RUNNING","manifest",struct(),"report_path","", ...
    "error_identifier","");
try
    environment=inspect_stage_b2b_environment();
    environment=addvars(environment,repmat(string(context.run_id), ...
        height(environment),1),'Before',1,'NewVariableNames','run_id');
    write_new_table(context.environment_csv_path,environment);
    assert(all(environment.status(logical(environment.blocking))=="PASS"), ...
        "stageB2B:Environment","A blocking environment check failed.");
    write_new_table(context.input_hashes_csv_path, ...
        input_hash_table(inputHashes,context.run_id));

    data=load_project_data(root);
    waterInput=build_stage_b1_water_input_audit(data,context.run_id);
    write_new_table(fullfile(diagnosticsDir,"water_input_audit.csv"),waterInput);
    assert(height(waterInput)==28 && all(waterInput.status=="PASS"), ...
        "stageB2B:WaterInput","The controlled water-input audit failed.");
    index=build_stage_b2b_index(data,config,"RunId",string(context.run_id));
    state=initialize_stage_b2b_state(data,index,config);
    linearization=build_stage_b2b_multiday_linearization( ...
        state,data,index,config);

    recursive=solve_stage_b2b_recursive_direction(linearization, ...
        SymmetryTolerance=config.reduced_symmetry_tolerance, ...
        ResidualRefinementMaxPasses=config.recursive_refinement_max_passes, ...
        UseCongruenceScaling=false);
    fullAudit=solve_stage_b2b_full_kkt_direction(linearization);
    audits=build_stage_b2b_audits( ...
        data,index,linearization,recursive,fullAudit,config);
    assert(audits.equivalence.all_pass, ...
        "stageB2B:DirectionEquivalence", ...
        "Full-vs-recursive direction equivalence failed.");

    persist_index_artifacts(context,index);
    persist_diagnostic_tables(diagnosticsDir,audits,index,context.run_id);
    matPaths=persist_mat_artifacts(context,index,state,linearization, ...
        recursive,fullAudit,audits.equivalence);
    matrixManifest=build_matrix_manifest( ...
        context,linearization,recursive,fullAudit,matPaths);
    write_new_table(context.matrix_manifest_path,matrixManifest);

    acceptance=make_acceptance(context,audits,config);
    write_new_table(context.acceptance_results_path,acceptance);
    physicalAudit=table(string(context.run_id),"SB-PHY-001", ...
        "Stage-B optimized daily-water physical feasibility","NOT_RUN", ...
        "B-2B performs one direction only; no optimization or physical claim.", ...
        'VariableNames',{'run_id','audit_id','scope','status','actual_value'});
    write_new_table(fullfile(context.acceptance_dir,"physical_audit.csv"), ...
        physicalAudit);
    issues=empty_issue_log(); write_new_table(context.issue_log_path,issues);
    decision=table(string(context.run_id),"B-2B","READY_FOR_REVIEW", ...
        "SB-EQ-001 passed for one shared-linearization bordered recursive direction.", ...
        "Keep Stage B READY; SB-PHY-001 remains NOT_RUN and Stage C1 is not entered.", ...
        'VariableNames',{'run_id','milestone','status','conclusion','next_action'});
    write_new_table(context.decision_log_path,decision);

    update_running_run_manifest(context,struct( ...
        "full_kkt_solved",true,"full_kkt_role","audit_only", ...
        "recursive_direction_executed",true, ...
        "no_full_direction_fallback",true, ...
        "full_direction_consumed_by_recursive",false, ...
        "full_ipm_executed",false, ...
        "state_update_executed",false,"parallel_executed",false, ...
        "stage_c1_entered",false,"annual_scope_executed",false, ...
        "water_hessian_rebuilt_from_current_positive_state",true, ...
        "water_border_assembly","daily_augmented_border_low_rank_update", ...
        "primal_dimension",linearization.counts.primal, ...
        "equality_dimension",linearization.counts.equalities, ...
        "inequality_dimension",linearization.counts.inequalities, ...
        "full_kkt_dimension",fullAudit.kkt.dimension, ...
        "full_kkt_nnz",fullAudit.kkt.nnz, ...
        "daily_hourly_chain_dimensions", ...
            reshape([recursive.partition.day.hourly_chain_dimension],1,[]), ...
        "daily_water_border_dimensions",repmat(8,1,7), ...
        "daily_response_dimensions",repmat(14,1,7), ...
        "global_core_dimension",16, ...
        "direction_relative_error",audits.equivalence.direction_relative_error, ...
        "xi_direction_relative_error", ...
            audits.equivalence.component_relative_errors.xi, ...
        "y_direction_relative_error", ...
            audits.equivalence.component_relative_errors.y, ...
        "l_direction_relative_error", ...
            audits.equivalence.component_relative_errors.l, ...
        "z_direction_relative_error", ...
            audits.equivalence.component_relative_errors.z, ...
        "recursive_full_kkt_relative_residual", ...
            audits.equivalence.recursive_kkt_relative_residual, ...
        "full_kkt_audit_relative_residual", ...
            audits.equivalence.full_kkt_relative_residual, ...
        "fixed_zero_count",recursive.fixed_zero.count, ...
        "fixed_zero_exact",recursive.fixed_zero.all_exact_zero, ...
        "blocking_acceptance_id","SB-EQ-001", ...
        "blocking_acceptance_status","PASS", ...
        "not_run_acceptance_id","SB-PHY-001"));

    b2b=run_stage_B_2B_tests("EvidenceDirectory", ...
        string(context.tests_dir),"CommandText", ...
        "run_stage_B_2B_tests() [formal B-2B evidence]");
    b2a=run_stage_B_2A_tests("EvidenceDirectory", ...
        string(fullfile(context.tests_dir,"b2a_regression")), ...
        "CommandText","run_stage_B_2A_tests() [B-2B regression]");
    b1=run_stage_B_1_tests("EvidenceDirectory", ...
        string(fullfile(context.tests_dir,"b1_regression")), ...
        "CommandText","run_stage_B_1_tests() [B-2B regression]");
    b1Affected=run_stage_B_1_affected_regressions("EvidenceDirectory", ...
        string(fullfile(context.tests_dir,"b1_affected")), ...
        "CommandText","run_stage_B_1_affected_regressions() [B-2B]");
    a4=run_stage_B_2A_stage_A_regressions("EvidenceDirectory", ...
        string(fullfile(context.tests_dir,"a4_structure")), ...
        "CommandText","run_stage_B_2A_stage_A_regressions() [B-2B]");
    assert(b2b.all_pass&&b2a.all_pass&&b1.all_pass&& ...
        b1Affected.all_pass&&a4.all_pass,"stageB2B:Tests", ...
        "A fixed or affected regression suite failed.");
    static=run_stage_b2b_static_checks(root);
    write_new_table(fullfile(context.tests_dir,"static_check_summary.csv"), ...
        static.code_analyzer);
    write_new_table(fullfile(context.tests_dir, ...
        "forbidden_execution_audit.csv"),static.forbidden_execution);
    write_new_table(fullfile(context.tests_dir, ...
        "dependency_closure_audit.csv"),static.dependency_closure);
    assert(static.all_pass,"stageB2B:Static", ...
        "Code Analyzer or forbidden-execution audit failed.");
    total=b2b.summary.test_total+b2a.summary.test_total+ ...
        b1.summary.test_total+b1Affected.summary.test_total+a4.summary.test_total;
    passed=b2b.summary.test_passed+b2a.summary.test_passed+ ...
        b1.summary.test_passed+b1Affected.summary.test_passed+a4.summary.test_passed;
    update_running_run_manifest(context,struct("tests_executed",true, ...
        "b2b_test_total",b2b.summary.test_total, ...
        "b2b_test_passed",b2b.summary.test_passed, ...
        "b2a_regression_total",b2a.summary.test_total, ...
        "b2a_regression_passed",b2a.summary.test_passed, ...
        "b1_regression_total",b1.summary.test_total, ...
        "b1_regression_passed",b1.summary.test_passed, ...
        "b1_affected_total",b1Affected.summary.test_total, ...
        "b1_affected_passed",b1Affected.summary.test_passed, ...
        "stage_a_structure_regression_total",a4.summary.test_total, ...
        "stage_a_structure_regression_passed",a4.summary.test_passed, ...
        "test_total",total,"test_passed",passed,"test_failed",0, ...
        "test_incomplete",0,"code_analyzer_blocking_findings", ...
        static.blocking_findings,"forbidden_execution_pass",true));

    report=generate_stage_b2b_report(context.root);
    [reportValid,reportDetails]=validate_stage_b2b_report(context.root);
    validation=table(string(context.run_id), ...
        "stage_B_2B_bordered_recursive_direction_equivalence", ...
        string(report.path),reportValid,conditional_status(reportValid), ...
        string(reportDetails.message), ...
        'VariableNames',{'run_id','report_id','path','valid','status','details'});
    write_new_table(fullfile(context.reports_dir, ...
        "report_structure_validation.csv"),validation);
    assert(reportValid,"stageB2B:Report", ...
        "The B-2B Chinese report failed structural validation: %s", ...
        reportDetails.message);
    reportHash=table( ...
        "reports/阶段B-2B_日级水量边框递推KKT方向等价验证报告.docx", ...
        compute_sha256_file(report.path),string(context.run_id),"PASS", ...
        'VariableNames',{'relative_path','sha256','run_id','status'});
    write_new_table(fullfile(context.reports_dir,"report_sha256.csv"),reportHash);
    update_running_run_manifest(context,struct("reports_generated",true, ...
        "report_structure_validated",true, ...
        "report_relative_path",char(reportHash.relative_path), ...
        "report_sha256",char(reportHash.sha256), ...
        "milestone_status","READY_FOR_REVIEW"));

    evidence=write_evidence_hashes(context.root, ...
        fullfile(context.acceptance_dir,"evidence_hashes.csv"));
    manifest=finalize_run_manifest(context,"PASS",struct( ...
        "milestone_status","READY_FOR_REVIEW", ...
        "stage_b_complete",false,"stage_c1_entered",false, ...
        "evidence_hashes","acceptance/evidence_hashes.csv", ...
        "evidence_hashes_sha256",char(compute_sha256_file( ...
            fullfile(context.acceptance_dir,"evidence_hashes.csv"))), ...
        "evidence_file_count",height(evidence)));
    result.status=string(manifest.status); result.manifest=manifest;
    result.report_path=string(report.path); result.acceptance=acceptance;
    result.equivalence=audits.equivalence;
catch cause
    try
        write_table_csv_17g_atomic(string(context.issue_log_path), ...
            failure_issue(context,cause));
    catch
    end
    finalStatus="FAIL_RETRYABLE";
    if contains(string(cause.identifier),["Environment","InputHash"])
        finalStatus="BLOCKED_EXTERNAL";
    elseif contains(string(cause.identifier),"ModelDecision")
        finalStatus="NEEDS_MODEL_DECISION";
    end
    try
        manifest=jsondecode(fileread(context.run_manifest_path));
        if string(manifest.status)=="RUNNING"
            manifest=finalize_run_manifest(context,finalStatus,struct( ...
                "milestone_status",char(finalStatus),"stage_b_complete",false, ...
                "stage_c1_entered",false, ...
                "failure_identifier",char(string(cause.identifier)), ...
                "failure_message",char(string(cause.message))));
        end
    catch
        manifest=struct();
    end
    result.status=finalStatus; result.manifest=manifest;
    result.error_identifier=string(cause.identifier);
    result.error_message=string(cause.message);
end
end

function persist_index_artifacts(context,index)
write_new_table(fullfile(context.indices_dir,"variable_index.csv"),index.variable_index);
write_new_table(fullfile(context.indices_dir,"constraint_index.csv"),index.constraint_index);
write_new_table(fullfile(context.indices_dir,"block_index.csv"),index.block_index);
write_new_table(fullfile(context.indices_dir,"fixed_zero_map.csv"),index.fixed_zero_map);
write_new_table(fullfile(context.indices_dir,"permutation_map.csv"),index.permutation_map);
write_new_table(fullfile(context.indices_dir,"soc_link_map.csv"),index.soc_link_map);
write_new_table(fullfile(context.indices_dir,"water_constraint_index.csv"), ...
    index.water_constraint_index);
end

function persist_diagnostic_tables(root,audits,index,runId)
write_new_table(fullfile(root,"inequality_elimination_audit.csv"),audits.inequality_elimination);
write_new_table(fullfile(root,"reduced_symmetry_audit.csv"),audits.reduced_symmetry);
write_new_table(fullfile(root,"daily_water_border_audit.csv"),audits.daily_water_border);
write_new_table(fullfile(root,"daily_response_audit.csv"),audits.daily_response);
write_new_table(fullfile(root,"direction_comparison.csv"),audits.direction_comparison);
write_new_table(fullfile(root,"back_substitution_audit.csv"),audits.back_substitution);
write_new_table(fullfile(root,"fixed_zero_audit.csv"),audits.fixed_zero);
write_new_table(fullfile(root,"stationarity_finite_difference_audit.csv"), ...
    audits.stationarity_finite_difference);
write_new_table(fullfile(root,"full_kkt_structure.csv"),audits.full_kkt_structure);
write_new_table(fullfile(root,"execution_boundary_audit.csv"),audits.execution);
water=index.water_constraint_index;
water.run_id=repmat(string(runId),height(water),1);
water.border_row_within_day=repmat((1:8).',7,1);
water.border_dimension(:)=8;
water.assembly_location(:)="daily_augmented_border_outside_hourly_chain";
write_new_table(fullfile(root,"water_border_structure.csv"),water);
end

function paths=persist_mat_artifacts(context,index,state,lin,recursive,fullAudit,equivalence)
paths=struct("index",fullfile(context.matrices_dir,"stage_b2b_index_state.mat"), ...
    "linearization",fullfile(context.matrices_dir,"stage_b2b_linearization.mat"), ...
    "recursive",fullfile(context.matrices_dir,"stage_b2b_recursive_direction.mat"), ...
    "full",fullfile(context.matrices_dir,"stage_b2b_full_kkt_audit.mat"));
for path=string(struct2cell(paths)).'
    assert(~isfile(path)&&~isfolder(path),"stageB2B:ArtifactExists", ...
        "Refusing to overwrite %s.",path);
end
save_mat_artifact(paths.index,"index",index,"state",state);
save_mat_artifact(paths.linearization,"linearization",lin);
save_mat_artifact(paths.recursive,"recursive",recursive,"equivalence",equivalence);
save_mat_artifact(paths.full,"matrix",fullAudit.kkt.matrix, ...
    "rhs",fullAudit.kkt.rhs,"direction",fullAudit.direction, ...
    "slices",fullAudit.kkt.slices,"symmetry",fullAudit.kkt.symmetry, ...
    "linearization_identity",fullAudit.linearization_identity);
end

function value=build_matrix_manifest(context,lin,recursive,fullAudit,paths)
matrix_name=["H_L";"A";"G";"reduced_W";"reduced_saddle"; ...
    "global_core_16";"full_KKT_audit"];
matrices={lin.H;lin.A;lin.G;recursive.reduced.W; ...
    recursive.reduced.saddle;recursive.core.matrix;fullAudit.kkt.matrix};
row_count=zeros(7,1); column_count=zeros(7,1); nonzero_count=zeros(7,1);
for k=1:7
    [row_count(k),column_count(k)]=size(matrices{k});
    nonzero_count(k)=nnz(matrices{k});
end
artifact_path=[repmat("matrices/stage_b2b_linearization.mat",3,1); ...
    repmat("matrices/stage_b2b_recursive_direction.mat",3,1); ...
    "matrices/stage_b2b_full_kkt_audit.mat"];
sha256=[repmat(compute_sha256_file(paths.linearization),3,1); ...
    repmat(compute_sha256_file(paths.recursive),3,1); ...
    compute_sha256_file(paths.full)];
role=["shared_lagrangian_hessian";"shared_equality_jacobian"; ...
    "shared_inequality_jacobian";"algebraic_audit"; ...
    "algebraic_audit";"recursive_formal";"independent_audit_only"];
solved=[false;false;false;false;false;true;true];
value=table(repmat(string(context.run_id),7,1),matrix_name,role, ...
    row_count,column_count,nonzero_count,true(7,1),artifact_path,sha256, ...
    repmat(string(lin.identity),7,1),solved,repmat("PASS",7,1), ...
    'VariableNames',{'run_id','matrix_name','role','row_count', ...
    'column_count','nonzero_count','is_sparse','artifact_path','sha256', ...
    'linearization_identity','solved','status'});
end

function value=make_acceptance(context,audits,config)
test_id=["SB-DATA-001";"SB-DER-001";"SB-EQ-001";"SB-PHY-001"];
category=["数据";"导数";"方向等价";"物理"];
requirement=["受控第14—20日水量输入"; ...
    "水量Lagrangian Hessian与stationarity有限差分一致"; ...
    "完整与递推方向误差及递推KKT残差<=1e-10"; ...
    "优化后四座水电日用水物理可行"];
status=["PASS";"PASS";"PASS";"NOT_RUN"];
actual_value=["28 day-hydro rows PASS"; ...
    compose("relative_error=%.17g", ...
        audits.stationarity_finite_difference.relative_error); ...
    compose("direction=%.17g; recursive_residual=%.17g", ...
        audits.equivalence.direction_relative_error, ...
        audits.equivalence.recursive_kkt_relative_residual); ...
    "No optimization in B-2B"];
evidence_path=["diagnostics/water_input_audit.csv"; ...
    "diagnostics/stationarity_finite_difference_audit.csv"; ...
    "diagnostics/direction_comparison.csv"; ...
    "acceptance/physical_audit.csv"];
value=table(repmat(string(context.run_id),4,1),test_id,category, ...
    requirement,true(4,1),status,actual_value,evidence_path, ...
    repmat(string(config.milestone_id),4,1), ...
    'VariableNames',{'run_id','test_id','category','requirement', ...
    'blocking','status','actual_value','evidence_path','milestone'});
end

function value=empty_issue_log()
value=table(strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end
function value=failure_issue(context,cause)
value=table(string(context.run_id),"B2B-EXECUTION","SB-EQ-001", ...
    "execution",string(cause.message), ...
    "Unique failed run and all completed artifacts were preserved.", ...
    "Repair the first failed layer without changing model or thresholds.", ...
    "OPEN","run_manifest.json", ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end

function value=write_evidence_hashes(runRoot,pathValue)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB2B:EvidenceHashExists","Refusing to overwrite hash evidence.");
listing=dir(fullfile(runRoot,"**","*")); listing=listing(~[listing.isdir]);
relative_path=strings(0,1); sha256=strings(0,1); bytes=zeros(0,1);
for k=1:numel(listing)
    absolute=string(fullfile(listing(k).folder,listing(k).name));
    relative=replace(extractAfter(absolute,string(runRoot)+filesep),filesep,"/");
    if relative=="acceptance/evidence_hashes.csv" || relative=="run_manifest.json", continue; end
    relative_path(end+1,1)=relative; sha256(end+1,1)=compute_sha256_file(absolute); ...
        bytes(end+1,1)=listing(k).bytes; %#ok<AGROW>
end
[relative_path,order]=sort(relative_path); sha256=sha256(order); bytes=bytes(order);
value=table(relative_path,sha256,bytes,repmat("PASS",numel(bytes),1), ...
    'VariableNames',{'relative_path','sha256','bytes','status'});
write_new_table(pathValue,value);
end

function value=input_hash_object(hashes)
base=hashes.fileName=="基础参数.xlsx"; series=hashes.fileName=="输入数据.xlsx";
assert(nnz(base)==1&&nnz(series)==1,"stageB2B:InputHashRows", ...
    "Both controlled input rows are required.");
value=struct("base_parameters",char(hashes.actualSHA256(base)), ...
    "timeseries",char(hashes.actualSHA256(series)));
end
function value=input_hash_table(hashes,runId)
n=height(hashes);
value=table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status'});
end
function assert_clean_implementation_commit(root)
[code,branch]=system(git_command(root,"rev-parse --abbrev-ref HEAD"));
assert(code==0&&strip(string(branch))=="stage_B","stageB2B:GitBranch", ...
    "Formal B-2B must run on branch stage_B.");
[code,changes]=system(git_command(root,"status --porcelain --untracked-files=no"));
assert(code==0&&strlength(strip(string(changes)))==0,"stageB2B:GitDirty", ...
    "Formal B-2B requires a clean tracked worktree.");
end
function value=git_commit(root)
[code,output]=system(git_command(root,"rev-parse HEAD")); value=lower(strip(string(output)));
assert(code==0&&~isempty(regexp(value,"^[0-9a-f]{40}$","once")), ...
    "stageB2B:GitCommit","Could not resolve implementation commit.");
end
function value=git_command(root,arguments)
safe=replace(char(root),'\','/');
value=string(sprintf('git -c safe.directory=%s %s',safe,char(arguments)));
end
function runId=choose_run_id(root,requested,shortCommit)
if strlength(strtrim(requested))>0
    runId=requested; assert(~contains(runId,["/","\"]),"stageB2B:RunId", ...
        "Run id must be a leaf name.");
else
    timestamp=string(datetime("now","TimeZone","UTC","Format","yyyyMMdd_HHmmss"));
    runId=timestamp+"_stage_B_2B_"+shortCommit;
end
assert(~isfile(fullfile(root,"runs",runId))&&~isfolder(fullfile(root,"runs",runId)), ...
    "stageB2B:RunExists","Run path already exists: %s",runId);
end
function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message]=mkdir(pathValue); assert(created,"stageB2B:Directory","%s",message);
end
function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue),"stageB2B:ArtifactExists", ...
    "Refusing to overwrite %s.",pathValue);
write_table_csv_17g(pathValue,value);
end
function value=conditional_status(passed)
if passed, value="PASS"; else, value="FAIL"; end
end
