function result = main_stage_A1()
%MAIN_STAGE_A1 Execute the one frozen three-hour direction comparison.
% The function never performs an IPM update, starts a parallel pool, or
% interprets the artificial closed window as a physical operating day.

projectRoot = string(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(projectRoot,"src")));
addpath(fullfile(projectRoot,"tests"));
assert_stage_a1_preflight(projectRoot);
config = load_stage_a1_configuration(projectRoot);

environment = inspect_stage_a1_environment();
[inputHashes,inputHashesPass] = verify_input_hashes(projectRoot);
environmentPass = all(string(environment.status(logical(environment.blocking)))=="PASS");
solverWillExecute = environmentPass && inputHashesPass;
formalCommand = ['matlab -batch "result=main_stage_A1(); ' ...
    'assert(strcmp(char(result.status),''PASS''))"'];
metadata = struct( ...
    "run_purpose","stage_A1_single_newton_direction_equivalence", ...
    "window_type",char(config.window_type), ...
    "input_day",config.days, ...
    "start_hour",config.start_hour, ...
    "terminal_hour",config.terminal_hour, ...
    "soc_boundary_mode",char(config.soc_boundary_mode), ...
    "formal_model_soc_boundary", ...
        "full_24_hour_day_fixed_half_energy_no_interday_link", ...
    "expected_full_kkt_dimension",config.expected_full_kkt_dimension, ...
    "expected_hourly_kkt_block_dimensions", ...
        config.expected_hourly_kkt_block_dimensions, ...
    "expected_global_core_dimension",config.expected_global_core_dimension, ...
    "actual_execution_command",formalCommand, ...
    "actual_test_command","NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK", ...
    "newton_direction_count",1, ...
    "optimization_executed",false, ...
    "full_ipm_executed",false, ...
    "parallel_executed",false, ...
    "a1_solver_executed",false, ...
    "physical_dispatch_interpretation",false);
runContext = create_run_context(projectRoot,"stage_A1", ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",config.source_paths.stage, ...
    "ManifestMetadata",metadata);
testCommand = "run_stage_A1_tests('EvidenceDirectory','" + ...
    replace(string(runContext.tests_dir),"'","''") + ...
    "','CommandText','" + replace(string(formalCommand),"'","''") + "')";

acceptance = table();
issues = new_stage_a1_issue_log();
stagingRoot = "";
try
    environmentArtifact = addvars(environment, ...
        repmat(string(runContext.run_id),height(environment),1), ...
        'Before',1,'NewVariableNames','run_id');
    inputArtifact = input_hash_table(inputHashes,runContext.run_id);
    write_new_table(runContext.environment_csv_path,environmentArtifact);
    write_new_table(runContext.input_hashes_csv_path,inputArtifact);

    if ~solverWillExecute
        [acceptance,issues] = persist_external_block( ...
            projectRoot,runContext,environment,inputHashes,issues);
        finalStatus = aggregate_stage_a1_status(acceptance);
        blockedException = MException("stageA1:external:Blocked", ...
            "A1 solver was not executed because the external preflight did not pass.");
        failureReport = generate_stage_a1_failure_report( ...
            runContext,blockedException,issues,acceptance);
        externalEvidence = write_stage_a1_evidence_hashes(runContext,struct());
        externalHashPath = fullfile(runContext.acceptance_dir, ...
            "evidence_hashes.csv");
        finalize_run_manifest(runContext,finalStatus,struct( ...
            "blocking_acceptance_total",height(acceptance), ...
            "blocking_acceptance_pass",sum(acceptance.status=="PASS"), ...
            "evidence_hashes","acceptance/evidence_hashes.csv", ...
            "evidence_hashes_sha256",compute_sha256_file(externalHashPath), ...
            "evidence_file_count",height(externalEvidence), ...
            "reports",struct("failure",relative_run_path( ...
                failureReport,runContext.root)), ...
            "first_failed_layer","external_preflight"));
        result = struct("run_id",string(runContext.run_id), ...
            "run_path",string(runContext.root),"status",finalStatus, ...
            "acceptance",acceptance,"issues",issues);
        return
    end

    data = load_project_data(projectRoot);
    record_stage_a1_test_command(runContext,testCommand);
    tests = run_stage_A1_tests('EvidenceDirectory',runContext.tests_dir, ...
        'CommandText',testCommand);
    testAudit = summarize_tests(tests);

    index = build_stage_a1_index(data,"RunId",string(runContext.run_id));
    mark_stage_a1_solver_execution(runContext);
    verification = run_stage_a1_direction_verification(data,index,config);
    codeScan = scan_stage_a1_forbidden_code(projectRoot,config);
    exported = export_stage_a1_artifacts(runContext,data,index,config, ...
        verification.linearization,verification.direct, ...
        verification.recursive,verification.audit, ...
        Environment=environmentArtifact,Tests=tests.summary,CodeScan=codeScan);

    acceptance = evaluate_stage_a1_acceptance_facts(projectRoot, ...
        environment,inputHashes,data,index,verification,codeScan,testAudit);
    otherRows = acceptance.test_id ~= "SA1-ART-001";
    if any(acceptance.status(otherRows)~="PASS")
        raise_first_acceptance_failure(acceptance,verification);
    end
    numericalArtifactsPass = all(exported.artifact_hashes.status=="PASS") && ...
        all_required_test_evidence_exists(tests.paths) && tests.all_pass;
    if ~numericalArtifactsPass
        error("stageA1:acceptance:ArtifactPrerequisite", ...
            ["test_id 'SA1-ART-001'; layer 'artifact_export'; " ...
            "object 'numerical and test evidence'; required artifacts are incomplete"]);
    end
    write_new_table(runContext.issue_log_path,issues);
    smokeReportCount = validate_report_smoke(runContext,acceptance);
    acceptance = set_stage_a1_acceptance_result(acceptance, ...
        "SA1-ART-001","PASS", ...
        "tests="+tests.summary.test_passed+"/"+tests.summary.test_total+ ...
        "; numerical_hashes="+height(exported.artifact_hashes)+ ...
        "; validated_report_smoke_count="+smokeReportCount, ...
        "all numerical/test evidence passed and three artifact-backed DOCX packages were staged and validated in an isolated clone", ...
        "matrices/numerical_artifact_hashes.csv; tests; reports");
    write_new_table(runContext.acceptance_results_path,acceptance);
    finalStatusCandidate = aggregate_stage_a1_status(acceptance);
    assert(finalStatusCandidate=="PASS", ...
        "stageA1:acceptance:CandidateNotPass", ...
        "All Stage A1 blocking rows must pass before report staging.");

    stagingRoot = string(tempname);
    mkdir(stagingRoot);
    stagedReports = generate_stage_a1_reports(runContext, ...
        'OutputDirectory',stagingRoot, ...
        'FinalStatusCandidate',finalStatusCandidate);
    validate_report_set(stagedReports);
    reportPaths = install_staged_reports(runContext,stagedReports);
    evidenceHashes = write_stage_a1_evidence_hashes(runContext,struct());

    evidenceHashPath = fullfile(runContext.acceptance_dir,"evidence_hashes.csv");
    updates = struct( ...
        "test_total",tests.summary.test_total, ...
        "test_passed",tests.summary.test_passed, ...
        "test_failed",tests.summary.test_failed, ...
        "test_incomplete",tests.summary.test_incomplete, ...
        "full_kkt_dimension",verification.direct.kkt.dimension, ...
        "hourly_kkt_block_dimensions", ...
            [verification.recursive.partition.hour.dimension], ...
        "global_core_dimension",size(verification.recursive.core.matrix,1), ...
        "direction_relative_error", ...
            verification.audit.direction_relative_error, ...
        "recursive_full_kkt_relative_residual", ...
            verification.audit.recursive_kkt_relative_residual, ...
        "direct_full_kkt_relative_residual", ...
            verification.audit.full_kkt_relative_residual, ...
        "fixed_zero_count",verification.physical.fixed_zero_audit.count, ...
        "fixed_zero_exact", ...
            verification.physical.fixed_zero_audit.values_exact_zero && ...
            verification.physical.fixed_zero_audit.directions_exact_zero, ...
        "linearization_identity",char(verification.linearization.identity), ...
        "blocking_acceptance_total",height(acceptance), ...
        "blocking_acceptance_pass",sum(acceptance.status=="PASS"), ...
        "numerical_artifact_hashes", ...
            "matrices/numerical_artifact_hashes.csv", ...
        "evidence_hashes","acceptance/evidence_hashes.csv", ...
        "evidence_hashes_sha256",compute_sha256_file(evidenceHashPath), ...
        "evidence_file_count",height(evidenceHashes), ...
        "reports",relative_report_paths(reportPaths), ...
        "first_failed_layer","none");
    cleanup_staging(stagingRoot);
    stagingRoot = "";
    result = struct("run_id",string(runContext.run_id), ...
        "run_path",string(runContext.root),"status","PASS", ...
        "acceptance",acceptance,"issues",issues,"tests",tests, ...
        "verification",verification,"exported",exported, ...
        "evidence_hashes",evidenceHashes,"reports",reportPaths);
    result.manifest = finalize_run_manifest(runContext,"PASS",updates);
catch exception
    cleanup_staging(stagingRoot);
    preserve_stage_a1_failure(runContext,acceptance,issues,exception);
    rethrow(exception);
end
end

function assert_stage_a1_preflight(projectRoot)
current = string(fileread(fullfile(projectRoot,"CURRENT_STAGE.md")));
assert(contains(current,"`stage_id`: `stage_A1`") && ...
    contains(current,"`status`: `READY`"), ...
    "stageA1:gate:CurrentStage","CURRENT_STAGE must be stage_A1 / READY.");
[status,branch] = git_command(projectRoot,"branch --show-current");
assert(status==0 && strip(string(branch))=="stage_A1", ...
    "stageA1:gate:Branch","Formal A1 execution requires branch stage_A1.");
[status,tracked] = git_command(projectRoot,"status --porcelain --untracked-files=no");
assert(status==0 && strlength(strip(string(tracked)))==0, ...
    "stageA1:gate:TrackedChanges", ...
    "Formal A1 execution requires no uncommitted tracked changes.");
[status,worktree] = git_command(projectRoot, ...
    "status --porcelain --untracked-files=normal");
assert(status==0,"stageA1:gate:GitStatus", ...
    "Could not inspect untracked files before formal execution.");
lines = splitlines(string(worktree));
lines = lines(strlength(strip(lines))>0);
allowed = ["?? runs/20260718_163832_stage_0_9e12222e.zip"; ...
    "?? runs/20260719_150810_stage_0_6591d873/"];
unknown = lines(~ismember(strip(lines),allowed));
assert(isempty(unknown),"stageA1:gate:UnknownUntracked", ...
    "Unknown untracked content exists before formal A1 run: %s", ...
    strjoin(unknown,"; "));
assert(isfolder(fullfile(projectRoot,"runs", ...
    "20260719_150810_stage_0_6591d873")), ...
    "stageA1:gate:Stage0EvidenceRun", ...
    "The known untracked Stage 0 evidence run is missing.");
zipPath = fullfile(projectRoot,"runs", ...
    "20260718_163832_stage_0_9e12222e.zip");
expectedZip = "B44576FD8F20C94F79E631A8D286D709CE4C9D41FEAFB724FA7DD01010FE78D7";
assert(isfile(zipPath) && upper(string(compute_sha256_file(zipPath)))==expectedZip, ...
    "stageA1:gate:ProtectedZip", ...
    "The protected Stage 0 ZIP is missing or changed.");
end

function [status,output] = git_command(projectRoot,arguments)
root = replace(string(projectRoot),'\','/');
command = "git -c safe.directory=" + root + " " + string(arguments);
[status,output] = system(char(command));
end

function value = input_hash_object(hashes)
value = struct();
for k = 1:height(hashes)
    name = string(hashes.fileName(k));
    if name == "基础参数.xlsx"
        field = "base_parameters";
    elseif name == "输入数据.xlsx"
        field = "timeseries";
    else
        field = string(matlab.lang.makeValidName(name));
    end
    value.(field) = char(string(hashes.actualSHA256(k)));
end
end

function artifact = input_hash_table(hashes,runId)
n = height(hashes);
artifact = table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    repmat(string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX')),n,1), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status','checked_at'});
end

function audit = summarize_tests(tests)
names = string(tests.results.test_name);
fixedMask = contains(names, ...
    "testSyntheticFixedZeroMappingDeletesVariableAndBothBounds");
audit = struct( ...
    "all_pass",logical(tests.all_pass), ...
    "total",tests.summary.test_total, ...
    "passed",tests.summary.test_passed, ...
    "failed",tests.summary.test_failed, ...
    "incomplete",tests.summary.test_incomplete, ...
    "fixed_zero_regression_pass",nnz(fixedMask)==1 && ...
        tests.results.passed(fixedMask) && ...
        ~tests.results.failed(fixedMask) && ...
        ~tests.results.incomplete(fixedMask));
end

function passed = all_required_test_evidence_exists(paths)
values = string(struct2cell(paths));
passed = numel(values)==6 && all(isfile(values));
end

function validate_report_set(paths)
names = fieldnames(paths);
assert(numel(names)==3,"stageA1:report:ReportCount", ...
    "Exactly three Chinese Stage A1 reports are required.");
for k = 1:numel(names)
    pathValue = paths.(names{k});
    [valid,details] = validate_docx_package(pathValue);
    assert(valid,"stageA1:report:StructureValidation", ...
        "%s",strjoin(details.errors,"; "));
end
end

function count = validate_report_smoke(context,acceptance)
cloneRoot = string(tempname(tempdir));
cleanup = onCleanup(@() cleanup_staging(cloneRoot)); %#ok<NASGU>
[copied,message] = copyfile(context.root,cloneRoot);
assert(copied,"stageA1:report:SmokeCloneFailed","%s",message);
candidate = set_stage_a1_acceptance_result(acceptance, ...
    "SA1-ART-001","PASS", ...
    "TEMPORARY_ISOLATED_REPORT_SMOKE_CANDIDATE", ...
    "not a persisted formal acceptance result", ...
    "matrices/numerical_artifact_hashes.csv; tests; reports");
candidatePath = fullfile(cloneRoot,"acceptance","acceptance_results.csv");
write_table_csv_17g(candidatePath,candidate);
cloneContext = struct("root",char(cloneRoot), ...
    "project_root",context.project_root);
outputDirectory = fullfile(cloneRoot,"_report_smoke_output");
paths = generate_stage_a1_reports(cloneContext, ...
    'OutputDirectory',outputDirectory,'FinalStatusCandidate',"PASS");
validate_report_set(paths);
count = numel(fieldnames(paths));
assert(count==3,"stageA1:report:SmokeReportCount", ...
    "The isolated report smoke test did not create three reports.");
end

function raise_first_acceptance_failure(acceptance,verification)
row = find(acceptance.status~="PASS" & ...
    acceptance.test_id~="SA1-ART-001",1,"first");
assert(~isempty(row),"stageA1:acceptance:MissingFailure", ...
    "A non-PASS acceptance row was expected.");
testId = acceptance.test_id(row);
switch testId
    case "SA1-EQ-001"
        layer = "direction_equivalence_comparison";
        object = location_text( ...
            verification.audit.maximum_direction_difference.location);
    case "SA1-EQ-002"
        layer = "full_kkt_reinsertion";
        object = location_text( ...
            verification.audit.maximum_recursive_residual.location);
    case "SA1-EQ-003"
        layer = "full_kkt_direct_solve";
        object = location_text(verification.audit.maximum_full_residual.location);
    case {"SA1-MAT-001","SA1-MAT-002","SA1-BLK-001"}
        layer = "matrix_dimension_audit";
        object = acceptance.actual_value(row);
    case "SA1-LIN-001"
        layer = "shared_linearization_identity";
        object = acceptance.actual_value(row);
    case "SA1-BND-001"
        layer = "soc_window_boundary_assembly";
        object = "day1 hours8-10 SOC equations";
    case {"SA1-IDX-001","SA1-IDX-002"}
        layer = "canonical_index_or_fixed_zero_recovery";
        object = acceptance.actual_value(row);
    case "SA1-NUM-001"
        layer = "numerical_safeguard_audit";
        object = acceptance.actual_value(row);
    otherwise
        layer = "acceptance_evaluation";
        object = acceptance.actual_value(row);
end
error("stageA1:acceptance:BlockingFailure", ...
    "test_id '%s'; layer '%s'; object '%s'; actual '%s'", ...
    testId,layer,replace(string(object),"'",""),acceptance.actual_value(row));
end

function value = location_text(location)
try
    value = string(jsonencode(location));
catch
    value = string(location);
end
end

function installed = install_staged_reports(context,staged)
installed = struct();
names = fieldnames(staged);
for k = 1:numel(names)
    source = string(staged.(names{k}));
    sourceHash = lower(string(compute_sha256_file(source)));
    [~,base,extension] = fileparts(source);
    target = string(fullfile(context.reports_dir,base+extension));
    if isfile(target) || isfolder(target)
        error("stageA1:report:TargetExists", ...
            "Refusing to overwrite report %s.",target);
    end
    [moved,message] = movefile(source,target);
    assert(moved,"stageA1:report:InstallFailed","%s",message);
    assert(lower(string(compute_sha256_file(target)))==sourceHash, ...
        "stageA1:report:InstalledHash", ...
        "Installed report hash differs for reports/%s%s.",base,extension);
    installed.(names{k}) = char(target);
end
end

function value = relative_report_paths(paths)
value = struct();
names = fieldnames(paths);
for k = 1:numel(names)
    [~,base,extension] = fileparts(paths.(names{k}));
    value.(names{k}) = char("reports/"+string(base)+string(extension));
end
end

function write_new_table(pathValue,value)
if isfile(pathValue) || isfolder(pathValue)
    error("stageA1:artifacts:TargetExists", ...
        "Refusing to overwrite %s.",pathValue);
end
write_table_csv_17g(pathValue,value);
end

function [acceptance,issues] = persist_external_block(projectRoot,context, ...
        environment,hashes,issues)
acceptance = initialize_stage_a1_acceptance(projectRoot);
envPass = all(string(environment.status(logical(environment.blocking)))=="PASS");
hashPass = height(hashes)==2 && all(string(hashes.status)=="PASS");
acceptance = set_stage_a1_acceptance_result(acceptance,"SA1-ENV-001", ...
    blocked_or_pass(envPass),"environment preflight", ...
    "blocking environment checks","environment.csv");
acceptance = set_stage_a1_acceptance_result(acceptance,"SA1-DATA-001", ...
    blocked_or_pass(hashPass),"controlled input hash preflight", ...
    "two SHA256 comparisons","input_hashes.csv");
for row = 1:height(acceptance)
    if acceptance.status(row)=="NOT_RUN"
        acceptance = set_stage_a1_acceptance_result(acceptance, ...
            acceptance.test_id(row),"BLOCKED", ...
            "not run because external preflight did not pass", ...
            "dependency blocked","environment.csv; input_hashes.csv");
    end
end
issues = append_stage_a1_issue(issues,context,"SA1-ENV-001", ...
    "external_preflight","MATLAB environment or controlled input", ...
    "A1 execution was not started","Environment or input SHA256 unavailable", ...
    "external environment or controlled input mismatch", ...
    "Restore the required environment or controlled input and create a new run", ...
    "BLOCKED","environment.csv; input_hashes.csv");
write_new_table(context.issue_log_path,issues);
write_new_table(context.acceptance_results_path,acceptance);
end

function value = blocked_or_pass(passed)
if passed, value="PASS"; else, value="BLOCKED"; end
end

function preserve_stage_a1_failure(context,acceptance,issues,exception)
hashPath = fullfile(context.acceptance_dir,"evidence_hashes.csv");
if isfile(hashPath)
    priorPath = fullfile(context.acceptance_dir, ...
        "evidence_hashes.pre_failure_candidate.csv");
    try
        if ~isfile(priorPath) && ~isfolder(priorPath)
            movefile(hashPath,priorPath);
        end
    catch
    end
end
try
    if isempty(acceptance)
        acceptance = initialize_stage_a1_acceptance(string(context.project_root));
    end
    failureId = first_failure_test_id(exception);
    if nnz(acceptance.test_id==failureId)~=1
        failureId = "SA1-ART-001";
    end
    acceptance = set_stage_a1_acceptance_result(acceptance, ...
        failureId,"FAIL",exception.message, ...
        "first failing Stage A1 layer","run_manifest.json");
    artifactRow = acceptance.test_id=="SA1-ART-001";
    if failureId~="SA1-ART-001" && acceptance.status(artifactRow)~="FAIL"
        acceptance = set_stage_a1_acceptance_result(acceptance, ...
            "SA1-ART-001","BLOCKED", ...
            "not completed after "+failureId, ...
            "dependency blocked by first failure","run_manifest.json");
    end
    for row = 1:height(acceptance)
        if acceptance.status(row)=="NOT_RUN"
            acceptance = set_stage_a1_acceptance_result(acceptance, ...
                acceptance.test_id(row),"BLOCKED", ...
                "not completed after "+failureId, ...
                "dependency blocked by first failure","run_manifest.json");
        end
    end
    write_table_csv_17g(context.acceptance_results_path,acceptance);
catch
end
try
    issues = append_stage_a1_issue(issues,context, ...
        first_failure_test_id(exception), ...
        first_failure_layer(exception),first_failure_object(exception), ...
        "Stage A1 formal run failed",exception.message, ...
        "See exception cause and persisted evidence", ...
        "Fix the first failing layer and create a new unique run", ...
        "OPEN","run_manifest.json");
    write_table_csv_17g(context.issue_log_path,issues);
catch
end
try
    generate_stage_a1_failure_report(context,exception,issues,acceptance);
catch
end
try
    if ~isfile(hashPath)
        write_stage_a1_evidence_hashes(context,struct());
    end
catch
end
try
    manifest = jsondecode(fileread(context.run_manifest_path));
    if string(manifest.status)=="RUNNING"
        updates = struct( ...
            "fatal_error_identifier",exception.identifier, ...
            "fatal_error_message",exception.message, ...
            "first_failed_layer",first_failure_layer(exception), ...
            "first_failed_object",first_failure_object(exception));
        if isfile(hashPath)
            updates.evidence_hashes = "acceptance/evidence_hashes.csv";
            updates.evidence_hashes_sha256 = compute_sha256_file(hashPath);
        end
        failureReportPath = fullfile(context.reports_dir, ...
            "阶段A1_失败与首层定位报告.docx");
        if isfile(failureReportPath)
            updates.reports = struct("failure", ...
                relative_run_path(failureReportPath,context.root));
        end
        finalize_run_manifest(context,"FAIL_RETRYABLE",updates);
    end
catch
end
end

function value = first_failure_layer(exception)
token = regexp(exception.message,"layer '([^']+)'",'tokens','once');
if isempty(token), value="execution_or_artifact"; else, value=string(token{1}); end
end

function value = first_failure_object(exception)
token = regexp(exception.message,"object '([^']*)'",'tokens','once');
if isempty(token)
    message = string(exception.message);
    hourMatch = regexp(message, ...
        "Hour \d+ failed at [^;]+; xi indices=\[[^\]]*\]; equality indices=\[[^\]]*\]; block dimension=\d+", ...
        'match','once');
    coreMatch = regexp(message, ...
        "16-by-16 core failed for q indices 1:14 and duration multiplier indices 1:2", ...
        'match','once');
    inequalityMatch = regexp(message, ...
        "Inequality elimination failed at row \d+",'match','once');
    if ~isempty(hourMatch)
        value = string(hourMatch);
    elseif ~isempty(coreMatch)
        value = string(coreMatch);
    elseif ~isempty(inequalityMatch)
        value = string(inequalityMatch);
    else
        value = string(exception.identifier);
    end
else
    value = string(token{1});
end
if ~isempty(exception.cause)
    value = value+"; cause="+string(exception.cause{1}.identifier);
end
end

function value = first_failure_test_id(exception)
token = regexp(exception.message,"test_id '([^']+)'",'tokens','once');
if isempty(token)
    if contains(string(exception.identifier),"Recursive")
        value = "SA1-EQ-002";
    elseif contains(string(exception.identifier),"FullKkt")
        value = "SA1-EQ-003";
    elseif contains(string(exception.identifier),"tests")
        value = "SA1-ART-001";
    else
        value = "SA1-ART-001";
    end
else
    value = string(token{1});
end
end

function value = relative_run_path(pathValue,runRoot)
value = char(replace(extractAfter(string(pathValue), ...
    strlength(string(runRoot))+1),'\','/'));
end

function cleanup_staging(pathValue)
if strlength(string(pathValue))>0 && isfolder(pathValue)
    try
        rmdir(pathValue,'s');
    catch
        % Temporary cleanup must never hide the original execution result.
    end
end
end
