function result = main_stage_A4_iteration24_rank_replay()
%MAIN_STAGE_A4_ITERATION24_RANK_REPLAY Persist the controlled root-cause replay.
%
% This creates one unique diagnostic run directory.  The manifest PASS
% means only that the frozen failure was reproduced and its numerical root
% cause was closed with evidence.  It does not mean Stage A4 passed, and it
% never applies a Newton update or repairs the production solver.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(projectRoot);
addpath(genpath(fullfile(projectRoot,"src")));
addpath(fullfile(projectRoot,"tests"));

preflight = rkkt.diagnostics.assert_stage_a4_3_preflight(projectRoot);
assert(preflight.passed && preflight.stage_id=="stage_A4" && ...
    preflight.stage_status=="READY", ...
    "stageA4:iter24:Preflight", ...
    "Iteration-24 diagnostic preflight did not pass.");
[inputHashes,inputPass] = rkkt.data.verify_input_hashes(projectRoot);
environment = rkkt.diagnostics.inspect_stage_a4_environment();
blocking = logical(environment.blocking);
environmentPass = all(string(environment.status(blocking))=="PASS");
assert(inputPass && environmentPass, ...
    "stageA4:iter24:BlockedExternal", ...
    "Iteration-24 replay requires the controlled inputs and MATLAB environment.");

historicalBefore = rkkt.diagnostics.snapshot_stage_a4_historical_runs(projectRoot);
commandText = ...
    "matlab -batch ""result=main_stage_A4_iteration24_rank_replay(); "+ ...
    "assert(strcmp(result.diagnostic_status,'PASS'));""";
metadata = struct( ...
    "run_purpose", ...
        "stage_a4_iteration24_ill_conditioned_thomas_root_cause_diagnostic", ...
    "milestone","A4-ITER24-RANK-REPLAY", ...
    "parent_run_id","20260728_112548_stage_A4_1f3836ca", ...
    "authority_revision",23, ...
    "attempted_iteration",24, ...
    "actual_execution_command",char(commandText), ...
    "state_update_count",0, ...
    "newton_direction_count",0, ...
    "newton_direction_attempt_count",1, ...
    "formal_a4_run_created",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "stage_b_entered",false, ...
    "complete_kkt_role","independent_audit_only", ...
    "diagnostic_unguarded_ldl_executed",true, ...
    "diagnostic_symmetric_diagonal_congruence_executed",true, ...
    "diagnostic_results_consumed_by_formal_solver",false, ...
    "repair_applied",false, ...
    "a4_pass_claimed",false);
runId = make_run_id(projectRoot,preflight.git_commit);
context = rkkt.artifacts.create_run_context(projectRoot,"stage_A4", ...
    "RunId",runId, ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",fullfile(projectRoot,"config","stage_A4_3.yaml"), ...
    "ManifestMetadata",metadata);

rkkt.artifacts.write_table_csv_17g_atomic(context.input_hashes_csv_path,inputHashes);
environment = addvars(environment, ...
    repmat(string(context.run_id),height(environment),1), ...
    'Before',1,'NewVariableNames','run_id');
rkkt.artifacts.write_table_csv_17g_atomic(context.environment_csv_path,environment);
rkkt.artifacts.write_table_csv_17g_atomic( ...
    fullfile(context.root,"historical_runs_before.csv"),historicalBefore);
diagnosticsDirectory = fullfile(context.root,"diagnostics");
ensure_directory(diagnosticsDirectory);
consolePath = fullfile(diagnosticsDirectory,"matlab_console.log");
diary(consolePath);
diaryGuard = onCleanup(@()diary("off"));

try
    fprintf("A4 iteration-24 controlled replay run_id=%s\n",context.run_id);
    diagnostic = rkkt.diagnostics.diagnose_stage_a4_iteration24_rank_failure(projectRoot);
    exported = rkkt.artifacts.export_stage_a4_iteration24_rank_replay( ...
        context,diagnostic,CommandText=commandText);

    testCommand = ...
        "matlab -batch ""addpath('tests'); evidence="+ ...
        "run_stage_A4_ITER24_rank_replay_tests(); "+ ...
        "assert(evidence.all_pass);""";
    testEvidence = run_stage_A4_ITER24_rank_replay_tests( ...
        EvidenceDirectory=string(context.tests_dir), ...
        CommandText=testCommand);
    [reportPath,reportValidation] = ...
        rkkt.reporting.generate_stage_a4_iteration24_rank_report(context);
    historicalAudit = rkkt.diagnostics.compare_stage_a4_historical_runs( ...
        projectRoot,historicalBefore,string(context.run_id));
    rkkt.artifacts.write_json_file(fullfile(context.root, ...
        "historical_runs_audit.json"),historicalAudit);

    clear diaryGuard
    hashes = write_evidence_hash_manifest(context);
    tests = testEvidence.summary;
    updates = struct( ...
        "diagnostic_status","PASS", ...
        "stage_a4_status","READY", ...
        "a4_pass_claimed",false, ...
        "root_cause_classification", ...
            char(diagnostic.root_cause.classification), ...
        "root_cause_title",char(diagnostic.root_cause.title), ...
        "production_failure_reproduced",true, ...
        "structural_rank_deficiency_rejected",true, ...
        "hour3_numeric_rank", ...
            double(exported.summary.hour3_numeric_rank), ...
        "hour3_dimension",double(exported.summary.hour3_dimension), ...
        "hour3_condition_2", ...
            double(exported.summary.hour3_condition_2), ...
        "hour3_singular_values_below_rank_tolerance", ...
            double(exported.summary. ...
            hour3_singular_values_below_rank_tolerance), ...
        "high_precision_full_rank", ...
            logical(exported.summary.high_precision_full_rank), ...
        "diagnostic_scaled_rank", ...
            double(exported.summary.scaled_counterfactual_rank), ...
        "diagnostic_scaled_condition_2", ...
            double(exported.summary.scaled_counterfactual_condition_2), ...
        "full_kkt_audit_relative_residual", ...
            double(exported.summary.full_kkt_relative_residual), ...
        "full_kkt_direction_consumed",false, ...
        "state_update_count_observed",0, ...
        "repair_applied",false, ...
        "test_total",double(tests.test_total), ...
        "test_passed",double(tests.test_passed), ...
        "test_failed",double(tests.test_failed), ...
        "test_incomplete",double(tests.test_incomplete), ...
        "report_path",relative_path(context.root,reportPath), ...
        "report_structure_validated",isempty(reportValidation.errors), ...
        "historical_runs_unchanged",historicalAudit.passed, ...
        "evidence_sha256_manifest", ...
            "acceptance/evidence_sha256.csv", ...
        "evidence_sha256_manifest_sha256", ...
            char(rkkt.data.compute_sha256_file(hashes.path)), ...
        "evidence_file_count",height(hashes.table), ...
        "next_action", ...
            "separately authorize and test a unified local symmetric "+ ...
            "diagonal congruence repair; do not resume formal A4 yet");
    finalManifest = rkkt.artifacts.finalize_run_manifest(context,"PASS",updates);
    result = struct( ...
        "run_id",string(context.run_id), ...
        "run_path",string(context.root), ...
        "diagnostic_status","PASS", ...
        "manifest_status",string(finalManifest.status), ...
        "root_cause",diagnostic.root_cause, ...
        "summary",exported.summary, ...
        "test_summary",tests, ...
        "report_path",string(reportPath), ...
        "evidence_sha256_path",string(hashes.path), ...
        "stage_status","READY", ...
        "stage_a4_pass_claimed",false, ...
        "repair_applied",false, ...
        "state_update_count",0);
    print_summary(result);
catch cause
    clear diaryGuard
    preserve_failure(context,cause);
    rethrow(cause)
end
end

function hashes = write_evidence_hash_manifest(context)
target = fullfile(context.acceptance_dir,"evidence_sha256.csv");
assert(~isfile(target)&&~isfolder(target), ...
    "stageA4:iter24:EvidenceHashExists", ...
    "Refusing to overwrite %s.",target);
entries = dir(fullfile(context.root,"**","*"));
entries = entries(~[entries.isdir]);
absolute = strings(0,1);
relative = strings(0,1);
for k=1:numel(entries)
    pathValue = string(fullfile(entries(k).folder,entries(k).name));
    rel = relative_path(context.root,pathValue);
    if rel=="run_manifest.json" || ...
            rel=="acceptance/evidence_sha256.csv"
        continue
    end
    absolute(end+1,1)=pathValue; %#ok<AGROW>
    relative(end+1,1)=rel; %#ok<AGROW>
end
[relative,order]=sort(relative);
absolute=absolute(order);
sha256=strings(numel(absolute),1);
bytes=zeros(numel(absolute),1);
for k=1:numel(absolute)
    sha256(k)=rkkt.data.compute_sha256_file(absolute(k));
    info=dir(absolute(k)); bytes(k)=info.bytes;
end
tableValue=table(relative,bytes,sha256, ...
    'VariableNames',{'relative_path','bytes','sha256'});
rkkt.artifacts.write_table_csv_17g_atomic(target,tableValue);
hashes=struct("path",string(target),"table",tableValue);
end

function preserve_failure(context,cause)
try
    failurePath=fullfile(context.issues_dir,"diagnostic_failure.json");
    if ~isfile(failurePath)&&~isfolder(failurePath)
        value=struct("identifier",cause.identifier, ...
            "message",cause.message, ...
            "report",getReport(cause,"extended","hyperlinks","off"));
        rkkt.artifacts.write_json_file(failurePath,value);
    end
    manifest=jsondecode(fileread(context.run_manifest_path));
    if string(manifest.status)=="RUNNING"
        rkkt.artifacts.finalize_run_manifest(context,"FAIL_RETRYABLE",struct( ...
            "diagnostic_status","FAIL_RETRYABLE", ...
            "stage_a4_status","READY", ...
            "a4_pass_claimed",false, ...
            "failure_identifier",cause.identifier, ...
            "failure_message",cause.message, ...
            "state_update_count_observed",0, ...
            "repair_applied",false));
    end
catch
    % Preserve the original exception and every partial artifact.
end
end

function print_summary(result)
s=result.summary;
fprintf("A4 iteration-24 replay run_id=%s status=%s\n", ...
    result.run_id,result.diagnostic_status);
fprintf("hour3 rank=%d/%d cond2=%.17g; hp_full_rank=%d\n", ...
    s.hour3_numeric_rank,s.hour3_dimension,s.hour3_condition_2, ...
    s.high_precision_full_rank);
fprintf("scaled diagnostic rank=%d cond2=%.17g; full_kkt=%.17g\n", ...
    s.scaled_counterfactual_rank,s.scaled_counterfactual_condition_2, ...
    s.full_kkt_relative_residual);
fprintf("Stage A4 remains READY; state updates=0; repair applied=0.\n");
end

function value=input_hash_object(inputHashes)
value=struct( ...
    "base_parameters",char(string(inputHashes.actualSHA256(1))), ...
    "timeseries",char(string(inputHashes.actualSHA256(2))));
end

function value=relative_path(root,pathValue)
value=replace(erase(string(pathValue),string(root)+filesep),"\","/");
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message]=mkdir(pathValue);
assert(created,"stageA4:iter24:DirectoryCreate", ...
    "Could not create %s: %s",pathValue,message);
end

function runId=make_run_id(root,commit)
stamp=string(datetime("now","TimeZone","Asia/Shanghai", ...
    "Format","yyyyMMdd_HHmmss"));
base=stamp+"_stage_A4_ITER24_REPLAY_"+extractBefore(commit,9);
runId=base;
suffix=1;
while isfolder(fullfile(root,"runs",runId)) || ...
        isfile(fullfile(root,"runs",runId))
    suffix=suffix+1;
    runId=base+"_"+compose("%03d",suffix);
end
end
