function result = main_PKG_1(projectRoot)
%MAIN_PKG_1 Verify the PKG-1 package skeleton and contract infrastructure.
%   This auxiliary engineering run does not load optimization inputs,
%   assemble a model, compute a Newton direction, or update an IPM state.

arguments
    projectRoot (1,1) string = string(fileparts(mfilename("fullpath")))
end

sourceRoot = fullfile(projectRoot,"src");
addpath(sourceRoot);
addpath(fullfile(sourceRoot,"artifacts"));
addpath(fullfile(sourceRoot,"data"));
addpath(fullfile(sourceRoot,"testing"));
addpath(fullfile(projectRoot,"tests"));

designPaths = [
    fullfile(projectRoot,"docs","PKG-00_包接口重构路线与边界_v1.0.md")
    fullfile(projectRoot,"docs","PKG-02_公共接口数据合同_v1.0.md")
    fullfile(projectRoot,"docs","PKG-03_包依赖方向与命名规则_v1.0.md")
    ];
for k = 1:numel(designPaths)
    assert(isfile(designPaths(k)),"rkkt:pkg1:DesignFileMissing", ...
        "PKG-1 design input is missing: %s",designPaths(k));
end
designHashes = strings(numel(designPaths),1);
for k = 1:numel(designPaths)
    designHashes(k) = rkkt.data.compute_sha256_file(designPaths(k));
end
inputHashes = struct( ...
    "pkg_00_route",designHashes(1), ...
    "pkg_02_contract",designHashes(2), ...
    "pkg_03_dependencies",designHashes(3));
metadata = struct( ...
    "run_purpose","pkg_1_package_skeleton_and_contract_infrastructure", ...
    "formal_project_stage","stage_A4_READY_unchanged", ...
    "actual_test_command","main_PKG_1()", ...
    "optimization_executed",false, ...
    "production_algorithm_migrated",false);
context = rkkt.artifacts.create_run_context(projectRoot,"PKG-1", ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",inputHashes, ...
    "ManifestMetadata",metadata);

commandText = "main_PKG_1("""+projectRoot+""")";
try
    write_static_run_evidence(context,designPaths,designHashes);
    evidence = run_PKG_1_tests( ...
        "EvidenceDirectory",string(context.tests_dir), ...
        "CommandText",commandText);
    packageInfo = rkkt.info();
    acceptance = make_acceptance(evidence,true,"");
    rkkt.artifacts.write_table_csv_17g(context.acceptance_results_path,acceptance);
    result = struct( ...
        "run_id",string(context.run_id), ...
        "run_root",string(context.root), ...
        "package_info",packageInfo, ...
        "test_summary",evidence.summary, ...
        "acceptance",acceptance, ...
        "optimization_executed",false, ...
        "production_algorithm_migrated",false);
    save(fullfile(context.root,"pkg1_result.mat"),"result","-v7");
    rkkt.artifacts.finalize_run_manifest(context,"PASS",struct( ...
        "pkg_stage_status","READY_FOR_USER_REVIEW", ...
        "package_version",packageInfo.package_version, ...
        "contract_version",packageInfo.contract_version, ...
        "test_total",evidence.summary.test_total, ...
        "test_passed",evidence.summary.test_passed));
catch cause
    acceptance = make_acceptance(struct(),false, ...
        string(cause.identifier)+": "+string(cause.message));
    if ~isfile(context.acceptance_results_path)
        rkkt.artifacts.write_table_csv_17g(context.acceptance_results_path,acceptance);
    end
    result = struct( ...
        "run_id",string(context.run_id), ...
        "run_root",string(context.root), ...
        "error_identifier",string(cause.identifier), ...
        "error_message",string(cause.message), ...
        "acceptance",acceptance, ...
        "optimization_executed",false, ...
        "production_algorithm_migrated",false);
    save(fullfile(context.root,"pkg1_result.mat"),"result","-v7");
    try
        rkkt.artifacts.finalize_run_manifest(context,"FAIL_RETRYABLE",struct( ...
            "pkg_stage_status","IMPLEMENTATION_FAILED"));
    catch finalizationCause
        warning("rkkt:pkg1:ManifestFinalizationFailed", ...
            "Could not finalize failed PKG-1 run: %s", ...
            finalizationCause.message);
    end
    rethrow(cause)
end
end

function write_static_run_evidence(context,designPaths,designHashes)
relative_path = [
    "docs/PKG-00_包接口重构路线与边界_v1.0.md"
    "docs/PKG-02_公共接口数据合同_v1.0.md"
    "docs/PKG-03_包依赖方向与命名规则_v1.0.md"
    ];
bytes = zeros(numel(designPaths),1);
for k = 1:numel(designPaths)
    information = dir(designPaths(k));
    bytes(k) = information.bytes;
end
rkkt.artifacts.write_table_csv_17g(context.input_hashes_csv_path, ...
    table(relative_path,designHashes,bytes, ...
    'VariableNames',["relative_path","sha256","bytes"]));
check_id = ["MATLAB_VERSION";"COMPUTER";"PACKAGE_PATH_MODE"];
actual_value = [string(version);string(computer); ...
    "src root plus explicit legacy test utilities"];
status = repmat("RECORDED",numel(check_id),1);
rkkt.artifacts.write_table_csv_17g(context.environment_csv_path, ...
    table(check_id,actual_value,status));
end

function value = make_acceptance(evidence,passed,details)
test_id = ["PKG1-STRUCT-001";"PKG1-CONTRACT-001"; ...
    "PKG1-BOUNDARY-001"];
requirement = [
    "MATLAB可解析+rkkt骨架与全部计划命名空间"
    "公共合同与moduleResult固定测试通过"
    "未加载模型、未运行优化、未迁移生产算法"
    ];
threshold = repmat("PASS",3,1);
blocking = true(3,1);
if passed
    status = repmat("PASS",3,1);
    actual_value = [
        "15个包目录已建立，src根路径可解析"
        string(evidence.summary.test_passed)+"/"+ ...
            string(evidence.summary.test_total)+"通过"
        "optimization_executed=false; production_algorithm_migrated=false"
        ];
else
    status = repmat("FAIL_RETRYABLE",3,1);
    actual_value = repmat(details,3,1);
end
value = table(test_id,requirement,threshold,blocking,status,actual_value);
end
