function result = main_stage_A4_2C()
%MAIN_STAGE_A4_2C Execute the non-formal five-round controlled A/B audit.
%
% Chain A uses the frozen independent primal/dual steps. Chain B uses the
% experimental common minimum step. Both chains independently initialize,
% rebuild, solve, audit, and update for exactly five rounds. No formal run
% or stage transition is created.

projectRoot = string(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));
config = load_stage_a4_configuration(projectRoot);
data = load_project_data(projectRoot);
indexA = build_stage_a4_index(data,"RunId","A4_2C_CHAIN_A_INDEX");
indexB = build_stage_a4_index(data,"RunId","A4_2C_CHAIN_B_INDEX");
result = run_stage_a4_step_strategy_ab_diagnostic( ...
    data,indexA,indexB,config);
assert(result.all_pass && result.milestone_status=="PASS" && ...
    result.stage_status=="READY" && ...
    result.execution.chain_count==2 && ...
    result.execution.iterations_per_chain==5 && ...
    result.execution.newton_direction_count==10 && ...
    result.execution.full_kkt_audit_count==10 && ...
    ~result.convergence_claimed && ~result.formal_step_rule_replaced && ...
    ~result.execution.full_ipm_executed && ...
    ~result.execution.optimization_executed && ...
    ~result.execution.parallel_executed && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.stage_b_entered, ...
    "stageA4:a42c:MainContract", ...
    "A4-2C did not satisfy its isolated five-round A/B contract.");
print_comparison(result);
end

function print_comparison(result)
fprintf(['A4-2C controlled A/B comparison; stage=%s; ' ...
    'formal_rule_replaced=%d\n'],result.stage_status, ...
    result.formal_step_rule_replaced);
disp(result.chain_summary);
fprintf('A4-2C residual/gap comparison against initial state and peer chain:\n');
disp(result.residual_gap_comparison);
fprintf('A4-2C investment objective and 14-capacity history:\n');
disp(result.capacity_history);
fprintf('A4-2C l*z centrality statistics:\n');
disp(result.centrality_statistics);
fprintf('A4-2C r_ineq/r_comp overall scale statistics:\n');
disp(result.residual_scale_statistics);
fprintf(['A4-2C constraint-family scale rows=%d; all available in ' ...
    'result.inequality_family_scale_statistics.\n'], ...
    height(result.inequality_family_scale_statistics));
end
