function moduleResult = runLinearization(options)
%RUNLINEARIZATION Validate the shared A4 linearization from the state MAT.
%   The caller state is read from 状态模块输出.mat and passed explicitly to
%   both the legacy production entry and rkkt.model.linearize.

arguments
    options.InputArtifact (1,1) string = default_input_artifact()
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = default_output_directory()
end

inputArtifact = string(options.InputArtifact);
outputDirectory = string(options.OutputDirectory);
rkkt.model.validation.ValidationSupport.requireOutputDirectory( ...
    outputDirectory,options.WriteArtifacts);

upstream = rkkt.model.validation.ValidationSupport.loadResult( ...
    inputArtifact,"runLinearization");
if string(upstream.meta.interface_name) ~= "rkkt.model.initialize"
    error("rkkt:model:validation:LinearizationUpstreamInterface", ...
        "runLinearization requires the rkkt.model.initialize artifact.");
end
rkkt.contracts.requireFields(upstream.input, ...
    ["projectData";"index";"config"], ...
    "runLinearization upstream.input");
rkkt.contracts.requireFields(upstream.output,"state", ...
    "runLinearization upstream.output");
data = upstream.input.projectData;
index = upstream.input.index;
config = upstream.input.config;
state = upstream.output.state;

legacyLinearization = call_legacy_linearization( ...
    state,data,index,config);
linearization = rkkt.model.linearize(state,data,index,config);
legacyFacadeExact = isequaln(legacyLinearization,linearization);
facts = inspect_linearization_facts( ...
    linearization,state,index,legacyFacadeExact);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:model:validation:LinearizationFacts", ...
        "One or more objective linearization observations are false.");
end

fieldSummary = linearization_summary(linearization);
residualSummary = residual_summary(linearization);
[outputFile,tableFiles,figureFiles,figureIndex] = output_paths( ...
    outputDirectory,options.WriteArtifacts);
metadata = rkkt.model.validation.ValidationSupport.metadata( ...
    "rkkt.model.linearize","build_stage_a4_linearization", ...
    inputArtifact,string(data.projectRoot),outputFile, ...
    "统一线性化模块",state.iteration_index,state.state_revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "state",state, ...
    "projectData",data, ...
    "index",index, ...
    "config",config, ...
    "upstreamMetadata",upstream.meta, ...
    "inputArtifact",inputArtifact);
moduleResult.output = struct("linearization",linearization);
moduleResult.intermediate = struct( ...
    "fieldSummary",fieldSummary, ...
    "residualSummary",residualSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "explicit_state_exact_equal",isequaln(linearization.state,state), ...
    "identity",string(linearization.identity), ...
    "objective_facts",facts, ...
    "matrix_nonzeros",[nnz(linearization.H), ...
        nnz(linearization.A),nnz(linearization.G)], ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "identity","唯一A4线性化身份，含iteration和revision", ...
    "matrix_order","H/A/G沿canonical xi/equality/inequality顺序", ...
    "residual_order","r_dual/r_eq/r_ineq/r_comp来自同一对象", ...
    "state_semantics","显式调用者state，未重新初始化");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.model.validation.ValidationSupport.writeTable17( ...
        fieldSummary,tableFiles(1));
    rkkt.model.validation.ValidationSupport.writeTable17( ...
        residualSummary,tableFiles(2));
    fig = sparsity_figure(linearization,options.Interactive);
    rkkt.model.validation.ValidationSupport.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.model.validation.ValidationSupport.saveResult( ...
        outputFile,moduleResult);
end

fprintf("当前模块：统一线性化模块\n");
fprintf("公共接口：rkkt.model.linearize\n");
fprintf("正式生产函数：build_stage_a4_linearization\n");
fprintf("新旧线性化严格相同：%d\n",legacyFacadeExact);
fprintf("linearization.state与传入state严格相同：%d\n", ...
    isequaln(linearization.state,state));
fprintf("identity：%s\n",linearization.identity);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function value = call_legacy_linearization(state,data,index,config)
modelDirectory = fullfile(string(data.projectRoot),"src","model");
productionFile = fullfile(modelDirectory, ...
    "build_stage_a4_linearization.m");
originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(modelDirectory,"-begin");
resolved = string(which("build_stage_a4_linearization"));
if ~same_path(resolved,productionFile)
    error("rkkt:model:validation:LinearizationFunctionShadowed", ...
        "Expected build_stage_a4_linearization at '%s'; resolved '%s'.", ...
        productionFile,resolved);
end
value = build_stage_a4_linearization(state,data,index,config);
clear pathGuard
end

function facts = inspect_linearization_facts( ...
        linearization,state,index,legacyFacadeExact)
required = [ ...
    "identity"
    "version"
    "stage_id"
    "state"
    "jacobian"
    "hessian"
    "H"
    "A"
    "G"
    "r_dual"
    "r_eq"
    "r_ineq"
    "r_comp"
    "l"
    "z"
    "mu"
    "explicit_slack_consumed"];
types = string(index.constraint_index.constraint_type);
nPrimal = height(index.variable_index);
nEquality = nnz(types == "equality");
nInequality = nnz(types == "inequality");
facts = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "required_fields_present", ...
        all(ismember(required,string(fieldnames(linearization)))), ...
    "stage_a4_exact",string(linearization.stage_id) == "stage_A4" && ...
        startsWith(string(linearization.identity), ...
            "stageA4-linearization-"), ...
    "explicit_state_exact_equal", ...
        isequaln(linearization.state,state), ...
    "explicit_slack_consumed", ...
        logical(linearization.explicit_slack_consumed), ...
    "matrix_dimensions_closed", ...
        isequal(size(linearization.H),[nPrimal,nPrimal]) && ...
        isequal(size(linearization.A),[nEquality,nPrimal]) && ...
        isequal(size(linearization.G),[nInequality,nPrimal]), ...
    "matrix_storage_sparse", ...
        issparse(linearization.H) && ...
        issparse(linearization.A) && ...
        issparse(linearization.G), ...
    "matrix_aliases_exact", ...
        isequaln(linearization.jacobian.A,linearization.A) && ...
        isequaln(linearization.jacobian.G,linearization.G) && ...
        isequaln(linearization.hessian.H,linearization.H), ...
    "residual_dimensions_closed", ...
        numel(linearization.r_dual) == nPrimal && ...
        numel(linearization.r_eq) == nEquality && ...
        numel(linearization.r_ineq) == nInequality && ...
        numel(linearization.r_comp) == nInequality && ...
        numel(linearization.l) == nInequality && ...
        numel(linearization.z) == nInequality, ...
    "slack_multiplier_finite_positive", ...
        all(isfinite(linearization.l)) && ...
        all(linearization.l > 0) && ...
        all(isfinite(linearization.z)) && ...
        all(linearization.z > 0) && ...
        isfinite(linearization.mu) && linearization.mu > 0);
end

function value = linearization_summary(linearization)
objectName = ["H";"A";"G";"r_dual";"r_eq";"r_ineq"; ...
    "r_comp";"l";"z";"mu"];
objects = {linearization.H;linearization.A;linearization.G; ...
    linearization.r_dual;linearization.r_eq; ...
    linearization.r_ineq;linearization.r_comp; ...
    linearization.l;linearization.z;linearization.mu};
n = numel(objects);
className = strings(n,1);
rowCount = zeros(n,1);
columnCount = zeros(n,1);
elementCount = zeros(n,1);
nonzeroCount = zeros(n,1);
sparseStorage = false(n,1);
for k = 1:n
    object = objects{k};
    className(k) = string(class(object));
    rowCount(k) = size(object,1);
    columnCount(k) = size(object,2);
    elementCount(k) = numel(object);
    nonzeroCount(k) = nnz(object);
    sparseStorage(k) = issparse(object);
end
value = table(objectName,className,rowCount,columnCount, ...
    elementCount,nonzeroCount,sparseStorage);
end

function value = residual_summary(linearization)
component = ["r_dual";"r_eq";"r_ineq";"r_comp"];
vectors = {linearization.r_dual;linearization.r_eq; ...
    linearization.r_ineq;linearization.r_comp};
n = numel(vectors);
elementCount = zeros(n,1);
norm2 = zeros(n,1);
normInf = zeros(n,1);
minimum = zeros(n,1);
maximum = zeros(n,1);
for k = 1:n
    vector = vectors{k};
    elementCount(k) = numel(vector);
    norm2(k) = norm(vector,2);
    normInf(k) = norm(vector,inf);
    minimum(k) = min(vector,[],"all");
    maximum(k) = max(vector,[],"all");
end
value = table(component,elementCount,norm2,normInf,minimum,maximum);
end

function fig = sparsity_figure(linearization,interactive)
visibility = "off";
if interactive
    visibility = "on";
end
fig = figure("Name","统一线性化：H_A_G稀疏结构", ...
    "NumberTitle","off","Color","w","Visible",visibility, ...
    "Position",[100,100,1260,620]);
layout = tiledlayout(fig,1,3,"TileSpacing","compact");
nexttile(layout);
spy(linearization.H);
title(compose("H：%d×%d，nnz=%d", ...
    size(linearization.H,1),size(linearization.H,2), ...
    nnz(linearization.H)));
nexttile(layout);
spy(linearization.A);
title(compose("A：%d×%d，nnz=%d", ...
    size(linearization.A,1),size(linearization.A,2), ...
    nnz(linearization.A)));
nexttile(layout);
spy(linearization.G);
title(compose("G：%d×%d，nnz=%d", ...
    size(linearization.G,1),size(linearization.G,2), ...
    nnz(linearization.G)));
end

function [outputFile,tableFiles,figureFiles,index] = ...
        output_paths(outputDirectory,writeArtifacts)
if writeArtifacts
    outputFile = fullfile(outputDirectory,"统一线性化模块输出.mat");
    tableFiles = [ ...
        fullfile(outputDirectory,"线性化字段维数.csv")
        fullfile(outputDirectory,"初始残差范数.csv")];
    figPath = fullfile(outputDirectory,"H_A_G稀疏结构.fig");
    pngPath = fullfile(outputDirectory,"H_A_G稀疏结构.png");
    figureFiles = [figPath;pngPath];
else
    outputFile = "";
    tableFiles = strings(0,1);
    figPath = "";
    pngPath = "";
    figureFiles = strings(0,1);
end
tableFiles = reshape(string(tableFiles),[],1);
figureFiles = reshape(string(figureFiles),[],1);
index = struct("figPath",string(figPath),"pngPath",string(pngPath));
end

function value = default_input_artifact()
value = fullfile(default_output_directory(),"状态模块输出.mat");
end

function value = default_output_directory()
value = string(fileparts(mfilename("fullpath")));
end

function value = same_path(left,right)
left = replace(string(left),"/","\");
right = replace(string(right),"/","\");
if ispc
    value = strcmpi(left,right);
else
    value = strcmp(left,right);
end
end
