function moduleResult = runStageB2A(options)
%RUNSTAGEB2A Observe one explicit Stage B-2A model assembly chain.
%   The chain is data -> B-2A index -> B-2A state -> B-2A
%   linearization. It does not assemble or solve a KKT system and never
%   updates the returned state.

arguments
    options.ProjectRoot (1,1) string = default_project_root()
    options.Interactive (1,1) logical = false
    options.WriteArtifacts (1,1) logical = false
    options.OutputDirectory (1,1) string = default_output_directory()
end

projectRoot = strip(options.ProjectRoot);
outputDirectory = strip(options.OutputDirectory);
require_inputs(projectRoot,outputDirectory,options.WriteArtifacts);

data = rkkt.data.load(projectRoot);
config = call_configuration(projectRoot);
index = rkkt.indexing.buildStageB2A(data,config, ...
    "RunId","PKG9_STAGE_B2A_MODEL_VALIDATION");
state = rkkt.model.initializeStageB2A(data,index,config);
linearization = rkkt.model.linearizeStageB2A( ...
    state,data,index,config);
summary = linearization_summary(linearization);
facts = inspect_chain(index,state,linearization);
if ~all(structfun(@logical,facts))
    error("rkkt:model:validation:StageB2AChainFacts", ...
        "The Stage B-2A model-chain observations are inconsistent.");
end
[outputFile,tableFiles,figureFiles,figureIndex] = output_paths( ...
    outputDirectory,options.WriteArtifacts);

sourceFiles = string(data.hashes.filePath);
sourceHashes = lower(string(data.hashes.actualSHA256));
metadata = struct( ...
    "interface_name","rkkt.model.linearizeStageB2A", ...
    "production_function","build_stage_b_multiday_linearization", ...
    "input_artifact",sourceFiles(1), ...
    "input_sha256",sourceHashes(1), ...
    "git_commit",git_commit(projectRoot), ...
    "stage_id","stage_B", ...
    "day",14:20, ...
    "hour",1:24, ...
    "iteration",state.iteration_index, ...
    "revision",state.state_revision, ...
    "matlab_version",string(version), ...
    "generated_at",now_text(), ...
    "contract_version",rkkt.contracts.version(), ...
    "module_name","阶段B-2A模型验证", ...
    "output_file",outputFile, ...
    "interactive_figures",options.Interactive, ...
    "artifacts_requested",options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "project_root",projectRoot, ...
    "source_files",sourceFiles, ...
    "source_sha256",sourceHashes, ...
    "configuration_paths",config.source_paths, ...
    "facade_chain",[ ...
        "rkkt.data.load"
        "rkkt.indexing.buildStageB2A"
        "rkkt.model.initializeStageB2A"
        "rkkt.model.linearizeStageB2A"]);
moduleResult.output = struct( ...
    "linearizationIdentity",string(linearization.identity), ...
    "linearizationVersion",string(linearization.version), ...
    "counts",linearization.counts, ...
    "dimensionSummary",summary, ...
    "stateCounters",struct( ...
        "iteration_index",state.iteration_index, ...
        "state_revision",state.state_revision, ...
        "newton_direction_number",state.newton_direction_number, ...
        "completed_newton_direction_count", ...
            state.completed_newton_direction_count));
moduleResult.intermediate = struct( ...
    "indexVersion",string(index.version), ...
    "waterConstraintCount",height(index.water_constraint_index), ...
    "hessianSymmetryRelative", ...
        linearization.lagrangian_hessian_symmetry_relative, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "objective_facts",facts, ...
    "linearization_identity",string(linearization.identity), ...
    "hessian_nonzeros",nnz(linearization.H), ...
    "fixed_zero_count",height(index.fixed_zero_map), ...
    "optimization_executed",false, ...
    "state_update_executed",false, ...
    "full_ipm_executed",false, ...
    "formal_run_created",false, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "primal_order","沿B-2A canonical variable_index", ...
    "equality_order","沿Stage-A等式前缀", ...
    "inequality_order","7248条Stage-A不等式后追加56条日级水量约束", ...
    "stored_payload","仅保存身份、维数和摘要，不重复嵌入大对象");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    write_table17(summary,tableFiles(1));
    fig = hessian_figure(linearization.H,options.Interactive);
    save_figure_pair(fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    save(outputFile,"moduleResult","-v7.3");
end
end

function value = linearization_summary(linearization)
objectName = [ ...
    "H"
    "A"
    "G"
    "r_dual"
    "r_eq"
    "r_ineq"
    "r_comp"
    "l"
    "z"
    "mu"];
objects = { ...
    linearization.H
    linearization.A
    linearization.G
    linearization.r_dual
    linearization.r_eq
    linearization.r_ineq
    linearization.r_comp
    linearization.l
    linearization.z
    linearization.mu};
n = numel(objects);
className = strings(n,1);
rowCount = zeros(n,1);
columnCount = zeros(n,1);
elementCount = zeros(n,1);
nonzeroCount = zeros(n,1);
sparseStorage = false(n,1);
finiteNonzeros = false(n,1);
for k = 1:n
    object = objects{k};
    className(k) = string(class(object));
    rowCount(k) = size(object,1);
    columnCount(k) = size(object,2);
    elementCount(k) = numel(object);
    nonzeroCount(k) = nnz(object);
    sparseStorage(k) = issparse(object);
    finiteNonzeros(k) = all(isfinite(nonzeros(object)));
end
value = table(objectName,className,rowCount,columnCount,elementCount, ...
    nonzeroCount,sparseStorage,finiteNonzeros);
end

function facts = inspect_chain(index,state,linearization)
facts = struct( ...
    "stage_identity_exact", ...
        string(state.stage_id) == "stage_B" && ...
        string(linearization.stage_id) == "stage_B" && ...
        string(linearization.milestone_id) == "B-2A", ...
    "controlled_dimensions_exact", ...
        isequal(size(linearization.H),[3722,3722]) && ...
        isequal(size(linearization.A),[618,3722]) && ...
        isequal(size(linearization.G),[7304,3722]), ...
    "matrix_storage_sparse", ...
        issparse(linearization.H) && ...
        issparse(linearization.A) && ...
        issparse(linearization.G), ...
    "water_constraint_count_exact", ...
        height(index.water_constraint_index) == 56, ...
    "fixed_zero_count_exact",height(index.fixed_zero_map) == 422, ...
    "slack_multiplier_positive", ...
        all(isfinite(state.l)) && all(state.l > 0) && ...
        all(isfinite(state.z)) && all(state.z > 0), ...
    "initial_counters_exact", ...
        state.iteration_index == 0 && ...
        state.state_revision == 0 && ...
        state.newton_direction_number == 0 && ...
        state.completed_newton_direction_count == 0, ...
    "state_not_updated", ...
        isfield(state,"state_update_executed") && ...
        ~state.state_update_executed, ...
    "execution_boundary_preserved", ...
        ~linearization.execution.full_kkt_assembled && ...
        ~linearization.execution.full_kkt_solved && ...
        ~linearization.execution.recursive_direction_executed && ...
        ~linearization.execution.full_ipm_executed && ...
        ~linearization.execution.optimization_executed && ...
        ~linearization.execution.state_update_executed && ...
        ~linearization.execution.parallel_executed && ...
        ~linearization.execution.stage_c1_entered, ...
    "hessian_symmetry_within_contract", ...
        linearization.lagrangian_hessian_symmetry_relative <= 1e-12);
end

function config = call_configuration(projectRoot)
modelDirectory = fullfile(projectRoot,"src","model");
productionFile = fullfile(modelDirectory, ...
    "load_stage_b2a_configuration.m");
if ~isfile(productionFile)
    error("rkkt:model:validation:StageB2AConfigMissing", ...
        "The controlled configuration loader is missing: %s", ...
        productionFile);
end
originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(modelDirectory,"-begin");
resolved = string(which("load_stage_b2a_configuration"));
if ~same_path(resolved,productionFile)
    error("rkkt:model:validation:StageB2AConfigShadowed", ...
        "Expected '%s'; MATLAB resolved '%s'.", ...
        productionFile,resolved);
end
config = load_stage_b2a_configuration(projectRoot);
clear pathGuard
end

function fig = hessian_figure(hessian,interactive)
visibility = "off";
if interactive
    visibility = "on";
end
fig = figure("Name","阶段B-2A拉格朗日Hessian稀疏结构", ...
    "NumberTitle","off","Color","w","Visible",visibility, ...
    "Position",[100,100,900,720]);
spy(hessian);
title(compose("阶段B-2A拉格朗日Hessian：%d×%d，nnz=%d", ...
    size(hessian,1),size(hessian,2),nnz(hessian)));
xlabel("原始变量列");
ylabel("原始变量行");
end

function [outputFile,tableFiles,figureFiles,index] = ...
        output_paths(outputDirectory,writeArtifacts)
if writeArtifacts
    outputFile = fullfile(outputDirectory, ...
        "阶段B-2A模型验证输出.mat");
    tableFiles = fullfile(outputDirectory, ...
        "阶段B-2A线性化维数摘要.csv");
    figPath = fullfile(outputDirectory, ...
        "阶段B-2A拉格朗日Hessian稀疏结构.fig");
    pngPath = fullfile(outputDirectory, ...
        "阶段B-2A拉格朗日Hessian稀疏结构.png");
    figureFiles = [figPath;pngPath];
else
    outputFile = "";
    tableFiles = strings(0,1);
    figPath = "";
    pngPath = "";
    figureFiles = strings(0,1);
end
outputFile = string(outputFile);
tableFiles = reshape(string(tableFiles),[],1);
figureFiles = reshape(string(figureFiles),[],1);
index = struct("figPath",string(figPath),"pngPath",string(pngPath));
end

function require_inputs(projectRoot,outputDirectory,writeArtifacts)
if strlength(projectRoot) == 0 || ~isfolder(projectRoot)
    error("rkkt:model:validation:StageB2AProjectRoot", ...
        "ProjectRoot must be an existing nonempty directory: %s", ...
        projectRoot);
end
if writeArtifacts && ~isfolder(outputDirectory)
    error("rkkt:model:validation:StageB2AOutputDirectory", ...
        "OutputDirectory must already exist: %s",outputDirectory);
end
end

function save_figure_pair(fig,figPath,pngPath)
savefig(fig,figPath);
exportgraphics(fig,pngPath,"Resolution",200);
end

function write_table17(value,destination)
names = string(value.Properties.VariableNames);
cells = strings(height(value),width(value));
for columnIndex = 1:width(value)
    column = value.(value.Properties.VariableNames{columnIndex});
    if isnumeric(column)
        cells(:,columnIndex) = compose("%.17g",double(column));
    elseif islogical(column)
        cells(:,columnIndex) = lower(string(column));
    else
        cells(:,columnIndex) = csv_escape(string(column));
    end
end
lines = [strjoin(csv_escape(names),",");join(cells,",",2)];
write_text(destination,strjoin(lines,newline)+newline);
end

function value = csv_escape(value)
value = replace(string(value),"""","""""");
value = """"+value+"""";
end

function write_text(destination,textValue)
[fileId,message] = fopen(destination,"wb","n","UTF-8");
if fileId < 0
    error("rkkt:model:validation:StageB2ACsvOpen","%s",message);
end
fileGuard = onCleanup(@() close_file(fileId));
bytes = unicode2native(char(textValue),"UTF-8");
if fwrite(fileId,bytes,"uint8") ~= numel(bytes)
    error("rkkt:model:validation:StageB2ACsvWrite", ...
        "Incomplete CSV write: %s",destination);
end
status = fclose(fileId);
clear fileGuard
if status ~= 0
    error("rkkt:model:validation:StageB2ACsvClose", ...
        "Could not close CSV: %s",destination);
end
end

function close_file(fileId)
try
    if ischar(fopen(fileId))
        fclose(fileId);
    end
catch
end
end

function value = git_commit(projectRoot)
value = "NOT_AVAILABLE";
safeRoot = replace(projectRoot,"\","/");
command = sprintf('git -c safe.directory="%s" -C "%s" rev-parse HEAD', ...
    safeRoot,projectRoot);
[status,output] = system(command);
candidate = lower(strip(string(output)));
if status == 0 && ~isempty(regexp(char(candidate), ...
        "^[0-9a-f]{40}$","once"))
    value = candidate;
end
end

function value = now_text()
value = string(datetime("now","TimeZone","Asia/Shanghai", ...
    "Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
end

function value = same_path(left,right)
left = replace(string(left),"/","\");
right = replace(string(right),"/","\");
if ispc
    value = strcmpi(left,right);
else
    value = strcmp(left,right);
end
end

function value = default_project_root()
value = string(fileparts(mfilename("fullpath")));
for k = 1:4
    value = string(fileparts(value));
end
end

function value = default_output_directory()
value = string(fileparts(mfilename("fullpath")));
end
