function issues = append_stage_a2_issue(issues,runContext,testId, ...
        layer,variableOrEquation,symptom,errorMessage,rootCause, ...
        proposedSolution,status,evidencePath)
%APPEND_STAGE_A2_ISSUE Append one immutable run-specific issue fact.

allowed = ["OPEN","FIXED","BLOCKED","WONT_FIX"];
status = upper(string(status));
assert(isscalar(status) && ismember(status,allowed), ...
    "stageA2:issues:InvalidStatus","Invalid issue status %s.",status);
gitCommit = "NOT_AVAILABLE";
if isfile(runContext.run_manifest_path)
    manifest = jsondecode(fileread(runContext.run_manifest_path));
    if isfield(manifest,"git_commit"), gitCommit=string(manifest.git_commit); end
end
issueId = "SA2-ISSUE-"+compose("%03d",height(issues)+1);
issues(end+1,:) = {issueId,string(runContext.run_id), ...
    string(runContext.stage_id),string(testId),string(layer), ...
    string(variableOrEquation),string(symptom),string(errorMessage), ...
    string(rootCause),string(proposedSolution),gitCommit,"",status, ...
    replace(string(evidencePath),'\','/'),string(datetime('now', ...
    'TimeZone','Asia/Shanghai','Format','yyyy-MM-dd''T''HH:mm:ssXXX'))};
end
