function audit = assert_stage_a4_3_preflight(projectRoot)
%ASSERT_STAGE_A4_3_PREFLIGHT Enforce the formal A4-3 Git/stage boundary.

arguments
    projectRoot (1,1) string
end
currentPath = fullfile(projectRoot,"CURRENT_STAGE.md");
assert(isfile(currentPath),"stageA4:a43:CurrentStageMissing", ...
    "CURRENT_STAGE.md is missing.");
current = string(fileread(currentPath));
stagePassed = contains(current,"`stage_id`: `stage_A4`") && ...
    contains(current,"`status`: `READY`");
assert(stagePassed,"stageA4:a43:CurrentStage", ...
    "CURRENT_STAGE.md must remain stage_A4 / READY.");

[branchStatus,branchText] = git_command( ...
    projectRoot,"branch --show-current");
branch = strip(string(branchText));
assert(branchStatus==0 && branch=="stage_A4", ...
    "stageA4:a43:Branch", ...
    "Formal A4-3 execution requires branch stage_A4.");
[headStatus,headText] = git_command(projectRoot,"rev-parse HEAD");
head = lower(strip(string(headText)));
assert(headStatus==0 && ...
    ~isempty(regexp(char(head),"^[0-9a-f]{40}$","once")), ...
    "stageA4:a43:Head","Could not resolve the full Git HEAD.");
[trackedStatus,trackedText] = git_command( ...
    projectRoot,"status --porcelain --untracked-files=no");
trackedClean = trackedStatus==0 && ...
    strlength(strip(string(trackedText)))==0;
assert(trackedClean,"stageA4:a43:TrackedChanges", ...
    "Formal A4-3 execution requires a clean tracked worktree.");
[statusCode,statusText] = git_command( ...
    projectRoot,"status --porcelain --untracked-files=normal");
assert(statusCode==0,"stageA4:a43:GitStatus", ...
    "Could not inspect the full Git status.");
lines = strip(splitlines(string(statusText)));
lines = lines(strlength(lines)>0);
unknown = lines(~startsWith(lines,"?? runs/"));
assert(isempty(unknown),"stageA4:a43:UnknownUntracked", ...
    "Only preserved untracked runs are allowed before formal A4-3: %s", ...
    strjoin(unknown,"; "));

audit = struct( ...
    "stage_id","stage_A4", ...
    "stage_status","READY", ...
    "branch",branch, ...
    "git_commit",head, ...
    "authority_starting_head", ...
        "521ea489c2e0fba79fde22f32b5f647167eb637b", ...
    "tracked_worktree_clean",trackedClean, ...
    "untracked_entries",lines, ...
    "untracked_entries_all_under_runs",isempty(unknown), ...
    "passed",stagePassed && trackedClean && isempty(unknown));
end

function [status,output] = git_command(root,arguments)
safe = replace(string(root),"\","/");
quotedSafe = '"'+replace(safe,'"','\"')+'"';
quotedRoot = '"'+replace(string(root),'"','\"')+'"';
command = "git -c safe.directory="+quotedSafe+" -C "+quotedRoot+" "+ ...
    arguments;
[status,output] = system(char(command));
end
