function [audit,execution] = audit_stage_a4_r1_forbidden_execution( ...
        unscaledFive,scaledFive,scaledTwenty,executionSequence, ...
        roundTable,refinementTable,config,codeAudit,dependencyClosure)
%AUDIT_STAGE_A4_R1_FORBIDDEN_EXECUTION Prove the isolated R1 boundary.
%
% This audit deliberately does not use roundTable.no_full_direction_fallback
% when deciding whether forbidden execution occurred.  No-fallback remains
% a separate blocking contract.  Here, recorded chain/state/step facts are
% combined with the dependency closure rooted at the actual R1 entry.

arguments
    unscaledFive (1,1) struct
    scaledFive (1,1) struct
    scaledTwenty (1,1) struct
    executionSequence string
    roundTable table
    refinementTable table
    config (1,1) struct
    codeAudit table
    dependencyClosure table
end

chains = {unscaledFive,scaledFive,scaledTwenty};
expectedSequence = [ ...
    "unscaled_stable5_completed"
    "scaled_stable5_completed"
    "scaled_stable5_gate_passed"
    "scaled_stable20_completed"];
iterationCounts = [unscaledFive.iteration_count, ...
    scaledFive.iteration_count,scaledTwenty.iteration_count];
recordedDirectionCount = sum(iterationCounts);
revisionPassed = height(roundTable)==30 && ...
    all(roundTable.state_revision_after== ...
        roundTable.state_revision_before+1) && ...
    unscaledFive.initial_state_revision==0 && ...
    unscaledFive.final_state_revision==5 && ...
    scaledFive.initial_state.state_revision==0 && ...
    scaledFive.final_state.state_revision==5 && ...
    scaledTwenty.initial_state.state_revision==0 && ...
    scaledTwenty.final_state.state_revision==20;
expectedScopePassed = isequal(executionSequence(:),expectedSequence) && ...
    isequal(iterationCounts,[5 5 20]) && ...
    recordedDirectionCount==30 && revisionPassed;

chainStrategies = [string(unscaledFive.step_strategy), ...
    string(scaledFive.step_strategy),string(scaledTwenty.step_strategy)];
independentStepsPassed = all(chainStrategies=="independent") && ...
    all(roundTable.candidate_alpha_primal== ...
        roundTable.applied_alpha_primal) && ...
    all(roundTable.candidate_alpha_dual==roundTable.applied_alpha_dual);

sigma = config.initialization.centering_sigma;
fixedSigmaPassed = sigma==0.1 && ...
    all(roundTable.mu_before==sigma*roundTable.gap_before) && ...
    all(roundTable.mu_after==sigma*roundTable.gap_after);

automaticRegularization = true;
automaticSymmetrization = true;
if isfield(config,"linear_algebra")
    if isfield(config.linear_algebra,"automatic_regularization")
        automaticRegularization = logical( ...
            config.linear_algebra.automatic_regularization);
    end
    if isfield(config.linear_algebra,"automatic_symmetrization")
        automaticSymmetrization = logical( ...
            config.linear_algebra.automatic_symmetrization);
    end
end
parallelModeOff = isfield(config,"parallel_mode") && ...
    string(config.parallel_mode)=="off";

predictorCorrectorPassed = code_pass( ...
    codeAudit,"R1-NO-PREDICTOR-CORRECTOR");
lineSearchPassed = code_pass(codeAudit,"R1-NO-LINE-SEARCH");
regularizationPassed = code_pass( ...
    codeAudit,"R1-NO-REGULARIZATION") && ~automaticRegularization;
symmetrizationPassed = code_pass( ...
    codeAudit,"R1-NO-AUTOMATIC-SYMMETRIZATION") && ...
    ~automaticSymmetrization;
parallelPassed = code_pass(codeAudit,"R1-NO-PARALLEL-CALL") && ...
    parallelModeOff && ~any_execution_flag(chains,"parallel_executed");
formalRunPassed = code_pass( ...
    codeAudit,"R1-NO-FILESYSTEM-MUTATION") && ...
    ~any_execution_flag(chains,"formal_a4_run_created");
exactChainCallsPassed = code_pass( ...
    codeAudit,"R1-EXPLICIT-THREE-PASS-CHAINS");
hundredRoundPassed = expectedScopePassed && exactChainCallsPassed && ...
    recordedDirectionCount<100;
stageBPassed = code_pass(codeAudit,"R1-NO-STAGE-B-DEPENDENCY") && ...
    ~any_execution_flag(chains,"stage_b_entered");

requiredDependencies = [ ...
    "main_stage_A4_2D_2A_R1.m"
    "src/diagnostics/run_stage_a4_objective_unitization_r1_diagnostic.m"
    "src/diagnostics/audit_stage_a4_r1_forbidden_execution.m"
    "src/diagnostics/make_stage_a4_r1_blocking_audit.m"
    "src/diagnostics/scan_stage_a4_r1_forbidden_code.m"
    "src/diagnostics/run_stage_a4_five_iteration_diagnostic.m"
    "src/diagnostics/run_stage_a4_scaled_objective_chain.m"
    "src/diagnostics/execute_stage_a4_iteration.m"
    "src/solver/solve_stage_a_multiday_recursive_direction.m"
    "src/solver/solve_stage_a_multiday_full_kkt_direction.m"
    "src/solver/update_primal_dual_state.m"];
closureSchemaPassed = all(ismember( ...
    ["relative_path","sha256"], ...
    string(dependencyClosure.Properties.VariableNames)));
closureCoveragePassed = false;
if closureSchemaPassed
    closurePaths = replace(string( ...
        dependencyClosure.relative_path),'\','/');
    closureHashes = lower(string(dependencyClosure.sha256));
    closureCoveragePassed = all(ismember(requiredDependencies,closurePaths)) && ...
        numel(unique(closurePaths))==height(dependencyClosure) && ...
        all(strlength(closureHashes)==64) && ...
        all(~ismissing(closureHashes));
end
codeClosurePassed = all(codeAudit.status=="PASS");

testId = [ ...
    "R1-RUN-EXPECTED-SEQUENCE"
    "R1-RUN-INDEPENDENT-STEPS"
    "R1-RUN-FIXED-SIGMA"
    "R1-RUN-NO-PREDICTOR-CORRECTOR"
    "R1-RUN-NO-LINE-SEARCH"
    "R1-RUN-NO-REGULARIZATION"
    "R1-RUN-NO-AUTOMATIC-SYMMETRIZATION"
    "R1-RUN-NO-PARALLEL"
    "R1-RUN-NO-FORMAL-RUN"
    "R1-RUN-NO-100-ROUNDS"
    "R1-RUN-NO-STAGE-B"
    "R1-RUN-ROOTED-DEPENDENCY-CLOSURE"
    "R1-RUN-CLOSURE-CODE-SCAN"];
requirement = [ ...
    "Recorded R1 sequence contains exactly 5+5+20 directions and updates"
    "Recorded chains and applied steps use independent primal/dual steps"
    "Every recorded round consumes the frozen fixed sigma=0.1"
    "The R1 closure contains no predictor-corrector mechanism"
    "The R1 closure contains no line-search mechanism"
    "The R1 closure and configuration contain no regularization"
    "The R1 closure and configuration contain no automatic symmetrization"
    "The R1 closure, configuration and child records show no parallel run"
    "The R1 closure and child records show no formal A4 run creation"
    "Recorded scope is exactly 30 updates and contains no 100-round run"
    "The R1 closure and child records exclude Stage B"
    "The hashed dependency closure is rooted at R1 and covers its helpers"
    "Every R1 dependency-closure code rule passes"];
actual = [ ...
    expectedScopePassed
    independentStepsPassed
    fixedSigmaPassed
    predictorCorrectorPassed
    lineSearchPassed
    regularizationPassed
    symmetrizationPassed
    parallelPassed
    formalRunPassed
    hundredRoundPassed
    stageBPassed
    closureCoveragePassed
    codeClosurePassed];
evidenceSource = [ ...
    "execution_sequence; chain iteration counts; round state revisions"
    "chain step_strategy; recorded candidate/applied alpha pairs"
    "config sigma; recorded mu/gap before and after every update"
    "R1-rooted dependency closure code scan"
    "R1-rooted dependency closure code scan"
    "R1-rooted dependency closure code scan; solver configuration"
    "R1-rooted dependency closure code scan; solver configuration"
    "R1-rooted dependency closure scan; configuration; child records"
    "R1-rooted dependency closure mutation scan; child records"
    "execution_sequence; chain iteration counts; round state revisions"
    "R1-rooted Stage-B dependency scan; child records"
    "dependency-closure relative paths and SHA256"
    "R1-rooted dependency closure code scan"];
status = repmat("FAIL",numel(testId),1);
status(actual) = "PASS";
audit = table(testId,requirement,actual,evidenceSource,status, ...
    'VariableNames',{'test_id','requirement','actual', ...
    'evidence_source','status'});

fullDirectionConsumed = any( ...
    logical(refinementTable.full_kkt_direction_consumed));
noFallback = all(logical(roundTable.no_full_direction_fallback)) && ...
    ~fullDirectionConsumed;
recursiveOfficial = all_execution_flag( ...
    chains,"recursive_direction_is_official");
forbiddenPass = all(actual);
execution = struct( ...
    "unscaled_five_newton_direction_count",iterationCounts(1), ...
    "scaled_five_newton_direction_count",iterationCounts(2), ...
    "scaled_twenty_newton_direction_count",iterationCounts(3), ...
    "total_newton_direction_count",recordedDirectionCount, ...
    "state_update_count",height(roundTable), ...
    "full_kkt_audit_count",height(roundTable), ...
    "recursive_refinement_max_passes", ...
        max(roundTable.recursive_refinement_max_passes), ...
    "stable_v2_recursive_route", ...
        all(roundTable.recursive_refinement_max_passes==3), ...
    "recursive_direction_is_official",recursiveOfficial, ...
    "full_kkt_direction_consumed",fullDirectionConsumed, ...
    "complete_kkt_direction_fallback_used",~noFallback, ...
    "common_step_used",~independentStepsPassed, ...
    "dynamic_sigma_used",~fixedSigmaPassed, ...
    "predictor_corrector_used",~predictorCorrectorPassed, ...
    "line_search_used",~lineSearchPassed, ...
    "regularization_used",~regularizationPassed, ...
    "automatic_symmetrization_used",~symmetrizationPassed, ...
    "hundred_round_run_executed",~hundredRoundPassed, ...
    "full_ipm_executed", ...
        ~(expectedScopePassed && exactChainCallsPassed), ...
    "optimization_executed", ...
        ~(expectedScopePassed && exactChainCallsPassed), ...
    "parallel_executed",~parallelPassed, ...
    "formal_a4_run_created",~formalRunPassed, ...
    "stage_b_entered",~stageBPassed, ...
    "r1_dependency_file_count",height(dependencyClosure), ...
    "r1_dependency_closure_all_hashed",closureCoveragePassed, ...
    "r1_dependency_root","main_stage_A4_2D_2A_R1.m", ...
    "r1_dependency_analysis_method", ...
        "matlab.codetools.requiredFilesAndProducts", ...
    "r1_forbidden_code_check_count",height(codeAudit), ...
    "forbidden_execution_audit_pass",forbiddenPass, ...
    "forbidden_execution_evidence_source", ...
        "recorded runtime facts plus R1-rooted hashed dependency closure", ...
    "forbidden_execution_reuses_no_fallback",false);
end

function passed = code_pass(audit,checkId)
row = string(audit.check_id)==string(checkId);
passed = nnz(row)==1 && string(audit.status(row))=="PASS";
end

function value = any_execution_flag(chains,fieldName)
value = false;
for k = 1:numel(chains)
    execution = chains{k}.execution;
    if isfield(execution,fieldName)
        value = value || any(logical(execution.(fieldName)),"all");
    end
end
end

function value = all_execution_flag(chains,fieldName)
value = true;
for k = 1:numel(chains)
    execution = chains{k}.execution;
    value = value && isfield(execution,fieldName) && ...
        all(logical(execution.(fieldName)),"all");
end
end
