function audit = audit_stage_a4_complementarity_change( ...
        iteration,linearizationBefore,linearizationAfter,direction, ...
        alphaPrimal,alphaDual)
%AUDIT_STAGE_A4_COMPLEMENTARITY_CHANGE Diagnose one accepted A4 update.
%
% This is a read-only diagnostic.  It evaluates the official independent
% primal/dual step and a common-step counterfactual from the same Newton
% direction; it never creates or updates an optimization state.

arguments
    iteration (1,1) double {mustBeInteger,mustBePositive}
    linearizationBefore (1,1) struct
    linearizationAfter (1,1) struct
    direction (1,1) struct
    alphaPrimal (1,1) double {mustBeFinite,mustBeNonnegative}
    alphaDual (1,1) double {mustBeFinite,mustBeNonnegative}
end

assert(alphaPrimal<=1 && alphaDual<=1, ...
    "stageA4:audit:StepRange", ...
    "The official primal and dual step lengths must not exceed one.");
validate_inputs(linearizationBefore,linearizationAfter,direction);

lBefore = linearizationBefore.l(:);
zBefore = linearizationBefore.z(:);
lAfter = linearizationAfter.l(:);
zAfter = linearizationAfter.z(:);
deltaL = direction.l(:);
deltaZ = direction.z(:);
nInequality = numel(lBefore);
inequalityIndex = (1:nInequality).';

productBefore = lBefore.*zBefore;
productAfter = lAfter.*zAfter;
deltaActual = productAfter-productBefore;
deltaSlackTerm = alphaPrimal*(deltaL.*zBefore);
deltaMultiplierTerm = alphaDual*(lBefore.*deltaZ);
deltaCrossTerm = alphaPrimal*alphaDual*(deltaL.*deltaZ);
deltaPredicted = deltaSlackTerm+deltaMultiplierTerm+deltaCrossTerm;
deltaClosure = deltaActual-deltaPredicted;

gapBefore = mean(productBefore);
gapAfter = mean(productAfter);
gapSlackTerm = mean(deltaSlackTerm);
gapMultiplierTerm = mean(deltaMultiplierTerm);
gapCrossTerm = mean(deltaCrossTerm);
gapPredicted = gapBefore+gapSlackTerm+gapMultiplierTerm+gapCrossTerm;
gapClosure = gapAfter-gapPredicted;
gapScale = max([1,abs(gapBefore),abs(gapAfter),abs(gapPredicted)]);
gapClosureRelative = abs(gapClosure)/gapScale;
elementScale = max([ones(nInequality,1),abs(productBefore), ...
    abs(productAfter),abs(deltaPredicted)],[],2);
elementClosureRelative = abs(deltaClosure)./elementScale;

expectedLAfter = lBefore+alphaPrimal*deltaL;
expectedZAfter = zBefore+alphaDual*deltaZ;
lUpdateScale = max([1;abs(lAfter);abs(expectedLAfter)]);
zUpdateScale = max([1;abs(zAfter);abs(expectedZAfter)]);
lUpdateRelativeError = norm(lAfter-expectedLAfter,inf)/lUpdateScale;
zUpdateRelativeError = norm(zAfter-expectedZAfter,inf)/zUpdateScale;

termNames = ["alpha_primal_mean_delta_l_times_z", ...
    "alpha_dual_mean_l_times_delta_z", ...
    "alpha_primal_alpha_dual_mean_delta_l_times_delta_z"];
termValues = [gapSlackTerm,gapMultiplierTerm,gapCrossTerm];
[largestSignedValue,largestSignedPosition] = max(termValues);
positivePositions = find(termValues>0);
if isempty(positivePositions)
    largestPositiveName = "none";
    largestPositiveValue = 0;
else
    [largestPositiveValue,localPosition] = max(termValues(positivePositions));
    largestPositiveName = termNames(positivePositions(localPosition));
end
decomposition = struct( ...
    "iteration",iteration, ...
    "gap_before",gapBefore, ...
    "gap_after",gapAfter, ...
    "gap_change",gapAfter-gapBefore, ...
    "alpha_primal",alphaPrimal, ...
    "alpha_dual",alphaDual, ...
    "alpha_primal_mean_delta_l_times_z",gapSlackTerm, ...
    "alpha_dual_mean_l_times_delta_z",gapMultiplierTerm, ...
    "alpha_primal_alpha_dual_mean_delta_l_times_delta_z",gapCrossTerm, ...
    "predicted_gap_after",gapPredicted, ...
    "closure_error",gapClosure, ...
    "closure_absolute_error",abs(gapClosure), ...
    "closure_relative_error",gapClosureRelative, ...
    "maximum_item_closure_absolute_error",max(abs(deltaClosure)), ...
    "maximum_item_closure_relative_error",max(elementClosureRelative), ...
    "official_l_update_relative_error",lUpdateRelativeError, ...
    "official_z_update_relative_error",zUpdateRelativeError, ...
    "gap_increased",gapAfter>gapBefore, ...
    "largest_signed_term",termNames(largestSignedPosition), ...
    "largest_signed_term_value",largestSignedValue, ...
    "largest_positive_term",largestPositiveName, ...
    "largest_positive_term_value",largestPositiveValue, ...
    "positive_constraint_count",nnz(deltaActual>0));

inequalities = linearizationBefore.index.constraint_index( ...
    string(linearizationBefore.index.constraint_index.constraint_type)== ...
    "inequality",:);
deltaByInequality = table( ...
    repmat(iteration,nInequality,1),inequalityIndex, ...
    inequalities.global_row,string(inequalities.constraint_id), ...
    inequalities.day,inequalities.hour,string(inequalities.asset_type), ...
    inequalities.asset_id,string(inequalities.constraint_name), ...
    string(inequalities.unit),lBefore,zBefore,deltaL,deltaZ, ...
    repmat(alphaPrimal,nInequality,1), ...
    repmat(alphaDual,nInequality,1),lAfter,zAfter,productBefore, ...
    productAfter,deltaSlackTerm,deltaMultiplierTerm,deltaCrossTerm, ...
    deltaPredicted,deltaActual,deltaClosure,elementClosureRelative, ...
    'VariableNames',{'iteration','inequality_index', ...
    'constraint_global_row','constraint_id','day','hour','asset_type', ...
    'asset_id','constraint_name','unit','l_before','z_before','delta_l', ...
    'delta_z','alpha_primal','alpha_dual','l_after','z_after', ...
    'product_before','product_after','slack_term_contribution', ...
    'multiplier_term_contribution','cross_term_contribution', ...
    'predicted_delta','delta_i','closure_error', ...
    'closure_relative_error'});

positiveRows = find(deltaActual>0);
if isempty(positiveRows)
    topRows = zeros(0,1);
else
    [~,positiveOrder] = sortrows( ...
        [-deltaActual(positiveRows),inequalityIndex(positiveRows)],[1,2]);
    topRows = positiveRows(positiveOrder(1:min(20,numel(positiveOrder))));
end
top20 = deltaByInequality(topRows,:);
top20.rank = (1:height(top20)).';
top20 = movevars(top20,'rank','After','iteration');
decomposition.top_positive_constraint_count = height(top20);

constraintFamilySummary = contribution_summary( ...
    iteration,string(inequalities.constraint_name),deltaActual, ...
    deltaPredicted,"constraint_name");
assetTypeSummary = contribution_summary( ...
    iteration,string(inequalities.asset_type),deltaActual, ...
    deltaPredicted,"asset_type");

centralityStatistics = [ ...
    distribution_row(iteration,"before","l_times_z",productBefore); ...
    distribution_row(iteration,"after","l_times_z",productAfter); ...
    distribution_row(iteration,"before","l_times_z_over_mu", ...
        productBefore/linearizationBefore.mu); ...
    distribution_row(iteration,"after","l_times_z_over_mu", ...
        productAfter/linearizationAfter.mu)];

vectorScaleStatistics = [ ...
    scale_row(iteration,"l","before",lBefore); ...
    scale_row(iteration,"z","before",zBefore); ...
    scale_row(iteration,"delta_l","direction",deltaL); ...
    scale_row(iteration,"delta_z","direction",deltaZ); ...
    scale_row(iteration,"l","after",lAfter); ...
    scale_row(iteration,"z","after",zAfter)];

variables = linearizationBefore.index.variable_index;
[variableGroups,variableAssetTypes,variableMembers] = ...
    canonical_variable_groups(variables);
equalities = linearizationBefore.index.constraint_index( ...
    string(linearizationBefore.index.constraint_index.constraint_type)== ...
    "equality",:);
equalityGroups = string(equalities.constraint_name)+"|"+ ...
    string(equalities.asset_type);
groupScaleStatistics = [ ...
    grouped_scale_rows(iteration,"objective_gradient","before", ...
        "variable_group",variableGroups,variableAssetTypes, ...
        variableMembers,linearizationBefore.objective.gradient); ...
    grouped_scale_rows(iteration,"objective_gradient","after", ...
        "variable_group",variableGroups,variableAssetTypes, ...
        variableMembers,linearizationAfter.objective.gradient); ...
    grouped_scale_rows(iteration,"dual_residual","before", ...
        "variable_group",variableGroups,variableAssetTypes, ...
        variableMembers,linearizationBefore.r_dual); ...
    grouped_scale_rows(iteration,"dual_residual","after", ...
        "variable_group",variableGroups,variableAssetTypes, ...
        variableMembers,linearizationAfter.r_dual); ...
    grouped_scale_rows(iteration,"equality_residual","before", ...
        "constraint_group",equalityGroups,string(equalities.asset_type), ...
        string(equalities.constraint_name),linearizationBefore.r_eq); ...
    grouped_scale_rows(iteration,"equality_residual","after", ...
        "constraint_group",equalityGroups,string(equalities.asset_type), ...
        string(equalities.constraint_name),linearizationAfter.r_eq)];

alphaCommon = min(alphaPrimal,alphaDual);
lCommon = lBefore+alphaCommon*deltaL;
zCommon = zBefore+alphaCommon*deltaZ;
commonProduct = lCommon.*zCommon;
commonGap = mean(commonProduct);
commonSlackTerm = alphaCommon*mean(deltaL.*zBefore);
commonMultiplierTerm = alphaCommon*mean(lBefore.*deltaZ);
commonCrossTerm = alphaCommon^2*mean(deltaL.*deltaZ);
commonPredictedGap = gapBefore+commonSlackTerm+commonMultiplierTerm+ ...
    commonCrossTerm;
commonGapScale = max([1,abs(commonGap),abs(commonPredictedGap), ...
    abs(gapBefore)]);
counterfactual = struct( ...
    "iteration",iteration, ...
    "read_only",true, ...
    "used_for_official_state_update",false, ...
    "same_newton_direction",true, ...
    "alpha_common",alphaCommon, ...
    "official_alpha_primal",alphaPrimal, ...
    "official_alpha_dual",alphaDual, ...
    "gap_before",gapBefore, ...
    "gap_after",commonGap, ...
    "gap_change",commonGap-gapBefore, ...
    "gap_difference_from_official",commonGap-gapAfter, ...
    "predicted_gap_after",commonPredictedGap, ...
    "closure_error",commonGap-commonPredictedGap, ...
    "closure_relative_error",abs(commonGap-commonPredictedGap)/ ...
        commonGapScale, ...
    "slack_term_contribution",commonSlackTerm, ...
    "multiplier_term_contribution",commonMultiplierTerm, ...
    "cross_term_contribution",commonCrossTerm, ...
    "minimum_l",min(lCommon), ...
    "minimum_z",min(zCommon), ...
    "strictly_positive",all(lCommon>0) && all(zCommon>0), ...
    "all_finite",all(isfinite([lCommon;zCommon;commonProduct])));

totalDelta = sum(deltaActual);
constraintFamilyClosure = summary_closure( ...
    constraintFamilySummary,totalDelta,nInequality);
assetTypeClosure = summary_closure( ...
    assetTypeSummary,totalDelta,nInequality);
topTraceable = top20_traceable( ...
    top20,deltaByInequality,deltaActual,inequalityIndex);
numericTolerance = 2048*eps;
checks = struct( ...
    "all_numeric_inputs_finite",all(isfinite([lBefore;zBefore;lAfter; ...
        zAfter;deltaL;deltaZ;linearizationBefore.objective.gradient; ...
        linearizationAfter.objective.gradient; ...
        linearizationBefore.r_eq;linearizationAfter.r_eq; ...
        linearizationBefore.r_dual;linearizationAfter.r_dual])), ...
    "official_l_update_closed",lUpdateRelativeError<=numericTolerance, ...
    "official_z_update_closed",zUpdateRelativeError<=numericTolerance, ...
    "gap_decomposition_closed",gapClosureRelative<=numericTolerance, ...
    "item_decomposition_closed", ...
        max(elementClosureRelative)<=numericTolerance, ...
    "constraint_family_summary_closed",constraintFamilyClosure, ...
    "asset_type_summary_closed",assetTypeClosure, ...
    "top20_traceable",topTraceable, ...
    "common_step_closed", ...
        counterfactual.closure_relative_error<=numericTolerance, ...
    "common_step_strictly_positive",counterfactual.strictly_positive, ...
    "counterfactual_read_only",counterfactual.read_only && ...
        ~counterfactual.used_for_official_state_update, ...
    "official_gap_matches_linearizations", ...
        gap_matches(linearizationBefore,gapBefore) && ...
        gap_matches(linearizationAfter,gapAfter));
checkValues = struct2cell(checks);

audit = struct();
audit.iteration = iteration;
audit.linearization_identity_before = linearizationBefore.identity;
audit.linearization_identity_after = linearizationAfter.identity;
audit.decomposition = decomposition;
audit.delta_by_inequality = deltaByInequality;
audit.top20 = top20;
audit.constraint_family_summary = constraintFamilySummary;
audit.asset_type_summary = assetTypeSummary;
audit.centrality_statistics = centralityStatistics;
audit.vector_scale_statistics = vectorScaleStatistics;
audit.group_scale_statistics = groupScaleStatistics;
audit.counterfactual = counterfactual;
audit.checks = checks;
audit.all_pass = all(cellfun(@(value)isequal(value,true),checkValues));
end

function validate_inputs(before,after,direction)
requiredLinearization = ["identity","l","z","mu", ...
    "complementarity_gap","objective","r_eq","r_dual","index"];
for field = requiredLinearization
    assert(isfield(before,field) && isfield(after,field), ...
        "stageA4:audit:MissingLinearizationField", ...
        "Both linearizations require field %s.",field);
end
for field = ["xi","y","l","z"]
    assert(isfield(direction,field), ...
        "stageA4:audit:MissingDirectionField", ...
        "direction.%s is required.",field);
end
assert(isfield(before.objective,"gradient") && ...
    isfield(after.objective,"gradient"), ...
    "stageA4:audit:MissingObjectiveGradient", ...
    "Both objective structures require a gradient.");
assert(isfield(before.index,"variable_index") && ...
    isfield(before.index,"constraint_index") && ...
    isfield(after.index,"variable_index") && ...
    isfield(after.index,"constraint_index"), ...
    "stageA4:audit:MissingCanonicalIndex", ...
    "Both linearizations require canonical variable and constraint tables.");

beforeConstraints = before.index.constraint_index;
afterConstraints = after.index.constraint_index;
beforeTypes = string(beforeConstraints.constraint_type);
afterTypes = string(afterConstraints.constraint_type);
nInequality = nnz(beforeTypes=="inequality");
nEquality = nnz(beforeTypes=="equality");
nVariable = height(before.index.variable_index);
assert(nInequality>0 && nEquality>0 && nVariable>0 && ...
    nnz(afterTypes=="inequality")==nInequality && ...
    nnz(afterTypes=="equality")==nEquality, ...
    "stageA4:audit:IndexCounts", ...
    "Before/after canonical index counts must agree and be nonzero.");
assert(isequal(string(beforeConstraints.constraint_id), ...
    string(afterConstraints.constraint_id)) && ...
    isequal(before.index.variable_index.global_index_start, ...
    after.index.variable_index.global_index_start), ...
    "stageA4:audit:IndexChanged", ...
    "The canonical constraint and variable ordering changed.");
assert(numel(before.l)==nInequality && numel(before.z)==nInequality && ...
    numel(after.l)==nInequality && numel(after.z)==nInequality && ...
    numel(direction.l)==nInequality && numel(direction.z)==nInequality, ...
    "stageA4:audit:InequalityDimension", ...
    "Inequality states and directions must follow canonical ordering.");
assert(numel(direction.xi)==nVariable && numel(direction.y)==nEquality && ...
    numel(before.objective.gradient)==nVariable && ...
    numel(after.objective.gradient)==nVariable && ...
    numel(before.r_dual)==nVariable && numel(after.r_dual)==nVariable && ...
    numel(before.r_eq)==nEquality && numel(after.r_eq)==nEquality, ...
    "stageA4:audit:ResidualDimension", ...
    "Directions, gradients, and residuals must follow canonical ordering.");
assert(before.mu>0 && after.mu>0 && ...
    all(before.l>0) && all(before.z>0) && ...
    all(after.l>0) && all(after.z>0), ...
    "stageA4:audit:NonpositiveInteriorState", ...
    "Both official states must remain strictly interior.");
end

function summary = contribution_summary( ...
        iteration,groupValues,actual,predicted,groupKind)
groups = sort(unique(groupValues));
nGroup = numel(groups);
iterationColumn = repmat(iteration,nGroup,1);
groupKindColumn = repmat(string(groupKind),nGroup,1);
count = zeros(nGroup,1);
positiveCount = zeros(nGroup,1);
negativeCount = zeros(nGroup,1);
zeroCount = zeros(nGroup,1);
positiveContribution = zeros(nGroup,1);
negativeContribution = zeros(nGroup,1);
netContribution = zeros(nGroup,1);
predictedNetContribution = zeros(nGroup,1);
closureError = zeros(nGroup,1);
closureRelativeError = zeros(nGroup,1);
for k = 1:nGroup
    mask = groupValues==groups(k);
    values = actual(mask);
    predictedValues = predicted(mask);
    count(k) = nnz(mask);
    positiveCount(k) = nnz(values>0);
    negativeCount(k) = nnz(values<0);
    zeroCount(k) = nnz(values==0);
    positiveContribution(k) = sum(values(values>0));
    negativeContribution(k) = sum(values(values<0));
    netContribution(k) = sum(values);
    predictedNetContribution(k) = sum(predictedValues);
    closureError(k) = netContribution(k)-predictedNetContribution(k);
    scale = max([1,abs(netContribution(k)), ...
        abs(predictedNetContribution(k))]);
    closureRelativeError(k) = abs(closureError(k))/scale;
end
summary = table(iterationColumn,groupKindColumn,groups,count, ...
    positiveCount,negativeCount,zeroCount,positiveContribution, ...
    negativeContribution,netContribution,predictedNetContribution, ...
    closureError,closureRelativeError, ...
    'VariableNames',{'iteration','group_kind','group_name', ...
    'inequality_count','positive_count','negative_count','zero_count', ...
    'positive_contribution','negative_contribution','net_contribution', ...
    'predicted_net_contribution','closure_error', ...
    'closure_relative_error'});
end

function passed = summary_closure(summary,totalDelta,totalCount)
net = sum(summary.net_contribution);
scale = max([1,abs(net),abs(totalDelta)]);
passed = sum(summary.inequality_count)==totalCount && ...
    sum(summary.positive_count+summary.negative_count+ ...
        summary.zero_count)==totalCount && ...
    abs(net-totalDelta)/scale<=2048*eps && ...
    max(summary.closure_relative_error)<=2048*eps;
end

function row = distribution_row(iteration,stateName,metricName,values)
values = values(:);
minimumValue = min(values);
medianValue = median(values);
p95Value = percentile95(values);
maximumValue = max(values);
meanValue = mean(values);
standardDeviation = std(values,1);
if meanValue==0
    coefficientOfVariation = Inf;
else
    coefficientOfVariation = standardDeviation/abs(meanValue);
end
if minimumValue==0
    maximumToMinimumRatio = Inf;
else
    maximumToMinimumRatio = maximumValue/minimumValue;
end
if medianValue==0
    p95ToMedianRatio = Inf;
else
    p95ToMedianRatio = p95Value/medianValue;
end
row = table(iteration,string(stateName),string(metricName),numel(values), ...
    minimumValue,medianValue,p95Value,maximumValue,meanValue, ...
    maximumValue-minimumValue,standardDeviation,coefficientOfVariation, ...
    maximumToMinimumRatio,p95ToMedianRatio, ...
    'VariableNames',{'iteration','state','metric','count','minimum', ...
    'median','p95','maximum','mean','range','standard_deviation', ...
    'coefficient_of_variation','maximum_to_minimum_ratio', ...
    'p95_to_median_ratio'});
end

function value = percentile95(values)
sortedValues = sort(values(:));
n = numel(sortedValues);
position = 1+0.95*(n-1);
lowerPosition = floor(position);
upperPosition = ceil(position);
if lowerPosition==upperPosition
    value = sortedValues(lowerPosition);
else
    weight = position-lowerPosition;
    value = (1-weight)*sortedValues(lowerPosition)+ ...
        weight*sortedValues(upperPosition);
end
end

function row = scale_row(iteration,quantity,stateName,values)
statistics = scale_statistics(values);
row = table(iteration,string(quantity),string(stateName), ...
    statistics.count,statistics.nonzero_count,statistics.negative_count, ...
    statistics.zero_count,statistics.positive_count, ...
    statistics.minimum_value,statistics.maximum_value, ...
    statistics.minimum_absolute_nonzero,statistics.median_absolute, ...
    statistics.p95_absolute,statistics.maximum_absolute, ...
    statistics.minimum_order_of_magnitude, ...
    statistics.maximum_order_of_magnitude, ...
    statistics.order_of_magnitude_span, ...
    'VariableNames',{'iteration','quantity','state','count', ...
    'nonzero_count','negative_count','zero_count','positive_count', ...
    'minimum_value','maximum_value','minimum_absolute_nonzero', ...
    'median_absolute','p95_absolute','maximum_absolute', ...
    'minimum_order_of_magnitude','maximum_order_of_magnitude', ...
    'order_of_magnitude_span'});
end

function statistics = scale_statistics(values)
values = values(:);
absoluteValues = abs(values);
nonzeroValues = absoluteValues(absoluteValues>0);
if isempty(nonzeroValues)
    minimumAbsoluteNonzero = NaN;
    minimumOrder = NaN;
    maximumOrder = NaN;
    orderSpan = NaN;
else
    minimumAbsoluteNonzero = min(nonzeroValues);
    minimumOrder = floor(log10(minimumAbsoluteNonzero));
    maximumOrder = floor(log10(max(nonzeroValues)));
    orderSpan = maximumOrder-minimumOrder;
end
statistics = struct( ...
    "count",numel(values), ...
    "nonzero_count",numel(nonzeroValues), ...
    "negative_count",nnz(values<0), ...
    "zero_count",nnz(values==0), ...
    "positive_count",nnz(values>0), ...
    "minimum_value",min(values), ...
    "maximum_value",max(values), ...
    "minimum_absolute_nonzero",minimumAbsoluteNonzero, ...
    "median_absolute",median(absoluteValues), ...
    "p95_absolute",percentile95(absoluteValues), ...
    "maximum_absolute",max(absoluteValues), ...
    "minimum_order_of_magnitude",minimumOrder, ...
    "maximum_order_of_magnitude",maximumOrder, ...
    "order_of_magnitude_span",orderSpan);
end

function [groups,assetTypes,members] = canonical_variable_groups(variables)
nVariable = height(variables);
groups = strings(nVariable,1);
assetTypes = string(variables.asset_type);
members = string(variables.variable_name);
for k = 1:nVariable
    if variables.day(k)==0 && variables.hour(k)==0
        scope = "global_capacity";
        members(k) = "capacity";
    elseif variables.day(k)>0 && variables.hour(k)==0
        scope = "daily_capacity_copy";
        members(k) = "capacity_copy";
    else
        scope = "hourly";
    end
    groups(k) = scope+"|"+assetTypes(k)+"|"+members(k);
end
end

function rows = grouped_scale_rows(iteration,quantity,stateName,groupKind, ...
        groupValues,assetTypes,members,values)
groups = sort(unique(groupValues));
nGroup = numel(groups);
records = repmat(empty_group_scale_record(),nGroup,1);
for k = 1:nGroup
    mask = groupValues==groups(k);
    statistics = scale_statistics(values(mask));
    record = empty_group_scale_record();
    record.iteration = iteration;
    record.quantity = char(quantity);
    record.state = char(stateName);
    record.group_kind = char(groupKind);
    record.group_name = char(groups(k));
    record.asset_type = char(unique_scalar_string(assetTypes(mask)));
    record.member_name = char(unique_scalar_string(members(mask)));
    statisticFields = string(fieldnames(statistics));
    for field = statisticFields.'
        record.(field) = statistics.(field);
    end
    records(k) = record;
end
rows = struct2table(records);
rows.quantity = string(rows.quantity);
rows.state = string(rows.state);
rows.group_kind = string(rows.group_kind);
rows.group_name = string(rows.group_name);
rows.asset_type = string(rows.asset_type);
rows.member_name = string(rows.member_name);
end

function record = empty_group_scale_record()
record = struct("iteration",0,"quantity","","state","", ...
    "group_kind","","group_name","","asset_type","", ...
    "member_name","","count",0,"nonzero_count",0, ...
    "negative_count",0,"zero_count",0,"positive_count",0, ...
    "minimum_value",0,"maximum_value",0, ...
    "minimum_absolute_nonzero",0,"median_absolute",0, ...
    "p95_absolute",0,"maximum_absolute",0, ...
    "minimum_order_of_magnitude",0, ...
    "maximum_order_of_magnitude",0,"order_of_magnitude_span",0);
end

function value = unique_scalar_string(values)
uniqueValues = unique(values);
if isscalar(uniqueValues)
    value = uniqueValues;
else
    value = strjoin(sort(uniqueValues),"+");
end
end

function passed = top20_traceable(top20,deltaTable,delta,index)
positiveRows = find(delta>0);
if isempty(positiveRows)
    expectedRows = zeros(0,1);
else
    [~,order] = sortrows([-delta(positiveRows),index(positiveRows)],[1,2]);
    expectedRows = positiveRows(order(1:min(20,numel(order))));
end
passed = height(top20)==numel(expectedRows) && ...
    isequal(top20.inequality_index,expectedRows) && ...
    isequal(top20.delta_i,deltaTable.delta_i(expectedRows)) && ...
    isequal(top20.rank,(1:numel(expectedRows)).');
end

function matches = gap_matches(linearization,gap)
scale = max([1,abs(gap),abs(linearization.complementarity_gap)]);
matches = abs(gap-linearization.complementarity_gap)/scale<=16*eps;
end
