function linearization = build_stage_a4_scaled_objective_linearization( ...
        state,data,index,config,diagnosticChainId)
%BUILD_STAGE_A4_SCALED_OBJECTIVE_LINEARIZATION Isolated objective-unit audit.
%
% The formal A4 model is built and validated first.  This diagnostic copy
% changes only the common positive scalar unit of the investment objective
% and rebuilds r_dual from the caller's unchanged multiplier state.  It is
% not reachable from the default A4 path.

arguments
    state (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    diagnosticChainId (1,1) string {mustBeMember( ...
        diagnosticChainId, ...
        ["A4-2D-2A-SCALED-5","A4-2D-2A-SCALED-20", ...
        "A4-2D-2A-R1-SCALED-STABLE-V2"])}
end

base = build_stage_a4_linearization(state,data,index,config);
qGlobal = base.maps.q_global(:);
assert(numel(qGlobal)==14 && numel(unique(qGlobal))==14, ...
    "stageA4:a42d2a:GlobalCapacityMap", ...
    "Objective unitization requires the canonical 14 global capacities.");

originalGradient = base.objective.gradient;
originalValue = base.objective.value;
capacityGradient = originalGradient(qGlobal);
scaleFactor = max(abs(capacityGradient));
assert(isscalar(scaleFactor) && isfinite(scaleFactor) && scaleFactor>0 && ...
    all(isfinite(capacityGradient)), ...
    "stageA4:a42d2a:ObjectiveScale", ...
    "The objective scale derived from the actual capacity gradient "+ ...
    "must be finite and strictly positive.");
outsideQ = true(numel(originalGradient),1);
outsideQ(qGlobal) = false;
assert(all(originalGradient(outsideQ)==0), ...
    "stageA4:a42d2a:ObjectiveSupport", ...
    "The frozen Stage-A investment objective must be supported only on q.");

linearization = base;
linearization.objective.original_gradient = originalGradient;
linearization.objective.original_value = originalValue;
linearization.objective.gradient = originalGradient/scaleFactor;
linearization.objective.value = originalValue/scaleFactor;
linearization.r_dual = linearization.objective.gradient+ ...
    linearization.A.'*linearization.state.y+ ...
    linearization.G.'*linearization.state.z;
linearization.base_identity = base.identity;
linearization.identity = base.identity+ ...
    "|objective_scale=positive_scalar_unitization|factor="+ ...
    string(compose("%.17g",scaleFactor))+ ...
    "|diagnostic_chain="+diagnosticChainId;
linearization.objective_scale = struct( ...
    "enabled",true, ...
    "mode","positive_scalar_unitization", ...
    "scale_source","max_abs_global_capacity_gradient", ...
    "factor",scaleFactor, ...
    "diagnostic_chain_id",diagnosticChainId, ...
    "base_identity",base.identity, ...
    "original_gradient",originalGradient, ...
    "scaled_gradient",linearization.objective.gradient, ...
    "original_value",originalValue, ...
    "scaled_value",linearization.objective.value);
linearization.diagnostic_objective_chain_id = diagnosticChainId;
linearization.residual_definitions.r_dual = ...
    "scaled_gradient+A'*y+G'*z";
linearization.residual_definitions.r_dual_original_mapped = ...
    "original_gradient+A'*(S*y)+G'*(S*z)";

assert(isequal(linearization.H,base.H) && ...
    isequal(linearization.A,base.A) && ...
    isequal(linearization.G,base.G) && ...
    isequal(linearization.constraints.eq_offset, ...
        base.constraints.eq_offset) && ...
    isequal(linearization.constraints.ineq_offset, ...
        base.constraints.ineq_offset) && ...
    isequal(linearization.state,base.state) && ...
    isequal(linearization.r_eq,base.r_eq) && ...
    isequal(linearization.r_ineq,base.r_ineq) && ...
    isequal(linearization.r_comp,base.r_comp) && ...
    isequal(linearization.l,base.l) && ...
    isequal(linearization.z,base.z) && ...
    linearization.mu==base.mu && ...
    isequal(linearization.capacity_parameters, ...
        base.capacity_parameters), ...
    "stageA4:a42d2a:StructuralInvariance", ...
    "Objective unitization changed a frozen state, matrix, constraint, "+ ...
    "residual, or capacity parameter.");
end
