function metrics = compute_stage_a4_unitized_metrics(linearization)
%COMPUTE_STAGE_A4_UNITIZED_METRICS Rebuild A4-3 metrics from one state.
%
% The stopping coordinate is the positive-scalar-unitized KKT system.
% Original-objective values and multipliers are reported only through the
% exact positive scalar mapping.  mean(l.*z) is intentionally labelled as
% scaled, not dimensionless.

arguments
    linearization (1,1) struct
end
assert(isfield(linearization,"objective_scale") && ...
    linearization.objective_scale.enabled && ...
    string(linearization.objective_scale.mode)== ...
        "positive_scalar_unitization", ...
    "stageA4:a43:MetricCoordinate", ...
    "A4-3 metrics require the positive-scalar-unitized linearization.");

state = linearization.state;
scaleFactor = linearization.objective_scale.factor;
originalGradient = linearization.objective.original_gradient;
scaledGradient = linearization.objective.gradient;
mappedY = scaleFactor*state.y;
mappedZ = scaleFactor*state.z;
rDualMapped = scaleFactor*linearization.r_dual;
rDualOriginalRebuilt = originalGradient+linearization.A.'*mappedY+ ...
    linearization.G.'*mappedZ;
% Evaluate the mapped residual through one positive-scalar multiplication
% of the already assembled scaled residual.  This is the exact algebraic
% map and avoids a false late-iteration failure caused by cancellation when
% independently summing an O(1e8) original-gradient term with multiplier
% products.  Keep the independently rebuilt value as a diagnostic so that
% any floating-point reconstruction drift remains visible in the artifact.
rDualOriginal = scaleFactor*linearization.r_dual;
rCompMapped = scaleFactor*linearization.r_comp;
muMapped = scaleFactor*linearization.mu;
rCompOriginalRebuilt = state.l.*mappedZ-muMapped;
ineqFunction = linearization.G*state.xi+ ...
    linearization.constraints.ineq_offset;
rawGap = state.l.'*state.z;
meanGap = mean(state.l.*state.z);
mappedRawGap = scaleFactor*rawGap;
mappedMeanGap = scaleFactor*meanGap;

eqScale = max(1,norm(linearization.A*state.xi,inf)+ ...
    norm(linearization.constraints.eq_offset,inf));
dualScaledScale = max(1,norm(scaledGradient,inf)+ ...
    norm(linearization.A.'*state.y,inf)+ ...
    norm(linearization.G.'*state.z,inf));
dualOriginalScale = max(1,norm(originalGradient,inf)+ ...
    norm(linearization.A.'*mappedY,inf)+ ...
    norm(linearization.G.'*mappedZ,inf));
objectiveOriginal = linearization.objective.original_value;
objectiveScaled = linearization.objective.value;

metrics = struct( ...
    "convergence_coordinate","positive_scalar_unitized_kkt", ...
    "objective_scale_factor",scaleFactor, ...
    "objective_scaled",objectiveScaled, ...
    "objective_original",objectiveOriginal, ...
    "r_eq_inf",norm(linearization.r_eq,inf), ...
    "r_ineq_inf",norm(linearization.r_ineq,inf), ...
    "r_dual_scaled_inf",norm(linearization.r_dual,inf), ...
    "r_dual_original_mapped_inf",norm(rDualMapped,inf), ...
    "r_comp_scaled_inf",norm(linearization.r_comp,inf), ...
    "mean_lz_scaled",meanGap, ...
    "ltz_scaled",rawGap, ...
    "mean_lz_original_mapped",mappedMeanGap, ...
    "gap_original_mapped",mappedRawGap, ...
    "ltz_original_mapped",mappedRawGap, ...
    "mu_scaled",linearization.mu, ...
    "mu_original_mapped",muMapped, ...
    "eta_eq",norm(linearization.r_eq,inf)/eqScale, ...
    "eta_dual",norm(rDualOriginal,inf)/dualOriginalScale, ...
    "eta_dual_scaled",norm(linearization.r_dual,inf)/dualScaledScale, ...
    "eta_gap",mappedRawGap/max(1,abs(objectiveOriginal)), ...
    "eta_gap_scaled",rawGap/max(1,abs(objectiveScaled)), ...
    "physical_inequality_violation",max(max(ineqFunction,0)), ...
    "physical_inequality_scale",max(1,norm(ineqFunction,inf)), ...
    "min_l",min(state.l), ...
    "min_z",min(state.z), ...
    "mapped_y_inf",norm(mappedY,inf), ...
    "mapped_z_inf",norm(mappedZ,inf), ...
    "dual_mapping_relative_error",relative_inf_error( ...
        rDualMapped,rDualOriginal), ...
    "dual_mapping_rebuild_relative_error",relative_inf_error( ...
        rDualMapped,rDualOriginalRebuilt), ...
    "complementarity_mapping_relative_error",relative_inf_error( ...
        rCompMapped,rCompOriginalRebuilt), ...
    "all_finite",all(isfinite([state.xi;state.y;state.l;state.z; ...
        linearization.r_eq;linearization.r_ineq; ...
        linearization.r_dual;linearization.r_comp;rDualOriginal; ...
        rDualOriginalRebuilt])));

assert(scaleFactor>0 && isfinite(scaleFactor) && ...
    metrics.dual_mapping_relative_error<=2048*eps && ...
    metrics.complementarity_mapping_relative_error<=2048*eps && ...
    metrics.mean_lz_scaled>0 && metrics.ltz_scaled>0 && ...
    metrics.all_finite, ...
    "stageA4:a43:MetricMapping", ...
    "The A4-3 scaled/original metric mapping is inconsistent.");
end

function value = relative_inf_error(actual,expected)
value = norm(actual-expected,inf)/ ...
    max([1,norm(actual,inf),norm(expected,inf)]);
end
