function acceptance = evaluate_stage_a2_acceptance_facts(projectRoot,data, ...
        index,verification)
%EVALUATE_STAGE_A2_ACCEPTANCE_FACTS Evaluate exactly the six frozen A2 gates.

arguments
    projectRoot (1,1) string
    data (1,1) struct
    index (1,1) struct
    verification (1,1) struct
end
acceptance = initialize_stage_a2_acceptance(projectRoot);

dimension = verification.direct.kkt.dimension;
acceptance = set_boolean(acceptance,"SA2-MAT-001",dimension==2749, ...
    string(dimension),"equals 2749","matrices/matrix_manifest.csv");

map = index.fixed_zero_map;
required = ["day","hour","asset_type","asset_id","variable_name", ...
    "fixed_value","fixed_direction_value","reason","inequality_status"];
assert(all(ismember(required,string(map.Properties.VariableNames))), ...
    "stageA2:acceptance:FixedZeroSchema", ...
    "fixed_zero_map is missing a required exact-removal field.");
physical = verification.physical.fixed_zero_audit;
allExact = physical.values_exact_zero && physical.directions_exact_zero && ...
    all(map.fixed_value==0) && all(map.fixed_direction_value==0) && ...
    all(string(map.reason)=="zero_availability") && ...
    all(string(map.inequality_status)=="NOT_APPLICABLE_BOTH_BOUNDS");

windMask = map.day==14 & map.hour==19 & ...
    string(map.asset_type)=="wind" & map.asset_id==3 & ...
    string(map.variable_name)=="PW";
windActive = active_variable_present(index.variable_index,14,19,"wind",3,"PW");
windDataZero = data.timeseries.windAvailability(14,19,3)==0;
windPassed = height(map)==61 && nnz(windMask)==1 && ~windActive && ...
    windDataZero && allExact;
acceptance = set_boolean(acceptance,"SA2-ZERO-001",windPassed, ...
    "fixed_zero_total="+height(map)+"; day14_hour19_wind3_rows="+ ...
    nnz(windMask)+"; active_variable_present="+string(windActive)+ ...
    "; max_value="+compose("%.17g",physical.maximum_absolute_value)+ ...
    "; max_direction="+compose("%.17g",physical.maximum_absolute_direction), ...
    "one exact-zero wind-3 row at hour 19; no active variable or bounds", ...
    "indices/fixed_zero_map.csv; indices/fixed_zero_recovery_audit.csv");

availability = squeeze(data.timeseries.solarAvailability(14,1:24,:));
[hourPosition,assetId] = find(availability==0);
expectedSolarKeys = sort(compose("14|%d|solar|%d|PP",hourPosition,assetId));
solarRows = map(string(map.asset_type)=="solar",:);
actualSolarKeys = sort(compose("%d|%d|%s|%d|%s",solarRows.day, ...
    solarRows.hour,string(solarRows.asset_type),solarRows.asset_id, ...
    string(solarRows.variable_name)));
solarActiveAbsent = true;
for row = 1:height(solarRows)
    solarActiveAbsent = solarActiveAbsent && ~active_variable_present( ...
        index.variable_index,solarRows.day(row),solarRows.hour(row), ...
        "solar",solarRows.asset_id(row),"PP");
end
solarPassed = numel(expectedSolarKeys)==60 && height(solarRows)==60 && ...
    isequal(actualSolarKeys,expectedSolarKeys) && solarActiveAbsent && allExact;
acceptance = set_boolean(acceptance,"SA2-ZERO-002",solarPassed, ...
    "data_exact_zero="+numel(expectedSolarKeys)+"; mapped_solar="+ ...
    height(solarRows)+"; active_absent="+string(solarActiveAbsent)+ ...
    "; all_recovered_exact_zero="+string(allExact), ...
    "60 exact-zero nighttime solar rows; each variable and both bounds removed", ...
    "indices/fixed_zero_map.csv; indices/hourly_renewable_activity.csv; "+ ...
    "indices/fixed_zero_recovery_audit.csv");

directionError = verification.audit.direction_relative_error;
acceptance = set_boolean(acceptance,"SA2-EQ-001", ...
    isfinite(directionError) && directionError<=1e-10, ...
    compose("%.17g",directionError),"<= 1e-10", ...
    "iterations/direction_comparison.csv");
recursiveResidual = verification.audit.recursive_kkt_relative_residual;
acceptance = set_boolean(acceptance,"SA2-EQ-002", ...
    isfinite(recursiveResidual) && recursiveResidual<=1e-10, ...
    compose("%.17g",recursiveResidual),"<= 1e-10", ...
    "iterations/residual_summary.csv");

[boundaryPassed,boundaryActual] = boundary_contract_passes(index, ...
    verification.linearization);
acceptance = set_boolean(acceptance,"SA2-PHY-001",boundaryPassed, ...
    boundaryActual, ...
    "formal day 14 SOC chain; exactly two terminal equations at hour 24", ...
    "indices/soc_boundary_audit.csv; indices/constraint_index.csv");
end

function present = active_variable_present(variables,day,hour,assetType,assetId,name)
present = any(variables.day==day & variables.hour==hour & ...
    string(variables.asset_type)==assetType & variables.asset_id==assetId & ...
    string(variables.variable_name)==name & logical(variables.active_flag));
end

function [passed,actual] = boundary_contract_passes(index,lin)
links = index.soc_link_map;
constraints = index.constraint_index;
passed = height(links)==48 && all(links.day==14) && ...
    ~any(index.variable_index.day==14 & index.variable_index.hour==0 & ...
    string(index.variable_index.variable_name)=="SOC");
for hour = 1:24
    for storage = 1:2
        link = links(links.hour==hour & links.storage_id==storage,:);
        dynamic = constraints(constraints.day==14 & constraints.hour==hour & ...
            string(constraints.constraint_type)=="equality" & ...
            string(constraints.constraint_name)=="soc_dynamics" & ...
            constraints.asset_id==storage,:);
        rowPassed = height(link)==1 && height(dynamic)==1 && ...
            link.current_soc_global_index>0 && ...
            lin.A(dynamic.global_row,link.current_soc_global_index)==1;
        if rowPassed && hour==1
            rowPassed = isnan(link.predecessor_hour) && ...
                link.predecessor_soc_global_index==0 && ...
                link.initial_energy_fraction==0.5 && ...
                lin.A(dynamic.global_row,lin.maps.q_day(12+storage))==-0.5;
        elseif rowPassed
            rowPassed = link.predecessor_hour==hour-1 && ...
                link.predecessor_soc_global_index>0 && ...
                lin.A(dynamic.global_row,link.predecessor_soc_global_index)==-1 && ...
                lin.A(dynamic.global_row,lin.maps.q_day(12+storage))==0;
        end
        passed = passed && rowPassed;
    end
end
terminal = constraints(constraints.day==14 & ...
    string(constraints.constraint_type)=="equality" & ...
    string(constraints.constraint_name)=="terminal_soc",:);
terminalFlags = links(logical(links.terminal_equality),:);
passed = passed && height(terminal)==2 && all(terminal.hour==24) && ...
    height(terminalFlags)==2 && all(terminalFlags.hour==24) && ...
    all(terminalFlags.terminal_energy_fraction==0.5);
for storage = 1:2
    row = terminal(terminal.asset_id==storage,:);
    link = links(links.hour==24 & links.storage_id==storage,:);
    passed = passed && height(row)==1 && height(link)==1 && ...
        lin.A(row.global_row,link.current_soc_global_index)==1 && ...
        lin.A(row.global_row,lin.maps.q_day(12+storage))==-0.5;
end
actual = "soc_links="+height(links)+"; dynamics="+ ...
    nnz(string(constraints.constraint_name)=="soc_dynamics" & ...
    constraints.day==14)+"; terminal_total="+height(terminal)+ ...
    "; terminal_hours="+mat2str(unique(terminal.hour).');
end

function acceptance = set_boolean(acceptance,id,passed,actual,comparison,evidence)
if passed, status="PASS"; else, status="FAIL"; end
acceptance = set_stage_a2_acceptance_result(acceptance,id,status, ...
    actual,comparison,evidence);
end
