function acceptance = evaluate_stage_a3_acceptance_facts(projectRoot,verification)
%EVALUATE_STAGE_A3_ACCEPTANCE_FACTS Evaluate exactly the six frozen A3 gates.

arguments
    projectRoot (1,1) string
    verification (1,1) struct
end
acceptance = initialize_stage_a3_acceptance(projectRoot);
recursive = verification.recursive;
direct = verification.direct;
audit = verification.audit;
physical = verification.physical.fixed_zero_audit;
assert(physical.count==height(verification.linearization.index.fixed_zero_map)&& ...
    physical.values_exact_zero&&physical.directions_exact_zero&& ...
    physical.maximum_absolute_value==0&&physical.maximum_absolute_direction==0, ...
    "stageA3:acceptance:PhysicalFixedZero", ...
    "Acceptance requires actual compact-to-physical exact-zero recovery.");

dimension = direct.kkt.dimension;
acceptance = set_boolean(acceptance,"SA3-MAT-001",dimension==18836, ...
    string(dimension),"equals 18836","matrices/matrix_manifest.csv");

responses = recursive.daily_responses;
dayPassed = isstruct(responses) && numel(responses)==7;
days = nan(1,numel(responses));
for k=1:numel(responses)
    response=responses(k);
    fields=["day_id","S","c","beta","gamma"];
    rowPassed=all(isfield(response,cellstr(fields)));
    if rowPassed
        days(k)=double(response.day_id);
        rowPassed=isequal(size(response.S),[14 14]) && ...
            isequal(size(response.c),[14 1]) && ...
            isequal(size(response.beta),[14 1]) && ...
            isequal(size(response.gamma),[14 1]);
    end
    dayPassed=dayPassed && rowPassed;
end
dayPassed=dayPassed && isequal(days,14:20);
actual="count="+numel(responses)+"; day_ids="+mat2str(days)+ ...
    "; S=14x14; c,beta,gamma=14x1";
acceptance = set_boolean(acceptance,"SA3-DAY-001",dayPassed,actual, ...
    "seven sorted day responses for days 14 through 20", ...
    "matrices/daily_response_summary.csv; matrices/daily_responses.mat");

corePassed=isequal(size(recursive.core.matrix),[16 16]) && ...
    isequal(size(recursive.core.rhs),[16 1]);
acceptance = set_boolean(acceptance,"SA3-CORE-001",corePassed, ...
    size_text(recursive.core.matrix),"equals 16x16", ...
    "matrices/global_core_triplets.csv; matrices/daily_aggregation.mat");

directionError=audit.direction_relative_error;
acceptance = set_boolean(acceptance,"SA3-EQ-001", ...
    isfinite(directionError) && directionError<=1e-10, ...
    compose("%.17g",directionError),"<= 1e-10", ...
    "iterations/direction_comparison.csv");
recursiveResidual=audit.recursive_kkt_relative_residual;
acceptance = set_boolean(acceptance,"SA3-EQ-002", ...
    isfinite(recursiveResidual) && recursiveResidual<=1e-10, ...
    compose("%.17g",recursiveResidual),"<= 1e-10", ...
    "iterations/residual_summary.csv");

aggregation=recursive.aggregation;
required=["day_ids_sorted","S_sum","gamma_sum", ...
    "order_invariant_S_relative_error", ...
    "order_invariant_gamma_relative_error","order_invariant_passed"];
sumPassed=all(isfield(aggregation,cellstr(required)));
if sumPassed
    sError=double(aggregation.order_invariant_S_relative_error);
    gError=double(aggregation.order_invariant_gamma_relative_error);
    sumPassed=isequal(double(aggregation.day_ids_sorted(:).'),14:20) && ...
        isequal(size(aggregation.S_sum),[14 14]) && ...
        isequal(size(aggregation.gamma_sum),[14 1]) && ...
        logical(aggregation.order_invariant_passed) && ...
        isfinite(sError) && isfinite(gError) && ...
        sError<=1e-12 && gError<=1e-12;
    sumActual="sorted_days="+mat2str(double(aggregation.day_ids_sorted(:).'))+ ...
        "; S_relative_error="+compose("%.17g",sError)+ ...
        "; gamma_relative_error="+compose("%.17g",gError);
else
    sumActual="missing deterministic aggregation evidence";
end
acceptance = set_boolean(acceptance,"SA3-SUM-001",sumPassed,sumActual, ...
    "sort by day_id 14..20; shuffled-input aggregation identical", ...
    "matrices/daily_aggregation_audit.csv; matrices/daily_aggregation.mat");
end

function acceptance = set_boolean(acceptance,id,passed,actual,comparison,evidence)
if passed, status="PASS"; else, status="FAIL"; end
acceptance=set_stage_a3_acceptance_result(acceptance,id,status, ...
    actual,comparison,evidence);
end

function value = size_text(matrix)
value=compose("%dx%d",size(matrix,1),size(matrix,2));
end
