function result = execute_stage_a4_iteration( ...
        stateBefore,data,index,config,options)
%EXECUTE_STAGE_A4_ITERATION Execute one reusable A4 primal-dual transition.
%
% The caller owns initialization and iteration count.  This function always
% consumes the caller's explicit state.l, obtains the official direction by
% recursive reduction, performs an independent complete sparse-KKT audit,
% applies the explicitly selected step strategy, and rebuilds the shared
% linearization from the updated explicit state.  The default independent
% strategy is the frozen A4 rule.  common_min is permitted only for the
% isolated A4-2C-B experiment.  This function has no run or filesystem
% side effects.

arguments
    stateBefore (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.StepStrategy (1,1) string {mustBeMember( ...
        options.StepStrategy,["independent","common_min"])} = "independent"
    options.ObjectiveScaleMode (1,1) string {mustBeMember( ...
        options.ObjectiveScaleMode, ...
        ["unscaled","positive_scalar_unitization"])} = "unscaled"
    options.DiagnosticObjectiveChainId (1,1) string = ""
    options.EqualityResidualReferenceScale (1,1) double = NaN
    options.DualResidualReferenceScale (1,1) double = NaN
end

validate_iteration_inputs(stateBefore,index,config,options.StepStrategy, ...
    options.ObjectiveScaleMode,options.DiagnosticObjectiveChainId, ...
    options.EqualityResidualReferenceScale, ...
    options.DualResidualReferenceScale);
totalTimer = tic;

timer = tic;
linearizationBefore = build_selected_linearization( ...
    stateBefore,data,index,config,options.ObjectiveScaleMode, ...
    options.DiagnosticObjectiveChainId);
timing.linearization_before_seconds = toc(timer);
assert_explicit_state_consumed(linearizationBefore,stateBefore,"before");

timer = tic;
recursive = solve_stage_a_multiday_recursive_direction( ...
    linearizationBefore, ...
    AssemblyTolerance=config.tolerances.symmetry_relative, ...
    SymmetryTolerance=config.tolerances.symmetry_relative);
timing.recursive_seconds = toc(timer);
timing.recursive_direction_and_reinsertion_seconds = ...
    timing.recursive_seconds;

timer = tic;
direct = solve_stage_a_multiday_full_kkt_direction(linearizationBefore);
timing.full_kkt_audit_seconds = toc(timer);

timer = tic;
audit = verify_stage_a_multiday_direction_equivalence( ...
    direct,recursive,linearizationBefore, ...
    DirectionRelative=config.tolerances.direction_relative_2norm, ...
    RecursiveResidual= ...
        config.tolerances.recursive_full_kkt_relative_residual, ...
    FullResidualPreferred=config.tolerances.direct_preferred, ...
    FullResidualMaximum=config.tolerances.direct_maximum);
timing.direction_equivalence_audit_seconds = toc(timer);

timer = tic;
primalStep = compute_fraction_to_boundary_step( ...
    linearizationBefore.l,recursive.components.l, ...
    config.fraction_to_boundary);
dualStep = compute_fraction_to_boundary_step( ...
    linearizationBefore.z,recursive.components.z, ...
    config.fraction_to_boundary);
primalStep = annotate_limiting_inequality(primalStep,index);
dualStep = annotate_limiting_inequality(dualStep,index);
if options.StepStrategy=="independent"
    appliedAlphaPrimal = primalStep.alpha;
    appliedAlphaDual = dualStep.alpha;
    alphaCommon = min(primalStep.alpha,dualStep.alpha);
    experimental = false;
else
    alphaCommon = min(primalStep.alpha,dualStep.alpha);
    appliedAlphaPrimal = alphaCommon;
    appliedAlphaDual = alphaCommon;
    experimental = true;
end
timing.fraction_to_boundary_seconds = toc(timer);

timer = tic;
stateAfter = update_primal_dual_state( ...
    linearizationBefore.state,recursive.components, ...
    appliedAlphaPrimal,appliedAlphaDual);
stateAfter.iteration_index = linearizationBefore.state.iteration_index+1;
stateAfter.state_revision = linearizationBefore.state.state_revision+1;
stateAfter.newton_direction_number = stateAfter.iteration_index;
stateAfter.completed_newton_direction_count = stateAfter.iteration_index;
timing.state_update_seconds = toc(timer);

timer = tic;
linearizationAfter = build_selected_linearization( ...
    stateAfter,data,index,config,options.ObjectiveScaleMode, ...
    options.DiagnosticObjectiveChainId);
timing.linearization_after_seconds = toc(timer);
assert_explicit_state_consumed(linearizationAfter,stateAfter,"after");

timer = tic;
before = residual_snapshot( ...
    linearizationBefore,config.initialization.centering_sigma);
after = residual_snapshot( ...
    linearizationAfter,config.initialization.centering_sigma);
closure = audit_linear_update(linearizationBefore,linearizationAfter, ...
    recursive.components,appliedAlphaPrimal,appliedAlphaDual, ...
    options.EqualityResidualReferenceScale, ...
    options.DualResidualReferenceScale);
physicalBefore = recover_stage_a_physical_arrays( ...
    linearizationBefore.state.xi,recursive.components.xi,index,data);
physicalAfter = recover_stage_a_physical_arrays( ...
    linearizationAfter.state.xi,recursive.components.xi,index,data);
fixedZero = make_fixed_zero_audit(physicalBefore,physicalAfter);
if options.ObjectiveScaleMode=="positive_scalar_unitization"
    diagnosticClosureMultiplier = 2048;
else
    diagnosticClosureMultiplier = 256;
end
soc = audit_formal_soc_boundaries(index,config,linearizationBefore, ...
    linearizationAfter,recursive.components,appliedAlphaPrimal, ...
    diagnosticClosureMultiplier);
qp5 = audit_qp5_bounds(index,linearizationBefore,linearizationAfter, ...
    recursive.components);
permutationAudit = make_permutation_audit(recursive.partition.permutation);
timing.closure_and_structure_audit_seconds = toc(timer);

allStatesFinite = all(isfinite([linearizationAfter.state.xi; ...
    linearizationAfter.state.y;linearizationAfter.state.l; ...
    linearizationAfter.state.z]));
identitySeparated = linearizationBefore.identity~=linearizationAfter.identity;
fixedZeroPassed = fixedZero.count==config.expected_fixed_zero_count && ...
    fixedZero.values_exact_zero_before && ...
    fixedZero.values_exact_zero_after && ...
    fixedZero.directions_exact_zero && ...
    fixedZero.maximum_absolute_value_after==0 && ...
    fixedZero.maximum_absolute_direction==0;
stepPassed = primalStep.alpha>0 && primalStep.alpha<=1 && ...
    dualStep.alpha>0 && dualStep.alpha<=1 && ...
    appliedAlphaPrimal>0 && appliedAlphaPrimal<=1 && ...
    appliedAlphaDual>0 && appliedAlphaDual<=1 && ...
    min(linearizationAfter.l)>0 && min(linearizationAfter.z)>0;
appliedStep = make_applied_step_audit( ...
    options.StepStrategy,experimental,primalStep,dualStep, ...
    appliedAlphaPrimal,appliedAlphaDual,alphaCommon, ...
    linearizationBefore.state,linearizationAfter.state, ...
    recursive.components);
if options.ObjectiveScaleMode=="positive_scalar_unitization"
    equalityClosurePassed = ...
        closure.equality_linear_update_reference_scaled_error<=2048*eps && ...
        closure.equality_contraction_reference_scaled_error<=2048*eps;
    dualClosurePassed = ...
        closure.dual_linear_update_reference_scaled_error<=2048*eps && ...
        closure.dual_contraction_reference_scaled_error<=2048*eps;
else
    equalityClosurePassed = ...
        closure.equality_linear_update_relative_error<=256*eps && ...
        closure.equality_contraction_relative_error<=256*eps;
    dualClosurePassed = ...
        closure.dual_linear_update_relative_error<=256*eps && ...
        closure.dual_contraction_relative_error<=256*eps;
end
closurePassed = closure.slack_residual_scaled<=256*eps && ...
    equalityClosurePassed && dualClosurePassed && ...
    closure.slack_linear_update_relative_error<=2048*eps && ...
    closure.slack_state_consistency_inf<=16*eps && ...
    after.physical_inequality_violation<= ...
        256*eps*after.physical_inequality_scale && ...
    after.complementarity_gap>0 && isfinite(after.complementarity_gap);
structurePassed = soc.passed && permutationAudit.dimension==4340 && ...
    permutationAudit.is_bijection && permutationAudit.is_nonidentity && ...
    permutationAudit.forward_inverse_composition_exact && ...
    permutationAudit.inverse_forward_composition_exact && ...
    closure.model_matrices_unchanged && identitySeparated;
directionPassed = audit.direction_relative_error<= ...
    config.tolerances.direction_relative_2norm && ...
    audit.recursive_kkt_relative_residual<= ...
    config.tolerances.recursive_full_kkt_relative_residual && ...
    audit.full_kkt_relative_residual<= ...
    config.tolerances.direct_maximum && ...
    audit.passed.full_residual_hard && ...
    audit.passed.no_full_direction_fallback;

checks = struct( ...
    "direction_equivalence",directionPassed, ...
    "positive_fraction_to_boundary",stepPassed, ...
    "applied_step_contract",appliedStep.passed, ...
    "updated_state_finite",allStatesFinite, ...
    "linear_update_closure",closurePassed, ...
    "formal_soc_and_permutation",structurePassed, ...
    "fixed_zero_exact",fixedZeroPassed, ...
    "qp5_semantic_audit",qp5.passed, ...
    "explicit_slack_consumed", ...
        linearizationBefore.explicit_slack_consumed && ...
        linearizationAfter.explicit_slack_consumed, ...
    "recursive_no_full_direction_fallback", ...
        recursive.no_full_direction_fallback && ...
        ~recursive.full_direction_consumed);
checkValues = struct2cell(checks);
allPassed = all(cellfun(@(value)isequal(value,true),checkValues));
if ~allPassed
    failedNames = string(fieldnames(checks));
    failedNames = failedNames(~cellfun( ...
        @(value)isequal(value,true),checkValues));
    error("stageA4:iteration:ClosureFailed", ...
        "A4 iteration checks failed: %s. closure=[eq %.17g, dual %.17g, "+ ...
        "slack %.17g, eq-contract %.17g, dual-contract %.17g, "+ ...
        "slack-scale %.17g, slack-state %.17g, physical %.17g/%.17g], "+ ...
        "soc=[initial %.17g, terminal %.17g, terminal-scaled %.17g].", ...
        strjoin(failedNames,", "), ...
        closure.equality_linear_update_relative_error, ...
        closure.dual_linear_update_relative_error, ...
        closure.slack_linear_update_relative_error, ...
        closure.equality_contraction_relative_error, ...
        closure.dual_contraction_relative_error, ...
        closure.slack_residual_scaled, ...
        closure.slack_state_consistency_inf, ...
        after.physical_inequality_violation, ...
        256*eps*after.physical_inequality_scale, ...
        soc.initial_linear_update_relative_error, ...
        soc.terminal_linear_update_relative_error, ...
        soc.terminal_maximum_locally_scaled_residual_after);
end

timing.total_seconds = toc(totalTimer);
result = struct();
result.state_before = linearizationBefore.state;
result.state_after = linearizationAfter.state;
result.linearization_before = linearizationBefore;
result.linearization_after = linearizationAfter;
result.recursive = recursive;
result.direct_audit = direct;
result.direction_audit = audit;
result.primal_step = primalStep;
result.dual_step = dualStep;
result.applied_step = appliedStep;
result.residuals = struct("before",before,"after",after, ...
    "closure",closure);
result.fixed_zero = fixedZero;
result.soc = soc;
result.qp5 = qp5;
result.permutation = permutationAudit;
result.checks = checks;
result.all_pass = allPassed;
result.timing = timing;
result.objective_scale_mode = options.ObjectiveScaleMode;
result.diagnostic_objective_chain_id = ...
    options.DiagnosticObjectiveChainId;
end

function linearization = build_selected_linearization( ...
        state,data,index,config,objectiveScaleMode,chainId)
if objectiveScaleMode=="unscaled"
    linearization = build_stage_a4_linearization( ...
        state,data,index,config);
else
    linearization = build_stage_a4_scaled_objective_linearization( ...
        state,data,index,config,chainId);
end
end

function audit = make_applied_step_audit(strategy,experimental, ...
        primalStep,dualStep,appliedAlphaPrimal,appliedAlphaDual, ...
        alphaCommon,before,after,direction)
expectedXi = before.xi+appliedAlphaPrimal*direction.xi;
expectedL = before.l+appliedAlphaPrimal*direction.l;
expectedY = before.y+appliedAlphaDual*direction.y;
expectedZ = before.z+appliedAlphaDual*direction.z;
xiError = relative_inf_error(after.xi,expectedXi);
lError = relative_inf_error(after.l,expectedL);
yError = relative_inf_error(after.y,expectedY);
zError = relative_inf_error(after.z,expectedZ);
if strategy=="independent"
    policyPassed = appliedAlphaPrimal==primalStep.alpha && ...
        appliedAlphaDual==dualStep.alpha && ~experimental;
else
    policyPassed = appliedAlphaPrimal==alphaCommon && ...
        appliedAlphaDual==alphaCommon && ...
        alphaCommon==min(primalStep.alpha,dualStep.alpha) && experimental;
end
audit = struct( ...
    "strategy",strategy, ...
    "experimental",experimental, ...
    "candidate_alpha_primal",primalStep.alpha, ...
    "candidate_alpha_dual",dualStep.alpha, ...
    "alpha_common",alphaCommon, ...
    "applied_alpha_primal",appliedAlphaPrimal, ...
    "applied_alpha_dual",appliedAlphaDual, ...
    "all_four_groups_use_common_step",strategy=="common_min" && ...
        appliedAlphaPrimal==appliedAlphaDual, ...
    "xi_update_relative_error",xiError, ...
    "l_update_relative_error",lError, ...
    "y_update_relative_error",yError, ...
    "z_update_relative_error",zError, ...
    "policy_contract_passed",policyPassed, ...
    "passed",policyPassed && max([xiError,lError,yError,zError])<=16*eps);
end

function errorValue = relative_inf_error(actual,expected)
scale = max([1,norm(actual,inf),norm(expected,inf)]);
errorValue = norm(actual-expected,inf)/scale;
end

function validate_iteration_inputs(state,index,config,stepStrategy, ...
        objectiveScaleMode,objectiveChainId,equalityReferenceScale, ...
        dualReferenceScale)
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY", ...
    "stageA4:iteration:StageStatus", ...
    "An A4 iteration requires stage_A4 / READY.");
assert(config.fraction_to_boundary==0.9995 && ...
    config.initialization.centering_sigma==0.1, ...
    "stageA4:iteration:FrozenStepParameters", ...
    "A4 iterations require sigma=0.1 and tau=0.9995 from solver.yaml.");
assert(isfield(index,"scope") && ...
    string(index.scope.stage_id)=="stage_A4", ...
    "stageA4:iteration:IndexIdentity", ...
    "The canonical index must identify stage_A4.");
required = ["xi","y","l","z","stage_id", ...
    "iteration_index","state_revision","newton_direction_number", ...
    "completed_newton_direction_count"];
for name = required
    assert(isfield(state,name),"stageA4:iteration:MissingStateField", ...
        "state.%s is required.",name);
end
assert(string(state.stage_id)=="stage_A4", ...
    "stageA4:iteration:StateIdentity", ...
    "The explicit state must identify stage_A4.");
for name = ["xi","y","l","z"]
    value = state.(name);
    assert(isa(value,"double") && isreal(value) && size(value,2)==1 && ...
        ~isempty(value) && all(isfinite(value)), ...
        "stageA4:iteration:InvalidStateVector", ...
        "state.%s must be a nonempty finite real double column vector.",name);
end
assert(all(state.l>0) && all(state.z>0), ...
    "stageA4:iteration:NonpositiveState", ...
    "The explicit state l and z must be strictly positive.");
for name = ["iteration_index","state_revision"]
    value = state.(name);
    assert(isa(value,"double") && isscalar(value) && isfinite(value) && ...
        value>=0 && value==fix(value), ...
        "stageA4:iteration:InvalidRevision", ...
        "state.%s must be a finite nonnegative integer scalar.",name);
end
assert(state.iteration_index==state.state_revision, ...
    "stageA4:iteration:RevisionMismatch", ...
    "A4-2A requires iteration_index and state_revision to advance together.");
assert(state.newton_direction_number==state.iteration_index && ...
    state.completed_newton_direction_count==state.iteration_index, ...
    "stageA4:iteration:DirectionCountMetadata", ...
    "A4 direction-count metadata must equal the completed iteration count.");
if isfield(state,"diagnostic_chain_id")
    chainId = string(state.diagnostic_chain_id);
    assert(isscalar(chainId) && ismember(chainId,["A4-2C-A","A4-2C-B"]), ...
        "stageA4:iteration:DiagnosticChainId", ...
        "A4-2C diagnostic chain identity is invalid.");
else
    chainId = "";
end
if stepStrategy=="common_min"
    assert(chainId=="A4-2C-B", ...
        "stageA4:iteration:ExperimentalCommonStepScope", ...
        "common_min is allowed only for the isolated A4-2C-B chain.");
elseif strlength(chainId)>0
    assert(chainId=="A4-2C-A", ...
        "stageA4:iteration:BaselineChainScope", ...
        "The namespaced independent A4-2C chain must be A4-2C-A.");
end
if objectiveScaleMode=="positive_scalar_unitization"
    assert(stepStrategy=="independent" && strlength(chainId)==0 && ...
        ismember(objectiveChainId, ...
        ["A4-2D-2A-SCALED-5","A4-2D-2A-SCALED-20"]) && ...
        isfinite(equalityReferenceScale) && ...
        equalityReferenceScale>=1 && ...
        isfinite(dualReferenceScale) && dualReferenceScale>=1, ...
        "stageA4:iteration:ObjectiveScaleScope", ...
        "Objective unitization is allowed only in an isolated A4-2D-2A "+ ...
        "independent-step diagnostic chain with fixed initial residual "+ ...
        "reference scales.");
else
    assert(strlength(objectiveChainId)==0 && ...
        isnan(equalityReferenceScale) && isnan(dualReferenceScale), ...
        "stageA4:iteration:UnexpectedObjectiveChain", ...
        "Objective diagnostic metadata requires objective unitization.");
end
end

function assert_explicit_state_consumed(lin,state,position)
chainIdentityConsumed = ~isfield(state,"diagnostic_chain_id") || ...
    (isfield(lin.state,"diagnostic_chain_id") && ...
    string(lin.state.diagnostic_chain_id)==string(state.diagnostic_chain_id) && ...
    isfield(lin,"diagnostic_chain_id") && ...
    string(lin.diagnostic_chain_id)==string(state.diagnostic_chain_id));
assert(lin.explicit_slack_consumed && chainIdentityConsumed && ...
    isequal(lin.state.xi,state.xi) && isequal(lin.state.y,state.y) && ...
    isequal(lin.state.l,state.l) && isequal(lin.state.z,state.z), ...
    "stageA4:iteration:ExplicitStateNotConsumed", ...
    "The %s linearization did not consume the caller's exact xi/y/l/z state.", ...
    position);
end

function snapshot = residual_snapshot(lin,sigma)
inequalityFunction = lin.G*lin.state.xi+lin.constraints.ineq_offset;
physicalViolation = max(max(inequalityFunction,0));
gap = mean(lin.l.*lin.z);
raw = lin.l.'*lin.z;
snapshot = struct( ...
    "equality_inf",norm(lin.r_eq,inf), ...
    "slack_equality_inf",norm(lin.r_ineq,inf), ...
    "slack_equality_scaled",norm(lin.r_ineq,inf)/max(1, ...
        norm(inequalityFunction,inf)+norm(lin.state.l,inf)), ...
    "physical_inequality_violation",physicalViolation, ...
    "physical_inequality_scale",max(1,norm(inequalityFunction,inf)), ...
    "dual_inf",norm(lin.r_dual,inf), ...
    "complementarity_inf",norm(lin.r_comp,inf), ...
    "complementarity_gap",gap, ...
    "raw_complementarity",raw, ...
    "mu",lin.mu, ...
    "minimum_l",min(lin.l), ...
    "minimum_z",min(lin.z));
assert(isfinite(gap) && gap>0 && isfinite(raw) && raw>0 && ...
    lin.mu==sigma*gap, ...
    "stageA4:iteration:ComplementarityDefinition", ...
    "The normalized/raw complementarity or mu definition is inconsistent.");
end

function closure = audit_linear_update(before,after,direction,alphaP,alphaD, ...
        equalityReferenceScale,dualReferenceScale)
assert(nnz(after.H-before.H)==0 && nnz(after.A-before.A)==0 && ...
    nnz(after.G-before.G)==0 && ...
    isequal(after.objective.gradient,before.objective.gradient), ...
    "stageA4:iteration:ModelChanged", ...
    "The model matrices or objective gradient changed during one update.");

expectedEq = before.r_eq+alphaP*(before.A*direction.xi);
expectedSlack = before.r_ineq+alphaP*( ...
    before.G*direction.xi+direction.l);
expectedDual = before.r_dual+alphaD*( ...
    before.A.'*direction.y+before.G.'*direction.z);
eqScale = max([1,norm(after.r_eq,inf),norm(expectedEq,inf)]);
slackScale = max([1,norm(after.r_ineq,inf),norm(expectedSlack,inf)]);
dualScale = max([1,norm(after.r_dual,inf),norm(expectedDual,inf)]);
constraintScale = max(1,norm(after.G*after.state.xi+ ...
    after.constraints.ineq_offset,inf)+norm(after.state.l,inf));
equalityModelScale = max(1,norm(after.A*after.state.xi,inf)+ ...
    norm(after.constraints.eq_offset,inf));
dualModelScale = max(1,norm(after.objective.gradient,inf)+ ...
    norm(after.A.'*after.state.y,inf)+ ...
    norm(after.G.'*after.state.z,inf));
if isnan(equalityReferenceScale)
    equalityReferenceScale = eqScale;
end
if isnan(dualReferenceScale)
    dualReferenceScale = dualScale;
end

impliedSlack = -(after.G*after.state.xi+ ...
    after.constraints.ineq_offset);
consistencyDifference = after.state.l-impliedSlack-after.r_ineq;
closure = struct( ...
    "equality_linear_update_relative_error", ...
        norm(after.r_eq-expectedEq,inf)/eqScale, ...
    "slack_linear_update_relative_error", ...
        norm(after.r_ineq-expectedSlack,inf)/slackScale, ...
    "dual_linear_update_relative_error", ...
        norm(after.r_dual-expectedDual,inf)/dualScale, ...
    "equality_linear_update_model_scaled_error", ...
        norm(after.r_eq-expectedEq,inf)/equalityModelScale, ...
    "dual_linear_update_model_scaled_error", ...
        norm(after.r_dual-expectedDual,inf)/dualModelScale, ...
    "equality_linear_update_reference_scaled_error", ...
        norm(after.r_eq-expectedEq,inf)/equalityReferenceScale, ...
    "dual_linear_update_reference_scaled_error", ...
        norm(after.r_dual-expectedDual,inf)/dualReferenceScale, ...
    "equality_contraction_relative_error", ...
        norm(after.r_eq-(1-alphaP)*before.r_eq,inf)/eqScale, ...
    "dual_contraction_relative_error", ...
        norm(after.r_dual-(1-alphaD)*before.r_dual,inf)/dualScale, ...
    "equality_contraction_model_scaled_error", ...
        norm(after.r_eq-(1-alphaP)*before.r_eq,inf)/ ...
        equalityModelScale, ...
    "dual_contraction_model_scaled_error", ...
        norm(after.r_dual-(1-alphaD)*before.r_dual,inf)/dualModelScale, ...
    "equality_contraction_reference_scaled_error", ...
        norm(after.r_eq-(1-alphaP)*before.r_eq,inf)/ ...
        equalityReferenceScale, ...
    "dual_contraction_reference_scaled_error", ...
        norm(after.r_dual-(1-alphaD)*before.r_dual,inf)/ ...
        dualReferenceScale, ...
    "slack_residual_scaled",norm(after.r_ineq,inf)/constraintScale, ...
    "slack_state_consistency_inf",norm(consistencyDifference,inf), ...
    "model_matrices_unchanged",true);
end

function fixedZero = make_fixed_zero_audit(physicalBefore,physicalAfter)
fixedZero = struct( ...
    "count",physicalAfter.fixed_zero_audit.count, ...
    "values_exact_zero_before", ...
        physicalBefore.fixed_zero_audit.values_exact_zero, ...
    "values_exact_zero_after", ...
        physicalAfter.fixed_zero_audit.values_exact_zero, ...
    "directions_exact_zero", ...
        physicalAfter.fixed_zero_audit.directions_exact_zero, ...
    "maximum_absolute_value_after", ...
        physicalAfter.fixed_zero_audit.maximum_absolute_value, ...
    "maximum_absolute_direction", ...
        physicalAfter.fixed_zero_audit.maximum_absolute_direction);
end

function audit = make_permutation_audit(permutation)
audit = struct( ...
    "dimension",permutation.dimension, ...
    "is_bijection",permutation.is_bijection, ...
    "is_nonidentity",permutation.is_nonidentity, ...
    "forward_inverse_composition_exact", ...
        permutation.forward_inverse_composition_exact, ...
    "inverse_forward_composition_exact", ...
        permutation.inverse_forward_composition_exact);
end

function audit = audit_formal_soc_boundaries(index,config,before,after, ...
        direction,alphaPrimal,relativeToleranceMultiplier)
links = index.soc_link_map;
variables = index.variable_index;
equalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type)=="equality",:);
initialCount = 0;
terminalCount = 0;
crossDayCount = 0;
initialCoefficientFailures = 0;
terminalCoefficientFailures = 0;
initialRows = zeros(0,1);
terminalRows = zeros(0,1);
terminalLocalScales = zeros(0,1);
for day = config.days
    dayPosition = find(before.maps.days==day,1,"first");
    for storage = 1:2
        first = links(links.day==day & links.hour==1 & ...
            links.storage_id==storage,:);
        initialCount = initialCount+height(first);
        firstRow = find(equalities.day==day & equalities.hour==1 & ...
            string(equalities.constraint_name)=="soc_dynamics" & ...
            equalities.asset_id==storage);
        qEnergy = before.maps.q_day(12+storage,dayPosition);
        if isscalar(firstRow)
            initialRows(end+1,1) = firstRow; %#ok<AGROW>
        end
        if height(first)~=1 || ~isscalar(firstRow) || ...
                ~isnan(first.predecessor_hour) || ...
                first.predecessor_soc_global_index~=0 || ...
                first.initial_energy_fraction~=0.5 || ...
                before.A(firstRow,qEnergy)~=-0.5 || ...
                before.A(firstRow,first.current_soc_global_index)~=1
            initialCoefficientFailures = initialCoefficientFailures+1;
        end
        last = links(links.day==day & links.hour==24 & ...
            links.storage_id==storage & links.terminal_equality,:);
        terminalCount = terminalCount+height(last);
        lastRow = find(equalities.day==day & equalities.hour==24 & ...
            string(equalities.constraint_name)=="terminal_soc" & ...
            equalities.asset_id==storage);
        if isscalar(lastRow)
            terminalRows(end+1,1) = lastRow; %#ok<AGROW>
            terminalLocalScales(end+1,1) = max([1, ...
                abs(after.state.xi(last.current_soc_global_index)), ...
                0.5*abs(after.state.xi(qEnergy))]); %#ok<AGROW>
        end
        if height(last)~=1 || ~isscalar(lastRow) || ...
                last.terminal_energy_fraction~=0.5 || ...
                before.A(lastRow,qEnergy)~=-0.5 || ...
                before.A(lastRow,last.current_soc_global_index)~=1
            terminalCoefficientFailures = terminalCoefficientFailures+1;
        end
    end
    internal = links(links.day==day & links.hour>1,:);
    predecessors = variables(internal.predecessor_soc_global_index,:);
    crossDayCount = crossDayCount+nnz(predecessors.day~=day | ...
        predecessors.hour~=internal.hour-1);
end
expectedInitial = before.r_eq(initialRows)+alphaPrimal*( ...
    before.A(initialRows,:)*direction.xi);
initialScale = max([1,norm(after.r_eq(initialRows),inf), ...
    norm(expectedInitial,inf)]);
initialUpdateError = norm(after.r_eq(initialRows)-expectedInitial,inf)/ ...
    initialScale;
expectedTerminal = before.r_eq(terminalRows)+alphaPrimal*( ...
    before.A(terminalRows,:)*direction.xi);
terminalScale = max([1,norm(after.r_eq(terminalRows),inf), ...
    norm(expectedTerminal,inf)]);
terminalUpdateError = norm(after.r_eq(terminalRows)-expectedTerminal,inf)/ ...
    terminalScale;
terminalScaledResiduals = abs(after.r_eq(terminalRows))./ ...
    terminalLocalScales;
terminalMaximumScaledResidual = max(terminalScaledResiduals);
audit = struct( ...
    "day_ids",config.days, ...
    "initial_half_energy_link_count",initialCount, ...
    "terminal_half_energy_link_count",terminalCount, ...
    "cross_day_or_nonadjacent_link_count",crossDayCount, ...
    "initial_boundary_coefficient_failure_count", ...
        initialCoefficientFailures, ...
    "terminal_boundary_coefficient_failure_count", ...
        terminalCoefficientFailures, ...
    "initial_residual_inf_before",norm(before.r_eq(initialRows),inf), ...
    "initial_residual_inf_after",norm(after.r_eq(initialRows),inf), ...
    "initial_linear_update_relative_error",initialUpdateError, ...
    "terminal_residual_inf_before",norm(before.r_eq(terminalRows),inf), ...
    "terminal_residual_inf_after",norm(after.r_eq(terminalRows),inf), ...
    "terminal_maximum_locally_scaled_residual_after", ...
        terminalMaximumScaledResidual, ...
    "relative_tolerance_multiplier",relativeToleranceMultiplier, ...
    "terminal_linear_update_relative_error",terminalUpdateError, ...
    "passed",initialCount==14 && terminalCount==14 && ...
        crossDayCount==0 && initialCoefficientFailures==0 && ...
        terminalCoefficientFailures==0 && ...
        initialUpdateError<=relativeToleranceMultiplier*eps && ...
        terminalUpdateError<=relativeToleranceMultiplier*eps && ...
        terminalMaximumScaledResidual<= ...
            max(512,relativeToleranceMultiplier)*eps);
end

function audit = audit_qp5_bounds(index,before,after,direction)
variables = index.variable_index;
qMask = variables.day==0 & variables.hour==0 & ...
    string(variables.variable_name)=="QP5";
assert(nnz(qMask)==1,"stageA4:iteration:QP5Variable", ...
    "The global QP5 variable must occur exactly once.");
qIndex = variables.global_index_start(qMask);
qPosition = find(before.maps.q_global==qIndex,1,"first");
assert(isscalar(qPosition),"stageA4:iteration:QP5Map", ...
    "The global QP5 variable is missing from maps.q_global.");

inequalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type)=="inequality",:);
lower = find(string(inequalities.constraint_id)=="INEQ-Q-LOWER-QP5");
upper = find(string(inequalities.constraint_id)=="INEQ-Q-UPPER-QP5");
assert(isscalar(lower) && isscalar(upper), ...
    "stageA4:iteration:QP5BoundRows", ...
    "QP5 must have exactly one semantic lower and upper inequality row.");

lowerAudit = make_qp5_side(inequalities,lower,before,after,direction);
upperAudit = make_qp5_side(inequalities,upper,before,after,direction);
lowerBound = before.capacity_parameters.lower(qPosition);
upperBound = before.capacity_parameters.upper(qPosition);
audit = struct( ...
    "capacity_name","QP5", ...
    "capacity_position",qPosition, ...
    "capacity_variable_global_index",qIndex, ...
    "capacity_lower_bound",lowerBound, ...
    "capacity_upper_bound",upperBound, ...
    "capacity_value_before",before.state.xi(qIndex), ...
    "capacity_value_after",after.state.xi(qIndex), ...
    "capacity_direction",direction.xi(qIndex), ...
    "distance_to_lower_before",before.state.xi(qIndex)-lowerBound, ...
    "distance_to_lower_after",after.state.xi(qIndex)-lowerBound, ...
    "distance_to_upper_before",upperBound-before.state.xi(qIndex), ...
    "distance_to_upper_after",upperBound-after.state.xi(qIndex), ...
    "lower",lowerAudit,"upper",upperAudit, ...
    "passed",lowerAudit.constraint_id=="INEQ-Q-LOWER-QP5" && ...
        upperAudit.constraint_id=="INEQ-Q-UPPER-QP5" && ...
        lowerAudit.physical_function_before== ...
            lowerBound-before.state.xi(qIndex) && ...
        lowerAudit.physical_function_after== ...
            lowerBound-after.state.xi(qIndex) && ...
        upperAudit.physical_function_before== ...
            before.state.xi(qIndex)-upperBound && ...
        upperAudit.physical_function_after== ...
            after.state.xi(qIndex)-upperBound && ...
        lowerAudit.physical_function_direction== -direction.xi(qIndex) && ...
        upperAudit.physical_function_direction== direction.xi(qIndex) && ...
        all(isfinite([before.state.xi(qIndex),after.state.xi(qIndex), ...
            direction.xi(qIndex)])));
end

function side = make_qp5_side(inequalities,row,before,after,direction)
slackRatio = boundary_ratio(before.l(row),direction.l(row));
multiplierRatio = boundary_ratio(before.z(row),direction.z(row));
side = struct( ...
    "constraint_id",string(inequalities.constraint_id(row)), ...
    "inequality_index",row, ...
    "constraint_global_row",inequalities.global_row(row), ...
    "physical_function_before",before.constraints.ineq(row), ...
    "physical_function_after",after.constraints.ineq(row), ...
    "physical_function_direction",before.G(row,:)*direction.xi, ...
    "slack_before",before.l(row), ...
    "slack_after",after.l(row), ...
    "slack_direction",direction.l(row), ...
    "slack_boundary_ratio",slackRatio, ...
    "multiplier_before",before.z(row), ...
    "multiplier_after",after.z(row), ...
    "multiplier_direction",direction.z(row), ...
    "multiplier_boundary_ratio",multiplierRatio);
end

function ratio = boundary_ratio(value,direction)
if direction<0
    ratio = -value/direction;
else
    ratio = Inf;
end
end

function step = annotate_limiting_inequality(step,index)
inequalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type)=="inequality",:);
if step.limiting_index==0
    step.limiting_constraint_id = "";
    step.limiting_constraint_global_row = 0;
    step.limiting_day = NaN;
    step.limiting_hour = NaN;
    step.limiting_asset_type = "";
    step.limiting_asset_id = NaN;
    return
end
row = inequalities(step.limiting_index,:);
step.limiting_constraint_id = string(row.constraint_id);
step.limiting_constraint_global_row = row.global_row;
step.limiting_day = row.day;
step.limiting_hour = row.hour;
step.limiting_asset_type = string(row.asset_type);
step.limiting_asset_id = row.asset_id;
end
