function evidence = export_stage_a4_2d_2a_r1_stable_v2_evidence( ...
        projectRoot,outputDirectory,options)
%EXPORT_STAGE_A4_2D_2A_R1_STABLE_V2_EVIDENCE Persist the 30-update result.
%
% This exporter consumes an already computed R1 result and its fixed test
% evidence.  It does not solve another direction or update another state.
% The controlled fixture directory is versioned and cannot be overwritten.

arguments
    projectRoot (1,1) string
    outputDirectory (1,1) string
    options.Result (1,1) struct
    options.TestEvidence (1,1) struct
    options.SourceCommit (1,1) string
    options.ToolingCommit (1,1) string
end
assert(strlength(options.SourceCommit)==40 && ...
    strlength(options.ToolingCommit)==40, ...
    "stageA4:r1:EvidenceCommit", ...
    "R1 evidence requires full source and tooling commits.");
result = options.Result;
testEvidence = options.TestEvidence;
assert(result.milestone_status=="PASS" && ...
    result.all_blocking_pass && result.stage_status=="READY" && ...
    result.forbidden_execution_pass && ...
    result.execution.forbidden_execution_audit_pass && ...
    result.execution.total_newton_direction_count==30 && ...
    result.execution.state_update_count==30 && ...
    result.scaled_twenty.iteration_count==20 && ...
    result.recursive_refinement_max_passes==3 && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.hundred_round_run_executed && ...
    ~result.execution.stage_b_entered && ...
    testEvidence.all_pass && ...
    testEvidence.summary.test_total==18 && ...
    testEvidence.summary.test_passed==18, ...
    "stageA4:r1:EvidenceResult", ...
    "Only a passing 30-update R1 result and 18/18 tests may be exported.");

projectRoot = canonical_folder(projectRoot);
expectedOutput = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_2D_2A_R1_stable_v2");
assert(canonical_candidate(outputDirectory)== ...
    canonical_candidate(expectedOutput), ...
    "stageA4:r1:EvidencePath", ...
    "R1 stable-v2 evidence must use its controlled fixture directory.");
assert(~isfolder(outputDirectory), ...
    "stageA4:r1:EvidenceOverwrite", ...
    "Refusing to overwrite R1 stable-v2 evidence: %s",outputDirectory);
stagingDirectory = outputDirectory+".building";
assert(~isfolder(stagingDirectory), ...
    "stageA4:r1:EvidenceStaging", ...
    "R1 stable-v2 staging already exists: %s",stagingDirectory);
[created,message] = mkdir(stagingDirectory);
assert(created,"stageA4:r1:EvidenceDirectory", ...
    "Unable to create R1 evidence staging %s: %s", ...
    stagingDirectory,message);
cleanup = onCleanup(@()cleanup_staging( ...
    stagingDirectory,outputDirectory));

paths = evidence_paths(stagingDirectory);
r1Result = result;
r1TestSummary = testEvidence.summary;
r1TestInventory = testEvidence.inventory;
r1TestResults = testEvidence.results;
save(paths.mat,"r1Result","r1TestSummary","r1TestInventory", ...
    "r1TestResults","-v7.3");
write_table_csv_17g(paths.rounds,result.round_table);
write_table_csv_17g(paths.residuals,result.residual_trajectory);
write_table_csv_17g(paths.refinement,result.refinement_table);
write_table_csv_17g(paths.convergence, ...
    result.convergence_analysis.intervals);
write_table_csv_17g(paths.blocking,result.blocking_audit);
write_table_csv_17g(paths.forbidden_execution, ...
    result.forbidden_execution_audit);
write_table_csv_17g(paths.forbidden_code,result.r1_forbidden_code_audit);
write_table_csv_17g(paths.dependency_closure,result.r1_dependency_closure);
write_table_csv_17g(paths.gap_unscaled, ...
    result.gap_tables.unscaled_five);
write_table_csv_17g(paths.gap_scaled_five, ...
    result.gap_tables.scaled_five);
write_table_csv_17g(paths.gap_scaled_twenty, ...
    result.gap_tables.scaled_twenty);
write_table_csv_17g(paths.test_inventory,testEvidence.inventory);
write_table_csv_17g(paths.test_results,testEvidence.results);

inputHashes = make_input_hashes(projectRoot);
sourceHashes = make_source_hashes(projectRoot);
write_table_csv_17g(paths.input_hashes,inputHashes);
write_table_csv_17g(paths.source_hashes,sourceHashes);

generationCommand = ...
    "powershell -NoProfile -ExecutionPolicy Bypass -File "+ ...
    "scripts/export_stage_A4_2D_2A_R1_stable_v2.ps1 "+ ...
    "-SourceCommit "+options.SourceCommit;
write_text(paths.command,generationCommand+newline);

authorityPath = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_RNS_1_authority_v1", ...
    "stage_A4_RNS_1_round19_authority_v1.mat");
authoritySha256 = compute_sha256_file(authorityPath);
assert(authoritySha256== ...
    "14c5501a17fc317a5653b8d55ac29f6b103ddcfb3004aef807acff6bde4e62b3", ...
    "stageA4:r1:EvidenceAuthority", ...
    "The round-18/19 authority MAT changed before R1 export.");
final = result.scaled_twenty.final_metrics;
round19 = result.scaled_twenty.iterations(19);
round20 = result.scaled_twenty.iterations(20);
metadata = struct( ...
    "milestone","A4-2D-2A-R1", ...
    "fixture_version","stable-v2", ...
    "starting_authority_head", ...
        "4ac1c2b081e8f391a4aa94a5b72686de777fee78", ...
    "source_commit",options.SourceCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "generation_command",generationCommand, ...
    "stage_id","stage_A4", ...
    "stage_status","READY", ...
    "r1_status","PASS", ...
    "original_a4_2d_2a_status","FAIL_RETRYABLE", ...
    "recursive_route",result.stable_route, ...
    "recursive_refinement_max_passes",3, ...
    "unscaled_five_iteration_count",5, ...
    "scaled_five_iteration_count",5, ...
    "scaled_twenty_iteration_count",20, ...
    "newton_direction_count",30, ...
    "state_update_count",30, ...
    "objective_scale_factor",result.scaled_twenty.objective_scale.factor, ...
    "final_gap_scaled_mean_lz",final.mean_gap_scaled, ...
    "final_gap_original_mapped_mean_lz",final.mapped_mean_gap, ...
    "final_raw_gap_scaled",final.raw_gap_scaled, ...
    "final_r_eq_inf",final.equality_inf, ...
    "final_r_ineq_inf",final.slack_equality_inf, ...
    "final_r_dual_scaled_inf",final.dual_scaled_inf, ...
    "final_r_dual_original_mapped_inf",final.mapped_r_dual_inf, ...
    "final_r_comp_scaled_inf",final.complementarity_inf, ...
    "final_min_l",final.minimum_l, ...
    "final_min_z",final.minimum_z, ...
    "round19_alpha_primal",round19.applied_alpha_primal, ...
    "round19_alpha_dual",round19.applied_alpha_dual, ...
    "round20_alpha_primal",round20.applied_alpha_primal, ...
    "round20_alpha_dual",round20.applied_alpha_dual, ...
    "convergence_achieved",result.convergence_achieved, ...
    "mean_lz_is_dimensionless",false, ...
    "thirty_newton_seconds",result.timing.thirty_newton_seconds, ...
    "r1_total_seconds",result.timing.total_seconds, ...
    "r1_test_total",testEvidence.summary.test_total, ...
    "r1_test_passed",testEvidence.summary.test_passed, ...
    "r1_test_failed",testEvidence.summary.test_failed, ...
    "r1_test_incomplete",testEvidence.summary.test_incomplete, ...
    "r1_test_seconds",testEvidence.summary.duration_seconds, ...
    "r1_test_consumed_precomputed_result", ...
        testEvidence.summary.precomputed_result_consumed, ...
    "r1_forbidden_execution_audit_pass", ...
        result.execution.forbidden_execution_audit_pass, ...
    "r1_dependency_file_count",height(result.r1_dependency_closure), ...
    "r1_dependency_root",result.execution.r1_dependency_root, ...
    "r1_dependency_analysis_method", ...
        result.execution.r1_dependency_analysis_method, ...
    "r1_dependency_closure_sha256", ...
        compute_sha256_file(paths.dependency_closure), ...
    "authority_mat_sha256",authoritySha256, ...
    "round18_corrected_min_z",1.5822518332365282e-06, ...
    "round18_gap",0.16366994392519446, ...
    "round18_old_document_min_z",0.51589348514731437, ...
    "historical_correction_affects_computation",false, ...
    "complete_kkt_direction_fallback_used", ...
        result.execution.complete_kkt_direction_fallback_used, ...
    "common_step_used",result.execution.common_step_used, ...
    "dynamic_sigma_used",result.execution.dynamic_sigma_used, ...
    "predictor_corrector_used", ...
        result.execution.predictor_corrector_used, ...
    "line_search_used",result.execution.line_search_used, ...
    "regularization_used",result.execution.regularization_used, ...
    "automatic_symmetrization_used", ...
        result.execution.automatic_symmetrization_used, ...
    "formal_a4_run_created",result.execution.formal_a4_run_created, ...
    "hundred_round_run_executed", ...
        result.execution.hundred_round_run_executed, ...
    "full_ipm_executed",result.execution.full_ipm_executed, ...
    "optimization_executed",result.execution.optimization_executed, ...
    "parallel_executed",result.execution.parallel_executed, ...
    "stage_b_entered",result.execution.stage_b_entered);
metadata.result_mat_file = leaf(paths.mat);
metadata.result_mat_sha256 = compute_sha256_file(paths.mat);
metadata.rounds_file = leaf(paths.rounds);
metadata.rounds_sha256 = compute_sha256_file(paths.rounds);
metadata.refinement_file = leaf(paths.refinement);
metadata.refinement_sha256 = compute_sha256_file(paths.refinement);
metadata.test_results_file = leaf(paths.test_results);
metadata.test_results_sha256 = compute_sha256_file(paths.test_results);
write_text(paths.metadata,string(jsonencode( ...
    metadata,PrettyPrint=true))+newline);

artifactPath = [ ...
    leaf(paths.mat)
    leaf(paths.rounds)
    leaf(paths.residuals)
    leaf(paths.refinement)
    leaf(paths.convergence)
    leaf(paths.blocking)
    leaf(paths.forbidden_execution)
    leaf(paths.forbidden_code)
    leaf(paths.dependency_closure)
    leaf(paths.gap_unscaled)
    leaf(paths.gap_scaled_five)
    leaf(paths.gap_scaled_twenty)
    leaf(paths.test_inventory)
    leaf(paths.test_results)
    leaf(paths.input_hashes)
    leaf(paths.source_hashes)
    leaf(paths.command)
    leaf(paths.metadata)];
sha256 = strings(numel(artifactPath),1);
for k = 1:numel(artifactPath)
    sha256(k) = compute_sha256_file( ...
        fullfile(stagingDirectory,artifactPath(k)));
end
manifest = table(artifactPath,sha256, ...
    'VariableNames',{'artifact_path','sha256'});
write_table_csv_17g(paths.manifest,manifest);

[moved,message] = movefile(stagingDirectory,outputDirectory);
assert(moved,"stageA4:r1:EvidenceFinalize", ...
    "Unable to finalize R1 stable-v2 evidence %s: %s", ...
    outputDirectory,message);
finalAudit = verify_final(outputDirectory,manifest);
evidence = struct( ...
    "output_directory",outputDirectory, ...
    "source_commit",options.SourceCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "manifest",manifest, ...
    "final_audit",finalAudit, ...
    "all_pass",finalAudit.all_pass);
clear cleanup
end

function hashes = make_input_hashes(projectRoot)
relativePath = ["inputs/raw/基础参数.xlsx";"inputs/raw/输入数据.xlsx"];
sha256 = strings(2,1);
for k = 1:2
    sha256(k) = compute_sha256_file(fullfile(projectRoot, ...
        strrep(relativePath(k),"/",filesep)));
end
hashes = table(relativePath,sha256, ...
    'VariableNames',{'relative_path','sha256'});
end

function hashes = make_source_hashes(projectRoot)
relativePath = [ ...
    "AGENTS.md"
    "CURRENT_STAGE.md"
    "config/solver.yaml"
    "config/stage_A4.yaml"
    "src/model/initialize_stage_a4_state.m"
    "src/model/build_stage_a4_linearization.m"
    "src/model/build_stage_a_multiday_linearization.m"
    "stages/stage_A4/阶段A4_验收矩阵.csv"
    "main_stage_A4_2D_2A_R1.m"
    "src/diagnostics/run_stage_a4_objective_unitization_r1_diagnostic.m"
    "src/diagnostics/audit_stage_a4_r1_forbidden_execution.m"
    "src/diagnostics/make_stage_a4_r1_blocking_audit.m"
    "src/diagnostics/scan_stage_a4_r1_forbidden_code.m"
    "src/diagnostics/run_stage_a4_scaled_objective_chain.m"
    "src/diagnostics/run_stage_a4_five_iteration_diagnostic.m"
    "src/diagnostics/execute_stage_a4_iteration.m"
    "src/diagnostics/export_stage_a4_2d_2a_r1_stable_v2_evidence.m"
    "scripts/export_stage_A4_2D_2A_R1_stable_v2.ps1"
    "tests/run_stage_A4_2D_2A_R1_tests.m"
    "tests/integration/test_stage_a4_objective_unitization_stable_rerun.m"
    "tests/stage_A4_2D_2A_R1_expected_test_inventory.csv"
    "main_stage_A4_2D_2A.m"
    "src/diagnostics/run_stage_a4_objective_unitization_diagnostic.m"];
sha256 = strings(numel(relativePath),1);
for k = 1:numel(relativePath)
    sha256(k) = compute_sha256_file(fullfile(projectRoot, ...
        strrep(relativePath(k),"/",filesep)));
end
hashes = table(relativePath,sha256, ...
    'VariableNames',{'relative_path','sha256'});
end

function paths = evidence_paths(root)
prefix = "stage_A4_2D_2A_R1_stable_v2";
paths = struct( ...
    "mat",fullfile(root,prefix+"_result.mat"), ...
    "rounds",fullfile(root,prefix+"_rounds.csv"), ...
    "residuals",fullfile(root,prefix+"_residual_trajectory.csv"), ...
    "refinement",fullfile(root,prefix+"_refinement.csv"), ...
    "convergence",fullfile(root,prefix+"_convergence_intervals.csv"), ...
    "blocking",fullfile(root,prefix+"_blocking_audit.csv"), ...
    "forbidden_execution", ...
        fullfile(root,prefix+"_forbidden_execution_audit.csv"), ...
    "forbidden_code", ...
        fullfile(root,prefix+"_forbidden_code_audit.csv"), ...
    "dependency_closure", ...
        fullfile(root,prefix+"_dependency_closure_sha256.csv"), ...
    "gap_unscaled",fullfile(root,prefix+"_unscaled5_gap.csv"), ...
    "gap_scaled_five",fullfile(root,prefix+"_scaled5_gap.csv"), ...
    "gap_scaled_twenty",fullfile(root,prefix+"_scaled20_gap.csv"), ...
    "test_inventory",fullfile(root,prefix+"_test_inventory.csv"), ...
    "test_results",fullfile(root,prefix+"_test_results.csv"), ...
    "input_hashes",fullfile(root,prefix+"_input_hashes.csv"), ...
    "source_hashes",fullfile(root,prefix+"_source_hashes.csv"), ...
    "command",fullfile(root,prefix+"_generation_command.txt"), ...
    "metadata",fullfile(root,prefix+".metadata.json"), ...
    "manifest",fullfile(root,prefix+"_artifact_sha256.csv"));
end

function audit = verify_final(outputDirectory,expectedManifest)
paths = evidence_paths(outputDirectory);
assert(isfile(paths.manifest), ...
    "stageA4:r1:EvidenceManifestMissing", ...
    "Final R1 evidence manifest is missing.");
actualManifest = readtable(paths.manifest,Delimiter=',', ...
    ReadVariableNames=true,TextType="string", ...
    VariableNamingRule="preserve");
schemaExact = isequal(string(actualManifest.Properties.VariableNames), ...
    ["artifact_path","sha256"]);
rowsExact = schemaExact && ...
    isequal(string(actualManifest.artifact_path), ...
        expectedManifest.artifact_path) && ...
    isequal(string(actualManifest.sha256),expectedManifest.sha256);
hashesExact = rowsExact;
if rowsExact
    for k = 1:height(actualManifest)
        pathValue = fullfile(outputDirectory, ...
            actualManifest.artifact_path(k));
        hashesExact = hashesExact && isfile(pathValue) && ...
            compute_sha256_file(pathValue)==actualManifest.sha256(k);
    end
end
matSchema = false;
if isfile(paths.mat)
    variablesInfo = whos("-file",paths.mat);
    variables = string({variablesInfo.name});
    matSchema = all(ismember( ...
        ["r1Result","r1TestSummary","r1TestInventory","r1TestResults"], ...
        variables));
end
audit = struct( ...
    "schema_exact",schemaExact, ...
    "rows_exact",rowsExact, ...
    "hashes_exact",hashesExact, ...
    "mat_schema_exact",matSchema, ...
    "all_pass",schemaExact && rowsExact && hashesExact && matSchema);
assert(audit.all_pass,"stageA4:r1:EvidenceFinalAudit", ...
    "Final R1 stable-v2 evidence failed its hash or schema audit.");
end

function write_text(pathValue,textValue)
fileId = fopen(pathValue,"wb","n","UTF-8");
assert(fileId>=0,"stageA4:r1:EvidenceTextOpen", ...
    "Unable to open R1 evidence text file: %s",pathValue);
cleanup = onCleanup(@()close_file_if_open(fileId));
fprintf(fileId,"%s",textValue);
status = fclose(fileId);
clear cleanup
assert(status==0,"stageA4:r1:EvidenceTextClose", ...
    "Unable to close R1 evidence text file: %s",pathValue);
end

function close_file_if_open(fileId)
if any(fopen("all")==fileId)
    fclose(fileId);
end
end

function cleanup_staging(stagingDirectory,outputDirectory)
if ~isfolder(stagingDirectory) || isfolder(outputDirectory)
    return
end
fixtureParent = canonical_folder(fileparts(outputDirectory));
stagingCanonical = canonical_candidate(stagingDirectory);
requiredPrefix = lower(fixtureParent+filesep);
assert(startsWith(lower(stagingCanonical),requiredPrefix) && ...
    endsWith(stagingCanonical,".building"), ...
    "stageA4:r1:UnsafeStagingCleanup", ...
    "Refusing to clean an unsafe R1 staging path: %s",stagingCanonical);
rmdir(stagingCanonical,"s");
end

function value = leaf(pathValue)
[~,name,extension] = fileparts(pathValue);
value = string(name)+string(extension);
end

function value = canonical_folder(pathValue)
assert(isfolder(pathValue),"stageA4:r1:CanonicalFolder", ...
    "Expected an existing folder: %s",pathValue);
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end

function value = canonical_candidate(pathValue)
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end
