function result = generate_stage_a4_rns1_stress_fixture( ...
        sourceProjectRoot,outputDirectory,options)
%GENERATE_STAGE_A4_RNS1_STRESS_FIXTURE Freeze the authority round-19 input.
%
% SOURCEPROJECTROOT must be a detached worktree at the frozen authority
% commit.  The function replays the scaled twenty-round diagnostic until
% its expected round-19 recursive failure, then stores the round-18 state,
% round-19 linearization, day-17 recursive objects, and sparse full-KKT
% audit.  It never updates a formal run or solver state.

arguments
    sourceProjectRoot (1,1) string
    outputDirectory (1,1) string
    options.SourceCommit (1,1) string = ...
        "58b2b3645b79c71460ff0de1a03033c319829cd6"
    options.ToolingCommit (1,1) string = ""
end

sourceProjectRoot = absolute_existing_folder(sourceProjectRoot);
outputDirectory = string(outputDirectory);
assert(strlength(options.ToolingCommit)==40, ...
    "stageA4:rns1:ToolingCommit", ...
    "ToolingCommit must be the 40-character commit containing this generator.");
[sourceCommit,sourceClean] = git_source_evidence(sourceProjectRoot);
assert(sourceCommit==options.SourceCommit && sourceClean, ...
    "stageA4:rns1:AuthoritySource", ...
    "The source worktree must be clean and exactly at authority commit %s.", ...
    options.SourceCommit);

assert(~isfolder(outputDirectory), ...
    "stageA4:rns1:FixtureOverwrite", ...
    "The RNS authority fixture directory already exists: %s", ...
    outputDirectory);
stagingDirectory = outputDirectory+".building";
assert(~isfolder(stagingDirectory), ...
    "stageA4:rns1:FixtureStagingOverwrite", ...
    "The RNS authority fixture staging directory already exists: %s", ...
    stagingDirectory);
[created,message] = mkdir(stagingDirectory);
assert(created,"stageA4:rns1:FixtureDirectory", ...
    "Unable to create fixture directory %s: %s",stagingDirectory,message);
stagingCleanup = onCleanup(@()cleanup_staging_directory( ...
    stagingDirectory,outputDirectory));
paths = fixture_paths(stagingDirectory);

sourcePath = path;
pathCleanup = onCleanup(@()path(sourcePath));
addpath(sourceProjectRoot);
addpath(genpath(fullfile(sourceProjectRoot,"src")));

config = load_stage_a4_configuration(sourceProjectRoot);
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY" && ...
    config.symmetry_relative_tolerance==1e-12 && ...
    config.direction_relative_tolerance==1e-10 && ...
    config.recursive_full_kkt_residual_tolerance==1e-10, ...
    "stageA4:rns1:FrozenThresholds", ...
    "The authority Stage-A4 thresholds are not frozen at 1e-12/1e-10.");
data = load_project_data(sourceProjectRoot);
index = build_stage_a4_index( ...
    data,"RunId","A4_2D_2A_OBJECTIVE_UNITIZATION_DIAGNOSTIC");

chain = run_stage_a4_scaled_objective_chain( ...
    data,index,config,"IterationCount",20);
assert(chain.iteration_count==18 && chain.failure.present && ...
    chain.failure.attempted_iteration==19 && ...
    chain.milestone_status=="FAIL_RETRYABLE", ...
    "stageA4:rns1:AuthorityFailureBoundary", ...
    "Authority replay must stop after round 18 at attempted round 19.");
assert(chain.failure.state_fingerprint_before== ...
    chain.iterations(end).state_fingerprint_after, ...
    "stageA4:rns1:AuthorityFailureFingerprint", ...
    "The round-19 failure did not consume the exact frozen round-18 state.");
stateAfterRound18 = chain.final_state;
assert(stateAfterRound18.state_revision==18 && ...
    stateAfterRound18.iteration_index==18 && ...
    min(stateAfterRound18.l)>0 && min(stateAfterRound18.z)>0, ...
    "stageA4:rns1:Round18State", ...
    "The frozen round-18 state has invalid revision or positivity.");
linearizationRound19 = build_stage_a4_scaled_objective_linearization( ...
    stateAfterRound18,data,index,config,"A4-2D-2A-SCALED-20");

reducedRound19 = eliminate_stage_a_multiday_inequality_directions( ...
    linearizationRound19);
partitionRound19 = partition_stage_a_multiday_recursive_system( ...
    linearizationRound19,reducedRound19, ...
    AssemblyTolerance=1e-12);
dayIds = reshape([partitionRound19.day.day_id],[],1);
day17Position = find(dayIds==17);
assert(isscalar(day17Position), ...
    "stageA4:rns1:Day17Partition", ...
    "The authority partition must contain exactly one day-17 chain.");
day17Partition = partitionRound19.day(day17Position);
day17Thomas = solve_block_thomas_ldl( ...
    day17Partition,SymmetryTolerance=1e-12);
day17Response = form_stage_a_multiday_day_response( ...
    day17Partition,day17Thomas);
assert(day17Thomas.rhs_count==15 && ...
    numel(day17Thomas.schur_blocks)==24 && ...
    day17Response.diagnostics.symmetry_relative>1e-12, ...
    "stageA4:rns1:StressSignature", ...
    "The authority day-17 stress signature was not reproduced.");

fullAuditRound19 = solve_stage_a_multiday_full_kkt_direction( ...
    linearizationRound19);
fullAuditRound19.audit_only = true;
fullAuditRound19.consumed_by_recursive = false;
recursiveLooseRound19 = solve_stage_a_multiday_recursive_direction( ...
    linearizationRound19,SymmetryTolerance=1e-10);
looseAudit = verify_stage_a_multiday_direction_equivalence( ...
    fullAuditRound19,recursiveLooseRound19,linearizationRound19, ...
    DirectionRelative=1e-10,RecursiveResidual=1e-10, ...
    FullResidualPreferred=1e-12,FullResidualMaximum=1e-10);
assert(~looseAudit.passed.direction && ...
    ~looseAudit.passed.recursive_residual && ...
    looseAudit.passed.full_residual_hard, ...
    "stageA4:rns1:LooseFailureSignature", ...
    "The authority round-19 loose recursive audit signature changed.");

stateFingerprint = compute_stage_a4_rns1_fingerprint( ...
    stateAfterRound18,"state");
linearizationFingerprint = compute_stage_a4_rns1_fingerprint( ...
    linearizationRound19,"linearization");
prefix = make_prefix_table(chain.iterations);
inputHashes = make_input_hash_table(data.hashes);

sourceEvidence = struct( ...
    "milestone","A4-RNS-1", ...
    "fixture_version","authority-v1", ...
    "source_commit",sourceCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "d2a_implementation_lineage_commit", ...
        "9fcc40167ed6338337732517b5ca9ded7bc03e96", ...
    "generation_command", ...
        "powershell -NoProfile -ExecutionPolicy Bypass -File "+ ...
        "scripts/generate_stage_A4_RNS_1_fixture.ps1 "+ ...
        "-SourceCommit "+sourceCommit+" -ExpectedToolingCommit "+ ...
        options.ToolingCommit, ...
    "source_worktree_clean",sourceClean, ...
    "historical_runs_modified",false, ...
    "formal_a4_run_created",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "stage_b_entered",false, ...
    "matlab_release",string(version("-release")), ...
    "computer_architecture",string(computer("arch")), ...
    "byte_order",local_byte_order(), ...
    "solver_yaml_sha256",compute_sha256_file( ...
        fullfile(sourceProjectRoot,"config","solver.yaml")), ...
    "stage_a4_yaml_sha256",compute_sha256_file( ...
        fullfile(sourceProjectRoot,"config","stage_A4.yaml")), ...
    "authority_chain_state_fingerprint", ...
        chain.failure.state_fingerprint_before, ...
    "state_after_round18_fingerprint",stateFingerprint, ...
    "linearization_round19_fingerprint",linearizationFingerprint, ...
    "round18_min_l",min(stateAfterRound18.l), ...
    "round18_min_z",min(stateAfterRound18.z), ...
    "day17_rhs_count",day17Thomas.rhs_count, ...
    "day17_hour_count",numel(day17Partition.hour), ...
    "day17_chain_dimension",size(day17Partition.M,1), ...
    "full_kkt_dimension",fullAuditRound19.kkt.dimension, ...
    "full_kkt_nnz",nnz(fullAuditRound19.kkt.matrix), ...
    "linearization_nx",numel(linearizationRound19.state.xi), ...
    "linearization_neq",numel(linearizationRound19.state.y), ...
    "linearization_nineq",numel(linearizationRound19.state.l), ...
    "day17_response_symmetry_relative", ...
        day17Response.diagnostics.symmetry_relative, ...
    "authority_loose_direction_relative_error", ...
        looseAudit.direction_relative_error, ...
    "authority_loose_recursive_kkt_relative_residual", ...
        looseAudit.recursive_kkt_relative_residual, ...
    "authority_full_kkt_relative_residual", ...
        looseAudit.full_kkt_relative_residual, ...
    "no_full_direction_fallback", ...
        recursiveLooseRound19.no_full_direction_fallback && ...
        ~recursiveLooseRound19.full_direction_consumed);

authorityLooseDirection = recursiveLooseRound19.direction;
save(paths.mat, ...
    "sourceEvidence","stateAfterRound18","linearizationRound19", ...
    "reducedRound19","day17Partition","day17Thomas", ...
    "day17Response","fullAuditRound19","authorityLooseDirection", ...
    "looseAudit","prefix","inputHashes","-v7");
write_table_csv_17g(paths.prefix,prefix);
write_table_csv_17g(paths.input_hashes,inputHashes);
write_text(paths.command,sourceEvidence.generation_command+newline);

metadata = sourceEvidence;
metadata.mat_file = relative_leaf(paths.mat);
metadata.mat_sha256 = compute_sha256_file(paths.mat);
metadata.prefix_file = relative_leaf(paths.prefix);
metadata.prefix_sha256 = compute_sha256_file(paths.prefix);
metadata.input_hash_file = relative_leaf(paths.input_hashes);
metadata.input_hash_sha256 = compute_sha256_file(paths.input_hashes);
metadata.command_file = relative_leaf(paths.command);
metadata.command_sha256 = compute_sha256_file(paths.command);
write_text(paths.metadata,string(jsonencode(metadata,PrettyPrint=true))+newline);

artifactPath = [relative_leaf(paths.mat);relative_leaf(paths.prefix); ...
    relative_leaf(paths.input_hashes);relative_leaf(paths.command); ...
    relative_leaf(paths.metadata)];
sha256 = strings(numel(artifactPath),1);
for k = 1:numel(artifactPath)
    sha256(k) = compute_sha256_file( ...
        fullfile(stagingDirectory,artifactPath(k)));
end
artifactManifest = table(artifactPath,sha256, ...
    'VariableNames',{'artifact_path','sha256'});
write_table_csv_17g(paths.manifest,artifactManifest);
[moved,message] = movefile(stagingDirectory,outputDirectory);
assert(moved,"stageA4:rns1:FixtureFinalize", ...
    "Unable to finalize fixture directory %s: %s",outputDirectory,message);
finalAudit = verify_finalized_fixture( ...
    outputDirectory,artifactManifest,paths);

result = struct( ...
    "output_directory",outputDirectory, ...
    "source_commit",sourceCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "state_fingerprint",stateFingerprint, ...
    "linearization_fingerprint",linearizationFingerprint, ...
    "day17_response_symmetry_relative", ...
        day17Response.diagnostics.symmetry_relative, ...
    "loose_direction_relative_error", ...
        looseAudit.direction_relative_error, ...
    "loose_recursive_kkt_relative_residual", ...
        looseAudit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual",looseAudit.full_kkt_relative_residual, ...
    "artifact_manifest",artifactManifest, ...
    "finalized_artifact_reverification",finalAudit, ...
    "all_pass",finalAudit.all_pass);
clear stagingCleanup
clear pathCleanup
end

function cleanup_staging_directory(stagingDirectory,outputDirectory)
if ~isfolder(stagingDirectory)
    return
end
stagingDirectory = string(char(java.io.File( ...
    char(stagingDirectory)).getCanonicalPath()));
outputDirectory = string(char(java.io.File( ...
    char(outputDirectory)).getCanonicalPath()));
[stagingParent,stagingName,stagingExtension] = ...
    fileparts(stagingDirectory);
[outputParent,outputName,outputExtension] = ...
    fileparts(outputDirectory);
expectedStagingLeaf = outputName+outputExtension+".building";
safe = stagingParent==outputParent && ...
    stagingName+stagingExtension==expectedStagingLeaf && ...
    endsWith(stagingDirectory,".building");
if safe
    rmdir(stagingDirectory,"s");
end
end

function audit = verify_finalized_fixture( ...
        outputDirectory,artifactManifest,stagingPaths)
finalPaths = fixture_paths(outputDirectory);
artifactPath = string(artifactManifest.artifact_path);
expectedSha256 = lower(string(artifactManifest.sha256));
actualSha256 = strings(numel(artifactPath),1);
exists = false(numel(artifactPath),1);
for k = 1:numel(artifactPath)
    pathValue = fullfile(outputDirectory,artifactPath(k));
    exists(k) = isfile(pathValue);
    if exists(k)
        actualSha256(k) = compute_sha256_file(pathValue);
    end
end
variables = whos("-file",finalPaths.mat);
actualSchema = sort(string({variables.name}).');
expectedSchema = sort([ ...
    "authorityLooseDirection"
    "day17Partition"
    "day17Response"
    "day17Thomas"
    "fullAuditRound19"
    "inputHashes"
    "linearizationRound19"
    "looseAudit"
    "prefix"
    "reducedRound19"
    "sourceEvidence"
    "stateAfterRound18"]);
stagingGone = ~isfolder(fileparts(stagingPaths.mat));
audit = struct( ...
    "all_files_exist",all(exists), ...
    "all_hashes_exact",all(actualSha256==expectedSha256), ...
    "mat_schema_exact",isequal(actualSchema,expectedSchema), ...
    "staging_directory_gone",stagingGone);
audit.all_pass = audit.all_files_exist && audit.all_hashes_exact && ...
    audit.mat_schema_exact && audit.staging_directory_gone;
end

function order = local_byte_order()
[~,~,endian] = computer;
if string(endian)=="L"
    order = "little_endian";
else
    order = "big_endian";
end
end

function root = absolute_existing_folder(root)
root = string(root);
assert(isfolder(root),"stageA4:rns1:SourceFolder", ...
    "The RNS source project root does not exist: %s",root);
original = pwd;
cleanup = onCleanup(@()cd(original));
cd(root);
root = string(pwd);
clear cleanup
end

function [commit,clean] = git_source_evidence(root)
command = sprintf('git -c safe.directory="%s" -C "%s" rev-parse HEAD', ...
    replace(root,"\","/"),root);
[status,output] = system(command);
assert(status==0,"stageA4:rns1:SourceGit", ...
    "Unable to read source worktree HEAD: %s",string(output));
commit = strip(string(output));
command = sprintf('git -c safe.directory="%s" -C "%s" status --porcelain', ...
    replace(root,"\","/"),root);
[status,output] = system(command);
assert(status==0,"stageA4:rns1:SourceGitStatus", ...
    "Unable to read source worktree status: %s",string(output));
clean = strlength(strip(string(output)))==0;
end

function paths = fixture_paths(root)
paths = struct( ...
    "mat",fullfile(root,"stage_A4_RNS_1_round19_authority_v1.mat"), ...
    "metadata",fullfile(root, ...
        "stage_A4_RNS_1_round19_authority_v1.metadata.json"), ...
    "prefix",fullfile(root, ...
        "stage_A4_RNS_1_authority_round_prefix.csv"), ...
    "input_hashes",fullfile(root, ...
        "stage_A4_RNS_1_authority_input_hashes.csv"), ...
    "command",fullfile(root, ...
        "stage_A4_RNS_1_authority_generation_command.txt"), ...
    "manifest",fullfile(root, ...
        "stage_A4_RNS_1_authority_artifact_sha256.csv"));
end

function prefix = make_prefix_table(iterations)
count = numel(iterations);
iteration = reshape([iterations.iteration],[],1);
stateRevisionAfter = reshape([iterations.state_revision_after],[],1);
stateFingerprintAfter = reshape(string( ...
    {iterations.state_fingerprint_after}),[],1);
directionFingerprint = reshape(string( ...
    {iterations.direction_fingerprint}),[],1);
directionRelativeError = reshape( ...
    [iterations.direction_relative_error],[],1);
recursiveKktRelativeResidual = reshape( ...
    [iterations.recursive_kkt_relative_residual],[],1);
fullKktRelativeResidual = reshape( ...
    [iterations.full_kkt_relative_residual],[],1);
noFullDirectionFallback = reshape( ...
    [iterations.no_full_direction_fallback],[],1);
assert(count==18 && isequal(iteration,(1:18).'), ...
    "stageA4:rns1:RoundPrefix", ...
    "The authority prefix must contain rounds 1 through 18.");
prefix = table(iteration,stateRevisionAfter,stateFingerprintAfter, ...
    directionFingerprint,directionRelativeError, ...
    recursiveKktRelativeResidual,fullKktRelativeResidual, ...
    noFullDirectionFallback, ...
    'VariableNames',{'iteration','state_revision_after', ...
    'state_fingerprint_after','direction_fingerprint', ...
    'direction_relative_error','recursive_kkt_relative_residual', ...
    'full_kkt_relative_residual','no_full_direction_fallback'});
end

function result = make_input_hash_table(hashes)
result = table(string(hashes.fileName),double(hashes.actualBytes), ...
    lower(string(hashes.actualSHA256)),string(hashes.status), ...
    'VariableNames',{'file_name','actual_bytes','actual_sha256','status'});
assert(height(result)==2 && all(result.status=="PASS"), ...
    "stageA4:rns1:InputHashes", ...
    "Both controlled input hashes must pass before fixture generation.");
end

function value = relative_leaf(pathValue)
[~,name,extension] = fileparts(pathValue);
value = string(name)+string(extension);
end

function write_text(pathValue,text)
[fileId,message] = fopen(pathValue,"w","n","UTF-8");
assert(fileId>=0,"stageA4:rns1:WriteText", ...
    "Unable to open %s: %s",pathValue,message);
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,"%s",text);
clear cleanup
end
