function acceptance = initialize_stage_a1_acceptance(projectRoot)
%INITIALIZE_STAGE_A1_ACCEPTANCE Load and freeze the complete A1 gate list.

arguments
    projectRoot (1,1) string
end
matrixPath = fullfile(projectRoot,"stages","stage_A1", ...
    "阶段A1_验收矩阵.csv");
options = detectImportOptions(matrixPath,"Encoding","UTF-8", ...
    "Delimiter",",");
options.VariableNamesLine = 1;
options.DataLines = [2 Inf];
options = setvartype(options,options.VariableNames,"string");
matrix = readtable(matrixPath,options);
requiredColumns = ["test_id","requirement","threshold","blocking"];
assert(all(ismember(requiredColumns,string(matrix.Properties.VariableNames))), ...
    "stageA1:acceptance:InvalidMatrix", ...
    "Stage A1 acceptance matrix is missing a required column.");

expectedIds = ["SA1-ENV-001";"SA1-DATA-001";"SA1-MAT-001"; ...
    "SA1-MAT-002";"SA1-BLK-001";"SA1-LIN-001";"SA1-BND-001"; ...
    "SA1-EQ-001";"SA1-EQ-002";"SA1-EQ-003";"SA1-IDX-001"; ...
    "SA1-IDX-002";"SA1-NUM-001";"SA1-ART-001";"SA1-SCOPE-001"];
ids = string(matrix.test_id);
assert(numel(unique(ids)) == numel(ids), ...
    "stageA1:acceptance:DuplicateId", ...
    "Stage A1 acceptance IDs must be unique.");
assert(isequal(ids,expectedIds),"stageA1:acceptance:UnexpectedInventory", ...
    "Stage A1 acceptance inventory or ordering differs from the frozen list.");
blocking = matrix.blocking;
if ~islogical(blocking)
    blocking = lower(strip(string(blocking))) == "true";
end
assert(all(blocking),"stageA1:acceptance:NonblockingRow", ...
    "Every frozen Stage A1 acceptance item is blocking.");
n = height(matrix);
acceptance = table(ids,string(matrix.requirement),string(matrix.threshold), ...
    repmat("",n,1),repmat("",n,1),repmat("NOT_RUN",n,1), ...
    logical(blocking),repmat("",n,1),repmat("",n,1), ...
    'VariableNames',{'test_id','requirement','threshold','actual_value', ...
    'comparison','status','blocking','evidence_path','checked_at'});
end
