function environment = inspect_stage_b2b_environment()
%INSPECT_STAGE_B2B_ENVIRONMENT Record capabilities used by one direction.

checked = string(datetime("now","TimeZone","Asia/Shanghai", ...
    "Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
id = ["MATLAB_RELEASE";"SPARSE_LINEAR_ALGEBRA";"LDL_FACTORIZATION"; ...
    "FULL_KKT_AUDIT";"RECURSIVE_DIRECTION";"IPM_OPTIMIZATION"; ...
    "PARALLEL_EXECUTION"];
component = ["MATLAB R2024a";"sparse matrices";"sparse LDL"; ...
    "independent sparse audit solve";"daily bordered LDL/Thomas"; ...
    "full IPM / optimization";"parpool / parfor"];
expected = ["2024a";"available";"available";"audit_only"; ...
    "one_direction";"not_executed";"off"];
actual = [string(version("-release")); ...
    string(exist("sparse","builtin")>0 || exist("sparse","file")>0); ...
    string(exist("ldl","file")>0);"audit_only";"one_direction"; ...
    "not_executed";"off"];
available = [actual(1)=="2024a";actual(2)=="1";actual(3)=="1"; ...
    true;true;true;true];
blocking = true(numel(id),1);
status = repmat("PASS",numel(id),1);
status(~available) = "FAIL";
details = ["Required release";"No dense conversion of day/full KKT"; ...
    "Used only through retained symmetric block factors"; ...
    "Raw nonsymmetric KKT is solved by sparse backslash for audit only"; ...
    "Seven daily chains, eight-row borders, and one 16-D core"; ...
    "No state update or convergence loop";"Serial execution only"];
environment = table(id,component,blocking,expected,actual,status, ...
    available,repmat(checked,numel(id),1),details, ...
    'VariableNames',{'check_id','component','blocking','expected', ...
    'actual','status','available','checked_at','details'});
end
