function config = ...
        load_stage_a4_iteration24_scaling_stress_configuration(projectRoot)
%LOAD_STAGE_A4_ITERATION24_SCALING_STRESS_CONFIGURATION Read frozen YAML.
%
% This intentionally parses only the scalar/list fields owned by the
% independent stress milestone.  It makes the copied effective_config.yaml
% an actual execution input rather than a documentary snapshot.

arguments
    projectRoot (1,1) string
end

pathValue = fullfile(projectRoot,"config", ...
    "stage_A4_iteration24_scaling_stress.yaml");
assert(isfile(pathValue),"stageA4:scaleStress:ConfigMissing", ...
    "The scaling-stress configuration is missing.");
lines = strip(readlines(pathValue));
lines = lines(strlength(lines)>0 & ~startsWith(lines,"#"));

config = struct( ...
    "path",string(pathValue), ...
    "sha256",string(compute_sha256_file(pathValue)), ...
    "stage_id",text_value(lines,"stage_id"), ...
    "status",text_value(lines,"status"), ...
    "milestone",text_value(lines,"milestone"), ...
    "run_purpose",text_value(lines,"run_purpose"), ...
    "authority_run_id",text_value(lines,"authority_run_id"), ...
    "authority_state_revision", ...
        numeric_value(lines,"authority_state_revision"), ...
    "attempted_iteration",numeric_value(lines,"attempted_iteration"), ...
    "data_days",numeric_list(lines,"data_days"), ...
    "data_hours",numeric_list(lines,"data_hours"), ...
    "recursive_route",text_value(lines,"recursive_route"), ...
    "sigma",numeric_value(lines,"sigma"), ...
    "tau",numeric_value(lines,"tau"), ...
    "initialization_id",text_value(lines,"initialization_id"), ...
    "step_rule",text_value(lines,"step_rule"), ...
    "use_congruence_scaling", ...
        logical_value(lines,"use_congruence_scaling"), ...
    "equilibration_passes", ...
        numeric_value(lines,"equilibration_passes"), ...
    "recursive_refinement_max_passes", ...
        numeric_value(lines,"recursive_refinement_max_passes"), ...
    "repeat_count",numeric_value(lines,"repeat_count"), ...
    "direction_relative_engineering_tolerance", ...
        numeric_value(lines, ...
        "direction_relative_engineering_tolerance"), ...
    "recursive_full_kkt_residual_engineering_tolerance", ...
        numeric_value(lines, ...
        "recursive_full_kkt_residual_engineering_tolerance"), ...
    "full_kkt_audit_residual_tolerance", ...
        numeric_value(lines,"full_kkt_audit_residual_tolerance"), ...
    "symmetry_relative_tolerance", ...
        numeric_value(lines,"symmetry_relative_tolerance"), ...
    "state_update_count",numeric_value(lines,"state_update_count"), ...
    "full_ipm_executed",logical_value(lines,"full_ipm_executed"), ...
    "optimization_executed", ...
        logical_value(lines,"optimization_executed"), ...
    "parallel_executed",logical_value(lines,"parallel_executed"), ...
    "formal_a4_run",logical_value(lines,"formal_a4_run"), ...
    "complete_kkt_role",text_value(lines,"complete_kkt_role"), ...
    "automatic_symmetrization_enabled", ...
        logical_value(lines,"automatic_symmetrization_enabled"), ...
    "regularization_enabled", ...
        logical_value(lines,"regularization_enabled"), ...
    "full_kkt_direction_fallback_enabled", ...
        logical_value(lines,"full_kkt_direction_fallback_enabled"), ...
    "model_or_input_change_enabled", ...
        logical_value(lines,"model_or_input_change_enabled"), ...
    "centering_sigma_changed", ...
        logical_value(lines,"centering_sigma_changed"), ...
    "fraction_to_boundary_changed", ...
        logical_value(lines,"fraction_to_boundary_changed"), ...
    "initialization_changed", ...
        logical_value(lines,"initialization_changed"), ...
    "step_rule_changed",logical_value(lines,"step_rule_changed"));

assert(config.stage_id=="stage_A4" && config.status=="READY" && ...
    config.milestone=="A4-ITER24-SCALE-STRESS" && ...
    config.authority_run_id== ...
        "20260728_112548_stage_A4_1f3836ca" && ...
    config.authority_state_revision==23 && ...
    config.attempted_iteration==24 && ...
    isequal(config.data_days,14:20) && ...
    isequal(config.data_hours,1:24) && ...
    config.sigma==0.1 && config.tau==0.9995 && ...
    config.initialization_id=="stageA4-deterministic-interior-v1.0" && ...
    config.step_rule=="independent_alpha_primal_alpha_dual" && ...
    config.use_congruence_scaling && ...
    config.equilibration_passes==8 && ...
    config.recursive_refinement_max_passes==3 && ...
    config.repeat_count==2 && ...
    config.direction_relative_engineering_tolerance==1e-10 && ...
    config.recursive_full_kkt_residual_engineering_tolerance==1e-10 && ...
    config.full_kkt_audit_residual_tolerance==1e-10 && ...
    config.symmetry_relative_tolerance==1e-12 && ...
    config.state_update_count==0 && ...
    ~config.full_ipm_executed && ...
    ~config.optimization_executed && ...
    ~config.parallel_executed && ...
    ~config.formal_a4_run && ...
    config.complete_kkt_role=="independent_audit_only" && ...
    ~config.automatic_symmetrization_enabled && ...
    ~config.regularization_enabled && ...
    ~config.full_kkt_direction_fallback_enabled && ...
    ~config.model_or_input_change_enabled && ...
    ~config.centering_sigma_changed && ...
    ~config.fraction_to_boundary_changed && ...
    ~config.initialization_changed && ...
    ~config.step_rule_changed, ...
    "stageA4:scaleStress:ConfigContract", ...
    "The scaling-stress YAML differs from the frozen execution contract.");
end

function value = text_value(lines,key)
raw = raw_value(lines,key);
if startsWith(raw,'"') && endsWith(raw,'"')
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
end

function value = numeric_value(lines,key)
raw = raw_value(lines,key);
value = str2double(raw);
assert(isscalar(value) && isfinite(value), ...
    "stageA4:scaleStress:ConfigNumeric", ...
    "Configuration field %s is not a finite scalar.",key);
end

function value = logical_value(lines,key)
raw = lower(raw_value(lines,key));
assert(ismember(raw,["true","false"]), ...
    "stageA4:scaleStress:ConfigLogical", ...
    "Configuration field %s is not true/false.",key);
value = raw=="true";
end

function value = numeric_list(lines,key)
raw = raw_value(lines,key);
assert(startsWith(raw,"[") && endsWith(raw,"]"), ...
    "stageA4:scaleStress:ConfigList", ...
    "Configuration field %s is not a numeric list.",key);
inside = extractBetween(raw,2,strlength(raw)-1);
parts = strip(split(inside,","));
value = reshape(str2double(parts),1,[]);
assert(all(isfinite(value)), ...
    "stageA4:scaleStress:ConfigListNumeric", ...
    "Configuration field %s has a nonnumeric list item.",key);
end

function value = raw_value(lines,key)
prefix = string(key)+":";
matches = startsWith(lines,prefix);
assert(nnz(matches)==1,"stageA4:scaleStress:ConfigField", ...
    "Configuration field %s must appear exactly once.",key);
value = strip(extractAfter(lines(matches),strlength(prefix)));
value = string(value);
end
