function issues = new_stage_a1_issue_log()
%NEW_STAGE_A1_ISSUE_LOG Create the Stage A1 issue evidence schema.

names = {'issue_id','run_id','stage_id','test_id','elimination_layer', ...
    'variable_or_equation','symptom','error_message','root_cause', ...
    'proposed_solution','git_commit','regression_test','status', ...
    'evidence_path','recorded_at'};
types = repmat({'string'},1,numel(names));
issues = table('Size',[0,numel(names)],'VariableTypes',types, ...
    'VariableNames',names);
end
