function issues = new_stage0_issue_log()
%NEW_STAGE0_ISSUE_LOG Create a schema-aligned empty issue log table.

names = {'issue_id','run_id','stage_id','first_seen_iteration','test_id', ...
    'symptom','error_message','root_cause','proposed_solution', ...
    'implemented_change','git_commit','regression_test','status','evidence_path'};
types = {'string','string','string','double','string','string','string', ...
    'string','string','string','string','string','string','string'};
issues = table('Size',[0,numel(names)],'VariableTypes',types, ...
    'VariableNames',names);
end
