function result = run_stage_b2a_static_checks(projectRoot)
%RUN_STAGE_B2A_STATIC_CHECKS Code Analyzer and forbidden-call evidence.

arguments
    projectRoot (1,1) string
end
relative = [ ...
    "main_stage_B_2A.m"; ...
    "src/indexing/build_stage_b_index.m"; ...
    "src/model/load_stage_b2a_configuration.m"; ...
    "src/model/assemble_stage_b_water_linearization.m"; ...
    "src/model/initialize_stage_b2a_state.m"; ...
    "src/model/build_stage_b_multiday_linearization.m"; ...
    "src/solver/assemble_stage_b_multiday_full_kkt.m"; ...
    "src/diagnostics/inspect_stage_b2a_environment.m"; ...
    "src/diagnostics/build_stage_b2a_audits.m"; ...
    "src/diagnostics/run_stage_b2a_static_checks.m"; ...
    "src/reporting/generate_stage_b2a_report.m"; ...
    "src/reporting/write_stage_b2a_docx.m"; ...
    "src/reporting/validate_stage_b2a_report.m"; ...
    "tests/run_stage_B_2A_tests.m"; ...
    "tests/run_stage_B_2A_stage_A_regressions.m"; ...
    "tests/unit/test_stage_b2a_index.m"; ...
    "tests/unit/test_stage_b2a_linearization.m"; ...
    "tests/unit/test_stage_b2a_full_kkt_structure.m"; ...
    "tests/integration/test_stage_b2a_stage_a_regression.m"];
relative = relative(arrayfun(@(x)isfile(fullfile(projectRoot, ...
    replace(x,"/",filesep))),relative));

n = numel(relative);
file = relative;
finding_count = zeros(n,1);
status = repmat("PASS",n,1);
details = strings(n,1);
for k = 1:n
    absolute = fullfile(projectRoot,replace(relative(k),"/",filesep));
    findings = checkcode(absolute,"-id");
    finding_count(k) = numel(findings);
    if isempty(findings)
        details(k) = "0 Code Analyzer findings";
    else
        status(k) = "FAIL";
        details(k) = strjoin(string({findings.id})+":"+ ...
            string({findings.message})," | ");
    end
end
codeAnalyzer = table(file,finding_count,status,details);

production = relative(startsWith(relative,"src/") | ...
    startsWith(relative,"main_stage_B_2A"));
pattern = ["(?i)\binv\s*\(";"(?i)\bpinv\s*\("; ...
    "(?i)\blsqminnorm\s*\(";"(?i)\bldl\s*\("; ...
    "(?i)\bparfor\b";"(?i)\bparpool\s*\("; ...
    "(?i)\bsolve_stage_.*kkt";"(?i)\bthomas\w*\s*\("; ...
    "(?i)\bschur\w*\s*\(";"(?i)\bregulari[sz]\w*\s*\("];
rule_id = ["NO_INV";"NO_PINV";"NO_LSQMINNORM";"NO_LDL"; ...
    "NO_PARFOR";"NO_PARPOOL";"NO_KKT_SOLVE_CALL";"NO_THOMAS"; ...
    "NO_SCHUR";"NO_REGULARIZATION"];
forbidden = repmat(forbidden_template(),numel(pattern),1);
for r = 1:numel(pattern)
    matches = strings(0,1);
    for k = 1:numel(production)
        absolute = fullfile(projectRoot,replace(production(k),"/",filesep));
        source = strip_comments(string(fileread(absolute)));
        if ~isempty(regexp(char(source),char(pattern(r)),"once"))
            matches(end+1,1) = production(k); %#ok<AGROW>
        end
    end
    forbidden(r).rule_id = char(rule_id(r));
    forbidden(r).pattern = char(pattern(r));
    forbidden(r).matching_files = char(strjoin(matches,"|"));
    forbidden(r).match_count = numel(matches);
    if isempty(matches)
        forbidden(r).status = "PASS";
    end
end
forbiddenExecution = struct2table(forbidden);
result = struct("code_analyzer",codeAnalyzer, ...
    "forbidden_execution",forbiddenExecution, ...
    "all_pass",all(codeAnalyzer.status=="PASS") && ...
        all(string(forbiddenExecution.status)=="PASS"), ...
    "blocking_findings",sum(codeAnalyzer.finding_count), ...
    "forbidden_failures",sum(string(forbiddenExecution.status)~="PASS"));
end

function value = strip_comments(source)
lines = splitlines(source);
for k = 1:numel(lines)
    line = lines(k);
    comment = regexp(char(line),'(?<!'')%(?!'')','once');
    if ~isempty(comment)
        lines(k) = extractBefore(line,comment);
    end
end
value = strjoin(lines,newline);
end

function value = forbidden_template()
value = struct("rule_id","","pattern","","matching_files","", ...
    "match_count",0,"status","FAIL");
end
