function result = run_stage_a4_rns1_stability_audit(projectRoot)
%RUN_STAGE_A4_RNS1_STABILITY_AUDIT Audit the frozen round-19 stress input.
%
% This milestone performs one recursive Newton direction twice for
% determinism.  It does not update the primal-dual state, rerun D2A, create
% a formal run, or consume the complete-KKT direction as a fallback.

arguments
    projectRoot (1,1) string
end

fixtureRoot = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_RNS_1_authority_v1");
metadataPath = fullfile(fixtureRoot, ...
    "stage_A4_RNS_1_round19_authority_v1.metadata.json");
manifestPath = fullfile(fixtureRoot, ...
    "stage_A4_RNS_1_authority_artifact_sha256.csv");
matPath = fullfile(fixtureRoot, ...
    "stage_A4_RNS_1_round19_authority_v1.mat");
require_file(metadataPath);
require_file(manifestPath);
require_file(matPath);

metadata = jsondecode(fileread(metadataPath));
artifactAudit = verify_artifact_hashes( ...
    fixtureRoot,manifestPath,metadata);
fixture = load(matPath);
config = load_stage_a4_configuration(projectRoot);
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY" && ...
    config.symmetry_relative_tolerance==1e-12 && ...
    config.direction_relative_tolerance==1e-10 && ...
    config.recursive_full_kkt_residual_tolerance==1e-10, ...
    "stageA4:rns1:FrozenGovernance", ...
    "A4-RNS-1 requires stage_A4 / READY and frozen 1e-12/1e-10 audits.");

stateFingerprint = compute_stage_a4_rns1_fingerprint( ...
    fixture.stateAfterRound18,"state");
linearizationFingerprint = compute_stage_a4_rns1_fingerprint( ...
    fixture.linearizationRound19,"linearization");
inputHashAudit = verify_current_input_hashes( ...
    projectRoot,fixture.inputHashes);
authorityAudit = verify_authority_failure_evidence( ...
    projectRoot,fixture,metadata,matPath);
fixtureAudit = struct( ...
    "source_commit",string(metadata.source_commit), ...
    "source_commit_exact",string(metadata.source_commit)== ...
        "58b2b3645b79c71460ff0de1a03033c319829cd6", ...
    "state_fingerprint",stateFingerprint, ...
    "state_fingerprint_exact",stateFingerprint== ...
        string(metadata.state_after_round18_fingerprint), ...
    "linearization_fingerprint",linearizationFingerprint, ...
    "linearization_fingerprint_exact",linearizationFingerprint== ...
        string(metadata.linearization_round19_fingerprint), ...
    "artifact_hashes",artifactAudit, ...
    "input_hashes",inputHashAudit, ...
    "authority_failure",authorityAudit, ...
    "day17_authority_symmetry_relative", ...
        fixture.day17Response.diagnostics.symmetry_relative, ...
    "authority_loose_direction_relative_error", ...
        fixture.looseAudit.direction_relative_error, ...
    "authority_loose_recursive_kkt_relative_residual", ...
        fixture.looseAudit.recursive_kkt_relative_residual);
fixtureAudit.all_pass = fixtureAudit.source_commit_exact && ...
    fixtureAudit.state_fingerprint_exact && ...
    fixtureAudit.linearization_fingerprint_exact && ...
    artifactAudit.all_pass && inputHashAudit.all_pass && ...
    authorityAudit.all_pass;

try
    first = solve_stage_a_multiday_recursive_direction( ...
        fixture.linearizationRound19, ...
        AssemblyTolerance=1e-12,SymmetryTolerance=1e-12, ...
        ResidualRefinementMaxPasses=3);
    second = solve_stage_a_multiday_recursive_direction( ...
        fixture.linearizationRound19, ...
        AssemblyTolerance=1e-12,SymmetryTolerance=1e-12, ...
        ResidualRefinementMaxPasses=3);
catch cause
    result = failed_result(fixtureAudit,cause);
    return
end

fullAudit = fixture.fullAuditRound19;
directionAudit = verify_stage_a_multiday_direction_equivalence( ...
    fullAudit,first,fixture.linearizationRound19, ...
    DirectionRelative=1e-10,RecursiveResidual=1e-10, ...
    FullResidualPreferred=1e-12,FullResidualMaximum=1e-10);
directResidual = directionAudit.full_kkt_relative_residual;
dayIds = reshape([first.daily_responses.day_id],[],1);
day17Position = find(dayIds==17);
assert(isscalar(day17Position), ...
    "stageA4:rns1:StableDay17", ...
    "The stable result must contain exactly one day-17 response.");
day17 = first.daily_responses(day17Position);
refinementTable = make_refinement_table(first);
operatorAudit = audit_factorized_operators(first);
determinism = audit_determinism(first,second);

componentErrors = directionAudit.component_relative_errors;
componentVector = [componentErrors.xi;componentErrors.y; ...
    componentErrors.l;componentErrors.z];
recursiveResidual = directionAudit.recursive_kkt_relative_residual;
engineeringTarget = 5e-11;
if recursiveResidual<=engineeringTarget
    marginStatus = "SUFFICIENT";
else
    marginStatus = "INSUFFICIENT";
end
blocking = struct( ...
    "day17_response_symmetry", ...
        day17.diagnostics.symmetry_relative<=1e-12, ...
    "overall_direction", ...
        directionAudit.direction_relative_error<=1e-10, ...
    "component_directions",all(componentVector<=1e-10), ...
    "recursive_full_kkt_residual",recursiveResidual<=1e-10, ...
    "direct_full_kkt_residual",directResidual<=1e-10, ...
    "fixed_zero_exact",directionAudit.passed.fixed_zero_exact, ...
    "day_sort_invariant",directionAudit.passed.day_sort_invariant, ...
    "no_full_direction_fallback", ...
        first.no_full_direction_fallback && ...
        ~first.full_direction_consumed, ...
    "positive_input_state", ...
        min(fixture.linearizationRound19.l)>0 && ...
        min(fixture.linearizationRound19.z)>0, ...
    "operator_identity_audit",operatorAudit.all_pass, ...
    "bounded_refinement", ...
        all(refinementTable.selected_pass<=3) && ...
        all(refinementTable.passes_attempted<=3) && ...
        all(refinementTable.additional_factorization_count==0), ...
    "deterministic_repeat",determinism.all_pass, ...
    "fixture_evidence",fixtureAudit.all_pass);
blockingValues = struct2cell(blocking);
allBlockingPass = all(cellfun(@(value)isequal(value,true), ...
    blockingValues));

result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-RNS-1";
if allBlockingPass
    result.milestone_status = "PASS";
else
    result.milestone_status = "FAIL_RETRYABLE";
end
result.fixture = fixtureAudit;
result.first = first;
result.second = second;
result.refinement = refinementTable;
result.operator_audit = operatorAudit;
result.determinism = determinism;
result.direction_audit = directionAudit;
result.actual = struct( ...
    "day17_response_symmetry_relative", ...
        day17.diagnostics.symmetry_relative, ...
    "direction_relative_error", ...
        directionAudit.direction_relative_error, ...
    "xi_relative_error",componentErrors.xi, ...
    "y_relative_error",componentErrors.y, ...
    "l_relative_error",componentErrors.l, ...
    "z_relative_error",componentErrors.z, ...
    "recursive_full_kkt_relative_residual",recursiveResidual, ...
    "direct_full_kkt_relative_residual",directResidual, ...
    "minimum_l",min(fixture.linearizationRound19.l), ...
    "minimum_z",min(fixture.linearizationRound19.z), ...
    "engineering_target",engineeringTarget, ...
    "numerical_margin_status",marginStatus, ...
    "engineering_margin_is_nonblocking",true);
result.blocking = blocking;
result.all_blocking_pass = allBlockingPass;
result.failure = struct("present",false,"identifier","","message","");
if fixtureAudit.authority_failure.all_pass
    result.d2a_original_status_preserved = "FAIL_RETRYABLE";
else
    result.d2a_original_status_preserved = "UNVERIFIED";
end
result.stage_a4_pass_claimed = false;
result.execution = struct( ...
    "recursive_newton_direction_count",2, ...
    "state_update_count",0, ...
    "full_kkt_direction_solve_count",0, ...
    "full_kkt_audit_matvec_count",2, ...
    "complete_kkt_direction_fallback_used",false, ...
    "hundred_round_run_executed",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "d2a_rerun_executed",false, ...
    "stage_b_entered",false);
end

function audit = verify_artifact_hashes(root,manifestPath,metadata)
expectedManifestSha256 = ...
    "391517925f12d5654d2cc46de187e8807420e5761a8bba203e2010686e076fd5";
manifestSha256 = compute_sha256_file(manifestPath);
manifest = readtable(manifestPath,Delimiter=',', ...
    ReadVariableNames=true,TextType="string", ...
    VariableNamingRule="preserve");
required = ["artifact_path","sha256"];
assert(all(ismember(required,string(manifest.Properties.VariableNames))), ...
    "stageA4:rns1:ArtifactManifestSchema", ...
    "The RNS authority artifact manifest schema is invalid.");
expectedNames = [ ...
    "stage_A4_RNS_1_round19_authority_v1.mat"
    "stage_A4_RNS_1_authority_round_prefix.csv"
    "stage_A4_RNS_1_authority_input_hashes.csv"
    "stage_A4_RNS_1_authority_generation_command.txt"
    "stage_A4_RNS_1_round19_authority_v1.metadata.json"];
names = string(manifest.artifact_path);
namesAreUnique = numel(unique(names))==numel(names);
namesExact = isequal(names,expectedNames);
safeLeafNames = all(arrayfun(@is_safe_leaf,names));
hashShapeExact = all(~cellfun("isempty", ...
    regexp(cellstr(lower(string(manifest.sha256))), ...
    '^[0-9a-f]{64}$','once')));
actual = strings(height(manifest),1);
exists = false(height(manifest),1);
for k = 1:height(manifest)
    pathValue = fullfile(root,names(k));
    exists(k) = isfile(pathValue);
    if exists(k)
        actual(k) = compute_sha256_file(pathValue);
    end
end
expected = lower(string(manifest.sha256));
matches = exists & actual==expected;
metadataNames = [string(metadata.mat_file); ...
    string(metadata.prefix_file);string(metadata.input_hash_file); ...
    string(metadata.command_file);expectedNames(5)];
metadataHashes = lower([string(metadata.mat_sha256); ...
    string(metadata.prefix_sha256);string(metadata.input_hash_sha256); ...
    string(metadata.command_sha256);expected(5)]);
metadataCrossExact = isequal(metadataNames,expectedNames) && ...
    isequal(metadataHashes,expected);
audit = struct( ...
    "count",height(manifest), ...
    "manifest_sha256",manifestSha256, ...
    "manifest_root_exact",manifestSha256==expectedManifestSha256, ...
    "names_unique",namesAreUnique, ...
    "names_exact",namesExact, ...
    "safe_leaf_names",safeLeafNames, ...
    "hash_shape_exact",hashShapeExact, ...
    "metadata_cross_reference_exact",metadataCrossExact, ...
    "all_exist",all(exists), ...
    "all_match",all(matches), ...
    "actual_sha256",actual, ...
    "expected_sha256",expected, ...
    "all_pass",height(manifest)==5 && ...
        manifestSha256==expectedManifestSha256 && ...
        namesAreUnique && namesExact && safeLeafNames && ...
        hashShapeExact && metadataCrossExact && all(matches));
end

function value = is_safe_leaf(pathValue)
pathValue = string(pathValue);
[folder,name,extension] = fileparts(pathValue);
value = strlength(folder)==0 && ...
    pathValue==string(name)+string(extension) && ...
    ~contains(pathValue,["..","/","\"]) && strlength(pathValue)>0;
end

function audit = verify_authority_failure_evidence( ...
        projectRoot,fixture,metadata,matPath)
expected = struct( ...
    "source_commit","58b2b3645b79c71460ff0de1a03033c319829cd6", ...
    "tooling_commit","8722eb86cbc10190b1d60afc60868de9ef35cde4", ...
    "lineage_commit","9fcc40167ed6338337732517b5ca9ded7bc03e96", ...
    "completed_round_count",18, ...
    "attempted_round",19, ...
    "day_id",17, ...
    "symmetry_relative",1.2272255924590032e-12, ...
    "direction_relative_error",6.4303876423081673e-9, ...
    "recursive_kkt_relative_residual",2.8387370718492251e-10, ...
    "direct_kkt_relative_residual",1.2503952621846266e-14, ...
    "failure_identifier","stageAMultiday:solver:RecursiveLayerFailure", ...
    "failure_cause_identifier","stageAMultiday:solver:DayResponseAsymmetry");
expected.failure_cause_message = string(sprintf( ...
    "Day %d response symmetry error %.17g exceeds %.17g; "+ ...
    "no matrix modification was applied.", ...
    expected.day_id,expected.symmetry_relative,1e-12));
expected.failure_message = "stage_A4 recursion failed first at layer "+ ...
    "'day_17_response': "+expected.failure_cause_message;

variables = whos("-file",matPath);
schema = sort(string({variables.name}).');
expectedSchema = sort([ ...
    "authorityLooseDirection"
    "day17Partition"
    "day17Response"
    "day17Thomas"
    "fullAuditRound19"
    "inputHashes"
    "linearizationRound19"
    "looseAudit"
    "prefix"
    "reducedRound19"
    "sourceEvidence"
    "stateAfterRound18"]);
schemaExact = isequal(schema,expectedSchema);

prefix = fixture.prefix;
roundsExact = height(prefix)==expected.completed_round_count && ...
    isequal(double(prefix.iteration),(1:18).') && ...
    all(logical(prefix.no_full_direction_fallback));
stateBoundaryExact = fixture.stateAfterRound18.state_revision==18 && ...
    fixture.stateAfterRound18.iteration_index==18 && ...
    fixture.stateAfterRound18.iteration_index+1== ...
        expected.attempted_round && ...
    string(prefix.state_fingerprint_after(end))== ...
        string(metadata.authority_chain_state_fingerprint);
source = fixture.sourceEvidence;
sourceExact = string(metadata.source_commit)==expected.source_commit && ...
    string(metadata.tooling_commit)==expected.tooling_commit && ...
    string(metadata.d2a_implementation_lineage_commit)== ...
        expected.lineage_commit && ...
    string(source.source_commit)==expected.source_commit && ...
    string(source.tooling_commit)==expected.tooling_commit && ...
    string(source.d2a_implementation_lineage_commit)== ...
        expected.lineage_commit;
numericSignatureExact = ...
    fixture.day17Response.diagnostics.symmetry_relative== ...
        expected.symmetry_relative && ...
    fixture.looseAudit.direction_relative_error== ...
        expected.direction_relative_error && ...
    fixture.looseAudit.recursive_kkt_relative_residual== ...
        expected.recursive_kkt_relative_residual && ...
    fixture.looseAudit.full_kkt_relative_residual== ...
        expected.direct_kkt_relative_residual && ...
    double(metadata.day17_response_symmetry_relative)== ...
        expected.symmetry_relative && ...
    double(metadata.authority_loose_direction_relative_error)== ...
        expected.direction_relative_error && ...
    double(metadata.authority_loose_recursive_kkt_relative_residual)== ...
        expected.recursive_kkt_relative_residual && ...
    double(metadata.authority_full_kkt_relative_residual)== ...
        expected.direct_kkt_relative_residual;
failureLogicExact = ...
    fixture.day17Response.diagnostics.symmetry_relative>1e-12 && ...
    ~fixture.looseAudit.passed.direction && ...
    ~fixture.looseAudit.passed.recursive_residual && ...
    fixture.looseAudit.passed.full_residual_hard && ...
    logical(metadata.no_full_direction_fallback) && ...
    fixture.fullAuditRound19.audit_only && ...
    ~fixture.fullAuditRound19.consumed_by_recursive;
toolingCommitAnchorExact = ...
    string(metadata.tooling_commit)==expected.tooling_commit && ...
    string(source.tooling_commit)==expected.tooling_commit;
logExact = verify_d2a_failure_log(projectRoot,expected);

audit = struct( ...
    "completed_round_count",height(prefix), ...
    "attempted_round",fixture.stateAfterRound18.iteration_index+1, ...
    "failure_day_id",expected.day_id, ...
    "failure_identifier",expected.failure_identifier, ...
    "failure_cause_identifier",expected.failure_cause_identifier, ...
    "failure_message",expected.failure_message, ...
    "mat_schema_exact",schemaExact, ...
    "round_prefix_exact",roundsExact, ...
    "round18_boundary_exact",stateBoundaryExact, ...
    "source_and_tooling_commit_exact",sourceExact, ...
    "numeric_failure_signature_exact",numericSignatureExact, ...
    "failure_logic_exact",failureLogicExact, ...
    "tooling_commit_anchor_exact",toolingCommitAnchorExact, ...
    "stage_log_failure_record_exact",logExact);
values = struct2cell(rmfield(audit, ...
    ["completed_round_count","attempted_round","failure_day_id", ...
    "failure_identifier","failure_cause_identifier","failure_message"]));
audit.all_pass = all(cellfun(@(value)isequal(value,true),values));
end

function exact = verify_d2a_failure_log(projectRoot,expected)
logPath = fullfile(projectRoot,"stages","stage_A4", ...
    "阶段A4_状态与决策日志.md");
text = string(fileread(logPath));
exact = contains(text,expected.lineage_commit) && ...
    contains(text,"A4-2D-2A 终态：`FAIL_RETRYABLE`") && ...
    contains(text,"首个失败层级：`day_17_response`") && ...
    contains(text,expected.failure_identifier) && ...
    contains(text,"1.2272255924590032e-12") && ...
    contains(text,"第19轮");
end

function audit = verify_current_input_hashes(projectRoot,frozen)
[current,allMatch] = verify_input_hashes(projectRoot);
currentNames = string(current.fileName);
frozenNames = string(frozen.file_name);
[sortedCurrent,currentOrder] = sort(currentNames);
[sortedFrozen,frozenOrder] = sort(frozenNames);
namesExact = isequal(sortedCurrent,sortedFrozen);
hashesExact = namesExact && isequal( ...
    lower(string(current.actualSHA256(currentOrder))), ...
    lower(string(frozen.actual_sha256(frozenOrder))));
audit = struct( ...
    "manifest_pass",allMatch, ...
    "names_exact",namesExact, ...
    "hashes_exact",hashesExact, ...
    "all_pass",allMatch && namesExact && hashesExact);
end

function tableValue = make_refinement_table(recursive)
dayCount = numel(recursive.daily_thomas);
objectType = [repmat("day_chain",dayCount,1);"global_core"];
dayId = [reshape([recursive.daily_responses.day_id],[],1);0];
selectedPass = zeros(dayCount+1,1);
passesAttempted = zeros(dayCount+1,1);
initialResidual = zeros(dayCount+1,1);
finalResidual = zeros(dayCount+1,1);
reductionRatio = zeros(dayCount+1,1);
stopReason = strings(dayCount+1,1);
targetMet = false(dayCount+1,1);
additionalFactorizationCount = zeros(dayCount+1,1);
for d = 1:dayCount
    item = recursive.daily_thomas(d).diagnostics.residual_refinement;
    selectedPass(d) = item.selected_pass;
    passesAttempted(d) = item.passes_attempted;
    initialResidual(d) = item.initial_maximum_column_relative;
    finalResidual(d) = item.final_maximum_column_relative;
    reductionRatio(d) = item.residual_reduction_ratio;
    stopReason(d) = item.stop_reason;
    targetMet(d) = item.target_met;
    additionalFactorizationCount(d) = ...
        item.additional_factorization_count;
end
item = recursive.core.diagnostics.residual_refinement;
selectedPass(end) = item.selected_pass;
passesAttempted(end) = item.passes_attempted;
initialResidual(end) = item.initial_maximum_column_relative;
finalResidual(end) = item.final_maximum_column_relative;
reductionRatio(end) = item.residual_reduction_ratio;
stopReason(end) = item.stop_reason;
targetMet(end) = item.target_met;
additionalFactorizationCount(end) = ...
    item.additional_factorization_count;
tableValue = table(objectType,dayId,selectedPass,passesAttempted, ...
    initialResidual,finalResidual,reductionRatio,stopReason,targetMet, ...
    additionalFactorizationCount, ...
    'VariableNames',{'object_type','day_id','selected_pass', ...
    'passes_attempted','initial_maximum_column_relative', ...
    'final_maximum_column_relative','residual_reduction_ratio', ...
    'stop_reason','target_met','additional_factorization_count'});
end

function audit = audit_factorized_operators(recursive)
factorCount = 0;
reconstructionExact = true;
available = true;
rawMismatchMaximum = 0;
rawResidualRebuildExact = true;
retainedContextExact = true;
factorizedSolveResiduals = zeros(0,1);
factorizedSolveAuditCount = 0;
for d = 1:numel(recursive.daily_thomas)
    factors = recursive.daily_thomas(d).factors;
    schurBlocks = recursive.daily_thomas(d).schur_blocks;
    factorCount = factorCount+numel(factors);
    for k = 1:numel(factors)
        factor = factors{k};
        reconstructedPermuted = factor.L*factor.D*factor.L.';
        permutationMatrix = sparse(factor.permutation, ...
            1:factor.dimension,1,factor.dimension,factor.dimension);
        reconstructed = permutationMatrix*reconstructedPermuted* ...
            permutationMatrix.';
        reconstructionExact = reconstructionExact && ...
            isequal(reconstructed,factor.factorized_operator);
        retainedContextExact = retainedContextExact && ...
            isequal(factor.matrix,schurBlocks{k});
        available = available && ...
            factor.actual_factorized_operator_available_for_residual_audit;
        rawMismatchMaximum = max(rawMismatchMaximum, ...
            factor.raw_to_factorized_operator_relative);
    end
    refinement = recursive.daily_thomas(d).diagnostics. ...
        residual_refinement;
    rhs = [recursive.partition.day(d).r_v, ...
        recursive.partition.day(d).B];
    rawMetric = maximum_column_relative( ...
        rhs-recursive.partition.day(d).M* ...
        recursive.daily_thomas(d).stacked_solution,rhs);
    rawResidualRebuildExact = rawResidualRebuildExact && ...
        rawMetric==refinement.final_maximum_column_relative;
    reconstructionExact = reconstructionExact && ...
        refinement.residual_operator_exact_original && ...
        refinement.factor_context_unchanged;
    [values,count,availableValues] = collect_factorized_residuals( ...
        recursive.daily_thomas(d).diagnostics.multiplier_solve);
    factorizedSolveResiduals = [ ...
        factorizedSolveResiduals;values]; %#ok<AGROW>
    factorizedSolveAuditCount = factorizedSolveAuditCount+count;
    available = available && availableValues;
    [values,count,availableValues] = collect_factorized_residuals( ...
        recursive.daily_thomas(d).diagnostics.back_solve);
    factorizedSolveResiduals = [ ...
        factorizedSolveResiduals;values]; %#ok<AGROW>
    factorizedSolveAuditCount = factorizedSolveAuditCount+count;
    available = available && availableValues;
    [values,count,availableValues] = collect_factorized_residuals( ...
        refinement.correction_solve);
    factorizedSolveResiduals = [ ...
        factorizedSolveResiduals;values]; %#ok<AGROW>
    factorizedSolveAuditCount = factorizedSolveAuditCount+count;
    available = available && availableValues;
end
factor = recursive.core.factor;
factorCount = factorCount+1;
reconstructedPermuted = factor.L*factor.D*factor.L.';
permutationMatrix = sparse(factor.permutation, ...
    1:factor.dimension,1,factor.dimension,factor.dimension);
reconstructed = permutationMatrix*reconstructedPermuted* ...
    permutationMatrix.';
reconstructionExact = reconstructionExact && ...
    isequal(reconstructed,factor.factorized_operator) && ...
    isequal(recursive.core.matrix,factor.matrix) && ...
    recursive.core.diagnostics.residual_refinement. ...
        residual_operator_exact_original && ...
    recursive.core.diagnostics.residual_refinement. ...
        factor_context_unchanged;
retainedContextExact = retainedContextExact && ...
    isequal(recursive.core.matrix,factor.matrix);
available = available && ...
    factor.actual_factorized_operator_available_for_residual_audit;
rawMismatchMaximum = max(rawMismatchMaximum, ...
    factor.raw_to_factorized_operator_relative);
coreRawMetric = maximum_column_relative( ...
    recursive.core.rhs-recursive.core.matrix* ...
    recursive.core.solution,recursive.core.rhs);
rawResidualRebuildExact = rawResidualRebuildExact && ...
    coreRawMetric==recursive.core.diagnostics.residual_refinement. ...
        final_maximum_column_relative;
[values,count,availableValues] = collect_factorized_residuals( ...
    recursive.core.diagnostics.solve);
factorizedSolveResiduals = [ ...
    factorizedSolveResiduals;values];
factorizedSolveAuditCount = factorizedSolveAuditCount+count;
available = available && availableValues;
[values,count,availableValues] = collect_factorized_residuals( ...
    recursive.core.diagnostics.residual_refinement.correction_solve);
factorizedSolveResiduals = [ ...
    factorizedSolveResiduals;values];
factorizedSolveAuditCount = factorizedSolveAuditCount+count;
available = available && availableValues;
factorizedResidualsFinite = ~isempty(factorizedSolveResiduals) && ...
    all(isfinite(factorizedSolveResiduals));
if factorizedResidualsFinite
    maximumFactorizedSolveResidual = max(factorizedSolveResiduals);
else
    maximumFactorizedSolveResidual = Inf;
end
factorizedSolveSanityLimit = sqrt(eps);
audit = struct( ...
    "factor_count",factorCount, ...
    "actual_operator_reconstruction_exact",reconstructionExact, ...
    "actual_operator_available_for_residual_audit",available, ...
    "retained_factor_context_exact",retainedContextExact, ...
    "maximum_raw_to_factorized_operator_relative",rawMismatchMaximum, ...
    "raw_residual_operator_preserved",rawResidualRebuildExact, ...
    "factorized_solve_audit_count",factorizedSolveAuditCount, ...
    "maximum_factorized_operator_solve_relative_residual", ...
        maximumFactorizedSolveResidual, ...
    "factorized_operator_solve_sanity_limit", ...
        factorizedSolveSanityLimit, ...
    "factorized_operator_solve_residuals_finite", ...
        factorizedResidualsFinite, ...
    "automatic_symmetrization_used",false, ...
    "additional_factorization_count",0, ...
    "all_pass",factorCount==169 && reconstructionExact && ...
        available && retainedContextExact && rawResidualRebuildExact && ...
        factorizedResidualsFinite && ...
        maximumFactorizedSolveResidual<=factorizedSolveSanityLimit);
end

function [values,count,allAvailable] = collect_factorized_residuals(value)
values = zeros(0,1);
count = 0;
allAvailable = true;
if isempty(value)
    return
end
if iscell(value)
    for k = 1:numel(value)
        [childValues,childCount,childAvailable] = ...
            collect_factorized_residuals(value{k});
        values = [values;childValues]; %#ok<AGROW>
        count = count+childCount;
        allAvailable = allAvailable && childAvailable;
    end
    return
end
if ~isstruct(value)
    return
end
for itemIndex = 1:numel(value)
    item = value(itemIndex);
    if isfield(item,"factorized_operator_relative_residual")
        values = [values; ...
            item.factorized_operator_relative_residual]; %#ok<AGROW>
        count = count+1;
        allAvailable = allAvailable && ...
            isfield(item,"actual_factorized_operator_available") && ...
            item.actual_factorized_operator_available && ...
            isfield(item,"actual_factorized_operator_used_for_audit") && ...
            item.actual_factorized_operator_used_for_audit;
    end
    fields = string(fieldnames(item));
    for fieldIndex = 1:numel(fields)
        fieldName = fields(fieldIndex);
        if fieldName=="factorized_operator_relative_residual" || ...
                fieldName=="actual_factorized_operator_available" || ...
                fieldName=="actual_factorized_operator_used_for_audit"
            continue
        end
        child = item.(fieldName);
        if isstruct(child) || iscell(child)
            [childValues,childCount,childAvailable] = ...
                collect_factorized_residuals(child);
            values = [values;childValues]; %#ok<AGROW>
            count = count+childCount;
            allAvailable = allAvailable && childAvailable;
        end
    end
end
end

function value = maximum_column_relative(residual,rhs)
rhsNorm = full(sqrt(sum(abs(rhs).^2,1)));
residualNorm = full(sqrt(sum(abs(residual).^2,1)));
value = full(max(residualNorm./max(1,rhsNorm)));
end

function audit = audit_determinism(first,second)
directionExact = isequal(first.direction,second.direction);
refinementExact = isequaln(first.residual_refinement, ...
    second.residual_refinement);
responseExact = isequaln(first.daily_responses,second.daily_responses);
coreExact = isequaln(first.core.solution,second.core.solution);
audit = struct( ...
    "direction_exact",directionExact, ...
    "refinement_diagnostics_exact",refinementExact, ...
    "daily_responses_exact",responseExact, ...
    "core_solution_exact",coreExact, ...
    "all_pass",directionExact && refinementExact && ...
        responseExact && coreExact);
end

function result = failed_result(fixtureAudit,cause)
if isfield(fixtureAudit,"authority_failure") && ...
        fixtureAudit.authority_failure.all_pass
    preservedStatus = "FAIL_RETRYABLE";
else
    preservedStatus = "UNVERIFIED";
end
result = struct( ...
    "stage_id","stage_A4", ...
    "stage_status","READY", ...
    "milestone","A4-RNS-1", ...
    "milestone_status","FAIL_RETRYABLE", ...
    "fixture",fixtureAudit, ...
    "all_blocking_pass",false, ...
    "failure",struct( ...
        "present",true, ...
        "identifier",string(cause.identifier), ...
        "message",string(cause.message)), ...
    "d2a_original_status_preserved",preservedStatus, ...
    "stage_a4_pass_claimed",false, ...
    "execution",struct( ...
        "recursive_newton_direction_count",0, ...
        "state_update_count",0, ...
        "full_kkt_direction_solve_count",0, ...
        "complete_kkt_direction_fallback_used",false, ...
        "hundred_round_run_executed",false, ...
        "full_ipm_executed",false, ...
        "optimization_executed",false, ...
        "parallel_executed",false, ...
        "formal_a4_run_created",false, ...
        "d2a_rerun_executed",false, ...
        "stage_b_entered",false));
end

function require_file(pathValue)
assert(isfile(pathValue),"stageA4:rns1:FixtureFileMissing", ...
    "Required A4-RNS-1 fixture file is missing: %s",pathValue);
end
