function result = run_stage_a4_small_step_root_cause_audit( ...
        abResult,indexA,indexB,config,projectRoot)
%RUN_STAGE_A4_SMALL_STEP_ROOT_CAUSE_AUDIT Read-only A4-2D-1 audit.
%
% The caller supplies the already executed A4-2C A/B result.  This
% function only evaluates retained states, recursive directions, and
% sparse pre-update linearization snapshots.  It performs no Newton solve,
% state update, artifact write, or stage transition.

arguments
    abResult (1,1) struct
    indexA (1,1) struct
    indexB (1,1) struct
    config (1,1) struct
    projectRoot (1,1) string
end

validate_scope(abResult,indexA,indexB,config,projectRoot);
numericTolerance = 2048*eps;
directionTolerance = config.tolerances.direction_relative_2norm;
recursiveResidualTolerance = ...
    config.tolerances.recursive_full_kkt_relative_residual;
directResidualTolerance = config.tolerances.direct_maximum;
protectedBefore = capture_protected_objects(abResult);

fixtureAudit = audit_frozen_fixtures(abResult,projectRoot);
[candidateInventory,candidateSummary,candidateGroupSummary] = ...
    build_step_candidate_evidence(abResult,indexA,indexB,config, ...
        numericTolerance);
top20Candidates = candidateInventory(candidateInventory.rank<=20,:);

[dualDecomposition,qp5Metadata,dualDecompositionAudit] = ...
    build_initial_dual_decomposition(abResult,indexA,indexB, ...
        numericTolerance);
[directionClosure,qp5CausalChain] = build_direction_closure_evidence( ...
    abResult,indexA,indexB,config,numericTolerance);
[initialStateScales,initialGroupScales, ...
    initialResidualGroupScales,initialCentrality,scaleAudit] = ...
    build_initialization_and_scale_evidence(abResult,indexA,indexB);

protectedAfter = capture_protected_objects(abResult);
readOnlyAudit = compare_protected_objects(protectedBefore,protectedAfter);
directionAudit = audit_existing_direction_evidence(abResult, ...
    directionTolerance,recursiveResidualTolerance,directResidualTolerance);
rootCauseConclusion = build_root_cause_conclusion( ...
    dualDecomposition,qp5Metadata,qp5CausalChain, ...
    directionClosure,abResult);

checks = struct( ...
    "frozen_a4_2a_baseline_fixture_reproduced_field_by_field", ...
        fixtureAudit.passed, ...
    "all_step_candidates_reconstructed_and_traceable", ...
        all(candidateSummary.alpha_closure_scaled_error<= ...
            numericTolerance) && ...
        all(candidateSummary.limiter_traceable) && ...
        height(candidateSummary)==20 && ...
        candidate_group_evidence_closed(candidateSummary, ...
            candidateGroupSummary,numericTolerance), ...
    "initial_dual_residual_decomposition_closed", ...
        dualDecompositionAudit.passed, ...
    "all_four_direction_equations_closed", ...
        all(directionClosure.maximum_scaled_closure<=numericTolerance), ...
    "qp5_bound_causal_chain_closed", ...
        height(qp5CausalChain)==20 && ...
        all(qp5CausalChain.maximum_scaled_closure<=numericTolerance), ...
    "initialization_and_scale_coverage_complete",scaleAudit.passed, ...
    "audit_objects_and_fingerprints_unchanged",readOnlyAudit.passed, ...
    "existing_recursive_and_complete_kkt_audits_passed", ...
        directionAudit.passed, ...
    "single_factor_recommendation_only", ...
        rootCauseConclusion.next_single_factor_experiment== ...
            "dual_initialization");
checkValues = struct2cell(checks);
allPass = all(cellfun(@(value)isequal(value,true),checkValues));
if ~allPass
    names = string(fieldnames(checks));
    names = names(~cellfun(@(value)isequal(value,true),checkValues));
    error("stageA4:a42d1:AuditFailed", ...
        "A4-2D-1 checks failed: %s.",strjoin(names,", "));
end

result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-2D-1_small_step_root_cause_read_only_audit";
result.milestone_status = "PASS";
result.ab_result = abResult;
result.index_a = indexA;
result.index_b = indexB;
result.fixture_audit = fixtureAudit;
result.step_candidate_inventory = candidateInventory;
result.top20_step_candidates = top20Candidates;
result.step_candidate_summary = candidateSummary;
result.step_candidate_group_summary = candidateGroupSummary;
result.initial_dual_decomposition = dualDecomposition;
result.qp5_metadata = qp5Metadata;
result.dual_decomposition_audit = dualDecompositionAudit;
result.direction_equation_closure = directionClosure;
result.qp5_causal_chain = qp5CausalChain;
result.initial_state_scale_statistics = initialStateScales;
result.initial_user_group_scale_statistics = initialGroupScales;
result.initial_residual_group_scale_statistics = ...
    initialResidualGroupScales;
result.initial_centrality_statistics = initialCentrality;
result.scale_audit = scaleAudit;
result.read_only_audit = readOnlyAudit;
result.existing_direction_audit = directionAudit;
result.root_cause_conclusion = rootCauseConclusion;
result.checks = checks;
result.all_pass = allPass;
result.execution = struct( ...
    "baseline_chain_count",2, ...
    "baseline_iterations_per_chain",5, ...
    "baseline_newton_direction_count",10, ...
    "baseline_complete_kkt_audit_count",10, ...
    "baseline_state_update_count",10, ...
    "additional_audit_newton_direction_count",0, ...
    "additional_audit_complete_kkt_solve_count",0, ...
    "additional_audit_state_update_count",0, ...
    "formal_a4_run_created",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_step_rule_modified",false, ...
    "initialization_modified",false, ...
    "objective_or_model_scale_modified",false, ...
    "stage_b_entered",false);
end

function validate_scope(abResult,indexA,indexB,config,projectRoot)
assert(isfolder(projectRoot) && config.stage_id=="stage_A4" && ...
    config.status=="READY" && abResult.stage_id=="stage_A4" && ...
    abResult.stage_status=="READY" && abResult.all_pass, ...
    "stageA4:a42d1:Scope", ...
    "A4-2D-1 requires a passing A4-2C result under stage_A4 / READY.");
assert(abResult.execution.chain_count==2 && ...
    abResult.execution.iterations_per_chain==5 && ...
    abResult.execution.newton_direction_count==10 && ...
    abResult.execution.full_kkt_audit_count==10 && ...
    abResult.execution.state_update_count==10, ...
    "stageA4:a42d1:BaselineExecution", ...
    "The retained A4-2C baseline must contain both complete five-round chains.");
assert(abResult.chain_a.diagnostic_chain_id=="A4-2C-A" && ...
    abResult.chain_b.diagnostic_chain_id=="A4-2C-B" && ...
    abResult.chain_a.step_strategy=="independent" && ...
    abResult.chain_b.step_strategy=="common_min" && ...
    numel(abResult.chain_a.iterations)==5 && ...
    numel(abResult.chain_b.iterations)==5, ...
    "stageA4:a42d1:ChainIdentity", ...
    "A4-2D-1 must reuse the isolated A4-2C A and B chains.");
assert(indexA.scope.stage_id=="stage_A4" && ...
    indexB.scope.stage_id=="stage_A4", ...
    "stageA4:a42d1:IndexIdentity", ...
    "Both supplied canonical indices must identify stage_A4.");

chains = {abResult.chain_a,abResult.chain_b};
indices = {indexA,indexB};
requiredSnapshot = ["identity","H","A","G","objective_gradient", ...
    "r_dual","r_eq","r_ineq","r_comp","l","z","mu", ...
    "eq_offset","ineq_offset"];
for c = 1:2
    variables = indices{c}.variable_index;
    constraints = indices{c}.constraint_index;
    nPrimal = height(variables);
    nEquality = nnz(string(constraints.constraint_type)=="equality");
    nInequality = nnz(string(constraints.constraint_type)=="inequality");
    for k = 1:5
        item = chains{c}.iterations(k);
        assert(isfield(item,"root_cause_linearization_before") && ...
            isfield(item,"canonical_state_before") && ...
            isfield(item,"canonical_state_after") && ...
            isfield(item,"recursive_direction_components"), ...
            "stageA4:a42d1:RetainedEvidence", ...
            "Chain %d iteration %d lacks retained root-cause evidence.",c,k);
        snapshot = item.root_cause_linearization_before;
        for name = requiredSnapshot
            assert(isfield(snapshot,name), ...
                "stageA4:a42d1:SnapshotField", ...
                "Retained linearization field %s is missing.",name);
        end
        state = item.canonical_state_before;
        direction = item.recursive_direction_components;
        assert(snapshot.identity==item.linearization_identity_before && ...
            isequal(snapshot.l(:),state.l(:)) && ...
            isequal(snapshot.z(:),state.z(:)) && ...
            isequal(size(snapshot.A),[nEquality,nPrimal]) && ...
            isequal(size(snapshot.G),[nInequality,nPrimal]) && ...
            numel(snapshot.r_eq)==nEquality && ...
            numel(snapshot.r_dual)==nPrimal && ...
            numel(snapshot.r_ineq)==nInequality && ...
            numel(snapshot.r_comp)==nInequality && ...
            numel(direction.xi)==nPrimal && ...
            numel(direction.y)==nEquality && ...
            numel(direction.l)==nInequality && ...
            numel(direction.z)==nInequality && nnz(snapshot.H)==0, ...
            "stageA4:a42d1:SnapshotDimension", ...
            "Retained root-cause evidence has inconsistent dimensions.");
    end
end
end

function audit = audit_frozen_fixtures(abResult,projectRoot)
fixtureAPath = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_2A_five_round_baseline.csv");
assert(isfile(fixtureAPath), ...
    "stageA4:a42d1:FrozenFixtureMissing", ...
    "The frozen A4-2A baseline fixture is required.");

actualA = make_baseline_table(abResult.chain_a.iterations);
expectedA = readtable(fixtureAPath,'Delimiter',',', ...
    'ReadVariableNames',true,'TextType','string', ...
    'VariableNamingRule','preserve');
[passedA,detailsA] = fixture_matches(actualA,expectedA);
chainB = abResult.chain_b;
chainBInternalContract = chainB.all_pass && ...
    chainB.iteration_count==5 && chainB.step_strategy=="common_min" && ...
    all([chainB.iterations.all_pass]) && ...
    numel(unique(string( ...
        {chainB.iterations.direction_solve_invocation_id})))==5 && ...
    all([chainB.iterations.no_full_direction_fallback]);
audit = struct( ...
    "chain_a_fixture_path",string(fixtureAPath), ...
    "chain_a_fixture_sha256",string(compute_sha256_file(fixtureAPath)), ...
    "chain_a_field_count",width(expectedA), ...
    "chain_a_row_count",height(expectedA), ...
    "chain_a_details",detailsA, ...
    "chain_a_passed",passedA, ...
    "chain_b_internal_five_round_contract_passed", ...
        chainBInternalContract, ...
    "passed",passedA && chainBInternalContract);
end

function [passed,details] = fixture_matches(actual,expected)
expectedNames = string(expected.Properties.VariableNames).';
actualNames = string(actual.Properties.VariableNames).';
sameNames = isequal(actualNames,expectedNames);
sameHeight = height(actual)==height(expected);
fieldPassed = false(numel(expectedNames),1);
if sameNames && sameHeight
    for k = 1:numel(expectedNames)
        name = expectedNames(k);
        left = actual.(name);
        right = expected.(name);
        if isnumeric(left) && isnumeric(right)
            fieldPassed(k) = isequaln(double(left),double(right));
        else
            fieldPassed(k) = isequaln(string(left),string(right));
        end
    end
end
details = table(expectedNames,fieldPassed, ...
    'VariableNames',{'field_name','passed'});
passed = sameNames && sameHeight && all(fieldPassed);
end

function baseline = make_baseline_table(iterations)
n = numel(iterations);
iteration = reshape([iterations.iteration],[],1);
alphaPrimal = reshape([iterations.alpha_primal],[],1);
alphaDual = reshape([iterations.alpha_dual],[],1);
primalLimiter = strings(n,1);
dualLimiter = strings(n,1);
numericNames = ["equality_before","equality_after", ...
    "slack_equality_before","slack_equality_after","dual_before", ...
    "dual_after","complementarity_inf_before", ...
    "complementarity_inf_after","gap_before","gap_after", ...
    "minimum_l_after","minimum_z_after","direction_relative_error", ...
    "xi_relative_error","y_relative_error","l_relative_error", ...
    "z_relative_error","recursive_kkt_relative_residual", ...
    "full_kkt_relative_residual"];
values = zeros(n,numel(numericNames));
for k = 1:n
    item = iterations(k);
    primalLimiter(k) = item.primal_step.limiting_constraint_id;
    dualLimiter(k) = item.dual_step.limiting_constraint_id;
    before = item.residuals_before;
    after = item.residuals_after;
    values(k,:) = [before.equality_inf,after.equality_inf, ...
        before.slack_equality_inf,after.slack_equality_inf, ...
        before.dual_inf,after.dual_inf, ...
        before.complementarity_inf,after.complementarity_inf, ...
        before.complementarity_gap,after.complementarity_gap, ...
        after.minimum_l,after.minimum_z,item.direction_relative_error, ...
        item.component_relative_errors.xi, ...
        item.component_relative_errors.y, ...
        item.component_relative_errors.l, ...
        item.component_relative_errors.z, ...
        item.recursive_kkt_relative_residual, ...
        item.full_kkt_relative_residual];
end
baseline = table(iteration,alphaPrimal,alphaDual,primalLimiter, ...
    dualLimiter,values(:,1),values(:,2),values(:,3),values(:,4), ...
    values(:,5),values(:,6),values(:,7),values(:,8),values(:,9), ...
    values(:,10),values(:,11),values(:,12),values(:,13),values(:,14), ...
    values(:,15),values(:,16),values(:,17),values(:,18),values(:,19), ...
    'VariableNames',[{'iteration','alpha_primal','alpha_dual', ...
    'primal_limiter','dual_limiter'},cellstr(numericNames)]);
end

function [inventory,summary,groupSummary] = ...
        build_step_candidate_evidence(abResult,indexA,indexB,config,tolerance)
chains = {abResult.chain_a,abResult.chain_b};
indices = {indexA,indexB};
inventory = table();
summaryRecords = repmat(empty_candidate_summary(),20,1);
summaryPosition = 0;
for c = 1:2
    inequalities = inequalities_from_index(indices{c});
    for k = 1:5
        item = chains{c}.iterations(k);
        state = item.canonical_state_before;
        direction = item.recursive_direction_components;
        for stepKind = ["primal","dual"]
            if stepKind=="primal"
                values = state.l(:);
                delta = direction.l(:);
                officialStep = item.primal_step;
            else
                values = state.z(:);
                delta = direction.z(:);
                officialStep = item.dual_step;
            end
            [rows,record] = candidate_rows(chains{c},k,stepKind, ...
                values,delta,officialStep,inequalities, ...
                config.fraction_to_boundary,tolerance);
            inventory = append_table(inventory,rows);
            summaryPosition = summaryPosition+1;
            summaryRecords(summaryPosition) = record;
        end
    end
end
summary = struct2table(summaryRecords);
summary.chain_id = string(summary.chain_id);
summary.strategy = string(summary.strategy);
summary.step_kind = string(summary.step_kind);
summary.concentration_basis = string(summary.concentration_basis);
groupSummary = group_candidate_inventory(inventory);
end

function [rows,record] = candidate_rows(chain,iteration,stepKind, ...
        values,direction,officialStep,inequalities,tau,tolerance)
negative = find(direction<0);
rawRatio = -values(negative)./direction(negative);
candidateAlpha = min(ones(numel(negative),1),tau*rawRatio);
if isempty(negative)
    reconstructedAlpha = 1;
else
    [~,order] = sortrows([candidateAlpha,negative],[1,2]);
    negative = negative(order);
    rawRatio = rawRatio(order);
    candidateAlpha = candidateAlpha(order);
    reconstructedAlpha = min(candidateAlpha);
end
metadata = inequalities(negative,:);
n = numel(negative);
rank = (1:n).';
isLimiter = negative==officialStep.limiting_index;
rows = table( ...
    repmat(chain.diagnostic_chain_id,n,1), ...
    repmat(chain.step_strategy,n,1),repmat(iteration,n,1), ...
    repmat(stepKind,n,1),negative,metadata.global_row, ...
    string(metadata.constraint_id),string(metadata.constraint_name), ...
    metadata.day,metadata.hour,string(metadata.asset_type), ...
    metadata.asset_id,string(metadata.unit),values(negative), ...
    direction(negative),rawRatio,repmat(tau,n,1),candidateAlpha, ...
    rank,isLimiter, ...
    'VariableNames',{'chain_id','strategy','iteration','step_kind', ...
    'inequality_index','constraint_global_row','constraint_id', ...
    'constraint_name','day','hour','asset_type','asset_id','unit', ...
    'state_value','direction_value','raw_boundary_ratio','tau', ...
    'reconstructed_candidate_alpha','rank','is_global_limiter'});

if isempty(candidateAlpha)
    minimumValue = NaN; medianValue = NaN; p95Value = NaN;
    maximumValue = NaN; rawMinimum = NaN; rawMedian = NaN;
    rawP95 = NaN; rawMaximum = NaN;
    within2 = 0; within10 = 0; within100 = 0;
else
    minimumValue = min(candidateAlpha);
    medianValue = median(candidateAlpha);
    p95Value = percentile95(candidateAlpha);
    maximumValue = max(candidateAlpha);
    rawMinimum = min(rawRatio);
    rawMedian = median(rawRatio);
    rawP95 = percentile95(rawRatio);
    rawMaximum = max(rawRatio);
    within2 = nnz(rawRatio<=2*rawMinimum);
    within10 = nnz(rawRatio<=10*rawMinimum);
    within100 = nnz(rawRatio<=100*rawMinimum);
end
scale = max([1,abs(reconstructedAlpha),abs(officialStep.alpha)]);
record = empty_candidate_summary();
record.chain_id = char(chain.diagnostic_chain_id);
record.strategy = char(chain.step_strategy);
record.iteration = iteration;
record.step_kind = char(stepKind);
record.candidate_count = n;
record.minimum_candidate_alpha = minimumValue;
record.median_candidate_alpha = medianValue;
record.p95_candidate_alpha = p95Value;
record.maximum_candidate_alpha = maximumValue;
record.minimum_raw_boundary_ratio = rawMinimum;
record.median_raw_boundary_ratio = rawMedian;
record.p95_raw_boundary_ratio = rawP95;
record.maximum_raw_boundary_ratio = rawMaximum;
record.within_2x_minimum_count = within2;
record.within_10x_minimum_count = within10;
record.within_100x_minimum_count = within100;
record.concentration_basis = 'raw_boundary_ratio';
record.reconstructed_global_alpha = reconstructedAlpha;
record.official_candidate_alpha = officialStep.alpha;
record.alpha_closure_scaled_error = ...
    abs(reconstructedAlpha-officialStep.alpha)/scale;
record.negative_direction_count = nnz(direction<0);
record.global_limiter_count = nnz(isLimiter);
record.limiter_traceable = n>0 && nnz(isLimiter)==1 && ...
    record.alpha_closure_scaled_error<=tolerance;
end

function record = empty_candidate_summary()
record = struct("chain_id","","strategy","","iteration",0, ...
    "step_kind","","candidate_count",0, ...
    "minimum_candidate_alpha",NaN,"median_candidate_alpha",NaN, ...
    "p95_candidate_alpha",NaN,"maximum_candidate_alpha",NaN, ...
    "minimum_raw_boundary_ratio",NaN, ...
    "median_raw_boundary_ratio",NaN,"p95_raw_boundary_ratio",NaN, ...
    "maximum_raw_boundary_ratio",NaN, ...
    "within_2x_minimum_count",0,"within_10x_minimum_count",0, ...
    "within_100x_minimum_count",0, ...
    "concentration_basis","", ...
    "reconstructed_global_alpha",NaN, ...
    "official_candidate_alpha",NaN, ...
    "alpha_closure_scaled_error",NaN, ...
    "negative_direction_count",0,"global_limiter_count",0, ...
    "limiter_traceable",false);
end

function output = group_candidate_inventory(inventory)
records = repmat(empty_candidate_group_record(),0,1);
for groupKind = ["constraint_name","asset_type"]
    groupValues = string(inventory.(groupKind));
    keys = unique(inventory(:,{'chain_id','strategy','iteration', ...
        'step_kind'}),'rows','stable');
    for keyIndex = 1:height(keys)
        key = keys(keyIndex,:);
        keyMask = inventory.chain_id==key.chain_id & ...
            inventory.strategy==key.strategy & ...
            inventory.iteration==key.iteration & ...
            inventory.step_kind==key.step_kind;
        names = sort(unique(groupValues(keyMask)));
        for groupName = names.'
            mask = keyMask & groupValues==groupName;
            values = inventory.reconstructed_candidate_alpha(mask);
            raw = inventory.raw_boundary_ratio(mask);
            record = empty_candidate_group_record();
            record.chain_id = char(key.chain_id);
            record.strategy = char(key.strategy);
            record.iteration = key.iteration;
            record.step_kind = char(key.step_kind);
            record.group_kind = char(groupKind);
            record.group_name = char(groupName);
            record.candidate_count = nnz(mask);
            record.minimum_candidate_alpha = min(values);
            record.minimum_raw_boundary_ratio = min(raw);
            record.global_limiter_count = ...
                nnz(inventory.is_global_limiter(mask));
            records(end+1,1) = record; %#ok<AGROW>
        end
    end
end
output = struct2table(records);
for name = ["chain_id","strategy","step_kind","group_kind","group_name"]
    output.(name) = string(output.(name));
end
end

function record = empty_candidate_group_record()
record = struct("chain_id","","strategy","","iteration",0, ...
    "step_kind","","group_kind","","group_name","", ...
    "candidate_count",0,"minimum_candidate_alpha",NaN, ...
    "minimum_raw_boundary_ratio",NaN,"global_limiter_count",0);
end

function passed = candidate_group_evidence_closed(summary,grouped,tolerance)
passed = true;
for rowNumber = 1:height(summary)
    source = summary(rowNumber,:);
    for groupKind = ["constraint_name","asset_type"]
        mask = grouped.chain_id==source.chain_id & ...
            grouped.strategy==source.strategy & ...
            grouped.iteration==source.iteration & ...
            grouped.step_kind==source.step_kind & ...
            grouped.group_kind==groupKind;
        rows = grouped(mask,:);
        if isempty(rows)
            passed = false;
            return
        end
        rawMinimum = min(rows.minimum_raw_boundary_ratio);
        scale = max([1,abs(rawMinimum), ...
            abs(source.minimum_raw_boundary_ratio)]);
        passed = passed && ...
            sum(rows.candidate_count)==source.candidate_count && ...
            abs(rawMinimum-source.minimum_raw_boundary_ratio)/scale<= ...
                tolerance && ...
            sum(rows.global_limiter_count)==1;
        if ~passed
            return
        end
    end
end
end

function [decomposition,qp5Metadata,audit] = ...
        build_initial_dual_decomposition(abResult,indexA,indexB,tolerance)
itemA = abResult.chain_a.iterations(1);
itemB = abResult.chain_b.iterations(1);
snapshotA = itemA.root_cause_linearization_before;
snapshotB = itemB.root_cause_linearization_before;
stateA = itemA.canonical_state_before;
stateB = itemB.canonical_state_before;
assert(isequal(stateA.xi,stateB.xi) && isequal(stateA.y,stateB.y) && ...
    isequal(stateA.l,stateB.l) && isequal(stateA.z,stateB.z), ...
    "stageA4:a42d1:InitialChainState", ...
    "A4-2C chains must start from the same canonical state.");

variables = indexA.variable_index;
variables = sortrows(variables,"global_index_start");
objectiveGradient = snapshotA.objective_gradient(:);
aTransposeY = snapshotA.A.'*stateA.y;
gTransposeZ = snapshotA.G.'*stateA.z;
reconstructed = objectiveGradient+aTransposeY+gTransposeZ;
actual = snapshotA.r_dual(:);
closure = reconstructed-actual;
closureDenominator = max(ones(numel(closure),1), ...
    abs(objectiveGradient)+abs(snapshotA.A).'*abs(stateA.y)+ ...
    abs(snapshotA.G).'*abs(stateA.z)+abs(actual));
scaledClosure = abs(closure)./closureDenominator;
groups = primal_variable_groups(variables);
variableId = string(variables.block_id)+"|"+ ...
    string(variables.variable_name)+"|"+ ...
    string(variables.global_index_start);
decomposition = table(variables.global_index_start,variableId, ...
    string(variables.block_id),variables.day,variables.hour, ...
    string(variables.asset_type),variables.asset_id, ...
    string(variables.variable_name),string(variables.unit),groups, ...
    objectiveGradient,aTransposeY,gTransposeZ,reconstructed,actual, ...
    closure,scaledClosure, ...
    'VariableNames',{'variable_global_index','variable_id','block_id', ...
    'day','hour','asset_type','asset_id','variable_name','unit', ...
    'variable_group','objective_gradient','a_transpose_y', ...
    'g_transpose_z','reconstructed_r_dual','actual_r_dual', ...
    'closure_error','scaled_closure_error'});

qp5Mask = variables.day==0 & variables.hour==0 & ...
    string(variables.variable_name)=="QP5";
assert(nnz(qp5Mask)==1,"stageA4:a42d1:QP5Variable", ...
    "The global QP5 variable must occur exactly once.");
qIndex = variables.global_index_start(qp5Mask);
inequalitiesA = inequalities_from_index(indexA);
inequalitiesB = inequalities_from_index(indexB);
lowerA = find(string(inequalitiesA.constraint_id)=="INEQ-Q-LOWER-QP5");
upperA = find(string(inequalitiesA.constraint_id)=="INEQ-Q-UPPER-QP5");
lowerB = find(string(inequalitiesB.constraint_id)=="INEQ-Q-LOWER-QP5");
upperB = find(string(inequalitiesB.constraint_id)=="INEQ-Q-UPPER-QP5");
assert(all(cellfun(@isscalar,{lowerA,upperA,lowerB,upperB})), ...
    "stageA4:a42d1:QP5Bounds", ...
    "Each chain must expose exactly one QP5 lower and upper bound.");
qp5Row = decomposition(decomposition.variable_global_index==qIndex,:);
qp5Metadata = struct( ...
    "variable_global_index",qIndex, ...
    "variable_id",qp5Row.variable_id, ...
    "variable_name",qp5Row.variable_name, ...
    "unit",qp5Row.unit, ...
    "objective_gradient",qp5Row.objective_gradient, ...
    "a_transpose_y",qp5Row.a_transpose_y, ...
    "g_transpose_z",qp5Row.g_transpose_z, ...
    "r_dual",qp5Row.actual_r_dual, ...
    "scaled_dual_decomposition_closure", ...
        qp5Row.scaled_closure_error, ...
    "chain_a_lower_inequality_index",lowerA, ...
    "chain_a_upper_inequality_index",upperA, ...
    "chain_b_lower_inequality_index",lowerB, ...
    "chain_b_upper_inequality_index",upperB, ...
    "lower_constraint_id", ...
        string(inequalitiesA.constraint_id(lowerA)), ...
    "upper_constraint_id", ...
        string(inequalitiesA.constraint_id(upperA)), ...
    "lower_constraint_global_row",inequalitiesA.global_row(lowerA), ...
    "upper_constraint_global_row",inequalitiesA.global_row(upperA));

crossChainTermsExact = isequal(snapshotA.objective_gradient, ...
    snapshotB.objective_gradient) && isequal(snapshotA.A,snapshotB.A) && ...
    isequal(snapshotA.G,snapshotB.G) && ...
    isequal(snapshotA.r_dual,snapshotB.r_dual);
audit = struct( ...
    "maximum_scaled_closure_error",max(scaledClosure), ...
    "qp5_scaled_closure_error",qp5Row.scaled_closure_error, ...
    "chain_b_initial_terms_exactly_equal",crossChainTermsExact, ...
    "passed",max(scaledClosure)<=tolerance && ...
        qp5Row.scaled_closure_error<=tolerance && crossChainTermsExact);
end

function [closureTable,qp5Table] = build_direction_closure_evidence( ...
        abResult,indexA,indexB,config,tolerance)
chains = {abResult.chain_a,abResult.chain_b};
indices = {indexA,indexB};
closureRecords = repmat(empty_direction_closure_record(),10,1);
qp5Records = repmat(empty_qp5_causal_record(),20,1);
closurePosition = 0;
qp5Position = 0;
for c = 1:2
    variables = indices{c}.variable_index;
    qMask = variables.day==0 & variables.hour==0 & ...
        string(variables.variable_name)=="QP5";
    qIndex = variables.global_index_start(qMask);
    inequalities = inequalities_from_index(indices{c});
    lower = find(string(inequalities.constraint_id)=="INEQ-Q-LOWER-QP5");
    upper = find(string(inequalities.constraint_id)=="INEQ-Q-UPPER-QP5");
    for k = 1:5
        item = chains{c}.iterations(k);
        snapshot = item.root_cause_linearization_before;
        direction = item.recursive_direction_components;
        eqTerm = snapshot.A*direction.xi;
        eqClosure = eqTerm+snapshot.r_eq;
        ineqGTerm = snapshot.G*direction.xi;
        ineqClosure = ineqGTerm+direction.l+snapshot.r_ineq;
        compSlackTerm = snapshot.z.*direction.l;
        compMultiplierTerm = snapshot.l.*direction.z;
        compClosure = compSlackTerm+compMultiplierTerm+snapshot.r_comp;
        dualHTerm = snapshot.H*direction.xi;
        dualATerm = snapshot.A.'*direction.y;
        dualGTerm = snapshot.G.'*direction.z;
        dualClosure = dualHTerm+dualATerm+dualGTerm+snapshot.r_dual;
        eqDenominator = max(ones(numel(eqClosure),1), ...
            abs(snapshot.A)*abs(direction.xi)+abs(snapshot.r_eq));
        ineqDenominator = max(ones(numel(ineqClosure),1), ...
            abs(snapshot.G)*abs(direction.xi)+abs(direction.l)+ ...
            abs(snapshot.r_ineq));
        compDenominator = max(ones(numel(compClosure),1), ...
            abs(compSlackTerm)+abs(compMultiplierTerm)+ ...
            abs(snapshot.r_comp));
        dualDenominator = max(ones(numel(dualClosure),1), ...
            abs(snapshot.H)*abs(direction.xi)+ ...
            abs(snapshot.A).'*abs(direction.y)+ ...
            abs(snapshot.G).'*abs(direction.z)+abs(snapshot.r_dual));
        eqScaled = max(abs(eqClosure)./eqDenominator);
        ineqScaled = max(abs(ineqClosure)./ineqDenominator);
        compScaled = max(abs(compClosure)./compDenominator);
        dualScaled = max(abs(dualClosure)./dualDenominator);
        closurePosition = closurePosition+1;
        record = empty_direction_closure_record();
        record.chain_id = char(chains{c}.diagnostic_chain_id);
        record.strategy = char(chains{c}.step_strategy);
        record.iteration = k;
        record.linearization_identity = char(snapshot.identity);
        record.hessian_nnz = nnz(snapshot.H);
        record.equality_scaled_closure = eqScaled;
        record.inequality_scaled_closure = ineqScaled;
        record.complementarity_scaled_closure = compScaled;
        record.dual_scaled_closure = dualScaled;
        record.maximum_scaled_closure = max([eqScaled,ineqScaled, ...
            compScaled,dualScaled]);
        record.direction_relative_error = item.direction_relative_error;
        record.recursive_kkt_relative_residual = ...
            item.recursive_kkt_relative_residual;
        record.full_kkt_relative_residual = ...
            item.full_kkt_relative_residual;
        record.no_full_direction_fallback = ...
            item.no_full_direction_fallback;
        record.passed = record.hessian_nnz==0 && ...
            record.maximum_scaled_closure<=tolerance && ...
            item.direction_relative_error<= ...
                config.tolerances.direction_relative_2norm && ...
            item.recursive_kkt_relative_residual<= ...
                config.tolerances.recursive_full_kkt_relative_residual && ...
            item.full_kkt_relative_residual<= ...
                config.tolerances.direct_maximum && ...
            item.no_full_direction_fallback;
        closureRecords(closurePosition) = record;

        for row = [lower,upper]
            qp5Position = qp5Position+1;
            qp5Records(qp5Position) = qp5_causal_record( ...
                chains{c},item,snapshot,direction,inequalities,row, ...
                qIndex,config.fraction_to_boundary,tolerance);
        end
    end
end
closureTable = struct2table(closureRecords);
closureTable.chain_id = string(closureTable.chain_id);
closureTable.strategy = string(closureTable.strategy);
closureTable.linearization_identity = ...
    string(closureTable.linearization_identity);
qp5Table = struct2table(qp5Records);
for name = ["chain_id","strategy","bound_side","constraint_id"]
    qp5Table.(name) = string(qp5Table.(name));
end
end

function record = qp5_causal_record(chain,item,snapshot,direction, ...
        inequalities,row,qIndex,tau,tolerance)
constraintId = string(inequalities.constraint_id(row));
if contains(constraintId,"LOWER")
    side = "lower";
else
    side = "upper";
end
gDirection = snapshot.G(row,:)*direction.xi;
qContribution = snapshot.G(row,qIndex)*direction.xi(qIndex);
otherGContribution = gDirection-qContribution;
ineqClosure = gDirection+direction.l(row)+snapshot.r_ineq(row);
ineqScale = max(1,abs(snapshot.G(row,:))*abs(direction.xi)+ ...
    abs(direction.l(row))+abs(snapshot.r_ineq(row)));
slackCompTerm = snapshot.z(row)*direction.l(row);
multiplierCompTerm = snapshot.l(row)*direction.z(row);
compClosure = slackCompTerm+multiplierCompTerm+snapshot.r_comp(row);
compScale = max(1,abs(slackCompTerm)+abs(multiplierCompTerm)+ ...
    abs(snapshot.r_comp(row)));
dualATerm = snapshot.A(:,qIndex).'*direction.y;
dualGTerm = snapshot.G(:,qIndex).'*direction.z;
dualHTerm = snapshot.H(qIndex,:)*direction.xi;
dualClosure = dualHTerm+dualATerm+dualGTerm+snapshot.r_dual(qIndex);
dualScale = max(1,abs(snapshot.H(qIndex,:))*abs(direction.xi)+ ...
    abs(snapshot.A(:,qIndex)).'*abs(direction.y)+ ...
    abs(snapshot.G(:,qIndex)).'*abs(direction.z)+ ...
    abs(snapshot.r_dual(qIndex)));
slackRaw = boundary_ratio(snapshot.l(row),direction.l(row));
multiplierRaw = boundary_ratio(snapshot.z(row),direction.z(row));
slackCandidate = capped_candidate(slackRaw,tau);
multiplierCandidate = capped_candidate(multiplierRaw,tau);

record = empty_qp5_causal_record();
record.chain_id = char(chain.diagnostic_chain_id);
record.strategy = char(chain.step_strategy);
record.iteration = item.iteration;
record.bound_side = char(side);
record.inequality_index = row;
record.constraint_global_row = inequalities.global_row(row);
record.constraint_id = char(constraintId);
record.qp5_variable_global_index = qIndex;
record.qp5_value = item.canonical_state_before.xi(qIndex);
record.delta_qp5 = direction.xi(qIndex);
record.g_qp5_coefficient = snapshot.G(row,qIndex);
record.g_delta_xi = gDirection;
record.g_delta_qp5_contribution = qContribution;
record.g_other_variable_contribution = otherGContribution;
record.r_ineq = snapshot.r_ineq(row);
record.l = snapshot.l(row);
record.delta_l = direction.l(row);
record.inequality_direction_closure = ineqClosure;
record.inequality_direction_scaled_closure = abs(ineqClosure)/ineqScale;
record.z = snapshot.z(row);
record.delta_z = direction.z(row);
record.r_comp = snapshot.r_comp(row);
record.z_times_delta_l = slackCompTerm;
record.l_times_delta_z = multiplierCompTerm;
record.complementarity_direction_closure = compClosure;
record.complementarity_direction_scaled_closure = ...
    abs(compClosure)/compScale;
record.slack_raw_boundary_ratio = slackRaw;
record.multiplier_raw_boundary_ratio = multiplierRaw;
record.slack_candidate_alpha = slackCandidate;
record.multiplier_candidate_alpha = multiplierCandidate;
record.official_candidate_alpha_primal = item.candidate_alpha_primal;
record.official_candidate_alpha_dual = item.candidate_alpha_dual;
record.is_primal_limiter = item.primal_step.limiting_index==row;
record.is_dual_limiter = item.dual_step.limiting_index==row;
record.qp5_dual_h_delta_xi = dualHTerm;
record.qp5_dual_a_transpose_delta_y = dualATerm;
record.qp5_dual_g_transpose_delta_z = dualGTerm;
record.qp5_r_dual = snapshot.r_dual(qIndex);
record.qp5_dual_direction_closure = dualClosure;
record.qp5_dual_direction_scaled_closure = abs(dualClosure)/dualScale;
record.maximum_scaled_closure = max([ ...
    record.inequality_direction_scaled_closure, ...
    record.complementarity_direction_scaled_closure, ...
    record.qp5_dual_direction_scaled_closure]);
record.passed = record.maximum_scaled_closure<=tolerance;
end

function record = empty_direction_closure_record()
record = struct("chain_id","","strategy","","iteration",0, ...
    "linearization_identity","","hessian_nnz",0, ...
    "equality_scaled_closure",NaN, ...
    "inequality_scaled_closure",NaN, ...
    "complementarity_scaled_closure",NaN, ...
    "dual_scaled_closure",NaN,"maximum_scaled_closure",NaN, ...
    "direction_relative_error",NaN, ...
    "recursive_kkt_relative_residual",NaN, ...
    "full_kkt_relative_residual",NaN, ...
    "no_full_direction_fallback",false,"passed",false);
end

function record = empty_qp5_causal_record()
record = struct("chain_id","","strategy","","iteration",0, ...
    "bound_side","","inequality_index",0, ...
    "constraint_global_row",0,"constraint_id","", ...
    "qp5_variable_global_index",0,"qp5_value",NaN, ...
    "delta_qp5",NaN,"g_qp5_coefficient",NaN, ...
    "g_delta_xi",NaN,"g_delta_qp5_contribution",NaN, ...
    "g_other_variable_contribution",NaN,"r_ineq",NaN, ...
    "l",NaN,"delta_l",NaN,"inequality_direction_closure",NaN, ...
    "inequality_direction_scaled_closure",NaN,"z",NaN, ...
    "delta_z",NaN,"r_comp",NaN,"z_times_delta_l",NaN, ...
    "l_times_delta_z",NaN,"complementarity_direction_closure",NaN, ...
    "complementarity_direction_scaled_closure",NaN, ...
    "slack_raw_boundary_ratio",NaN, ...
    "multiplier_raw_boundary_ratio",NaN, ...
    "slack_candidate_alpha",NaN,"multiplier_candidate_alpha",NaN, ...
    "official_candidate_alpha_primal",NaN, ...
    "official_candidate_alpha_dual",NaN, ...
    "is_primal_limiter",false,"is_dual_limiter",false, ...
    "qp5_dual_h_delta_xi",NaN, ...
    "qp5_dual_a_transpose_delta_y",NaN, ...
    "qp5_dual_g_transpose_delta_z",NaN,"qp5_r_dual",NaN, ...
    "qp5_dual_direction_closure",NaN, ...
    "qp5_dual_direction_scaled_closure",NaN, ...
    "maximum_scaled_closure",NaN,"passed",false);
end

function [stateScales,userGroupScales,residualGroupScales, ...
        centrality,audit] = build_initialization_and_scale_evidence( ...
        abResult,indexA,indexB)
item = abResult.chain_a.iterations(1);
snapshot = item.root_cause_linearization_before;
state = item.canonical_state_before;
direction = item.recursive_direction_components;
product = state.l.*state.z;
normalizedProduct = product/snapshot.mu;
stateScales = [ ...
    scale_table_row("initial_state","y","equality_multiplier",state.y); ...
    scale_table_row("initial_state","z","inequality_multiplier",state.z); ...
    scale_table_row("initial_state","l","slack",state.l); ...
    scale_table_row("initial_direction","delta_l","slack",direction.l); ...
    scale_table_row("initial_direction","delta_z", ...
        "inequality_multiplier",direction.z); ...
    scale_table_row("initial_state","l_times_z","complementarity",product); ...
    scale_table_row("initial_state","l_times_z_over_mu", ...
        "centrality",normalizedProduct)];
centrality = [ ...
    distribution_table_row("l_times_z",product); ...
    distribution_table_row("l_times_z_over_mu",normalizedProduct)];

variables = sortrows(indexA.variable_index,"global_index_start");
groups = primal_variable_groups(variables);
variablesB = sortrows(indexB.variable_index,"global_index_start");
groupsB = primal_variable_groups(variablesB);
assert(isequal(groups,groupsB) && ...
    isequal(string(variables.variable_name), ...
        string(variablesB.variable_name)) && ...
    isequal(variables.global_index_start,variablesB.global_index_start), ...
    "stageA4:a42d1:InitialScaleIndex", ...
    "Both isolated chains must share the same canonical variable groups.");
aTransposeY = snapshot.A.'*state.y;
gTransposeZ = snapshot.G.'*state.z;
quantities = {snapshot.objective_gradient(:),aTransposeY,gTransposeZ, ...
    snapshot.r_dual(:)};
quantityNames = ["objective_gradient","a_transpose_y", ...
    "g_transpose_z","r_dual"];
userGroupScales = table();
for groupName = sort(unique(groups)).'
    mask = groups==groupName;
    for q = 1:numel(quantityNames)
        userGroupScales = append_table(userGroupScales, ...
            scale_table_row("primal_variable",quantityNames(q), ...
                groupName,quantities{q}(mask)));
    end
end
userGroupScales = append_table(userGroupScales, ...
    scale_table_row("dual_state","y","equality_multiplier",state.y));
userGroupScales = append_table(userGroupScales, ...
    scale_table_row("dual_state","z","inequality_multiplier",state.z));
userGroupScales = append_table(userGroupScales, ...
    scale_table_row("primal_slack","l","slack",state.l));
userGroupScales = append_table(userGroupScales, ...
    scale_table_row("direction","delta_l","slack",direction.l));
userGroupScales = append_table(userGroupScales, ...
    scale_table_row("direction","delta_z", ...
        "inequality_multiplier",direction.z));

equalities = indexA.constraint_index( ...
    string(indexA.constraint_index.constraint_type)=="equality",:);
inequalities = inequalities_from_index(indexA);
residualGroupScales = table();
for groupName = sort(unique(string(equalities.constraint_name))).'
    mask = string(equalities.constraint_name)==groupName;
    residualGroupScales = append_table(residualGroupScales, ...
        scale_table_row("equality_constraint","r_eq", ...
            groupName,snapshot.r_eq(mask)));
end
for quantity = ["r_ineq","r_comp","delta_l","delta_z"]
    if quantity=="delta_l"
        values = direction.l;
    elseif quantity=="delta_z"
        values = direction.z;
    else
        values = snapshot.(quantity);
    end
    for groupName = sort(unique(string(inequalities.constraint_name))).'
        mask = string(inequalities.constraint_name)==groupName;
        residualGroupScales = append_table(residualGroupScales, ...
            scale_table_row("inequality_constraint",quantity, ...
                groupName,values(mask)));
    end
end

expectedGroups = ["global_capacity","daily_capacity_copy","wind", ...
    "solar","hydro","thermal","pch","pdis","soc", ...
    "equality_multiplier","inequality_multiplier","slack"];
actualGroups = unique(userGroupScales.group_name);
chainInitialExact = initial_chain_state_exact( ...
    abResult.chain_a.initial_state,abResult.chain_b.initial_state);
chainInitialDirectionExact = isequaln( ...
    abResult.chain_a.iterations(1).recursive_direction_components, ...
    abResult.chain_b.iterations(1).recursive_direction_components);
audit = struct( ...
    "expected_user_groups",expectedGroups, ...
    "actual_user_groups",sort(actualGroups), ...
    "user_group_count",numel(actualGroups), ...
    "state_scale_row_count",height(stateScales), ...
    "initial_chains_exactly_equal",chainInitialExact, ...
    "initial_chain_directions_exactly_equal",chainInitialDirectionExact, ...
    "all_source_counts_closed", ...
        scale_source_counts_closed(userGroupScales,groups,state), ...
    "residual_and_direction_group_counts_closed", ...
        residual_group_counts_closed(residualGroupScales,equalities, ...
            inequalities,snapshot), ...
    "passed",isequal(sort(actualGroups),sort(expectedGroups(:))) && ...
        height(stateScales)==7 && chainInitialExact && ...
        chainInitialDirectionExact && ...
        scale_source_counts_closed(userGroupScales,groups,state) && ...
        residual_group_counts_closed(residualGroupScales,equalities, ...
            inequalities,snapshot));
end

function tableRow = scale_table_row(scope,quantity,groupName,values)
statistics = scale_statistics(values);
tableRow = struct2table(struct( ...
    "scope",char(scope),"quantity",char(quantity), ...
    "group_name",char(groupName), ...
    "count",statistics.count, ...
    "nonzero_count",statistics.nonzero_count, ...
    "negative_count",statistics.negative_count, ...
    "zero_count",statistics.zero_count, ...
    "positive_count",statistics.positive_count, ...
    "minimum_value",statistics.minimum_value, ...
    "maximum_value",statistics.maximum_value, ...
    "minimum_absolute_nonzero", ...
        statistics.minimum_absolute_nonzero, ...
    "median_absolute",statistics.median_absolute, ...
    "p95_absolute",statistics.p95_absolute, ...
    "maximum_absolute",statistics.maximum_absolute, ...
    "minimum_order_of_magnitude", ...
        statistics.minimum_order_of_magnitude, ...
    "maximum_order_of_magnitude", ...
        statistics.maximum_order_of_magnitude, ...
    "order_of_magnitude_span",statistics.order_of_magnitude_span));
tableRow.scope = string(tableRow.scope);
tableRow.quantity = string(tableRow.quantity);
tableRow.group_name = string(tableRow.group_name);
end

function row = distribution_table_row(metric,values)
values = values(:);
row = table(string(metric),numel(values),min(values),median(values), ...
    percentile95(values),max(values),mean(values),std(values,1), ...
    'VariableNames',{'metric','count','minimum','median','p95', ...
    'maximum','mean','standard_deviation'});
end

function passed = scale_source_counts_closed(rows,primalGroups,state)
passed = true;
for quantity = ["objective_gradient","a_transpose_y", ...
        "g_transpose_z","r_dual"]
    selected = rows(rows.scope=="primal_variable" & ...
        rows.quantity==quantity,:);
    passed = passed && sum(selected.count)==numel(primalGroups);
end
passed = passed && rows.count(rows.group_name=="equality_multiplier")== ...
    numel(state.y);
passed = passed && rows.count(rows.group_name=="inequality_multiplier" & ...
    rows.quantity=="z")==numel(state.z) && ...
    rows.count(rows.group_name=="inequality_multiplier" & ...
    rows.quantity=="delta_z")==numel(state.z) && ...
    rows.count(rows.group_name=="slack" & rows.quantity=="l")== ...
        numel(state.l) && ...
    rows.count(rows.group_name=="slack" & rows.quantity=="delta_l")== ...
        numel(state.l);
end

function passed = residual_group_counts_closed( ...
        rows,equalities,inequalities,snapshot)
equalityGroups = unique(string(equalities.constraint_name));
inequalityGroups = unique(string(inequalities.constraint_name));
equalityRows = rows(rows.scope=="equality_constraint" & ...
    rows.quantity=="r_eq",:);
passed = height(equalityRows)==numel(equalityGroups) && ...
    isequal(sort(equalityRows.group_name),sort(equalityGroups)) && ...
    sum(equalityRows.count)==numel(snapshot.r_eq);
if ~passed
    return
end
for quantity = ["r_ineq","r_comp","delta_l","delta_z"]
    selected = rows(rows.scope=="inequality_constraint" & ...
        rows.quantity==quantity,:);
    passed = passed && height(selected)==numel(inequalityGroups) && ...
        isequal(sort(selected.group_name),sort(inequalityGroups)) && ...
        sum(selected.count)==numel(snapshot.r_ineq);
    if ~passed
        return
    end
end
expectedHeight = numel(equalityGroups)+4*numel(inequalityGroups);
passed = passed && height(rows)==expectedHeight;
end

function exact = initial_chain_state_exact(left,right)
exact = isequal(left.xi,right.xi) && isequal(left.y,right.y) && ...
    isequal(left.l,right.l) && isequal(left.z,right.z);
end

function audit = audit_existing_direction_evidence(abResult, ...
        directionTolerance,recursiveTolerance,directTolerance)
items = [abResult.chain_a.iterations(:);abResult.chain_b.iterations(:)];
directionErrors = reshape([items.direction_relative_error],[],1);
recursiveResiduals = reshape( ...
    [items.recursive_kkt_relative_residual],[],1);
directResiduals = reshape([items.full_kkt_relative_residual],[],1);
noFallback = reshape([items.no_full_direction_fallback],[],1);
audit = struct( ...
    "maximum_direction_relative_error",max(directionErrors), ...
    "maximum_recursive_complete_kkt_relative_residual", ...
        max(recursiveResiduals), ...
    "maximum_direct_complete_kkt_relative_residual", ...
        max(directResiduals), ...
    "all_no_full_direction_fallback",all(noFallback), ...
    "passed",all(directionErrors<=directionTolerance) && ...
        all(recursiveResiduals<=recursiveTolerance) && ...
        all(directResiduals<=directTolerance) && all(noFallback));
end

function conclusion = build_root_cause_conclusion( ...
        decomposition,qp5Metadata,qp5CausalChain,directionClosure,abResult)
initialSnapshot = ...
    abResult.chain_a.iterations(1).root_cause_linearization_before;
initialState = abResult.chain_a.iterations(1).canonical_state_before;
initialDirection = ...
    abResult.chain_a.iterations(1).recursive_direction_components;
objectiveMaximum = max(abs(decomposition.objective_gradient));
dualMaximum = max(abs(decomposition.actual_r_dual));
initialMultiplierMaximum = max(abs(initialState.z));
initialEqualityMultiplierMaximum = max(abs(initialState.y));
qp5DirectionMagnitude = abs(initialDirection.xi( ...
    qp5Metadata.variable_global_index));
qp5Rows = qp5CausalChain(qp5CausalChain.iteration==1,:);
findingCategory = [ ...
    "excluded";"excluded";"excluded"; ...
    "evidence_supported";"evidence_supported"; ...
    "requires_single_factor_experiment"; ...
    "requires_single_factor_experiment"; ...
    "requires_single_factor_experiment"];
finding = [ ...
    "recursive_direction_error"; ...
    "complete_kkt_direction_fallback"; ...
    "already_near_optimal"; ...
    "large_initial_dual_infeasibility"; ...
    "capacity_direction_and_central_path_scale_mismatch"; ...
    "dual_initialization_causality"; ...
    "objective_unitization_or_algorithm_path_scaling_causality"; ...
    "centering_parameter_causality"];
evidence = [ ...
    "All ten recursive directions pass the retained complete-KKT audit."; ...
    "All ten retained directions state no complete-KKT fallback."; ...
    "Initial equality and dual residuals are materially nonzero."; ...
    "The initial dual residual contains the measured objective, A'*y, and G'*z terms."; ...
    "QP5 bound rows close the DeltaQ-to-Delta l-to-Delta z fraction-to-boundary chain."; ...
    "Not changed in A4-2D-1; requires a separate controlled experiment."; ...
    "Not changed in A4-2D-1; unlike pure preconditioning it changes the algorithm path."; ...
    "Not changed in A4-2D-1 and cannot be isolated from this audit alone."];
conclusionTable = table(findingCategory,finding,evidence, ...
    'VariableNames',{'category','finding','evidence'});
conclusion = struct( ...
    "classification",conclusionTable, ...
    "objective_gradient_maximum_absolute",objectiveMaximum, ...
    "initial_dual_residual_maximum_absolute",dualMaximum, ...
    "initial_equality_multiplier_maximum_absolute", ...
        initialEqualityMultiplierMaximum, ...
    "initial_inequality_multiplier_maximum_absolute", ...
        initialMultiplierMaximum, ...
    "initial_qp5_direction_absolute",qp5DirectionMagnitude, ...
    "initial_qp5_bound_row_count",height(qp5Rows), ...
    "maximum_direction_equation_scaled_closure", ...
        max(directionClosure.maximum_scaled_closure), ...
    "initial_equality_residual_inf",norm(initialSnapshot.r_eq,inf), ...
    "initial_dual_residual_inf",norm(initialSnapshot.r_dual,inf), ...
    "pure_equivalent_preconditioning_changes_exact_direction",false, ...
    "objective_unitization_changes_algorithm_path",true, ...
    "dual_initialization_changes_algorithm_path",true, ...
    "unique_root_cause_claimed",false, ...
    "next_single_factor_experiment","dual_initialization", ...
    "recommendation_rationale", ...
        "Test dual initialization alone before changing objective units, "+ ...
        "centering, or the formal step rule.");
end

function snapshot = capture_protected_objects(abResult)
chains = {abResult.chain_a,abResult.chain_b};
snapshot.states_before = cell(2,5);
snapshot.states_after = cell(2,5);
snapshot.directions = cell(2,5);
snapshot.linearizations = cell(2,5);
snapshot.state_fingerprints_before = strings(2,5);
snapshot.state_fingerprints_after = strings(2,5);
snapshot.direction_fingerprints = strings(2,5);
for c = 1:2
    for k = 1:5
        item = chains{c}.iterations(k);
        snapshot.states_before{c,k} = item.canonical_state_before;
        snapshot.states_after{c,k} = item.canonical_state_after;
        snapshot.directions{c,k} = item.recursive_direction_components;
        snapshot.linearizations{c,k} = ...
            item.root_cause_linearization_before;
        snapshot.state_fingerprints_before(c,k) = ...
            item.state_fingerprint_before;
        snapshot.state_fingerprints_after(c,k) = ...
            item.state_fingerprint_after;
        snapshot.direction_fingerprints(c,k) = ...
            item.direction_fingerprint;
    end
end
end

function audit = compare_protected_objects(before,after)
statesBeforeExact = isequaln(before.states_before,after.states_before);
statesAfterExact = isequaln(before.states_after,after.states_after);
directionsExact = isequaln(before.directions,after.directions);
linearizationsExact = isequaln(before.linearizations,after.linearizations);
stateFingerprintsExact = ...
    isequal(before.state_fingerprints_before, ...
        after.state_fingerprints_before) && ...
    isequal(before.state_fingerprints_after,after.state_fingerprints_after);
directionFingerprintsExact = isequal( ...
    before.direction_fingerprints,after.direction_fingerprints);
audit = struct( ...
    "canonical_states_before_exact",statesBeforeExact, ...
    "canonical_states_after_exact",statesAfterExact, ...
    "recursive_directions_exact",directionsExact, ...
    "linearization_snapshots_exact",linearizationsExact, ...
    "state_fingerprints_exact",stateFingerprintsExact, ...
    "direction_fingerprints_exact",directionFingerprintsExact, ...
    "additional_state_update_count",0, ...
    "additional_newton_direction_count",0, ...
    "passed",statesBeforeExact && statesAfterExact && ...
        directionsExact && linearizationsExact && ...
        stateFingerprintsExact && directionFingerprintsExact);
end

function inequalities = inequalities_from_index(index)
constraints = index.constraint_index;
inequalities = constraints( ...
    string(constraints.constraint_type)=="inequality",:);
end

function groups = primal_variable_groups(variables)
groups = strings(height(variables),1);
for k = 1:height(variables)
    assetType = string(variables.asset_type(k));
    variableName = string(variables.variable_name(k));
    if variables.day(k)==0 && variables.hour(k)==0
        groups(k) = "global_capacity";
    elseif variables.day(k)>0 && variables.hour(k)==0
        groups(k) = "daily_capacity_copy";
    elseif assetType=="wind"
        groups(k) = "wind";
    elseif assetType=="solar"
        groups(k) = "solar";
    elseif assetType=="hydro"
        groups(k) = "hydro";
    elseif assetType=="thermal"
        groups(k) = "thermal";
    elseif variableName=="Pch"
        groups(k) = "pch";
    elseif variableName=="Pdis"
        groups(k) = "pdis";
    elseif variableName=="SOC"
        groups(k) = "soc";
    else
        error("stageA4:a42d1:VariableGroup", ...
            "Canonical variable %d cannot be assigned to a user group.",k);
    end
end
end

function statistics = scale_statistics(values)
values = values(:);
absoluteValues = abs(values);
nonzeroValues = absoluteValues(absoluteValues>0);
if isempty(nonzeroValues)
    minimumAbsoluteNonzero = NaN;
    minimumOrder = NaN;
    maximumOrder = NaN;
    orderSpan = NaN;
else
    minimumAbsoluteNonzero = min(nonzeroValues);
    minimumOrder = floor(log10(minimumAbsoluteNonzero));
    maximumOrder = floor(log10(max(nonzeroValues)));
    orderSpan = maximumOrder-minimumOrder;
end
statistics = struct( ...
    "count",numel(values), ...
    "nonzero_count",numel(nonzeroValues), ...
    "negative_count",nnz(values<0), ...
    "zero_count",nnz(values==0), ...
    "positive_count",nnz(values>0), ...
    "minimum_value",min(values), ...
    "maximum_value",max(values), ...
    "minimum_absolute_nonzero",minimumAbsoluteNonzero, ...
    "median_absolute",median(absoluteValues), ...
    "p95_absolute",percentile95(absoluteValues), ...
    "maximum_absolute",max(absoluteValues), ...
    "minimum_order_of_magnitude",minimumOrder, ...
    "maximum_order_of_magnitude",maximumOrder, ...
    "order_of_magnitude_span",orderSpan);
end

function value = percentile95(values)
values = sort(values(:));
position = 1+0.95*(numel(values)-1);
lowerPosition = floor(position);
upperPosition = ceil(position);
if lowerPosition==upperPosition
    value = values(lowerPosition);
else
    weight = position-lowerPosition;
    value = (1-weight)*values(lowerPosition)+weight*values(upperPosition);
end
end

function ratio = boundary_ratio(value,direction)
if direction<0
    ratio = -value/direction;
else
    ratio = Inf;
end
end

function value = capped_candidate(rawRatio,tau)
if isinf(rawRatio)
    value = 1;
else
    value = min(1,tau*rawRatio);
end
end

function output = append_table(output,rows)
if isempty(output)
    output = rows;
else
    output = [output;rows];
end
end
