function result = run_stage_a4_five_iteration_diagnostic(data,index,config,options)
%RUN_STAGE_A4_FIVE_ITERATION_DIAGNOSTIC Run exactly five diagnostic updates.
%
% This is the A4-2A convergence diagnostic, not the complete A4 IPM.  Each
% round rebuilds a shared linearization from the current explicit state.l,
% computes the official recursive direction, audits it independently with
% the complete sparse KKT, and then updates the canonical state.  Only
% compact per-round diagnostics are retained; no run directory is created.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.ComplementarityAudit (1,1) logical = false
end

iterationCount = 5;
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY", ...
    "stageA4:fiveIteration:StageStatus", ...
    "A4-2A requires stage_A4 / READY.");
assert(config.fraction_to_boundary==0.9995 && ...
    config.initialization.centering_sigma==0.1, ...
    "stageA4:fiveIteration:FrozenStepParameters", ...
    "A4-2A requires sigma=0.1 and tau=0.9995 from solver.yaml.");
assert(isfield(config,"a4_2a_iteration_count") && ...
    config.a4_2a_iteration_count==iterationCount, ...
    "stageA4:fiveIteration:ConfiguredCount", ...
    "The A4-2A configured iteration count must exist and equal five.");

totalTimer = tic;
timer = tic;
state = initialize_stage_a4_state(data,index,config);
initializationSeconds = toc(timer);
assert(state.iteration_index==0 && state.state_revision==0, ...
    "stageA4:fiveIteration:InitialRevision", ...
    "A4-2A must start from deterministic revision zero.");

previousAfterIdentity = "";
previousStateAfter = struct();
beforeIdentities = strings(iterationCount,1);
afterIdentities = strings(iterationCount,1);
for iteration = 1:iterationCount
    assert(state.iteration_index==iteration-1 && ...
        state.state_revision==iteration-1, ...
        "stageA4:fiveIteration:RevisionSequence", ...
        "Round %d did not receive revision %d.",iteration,iteration-1);
    step = execute_stage_a4_iteration(state,data,index,config);
    inputStateExact = canonical_state_equal(step.state_before,state);
    if iteration==1
        previousStateChainExact = true;
    else
        previousStateChainExact = canonical_state_equal( ...
            step.state_before,previousStateAfter);
    end
    assert(inputStateExact && previousStateChainExact, ...
        "stageA4:fiveIteration:ExactStateChain", ...
        "Round %d did not consume the exact prior xi/y/l/z state.",iteration);
    assert(step.state_after.iteration_index==iteration && ...
        step.state_after.state_revision==iteration, ...
        "stageA4:fiveIteration:RevisionAdvance", ...
        "Round %d did not advance state revision exactly once.",iteration);
    beforeIdentities(iteration) = step.linearization_before.identity;
    afterIdentities(iteration) = step.linearization_after.identity;
    if iteration>1
        assert(beforeIdentities(iteration)==previousAfterIdentity, ...
            "stageA4:fiveIteration:IdentityChain", ...
            "Round %d did not rebuild the prior round's explicit state.", ...
            iteration);
    end
    summary = compact_iteration_summary(step,iteration, ...
        inputStateExact,previousStateChainExact);
    if options.ComplementarityAudit
        stateBeforeSnapshot = step.state_before;
        stateAfterSnapshot = step.state_after;
        complementarityAudit = ...
            audit_stage_a4_complementarity_change(iteration, ...
                step.linearization_before,step.linearization_after, ...
                step.recursive.components,step.primal_step.alpha, ...
                step.dual_step.alpha);
        complementarityAudit.official_state_unchanged = ...
            canonical_state_equal(step.state_before,stateBeforeSnapshot) && ...
            canonical_state_equal(step.state_after,stateAfterSnapshot);
        assert(complementarityAudit.all_pass && ...
            complementarityAudit.official_state_unchanged, ...
            "stageA4:fiveIteration:ComplementarityAudit", ...
            "Round %d complementarity audit failed or changed official state.", ...
            iteration);
        if iteration==1
            complementarityAudits = complementarityAudit;
        else
            complementarityAudits(iteration,1) = ...
                complementarityAudit; %#ok<AGROW>
        end
    end
    if iteration==1
        iterations = summary;
    else
        iterations(iteration,1) = summary;
    end
    previousAfterIdentity = afterIdentities(iteration);
    previousStateAfter = step.state_after;
    state = step.state_after;
    clear step
end

assert(numel(unique(beforeIdentities))==iterationCount && ...
    all(beforeIdentities~=afterIdentities), ...
    "stageA4:fiveIteration:IdentityRevisionEvidence", ...
    "The five explicit state revisions do not have distinct identities.");
allPassed = all([iterations.all_pass]);
if ~allPassed
    error("stageA4:fiveIteration:IterationFailed", ...
        "At least one of the five A4-2A diagnostic iterations failed.");
end

alphaPrimal = reshape([iterations.alpha_primal],[],1);
alphaDual = reshape([iterations.alpha_dual],[],1);
result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-2A_five_primal_dual_iteration_diagnostic";
result.milestone_status = "PASS";
result.config = config;
result.iteration_count = iterationCount;
result.iterations = iterations;
result.initial_state_revision = 0;
result.final_state = state;
result.final_state_revision = state.state_revision;
result.completed_newton_direction_count = ...
    state.completed_newton_direction_count;
result.linearization_before_identities = beforeIdentities;
result.linearization_after_identities = afterIdentities;
result.step_recovery = struct( ...
    "alpha_primal",alphaPrimal, ...
    "alpha_dual",alphaDual, ...
    "primal_later_maximum",max(alphaPrimal(2:end)), ...
    "dual_later_maximum",max(alphaDual(2:end)), ...
    "primal_later_to_first_ratio", ...
        max(alphaPrimal(2:end))/alphaPrimal(1), ...
    "dual_later_to_first_ratio",max(alphaDual(2:end))/alphaDual(1), ...
    "primal_recovered_after_first",max(alphaPrimal(2:end))>alphaPrimal(1), ...
    "dual_recovered_after_first",max(alphaDual(2:end))>alphaDual(1));
result.all_pass = allPassed;
result.timing = struct( ...
    "initialization_seconds",initializationSeconds, ...
    "iteration_seconds",reshape([iterations.timing_total_seconds],[],1), ...
    "total_seconds",toc(totalTimer));
result.execution = struct( ...
    "newton_direction_count",iterationCount, ...
    "state_update_count",iterationCount, ...
    "full_kkt_audit_count",iterationCount, ...
    "recursive_direction_is_official",true, ...
    "full_kkt_direction_consumed_by_recursive",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "stage_b_entered",false);
if options.ComplementarityAudit
    result.complementarity_audits = complementarityAudits;
end
end

function summary = compact_iteration_summary(step,iteration, ...
        inputStateExact,previousStateChainExact)
% Deliberately exclude full KKT matrices, partitions, and direction vectors.
summary = struct( ...
    "iteration",iteration, ...
    "state_revision_before",step.state_before.state_revision, ...
    "state_revision_after",step.state_after.state_revision, ...
    "linearization_identity_before",step.linearization_before.identity, ...
    "linearization_identity_after",step.linearization_after.identity, ...
    "explicit_slack_consumed_before", ...
        step.linearization_before.explicit_slack_consumed, ...
    "explicit_slack_consumed_after", ...
        step.linearization_after.explicit_slack_consumed, ...
    "input_state_exact",inputStateExact, ...
    "previous_state_chain_exact",previousStateChainExact, ...
    "alpha_primal",step.primal_step.alpha, ...
    "alpha_dual",step.dual_step.alpha, ...
    "primal_step",step.primal_step, ...
    "dual_step",step.dual_step, ...
    "residuals_before",step.residuals.before, ...
    "residuals_after",step.residuals.after, ...
    "closure",step.residuals.closure, ...
    "direction_relative_error",step.direction_audit.direction_relative_error, ...
    "component_relative_errors", ...
        step.direction_audit.component_relative_errors, ...
    "recursive_kkt_relative_residual", ...
        step.direction_audit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual", ...
        step.direction_audit.full_kkt_relative_residual, ...
    "maximum_direction_difference", ...
        step.direction_audit.maximum_direction_difference, ...
    "maximum_recursive_residual", ...
        step.direction_audit.maximum_recursive_residual, ...
    "maximum_full_residual",step.direction_audit.maximum_full_residual, ...
    "fixed_zero",step.fixed_zero, ...
    "soc",step.soc, ...
    "qp5",step.qp5, ...
    "permutation",step.permutation, ...
    "no_full_direction_fallback", ...
        step.recursive.no_full_direction_fallback && ...
        ~step.recursive.full_direction_consumed, ...
    "checks",step.checks, ...
    "all_pass",step.all_pass, ...
    "timing",step.timing, ...
    "timing_total_seconds",step.timing.total_seconds);
end

function exact = canonical_state_equal(left,right)
exact = isequal(left.xi,right.xi) && isequal(left.y,right.y) && ...
    isequal(left.l,right.l) && isequal(left.z,right.z) && ...
    left.iteration_index==right.iteration_index && ...
    left.state_revision==right.state_revision && ...
    left.newton_direction_number==right.newton_direction_number && ...
    left.completed_newton_direction_count== ...
        right.completed_newton_direction_count;
end
