function result = run_stage_a4_five_iteration_diagnostic(data,index,config,options)
%RUN_STAGE_A4_FIVE_ITERATION_DIAGNOSTIC Run exactly five diagnostic updates.
%
% This is the A4-2A convergence diagnostic, not the complete A4 IPM.  Each
% round rebuilds a shared linearization from the current explicit state.l,
% computes the official recursive direction, audits it independently with
% the complete sparse KKT, and then updates the canonical state.  Only
% compact per-round diagnostics are retained; no run directory is created.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.ComplementarityAudit (1,1) logical = false
    options.CompactComplementarityAudit (1,1) logical = false
    options.RetainCanonicalVectors (1,1) logical = false
    options.StepStrategy (1,1) string {mustBeMember( ...
        options.StepStrategy,["independent","common_min"])} = "independent"
    options.DiagnosticChainId (1,1) string = ""
    options.ComplementarityContributionAnalysis (1,1) logical = true
    options.RetainRootCauseEvidence (1,1) logical = false
    options.RecursiveRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
assert(options.RecursiveRefinementMaxPasses<=3, ...
    "stageA4:rns1:FiveIterationRefinementPassLimit", ...
    "Stage-A retained-factor refinement permits at most three passes.");

iterationCount = 5;
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY", ...
    "stageA4:fiveIteration:StageStatus", ...
    "A4-2A requires stage_A4 / READY.");
assert(config.fraction_to_boundary==0.9995 && ...
    config.initialization.centering_sigma==0.1, ...
    "stageA4:fiveIteration:FrozenStepParameters", ...
    "A4-2A requires sigma=0.1 and tau=0.9995 from solver.yaml.");
assert(isfield(config,"a4_2a_iteration_count") && ...
    config.a4_2a_iteration_count==iterationCount, ...
    "stageA4:fiveIteration:ConfiguredCount", ...
    "The A4-2A configured iteration count must exist and equal five.");
if strlength(options.DiagnosticChainId)>0
    assert(isfield(config,"a4_2c_iteration_count") && ...
        config.a4_2c_iteration_count==iterationCount && ...
        ismember(options.DiagnosticChainId,["A4-2C-A","A4-2C-B"]) && ...
        ((options.DiagnosticChainId=="A4-2C-A" && ...
        options.StepStrategy=="independent") || ...
        (options.DiagnosticChainId=="A4-2C-B" && ...
        options.StepStrategy=="common_min")), ...
        "stageA4:fiveIteration:A42CChainContract", ...
        "A4-2C requires isolated A/independent or B/common_min chains.");
else
    assert(options.StepStrategy=="independent", ...
        "stageA4:fiveIteration:DefaultStepStrategy", ...
        "The unnamespaced A4-1/A4-2A/A4-2B path must remain independent.");
end
assert(~options.CompactComplementarityAudit || ...
    options.ComplementarityAudit, ...
    "stageA4:fiveIteration:CompactAuditWithoutAudit", ...
    "A compact complementarity audit requires the audit to be enabled.");
assert(options.ComplementarityContributionAnalysis || ...
    (options.ComplementarityAudit && ...
    ismember(options.DiagnosticChainId,["A4-2C-A","A4-2C-B"])), ...
    "stageA4:fiveIteration:ComplementarityContributionScope", ...
    "Skipping the A4-2B-only contribution analysis is permitted only "+ ...
    "inside an isolated A4-2C comparison chain.");
assert(~options.RetainRootCauseEvidence || ...
    (options.RetainCanonicalVectors && ...
    ismember(options.DiagnosticChainId,["A4-2C-A","A4-2C-B"])), ...
    "stageA4:fiveIteration:RootCauseEvidenceScope", ...
    "Root-cause evidence may be retained only for an isolated A4-2C "+ ...
    "chain that also retains canonical vectors.");

totalTimer = tic;
timer = tic;
state = initialize_stage_a4_state(data,index,config);
initialCanonicalState = state;
if strlength(options.DiagnosticChainId)>0
    state.diagnostic_chain_id = options.DiagnosticChainId;
end
initializationSeconds = toc(timer);
assert(state.iteration_index==0 && state.state_revision==0, ...
    "stageA4:fiveIteration:InitialRevision", ...
    "A4-2A must start from deterministic revision zero.");

previousAfterIdentity = "";
previousStateAfter = struct();
beforeIdentities = strings(iterationCount,1);
afterIdentities = strings(iterationCount,1);
for iteration = 1:iterationCount
    assert(state.iteration_index==iteration-1 && ...
        state.state_revision==iteration-1, ...
        "stageA4:fiveIteration:RevisionSequence", ...
        "Round %d did not receive revision %d.",iteration,iteration-1);
    step = execute_stage_a4_iteration(state,data,index,config, ...
        "StepStrategy",options.StepStrategy, ...
        "RecursiveRefinementMaxPasses", ...
            options.RecursiveRefinementMaxPasses);
    rhsSourceDecomposition = struct();
    if options.RetainRootCauseEvidence && ...
            options.DiagnosticChainId=="A4-2C-A" && iteration==1
        rhsSourceDecomposition = ...
            solve_stage_a_multiday_diagnostic_rhs_responses( ...
            step.linearization_before,step.recursive);
        assert(rhsSourceDecomposition.audit.passed, ...
            "stageA4:fiveIteration:DiagnosticRhsResponse", ...
            "The retained first-round four-source RHS response failed.");
    end
    inputStateExact = canonical_state_equal(step.state_before,state);
    if iteration==1
        previousStateChainExact = true;
    else
        previousStateChainExact = canonical_state_equal( ...
            step.state_before,previousStateAfter);
    end
    chainIdentityExact = diagnostic_chain_equal( ...
        step.state_before,state,options.DiagnosticChainId);
    assert(inputStateExact && previousStateChainExact && ...
        chainIdentityExact, ...
        "stageA4:fiveIteration:ExactStateChain", ...
        "Round %d did not consume the exact prior xi/y/l/z state.",iteration);
    assert(step.state_after.iteration_index==iteration && ...
        step.state_after.state_revision==iteration, ...
        "stageA4:fiveIteration:RevisionAdvance", ...
        "Round %d did not advance state revision exactly once.",iteration);
    beforeIdentities(iteration) = step.linearization_before.identity;
    afterIdentities(iteration) = step.linearization_after.identity;
    if iteration>1
        assert(beforeIdentities(iteration)==previousAfterIdentity, ...
            "stageA4:fiveIteration:IdentityChain", ...
            "Round %d did not rebuild the prior round's explicit state.", ...
            iteration);
    end
    summary = compact_iteration_summary(step,iteration, ...
        inputStateExact,previousStateChainExact);
    if options.RetainCanonicalVectors
        summary.canonical_state_before = step.state_before;
        summary.canonical_state_after = step.state_after;
        summary.recursive_direction_components = step.recursive.components;
        summary.residual_vectors_before = struct( ...
            "r_ineq",step.linearization_before.r_ineq, ...
            "r_comp",step.linearization_before.r_comp);
        summary.residual_vectors_after = struct( ...
            "r_ineq",step.linearization_after.r_ineq, ...
            "r_comp",step.linearization_after.r_comp);
    end
    if options.RetainRootCauseEvidence
        summary.root_cause_linearization_before = ...
            make_root_cause_linearization_snapshot( ...
                step.linearization_before);
        summary.rhs_source_decomposition = rhsSourceDecomposition;
    end
    if options.ComplementarityAudit
        stateBeforeSnapshot = step.state_before;
        stateAfterSnapshot = step.state_after;
        complementarityAudit = ...
            audit_stage_a4_complementarity_change(iteration, ...
                step.linearization_before,step.linearization_after, ...
                step.recursive.components, ...
                step.applied_step.applied_alpha_primal, ...
                step.applied_step.applied_alpha_dual, ...
                "ContributionAnalysis", ...
                options.ComplementarityContributionAnalysis);
        complementarityAudit.official_state_unchanged = ...
            canonical_state_equal(step.state_before,stateBeforeSnapshot) && ...
            canonical_state_equal(step.state_after,stateAfterSnapshot);
        if ~complementarityAudit.official_state_unchanged
            error("stageA4:fiveIteration:ComplementarityAudit", ...
                "Round %d complementarity audit changed official state.", ...
                iteration);
        end
        if ~complementarityAudit.all_pass
            checkNames = string(fieldnames(complementarityAudit.checks));
            checkValues = struct2cell(complementarityAudit.checks);
            failedNames = checkNames(~cellfun( ...
                @(value)isequal(value,true),checkValues));
            error("stageA4:fiveIteration:ComplementarityAudit", ...
                "Round %d complementarity audit failed: %s.", ...
                iteration,strjoin(failedNames,", "));
        end
        if options.CompactComplementarityAudit
            complementarityAudit = rmfield( ...
                complementarityAudit,"delta_by_inequality");
        end
        if iteration==1
            complementarityAudits = complementarityAudit;
        else
            complementarityAudits(iteration,1) = ...
                complementarityAudit;
        end
    end
    if iteration==1
        iterations = summary;
    else
        iterations(iteration,1) = summary;
    end
    previousAfterIdentity = afterIdentities(iteration);
    previousStateAfter = step.state_after;
    state = step.state_after;
    clear step
end

assert(numel(unique(beforeIdentities))==iterationCount && ...
    all(beforeIdentities~=afterIdentities), ...
    "stageA4:fiveIteration:IdentityRevisionEvidence", ...
    "The five explicit state revisions do not have distinct identities.");
allPassed = all([iterations.all_pass]);
if ~allPassed
    error("stageA4:fiveIteration:IterationFailed", ...
        "At least one of the five A4-2A diagnostic iterations failed.");
end

alphaPrimal = reshape([iterations.alpha_primal],[],1);
alphaDual = reshape([iterations.alpha_dual],[],1);
result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
if strlength(options.DiagnosticChainId)==0
    result.milestone = "A4-2A_five_primal_dual_iteration_diagnostic";
else
    result.milestone = "A4-2C_isolated_five_iteration_chain";
end
result.milestone_status = "PASS";
result.config = config;
result.diagnostic_chain_id = options.DiagnosticChainId;
result.step_strategy = options.StepStrategy;
result.recursive_refinement_max_passes = ...
    options.RecursiveRefinementMaxPasses;
result.iteration_count = iterationCount;
result.iterations = iterations;
result.initial_state = state_with_chain_identity( ...
    initialCanonicalState,options.DiagnosticChainId);
result.initial_state_fingerprint = ...
    fingerprint_stage_a4_vectors(initialCanonicalState,true);
result.initial_state_revision = 0;
result.final_state = state;
result.final_state_fingerprint = ...
    fingerprint_stage_a4_vectors(state,true);
result.final_state_revision = state.state_revision;
result.completed_newton_direction_count = ...
    state.completed_newton_direction_count;
result.linearization_before_identities = beforeIdentities;
result.linearization_after_identities = afterIdentities;
result.step_recovery = struct( ...
    "alpha_primal",alphaPrimal, ...
    "alpha_dual",alphaDual, ...
    "primal_later_maximum",max(alphaPrimal(2:end)), ...
    "dual_later_maximum",max(alphaDual(2:end)), ...
    "primal_later_to_first_ratio", ...
        max(alphaPrimal(2:end))/alphaPrimal(1), ...
    "dual_later_to_first_ratio",max(alphaDual(2:end))/alphaDual(1), ...
    "primal_recovered_after_first",max(alphaPrimal(2:end))>alphaPrimal(1), ...
    "dual_recovered_after_first",max(alphaDual(2:end))>alphaDual(1));
result.all_pass = allPassed;
result.timing = struct( ...
    "initialization_seconds",initializationSeconds, ...
    "iteration_seconds",reshape([iterations.timing_total_seconds],[],1), ...
    "total_seconds",toc(totalTimer));
result.execution = struct( ...
    "newton_direction_count",iterationCount, ...
    "state_update_count",iterationCount, ...
    "full_kkt_audit_count",iterationCount, ...
    "recursive_direction_is_official",true, ...
    "full_kkt_direction_consumed_by_recursive",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "stage_b_entered",false, ...
    "step_strategy",options.StepStrategy, ...
    "diagnostic_chain_id",options.DiagnosticChainId, ...
    "experimental_common_step",options.StepStrategy=="common_min", ...
    "formal_independent_step_rule_modified",false, ...
    "root_cause_evidence_retained",options.RetainRootCauseEvidence, ...
    "diagnostic_rhs_source_count", ...
        4*double(options.RetainRootCauseEvidence && ...
        options.DiagnosticChainId=="A4-2C-A"), ...
    "diagnostic_rhs_additional_factorization_count",0, ...
    "diagnostic_rhs_additional_state_update_count",0, ...
    "diagnostic_rhs_additional_complete_kkt_solve_count",0, ...
    "recursive_refinement_max_passes", ...
        options.RecursiveRefinementMaxPasses, ...
    "stable_v2_recursive_route", ...
        options.RecursiveRefinementMaxPasses==3, ...
    "state_contains_mutable_handle",state_contains_handle(state));
if options.ComplementarityAudit
    result.complementarity_audits = complementarityAudits;
end
end

function summary = compact_iteration_summary(step,iteration, ...
        inputStateExact,previousStateChainExact)
% Deliberately exclude full KKT matrices and partitions. Canonical vectors
% and a compact sparse linearization snapshot are retained only when the
% caller explicitly requests the isolated diagnostic evidence.
stateBeforeFingerprint = fingerprint_stage_a4_vectors( ...
    step.state_before,true);
stateAfterFingerprint = fingerprint_stage_a4_vectors( ...
    step.state_after,true);
directionFingerprint = fingerprint_stage_a4_vectors( ...
    step.recursive.components,false);
if isfield(step.state_before,"diagnostic_chain_id")
    chainId = string(step.state_before.diagnostic_chain_id);
else
    chainId = "";
end
qIndices = step.linearization_before.maps.q_global;
capacityNames = step.linearization_before.capacity_parameters.names;
summary = struct( ...
    "iteration",iteration, ...
    "diagnostic_chain_id",chainId, ...
    "step_strategy",step.applied_step.strategy, ...
    "state_revision_before",step.state_before.state_revision, ...
    "state_revision_after",step.state_after.state_revision, ...
    "linearization_identity_before",step.linearization_before.identity, ...
    "linearization_identity_after",step.linearization_after.identity, ...
    "explicit_slack_consumed_before", ...
        step.linearization_before.explicit_slack_consumed, ...
    "explicit_slack_consumed_after", ...
        step.linearization_after.explicit_slack_consumed, ...
    "input_state_exact",inputStateExact, ...
    "previous_state_chain_exact",previousStateChainExact, ...
    "state_fingerprint_before",stateBeforeFingerprint, ...
    "state_fingerprint_after",stateAfterFingerprint, ...
    "execution_identity_before",step.linearization_before.identity+ ...
        "|state_sha256="+stateBeforeFingerprint, ...
    "execution_identity_after",step.linearization_after.identity+ ...
        "|state_sha256="+stateAfterFingerprint, ...
    "direction_solve_invocation_id",chainId+"|iteration="+ ...
        string(iteration)+"|state_sha256="+stateBeforeFingerprint, ...
    "direction_fingerprint",directionFingerprint, ...
    "recursive_direction_linearization_identity", ...
        step.recursive.linearization_identity, ...
    "full_kkt_direction_linearization_identity", ...
        step.direct_audit.linearization_identity, ...
    "direction_audit_linearization_identity", ...
        step.direction_audit.linearization_identity, ...
    "alpha_primal",step.primal_step.alpha, ...
    "alpha_dual",step.dual_step.alpha, ...
    "candidate_alpha_primal",step.primal_step.alpha, ...
    "candidate_alpha_dual",step.dual_step.alpha, ...
    "alpha_common",step.applied_step.alpha_common, ...
    "applied_alpha_primal", ...
        step.applied_step.applied_alpha_primal, ...
    "applied_alpha_dual",step.applied_step.applied_alpha_dual, ...
    "applied_step",step.applied_step, ...
    "primal_step",step.primal_step, ...
    "dual_step",step.dual_step, ...
    "residuals_before",step.residuals.before, ...
    "residuals_after",step.residuals.after, ...
    "objective_value_before",step.linearization_before.objective.value, ...
    "objective_value_after",step.linearization_after.objective.value, ...
    "global_capacity_names",capacityNames, ...
    "global_capacity_before", ...
        step.linearization_before.state.xi(qIndices), ...
    "global_capacity_after", ...
        step.linearization_after.state.xi(qIndices), ...
    "closure",step.residuals.closure, ...
    "direction_relative_error",step.direction_audit.direction_relative_error, ...
    "component_relative_errors", ...
        step.direction_audit.component_relative_errors, ...
    "recursive_kkt_relative_residual", ...
        step.direction_audit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual", ...
        step.direction_audit.full_kkt_relative_residual, ...
    "maximum_direction_difference", ...
        step.direction_audit.maximum_direction_difference, ...
    "maximum_recursive_residual", ...
        step.direction_audit.maximum_recursive_residual, ...
    "maximum_full_residual",step.direction_audit.maximum_full_residual, ...
    "fixed_zero",step.fixed_zero, ...
    "soc",step.soc, ...
    "qp5",step.qp5, ...
    "permutation",step.permutation, ...
    "no_full_direction_fallback", ...
        step.recursive.no_full_direction_fallback && ...
        ~step.recursive.full_direction_consumed, ...
    "recursive_refinement_max_passes", ...
        step.recursive_refinement_max_passes, ...
    "recursive_refinement", ...
        summarize_stage_a4_recursive_refinement(step.recursive), ...
    "checks",step.checks, ...
    "all_pass",step.all_pass, ...
    "timing",step.timing, ...
    "timing_total_seconds",step.timing.total_seconds);
end

function snapshot = make_root_cause_linearization_snapshot(linearization)
snapshot = struct( ...
    "identity",linearization.identity, ...
    "stage_id",linearization.stage_id, ...
    "H",linearization.H, ...
    "A",linearization.A, ...
    "G",linearization.G, ...
    "objective_gradient",linearization.objective.gradient, ...
    "r_dual",linearization.r_dual, ...
    "r_eq",linearization.r_eq, ...
    "r_ineq",linearization.r_ineq, ...
    "r_comp",linearization.r_comp, ...
    "l",linearization.l, ...
    "z",linearization.z, ...
    "mu",linearization.mu, ...
    "eq_offset",linearization.constraints.eq_offset, ...
    "ineq_offset",linearization.constraints.ineq_offset);
assert(issparse(snapshot.H) && issparse(snapshot.A) && ...
    issparse(snapshot.G) && nnz(snapshot.H)==0 && ...
    snapshot.identity==linearization.identity, ...
    "stageA4:fiveIteration:RootCauseEvidence", ...
    "The retained root-cause evidence must preserve the actual sparse "+ ...
    "linearization and exact-zero Stage-A Hessian.");
end

function exact = canonical_state_equal(left,right)
exact = isequal(left.xi,right.xi) && isequal(left.y,right.y) && ...
    isequal(left.l,right.l) && isequal(left.z,right.z) && ...
    left.iteration_index==right.iteration_index && ...
    left.state_revision==right.state_revision && ...
    left.newton_direction_number==right.newton_direction_number && ...
    left.completed_newton_direction_count== ...
        right.completed_newton_direction_count;
end

function exact = diagnostic_chain_equal(left,right,expectedChainId)
if strlength(expectedChainId)==0
    exact = ~isfield(left,"diagnostic_chain_id") && ...
        ~isfield(right,"diagnostic_chain_id");
else
    exact = isfield(left,"diagnostic_chain_id") && ...
        isfield(right,"diagnostic_chain_id") && ...
        string(left.diagnostic_chain_id)==expectedChainId && ...
        string(right.diagnostic_chain_id)==expectedChainId;
end
end

function state = state_with_chain_identity(state,chainId)
if strlength(chainId)>0
    state.diagnostic_chain_id = chainId;
end
end

function digest = fingerprint_stage_a4_vectors(value,includeMetadata)
fields = ["xi","y","l","z"];
payload = zeros(0,1);
lengths = zeros(numel(fields),1);
for k = 1:numel(fields)
    assert(isfield(value,fields(k)), ...
        "stageA4:fiveIteration:FingerprintField", ...
        "Fingerprint source is missing %s.",fields(k));
    vector = value.(fields(k));
    assert(isa(vector,"double") && isreal(vector) && ...
        size(vector,2)==1 && all(isfinite(vector)), ...
        "stageA4:fiveIteration:FingerprintVector", ...
        "Fingerprint source %s must be a finite real double column.", ...
        fields(k));
    lengths(k) = numel(vector);
    payload = [payload;vector]; %#ok<AGROW>
end
metadata = zeros(0,1);
if includeMetadata
    names = ["iteration_index","state_revision", ...
        "newton_direction_number","completed_newton_direction_count"];
    metadata = zeros(numel(names),1);
    for k = 1:numel(names)
        assert(isfield(value,names(k)) && ...
            isa(value.(names(k)),"double") && ...
            isscalar(value.(names(k))) && isfinite(value.(names(k))), ...
            "stageA4:fiveIteration:FingerprintMetadata", ...
            "Fingerprint metadata %s is invalid.",names(k));
        metadata(k) = value.(names(k));
    end
end
bytes = typecast([lengths;metadata;payload],"uint8");
messageDigest = java.security.MessageDigest.getInstance("SHA-256");
messageDigest.update(typecast(bytes,"int8"));
digestBytes = mod(double(messageDigest.digest()),256);
digest = lower(join(compose("%02x",digestBytes),""));
digest = reshape(digest,1,1);
assert(strlength(digest)==64, ...
    "stageA4:fiveIteration:FingerprintLength", ...
    "State/direction SHA256 fingerprint length is invalid.");
end

function present = state_contains_handle(state)
names = string(fieldnames(state));
present = false;
for name = names.'
    if isa(state.(name),"handle")
        present = true;
        return
    end
end
end
