function result = run_stage_a4_scaled_objective_chain( ...
        data,index,config,options)
%RUN_STAGE_A4_SCALED_OBJECTIVE_CHAIN Run an isolated 5- or 20-round chain.
%
% Each invocation starts from the frozen deterministic A4 initialization.
% The only intervention is c/f division by one positive scalar derived from
% the actual 14-capacity objective gradient.  The official state transition
% continues to consume only the recursive direction.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.IterationCount (1,1) double {mustBeMember( ...
        options.IterationCount,[5,20])}
end

iterationCount = options.IterationCount;
if iterationCount==5
    chainId = "A4-2D-2A-SCALED-5";
else
    chainId = "A4-2D-2A-SCALED-20";
end
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY" && ...
    config.fraction_to_boundary==0.9995 && ...
    config.initialization.centering_sigma==0.1, ...
    "stageA4:a42d2a:FrozenConfiguration", ...
    "The scaled-objective diagnostic requires frozen stage_A4 / READY, "+ ...
    "sigma=0.1, and tau=0.9995.");

totalTimer = tic;
state = initialize_stage_a4_state(data,index,config);
initialState = state;
baseInitial = build_stage_a4_linearization(state,data,index,config);
scaledInitial = build_stage_a4_scaled_objective_linearization( ...
    state,data,index,config,chainId);
scaleFactor = scaledInitial.objective_scale.factor;
structuralAudit = audit_initial_structure( ...
    baseInitial,scaledInitial,state,scaleFactor);
assert(structuralAudit.all_pass, ...
    "stageA4:a42d2a:InitialStructure", ...
    "The objective-unitized initial linearization changed frozen content.");

initialReq = scaledInitial.r_eq;
initialRdual = scaledInitial.r_dual;
equalityReferenceScale = max(1,norm(initialReq,inf));
dualReferenceScale = max(1,norm(initialRdual,inf));
cumulativePrimalBudget = 0;
cumulativeDualBudget = 0;
cumulativePrimalProduct = 1;
cumulativeDualProduct = 1;
previousState = state;
previousAfterIdentity = "";
iterations = struct([]);
failure = struct( ...
    "present",false, ...
    "attempted_iteration",0, ...
    "identifier","", ...
    "message","", ...
    "state_revision_before",0, ...
    "state_fingerprint_before","");

for iteration = 1:iterationCount
    assert(state.iteration_index==iteration-1 && ...
        state.state_revision==iteration-1 && ...
        canonical_state_equal(state,previousState), ...
        "stageA4:a42d2a:StateChain", ...
        "Scaled round %d did not receive its own exact prior state.", ...
        iteration);
    try
        step = execute_stage_a4_iteration(state,data,index,config, ...
            "StepStrategy","independent", ...
            "ObjectiveScaleMode","positive_scalar_unitization", ...
            "DiagnosticObjectiveChainId",chainId, ...
            "EqualityResidualReferenceScale",equalityReferenceScale, ...
            "DualResidualReferenceScale",dualReferenceScale);
    catch cause
        failure = struct( ...
            "present",true, ...
            "attempted_iteration",iteration, ...
            "identifier",string(cause.identifier), ...
            "message",string(cause.message), ...
            "state_revision_before",state.state_revision, ...
            "state_fingerprint_before", ...
                fingerprint_vectors(state,true));
        break
    end
    assert(step.linearization_before.objective_scale.factor== ...
        scaleFactor && step.linearization_after.objective_scale.factor== ...
        scaleFactor, ...
        "stageA4:a42d2a:ScaleDrift", ...
        "The objective scale changed within the isolated chain.");
    if iteration>1
        assert(step.linearization_before.identity==previousAfterIdentity, ...
            "stageA4:a42d2a:IdentityChain", ...
            "Scaled round %d did not rebuild the prior revision.",iteration);
    end

    alphaPrimal = step.applied_step.applied_alpha_primal;
    alphaDual = step.applied_step.applied_alpha_dual;
    cumulativePrimalBudget = cumulativePrimalBudget-log1p(-alphaPrimal);
    cumulativeDualBudget = cumulativeDualBudget-log1p(-alphaDual);
    cumulativePrimalProduct = cumulativePrimalProduct*(1-alphaPrimal);
    cumulativeDualProduct = cumulativeDualProduct*(1-alphaDual);
    record = make_iteration_record(step,iteration,scaleFactor, ...
        initialReq,initialRdual,cumulativePrimalBudget, ...
        cumulativeDualBudget,cumulativePrimalProduct, ...
        cumulativeDualProduct);
    assert(record.all_pass, ...
        "stageA4:a42d2a:RoundAudit", ...
        "Scaled-objective round %d failed a blocking diagnostic audit.", ...
        iteration);
    if iteration==1
        iterations = record;
    else
        iterations(iteration,1) = record;
    end
    previousAfterIdentity = step.linearization_after.identity;
    previousState = step.state_after;
    state = step.state_after;
    clear step
end

completedCount = numel(iterations);
allPassed = completedCount==iterationCount && ~failure.present && ...
    structuralAudit.all_pass && all([iterations.all_pass]) && ...
    all([iterations.no_full_direction_fallback]) && ...
    all([iterations.state_update_consumed_recursive_only]);

result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-2D-2A_positive_scalar_objective_unitization";
if allPassed
    result.milestone_status = "PASS";
else
    result.milestone_status = "FAIL_RETRYABLE";
end
result.chain_id = chainId;
result.requested_iteration_count = iterationCount;
result.iteration_count = completedCount;
result.step_strategy = "independent";
result.objective_scale_mode = "positive_scalar_unitization";
result.objective_scale = scaledInitial.objective_scale;
result.initial_state = initialState;
result.initial_state_fingerprint = fingerprint_vectors(initialState,true);
result.final_state = state;
result.final_state_fingerprint = fingerprint_vectors(state,true);
result.initial_unscaled_linearization = ...
    make_linearization_snapshot(baseInitial);
result.initial_scaled_linearization = ...
    make_linearization_snapshot(scaledInitial);
result.structural_audit = structuralAudit;
result.iterations = iterations;
if completedCount>0
    result.final_metrics = iterations(end).metrics_after;
else
    result.final_metrics = make_metrics(scaledInitial,scaleFactor);
end
result.failure = failure;
result.all_pass = allPassed;
result.timing_total_seconds = toc(totalTimer);
result.execution = struct( ...
    "requested_newton_direction_count",iterationCount, ...
    "newton_direction_count",completedCount, ...
    "state_update_count",completedCount, ...
    "full_kkt_audit_count",completedCount, ...
    "recursive_direction_is_official",true, ...
    "full_kkt_direction_consumed",false, ...
    "full_direction_fallback_used",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "stage_b_entered",false, ...
    "formal_step_rule_modified",false, ...
    "formal_objective_modified",false, ...
    "diagnostic_objective_unitization",true, ...
    "initialization_modified",false, ...
    "sigma_modified",false, ...
    "tau_modified",false, ...
    "constraint_or_variable_scaling_used",false, ...
    "common_step_used",false, ...
    "predictor_corrector_used",false, ...
    "line_search_used",false, ...
    "regularization_used",false, ...
    "additional_state_update_count",0);
end

function audit = audit_initial_structure(base,scaled,state,scaleFactor)
gradientExpected = base.objective.gradient/scaleFactor;
valueExpected = base.objective.value/scaleFactor;
rdualExpected = gradientExpected+base.A.'*state.y+base.G.'*state.z;
audit = struct( ...
    "H_exact",isequal(base.H,scaled.H), ...
    "A_exact",isequal(base.A,scaled.A), ...
    "G_exact",isequal(base.G,scaled.G), ...
    "eq_offset_exact",isequal(base.constraints.eq_offset, ...
        scaled.constraints.eq_offset), ...
    "ineq_offset_exact",isequal(base.constraints.ineq_offset, ...
        scaled.constraints.ineq_offset), ...
    "state_exact",isequal(base.state,scaled.state) && ...
        canonical_state_equal(base.state,state), ...
    "r_eq_exact",isequal(base.r_eq,scaled.r_eq), ...
    "r_ineq_exact",isequal(base.r_ineq,scaled.r_ineq), ...
    "r_comp_exact",isequal(base.r_comp,scaled.r_comp), ...
    "l_exact",isequal(base.l,scaled.l), ...
    "z_exact",isequal(base.z,scaled.z), ...
    "mu_exact",base.mu==scaled.mu, ...
    "maps_exact",isequal(base.maps,scaled.maps), ...
    "capacity_parameters_exact",isequal(base.capacity_parameters, ...
        scaled.capacity_parameters), ...
    "scale_finite_positive",isfinite(scaleFactor) && scaleFactor>0, ...
    "gradient_scaled_exact",isequal(scaled.objective.gradient, ...
        gradientExpected), ...
    "value_scaled_exact",scaled.objective.value==valueExpected, ...
    "r_dual_rebuild_scaled_error",relative_inf_error( ...
        scaled.r_dual,rdualExpected), ...
    "hessian_exact_zero",nnz(scaled.H)==0);
values = struct2cell(rmfield(audit,"r_dual_rebuild_scaled_error"));
audit.all_pass = all(cellfun(@(x)isequal(x,true),values)) && ...
    audit.r_dual_rebuild_scaled_error<=2048*eps;
end

function record = make_iteration_record(step,iteration,scaleFactor, ...
        initialReq,initialRdual,primalBudget,dualBudget, ...
        primalProduct,dualProduct)
before = make_metrics(step.linearization_before,scaleFactor);
after = make_metrics(step.linearization_after,scaleFactor);
predictedReq = initialReq*primalProduct;
predictedRdual = initialRdual*dualProduct;
reqProductAbsoluteError = norm( ...
    step.linearization_after.r_eq-predictedReq,inf);
rdualProductAbsoluteError = norm( ...
    step.linearization_after.r_dual-predictedRdual,inf);
reqProductScaledError = reqProductAbsoluteError/max(1,norm(initialReq,inf));
rdualProductScaledError = rdualProductAbsoluteError/ ...
    max(1,norm(initialRdual,inf));
primalProductFromBudget = exp(-primalBudget);
dualProductFromBudget = exp(-dualBudget);
budgetProductError = max(abs([ ...
    primalProduct-primalProductFromBudget, ...
    dualProduct-dualProductFromBudget]));

direction = step.recursive.components;
stateBefore = step.state_before;
stateAfter = step.state_after;
expectedXi = stateBefore.xi+ ...
    step.applied_step.applied_alpha_primal*direction.xi;
expectedL = stateBefore.l+ ...
    step.applied_step.applied_alpha_primal*direction.l;
expectedY = stateBefore.y+ ...
    step.applied_step.applied_alpha_dual*direction.y;
expectedZ = stateBefore.z+ ...
    step.applied_step.applied_alpha_dual*direction.z;
stateUpdateError = max([ ...
    relative_inf_error(stateAfter.xi,expectedXi), ...
    relative_inf_error(stateAfter.l,expectedL), ...
    relative_inf_error(stateAfter.y,expectedY), ...
    relative_inf_error(stateAfter.z,expectedZ)]);
identityExact = ...
    step.recursive.linearization_identity== ...
        step.linearization_before.identity && ...
    step.direct_audit.linearization_identity== ...
        step.linearization_before.identity && ...
    step.direction_audit.linearization_identity== ...
        step.linearization_before.identity;
physicalThreshold = 256*eps* ...
    step.residuals.after.physical_inequality_scale;
directionPassed = step.direction_audit.direction_relative_error<=1e-10 && ...
    step.direction_audit.recursive_kkt_relative_residual<=1e-10 && ...
    step.direction_audit.full_kkt_relative_residual<=1e-10;
productPassed = reqProductScaledError<=2048*eps && ...
    rdualProductScaledError<=2048*eps && budgetProductError<=2048*eps;
noFallback = step.recursive.no_full_direction_fallback && ...
    ~step.recursive.full_direction_consumed;
record = struct( ...
    "iteration",iteration, ...
    "chain_id",step.diagnostic_objective_chain_id, ...
    "state_revision_before",stateBefore.state_revision, ...
    "state_revision_after",stateAfter.state_revision, ...
    "linearization_identity_before", ...
        step.linearization_before.identity, ...
    "linearization_identity_after",step.linearization_after.identity, ...
    "recursive_linearization_identity", ...
        step.recursive.linearization_identity, ...
    "full_kkt_linearization_identity", ...
        step.direct_audit.linearization_identity, ...
    "direction_audit_linearization_identity", ...
        step.direction_audit.linearization_identity, ...
    "objective_scale_factor",scaleFactor, ...
    "objective_original_before",before.objective_original, ...
    "objective_scaled_before",before.objective_scaled, ...
    "objective_original_after",after.objective_original, ...
    "objective_scaled_after",after.objective_scaled, ...
    "metrics_before",before, ...
    "metrics_after",after, ...
    "candidate_alpha_primal",step.primal_step.alpha, ...
    "candidate_alpha_dual",step.dual_step.alpha, ...
    "applied_alpha_primal", ...
        step.applied_step.applied_alpha_primal, ...
    "applied_alpha_dual",step.applied_step.applied_alpha_dual, ...
    "primal_limiter",step.primal_step.limiting_constraint_id, ...
    "dual_limiter",step.dual_step.limiting_constraint_id, ...
    "minimum_l_after",after.minimum_l, ...
    "minimum_z_after",after.minimum_z, ...
    "delta_qp5",step.qp5.capacity_direction, ...
    "direction_relative_error", ...
        step.direction_audit.direction_relative_error, ...
    "component_relative_errors", ...
        step.direction_audit.component_relative_errors, ...
    "recursive_kkt_relative_residual", ...
        step.direction_audit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual", ...
        step.direction_audit.full_kkt_relative_residual, ...
    "no_full_direction_fallback",noFallback, ...
    "full_direction_consumed",step.recursive.full_direction_consumed, ...
    "state_update_consumed_recursive_only", ...
        stateUpdateError<=16*eps && noFallback, ...
    "state_update_scaled_error",stateUpdateError, ...
    "cumulative_primal_step_budget",primalBudget, ...
    "cumulative_dual_step_budget",dualBudget, ...
    "cumulative_primal_residual_product",primalProduct, ...
    "cumulative_dual_residual_product",dualProduct, ...
    "primal_product_from_budget",primalProductFromBudget, ...
    "dual_product_from_budget",dualProductFromBudget, ...
    "budget_product_absolute_error",budgetProductError, ...
    "r_eq_product_absolute_error",reqProductAbsoluteError, ...
    "r_eq_product_scaled_error",reqProductScaledError, ...
    "r_dual_product_absolute_error",rdualProductAbsoluteError, ...
    "r_dual_product_scaled_error",rdualProductScaledError, ...
    "global_capacity_names", ...
        step.linearization_before.capacity_parameters.names, ...
    "global_capacity_before",stateBefore.xi( ...
        step.linearization_before.maps.q_global), ...
    "global_capacity_after",stateAfter.xi( ...
        step.linearization_after.maps.q_global), ...
    "state_before",stateBefore, ...
    "state_after",stateAfter, ...
    "recursive_direction",direction, ...
    "state_fingerprint_before",fingerprint_vectors(stateBefore,true), ...
    "state_fingerprint_after",fingerprint_vectors(stateAfter,true), ...
    "direction_fingerprint",fingerprint_vectors(direction,false), ...
    "physical_violation_threshold",physicalThreshold, ...
    "same_scaled_linearization_identity",identityExact, ...
    "checks",step.checks, ...
    "all_pass",step.all_pass && directionPassed && productPassed && ...
        identityExact && noFallback && stateUpdateError<=16*eps && ...
        after.minimum_l>0 && after.minimum_z>0 && ...
        after.physical_inequality_violation<=physicalThreshold && ...
        before.mapping_r_dual_scaled_error<=2048*eps && ...
        after.mapping_r_dual_scaled_error<=2048*eps && ...
        before.mapping_r_comp_scaled_error<=2048*eps && ...
        after.mapping_r_comp_scaled_error<=2048*eps, ...
    "timing_total_seconds",step.timing.total_seconds);
end

function metrics = make_metrics(linearization,scaleFactor)
state = linearization.state;
originalGradient = linearization.objective.original_gradient;
scaledGradient = linearization.objective.gradient;
objectiveOriginalRebuilt = originalGradient.'*state.xi;
objectiveScaledRebuilt = scaledGradient.'*state.xi;
mappedY = scaleFactor*state.y;
mappedZ = scaleFactor*state.z;
rdualMapped = scaleFactor*linearization.r_dual;
rdualOriginalRebuilt = originalGradient+ ...
    linearization.A.'*mappedY+linearization.G.'*mappedZ;
mappedRcomp = scaleFactor*linearization.r_comp;
mappedMu = scaleFactor*linearization.mu;
rcompOriginalRebuilt = state.l.*mappedZ-mappedMu;
ineqFunction = linearization.G*state.xi+ ...
    linearization.constraints.ineq_offset;
rawGap = state.l.'*state.z;
meanGap = mean(state.l.*state.z);
mappedRawGap = scaleFactor*rawGap;
mappedMeanGap = scaleFactor*meanGap;
atyScaled = linearization.A.'*state.y;
gtzScaled = linearization.G.'*state.z;
atyMapped = linearization.A.'*mappedY;
gtzMapped = linearization.G.'*mappedZ;
metrics = struct( ...
    "objective_original",linearization.objective.original_value, ...
    "objective_scaled",linearization.objective.value, ...
    "objective_original_rebuilt",objectiveOriginalRebuilt, ...
    "objective_scaled_rebuilt",objectiveScaledRebuilt, ...
    "objective_scaling_relative_error",relative_scalar_error( ...
        linearization.objective.original_value, ...
        scaleFactor*linearization.objective.value), ...
    "equality_inf",norm(linearization.r_eq,inf), ...
    "slack_equality_inf",norm(linearization.r_ineq,inf), ...
    "physical_inequality_violation",max(max(ineqFunction,0)), ...
    "physical_inequality_scale",max(1,norm(ineqFunction,inf)), ...
    "dual_scaled_inf",norm(linearization.r_dual,inf), ...
    "complementarity_inf",norm(linearization.r_comp,inf), ...
    "mean_gap_scaled",meanGap, ...
    "raw_gap_scaled",rawGap, ...
    "mu_scaled",linearization.mu, ...
    "eta_dual_scaled",norm(linearization.r_dual,inf)/max(1, ...
        norm(scaledGradient,inf)+norm(atyScaled,inf)+ ...
        norm(gtzScaled,inf)), ...
    "eta_gap_scaled",rawGap/max(1, ...
        abs(linearization.objective.value)), ...
    "y_original_mapped",mappedY, ...
    "z_original_mapped",mappedZ, ...
    "mapped_y_inf",norm(mappedY,inf), ...
    "mapped_z_inf",norm(mappedZ,inf), ...
    "r_dual_original_mapped",rdualMapped, ...
    "mapped_r_dual_inf",norm(rdualMapped,inf), ...
    "mapped_r_dual_rebuilt_inf",norm(rdualOriginalRebuilt,inf), ...
    "mapping_r_dual_scaled_error",relative_inf_error( ...
        rdualMapped,rdualOriginalRebuilt), ...
    "mapped_mean_gap",mappedMeanGap, ...
    "mapped_raw_gap",mappedRawGap, ...
    "gap_original_mapped",mappedRawGap, ...
    "mapped_mu",mappedMu, ...
    "r_comp_original_mapped",mappedRcomp, ...
    "mapping_r_comp_scaled_error",relative_inf_error( ...
        mappedRcomp,rcompOriginalRebuilt), ...
    "eta_dual_mapped",norm(rdualOriginalRebuilt,inf)/max(1, ...
        norm(originalGradient,inf)+norm(atyMapped,inf)+ ...
        norm(gtzMapped,inf)), ...
    "eta_gap_mapped",mappedRawGap/max(1, ...
        abs(linearization.objective.original_value)), ...
    "minimum_l",min(state.l), ...
    "minimum_z",min(state.z), ...
    "all_finite",all(isfinite([state.xi;state.y;state.l;state.z; ...
        linearization.r_eq;linearization.r_ineq; ...
        linearization.r_dual;linearization.r_comp])));
end

function snapshot = make_linearization_snapshot(linearization)
snapshot = struct( ...
    "identity",linearization.identity, ...
    "H",linearization.H, ...
    "A",linearization.A, ...
    "G",linearization.G, ...
    "eq_offset",linearization.constraints.eq_offset, ...
    "ineq_offset",linearization.constraints.ineq_offset, ...
    "state",linearization.state, ...
    "objective",linearization.objective, ...
    "r_eq",linearization.r_eq, ...
    "r_ineq",linearization.r_ineq, ...
    "r_dual",linearization.r_dual, ...
    "r_comp",linearization.r_comp, ...
    "l",linearization.l, ...
    "z",linearization.z, ...
    "mu",linearization.mu, ...
    "maps",linearization.maps, ...
    "capacity_parameters",linearization.capacity_parameters, ...
    "constraints",linearization.constraints);
if isfield(linearization,"objective_scale")
    snapshot.objective_scale = linearization.objective_scale;
    snapshot.base_identity = linearization.base_identity;
end
end

function exact = canonical_state_equal(left,right)
names = ["xi","y","l","z","iteration_index","state_revision", ...
    "newton_direction_number","completed_newton_direction_count"];
exact = true;
for name = names
    exact = exact && isfield(left,name) && isfield(right,name) && ...
        isequal(left.(name),right.(name));
end
end

function errorValue = relative_inf_error(actual,expected)
errorValue = norm(actual-expected,inf)/ ...
    max([1,norm(actual,inf),norm(expected,inf)]);
end

function errorValue = relative_scalar_error(actual,expected)
errorValue = abs(actual-expected)/max([1,abs(actual),abs(expected)]);
end

function digest = fingerprint_vectors(value,includeMetadata)
fields = ["xi","y","l","z"];
payload = zeros(0,1);
lengths = zeros(numel(fields),1);
for k = 1:numel(fields)
    vector = value.(fields(k));
    lengths(k) = numel(vector);
    payload = [payload;vector]; %#ok<AGROW>
end
metadata = zeros(0,1);
if includeMetadata
    names = ["iteration_index","state_revision", ...
        "newton_direction_number","completed_newton_direction_count"];
    metadata = zeros(numel(names),1);
    for k = 1:numel(names)
        metadata(k) = value.(names(k));
    end
end
bytes = typecast([lengths;metadata;payload],"uint8");
messageDigest = java.security.MessageDigest.getInstance("SHA-256");
messageDigest.update(typecast(bytes,"int8"));
digestBytes = mod(double(messageDigest.digest()),256);
digest = lower(join(compose("%02x",digestBytes),""));
digest = reshape(digest,1,1);
end
