function result = run_stage_a4_objective_unitization_diagnostic( ...
        data,index,config,projectRoot)
%RUN_STAGE_A4_OBJECTIVE_UNITIZATION_DIAGNOSTIC Execute A4-2D-2A.
%
% Order is mandatory: frozen unscaled five-round reproduction, isolated
% scaled five-round gate, then a fresh scaled twenty-round chain.  This is
% a diagnostic experiment only and creates no formal run.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    projectRoot (1,1) string
end

sequence = strings(0,1);
totalTimer = tic;
baseline = run_stage_a4_five_iteration_diagnostic(data,index,config);
baselineTable = make_baseline_table(baseline.iterations);
fixturePath = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_2A_five_round_baseline.csv");
fixture = readtable(fixturePath,'Delimiter',',', ...
    'ReadVariableNames',true,'TextType','string', ...
    'VariableNamingRule','preserve');
baselineFixtureAudit = compare_baseline_fixture(baselineTable,fixture);
assert(baselineFixtureAudit.all_pass && baseline.all_pass, ...
    "stageA4:a42d2a:BaselineReproduction", ...
    "The unscaled five-round A4-2A baseline did not reproduce exactly.");
sequence(end+1,1) = "baseline5_completed";

scaledFive = run_stage_a4_scaled_objective_chain( ...
    data,index,config,"IterationCount",5);
sequence(end+1,1) = "scaled5_completed";
sequence(end+1,1) = "five_round_gate_evaluated";
fiveRoundGate = evaluate_stage_a4_scaled_five_round_gate(scaledFive);
assert(fiveRoundGate.passed && ...
    fiveRoundGate.permission_to_start_twenty_round_chain, ...
    "stageA4:a42d2a:FiveRoundGate", ...
    "The five-round scaled-objective gate failed; twenty rounds "+ ...
    "were not authorized.");
sequence(end+1,1) = "five_round_gate_passed";

sequence(end+1,1) = "scaled20_started";
scaledTwenty = run_stage_a4_scaled_objective_chain( ...
    data,index,config,"IterationCount",20);
if scaledTwenty.all_pass
    sequence(end+1,1) = "scaled20_completed";
else
    sequence(end+1,1) = "scaled20_failed";
end
firstFiveAudit = compare_scaled_first_five(scaledFive,scaledTwenty);
assert(firstFiveAudit.all_pass, ...
    "stageA4:a42d2a:FreshChainReproduction", ...
    "The fresh twenty-round chain did not reproduce the isolated five "+ ...
    "round trajectory exactly.");

initializationAudit = struct( ...
    "baseline_vs_scaled_five",canonical_state_equal( ...
        baseline.initial_state,scaledFive.initial_state), ...
    "baseline_vs_scaled_twenty",canonical_state_equal( ...
        baseline.initial_state,scaledTwenty.initial_state), ...
    "scaled_five_vs_twenty",canonical_state_equal( ...
        scaledFive.initial_state,scaledTwenty.initial_state));
initializationAudit.all_pass = ...
    initializationAudit.baseline_vs_scaled_five && ...
    initializationAudit.baseline_vs_scaled_twenty && ...
    initializationAudit.scaled_five_vs_twenty;
assert(initializationAudit.all_pass, ...
    "stageA4:a42d2a:FrozenInitialization", ...
    "The baseline and scaled chains did not start from the exact same "+ ...
    "frozen xi/y/l/z state.");

convergence = evaluate_convergence(scaledTwenty,config);
effect = compare_five_round_effect(baseline,scaledFive);
conclusion = make_conclusion(convergence,scaledTwenty,effect);
issue = struct( ...
    "issue_id","A4-2D-2-EVIDENCE-TAIL-001", ...
    "status","OPEN_NONBLOCKING", ...
    "classification","DEFERRED_EVIDENCE_CLOSEOUT", ...
    "description","A4-2D-1R fixture metadata names an exporter "+ ...
        "that is absent from the authority commit and current tree.", ...
    "impact","The frozen CSV remains usable for field-by-field "+ ...
        "regression, but its byte-level generation path is not "+ ...
        "self-contained.", ...
    "blocking_scope","Does not block A4-2D-2A numerical diagnosis; "+ ...
        "must close before formal A4 evidence finalization.", ...
    "resolved",false);

allPass = baselineFixtureAudit.all_pass && scaledFive.all_pass && ...
    fiveRoundGate.passed && scaledTwenty.all_pass && ...
    firstFiveAudit.all_pass && initializationAudit.all_pass;

result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-2D-2A_objective_positive_scalar_unitization";
if allPass
    result.milestone_status = "PASS";
    result.pass_semantics = ...
        "The positive-scalar objective-unitization experiment executed "+ ...
        "correctly and can diagnose scale effects on steps and residuals.";
else
    result.milestone_status = "FAIL_RETRYABLE";
    result.pass_semantics = ...
        "The scaled five-round gate passed, but the requested twenty-round "+ ...
        "recursive direction chain did not complete under frozen audits.";
end
result.baseline_five = baseline;
result.baseline_table = baselineTable;
result.baseline_fixture_audit = baselineFixtureAudit;
result.scaled_five = scaledFive;
result.five_round_gate = fiveRoundGate;
result.scaled_twenty = scaledTwenty;
result.first_five_reproduction_audit = firstFiveAudit;
result.initialization_audit = initializationAudit;
result.objective_scale = scaledFive.objective_scale;
result.five_round_effect = effect;
result.convergence_diagnostics = convergence;
result.conclusion = conclusion;
result.evidence_tail_issue = issue;
result.execution_sequence = sequence;
result.all_pass = allPass;
result.convergence_claimed = false;
result.stage_a4_pass_claimed = false;
result.formal_acceptance_metric_changed = false;
result.formal_algorithm_replaced = false;
result.execution = struct( ...
    "baseline_newton_direction_count",5, ...
    "scaled_five_newton_direction_count",5, ...
    "scaled_twenty_requested_newton_direction_count",20, ...
    "scaled_twenty_newton_direction_count", ...
        scaledTwenty.execution.newton_direction_count, ...
    "total_diagnostic_newton_direction_count", ...
        10+scaledTwenty.execution.newton_direction_count, ...
    "full_kkt_audit_count", ...
        10+scaledTwenty.execution.full_kkt_audit_count, ...
    "state_update_count", ...
        10+scaledTwenty.execution.state_update_count, ...
    "hundred_round_run_executed",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "stage_b_entered",false, ...
    "solver_yaml_modified",false, ...
    "formal_initialization_modified",false, ...
    "formal_objective_modified",false, ...
    "sigma_modified",false, ...
    "tau_modified",false, ...
    "formal_step_rule_modified",false, ...
    "common_step_used",false, ...
    "predictor_corrector_used",false, ...
    "line_search_used",false, ...
    "regularization_used",false, ...
    "complete_kkt_direction_fallback_used",false);
result.timing_total_seconds = toc(totalTimer);
end

function audit = compare_baseline_fixture(actual,expected)
sameNames = isequal(string(actual.Properties.VariableNames), ...
    string(expected.Properties.VariableNames));
sameHeight = height(actual)==5 && height(expected)==5;
stringNames = ["primal_limiter","dual_limiter"];
stringsExact = sameNames && all(arrayfun(@(name) ...
    isequal(string(actual.(name)),string(expected.(name))),stringNames));
numericNames = setdiff(string(actual.Properties.VariableNames), ...
    stringNames,'stable');
numericExact = sameNames && all(arrayfun(@(name) ...
    isequal(actual.(name),double(expected.(name))),numericNames));
audit = struct( ...
    "fixture_path_relative", ...
        "tests/fixtures/stage_A4_2A_five_round_baseline.csv", ...
    "row_count_exact",sameHeight, ...
    "column_names_and_order_exact",sameNames, ...
    "string_fields_exact",stringsExact, ...
    "numeric_fields_zero_tolerance_exact",numericExact, ...
    "all_pass",sameHeight && sameNames && stringsExact && numericExact);
end

function audit = compare_scaled_first_five(five,twenty)
assert(twenty.iteration_count>=5, ...
    "stageA4:a42d2a:InsufficientTwentyRoundPrefix", ...
    "The twenty-round attempt did not preserve a five-round prefix.");
flags = false(5,1);
for k = 1:5
    left = five.iterations(k);
    right = twenty.iterations(k);
    flags(k) = canonical_state_equal(left.state_before,right.state_before) && ...
        canonical_state_equal(left.state_after,right.state_after) && ...
        direction_equal(left.recursive_direction, ...
            right.recursive_direction) && ...
        left.candidate_alpha_primal==right.candidate_alpha_primal && ...
        left.candidate_alpha_dual==right.candidate_alpha_dual && ...
        left.applied_alpha_primal==right.applied_alpha_primal && ...
        left.applied_alpha_dual==right.applied_alpha_dual && ...
        left.primal_limiter==right.primal_limiter && ...
        left.dual_limiter==right.dual_limiter && ...
        metrics_equal(left.metrics_before,right.metrics_before) && ...
        metrics_equal(left.metrics_after,right.metrics_after) && ...
        left.delta_qp5==right.delta_qp5 && ...
        left.direction_relative_error==right.direction_relative_error && ...
        left.recursive_kkt_relative_residual== ...
            right.recursive_kkt_relative_residual && ...
        left.full_kkt_relative_residual== ...
            right.full_kkt_relative_residual && ...
        left.state_fingerprint_before==right.state_fingerprint_before && ...
        left.state_fingerprint_after==right.state_fingerprint_after && ...
        left.direction_fingerprint==right.direction_fingerprint;
end
audit = struct( ...
    "per_iteration_exact",flags, ...
    "fresh_initial_state_exact",canonical_state_equal( ...
        five.initial_state,twenty.initial_state), ...
    "five_round_chain_count",five.iteration_count, ...
    "twenty_round_completed_count",twenty.iteration_count, ...
    "twenty_round_requested_count",twenty.requested_iteration_count, ...
    "all_pass",all(flags) && ...
        canonical_state_equal(five.initial_state,twenty.initial_state));
end

function convergence = evaluate_convergence(chain,config)
final = chain.final_metrics;
thresholds = struct( ...
    "equality_inf",config.convergence.primal_equality_inf, ...
    "slack_equality_inf",config.convergence.primal_inequality_inf, ...
    "dual_scaled_inf",config.convergence.dual_inf, ...
    "mean_gap_scaled", ...
        config.convergence.normalized_complementarity_gap);
actual = struct( ...
    "equality_inf",final.equality_inf, ...
    "slack_equality_inf",final.slack_equality_inf, ...
    "dual_scaled_inf",final.dual_scaled_inf, ...
    "mean_gap_scaled",final.mean_gap_scaled);
names = string(fieldnames(thresholds));
ratios = zeros(numel(names),1);
passed = false(numel(names),1);
for k = 1:numel(names)
    ratios(k) = actual.(names(k))/thresholds.(names(k));
    passed(k) = ratios(k)<=1;
end
convergence = struct( ...
    "metric_names",names, ...
    "thresholds",thresholds, ...
    "actual",actual, ...
    "threshold_ratios",ratios, ...
    "metric_passed",passed, ...
    "twenty_round_chain_completed",chain.all_pass && ...
        chain.iteration_count==20, ...
    "completed_iteration_count",chain.iteration_count, ...
    "requested_iteration_count",chain.requested_iteration_count, ...
    "all_frozen_numeric_thresholds_met",all(passed) && ...
        chain.all_pass && chain.iteration_count==20, ...
    "eta_dual_scaled",final.eta_dual_scaled, ...
    "eta_gap_scaled",final.eta_gap_scaled, ...
    "eta_dual_mapped",final.eta_dual_mapped, ...
    "eta_gap_mapped",final.eta_gap_mapped, ...
    "formal_acceptance_interpretation_changed",false);
end

function effect = compare_five_round_effect(baseline,scaled)
baseLast = baseline.iterations(end);
scaledLast = scaled.iterations(end);
effect = struct( ...
    "baseline_initial_dual_inf", ...
        baseline.iterations(1).residuals_before.dual_inf, ...
    "scaled_initial_dual_inf", ...
        scaled.iterations(1).metrics_before.dual_scaled_inf, ...
    "baseline_first_alpha_primal", ...
        baseline.iterations(1).applied_alpha_primal, ...
    "scaled_first_alpha_primal", ...
        scaled.iterations(1).applied_alpha_primal, ...
    "baseline_first_alpha_dual", ...
        baseline.iterations(1).applied_alpha_dual, ...
    "scaled_first_alpha_dual", ...
        scaled.iterations(1).applied_alpha_dual, ...
    "baseline_first_delta_qp5",baseline.iterations(1).qp5.capacity_direction, ...
    "scaled_first_delta_qp5",scaled.iterations(1).delta_qp5, ...
    "baseline_fifth_equality_inf", ...
        baseLast.residuals_after.equality_inf, ...
    "scaled_fifth_equality_inf", ...
        scaledLast.metrics_after.equality_inf, ...
    "baseline_fifth_dual_inf",baseLast.residuals_after.dual_inf, ...
    "scaled_fifth_dual_inf",scaledLast.metrics_after.dual_scaled_inf, ...
    "baseline_fifth_mean_gap", ...
        baseLast.residuals_after.complementarity_gap, ...
    "scaled_fifth_mean_gap",scaledLast.metrics_after.mean_gap_scaled, ...
    "only_controlled_intervention", ...
        "objective_gradient_and_value_divided_by_derived_positive_scalar");
end

function conclusion = make_conclusion(convergence,chain,effect)
ratios = convergence.threshold_ratios;
names = convergence.metric_names;
if ~convergence.twenty_round_chain_completed
    nextFactor = "resolve_recursive_round_failure_before_next_factor";
    reason = "The twenty-round chain stopped before another legal state "+ ...
        "update because a frozen recursive-direction audit failed; no "+ ...
        "centering or step-policy experiment is authorized yet.";
elseif convergence.all_frozen_numeric_thresholds_met
    nextFactor = "none_required_by_twenty_round_diagnostic";
    reason = "All four frozen numerical thresholds were met in the "+ ...
        "diagnostic chain; this is not a formal A4 pass.";
else
    maximumRatio = max(ratios);
    dominant = find(ratios==maximumRatio);
    primalBudget = chain.iterations(end).cumulative_primal_step_budget;
    dualBudget = chain.iterations(end).cumulative_dual_step_budget;
    if isscalar(dominant) && names(dominant)=="mean_gap_scaled"
        nextFactor = "dynamic_centering_strategy";
        reason = "Complementarity is the unique largest frozen-threshold "+ ...
            "overrun, so the next isolated factor should address centering.";
    elseif isscalar(dominant) && ...
            ismember(names(dominant),["equality_inf","dual_scaled_inf"]) && ...
            primalBudget~=dualBudget && ...
            ((names(dominant)=="equality_inf" && ...
            primalBudget<dualBudget) || ...
            (names(dominant)=="dual_scaled_inf" && ...
            dualBudget<primalBudget))
        nextFactor = "step_globalization";
        reason = "The uniquely dominant equality/dual residual has the "+ ...
            "smaller corresponding cumulative step budget.";
    else
        nextFactor = "insufficient_evidence_for_unique_next_factor";
        reason = "Observed residual ratios and step budgets do not select "+ ...
            "one allowed next single factor without an arbitrary rule.";
    end
end
conclusion = struct( ...
    "experiment_correct",chain.all_pass && ...
        convergence.twenty_round_chain_completed, ...
    "objective_scale_effect_observed", ...
        effect.scaled_initial_dual_inf~=effect.baseline_initial_dual_inf || ...
        effect.scaled_first_alpha_primal~= ...
            effect.baseline_first_alpha_primal, ...
    "twenty_round_frozen_thresholds_met", ...
        convergence.all_frozen_numeric_thresholds_met, ...
    "next_single_factor",nextFactor, ...
    "reason",reason, ...
    "formal_ipm_convergence_claimed",false, ...
    "stage_a4_pass_claimed",false, ...
    "formal_objective_unitization_adopted",false, ...
    "formal_acceptance_metric_selected",false, ...
    "stage_b_entered",false);
end

function baseline = make_baseline_table(iterations)
count = numel(iterations);
iteration = reshape([iterations.iteration],[],1);
alphaPrimal = reshape([iterations.alpha_primal],[],1);
alphaDual = reshape([iterations.alpha_dual],[],1);
primalLimiter = strings(count,1); dualLimiter = strings(count,1);
equalityBefore = zeros(count,1); equalityAfter = zeros(count,1);
slackEqualityBefore = zeros(count,1); slackEqualityAfter = zeros(count,1);
dualBefore = zeros(count,1); dualAfter = zeros(count,1);
complementarityInfBefore = zeros(count,1);
complementarityInfAfter = zeros(count,1);
gapBefore = zeros(count,1); gapAfter = zeros(count,1);
minimumLAfter = zeros(count,1); minimumZAfter = zeros(count,1);
directionRelativeError = zeros(count,1);
xiRelativeError = zeros(count,1); yRelativeError = zeros(count,1);
lRelativeError = zeros(count,1); zRelativeError = zeros(count,1);
recursiveKktRelativeResidual = zeros(count,1);
fullKktRelativeResidual = zeros(count,1);
for k = 1:count
    item = iterations(k);
    primalLimiter(k) = item.primal_step.limiting_constraint_id;
    dualLimiter(k) = item.dual_step.limiting_constraint_id;
    equalityBefore(k) = item.residuals_before.equality_inf;
    equalityAfter(k) = item.residuals_after.equality_inf;
    slackEqualityBefore(k) = item.residuals_before.slack_equality_inf;
    slackEqualityAfter(k) = item.residuals_after.slack_equality_inf;
    dualBefore(k) = item.residuals_before.dual_inf;
    dualAfter(k) = item.residuals_after.dual_inf;
    complementarityInfBefore(k) = item.residuals_before.complementarity_inf;
    complementarityInfAfter(k) = item.residuals_after.complementarity_inf;
    gapBefore(k) = item.residuals_before.complementarity_gap;
    gapAfter(k) = item.residuals_after.complementarity_gap;
    minimumLAfter(k) = item.residuals_after.minimum_l;
    minimumZAfter(k) = item.residuals_after.minimum_z;
    directionRelativeError(k) = item.direction_relative_error;
    xiRelativeError(k) = item.component_relative_errors.xi;
    yRelativeError(k) = item.component_relative_errors.y;
    lRelativeError(k) = item.component_relative_errors.l;
    zRelativeError(k) = item.component_relative_errors.z;
    recursiveKktRelativeResidual(k) = item.recursive_kkt_relative_residual;
    fullKktRelativeResidual(k) = item.full_kkt_relative_residual;
end
baseline = table(iteration,alphaPrimal,alphaDual,primalLimiter, ...
    dualLimiter,equalityBefore,equalityAfter,slackEqualityBefore, ...
    slackEqualityAfter,dualBefore,dualAfter, ...
    complementarityInfBefore,complementarityInfAfter,gapBefore,gapAfter, ...
    minimumLAfter,minimumZAfter,directionRelativeError,xiRelativeError, ...
    yRelativeError,lRelativeError,zRelativeError, ...
    recursiveKktRelativeResidual,fullKktRelativeResidual, ...
    'VariableNames',{'iteration','alpha_primal','alpha_dual', ...
    'primal_limiter','dual_limiter','equality_before','equality_after', ...
    'slack_equality_before','slack_equality_after','dual_before', ...
    'dual_after','complementarity_inf_before', ...
    'complementarity_inf_after','gap_before','gap_after', ...
    'minimum_l_after','minimum_z_after','direction_relative_error', ...
    'xi_relative_error','y_relative_error','l_relative_error', ...
    'z_relative_error','recursive_kkt_relative_residual', ...
    'full_kkt_relative_residual'});
end

function exact = canonical_state_equal(left,right)
names = ["xi","y","l","z","iteration_index","state_revision", ...
    "newton_direction_number","completed_newton_direction_count"];
exact = true;
for name = names
    exact = exact && isfield(left,name) && isfield(right,name) && ...
        isequal(left.(name),right.(name));
end
end

function exact = direction_equal(left,right)
exact = isequal(left.xi,right.xi) && isequal(left.y,right.y) && ...
    isequal(left.l,right.l) && isequal(left.z,right.z);
end

function exact = metrics_equal(left,right)
names = string(fieldnames(left));
exact = isequal(names,string(fieldnames(right)));
for name = names.'
    exact = exact && isequal(left.(name),right.(name));
end
end
