function result = run_stage_a4_step_strategy_ab_diagnostic( ...
        data,indexA,indexB,config,options)
%RUN_STAGE_A4_STEP_STRATEGY_AB_DIAGNOSTIC Run isolated five-round A/B chains.
%
% Chain A preserves the frozen independent primal/dual step rule. Chain B
% is an experimental common-minimum-step chain. Each chain initializes and
% solves all five Newton directions inside its own function invocation.
% Neither chain can receive the other chain's state or direction.

arguments
    data (1,1) struct
    indexA (1,1) struct
    indexB (1,1) struct
    config (1,1) struct
    options.RetainRootCauseEvidence (1,1) logical = false
end

validate_scope(config,indexA,indexB);
totalTimer = tic;

chainA = run_stage_a4_five_iteration_diagnostic( ...
    data,indexA,config,"ComplementarityAudit",true, ...
    "CompactComplementarityAudit",true, ...
    "RetainCanonicalVectors",true, ...
    "StepStrategy","independent", ...
    "DiagnosticChainId","A4-2C-A", ...
    "ComplementarityContributionAnalysis",false, ...
    "RetainRootCauseEvidence",options.RetainRootCauseEvidence);
chainAFinalSnapshot = chainA.final_state;
chainAFingerprintSnapshot = chainA.final_state_fingerprint;
chainAIterationSnapshot = reshape( ...
    string({chainA.iterations.state_fingerprint_after}),[],1);

chainB = run_stage_a4_five_iteration_diagnostic( ...
    data,indexB,config,"ComplementarityAudit",true, ...
    "CompactComplementarityAudit",true, ...
    "RetainCanonicalVectors",true, ...
    "StepStrategy","common_min", ...
    "DiagnosticChainId","A4-2C-B", ...
    "ComplementarityContributionAnalysis",false, ...
    "RetainRootCauseEvidence",options.RetainRootCauseEvidence);

chainAUnchanged = canonical_state_equal( ...
    chainA.final_state,chainAFinalSnapshot) && ...
    chainA.final_state_fingerprint==chainAFingerprintSnapshot && ...
    isequal(reshape(string( ...
        {chainA.iterations.state_fingerprint_after}),[],1), ...
        chainAIterationSnapshot);

baselineTable = make_baseline_table(chainA.iterations);
chainSummary = make_chain_summary(chainA,chainB);
capacityHistory = make_capacity_history(chainA,chainB);
comparison = make_comparison_table(chainA,chainB);
centrality = combine_audit_table(chainA,chainB, ...
    "centrality_statistics");
residualScales = combine_audit_table(chainA,chainB, ...
    "residual_scale_statistics");
familyScales = combine_audit_table(chainA,chainB, ...
    "inequality_family_scale_statistics");

isolation = audit_isolation(chainA,chainB,indexA,indexB, ...
    chainAUnchanged);
commonStep = audit_common_step_chain(chainB);
directionProvenance = audit_direction_provenance(chainA,chainB);
numeric = audit_numeric_chain(chainA,chainB,config);
scaleCoverage = audit_scale_coverage(chainA,chainB,centrality, ...
    residualScales,familyScales);

checks = struct( ...
    "both_chains_passed",chainA.all_pass && chainB.all_pass, ...
    "separate_deterministic_initializations",isolation.passed, ...
    "common_step_applied_to_all_state_groups",commonStep.passed, ...
    "directions_recomputed_from_each_chain_state", ...
        directionProvenance.passed, ...
    "finite_positive_and_physically_feasible",numeric.passed, ...
    "residual_and_centrality_scales_complete",scaleCoverage.passed, ...
    "a4_2c_comparison_complementarity_checks_passed", ...
        all([chainA.complementarity_audits.all_pass]) && ...
        all([chainB.complementarity_audits.all_pass]), ...
    "comparison_tables_complete",height(chainSummary)==10 && ...
        height(capacityHistory)==20 && height(comparison)==55 && ...
        height(centrality)==40 && height(residualScales)==40 && ...
        height(familyScales)==640, ...
    "formal_step_rule_not_replaced", ...
        chainA.step_strategy=="independent" && ...
        chainB.step_strategy=="common_min" && ...
        ~chainA.execution.formal_independent_step_rule_modified && ...
        ~chainB.execution.formal_independent_step_rule_modified);
checkValues = struct2cell(checks);
allPass = all(cellfun(@(value)isequal(value,true),checkValues));
if ~allPass
    failed = string(fieldnames(checks));
    failed = failed(~cellfun(@(value)isequal(value,true),checkValues));
    error("stageA4:a42c:ComparisonFailed", ...
        "A4-2C checks failed: %s.",strjoin(failed,", "));
end

result = struct();
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-2C_independent_vs_common_step_five_round_ab";
result.milestone_status = "PASS";
result.run_purpose = config.a4_2c_run_purpose;
result.config = config;
result.chain_a = chainA;
result.chain_b = chainB;
result.baseline_table = baselineTable;
result.chain_summary = chainSummary;
result.capacity_history = capacityHistory;
result.residual_gap_comparison = comparison;
result.centrality_statistics = centrality;
result.residual_scale_statistics = residualScales;
result.inequality_family_scale_statistics = familyScales;
result.inequality_inventory = make_inequality_inventory(indexA);
result.isolation = isolation;
result.common_step_audit = commonStep;
result.direction_provenance = directionProvenance;
result.numeric_audit = numeric;
result.scale_coverage = scaleCoverage;
result.checks = checks;
result.all_pass = allPass;
result.convergence_claimed = false;
result.formal_step_rule_replaced = false;
result.execution = struct( ...
    "chain_count",2, ...
    "iterations_per_chain",5, ...
    "newton_direction_count",10, ...
    "full_kkt_audit_count",10, ...
    "state_update_count",10, ...
    "independent_chain_update_count",5, ...
    "experimental_common_step_update_count",5, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "formal_a4_run_created",false, ...
    "stage_b_entered",false, ...
    "solver_parameter_change_count",0, ...
    "formal_step_rule_change_count",0, ...
    "root_cause_evidence_retained",options.RetainRootCauseEvidence);
result.timing = struct("total_seconds",toc(totalTimer));
end

function validate_scope(config,indexA,indexB)
assert(config.stage_id=="stage_A4" && config.status=="READY" && ...
    config.a4_2c_iteration_count==5 && ...
    config.a4_2c_run_purpose== ...
        "five_iteration_independent_vs_common_step_controlled_ab_comparison" && ...
    config.a4_2c_baseline_strategy=="independent_primal_dual_steps" && ...
    config.a4_2c_experimental_strategy=="common_minimum_step", ...
    "stageA4:a42c:Scope", ...
    "A4-2C requires its fixed five-round A/B diagnostic scope.");
assert(indexA.scope.stage_id=="stage_A4" && ...
    indexB.scope.stage_id=="stage_A4" && ...
    canonical_index_equal(indexA,indexB), ...
    "stageA4:a42c:CanonicalIndex", ...
    "The two isolated indices must have identical canonical content.");
runIdA = unique(string(indexA.variable_index.run_id));
runIdB = unique(string(indexB.variable_index.run_id));
assert(isscalar(runIdA) && isscalar(runIdB) && runIdA~=runIdB, ...
    "stageA4:a42c:IndexObjectIsolation", ...
    "The two chains require separately constructed index objects.");
end

function equal = canonical_index_equal(left,right)
names = ["variable_index","constraint_index","fixed_zero_map", ...
    "block_index","soc_link_map","permutation_map"];
equal = true;
for name = names
    if ~isfield(left,name) || ~isfield(right,name)
        equal = false;
        return
    end
    leftValue = remove_run_id(left.(name));
    rightValue = remove_run_id(right.(name));
    if ~isequaln(leftValue,rightValue)
        equal = false;
        return
    end
end
end

function value = remove_run_id(value)
if istable(value) && ismember("run_id",string(value.Properties.VariableNames))
    value = removevars(value,"run_id");
end
end

function audit = audit_isolation(chainA,chainB,indexA,indexB,aUnchanged)
aBefore = reshape(string( ...
    {chainA.iterations.linearization_identity_before}),[],1);
aAfter = reshape(string( ...
    {chainA.iterations.linearization_identity_after}),[],1);
bBefore = reshape(string( ...
    {chainB.iterations.linearization_identity_before}),[],1);
bAfter = reshape(string( ...
    {chainB.iterations.linearization_identity_after}),[],1);
aStates = reshape(string( ...
    {chainA.iterations.state_fingerprint_after}),[],1);
bStates = reshape(string( ...
    {chainB.iterations.state_fingerprint_after}),[],1);
initialEqual = canonical_state_vectors_equal( ...
    chainA.initial_state,chainB.initial_state) && ...
    chainA.initial_state_fingerprint==chainB.initial_state_fingerprint;
identitiesDisjoint = isempty(intersect(unique([aBefore;aAfter]), ...
    unique([bBefore;bAfter])));
stateDivergedAfterFirst = all(aStates~=bStates);
runIdA = unique(string(indexA.variable_index.run_id));
runIdB = unique(string(indexB.variable_index.run_id));
noHandles = ~chainA.execution.state_contains_mutable_handle && ...
    ~chainB.execution.state_contains_mutable_handle;
audit = struct( ...
    "initial_canonical_states_exact",initialEqual, ...
    "chain_ids_distinct",chainA.diagnostic_chain_id~= ...
        chainB.diagnostic_chain_id, ...
    "index_run_ids_distinct",runIdA~=runIdB, ...
    "linearization_identity_sets_disjoint",identitiesDisjoint, ...
    "chain_states_diverge_after_first_update",stateDivergedAfterFirst, ...
    "chain_a_unchanged_after_chain_b",aUnchanged, ...
    "state_contains_no_mutable_handle",noHandles, ...
    "matlab_value_semantics_boundary", ...
        "struct/double/string state; no mutable handle fields", ...
    "passed",initialEqual && chainA.diagnostic_chain_id~= ...
        chainB.diagnostic_chain_id && runIdA~=runIdB && ...
        identitiesDisjoint && stateDivergedAfterFirst && ...
        aUnchanged && noHandles);
end

function audit = audit_common_step_chain(chainB)
items = chainB.iterations;
candidateMinimum = min( ...
    reshape([items.candidate_alpha_primal],[],1), ...
    reshape([items.candidate_alpha_dual],[],1));
appliedPrimal = reshape([items.applied_alpha_primal],[],1);
appliedDual = reshape([items.applied_alpha_dual],[],1);
updateErrors = zeros(5,4);
allGroupsCommon = false(5,1);
for k = 1:5
    applied = items(k).applied_step;
    updateErrors(k,:) = [applied.xi_update_relative_error, ...
        applied.l_update_relative_error,applied.y_update_relative_error, ...
        applied.z_update_relative_error];
    allGroupsCommon(k) = applied.all_four_groups_use_common_step;
end
passed = isequal(appliedPrimal,candidateMinimum) && ...
    isequal(appliedDual,candidateMinimum) && all(allGroupsCommon) && ...
    max(updateErrors,[],'all')<=16*eps;
audit = struct("candidate_minimum",candidateMinimum, ...
    "applied_alpha_primal",appliedPrimal, ...
    "applied_alpha_dual",appliedDual, ...
    "maximum_state_update_relative_error",max(updateErrors,[],'all'), ...
    "all_four_groups_common",allGroupsCommon, ...
    "passed",passed);
end

function audit = audit_direction_provenance(chainA,chainB)
a = chainA.iterations;
b = chainB.iterations;
aDirection = reshape(string({a.direction_fingerprint}),[],1);
bDirection = reshape(string({b.direction_fingerprint}),[],1);
bBeforeState = reshape(string({b.state_fingerprint_before}),[],1);
bAfterState = reshape(string({b.state_fingerprint_after}),[],1);
bInvocation = reshape(string({b.direction_solve_invocation_id}),[],1);
sourceBound = true(5,1);
for k = 1:5
    source = b(k).linearization_identity_before;
    sourceBound(k) = b(k).recursive_direction_linearization_identity==source && ...
        b(k).full_kkt_direction_linearization_identity==source && ...
        b(k).direction_audit_linearization_identity==source && ...
        contains(source,"diagnostic_chain=A4-2C-B") && ...
        contains(bInvocation(k),"A4-2C-B");
end
ownStateChain = isequal(bBeforeState(2:5),bAfterState(1:4));
firstDirectionExpectedEqual = aDirection(1)==bDirection(1);
laterDirectionsDiverged = all(aDirection(2:5)~=bDirection(2:5));
passed = all(sourceBound) && ownStateChain && ...
    numel(unique(bInvocation))==5 && firstDirectionExpectedEqual && ...
    laterDirectionsDiverged && chainB.execution.newton_direction_count==5 && ...
    chainB.execution.full_kkt_audit_count==5;
audit = struct( ...
    "source_identity_bound_to_chain_b",sourceBound, ...
    "chain_b_consumes_only_previous_chain_b_state",ownStateChain, ...
    "solve_invocation_ids_unique",numel(unique(bInvocation))==5, ...
    "round_one_direction_equal_from_same_initial_state", ...
        firstDirectionExpectedEqual, ...
    "rounds_two_to_five_direction_fingerprints_diverge", ...
        laterDirectionsDiverged, ...
    "recursive_solve_count",chainB.execution.newton_direction_count, ...
    "full_kkt_audit_count",chainB.execution.full_kkt_audit_count, ...
    "passed",passed);
end

function audit = audit_numeric_chain(chainA,chainB,config)
items = [chainA.iterations(:);chainB.iterations(:)];
finite = true;
positive = true;
physical = true;
directions = true;
componentDirections = true;
for k = 1:numel(items)
    before = items(k).residuals_before;
    after = items(k).residuals_after;
    valuesBefore = cellfun(@double,struct2cell(before));
    valuesAfter = cellfun(@double,struct2cell(after));
    finite = finite && all(isfinite(valuesBefore)) && ...
        all(isfinite(valuesAfter)) && ...
        isfinite(items(k).objective_value_before) && ...
        isfinite(items(k).objective_value_after) && ...
        all(isfinite(items(k).global_capacity_before)) && ...
        all(isfinite(items(k).global_capacity_after));
    positive = positive && before.minimum_l>0 && before.minimum_z>0 && ...
        after.minimum_l>0 && after.minimum_z>0;
    physical = physical && before.physical_inequality_violation<= ...
        256*eps*before.physical_inequality_scale && ...
        after.physical_inequality_violation<= ...
        256*eps*after.physical_inequality_scale;
    componentValues = struct2cell(items(k).component_relative_errors);
    componentValues = cellfun(@double,componentValues);
    componentDirections = componentDirections && ...
        all(isfinite(componentValues)) && ...
        all(componentValues<=config.tolerances.direction_relative_2norm);
    directions = directions && items(k).direction_relative_error<= ...
        config.tolerances.direction_relative_2norm && ...
        items(k).recursive_kkt_relative_residual<= ...
        config.tolerances.recursive_full_kkt_relative_residual && ...
        items(k).full_kkt_relative_residual<= ...
        config.tolerances.direct_maximum && ...
        items(k).no_full_direction_fallback;
end
audit = struct("all_values_finite",finite, ...
    "strictly_positive_l_and_z",positive, ...
    "physical_inequality_within_existing_threshold",physical, ...
    "every_direction_passes_complete_kkt_audit",directions, ...
    "component_direction_errors_within_threshold",componentDirections, ...
    "passed",finite && positive && physical && directions && ...
        componentDirections);
end

function audit = audit_scale_coverage(chainA,chainB,centrality, ...
        residualScales,familyScales)
chains = {chainA,chainB};
passed = true;
for c = 1:2
    for k = 1:5
        item = chains{c}.complementarity_audits(k);
        passed = passed && item.checks.residual_definitions_exact && ...
            item.checks.residual_scale_coverage_closed && ...
            height(item.centrality_statistics)==4 && ...
            height(item.residual_scale_statistics)==4 && ...
            height(item.inequality_family_scale_statistics)==64;
        grouped = item.inequality_family_scale_statistics;
        for quantity = ["r_ineq","r_comp"]
            for state = ["before","after"]
                mask = grouped.quantity==quantity & grouped.state==state;
                passed = passed && nnz(mask)==16 && ...
                    numel(unique(grouped.group_name(mask)))==16 && ...
                    sum(grouped.count(mask))==7248;
            end
        end
        chainId = chains{c}.diagnostic_chain_id;
        passed = passed && nnz(centrality.chain_id==chainId & ...
            centrality.iteration==k)==4 && ...
            nnz(residualScales.chain_id==chainId & ...
            residualScales.iteration==k)==4 && ...
            nnz(familyScales.chain_id==chainId & ...
            familyScales.iteration==k)==64;
    end
end
combinedComplete = height(centrality)==40 && ...
    height(residualScales)==40 && height(familyScales)==640;
passed = passed && combinedComplete;
audit = struct("both_chains_all_five_rounds_complete",passed, ...
    "combined_scale_tables_complete",combinedComplete, ...
    "passed",passed);
end

function output = make_chain_summary(chainA,chainB)
chains = {chainA,chainB};
records = repmat(chain_summary_template(),10,1);
position = 0;
for c = 1:2
    for k = 1:5
        position = position+1;
        item = chains{c}.iterations(k);
        before = item.residuals_before;
        after = item.residuals_after;
        record = chain_summary_template();
        record.chain_id = char(chains{c}.diagnostic_chain_id);
        record.strategy = char(chains{c}.step_strategy);
        record.iteration = k;
        record.candidate_alpha_primal = item.candidate_alpha_primal;
        record.candidate_alpha_dual = item.candidate_alpha_dual;
        record.applied_alpha_primal = item.applied_alpha_primal;
        record.applied_alpha_dual = item.applied_alpha_dual;
        record.primal_limiter = char(item.primal_step.limiting_constraint_id);
        record.dual_limiter = char(item.dual_step.limiting_constraint_id);
        record.primal_limiter_global_row = ...
            item.primal_step.limiting_constraint_global_row;
        record.primal_limiter_day = item.primal_step.limiting_day;
        record.primal_limiter_hour = item.primal_step.limiting_hour;
        record.primal_limiter_asset_type = ...
            char(item.primal_step.limiting_asset_type);
        record.primal_limiter_asset_id = item.primal_step.limiting_asset_id;
        record.primal_limiter_value = item.primal_step.limiting_value;
        record.primal_limiter_direction = ...
            item.primal_step.limiting_direction;
        record.dual_limiter_global_row = ...
            item.dual_step.limiting_constraint_global_row;
        record.dual_limiter_day = item.dual_step.limiting_day;
        record.dual_limiter_hour = item.dual_step.limiting_hour;
        record.dual_limiter_asset_type = ...
            char(item.dual_step.limiting_asset_type);
        record.dual_limiter_asset_id = item.dual_step.limiting_asset_id;
        record.dual_limiter_value = item.dual_step.limiting_value;
        record.dual_limiter_direction = item.dual_step.limiting_direction;
        record.equality_before = before.equality_inf;
        record.equality_after = after.equality_inf;
        record.slack_equality_before = before.slack_equality_inf;
        record.slack_equality_after = after.slack_equality_inf;
        record.physical_violation_before = ...
            before.physical_inequality_violation;
        record.physical_violation_after = ...
            after.physical_inequality_violation;
        record.dual_before = before.dual_inf;
        record.dual_after = after.dual_inf;
        record.complementarity_inf_before = before.complementarity_inf;
        record.complementarity_inf_after = after.complementarity_inf;
        record.gap_before = before.complementarity_gap;
        record.gap_after = after.complementarity_gap;
        record.raw_complementarity_before = before.raw_complementarity;
        record.raw_complementarity_after = after.raw_complementarity;
        record.mu_before = before.mu;
        record.mu_after = after.mu;
        record.minimum_l_after = after.minimum_l;
        record.minimum_z_after = after.minimum_z;
        record.direction_relative_error = item.direction_relative_error;
        record.xi_relative_error = item.component_relative_errors.xi;
        record.y_relative_error = item.component_relative_errors.y;
        record.l_relative_error = item.component_relative_errors.l;
        record.z_relative_error = item.component_relative_errors.z;
        record.recursive_kkt_relative_residual = ...
            item.recursive_kkt_relative_residual;
        record.full_kkt_relative_residual = item.full_kkt_relative_residual;
        record.objective_before = item.objective_value_before;
        record.objective_after = item.objective_value_after;
        records(position) = record;
    end
end
output = struct2table(records);
output.chain_id = string(output.chain_id);
output.strategy = string(output.strategy);
output.primal_limiter = string(output.primal_limiter);
output.dual_limiter = string(output.dual_limiter);
output.primal_limiter_asset_type = ...
    string(output.primal_limiter_asset_type);
output.dual_limiter_asset_type = string(output.dual_limiter_asset_type);
end

function record = chain_summary_template()
record = struct("chain_id","","strategy","","iteration",0, ...
    "candidate_alpha_primal",0,"candidate_alpha_dual",0, ...
    "applied_alpha_primal",0,"applied_alpha_dual",0, ...
    "primal_limiter","","dual_limiter","", ...
    "primal_limiter_global_row",0,"primal_limiter_day",NaN, ...
    "primal_limiter_hour",NaN,"primal_limiter_asset_type","", ...
    "primal_limiter_asset_id",NaN, ...
    "primal_limiter_value",NaN,"primal_limiter_direction",NaN, ...
    "dual_limiter_global_row",0,"dual_limiter_day",NaN, ...
    "dual_limiter_hour",NaN,"dual_limiter_asset_type","", ...
    "dual_limiter_asset_id",NaN, ...
    "dual_limiter_value",NaN,"dual_limiter_direction",NaN, ...
    "equality_before",0,"equality_after",0, ...
    "slack_equality_before",0,"slack_equality_after",0, ...
    "physical_violation_before",0,"physical_violation_after",0, ...
    "dual_before",0,"dual_after",0, ...
    "complementarity_inf_before",0,"complementarity_inf_after",0, ...
    "gap_before",0,"gap_after",0, ...
    "raw_complementarity_before",0,"raw_complementarity_after",0, ...
    "mu_before",0,"mu_after",0,"minimum_l_after",0, ...
    "minimum_z_after",0,"direction_relative_error",0, ...
    "xi_relative_error",0,"y_relative_error",0,"l_relative_error",0, ...
    "z_relative_error",0,"recursive_kkt_relative_residual",0, ...
    "full_kkt_relative_residual",0,"objective_before",0, ...
    "objective_after",0);
end

function output = make_capacity_history(chainA,chainB)
chains = {chainA,chainB};
chainId = strings(20,1);
strategy = strings(20,1);
iteration = zeros(20,1);
state = strings(20,1);
objective = zeros(20,1);
capacity = zeros(20,14);
position = 0;
for c = 1:2
    for k = 1:5
        item = chains{c}.iterations(k);
        for stateName = ["before","after"]
            position = position+1;
            chainId(position) = chains{c}.diagnostic_chain_id;
            strategy(position) = chains{c}.step_strategy;
            iteration(position) = k;
            state(position) = stateName;
            objective(position) = item.("objective_value_"+stateName);
            capacity(position,:) = reshape( ...
                item.("global_capacity_"+stateName),1,[]);
        end
    end
end
metadata = table(chainId,strategy,iteration,state,objective, ...
    'VariableNames',{'chain_id','strategy','iteration','state', ...
    'investment_objective'});
capacityTable = array2table(capacity, ...
    'VariableNames',cellstr(chainA.iterations(1).global_capacity_names));
output = [metadata,capacityTable];
end

function output = make_comparison_table(chainA,chainB)
metrics = ["equality_inf","slack_equality_inf", ...
    "physical_inequality_violation","dual_inf","complementarity_inf", ...
    "complementarity_gap","raw_complementarity","mu", ...
    "minimum_l","minimum_z","investment_objective"];
n = 5*numel(metrics);
iteration = zeros(n,1);
metric = strings(n,1);
initialValue = zeros(n,1);
chainAValue = zeros(n,1);
chainBValue = zeros(n,1);
chainADelta = zeros(n,1);
chainBDelta = zeros(n,1);
chainARatio = nan(n,1);
chainBRatio = nan(n,1);
chainARatioDefined = false(n,1);
chainBRatioDefined = false(n,1);
chainBToARatio = nan(n,1);
chainBToARatioDefined = false(n,1);
chainAScaledChange = zeros(n,1);
chainBScaledChange = zeros(n,1);
betweenScaledDifference = zeros(n,1);
position = 0;
for k = 1:5
    for metricName = metrics
        position = position+1;
        initial = metric_value(chainA.iterations(1),metricName,"before");
        aValue = metric_value(chainA.iterations(k),metricName,"after");
        bValue = metric_value(chainB.iterations(k),metricName,"after");
        [aRatio,aDefined] = safe_ratio(aValue,initial);
        [bRatio,bDefined] = safe_ratio(bValue,initial);
        [betweenRatio,betweenDefined] = safe_ratio(bValue,aValue);
        iteration(position) = k;
        metric(position) = metricName;
        initialValue(position) = initial;
        chainAValue(position) = aValue;
        chainBValue(position) = bValue;
        chainADelta(position) = aValue-initial;
        chainBDelta(position) = bValue-initial;
        chainARatio(position) = aRatio;
        chainBRatio(position) = bRatio;
        chainARatioDefined(position) = aDefined;
        chainBRatioDefined(position) = bDefined;
        chainBToARatio(position) = betweenRatio;
        chainBToARatioDefined(position) = betweenDefined;
        chainAScaledChange(position) = ...
            (aValue-initial)/max(1,abs(initial));
        chainBScaledChange(position) = ...
            (bValue-initial)/max(1,abs(initial));
        betweenScaledDifference(position) = ...
            (bValue-aValue)/max([1,abs(aValue),abs(bValue)]);
    end
end
output = table(iteration,metric,initialValue,chainAValue,chainBValue, ...
    chainADelta,chainBDelta,chainARatio,chainBRatio, ...
    chainARatioDefined,chainBRatioDefined,chainBToARatio, ...
    chainBToARatioDefined,chainAScaledChange,chainBScaledChange, ...
    betweenScaledDifference, ...
    'VariableNames',{'iteration','metric','initial_value','chain_a_value', ...
    'chain_b_value','chain_a_delta_from_initial', ...
    'chain_b_delta_from_initial','chain_a_ratio_to_initial', ...
    'chain_b_ratio_to_initial','chain_a_ratio_defined', ...
    'chain_b_ratio_defined','chain_b_to_chain_a_ratio', ...
    'chain_b_to_chain_a_ratio_defined','chain_a_scaled_change', ...
    'chain_b_scaled_change','between_chain_scaled_difference'});
end

function value = metric_value(item,metric,state)
if metric=="investment_objective"
    value = item.("objective_value_"+state);
else
    snapshot = item.("residuals_"+state);
    value = snapshot.(metric);
end
end

function [ratio,defined] = safe_ratio(value,reference)
defined = reference~=0;
if defined
    ratio = value/reference;
else
    ratio = NaN;
end
end

function output = combine_audit_table(chainA,chainB,fieldName)
chains = {chainA,chainB};
output = table();
for c = 1:2
    for k = 1:5
        rows = chains{c}.complementarity_audits(k).(fieldName);
        rows = addvars(rows, ...
            repmat(chains{c}.diagnostic_chain_id,height(rows),1), ...
            repmat(chains{c}.step_strategy,height(rows),1), ...
            'Before',1,'NewVariableNames',{'chain_id','strategy'});
        output = [output;rows]; %#ok<AGROW>
    end
end
end

function baseline = make_baseline_table(iterations)
count = numel(iterations);
iteration = reshape([iterations.iteration],[],1);
alphaPrimal = reshape([iterations.alpha_primal],[],1);
alphaDual = reshape([iterations.alpha_dual],[],1);
primalLimiter = strings(count,1);
dualLimiter = strings(count,1);
equalityBefore = zeros(count,1); equalityAfter = zeros(count,1);
slackEqualityBefore = zeros(count,1); slackEqualityAfter = zeros(count,1);
dualBefore = zeros(count,1); dualAfter = zeros(count,1);
complementarityInfBefore = zeros(count,1);
complementarityInfAfter = zeros(count,1);
gapBefore = zeros(count,1); gapAfter = zeros(count,1);
minimumLAfter = zeros(count,1); minimumZAfter = zeros(count,1);
directionRelativeError = zeros(count,1);
xiRelativeError = zeros(count,1); yRelativeError = zeros(count,1);
lRelativeError = zeros(count,1); zRelativeError = zeros(count,1);
recursiveKktRelativeResidual = zeros(count,1);
fullKktRelativeResidual = zeros(count,1);
for k = 1:count
    item = iterations(k);
    primalLimiter(k) = item.primal_step.limiting_constraint_id;
    dualLimiter(k) = item.dual_step.limiting_constraint_id;
    equalityBefore(k) = item.residuals_before.equality_inf;
    equalityAfter(k) = item.residuals_after.equality_inf;
    slackEqualityBefore(k) = item.residuals_before.slack_equality_inf;
    slackEqualityAfter(k) = item.residuals_after.slack_equality_inf;
    dualBefore(k) = item.residuals_before.dual_inf;
    dualAfter(k) = item.residuals_after.dual_inf;
    complementarityInfBefore(k) = ...
        item.residuals_before.complementarity_inf;
    complementarityInfAfter(k) = ...
        item.residuals_after.complementarity_inf;
    gapBefore(k) = item.residuals_before.complementarity_gap;
    gapAfter(k) = item.residuals_after.complementarity_gap;
    minimumLAfter(k) = item.residuals_after.minimum_l;
    minimumZAfter(k) = item.residuals_after.minimum_z;
    directionRelativeError(k) = item.direction_relative_error;
    xiRelativeError(k) = item.component_relative_errors.xi;
    yRelativeError(k) = item.component_relative_errors.y;
    lRelativeError(k) = item.component_relative_errors.l;
    zRelativeError(k) = item.component_relative_errors.z;
    recursiveKktRelativeResidual(k) = ...
        item.recursive_kkt_relative_residual;
    fullKktRelativeResidual(k) = item.full_kkt_relative_residual;
end
baseline = table(iteration,alphaPrimal,alphaDual,primalLimiter, ...
    dualLimiter,equalityBefore,equalityAfter,slackEqualityBefore, ...
    slackEqualityAfter,dualBefore,dualAfter, ...
    complementarityInfBefore,complementarityInfAfter,gapBefore,gapAfter, ...
    minimumLAfter,minimumZAfter,directionRelativeError,xiRelativeError, ...
    yRelativeError,lRelativeError,zRelativeError, ...
    recursiveKktRelativeResidual,fullKktRelativeResidual, ...
    'VariableNames',{'iteration','alpha_primal','alpha_dual', ...
    'primal_limiter','dual_limiter','equality_before','equality_after', ...
    'slack_equality_before','slack_equality_after','dual_before', ...
    'dual_after','complementarity_inf_before', ...
    'complementarity_inf_after','gap_before','gap_after', ...
    'minimum_l_after','minimum_z_after','direction_relative_error', ...
    'xi_relative_error','y_relative_error','l_relative_error', ...
    'z_relative_error','recursive_kkt_relative_residual', ...
    'full_kkt_relative_residual'});
end

function inventory = make_inequality_inventory(index)
constraints = index.constraint_index;
inventory = constraints(string(constraints.constraint_type)=="inequality", ...
    {'global_row','constraint_id','constraint_name','day','hour', ...
    'asset_type','asset_id','unit'});
inventory = addvars(inventory,(1:height(inventory)).', ...
    'Before','global_row','NewVariableNames','inequality_index');
end

function equal = canonical_state_vectors_equal(left,right)
equal = isequal(left.xi,right.xi) && isequal(left.y,right.y) && ...
    isequal(left.l,right.l) && isequal(left.z,right.z) && ...
    left.iteration_index==right.iteration_index && ...
    left.state_revision==right.state_revision;
end

function equal = canonical_state_equal(left,right)
equal = canonical_state_vectors_equal(left,right) && ...
    left.newton_direction_number==right.newton_direction_number && ...
    left.completed_newton_direction_count== ...
        right.completed_newton_direction_count && ...
    string(left.diagnostic_chain_id)==string(right.diagnostic_chain_id);
end
