function audit = validate_stage_a4_1_test_inventory_contract(actual,projectRoot)
%VALIDATE_STAGE_A4_1_TEST_INVENTORY_CONTRACT Enforce the fixed 24-test set.

if ~(istable(actual) && is_text_scalar(projectRoot))
    error("stageA4:tests:InventoryContractInput", ...
        "An actual inventory table and scalar project root are required.");
end
projectRoot = string(projectRoot);
relativePath = "tests/stage_A4_1_expected_test_inventory.csv";
expectedPath = fullfile(projectRoot,strrep(relativePath,'/',filesep));
if ~isfile(expectedPath)
    error("stageA4:tests:ExpectedInventoryMissing", ...
        "The version-controlled A4-1 expected inventory is missing: %s", ...
        expectedPath);
end

expected = readtable(expectedPath,'Delimiter',',', ...
    'ReadVariableNames',true,'TextType','string', ...
    'VariableNamingRule','preserve');
required = ["test_order","test_name","source_file"];
expectedVariables = string(expected.Properties.VariableNames);
actualVariables = string(actual.Properties.VariableNames);
if ~all(ismember(required,expectedVariables)) || ...
        ~all(ismember(required,actualVariables))
    error("stageA4:tests:ExpectedInventorySchema", ...
        "Expected and actual A4-1 inventories require test_order, " + ...
        "test_name, and source_file. expected_columns=[%s] " + ...
        "actual_columns=[%s]",strjoin(expectedVariables,','), ...
        strjoin(actualVariables,','));
end
expected = expected(:,cellstr(required));
actual = actual(:,cellstr(required));

expectedNames = strip(string(expected.test_name));
actualNames = strip(string(actual.test_name));
expectedSources = normalize_sources(expected.source_file);
actualSources = normalize_sources(actual.source_file);
expectedOrder = double(expected.test_order);
actualOrder = double(actual.test_order);
allowedSources = [ ...
    "tests/unit/test_stage_a4_model.m"
    "tests/unit/test_stage_a4_step_update.m"
    "tests/integration/test_stage_a4_single_iteration.m"];

if height(expected) ~= 24 || ...
        ~isequal(expectedOrder,(1:24).') || ...
        any(strlength(expectedNames) == 0) || ...
        numel(unique(expectedNames)) ~= 24
    error("stageA4:tests:ExpectedInventoryInvalid", ...
        "The controlled A4-1 inventory must contain exactly 24 unique, " + ...
        "consecutively ordered tests.");
end
if ~all(startsWith(expectedNames,"test_stage_a4_")) || ...
        ~all(ismember(expectedSources,allowedSources))
    error("stageA4:tests:ExpectedInventorySource", ...
        "Every controlled A4-1 test must come from one of the three " + ...
        "explicit A4-1 test files.");
end
if height(actual) ~= 24 || ...
        ~isequal(actualOrder,(1:24).') || ...
        any(strlength(actualNames) == 0) || ...
        numel(unique(actualNames)) ~= 24
    error("stageA4:tests:ActualInventoryInvalid", ...
        "The discovered A4-1 inventory must contain exactly 24 unique, " + ...
        "consecutively ordered tests.");
end

missing = setdiff(expectedNames,actualNames,'stable');
unexpected = setdiff(actualNames,expectedNames,'stable');
orderMatches = isequal(actualNames,expectedNames);
sourceMatches = orderMatches && isequal(actualSources,expectedSources);
if ~isempty(missing) || ~isempty(unexpected) || ...
        ~orderMatches || ~sourceMatches
    error("stageA4:tests:ExpectedInventoryMismatch", ...
        "Discovered A4-1 tests differ from the controlled 24-test " + ...
        "inventory. missing=[%s] unexpected=[%s] " + ...
        "order_matches=%d source_matches=%d",strjoin(missing,','), ...
        strjoin(unexpected,','),orderMatches,sourceMatches);
end

audit = struct( ...
    "matches_expected",true, ...
    "expected_count",24, ...
    "actual_count",height(actual), ...
    "expected_inventory_relative_path",char(relativePath), ...
    "expected_inventory_sha256",char(lower(string( ...
        compute_sha256_file(expectedPath)))), ...
    "test_names_unique",true, ...
    "missing_count",0, ...
    "unexpected_count",0, ...
    "order_matches",true, ...
    "source_files_match",true);
end

function values = normalize_sources(values)
values = replace(strip(string(values)),'\','/');
end

function tf = is_text_scalar(value)
tf = ischar(value) || (isstring(value) && isscalar(value));
end
