function audit = validate_stage_a4_2d_1_test_inventory_contract( ...
        actual,projectRoot)
%VALIDATE_STAGE_A4_2D_1_TEST_INVENTORY_CONTRACT Enforce the fixed 8-test set.

if ~(istable(actual) && (ischar(projectRoot) || ...
        (isstring(projectRoot) && isscalar(projectRoot))))
    error("stageA4:tests:A42D1InventoryContractInput", ...
        "An actual inventory table and scalar project root are required.");
end
projectRoot = string(projectRoot);
relativePath = "tests/stage_A4_2D_1_expected_test_inventory.csv";
expectedPath = fullfile(projectRoot,strrep(relativePath,'/',filesep));
if ~isfile(expectedPath)
    error("stageA4:tests:A42D1ExpectedInventoryMissing", ...
        "The controlled A4-2D-1 inventory is missing: %s",expectedPath);
end

expected = readtable(expectedPath,'Delimiter',',', ...
    'ReadVariableNames',true,'TextType','string', ...
    'VariableNamingRule','preserve');
required = ["test_order","test_name","source_file"];
if ~all(ismember(required,string(expected.Properties.VariableNames))) || ...
        ~all(ismember(required,string(actual.Properties.VariableNames)))
    error("stageA4:tests:A42D1ExpectedInventorySchema", ...
        "A4-2D-1 inventories require test_order, test_name, and source_file.");
end
expected = expected(:,cellstr(required));
actual = actual(:,cellstr(required));
expected.test_name = strip(string(expected.test_name));
actual.test_name = strip(string(actual.test_name));
expected.source_file = replace(strip(string(expected.source_file)),'\','/');
actual.source_file = replace(strip(string(actual.source_file)),'\','/');
expectedOrder = double(expected.test_order);
actualOrder = double(actual.test_order);
allowedSource = ...
    "tests/integration/test_stage_a4_small_step_root_cause_audit.m";

if height(expected)~=8 || ~isequal(expectedOrder,(1:8).') || ...
        numel(unique(expected.test_name))~=8 || ...
        ~all(expected.source_file==allowedSource)
    error("stageA4:tests:A42D1ExpectedInventoryInvalid", ...
        "The controlled A4-2D-1 inventory must contain eight ordered tests.");
end
if height(actual)~=8 || ~isequal(actualOrder,(1:8).') || ...
        numel(unique(actual.test_name))~=8 || ...
        ~all(actual.source_file==allowedSource)
    error("stageA4:tests:A42D1ActualInventoryInvalid", ...
        "The discovered A4-2D-1 inventory must contain eight ordered tests.");
end
if ~isequal(actual.test_name,expected.test_name) || ...
        ~isequal(actual.source_file,expected.source_file)
    error("stageA4:tests:A42D1ExpectedInventoryMismatch", ...
        "Discovered A4-2D-1 tests differ from the controlled inventory.");
end

audit = struct( ...
    "matches_expected",true, ...
    "expected_count",8, ...
    "actual_count",height(actual), ...
    "expected_inventory_relative_path",relativePath, ...
    "expected_inventory_sha256",lower(string( ...
        compute_sha256_file(expectedPath))), ...
    "test_names_unique",true, ...
    "order_matches",true, ...
    "source_files_match",true);
end
