function evidence = run_stage_A4_RNS_1_tests()
%RUN_STAGE_A4_RNS_1_TESTS Run only the fixed RNS stability tests.

repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(repoRoot);
addpath(genpath(fullfile(repoRoot,"src")));
relativeFile = ...
    "tests/integration/test_stage_a4_rns1_numerical_stability.m";
absolutePath = fullfile(repoRoot,strrep(relativeFile,"/",filesep));
assert(isfile(absolutePath),"stageA4:tests:RNS1MissingFile", ...
    "A4-RNS-1 integration test file is missing: %s",absolutePath);
suite = matlab.unittest.TestSuite.fromFile(absolutePath);
testNames = string({suite.Name}).';
sourceFiles = repmat(relativeFile,numel(suite),1);
inventory = table(uint32((1:numel(suite)).'),testNames,sourceFiles, ...
    'VariableNames',{'test_order','test_name','source_file'});
assert(height(inventory)==17 && numel(unique(testNames))==17, ...
    "stageA4:tests:RNS1Inventory", ...
    "The fixed A4-RNS-1 suite must contain exactly 17 unique tests.");
inventoryAudit = rkkt.diagnostics.validate_stage_a4_rns1_test_inventory_contract( ...
    inventory,repoRoot);
fprintf("Controlled A4-RNS-1 test inventory (%d tests):\n", ...
    height(inventory));
disp(inventory);

runner = matlab.unittest.TestRunner.withTextOutput( ...
    OutputDetail=matlab.unittest.Verbosity.Detailed);
raw = runner.run(suite);
rawNames = string({raw.Name}).';
assert(numel(raw)==17 && isequal(rawNames,testNames), ...
    "stageA4:tests:RNS1ResultIdentity", ...
    "A4-RNS-1 result identity/order differs from its fixed inventory.");
passed = logical([raw.Passed]).';
failed = logical([raw.Failed]).';
incomplete = logical([raw.Incomplete]).';
durationSeconds = zeros(numel(raw),1);
for k = 1:numel(raw)
    duration = raw(k).Duration;
    if isduration(duration)
        durationSeconds(k) = seconds(duration);
    else
        durationSeconds(k) = double(duration);
    end
end
results = table(rawNames,passed,failed,incomplete,durationSeconds, ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds'});
summary = struct( ...
    "test_total",height(results), ...
    "test_passed",nnz(passed), ...
    "test_failed",nnz(failed), ...
    "test_incomplete",nnz(incomplete), ...
    "duration_seconds",sum(durationSeconds), ...
    "expected_inventory_match",inventoryAudit.matches_expected, ...
    "expected_inventory_sha256", ...
        inventoryAudit.expected_inventory_sha256);
allPass = summary.test_total==17 && all(passed) && ...
    ~any(failed) && ~any(incomplete) && ...
    inventoryAudit.matches_expected;
evidence = struct("inventory",inventory,"results",results, ...
    "summary",summary,"inventory_audit",inventoryAudit, ...
    "all_pass",allPass);
fprintf("A4-RNS-1 tests total=%d passed=%d failed=%d incomplete=%d\n", ...
    summary.test_total,summary.test_passed,summary.test_failed, ...
    summary.test_incomplete);
if ~allPass
    error("stageA4:tests:RNS1Failed", ...
        "The fixed A4-RNS-1 suite exposed a blocking failure.");
end
end
