function evidence = run_stage_A4_ITER24_scaling_stress_tests(options)
%RUN_STAGE_A4_ITER24_SCALING_STRESS_TESTS Run the fixed 15-test suite.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = ...
        "matlab -batch ""addpath('tests'); evidence="+ ...
        "run_stage_A4_ITER24_scaling_stress_tests(); "+ ...
        "assert(evidence.all_pass);"""
end

root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(genpath(fullfile(root,"src")));
relativeFiles = ...
    "tests/integration/test_stage_a4_iteration24_scaling_stress.m";
expected = fullfile(root,"tests", ...
    "stage_A4_ITER24_scaling_stress_expected_test_inventory.csv");
evidence = run_fixed_test_inventory_with_evidence( ...
    root,relativeFiles,expected, ...
    EvidenceDirectory=options.EvidenceDirectory, ...
    CommandText=options.CommandText, ...
    SuiteLabel="A4-ITER24-SCALE-STRESS");
assert(evidence.summary.test_total==15 && ...
    evidence.summary.test_passed==15 && ...
    evidence.summary.test_failed==0 && ...
    evidence.summary.test_incomplete==0 && ...
    evidence.all_pass, ...
    "stageA4:scaleStress:FixedTestGate", ...
    "The fixed iteration-24 scaling stress suite did not pass 15/15.");
end
