function evidence = run_stage_A4_3_tests(options)
%RUN_STAGE_A4_3_TESTS Run the exact A4-3 entry/checkpoint evidence suite.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = "run_stage_A4_3_tests()"
    options.RunId (1,1) string = ""
end
root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(fullfile(root,"tests"));
addpath(genpath(fullfile(root,"src")));
files = [ ...
    "tests/integration/test_stage_a4_3_formal_candidate.m"
    "tests/unit/test_stage_a4_checkpoint.m"
    "tests/integration/test_stage_a4_result_artifacts.m"
    "tests/integration/test_stage_a4_report.m"];
expected = fullfile(root,"tests", ...
    "stage_A4_3_expected_test_inventory.csv");
evidence = run_fixed_test_inventory_with_evidence( ...
    root,files,expected, ...
    "EvidenceDirectory",options.EvidenceDirectory, ...
    "CommandText",options.CommandText, ...
    "SuiteLabel","stage_A4_3");
assert(evidence.summary.test_total==27 && evidence.all_pass, ...
    "stageA4:tests:A43Failed", ...
    "The exact 27-test A4-3 suite must pass.");
if strlength(strip(options.RunId))>0
    assert(strlength(strip(options.EvidenceDirectory))>0, ...
        "stageA4:tests:SuiteRunBinding", ...
        "Run-bound specialty tests require an evidence directory.");
    evidence.suite_identity = ...
        bind_stage_a4_3_specialty_test_evidence( ...
        root,strip(options.RunId),strip(options.EvidenceDirectory));
    evidence.paths.suite_identity = fullfile( ...
        strip(options.EvidenceDirectory),"suite_identity.json");
end
end
