function evidence = run_stage_A4_2C_tests()
%RUN_STAGE_A4_2C_TESTS Run only the fixed A4-2C diagnostic tests.

repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(repoRoot);
addpath(genpath(fullfile(repoRoot,"src")));
relativeFile = ...
    "tests/integration/test_stage_a4_common_step_ab_comparison.m";
absolutePath = fullfile(repoRoot,strrep(relativeFile,"/",filesep));
assert(isfile(absolutePath),"stageA4:tests:A42CMissingFile", ...
    "A4-2C integration test file is missing: %s",absolutePath);
suite = matlab.unittest.TestSuite.fromFile(absolutePath);
testNames = string({suite.Name}).';
sourceFiles = repmat(relativeFile,numel(suite),1);
inventory = table(uint32((1:numel(suite)).'),testNames,sourceFiles, ...
    'VariableNames',{'test_order','test_name','source_file'});
assert(height(inventory)==8 && numel(unique(testNames))==8, ...
    "stageA4:tests:A42CInventory", ...
    "The fixed A4-2C suite must contain exactly eight unique tests.");
inventoryAudit = validate_stage_a4_2c_test_inventory_contract( ...
    inventory,repoRoot);
fprintf("Controlled A4-2C test inventory (%d tests):\n",height(inventory));
disp(inventory);

runner = matlab.unittest.TestRunner.withTextOutput( ...
    "OutputDetail",matlab.unittest.Verbosity.Detailed);
raw = runner.run(suite);
rawNames = string({raw.Name}).';
assert(numel(raw)==8 && isequal(rawNames,testNames), ...
    "stageA4:tests:A42CResultIdentity", ...
    "A4-2C result identity/order differs from its fixed inventory.");
passed = logical([raw.Passed]).';
failed = logical([raw.Failed]).';
incomplete = logical([raw.Incomplete]).';
durationSeconds = zeros(numel(raw),1);
for testIndex = 1:numel(raw)
    duration = raw(testIndex).Duration;
    if isduration(duration)
        durationSeconds(testIndex) = seconds(duration);
    else
        durationSeconds(testIndex) = double(duration);
    end
end
results = table(rawNames,passed,failed,incomplete,durationSeconds, ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds'});
summary = struct( ...
    "test_total",height(results), ...
    "test_passed",nnz(passed), ...
    "test_failed",nnz(failed), ...
    "test_incomplete",nnz(incomplete), ...
    "duration_seconds",sum(durationSeconds), ...
    "expected_inventory_match",inventoryAudit.matches_expected, ...
    "expected_inventory_sha256", ...
        inventoryAudit.expected_inventory_sha256);
allPass = summary.test_total==8 && all(passed) && ...
    ~any(failed) && ~any(incomplete) && ...
    inventoryAudit.matches_expected;
evidence = struct("inventory",inventory,"results",results, ...
    "summary",summary,"inventory_audit",inventoryAudit, ...
    "all_pass",allPass);
if ~allPass
    error("stageA4:tests:A42CFailed", ...
        "One or more fixed A4-2C tests failed or were incomplete.");
end
end
