function evidence = run_stage_A4_3_test_evidence_tests(options)
%RUN_STAGE_A4_3_TEST_EVIDENCE_TESTS Test orchestration without formal count.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = ...
        "run_stage_A4_3_test_evidence_tests()"
end
root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(fullfile(root,"tests"));
addpath(genpath(fullfile(root,"src")));
evidence = rkkt.testing.run_fixed_test_inventory_with_evidence( ...
    root,"tests/unit/test_stage_a4_3_test_evidence_orchestration.m", ...
    fullfile(root,"tests", ...
        "stage_A4_3_test_evidence_expected_test_inventory.csv"), ...
    "EvidenceDirectory",options.EvidenceDirectory, ...
    "CommandText",options.CommandText, ...
    "SuiteLabel","stage_A4_3_test_evidence_infrastructure");
assert(evidence.summary.test_total==5 && evidence.all_pass, ...
    "stageA4:a43:tests:EvidenceInfrastructureFailed", ...
    "The exact five-test evidence infrastructure suite must pass.");
end
