function evidence = run_stage_A4_3_finalizer_tests(options)
%RUN_STAGE_A4_3_FINALIZER_TESTS Run the independent A4-3 finalizer suite.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = ...
        "run_stage_A4_3_finalizer_tests()"
end
root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(fullfile(root,"tests"));
addpath(genpath(fullfile(root,"src")));
files = "tests/integration/testA43Finalizer.m";
expected = fullfile(root,"tests", ...
    "stage_A4_3_finalizer_expected_test_inventory.csv");
evidence = run_fixed_test_inventory_with_evidence( ...
    root,files,expected, ...
    "EvidenceDirectory",options.EvidenceDirectory, ...
    "CommandText",options.CommandText, ...
    "SuiteLabel","stage_A4_3_finalizer");
assert(evidence.summary.test_total==5 && evidence.all_pass, ...
    "stageA4:tests:A43FinalizerFailed", ...
    "The exact five-test A4-3 finalizer suite must pass.");
end
