function evidence = run_stage_A4_2D_2A_R1_tests(options)
%RUN_STAGE_A4_2D_2A_R1_TESTS Run only the fixed stable-v2 R1 tests.

arguments
    options.PrecomputedResult (1,1) struct = struct()
end
repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(repoRoot);
addpath(fullfile(repoRoot,"tests"));
addpath(genpath(fullfile(repoRoot,"src")));
hasPrecomputed = ~isempty(fieldnames(options.PrecomputedResult));
if hasPrecomputed
    stage_a4_r1_test_cache("set",options.PrecomputedResult);
end
cacheCleanup = onCleanup(@()stage_a4_r1_test_cache("clear"));

relativeFile = ...
    "tests/integration/test_stage_a4_objective_unitization_stable_rerun.m";
absolutePath = fullfile(repoRoot,strrep(relativeFile,"/",filesep));
assert(isfile(absolutePath),"stageA4:tests:R1MissingFile", ...
    "R1 integration test file is missing: %s",absolutePath);
suite = matlab.unittest.TestSuite.fromFile(absolutePath);
testNames = string({suite.Name}).';
sourceFiles = repmat(relativeFile,numel(suite),1);
inventory = table(uint32((1:numel(suite)).'),testNames,sourceFiles, ...
    'VariableNames',{'test_order','test_name','source_file'});
assert(height(inventory)==18 && numel(unique(testNames))==18, ...
    "stageA4:tests:R1Inventory", ...
    "The fixed R1 suite must contain exactly 18 unique tests.");
inventoryAudit = rkkt.diagnostics.validate_stage_a4_2d_2a_r1_test_inventory_contract( ...
    inventory,repoRoot);
fprintf("Controlled A4-2D-2A-R1 test inventory (%d tests):\n", ...
    height(inventory));
disp(inventory);

runner = matlab.unittest.TestRunner.withTextOutput( ...
    "OutputDetail",matlab.unittest.Verbosity.Detailed);
raw = runner.run(suite);
rawNames = string({raw.Name}).';
assert(numel(raw)==18 && isequal(rawNames,testNames), ...
    "stageA4:tests:R1ResultIdentity", ...
    "R1 result identity/order differs from its fixed inventory.");
passed = logical([raw.Passed]).';
failed = logical([raw.Failed]).';
incomplete = logical([raw.Incomplete]).';
durationSeconds = zeros(numel(raw),1);
details = strings(numel(raw),1);
for k = 1:numel(raw)
    duration = raw(k).Duration;
    if isduration(duration)
        durationSeconds(k) = seconds(duration);
    else
        durationSeconds(k) = double(duration);
    end
    details(k) = "";
end
results = table(rawNames,passed,failed,incomplete,durationSeconds,details, ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds','details'});
summary = struct( ...
    "test_total",height(results), ...
    "test_passed",nnz(passed), ...
    "test_failed",nnz(failed), ...
    "test_incomplete",nnz(incomplete), ...
    "duration_seconds",sum(durationSeconds), ...
    "precomputed_result_consumed",hasPrecomputed, ...
    "expected_inventory_match",inventoryAudit.matches_expected, ...
    "expected_inventory_sha256", ...
        inventoryAudit.expected_inventory_sha256);
allPass = summary.test_total==18 && all(passed) && ...
    ~any(failed) && ~any(incomplete) && ...
    inventoryAudit.matches_expected;
evidence = struct("inventory",inventory,"results",results, ...
    "summary",summary,"inventory_audit",inventoryAudit, ...
    "all_pass",allPass);
fprintf("R1 tests total=%d passed=%d failed=%d incomplete=%d\n", ...
    summary.test_total,summary.test_passed,summary.test_failed, ...
    summary.test_incomplete);
clear cacheCleanup
if ~allPass
    error("stageA4:tests:R1Failed", ...
        "The fixed R1 suite exposed a blocking failure.");
end
end
