function evidence = run_stage_B_2A_tests(options)
%RUN_STAGE_B_2A_TESTS Run the exact frozen B-2A structure suite.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = "run_stage_B_2A_tests()"
end

root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(fullfile(root,"tests"));
addpath(genpath(fullfile(root,"src")));
files = [ ...
    "tests/unit/test_stage_b2a_index.m"; ...
    "tests/unit/test_stage_b2a_linearization.m"; ...
    "tests/unit/test_stage_b2a_full_kkt_structure.m"];
expected = fullfile(root,"tests", ...
    "stage_B_2A_expected_test_inventory.csv");
evidence = rkkt.testing.run_fixed_test_inventory_with_evidence( ...
    root,files,expected, ...
    "EvidenceDirectory",options.EvidenceDirectory, ...
    "CommandText",options.CommandText, ...
    "SuiteLabel","stage_B_2A");
assert(evidence.summary.test_total==19 && evidence.all_pass, ...
    "stageB2A:tests:Inventory", ...
    "The exact nineteen B-2A structure tests must pass.");
end
