function evidence = run_stage_A4_ITER24_rank_replay_tests(options)
%RUN_STAGE_A4_ITER24_RANK_REPLAY_TESTS Run the fixed 12-test replay suite.

arguments
    options.EvidenceDirectory (1,1) string = ""
    options.CommandText (1,1) string = ...
        "matlab -batch ""addpath('tests'); evidence="+ ...
        "run_stage_A4_ITER24_rank_replay_tests(); "+ ...
        "assert(evidence.all_pass);"""
end

root = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(root);
addpath(genpath(fullfile(root,"src")));
relativeFiles = ...
    "tests/integration/test_stage_a4_iteration24_rank_replay.m";
expected = fullfile(root,"tests", ...
    "stage_A4_ITER24_rank_replay_expected_test_inventory.csv");
evidence = rkkt.testing.run_fixed_test_inventory_with_evidence( ...
    root,relativeFiles,expected, ...
    EvidenceDirectory=options.EvidenceDirectory, ...
    CommandText=options.CommandText, ...
    SuiteLabel="A4-ITER24-RANK-REPLAY");
assert(evidence.summary.test_total==12 && ...
    evidence.summary.test_passed==12 && ...
    evidence.summary.test_failed==0 && ...
    evidence.summary.test_incomplete==0 && ...
    evidence.all_pass, ...
    "stageA4:iter24:FixedTestGate", ...
    "The fixed iteration-24 replay suite did not pass 12/12.");
end
