function [solution,diagnostics] = ...
        apply_retained_block_thomas_refinement_passes( ...
        partition,thomas,rhs,passCount,label)
%APPLY_RETAINED_BLOCK_THOMAS_REFINEMENT_PASSES Use one fixed pass schedule.

arguments
    partition (1,1) struct
    thomas (1,1) struct
    rhs {mustBeNumeric,mustBeReal}
    passCount (1,1) double {mustBeInteger,mustBeNonnegative}
    label (1,1) string
end
assert(passCount<=3, ...
    "stageA:RNS1:FixedThomasPassLimit", ...
    "A fixed retained-Thomas schedule permits at most three passes.");

[solution,~,initialSolve] = rkkt.solver.apply_retained_block_thomas_once( ...
    partition,thomas.factors,thomas.elimination_multipliers, ...
    rhs,label+"_initial");
correctionSolve = cell(passCount,1);
for pass = 1:passCount
    residual = rhs-partition.M*solution;
    [correction,~,correctionSolve{pass}] = ...
        rkkt.solver.apply_retained_block_thomas_once( ...
        partition,thomas.factors, ...
        thomas.elimination_multipliers,residual, ...
        label+"_correction_"+string(pass));
    solution = solution+correction;
end
metrics = rkkt.solver.compute_retained_residual_metrics( ...
    partition.M,solution,rhs);
scale = max(ones(size(metrics.residual)), ...
    abs(partition.M)*abs(solution)+abs(rhs));
diagnostics = struct( ...
    "day_id",get_day_id(partition), ...
    "rhs_count",size(rhs,2), ...
    "selected_pass_inherited",passCount, ...
    "fixed_pass_schedule",true, ...
    "initial_solve",initialSolve, ...
    "correction_solve",{correctionSolve}, ...
    "maximum_scaled_residual", ...
        max(abs(metrics.residual)./scale,[],"all"), ...
    "maximum_column_relative", ...
        metrics.maximum_column_relative, ...
    "frobenius_relative",metrics.frobenius_relative, ...
    "componentwise_backward_error", ...
        metrics.componentwise_backward_error, ...
    "additional_factorization_count",0, ...
    "direct_chain_backslash_used",false, ...
    "full_kkt_direction_consumed",false);
end

function dayId = get_day_id(partition)
if isfield(partition,"day_id")
    dayId = partition.day_id;
else
    dayId = 0;
end
end
