function [solution,diagnostics] = ...
        apply_retained_ldl_refinement_passes( ...
        factor,rawOperator,rhs,passCount,label)
%APPLY_RETAINED_LDL_REFINEMENT_PASSES Apply a fixed linear pass schedule.
%
% Diagnostic RHS decompositions inherit the official selected pass count.
% They must not independently trigger or select a nonlinear best pass.

arguments
    factor (1,1) struct
    rawOperator {mustBeNumeric,mustBeReal}
    rhs {mustBeNumeric,mustBeReal}
    passCount (1,1) double {mustBeInteger,mustBeNonnegative}
    label (1,1) string
end
assert(passCount<=3, ...
    "stageA:RNS1:FixedLdlPassLimit", ...
    "A fixed retained-LDL schedule permits at most three passes.");

[solution,initialSolve] = rkkt.solver.solve_with_ldl_factor( ...
    factor,rhs,label+"_initial");
correctionSolve = cell(passCount,1);
for pass = 1:passCount
    residual = rhs-rawOperator*solution;
    [correction,correctionSolve{pass}] = rkkt.solver.solve_with_ldl_factor( ...
        factor,residual,label+"_correction_"+string(pass));
    solution = solution+correction;
end
metrics = rkkt.solver.compute_retained_residual_metrics( ...
    rawOperator,solution,rhs);
diagnostics = struct( ...
    "selected_pass_inherited",passCount, ...
    "fixed_pass_schedule",true, ...
    "rhs_count",size(rhs,2), ...
    "initial_solve",initialSolve, ...
    "correction_solve",{correctionSolve}, ...
    "maximum_column_relative", ...
        metrics.maximum_column_relative, ...
    "frobenius_relative",metrics.frobenius_relative, ...
    "componentwise_backward_error", ...
        metrics.componentwise_backward_error, ...
    "additional_factorization_count",0, ...
    "full_kkt_direction_consumed",false);
end
