function [solution,diagnostics] = apply_stage_b2c_daily_joint_factor( ...
        retained,matrix,rhs,label,options)
%APPLY_STAGE_B2C_DAILY_JOINT_FACTOR Apply one retained sparse LDL factor.
%
% The supplied right-hand side is solved directly with the factorization
% already formed for matrix. No refactorization, inverse, pseudoinverse,
% regularization, dense day conversion, or complete-KKT fallback is used.

arguments
    retained (1,1) struct
    matrix {mustBeNumeric,mustBeReal}
    rhs {mustBeNumeric,mustBeReal}
    label (1,1) string
    options.ResidualTolerance (1,1) double = 1e-10
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.ContinueNumericalPivotWarning (1,1) logical = false
end
assert(options.RefinementPasses<=3, ...
    "stageB2C:dailyJoint:RefinementPassLimit", ...
    "A retained daily-joint LDL factor permits at most three correction passes.");

matrix = sparse(matrix);
n = size(matrix,1);
required = ["L","D","permutation","scale","inertia_zero","dimension"];
assert(all(isfield(retained,required)) && size(matrix,2)==n && ...
    size(rhs,1)==n && retained.dimension==n && ...
    all(isfinite(nonzeros(matrix))) && all(isfinite(rhs),"all"), ...
    "stageB2C:dailyJoint:RetainedFactorShape", ...
    "%s has an invalid retained factor, matrix, or right-hand side.",label);

L = retained.L;
D = retained.D;
permutation = retained.permutation;
scale = retained.scale;
inertiaZero = retained.inertia_zero;
assert(numel(scale)==n && numel(permutation)==n && ...
    all(isfinite(scale)) && all(scale>0), ...
    "stageB2C:dailyJoint:RetainedFactorScale", ...
    "%s retained factor scale or permutation is invalid.",label);

[solution,warning] = apply_once( ...
    L,D,permutation,scale,rhs,label,inertiaZero, ...
    options.ContinueNumericalPivotWarning,"SolveWarning");
assert(all(isfinite(solution),"all"), ...
    "stageB2C:dailyJoint:SolutionFinite", ...
    "%s solution contains NaN or Inf.",label);

residual = matrix*solution-rhs;
columnRelative = vecnorm(residual,2,1)./ ...
    max(ones(1,size(rhs,2)),vecnorm(rhs,2,1));
maximumColumnRelative = full(max(columnRelative));
initialMaximumColumnRelative = maximumColumnRelative;
refinementTriggered = options.RefinementPasses>0 && ...
    maximumColumnRelative>options.ResidualTolerance;
refinementPassesApplied = 0;
refinementSeconds = 0;
if refinementTriggered
    refinementTimer = tic;
    for pass = 1:options.RefinementPasses
        correctionRhs = rhs-matrix*solution;
        [correction,~] = apply_once( ...
            L,D,permutation,scale,correctionRhs, ...
            label+" refinement pass "+string(pass),inertiaZero, ...
            options.ContinueNumericalPivotWarning, ...
            "RefinementSolveWarning");
        candidate = solution+correction;
        assert(all(isfinite(candidate),"all"), ...
            "stageB2C:dailyJoint:RefinementFinite", ...
            "%s refinement pass %d produced NaN or Inf.",label,pass);
        candidateResidual = matrix*candidate-rhs;
        candidateColumnRelative = vecnorm(candidateResidual,2,1)./ ...
            max(ones(1,size(rhs,2)),vecnorm(rhs,2,1));
        candidateMaximum = full(max(candidateColumnRelative));
        if candidateMaximum>=maximumColumnRelative
            break
        end
        solution = candidate;
        residual = candidateResidual;
        maximumColumnRelative = candidateMaximum;
        refinementPassesApplied = pass;
        if maximumColumnRelative<=options.ResidualTolerance
            break
        end
    end
    refinementSeconds = toc(refinementTimer);
end

diagnostics = struct( ...
    "label",label,"rhs_count",size(rhs,2), ...
    "maximum_column_relative_residual",maximumColumnRelative, ...
    "initial_maximum_column_relative_residual", ...
        initialMaximumColumnRelative, ...
    "frobenius_relative_residual", ...
        norm(residual,"fro")/max(1,norm(rhs,"fro")), ...
    "maximum_absolute_residual",max(abs(residual),[],"all"), ...
    "warning_identifier",warning.identifier, ...
    "warning_message",warning.message, ...
    "warning_present",warning.present, ...
    "warning_continued",warning.continued, ...
    "blocking_warning_present",warning.present && ~warning.continued, ...
    "solution_finite",true, ...
    "local_residual_tolerance",options.ResidualTolerance, ...
    "local_residual_target_met", ...
        maximumColumnRelative<=options.ResidualTolerance, ...
    "refinement_enabled",options.RefinementPasses>0, ...
    "refinement_triggered",refinementTriggered, ...
    "refinement_maximum_passes",options.RefinementPasses, ...
    "refinement_passes_applied",refinementPassesApplied, ...
    "solve_seconds",warning.solve_seconds+refinementSeconds, ...
    "additional_factorization_count",0, ...
    "retained_factor_reused",true, ...
    "direct_final_rhs_solve",true, ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "dense_day_conversion_used",false);
end

function [solution,warning] = apply_once( ...
        L,D,permutation,scale,rhs,label,inertiaZero,continueWarning,errorTag)
lastwarn("");
timer = tic;
transformedRhs = scale.*rhs;
work = L\transformedRhs(permutation,:);
work = D\work;
work = L.'\work;
transformedSolution = zeros(size(rhs),"like",rhs);
transformedSolution(permutation,:) = work;
solution = scale.*transformedSolution;
solveSeconds = toc(timer);
[warningMessage,warningId] = lastwarn;
warningPresent = strlength(string(warningId))>0 || ...
    strlength(string(warningMessage))>0;
warningContinued = warningPresent && continueWarning && inertiaZero>0 && ...
    any(string(warningId)== ...
        ["MATLAB:nearlySingularMatrix","MATLAB:singularMatrix"]);
if warningPresent && ~warningContinued
    error("stageB2C:dailyJoint:"+errorTag, ...
        "%s retained-factor solve emitted %s: %s", ...
        label,warningId,warningMessage);
end
warning = struct("identifier",string(warningId), ...
    "message",string(warningMessage),"present",warningPresent, ...
    "continued",warningContinued,"solve_seconds",solveSeconds);
end
