function [solution,diagnostics] = ...
        apply_stage_b2b_retained_chain_rhs(day,thomas,rhs,options)
%APPLY_STAGE_B2B_RETAINED_CHAIN_RHS Solve extra RHS using retained factors.
%
% No block is factored here.  The same Schur pivots and Thomas elimination
% multipliers produced for the physical/capacity RHS are reused for the
% eight daily-water border RHS columns.

arguments
    day (1,1) struct
    thomas (1,1) struct
    rhs (:,:) double
    options.ResidualRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.Label (1,1) string = "stageB2B_extra_rhs"
    options.UseExtendedResidual (1,1) logical = false
end
assert(size(rhs,1)==size(day.M,1) && size(rhs,2)>=1, ...
    "stageB2B:retainedRhs:Shape","Extra chain RHS has invalid shape.");
[initial,~,initialDiagnostics] = rkkt.solver.apply_retained_block_thomas_once( ...
    day,thomas.factors,thomas.elimination_multipliers,rhs, ...
    options.Label);
[solution,refinement] = rkkt.solver.refine_stage_b2b_retained_chain_solution( ...
    day,thomas.factors,thomas.elimination_multipliers,rhs,initial, ...
    MaxPasses=options.ResidualRefinementMaxPasses, ...
    Label=options.Label, ...
    UseExtendedResidual=options.UseExtendedResidual);
residual = day.M*solution-rhs;
relativeResidual = norm(residual,"fro")/max(1,norm(rhs,"fro"));
residualMetrics = rkkt.solver.compute_retained_residual_metrics( ...
    day.M,solution,rhs, ...
    UseExtendedResidual=options.UseExtendedResidual);
% This auxiliary response can have a forward residual floor slightly above
% 1e-10 when the raw day chain is ill-conditioned, even when the solve is
% backward stable to machine precision.  Persist the 1e-10 engineering
% target, but gate the auxiliary solve on finite values and componentwise
% backward stability.  The unchanged formal 1e-10 direction and full-KKT
% residual gates remain mandatory before any IPM state update.
backwardTolerance = 2048*eps;
assert(all(isfinite(solution),"all") && ...
    isfinite(residualMetrics.componentwise_backward_error), ...
    "stageB2B:retainedRhs:Nonfinite", ...
    "%s retained-factor extra RHS is nonfinite.",options.Label);
refinement.engineering_relative_residual_target = 1e-10;
refinement.engineering_relative_residual_target_met = ...
    relativeResidual<=1e-10;
refinement.componentwise_backward_error = ...
    residualMetrics.componentwise_backward_error;
refinement.componentwise_backward_error_tolerance = backwardTolerance;
refinement.componentwise_backward_stability_passed = ...
    residualMetrics.componentwise_backward_error<=backwardTolerance;
diagnostics = struct("initial_solve",initialDiagnostics, ...
    "residual_refinement",refinement, ...
    "relative_residual",relativeResidual, ...
    "engineering_relative_residual_target",1e-10, ...
    "engineering_relative_residual_target_met", ...
        relativeResidual<=1e-10, ...
    "componentwise_backward_error", ...
        residualMetrics.componentwise_backward_error, ...
    "componentwise_backward_error_tolerance",backwardTolerance, ...
    "componentwise_backward_stability_passed", ...
        residualMetrics.componentwise_backward_error<=backwardTolerance, ...
    "extended_residual_used",options.UseExtendedResidual, ...
    "maximum_absolute_residual",max(abs(residual),[],"all"), ...
    "factor_context_reused",true,"additional_factorization_count",0);
end
