function assembly = assemble_stage_b2b_full_kkt(lin)
%ASSEMBLE_STAGE_B2B_FULL_KKT Assemble the independent sparse audit KKT.
%
% The raw primal-dual operator follows docs/08 exactly and is not passed to
% LDL.  Its I/Z complementarity placement is contractually nonsymmetric;
% only H and the explicit transpose block placements are symmetry-audited.

arguments
    lin (1,1) struct
end

contract = rkkt.solver.stage_b2b_linearization_contract(lin);
nx = contract.nx;
neq = contract.neq;
ni = contract.nineq;
H = sparse(lin.H);
A = sparse(lin.A);
G = sparse(lin.G);
I = speye(ni);
Z = spdiags(contract.z,0,ni,ni);
L = spdiags(contract.l,0,ni,ni);

matrix = [H,A.',sparse(nx,ni),G.'; ...
    A,sparse(neq,neq),sparse(neq,ni),sparse(neq,ni); ...
    G,sparse(ni,neq),I,sparse(ni,ni); ...
    sparse(ni,nx),sparse(ni,neq),Z,L];
rhs = [-contract.r_dual;-contract.r_eq; ...
    -contract.r_ineq;-contract.r_comp];
dimension = nx+neq+2*ni;
assert(dimension==18948 && isequal(size(matrix),[dimension,dimension]) && ...
    numel(rhs)==dimension && issparse(matrix) && ...
    all(isfinite(nonzeros(matrix))) && all(isfinite(rhs)), ...
    "stageB2B:fullKkt:Assembly", ...
    "The B-2B sparse full-KKT shape or finite-value contract failed.");

slices = struct( ...
    "xi",(1:nx).', ...
    "y",(nx+(1:neq)).', ...
    "l",(nx+neq+(1:ni)).', ...
    "z",(nx+neq+ni+(1:ni)).', ...
    "stationarity_rows",(1:nx).', ...
    "equality_rows",(nx+(1:neq)).', ...
    "slack_rows",(nx+neq+(1:ni)).', ...
    "complementarity_rows",(nx+neq+ni+(1:ni)).');
symmetry = struct( ...
    "lagrangian_hessian_relative",relative_symmetry_error(H), ...
    "raw_full_kkt_relative",relative_symmetry_error(matrix), ...
    "raw_full_kkt_status", ...
        "NOT_APPLICABLE_CONTRACTUALLY_NONSYMMETRIC", ...
    "a_transpose_relative",relative_block_error( ...
        A.',matrix(1:nx,nx+(1:neq))), ...
    "g_transpose_relative",relative_block_error( ...
        G.',matrix(1:nx,nx+neq+ni+(1:ni))), ...
    "identity_relative",relative_block_error( ...
        I,matrix(nx+neq+(1:ni),nx+neq+(1:ni))), ...
    "z_relative",relative_block_error( ...
        Z,matrix(nx+neq+ni+(1:ni),nx+neq+(1:ni))), ...
    "l_relative",relative_block_error( ...
        L,matrix(nx+neq+ni+(1:ni),nx+neq+ni+(1:ni))));
assert(symmetry.lagrangian_hessian_relative<=1e-12 && ...
    symmetry.a_transpose_relative==0 && ...
    symmetry.g_transpose_relative==0 && ...
    symmetry.identity_relative==0 && symmetry.z_relative==0 && ...
    symmetry.l_relative==0, ...
    "stageB2B:fullKkt:BlockAudit", ...
    "One or more B-2B full-KKT block audits failed.");

assembly = struct();
assembly.stage_id = "stage_B";
assembly.milestone_id = contract.milestone_id;
assembly.linearization_identity = contract.identity;
assembly.matrix = matrix;
assembly.rhs = rhs;
assembly.dimension = dimension;
assembly.nnz = nnz(matrix);
assembly.slices = slices;
assembly.symmetry = symmetry;
assembly.block_audit = build_block_audit(matrix,H,A,G,I,Z,L,nx,neq,ni);
assembly.execution = struct( ...
    "assembled",true,"solved",false,"audit_only",true, ...
    "recursive_direction_consumed",false, ...
    "full_direction_fallback_available",false, ...
    "automatic_symmetrization_used",false, ...
    "regularization_used",false);
end

function audit = build_block_audit(K,H,A,G,I,Z,L,nx,neq,ni)
block_name = ["H";"A_transpose";"G_transpose";"A";"G"; ...
    "I_slack";"Z_complementarity";"L_complementarity"];
row_start = [1;1;1;nx+1;nx+neq+1;nx+neq+1; ...
    nx+neq+ni+1;nx+neq+ni+1];
row_end = [nx;nx;nx;nx+neq;nx+neq+ni;nx+neq+ni; ...
    nx+neq+2*ni;nx+neq+2*ni];
column_start = [1;nx+1;nx+neq+ni+1;1;1;nx+neq+1; ...
    nx+neq+1;nx+neq+ni+1];
column_end = [nx;nx+neq;nx+neq+2*ni;nx;nx;nx+neq+ni; ...
    nx+neq+ni;nx+neq+2*ni];
expected_nnz = [nnz(H);nnz(A);nnz(G);nnz(A);nnz(G); ...
    nnz(I);nnz(Z);nnz(L)];
actual_nnz = zeros(8,1);
for row = 1:8
    actual_nnz(row) = nnz(K(row_start(row):row_end(row), ...
        column_start(row):column_end(row)));
end
status = repmat("PASS",8,1);
status(actual_nnz~=expected_nnz) = "FAIL";
audit = table(block_name,row_start,row_end,column_start,column_end, ...
    expected_nnz,actual_nnz,status);
assert(all(status=="PASS"),"stageB2B:fullKkt:BlockNnz", ...
    "B-2B full-KKT block nnz inventory failed.");
end

function value = relative_symmetry_error(matrix)
value = norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro"));
end

function value = relative_block_error(expected,actual)
value = norm(expected-actual,"fro")/max(1,norm(expected,"fro"));
end
