function assembly = assemble_full_kkt(lin)
%ASSEMBLE_FULL_KKT Assemble the canonical sparse primal-dual Newton system.
% The function consumes the shared linearization without re-evaluating any
% objective, constraint, Jacobian, Hessian, or residual.

arguments
    lin (1,1) struct
end

contract = rkkt.solver.solver_linearization_contract(lin);
nx = contract.nx;
neq = contract.neq;
nineq = contract.nineq;

zeroXiIneq = sparse(nx,nineq);
zeroEqEq = sparse(neq,neq);
zeroEqIneq = sparse(neq,nineq);
zeroIneqEq = sparse(nineq,neq);
zeroIneqIneq = sparse(nineq,nineq);
identityIneq = speye(nineq);
Z = spdiags(contract.z,0,nineq,nineq);
L = spdiags(contract.l,0,nineq,nineq);

matrix = [sparse(lin.H), sparse(lin.A.'), zeroXiIneq, sparse(lin.G.'); ...
          sparse(lin.A), zeroEqEq, zeroEqIneq, zeroEqIneq; ...
          sparse(lin.G), zeroIneqEq, identityIneq, zeroIneqIneq; ...
          sparse(nineq,nx), zeroIneqEq, Z, L];
rhs = [-contract.r_dual; -contract.r_eq; ...
       -contract.r_ineq; -contract.r_comp];

dimension = nx + neq + 2*nineq;
assert(isequal(size(matrix), [dimension,dimension]), ...
    "stageA1:solver:FullKktShape", ...
    "Full KKT has shape %dx%d; expected %dx%d.", ...
    size(matrix,1), size(matrix,2), dimension, dimension);
assert(numel(rhs) == dimension, "stageA1:solver:FullKktRhsShape", ...
    "Full KKT RHS length is inconsistent with the matrix dimension.");
assert(all(isfinite(nonzeros(matrix))) && all(isfinite(rhs)), ...
    "stageA1:solver:FullKktNonfinite", ...
    "Full KKT matrix or RHS contains NaN or Inf.");

assembly = struct();
assembly.linearization_identity = contract.identity;
assembly.matrix = matrix;
assembly.rhs = rhs;
assembly.dimension = dimension;
assembly.nnz = nnz(matrix);
assembly.slices = struct( ...
    "xi", (1:nx).', ...
    "y", (nx + (1:neq)).', ...
    "l", (nx + neq + (1:nineq)).', ...
    "z", (nx + neq + nineq + (1:nineq)).', ...
    "stationarity_rows", (1:nx).', ...
    "equality_rows", (nx + (1:neq)).', ...
    "slack_rows", (nx + neq + (1:nineq)).', ...
    "complementarity_rows", (nx + neq + nineq + (1:nineq)).');
end
