function template = build_stage_b2c_daily_joint_structure_template(lin)
%BUILD_STAGE_B2C_DAILY_JOINT_STRUCTURE_TEMPLATE Cache immutable day slices.
%
% The canonical index maps, daily reduced-space slices, permutation, and
% cross-day structural separation do not change during IPM iterations.
% Build and validate them once; each iteration only refreshes numerical
% residuals and extracts the current reduced matrices.

arguments
    lin (1,1) struct
end

contract = rkkt.solver.stage_b2b_linearization_contract(lin);
assert(contract.milestone_id=="B-2C", ...
    "stageB2C:dailyJointTemplate:Milestone", ...
    "The daily-joint structure template requires a B-2C linearization.");

nx = contract.nx;
globalIndices = [contract.q_global;nx+contract.y_duration];
dayCells = cell(contract.n_days,1);
primalOwner = zeros(contract.nx,1);
equalityOwner = zeros(contract.neq,1);

for d = 1:contract.n_days
    hourlyIndices = vertcat(contract.x_by_day_hour{d,:}, ...
        contract.y_by_day_hour{d,:});
    primalHourlyCount = sum(cellfun(@numel,contract.x_by_day_hour(d,:)));
    primalHourlyIndices = hourlyIndices(1:primalHourlyCount);
    equalityHourlyIndices = hourlyIndices(primalHourlyCount+1:end);
    localIndices = [contract.q_day_by_day{d}; ...
        nx+contract.y_binding_by_day{d}; ...
        interleave_hourly_indices(contract,d,nx)];

    primalOwner([contract.q_day_by_day{d};primalHourlyIndices]) = d;
    equalityOwner([contract.y_binding_by_day{d};equalityHourlyIndices]) = d;
    dayCells{d} = struct( ...
        "day_id",contract.days(d), ...
        "canonical_reduced_indices",localIndices, ...
        "q_day_local_positions",(1:14).', ...
        "pi_day_local_positions",(15:28).', ...
        "hourly_local_positions",(29:numel(localIndices)).', ...
        "hourly_dimension",numel(localIndices)-28, ...
        "water_rows",contract.water_by_day{d});
end
days = vertcat(dayCells{:});

expectedDimensions = lin.layout.daily_chain_dimensions+28;
if isfield(lin,"config") && isfield(lin.config,"expected_daily_joint_dimensions")
    assert(isequal(expectedDimensions, ...
        lin.config.expected_daily_joint_dimensions), ...
        "stageB2C:dailyJointTemplate:ConfiguredDayDimensions", ...
        "Daily joint dimensions disagree with the active configuration.");
end
assert(isequal(reshape(arrayfun(@(value) ...
        numel(value.canonical_reduced_indices),days),1,[]), ...
        expectedDimensions), ...
    "stageB2C:dailyJointTemplate:DayDimensions", ...
    "Daily joint dimensions do not match the active configuration.");

permutation = [globalIndices;vertcat(days.canonical_reduced_indices)];
canonicalDimension = contract.nx+contract.neq;
assert(numel(permutation)==canonicalDimension && ...
    isequal(sort(permutation),(1:canonicalDimension).'), ...
    "stageB2C:dailyJointTemplate:Permutation", ...
    "The daily-joint partition is not a canonical reduced-space bijection.");

assert_no_cross_day_structure(lin,primalOwner,equalityOwner,contract.n_days);

dynamicFields = ["identity","r_dual","r_eq","r_ineq","r_comp", ...
    "l","z","xi","l_water","z_water","l_base","z_base", ...
    "r_ineq_water","r_comp_water","r_ineq_base","r_comp_base"];
staticContract = rmfield(contract,cellstr(dynamicFields));

template = struct( ...
    "stage_id","stage_B", ...
    "milestone_id","B-2C-DAILY-JOINT-STRUCTURE-TEMPLATE", ...
    "template_version","stage_b2c_daily_joint_structure_v1", ...
    "source_linearization_identity",contract.identity, ...
    "nx",contract.nx,"neq",contract.neq,"nineq",contract.nineq, ...
    "days",contract.days,"hours",contract.hours, ...
    "contract_static",staticContract, ...
    "global_indices",globalIndices,"day",days, ...
    "permutation",permutation,"permutation_is_bijection",true, ...
    "cross_day_nnz",0, ...
    "total_daily_dimension",sum(expectedDimensions), ...
    "canonical_reduced_dimension",canonicalDimension);
end

function indices = interleave_hourly_indices(contract,d,nx)
cells = cell(2*contract.n_hours,1);
for t = 1:contract.n_hours
    cells{2*t-1} = contract.x_by_day_hour{d,t};
    cells{2*t} = nx+contract.y_by_day_hour{d,t};
end
indices = vertcat(cells{:});
end

function assert_no_cross_day_structure(lin,primalOwner,equalityOwner,nDays)
[row,column] = find(lin.H);
badH = primalOwner(row)>0 & primalOwner(column)>0 & ...
    primalOwner(row)~=primalOwner(column);

[row,column] = find(lin.A);
badA = equalityOwner(row)>0 & primalOwner(column)>0 & ...
    equalityOwner(row)~=primalOwner(column);

[row,column] = find(lin.G);
owner = primalOwner(column);
local = owner>0;
rowDayIncidence = sparse(row(local),owner(local),true,size(lin.G,1),nDays);
mixedInequalityRows = sum(spones(rowDayIncidence),2)>1;

assert(~any(badH) && ~any(badA) && ~any(mixedInequalityRows), ...
    "stageB2C:dailyJointTemplate:CrossDayStructure", ...
    "H, A, or G contains direct cross-day local-variable structure.");
end
