function [correction,waterAfter] = ...
        compute_stage_b2c_water_slack_second_order_correction( ...
        linearizationBefore,directionXi,alphaPrimal,trialState, ...
        data,index,config,options)
%COMPUTE_STAGE_B2C_WATER_SLACK_SECOND_ORDER_CORRECTION Correct water l.
%
% The accepted primal point and Newton direction are left unchanged.  For
% the configured quadratic daily-water rows only, this function computes
% the exact
% nonlinear Taylor remainder and applies the largest positivity-preserving
% correction fraction:
%
%   l_corrected = l_trial - beta*(g(x_trial)-g(x)-alpha*G*dx).
%
% beta is one whenever the full correction retains at least sigma of the
% ordinary trial slack. Otherwise the frozen fraction-to-boundary tau is
% applied to that centrality boundary without changing the primal/dual
% Newton direction or either formal Newton step length.

arguments
    linearizationBefore (1,1) struct
    directionXi (:,1) double
    alphaPrimal (1,1) double
    trialState (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.PrecomputedWaterAfter (1,1) struct = struct()
    options.AcceptedPrimalDisplacementHigh (:,1) double = zeros(0,1)
    options.AcceptedPrimalDisplacementLow (:,1) double = zeros(0,1)
end

assert(alphaPrimal>0 && alphaPrimal<=1 && isfinite(alphaPrimal), ...
    "stageB2C:waterCorrection:Step", ...
    "alphaPrimal must be finite and in (0,1].");
assert(string(linearizationBefore.milestone_id)=="B-2C" && ...
    string(trialState.milestone_id)=="B-2C", ...
    "stageB2C:waterCorrection:Identity", ...
    "The correction requires B-2C states and linearizations.");
assert(numel(directionXi)==linearizationBefore.counts.primal && ...
    numel(trialState.xi)==linearizationBefore.counts.primal && ...
    numel(trialState.l)==linearizationBefore.counts.inequalities, ...
    "stageB2C:waterCorrection:Dimensions", ...
    "The direction or trial state has an invalid dimension.");

waterRows = linearizationBefore.maps.ineq_water(:);
waterIndex = index.water_constraint_index;
nWater = height(waterIndex);
assert(numel(waterRows)==nWater && ...
    nWater==config.expected_water_inequality_count && ...
    isequal(waterRows,waterIndex.inequality_position), ...
    "stageB2C:waterCorrection:WaterRows", ...
    "The canonical water mapping changed.");
acceptedDisplacementUsed = ...
    ~isempty(options.AcceptedPrimalDisplacementHigh) || ...
    ~isempty(options.AcceptedPrimalDisplacementLow);
if acceptedDisplacementUsed
    assert(numel(options.AcceptedPrimalDisplacementHigh)== ...
        linearizationBefore.counts.primal && ...
        numel(options.AcceptedPrimalDisplacementLow)== ...
        linearizationBefore.counts.primal, ...
        "stageB2C:waterCorrection:AcceptedDisplacement", ...
        "Both accepted primal displacement parts must match the primal dimension.");
    [expectedXiHigh,expectedXiLow] = add_pairs( ...
        linearizationBefore.state.xi, ...
        zeros(linearizationBefore.counts.primal,1), ...
        options.AcceptedPrimalDisplacementHigh, ...
        options.AcceptedPrimalDisplacementLow);
    expectedXi = expectedXiHigh+expectedXiLow;
else
    expectedXi = linearizationBefore.state.xi+alphaPrimal*directionXi;
end
xiClosure = relative_error(trialState.xi,expectedXi);
assert(xiClosure<=16*eps, ...
    "stageB2C:waterCorrection:PrimalUpdate", ...
    "The trial primal point is not the accepted Newton update.");

if isempty(fieldnames(options.PrecomputedWaterAfter))
    waterAfter = rkkt.model.assemble_stage_b_water_linearization( ...
        trialState.xi,data,index,config);
else
    waterAfter = options.PrecomputedWaterAfter;
end
gBefore = linearizationBefore.constraints.water.constraint_value(:);
gAfter = waterAfter.constraint_value(:);
if acceptedDisplacementUsed
    [linearIncrementHigh,linearIncrementLow] = ...
        sparse_matvec_high_low( ...
        linearizationBefore.G(waterRows,:), ...
        options.AcceptedPrimalDisplacementHigh, ...
        options.AcceptedPrimalDisplacementLow);
    linearIncrement = linearIncrementHigh+linearIncrementLow;
    linearIncrementSource = "accepted_state_displacement_high_low";
else
    linearIncrement = alphaPrimal* ...
        (linearizationBefore.G(waterRows,:)*directionXi);
    linearIncrementSource = "scaled_binary64_newton_direction";
end
secondOrderRemainder = gAfter-gBefore-linearIncrement;

lBefore = linearizationBefore.state.l(waterRows);
lTrial = trialState.l(waterRows);
fullCorrectionCandidateL = lTrial-secondOrderRemainder;
fullCorrectionFeasible = all(fullCorrectionCandidateL>0);
centralityFloor = config.centering_sigma*lTrial;
fullCorrectionCentralitySafe = all( ...
    fullCorrectionCandidateL>=centralityFloor);
if fullCorrectionCentralitySafe
    correctionFraction = 1;
    limitingPosition = 0;
else
    positiveRemainder = secondOrderRemainder>0;
    assert(any(positiveRemainder), ...
        "stageB2C:waterCorrection:Fraction", ...
        "A nonpositive full correction requires a positive remainder.");
    ratios = inf(size(secondOrderRemainder));
    ratios(positiveRemainder) = (1-config.centering_sigma)* ...
        lTrial(positiveRemainder)./secondOrderRemainder(positiveRemainder);
    [correctionBoundary,limitingPosition] = min(ratios);
    correctionFraction = config.fraction_to_boundary*correctionBoundary;
end
assert(correctionFraction>0 && correctionFraction<=1 && ...
    isfinite(correctionFraction), ...
    "stageB2C:waterCorrection:Fraction", ...
    "The centrality-limited water correction fraction is invalid.");
appliedSecondOrderCorrection = correctionFraction*secondOrderRemainder;
lCorrected = lTrial-appliedSecondOrderCorrection;
residualBefore = gBefore+lBefore;
residualTrial = gAfter+lTrial;
residualCorrected = gAfter+lCorrected;
acceptedLinearizationDefect = zeros(size(residualBefore));
if acceptedDisplacementUsed
    [slackIncrementHigh,slackIncrementLow] = ...
        two_sum(lTrial,-lBefore);
    slackIncrement = slackIncrementHigh+slackIncrementLow;
    acceptedLinearizationDefect = linearIncrement+slackIncrement+ ...
        alphaPrimal*residualBefore;
    expectedResidual = (1-alphaPrimal)*residualBefore+ ...
        acceptedLinearizationDefect+ ...
        (1-correctionFraction)*secondOrderRemainder;
else
    expectedResidual = (1-alphaPrimal)*residualBefore+ ...
        (1-correctionFraction)*secondOrderRemainder;
end
closure = residualCorrected-expectedResidual;
closureScale = max([ones(size(gAfter)),abs(gAfter),abs(lCorrected), ...
    abs(expectedResidual)],[],2);
closureTolerance = 512*eps(closureScale);

assert(all(isfinite([secondOrderRemainder;lCorrected;closure])) && ...
    all(lCorrected>0) && all(lCorrected>=centralityFloor), ...
    "stageB2C:waterCorrection:Positivity", ...
    "The water correction did not preserve its centrality slack floor.");
assert(all(abs(closure)<=closureTolerance), ...
    "stageB2C:waterCorrection:Closure", ...
    "The corrected water residual does not equal the damped prior residual.");

audit = table(string(waterIndex.constraint_id),waterIndex.day, ...
    waterIndex.hydro_id,string(waterIndex.bound_type),waterRows, ...
    gBefore,gAfter,lBefore,lTrial,fullCorrectionCandidateL,lCorrected, ...
    linearIncrement,secondOrderRemainder,appliedSecondOrderCorrection, ...
    repmat(correctionFraction,nWater,1), ...
    repmat(fullCorrectionCentralitySafe,nWater,1), ...
    repmat(fullCorrectionFeasible,nWater,1),residualBefore,residualTrial, ...
    residualCorrected,expectedResidual,closure,closureTolerance,lCorrected>0, ...
    'VariableNames',{'constraint_id','day','hydro_id','bound_type', ...
    'inequality_position','g_before','g_after','l_before','l_trial', ...
    'full_correction_candidate_l','l_corrected', ...
    'linearized_constraint_increment','second_order_remainder', ...
    'applied_second_order_correction','correction_fraction', ...
    'full_correction_centrality_safe', ...
    'full_correction_feasible','residual_before','residual_trial', ...
    'residual_corrected','expected_corrected_residual','closure_error', ...
    'closure_tolerance','strictly_positive'});

correction = struct( ...
    "method", ...
        "exact_quadratic_remainder_with_centrality_limited_slack_correction", ...
    "formula",correction_formula(acceptedDisplacementUsed), ...
    "accepted_primal_displacement_used",acceptedDisplacementUsed, ...
    "linear_increment_source",linearIncrementSource, ...
    "accepted_linearization_defect",acceptedLinearizationDefect, ...
    "maximum_accepted_linearization_defect", ...
        norm(acceptedLinearizationDefect,inf), ...
    "water_rows",waterRows,"corrected_l",lCorrected, ...
    "second_order_remainder",secondOrderRemainder, ...
    "applied_second_order_correction",appliedSecondOrderCorrection, ...
    "correction_fraction",correctionFraction, ...
    "correction_fraction_limited",correctionFraction<1, ...
    "full_correction_feasible",fullCorrectionFeasible, ...
    "full_correction_centrality_safe",fullCorrectionCentralitySafe, ...
    "full_correction_candidate_l",fullCorrectionCandidateL, ...
    "minimum_full_correction_candidate_l",min(fullCorrectionCandidateL), ...
    "minimum_corrected_to_trial_slack_ratio",min(lCorrected./lTrial), ...
    "centrality_floor_fraction",config.centering_sigma, ...
    "limiting_constraint_position",limitingPosition, ...
    "limiting_constraint_id",limiting_constraint_id( ...
        waterIndex,limitingPosition), ...
    "residual_before",residualBefore, ...
    "residual_trial",residualTrial, ...
    "residual_corrected",residualCorrected, ...
    "expected_corrected_residual",expectedResidual, ...
    "maximum_absolute_remainder",norm(secondOrderRemainder,inf), ...
    "maximum_trial_residual",norm(residualTrial,inf), ...
    "maximum_corrected_residual",norm(residualCorrected,inf), ...
    "maximum_expected_residual",norm(expectedResidual,inf), ...
    "maximum_closure_error",norm(closure,inf), ...
    "minimum_corrected_l",min(lCorrected), ...
    "primal_update_relative_error",xiClosure, ...
    "all_strictly_positive",all(lCorrected>0), ...
    "audit",audit);
end

function value = correction_formula(acceptedDisplacementUsed)
if acceptedDisplacementUsed
    value = ...
        "l_corrected=l_trial-beta*(g_after-g_before-G*(x_trial-x_before))";
else
    value = ...
        "l_corrected=l_trial-beta*(g_after-g_before-alpha*G*dx)";
end
end

function [resultHigh,resultLow] = sparse_matvec_high_low( ...
        matrix,xHigh,xLow)
[rowIndex,columnIndex,entry] = find(sparse(matrix));
[~,order] = sortrows([rowIndex,columnIndex],[1,2]);
rowIndex = rowIndex(order);
columnIndex = columnIndex(order);
entry = entry(order);
counts = accumarray(rowIndex,1,[size(matrix,1),1]);
starts = cumsum([1;counts(1:end-1)]);
resultHigh = zeros(size(matrix,1),1);
resultLow = zeros(size(resultHigh));
for row = 1:size(matrix,1)
    count = counts(row);
    accumulatorHigh = 0;
    accumulatorLow = 0;
    for k = starts(row):(starts(row)+count-1)
        column = columnIndex(k);
        [firstHigh,firstLow] = two_product(entry(k),xHigh(column));
        [secondHigh,secondLow] = two_product(entry(k),xLow(column));
        [productHigh,productLow] = add_pairs( ...
            firstHigh,firstLow,secondHigh,secondLow);
        [accumulatorHigh,accumulatorLow] = add_pairs( ...
            accumulatorHigh,accumulatorLow,productHigh,productLow);
    end
    [resultHigh(row),resultLow(row)] = ...
        two_sum(accumulatorHigh,accumulatorLow);
end
end

function [high,low] = add_pairs(aHigh,aLow,bHigh,bLow)
[sumHigh,sumError] = two_sum(aHigh,bHigh);
[lowHigh,lowError] = two_sum(aLow,bLow);
[sumError,lowCarry] = two_sum(sumError,lowHigh);
[sumHigh,sumCarry] = two_sum(sumHigh,sumError);
low = sumCarry+lowCarry+lowError;
[high,low] = two_sum(sumHigh,low);
end

function [product,errorValue] = two_product(left,right)
product = left.*right;
splitter = 134217729;
leftScaled = splitter*left;
leftHigh = leftScaled-(leftScaled-left);
leftLow = left-leftHigh;
rightScaled = splitter*right;
rightHigh = rightScaled-(rightScaled-right);
rightLow = right-rightHigh;
errorValue = ((leftHigh.*rightHigh-product)+ ...
    leftHigh.*rightLow+leftLow.*rightHigh)+leftLow.*rightLow;
end

function [sumValue,errorValue] = two_sum(left,right)
sumValue = left+right;
rightVirtual = sumValue-left;
leftVirtual = sumValue-rightVirtual;
rightError = right-rightVirtual;
leftError = left-leftVirtual;
errorValue = leftError+rightError;
end

function value = limiting_constraint_id(waterIndex,position)
value = "";
if position>0
    value = string(waterIndex.constraint_id(position));
end
end

function value = relative_error(actual,expected)
value = norm(actual-expected,inf)/ ...
    max([1,norm(actual,inf),norm(expected,inf)]);
end
