function metrics = compute_retained_residual_metrics( ...
        matrix,solution,rhs,options)
%COMPUTE_RETAINED_RESIDUAL_METRICS Audit a solve against its raw operator.

arguments
    matrix {mustBeNumeric,mustBeReal}
    solution {mustBeNumeric,mustBeReal}
    rhs {mustBeNumeric,mustBeReal}
    options.UseExtendedResidual (1,1) logical = false
end
assert(size(matrix,1)==size(matrix,2) && ...
    size(matrix,1)==size(solution,1) && ...
    isequal(size(solution),size(rhs)), ...
    "stageA:RNS1:ResidualMetricShape", ...
    "Raw operator, solution, and RHS dimensions are inconsistent.");

if options.UseExtendedResidual
    residual = rkkt.solver.compute_sparse_residual_double_double( ...
        matrix,solution,rhs);
else
    residual = rhs-matrix*solution;
end
rhsNorm = full(sqrt(sum(abs(rhs).^2,1)));
residualNorm = full(sqrt(sum(abs(residual).^2,1)));
columnRelative = full(residualNorm./max(1,rhsNorm));
denominator = max(ones(size(residual)), ...
    abs(matrix)*abs(solution)+abs(rhs));
metrics = struct( ...
    "maximum_column_relative",full(max(columnRelative)), ...
    "column_relative",columnRelative, ...
    "frobenius_relative",full(norm(residual,"fro")/ ...
        max(1,norm(rhs,"fro"))), ...
    "componentwise_backward_error", ...
        full(max(abs(residual)./denominator,[],"all")), ...
    "maximum_absolute",full(max(abs(residual),[],"all")), ...
    "extended_residual_used",options.UseExtendedResidual, ...
    "residual",residual);
end
