function correction = compute_stage_b2c_water_slack_second_order_correction( ...
        linearizationBefore,directionXi,alphaPrimal,trialState, ...
        data,index,config)
%COMPUTE_STAGE_B2C_WATER_SLACK_SECOND_ORDER_CORRECTION Correct water l.
%
% The accepted primal point and Newton direction are left unchanged.  For
% the configured quadratic daily-water rows only, this function computes
% the exact
% nonlinear Taylor remainder and applies the largest positivity-preserving
% correction fraction:
%
%   l_corrected = l_trial - beta*(g(x_trial)-g(x)-alpha*G*dx).
%
% beta is one whenever the full correction retains at least sigma of the
% ordinary trial slack. Otherwise the frozen fraction-to-boundary tau is
% applied to that centrality boundary without changing the primal/dual
% Newton direction or either formal Newton step length.

arguments
    linearizationBefore (1,1) struct
    directionXi (:,1) double
    alphaPrimal (1,1) double
    trialState (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
end

assert(alphaPrimal>0 && alphaPrimal<=1 && isfinite(alphaPrimal), ...
    "stageB2C:waterCorrection:Step", ...
    "alphaPrimal must be finite and in (0,1].");
assert(string(linearizationBefore.milestone_id)=="B-2C" && ...
    string(trialState.milestone_id)=="B-2C", ...
    "stageB2C:waterCorrection:Identity", ...
    "The correction requires B-2C states and linearizations.");
assert(numel(directionXi)==linearizationBefore.counts.primal && ...
    numel(trialState.xi)==linearizationBefore.counts.primal && ...
    numel(trialState.l)==linearizationBefore.counts.inequalities, ...
    "stageB2C:waterCorrection:Dimensions", ...
    "The direction or trial state has an invalid dimension.");

waterRows = linearizationBefore.maps.ineq_water(:);
waterIndex = index.water_constraint_index;
nWater = height(waterIndex);
assert(numel(waterRows)==nWater && ...
    nWater==config.expected_water_inequality_count && ...
    isequal(waterRows,waterIndex.inequality_position), ...
    "stageB2C:waterCorrection:WaterRows", ...
    "The canonical water mapping changed.");
expectedXi = linearizationBefore.state.xi+alphaPrimal*directionXi;
xiClosure = relative_error(trialState.xi,expectedXi);
assert(xiClosure<=16*eps, ...
    "stageB2C:waterCorrection:PrimalUpdate", ...
    "The trial primal point is not the accepted Newton update.");

waterAfter = rkkt.model.assemble_stage_b_water_linearization( ...
    trialState.xi,data,index,config);
gBefore = linearizationBefore.constraints.water.constraint_value(:);
gAfter = waterAfter.constraint_value(:);
linearIncrement = alphaPrimal* ...
    (linearizationBefore.G(waterRows,:)*directionXi);
secondOrderRemainder = gAfter-gBefore-linearIncrement;

lBefore = linearizationBefore.state.l(waterRows);
lTrial = trialState.l(waterRows);
fullCorrectionCandidateL = lTrial-secondOrderRemainder;
fullCorrectionFeasible = all(fullCorrectionCandidateL>0);
centralityFloor = config.centering_sigma*lTrial;
fullCorrectionCentralitySafe = all( ...
    fullCorrectionCandidateL>=centralityFloor);
if fullCorrectionCentralitySafe
    correctionFraction = 1;
    limitingPosition = 0;
else
    positiveRemainder = secondOrderRemainder>0;
    assert(any(positiveRemainder), ...
        "stageB2C:waterCorrection:Fraction", ...
        "A nonpositive full correction requires a positive remainder.");
    ratios = inf(size(secondOrderRemainder));
    ratios(positiveRemainder) = (1-config.centering_sigma)* ...
        lTrial(positiveRemainder)./secondOrderRemainder(positiveRemainder);
    [correctionBoundary,limitingPosition] = min(ratios);
    correctionFraction = config.fraction_to_boundary*correctionBoundary;
end
assert(correctionFraction>0 && correctionFraction<=1 && ...
    isfinite(correctionFraction), ...
    "stageB2C:waterCorrection:Fraction", ...
    "The centrality-limited water correction fraction is invalid.");
appliedSecondOrderCorrection = correctionFraction*secondOrderRemainder;
lCorrected = lTrial-appliedSecondOrderCorrection;
residualBefore = gBefore+lBefore;
residualTrial = gAfter+lTrial;
residualCorrected = gAfter+lCorrected;
expectedResidual = (1-alphaPrimal)*residualBefore+ ...
    (1-correctionFraction)*secondOrderRemainder;
closure = residualCorrected-expectedResidual;
closureScale = max([ones(size(gAfter)),abs(gAfter),abs(lCorrected), ...
    abs(expectedResidual)],[],2);
closureTolerance = 512*eps(closureScale);

assert(all(isfinite([secondOrderRemainder;lCorrected;closure])) && ...
    all(lCorrected>0) && all(lCorrected>=centralityFloor), ...
    "stageB2C:waterCorrection:Positivity", ...
    "The water correction did not preserve its centrality slack floor.");
assert(all(abs(closure)<=closureTolerance), ...
    "stageB2C:waterCorrection:Closure", ...
    "The corrected water residual does not equal the damped prior residual.");

audit = table(string(waterIndex.constraint_id),waterIndex.day, ...
    waterIndex.hydro_id,string(waterIndex.bound_type),waterRows, ...
    gBefore,gAfter,lBefore,lTrial,fullCorrectionCandidateL,lCorrected, ...
    linearIncrement,secondOrderRemainder,appliedSecondOrderCorrection, ...
    repmat(correctionFraction,nWater,1), ...
    repmat(fullCorrectionCentralitySafe,nWater,1), ...
    repmat(fullCorrectionFeasible,nWater,1),residualBefore,residualTrial, ...
    residualCorrected,expectedResidual,closure,closureTolerance,lCorrected>0, ...
    'VariableNames',{'constraint_id','day','hydro_id','bound_type', ...
    'inequality_position','g_before','g_after','l_before','l_trial', ...
    'full_correction_candidate_l','l_corrected', ...
    'linearized_constraint_increment','second_order_remainder', ...
    'applied_second_order_correction','correction_fraction', ...
    'full_correction_centrality_safe', ...
    'full_correction_feasible','residual_before','residual_trial', ...
    'residual_corrected','expected_corrected_residual','closure_error', ...
    'closure_tolerance','strictly_positive'});

correction = struct( ...
    "method", ...
        "exact_quadratic_remainder_with_centrality_limited_slack_correction", ...
    "formula", ...
        "l_corrected=l_trial-beta*(g_after-g_before-alpha*G*dx)", ...
    "water_rows",waterRows,"corrected_l",lCorrected, ...
    "second_order_remainder",secondOrderRemainder, ...
    "applied_second_order_correction",appliedSecondOrderCorrection, ...
    "correction_fraction",correctionFraction, ...
    "correction_fraction_limited",correctionFraction<1, ...
    "full_correction_feasible",fullCorrectionFeasible, ...
    "full_correction_centrality_safe",fullCorrectionCentralitySafe, ...
    "full_correction_candidate_l",fullCorrectionCandidateL, ...
    "minimum_full_correction_candidate_l",min(fullCorrectionCandidateL), ...
    "minimum_corrected_to_trial_slack_ratio",min(lCorrected./lTrial), ...
    "centrality_floor_fraction",config.centering_sigma, ...
    "limiting_constraint_position",limitingPosition, ...
    "limiting_constraint_id",limiting_constraint_id( ...
        waterIndex,limitingPosition), ...
    "residual_before",residualBefore, ...
    "residual_trial",residualTrial, ...
    "residual_corrected",residualCorrected, ...
    "expected_corrected_residual",expectedResidual, ...
    "maximum_absolute_remainder",norm(secondOrderRemainder,inf), ...
    "maximum_trial_residual",norm(residualTrial,inf), ...
    "maximum_corrected_residual",norm(residualCorrected,inf), ...
    "maximum_expected_residual",norm(expectedResidual,inf), ...
    "maximum_closure_error",norm(closure,inf), ...
    "minimum_corrected_l",min(lCorrected), ...
    "primal_update_relative_error",xiClosure, ...
    "all_strictly_positive",all(lCorrected>0), ...
    "audit",audit);
end

function value = limiting_constraint_id(waterIndex,position)
value = "";
if position>0
    value = string(waterIndex.constraint_id(position));
end
end

function value = relative_error(actual,expected)
value = norm(actual-expected,inf)/ ...
    max([1,norm(actual,inf),norm(expected,inf)]);
end
