function candidate = detect_stage_b2c_joint_microborder( ...
        lin,partition,responses,retainedFactors,problemDayPositions,options)
%DETECT_STAGE_B2C_JOINT_MICROBORDER Confirm one model-derived joint mode.
%
% Version 1 deliberately supports one numerical-zero singleton LDL pivot
% and one exact equality/inequality relation.  The day and relation window
% are inferred from the factor mode; no day or hour is hard coded.

arguments
    lin (1,1) struct
    partition (1,1) struct
    responses (:,1) struct
    retainedFactors (:,1) cell
    problemDayPositions (:,1) double
    options.PrimalFractionTolerance (1,1) double = 1e-8
    options.ModeAlignmentTolerance (1,1) double = 1e-6
    options.RelationResidualTolerance (1,1) double = 1e-12
    options.PreemptiveActiveSetDetection (1,1) logical = false
    options.DegeneracyTolerance (1,1) double = 1e-12
end

candidate = empty_candidate();
if options.PreemptiveActiveSetDetection
    candidate = detect_preemptive_active_set( ...
        lin,partition,options.DegeneracyTolerance, ...
        options.RelationResidualTolerance);
    return
end
if numel(problemDayPositions)~=1
    candidate.stop_reason = "single_problem_day_required";
    return
end
position = problemDayPositions(1);
day = partition.day(position);
responsePosition = find([responses.day_id]==day.day_id,1);
if ~isscalar(responsePosition)
    candidate.stop_reason = "problem_day_response_missing";
    return
end
retained = retainedFactors{responsePosition};
[pivotPosition,pivotValue,pivotStatus] = singleton_zero_pivot(retained);
if pivotStatus~="confirmed"
    candidate.stop_reason = pivotStatus;
    return
end

mode = factor_coordinate_mode(retained,pivotPosition);
mode = mode/norm(mode,2);
localCanonical = day.canonical_reduced_indices(:);
primalPositions = find(localCanonical<=partition.contract.nx);
localPrimalCanonical = localCanonical(primalPositions);
equalityPositions = find(localCanonical>partition.contract.nx);
equalityRows = localCanonical(equalityPositions)-partition.contract.nx;
primalFraction = norm(mode(primalPositions),2);
if primalFraction>options.PrimalFractionTolerance
    candidate.stop_reason = "factor_mode_not_pure_dual";
    candidate.primal_fraction = primalFraction;
    return
end

rows = [vertcat(partition.contract.ineq_by_day_hour{position,:}); ...
    partition.contract.water_by_day{position}];
rows = rows(:);
[equalityMeta,inequalityMeta] = canonical_constraint_metadata( ...
    lin.index,partition.contract);
nHours = partition.contract.n_hours;
scores = zeros(nHours,1);
relationResiduals = Inf(nHours,1);
relations = cell(nHours,1);
for terminalHour = 1:nHours
    hours = (1:terminalHour).';
    [a,b,bGlobal,relationTable] = build_relation_coefficients( ...
        lin,partition.contract,equalityMeta,inequalityMeta,rows, ...
        localPrimalCanonical,day.day_id,hours);
    relationMode = a(equalityRows);
    denominator = norm(relationMode,2)*norm(mode(equalityPositions),2);
    if denominator>0
        scores(terminalHour) = abs( ...
            relationMode.'*mode(equalityPositions))/denominator;
    end
    relationResiduals(terminalHour) = relation_residual( ...
        lin,a,bGlobal,localPrimalCanonical);
    relations{terminalHour} = struct( ...
        "a",a,"b",b,"b_global",bGlobal, ...
        "table",relationTable,"hours",hours);
end
[bestAlignment,bestHour] = max(scores);
runnerUp = max(scores((1:nHours).'~=bestHour));
best = relations{bestHour};
bestResidual = relationResiduals(bestHour);
if bestAlignment<1-options.ModeAlignmentTolerance
    candidate.stop_reason = "joint_relation_not_aligned_with_factor_mode";
    candidate.primal_fraction = primalFraction;
    candidate.mode_alignment = bestAlignment;
    candidate.runner_up_alignment = runnerUp;
    candidate.relation_residual = bestResidual;
    return
end
if bestResidual>options.RelationResidualTolerance
    candidate.stop_reason = "joint_relation_not_exact";
    candidate.primal_fraction = primalFraction;
    candidate.mode_alignment = bestAlignment;
    candidate.runner_up_alignment = runnerUp;
    candidate.relation_residual = bestResidual;
    return
end

if best.a(equalityRows).'*mode(equalityPositions)<0
    best.a = -best.a;
    best.b = -best.b;
    best.b_global = -best.b_global;
    best.table.coefficient = -best.table.coefficient;
end
candidate = struct( ...
    "used",true,"stop_reason","confirmed_single_joint_mode", ...
    "day_position",position,"day_id",day.day_id, ...
    "relation_hours",best.hours,"terminal_hour",bestHour, ...
    "equality_coefficients",best.a, ...
    "inequality_coefficients",best.b, ...
    "global_inequality_coefficients",best.b_global, ...
    "inequality_rows",rows,"relation_table",best.table, ...
    "factor_mode",mode,"factor_pivot_position",pivotPosition, ...
    "factor_pivot_value",pivotValue, ...
    "primal_fraction",primalFraction, ...
    "mode_alignment",bestAlignment, ...
    "runner_up_alignment",runnerUp, ...
    "relation_residual",bestResidual, ...
    "primal_fraction_tolerance",options.PrimalFractionTolerance, ...
    "mode_alignment_tolerance",options.ModeAlignmentTolerance, ...
    "relation_residual_tolerance",options.RelationResidualTolerance, ...
    "joint_d",NaN,"normalized_joint_d",NaN, ...
    "degeneracy_tolerance",options.DegeneracyTolerance, ...
    "candidate_count_below_tolerance",NaN, ...
    "detection_method","retained_ldl_mode_alignment", ...
    "regularization_used",false,"rank_truncation_used",false, ...
    "model_changed",false);
end

function candidate = empty_candidate()
candidate = struct( ...
    "used",false,"stop_reason","not_evaluated", ...
    "day_position",NaN,"day_id",NaN, ...
    "relation_hours",zeros(0,1),"terminal_hour",NaN, ...
    "equality_coefficients",zeros(0,1), ...
    "inequality_coefficients",zeros(0,1), ...
    "global_inequality_coefficients",zeros(0,1), ...
    "inequality_rows",zeros(0,1),"relation_table",table(), ...
    "factor_mode",zeros(0,1),"factor_pivot_position",NaN, ...
    "factor_pivot_value",NaN,"primal_fraction",NaN, ...
    "mode_alignment",NaN,"runner_up_alignment",NaN, ...
    "relation_residual",NaN,"primal_fraction_tolerance",NaN, ...
    "mode_alignment_tolerance",NaN, ...
    "relation_residual_tolerance",NaN, ...
    "joint_d",NaN,"normalized_joint_d",NaN, ...
    "degeneracy_tolerance",NaN, ...
    "candidate_count_below_tolerance",0, ...
    "detection_method","none", ...
    "regularization_used",false,"rank_truncation_used",false, ...
    "model_changed",false);
end

function candidate = detect_preemptive_active_set( ...
        lin,partition,degeneracyTolerance,relationTolerance)
contract = partition.contract;
[equalityMeta,inequalityMeta] = canonical_constraint_metadata( ...
    lin.index,contract);
nHours = contract.n_hours;
recordCount = numel(partition.day)*nHours;
dayPositions = zeros(recordCount,1);
terminalHours = zeros(recordCount,1);
jointD = Inf(recordCount,1);
normalizedD = Inf(recordCount,1);
cursor = 0;
for position = 1:numel(partition.day)
    rows = [vertcat(contract.ineq_by_day_hour{position,:}); ...
        contract.water_by_day{position}];
    rows = rows(:);
    dayMeta = inequalityMeta(rows,:);
    inverseTheta = contract.l(rows)./contract.z(rows);
    dayId = partition.day(position).day_id;
    for terminalHour = 1:nHours
        cursor = cursor+1;
        hours = (1:terminalHour).';
        b = zeros(numel(rows),1);
        upperMask = dayMeta.day==dayId & ...
            ismember(dayMeta.hour,hours) & ...
            ismember(dayMeta.constraint_name, ...
                ["pw_upper_bound","ph_upper_bound","pf_upper_bound"]);
        pchMask = dayMeta.day==dayId & ...
            ismember(dayMeta.hour,hours) & ...
            dayMeta.constraint_name=="pch_lower_bound";
        socLowerMask = dayMeta.day==dayId & ...
            dayMeta.hour==terminalHour & ...
            dayMeta.constraint_name=="soc_lower_bound";
        b(upperMask) = 1;
        b(pchMask) = 0.19;
        b(socLowerMask) = 0.9;
        dayPositions(cursor) = position;
        terminalHours(cursor) = terminalHour;
        jointD(cursor) = sum(inverseTheta.*(b.^2));
        normalizedD(cursor) = jointD(cursor)/max(1,sum(b.^2));
    end
end
below = isfinite(normalizedD) & normalizedD<=degeneracyTolerance;
candidateCount = nnz(below);
if candidateCount~=1
    candidate = empty_candidate();
    candidate.stop_reason = ...
        "preemptive_joint_candidate_count_"+string(candidateCount);
    candidate.degeneracy_tolerance = degeneracyTolerance;
    candidate.candidate_count_below_tolerance = candidateCount;
    candidate.detection_method = "active_set_joint_d";
    if any(isfinite(normalizedD))
        [candidate.normalized_joint_d,location] = min(normalizedD);
        candidate.joint_d = jointD(location);
        candidate.day_position = dayPositions(location);
        candidate.day_id = partition.day(candidate.day_position).day_id;
        candidate.terminal_hour = terminalHours(location);
    end
    return
end
location = find(below,1);
position = dayPositions(location);
day = partition.day(position);
terminalHour = terminalHours(location);
hours = (1:terminalHour).';
rows = [vertcat(contract.ineq_by_day_hour{position,:}); ...
    contract.water_by_day{position}];
rows = rows(:);
localCanonical = day.canonical_reduced_indices(:);
localPrimalCanonical = localCanonical(localCanonical<=contract.nx);
[a,b,bGlobal,relationTable] = build_relation_coefficients( ...
    lin,contract,equalityMeta,inequalityMeta,rows, ...
    localPrimalCanonical,day.day_id,hours);
relationResidual = relation_residual( ...
    lin,a,bGlobal,localPrimalCanonical);
if relationResidual>relationTolerance
    candidate = empty_candidate();
    candidate.stop_reason = "preemptive_joint_relation_not_exact";
    candidate.day_position = position;
    candidate.day_id = day.day_id;
    candidate.terminal_hour = terminalHour;
    candidate.relation_residual = relationResidual;
    candidate.joint_d = jointD(location);
    candidate.normalized_joint_d = normalizedD(location);
    candidate.degeneracy_tolerance = degeneracyTolerance;
    candidate.candidate_count_below_tolerance = candidateCount;
    candidate.detection_method = "active_set_joint_d";
    return
end
candidate = struct( ...
    "used",true, ...
    "stop_reason","confirmed_preemptive_single_joint_mode", ...
    "day_position",position,"day_id",day.day_id, ...
    "relation_hours",hours,"terminal_hour",terminalHour, ...
    "equality_coefficients",a,"inequality_coefficients",b, ...
    "global_inequality_coefficients",bGlobal, ...
    "inequality_rows",rows,"relation_table",relationTable, ...
    "factor_mode",zeros(0,1),"factor_pivot_position",NaN, ...
    "factor_pivot_value",NaN,"primal_fraction",NaN, ...
    "mode_alignment",NaN,"runner_up_alignment",NaN, ...
    "relation_residual",relationResidual, ...
    "primal_fraction_tolerance",NaN, ...
    "mode_alignment_tolerance",NaN, ...
    "relation_residual_tolerance",relationTolerance, ...
    "joint_d",jointD(location), ...
    "normalized_joint_d",normalizedD(location), ...
    "degeneracy_tolerance",degeneracyTolerance, ...
    "candidate_count_below_tolerance",candidateCount, ...
    "detection_method","active_set_joint_d", ...
    "regularization_used",false,"rank_truncation_used",false, ...
    "model_changed",false);
end

function [position,value,status] = singleton_zero_pivot(retained)
D = retained.D;
n = retained.dimension;
tolerance = retained.pivot_tolerance;
zeroPositions = zeros(0,1);
zeroValues = zeros(0,1);
row = 1;
while row<=n
    if row<n && D(row+1,row)~=0
        values = eig(full(D(row:row+1,row:row+1)));
        if any(abs(values)<=tolerance)
            position = NaN;
            value = min(abs(values));
            status = "two_by_two_zero_pivot_not_supported";
            return
        end
        row = row+2;
    else
        if abs(D(row,row))<=tolerance
            zeroPositions(end+1,1) = row; %#ok<AGROW>
            zeroValues(end+1,1) = D(row,row); %#ok<AGROW>
        end
        row = row+1;
    end
end
if isempty(zeroPositions)
    position = NaN;
    value = NaN;
    status = "no_numerical_zero_pivot";
elseif numel(zeroPositions)>1
    position = NaN;
    value = NaN;
    status = "multiple_zero_pivots_not_supported";
else
    position = zeroPositions(1);
    value = zeroValues(1);
    status = "confirmed";
end
end

function mode = factor_coordinate_mode(retained,pivotPosition)
factorCoordinate = sparse(retained.dimension,1);
factorCoordinate(pivotPosition) = 1;
permutedMode = retained.L.'\factorCoordinate;
scaledMode = zeros(retained.dimension,1);
scaledMode(retained.permutation) = permutedMode;
mode = retained.scale.*scaledMode;
assert(all(isfinite(mode)) && norm(mode,2)>0, ...
    "stageB2C:jointMicroborder:FactorMode", ...
    "The retained daily factor did not produce a finite near-null mode.");
end

function [a,b,bGlobal,tableOut] = build_relation_coefficients( ...
        lin,contract,equalityMeta,inequalityMeta,rows, ...
        localPrimalCanonical,problemDayId,hours)
a = zeros(contract.neq,1);
bGlobal = sparse(contract.nineq,1);
inWindow = ismember(equalityMeta.hour,hours);
balanceMask = equalityMeta.day==problemDayId & inWindow & ...
    equalityMeta.constraint_name=="hourly_power_balance";
socMask = equalityMeta.day==problemDayId & inWindow & ...
    equalityMeta.constraint_name=="soc_dynamics";
a(equalityMeta.global_row(balanceMask)) = -1;
a(equalityMeta.global_row(socMask)) = 0.9;

upperNames = ["pw_upper_bound","ph_upper_bound","pf_upper_bound"];
upperMask = inequalityMeta.day==problemDayId & ...
    ismember(inequalityMeta.hour,hours) & ...
    ismember(inequalityMeta.constraint_name,upperNames);
pchMask = inequalityMeta.day==problemDayId & ...
    ismember(inequalityMeta.hour,hours) & ...
    inequalityMeta.constraint_name=="pch_lower_bound";
socLowerMask = inequalityMeta.day==problemDayId & ...
    inequalityMeta.hour==hours(end) & ...
    inequalityMeta.constraint_name=="soc_lower_bound";
bGlobal(inequalityMeta.global_row(upperMask)) = 1;
bGlobal(inequalityMeta.global_row(pchMask)) = 0.19;
bGlobal(inequalityMeta.global_row(socLowerMask)) = 0.9;

qbindMask = equalityMeta.day==problemDayId & ...
    equalityMeta.constraint_name=="daily_capacity_binding" & ...
    ismember(equalityMeta.asset_type, ...
        ["wind_capacity","storage_energy_capacity"]);
qbindRows = equalityMeta.global_row(qbindMask);
assert(nnz(balanceMask)==numel(hours) && ...
    nnz(socMask)==2*numel(hours) && nnz(qbindMask)==7 && ...
    nnz(pchMask)==2*numel(hours) && nnz(socLowerMask)==2, ...
    "stageB2C:jointMicroborder:RelationCardinality", ...
    "The model-derived joint relation cardinality changed for day %d.", ...
    problemDayId);

gradient = sparse(lin.A(:,localPrimalCanonical)).'*a+ ...
    sparse(lin.G(:,localPrimalCanonical)).'*bGlobal;
usedLocalColumns = zeros(numel(qbindRows),1);
for k = 1:numel(qbindRows)
    row = qbindRows(k);
    coefficients = sparse(lin.A(row,localPrimalCanonical));
    localColumn = find(coefficients,1);
    assert(nnz(coefficients)==1 && ...
        ~ismember(localColumn,usedLocalColumns(1:k-1)), ...
        "stageB2C:jointMicroborder:BindingColumn", ...
        "A target daily binding does not have one unique capacity column.");
    a(row) = -gradient(localColumn)/coefficients(localColumn);
    gradient = gradient+coefficients.'*a(row);
    usedLocalColumns(k) = localColumn;
end
b = full(bGlobal(rows));

selectedEquality = find(a);
selectedInequality = find(bGlobal);
eqTable = table(repmat("equality",numel(selectedEquality),1), ...
    equalityMeta.constraint_id(selectedEquality), ...
    equalityMeta.constraint_name(selectedEquality), ...
    equalityMeta.day(selectedEquality),equalityMeta.hour(selectedEquality), ...
    equalityMeta.asset_type(selectedEquality), ...
    equalityMeta.asset_id(selectedEquality),full(a(selectedEquality)), ...
    'VariableNames',{'constraint_type','constraint_id','constraint_name', ...
    'day','hour','asset_type','asset_id','coefficient'});
ineqTable = table(repmat("inequality",numel(selectedInequality),1), ...
    inequalityMeta.constraint_id(selectedInequality), ...
    inequalityMeta.constraint_name(selectedInequality), ...
    inequalityMeta.day(selectedInequality), ...
    inequalityMeta.hour(selectedInequality), ...
    inequalityMeta.asset_type(selectedInequality), ...
    inequalityMeta.asset_id(selectedInequality), ...
    full(bGlobal(selectedInequality)), ...
    'VariableNames',eqTable.Properties.VariableNames);
tableOut = [eqTable;ineqTable];
end

function value = relation_residual(lin,a,bGlobal,localPrimalCanonical)
selectedEquality = find(a);
selectedInequality = find(bGlobal);
aSelected = a(selectedEquality);
bSelected = full(bGlobal(selectedInequality));
aMatrix = sparse(lin.A(selectedEquality,localPrimalCanonical));
gMatrix = sparse(lin.G(selectedInequality,localPrimalCanonical));
gradient = aMatrix.'*aSelected+gMatrix.'*bSelected;
scale = max(1,norm(aMatrix,"fro")*norm(aSelected,2)+ ...
    norm(gMatrix,"fro")*norm(bSelected,2));
value = norm(gradient,2)/scale;
end

function [equalityMeta,inequalityMeta] = ...
        canonical_constraint_metadata(index,contract)
baseMeta = index.stage_a_base_index.constraint_index;
baseType = string(baseMeta.constraint_type);
equalityMeta = baseMeta(baseType=="equality",:);
baseInequality = baseMeta(baseType=="inequality",:);
waterIndex = index.water_constraint_index;
topMeta = index.constraint_index;
[waterFound,waterLocation] = ismember( ...
    string(waterIndex.constraint_id),string(topMeta.constraint_id));
assert(all(waterFound) && numel(unique(waterLocation))==height(waterIndex), ...
    "stageB2C:jointMicroborder:WaterMetadata", ...
    "The appended water-row metadata map is incomplete.");
waterMeta = topMeta(waterLocation,:);
assert(isequal(waterIndex.inequality_position, ...
    height(baseInequality)+(1:height(waterIndex)).'), ...
    "stageB2C:jointMicroborder:WaterCanonicalPosition", ...
    "Water inequalities are not the formal appended suffix.");
inequalityMeta = [baseInequality;waterMeta];
equalityMeta.global_row = (1:height(equalityMeta)).';
inequalityMeta.global_row = (1:height(inequalityMeta)).';
assert(height(equalityMeta)==contract.neq && ...
    height(inequalityMeta)==contract.nineq, ...
    "stageB2C:jointMicroborder:ConstraintMetadata", ...
    "Constraint metadata does not cover the canonical rows.");
equalityMeta.constraint_name = string(equalityMeta.constraint_name);
equalityMeta.asset_type = string(equalityMeta.asset_type);
inequalityMeta.constraint_name = string(inequalityMeta.constraint_name);
inequalityMeta.asset_type = string(inequalityMeta.asset_type);
end
