
function response = form_stage_a_multiday_day_response(dayPartition,thomas)
%FORM_STAGE_A_MULTIDAY_DAY_RESPONSE Form one side-effect-free day response.

arguments
    dayPartition (1,1) struct
    thomas (1,1) struct
end
assert(isequal(dayPartition.linearization_identity, ...
    thomas.linearization_identity), ...
    "stageAMultiday:solver:LinearizationIdentityMismatch", ...
    "Day partition and Thomas solution identities differ.");
assert(thomas.rhs_count==15,"stageAMultiday:solver:DayResponseRhsCount", ...
    "Day %d needs one physical and fourteen capacity RHS columns.", ...
    dayPartition.day_id);

a = thomas.stacked_solution(:,1);
U = thomas.stacked_solution(:,2:15);
S = dayPartition.C-dayPartition.B.'*U;
c = dayPartition.r_q_day-dayPartition.B.'*a;
beta = -dayPartition.r_binding;
gamma = c-S*beta;
symmetryRelative = norm(S-S.',"fro")/max(1,norm(S,"fro"));
assert(isequal(size(S),[14,14]) && numel(c)==14 && ...
    numel(beta)==14 && numel(gamma)==14, ...
    "stageAMultiday:solver:DayResponseDimension", ...
    "Day %d response dimensions are not 14-by-14 and 14-vectors.", ...
    dayPartition.day_id);
assert(all(isfinite(nonzeros(S))) && all(isfinite(c)) && ...
    all(isfinite(beta)) && all(isfinite(gamma)), ...
    "stageAMultiday:solver:DayResponseNonfinite", ...
    "Day %d response contains NaN or Inf.",dayPartition.day_id);

nHours = numel(dayPartition.hour);
aByHour = cell(nHours,1);
uByHour = cell(nHours,1);
for t = 1:nHours
    aByHour{t} = thomas.X_by_hour{t}(:,1);
    uByHour{t} = thomas.X_by_hour{t}(:,2:15);
end
response = struct();
if isfield(dayPartition,"stage_id")
    response.stage_id = string(dayPartition.stage_id);
else
    response.stage_id = "";
end
response.linearization_identity = dayPartition.linearization_identity;
response.day_id = dayPartition.day_id;
response.a = a;
response.U = U;
response.a_by_hour = aByHour;
response.U_by_hour = uByHour;
response.S = sparse(S);
response.c = c;
response.beta = beta;
response.gamma = gamma;
response.diagnostics = struct( ...
    "dimension",14, ...
    "rhs_count",15, ...
    "chain_dimension",size(dayPartition.M,1), ...
    "symmetry_relative",symmetryRelative, ...
    "chain_relative_residual",thomas.diagnostics.chain_relative_residual, ...
    "chain_max_absolute_residual", ...
        thomas.diagnostics.chain_max_absolute_residual, ...
    "side_effect_free",true, ...
    "c_gamma_distinct_formula",true);
end
