function partition = partition_stage_b2c_daily_joint_system(lin,reduced)
%PARTITION_STAGE_B2C_DAILY_JOINT_SYSTEM Form configured independent day blocks.
%
% The canonical reduced system is partitioned directly.  Each daily block
% contains q_day, pi_day, and all hourly primal/equality directions.  The
% only external variables are the 14 global capacity directions and the
% two duration-multiplier directions.

arguments
    lin (1,1) struct
    reduced (1,1) struct
end

contract = rkkt.solver.stage_b2b_linearization_contract(lin);
assert(isequal(reduced.linearization_identity,contract.identity), ...
    "stageB2C:dailyJoint:PartitionIdentity", ...
    "Partition and elimination must use the same linearization.");

nx = contract.nx;
globalIndices = [contract.q_global;nx+contract.y_duration];
globalMatrix = reduced.saddle(globalIndices,globalIndices);
globalRhs = reduced.rhs(globalIndices);
dayCells = cell(contract.n_days,1);

for d = 1:contract.n_days
    hourlyIndices = zeros(0,1);
    for t = 1:contract.n_hours
        hourlyIndices = [hourlyIndices; ...
            contract.x_by_day_hour{d,t}; ...
            nx+contract.y_by_day_hour{d,t}]; %#ok<AGROW>
    end
    localIndices = [contract.q_day_by_day{d}; ...
        nx+contract.y_binding_by_day{d};hourlyIndices];
    matrix = reduced.saddle(localIndices,localIndices);
    coupling = reduced.saddle(localIndices,globalIndices);
    rhs = reduced.rhs(localIndices);
    waterRows = contract.water_by_day{d};
    waterRatio = contract.l(waterRows)./contract.z(waterRows);

    dayCells{d} = struct( ...
        "day_id",contract.days(d), ...
        "linearization_identity",contract.identity, ...
        "canonical_reduced_indices",localIndices, ...
        "matrix",sparse(matrix), ...
        "coupling",sparse(coupling), ...
        "capacity_coupling",sparse(coupling(:,1:14)), ...
        "rhs",rhs, ...
        "dimension",numel(localIndices), ...
        "nnz",nnz(matrix), ...
        "q_day_local_positions",(1:14).', ...
        "pi_day_local_positions",(15:28).', ...
        "hourly_local_positions",(29:numel(localIndices)).', ...
        "hourly_dimension",numel(hourlyIndices), ...
        "rho_coupling_nnz",nnz(coupling(:,15:16)), ...
        "symmetry_relative",relative_symmetry(matrix), ...
        "water_rows",waterRows, ...
        "maximum_water_l_over_z",max(waterRatio), ...
        "minimum_water_z_over_l",min(1./waterRatio), ...
        "water_eta_dimension",0);
end

days = vertcat(dayCells{:});
expectedDimensions = lin.layout.daily_chain_dimensions+28;
if isfield(lin,"config") && isfield(lin.config,"expected_daily_joint_dimensions")
    assert(isequal(expectedDimensions, ...
        lin.config.expected_daily_joint_dimensions), ...
        "stageB2C:dailyJoint:ConfiguredDayDimensions", ...
        "Daily joint dimensions disagree with the active configuration.");
end
assert(isequal(reshape([days.dimension],1,[]),expectedDimensions) && ...
    all([days.rho_coupling_nnz]==0) && ...
    all([days.water_eta_dimension]==0), ...
    "stageB2C:dailyJoint:DayDimensions", ...
    "Daily joint dimensions or external coupling do not match the contract.");

crossDayNnz = 0;
for d = 1:contract.n_days
    for other = d+1:contract.n_days
        crossDayNnz = crossDayNnz+nnz(reduced.saddle( ...
            days(d).canonical_reduced_indices, ...
            days(other).canonical_reduced_indices));
    end
end
assert(crossDayNnz==0, ...
    "stageB2C:dailyJoint:CrossDayCoupling", ...
    "The fully eliminated reduced system contains direct cross-day coupling.");

permutation = [globalIndices;vertcat(days.canonical_reduced_indices)];
canonicalDimension = contract.nx+contract.neq;
assert(numel(permutation)==canonicalDimension && ...
    isequal(sort(permutation),(1:canonicalDimension).'), ...
    "stageB2C:dailyJoint:Permutation", ...
    "The daily-joint partition is not a canonical reduced-space bijection.");

partition = struct();
partition.stage_id = "stage_B";
partition.milestone_id = "B-2C";
partition.linearization_identity = contract.identity;
partition.contract = contract;
partition.global = struct("canonical_reduced_indices",globalIndices, ...
    "matrix",sparse(globalMatrix),"rhs",globalRhs,"dimension",16, ...
    "symmetry_relative",relative_symmetry(globalMatrix));
partition.day = days;
partition.days = contract.days;
partition.permutation = permutation;
partition.permutation_is_bijection = true;
partition.cross_day_nnz = crossDayNnz;
partition.total_daily_dimension = sum([days.dimension]);
partition.canonical_reduced_dimension = canonicalDimension;
partition.water_eta_dimension = 0;
partition.full_inequality_elimination = true;
end

function value = relative_symmetry(matrix)
value = norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro"));
end
