function recovery = recover_stage_b2c_daily_joint_direction( ...
        lin,partition,responses,core,retainedFactors,options)
%RECOVER_STAGE_B2C_DAILY_JOINT_DIRECTION Recover every canonical direction.

arguments
    lin (1,1) struct
    partition (1,1) struct
    responses (:,1) struct
    core (1,1) struct
    retainedFactors (:,1) cell
    options.ResidualTolerance (1,1) double = 1e-10
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.ResponseRecoveryMaximumPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 3
end
assert(options.ResponseRecoveryMaximumPasses<=5, ...
    "stageB2C:dailyJoint:ResponseRecoveryPassLimit", ...
    "Affine-response recovery permits at most five retained-factor corrections.");

contract = partition.contract;
assert(isequal(partition.linearization_identity,lin.identity) && ...
    isequal(core.linearization_identity,lin.identity), ...
    "stageB2C:dailyJoint:RecoveryIdentity", ...
    "Recovery inputs do not share one linearization identity.");

reducedDirection = zeros(contract.nx+contract.neq,1);
written = false(size(reducedDirection));
globalIndices = partition.global.canonical_reduced_indices;
reducedDirection(globalIndices) = core.solution;
written(globalIndices) = true;
dailySolutions = cell(contract.n_days,1);
deltaQDay = cell(contract.n_days,1);
deltaPi = cell(contract.n_days,1);
directDiagnostics = cell(contract.n_days,1);

for d = 1:contract.n_days
    day = partition.day(d);
    responsePosition = find([responses.day_id]==day.day_id,1);
    assert(~isempty(responsePosition), ...
        "stageB2C:dailyJoint:RecoveryDay", ...
        "Day %d response is missing.",day.day_id);
    retained = retainedFactors{responsePosition};
    assert(retained.day_id==day.day_id && ...
        isequal(retained.linearization_identity,lin.identity), ...
        "stageB2C:dailyJoint:RecoveryFactorIdentity", ...
        "Day %d retained factor does not match the recovery system.", ...
        day.day_id);
    response = responses(responsePosition);
    finalRhs = day.rhs-day.coupling*core.solution;
    [localDirection,directDiagnostics{d}] = ...
        recover_from_affine_response( ...
            day,response,retained,core.solution,finalRhs, ...
            options.ResidualTolerance, ...
            options.ResponseRecoveryMaximumPasses);
    directDiagnostics{d}.day_id = day.day_id;
    indices = day.canonical_reduced_indices;
    assert(~any(written(indices)), ...
        "stageB2C:dailyJoint:RecoveryOverlap", ...
        "Day %d overlaps an already recovered canonical slice.",day.day_id);
    reducedDirection(indices) = localDirection;
    written(indices) = true;
    dailySolutions{d} = localDirection;
    deltaQDay{d} = localDirection(day.q_day_local_positions);
    deltaPi{d} = localDirection(day.pi_day_local_positions);
end
assert(all(written), ...
    "stageB2C:dailyJoint:RecoveryCoverage", ...
    "Daily-joint recovery did not fill the complete reduced direction.");

deltaXi = reducedDirection(1:contract.nx);
deltaY = reducedDirection(contract.nx+1:end);
deltaL = -contract.r_ineq- ...
    rkkt.model.apply_stage_b2c_inequality_jacobian(lin,deltaXi);
deltaZ = (-contract.r_comp-contract.z.*deltaL)./contract.l;
direction = [deltaXi;deltaY;deltaL;deltaZ];
assert(all(isfinite(direction)), ...
    "stageB2C:dailyJoint:RecoveryFinite", ...
    "Recovered daily-joint direction contains NaN or Inf.");

fixed = rkkt.solver.stage_a_multiday_fixed_zero_evidence(lin.index);
dailyDirect = vertcat(directDiagnostics{:});
recovery = struct();
recovery.stage_id = "stage_B";
recovery.milestone_id = "B-2C";
recovery.linearization_identity = lin.identity;
recovery.direction = direction;
recovery.canonical_reduced_direction = reducedDirection;
recovery.components = struct("xi",deltaXi,"y",deltaY, ...
    "l",deltaL,"z",deltaZ,"q",deltaXi(contract.q_global), ...
    "rho",deltaY(contract.y_duration), ...
    "q_day_by_day",{deltaQDay},"pi_by_day",{deltaPi}, ...
    "daily_joint_by_day",{dailySolutions}, ...
    "eta_by_day",{cell(contract.n_days,1)});
recovery.daily_direct_backsolve = dailyDirect;
recovery.fixed_zero = fixed;
recovery.no_full_direction_fallback = true;
recovery.full_direction_consumed = false;
recovery.state_update_executed = false;
recovery.diagnostics = struct( ...
    "equality_recovery_residual", ...
        norm(rkkt.model.apply_stage_b2c_equality_jacobian( ...
            lin,deltaXi)+contract.r_eq,inf), ...
    "slack_recovery_residual", ...
        norm(rkkt.model.apply_stage_b2c_inequality_jacobian( ...
            lin,deltaXi)+deltaL+contract.r_ineq,inf), ...
    "complementarity_recovery_residual", ...
        norm(contract.z.*deltaL+contract.l.*deltaZ+contract.r_comp,inf), ...
    "all_daily_direct_factor_backsolve_used", ...
        all([dailyDirect.direct_final_rhs_solve]) && ...
        all([dailyDirect.retained_factor_reused]), ...
    "all_daily_affine_response_recovery_used", ...
        all([dailyDirect.affine_response_combination_used]), ...
    "daily_recovery_retained_factor_correction_count", ...
        sum([dailyDirect.corrections_applied]), ...
    "additional_factorization_count", ...
        sum([dailyDirect.additional_factorization_count]), ...
    "certified_residual_day_count", ...
        sum([dailyDirect.certified_residual_used]), ...
    "extended_residual_fallback_day_count", ...
        sum([dailyDirect.extended_residual_fallback_used]), ...
    "maximum_daily_direct_relative_residual", ...
        max([dailyDirect.maximum_column_relative_residual]), ...
    "water_eta_dimension",0,"fixed_zero_exact",fixed.all_exact_zero);
end

function [solution,diagnostics] = recover_from_affine_response( ...
        day,response,retained,coreSolution,finalRhs,residualTolerance, ...
        maximumPasses)
% The affine responses are the recursive backsolve result already formed
% from the retained daily factor.  Recombining them is the primary recovery
% route; the same factor is applied again only to correct an accurately
% reconstructed residual that misses the local gate.
timer = tic;
solution = response.a-response.U*coreSolution;
metrics = rkkt.solver.compute_certified_retained_residual_metrics( ...
    day.matrix,solution,finalRhs,residualTolerance);
initialRelative = metrics.maximum_column_relative;
initialCertifiedUpper = metrics.certified_relative_upper_bound;
relativeHistory = initialRelative;
maximumHistory = metrics.maximum_absolute;
correctionsApplied = 0;
factorApplyAttempted = false;
factorApplySeconds = 0;
extendedResidualFallbackUsed = metrics.extended_residual_fallback_used;
stopReason = "response_combination_met_target";
for pass = 1:maximumPasses
    if metrics.maximum_column_relative<=residualTolerance
        break
    end
    applyTimer = tic;
    [correction,correctionDiagnostics] = ...
        rkkt.solver.apply_stage_b2c_daily_joint_factor( ...
            retained,day.matrix,metrics.residual, ...
            "stageB2C_daily_joint_response_correction_day_"+ ...
                string(day.day_id)+"_pass_"+string(pass), ...
            ResidualTolerance=residualTolerance,RefinementPasses=0, ...
            ContinueNumericalPivotWarning=true);
    factorApplyAttempted = true;
    factorApplySeconds = factorApplySeconds+toc(applyTimer);
    assert(correctionDiagnostics.additional_factorization_count==0 && ...
        correctionDiagnostics.retained_factor_reused, ...
        "stageB2C:dailyJoint:ResponseCorrectionFactorReuse", ...
        "Day %d response correction did not reuse its retained factor.", ...
        day.day_id);
    candidate = solution+correction;
    candidateMetrics = ...
        rkkt.solver.compute_certified_retained_residual_metrics( ...
        day.matrix,candidate,finalRhs,residualTolerance);
    extendedResidualFallbackUsed = extendedResidualFallbackUsed || ...
        candidateMetrics.extended_residual_fallback_used;
    relativeHistory(end+1) = candidateMetrics.maximum_column_relative; %#ok<AGROW>
    maximumHistory(end+1) = candidateMetrics.maximum_absolute; %#ok<AGROW>
    if candidateMetrics.maximum_column_relative>= ...
            metrics.maximum_column_relative
        stopReason = "retained_factor_correction_did_not_improve";
        break
    end
    solution = candidate;
    metrics = candidateMetrics;
    correctionsApplied = pass;
    if metrics.maximum_column_relative<=residualTolerance
        stopReason = "retained_factor_correction_met_target";
        break
    end
    stopReason = "maximum_response_corrections_reached";
end
assert(metrics.maximum_column_relative<=residualTolerance, ...
    "stageB2C:dailyJoint:ResponseRecoveryResidual", ...
    "Day %d affine-response recovery residual %.17g exceeds %.17g.", ...
    day.day_id,metrics.maximum_column_relative,residualTolerance);
diagnostics = struct( ...
    "label","stageB2C_daily_joint_affine_recovery_day_"+ ...
        string(day.day_id), ...
    "rhs_count",1, ...
    "maximum_column_relative_residual", ...
        metrics.maximum_column_relative, ...
    "initial_maximum_column_relative_residual",initialRelative, ...
    "frobenius_relative_residual",metrics.frobenius_relative, ...
    "maximum_absolute_residual",metrics.maximum_absolute, ...
    "ordinary_maximum_column_relative_residual", ...
        metrics.ordinary_maximum_column_relative, ...
    "initial_certified_relative_upper_bound",initialCertifiedUpper, ...
    "certified_relative_upper_bound", ...
        metrics.certified_relative_upper_bound, ...
    "residual_validation_mode",metrics.residual_validation_mode, ...
    "certification_method",metrics.certification_method, ...
    "certified_residual_used",metrics.certified_binary64, ...
    "extended_residual_fallback_used",extendedResidualFallbackUsed, ...
    "componentwise_backward_error", ...
        metrics.componentwise_backward_error, ...
    "relative_residual_history",relativeHistory, ...
    "maximum_absolute_residual_history",maximumHistory, ...
    "warning_identifier","", "warning_message","", ...
    "warning_present",false,"warning_continued",false, ...
    "blocking_warning_present",false,"solution_finite",true, ...
    "local_residual_tolerance",residualTolerance, ...
    "local_residual_target_met",true, ...
    "refinement_enabled",maximumPasses>0, ...
    "refinement_triggered",initialRelative>residualTolerance, ...
    "refinement_maximum_passes",maximumPasses, ...
    "refinement_passes_applied",correctionsApplied, ...
    "corrections_applied",correctionsApplied, ...
    "solve_seconds",toc(timer), ...
    "factor_apply_seconds",factorApplySeconds, ...
    "additional_factorization_count",0, ...
    "retained_factor_reused",factorApplyAttempted, ...
    "retained_factor_available",true, ...
    "direct_final_rhs_solve",false, ...
    "affine_response_combination_used",true, ...
    "extended_residual_used",metrics.extended_residual_used, ...
    "stop_reason",stopReason, ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "dense_day_conversion_used",false);
end
