function recovery = recover_stage_a3_recursive_direction( ...
        lin,partition,responses,core)
%RECOVER_STAGE_A3_RECURSIVE_DIRECTION Backward-compatible A3 wrapper.
assert(string(lin.stage_id)=="stage_A3","stageA3:solver:StageId", ...
    "The stage_A3 recovery wrapper requires a stage_A3 linearization.");
recovery = rkkt.solver.recover_stage_a_multiday_recursive_direction( ...
    lin,partition,responses,core);
end
