function [solution,diagnostics] = ...
        refine_stage_b2b_augmented_day_solution( ...
        day,thomas,borderFactor,V,rhs,initialSolution,options)
%REFINE_STAGE_B2B_AUGMENTED_DAY_SOLUTION Refine the bordered daily solve.
%
% The correction equation is solved with exactly the retained hourly
% Thomas factors and the retained 8-by-8 border factor.  No new
% factorization, direct day solve, or full-KKT direction is used.

arguments
    day (1,1) struct
    thomas (1,1) struct
    borderFactor (1,1) struct
    V (:,:) double
    rhs (:,:) double
    initialSolution (:,:) double
    options.MaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.TargetRelative (1,1) double ...
        {mustBePositive,mustBeFinite} = 64*eps
    options.MinimumAttemptedPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.UseExtendedResidual (1,1) logical = false
end
assert(options.MaxPasses<=3 && size(V,2)==8 && ...
    options.MinimumAttemptedPasses<=options.MaxPasses && ...
    size(rhs,1)==size(day.M,1)+8 && ...
    isequal(size(initialSolution),size(rhs)), ...
    "stageB2B:augmentedRefinement:Contract", ...
    "The bordered-day refinement contract is invalid.");

T = sparse(day.water.T);
Dinv = sparse(day.water.Dinv);
U = T.';
operator = [day.M,U;T,-Dinv];
current = initialSolution;
metrics = residual_metrics( ...
    operator,current,rhs,options.UseExtendedResidual);
initialMetric = metrics.maximum_column_relative;
selectedPass = 0;
attemptedPasses = 0;
history = repmat(history_row(0,metrics,true),options.MaxPasses+1,1);
correctionDiagnostics = cell(options.MaxPasses,1);
if options.MaxPasses==0
    stopReason = "disabled";
elseif initialMetric<=options.TargetRelative && ...
        options.MinimumAttemptedPasses==0
    stopReason = "target_met_initial";
else
    stopReason = "maximum_passes_reached";
    nChain = size(day.M,1);
    for pass = 1:options.MaxPasses
        attemptedPasses = pass;
        correctionRhs = metrics.residual;
        [p,~,chainSolve] = rkkt.solver.apply_retained_block_thomas_once( ...
            day,thomas.factors,thomas.elimination_multipliers, ...
            correctionRhs(1:nChain,:), ...
            "stageB2B_augmented_refinement_chain_"+string(pass));
        etaRhs = T*p-correctionRhs(nChain+1:end,:);
        [etaCorrection,borderSolve] = rkkt.solver.solve_with_ldl_factor( ...
            borderFactor,etaRhs, ...
            "stageB2B_augmented_refinement_border_"+string(pass));
        correction = [p-V*etaCorrection;etaCorrection];
        candidate = current+correction;
        candidateMetrics = residual_metrics( ...
            operator,candidate,rhs,options.UseExtendedResidual);
        improved = candidateMetrics.maximum_column_relative < ...
            metrics.maximum_column_relative || ...
            (candidateMetrics.maximum_column_relative== ...
            metrics.maximum_column_relative && ...
            candidateMetrics.frobenius_relative<metrics.frobenius_relative);
        history(pass+1) = history_row(pass,candidateMetrics,improved);
        correctionDiagnostics{pass} = struct( ...
            "chain",chainSolve,"border",borderSolve, ...
            "additional_factorization_count",0);
        if ~improved
            stopReason = "residual_no_longer_decreased";
            break
        end
        current = candidate;
        metrics = candidateMetrics;
        selectedPass = pass;
        if metrics.maximum_column_relative<=options.TargetRelative && ...
                pass>=options.MinimumAttemptedPasses
            stopReason = "target_met";
            break
        end
    end
end
history = history(1:attemptedPasses+1);
solution = current;
finalMetrics = residual_metrics( ...
    operator,solution,rhs,options.UseExtendedResidual);
ordinaryResidual = rhs-operator*solution;
if initialMetric==0
    reductionRatio = 0;
else
    reductionRatio = finalMetrics.maximum_column_relative/initialMetric;
end
diagnostics = struct( ...
    "enabled",options.MaxPasses>0, ...
    "triggered",options.MaxPasses>0 && initialMetric>options.TargetRelative, ...
    "maximum_passes",options.MaxPasses, ...
    "minimum_attempted_passes",options.MinimumAttemptedPasses, ...
    "target_relative",options.TargetRelative, ...
    "passes_attempted",attemptedPasses, ...
    "correction_count",selectedPass,"selected_pass",selectedPass, ...
    "stop_reason",stopReason, ...
    "target_met",finalMetrics.maximum_column_relative<=options.TargetRelative, ...
    "initial_maximum_column_relative",initialMetric, ...
    "final_maximum_column_relative",finalMetrics.maximum_column_relative, ...
    "residual_reduction_ratio",reductionRatio,"history",history, ...
    "correction_solve",{correctionDiagnostics(1:attemptedPasses)}, ...
    "rhs_count",size(rhs,2),"additional_factorization_count",0, ...
    "residual_operator","original_augmented_day_operator", ...
    "extended_residual_used",options.UseExtendedResidual, ...
    "ordinary_frobenius_relative", ...
        norm(ordinaryResidual,"fro")/max(1,norm(rhs,"fro")), ...
    "correction_operator","retained_thomas_and_border_factors", ...
    "direct_chain_backslash_used",false, ...
    "full_kkt_direction_consumed",false);
end

function metrics = residual_metrics(operator,solution,rhs,useExtended)
if useExtended
    residual = rkkt.solver.compute_sparse_residual_double_double( ...
        operator,solution,rhs);
else
    residual = rhs-operator*solution;
end
denominator = max(ones(1,size(rhs,2)),vecnorm(rhs,2,1));
columnRelative = vecnorm(residual,2,1)./denominator;
metrics = struct("residual",residual, ...
    "column_relative",columnRelative, ...
    "maximum_column_relative",max(columnRelative), ...
    "frobenius_relative",norm(residual,"fro")/max(1,norm(rhs,"fro")), ...
    "maximum_absolute",max(abs(residual),[],"all"));
end

function value = history_row(pass,metrics,accepted)
value = struct("pass",pass, ...
    "maximum_column_relative",metrics.maximum_column_relative, ...
    "column_relative",metrics.column_relative, ...
    "frobenius_relative",metrics.frobenius_relative, ...
    "maximum_absolute",metrics.maximum_absolute,"accepted",accepted);
end
