function result = run_stage_b2c_full_ipm( ...
        data,index,config,context,options)
%RUN_STAGE_B2C_FULL_IPM Run the formal seven-day daily-joint recursive IPM.
%
% Every accepted iteration rebuilds the nonlinear water rows, their
% multiplier-weighted Lagrangian Hessian, seven fully eliminated daily
% joint systems, and the 16-dimensional core. The recursive direction is
% accepted only by its final KKT residual; a raw
% sparse full-KKT solve is performed independently once per attempted
% iteration and is consumed only by the audit.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    context (1,1) struct
    options.IterationLimit (1,1) double = NaN
end
validate_contract(config,context);
limit = config.max_iterations;
if ~isnan(options.IterationLimit)
    assert(options.IterationLimit>=1 && ...
        options.IterationLimit<=config.max_iterations && ...
        options.IterationLimit==fix(options.IterationLimit), ...
        "stageB2C:ipm:IterationLimit", ...
        "A diagnostic iteration limit must be an integer in [1,100].");
    limit = options.IterationLimit;
end
formalExecution = limit==config.max_iterations;
diagnosticsDir = fullfile(context.root,"diagnostics");
ensure_directory(diagnosticsDir);
paths = history_paths(diagnosticsDir);
assert(~any(isfile(string(struct2cell(paths)))) && ...
    ~isfile(context.checkpoint_manifest_path), ...
    "stageB2C:ipm:EvidenceExists", ...
    "A fresh B-2C IPM invocation refuses to overwrite evidence.");

manifest = jsondecode(fileread(context.run_manifest_path));
gitCommit = string(manifest.git_commit);
configSha = rkkt.data.compute_sha256_file(context.effective_config_path);
inputFingerprint = hash_text(jsonencode(manifest.input_hashes));
state = rkkt.model.initialize_stage_b2c_state(data,index,config);
linearization = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    state,data,index,config,"B-2C-FORMAL-IPM");
initialMetrics = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(linearization);
rkkt.artifacts.write_json_file(fullfile(diagnosticsDir,"initial_metrics.json"), ...
    initialMetrics);
metadata = checkpoint_metadata(0,gitCommit,configSha,inputFingerprint);
rkkt.artifacts.write_stage_b2c_checkpoint(context,state,linearization,metadata);

iterationHistory = empty_iteration_history();
residualHistory = empty_residual_history();
stepHistory = empty_step_history();
directionHistory = empty_direction_history();
waterHessianHistory = empty_water_hessian_history();
objectiveHistory = empty_objective_history(linearization);
timingHistory = empty_timing_history();
factorizationHistory = empty_factorization_history();
waterCorrectionHistory = empty_water_correction_history();
persist_histories(paths,iterationHistory,residualHistory,stepHistory, ...
    directionHistory,waterHessianHistory,objectiveHistory, ...
    timingHistory,factorizationHistory,waterCorrectionHistory);
terminalState = "MAX_ITERATIONS";
failure = struct("present",false,"iteration",0,"identifier","", ...
    "message","","evidence_path","");
previousIdentity = "";
runTimer = tic;
lastStep = struct();

for iteration = 1:limit
    checkpointCommitted = false;
    try
        step = rkkt.diagnostics.execute_stage_b2c_iteration(state,data,index,config, ...
            PreviousLinearizationIdentity=previousIdentity);
        assert_iteration_route(step,config);
        elapsed = toc(runTimer);
        convergenceCandidate = rkkt.diagnostics.stage_b2c_convergence_passed( ...
            step.metrics_after,config);
        candidateIteration = [iterationHistory; ...
            make_iteration_row(step,iteration,elapsed, ...
                convergenceCandidate,config)];
        candidateResidual = [residualHistory; ...
            make_residual_row(step,iteration)];
        candidateStep = [stepHistory;make_step_row(step,iteration)];
        candidateDirection = [directionHistory; ...
            make_direction_row(step,iteration)];
        candidateWater = [waterHessianHistory; ...
            make_water_hessian_row(step,iteration,index)];
        candidateObjective = [objectiveHistory; ...
            make_objective_row(step,iteration)];
        candidateTiming = [timingHistory; ...
            make_timing_row(step,iteration,elapsed)];
        candidateFactorization = [factorizationHistory; ...
            make_factorization_rows(step,iteration)];
        candidateWaterCorrection = [waterCorrectionHistory; ...
            make_water_correction_rows(step,iteration)];
        persist_histories(paths,candidateIteration,candidateResidual, ...
            candidateStep,candidateDirection,candidateWater, ...
            candidateObjective,candidateTiming,candidateFactorization, ...
            candidateWaterCorrection);
        metadata = checkpoint_metadata(iteration,gitCommit,configSha, ...
            inputFingerprint);
        metadata.iteration_history_sha256 = char( ...
            rkkt.data.compute_sha256_file(paths.iteration));
        metadata.direction_history_sha256 = char( ...
            rkkt.data.compute_sha256_file(paths.direction));
        metadata.water_correction_history_sha256 = char( ...
            rkkt.data.compute_sha256_file(paths.water_correction));
        rkkt.artifacts.write_stage_b2c_checkpoint(context,step.state_after, ...
            step.linearization_after,metadata);
        checkpointCommitted = true;
        iterationHistory = candidateIteration;
        residualHistory = candidateResidual;
        stepHistory = candidateStep;
        directionHistory = candidateDirection;
        waterHessianHistory = candidateWater;
        objectiveHistory = candidateObjective;
        timingHistory = candidateTiming;
        factorizationHistory = candidateFactorization;
        waterCorrectionHistory = candidateWaterCorrection;
        state = step.state_after;
        linearization = step.linearization_after;
        previousIdentity = step.linearization_before.identity;
        lastStep = step;
        rkkt.artifacts.update_running_run_manifest(context,struct( ...
            "b2c_solver_terminal_state","RUNNING", ...
            "accepted_iteration_count",iteration, ...
            "state_update_count",iteration, ...
            "convergence_achieved",convergenceCandidate, ...
            "last_state_fingerprint",char( ...
                rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint( ...
                    step.state_after)), ...
            "last_linearization_identity",char( ...
                step.linearization_after.identity), ...
            "full_kkt_role","audit_only", ...
            "recursive_direction_is_formal",true, ...
            "water_slack_second_order_correction_enabled",true, ...
            "water_slack_second_order_correction_scope_count",56, ...
            "no_full_direction_fallback",true, ...
            "full_direction_consumed_by_recursive",false));
        if convergenceCandidate
            terminalState = "CONVERGED";
            break
        end
        clear step
    catch cause
        if ~checkpointCommitted
            persist_histories(paths,iterationHistory,residualHistory, ...
                stepHistory,directionHistory,waterHessianHistory, ...
                objectiveHistory,timingHistory,factorizationHistory, ...
                waterCorrectionHistory);
        end
        terminalState = "NUMERICAL_FAILURE";
        failure = persist_failure(context,cause,iteration,state);
        break
    end
end

accepted = height(iterationHistory);
if accepted==limit && terminalState~="CONVERGED" && ...
        terminalState~="NUMERICAL_FAILURE"
    terminalState = "MAX_ITERATIONS";
end
if accepted==0
    finalMetrics = initialMetrics;
else
    finalMetrics = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(linearization);
end
executionAudit = build_execution_audit(iterationHistory, ...
    directionHistory,factorizationHistory,waterCorrectionHistory, ...
    config,accepted,formalExecution);
if terminalState~="NUMERICAL_FAILURE" && accepted>0 && ...
        ~executionAudit.all_accepted_iterations_pass
    terminalState = "NUMERICAL_FAILURE";
    cause = MException("stageB2C:ipm:ExecutionAudit", ...
        "A persisted B-2C per-iteration execution audit failed.");
    failure = persist_failure(context,cause,accepted,state);
end
rkkt.artifacts.update_running_run_manifest(context,struct( ...
    "b2c_solver_terminal_state",char(terminalState), ...
    "convergence_evaluated",true, ...
    "convergence_achieved",terminalState=="CONVERGED", ...
    "accepted_iteration_count",accepted, ...
    "state_update_count",accepted, ...
    "full_ipm_executed",formalExecution, ...
    "recursive_direction_executed",accepted>0, ...
    "recursive_direction_is_formal",true, ...
    "water_slack_second_order_correction_enabled",true, ...
    "water_slack_second_order_correction_scope_count",56, ...
    "minimum_water_slack_correction_fraction", ...
        executionAudit.minimum_water_slack_correction_fraction, ...
    "final_water_slack_correction_fraction", ...
        executionAudit.final_water_slack_correction_fraction, ...
    "centrality_limited_water_correction_iteration_count", ...
        executionAudit.centrality_limited_water_correction_iteration_count, ...
    "water_slack_second_order_correction_passed", ...
        executionAudit.water_slack_second_order_correction_pass, ...
    "maximum_water_slack_correction_closure_error", ...
        executionAudit.maximum_water_slack_correction_closure_error, ...
    "minimum_corrected_water_slack", ...
        executionAudit.minimum_corrected_water_slack, ...
    "full_kkt_role","audit_only", ...
    "no_full_direction_fallback",executionAudit.no_full_direction_fallback, ...
    "full_direction_consumed_by_recursive",false, ...
    "final_primal_equality_inf",finalMetrics.primal_equality_inf, ...
    "final_primal_inequality_inf",finalMetrics.primal_inequality_inf, ...
    "final_dual_scaled_inf",finalMetrics.dual_scaled_inf, ...
    "final_mean_lz_scaled",finalMetrics.mean_lz_scaled, ...
    "final_maximum_water_violation", ...
        finalMetrics.maximum_water_violation));

result = struct("stage_id","stage_B","milestone","B-2C", ...
    "run_id",string(context.run_id),"run_path",string(context.root), ...
    "run_terminal_state",terminalState, ...
    "convergence_achieved",terminalState=="CONVERGED", ...
    "accepted_iteration_count",accepted, ...
    "state_update_count",accepted,"iteration_limit",limit, ...
    "formal_execution",formalExecution, ...
    "initial_metrics",initialMetrics,"final_metrics",finalMetrics, ...
    "final_state",state,"final_linearization",linearization, ...
    "iteration_history",iterationHistory, ...
    "residual_history",residualHistory,"step_history",stepHistory, ...
    "direction_audit_history",directionHistory, ...
    "water_hessian_history",waterHessianHistory, ...
    "objective_history",objectiveHistory,"timing_history",timingHistory, ...
    "daily_joint_factorization_history",factorizationHistory, ...
    "water_slack_second_order_correction_history", ...
        waterCorrectionHistory, ...
    "execution_audit",executionAudit,"failure",failure, ...
    "last_step",lastStep,"solver_seconds",toc(runTimer), ...
    "full_kkt_role","audit_only", ...
    "recursive_direction_is_formal",true, ...
    "water_slack_second_order_correction_enabled",true, ...
    "no_full_direction_fallback", ...
        executionAudit.no_full_direction_fallback, ...
    "full_direction_consumed_by_recursive",false);
end

function validate_contract(config,context)
manifest = jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.stage_id)=="stage_B" && ...
    string(manifest.status)=="RUNNING" && ...
    config.milestone_id=="B-2C" && config.max_iterations==100 && ...
    config.recursive_route== ...
        "all_inequality_daily_joint_final_kkt_residual_gate" && ...
    config.recursive_refinement_max_passes==0 && ...
    config.recursive_congruence_scaling_enabled && ...
    config.equilibration_passes==0 && ...
    config.step_strategy=="independent" && ...
    config.centering_sigma==0.1 && ...
    config.fraction_to_boundary==0.9995, ...
    "stageB2C:ipm:Contract", ...
    "The formal B-2C run context or frozen algorithm contract changed.");
end

function assert_iteration_route(step,config)
responses = step.recursive.responses;
assert(numel(responses)==7 && all(arrayfun( ...
    @(x)x.rhs_count==15 && x.factor.factorization_count==1 && ...
    ~x.factor.blocking_warning_present && ...
    (~x.factor.warning_present || ...
        (x.factor.warning_continued && x.factor.inertia_zero>0)) && ...
    x.factor.solution_finite,responses)) && ...
    step.recursive.core.dimension==16 && ...
    step.recursive.core.factor.factorization_count==1 && ...
    ~step.recursive.core.factor.warning_present && ...
    step.recursive.core.factor.solution_finite && ...
    step.recursive.partition.full_inequality_elimination && ...
    step.recursive.partition.water_eta_dimension==0 && ...
    step.recursive.diagnostics.final_kkt_residual_gate_passed && ...
    step.recursive.diagnostics.candidate_kkt_relative_residual<= ...
        config.recursive_full_kkt_residual_tolerance && ...
    ~step.recursive.diagnostics.local_response_residual_is_blocking && ...
    step.direction_audit.all_pass && ...
    step.direction_audit.direction_relative_error<= ...
        config.direction_relative_error_tolerance && ...
    step.direction_audit.recursive_kkt_relative_residual<= ...
        config.recursive_full_kkt_residual_tolerance && ...
    step.direction_audit.full_kkt_relative_residual<= ...
        config.full_kkt_residual_tolerance && ...
    step.water_slack_second_order_correction_applied && ...
    step.water_slack_second_order_correction_scope_count==56 && ...
    step.only_water_slacks_corrected && ...
    step.water_slack_second_order_correction.correction_fraction>0 && ...
    step.water_slack_second_order_correction.correction_fraction<=1 && ...
    step.water_slack_second_order_correction.all_strictly_positive && ...
    step.water_residual_rebuild_closure<=max( ...
        step.water_slack_second_order_correction.audit.closure_tolerance) && ...
    step.no_full_direction_fallback && ...
    ~step.full_direction_consumed_by_recursive && ...
    ~step.factor_reused_across_iterations, ...
    "stageB2C:ipm:IterationRoute", ...
    "A B-2C iteration violated the daily-joint final-KKT audit contract.");
end

function row = make_iteration_row(step,iteration,cumulative,passed,config)
m = step.metrics_after;
d = step.recursive.diagnostics;
c = step.water_slack_second_order_correction;
row = table(iteration,true,m.objective_raw,m.objective_scaled, ...
    m.primal_equality_inf,m.primal_inequality_inf,m.dual_raw_inf, ...
    m.dual_scaled_inf,m.mean_lz_raw,m.mean_lz_scaled, ...
    step.primal_step.alpha,step.dual_step.alpha, ...
    config.centering_sigma,config.fraction_to_boundary, ...
    step.metrics_before.min_l,step.metrics_before.min_z,m.min_l,m.min_z, ...
    step.water_hessian_nnz,step.water_hessian_fro_norm, ...
    step.direction_audit.recursive_kkt_relative_residual, ...
    step.direction_audit.direction_relative_error, ...
    max(d.daily_local_maximum_relative_residuals), ...
    d.candidate_kkt_relative_residual, ...
    numel(d.near_zero_pivot_day_ids), ...
    sum(d.daily_factorization_counts)+ ...
        step.recursive.core.factor.factorization_count,true, ...
    m.maximum_water_violation,step.timing.total_seconds,cumulative, ...
    passed,passed,step.fixed_zero.count, ...
    step.fixed_zero.maximum_absolute_value, ...
    step.fixed_zero.maximum_absolute_direction, ...
    step.fixed_zero.all_exact_zero, ...
    step.uncorrected_metrics_after.primal_inequality_inf, ...
    c.maximum_absolute_remainder,c.maximum_trial_residual, ...
    c.maximum_corrected_residual,c.maximum_closure_error, ...
    c.minimum_corrected_l,step.water_residual_rebuild_closure, ...
    step.water_slack_second_order_correction_applied, ...
    step.water_slack_second_order_correction_scope_count, ...
    c.correction_fraction,c.correction_fraction_limited, ...
    c.full_correction_centrality_safe, ...
    c.full_correction_feasible, ...
    c.minimum_full_correction_candidate_l, ...
    c.minimum_corrected_to_trial_slack_ratio, ...
    string(c.limiting_constraint_id), ...
    'VariableNames',{'iteration','state_update_accepted','objective_raw', ...
    'objective_scaled','primal_equality_inf','primal_inequality_inf', ...
    'dual_raw_inf','dual_scaled_inf','mean_lz_raw','mean_lz_scaled', ...
    'alpha_primal','alpha_dual','sigma','tau','min_l_before', ...
    'min_z_before','min_l_after','min_z_after','water_hessian_nnz', ...
    'water_hessian_fro_norm','recursive_full_kkt_relative_residual', ...
    'full_kkt_direction_relative_error', ...
    'daily_local_response_maximum_relative_residual', ...
    'recursive_final_kkt_relative_residual', ...
    'daily_numerical_zero_pivot_day_count', ...
    'daily_joint_factorization_count', ...
    'full_kkt_audit_executed', ...
    'maximum_water_violation','iteration_time_seconds', ...
    'cumulative_time_seconds','convergence_candidate', ...
    'convergence_accepted','fixed_zero_count', ...
    'fixed_zero_maximum_absolute_value', ...
    'fixed_zero_maximum_absolute_direction','fixed_zero_exact', ...
    'uncorrected_primal_inequality_inf', ...
    'water_correction_maximum_absolute_remainder', ...
    'water_correction_maximum_trial_residual', ...
    'water_correction_maximum_corrected_residual', ...
    'water_correction_maximum_closure_error', ...
    'water_correction_minimum_corrected_l', ...
    'water_correction_rebuild_closure_error', ...
    'water_slack_second_order_correction_applied', ...
    'water_slack_second_order_correction_scope_count', ...
    'water_correction_fraction', ...
    'water_correction_fraction_limited', ...
    'full_water_correction_centrality_safe', ...
    'full_water_correction_feasible', ...
    'minimum_full_correction_candidate_l', ...
    'minimum_corrected_to_trial_water_slack_ratio', ...
    'water_correction_limiting_constraint_id'});
end

function row = make_residual_row(step,iteration)
b = step.metrics_before; a = step.metrics_after;
row = table(iteration,b.primal_equality_inf,a.primal_equality_inf, ...
    b.primal_inequality_inf,a.primal_inequality_inf, ...
    step.uncorrected_metrics_after.primal_inequality_inf, ...
    b.dual_scaled_inf,a.dual_scaled_inf,b.dual_raw_inf,a.dual_raw_inf, ...
    b.r_comp_scaled_inf,a.r_comp_scaled_inf, ...
    b.mean_lz_scaled,a.mean_lz_scaled,b.mean_lz_raw,a.mean_lz_raw, ...
    b.physical_inequality_violation,a.physical_inequality_violation, ...
    b.maximum_water_violation,a.maximum_water_violation, ...
    'VariableNames',{'iteration','primal_equality_before', ...
    'primal_equality_after','primal_inequality_before', ...
    'primal_inequality_after', ...
    'primal_inequality_after_before_water_correction', ...
    'dual_scaled_before','dual_scaled_after', ...
    'dual_raw_before','dual_raw_after','r_comp_scaled_before', ...
    'r_comp_scaled_after','mean_lz_scaled_before','mean_lz_scaled_after', ...
    'mean_lz_raw_before','mean_lz_raw_after', ...
    'physical_violation_before','physical_violation_after', ...
    'water_violation_before','water_violation_after'});
end

function row = make_step_row(step,iteration)
row = table(iteration,step.primal_step.alpha,step.primal_step.alpha, ...
    step.dual_step.alpha,step.dual_step.alpha, ...
    string(step.primal_step.limiting_constraint_id), ...
    string(step.dual_step.limiting_constraint_id), ...
    step.primal_step.limiting_index,step.dual_step.limiting_index, ...
    step.metrics_before.min_l,step.metrics_before.min_z, ...
    step.metrics_after.min_l,step.metrics_after.min_z, ...
    false,false,false,false,false,false,false,false, ...
    step.water_slack_second_order_correction_applied, ...
    step.water_slack_second_order_correction_scope_count, ...
    step.water_slack_second_order_correction.correction_fraction, ...
    step.water_slack_second_order_correction.correction_fraction_limited, ...
    step.water_slack_second_order_correction. ...
        full_correction_centrality_safe, ...
    step.water_slack_second_order_correction.full_correction_feasible, ...
    'VariableNames',{'iteration','candidate_alpha_primal', ...
    'applied_alpha_primal','candidate_alpha_dual','applied_alpha_dual', ...
    'primal_limiter','dual_limiter','primal_limiter_index', ...
    'dual_limiter_index','min_l_before','min_z_before', ...
    'min_l_after','min_z_after','common_step_used','dynamic_sigma_used', ...
    'predictor_corrector_used','line_search_used','regularization_used', ...
    'automatic_symmetrization_used','parallel_used', ...
    'full_kkt_direction_fallback_used', ...
    'water_slack_second_order_correction_used', ...
    'water_slack_second_order_correction_scope_count', ...
    'water_correction_fraction', ...
    'water_correction_fraction_limited', ...
    'full_water_correction_centrality_safe', ...
    'full_water_correction_feasible'});
end

function row = make_direction_row(step,iteration)
a = step.direction_audit; c = a.component_relative_errors;
delta = abs(step.recursive.direction-step.full_audit.direction);
[maximumDirection,maximumDirectionIndex] = max(delta);
recursiveResidual = step.full_audit.kkt.matrix* ...
    step.recursive.direction-step.full_audit.kkt.rhs;
[maximumRecursive,maximumRecursiveRow] = max(abs(recursiveResidual));
fullResidual = step.full_audit.kkt.matrix* ...
    step.full_audit.direction-step.full_audit.kkt.rhs;
[maximumFull,maximumFullRow] = max(abs(fullResidual));
row = table(iteration,a.direction_relative_error,c.xi,c.y,c.l,c.z, ...
    a.recursive_kkt_relative_residual,a.full_kkt_relative_residual, ...
    maximumDirection,maximumDirectionIndex, ...
    maximumRecursive,maximumRecursiveRow,maximumFull,maximumFullRow, ...
    true,true,true,false,string(a.linearization_identity), ...
    'VariableNames',{'iteration','direction_relative_error', ...
    'xi_relative_error','y_relative_error','l_relative_error', ...
    'z_relative_error','recursive_full_kkt_relative_residual', ...
    'full_kkt_relative_residual','maximum_direction_difference', ...
    'maximum_direction_index','maximum_recursive_residual', ...
    'maximum_recursive_residual_row','maximum_full_residual', ...
    'maximum_full_residual_row','no_full_direction_fallback', ...
    'full_kkt_audit_only','recursive_direction_is_formal', ...
    'full_direction_consumed_by_recursive','linearization_identity'});
end

function row = make_water_hessian_row(step,iteration,index)
rows = index.water_constraint_index.inequality_position;
upper = string(index.water_constraint_index.bound_type)=="upper";
z = step.state_before.z(rows);
row = table(iteration,step.state_before.state_revision, ...
    step.water_hessian_nnz,step.water_hessian_fro_norm, ...
    step.water_hessian_symmetry_relative,min(z(upper)),max(z(upper)), ...
    min(z(~upper)),max(z(~upper)), ...
    string(step.linearization_before.identity), ...
    'VariableNames',{'iteration','state_revision_before','nnz', ...
    'frobenius_norm','symmetry_relative','upper_z_min','upper_z_max', ...
    'lower_z_min','lower_z_max','linearization_identity'});
end

function row = make_objective_row(step,iteration)
q = step.state_after.xi(step.linearization_after.maps.q_global);
names = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName( ...
    cellstr(step.linearization_after.capacity_parameters.names(:))));
value = struct("iteration",iteration, ...
    "objective_raw",step.metrics_after.objective_raw, ...
    "objective_scaled",step.metrics_after.objective_scaled, ...
    "objective_scale_factor",step.metrics_after.objective_scale_factor);
for k = 1:14
    value.(names{k}) = q(k);
end
row = struct2table(value,"AsArray",true);
end

function row = make_timing_row(step,iteration,cumulative)
t = step.timing;
row = table(iteration,t.linearization_before_seconds,t.recursive_seconds, ...
    t.full_kkt_audit_seconds,t.step_and_state_update_seconds, ...
    t.linearization_after_seconds,t.total_seconds,cumulative, ...
    'VariableNames',{'iteration','linearization_before_seconds', ...
    'recursive_seconds','full_kkt_audit_seconds', ...
    'state_update_seconds','linearization_after_seconds', ...
    'total_seconds','cumulative_seconds'});
end

function rows = make_factorization_rows(step,iteration)
rows = empty_factorization_history();
for d = 1:7
    response = step.recursive.responses(d);
    factor = response.factor;
    rows = [rows;factorization_row(iteration,response.day_id, ...
        "daily_joint",factor,true)]; %#ok<AGROW>
end
rows = [rows;factorization_row(iteration,NaN,"global_core_16", ...
    step.recursive.core.factor,true)];
end

function row = factorization_row(iteration,dayId,objectType,factor, ...
        finalKktGateApplies)
empty = empty_factorization_history();
row = table(iteration,dayId,string(objectType),factor.dimension, ...
    factor.rhs_count,factor.factorization_count, ...
    factor.minimum_absolute_pivot_eigenvalue,factor.pivot_tolerance, ...
    factor.inertia_zero,factor.maximum_column_relative_residual, ...
    factor.local_residual_target_met,factor.warning_identifier, ...
    factor.warning_present,factor.warning_continued, ...
    factor.blocking_warning_present, ...
    factor.solution_finite,logical(finalKktGateApplies),false, ...
    'VariableNames',empty.Properties.VariableNames);
end

function rows = make_water_correction_rows(step,iteration)
rows = step.water_slack_second_order_correction.audit;
rows = addvars(rows,repmat(iteration,height(rows),1), ...
    'Before',1,'NewVariableNames','iteration');
end

function audit = build_execution_audit(iterations,directions,factorization, ...
        waterCorrection,config,accepted,formalExecution)
if accepted==0
    directionPass=false; positivity=false; noFallback=false;
    correctionPass=false; maximumCorrectionClosure=NaN;
    minimumCorrectedWaterSlack=NaN; minimumCorrectionFraction=NaN;
    finalCorrectionFraction=NaN; limitedCorrectionCount=0;
    fullCorrectionCount=0;
else
    directionPass = all(directions.direction_relative_error<=1e-10) && ...
        all(directions.xi_relative_error<=1e-10) && ...
        all(directions.y_relative_error<=1e-10) && ...
        all(directions.l_relative_error<=1e-10) && ...
        all(directions.z_relative_error<=1e-10) && ...
        all(directions.recursive_full_kkt_relative_residual<=1e-10) && ...
        all(directions.full_kkt_relative_residual<=1e-10);
    positivity=all(iterations.min_l_after>0) && ...
        all(iterations.min_z_after>0);
    noFallback=all(directions.no_full_direction_fallback) && ...
        ~any(directions.full_direction_consumed_by_recursive);
    correctionMechanicsPass = height(waterCorrection)==56*accepted && ...
        isequal(waterCorrection.iteration, ...
            repelem((1:accepted).',56,1)) && ...
        all(waterCorrection.correction_fraction>0) && ...
        all(waterCorrection.correction_fraction<=1) && ...
        all((waterCorrection.correction_fraction==1)== ...
            waterCorrection.full_correction_centrality_safe) && ...
        all(waterCorrection.strictly_positive) && ...
        all(waterCorrection.l_corrected>= ...
            config.centering_sigma*waterCorrection.l_trial) && ...
        all(abs(waterCorrection.closure_error)<= ...
            waterCorrection.closure_tolerance) && ...
        all(iterations.water_slack_second_order_correction_applied) && ...
        all(iterations.water_slack_second_order_correction_scope_count==56);
    maximumCorrectionClosure = max(abs(waterCorrection.closure_error));
    minimumCorrectedWaterSlack = min(waterCorrection.l_corrected);
    minimumCorrectionFraction = min(iterations.water_correction_fraction);
    finalCorrectionFraction = iterations.water_correction_fraction(end);
    limitedCorrectionCount = sum( ...
        iterations.water_correction_fraction_limited);
    fullCorrectionCount = sum(iterations.water_correction_fraction==1);
    correctionPass = correctionMechanicsPass && ...
        (~formalExecution || finalCorrectionFraction==1);
end
% The persisted step table is the execution source of truth for forbidden
% factors; iteration rows intentionally remain limited to the user contract.
forbidden = config.step_strategy=="independent" && ...
    ~config.common_step_enabled && ~config.dynamic_sigma_enabled && ...
    ~config.predictor_corrector_enabled && ~config.line_search_enabled && ...
    ~config.regularization_enabled && ...
    ~config.automatic_symmetrization_enabled && ...
    ~config.parallel_enabled && ...
    ~config.full_kkt_direction_fallback_enabled;
factorizationPass = height(factorization)==8*accepted && ...
    all(factorization.factorization_count==1) && ...
    ~any(factorization.blocking_warning_present) && ...
    all(~factorization.warning_present | factorization.warning_continued) && ...
    all(factorization.solution_finite) && ...
    all(factorization.final_kkt_gate_applies) && ...
    ~any(factorization.full_kkt_direction_consumed);
audit = struct("accepted_iteration_count",accepted, ...
    "formal_execution",formalExecution, ...
    "one_full_kkt_audit_per_accepted_iteration", ...
        height(directions)==accepted, ...
    "direction_audits_pass",directionPass, ...
    "strict_positivity_pass",positivity, ...
    "no_full_direction_fallback",noFallback, ...
    "forbidden_execution_pass",forbidden, ...
    "daily_joint_factorization_pass",factorizationPass, ...
    "water_slack_second_order_correction_pass",correctionPass, ...
    "maximum_water_slack_correction_closure_error", ...
        maximumCorrectionClosure, ...
    "minimum_corrected_water_slack",minimumCorrectedWaterSlack, ...
    "minimum_water_slack_correction_fraction",minimumCorrectionFraction, ...
    "final_water_slack_correction_fraction",finalCorrectionFraction, ...
    "centrality_limited_water_correction_iteration_count", ...
        limitedCorrectionCount, ...
    "full_water_correction_iteration_count",fullCorrectionCount, ...
    "final_full_water_correction_pass",finalCorrectionFraction==1, ...
    "all_accepted_iterations_pass",accepted>0 && ...
        height(directions)==accepted && directionPass && positivity && ...
        noFallback && forbidden && factorizationPass && correctionPass);
end

function metadata = checkpoint_metadata(iteration,commit,configSha,inputHash)
metadata = struct("iteration",iteration,"git_commit",char(commit), ...
    "config_sha256",char(configSha), ...
    "input_hash_fingerprint",char(inputHash), ...
    "recursive_route", ...
        "all_inequality_daily_joint_final_kkt_residual_gate", ...
    "recursive_refinement_max_passes",0, ...
    "equilibration_passes",0,"full_kkt_role","audit_only", ...
    "water_slack_second_order_correction_enabled",true, ...
    "water_slack_second_order_correction_scope_count",56, ...
    "water_slack_second_order_correction_formula", ...
        "l_corrected=l_trial-beta*(g_after-g_before-alpha*G*dx)", ...
    "water_correction_fraction_rule", ...
        "beta=1_if_l_exact_ge_sigma_l_trial_else_tau_times_centrality_boundary", ...
    "no_full_direction_fallback",true, ...
    "full_direction_consumed_by_recursive",false);
end

function failure = persist_failure(context,cause,iteration,state)
failure = struct("present",true,"iteration",iteration, ...
    "identifier",string(cause.identifier),"message",string(cause.message), ...
    "report",string(getReport(cause,"extended","hyperlinks","off")), ...
    "state_revision",state.state_revision, ...
    "state_fingerprint",rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(state), ...
    "evidence_path","checkpoints/failure_iteration_"+ ...
        compose("%03d",iteration)+".mat");
pathValue = fullfile(context.root,failure.evidence_path);
if ~isfile(pathValue)
    rkkt.artifacts.save_mat_artifact(pathValue,"failure",failure, ...
        "state_before_failure",state);
end
end

function persist_histories(paths,varargin)
names = string(fieldnames(paths));
assert(numel(names)==numel(varargin));
for k = 1:numel(names)
    rkkt.artifacts.write_table_csv_17g_atomic(paths.(names(k)),varargin{k});
end
end

function value = history_paths(root)
value = struct("iteration",fullfile(root,"iteration_history.csv"), ...
    "residual",fullfile(root,"residual_history.csv"), ...
    "step",fullfile(root,"step_history.csv"), ...
    "direction",fullfile(root,"direction_audit_history.csv"), ...
    "water_hessian",fullfile(root,"water_hessian_history.csv"), ...
    "objective",fullfile(root,"objective_history.csv"), ...
    "timing",fullfile(root,"timing_history.csv"), ...
    "factorization",fullfile(root, ...
        "daily_joint_factorization_history.csv"), ...
    "water_correction",fullfile(root, ...
        "water_slack_second_order_correction_history.csv"));
end

function value = empty_iteration_history()
value = make_empty(@()make_iteration_row(empty_step(),0,0,false, ...
    empty_config()));
end
function value = empty_residual_history()
value = make_empty(@()make_residual_row(empty_step(),0));
end
function value = empty_step_history()
value = make_empty(@()make_step_row(empty_step(),0));
end
function value = empty_direction_history()
value = table(zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    true(0,1),true(0,1),true(0,1),false(0,1),strings(0,1), ...
    'VariableNames',{'iteration','direction_relative_error', ...
    'xi_relative_error','y_relative_error','l_relative_error', ...
    'z_relative_error','recursive_full_kkt_relative_residual', ...
    'full_kkt_relative_residual','maximum_direction_difference', ...
    'maximum_direction_index','maximum_recursive_residual', ...
    'maximum_recursive_residual_row','maximum_full_residual', ...
    'maximum_full_residual_row','no_full_direction_fallback', ...
    'full_kkt_audit_only','recursive_direction_is_formal', ...
    'full_direction_consumed_by_recursive','linearization_identity'});
end
function value = empty_water_hessian_history()
value = table(zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),strings(0,1), ...
    'VariableNames',{'iteration','state_revision_before','nnz', ...
    'frobenius_norm','symmetry_relative','upper_z_min','upper_z_max', ...
    'lower_z_min','lower_z_max','linearization_identity'});
end
function value = empty_objective_history(linearization)
state = struct("xi",zeros(size(linearization.state.xi)));
step = struct("state_after",state, ...
    "linearization_after",linearization, ...
    "metrics_after",struct("objective_raw",0,"objective_scaled",0, ...
        "objective_scale_factor",linearization.objective_scale.factor));
value = make_objective_row(step,0); value = value([],:);
end
function value = empty_timing_history()
value = make_empty(@()make_timing_row(empty_step(),0,0));
end
function value = empty_factorization_history()
value = table(zeros(0,1),zeros(0,1),strings(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),false(0,1),strings(0,1),false(0,1),false(0,1), ...
    false(0,1),false(0,1),false(0,1),false(0,1), ...
    'VariableNames',{'iteration','day_id','object_type','dimension', ...
    'rhs_count','factorization_count','minimum_absolute_pivot', ...
    'pivot_tolerance','numerical_zero_pivot_count', ...
    'maximum_rhs_relative_residual','local_residual_target_met', ...
    'warning_identifier','warning_present','warning_continued', ...
    'blocking_warning_present','solution_finite', ...
    'final_kkt_gate_applies','full_kkt_direction_consumed'});
end
function value = empty_water_correction_history()
value = table(zeros(0,1),strings(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),false(0,1),false(0,1),zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    'VariableNames',{'iteration','constraint_id','day','hydro_id', ...
    'bound_type','inequality_position','g_before','g_after','l_before', ...
    'l_trial','full_correction_candidate_l','l_corrected', ...
    'linearized_constraint_increment','second_order_remainder', ...
    'applied_second_order_correction','correction_fraction', ...
    'full_correction_centrality_safe','full_correction_feasible', ...
    'residual_before','residual_trial', ...
    'residual_corrected','expected_corrected_residual','closure_error', ...
    'closure_tolerance','strictly_positive'});
end

function value = make_empty(factory)
value = factory(); value = value([],:);
end

function step = empty_step()
m = struct("objective_raw",0,"objective_scaled",0, ...
    "primal_equality_inf",0,"primal_inequality_inf",0, ...
    "dual_raw_inf",0,"dual_scaled_inf",0,"r_comp_scaled_inf",0, ...
    "mean_lz_raw",0,"mean_lz_scaled",0, ...
    "physical_inequality_violation",0,"maximum_water_violation",0, ...
    "min_l",0,"min_z",0,"objective_scale_factor",1);
limiter = struct("alpha",0,"limiting_constraint_id","", ...
    "limiting_index",0);
audit = struct("direction_relative_error",0, ...
    "component_relative_errors",struct("xi",0,"y",0,"l",0,"z",0), ...
    "recursive_kkt_relative_residual",0,"full_kkt_relative_residual",0, ...
    "maximum_direction_difference",struct("absolute_value",0, ...
        "canonical_index",0), ...
    "maximum_recursive_residual",struct("absolute_value",0,"row",0), ...
    "maximum_full_residual",struct("absolute_value",0,"row",0), ...
    "linearization_identity","");
step = struct("metrics_before",m,"metrics_after",m, ...
    "uncorrected_metrics_after",struct("primal_inequality_inf",0), ...
    "primal_step",limiter,"dual_step",limiter, ...
    "water_hessian_nnz",0,"water_hessian_fro_norm",0, ...
    "direction_audit",audit, ...
    "recursive",struct("diagnostics",struct( ...
        "daily_local_maximum_relative_residuals",zeros(1,7), ...
        "candidate_kkt_relative_residual",0, ...
        "near_zero_pivot_day_ids",zeros(1,0), ...
        "daily_factorization_counts",ones(1,7)), ...
        "core",struct("factor",struct("factorization_count",1))), ...
    "fixed_zero",struct("count",0,"maximum_absolute_value",0, ...
        "maximum_absolute_direction",0,"all_exact_zero",true), ...
    "water_slack_second_order_correction",struct( ...
        "maximum_absolute_remainder",0,"maximum_trial_residual",0, ...
        "maximum_corrected_residual",0,"maximum_closure_error",0, ...
        "minimum_corrected_l",0,"correction_fraction",1, ...
        "correction_fraction_limited",false, ...
        "full_correction_centrality_safe",true, ...
        "full_correction_feasible",true, ...
        "minimum_full_correction_candidate_l",0, ...
        "minimum_corrected_to_trial_slack_ratio",1, ...
        "limiting_constraint_id",""), ...
    "water_residual_rebuild_closure",0, ...
    "water_slack_second_order_correction_applied",true, ...
    "water_slack_second_order_correction_scope_count",56, ...
    "timing",struct("linearization_before_seconds",0, ...
        "recursive_seconds",0,"full_kkt_audit_seconds",0, ...
        "step_and_state_update_seconds",0, ...
        "linearization_after_seconds",0,"total_seconds",0));
end

function value = empty_config()
value = struct("centering_sigma",0.1,"fraction_to_boundary",0.9995);
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message] = mkdir(pathValue);
assert(created,"stageB2C:ipm:Directory","%s",message);
end

function digest = hash_text(value)
bytes = unicode2native(char(string(value)),"UTF-8");
md = java.security.MessageDigest.getInstance("SHA-256");
md.update(typecast(uint8(bytes(:)),"int8"));
digestBytes = mod(double(md.digest()),256);
digest = lower(join(compose("%02x",digestBytes),""));
end
