function result = run_stage_b2c_30day_ipm(data,index,config,context,options)
%RUN_STAGE_B2C_30DAY_IPM Run a recursive-only contiguous-range B-2C IPM.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    context (1,1) struct
    options.MaxIterations (1,1) double {mustBeInteger,mustBePositive} = 100
end

assert(ismember(config.time_scope_type,["experimental_30_day_scope", ...
    "configured_contiguous_day_scope"]) && ...
    ~isempty(config.days) && isequal(config.days, ...
        config.days(1):config.days(end)) && ...
    ~config.full_kkt_audit_enabled && ...
    ~config.full_kkt_enabled && ~config.full_kkt_solve_enabled, ...
    "stageB2C:recursive:Contract", ...
    "The recursive runner requires a contiguous recursive-only profile.");
limit = min(options.MaxIterations,config.max_iterations);
diagnosticsDir = fullfile(context.root,"diagnostics");
ensure_directory(diagnosticsDir);
paths = history_paths(diagnosticsDir);

manifest = jsondecode(fileread(context.run_manifest_path));
gitCommit = string(manifest.git_commit);
configSha = rkkt.data.compute_sha256_file(context.effective_config_path);
inputFingerprint = hash_text(jsonencode(manifest.input_hashes));

state = rkkt.model.initialize_stage_b2c_state(data,index,config);
linearization = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    state,data,index,config,"B-2C-FORMAL-IPM");
linearizationTemplate = rkkt.model.build_stage_b2c_linearization_template( ...
    linearization,data,index,config);
initialMetrics = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(linearization);
rkkt.artifacts.write_json_file(fullfile(diagnosticsDir,"initial_metrics.json"), ...
    initialMetrics);
rkkt.artifacts.write_stage_b2c_checkpoint(context,state,linearization, ...
    checkpoint_metadata(0,gitCommit,configSha,inputFingerprint,config));

iterationHistory = empty_iteration_history();
timingHistory = empty_timing_history();
factorizationHistory = empty_factorization_history();
waterCorrectionHistory = empty_water_correction_history();
persist_histories(paths,iterationHistory,timingHistory, ...
    factorizationHistory,waterCorrectionHistory);

terminalState = "ITERATION_LIMIT_REACHED";
previousIdentity = "";
lastDirection = struct();
lastCore = struct();
lastRecursiveDiagnostics = struct();
runTimer = tic;

for iteration = 1:limit
    step = rkkt.diagnostics.execute_stage_b2c_iteration( ...
        state,data,index,config, ...
        PreviousLinearizationIdentity=previousIdentity, ...
        FullKktAuditEnabled=false, ...
        PrecomputedLinearization=linearization, ...
        LinearizationTemplate=linearizationTemplate, ...
        LinearizationUpdateMode="cached_numeric");
    assert_iteration_route(step,config);
    cumulative = toc(runTimer);
    converged = rkkt.diagnostics.stage_b2c_convergence_passed( ...
        step.metrics_after,config);

    iterationHistory = [iterationHistory; ...
        make_iteration_row(step,iteration,cumulative,converged)]; %#ok<AGROW>
    timingHistory = [timingHistory; ...
        make_timing_row(step,iteration,cumulative)]; %#ok<AGROW>
    factorizationHistory = [factorizationHistory; ...
        make_factorization_rows(step,iteration)]; %#ok<AGROW>
    waterCorrectionHistory = [waterCorrectionHistory; ...
        make_water_correction_rows(step,iteration)]; %#ok<AGROW>
    persist_histories(paths,iterationHistory,timingHistory, ...
        factorizationHistory,waterCorrectionHistory);

    metadata = checkpoint_metadata(iteration,gitCommit,configSha, ...
        inputFingerprint,config);
    metadata.iteration_history_sha256 = char( ...
        rkkt.data.compute_sha256_file(paths.iteration));
    rkkt.artifacts.write_stage_b2c_checkpoint(context,step.state_after, ...
        step.linearization_after,metadata);

    state = step.state_after;
    linearization = step.linearization_after;
    previousIdentity = step.linearization_before.identity;
    lastDirection = step.recursive.components;
    lastCore = step.recursive.core;
    lastRecursiveDiagnostics = step.recursive.diagnostics;
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "b2c_recursive_solver_terminal_state","RUNNING", ...
        "accepted_iteration_count",iteration, ...
        "state_update_count",iteration, ...
        "convergence_achieved",converged, ...
        "full_kkt_audit_executed",false, ...
        "full_kkt_assembled",false,"full_kkt_solved",false, ...
        "recursive_final_kkt_relative_residual", ...
            step.recursive.diagnostics.candidate_kkt_relative_residual, ...
        "last_linearization_identity",char(linearization.identity)));
    clear step
    if converged
        terminalState = "CONVERGED";
        break
    end
end

finalMetrics = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(linearization);
result = struct("final_state",state,"final_linearization",linearization, ...
    "final_metrics",finalMetrics,"last_direction",lastDirection, ...
    "last_core",lastCore, ...
    "last_recursive_diagnostics",lastRecursiveDiagnostics, ...
    "iteration_history",iterationHistory,"timing_history",timingHistory, ...
    "factorization_history",factorizationHistory, ...
    "water_correction_history",waterCorrectionHistory, ...
    "accepted_iteration_count",height(iterationHistory), ...
    "convergence_achieved",terminalState=="CONVERGED", ...
    "run_terminal_state",terminalState, ...
    "elapsed_seconds",toc(runTimer), ...
    "full_kkt_audit_executed",false, ...
    "full_kkt_assembled",false,"full_kkt_solved",false);
end

function assert_iteration_route(step,config)
responses = step.recursive.responses;
adaptiveDelayed = step.recursive.diagnostics. ...
    adaptive_delayed_inequality_elimination_used;
jointMicroborder = step.recursive.diagnostics.joint_microborder_used;
dailyRecoveryPass = ...
    step.recursive.diagnostics.daily_direct_factor_backsolve_used || ...
    step.recursive.diagnostics.daily_affine_response_recovery_used || ...
    adaptiveDelayed;
retainedDailyPass = step.recursive.core.direct_daily_correction. ...
    retained_daily_factors_reused || adaptiveDelayed;
rhsPass = arrayfun(@(value)value.rhs_count==config.expected_rhs_per_day || ...
    (jointMicroborder && value.day_id== ...
        step.recursive.diagnostics.joint_microborder_day_ids && ...
        value.rhs_count==config.expected_rhs_per_day+1),responses);
factorsPass = numel(responses)==numel(config.days) && all(rhsPass) && ...
    all(arrayfun(@(value) ...
        value.factor.factorization_count==1 && ...
        value.factor.refinement_additional_factorization_count==0 && ...
        ~value.factor.blocking_warning_present && ...
        (~value.factor.warning_present || ...
            (value.factor.warning_continued && value.factor.inertia_zero>0)) && ...
        value.factor.solution_finite,responses));
assert(factorsPass && ismember(step.recursive.core.dimension,[16,17]) && ...
    (step.recursive.core.dimension==17)==jointMicroborder && ...
    (~jointMicroborder || step.high_low_state_update_used) && ...
    step.recursive.core.factor.factorization_count==1 && ...
    step.recursive.core.factor.refinement_additional_factorization_count==0 && ...
    ~step.recursive.core.factor.warning_present && ...
    step.recursive.core.factor.solution_finite && ...
    step.recursive.partition.full_inequality_elimination && ...
    step.recursive.partition.cross_day_nnz==0 && ...
    step.recursive.diagnostics.final_kkt_residual_gate_passed && ...
    step.recursive.diagnostics.candidate_kkt_relative_residual<= ...
        config.recursive_full_kkt_residual_tolerance && ...
    dailyRecoveryPass && ...
    step.recursive.diagnostics. ...
        daily_recovery_additional_factorization_count==0 && ...
    step.recursive.core.direct_daily_correction. ...
        daily_additional_factorization_count==0 && ...
    step.recursive.core.direct_daily_correction. ...
        core_additional_factorization_count==0 && ...
    retainedDailyPass && ...
    step.recursive.core.direct_daily_correction. ...
        retained_core_factor_reused && ...
    ~step.full_kkt_audit_executed && ~step.direction_audit.executed && ...
    step.water_slack_second_order_correction_scope_count== ...
        config.expected_water_inequality_count && ...
    step.water_slack_second_order_correction.all_strictly_positive && ...
    step.fixed_zero.count==config.expected_stage_a_fixed_zero_count && ...
    step.fixed_zero.all_exact_zero && step.no_full_direction_fallback && ...
    ~step.full_direction_consumed_by_recursive, ...
    "stageB2C:recursive:IterationRoute", ...
    "A configured recursive iteration violated its route.");
end

function row = make_iteration_row(step,iteration,cumulative,converged)
m = step.metrics_after;
d = step.recursive.diagnostics;
c = step.water_slack_second_order_correction;
row = table(iteration,m.objective_raw,m.objective_scaled, ...
    m.primal_equality_inf,m.primal_inequality_inf,m.dual_scaled_inf, ...
    m.mean_lz_scaled,step.primal_step.alpha,step.dual_step.alpha, ...
    m.min_l,m.min_z,d.candidate_kkt_relative_residual, ...
    max(d.daily_local_maximum_relative_residuals), ...
    numel(d.near_zero_pivot_day_ids), ...
    string(strjoin(string(d.near_zero_pivot_day_ids),"|")), ...
    sum(d.daily_factorization_counts)+ ...
        step.recursive.core.factor.factorization_count, ...
    false,m.maximum_water_violation,c.correction_fraction, ...
    c.correction_fraction_limited,c.minimum_corrected_l, ...
    step.fixed_zero.count,step.fixed_zero.maximum_absolute_value, ...
    step.fixed_zero.maximum_absolute_direction, ...
    step.fixed_zero.all_exact_zero,step.timing.total_seconds,cumulative, ...
    converged, ...
    'VariableNames',{'iteration','objective_raw','objective_scaled', ...
    'primal_equality_inf','primal_inequality_inf','dual_scaled_inf', ...
    'mean_lz_scaled','alpha_primal','alpha_dual','minimum_l','minimum_z', ...
    'recursive_final_kkt_relative_residual', ...
    'daily_local_response_maximum_relative_residual', ...
    'daily_numerical_zero_pivot_day_count', ...
    'daily_numerical_zero_pivot_day_ids','factorization_count', ...
    'full_kkt_audit_executed','maximum_water_violation', ...
    'water_correction_fraction','water_correction_fraction_limited', ...
    'minimum_corrected_water_slack','fixed_zero_count', ...
    'fixed_zero_maximum_absolute_value', ...
    'fixed_zero_maximum_absolute_direction','fixed_zero_exact', ...
    'iteration_time_seconds','cumulative_time_seconds','converged'});
end

function row = make_timing_row(step,iteration,cumulative)
t = step.timing;
row = table(iteration,t.linearization_before_seconds,t.recursive_seconds, ...
    t.full_kkt_audit_seconds,t.step_and_state_update_seconds, ...
    t.linearization_after_seconds,t.total_seconds,cumulative, ...
    'VariableNames',{'iteration','linearization_before_seconds', ...
    'recursive_seconds','full_kkt_audit_seconds','state_update_seconds', ...
    'linearization_after_seconds','total_seconds','cumulative_seconds'});
end

function rows = make_factorization_rows(step,iteration)
n = numel(step.recursive.responses);
rows = empty_factorization_history();
for position = 1:n
    response = step.recursive.responses(position);
    rows = [rows;factorization_row(iteration,response.day_id, ...
        "daily_joint",response.factor)]; %#ok<AGROW>
end
coreFactor = step.recursive.core.factor;
coreObjectType = "global_core_16";
if isfield(coreFactor,"object_type")
    coreObjectType = string(coreFactor.object_type);
end
rows = [rows;factorization_row(iteration,NaN,coreObjectType,coreFactor)];
end

function row = factorization_row(iteration,dayId,objectType,factor)
empty = empty_factorization_history();
row = table(iteration,dayId,string(objectType),factor.dimension, ...
    factor.rhs_count,factor.factorization_count, ...
    factor.minimum_absolute_pivot_eigenvalue,factor.pivot_tolerance, ...
    factor.inertia_zero,factor.maximum_column_relative_residual, ...
    factor.initial_maximum_column_relative_residual, ...
    factor.refinement_enabled,factor.refinement_triggered, ...
    factor.refinement_maximum_passes,factor.refinement_passes_applied, ...
    factor.refinement_additional_factorization_count, ...
    factor.warning_present,factor.warning_continued, ...
    factor.blocking_warning_present,factor.solution_finite, ...
    'VariableNames',empty.Properties.VariableNames);
end

function rows = make_water_correction_rows(step,iteration)
rows = step.water_slack_second_order_correction.audit;
rows = addvars(rows,repmat(iteration,height(rows),1), ...
    'Before',1,'NewVariableNames','iteration');
end

function value = empty_iteration_history()
value = table(zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),strings(0,1),zeros(0,1), ...
    false(0,1),zeros(0,1),zeros(0,1),false(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    zeros(0,1),zeros(0,1),false(0,1), ...
    'VariableNames',{'iteration','objective_raw','objective_scaled', ...
    'primal_equality_inf','primal_inequality_inf','dual_scaled_inf', ...
    'mean_lz_scaled','alpha_primal','alpha_dual','minimum_l','minimum_z', ...
    'recursive_final_kkt_relative_residual', ...
    'daily_local_response_maximum_relative_residual', ...
    'daily_numerical_zero_pivot_day_count', ...
    'daily_numerical_zero_pivot_day_ids','factorization_count', ...
    'full_kkt_audit_executed','maximum_water_violation', ...
    'water_correction_fraction','water_correction_fraction_limited', ...
    'minimum_corrected_water_slack','fixed_zero_count', ...
    'fixed_zero_maximum_absolute_value', ...
    'fixed_zero_maximum_absolute_direction','fixed_zero_exact', ...
    'iteration_time_seconds','cumulative_time_seconds','converged'});
end

function value = empty_timing_history()
value = table(zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    'VariableNames',{'iteration','linearization_before_seconds', ...
    'recursive_seconds','full_kkt_audit_seconds','state_update_seconds', ...
    'linearization_after_seconds','total_seconds','cumulative_seconds'});
end

function value = empty_factorization_history()
names = {'iteration','day_id','object_type','dimension', ...
    'rhs_count','factorization_count','minimum_absolute_pivot', ...
    'pivot_tolerance','numerical_zero_pivot_count', ...
    'maximum_rhs_relative_residual', ...
    'initial_maximum_rhs_relative_residual','refinement_enabled', ...
    'refinement_triggered','refinement_maximum_passes', ...
    'refinement_passes_applied', ...
    'refinement_additional_factorization_count','warning_present', ...
    'warning_continued','blocking_warning_present','solution_finite'};
types = ["double","double","string",repmat("double",1,8), ...
    "logical","logical",repmat("double",1,3), ...
    repmat("logical",1,4)];
value = table('Size',[0,numel(names)], ...
    'VariableTypes',cellstr(types),'VariableNames',names);
end

function value = empty_water_correction_history()
value = table(zeros(0,1),strings(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),false(0,1),false(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    'VariableNames',{'iteration','constraint_id','day','hydro_id', ...
    'bound_type','inequality_position','g_before','g_after','l_before', ...
    'l_trial','full_correction_candidate_l','l_corrected', ...
    'linearized_constraint_increment','second_order_remainder', ...
    'applied_second_order_correction','correction_fraction', ...
    'full_correction_centrality_safe','full_correction_feasible', ...
    'residual_before','residual_trial','residual_corrected', ...
    'expected_corrected_residual','closure_error','closure_tolerance', ...
    'strictly_positive'});
end

function paths = history_paths(root)
paths = struct("iteration",fullfile(root,"iteration_history.csv"), ...
    "timing",fullfile(root,"timing_history.csv"), ...
    "factorization",fullfile(root,"daily_joint_factorization_history.csv"), ...
    "water_correction",fullfile(root, ...
        "water_slack_second_order_correction_history.csv"));
end

function persist_histories(paths,iteration,timing,factorization,waterCorrection)
rkkt.artifacts.write_table_csv_17g_atomic(paths.iteration,iteration);
rkkt.artifacts.write_table_csv_17g_atomic(paths.timing,timing);
rkkt.artifacts.write_table_csv_17g_atomic(paths.factorization,factorization);
rkkt.artifacts.write_table_csv_17g_atomic(paths.water_correction,waterCorrection);
end

function metadata = checkpoint_metadata(iteration,commit,configSha,inputHash,config)
metadata = struct("iteration",iteration,"git_commit",char(commit), ...
    "config_sha256",char(configSha), ...
    "input_hash_fingerprint",char(inputHash), ...
    "recursive_route",char(config.recursive_route), ...
    "local_linear_solve_residual_tolerance", ...
        config.local_linear_solve_residual_tolerance, ...
    "recursive_full_kkt_residual_tolerance", ...
        config.recursive_full_kkt_residual_tolerance, ...
    "reduced_symmetry_tolerance",config.reduced_symmetry_tolerance, ...
    "border_symmetry_tolerance",config.border_symmetry_tolerance, ...
    "lagrangian_hessian_symmetry_tolerance", ...
        config.lagrangian_hessian_symmetry_tolerance, ...
    "full_kkt_role",char(config.full_kkt_role), ...
    "full_kkt_audit_executed",false, ...
    "water_slack_second_order_correction_enabled",true, ...
    "water_slack_second_order_correction_scope_count", ...
        config.expected_water_inequality_count, ...
    "no_full_direction_fallback",true, ...
    "full_direction_consumed_by_recursive",false);
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message] = mkdir(pathValue);
assert(created,"stageB2C:recursive:Directory","%s",message);
end

function value = hash_text(textValue)
engine = java.security.MessageDigest.getInstance("SHA-256");
engine.update(unicode2native(char(textValue),"UTF-8"));
bytes = mod(double(engine.digest()),256);
value = lower(string(reshape(dec2hex(bytes,2).',1,[])));
end
