function result = solve_stage_b2c_daily_joint_direction(lin,options)
%SOLVE_STAGE_B2C_DAILY_JOINT_DIRECTION Solve one formal Newton direction.
%
% Route:
%   all inequality elimination -> configured joint day responses -> 16-D core
%   -> daily reverse recovery -> uniform dl/dz recovery -> complete KKT
%   residual gate. Local near-zero pivots and response residuals are
%   diagnostics; they never replace the final global equation check.

arguments
    lin (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-12
    options.ResidualTolerance (1,1) double = 1e-10
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
assert(options.RefinementPasses<=3, ...
    "stageB2C:dailyJoint:RefinementPassLimit", ...
    "Daily-joint residual refinement permits at most three passes.");

totalTimer = tic;
timer = tic;
reduced = rkkt.solver.eliminate_stage_b2c_all_inequality_directions(lin);
timing.elimination_seconds = toc(timer);
assert(reduced.symmetry_relative<=options.SymmetryTolerance, ...
    "stageB2C:dailyJoint:ReducedSymmetry", ...
    "Fully eliminated W symmetry error %.17g exceeds %.17g.", ...
    reduced.symmetry_relative,options.SymmetryTolerance);

timer = tic;
partition = rkkt.solver.partition_stage_b2c_daily_joint_system(lin,reduced);
timing.partition_seconds = toc(timer);

timer = tic;
responseCells = cell(numel(partition.day),1);
for d = 1:numel(partition.day)
    responseCells{d} = rkkt.solver.solve_stage_b2c_daily_joint_day( ...
        partition.day(d), ...
        SymmetryTolerance=options.SymmetryTolerance, ...
        ResidualTolerance=options.ResidualTolerance, ...
        RefinementPasses=options.RefinementPasses);
end
responses = vertcat(responseCells{:});
timing.daily_response_seconds = toc(timer);

timer = tic;
coreMatrix = partition.global.matrix;
coreRhs = partition.global.rhs;
for d = 1:numel(responses)
    coreMatrix = coreMatrix-responses(d).schur_matrix_contribution;
    coreRhs = coreRhs-responses(d).schur_rhs_contribution;
end
[coreSolution,coreFactor] = ...
    rkkt.solver.solve_stage_b2c_daily_joint_block( ...
        coreMatrix,coreRhs,"stageB2C_daily_joint_core16", ...
        SymmetryTolerance=options.SymmetryTolerance, ...
        ResidualTolerance=options.ResidualTolerance, ...
        RefinementPasses=options.RefinementPasses);
core = struct("stage_id","stage_B", ...
    "milestone_id","B-2C", ...
    "linearization_identity",lin.identity, ...
    "matrix",sparse(coreMatrix),"rhs",coreRhs, ...
    "solution",coreSolution,"delta_q",coreSolution(1:14), ...
    "delta_rho",coreSolution(15:16),"factor",coreFactor, ...
    "dimension",16);
timing.core_seconds = toc(timer);

timer = tic;
recovery = rkkt.solver.recover_stage_b2c_daily_joint_direction( ...
    lin,partition,responses,core);
timing.recovery_seconds = toc(timer);

timer = tic;
[candidateKktRelative,candidateKktMaximum] = ...
    reconstructed_kkt_residual(lin,recovery.components);
timing.final_kkt_residual_seconds = toc(timer);
assert(candidateKktRelative<=options.ResidualTolerance, ...
    "stageB2C:dailyJoint:FinalKktResidual", ...
    "The reconstructed direction KKT residual %.17g exceeds %.17g.", ...
    candidateKktRelative,options.ResidualTolerance);
timing.total_seconds = toc(totalTimer);

result = struct();
result.stage_id = "stage_B";
result.milestone_id = "B-2C";
result.linearization_identity = lin.identity;
result.direction = recovery.direction;
result.components = recovery.components;
result.reduced = reduced;
result.partition = partition;
result.responses = responses;
result.daily_responses = responses;
result.core = core;
result.recovery = recovery;
result.fixed_zero = recovery.fixed_zero;
result.timing = timing;
result.no_full_direction_fallback = true;
result.full_direction_consumed = false;
result.daily_joint_direction_executed = true;
result.full_ipm_executed = false;
result.optimization_executed = false;
result.state_update_executed = false;
result.regularization_used = false;
result.pseudoinverse_used = false;
result.diagnostics = struct( ...
    "daily_response_count",numel(responses), ...
    "daily_response_dimension",14,"global_core_dimension",16, ...
    "daily_dimensions",reshape([partition.day.dimension],1,[]), ...
    "daily_rhs_counts",reshape([responses.rhs_count],1,[]), ...
    "daily_factorization_counts", ...
        arrayfun(@(value)value.factor.factorization_count,responses), ...
    "daily_minimum_absolute_pivots", ...
        arrayfun(@(value) ...
        value.factor.minimum_absolute_pivot_eigenvalue,responses), ...
    "daily_numerical_zero_pivot_counts", ...
        arrayfun(@(value)value.factor.inertia_zero,responses), ...
    "daily_local_maximum_relative_residuals", ...
        arrayfun(@(value) ...
        value.factor.maximum_column_relative_residual,responses), ...
    "daily_local_residual_targets_met", ...
        arrayfun(@(value)value.factor.local_residual_target_met,responses), ...
    "near_zero_pivot_day_ids", ...
        reshape([responses(arrayfun(@(value)value.factor.inertia_zero>0, ...
        responses)).day_id],1,[]), ...
    "continued_warning_day_ids", ...
        reshape([responses(arrayfun(@(value) ...
        value.factor.warning_continued,responses)).day_id],1,[]), ...
    "candidate_kkt_relative_residual",candidateKktRelative, ...
    "candidate_kkt_maximum_absolute_residual",candidateKktMaximum, ...
    "final_kkt_residual_tolerance",options.ResidualTolerance, ...
    "final_kkt_residual_gate_passed",true, ...
    "local_response_residual_is_blocking",false, ...
    "water_eta_dimension",0,"cross_day_nnz",partition.cross_day_nnz, ...
    "full_inequality_elimination",true, ...
    "no_full_direction_fallback",true, ...
    "formal_recursive_route", ...
        "all_inequality_daily_joint_final_kkt_residual_gate");
end

function [relativeResidual,maximumAbsolute] = ...
        reconstructed_kkt_residual(lin,components)
dx = components.xi;
dy = components.y;
dl = components.l;
dz = components.z;
residual = [ ...
    sparse(lin.H)*dx+sparse(lin.A).'*dy+sparse(lin.G).'*dz+lin.r_dual
    sparse(lin.A)*dx+lin.r_eq
    sparse(lin.G)*dx+dl+lin.r_ineq
    lin.z.*dl+lin.l.*dz+lin.r_comp];
rhsNorm = norm([lin.r_dual;lin.r_eq;lin.r_ineq;lin.r_comp],2);
relativeResidual = norm(residual,2)/max(1,rhsNorm);
maximumAbsolute = max(abs(residual));
end
