function result = solve_stage_b2b_recursive_direction(lin,options)
%SOLVE_STAGE_B2B_RECURSIVE_DIRECTION Compute exactly one recursive direction.
%
% The full-KKT audit direction is deliberately not an input or fallback.  A
% single shared linearization is consumed by elimination, daily borders,
% responses, the 16-D core, and strict reverse recovery.
arguments
    lin (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double = 0
    options.UseCongruenceScaling (1,1) logical = false
    options.EquilibrationPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 8
end
contract=rkkt.solver.stage_b2b_linearization_contract(lin);
assert(options.ResidualRefinementMaxPasses<=3, ...
    "stageB2B:solver:RefinementLimit", ...
    "The bordered stable-v2 route permits at most three refinement passes.");
route=solve_once(lin,options);
reduced=route.reduced;
partition=route.partition;
responses=route.responses;
aggregation=route.aggregation;
core=route.core;
recovery=route.recovery;
defectRefinement=struct("enabled",false,"passes",0, ...
    "initial_reduced_relative_residual",NaN, ...
    "final_reduced_relative_residual",NaN, ...
    "correction_relative_norm",0, ...
    "additional_day_factorization_count",0, ...
    "additional_core_factorization_count",0, ...
    "full_kkt_direction_consumed",false);
if contract.milestone_id=="B-2C"
    passCount=3;
    residualHistory=zeros(passCount+1,1);
    correctionRelativeNorm=zeros(passCount,1);
    correctionStepLength=zeros(passCount,1);
    recoveryCandidate=cell(passCount+1,1);
    recoveryCandidate{1}=recovery;
    residual=rkkt.solver.compute_sparse_residual_double_double( ...
        reduced.saddle,[recovery.components.xi;recovery.components.y], ...
        reduced.rhs);
    residualHistory(1)=relative_residual(residual,reduced.rhs);
    for pass=1:passCount
        correctionLin=lin;
        correctionLin.r_dual=-residual(1:contract.nx);
        correctionLin.r_eq=-residual(contract.nx+1:end);
        correctionLin.r_ineq=zeros(contract.nineq,1);
        correctionLin.r_comp=zeros(contract.nineq,1);
        correctionRoute=solve_once(correctionLin,options);
        correctionStepLength(pass)=1;
        recovery=combine_recoveries( ...
            recovery,correctionRoute.recovery,lin,contract, ...
            correctionStepLength(pass));
        correctionRelativeNorm(pass)= ...
            abs(correctionStepLength(pass))* ...
            norm(correctionRoute.recovery.direction,2)/ ...
            max(1,norm(recovery.direction,2));
        residual=rkkt.solver.compute_sparse_residual_double_double( ...
            reduced.saddle,[recovery.components.xi;recovery.components.y], ...
            reduced.rhs);
        residualHistory(pass+1)=relative_residual(residual,reduced.rhs);
        recoveryCandidate{pass+1}=recovery;
    end
    [~,selectedCandidate]=min(residualHistory);
    recovery=recoveryCandidate{selectedCandidate};
    selectedPass=selectedCandidate-1;
    defectRefinement=struct("enabled",true,"passes",passCount, ...
        "selected_pass",selectedPass, ...
        "initial_reduced_relative_residual", ...
            residualHistory(1), ...
        "final_reduced_relative_residual", ...
            residualHistory(selectedCandidate), ...
        "correction_relative_norm", ...
            max(correctionRelativeNorm), ...
        "residual_history",residualHistory, ...
        "correction_relative_norm_history",correctionRelativeNorm, ...
        "correction_step_length",correctionStepLength, ...
        "additional_day_factorization_count", ...
            passCount*contract.n_days, ...
        "additional_core_factorization_count",passCount, ...
        "full_kkt_direction_consumed",false);
end
result=struct("stage_id","stage_B","milestone_id",contract.milestone_id, ...
    "linearization_identity",contract.identity,"direction",recovery.direction, ...
    "components",recovery.components,"reduced",reduced,"partition",partition, ...
    "responses",responses,"daily_responses",responses, ...
    "aggregation",aggregation,"core",core,"recovery",recovery, ...
    "fixed_zero",recovery.fixed_zero, ...
    "no_full_direction_fallback",true,"full_direction_consumed",false, ...
    "recursive_direction_executed",true,"full_ipm_executed",false, ...
    "optimization_executed",false,"parallel_executed",false, ...
    "diagnostics",struct("daily_response_count",numel(responses), ...
        "daily_response_dimension",14,"global_core_dimension",16, ...
        "total_chain_dimension",partition.total_hourly_chain_dimension, ...
        "total_augmented_chain_dimension",partition.total_augmented_chain_dimension, ...
        "defect_refinement",defectRefinement), ...
    "residual_refinement",struct( ...
        "maximum_passes",options.ResidualRefinementMaxPasses, ...
        "daily_chain",{arrayfun(@(x)x.diagnostics.chain_residual_refinement, ...
            responses)}, ...
        "daily_extra_rhs",{arrayfun(@(x)x.diagnostics.extra_rhs_residual_refinement, ...
            responses)}, ...
        "daily_border",{arrayfun(@(x)x.diagnostics.border_residual_refinement, ...
            responses)}, ...
        "core",core.diagnostics.residual_refinement, ...
        "factor_reuse_within_iteration_only",true, ...
        "full_kkt_direction_consumed",false), ...
    "defect_refinement",defectRefinement, ...
    "congruence_scaling",struct("used",options.UseCongruenceScaling, ...
        "equilibration_passes",options.EquilibrationPasses*options.UseCongruenceScaling, ...
        "automatic_symmetrization_used",false,"regularization_used",false));
end

function route=solve_once(lin,options)
contract=rkkt.solver.stage_b2b_linearization_contract(lin);
reduced=rkkt.solver.eliminate_stage_b2b_inequality_directions(lin);
partition=rkkt.solver.partition_stage_b2b_recursive_system(lin,reduced, ...
    "AssemblyTolerance",1e-12);
for d=1:contract.n_days
    solved=rkkt.solver.solve_stage_b2b_day_border(partition.day(d),lin,reduced, ...
        "SymmetryTolerance",options.SymmetryTolerance, ...
        "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
        "UseCongruenceScaling",options.UseCongruenceScaling, ...
        "EquilibrationPasses",options.EquilibrationPasses);
    response=rkkt.solver.form_stage_b2b_day_response( ...
        partition.day(d),solved,lin,reduced);
    if d==1
        responses=response;
    else
        responses(d,1)=response;
    end
end
aggregation=rkkt.solver.aggregate_stage_b2b_day_responses( ...
    responses,contract.days);
core=rkkt.solver.solve_stage_b2b_core16_ldl(partition,aggregation, ...
    "SymmetryTolerance",options.SymmetryTolerance, ...
    "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
    "UseCongruenceScaling",options.UseCongruenceScaling, ...
    "EquilibrationPasses",options.EquilibrationPasses);
recovery=rkkt.solver.recover_stage_b2b_recursive_direction( ...
    lin,partition,responses,core);
route=struct("reduced",reduced,"partition",partition, ...
    "responses",responses,"aggregation",aggregation,"core",core, ...
    "recovery",recovery);
end

function combined=combine_recoveries(base,correction,lin,contract,weight)
deltaXi=base.components.xi+weight*correction.components.xi;
deltaY=base.components.y+weight*correction.components.y;
deltaL=-contract.r_ineq-sparse(lin.G)*deltaXi;
deltaZ=(-contract.r_comp-contract.z.*deltaL)./contract.l;
deltaQDay=cell(contract.n_days,1);
deltaPi=cell(contract.n_days,1);
vByDayHour=cell(contract.n_days,contract.n_hours);
etaByDay=cell(contract.n_days,1);
waterEtaError=zeros(contract.n_days,1);
waterEtaRelative=zeros(contract.n_days,1);
for d=1:contract.n_days
    deltaQDay{d}=deltaXi(contract.q_day_by_day{d});
    deltaPi{d}=deltaY(contract.y_binding_by_day{d});
    etaByDay{d}=base.components.eta_by_day{d}+ ...
        weight*correction.components.eta_by_day{d};
    expectedEta=deltaZ(contract.water_by_day{d});
    waterEtaError(d)=norm(expectedEta-etaByDay{d},inf);
    waterEtaRelative(d)=norm(expectedEta-etaByDay{d},2)/ ...
        max(1,norm(expectedEta,2));
    for t=1:contract.n_hours
        vByDayHour{d,t}=[ ...
            deltaXi(contract.x_by_day_hour{d,t}); ...
            deltaY(contract.y_by_day_hour{d,t})];
    end
end
assert(max(waterEtaRelative)<=1e-10, ...
    "stageB2C:recovery:RefinedWaterEta", ...
    "Refined water eta relative mismatch %.17g.",max(waterEtaRelative));
combined=base;
combined.direction=[deltaXi;deltaY;deltaL;deltaZ];
combined.components=struct("xi",deltaXi,"y",deltaY, ...
    "l",deltaL,"z",deltaZ,"q",deltaXi(contract.q_global), ...
    "rho",deltaY(contract.y_duration), ...
    "q_day_by_day",{deltaQDay},"pi_by_day",{deltaPi}, ...
    "v_by_day_hour",{vByDayHour},"eta_by_day",{etaByDay});
combined.diagnostics=struct( ...
    "water_eta_max_error",max(waterEtaError), ...
    "water_eta_max_relative_error",max(waterEtaRelative), ...
    "delta_l_residual", ...
        norm(deltaL+contract.r_ineq+lin.G*deltaXi,inf), ...
    "delta_z_residual", ...
        norm(contract.l.*deltaZ+contract.r_comp+contract.z.*deltaL,inf), ...
    "strict_reverse_recovery",true);
end

function value=relative_residual(residual,rhs)
value=norm(residual,2)/max(1,norm(rhs,2));
end
