function result = solveStageB2BRecursiveDirection(linearization,options)
%SOLVESTAGEB2BRECURSIVEDIRECTION Solve one official Stage B-2B direction.

arguments
    linearization (1,1) struct
    options.SymmetryTolerance (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.UseCongruenceScaling (1,1) logical = false
end

result = rkkt.solver.solve_stage_b2b_recursive_direction( ...
    linearization, ...
    SymmetryTolerance=options.SymmetryTolerance, ...
    ResidualRefinementMaxPasses=options.ResidualRefinementMaxPasses, ...
    UseCongruenceScaling=options.UseCongruenceScaling);
end
