function [responseCells,retainedFactorCells,diagnostics] = ...
        solve_stage_b2c_daily_joint_responses_parallel(days,options)
%SOLVE_STAGE_B2C_DAILY_JOINT_RESPONSES_PARALLEL Solve independent days in parallel.

arguments
    days struct
    options.WorkerCount (1,1) double {mustBeInteger,mustBePositive}
    options.SymmetryTolerance (1,1) double = 1e-10
    options.ResidualTolerance (1,1) double = 1e-10
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end

pool = gcp("nocreate");
assert(~isempty(pool) && contains(string(class(pool)),"ProcessPool") && ...
    pool.NumWorkers==options.WorkerCount, ...
    "stageB2C:parallel:ProcessPool", ...
    "A Processes pool with exactly %d workers must already exist.", ...
    options.WorkerCount);

dayCount = numel(days);
responseCells = cell(dayCount,1);
retainedFactorCells = cell(dayCount,1);
workerSeconds = zeros(dayCount,1);
symmetryTolerance = options.SymmetryTolerance;
residualTolerance = options.ResidualTolerance;
refinementPasses = options.RefinementPasses;
parfor d = 1:dayCount
    workerTimer = tic;
    [responseCells{d},retainedFactorCells{d}] = ...
        rkkt.solver.solve_stage_b2c_daily_joint_day( ...
        days(d),SymmetryTolerance=symmetryTolerance, ...
        ResidualTolerance=residualTolerance, ...
        RefinementPasses=refinementPasses);
    workerSeconds(d) = toc(workerTimer);
end

diagnostics = struct( ...
    "execution_mode","parallel_processes", ...
    "worker_count",pool.NumWorkers, ...
    "day_count",dayCount, ...
    "worker_day_seconds",workerSeconds, ...
    "worker_day_seconds_sum",sum(workerSeconds), ...
    "worker_day_seconds_maximum",max(workerSeconds));
end
