function [solution,diagnostics,retainedFactor] = solve_stage_b2c_daily_joint_block( ...
        matrix,rhs,label,options)
%SOLVE_STAGE_B2C_DAILY_JOINT_BLOCK Factor one sparse block for many RHS.
%
% No inverse, pseudoinverse, regularization, dense day conversion, or
% alternative solve is used. MATLAB's sparse pivoted LDL factor is formed
% once and reused for every supplied right-hand side. A numerical-zero
% pivot is recorded rather than rejected here; only the reconstructed
% complete KKT residual may accept the resulting Newton direction.

arguments
    matrix {mustBeNumeric,mustBeReal}
    rhs {mustBeNumeric,mustBeReal}
    label (1,1) string
    options.SymmetryTolerance (1,1) double = 1e-10
    options.ResidualTolerance (1,1) double = 1e-10
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.ContinueNumericalPivotWarning (1,1) logical = false
end
assert(options.RefinementPasses<=3, ...
    "stageB2C:dailyJoint:RefinementPassLimit", ...
    "A retained daily-joint LDL factor permits at most three correction passes.");

matrix = sparse(matrix);
n = size(matrix,1);
assert(size(matrix,2)==n && size(rhs,1)==n && ...
    all(isfinite(nonzeros(matrix))) && all(isfinite(rhs),"all"), ...
    "stageB2C:dailyJoint:BlockShape", ...
    "%s has an invalid matrix or right-hand side.",label);
symmetryRelative = norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro"));
assert(symmetryRelative<=options.SymmetryTolerance, ...
    "stageB2C:dailyJoint:BlockSymmetry", ...
    "%s symmetry error %.17g exceeds %.17g.", ...
    label,symmetryRelative,options.SymmetryTolerance);

structuralRank = sprank(matrix);
if structuralRank<n
    error("stageB2C:dailyJoint:ModelDecisionStructuralRank", ...
        "%s has structural rank %d below dimension %d.", ...
        label,structuralRank,n);
end

lastwarn("");
factorTimer = tic;
[L,D,permutation,C] = ldl(matrix,0.5,"vector");
factorSeconds = toc(factorTimer);
[factorWarningMessage,factorWarningId] = lastwarn;
if strlength(string(factorWarningId))>0 || ...
        strlength(string(factorWarningMessage))>0
    error("stageB2C:dailyJoint:FactorWarning", ...
        "%s LDL factorization emitted %s: %s", ...
        label,factorWarningId,factorWarningMessage);
end
assert(all(isfinite(nonzeros(L))) && all(isfinite(nonzeros(D))), ...
    "stageB2C:dailyJoint:FactorFinite", ...
    "%s LDL factors contain NaN or Inf.",label);

scale = nonzeros(C);
assert(numel(scale)==n && all(isfinite(scale)) && all(scale>0), ...
    "stageB2C:dailyJoint:FactorScale", ...
    "%s LDL congruence scale is invalid.",label);
pivotEigenvalues = block_pivot_eigenvalues(D);
pivotTolerance = n*eps(max(1,max(abs(pivotEigenvalues))));
inertiaZero = nnz(abs(pivotEigenvalues)<=pivotTolerance);

retainedFactor = struct("L",L,"D",D,"permutation",permutation, ...
    "scale",scale,"dimension",n,"inertia_zero",inertiaZero, ...
    "pivot_tolerance",pivotTolerance, ...
    "pivot_eigenvalues",pivotEigenvalues, ...
    "method","sparse_pivoted_ldl","factorization_count",1);
[solution,solveDiagnostics] = ...
    rkkt.solver.apply_stage_b2c_daily_joint_factor( ...
        retainedFactor,matrix,rhs,label, ...
        ResidualTolerance=options.ResidualTolerance, ...
        RefinementPasses=options.RefinementPasses, ...
        ContinueNumericalPivotWarning= ...
            options.ContinueNumericalPivotWarning);

scaledMatrix = C*matrix*C;
factorRelative = norm(L*D*L.'- ...
    scaledMatrix(permutation,permutation),"fro")/ ...
    max(1,norm(scaledMatrix,"fro"));
diagnostics = struct( ...
    "label",label,"dimension",n,"nnz",nnz(matrix), ...
    "rhs_count",size(rhs,2),"factorization_count",1, ...
    "method","sparse_pivoted_ldl", ...
    "structural_rank",structuralRank, ...
    "symmetry_relative",symmetryRelative, ...
    "factor_relative_residual",factorRelative, ...
    "maximum_column_relative_residual", ...
        solveDiagnostics.maximum_column_relative_residual, ...
    "initial_maximum_column_relative_residual", ...
        solveDiagnostics.initial_maximum_column_relative_residual, ...
    "frobenius_relative_residual", ...
        solveDiagnostics.frobenius_relative_residual, ...
    "maximum_absolute_residual", ...
        solveDiagnostics.maximum_absolute_residual, ...
    "pivot_tolerance",pivotTolerance, ...
    "minimum_absolute_pivot_eigenvalue",min(abs(pivotEigenvalues)), ...
    "maximum_absolute_pivot_eigenvalue",max(abs(pivotEigenvalues)), ...
    "pivot_dynamic_range",max(abs(pivotEigenvalues))/ ...
        min(abs(pivotEigenvalues)), ...
    "inertia_positive",nnz(pivotEigenvalues>pivotTolerance), ...
    "inertia_negative",nnz(pivotEigenvalues<-pivotTolerance), ...
    "inertia_zero",inertiaZero, ...
    "numerical_zero_pivot_continued",inertiaZero>0, ...
    "warning_identifier",solveDiagnostics.warning_identifier, ...
    "warning_message",solveDiagnostics.warning_message, ...
    "warning_present",solveDiagnostics.warning_present, ...
    "warning_continued",solveDiagnostics.warning_continued, ...
    "blocking_warning_present", ...
        solveDiagnostics.blocking_warning_present, ...
    "solution_finite",true, ...
    "local_residual_tolerance",options.ResidualTolerance, ...
    "local_residual_target_met", ...
        solveDiagnostics.local_residual_target_met, ...
    "acceptance_scope","final_reconstructed_kkt_residual", ...
    "factor_seconds",factorSeconds, ...
    "solve_seconds",solveDiagnostics.solve_seconds, ...
    "refinement_enabled",solveDiagnostics.refinement_enabled, ...
    "refinement_triggered",solveDiagnostics.refinement_triggered, ...
    "refinement_maximum_passes",options.RefinementPasses, ...
    "refinement_passes_applied", ...
        solveDiagnostics.refinement_passes_applied, ...
    "refinement_additional_factorization_count",0, ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "dense_day_conversion_used",false);
end

function values = block_pivot_eigenvalues(D)
n = size(D,1);
values = zeros(n,1);
cursor = 1;
row = 1;
while row<=n
    if row<n && D(row+1,row)~=0
        current = eig(full(D(row:row+1,row:row+1)));
        values(cursor:cursor+1) = current;
        cursor = cursor+2;
        row = row+2;
    else
        values(cursor) = D(row,row);
        cursor = cursor+1;
        row = row+1;
    end
end
values = values(1:cursor-1);
end
