function result = solve_stage_b2b_full_kkt_direction(lin)
%SOLVE_STAGE_B2B_FULL_KKT_DIRECTION Solve one independent audit direction.
%
% This route is audit-only.  It accepts only the shared linearization and
% exposes no API by which a recursive solver could consume its direction.

arguments
    lin (1,1) struct
end

assembly = rkkt.solver.assemble_stage_b2b_full_kkt(lin);
lastwarn("");
if string(assembly.milestone_id)=="B-2C"
    reduced=rkkt.solver.eliminate_stage_b2b_inequality_directions(lin);
    [permutation,rowScale,columnScale] = ...
        equilibrate(reduced.saddle,"vector");
    dimension = size(reduced.saddle,1);
    scaledMatrix = spdiags(rowScale,0,dimension,dimension)* ...
        reduced.saddle(permutation,:)* ...
        spdiags(columnScale,0,dimension,dimension);
    [lowerFactor,upperFactor,rowPermutation,columnPermutation]= ...
        lu(scaledMatrix,"vector");
    reducedDirection=columnScale.* ...
        apply_sparse_lu(lowerFactor,upperFactor,rowPermutation, ...
            columnPermutation,rowScale.*reduced.rhs(permutation));
    passCount=3;
    residualHistory=zeros(passCount+1,1);
    directionCandidate=cell(passCount+1,1);
    for pass=0:passCount
        residual=rkkt.solver.compute_sparse_residual_double_double( ...
            reduced.saddle,reducedDirection,reduced.rhs);
        residualHistory(pass+1)=norm(residual,2)/ ...
            max(1,norm(reduced.rhs,2));
        directionCandidate{pass+1}=reducedDirection;
        if pass<passCount
            reducedDirection=reducedDirection+columnScale.* ...
                apply_sparse_lu(lowerFactor,upperFactor,rowPermutation, ...
                    columnPermutation,rowScale.*residual(permutation));
        end
    end
    [~,selectedCandidate]=min(residualHistory);
    reducedDirection=directionCandidate{selectedCandidate};
    deltaXi=reducedDirection(1:reduced.nx);
    deltaY=reducedDirection(reduced.nx+1:end);
    deltaL=-lin.r_ineq-sparse(lin.G)*deltaXi;
    deltaZ=(-lin.r_comp-lin.z.*deltaL)./lin.l;
    direction=[deltaXi;deltaY;deltaL;deltaZ];
    method = "independent_global_saddle_extended_refinement_audit_only";
    equationPreservingScalingUsed = true;
    reducedAudit=struct("executed",true,"dimension",dimension, ...
        "factorization","equilibrated_explicit_sparse_lu", ...
        "refinement_passes",passCount, ...
        "selected_pass",selectedCandidate-1, ...
        "extended_residual_history",residualHistory, ...
        "recursive_partition_consumed",false, ...
        "global_core_consumed",false);
else
    direction = assembly.matrix\assembly.rhs;
    rowScale = 1;
    columnScale = 1;
    method = "sparse_backslash_audit_only";
    equationPreservingScalingUsed = false;
    reducedAudit=struct("executed",false,"dimension",0, ...
        "factorization","none","refinement_passes",0, ...
        "selected_pass",0,"extended_residual_history",zeros(0,1), ...
        "recursive_partition_consumed",false, ...
        "global_core_consumed",false);
end
[warningMessage,warningId] = lastwarn;
if strlength(string(warningId))>0 || strlength(string(warningMessage))>0
    error("stageB2B:fullKkt:SolveWarning", ...
        "B-2B sparse audit solve emitted warning %s: %s", ...
        string(warningId),string(warningMessage));
end
assert(all(isfinite(direction)),"stageB2B:fullKkt:DirectionFinite", ...
    "B-2B full-KKT audit direction contains NaN or Inf.");
residual = assembly.matrix*direction-assembly.rhs;

result = struct();
result.stage_id = "stage_B";
result.milestone_id = assembly.milestone_id;
result.method = method;
result.linearization_identity = assembly.linearization_identity;
result.direction = direction;
result.components = struct( ...
    "xi",direction(assembly.slices.xi), ...
    "y",direction(assembly.slices.y), ...
    "l",direction(assembly.slices.l), ...
    "z",direction(assembly.slices.z));
result.kkt = assembly;
result.diagnostics = struct( ...
    "relative_residual",norm(residual,2)/max(1,norm(assembly.rhs,2)), ...
    "max_absolute_residual",max(abs(residual)), ...
    "max_residual_row",find(abs(residual)==max(abs(residual)),1,"first"), ...
    "warning_id",string(warningId), ...
    "warning_message",string(warningMessage), ...
    "warning_present",false, ...
    "equation_preserving_scaling_used",equationPreservingScalingUsed, ...
    "row_scale_minimum",min(rowScale), ...
    "row_scale_maximum",max(rowScale), ...
    "column_scale_minimum",min(columnScale), ...
    "column_scale_maximum",max(columnScale), ...
    "independent_reduced_audit",reducedAudit);
result.audit_only = true;
result.execution = struct("audit_only",true,"full_kkt_solved",true, ...
    "recursive_direction_consumed",false,"fallback_used",false, ...
    "full_ipm_executed",false,"optimization_executed",false, ...
    "parallel_executed",false);
result.recursive_direction_consumed = false;
result.no_full_direction_fallback = true;
result.full_ipm_executed = false;
result.optimization_executed = false;
result.parallel_executed = false;
end

function solution=apply_sparse_lu(L,U,rowPermutation,columnPermutation,rhs)
n=size(L,1);
work=zeros(size(rhs));
permutedRhs=rhs(rowPermutation,:);
for row=1:n
    work(row,:)=(permutedRhs(row,:)- ...
        L(row,1:row-1)*work(1:row-1,:))/L(row,row);
end
permutedSolution=zeros(size(rhs));
for row=n:-1:1
    permutedSolution(row,:)=(work(row,:)- ...
        U(row,row+1:n)*permutedSolution(row+1:n,:))/U(row,row);
end
solution=zeros(size(rhs));
solution(columnPermutation,:)=permutedSolution;
end
