function result = solve_stage_b2c_delayed_inequality_border( ...
        lin,partition,responses,retainedFactors,problemDayPositions,options)
%SOLVE_STAGE_B2C_DELAYED_INEQUALITY_BORDER Solve numerically degenerate days.
%
% The ordinary daily responses remain the trigger evidence. For every day
% whose corrected multiple-RHS residual misses the configured local target,
% this route delays that day's inequality elimination and preserves its dz
% variables in one sparse border with the 16 global capacity variables.
% All equations are unchanged; no regularization or complete-KKT solve is
% used.

arguments
    lin (1,1) struct
    partition (1,1) struct
    responses (:,1) struct
    retainedFactors (:,1) cell
    problemDayPositions (:,1) double {mustBeInteger,mustBePositive}
    options.SymmetryTolerance (1,1) double = 1e-10
    options.LocalResidualTolerance (1,1) double = 1e-10
    options.ReconstructedKktResidualTolerance (1,1) double = 1e-8
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.ConsistencyMaximumPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.CompensatedCoreAccumulation (1,1) logical = false
end
assert(options.RefinementPasses<=3 && ...
    options.ConsistencyMaximumPasses<=10, ...
    "stageB2C:delayedInequality:PassLimit", ...
    "Delayed-inequality refinement limits are invalid.");
problemDayPositions = unique(problemDayPositions(:),"stable");
assert(all(problemDayPositions<=numel(partition.day)) && ...
    numel(responses)==numel(partition.day) && ...
    numel(retainedFactors)==numel(partition.day), ...
    "stageB2C:delayedInequality:ProblemDays", ...
    "Problem-day positions or daily response inputs are invalid.");

coreTimer = tic;
[diagnosticCoreMatrix,diagnosticCoreRhs] = aggregate_responses( ...
    partition,responses,(1:numel(partition.day)).', ...
    options.CompensatedCoreAccumulation);
ordinaryPositions = setdiff((1:numel(partition.day)).', ...
    problemDayPositions,"stable");
[borderMatrix,borderRhs] = aggregate_responses( ...
    partition,responses,ordinaryPositions, ...
    options.CompensatedCoreAccumulation);
[matrix,rhs,layout,construction] = build_expanded_border( ...
    lin,partition,problemDayPositions,borderMatrix,borderRhs, ...
    options.SymmetryTolerance);
[retainedFactor,factorBase] = factor_equilibrated_sparse_lu(matrix);
[solution,solveDiagnostics] = apply_equilibrated_sparse_lu( ...
    retainedFactor,matrix,rhs,options.LocalResidualTolerance, ...
    options.RefinementPasses);
factor = complete_factor_diagnostics(factorBase,solveDiagnostics,rhs);
timing.core_seconds = toc(coreTimer);

[current,recovery,evaluationTiming] = evaluate_candidate( ...
    lin,partition,retainedFactors,problemDayPositions, ...
    layout,matrix,rhs,solution,options.LocalResidualTolerance, ...
    options.ReconstructedKktResidualTolerance,options.RefinementPasses);
timing.recovery_seconds = evaluationTiming.recovery_seconds;
timing.reconstructed_kkt_residual_seconds = ...
    evaluationTiming.reconstructed_kkt_residual_seconds;

maximumPasses = options.ConsistencyMaximumPasses;
if maximumPasses==0
    maximumPasses = max(1,options.RefinementPasses);
end
initialRelative = current.expanded_relative;
initialKktRelative = current.kkt_relative;
relativeHistory = initialRelative;
kktHistory = initialKktRelative;
combinedHistory = current.combined_gate;
passesAttempted = 0;
passesApplied = 0;
stopReason = "maximum_passes_reached";
for pass = 1:maximumPasses
    if targets_met(current,options)
        stopReason = "both_targets_met";
        break
    end
    correctionRhs = ...
        rkkt.solver.compute_sparse_residual_double_double( ...
        matrix,solution,rhs);
    coreTimer = tic;
    [correction,~] = apply_equilibrated_sparse_lu( ...
        retainedFactor,matrix,correctionRhs, ...
        options.LocalResidualTolerance,options.RefinementPasses);
    timing.core_seconds = timing.core_seconds+toc(coreTimer);
    candidateSolution = solution+correction;
    [candidate,candidateRecovery,candidateTiming] = evaluate_candidate( ...
        lin,partition,retainedFactors,problemDayPositions, ...
        layout,matrix,rhs,candidateSolution, ...
        options.LocalResidualTolerance, ...
        options.ReconstructedKktResidualTolerance, ...
        options.RefinementPasses);
    timing.recovery_seconds = timing.recovery_seconds+ ...
        candidateTiming.recovery_seconds;
    timing.reconstructed_kkt_residual_seconds = ...
        timing.reconstructed_kkt_residual_seconds+ ...
        candidateTiming.reconstructed_kkt_residual_seconds;
    passesAttempted = pass;
    relativeHistory(end+1) = candidate.expanded_relative; %#ok<AGROW>
    kktHistory(end+1) = candidate.kkt_relative; %#ok<AGROW>
    combinedHistory(end+1) = candidate.combined_gate; %#ok<AGROW>
    if candidate.combined_gate>=current.combined_gate
        stopReason = "combined_gate_did_not_improve";
        break
    end
    solution = candidateSolution;
    current = candidate;
    recovery = candidateRecovery;
    passesApplied = pass;
    if targets_met(current,options)
        stopReason = "both_targets_met";
        break
    end
end

bothTargetsMet = targets_met(current,options);
correction = struct( ...
    "enabled",true,"maximum_passes",maximumPasses, ...
    "passes_attempted",passesAttempted,"passes_applied",passesApplied, ...
    "initial_relative_residual",initialRelative, ...
    "final_relative_residual",current.expanded_relative, ...
    "relative_residual_history",relativeHistory, ...
    "target_met",current.expanded_relative<= ...
        options.LocalResidualTolerance, ...
    "global_kkt_gate_enabled",true, ...
    "global_kkt_correction_triggered", ...
        initialKktRelative>options.ReconstructedKktResidualTolerance, ...
    "initial_reconstructed_kkt_relative_residual",initialKktRelative, ...
    "final_reconstructed_kkt_relative_residual",current.kkt_relative, ...
    "reconstructed_kkt_relative_residual_history",kktHistory, ...
    "combined_gate_history",combinedHistory, ...
    "both_targets_met",bothTargetsMet,"stop_reason",stopReason, ...
    "core_residual_tolerance",options.LocalResidualTolerance, ...
    "reconstructed_kkt_residual_tolerance", ...
        options.ReconstructedKktResidualTolerance, ...
    "compensated_accumulation_used", ...
        options.CompensatedCoreAccumulation, ...
    "daily_additional_factorization_count",0, ...
    "core_additional_factorization_count",0, ...
    "retained_core_factor_reused",true, ...
    "retained_daily_factors_reused", ...
        recovery.diagnostics.unpromoted_daily_factors_reused, ...
    "complete_kkt_factorization_count",0, ...
    "complete_kkt_solved",false, ...
    "adaptive_delayed_inequality_used",true, ...
    "delayed_inequality_day_ids",construction.day_ids);

coreSolution = current.core_solution;
expandedBorder = struct("matrix",sparse(matrix),"rhs",rhs, ...
    "solution",solution,"dimension",size(matrix,1), ...
    "base_dimension",layout.base_dimension, ...
    "inequality_dimension",layout.inequality_dimension, ...
    "day_ids",construction.day_ids, ...
    "factorization_method","equilibrated_sparse_lu", ...
    "construction",construction);
core = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "linearization_identity",lin.identity, ...
    "matrix",sparse(diagnosticCoreMatrix),"rhs",diagnosticCoreRhs, ...
    "solution",coreSolution,"delta_q",coreSolution(1:14), ...
    "delta_rho",coreSolution(15:16),"factor",factor, ...
    "direct_daily_correction",correction,"dimension",16, ...
    "expanded_border",expandedBorder, ...
    "diagnostic_reduced_core_not_direction_source",true);

result = struct("core",core,"recovery",recovery, ...
    "kkt_relative",current.kkt_relative, ...
    "kkt_maximum",current.kkt_maximum, ...
    "correction",correction,"timing",timing, ...
    "diagnostics",construction);
end

function value = targets_met(candidate,options)
value = candidate.expanded_relative<=options.LocalResidualTolerance && ...
    candidate.kkt_relative<=options.ReconstructedKktResidualTolerance;
end

function [matrix,rhs] = aggregate_responses( ...
        partition,responses,includedPositions,useCompensated)
matrix = partition.global.matrix;
rhs = partition.global.rhs;
if useCompensated
    matrix = full(matrix);
    rhs = full(rhs);
    matrixCompensation = zeros(size(matrix),"like",matrix);
    rhsCompensation = zeros(size(rhs),"like",rhs);
end
for position = reshape(includedPositions,1,[])
    responsePosition = find([responses.day_id]== ...
        partition.day(position).day_id,1);
    assert(isscalar(responsePosition), ...
        "stageB2C:delayedInequality:ResponseMap", ...
        "A daily response is missing from expanded-border assembly.");
    matrixContribution = ...
        -responses(responsePosition).schur_matrix_contribution;
    rhsContribution = -responses(responsePosition).schur_rhs_contribution;
    if useCompensated
        [matrix,matrixCompensation] = compensated_add( ...
            matrix,matrixCompensation,full(matrixContribution));
        [rhs,rhsCompensation] = compensated_add( ...
            rhs,rhsCompensation,full(rhsContribution));
    else
        matrix = matrix+matrixContribution;
        rhs = rhs+rhsContribution;
    end
end
end

function [matrix,rhs,layout,audit] = build_expanded_border( ...
        lin,partition,problemPositions,borderMatrix,borderRhs, ...
        symmetryTolerance)
contract = partition.contract;
nProblem = numel(problemPositions);
localRanges = cell(nProblem,1);
inequalityRows = cell(nProblem,1);
inequalityLocalRanges = cell(nProblem,1);
dayIds = zeros(1,nProblem);
cursor = 0;
for k = 1:nProblem
    day = partition.day(problemPositions(k));
    localRanges{k} = cursor+(1:day.dimension);
    cursor = cursor+day.dimension;
    dayIds(k) = day.day_id;
end
globalRange = cursor+(1:partition.global.dimension);
baseDimension = cursor+partition.global.dimension;

totalInequality = 0;
for k = 1:nProblem
    position = problemPositions(k);
    rows = [vertcat(contract.ineq_by_day_hour{position,:}); ...
        contract.water_by_day{position}];
    inequalityRows{k} = rows(:);
    inequalityLocalRanges{k} = totalInequality+(1:numel(rows));
    totalInequality = totalInequality+numel(rows);
end
assert(numel(unique(vertcat(inequalityRows{:})))==totalInequality, ...
    "stageB2C:delayedInequality:InequalityOverlap", ...
    "Problem-day inequality row sets overlap.");

referenceMatrix = sparse(baseDimension,baseDimension);
referenceRhs = zeros(baseDimension,1);
baseMatrix = sparse(baseDimension,baseDimension);
baseRhs = zeros(baseDimension,1);
embeddedJacobian = sparse(totalInequality,baseDimension);
inverseTheta = zeros(totalInequality,1);
theta = zeros(totalInequality,1);
phi = zeros(totalInequality,1);
otherTouchingCount = zeros(1,nProblem);
for k = 1:nProblem
    position = problemPositions(k);
    day = partition.day(position);
    localRange = localRanges{k};
    rows = inequalityRows{k};
    inequalityRange = inequalityLocalRanges{k};
    referenceMatrix(localRange,localRange) = day.matrix; %#ok<SPRIX>
    referenceMatrix(localRange,globalRange) = day.coupling; %#ok<SPRIX>
    referenceMatrix(globalRange,localRange) = day.coupling.'; %#ok<SPRIX>
    referenceRhs(localRange) = day.rhs;
    baseMatrix(localRange,localRange) = day.matrix; %#ok<SPRIX>
    baseMatrix(localRange,globalRange) = day.coupling; %#ok<SPRIX>
    baseMatrix(globalRange,localRange) = day.coupling.'; %#ok<SPRIX>
    baseRhs(localRange) = day.rhs;

    localCanonical = day.canonical_reduced_indices;
    localPrimalPositions = find(localCanonical<=contract.nx);
    localPrimalCanonical = localCanonical(localPrimalPositions);
    dayJacobianAll = sparse(lin.G(rows,:));
    outside = true(contract.nx,1);
    outside(localPrimalCanonical) = false;
    assert(nnz(dayJacobianAll(:,outside))==0, ...
        "stageB2C:delayedInequality:ExternalCoupling", ...
        "Day %d inequalities couple outside their local primal slice.", ...
        day.day_id);
    dayJacobian = dayJacobianAll(:,localPrimalCanonical);
    touchingRows = find(any(sparse(lin.G(:,localPrimalCanonical)),2));
    otherRows = setdiff(touchingRows,rows,"stable");
    otherTouchingCount(k) = numel(otherRows);
    otherJacobian = sparse(lin.G(otherRows,localPrimalCanonical));
    otherTheta = contract.z(otherRows)./contract.l(otherRows);
    otherPhi = (contract.r_comp(otherRows)- ...
        contract.z(otherRows).*contract.r_ineq(otherRows))./ ...
        contract.l(otherRows);
    directW = sparse(lin.H(localPrimalCanonical,localPrimalCanonical))+ ...
        otherJacobian.'*(spdiags(otherTheta,0,numel(otherRows), ...
        numel(otherRows))*otherJacobian);
    directRhs = -contract.r_dual(localPrimalCanonical)+ ...
        otherJacobian.'*otherPhi;
    embeddedPrimalPositions = localRange(localPrimalPositions);
    baseMatrix(embeddedPrimalPositions,embeddedPrimalPositions) = ...
        directW; %#ok<SPRIX>
    baseRhs(embeddedPrimalPositions) = directRhs;
    embeddedJacobian(inequalityRange,embeddedPrimalPositions) = ...
        dayJacobian; %#ok<SPRIX>
    inverseTheta(inequalityRange) = contract.l(rows)./contract.z(rows);
    theta(inequalityRange) = contract.z(rows)./contract.l(rows);
    phi(inequalityRange) = (contract.r_comp(rows)- ...
        contract.z(rows).*contract.r_ineq(rows))./contract.l(rows);
end
referenceMatrix(globalRange,globalRange) = sparse(borderMatrix);
referenceRhs(globalRange) = borderRhs;
baseMatrix(globalRange,globalRange) = sparse(borderMatrix);
baseRhs(globalRange) = borderRhs;

rebuiltMatrix = baseMatrix+embeddedJacobian.'* ...
    (spdiags(theta,0,totalInequality,totalInequality)*embeddedJacobian);
rebuiltRhs = baseRhs+embeddedJacobian.'*phi;
matrixError = norm(rebuiltMatrix-referenceMatrix,"fro")/ ...
    max(1,norm(referenceMatrix,"fro"));
rhsError = norm(rebuiltRhs-referenceRhs,2)/max(1,norm(referenceRhs,2));
matrix = [baseMatrix,embeddedJacobian.';embeddedJacobian, ...
    -spdiags(inverseTheta,0,totalInequality,totalInequality)];
rhs = [baseRhs;contract.r_comp(vertcat(inequalityRows{:}))./ ...
    contract.z(vertcat(inequalityRows{:}))- ...
    contract.r_ineq(vertcat(inequalityRows{:}))];
symmetryRelative = norm(matrix-matrix.',"fro")/ ...
    max(1,norm(matrix,"fro"));
equivalenceTolerance = max(128*eps,symmetryTolerance);
assert(matrixError<=equivalenceTolerance && ...
    rhsError<=equivalenceTolerance && ...
    symmetryRelative<=symmetryTolerance, ...
    "stageB2C:delayedInequality:Equivalence", ...
    "Expanded-border elimination does not reproduce the reduced equations.");

layout = struct("problem_day_positions",problemPositions, ...
    "day_ids",dayIds,"local_ranges",{localRanges}, ...
    "global_range",globalRange,"base_dimension",baseDimension, ...
    "inequality_rows",{inequalityRows}, ...
    "inequality_local_ranges",{inequalityLocalRanges}, ...
    "inequality_dimension",totalInequality);
audit = struct("used",true,"day_ids",dayIds, ...
    "problem_day_count",nProblem, ...
    "day_inequality_counts",cellfun(@numel,inequalityRows).', ...
    "total_delayed_inequality_count",totalInequality, ...
    "base_dimension",baseDimension, ...
    "expanded_dimension",size(matrix,1), ...
    "reduced_matrix_relative_error",matrixError, ...
    "reduced_rhs_relative_error",rhsError, ...
    "expanded_symmetry_relative_error",symmetryRelative, ...
    "minimum_l_over_z",min(inverseTheta), ...
    "maximum_l_over_z",max(inverseTheta), ...
    "other_touching_inequality_counts",otherTouchingCount, ...
    "factorization_method","equilibrated_sparse_lu", ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "complete_kkt_solved",false);
end

function [retained,diagnostics] = factor_equilibrated_sparse_lu(matrix)
matrix = sparse(matrix);
n = size(matrix,1);
assert(size(matrix,2)==n && sprank(matrix)==n, ...
    "stageB2C:delayedInequality:StructuralRank", ...
    "The expanded border is structurally rank deficient.");
lastwarn("");
timer = tic;
[equilibrationPermutation,rowScale,columnScale] = ...
    equilibrate(matrix,"vector");
scaled = spdiags(rowScale,0,n,n)* ...
    matrix(equilibrationPermutation,:)*spdiags(columnScale,0,n,n);
[L,U,rowPermutation,columnPermutation] = lu(scaled,"vector");
factorSeconds = toc(timer);
[warningMessage,warningId] = lastwarn;
if strlength(string(warningId))>0 || ...
        strlength(string(warningMessage))>0
    error("stageB2C:delayedInequality:FactorWarning", ...
        "Expanded-border LU emitted %s: %s",warningId,warningMessage);
end
assert(all(isfinite(nonzeros(L))) && all(isfinite(nonzeros(U))) && ...
    all(isfinite(rowScale)) && all(rowScale>0) && ...
    all(isfinite(columnScale)) && all(columnScale>0), ...
    "stageB2C:delayedInequality:FactorFinite", ...
    "Expanded-border LU factors or scales are invalid.");
pivots = abs(diag(U));
pivotTolerance = n*eps(max(1,max(pivots)));
retained = struct("L",L,"U",U, ...
    "row_permutation",rowPermutation, ...
    "column_permutation",columnPermutation, ...
    "equilibration_permutation",equilibrationPermutation, ...
    "row_scale",rowScale,"column_scale",columnScale, ...
    "dimension",n);
diagnostics = struct("label","stageB2C_delayed_inequality_border", ...
    "dimension",n,"nnz",nnz(matrix),"rhs_count",1, ...
    "factorization_count",1,"method","equilibrated_sparse_lu", ...
    "object_type","adaptive_delayed_inequality_border", ...
    "structural_rank",n,"symmetry_relative", ...
        norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro")), ...
    "factor_relative_residual", ...
        norm(L*U-scaled(rowPermutation,columnPermutation),"fro")/ ...
        max(1,norm(scaled,"fro")), ...
    "pivot_tolerance",pivotTolerance, ...
    "minimum_absolute_pivot_eigenvalue",min(pivots), ...
    "maximum_absolute_pivot_eigenvalue",max(pivots), ...
    "pivot_dynamic_range",max(pivots)/min(pivots), ...
    "inertia_positive",NaN,"inertia_negative",NaN, ...
    "inertia_zero",nnz(pivots<=pivotTolerance), ...
    "numerical_zero_pivot_continued",false, ...
    "factor_seconds",factorSeconds, ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "dense_day_conversion_used",false);
end

function [solution,diagnostics] = apply_equilibrated_sparse_lu( ...
        retained,matrix,rhs,residualTolerance,refinementPasses)
timer = tic;
solution = apply_lu_once(retained,rhs);
solveSeconds = toc(timer);
residual = matrix*solution-rhs;
relative = norm(residual,2)/max(1,norm(rhs,2));
initialRelative = relative;
passesApplied = 0;
triggered = refinementPasses>0 && relative>residualTolerance;
if triggered
    timer = tic;
    for pass = 1:refinementPasses
        correctionRhs = ...
            rkkt.solver.compute_sparse_residual_double_double( ...
            matrix,solution,rhs);
        correction = apply_lu_once(retained,correctionRhs);
        candidate = solution+correction;
        candidateResidual = matrix*candidate-rhs;
        candidateRelative = norm(candidateResidual,2)/max(1,norm(rhs,2));
        if candidateRelative>=relative
            break
        end
        solution = candidate;
        residual = candidateResidual;
        relative = candidateRelative;
        passesApplied = pass;
        if relative<=residualTolerance
            break
        end
    end
    solveSeconds = solveSeconds+toc(timer);
end
assert(all(isfinite(solution),"all"), ...
    "stageB2C:delayedInequality:SolutionFinite", ...
    "Expanded-border LU solution contains NaN or Inf.");
diagnostics = struct("maximum_column_relative_residual",relative, ...
    "initial_maximum_column_relative_residual",initialRelative, ...
    "frobenius_relative_residual", ...
        norm(residual,"fro")/max(1,norm(rhs,"fro")), ...
    "maximum_absolute_residual",max(abs(residual),[],"all"), ...
    "warning_identifier","","warning_message","", ...
    "warning_present",false,"warning_continued",false, ...
    "blocking_warning_present",false,"solution_finite",true, ...
    "local_residual_tolerance",residualTolerance, ...
    "local_residual_target_met",relative<=residualTolerance, ...
    "refinement_enabled",refinementPasses>0, ...
    "refinement_triggered",triggered, ...
    "refinement_maximum_passes",refinementPasses, ...
    "refinement_passes_applied",passesApplied, ...
    "solve_seconds",solveSeconds, ...
    "refinement_additional_factorization_count",0, ...
    "additional_factorization_count",0, ...
    "retained_factor_reused",true,"direct_final_rhs_solve",true);
end

function solution = apply_lu_once(retained,rhs)
transformed = retained.row_scale.* ...
    rhs(retained.equilibration_permutation,:);
work = retained.L\transformed(retained.row_permutation,:);
work = retained.U\work;
permuted = zeros(size(rhs),"like",rhs);
permuted(retained.column_permutation,:) = work;
solution = retained.column_scale.*permuted;
end

function factor = complete_factor_diagnostics(base,solve,rhs)
factor = base;
factor.rhs_count = size(rhs,2);
factor.maximum_column_relative_residual = ...
    solve.maximum_column_relative_residual;
factor.initial_maximum_column_relative_residual = ...
    solve.initial_maximum_column_relative_residual;
factor.frobenius_relative_residual = solve.frobenius_relative_residual;
factor.maximum_absolute_residual = solve.maximum_absolute_residual;
factor.warning_identifier = solve.warning_identifier;
factor.warning_message = solve.warning_message;
factor.warning_present = solve.warning_present;
factor.warning_continued = solve.warning_continued;
factor.blocking_warning_present = solve.blocking_warning_present;
factor.solution_finite = solve.solution_finite;
factor.local_residual_tolerance = solve.local_residual_tolerance;
factor.local_residual_target_met = solve.local_residual_target_met;
factor.acceptance_scope = "expanded_border_and_reconstructed_kkt";
factor.solve_seconds = solve.solve_seconds;
factor.refinement_enabled = solve.refinement_enabled;
factor.refinement_triggered = solve.refinement_triggered;
factor.refinement_maximum_passes = solve.refinement_maximum_passes;
factor.refinement_passes_applied = solve.refinement_passes_applied;
factor.refinement_additional_factorization_count = 0;
factor.regularization_used = false;
factor.pseudoinverse_used = false;
factor.dense_day_conversion_used = false;
end

function [candidate,recovery,timing] = evaluate_candidate( ...
        lin,partition,retainedFactors,problemPositions,layout, ...
        matrix,rhs,solution,residualTolerance,kktTolerance,refinementPasses)
contract = partition.contract;
expandedResidual = matrix*solution-rhs;
expandedRelative = norm(expandedResidual,2)/max(1,norm(rhs,2));
coreSolution = solution(layout.global_range);
recoveryTimer = tic;
reducedDirection = zeros(contract.nx+contract.neq,1);
written = false(size(reducedDirection));
globalIndices = partition.global.canonical_reduced_indices;
reducedDirection(globalIndices) = coreSolution;
written(globalIndices) = true;
dailySolutions = cell(contract.n_days,1);
deltaQDay = cell(contract.n_days,1);
deltaPi = cell(contract.n_days,1);
directDiagnostics = cell(contract.n_days,1);
for d = 1:contract.n_days
    day = partition.day(d);
    problemIndex = find(problemPositions==d,1);
    if isempty(problemIndex)
        finalRhs = day.rhs-day.coupling*coreSolution;
        [local,directDiagnostics{d}] = ...
            rkkt.solver.apply_stage_b2c_daily_joint_factor( ...
            retainedFactors{d},day.matrix,finalRhs, ...
            "stageB2C_delayed_recovery_day_"+string(day.day_id), ...
            ResidualTolerance=residualTolerance, ...
            RefinementPasses=refinementPasses, ...
            ContinueNumericalPivotWarning=true);
    else
        localRange = layout.local_ranges{problemIndex};
        local = solution(localRange);
        localResidual = expandedResidual(localRange);
        localRelative = norm(localResidual,2)/max(1,norm(rhs(localRange),2));
        directDiagnostics{d} = promoted_daily_diagnostic( ...
            day.day_id,localRelative,max(abs(localResidual)), ...
            residualTolerance,refinementPasses);
    end
    directDiagnostics{d}.day_id = day.day_id;
    indices = day.canonical_reduced_indices;
    assert(~any(written(indices)), ...
        "stageB2C:delayedInequality:RecoveryOverlap", ...
        "Day %d overlaps an already recovered slice.",day.day_id);
    reducedDirection(indices) = local;
    written(indices) = true;
    dailySolutions{d} = local;
    deltaQDay{d} = local(day.q_day_local_positions);
    deltaPi{d} = local(day.pi_day_local_positions);
end
assert(all(written),"stageB2C:delayedInequality:RecoveryCoverage", ...
    "Expanded-border recovery did not fill the reduced direction.");
deltaXi = reducedDirection(1:contract.nx);
deltaY = reducedDirection(contract.nx+1:end);
deltaL = -contract.r_ineq-sparse(lin.G)*deltaXi;
deltaZ = (-contract.r_comp-contract.z.*deltaL)./contract.l;
for k = 1:numel(problemPositions)
    rows = layout.inequality_rows{k};
    localRange = layout.inequality_local_ranges{k};
    deltaZ(rows) = solution(layout.base_dimension+localRange);
end
direction = [deltaXi;deltaY;deltaL;deltaZ];
assert(all(isfinite(direction)), ...
    "stageB2C:delayedInequality:RecoveryFinite", ...
    "Expanded-border recovery contains NaN or Inf.");
timing.recovery_seconds = toc(recoveryTimer);

kktTimer = tic;
[kktRelative,kktMaximum] = reconstructed_kkt_residual( ...
    lin,deltaXi,deltaY,deltaL,deltaZ);
timing.reconstructed_kkt_residual_seconds = toc(kktTimer);
dailyDirect = vertcat(directDiagnostics{:});
fixed = rkkt.solver.stage_a_multiday_fixed_zero_evidence(lin.index);
problemMask = false(contract.n_days,1);
problemMask(problemPositions) = true;
recovery = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "linearization_identity",lin.identity,"direction",direction, ...
    "canonical_reduced_direction",reducedDirection, ...
    "components",struct("xi",deltaXi,"y",deltaY,"l",deltaL, ...
        "z",deltaZ,"q",deltaXi(contract.q_global), ...
        "rho",deltaY(contract.y_duration), ...
        "q_day_by_day",{deltaQDay},"pi_by_day",{deltaPi}, ...
        "daily_joint_by_day",{dailySolutions}, ...
        "eta_by_day",{cell(contract.n_days,1)}), ...
    "daily_direct_backsolve",dailyDirect,"fixed_zero",fixed, ...
    "no_full_direction_fallback",true,"full_direction_consumed",false, ...
    "state_update_executed",false, ...
    "diagnostics",struct( ...
        "equality_recovery_residual", ...
            norm(sparse(lin.A)*deltaXi+contract.r_eq,inf), ...
        "slack_recovery_residual", ...
            norm(sparse(lin.G)*deltaXi+deltaL+contract.r_ineq,inf), ...
        "complementarity_recovery_residual", ...
            norm(contract.z.*deltaL+contract.l.*deltaZ+ ...
            contract.r_comp,inf), ...
        "all_daily_direct_factor_backsolve_used",false, ...
        "all_daily_affine_response_recovery_used",false, ...
        "daily_recovery_retained_factor_correction_count",0, ...
        "unpromoted_daily_factors_reused", ...
            all([dailyDirect(~problemMask).retained_factor_reused]), ...
        "additional_factorization_count",0, ...
        "maximum_daily_direct_relative_residual", ...
            max([dailyDirect.maximum_column_relative_residual]), ...
        "adaptive_delayed_inequality_used",true, ...
        "promoted_day_ids",reshape([partition.day(problemMask).day_id],1,[]), ...
        "water_eta_dimension",0,"fixed_zero_exact",fixed.all_exact_zero));
candidate = struct("expanded_residual",expandedResidual, ...
    "expanded_relative",expandedRelative,"core_solution",coreSolution, ...
    "kkt_relative",kktRelative,"kkt_maximum",kktMaximum, ...
    "combined_gate",max(expandedRelative/residualTolerance, ...
        kktRelative/kktTolerance));
end

function diagnostics = promoted_daily_diagnostic( ...
        dayId,relative,maximumAbsolute,residualTolerance,refinementPasses)
diagnostics = struct( ...
    "label","stageB2C_delayed_recovery_day_"+string(dayId), ...
    "rhs_count",1,"maximum_column_relative_residual",relative, ...
    "initial_maximum_column_relative_residual",relative, ...
    "frobenius_relative_residual",relative, ...
    "maximum_absolute_residual",maximumAbsolute, ...
    "warning_identifier","","warning_message","", ...
    "warning_present",false,"warning_continued",false, ...
    "blocking_warning_present",false,"solution_finite",true, ...
    "local_residual_tolerance",residualTolerance, ...
    "local_residual_target_met",relative<=residualTolerance, ...
    "refinement_enabled",refinementPasses>0, ...
    "refinement_triggered",false, ...
    "refinement_maximum_passes",refinementPasses, ...
    "refinement_passes_applied",0,"solve_seconds",0, ...
    "additional_factorization_count",0, ...
    "retained_factor_reused",false,"direct_final_rhs_solve",false, ...
    "regularization_used",false,"pseudoinverse_used",false, ...
    "dense_day_conversion_used",false);
end

function [relative,maximum] = reconstructed_kkt_residual( ...
        lin,dx,dy,dl,dz)
residual = [ ...
    sparse(lin.H)*dx+sparse(lin.A).'*dy+sparse(lin.G).'*dz+lin.r_dual
    sparse(lin.A)*dx+lin.r_eq
    sparse(lin.G)*dx+dl+lin.r_ineq
    lin.z.*dl+lin.l.*dz+lin.r_comp];
rhsNorm = norm([lin.r_dual;lin.r_eq;lin.r_ineq;lin.r_comp],2);
relative = norm(residual,2)/max(1,rhsNorm);
maximum = max(abs(residual));
end

function [sumValue,compensation] = compensated_add( ...
        sumValue,compensation,value)
adjusted = value-compensation;
candidate = sumValue+adjusted;
compensation = (candidate-sumValue)-adjusted;
sumValue = candidate;
end
