function core = solve_stage_b2b_core16_ldl(partition,aggregation,options)
%SOLVE_STAGE_B2B_CORE16_LDL Solve the sparse 16-by-16 global core.
arguments
    partition (1,1) struct
    aggregation (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double = 0
    options.UseCongruenceScaling (1,1) logical = false
    options.EquilibrationPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 8
end
assert(string(partition.stage_id)=="stage_B" && string(aggregation.stage_id)=="stage_B" && ...
    isequal(partition.linearization_identity,aggregation.linearization_identity), ...
    "stageB2B:core:Identity","Core inputs do not share identity.");
assert(aggregation.order_invariant_passed, ...
    "stageB2B:core:DayOrder","Day responses must be sorted before summation.");
matrix=[partition.global.Q+aggregation.S_sum,partition.global.R.'; ...
    partition.global.R,sparse(2,2)];
rhs=[partition.global.b_q+aggregation.gamma_sum;-partition.global.r_duration];
assert(isequal(size(matrix),[16,16]),"stageB2B:core:Dimension", ...
    "B-2B global core must be exactly 16-by-16.");
factor=rkkt.solver.factor_symmetric_ldl(matrix,"stageB2B_global_core_16", ...
    options.SymmetryTolerance,UseCongruenceScaling=options.UseCongruenceScaling, ...
    EquilibrationPasses=options.EquilibrationPasses);
[initialSolution,solveDiagnostics]=rkkt.solver.solve_with_ldl_factor( ...
    factor,rhs,"stageB2B_global_core_rhs");
[solution,refinementDiagnostics]=rkkt.solver.refine_with_retained_ldl_factor( ...
    factor,matrix,rhs,initialSolution, ...
    MaxPasses=options.ResidualRefinementMaxPasses, ...
    Label="stageB2B_global_core_16");
residual=matrix*solution-rhs;
assert(norm(residual,2)/max(1,norm(rhs,2))<=1e-10,"stageB2B:core:Residual", ...
    "B-2B 16-D core residual exceeded 1e-10.");
core=struct("stage_id","stage_B","milestone_id",partition.milestone_id, ...
    "linearization_identity",partition.linearization_identity,"matrix",sparse(matrix), ...
    "rhs",rhs,"solution",solution,"delta_q",solution(1:14), ...
    "delta_rho",solution(15:16),"factor",strip_factor(factor), ...
    "diagnostics",struct("dimension",16,"relative_residual",norm(residual,2)/max(1,norm(rhs,2)), ...
        "max_absolute_residual",max(abs(residual)), ...
        "symmetry_relative",norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro")), ...
        "solve",solveDiagnostics,"residual_refinement",refinementDiagnostics, ...
        "factor_refinement_passes",options.ResidualRefinementMaxPasses, ...
        "congruence_scaling_used",options.UseCongruenceScaling, ...
        "equilibration_passes",options.EquilibrationPasses*options.UseCongruenceScaling));
end
function s=strip_factor(f)
names=["matrix","factorized_operator","factorized_operator_original","factorization_matrix","L","D"];
names=names(isfield(f,cellstr(names))); s=rmfield(f,names);
end
