function response = solve_stage_b2b_day_border(day,lin,reduced,options)
%SOLVE_STAGE_B2B_DAY_BORDER Solve one daily chain with an 8-row water border.

arguments
    day (1,1) struct
    lin (1,1) struct
    reduced (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double = 0
    options.UseCongruenceScaling (1,1) logical = false
    options.EquilibrationPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 8
end
assert(isequal(day.linearization_identity,lin.identity), ...
    "stageB2B:day:Identity","Day and linearization identities differ.");
contract = rkkt.solver.stage_b2b_linearization_contract(lin);
if contract.milestone_id=="B-2C"
    response = rkkt.solver.solve_stage_b2c_day_ldl(day,lin,reduced, ...
        ResidualRefinementMaxPasses=options.ResidualRefinementMaxPasses);
    return
end
thomas = rkkt.solver.solve_block_thomas_ldl(day, ...
    "SymmetryTolerance",options.SymmetryTolerance, ...
    "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
    "UseCongruenceScaling",options.UseCongruenceScaling, ...
    "EquilibrationPasses",options.EquilibrationPasses);
T = sparse(day.water.T);
Uwater = T.';
[extra,extraDiagnostics] = rkkt.solver.apply_stage_b2b_retained_chain_rhs( ...
    day,thomas,Uwater, ...
    "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
    "Label","stageB2B_day_"+string(day.day_id)+"_extra_rhs", ...
    "UseExtendedResidual",contract.milestone_id=="B-2C");
a0 = thomas.stacked_solution(:,1);
U0 = thomas.stacked_solution(:,2:15);
V = extra;
Dinv = day.water.Dinv;
phi = day.water.phi;
border = Dinv + T*V;
borderRelativeSymmetry = norm(border-border.',"fro")/max(1,norm(border,"fro"));
assert(borderRelativeSymmetry<=options.SymmetryTolerance, ...
    "stageB2B:day:BorderAsymmetry", ...
    "Day %d water border symmetry %.17g exceeds %.17g.", ...
    day.day_id,borderRelativeSymmetry,options.SymmetryTolerance);
% Border is only 8-by-8.  It is the explicit daily augmentation, not a
% black-box Schur solve and not an inverse.
borderLabel = "stageB2B_day_"+string(day.day_id)+"_water_border";
if options.ResidualRefinementMaxPasses==0 && ...
        ~options.UseCongruenceScaling
    % Preserve the already accepted B-2B numerical path exactly.  B-2C
    % explicitly selects the stable-v2 branch below (three passes and
    % congruence scaling), so the historical zero-pass path is not changed.
    borderFactor = rkkt.solver.factor_symmetric_ldl( ...
        border,borderLabel,options.SymmetryTolerance);
else
    borderFactor = rkkt.solver.factor_symmetric_ldl(border,borderLabel, ...
        options.SymmetryTolerance, ...
        UseCongruenceScaling=options.UseCongruenceScaling, ...
        EquilibrationPasses=options.EquilibrationPasses);
end
etaRhs = [T*a0-Dinv*phi,T*U0];
[etaInitial,borderSolveDiagnostics] = rkkt.solver.solve_with_ldl_factor(borderFactor,etaRhs, ...
    "stageB2B_day_"+string(day.day_id)+"_border_rhs");
[etaSolutions,borderRefinement] = rkkt.solver.refine_with_retained_ldl_factor( ...
    borderFactor,border,etaRhs,etaInitial, ...
    MaxPasses=options.ResidualRefinementMaxPasses, ...
    Label="stageB2B_day_"+string(day.day_id)+"_border");
augmentedOperator = [day.M,Uwater;Uwater.',-Dinv];
augmentedRhs = [day.r_v,day.B;Dinv*phi,sparse(8,14)];
[augmentedSolution,augmentedRefinement] = ...
    rkkt.solver.refine_stage_b2b_augmented_day_solution( ...
    day,thomas,borderFactor,V,augmentedRhs, ...
    [[a0,U0]-V*etaSolutions;etaSolutions], ...
    MaxPasses=options.ResidualRefinementMaxPasses, ...
    MinimumAttemptedPasses=double( ...
        options.ResidualRefinementMaxPasses>0), ...
    UseExtendedResidual=contract.milestone_id=="B-2C");
nChain = size(day.M,1);
a = augmentedSolution(1:nChain,1);
U = augmentedSolution(1:nChain,2:15);
eta0 = augmentedSolution(nChain+1:end,1);
etaQ = augmentedSolution(nChain+1:end,2:15);
augResidual = augmentedOperator*augmentedSolution-augmentedRhs;
chainResidual = day.M*[a,U]+Uwater*[eta0,etaQ]-[day.r_v,day.B];
borderResidual = border*[eta0,etaQ]-etaRhs;
assert(norm(augResidual,"fro")/max(1,norm(augmentedRhs,"fro"))<=1e-10, ...
    "stageB2B:day:AugmentedResidual", ...
    "Day %d augmented bordered chain residual %.17g exceeded 1e-10.", ...
    day.day_id,norm(augResidual,"fro")/max(1,norm(augmentedRhs,"fro")));

S = day.C-day.B.'*U;
c = day.r_q_day-day.B.'*a;
beta = -day.r_binding;
gamma = c-S*beta;
response = struct("stage_id","stage_B", ...
    "milestone_id",contract.milestone_id,"linearization_identity",lin.identity, ...
    "day_id",day.day_id,"a",a,"U",U, ...
    "a_by_hour",{split_by_hour(a,day.block_offsets)}, ...
    "U_by_hour",{split_matrix_by_hour(U,day.block_offsets)}, ...
    "S",sparse(S),"c",c,"beta",beta,"gamma",gamma, ...
    "eta0",eta0,"etaQ",etaQ, ...
    "eta_by_hour",{split_by_hour(eta0,[])}, ...
    "water_border",border,"water_border_factor",strip_factor(borderFactor), ...
    "diagnostics",struct( ...
        "chain_dimension",size(day.M,1), ...
        "border_dimension",8,"augmented_dimension",size(day.M,1)+8, ...
        "day_response_dimension",14,"rhs_count_physical",1, ...
        "capacity_rhs_count",14,"border_rhs_count",8, ...
        "total_chain_rhs_count",23, ...
        "chain_relative_residual",norm(chainResidual,"fro")/max(1,norm([day.r_v,day.B],"fro")), ...
        "extra_rhs_relative_residual",norm(day.M*V-Uwater,"fro")/max(1,norm(Uwater,"fro")), ...
        "border_relative_residual",norm(borderResidual,"fro")/max(1,norm(etaRhs,"fro")), ...
        "augmented_relative_residual",norm(augResidual,"fro")/max(1,norm(augmentedRhs,"fro")), ...
        "border_symmetry_relative",borderRelativeSymmetry, ...
        "additional_factorization_count",0, ...
        "hourly_water_GtDG_nnz_in_M",day.water.hourly_water_GtDG_nnz_in_M, ...
        "assembly_location",day.water.assembly_location, ...
        "recursive_rhs_contract",reduced.recursive_rhs_contract, ...
        "factor_refinement_passes",options.ResidualRefinementMaxPasses, ...
        "chain_residual_refinement",thomas.diagnostics.residual_refinement, ...
        "extra_rhs_residual_refinement",extraDiagnostics.residual_refinement, ...
        "border_residual_refinement",borderRefinement, ...
        "augmented_residual_refinement",augmentedRefinement, ...
        "border_solve",borderSolveDiagnostics, ...
        "congruence_scaling_used",options.UseCongruenceScaling, ...
        "equilibration_passes",options.EquilibrationPasses*options.UseCongruenceScaling, ...
        "no_full_direction_fallback",true));
end

function cells = split_by_hour(value,offsets)
if isempty(offsets), cells={value}; return; end
n = height(offsets); cells=cell(n,1);
for k=1:n, cells{k}=value(offsets.start_index(k):offsets.end_index(k)); end
end
function cells = split_matrix_by_hour(value,offsets)
n=height(offsets); cells=cell(n,1);
for k=1:n, cells{k}=value(offsets.start_index(k):offsets.end_index(k),:); end
end
function s = strip_factor(f)
names=["matrix","factorized_operator","factorized_operator_original", ...
    "factorization_matrix","L","D"];
names=names(isfield(f,cellstr(names))); s=rmfield(f,names);
end
