function result = solve_stage_b2c_daily_joint_direction(lin,options)
%SOLVE_STAGE_B2C_DAILY_JOINT_DIRECTION Solve one formal Newton direction.
%
% Route:
%   ordinary day responses -> 16-D core, except that a day whose corrected
%   multiple-RHS residual misses the local target keeps its inequality dz
%   variables in one mathematically equivalent expanded border. Both routes
%   finish with the reconstructed complete-KKT residual gate.

arguments
    lin (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-10
    options.LocalResidualTolerance (1,1) double = 1e-10
    options.ReconstructedKktResidualTolerance (1,1) double = 1e-8
    options.RefinementPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.CoreConsistencyMaximumPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.CompensatedCoreAccumulation (1,1) logical = false
    options.DailyJointStructureTemplate (1,1) struct = struct()
    options.JointMicroborderEnabled (1,1) logical = true
    options.JointMicroborderDegeneracyTolerance (1,1) double = 1e-12
    options.JointMicroborderPrecisionDigits (1,1) double ...
        {mustBeInteger,mustBePositive} = 50
    options.JointMicroborderResponseRefinementMaximumPasses (1,1) double ...
        {mustBeInteger,mustBePositive} = 32
    options.DayResponseExecutionMode (1,1) string {mustBeMember( ...
        options.DayResponseExecutionMode,["serial","parallel_processes"])} = ...
        "serial"
    options.ParallelWorkerCount (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
assert(options.RefinementPasses<=3, ...
    "stageB2C:dailyJoint:RefinementPassLimit", ...
    "Daily-joint residual refinement permits at most three passes.");
assert(options.CoreConsistencyMaximumPasses<=10, ...
    "stageB2C:dailyJoint:CoreConsistencyPassLimit", ...
    "The 16-D core consistency correction permits at most ten passes.");

totalTimer = tic;
parallelDayResponsesExecuted = false;
parallelWorkerCount = 0;
timer = tic;
reduced = rkkt.solver.eliminate_stage_b2c_all_inequality_directions(lin);
timing.elimination_seconds = toc(timer);
assert(reduced.symmetry_relative<=options.SymmetryTolerance, ...
    "stageB2C:dailyJoint:ReducedSymmetry", ...
    "Fully eliminated W symmetry error %.17g exceeds %.17g.", ...
    reduced.symmetry_relative,options.SymmetryTolerance);

timer = tic;
partition = rkkt.solver.partition_stage_b2c_daily_joint_system( ...
    lin,reduced,StructureTemplate=options.DailyJointStructureTemplate);
timing.partition_seconds = toc(timer);

timer = tic;
globalPhysicalCore = ...
    rkkt.solver.build_stage_b2c_global_physical_core_base(lin,partition);
timing.global_physical_core_seconds = toc(timer);
assert(globalPhysicalCore.symmetry_relative<=options.SymmetryTolerance, ...
    "stageB2C:dailyJoint:GlobalPhysicalSymmetry", ...
    "The physical 16-D global base symmetry error %.17g exceeds %.17g.", ...
    globalPhysicalCore.symmetry_relative,options.SymmetryTolerance);

if options.JointMicroborderEnabled
    timer = tic;
    jointCandidate = rkkt.solver.detect_stage_b2c_joint_microborder( ...
        lin,partition,repmat(struct(),0,1),cell(0,1),zeros(0,1), ...
        PreemptiveActiveSetDetection=true, ...
        DegeneracyTolerance=options.JointMicroborderDegeneracyTolerance, ...
        RelationResidualTolerance=max(4096*eps, ...
            options.LocalResidualTolerance^2));
    timing.joint_microborder_detection_seconds = toc(timer);
else
    jointCandidate = disabled_joint_microborder_candidate();
    timing.joint_microborder_detection_seconds = 0;
end
jointMicroborderUsed = jointCandidate.used;
if jointMicroborderUsed
    micro = rkkt.solver.solve_stage_b2c_joint_microborder_direction( ...
        lin,jointCandidate,SymmetryTolerance=options.SymmetryTolerance, ...
        LocalResidualTolerance=options.LocalResidualTolerance, ...
        ReconstructedKktResidualTolerance= ...
            options.ReconstructedKktResidualTolerance, ...
        RefinementPasses=options.RefinementPasses, ...
        ResponseRefinementMaximumPasses= ...
            options.JointMicroborderResponseRefinementMaximumPasses, ...
        VpaDigits=options.JointMicroborderPrecisionDigits);
    partition = micro.partition;
    responses = micro.responses;
    problemDayMask = false(numel(responses),1);
    adaptiveDelayedInequalityUsed = false;
    core = micro.core;
    recovery = micro.recovery;
    candidateKktRelative = micro.kkt_relative;
    candidateKktMaximum = micro.kkt_maximum;
    coreCorrection = micro.correction;
    timing.daily_response_seconds = ...
        micro.diagnostics.ordinary_response_seconds+ ...
        micro.diagnostics.problem_day_factorization_seconds+ ...
        micro.diagnostics.problem_day_affine_refinement_seconds;
    timing.core_seconds = micro.timing.core_seconds;
    timing.recovery_seconds = micro.timing.recovery_seconds;
    timing.final_kkt_residual_seconds = ...
        micro.timing.reconstructed_kkt_residual_seconds;
    adaptiveDiagnostics = struct("used",false, ...
        "day_ids",zeros(1,0),"problem_day_count",0, ...
        "day_inequality_counts",zeros(1,0), ...
        "total_delayed_inequality_count",0,"base_dimension",16, ...
        "expanded_dimension",16,"regularization_used",false, ...
        "pseudoinverse_used",false,"complete_kkt_solved",false);
    jointMicroborderDiagnostics = micro.diagnostics;
else
    timer = tic;
    if options.DayResponseExecutionMode=="parallel_processes"
        [responseCells,retainedFactorCells,parallelDiagnostics] = ...
            rkkt.solver.solve_stage_b2c_daily_joint_responses_parallel( ...
            partition.day,WorkerCount=options.ParallelWorkerCount, ...
            SymmetryTolerance=options.SymmetryTolerance, ...
            ResidualTolerance=options.LocalResidualTolerance, ...
            RefinementPasses=options.RefinementPasses);
        parallelDayResponsesExecuted = true;
        parallelWorkerCount = parallelDiagnostics.worker_count;
    else
        responseCells = cell(numel(partition.day),1);
        retainedFactorCells = cell(numel(partition.day),1);
        for d = 1:numel(partition.day)
            [responseCells{d},retainedFactorCells{d}] = ...
                rkkt.solver.solve_stage_b2c_daily_joint_day( ...
                partition.day(d), ...
                SymmetryTolerance=options.SymmetryTolerance, ...
                ResidualTolerance=options.LocalResidualTolerance, ...
                RefinementPasses=options.RefinementPasses);
        end
    end
    responses = vertcat(responseCells{:});
    timing.daily_response_seconds = toc(timer);
    problemDayMask = arrayfun(@(value) ...
        value.factor.maximum_column_relative_residual> ...
        options.LocalResidualTolerance,responses);
    problemDayPositions = find(problemDayMask(:));
    adaptiveDelayedInequalityUsed = ~isempty(problemDayPositions);
    jointMicroborderDiagnostics = struct( ...
        "used",false,"candidate",jointCandidate);
    if adaptiveDelayedInequalityUsed
        adaptive = rkkt.solver.solve_stage_b2c_delayed_inequality_border( ...
            lin,partition,responses,retainedFactorCells, ...
            problemDayPositions, ...
            SymmetryTolerance=options.SymmetryTolerance, ...
            LocalResidualTolerance=options.LocalResidualTolerance, ...
            ReconstructedKktResidualTolerance= ...
                options.ReconstructedKktResidualTolerance, ...
            RefinementPasses=options.RefinementPasses, ...
            ConsistencyMaximumPasses= ...
                options.CoreConsistencyMaximumPasses, ...
            CompensatedCoreAccumulation= ...
                options.CompensatedCoreAccumulation);
        core = adaptive.core;
        recovery = adaptive.recovery;
        candidateKktRelative = adaptive.kkt_relative;
        candidateKktMaximum = adaptive.kkt_maximum;
        coreCorrection = adaptive.correction;
        timing.core_seconds = adaptive.timing.core_seconds;
        timing.recovery_seconds = adaptive.timing.recovery_seconds;
        timing.final_kkt_residual_seconds = ...
            adaptive.timing.reconstructed_kkt_residual_seconds;
        adaptiveDiagnostics = adaptive.diagnostics;
    else
    timer = tic;
    [coreMatrix,coreRhs] = assemble_core_system( ...
        globalPhysicalCore,responses,options.CompensatedCoreAccumulation);
    [coreSolution,coreFactor,coreRetainedFactor] = ...
        rkkt.solver.solve_stage_b2c_daily_joint_block( ...
            coreMatrix,coreRhs,"stageB2C_daily_joint_core16", ...
            SymmetryTolerance=options.SymmetryTolerance, ...
            ResidualTolerance=options.LocalResidualTolerance, ...
            RefinementPasses=options.RefinementPasses);
    timing.core_seconds = toc(timer);
    [coreSolution,recovery,candidateKktRelative,candidateKktMaximum, ...
        coreCorrection,correctionTiming] = ...
        correct_core_for_reconstructed_kkt( ...
            lin,partition,globalPhysicalCore,responses,retainedFactorCells, ...
            coreRetainedFactor,coreMatrix,coreRhs,coreSolution, ...
            options.LocalResidualTolerance, ...
            options.ReconstructedKktResidualTolerance, ...
            options.RefinementPasses, ...
            options.CoreConsistencyMaximumPasses, ...
            options.CompensatedCoreAccumulation);
    timing.core_seconds = timing.core_seconds+correctionTiming.core_seconds;
    timing.recovery_seconds = correctionTiming.recovery_seconds;
    timing.final_kkt_residual_seconds = ...
        correctionTiming.reconstructed_kkt_residual_seconds;
    core = struct("stage_id","stage_B", ...
        "milestone_id","B-2C", ...
        "linearization_identity",lin.identity, ...
        "matrix",sparse(coreMatrix),"rhs",coreRhs, ...
        "solution",coreSolution,"delta_q",coreSolution(1:14), ...
        "delta_rho",coreSolution(15:16),"factor",coreFactor, ...
        "direct_daily_correction",coreCorrection, ...
        "dimension",16);
    core.global_physical_base = globalPhysicalCore;
        adaptiveDiagnostics = struct("used",false,"day_ids",zeros(1,0), ...
        "problem_day_count",0,"day_inequality_counts",zeros(1,0), ...
        "total_delayed_inequality_count",0,"base_dimension",16, ...
        "expanded_dimension",16, ...
        "reduced_matrix_relative_error",0, ...
        "reduced_rhs_relative_error",0, ...
        "expanded_symmetry_relative_error",0, ...
        "factorization_method","sparse_pivoted_ldl", ...
        "regularization_used",false,"pseudoinverse_used",false, ...
            "complete_kkt_solved",false);
    end
end
assert(candidateKktRelative<=options.ReconstructedKktResidualTolerance, ...
    "stageB2C:dailyJoint:FinalKktResidual", ...
    "The reconstructed direction KKT residual %.17g exceeds %.17g.", ...
    candidateKktRelative,options.ReconstructedKktResidualTolerance);
assert(coreCorrection.final_relative_residual<= ...
    options.LocalResidualTolerance, ...
    "stageB2C:dailyJoint:CoreConsistencyResidual", ...
    "The direct-response core residual %.17g exceeds %.17g.", ...
    coreCorrection.final_relative_residual, ...
    options.LocalResidualTolerance);
timing.total_seconds = toc(totalTimer);
jointMicroborderDayIds = zeros(1,0);
if jointMicroborderUsed
    jointMicroborderDayIds = jointCandidate.day_id;
end

result = struct();
result.stage_id = "stage_B";
result.milestone_id = "B-2C";
result.linearization_identity = lin.identity;
result.direction = recovery.direction;
result.components = recovery.components;
if isfield(recovery,"components_high")
    result.components_high = recovery.components_high;
    result.components_low = recovery.components_low;
else
    result.components_high = recovery.components;
    result.components_low = struct( ...
        "xi",zeros(size(recovery.components.xi)), ...
        "y",zeros(size(recovery.components.y)), ...
        "l",zeros(size(recovery.components.l)), ...
        "z",zeros(size(recovery.components.z)));
end
result.reduced = reduced;
result.partition = partition;
result.global_physical_core = globalPhysicalCore;
result.responses = responses;
result.daily_responses = responses;
result.core = core;
result.recovery = recovery;
result.fixed_zero = recovery.fixed_zero;
result.timing = timing;
result.no_full_direction_fallback = true;
result.full_direction_consumed = false;
result.daily_joint_direction_executed = true;
result.full_ipm_executed = false;
result.optimization_executed = false;
result.state_update_executed = false;
result.regularization_used = false;
result.pseudoinverse_used = false;
result.diagnostics = struct( ...
    "daily_response_count",numel(responses), ...
    "daily_response_dimension",14,"global_core_dimension",core.dimension, ...
    "daily_dimensions",reshape([partition.day.dimension],1,[]), ...
    "daily_rhs_counts",reshape([responses.rhs_count],1,[]), ...
    "daily_factorization_counts", ...
        arrayfun(@(value)value.factor.factorization_count,responses), ...
    "daily_minimum_absolute_pivots", ...
        arrayfun(@(value) ...
        value.factor.minimum_absolute_pivot_eigenvalue,responses), ...
    "daily_numerical_zero_pivot_counts", ...
        arrayfun(@(value)value.factor.inertia_zero,responses), ...
    "daily_local_maximum_relative_residuals", ...
        arrayfun(@(value) ...
        value.factor.maximum_column_relative_residual,responses), ...
    "daily_local_residual_targets_met", ...
        arrayfun(@(value)value.factor.local_residual_target_met,responses), ...
    "near_zero_pivot_day_ids", ...
        reshape([responses(arrayfun(@(value)value.factor.inertia_zero>0, ...
        responses)).day_id],1,[]), ...
    "continued_warning_day_ids", ...
        reshape([responses(arrayfun(@(value) ...
        value.factor.warning_continued,responses)).day_id],1,[]), ...
    "candidate_kkt_relative_residual",candidateKktRelative, ...
    "candidate_kkt_maximum_absolute_residual",candidateKktMaximum, ...
    "daily_direct_factor_backsolve_used", ...
        recovery.diagnostics.all_daily_direct_factor_backsolve_used, ...
    "daily_affine_response_recovery_used", ...
        recovery.diagnostics.all_daily_affine_response_recovery_used, ...
    "daily_recovery_retained_factor_correction_count", ...
        recovery.diagnostics.daily_recovery_retained_factor_correction_count, ...
    "daily_recovery_additional_factorization_count", ...
        recovery.diagnostics.additional_factorization_count, ...
    "daily_recovery_maximum_relative_residual", ...
        recovery.diagnostics.maximum_daily_direct_relative_residual, ...
    "core_direct_daily_correction_passes", ...
        coreCorrection.passes_applied, ...
    "core_direct_daily_correction_final_relative_residual", ...
        coreCorrection.final_relative_residual, ...
    "core_direct_daily_correction_relative_residual_history", ...
        coreCorrection.relative_residual_history, ...
    "core_global_kkt_correction_triggered", ...
        coreCorrection.global_kkt_correction_triggered, ...
    "core_correction_initial_reconstructed_kkt_relative_residual", ...
        coreCorrection.initial_reconstructed_kkt_relative_residual, ...
    "core_correction_reconstructed_kkt_relative_residual_history", ...
        coreCorrection.reconstructed_kkt_relative_residual_history, ...
    "core_correction_combined_gate_history", ...
        coreCorrection.combined_gate_history, ...
    "core_correction_both_targets_met", ...
        coreCorrection.both_targets_met, ...
    "core_correction_stop_reason",coreCorrection.stop_reason, ...
    "core_compensated_accumulation_used", ...
        options.CompensatedCoreAccumulation, ...
    "global_physical_core_used", ...
        ~adaptiveDelayedInequalityUsed || jointMicroborderUsed, ...
    "global_physical_core_matrix_relative_difference", ...
        globalPhysicalCore.canonical_matrix_relative_difference, ...
    "global_physical_core_rhs_relative_difference", ...
        globalPhysicalCore.canonical_rhs_relative_difference, ...
    "local_linear_solve_residual_tolerance", ...
        options.LocalResidualTolerance, ...
    "final_kkt_residual_tolerance", ...
        options.ReconstructedKktResidualTolerance, ...
    "final_kkt_residual_gate_passed",true, ...
    "local_response_residual_is_blocking",false, ...
    "water_eta_dimension",0,"cross_day_nnz",partition.cross_day_nnz, ...
    "full_inequality_elimination", ...
        ~adaptiveDelayedInequalityUsed && ~jointMicroborderUsed, ...
    "adaptive_delayed_inequality_elimination_used", ...
        adaptiveDelayedInequalityUsed, ...
    "adaptive_delayed_inequality_trigger_tolerance", ...
        options.LocalResidualTolerance, ...
    "adaptive_delayed_inequality_day_ids", ...
        reshape([responses(problemDayMask).day_id],1,[]), ...
    "adaptive_delayed_inequality",adaptiveDiagnostics, ...
    "joint_microborder_used",jointMicroborderUsed, ...
    "joint_microborder_scan_enabled",options.JointMicroborderEnabled, ...
    "joint_microborder_scan_executed",options.JointMicroborderEnabled, ...
    "joint_microborder_day_ids",jointMicroborderDayIds, ...
    "joint_microborder_detection",jointCandidate, ...
    "joint_microborder",jointMicroborderDiagnostics, ...
    "joint_microborder_degeneracy_tolerance", ...
        options.JointMicroborderDegeneracyTolerance, ...
    "joint_microborder_precision_digits", ...
        options.JointMicroborderPrecisionDigits, ...
    "day_response_execution_mode",options.DayResponseExecutionMode, ...
    "parallel_day_responses_executed",parallelDayResponsesExecuted, ...
    "parallel_worker_count",parallelWorkerCount, ...
    "high_low_state_update_required",jointMicroborderUsed, ...
    "state_update_contract",conditional_state_update_contract( ...
        jointMicroborderUsed), ...
    "no_full_direction_fallback",true, ...
    "formal_recursive_route",formal_route( ...
        adaptiveDelayedInequalityUsed,jointMicroborderUsed));
end

function candidate = disabled_joint_microborder_candidate()
candidate = struct( ...
    "used",false,"stop_reason","scan_disabled", ...
    "day_position",NaN,"day_id",NaN, ...
    "relation_hours",zeros(0,1),"terminal_hour",NaN, ...
    "equality_coefficients",zeros(0,1), ...
    "inequality_coefficients",zeros(0,1), ...
    "global_inequality_coefficients",zeros(0,1), ...
    "inequality_rows",zeros(0,1),"relation_table",table(), ...
    "factor_mode",zeros(0,1),"factor_pivot_position",NaN, ...
    "factor_pivot_value",NaN,"primal_fraction",NaN, ...
    "mode_alignment",NaN,"runner_up_alignment",NaN, ...
    "relation_residual",NaN,"primal_fraction_tolerance",NaN, ...
    "mode_alignment_tolerance",NaN, ...
    "relation_residual_tolerance",NaN, ...
    "joint_d",NaN,"normalized_joint_d",NaN, ...
    "degeneracy_tolerance",NaN, ...
    "candidate_count_below_tolerance",0, ...
    "detection_method","disabled", ...
    "regularization_used",false,"rank_truncation_used",false, ...
    "model_changed",false);
end

function value = conditional_state_update_contract(jointMicroborderUsed)
if jointMicroborderUsed
    value = "consume_components_high_low_before_final_state_rounding";
else
    value = "binary64_direction_update";
end
end

function value = formal_route(adaptiveDelayedInequalityUsed,jointMicroborderUsed)
if jointMicroborderUsed
    value = "joint_microborder17_high_low_affine_response_final_kkt_gate";
elseif adaptiveDelayedInequalityUsed
    value = "adaptive_delayed_inequality_expanded_border_final_kkt_gate";
else
    value = "all_inequality_daily_joint_final_kkt_residual_gate";
end
end

function [coreSolution,recovery,kktRelative,kktMaximum,diagnostics,timing] = ...
        correct_core_for_reconstructed_kkt( ...
        lin,partition,globalPhysicalCore,responses,retainedFactors, ...
        coreRetainedFactor, ...
        coreMatrix,coreRhs,coreSolution,residualTolerance,kktTolerance, ...
        refinementPasses,configuredMaximumPasses, ...
        useCompensatedAccumulation)
% Reconcile retained-factor daily recovery with both the 16-D core and the
% reconstructed original KKT equations. The complete KKT is measured only;
% it is never factored or used as a direction source.
maximumPasses = configuredMaximumPasses;
if maximumPasses==0
    maximumPasses = max(1,refinementPasses);
end
[current,recovery,evaluationTiming] = evaluate_core_candidate( ...
    lin,partition,globalPhysicalCore,responses,retainedFactors, ...
    coreSolution,coreRhs, ...
    residualTolerance,kktTolerance,refinementPasses, ...
    useCompensatedAccumulation);
timing = evaluationTiming;
initialRelative = current.core_relative;
initialKktRelative = current.kkt_relative;
passesApplied = 0;
passesAttempted = 0;
relativeResidualHistory = initialRelative;
reconstructedKktHistory = initialKktRelative;
combinedGateHistory = current.combined_gate;
dailyAdditionalFactorizationCount = ...
    recovery.diagnostics.additional_factorization_count;
coreAdditionalFactorizationCount = 0;
retainedDailyFactorsReused = ...
    recovery.diagnostics.all_daily_affine_response_recovery_used && ...
    recovery.diagnostics.additional_factorization_count==0;
retainedCoreFactorReused = true;
stopReason = "maximum_passes_reached";
for pass = 1:maximumPasses
    if current.core_relative<=residualTolerance && ...
            current.kkt_relative<=kktTolerance
        stopReason = "both_targets_met";
        break
    end
    timer = tic;
    [correction,correctionDiagnostics] = ...
        rkkt.solver.apply_stage_b2c_daily_joint_factor( ...
        coreRetainedFactor,coreMatrix,-current.core_residual, ...
        "stageB2C_daily_joint_core16_correction", ...
        ResidualTolerance=residualTolerance, ...
        RefinementPasses=refinementPasses);
    timing.core_seconds = timing.core_seconds+toc(timer);
    coreAdditionalFactorizationCount = ...
        coreAdditionalFactorizationCount+ ...
        correctionDiagnostics.additional_factorization_count;
    retainedCoreFactorReused = retainedCoreFactorReused && ...
        correctionDiagnostics.retained_factor_reused;
    candidateSolution = coreSolution+correction;
    [candidate,candidateRecovery,candidateTiming] = ...
        evaluate_core_candidate( ...
        lin,partition,globalPhysicalCore,responses,retainedFactors, ...
        candidateSolution,coreRhs, ...
        residualTolerance,kktTolerance,refinementPasses, ...
        useCompensatedAccumulation);
    timing = add_timing(timing,candidateTiming);
    passesAttempted = pass;
    relativeResidualHistory(end+1) = candidate.core_relative; %#ok<AGROW>
    reconstructedKktHistory(end+1) = candidate.kkt_relative; %#ok<AGROW>
    combinedGateHistory(end+1) = candidate.combined_gate; %#ok<AGROW>
    dailyAdditionalFactorizationCount = ...
        dailyAdditionalFactorizationCount+ ...
        candidateRecovery.diagnostics.additional_factorization_count;
    retainedDailyFactorsReused = retainedDailyFactorsReused && ...
        candidateRecovery.diagnostics.all_daily_affine_response_recovery_used && ...
        candidateRecovery.diagnostics.additional_factorization_count==0;
    if candidate.combined_gate>=current.combined_gate
        stopReason = "combined_gate_did_not_improve";
        break
    end
    coreSolution = candidateSolution;
    current = candidate;
    recovery = candidateRecovery;
    passesApplied = pass;
    if current.core_relative<=residualTolerance && ...
            current.kkt_relative<=kktTolerance
        stopReason = "both_targets_met";
        break
    end
end
kktRelative = current.kkt_relative;
kktMaximum = current.kkt_maximum;
bothTargetsMet = current.core_relative<=residualTolerance && ...
    current.kkt_relative<=kktTolerance;
diagnostics = struct( ...
    "enabled",true,"maximum_passes",maximumPasses, ...
    "passes_attempted",passesAttempted,"passes_applied",passesApplied, ...
    "initial_relative_residual",initialRelative, ...
    "final_relative_residual",current.core_relative, ...
    "relative_residual_history",relativeResidualHistory, ...
    "target_met",current.core_relative<=residualTolerance, ...
    "global_kkt_gate_enabled",true, ...
    "global_kkt_correction_triggered",initialKktRelative>kktTolerance, ...
    "initial_reconstructed_kkt_relative_residual",initialKktRelative, ...
    "final_reconstructed_kkt_relative_residual",current.kkt_relative, ...
    "reconstructed_kkt_relative_residual_history", ...
        reconstructedKktHistory, ...
    "combined_gate_history",combinedGateHistory, ...
    "both_targets_met",bothTargetsMet,"stop_reason",stopReason, ...
    "core_residual_tolerance",residualTolerance, ...
    "reconstructed_kkt_residual_tolerance",kktTolerance, ...
    "compensated_accumulation_used",useCompensatedAccumulation, ...
    "daily_additional_factorization_count", ...
        dailyAdditionalFactorizationCount, ...
    "core_additional_factorization_count", ...
        coreAdditionalFactorizationCount, ...
    "retained_core_factor_reused",retainedCoreFactorReused, ...
    "retained_daily_factors_reused",retainedDailyFactorsReused, ...
    "complete_kkt_factorization_count",0, ...
    "complete_kkt_solved",false);
end

function [candidate,recovery,timing] = evaluate_core_candidate( ...
        lin,partition,globalPhysicalCore,responses,retainedFactors, ...
        coreSolution,coreRhs, ...
        residualTolerance,kktTolerance,refinementPasses, ...
        useCompensatedAccumulation)
core = struct("linearization_identity",lin.identity, ...
    "solution",coreSolution);
timer = tic;
recovery = rkkt.solver.recover_stage_b2c_daily_joint_direction( ...
    lin,partition,responses,core,retainedFactors, ...
    ResidualTolerance=residualTolerance, ...
    RefinementPasses=refinementPasses);
timing.recovery_seconds = toc(timer);
timer = tic;
[kktRelative,kktMaximum] = ...
    reconstructed_kkt_residual(lin,recovery.components);
timing.reconstructed_kkt_residual_seconds = toc(timer);
timer = tic;
coreResidual = recovered_core_residual( ...
    partition,globalPhysicalCore,recovery,coreSolution, ...
    useCompensatedAccumulation);
timing.core_seconds = toc(timer);
coreRelative = norm(coreResidual,2)/max(1,norm(coreRhs,2));
candidate = struct( ...
    "core_residual",coreResidual,"core_relative",coreRelative, ...
    "kkt_relative",kktRelative,"kkt_maximum",kktMaximum, ...
    "combined_gate",max(coreRelative/residualTolerance, ...
        kktRelative/kktTolerance));
end

function residual = recovered_core_residual( ...
        partition,globalPhysicalCore,recovery,coreSolution, ...
        useCompensatedAccumulation)
residual = globalPhysicalCore.matrix_high*coreSolution- ...
    globalPhysicalCore.rhs_high;
if useCompensatedAccumulation
    residual = full(residual);
    compensation = zeros(size(residual),"like",residual);
    [residual,compensation] = compensated_add( ...
        residual,compensation, ...
        globalPhysicalCore.matrix_low*coreSolution- ...
            globalPhysicalCore.rhs_low);
else
    residual = residual+globalPhysicalCore.matrix_low*coreSolution- ...
        globalPhysicalCore.rhs_low;
end
for d = 1:numel(partition.day)
    day = partition.day(d);
    local = recovery.components.daily_joint_by_day{d};
    contribution = day.coupling.'*local;
    if useCompensatedAccumulation
        [residual,compensation] = compensated_add( ...
            residual,compensation,full(contribution));
    else
        residual = residual+contribution;
    end
end
end

function total = add_timing(total,value)
total.core_seconds = total.core_seconds+value.core_seconds;
total.recovery_seconds = total.recovery_seconds+value.recovery_seconds;
total.reconstructed_kkt_residual_seconds = ...
    total.reconstructed_kkt_residual_seconds+ ...
    value.reconstructed_kkt_residual_seconds;
end

function [coreMatrix,coreRhs] = assemble_core_system( ...
        globalPhysicalCore,responses,useCompensatedAccumulation)
coreMatrix = globalPhysicalCore.matrix_high;
coreRhs = globalPhysicalCore.rhs_high;
if useCompensatedAccumulation
    coreMatrix = full(coreMatrix);
    coreRhs = full(coreRhs);
    matrixCompensation = zeros(size(coreMatrix),"like",coreMatrix);
    rhsCompensation = zeros(size(coreRhs),"like",coreRhs);
    [coreMatrix,matrixCompensation] = compensated_add( ...
        coreMatrix,matrixCompensation,globalPhysicalCore.matrix_low);
    [coreRhs,rhsCompensation] = compensated_add( ...
        coreRhs,rhsCompensation,globalPhysicalCore.rhs_low);
else
    coreMatrix = coreMatrix+globalPhysicalCore.matrix_low;
    coreRhs = coreRhs+globalPhysicalCore.rhs_low;
end
for d = 1:numel(responses)
    matrixContribution = -responses(d).schur_matrix_contribution;
    rhsContribution = -responses(d).schur_rhs_contribution;
    if useCompensatedAccumulation
        [coreMatrix,matrixCompensation] = compensated_add( ...
            coreMatrix,matrixCompensation,full(matrixContribution));
        [coreRhs,rhsCompensation] = compensated_add( ...
            coreRhs,rhsCompensation,full(rhsContribution));
    else
        coreMatrix = coreMatrix+matrixContribution;
        coreRhs = coreRhs+rhsContribution;
    end
end
end

function [sumValue,compensation] = compensated_add( ...
        sumValue,compensation,value)
adjusted = value-compensation;
candidate = sumValue+adjusted;
compensation = (candidate-sumValue)-adjusted;
sumValue = candidate;
end

function [relativeResidual,maximumAbsolute] = ...
        reconstructed_kkt_residual(lin,components)
dx = components.xi;
dy = components.y;
dl = components.l;
dz = components.z;
residual = [ ...
    sparse(lin.H)*dx+sparse(lin.A).'*dy+sparse(lin.G).'*dz+lin.r_dual
    sparse(lin.A)*dx+lin.r_eq
    sparse(lin.G)*dx+dl+lin.r_ineq
    lin.z.*dl+lin.l.*dz+lin.r_comp];
rhsNorm = norm([lin.r_dual;lin.r_eq;lin.r_ineq;lin.r_comp],2);
relativeResidual = norm(residual,2)/max(1,rhsNorm);
maximumAbsolute = max(abs(residual));
end
