function response = solve_stage_b2c_day_ldl(day,lin,reduced,options)
%SOLVE_STAGE_B2C_DAY_LDL Solve one bordered day with one sparse LDL.

arguments
    day (1,1) struct
    lin (1,1) struct
    reduced (1,1) struct
    options.ResidualRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 3
end

contract = rkkt.solver.stage_b2b_linearization_contract(lin);
assert(contract.milestone_id=="B-2C" && ...
    isequal(day.linearization_identity,lin.identity));
T = sparse(day.water.T);
Dinv = sparse(day.water.Dinv);
operator = sparse([day.M,T.';T,-Dinv]);
rhs = [day.r_v,day.B;Dinv*day.water.phi,sparse(8,14)];
[solution,factorDiagnostics,refinement] = solve_multiple_rhs( ...
    operator,rhs,options.ResidualRefinementMaxPasses, ...
    "stageB2C_day_"+string(day.day_id));

nChain = size(day.M,1);
a = solution(1:nChain,1);
U = solution(1:nChain,2:15);
eta0 = solution(nChain+1:end,1);
etaQ = solution(nChain+1:end,2:15);
S = day.C-day.B.'*U;
c = day.r_q_day-day.B.'*a;
beta = -day.r_binding;
gamma = c-S*beta;
residual = operator*solution-rhs;
chainResidual = residual(1:nChain,:);
borderResidual = residual(nChain+1:end,:);

response = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "linearization_identity",lin.identity,"day_id",day.day_id, ...
    "a",a,"U",U, ...
    "a_by_hour",{split_by_hour(a,day.block_offsets)}, ...
    "U_by_hour",{split_matrix_by_hour(U,day.block_offsets)}, ...
    "S",sparse(S),"c",c,"beta",beta,"gamma",gamma, ...
    "eta0",eta0,"etaQ",etaQ, ...
    "eta_by_hour",{split_by_hour(eta0,[])}, ...
    "water_border",sparse(operator), ...
    "water_border_factor",factorDiagnostics, ...
    "diagnostics",struct( ...
        "chain_dimension",nChain,"border_dimension",8, ...
        "augmented_dimension",size(operator,1), ...
        "day_response_dimension",14,"rhs_count_physical",1, ...
        "capacity_rhs_count",14,"border_rhs_count",8, ...
        "total_chain_rhs_count",15, ...
        "chain_relative_residual",norm(chainResidual,"fro")/ ...
            max(1,norm(rhs(1:nChain,:),"fro")), ...
        "extra_rhs_relative_residual", ...
            norm(chainResidual(:,2:end),"fro")/ ...
            max(1,norm(rhs(1:nChain,2:end),"fro")), ...
        "border_relative_residual",norm(borderResidual,"fro")/ ...
            max(1,norm(rhs(nChain+1:end,:),"fro")), ...
        "augmented_relative_residual",norm(residual,"fro")/ ...
            max(1,norm(rhs,"fro")), ...
        "border_symmetry_relative", ...
            norm(operator-operator.',"fro")/max(1,norm(operator,"fro")), ...
        "additional_factorization_count",0, ...
        "hourly_water_GtDG_nnz_in_M", ...
            day.water.hourly_water_GtDG_nnz_in_M, ...
        "assembly_location",day.water.assembly_location, ...
        "hourly_elimination_order","sparse_day_pivoted_ldl", ...
        "recursive_rhs_contract",reduced.recursive_rhs_contract, ...
        "factor_refinement_passes",options.ResidualRefinementMaxPasses, ...
        "chain_residual_refinement", ...
            relabel(refinement,"bordered_day_chain"), ...
        "extra_rhs_residual_refinement", ...
            relabel(refinement,"joint_14_capacity_rhs"), ...
        "border_residual_refinement", ...
            relabel(refinement,"joint_water_border"), ...
        "augmented_residual_refinement", ...
            relabel(refinement,"bordered_day_operator"), ...
        "border_solve",factorDiagnostics, ...
        "congruence_scaling_used",true, ...
        "equilibration_passes",0, ...
        "no_full_direction_fallback",true));
end

function [solution,factorDiagnostics,refinement] = ...
        solve_multiple_rhs(operator,rhs,maxPasses,label)
lastwarn("");
[L,D,permutation,C] = ldl(operator,0.5,"vector");
[warningMessage,warningId] = lastwarn;
assert(strlength(string(warningId))==0 && ...
    strlength(string(warningMessage))==0, ...
    "stageB2C:dayLdl:FactorWarning", ...
    "%s factorization emitted %s: %s",label,warningId,warningMessage);
scaled = sparse(C*operator*C);
factorResidual = norm(L*D*L.'-scaled(permutation,permutation),"fro")/ ...
    max(1,norm(scaled,"fro"));
scale = full(diag(C));
solution = apply_factor(L,D,permutation,scale,rhs);
initialMetrics = residual_metrics(operator,solution,rhs);
metrics = initialMetrics;
solutionCandidate=cell(maxPasses+1,1);
metricCandidate=cell(maxPasses+1,1);
solutionCandidate{1}=solution;
metricCandidate{1}=metrics;
history = repmat(history_row(0,metrics,false),maxPasses+1,1);
for pass = 1:maxPasses
    correction = apply_factor( ...
        L,D,permutation,scale,metrics.residual);
    solution = solution+correction;
    metrics = residual_metrics(operator,solution,rhs);
    solutionCandidate{pass+1}=solution;
    metricCandidate{pass+1}=metrics;
    history(pass+1) = history_row(pass,metrics,false);
end
candidateResidual=zeros(maxPasses+1,1);
for candidate=1:maxPasses+1
    candidateResidual(candidate)=full( ...
        metricCandidate{candidate}.maximum_column_relative);
end
[~,selectedCandidate]=min(candidateResidual);
selectedPass=selectedCandidate-1;
solution=solutionCandidate{selectedCandidate};
metrics=metricCandidate{selectedCandidate};
history(selectedCandidate).accepted=true;
attemptedPasses=maxPasses;
stopReason="minimum_extended_residual_selected";
factorDiagnostics = struct("method","sparse_ldl", ...
    "dimension",size(operator,1),"nnz",nnz(operator), ...
    "pivot_tolerance",0.5,"factor_relative_residual",factorResidual, ...
    "warning_id",string(warningId), ...
    "warning_message",string(warningMessage),"warning_present",false);
refinement = struct("enabled",maxPasses>0, ...
    "triggered",maxPasses>0, ...
    "maximum_passes",maxPasses,"passes_attempted",attemptedPasses, ...
    "selected_pass",selectedPass,"stop_reason",stopReason, ...
    "initial_maximum_column_relative", ...
        initialMetrics.maximum_column_relative, ...
    "final_maximum_column_relative",metrics.maximum_column_relative, ...
    "residual_reduction_ratio",metrics.maximum_column_relative/ ...
        max(initialMetrics.maximum_column_relative,realmin), ...
    "rhs_count",size(rhs,2),"additional_factorization_count",0, ...
    "extended_residual_used",true, ...
    "ordinary_frobenius_relative",metrics.frobenius_relative, ...
    "engineering_relative_residual_target_met", ...
        metrics.maximum_column_relative<=1e-10, ...
    "componentwise_backward_error", ...
        metrics.componentwise_backward_error,"history",history);
end

function solution = apply_factor(L,D,permutation,scale,rhs)
transformed = scale.*rhs;
work = L\transformed(permutation,:);
work = solve_pivot_blocks(D,work);
work = L.'\work;
solution = zeros(size(rhs));
solution(permutation,:) = work;
solution = scale.*solution;
end

function solution = solve_pivot_blocks(D,rhs)
n = size(D,1);
solution = zeros(size(rhs));
row = 1;
while row<=n
    if row<n && D(row+1,row)~=0
        rows = row:row+1;
        solution(rows,:) = D(rows,rows)\rhs(rows,:);
        row = row+2;
    else
        solution(row,:) = rhs(row,:)/D(row,row);
        row = row+1;
    end
end
end

function metrics = residual_metrics(operator,solution,rhs)
residual = rkkt.solver.compute_sparse_residual_double_double( ...
    operator,solution,rhs);
columnRelative = vecnorm(residual,2,1)./ ...
    max(ones(1,size(rhs,2)),vecnorm(rhs,2,1));
denominator = max(ones(size(rhs)), ...
    abs(operator)*abs(solution)+abs(rhs));
metrics = struct("residual",residual, ...
    "maximum_column_relative",max(columnRelative), ...
    "frobenius_relative",norm(residual,"fro")/max(1,norm(rhs,"fro")), ...
    "componentwise_backward_error", ...
        max(abs(residual)./denominator,[],"all"), ...
    "maximum_absolute",max(abs(residual),[],"all"));
end

function value = history_row(pass,metrics,accepted)
value = struct("pass",pass, ...
    "maximum_column_relative",metrics.maximum_column_relative, ...
    "frobenius_relative",metrics.frobenius_relative, ...
    "componentwise_backward_error",metrics.componentwise_backward_error, ...
    "maximum_absolute",metrics.maximum_absolute,"accepted",accepted);
end

function value = relabel(value,label)
value.residual_operator = label;
end

function cells = split_by_hour(value,offsets)
if isempty(offsets)
    cells={value};
    return
end
cells=cell(height(offsets),1);
for hour=1:height(offsets)
    cells{hour}=value(offsets.start_index(hour):offsets.end_index(hour));
end
end

function cells = split_matrix_by_hour(value,offsets)
cells=cell(height(offsets),1);
for hour=1:height(offsets)
    cells{hour}=value( ...
        offsets.start_index(hour):offsets.end_index(hour),:);
end
end
