function result = solve_stage_b2b_full_kkt_direction(lin)
%SOLVE_STAGE_B2B_FULL_KKT_DIRECTION Solve one independent audit direction.
%
% This route is audit-only.  It accepts only the shared linearization and
% exposes no API by which a recursive solver could consume its direction.

arguments
    lin (1,1) struct
end

assembly = rkkt.solver.assemble_stage_b2b_full_kkt(lin);
lastwarn("");
direction = assembly.matrix\assembly.rhs;
[warningMessage,warningId] = lastwarn;
if strlength(string(warningId))>0 || strlength(string(warningMessage))>0
    error("stageB2B:fullKkt:SolveWarning", ...
        "B-2B sparse audit solve emitted warning %s: %s", ...
        string(warningId),string(warningMessage));
end
assert(all(isfinite(direction)),"stageB2B:fullKkt:DirectionFinite", ...
    "B-2B full-KKT audit direction contains NaN or Inf.");
residual = assembly.matrix*direction-assembly.rhs;

result = struct();
result.stage_id = "stage_B";
result.milestone_id = "B-2B";
result.method = "sparse_backslash_audit_only";
result.linearization_identity = assembly.linearization_identity;
result.direction = direction;
result.components = struct( ...
    "xi",direction(assembly.slices.xi), ...
    "y",direction(assembly.slices.y), ...
    "l",direction(assembly.slices.l), ...
    "z",direction(assembly.slices.z));
result.kkt = assembly;
result.diagnostics = struct( ...
    "relative_residual",norm(residual,2)/max(1,norm(assembly.rhs,2)), ...
    "max_absolute_residual",max(abs(residual)), ...
    "max_residual_row",find(abs(residual)==max(abs(residual)),1,"first"), ...
    "warning_id",string(warningId), ...
    "warning_message",string(warningMessage), ...
    "warning_present",false);
result.audit_only = true;
result.execution = struct("audit_only",true,"full_kkt_solved",true, ...
    "recursive_direction_consumed",false,"fallback_used",false, ...
    "full_ipm_executed",false,"optimization_executed",false, ...
    "parallel_executed",false);
result.recursive_direction_consumed = false;
result.no_full_direction_fallback = true;
result.full_ipm_executed = false;
result.optimization_executed = false;
result.parallel_executed = false;
end
