function audit = verifyEquivalence( ...
        fullResult,recursiveResult,linearization,thresholds)
%VERIFYEQUIVALENCE Verify complete and recursive Stage-A4 directions.

arguments
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    linearization (1,1) struct
    thresholds.DirectionRelative (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.RecursiveResidual (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.FullResidualPreferred (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-12
    thresholds.FullResidualMaximum (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
end

audit = rkkt.solver.verify_stage_a_multiday_direction_equivalence( ...
    fullResult,recursiveResult,linearization, ...
    DirectionRelative=thresholds.DirectionRelative, ...
    RecursiveResidual=thresholds.RecursiveResidual, ...
    FullResidualPreferred=thresholds.FullResidualPreferred, ...
    FullResidualMaximum=thresholds.FullResidualMaximum);
end
