function audit = verify_stage_b2b_direction_equivalence(fullResult,recursiveResult,lin,thresholds)
%VERIFY_STAGE_B2B_DIRECTION_EQUIVALENCE Compare independent directions.
arguments
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    lin (1,1) struct
    thresholds.DirectionRelative (1,1) double = 1e-10
    thresholds.RecursiveResidual (1,1) double = 1e-10
    thresholds.FullResidual (1,1) double = 1e-10
end
assembly=fullResult.kkt; fd=fullResult.direction(:); rd=recursiveResult.direction(:);
assert(numel(fd)==18948&&numel(rd)==18948,"stageB2B:equivalence:Dimension","Direction dimension mismatch.");
errs=struct(); names=["xi","y","l","z"];
for k=1:numel(names), rows=assembly.slices.(names(k)); errs.(names(k))=rel(rd(rows),fd(rows)); end
overall=rel(rd,fd); rv=assembly.matrix*rd-assembly.rhs; fv=assembly.matrix*fd-assembly.rhs;
recursiveResidual=norm(rv,2)/max(1,norm(assembly.rhs,2)); fullResidual=norm(fv,2)/max(1,norm(assembly.rhs,2));
fixed=recursiveResult.recovery.fixed_zero;
directionPass=overall<=thresholds.DirectionRelative && ...
    all(structfun(@(value)value<=thresholds.DirectionRelative,errs));
recursivePass=recursiveResidual<=thresholds.RecursiveResidual;
fullPass=fullResidual<=thresholds.FullResidual;
fallbackPass=recursiveResult.no_full_direction_fallback && ...
    ~recursiveResult.full_direction_consumed;
passes=struct("direction",directionPass, ...
    "recursive_residual",recursivePass, ...
    "full_residual_hard",fullPass, ...
    "fixed_zero",fixed.all_exact_zero,"no_fallback",fallbackPass);
contract=rkkt.solver.stage_b2b_linearization_contract(lin);
audit=struct("stage_id","stage_B","milestone_id",contract.milestone_id, ...
    "linearization_identity",lin.identity,"direction_relative_error",overall, ...
    "component_relative_errors",errs,"recursive_kkt_relative_residual",recursiveResidual, ...
    "full_kkt_relative_residual",fullResidual,"maximum_recursive_residual",max(abs(rv)), ...
    "maximum_full_residual",max(abs(fv)),"no_full_direction_fallback", ...
        recursiveResult.no_full_direction_fallback && ~recursiveResult.full_direction_consumed, ...
    "fixed_zero_exact",fixed.all_exact_zero,"passed",passes, ...
    "all_pass",all(structfun(@logical,passes)), ...
    "thresholds",thresholds);
end
function value=rel(a,b), value=norm(a-b,2)/max(1,norm(b,2)); end
