function audit = verifyStageB2BDirectionEquivalence( ...
        fullResult,recursiveResult,linearization,thresholds)
%VERIFYSTAGEB2BDIRECTIONEQUIVALENCE Verify the frozen B-2B directions.

arguments
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    linearization (1,1) struct
    thresholds.DirectionRelative (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.RecursiveResidual (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.FullResidual (1,1) double ...
        {mustBeNonnegative,mustBeFinite} = 1e-10
end

audit = rkkt.solver.verify_stage_b2b_direction_equivalence( ...
    fullResult,recursiveResult,linearization, ...
    DirectionRelative=thresholds.DirectionRelative, ...
    RecursiveResidual=thresholds.RecursiveResidual, ...
    FullResidual=thresholds.FullResidual);
end
