function report = generate_stage_b2a_report(runRoot)
%GENERATE_STAGE_B2A_REPORT Generate a report only from persisted artifacts.

arguments
    runRoot (1,1) string
end
runRoot = string(java.io.File(char(runRoot)).getCanonicalPath());
manifest = read_json(required(runRoot,"run_manifest.json"));
indexAudit = read_csv(required(runRoot,fullfile("diagnostics", ...
    "water_constraint_index_audit.csv")));
derivativeAudit = read_csv(required(runRoot,fullfile("diagnostics", ...
    "water_constraint_derivative_audit.csv")));
kkt = read_csv(required(runRoot,fullfile("diagnostics", ...
    "full_kkt_structure.csv")));
identity = read_csv(required(runRoot,fullfile("diagnostics", ...
    "linearization_identity.csv")));
hessian = read_csv(required(runRoot,fullfile("diagnostics", ...
    "lagrangian_hessian_audit.csv")));
acceptance = read_csv(required(runRoot,fullfile("acceptance", ...
    "acceptance_results.csv")));
summary = read_json(required(runRoot,fullfile("tests", ...
    "test_summary.json")));
inputHashes = read_csv(required(runRoot,"input_hashes.csv"));
environment = read_csv(required(runRoot,"environment.csv"));
issues = read_csv(required(runRoot,fullfile("issues","issue_log.csv")));
assert(height(acceptance)>=8 && ~isempty(environment), ...
    "stageB2A:report:RunEvidence", ...
    "Acceptance and environment evidence must be present.");

assert(height(indexAudit)==56 && all(string(indexAudit.status)=="PASS"), ...
    "stageB2A:report:IndexEvidence","Index evidence is incomplete.");
assert(height(derivativeAudit)==56 && ...
    all(string(derivativeAudit.status)=="PASS"), ...
    "stageB2A:report:DerivativeEvidence", ...
    "Derivative evidence is incomplete.");
assert(height(kkt)>=8 && all(string(kkt.status)=="PASS"), ...
    "stageB2A:report:KktEvidence","KKT structure evidence is incomplete.");
assert(height(identity)>=4 && all(string(identity.status)=="PASS"), ...
    "stageB2A:report:IdentityEvidence", ...
    "Linearization identity evidence is incomplete.");
assert(height(hessian)>=3 && all(string(hessian.status)=="PASS"), ...
    "stageB2A:report:HessianEvidence", ...
    "Hessian evidence is incomplete.");
assert(summary.test_total==19 && summary.test_passed==19 && ...
    summary.test_failed==0 && summary.test_incomplete==0, ...
    "stageB2A:report:TestEvidence", ...
    "B-2A fixed tests are not 19/19 PASS.");
assert(isempty(issues),"stageB2A:report:IssueEvidence", ...
    "A passing B-2A report requires no open issue rows.");

metadata = struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2A", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.status), ...
    "candidate_status","B-2A READY_FOR_REVIEW", ...
    "report_kicker","STAGE B-2A · 水量约束线性化与完整KKT结构", ...
    "header_label","STAGE B-2A · 只装配、不求解");

blocks = repmat(block_template(),0,1);
blocks(end+1) = callout_block("结论边界", ...
    "本报告确认 B-2A 已把第14—20日四座水电站的56条日用水不等式接入统一规范索引、非线性线性化和完整稀疏原始—对偶 KKT 结构。完整 KKT 只装配不求解；Stage B 整体仍为 READY_FOR_REVIEW，不能解释为优化、方向等价或物理调度结论。");
blocks(end+1) = heading_block(1,"1. 运行身份与结论");
identityRows = [ ...
    "run_id",string(manifest.run_id); ...
    "milestone",string(manifest.milestone); ...
    "implementation_commit",string(manifest.implementation_commit); ...
    "input_scope","第14—20日 / 每日1—24时段"; ...
    "full_kkt_dimension",number_text(manifest.full_kkt_dimension); ...
    "full_kkt_solved",logical_text(manifest.full_kkt_solved); ...
    "recursive_direction_executed",logical_text(manifest.recursive_direction_executed); ...
    "full_ipm_executed",logical_text(manifest.full_ipm_executed); ...
    "optimization_executed",logical_text(manifest.optimization_executed)];
blocks(end+1) = table_block(["字段","实际值"],identityRows,[3300,6060]);
blocks(end+1) = paragraph_block( ...
    "报告数值全部从本 run 的 CSV、JSON 和 MAT 工件重读。两份 Excel 输入及历史 B-1/A4 run 未修改；CURRENT_STAGE 仍为 stage_B / READY。SB-EQ-001 与 SB-PHY-001 明确保持 NOT_RUN。");

blocks(end+1) = heading_block(1,"2. 56条日用水约束规范索引");
blocks(end+1) = paragraph_block( ...
    "排序规则固定为 day 14,15,...,20 → hydro 1,2,3,4 → upper,lower。每条约束只触碰同日同站24个 PH 小时变量，不拆成小时约束，也不跨日或跨站耦合。");
sampleRows = strings(min(14,height(indexAudit)),6);
for k = 1:size(sampleRows,1)
    sampleRows(k,:) = [string(indexAudit.row_position(k)), ...
        number_text(indexAudit.day(k)),number_text(indexAudit.hydro_id(k)), ...
        string(indexAudit.bound_type(k)), ...
        number_text(indexAudit.touched_hour_count(k)), ...
        string(indexAudit.status(k))];
end
blocks(end+1) = table_block( ...
    ["序号","日","水电站","边界","触碰小时数","状态"], ...
    sampleRows,[900,900,1300,1800,1800,2660]);
blocks(end+1) = paragraph_block( ...
    "完整56行审计保存在 diagnostics/water_constraint_index_audit.csv；本页展示前14行以保持可读性。全局约束行范围为7867—7922，活动不等式位置为7249—7304。");

blocks(end+1) = heading_block(1,"3. 非线性值、Jacobian与Hessian");
maxGrad = max(derivativeAudit.gradient_relative_error);
maxHess = max(derivativeAudit.hessian_relative_error);
maxIdentity = max(identity.identity_error);
derivativeRows = [ ...
    "水量约束行",number_text(height(derivativeAudit)),"56"; ...
    "最大梯度相对误差",number_text(maxGrad),"<=1e-7"; ...
    "最大Hessian相对误差",number_text(maxHess),"<=1e-7"; ...
    "G*x+offset值误差",number_text(maxIdentity),"<=64*eps"; ...
    "上/下界符号",string(unique(derivativeAudit.sign_status,"stable")),"PASS"; ...
    "Hessian结构","24×24对角局部块","PASS"];
blocks(end+1) = table_block(["指标","实际值","门槛"], ...
    derivativeRows,[3100,3700,2560]);
blocks(end+1) = paragraph_block( ...
    "上界采用 gU=W-Wmax、+∇W、+2aI24；下界采用 gL=Wmin-W、-∇W、-2aI24。目标 Hessian 保持独立为零；完整 stationarity block 使用 z 加权的 Lagrangian Hessian，未把水量曲率伪装成目标 Hessian。");

blocks(end+1) = heading_block(1,"4. 完整稀疏KKT结构");
kktRows = [ ...
    "原始—对偶KKT维数",number_text(manifest.full_kkt_dimension),"18948"; ...
    "矩阵非零元",number_text(manifest.full_kkt_nnz),"54664"; ...
    "Hessian对称相对误差",number_text(manifest.hessian_symmetry_relative),"<=1e-12"; ...
    "原始完整KKT整体对称性","按合同不适用（互补块含Z/I）","N/A"; ...
    "KKT求解","未执行","必须未执行"];
blocks(end+1) = table_block(["指标","实际值","要求"], ...
    kktRows,[3100,3900,2360]);
blocks(end+1) = paragraph_block( ...
    "装配块严格为 [H A' 0 G'; A 0 0 0; G 0 I 0; 0 0 Z L]。A/G转置位置、I/Z/L互补块和每块非零元清单见 diagnostics/full_kkt_structure.csv。由于该原始原始—对偶合同本身非对称，未进行自动对称化。");

blocks(end+1) = heading_block(1,"5. 测试与停止边界");
testRows = [ ...
    "B-2A固定结构测试",number_text(summary.test_total), ...
        number_text(summary.test_passed),"PASS"; ...
    "B-1固定测试",number_text(read_suite_total(runRoot,"b1_fixed")), ...
        number_text(read_suite_passed(runRoot,"b1_fixed")),"回归"; ...
    "B-1受影响回归",number_text(read_suite_total(runRoot,"b1_affected")), ...
        number_text(read_suite_passed(runRoot,"b1_affected")),"回归"; ...
    "Stage-A结构回归",number_text(read_suite_total(runRoot,"a4_structure")), ...
        number_text(read_suite_passed(runRoot,"a4_structure")),"回归"; ...
    "问题日志",number_text(height(issues)),"0","PASS"];
blocks(end+1) = table_block(["套件","总数","通过","状态"], ...
    testRows,[3000,1500,1500,3360]);
blocks(end+1) = callout_block("明确未执行", ...
    "本阶段未求解完整KKT，未求递推方向或Newton方向，未运行IPM、优化、并行、LDL/Thomas、Schur、预条件、正则化或矩阵逆，未执行火电第二次、年度扩展或 Stage C1。SB-EQ-001 与 SB-PHY-001 保持 NOT_RUN。下一步需另行授权并完成后续里程碑。");

blocks(end+1) = heading_block(1,"6. 输入哈希与证据位置");
hashRows = strings(height(inputHashes),3);
for k = 1:height(inputHashes)
    hashRows(k,:) = [string(inputHashes.file_name(k)), ...
        string(inputHashes.actualSHA256(k)),string(inputHashes.status(k))];
end
blocks(end+1) = table_block(["输入文件","SHA256","状态"], ...
    hashRows,[2300,5260,1800]);
blocks(end+1) = paragraph_block( ...
    "关键证据文件、MAT 中间结果和 SHA256 清单均位于本 run 目录；环境状态见 environment.csv。报告未读取聊天文字或未持久化变量。");

outputPath = fullfile(runRoot,"reports", ...
    "阶段B-2A_水量约束线性化与完整KKT结构报告.docx");
rkkt.reporting.write_stage_b2a_docx(outputPath, ...
    "阶段B-2A：水量约束线性化与完整KKT结构报告", ...
    "第14—20日 · 56条日级水量不等式 · 18,948维稀疏KKT（仅装配）", ...
    metadata,blocks);
report = struct("path",string(outputPath),"run_id",string(manifest.run_id), ...
    "status","GENERATED","manifest_status",string(manifest.status), ...
    "maximum_gradient_relative_error",maxGrad, ...
    "maximum_hessian_relative_error",maxHess, ...
    "linearization_identity_error",maxIdentity);
end

function value = read_suite_total(root,name)
value = read_json(fullfile(root,"tests",name,"test_summary.json")).test_total;
end
function value = read_suite_passed(root,name)
value = read_json(fullfile(root,"tests",name,"test_summary.json")).test_passed;
end
function value = required(root,relative)
value = fullfile(root,relative);
assert(isfile(value),"stageB2A:report:MissingArtifact", ...
    "Missing report source: %s",value);
end
function value = read_csv(pathValue)
value = readtable(pathValue,detectImportOptions(pathValue, ...
    "Delimiter",",","TextType","string", ...
    "VariableNamingRule","preserve"));
end
function value = read_json(pathValue)
value = jsondecode(fileread(pathValue));
end
function value = number_text(number)
value = compose("%.17g",double(number));
end
function value = logical_text(number)
value = string(logical(number));
end
function value = block_template()
value = struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end
function value = heading_block(level,textValue)
value = block_template(); value.type="heading"; value.level=level; value.text=string(textValue);
end
function value = paragraph_block(textValue)
value = block_template(); value.type="paragraph"; value.text=string(textValue);
end
function value = callout_block(titleValue,textValue)
value = block_template(); value.type="callout"; value.title=string(titleValue); value.text=string(textValue);
end
function value = table_block(headers,rows,widths)
value = block_template(); value.type="table"; value.headers=reshape(string(headers),1,[]);
value.rows=string(rows); value.widths=reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && sum(value.widths)==9360, ...
    "stageB2A:report:TableShape","Report table geometry must total 9360 DXA.");
end
