function report = generate_stage_b2c_365day_serial_report(runRoot,options)
%GENERATE_STAGE_B2C_365DAY_SERIAL_REPORT Build the Chinese run report.

arguments
    runRoot (1,1) string
    options.OutputFileName (1,1) string = ...
        "阶段B-2C_365日串行递推IPM补充实验报告.docx"
end

manifest = jsondecode(fileread(fullfile(runRoot,"run_manifest.json")));
iterations = read_csv(fullfile(runRoot,"diagnostics","iteration_history.csv"));
timing = read_csv(fullfile(runRoot,"diagnostics","timing_history.csv"));
factors = read_csv(fullfile(runRoot,"diagnostics", ...
    "daily_joint_factorization_history.csv"));
dimensions = read_csv(fullfile(runRoot,"diagnostics","dimension_summary.csv"));
capacity = read_csv(fullfile(runRoot,"results","capacity_results.csv"));
daily = read_csv(fullfile(runRoot,"results","daily_generation_summary.csv"));
acceptance = read_csv(fullfile(runRoot,"acceptance","acceptance_results.csv"));
assert(height(timing)==height(iterations) && height(capacity)==14 && ...
    height(daily)==365 && height(acceptance)==8, ...
    "stageB2C:day365:ReportEvidence", ...
    "The 365-day serial experiment report evidence is incomplete.");

converged = logical_value(manifest.convergence_achieved);
if converged
    conclusion = "第1—365日串行递推原始—对偶IPM已满足四项停止判据，并完成最终物理审计。每轮方向仅由365个日内联合块与16维全局核心求得；未装配或求解完整KKT。";
else
    conclusion = "第1—365日串行递推实验已完成限定迭代，但尚未同时满足四项停止判据；该结果不应解释为365日收敛解。";
end
resumeCount = 0;
if isfield(manifest,"resume_count"), resumeCount = manifest.resume_count; end
metadata = struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2C 365日串行补充实验", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.milestone_status), ...
    "candidate_status",conditional_text(converged,"365日已收敛", ...
        "限定迭代试算"), ...
    "report_kicker","STAGE B-2C · 365日串行递推IPM", ...
    "header_label","STAGE B-2C · 第1—365日");

blocks = repmat(block_template(),0,1);
blocks(end+1) = callout_block("实验结论",conclusion);
blocks(end+1) = heading_block(1,"0. 运行身份与可追溯性");
identityRows = [ ...
    "run_id",string(manifest.run_id); ...
    "Git commit",string(manifest.git_commit); ...
    "有效配置","effective_config.yaml"; ...
    "基础参数输入SHA256",string(manifest.input_hashes.base_parameters); ...
    "时序输入SHA256",string(manifest.input_hashes.timeseries); ...
    "求解代码签名",string(manifest.solver_code_signature)];
blocks(end+1) = table_block(["身份项","值"],identityRows,[3000,6360]);
blocks(end+1) = heading_block(1,"1. 实验边界与算法口径");
blocks(end+1) = paragraph_block( ...
    "计算范围为第1—365日，每日24小时；各日储能初末SOC均为0.5E，日期之间不连接SOC。火电沿用第一次连续口径0≤Pf≤Pmax；C1/C2、火电第二次求解、并行和年度聚合目标均未启用。正式方向为全不等式消元后的365个串行日内联合块和16维全局核心，保留水量约束精确二阶松弛校正与重构KKT残差门禁。完整KKT只记录概念维数，不装配、不求解、无方向兜底。本补充实验不改写Stage B既有七日PASS，也不进入D1验收。" );

blocks(end+1) = heading_block(1,"2. 规模、恢复与耗时");
blocks(end+1) = table_block(["规模/耗时项目","实际值"], ...
    select_rows(dimensions,["metric","actual_value"]),[4400,4960]);
wallSeconds = 0;
if isfield(manifest,"iteration_loop_wall_seconds")
    wallSeconds = double(manifest.iteration_loop_wall_seconds);
elseif ~isempty(timing)
    wallSeconds = str2double(timing.cumulative_seconds(end));
end
timingRows = [ ...
    "接受迭代次数",number_text(height(iterations)); ...
    "断点恢复次数",number_text(resumeCount); ...
    "纯IPM数值计算秒数",number_text(sum_numeric(timing.total_seconds)); ...
    "累计迭代循环墙钟秒数",number_text(wallSeconds); ...
    "检查点/证据及循环管理秒数", ...
        number_text(wallSeconds-sum_numeric(timing.total_seconds)); ...
    "累计工作流准备秒数（含首次索引装配）", ...
        number_text(manifest_number(manifest, ...
        "cumulative_workflow_preparation_seconds")); ...
    "累计求解器初始/恢复准备秒数", ...
        number_text(manifest_number(manifest, ...
        "cumulative_solver_setup_seconds")); ...
    "端到端计算秒数（含装配与恢复准备）", ...
        number_text(manifest_number(manifest,"end_to_end_compute_seconds")); ...
    "递推方向内核累计秒数",number_text(sum_numeric(timing.recursive_seconds)); ...
    "迭代内线性化装配累计秒数", ...
        number_text(sum_numeric(timing.linearization_after_seconds)+ ...
        sum_numeric(timing.linearization_before_seconds)); ...
    "完整KKT审计秒数",number_text(sum_numeric(timing.full_kkt_audit_seconds)); ...
    "是否执行并行",string(manifest.parallel_executed)];
blocks(end+1) = table_block(["项目","实际值"],timingRows,[4400,4960]);

blocks(end+1) = heading_block(1,"3. 收敛轨迹（最后10次迭代）");
if isempty(iterations)
    tailRows = strings(0,8);
else
    tail = iterations(max(1,height(iterations)-9):height(iterations),:);
    tailRows = select_rows(tail,["iteration","primal_equality_inf", ...
        "primal_inequality_inf","dual_scaled_inf","mean_lz_scaled", ...
        "alpha_primal","alpha_dual", ...
        "recursive_final_kkt_relative_residual"]);
end
blocks(end+1) = table_block( ...
    ["迭代","等式残差","不等式残差","对偶残差","平均互补隙", ...
    "原始步长","对偶步长","重构KKT残差"],tailRows, ...
    [650,1300,1300,1250,1250,1000,1000,1610]);

blocks(end+1) = heading_block(1,"4. 串行日块数值诊断");
dailyFactors = factors(factors.object_type=="daily_joint",:);
factorSummary = summarize_factors(dailyFactors);
blocks(end+1) = table_block( ...
    ["日","分解次数","最小绝对主元","最大右端相对残差","零主元次数"], ...
    factorSummary,[700,1400,2300,2500,2460]);
blocks(end+1) = paragraph_block( ...
    "日块按日串行执行；局部弱主元只作诊断。日块和16维核心的局部LDL求解目标保持1e-10，方向接受条件是完整方向代回共享线性化对象后的重构KKT相对残差不超过1e-8。" );

blocks(end+1) = heading_block(1,"5. 容量规划结果");
blocks(end+1) = table_block(["序号","容量变量","值"], ...
    select_rows(capacity,["capacity_index","capacity_name","value"]), ...
    [900,4300,4160]);

blocks(end+1) = heading_block(1,"6. 各类电源每日发电量");
blocks(end+1) = table_block( ...
    ["日","风电MWh","光伏MWh","水电MWh","火电MWh", ...
    "充电MWh","放电MWh","总发电MWh"], ...
    select_rows(daily,["day","wind_mwh","solar_mwh","hydro_mwh", ...
    "thermal_mwh","storage_charge_mwh","storage_discharge_mwh", ...
    "total_generation_mwh"]), ...
    [500,1200,1200,1200,1200,1200,1200,1660]);

blocks(end+1) = heading_block(1,"7. 补充实验验收");
blocks(end+1) = table_block(["检查项","要求","实际值","状态"], ...
    select_rows(acceptance,["test_id","requirement","actual_value", ...
    "status"]),[1900,3000,2860,1600]);
blocks(end+1) = paragraph_block( ...
    "本报告的PASS仅表示365日串行补充实验按其独立配置完成，不替代Stage B权威七日验收，也不表示D1已启动或通过。" );

outputPath = fullfile(runRoot,"reports",options.OutputFileName);
rkkt.reporting.write_stage_b2c_docx(outputPath, ...
    "阶段B-2C：365日串行递推IPM补充实验报告", ...
    "第1—365日 · 可断点续算 · 无完整KKT审计",metadata,blocks);
report = struct("path",string(outputPath), ...
    "run_id",string(manifest.run_id),"status","GENERATED", ...
    "design_preset","standard_business_brief", ...
    "header_pattern","memo_masthead");
end

function value = summarize_factors(source)
if isempty(source)
    value = strings(0,5);
    return
end
days = unique(str2double(source.day_id),'stable');
rows = strings(numel(days),5);
for k = 1:numel(days)
    selected = str2double(source.day_id)==days(k);
    rows(k,:) = [string(days(k)),string(nnz(selected)), ...
        number_text(min(str2double(source.minimum_absolute_pivot(selected)))), ...
        number_text(max(str2double( ...
            source.maximum_rhs_relative_residual(selected)))), ...
        string(sum(str2double(source.numerical_zero_pivot_count(selected))))];
end
value = rows;
end

function value = read_csv(pathValue)
options = detectImportOptions(pathValue,"Delimiter",",", ...
    "TextType","string","VariableNamingRule","preserve");
options.VariableNamesLine = 1;
options.VariableUnitsLine = 0;
options.VariableDescriptionsLine = 0;
options.DataLines = [2,Inf];
options = setvartype(options,options.VariableNames,"string");
value = readtable(pathValue,options);
end

function rows = select_rows(source,names)
rows = strings(height(source),numel(names));
for column = 1:numel(names), rows(:,column) = string(source.(names(column))); end
end

function value = sum_numeric(raw)
value = sum(str2double(string(raw)),"omitnan");
end

function value = number_text(number)
value = compose("%.17g",double(number));
end

function value = logical_value(raw)
if islogical(raw), value = raw; else, value = lower(string(raw))=="true"; end
end

function value = manifest_number(manifest,name)
if isfield(manifest,name), value = double(manifest.(name)); else, value = NaN; end
end

function value = conditional_text(condition,whenTrue,whenFalse)
if condition, value = string(whenTrue); else, value = string(whenFalse); end
end

function value = block_template()
value = struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end

function value = heading_block(level,textValue)
value = block_template(); value.type = "heading";
value.level = level; value.text = string(textValue);
end

function value = paragraph_block(textValue)
value = block_template(); value.type = "paragraph";
value.text = string(textValue);
end

function value = callout_block(titleValue,textValue)
value = block_template(); value.type = "callout";
value.title = string(titleValue); value.text = string(textValue);
end

function value = table_block(headers,rows,widths)
value = block_template(); value.type = "table";
value.headers = reshape(string(headers),1,[]);
value.rows = string(rows); value.widths = reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && ...
    sum(value.widths)==9360,"stageB2C:day365:ReportTable", ...
    "Report table geometry must total 9360 DXA.");
end
