function report = generate_stage_b2c_day16_to_day17_warm_start_report(runRoot)
%GENERATE_STAGE_B2C_DAY16_TO_DAY17_WARM_START_REPORT Build experiment report.

arguments
    runRoot (1,1) string
end

manifest = jsondecode(fileread(fullfile(runRoot,"run_manifest.json")));
mapping = read_csv(fullfile(runRoot,"diagnostics", ...
    "day16_to_day17_primal_mapping.csv"));
reset = read_csv(fullfile(runRoot,"diagnostics", ...
    "day17_dual_slack_reset.csv"));
initial = read_csv(fullfile(runRoot,"diagnostics", ...
    "warm_start_initial_metrics.csv"));
iterations = read_csv(fullfile(runRoot,"diagnostics","iteration_history.csv"));
acceptance = read_csv(fullfile(runRoot,"acceptance", ...
    "acceptance_results.csv"));
issues = read_csv(fullfile(runRoot,"issues","issue_log.csv"));
analyzer = read_csv(fullfile(runRoot,"tests","code_analyzer.csv"));

matched = nnz(boolean_column(mapping.source_matched));
unmatchedRows = mapping(~boolean_column(mapping.source_matched),:);
terminal = string(manifest.experimental_solver_terminal_state);
accepted = double(manifest.accepted_iteration_count);
if terminal=="CONVERGED"
    conclusion = "本次一次性受控实验收敛。第16日物理原变量映射改变了第17日迭代轨迹，并在不修改模型、正式入口、零主元阈值或递推结构的情况下通过现有收敛判据。该结果仍不是正式Stage B通过证据。";
else
    conclusion = "本次一次性受控实验未收敛。前一日物理原变量warm start未能消除当前数值阻断，因此不能作为自动兜底或第17日结果替代。正式求解器保持不变。";
end

metadata = struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2C diagnostic", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.milestone_status), ...
    "candidate_status",terminal, ...
    "report_kicker","STAGE B-2C · WARM START实验", ...
    "header_label","STAGE B-2C · 第16日至第17日原变量映射");

blocks = repmat(block_template(),0,1);
blocks(end+1) = callout_block("实验结论",conclusion);

blocks(end+1) = heading_block(1,"1. 实验边界");
blocks(end+1) = paragraph_block( ...
    "实验从既有失败run的第30个已接受检查点出发，只把第16日每小时物理原变量按变量名称、设备和小时映射到第17日。第17日仍使用自己的负荷、风光可用率、水量上下限、活动变量集合和固定零映射；第17日y/l/z重新初始化。其余日期和统一14维容量保留源检查点状态。" );
blocks(end+1) = table_block(["项目","实际值"], ...
    ["源run",string(manifest.source_run_id); ...
    "源检查点",string(manifest.source_checkpoint_revision); ...
    "源日 / 目标日","16 / 17"; ...
    "已接受实验迭代",string(manifest.accepted_iteration_count); ...
    "正式入口修改","否";"模型修改","否"; ...
    "自动fallback新增","否"],[2700,6660]);

blocks(end+1) = heading_block(1,"2. 原变量映射与对偶重建");
blocks(end+1) = paragraph_block( ...
    "第17日共有516个活动小时原变量。其中515个在第16日存在同标识变量并精确复制；第16日少一个活动风电变量，因此第17日唯一未匹配变量使用第17日确定性初始化值。禁止按裸向量位置复制。" );
mappingRows = [ ...
    "第17日目标变量数",string(height(mapping)); ...
    "同标识复制数",string(matched); ...
    "未匹配数",string(height(unmatchedRows)); ...
    "未匹配变量",unmatched_description(unmatchedRows); ...
    "第17日等式乘子重置数",string(reset.equality_reset_count(1)); ...
    "第17日不等式l/z重置数",string(reset.inequality_reset_count(1)); ...
    "重置后最小l",reset.minimum_l(1); ...
    "重置后最小z",reset.minimum_z(1)];
blocks(end+1) = table_block(["指标","实际值"],mappingRows,[3500,5860]);

blocks(end+1) = heading_block(1,"3. 初始状态变化");
blocks(end+1) = table_block( ...
    ["点位","等式残差","不等式残差","对偶残差","平均l·z","水量越界"], ...
    select_rows(initial,["point","primal_equality_inf", ...
        "primal_inequality_inf","dual_scaled_inf", ...
        "mean_lz_scaled","maximum_water_violation"]), ...
    [1500,1550,1650,1550,1550,1560]);
blocks(end+1) = paragraph_block( ...
    "Warm start允许从不完全可行点启动，但必须保持l/z严格为正，并由第17日自己的约束重新计算残差。实验不把第16日残差或乘子冒充第17日状态。" );

blocks(end+1) = heading_block(1,"4. 续算结果与第17日主元");
outcomeRows = [ ...
    "实验终态",terminal; ...
    "已接受更新数",string(accepted); ...
    "最终等式残差",number_field(manifest,"final_primal_equality_inf"); ...
    "最终不等式残差",number_field(manifest,"final_primal_inequality_inf"); ...
    "最终对偶残差",number_field(manifest,"final_dual_scaled_inf"); ...
    "最终平均l·z",number_field(manifest,"final_mean_lz_scaled"); ...
    "最终水量越界",number_field(manifest,"final_maximum_water_violation")];
blocks(end+1) = table_block(["指标","实际值"],outcomeRows,[3500,5860]);
if ~isempty(iterations)
    tailCount = min(8,height(iterations));
    tailRows = iterations(end-tailCount+1:end,:);
    blocks(end+1) = table_block( ...
        ["实验轮次","不等式残差","平均l·z","第17日最小主元", ...
        "零主元数","方向误差"], ...
        select_rows(tailRows,["experiment_iteration", ...
        "primal_inequality_inf","mean_lz_scaled", ...
        "day17_minimum_absolute_pivot", ...
        "day17_numerical_zero_pivot_count","direction_relative_error"]), ...
        [900,1800,1600,2050,1100,1910]);
else
    blocks(end+1) = paragraph_block("实验未接受任何Newton更新。" );
end

blocks(end+1) = heading_block(1,"5. 实际启用与未启用内容");
blocks(end+1) = paragraph_block( ...
    "实际启用：第14—20日统一容量投资目标、小时功率平衡、SOC日内递推与每日0.5E闭合、储能时长等式、风光水火储小时边界、四座水电每日水量上下限、全不等式消元、七个日内联合块、16维全局核心和逐轮独立完整KKT审计。" );
blocks(end+1) = paragraph_block( ...
    "明确未启用：第二次火电掩码、最小开停机时间、启动停机成本、动态sigma、预测—校正、非线性线搜索、正则化、伪逆、完整KKT方向回退、并行、30日或365日、Stage C1。" );

blocks(end+1) = heading_block(1,"6. 验收与解释");
blocks(end+1) = table_block(["验收项","实际值","门限","状态"], ...
    select_rows(acceptance,["check_id","actual_value","threshold","status"]), ...
    [1900,3300,2500,1660]);
blocks(end+1) = paragraph_block( ...
    "本次未运行全量测试、完整构建、全量lint或E2E。只执行实验入口自身的映射、严格正值、检查点哈希、逐轮方向等价和完整KKT残差验证，并对两个新增实验文件执行Code Analyzer。" );
blocks(end+1) = table_block(["文件","Code Analyzer问题数","状态"], ...
    select_rows(analyzer,["file","finding_count","status"]), ...
    [6100,1800,1460]);

blocks(end+1) = heading_block(1,"7. 当前决策边界");
if terminal=="CONVERGED"
    blocks(end+1) = paragraph_block( ...
        "实验成功只说明该检查点和该映射可以形成一条收敛轨迹。若要采用为正式初始化策略，仍需从第0次状态执行全新正式run，并重新完成Stage B阻断验收。不得据此直接把前一日结果登记为目标日结果。" );
else
    symptom = "未记录具体异常标识。";
    if ~isempty(issues)
        symptom = string(issues.identifier(1))+"："+string(issues.message(1));
    end
    blocks(end+1) = callout_block("失败症状",symptom);
    blocks(end+1) = paragraph_block( ...
        "根因解释：warm start改变了初始原变量和中心路径，但没有删除两台同参数储能的无成本反向交换方向。若该方向再次只由障碍曲率约束，随着互补量下降仍会重新变成近零模态。" );
    blocks(end+1) = paragraph_block( ...
        "未解决项：本实验没有授权动态中心参数、二阶水量校正、显式凸储能退化成本或改变16维核心。下一步仍需在这些正式算法或模型路径中另行决策。" );
end

outputPath = fullfile(runRoot,"reports", ...
    "阶段B-2C_第16日原变量映射至第17日WarmStart实验报告.docx");
rkkt.reporting.write_stage_b2c_docx(outputPath, ...
    "阶段B-2C：第16日原变量映射至第17日Warm Start实验报告", ...
    "一次性受控检查点实验 · 不修改正式求解器 · 不建立自动兜底", ...
    metadata,blocks);
report = struct("path",string(outputPath), ...
    "run_id",string(manifest.run_id),"status","GENERATED", ...
    "design_preset","standard_business_brief", ...
    "header_pattern","memo_masthead");
end

function value = read_csv(pathValue)
options = detectImportOptions(pathValue,"Delimiter",",", ...
    "TextType","string","VariableNamingRule","preserve");
options.VariableNamesLine = 1;
options.VariableUnitsLine = 0;
options.VariableDescriptionsLine = 0;
options.DataLines = [2,Inf];
options = setvartype(options,options.VariableNames,"string");
value = readtable(pathValue,options);
end

function rows = select_rows(source,names)
rows = strings(height(source),numel(names));
for column = 1:numel(names)
    rows(:,column) = string(source.(names(column)));
end
end

function value = boolean_column(raw)
if islogical(raw)
    value = raw;
else
    value = lower(string(raw))=="true";
end
end

function value = unmatched_description(rows)
if isempty(rows)
    value = "无";
    return
end
value = strjoin("H"+rows.hour+" "+rows.variable_name+ ...
    "-"+rows.asset_id,"；");
end

function value = number_field(manifest,name)
if isfield(manifest,name)
    value = compose("%.17g",double(manifest.(name)));
else
    value = "未记录";
end
end

function value = block_template()
value = struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end

function value = heading_block(level,textValue)
value = block_template();
value.type = "heading";
value.level = level;
value.text = string(textValue);
end

function value = paragraph_block(textValue)
value = block_template();
value.type = "paragraph";
value.text = string(textValue);
end

function value = callout_block(titleValue,textValue)
value = block_template();
value.type = "callout";
value.title = string(titleValue);
value.text = string(textValue);
end

function value = table_block(headers,rows,widths)
value = block_template();
value.type = "table";
value.headers = reshape(string(headers),1,[]);
value.rows = string(rows);
value.widths = reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && ...
    sum(value.widths)==9360, ...
    "stageB2C:warmStart:ReportTable", ...
    "Report table geometry must total 9360 DXA.");
end
