function report = generate_stage_b2c_report(runRoot)
%GENERATE_STAGE_B2C_REPORT Generate the Chinese report from run artifacts.

arguments
    runRoot (1,1) string
end
runRoot=string(java.io.File(char(runRoot)).getCanonicalPath());
manifest=read_json(required(runRoot,"run_manifest.json"));
gate=read_csv(required(runRoot,fullfile("diagnostics", ...
    "nonzero_water_hessian_gate.csv")));
iterations=read_csv(required(runRoot,fullfile("diagnostics", ...
    "iteration_history.csv")));
directions=read_csv(required(runRoot,fullfile("diagnostics", ...
    "direction_audit_history.csv")));
corrections=read_csv(required(runRoot,fullfile("diagnostics", ...
    "water_slack_second_order_correction_history.csv")));
water=read_csv(required(runRoot,fullfile("diagnostics", ...
    "final_daily_water_constraint_audit.csv")));
acceptance=read_csv(required(runRoot,fullfile("acceptance", ...
    "acceptance_results.csv")));
tests=read_json(required(runRoot,fullfile("tests","test_summary.json")));
inputHashes=read_csv(required(runRoot,"input_hashes.csv"));
issues=read_csv(required(runRoot,fullfile("issues","issue_log.csv")));
assert(~isempty(iterations)&&~isempty(directions)&& ...
    height(corrections)==56*height(iterations) && ...
    all(corrections.strictly_positive=="true") && ...
    all(abs(corrections.closure_error)<=corrections.closure_tolerance) && ...
    height(water)==28 && ...
    all(string(gate.status)=="PASS") && ...
    all(string(acceptance.status)=="PASS") && isempty(issues), ...
    "stageB2C:report:Evidence", ...
    "The B-2C report source evidence is incomplete or not PASS.");

metadata=struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2C", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.status), ...
    "candidate_status","Stage B PASS candidate", ...
    "report_kicker","STAGE B-2C · 七日递推IPM与水量物理验收", ...
    "header_label","STAGE B-2C · 正式七日收敛验证");
blocks=repmat(block_template(),0,1);
blocks(end+1)=callout_block("结论", ...
    "非零水量Lagrangian Hessian方向门禁通过；正式主流程在每次普通Newton更新后，对56条水量松弛计算精确二阶余项并执行中心性限幅校正。校正系数beta仅在全量校正会把某条水量松弛压到普通试探值的10%以下时小于1，进入中心性安全区域后恢复为1。第14—20日七日原始—对偶IPM达到四项1e-6停止标准，28个日—站水量审计全部通过1e-8物理阈值。完整KKT逐轮仅作独立审计，未被递推路线消费或用于回退。");
blocks(end+1)=heading_block(1,"1. 运行身份与冻结边界");
identity=["run_id",string(manifest.run_id); ...
    "实现提交",string(manifest.git_commit); ...
    "父run","20260804_022443_stage_B_2B_4bcd7504"; ...
    "数据范围","第14—20日，每日1—24小时"; ...
    "接受迭代",number_text(height(iterations)); ...
    "正式方向","全不等式消元—日内联合块—16维核心递推"; ...
    "完整KKT","逐轮独立审计，不参与状态更新"; ...
    "水量松弛二阶校正","正式启用；每轮56行；Newton方向和主步长不变"; ...
    "年度/并行/火电第二次/Stage C1","均未执行"];
blocks(end+1)=table_block(["字段","实际值"],identity,[3000,6360]);

blocks(end+1)=heading_block(1,"2. 非零水量 Hessian 门禁");
gateRows=strings(height(gate),4);
for k=1:height(gate)
    gateRows(k,:)=[string(gate.check_id(k)), ...
        number_text(gate.actual_value(k)), ...
        string(gate.operator(k))+number_text(gate.threshold(k)), ...
        string(gate.status(k))];
end
blocks(end+1)=table_block(["检查项","实际值","门槛","状态"], ...
    gateRows,[3600,2000,2200,1560]);

blocks(end+1)=heading_block(1,"3. 收敛轨迹与方向审计");
last=iterations(end,:);
[worstDirection,worstIndex]=max(directions.direction_relative_error);
worstRecursive=max(directions.recursive_full_kkt_relative_residual);
worstFull=max(directions.full_kkt_relative_residual);
metrics=["等式原始残差",number_text(last.primal_equality_inf),"≤1e-6"; ...
    "不等式原始残差",number_text(last.primal_inequality_inf),"≤1e-6"; ...
    "尺度化对偶残差",number_text(last.dual_scaled_inf),"≤1e-6"; ...
    "尺度化平均互补间隙",number_text(last.mean_lz_scaled),"≤1e-6"; ...
    "最差方向相对误差（迭代"+string(worstIndex)+"）", ...
        number_text(worstDirection),"≤1e-10"; ...
    "最差递推代回完整KKT残差",number_text(worstRecursive),"≤1e-8"; ...
    "最差完整KKT审计残差",number_text(worstFull),"≤1e-10"; ...
    "全程最小l",number_text(min(iterations.min_l_after)),">0"; ...
    "全程最小z",number_text(min(iterations.min_z_after)),">0"; ...
    "最大水量校正闭合误差", ...
        number_text(max(abs(corrections.closure_error))), ...
        "≤逐行舍入容差"; ...
    "校正后最小水量松弛", ...
        number_text(min(corrections.l_corrected)),">0"; ...
    "最小水量校正系数beta", ...
        number_text(min(iterations.water_correction_fraction)),">0"; ...
    "中心性限幅校正迭代数", ...
        number_text(sum( ...
            iterations.water_correction_fraction_limited=="true")), ...
        "运行事实"; ...
    "末轮水量校正系数beta", ...
        number_text(iterations.water_correction_fraction(end)),"=1"];
blocks(end+1)=table_block(["指标","实际值","门槛"],metrics, ...
    [4500,2600,2260]);
blocks(end+1)=paragraph_block( ...
    "每轮均从当前xi/y/l/z重算W、g、G、水量Lagrangian Hessian和D=diag(z./l)，重新分解七个日链与16维核心；保留因子只在当轮23个右端间复用，未跨迭代复用。");
blocks(end+1)=paragraph_block( ...
    "正式校正公式为l_corrected=l_trial-beta·[g(x+alpha·dx)-g(x)-alpha·G·dx]。括号内二阶Taylor余项按二次水量函数精确计算。若beta=1不能满足l_corrected≥sigma·l_trial，则以冻结sigma=0.1形成中心性下界，并用冻结tau=0.9995在该边界内保持严格余量；否则beta=1并完整消除余项。xi、y、z、7248条非水量松弛、递推方向、独立完整KKT审计方向以及原始/对偶Newton步长均不改变，且不存在关闭校正或改走其他方向的回退分支。");

blocks(end+1)=heading_block(1,"4. 28项日—站水量物理审计");
waterRows=strings(height(water),7);
for k=1:height(water)
    waterRows(k,:)=[number_text(water.day(k)), ...
        number_text(water.hydro_id(k)),number_text(water.Wmin(k)), ...
        number_text(water.W(k)),number_text(water.Wmax(k)), ...
        number_text(water.maximum_violation(k)),string(water.status(k))];
end
blocks(end+1)=table_block( ...
    ["日","水电站","Wmin","W","Wmax","最大违反","状态"], ...
    waterRows,[700,1000,1600,1700,1600,1760,1000]);

blocks(end+1)=heading_block(1,"5. 验收、测试与执行边界");
acceptRows=strings(height(acceptance),3);
for k=1:height(acceptance)
    acceptRows(k,:)=[string(acceptance.test_id(k)), ...
        string(acceptance.actual_value(k)),string(acceptance.status(k))];
end
blocks(end+1)=table_block(["验收项","真实工件值","状态"], ...
    acceptRows,[1800,5760,1800]);
suiteRows=["B-2C固定测试",number_text(tests.test_total), ...
        number_text(tests.test_passed); ...
    "B-2B回归",suite_value(runRoot,"b2b_regression","test_total"), ...
        suite_value(runRoot,"b2b_regression","test_passed"); ...
    "B-2A回归",suite_value(runRoot,"b2a_regression","test_total"), ...
        suite_value(runRoot,"b2a_regression","test_passed"); ...
    "B-1回归",suite_value(runRoot,"b1_regression","test_total"), ...
        suite_value(runRoot,"b1_regression","test_passed"); ...
    "B-1受影响回归",suite_value(runRoot,"b1_affected","test_total"), ...
        suite_value(runRoot,"b1_affected","test_passed"); ...
    "Stage-A结构回归",suite_value(runRoot,"stage_a_structure","test_total"), ...
        suite_value(runRoot,"stage_a_structure","test_passed"); ...
    "A4-3受影响测试",suite_value(runRoot,"a4_3_affected","test_total"), ...
        suite_value(runRoot,"a4_3_affected","test_passed")];
blocks(end+1)=table_block(["测试套件","总数","通过"], ...
    suiteRows,[5000,1800,2560]);

blocks(end+1)=heading_block(1,"6. 输入哈希与证据真实性");
hashRows=strings(height(inputHashes),3);
for k=1:height(inputHashes)
    hashRows(k,:)=[string(inputHashes.file_name(k)), ...
        string(inputHashes.actualSHA256(k)),string(inputHashes.status(k))];
end
blocks(end+1)=table_block(["输入文件","SHA256","状态"], ...
    hashRows,[2300,5260,1800]);
blocks(end+1)=paragraph_block( ...
    "本报告所有数值均由当前唯一run的CSV、JSON和MAT工件重读生成。两份Excel、冻结模型合同、B-1/B-2A/B-2B/A4历史runs均未修改；未执行365日、并行、火电第二次或Stage C1实现。");

outputPath=fullfile(runRoot,"reports", ...
    "阶段B-2C_七日递推IPM收敛与水量物理验收报告.docx");
rkkt.reporting.write_stage_b2c_docx(outputPath, ...
    "阶段B-2C：七日递推IPM收敛与水量物理验收报告", ...
    "第14—20日 · 56条日级水量不等式 · 28项物理审计", ...
    metadata,blocks);
report=struct("path",string(outputPath), ...
    "run_id",string(manifest.run_id),"status","GENERATED", ...
    "design_preset","standard_business_brief", ...
    "header_pattern","memo_masthead");
end

function value=suite_value(root,name,field)
summary=read_json(required(root,fullfile("tests",name,"test_summary.json")));
value=number_text(summary.(field));
end
function value=required(root,relative)
value=fullfile(root,relative);
assert(isfile(value),"stageB2C:report:MissingArtifact", ...
    "Missing report source: %s",value);
end
function value=read_csv(pathValue)
value=readtable(pathValue,detectImportOptions(pathValue, ...
    "Delimiter",",","TextType","string","VariableNamingRule","preserve"));
end
function value=read_json(pathValue), value=jsondecode(fileread(pathValue)); end
function value=number_text(number), value=compose("%.17g",double(number)); end
function value=block_template()
value=struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end
function value=heading_block(level,textValue)
value=block_template(); value.type="heading";
value.level=level; value.text=string(textValue);
end
function value=paragraph_block(textValue)
value=block_template(); value.type="paragraph"; value.text=string(textValue);
end
function value=callout_block(titleValue,textValue)
value=block_template(); value.type="callout";
value.title=string(titleValue); value.text=string(textValue);
end
function value=table_block(headers,rows,widths)
value=block_template(); value.type="table";
value.headers=reshape(string(headers),1,[]); value.rows=string(rows);
value.widths=reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && sum(value.widths)==9360, ...
    "stageB2C:report:TableShape", ...
    "Report table geometry must total 9360 DXA.");
end
