function report = generate_stage_b2b_report(runRoot)
%GENERATE_STAGE_B2B_REPORT Generate Chinese B-2B report from artifacts only.

arguments
    runRoot (1,1) string
end
runRoot=string(java.io.File(char(runRoot)).getCanonicalPath());
manifest=read_json(required(runRoot,"run_manifest.json"));
direction=read_csv(required(runRoot,fullfile("diagnostics", ...
    "direction_comparison.csv")));
border=read_csv(required(runRoot,fullfile("diagnostics", ...
    "daily_water_border_audit.csv")));
elimination=read_csv(required(runRoot,fullfile("diagnostics", ...
    "inequality_elimination_audit.csv")));
back=read_csv(required(runRoot,fullfile("diagnostics", ...
    "back_substitution_audit.csv")));
acceptance=read_csv(required(runRoot,fullfile("acceptance", ...
    "acceptance_results.csv")));
tests=read_json(required(runRoot,fullfile("tests","test_summary.json")));
inputHashes=read_csv(required(runRoot,"input_hashes.csv"));
issues=read_csv(required(runRoot,fullfile("issues","issue_log.csv")));
assert(all(string(direction.status)=="PASS") && ...
    all(string(border.status)=="PASS") && ...
    all(string(elimination.status)=="PASS") && ...
    all(string(back.status)=="PASS") && isempty(issues), ...
    "stageB2B:report:Evidence","B-2B report source evidence is incomplete.");

metadata=struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2B", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.status), ...
    "candidate_status","B-2B READY_FOR_REVIEW", ...
    "report_kicker","STAGE B-2B · 日级水量边框递推KKT", ...
    "header_label","STAGE B-2B · 一次Newton方向验证");
blocks=repmat(block_template(),0,1);
blocks(end+1)=callout_block("结论", ...
    "本次使用第14—20日完整真实数据，把56条日级水量不等式作为每天8行的增广边框接入递推KKT。递推方向与独立完整稀疏KKT审计方向通过1e-10等价门槛。该结论仅覆盖一次Newton方向；Stage B整体仍未通过，SB-PHY-001仍待后续物理验收。");
blocks(end+1)=heading_block(1,"1. 运行身份与执行边界");
identityRows=["run_id",string(manifest.run_id); ...
    "Git提交",string(manifest.git_commit); ...
    "数据范围","第14—20日，每日1—24小时"; ...
    "完整KKT维数",number_text(manifest.full_kkt_dimension); ...
    "递推方向","已执行1次";"完整KKT","仅独立审计"; ...
    "完整IPM/优化/并行","均未执行";"Stage C1","未进入"];
blocks(end+1)=table_block(["字段","实际值"],identityRows,[3000,6360]);

blocks(end+1)=heading_block(1,"2. 方向等价与残差");
metricRows=strings(height(direction),3);
for k=1:height(direction)
    metricRows(k,:)=[string(direction.component(k)), ...
        number_text(direction.actual_value(k)), ...
        "≤"+number_text(direction.threshold(k))];
end
blocks(end+1)=table_block(["指标","实际值","门槛"], ...
    metricRows,[3600,3000,2760]);
blocks(end+1)=paragraph_block( ...
    "不等式回代严格使用 Δl=-r_ineq-GΔx 与 Δz=(-r_comp-z·Δl)./l。完整原始—对偶KKT保持合同规定的非对称块结构，未直接交给LDL；完整方向只用于独立审计，递推流程未消费该方向且不存在回退。");

blocks(end+1)=heading_block(1,"3. 七个日链与水量边框");
borderRows=strings(height(border),7);
for k=1:height(border)
    borderRows(k,:)=[number_text(border.day_id(k)), ...
        number_text(border.hourly_chain_dimension(k)), ...
        number_text(border.border_dimension(k)), ...
        number_text(border.augmented_dimension(k)), ...
        number_text(border.total_rhs(k)), ...
        number_text(border.augmented_relative_residual(k)), ...
        string(border.status(k))];
end
blocks(end+1)=table_block( ...
    ["日","小时链","边框","增广维数","RHS","相对残差","状态"], ...
    borderRows,[700,1250,1000,1400,900,2500,1610]);
blocks(end+1)=paragraph_block( ...
    "每个边框严格包含4座水电站×upper/lower共8行；每行只连接同日同站24个PH变量。水量G_w' D_w G_w未写入纯小时三对角块，而是由保留Thomas/LDL因子的8个附加右端和8维日边框处理。每天形成14×14日响应，最终只汇总到16×16全局核心。");

blocks(end+1)=heading_block(1,"4. 消元闭合、测试与验收边界");
summaryRows=["B-2B固定测试",number_text(tests.test_total), ...
        number_text(tests.test_passed); ...
    "B-2A回归",number_text(read_suite(runRoot,"b2a_regression","test_total")), ...
        number_text(read_suite(runRoot,"b2a_regression","test_passed")); ...
    "B-1回归",number_text(read_suite(runRoot,"b1_regression","test_total")), ...
        number_text(read_suite(runRoot,"b1_regression","test_passed")); ...
    "B-1受影响回归",number_text(read_suite(runRoot,"b1_affected","test_total")), ...
        number_text(read_suite(runRoot,"b1_affected","test_passed")); ...
    "Stage-A结构回归",number_text(read_suite(runRoot,"a4_structure","test_total")), ...
        number_text(read_suite(runRoot,"a4_structure","test_passed"))];
blocks(end+1)=table_block(["测试套件","总数","通过"], ...
    summaryRows,[5000,1800,2560]);
eqRow=acceptance(string(acceptance.test_id)=="SB-EQ-001",:);
phyRow=acceptance(string(acceptance.test_id)=="SB-PHY-001",:);
blocks(end+1)=callout_block("阶段门禁", ...
    "SB-EQ-001="+string(eqRow.status)+"；SB-PHY-001="+ ...
    string(phyRow.status)+"。因此B-2B可标记READY_FOR_REVIEW，但不得把Stage B整体标记为PASS，也不得进入Stage C1。");

blocks(end+1)=heading_block(1,"5. 输入哈希与证据真实性");
hashRows=strings(height(inputHashes),3);
for k=1:height(inputHashes)
    hashRows(k,:)=[string(inputHashes.file_name(k)), ...
        string(inputHashes.actualSHA256(k)),string(inputHashes.status(k))];
end
blocks(end+1)=table_block(["输入文件","SHA256","状态"], ...
    hashRows,[2300,5260,1800]);
blocks(end+1)=paragraph_block( ...
    "本报告全部数值均从当前唯一run的CSV、JSON和MAT工件重读生成；两份Excel、冻结模型合同、A4历史runs和B-2A历史证据均未修改。完整证据SHA256清单位于acceptance/evidence_hashes.csv。");

outputPath=fullfile(runRoot,"reports", ...
    "阶段B-2B_日级水量边框递推KKT方向等价验证报告.docx");
rkkt.reporting.write_stage_b2b_docx(outputPath, ...
    "阶段B-2B：日级水量边框递推KKT方向等价验证报告", ...
    "第14—20日 · 56条日级水量不等式 · 一次Newton方向", ...
    metadata,blocks);
report=struct("path",string(outputPath),"run_id",string(manifest.run_id), ...
    "status","GENERATED");
end

function value=read_suite(root,name,field)
summary=read_json(fullfile(root,"tests",name,"test_summary.json"));
value=summary.(field);
end
function value=required(root,relative)
value=fullfile(root,relative);
assert(isfile(value),"stageB2B:report:MissingArtifact", ...
    "Missing report source: %s",value);
end
function value=read_csv(pathValue)
value=readtable(pathValue,detectImportOptions(pathValue, ...
    "Delimiter",",","TextType","string","VariableNamingRule","preserve"));
end
function value=read_json(pathValue), value=jsondecode(fileread(pathValue)); end
function value=number_text(number), value=compose("%.17g",double(number)); end
function value=block_template()
value=struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end
function value=heading_block(level,textValue)
value=block_template(); value.type="heading"; value.level=level; value.text=string(textValue);
end
function value=paragraph_block(textValue)
value=block_template(); value.type="paragraph"; value.text=string(textValue);
end
function value=callout_block(titleValue,textValue)
value=block_template(); value.type="callout"; value.title=string(titleValue); value.text=string(textValue);
end
function value=table_block(headers,rows,widths)
value=block_template(); value.type="table"; value.headers=reshape(string(headers),1,[]);
value.rows=string(rows); value.widths=reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && sum(value.widths)==9360, ...
    "stageB2B:report:TableShape","Report table geometry must total 9360 DXA.");
end
