function report = generate_stage_b2c_initial_30_day_scan_report(runRoot)
%GENERATE_STAGE_B2C_INITIAL_30_DAY_SCAN_REPORT Build the Chinese run report.

arguments
    runRoot (1,1) string
end

manifest = jsondecode(fileread(fullfile(runRoot,"run_manifest.json")));
summary = read_csv(fullfile(runRoot,"diagnostics", ...
    "初始化30日日块扫描摘要.csv"));
scan = read_csv(fullfile(runRoot,"diagnostics", ...
    "初始化30日日块扫描.csv"));
equivalence = read_csv(fullfile(runRoot,"diagnostics", ...
    "正式七日日块表示一致性.csv"));
acceptance = read_csv(fullfile(runRoot,"acceptance", ...
    "acceptance_results.csv"));
analyzer = read_csv(fullfile(runRoot,"tests","code_analyzer.csv"));
testSummary = jsondecode(fileread(fullfile(runRoot,"tests", ...
    "test_summary.json")));
assert(height(summary)==14 && height(scan)==30 && ...
    height(equivalence)==7 && height(acceptance)==10 && ...
    height(analyzer)==5, ...
    "stageB2C:initialScan:ReportEvidenceRows", ...
    "The report evidence CSV row inventory is incomplete.");

weak = scan(boolean_column(scan.would_trigger_current_gate),:);
[~,order] = sort(str2double(scan.minimum_absolute_pivot),"ascend", ...
    "MissingPlacement","last");
weakest = scan(order(1:min(10,height(scan))),:);
conclusion = "初始化点30日日内联合块扫描已完成。数值弱主元按当前正式门禁原公式识别，但本诊断只记录并继续；该结果不代表Newton方向可用、IPM收敛或Stage B完成。";

metadata = struct("run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-2C diagnostic", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.milestone_status), ...
    "candidate_status","仅初始化点日块流行性诊断", ...
    "report_kicker","STAGE B-2C · 30日初始化弱主元扫描", ...
    "header_label","STAGE B-2C · 日内联合块诊断");

blocks = repmat(block_template(),0,1);
blocks(end+1) = callout_block("诊断结论",conclusion);
blocks(end+1) = heading_block(1,"1. 执行边界");
blocks(end+1) = paragraph_block( ...
    "范围固定为第1—30日、每日24小时，仅在确定性初始化状态形成并分解30个独立日内联合块。未装配完整KKT，未求Newton方向，未执行递推回代，未更新状态，未运行IPM。正式求解器与数值零主元阈值均未修改。" );

blocks(end+1) = heading_block(1,"2. 扫描摘要");
blocks(end+1) = table_block(["指标","值"], ...
    select_rows(summary,["metric","value"]),[4300,5060]);
if isempty(weak)
    blocks(end+1) = paragraph_block("30个日块均未触发当前数值零主元门禁。" );
else
    blocks(end+1) = paragraph_block("触发当前数值零主元门禁的日期："+ ...
        strjoin(string(weak.day),"、")+"。这些日期被记录后继续扫描，没有通过正则化、伪逆或改阈值处理。" );
end

blocks(end+1) = heading_block(1,"3. 最弱的10个日块");
blocks(end+1) = table_block( ...
    ["日","维数","nnz","结构秩","最小主元","参考阈值","状态"], ...
    select_rows(weakest,["day","dimension","nnz","structural_rank", ...
        "minimum_absolute_pivot","pivot_reference_tolerance","status"]), ...
    [550,750,850,850,1600,1600,3160]);

blocks(end+1) = heading_block(1,"4. 七日正式表示对照");
blocks(end+1) = table_block( ...
    ["日","诊断维数","正式维数","索引一致","矩阵isequaln","相对误差"], ...
    select_rows(equivalence,["day","diagnostic_dimension", ...
        "formal_dimension","index_exact_equal","matrix_isequaln", ...
        "matrix_relative_error"]), ...
    [650,1300,1250,1350,1450,3360]);
blocks(end+1) = paragraph_block( ...
    "该对照只证明诊断构造在第14—20日初始化点复现现有正式日内联合分块表示，不证明30日后续IPM迭代行为。" );

blocks(end+1) = heading_block(1,"5. 最小验证");
validationRows = [ ...
    "定向测试总数",number_text(testSummary.test_total); ...
    "定向测试通过",number_text(testSummary.test_passed); ...
    "Code Analyzer文件数",number_text(height(analyzer)); ...
    "Code Analyzer问题数",number_text(sum(str2double( ...
        analyzer.finding_count))); ...
    "完整KKT","未执行";"Newton方向","未计算"; ...
    "IPM与状态更新","未执行"];
blocks(end+1) = table_block(["项目","实际值"],validationRows,[4300,5060]);
blocks(end+1) = table_block(["验收项","实际值","要求","状态"], ...
    select_rows(acceptance,["check_id","actual_value","requirement","status"]), ...
    [2500,2500,2600,1760]);

outputPath = fullfile(runRoot,"reports", ...
    "阶段B-2C_初始化30日日块弱主元扫描报告.docx");
rkkt.reporting.write_stage_b2c_docx(outputPath, ...
    "阶段B-2C：初始化30日日块弱主元扫描报告", ...
    "第1—30日 · 仅初始化状态 · 数值弱主元记录后继续", ...
    metadata,blocks);
report = struct("path",string(outputPath), ...
    "run_id",string(manifest.run_id),"status","GENERATED", ...
    "design_preset","standard_business_brief", ...
    "header_pattern","memo_masthead");
end

function value = read_csv(pathValue)
options = detectImportOptions(pathValue, ...
    "Delimiter",",","TextType","string", ...
    "VariableNamingRule","preserve");
options.VariableNamesLine = 1;
options.VariableUnitsLine = 0;
options.VariableDescriptionsLine = 0;
options.DataLines = [2,Inf];
options = setvartype(options,options.VariableNames,"string");
value = readtable(pathValue,options);
end

function rows = select_rows(source,names)
rows = strings(height(source),numel(names));
for column = 1:numel(names)
    value = source.(names(column));
    if isnumeric(value) || islogical(value)
        rows(:,column) = compose("%.17g",double(value));
    else
        rows(:,column) = string(value);
    end
end
end

function value = number_text(number)
value = compose("%.17g",double(number));
end

function value = boolean_column(raw)
if islogical(raw)
    value = raw;
else
    value = lower(string(raw))=="true";
end
end

function value = block_template()
value = struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end

function value = heading_block(level,textValue)
value = block_template();
value.type = "heading";
value.level = level;
value.text = string(textValue);
end

function value = paragraph_block(textValue)
value = block_template();
value.type = "paragraph";
value.text = string(textValue);
end

function value = callout_block(titleValue,textValue)
value = block_template();
value.type = "callout";
value.title = string(titleValue);
value.text = string(textValue);
end

function value = table_block(headers,rows,widths)
value = block_template();
value.type = "table";
value.headers = reshape(string(headers),1,[]);
value.rows = string(rows);
value.widths = reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && ...
    sum(value.widths)==9360, ...
    "stageB2C:initialScan:ReportTable", ...
    "Report table geometry must total 9360 DXA.");
end
