function value = info()
%INFO Return immutable metadata for the rkkt package skeleton.
%   This function describes the package architecture only. It does not
%   inspect CURRENT_STAGE.md and does not call a production algorithm.

value = struct( ...
    "package_name","rkkt", ...
    "package_version","0.2.0", ...
    "contract_version",rkkt.contracts.version(), ...
    "pkg_stage","PKG-2", ...
    "modules",["contracts";"data";"indexing";"model";"solver"; ...
        "ipm";"artifacts";"reporting";"workflows"], ...
    "dependency_order",["contracts";"data";"indexing";"model"; ...
        "solver";"ipm";"workflows"], ...
    "implemented_public_interfaces",["rkkt.info";"rkkt.data.load"], ...
    "production_algorithm_migrated",false);
end
