function value = info()
%INFO Return immutable metadata for the rkkt package.
%   This function describes the package architecture only. It does not
%   inspect CURRENT_STAGE.md and does not call a production algorithm.

value = struct( ...
    "package_name","rkkt", ...
    "package_version","0.9.0", ...
    "contract_version",rkkt.contracts.version(), ...
    "pkg_stage","PKG-9", ...
    "modules",["contracts";"data";"indexing";"model";"solver"; ...
        "ipm";"artifacts";"reporting";"workflows"], ...
    "dependency_order",["contracts";"data";"indexing";"model"; ...
        "solver";"ipm";"workflows"], ...
    "implemented_public_interfaces", ...
        ["rkkt.info";"rkkt.data.load"; ...
        "rkkt.data.evaluateStageBDailyHydroWater"; ...
        "rkkt.indexing.build"; ...
        "rkkt.indexing.buildStageB2A"; ...
        "rkkt.indexing.buildStageB2B"; ...
        "rkkt.model.initialize";"rkkt.model.linearize"; ...
        "rkkt.model.initializeStageB2A"; ...
        "rkkt.model.linearizeStageB2A"; ...
        "rkkt.model.initializeStageB2B"; ...
        "rkkt.model.linearizeStageB2B"; ...
        "rkkt.model.residualView";"rkkt.model.jacobianView"; ...
        "rkkt.model.hessianView";"rkkt.solver.assembleFullKKT"; ...
        "rkkt.solver.solveFullKKT"; ...
        "rkkt.solver.eliminateInequalities"; ...
        "rkkt.solver.partitionRecursiveSystem"; ...
        "rkkt.solver.solveDayChain"; ...
        "rkkt.solver.buildDayResponse"; ...
        "rkkt.solver.aggregateDayResponses"; ...
        "rkkt.solver.solveGlobalCore"; ...
        "rkkt.solver.recoverDirection"; ...
        "rkkt.solver.verifyEquivalence"; ...
        "rkkt.solver.assembleStageB2AFullKKT"; ...
        "rkkt.solver.solveStageB2BRecursiveDirection"; ...
        "rkkt.solver.solveStageB2BFullKKTDirection"; ...
        "rkkt.solver.verifyStageB2BDirectionEquivalence"; ...
        "rkkt.ipm.step";"rkkt.ipm.solve"; ...
        "rkkt.artifacts.export";"rkkt.reporting.generate"; ...
        "rkkt.workflows.stageB1"; ...
        "rkkt.workflows.stageB2A"; ...
        "rkkt.workflows.stageB2B"], ...
    "production_callers_migrated",true, ...
    "production_algorithm_migrated",false, ...
    "stable_upstream_commit", ...
        "90bf33cca0611154231588ac5d7ee09fd0e9c089", ...
    "stable_backend_integrated",true, ...
    "b2c_integrated",false, ...
    "formal_project_stage","stage_B / READY", ...
    "stage_b_overall_pass_claimed",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "stage_c1_entered",false);
end
