function value = info()
%INFO Return immutable metadata for the rkkt package skeleton.
%   This function describes the package architecture only. It does not
%   inspect CURRENT_STAGE.md and does not call a production algorithm.

value = struct( ...
    "package_name","rkkt", ...
    "package_version","0.5.0", ...
    "contract_version",rkkt.contracts.version(), ...
    "pkg_stage","PKG-5", ...
    "modules",["contracts";"data";"indexing";"model";"solver"; ...
        "ipm";"artifacts";"reporting";"workflows"], ...
    "dependency_order",["contracts";"data";"indexing";"model"; ...
        "solver";"ipm";"workflows"], ...
    "implemented_public_interfaces", ...
        ["rkkt.info";"rkkt.data.load";"rkkt.indexing.build"; ...
        "rkkt.model.initialize";"rkkt.model.linearize"; ...
        "rkkt.model.residualView";"rkkt.model.jacobianView"; ...
        "rkkt.model.hessianView";"rkkt.solver.assembleFullKKT"; ...
        "rkkt.solver.solveFullKKT"; ...
        "rkkt.solver.eliminateInequalities"], ...
    "production_algorithm_migrated",false);
end
