function linearization = build_stage_a4_linearization(state,data,index,config)
%BUILD_STAGE_A4_LINEARIZATION Evaluate A4 from the caller's explicit state.

if string(config.stage_id) ~= "stage_A4" || ...
        ~isfield(index,"scope") || string(index.scope.stage_id) ~= "stage_A4" || ...
        ~isfield(state,"stage_id") || string(state.stage_id) ~= "stage_A4"
    error("stageA4:linearization:StageId", ...
        "State, index, and configuration must all identify stage_A4.");
end
types = string(index.constraint_index.constraint_type);
nInequality = nnz(types == "inequality");
if ~isfield(state,"l") || numel(state.l) ~= nInequality || ...
        any(~isfinite(state.l)) || any(state.l <= 0)
    error("stageA4:linearization:ExplicitSlack", ...
        "A4 requires one finite strictly positive explicit slack per inequality.");
end
linearization = build_stage_a_multiday_linearization( ...
    state,data,index,config,"SlackMode","explicit");
if ~isequal(linearization.l,state.l(:)) || ...
        ~isequal(linearization.state.l,state.l(:))
    error("stageA4:linearization:SlackOverwritten", ...
        "The A4 shared linearization did not preserve the caller's explicit l.");
end
scale = max(1,norm(linearization.r_ineq,inf));
if norm(linearization.slack_consistency.audit_error,inf) > ...
        8*eps(scale)
    error("stageA4:linearization:SlackConsistency", ...
        "state.l-implied_slack must equal the slack-equation residual.");
end
if linearization.stage_id ~= "stage_A4" || ...
        ~startsWith(linearization.identity,"stageA4-linearization-")
    error("stageA4:linearization:Identity", ...
        "The A4 linearization identity must not impersonate stage_A3.");
end
linearization.explicit_slack_consumed = true;
linearization.residual_definitions = struct( ...
    "r_eq","A*xi+b_eq", ...
    "r_ineq","G*xi+b_ineq+l", ...
    "physical_inequality_violation","max(max(G*xi+b_ineq,0))", ...
    "r_dual","gradient+A'*y+G'*z", ...
    "complementarity_gap","mean(l.*z)", ...
    "raw_complementarity","l'*z", ...
    "mu","sigma*mean(l.*z)");
end
