function result = evaluate_stage_b_daily_hydro_water( ...
        powerMW,waterA,waterB,waterC)
%EVALUATE_STAGE_B_DAILY_HYDRO_WATER Evaluate one plant-day water function.
%   RESULT = EVALUATE_STAGE_B_DAILY_HYDRO_WATER(POWERMW,A,B,C) consumes
%   exactly 24 finite real hourly hydro outputs in MW and returns the daily
%   water value, its analytic gradient, and its sparse analytic Hessian.
%   No time conversion is applied: the 24 hourly polynomial terms are
%   summed directly, as required by the frozen Stage-B model contract.

validate_power(powerMW);
validate_coefficient(waterA,"waterA");
validate_coefficient(waterB,"waterB");
validate_coefficient(waterC,"waterC");

powerMW = double(powerMW);
waterA = double(waterA);
waterB = double(waterB);
waterC = double(waterC);

hourCount = 24;
value = sum(waterA.*powerMW.^2 + waterB.*powerMW + waterC);
gradient = 2.*waterA.*powerMW + waterB;
hessian = spdiags(repmat(2.*waterA,hourCount,1),0, ...
    hourCount,hourCount);

result = struct();
result.value = value;
result.gradient = gradient;
result.hessian = hessian;
result.upper = struct( ...
    "constraint_form","W-Wmax<=0", ...
    "sign",1, ...
    "water_coefficient",1, ...
    "value",value, ...
    "value_without_bound",value, ...
    "gradient",gradient, ...
    "hessian",hessian);
result.lower = struct( ...
    "constraint_form","Wmin-W<=0", ...
    "sign",-1, ...
    "water_coefficient",-1, ...
    "value",-value, ...
    "value_without_bound",-value, ...
    "gradient",-gradient, ...
    "hessian",-hessian);
result.units = struct( ...
    "power","MW", ...
    "daily_water","m3/day", ...
    "time_aggregation","direct_sum_of_24_hourly_terms");
end

function validate_power(value)
if ~isnumeric(value) || ~isequal(size(value),[24,1])
    error("stageB1:hydroWater:InvalidPowerShape", ...
        "powerMW must be a 24-by-1 numeric column vector.");
end
if ~isreal(value) || any(~isfinite(value),"all")
    error("stageB1:hydroWater:InvalidPowerValue", ...
        "powerMW must contain only finite real values.");
end
end

function validate_coefficient(value,name)
if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
        ~isfinite(value)
    error("stageB1:hydroWater:InvalidCoefficient", ...
        "%s must be a finite real numeric scalar.",name);
end
end
