function config = load_stage_a2_configuration(projectRoot)
%LOAD_STAGE_A2_CONFIGURATION Read and validate the formal A2 day scope.
%
% Stage A2 is a complete physical day.  Its first and terminal hours are
% explicit configuration inputs so the model never inherits the A1
% artificial-window boundary semantics.

arguments
    projectRoot (1,1) string = default_project_root()
end

stagePath = fullfile(projectRoot,"config","stage_A2.yaml");
solverPath = fullfile(projectRoot,"config","solver.yaml");
if ~isfile(stagePath)
    error("stageA2:config:StageConfigMissing", ...
        "Stage A2 configuration is missing: %s",stagePath);
end
if ~isfile(solverPath)
    error("stageA2:config:SolverConfigMissing", ...
        "Solver configuration is missing: %s",solverPath);
end

stageText = string(fileread(stagePath));
solverText = string(fileread(solverPath));

config = struct();
config.stage_id = read_text(stageText,"stage_id");
config.status = read_text(stageText,"status");
config.days = read_number_array(stageText,"days");
config.hours = read_number_array(stageText,"hours");
config.time_scope_type = read_text(stageText,"time_scope_type");
config.start_hour = read_number(stageText,"start_hour");
config.terminal_hour = read_number(stageText,"terminal_hour");
config.soc_boundary_mode = read_text(stageText,"soc_boundary_mode");
config.terminal_soc_equality_count = read_number( ...
    stageText,"terminal_soc_equality_count");
config.run_purpose = read_text(stageText,"run_purpose");
config.expected_full_kkt_dimension = read_number( ...
    stageText,"expected_full_kkt_dimension");
config.expected_hourly_kkt_block_dimensions = read_number_array( ...
    stageText,"expected_hourly_kkt_block_dimensions");
config.expected_hourly_chain_dimension = read_number( ...
    stageText,"expected_hourly_chain_dimension");
config.expected_fixed_zero_count = read_number( ...
    stageText,"expected_fixed_zero_count");
config.expected_solar_fixed_zero_count = read_number( ...
    stageText,"expected_solar_fixed_zero_count");
config.expected_wind_fixed_zero_count = read_number( ...
    stageText,"expected_wind_fixed_zero_count");
config.expected_day_response_dimension = read_number( ...
    stageText,"expected_day_response_dimension");
config.expected_global_core_dimension = read_number( ...
    stageText,"expected_global_core_dimension");
config.direction_relative_tolerance = read_number( ...
    stageText,"direction_relative_tolerance");
config.recursive_full_kkt_residual_tolerance = read_number( ...
    stageText,"recursive_full_kkt_residual_tolerance");
config.full_kkt_direct_residual_preferred = read_number( ...
    stageText,"full_kkt_direct_residual_preferred");
config.full_kkt_direct_residual_maximum = read_number( ...
    stageText,"full_kkt_direct_residual_maximum");
config.symmetry_relative_tolerance = read_number( ...
    stageText,"symmetry_relative_tolerance");
config.newton_direction_count = read_number(stageText,"newton_direction_count");
config.run_full_ipm = read_boolean(stageText,"run_full_ipm");
config.optimization_executed = read_boolean(stageText,"optimization_executed");
config.physical_dispatch_interpretation = read_boolean( ...
    stageText,"physical_dispatch_interpretation");
config.capacity_planning_interpretation = read_boolean( ...
    stageText,"capacity_planning_interpretation");
config.economic_interpretation = read_boolean( ...
    stageText,"economic_interpretation");
config.artifact_mode = read_text(stageText,"artifact_mode");
config.parallel_mode = read_text(stageText,"parallel_mode");

config.initialization = struct( ...
    "global_capacity",read_text(solverText,"global_capacity"), ...
    "daily_capacity_copy_equals_global",read_boolean( ...
        solverText,"daily_capacity_copy_equals_global"), ...
    "active_wind_solar_fraction_of_upper",read_number( ...
        solverText,"active_wind_solar_fraction_of_upper"), ...
    "hydro_thermal_fraction_of_upper",read_number( ...
        solverText,"hydro_thermal_fraction_of_upper"), ...
    "charge_discharge_fraction_of_power_capacity",read_number( ...
        solverText,"charge_discharge_fraction_of_power_capacity"), ...
    "soc_fraction_of_energy_capacity",read_number( ...
        solverText,"soc_fraction_of_energy_capacity"), ...
    "equality_multipliers",read_number(solverText,"equality_multipliers"), ...
    "inequality_multiplier",read_number(solverText,"inequality_multiplier"), ...
    "centering_sigma",read_number(solverText,"centering_sigma"));
% Archived A2 acceptance remains governed by stage_A2.yaml.
config.tolerances = struct( ...
    "direction_relative_2norm",config.direction_relative_tolerance, ...
    "recursive_full_kkt_relative_residual", ...
        config.recursive_full_kkt_residual_tolerance, ...
    "direct_preferred",config.full_kkt_direct_residual_preferred, ...
    "direct_maximum",config.full_kkt_direct_residual_maximum, ...
    "symmetry_relative",config.symmetry_relative_tolerance);
config.linear_algebra = struct( ...
    "local_factorization",read_text(solverText,"local_factorization"), ...
    "global_core_factorization",read_text( ...
        solverText,"global_core_factorization"), ...
    "multiple_rhs",read_boolean(solverText,"multiple_rhs"), ...
    "explicit_inverse",read_boolean(solverText,"explicit_inverse"), ...
    "pseudoinverse",read_boolean(solverText,"pseudoinverse"), ...
    "least_norm_fallback",read_boolean(solverText,"least_norm_fallback"), ...
    "recursive_fallback_to_full_kkt",read_boolean( ...
        solverText,"recursive_fallback_to_full_kkt"), ...
    "automatic_regularization",read_boolean( ...
        solverText,"automatic_regularization"), ...
    "automatic_symmetrization",read_boolean( ...
        solverText,"automatic_symmetrization"));
config.source_paths = struct("stage",stagePath,"solver",solverPath);

validate_configuration(config);
end

function validate_configuration(config)
assert(config.stage_id == "stage_A2","stageA2:config:StageId", ...
    "stage_id must be stage_A2.");
assert(ismember(config.status,["READY","PASS"]), ...
    "stageA2:config:StageStatus", ...
    "Stage A2 configuration must be READY or archived PASS.");
assert(isequal(config.days,14) && isequal(config.hours,1:24), ...
    "stageA2:config:FormalDay", ...
    "Stage A2 must select day 14 and all physical hours 1 through 24.");
assert(config.time_scope_type == "formal_24_hour_day", ...
    "stageA2:config:TimeScopeType", ...
    "Stage A2 time_scope_type must identify a formal 24-hour day.");
assert(config.start_hour == 1 && config.terminal_hour == 24 && ...
    isequal(config.hours,config.start_hour:config.terminal_hour), ...
    "stageA2:config:Hours", ...
    "The formal A2 day must explicitly span hours 1 through 24.");
assert(config.soc_boundary_mode == "formal_daily_fixed_half_energy", ...
    "stageA2:config:SocBoundaryMode", ...
    "Stage A2 requires the formal daily fixed-half-energy SOC boundary.");
assert(config.terminal_soc_equality_count == 2, ...
    "stageA2:config:TerminalSocCount", ...
    "The formal day requires exactly two terminal SOC equalities.");
assert(config.run_purpose == "algorithmic_direction_equivalence_only", ...
    "stageA2:config:RunPurpose", ...
    "Stage A2 may only be used for one direction-equivalence verification.");
assert(config.expected_full_kkt_dimension == 2749, ...
    "stageA2:config:FullDimension", ...
    "The controlled A2 complete KKT dimension is 2749.");
expectedBlocks = [repmat(22,1,7),repmat(27,1,11),26, ...
    repmat(22,1,4),24];
assert(isequal(config.expected_hourly_kkt_block_dimensions,expectedBlocks), ...
    "stageA2:config:BlockDimensions", ...
    "The controlled A2 hourly block dimensions are not the required vector.");
assert(config.expected_hourly_chain_dimension == 589 && ...
    sum(config.expected_hourly_kkt_block_dimensions) == 589, ...
    "stageA2:config:ChainDimension", ...
    "The controlled A2 hourly chain dimension must be 589.");
assert(config.expected_fixed_zero_count == 61 && ...
    config.expected_solar_fixed_zero_count == 60 && ...
    config.expected_wind_fixed_zero_count == 1, ...
    "stageA2:config:FixedZeroCounts", ...
    "The controlled A2 fixed-zero composition must be 60 solar plus 1 wind.");
assert(config.expected_day_response_dimension == 14 && ...
    config.expected_global_core_dimension == 16, ...
    "stageA2:config:ReducedDimensions", ...
    "Stage A2 requires a 14-dimensional day response and 16-dimensional core.");
assert(config.newton_direction_count == 1 && ~config.run_full_ipm && ...
    ~config.optimization_executed, ...
    "stageA2:config:ExecutionScope", ...
    "Stage A2 permits one Newton direction and forbids optimization/IPM execution.");
assert(~config.physical_dispatch_interpretation && ...
    ~config.capacity_planning_interpretation && ...
    ~config.economic_interpretation && config.parallel_mode == "off", ...
    "stageA2:config:ForbiddenScope", ...
    "Stage A2 forbids interpretation conclusions and parallel execution.");
assert(config.artifact_mode == "unique_run_directory", ...
    "stageA2:config:ArtifactMode", ...
    "Stage A2 artifacts must use a unique run directory.");
assert(config.tolerances.direction_relative_2norm == 1e-10 && ...
    config.tolerances.recursive_full_kkt_relative_residual == 1e-10 && ...
    config.direction_relative_tolerance == ...
        config.tolerances.direction_relative_2norm && ...
    config.recursive_full_kkt_residual_tolerance == ...
        config.tolerances.recursive_full_kkt_relative_residual, ...
    "stageA2:config:EquivalenceTolerance", ...
    "Stage A2 equivalence tolerances must remain exactly 1e-10.");
assert(config.tolerances.direct_preferred == 1e-12 && ...
    config.tolerances.direct_maximum == 1e-10 && ...
    config.tolerances.symmetry_relative == 1e-12, ...
    "stageA2:config:DiagnosticTolerance", ...
    "A2 direct-residual and symmetry diagnostic thresholds changed.");
assert(config.initialization.global_capacity == "midpoint" && ...
    config.initialization.daily_capacity_copy_equals_global, ...
    "stageA2:config:Initialization", ...
    "Stage A2 requires midpoint capacities and identical daily copies.");
assert(config.initialization.centering_sigma > 0 && ...
    config.initialization.centering_sigma < 1, ...
    "stageA2:config:CenteringSigma", ...
    "centering_sigma must lie strictly between zero and one.");
assert(config.linear_algebra.local_factorization == "ldl_vector" && ...
    config.linear_algebra.global_core_factorization == "ldl_vector" && ...
    config.linear_algebra.multiple_rhs, ...
    "stageA2:config:LinearAlgebra", ...
    "Stage A2 requires vector-permuted LDL with multiple right hand sides.");
assert(~config.linear_algebra.explicit_inverse && ...
    ~config.linear_algebra.pseudoinverse && ...
    ~config.linear_algebra.least_norm_fallback && ...
    ~config.linear_algebra.recursive_fallback_to_full_kkt && ...
    ~config.linear_algebra.automatic_regularization && ...
    ~config.linear_algebra.automatic_symmetrization, ...
    "stageA2:config:ForbiddenLinearAlgebra", ...
    "Forbidden fallback, regularization, or symmetrization is enabled.");
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if startsWith(raw,'"') && endsWith(raw,'"')
    raw = extractBetween(raw,2,strlength(raw)-1);
elseif startsWith(raw,"'") && endsWith(raw,"'")
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value) > 0,"stageA2:config:EmptyText", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
raw = read_raw_value(document,key);
value = str2double(raw);
assert(isscalar(value) && isfinite(value),"stageA2:config:Number", ...
    "Configuration key %s must be a finite scalar number.",key);
end

function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[") && endsWith(raw,"]"), ...
    "stageA2:config:NumberArray", ...
    "Configuration key %s must use an explicit YAML flow sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
if strlength(strip(body)) == 0
    values = zeros(1,0);
    return;
end
parts = split(body,",");
values = str2double(strip(parts)).';
assert(all(isfinite(values)),"stageA2:config:NumberArray", ...
    "Configuration key %s contains a nonnumeric value.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageA2:config:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw == "true";
end

function raw = read_raw_value(document,key)
escapedKey = regexptranslate('escape',char(key));
pattern = ['(?m)^[ \t]*',escapedKey,'[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
if isempty(tokens)
    error("stageA2:config:MissingKey", ...
        "Configuration key %s is missing.",key);
end
if numel(tokens) ~= 1
    error("stageA2:config:DuplicateKey", ...
        "Configuration key %s is not unique.",key);
end
raw = strip(string(tokens{1}{1}));
end

function projectRoot = default_project_root()
modelDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fileparts(modelDirectory);
projectRoot = string(fileparts(sourceDirectory));
end
