function config = load_stage_a3_configuration(projectRoot)
%LOAD_STAGE_A3_CONFIGURATION Read and validate the formal seven-day scope.

arguments
    projectRoot (1,1) string = default_project_root()
end

stagePath = fullfile(projectRoot,"config","stage_A3.yaml");
solverPath = fullfile(projectRoot,"config","solver.yaml");
if ~isfile(stagePath)
    error("stageA3:config:StageConfigMissing", ...
        "Stage A3 configuration is missing: %s",stagePath);
end
if ~isfile(solverPath)
    error("stageA3:config:SolverConfigMissing", ...
        "Solver configuration is missing: %s",solverPath);
end

stageText = string(fileread(stagePath));
solverText = string(fileread(solverPath));
config = struct();
config.stage_id = read_text(stageText,"stage_id");
config.status = read_text(stageText,"status");
config.description = read_text(stageText,"description");
config.days = read_number_array(stageText,"days");
config.hours = read_number_array(stageText,"hours");
config.time_scope_type = read_text(stageText,"time_scope_type");
config.start_hour = read_number(stageText,"start_hour");
config.terminal_hour = read_number(stageText,"terminal_hour");
config.soc_boundary_mode = read_text(stageText,"soc_boundary_mode");
config.terminal_soc_equality_count_per_day = read_number( ...
    stageText,"terminal_soc_equality_count_per_day");
config.run_purpose = read_text(stageText,"run_purpose");
config.aggregation_day_order = read_number_array( ...
    stageText,"aggregation_day_order");
config.expected_full_kkt_dimension = read_number( ...
    stageText,"expected_full_kkt_dimension");
config.expected_day_count = read_number(stageText,"expected_day_count");
config.expected_day_response_dimension = read_number( ...
    stageText,"expected_day_response_dimension");
config.expected_day_rhs_dimension = read_number( ...
    stageText,"expected_day_rhs_dimension");
config.expected_global_core_dimension = read_number( ...
    stageText,"expected_global_core_dimension");
config.expected_daily_hourly_chain_dimensions = read_number_array( ...
    stageText,"expected_daily_hourly_chain_dimensions");
config.expected_total_hourly_chain_dimension = read_number( ...
    stageText,"expected_total_hourly_chain_dimension");
config.expected_fixed_zero_count = read_number( ...
    stageText,"expected_fixed_zero_count");
config.direction_relative_tolerance = read_number( ...
    stageText,"direction_relative_tolerance");
config.recursive_full_kkt_residual_tolerance = read_number( ...
    stageText,"recursive_full_kkt_residual_tolerance");
config.full_kkt_direct_residual_preferred = read_number( ...
    stageText,"full_kkt_direct_residual_preferred");
config.full_kkt_direct_residual_maximum = read_number( ...
    stageText,"full_kkt_direct_residual_maximum");
config.symmetry_relative_tolerance = read_number( ...
    stageText,"symmetry_relative_tolerance");
config.aggregation_order_tolerance = read_number( ...
    stageText,"aggregation_order_tolerance");
config.newton_direction_count = read_number(stageText,"newton_direction_count");
config.run_full_ipm = read_boolean(stageText,"run_full_ipm");
config.optimization_executed = read_boolean(stageText,"optimization_executed");
config.physical_dispatch_interpretation = read_boolean( ...
    stageText,"physical_dispatch_interpretation");
config.capacity_planning_interpretation = read_boolean( ...
    stageText,"capacity_planning_interpretation");
config.economic_interpretation = read_boolean( ...
    stageText,"economic_interpretation");
config.water_constraints_enabled = read_boolean( ...
    stageText,"water_constraints_enabled");
config.thermal_second_pass_enabled = read_boolean( ...
    stageText,"thermal_second_pass_enabled");
config.artifact_mode = read_text(stageText,"artifact_mode");
config.parallel_mode = read_text(stageText,"parallel_mode");
config.day_response_side_effects = read_text( ...
    stageText,"day_response_side_effects");

config.initialization = struct( ...
    "global_capacity",read_text(solverText,"global_capacity"), ...
    "daily_capacity_copy_equals_global",read_boolean( ...
        solverText,"daily_capacity_copy_equals_global"), ...
    "active_wind_solar_fraction_of_upper",read_number( ...
        solverText,"active_wind_solar_fraction_of_upper"), ...
    "hydro_thermal_fraction_of_upper",read_number( ...
        solverText,"hydro_thermal_fraction_of_upper"), ...
    "charge_discharge_fraction_of_power_capacity",read_number( ...
        solverText,"charge_discharge_fraction_of_power_capacity"), ...
    "soc_fraction_of_energy_capacity",read_number( ...
        solverText,"soc_fraction_of_energy_capacity"), ...
    "equality_multipliers",read_number(solverText,"equality_multipliers"), ...
    "inequality_multiplier",read_number(solverText,"inequality_multiplier"), ...
    "centering_sigma",read_number(solverText,"centering_sigma"));
% Archived A3 acceptance remains governed by stage_A3.yaml.
config.tolerances = struct( ...
    "direction_relative_2norm",config.direction_relative_tolerance, ...
    "recursive_full_kkt_relative_residual", ...
        config.recursive_full_kkt_residual_tolerance, ...
    "direct_preferred",config.full_kkt_direct_residual_preferred, ...
    "direct_maximum",config.full_kkt_direct_residual_maximum, ...
    "symmetry_relative",config.symmetry_relative_tolerance, ...
    "aggregation_order",config.aggregation_order_tolerance);
config.linear_algebra = struct( ...
    "local_factorization",read_text(solverText,"local_factorization"), ...
    "global_core_factorization",read_text( ...
        solverText,"global_core_factorization"), ...
    "multiple_rhs",read_boolean(solverText,"multiple_rhs"), ...
    "explicit_inverse",read_boolean(solverText,"explicit_inverse"), ...
    "pseudoinverse",read_boolean(solverText,"pseudoinverse"), ...
    "least_norm_fallback",read_boolean(solverText,"least_norm_fallback"), ...
    "recursive_fallback_to_full_kkt",read_boolean( ...
        solverText,"recursive_fallback_to_full_kkt"), ...
    "automatic_regularization",read_boolean( ...
        solverText,"automatic_regularization"), ...
    "automatic_symmetrization",read_boolean( ...
        solverText,"automatic_symmetrization"));
config.source_paths = struct("stage",stagePath,"solver",solverPath);

validate_configuration(config);
end

function validate_configuration(config)
assert(config.stage_id == "stage_A3","stageA3:config:StageId", ...
    "stage_id must be stage_A3.");
assert(ismember(config.status,["READY","PASS"]), ...
    "stageA3:config:StageStatus", ...
    "Stage A3 configuration must be READY or archived PASS.");
assert(isequal(config.days,14:20) && isequal(config.hours,1:24), ...
    "stageA3:config:FormalSevenDays", ...
    "Stage A3 must select days 14 through 20 and all 24 hours.");
assert(config.time_scope_type == "formal_7_day_scope" && ...
    config.start_hour == 1 && config.terminal_hour == 24, ...
    "stageA3:config:TimeScope", ...
    "Stage A3 must identify seven formal full-day scopes.");
assert(config.soc_boundary_mode == "formal_daily_fixed_half_energy" && ...
    config.terminal_soc_equality_count_per_day == 2, ...
    "stageA3:config:SocBoundary", ...
    "Every A3 day requires fixed-half-energy initial and terminal SOC boundaries.");
assert(config.run_purpose == "algorithmic_direction_equivalence_only", ...
    "stageA3:config:RunPurpose", ...
    "A3 may only execute the single-direction equivalence fixture.");
assert(isequal(config.aggregation_day_order,config.days) && ...
    config.expected_day_count == numel(config.days), ...
    "stageA3:config:DayOrder", ...
    "A3 aggregation order must be exactly days 14 through 20.");
assert(config.expected_full_kkt_dimension == 18836, ...
    "stageA3:config:FullDimension", ...
    "The controlled seven-day complete KKT dimension is 18836.");
assert(config.expected_day_response_dimension == 14 && ...
    config.expected_day_rhs_dimension == 14 && ...
    config.expected_global_core_dimension == 16, ...
    "stageA3:config:ReducedDimensions", ...
    "A3 requires seven 14-dimensional responses and one 16-dimensional core.");
assert(isequal(config.expected_daily_hourly_chain_dimensions, ...
    [589,590,589,590,590,590,590]) && ...
    config.expected_total_hourly_chain_dimension == 4128 && ...
    sum(config.expected_daily_hourly_chain_dimensions) == 4128, ...
    "stageA3:config:ChainDimensions", ...
    "Configured daily chain dimensions disagree with the controlled data.");
assert(config.expected_fixed_zero_count == 422, ...
    "stageA3:config:FixedZeroCount", ...
    "The controlled days 14 through 20 contain 422 exact-zero renewables.");
assert(config.newton_direction_count == 1 && ~config.run_full_ipm && ...
    ~config.optimization_executed && config.parallel_mode == "off", ...
    "stageA3:config:ExecutionScope", ...
    "A3 permits one serial Newton direction and forbids optimization/IPM.");
assert(~config.physical_dispatch_interpretation && ...
    ~config.capacity_planning_interpretation && ...
    ~config.economic_interpretation && ...
    ~config.water_constraints_enabled && ...
    ~config.thermal_second_pass_enabled, ...
    "stageA3:config:ForbiddenScope", ...
    "A3 forbids physical/economic conclusions, water constraints, and pass two.");
assert(config.artifact_mode == "unique_run_directory" && ...
    config.day_response_side_effects == "none", ...
    "stageA3:config:ExecutionIsolation", ...
    "A3 requires unique artifacts and side-effect-free daily response tasks.");
assert(config.direction_relative_tolerance == 1e-10 && ...
    config.recursive_full_kkt_residual_tolerance == 1e-10 && ...
    config.tolerances.direction_relative_2norm == 1e-10 && ...
    config.tolerances.recursive_full_kkt_relative_residual == 1e-10, ...
    "stageA3:config:EquivalenceTolerance", ...
    "A3 equivalence tolerances must remain exactly 1e-10.");
assert(config.tolerances.direct_preferred == 1e-12 && ...
    config.tolerances.direct_maximum == 1e-10 && ...
    config.tolerances.symmetry_relative == 1e-12 && ...
    config.tolerances.aggregation_order == 1e-14, ...
    "stageA3:config:DiagnosticTolerance", ...
    "A3 diagnostic tolerances changed.");
assert(config.initialization.global_capacity == "midpoint" && ...
    config.initialization.daily_capacity_copy_equals_global && ...
    config.initialization.centering_sigma > 0 && ...
    config.initialization.centering_sigma < 1, ...
    "stageA3:config:Initialization", ...
    "A3 requires the frozen deterministic interior initialization.");
assert(config.linear_algebra.local_factorization == "ldl_vector" && ...
    config.linear_algebra.global_core_factorization == "ldl_vector" && ...
    config.linear_algebra.multiple_rhs, ...
    "stageA3:config:LinearAlgebra", ...
    "A3 requires vector-permuted LDL with multiple right hand sides.");
assert(~config.linear_algebra.explicit_inverse && ...
    ~config.linear_algebra.pseudoinverse && ...
    ~config.linear_algebra.least_norm_fallback && ...
    ~config.linear_algebra.recursive_fallback_to_full_kkt && ...
    ~config.linear_algebra.automatic_regularization && ...
    ~config.linear_algebra.automatic_symmetrization, ...
    "stageA3:config:ForbiddenLinearAlgebra", ...
    "Forbidden fallback, regularization, or symmetrization is enabled.");
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if startsWith(raw,'"') && endsWith(raw,'"')
    raw = extractBetween(raw,2,strlength(raw)-1);
elseif startsWith(raw,"'") && endsWith(raw,"'")
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value) > 0,"stageA3:config:EmptyText", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
raw = read_raw_value(document,key);
value = str2double(raw);
assert(isscalar(value) && isfinite(value),"stageA3:config:Number", ...
    "Configuration key %s must be a finite scalar number.",key);
end

function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[") && endsWith(raw,"]"), ...
    "stageA3:config:NumberArray", ...
    "Configuration key %s must use an explicit YAML flow sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
if strlength(strip(body)) == 0
    values = zeros(1,0);
    return;
end
parts = split(body,",");
values = str2double(strip(parts)).';
assert(all(isfinite(values)),"stageA3:config:NumberArray", ...
    "Configuration key %s contains a nonnumeric value.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageA3:config:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw == "true";
end

function raw = read_raw_value(document,key)
escapedKey = regexptranslate('escape',char(key));
pattern = ['(?m)^[ \t]*',escapedKey,'[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
if isempty(tokens)
    error("stageA3:config:MissingKey", ...
        "Configuration key %s is missing.",key);
end
if numel(tokens) ~= 1
    error("stageA3:config:DuplicateKey", ...
        "Configuration key %s is not unique.",key);
end
raw = strip(string(tokens{1}{1}));
end

function projectRoot = default_project_root()
modelDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fileparts(modelDirectory);
projectRoot = string(fileparts(sourceDirectory));
end
