function config = load_stage_a4_configuration(projectRoot)
%LOAD_STAGE_A4_CONFIGURATION Read and strictly validate the A4-1 scope.

arguments
    projectRoot (1,1) string = default_project_root()
end

stagePath = fullfile(projectRoot,"config","stage_A4.yaml");
solverPath = fullfile(projectRoot,"config","solver.yaml");
currentStagePath = fullfile(projectRoot,"CURRENT_STAGE.md");
require_file(stagePath,"stageA4:config:StageConfigMissing");
require_file(solverPath,"stageA4:config:SolverConfigMissing");
require_file(currentStagePath,"stageA4:config:CurrentStageMissing");
stageText = string(fileread(stagePath));
solverText = string(fileread(solverPath));
currentText = string(fileread(currentStagePath));

config = struct();
textKeys = ["stage_id","status","description","time_scope_type", ...
    "soc_boundary_mode","run_purpose","objective_mode","thermal_pass", ...
    "thermal_lower_bound_mode","parallel_mode","day_response_side_effects", ...
    "a4_2a_run_purpose","a4_2b_run_purpose"];
for key = textKeys
    config.(key) = read_text(stageText,key);
end
config.days = read_number_array(stageText,"days");
config.hours = read_number_array(stageText,"hours");
config.aggregation_day_order = read_number_array( ...
    stageText,"aggregation_day_order");
numberKeys = ["start_hour","terminal_hour", ...
    "terminal_soc_equality_count_per_day", ...
    "expected_full_kkt_dimension","expected_day_count", ...
    "expected_day_response_dimension","expected_day_rhs_dimension", ...
    "expected_global_core_dimension","expected_total_hourly_chain_dimension", ...
    "expected_fixed_zero_count","direction_relative_tolerance", ...
    "recursive_full_kkt_residual_tolerance", ...
    "full_kkt_direct_residual_preferred", ...
    "full_kkt_direct_residual_maximum","symmetry_relative_tolerance", ...
    "newton_direction_count", ...
    "a4_1_iteration_count","a4_2a_iteration_count", ...
    "a4_2b_iteration_count"];
for key = numberKeys
    config.(key) = read_number(stageText,key);
end
config.expected_daily_hourly_chain_dimensions = read_number_array( ...
    stageText,"expected_daily_hourly_chain_dimensions");
booleanKeys = ["full_ipm_allowed","formal_a4_run", ...
    "optimization_executed","water_constraints_enabled", ...
    "thermal_second_pass_enabled","annual_multiobjective_enabled", ...
    "physical_dispatch_interpretation", ...
    "capacity_planning_interpretation","economic_interpretation"];
for key = booleanKeys
    config.(key) = read_boolean(stageText,key);
end

config.solver_contract_version = read_text(solverText,"solver_contract_version");
config.initialization = struct( ...
    "global_capacity",read_text(solverText,"global_capacity"), ...
    "daily_capacity_copy_equals_global",read_boolean( ...
        solverText,"daily_capacity_copy_equals_global"), ...
    "active_wind_solar_fraction_of_upper",read_number( ...
        solverText,"active_wind_solar_fraction_of_upper"), ...
    "hydro_thermal_fraction_of_upper",read_number( ...
        solverText,"hydro_thermal_fraction_of_upper"), ...
    "charge_discharge_fraction_of_power_capacity",read_number( ...
        solverText,"charge_discharge_fraction_of_power_capacity"), ...
    "soc_fraction_of_energy_capacity",read_number( ...
        solverText,"soc_fraction_of_energy_capacity"), ...
    "equality_multipliers",read_number(solverText,"equality_multipliers"), ...
    "inequality_multiplier",read_number( ...
        solverText,"inequality_multiplier"), ...
    "centering_sigma",read_number(solverText,"centering_sigma"));
config.fraction_to_boundary = read_number(solverText,"fraction_to_boundary");
config.convergence = struct( ...
    "max_iterations",read_number(solverText,"max_iterations"), ...
    "primal_equality_inf",read_number(solverText,"primal_equality_inf"), ...
    "primal_inequality_inf",read_number( ...
        solverText,"primal_inequality_inf"), ...
    "dual_inf",read_number(solverText,"dual_inf"), ...
    "normalized_complementarity_gap",read_number( ...
        solverText,"normalized_complementarity_gap"));
config.tolerances = struct( ...
    "direction_relative_2norm",read_number( ...
        solverText,"direction_relative_2norm"), ...
    "recursive_full_kkt_relative_residual",read_number( ...
        solverText,"recursive_direction_full_kkt_relative_residual"), ...
    "direct_preferred",config.full_kkt_direct_residual_preferred, ...
    "direct_maximum",config.full_kkt_direct_residual_maximum, ...
    "symmetry_relative",config.symmetry_relative_tolerance);
config.linear_algebra = struct( ...
    "local_factorization",read_text(solverText,"local_factorization"), ...
    "global_core_factorization",read_text( ...
        solverText,"global_core_factorization"), ...
    "multiple_rhs",read_boolean(solverText,"multiple_rhs"), ...
    "explicit_inverse",read_boolean(solverText,"explicit_inverse"), ...
    "pseudoinverse",read_boolean(solverText,"pseudoinverse"), ...
    "least_norm_fallback",read_boolean(solverText,"least_norm_fallback"), ...
    "recursive_fallback_to_full_kkt",read_boolean( ...
        solverText,"recursive_fallback_to_full_kkt"), ...
    "automatic_regularization",read_boolean( ...
        solverText,"automatic_regularization"), ...
    "automatic_symmetrization",read_boolean( ...
        solverText,"automatic_symmetrization"));
config.current_stage = struct( ...
    "stage_id",read_markdown_field(currentText,"stage_id"), ...
    "status",read_markdown_field(currentText,"status"));
config.source_paths = struct("stage",stagePath,"solver",solverPath, ...
    "current_stage",currentStagePath);

validate_configuration(config);
end

function validate_configuration(config)
assert(config.stage_id == "stage_A4" && config.status == "READY" && ...
    config.current_stage.stage_id == "stage_A4" && ...
    config.current_stage.status == "READY", ...
    "stageA4:config:StageGate", ...
    "Both stage_A4.yaml and CURRENT_STAGE.md must be stage_A4 / READY.");
assert(isequal(config.days,14:20) && isequal(config.hours,1:24) && ...
    isequal(config.aggregation_day_order,14:20) && ...
    config.time_scope_type == "formal_7_day_scope" && ...
    config.start_hour == 1 && config.terminal_hour == 24, ...
    "stageA4:config:FormalSevenDays", ...
    "A4 must select formal full days 14 through 20 and hours 1 through 24.");
assert(config.soc_boundary_mode == "formal_daily_fixed_half_energy" && ...
    config.terminal_soc_equality_count_per_day == 2, ...
    "stageA4:config:SocBoundary", ...
    "Each A4 day must start and end at 0.5E with two terminal rows.");
assert(config.run_purpose == ...
    "a4_1_single_primal_dual_iteration_closed_loop" && ...
    config.newton_direction_count == 1 && ...
    config.a4_1_iteration_count == 1 && ...
    config.a4_2a_run_purpose == ...
        "five_iteration_primal_dual_convergence_diagnostic" && ...
    config.a4_2a_iteration_count == 5 && ...
    config.a4_2b_run_purpose == ...
        "five_iteration_complementarity_gap_cause_audit" && ...
    config.a4_2b_iteration_count == 5 && config.full_ipm_allowed && ...
    ~config.formal_a4_run && ~config.optimization_executed, ...
    "stageA4:config:A41ExecutionScope", ...
    ["A4-1 permits exactly one closed-loop iteration; A4-2A and A4-2B " ...
     "each require exactly five diagnostic iterations. None is a formal A4 run."]);
assert(config.expected_full_kkt_dimension == 18836 && ...
    config.expected_day_count == 7 && ...
    config.expected_day_response_dimension == 14 && ...
    config.expected_day_rhs_dimension == 14 && ...
    config.expected_global_core_dimension == 16 && ...
    isequal(config.expected_daily_hourly_chain_dimensions, ...
        [589,590,589,590,590,590,590]) && ...
    config.expected_total_hourly_chain_dimension == 4128 && ...
    config.expected_fixed_zero_count == 422, ...
    "stageA4:config:ControlledDimensions", ...
    "A4 controlled dimensions or fixed-zero count changed.");
assert(config.objective_mode == "investment_cost_only" && ...
    config.thermal_pass == "first" && ...
    config.thermal_lower_bound_mode == "zero" && ...
    ~config.water_constraints_enabled && ...
    ~config.thermal_second_pass_enabled && ...
    ~config.annual_multiobjective_enabled && ...
    ~config.physical_dispatch_interpretation && ...
    ~config.capacity_planning_interpretation && ...
    ~config.economic_interpretation, ...
    "stageA4:config:FrozenModelScope", ...
    "A4-1 must use only investment cost and first-pass thermal bounds.");
assert(config.parallel_mode == "off" && ...
    config.day_response_side_effects == "none", ...
    "stageA4:config:SerialExecution", ...
    "A4-1 must remain serial and daily responses must be side-effect free.");
assert(config.solver_contract_version == "1.0" && ...
    config.initialization.global_capacity == "midpoint" && ...
    config.initialization.daily_capacity_copy_equals_global && ...
    config.initialization.centering_sigma == 0.1 && ...
    config.fraction_to_boundary == 0.9995, ...
    "stageA4:config:SolverInitialization", ...
    "The controlled solver initialization, sigma, or tau changed.");
assert(config.convergence.max_iterations == 100 && ...
    config.convergence.primal_equality_inf == 1e-8 && ...
    config.convergence.primal_inequality_inf == 1e-8 && ...
    config.convergence.dual_inf == 1e-8 && ...
    config.convergence.normalized_complementarity_gap == 1e-8 && ...
    config.tolerances.direction_relative_2norm == 1e-10 && ...
    config.tolerances.recursive_full_kkt_relative_residual == 1e-10 && ...
    config.direction_relative_tolerance == 1e-10 && ...
    config.recursive_full_kkt_residual_tolerance == 1e-10 && ...
    config.tolerances.direct_preferred == 1e-12 && ...
    config.tolerances.direct_maximum == 1e-10 && ...
    config.tolerances.symmetry_relative == 1e-12, ...
    "stageA4:config:SolverThresholds", ...
    "Existing solver convergence or equivalence thresholds changed.");
assert(config.linear_algebra.local_factorization == "ldl_vector" && ...
    config.linear_algebra.global_core_factorization == "ldl_vector" && ...
    config.linear_algebra.multiple_rhs && ...
    ~config.linear_algebra.explicit_inverse && ...
    ~config.linear_algebra.pseudoinverse && ...
    ~config.linear_algebra.least_norm_fallback && ...
    ~config.linear_algebra.recursive_fallback_to_full_kkt && ...
    ~config.linear_algebra.automatic_regularization && ...
    ~config.linear_algebra.automatic_symmetrization, ...
    "stageA4:config:ForbiddenLinearAlgebra", ...
    "A forbidden inverse, fallback, regularization, or symmetrization is enabled.");
end

function require_file(path,identifier)
if ~isfile(path)
    error(identifier,"Required configuration file is missing: %s",path);
end
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if (startsWith(raw,'"') && endsWith(raw,'"')) || ...
        (startsWith(raw,"'") && endsWith(raw,"'"))
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value) > 0,"stageA4:config:EmptyText", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
value = str2double(read_raw_value(document,key));
assert(isscalar(value) && isfinite(value),"stageA4:config:Number", ...
    "Configuration key %s must be a finite scalar number.",key);
end

function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[") && endsWith(raw,"]"), ...
    "stageA4:config:NumberArray", ...
    "Configuration key %s must use an explicit YAML flow sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
if strlength(strip(body)) == 0
    values = zeros(1,0);
else
    values = str2double(strip(split(body,","))).';
end
assert(all(isfinite(values)),"stageA4:config:NumberArray", ...
    "Configuration key %s contains a nonnumeric value.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageA4:config:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw == "true";
end

function raw = read_raw_value(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
if isempty(tokens)
    error("stageA4:config:MissingKey", ...
        "Configuration key %s is missing.",key);
elseif numel(tokens) ~= 1
    error("stageA4:config:DuplicateKey", ...
        "Configuration key %s is not unique.",key);
end
raw = strip(string(tokens{1}{1}));
end

function value = read_markdown_field(document,key)
pattern = ['(?m)^-[ \t]*`',regexptranslate('escape',char(key)), ...
    '`[ \t]*:[ \t]*`([^`]+)`[ \t\r]*$'];
tokens = regexp(char(document),pattern,'tokens');
if numel(tokens) ~= 1
    error("stageA4:config:CurrentStageField", ...
        "CURRENT_STAGE.md field %s must occur exactly once.",key);
end
value = string(tokens{1}{1});
end

function projectRoot = default_project_root()
modelDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fileparts(modelDirectory);
projectRoot = string(fileparts(sourceDirectory));
end
