function config = load_stage_a4_3_configuration(projectRoot)
%LOAD_STAGE_A4_3_CONFIGURATION Load and freeze the formal A4-3 controls.
%
% The existing stage_A4.yaml remains the authority for the frozen Stage-A
% model and historic A4 diagnostic entries.  This loader adds only the
% separately versioned A4-3 execution contract; it does not change solver
% parameters, model equations, indexing, or acceptance thresholds.

arguments
    projectRoot (1,1) string = default_project_root()
end

config = load_stage_a4_configuration(projectRoot);
pathValue = fullfile(projectRoot,"config","stage_A4_3.yaml");
assert(isfile(pathValue),"stageA4:a43:ConfigMissing", ...
    "The A4-3 execution configuration is missing: %s",pathValue);
document = string(fileread(pathValue));

a43 = struct();
for key = ["stage_id","status","milestone","run_purpose", ...
        "convergence_coordinate","objective_scale_mode", ...
        "objective_scale_source","recursive_route","step_strategy", ...
        "full_kkt_role","parallel_mode","formal_soc_boundary", ...
        "thermal_pass","thermal_lower_bound_mode"]
    a43.(key) = read_text(document,key);
end
a43.days = read_number_array(document,"days");
a43.hours = read_number_array(document,"hours");
for key = ["recursive_refinement_max_passes","centering_sigma", ...
        "fraction_to_boundary","max_iterations", ...
        "primal_equality_inf_tolerance", ...
        "primal_inequality_inf_tolerance", ...
        "dual_scaled_inf_tolerance","mean_lz_scaled_tolerance", ...
        "physical_violation_tolerance","direction_relative_tolerance", ...
        "recursive_full_kkt_residual_tolerance", ...
        "full_kkt_residual_tolerance","symmetry_relative_tolerance"]
    a43.(key) = read_number(document,key);
end
for key = ["checkpoint_after_each_accepted_update", ...
        "common_step_enabled","dynamic_sigma_enabled", ...
        "predictor_corrector_enabled","line_search_enabled", ...
        "regularization_enabled","automatic_symmetrization_enabled", ...
        "full_kkt_direction_fallback_enabled", ...
        "water_constraints_enabled","thermal_second_pass_enabled", ...
        "annual_scope_enabled"]
    a43.(key) = read_boolean(document,key);
end

validate_a4_3(config,a43);
freezePath = fullfile(projectRoot,"stages","stage_A4", ...
    "A4_数值稳定性修复冻结基线.json");
assert(isfile(freezePath),"stageA4:a43:FreezeMissing", ...
    "The A4 numerical-repair freeze manifest is missing: %s",freezePath);
freeze = jsondecode(fileread(freezePath));
validate_numerical_repair_freeze(config,a43,freeze,projectRoot);
config.a4_3 = a43;
config.numerical_repair_freeze = freeze;
config.source_paths.a4_3 = pathValue;
config.source_paths.numerical_repair_freeze = freezePath;
end

function validate_a4_3(base,a43)
assert(a43.stage_id=="stage_A4" && a43.status=="READY" && ...
    a43.milestone=="A4-3" && base.stage_id=="stage_A4" && ...
    base.status=="READY","stageA4:a43:StageGate", ...
    "A4-3 requires stage_A4 / READY.");
assert(isequal(a43.days,14:20) && isequal(a43.hours,1:24) && ...
    a43.run_purpose== ...
        "seven_day_full_primal_dual_ipm_convergence_candidate" && ...
    a43.convergence_coordinate=="positive_scalar_unitized_kkt", ...
    "stageA4:a43:Scope","A4-3 must use the formal seven-day scope.");
assert(a43.objective_scale_mode=="positive_scalar_unitization" && ...
    a43.objective_scale_source=="max_abs_global_capacity_gradient" && ...
    a43.recursive_route== ...
        "retained_factor_bounded_residual_refinement_stable_v2" && ...
    a43.recursive_refinement_max_passes==3 && ...
    a43.step_strategy=="independent" && ...
    a43.centering_sigma==base.initialization.centering_sigma && ...
    a43.fraction_to_boundary==base.fraction_to_boundary, ...
    "stageA4:a43:FrozenAlgorithm", ...
    "The A4-3 stable-v2, scaling, sigma, tau, or step contract changed.");
assert(a43.max_iterations==base.convergence.max_iterations && ...
    a43.primal_equality_inf_tolerance== ...
        base.convergence.primal_equality_inf && ...
    a43.primal_inequality_inf_tolerance== ...
        base.convergence.primal_inequality_inf && ...
    a43.dual_scaled_inf_tolerance==base.convergence.dual_inf && ...
    a43.mean_lz_scaled_tolerance== ...
        base.convergence.normalized_complementarity_gap && ...
    a43.physical_violation_tolerance==1e-8 && ...
    a43.direction_relative_tolerance== ...
        base.tolerances.direction_relative_2norm && ...
    a43.recursive_full_kkt_residual_tolerance== ...
        base.tolerances.recursive_full_kkt_relative_residual && ...
    a43.full_kkt_residual_tolerance==base.tolerances.direct_maximum && ...
    a43.symmetry_relative_tolerance== ...
        base.tolerances.symmetry_relative, ...
    "stageA4:a43:Thresholds", ...
    "The A4-3 convergence or audit thresholds changed.");
assert(a43.checkpoint_after_each_accepted_update && ...
    a43.full_kkt_role=="audit_only" && ...
    a43.parallel_mode=="off" && ~a43.common_step_enabled && ...
    ~a43.dynamic_sigma_enabled && ...
    ~a43.predictor_corrector_enabled && ...
    ~a43.line_search_enabled && ~a43.regularization_enabled && ...
    ~a43.automatic_symmetrization_enabled && ...
    ~a43.full_kkt_direction_fallback_enabled, ...
    "stageA4:a43:ForbiddenFactors", ...
    "A forbidden A4-3 algorithm factor is enabled.");
assert(a43.formal_soc_boundary== ...
        "daily_fixed_half_energy_no_interday_link" && ...
    a43.thermal_pass=="first" && ...
    a43.thermal_lower_bound_mode=="zero" && ...
    ~a43.water_constraints_enabled && ...
    ~a43.thermal_second_pass_enabled && ~a43.annual_scope_enabled, ...
    "stageA4:a43:FrozenModel", ...
    "The formal Stage-A model scope changed in A4-3.");
end

function validate_numerical_repair_freeze(base,a43,freeze,root)
assert(string(freeze.freeze_id)== ...
        "A4-NUMERICAL-STABILITY-REPAIR-FREEZE-20260728" && ...
    string(freeze.stage_id)=="stage_A4" && ...
    string(freeze.stage_status)=="READY" && ...
    string(freeze.stage_boundary.current_stage_must_remain)== ...
        "stage_A4 / READY" && ...
    ~logical(freeze.stage_boundary.formal_a4_run_executed_by_this_freeze) && ...
    ~logical(freeze.stage_boundary.stage_b_authorized), ...
    "stageA4:a43:FreezeIdentity", ...
    "The numerical-repair freeze identity or stage boundary changed.");

algorithm = freeze.frozen_algorithm;
assert(a43.centering_sigma==algorithm.centering_sigma && ...
    a43.fraction_to_boundary==algorithm.fraction_to_boundary && ...
    a43.step_strategy==string(algorithm.step_strategy) && ...
    ~logical(algorithm.common_step_enabled) && ...
    ~logical(algorithm.dynamic_sigma_enabled) && ...
    ~logical(algorithm.predictor_corrector_enabled) && ...
    ~logical(algorithm.line_search_enabled) && ...
    ~logical(algorithm.regularization_enabled) && ...
    ~logical(algorithm.automatic_symmetrization_enabled) && ...
    ~logical(algorithm.full_kkt_direction_fallback_enabled), ...
    "stageA4:a43:FreezeAlgorithm", ...
    "The frozen sigma, tau, or independent step strategy changed.");

initial = freeze.frozen_initialization;
assert(base.initialization.global_capacity== ...
        string(initial.global_capacity) && ...
    base.initialization.daily_capacity_copy_equals_global== ...
        logical(initial.daily_capacity_copy_equals_global) && ...
    base.initialization.active_wind_solar_fraction_of_upper== ...
        initial.active_wind_solar_fraction_of_upper && ...
    base.initialization.hydro_thermal_fraction_of_upper== ...
        initial.hydro_thermal_fraction_of_upper && ...
    base.initialization.charge_discharge_fraction_of_power_capacity== ...
        initial.charge_discharge_fraction_of_power_capacity && ...
    base.initialization.soc_fraction_of_energy_capacity== ...
        initial.soc_fraction_of_energy_capacity && ...
    base.initialization.equality_multipliers== ...
        initial.equality_multipliers && ...
    base.initialization.inequality_multiplier== ...
        initial.inequality_multiplier, ...
    "stageA4:a43:FreezeInitialization", ...
    "The deterministic A4 initialization changed.");

model = freeze.frozen_model;
assert(isequal(base.days,reshape(model.days,1,[])) && ...
    numel(base.hours)==model.hours_per_day && ...
    base.objective_mode==string(model.objective_mode) && ...
    a43.objective_scale_mode==string(model.objective_scale_mode) && ...
    a43.objective_scale_source==string(model.objective_scale_source) && ...
    base.thermal_pass==string(model.thermal_pass) && ...
    base.thermal_lower_bound_mode== ...
        string(model.thermal_lower_bound_mode) && ...
    a43.formal_soc_boundary==string(model.formal_soc_boundary) && ...
    a43.water_constraints_enabled== ...
        logical(model.water_constraints_enabled) && ...
    a43.thermal_second_pass_enabled== ...
        logical(model.thermal_second_pass_enabled) && ...
    a43.annual_scope_enabled==logical(model.annual_scope_enabled) && ...
    a43.parallel_mode==string(model.parallel_mode) && ...
    base.expected_full_kkt_dimension==model.full_kkt_dimension && ...
    base.expected_fixed_zero_count==model.fixed_zero_count, ...
    "stageA4:a43:FreezeModel", ...
    "The frozen Stage-A model scope or controlled dimensions changed.");

protected = freeze.protected_files;
assert(~isempty(protected),"stageA4:a43:FreezeFiles", ...
    "The numerical-repair freeze has no protected files.");
for k = 1:numel(protected)
    relative = string(protected(k).relative_path);
    pathValue = fullfile(root,replace(relative,"/",filesep));
    assert(isfile(pathValue) && ...
        compute_sha256_file(pathValue)== ...
            lower(string(protected(k).sha256)), ...
        "stageA4:a43:FreezeFileDrift", ...
        "Frozen model, input, initialization, or step file changed: %s", ...
        relative);
end
end

function value = read_text(document,key)
raw = read_raw(document,key);
if (startsWith(raw,'"') && endsWith(raw,'"')) || ...
        (startsWith(raw,"'") && endsWith(raw,"'"))
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value)>0,"stageA4:a43:EmptyText", ...
    "A4-3 configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
value = str2double(read_raw(document,key));
assert(isscalar(value)&&isfinite(value),"stageA4:a43:Number", ...
    "A4-3 configuration key %s must be numeric.",key);
end

function values = read_number_array(document,key)
raw = read_raw(document,key);
assert(startsWith(raw,"[")&&endsWith(raw,"]"), ...
    "stageA4:a43:NumberArray", ...
    "A4-3 configuration key %s must be an explicit sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
values = str2double(strip(split(body,","))).';
assert(all(isfinite(values)),"stageA4:a43:NumberArray", ...
    "A4-3 configuration key %s contains a nonnumeric item.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw(document,key));
assert(ismember(raw,["true","false"]),"stageA4:a43:Boolean", ...
    "A4-3 configuration key %s must be boolean.",key);
value = raw=="true";
end

function raw = read_raw(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens),"stageA4:a43:ConfigurationKey", ...
    "A4-3 configuration key %s must occur exactly once.",key);
raw = strip(string(tokens{1}{1}));
end

function projectRoot = default_project_root()
modelDirectory = fileparts(mfilename("fullpath"));
sourceDirectory = fileparts(modelDirectory);
projectRoot = string(fileparts(sourceDirectory));
end
