function exported = export_stage_a3_artifacts(runContext,data,index,config, ...
        linearization,fullResult,recursiveResult,audit,options)
%EXPORT_STAGE_A3_ARTIFACTS Persist the seven-day Stage A3 direction audit.
% The complete 18836 KKT and all day chains remain sparse MAT data.

arguments
    runContext (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    linearization (1,1) struct
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    audit (1,1) struct
    options.Environment = struct()
    options.Tests = struct()
    options.A2Regression = struct()
    options.A1Regression = struct()
    options.CodeScan table = table()
    options.Physical = struct()
end
exported=export_impl(runContext,data,index,config,linearization, ...
    fullResult,recursiveResult,audit,options);
end

function paths=artifact_paths(context,days)
paths=struct();
paths.diagnostics_dir=fullfile(context.root,"diagnostics");
paths.linearization_mat=fullfile(context.matrices_dir,"linearization.mat");
paths.full_kkt_mat=fullfile(context.matrices_dir,"full_kkt.mat");
paths.reduced_system_mat=fullfile(context.matrices_dir,"reduced_system.mat");
paths.daily_recursive_mat=fullfile(context.matrices_dir,"daily_recursive.mat");
paths.daily_responses_mat=fullfile(context.matrices_dir,"daily_responses.mat");
paths.daily_aggregation_mat=fullfile(context.matrices_dir,"daily_aggregation.mat");
paths.directions_mat=fullfile(context.matrices_dir,"directions.mat");
paths.physical_recovery_mat=fullfile(context.matrices_dir,"physical_recovery.mat");
paths.residuals_mat=fullfile(context.matrices_dir,"residuals.mat");
paths.index_mapping_mat=fullfile(context.matrices_dir,"index_mapping.mat");
paths.configuration_mat=fullfile(context.matrices_dir,"configuration.mat");
paths.matrix_manifest=fullfile(context.matrices_dir,"matrix_manifest.csv");
paths.block_dimensions=fullfile(context.matrices_dir,"block_dimensions.csv");
paths.daily_chain_dimensions=fullfile(context.matrices_dir, ...
    "daily_chain_dimensions.csv");
paths.block_diagnostics=fullfile(context.matrices_dir, ...
    "hourly_block_diagnostics.csv");
paths.daily_response_summary=fullfile(context.matrices_dir, ...
    "daily_response_summary.csv");
paths.daily_aggregation_audit=fullfile(context.matrices_dir, ...
    "daily_aggregation_audit.csv");
paths.variable_index=fullfile(context.indices_dir,"variable_index.csv");
paths.constraint_index=fullfile(context.indices_dir,"constraint_index.csv");
paths.block_index=fullfile(context.indices_dir,"block_index.csv");
paths.fixed_zero_map=fullfile(context.indices_dir,"fixed_zero_map.csv");
paths.permutation_map=fullfile(context.indices_dir,"permutation_map.csv");
paths.soc_link_map=fullfile(context.indices_dir,"soc_link_map.csv");
paths.index_audit=fullfile(context.indices_dir,"index_audit.csv");
paths.soc_boundary_audit=fullfile(context.indices_dir,"soc_boundary_audit.csv");
paths.fixed_zero_recovery_audit=fullfile(context.indices_dir, ...
    "fixed_zero_recovery_audit.csv");
paths.renewable_activity=fullfile(context.indices_dir, ...
    "hourly_renewable_activity.csv");
paths.direction_comparison=fullfile(context.iterations_dir, ...
    "direction_comparison.csv");
paths.residual_summary=fullfile(context.iterations_dir,"residual_summary.csv");
paths.code_scan=fullfile(paths.diagnostics_dir,"code_scan.csv");
paths.linearization_identity=fullfile(paths.diagnostics_dir, ...
    "linearization_identity.json");
paths.core_triplets=fullfile(context.matrices_dir,"global_core_triplets.csv");
paths.aggregated_response_triplets=fullfile(context.matrices_dir, ...
    "aggregated_response_S_sum_triplets.csv");
paths.day_response_triplets=strings(numel(days),1);
for k=1:numel(days)
    paths.day_response_triplets(k)=fullfile(context.matrices_dir, ...
        sprintf("day_%02d_response_S_triplets.csv",days(k)));
end
paths.artifact_hashes=fullfile(context.matrices_dir, ...
    "numerical_artifact_hashes.csv");
end

function targets=output_targets(paths)
names=fieldnames(paths); targets=strings(0,1);
for k=1:numel(names)
    if names{k}=="diagnostics_dir", continue; end
    targets=[targets;reshape(string(paths.(names{k})),[],1)]; %#ok<AGROW>
end
assert(numel(unique(lower(targets)))==numel(targets), ...
    "stageA3:artifacts:DuplicateTarget","A3 artifact targets are not unique.");
end
function assert_targets_absent(targets)
for target=targets.'
    if isfile(target)||isfolder(target)
        error("stageA3:artifacts:TargetExists", ...
            "A3 artifact target exists and will not be overwritten: %s",target);
    end
end
end
function ensure_directory(pathValue)
if isfolder(pathValue), return; end
if exist(pathValue,'file')
    error("stageA3:artifacts:PathConflict", ...
        "A file exists where a directory is required: %s",pathValue);
end
[created,message]=mkdir(pathValue);
assert(created,"stageA3:artifacts:CreateDirectory","%s",message);
end

function output=make_block_dimensions(recursive)
day=zeros(0,1); hour=zeros(0,1); n_primal=zeros(0,1);
n_equalities=zeros(0,1); kkt_dimension=zeros(0,1);
day_chain_offset_start=zeros(0,1); day_chain_offset_end=zeros(0,1);
status=strings(0,1);
for d=1:numel(recursive.daily_partitions)
    partition=recursive.daily_partitions(d); offset=0;
    for h=1:numel(partition.hour)
        block=partition.hour(h); dimension=double(block.dimension);
        day(end+1,1)=double(partition.day_id); %#ok<AGROW>
        hour(end+1,1)=double(block.hour); %#ok<AGROW>
        n_primal(end+1,1)=double(block.n_primal); %#ok<AGROW>
        n_equalities(end+1,1)=double(block.n_equalities); %#ok<AGROW>
        kkt_dimension(end+1,1)=dimension; %#ok<AGROW>
        day_chain_offset_start(end+1,1)=offset+1; %#ok<AGROW>
        day_chain_offset_end(end+1,1)=offset+dimension; %#ok<AGROW>
        passed=dimension==double(block.n_primal)+double(block.n_equalities)&& ...
            dimension>0;
        status(end+1,1)=pass_text(passed); %#ok<AGROW>
        offset=offset+dimension;
    end
end
output=table(day,hour,n_primal,n_equalities,kkt_dimension, ...
    day_chain_offset_start,day_chain_offset_end,status);
end

function output=make_daily_chain_dimensions(recursive)
n=numel(recursive.daily_partitions); day=zeros(n,1); block_count=zeros(n,1);
sum_block_dimensions=zeros(n,1); chain_rows=zeros(n,1); chain_columns=zeros(n,1);
chain_nnz=zeros(n,1); rhs_count=zeros(n,1); status=strings(n,1);
for k=1:n
    partition=recursive.daily_partitions(k);
    day(k)=double(partition.day_id); block_count(k)=numel(partition.hour);
    sum_block_dimensions(k)=sum([partition.hour.dimension]);
    [chain_rows(k),chain_columns(k)]=size(partition.M);
    chain_nnz(k)=nnz(partition.M); rhs_count(k)=size(partition.B,2)+1;
    status(k)=pass_text(block_count(k)==24&& ...
        sum_block_dimensions(k)==chain_rows(k)&& ...
        chain_rows(k)==chain_columns(k)&&issparse(partition.M)&&rhs_count(k)==15);
end
output=table(day,block_count,sum_block_dimensions,chain_rows,chain_columns, ...
    chain_nnz,rhs_count,status);
end

function output=make_block_diagnostics(recursive,config)
rows=table();
for k=1:numel(recursive.daily_thomas)
    value=recursive.daily_thomas(k).diagnostics.hour_block;
    assert(isstruct(value)&&numel(value)==24, ...
        "stageA3:artifacts:HourDiagnosticsCount", ...
        "Each day requires exactly 24 hourly block diagnostics.");
    current=struct2table(value(:));
    current=addvars(current,repmat(double(recursive.daily_partitions(k).day_id), ...
        height(current),1),'Before',1,'NewVariableNames','day');
    if isempty(rows), rows=current; else, rows=[rows;current]; end %#ok<AGROW>
end
required=["day","hour","dimension","D_numeric_rank", ...
    "D_condition_2","D_symmetry_relative","schur_numeric_rank", ...
    "schur_condition_2","schur_inertia_positive", ...
    "schur_inertia_negative","schur_inertia_zero", ...
    "schur_factor_relative_residual","rhs_count"];
assert(all(ismember(required,string(rows.Properties.VariableNames))), ...
    "stageA3:artifacts:HourDiagnosticsSchema", ...
    "Hourly diagnostic schema is incomplete.");
passed=rows.D_numeric_rank==rows.dimension&isfinite(rows.D_condition_2)& ...
    rows.D_symmetry_relative<=config.tolerances.symmetry_relative& ...
    rows.schur_numeric_rank==rows.dimension& ...
    isfinite(rows.schur_condition_2)&rows.schur_inertia_zero==0& ...
    rows.schur_factor_relative_residual<= ...
        config.tolerances.recursive_full_kkt_relative_residual& ...
    rows.rhs_count==15;
rows.status=repmat("PASS",height(rows),1); rows.status(~passed)="FAIL";
output=rows;
end

function exported=export_impl(runContext,data,index,config,linearization, ...
        fullResult,recursiveResult,audit,options)
validate_inputs(runContext,index,config,linearization,fullResult, ...
    recursiveResult,audit);
paths=artifact_paths(runContext,config.days);
targets=output_targets(paths); assert_targets_absent(targets);
ensure_directory(paths.diagnostics_dir);

save_mat_artifact(paths.linearization_mat,"linearization",linearization);
save_mat_artifact(paths.full_kkt_mat,"kkt",fullResult.kkt, ...
    "diagnostics",fullResult.diagnostics, ...
    "linearization_identity",fullResult.linearization_identity);
save_mat_artifact(paths.reduced_system_mat, ...
    "W",recursiveResult.reduced.W,"A",recursiveResult.reduced.A, ...
    "saddle",recursiveResult.reduced.saddle, ...
    "rhs",recursiveResult.reduced.rhs, ...
    "theta",recursiveResult.reduced.theta, ...
    "phi",recursiveResult.reduced.phi, ...
    "linearization_identity",recursiveResult.reduced.linearization_identity);
save_mat_artifact(paths.daily_recursive_mat, ...
    "daily_partitions",recursiveResult.daily_partitions, ...
    "daily_thomas",recursiveResult.daily_thomas, ...
    "recovery",recursiveResult.recovery, ...
    "linearization_identity",recursiveResult.linearization_identity);
save_mat_artifact(paths.daily_responses_mat, ...
    "daily_responses",recursiveResult.daily_responses);
save_mat_artifact(paths.daily_aggregation_mat, ...
    "aggregation",recursiveResult.aggregation,"core",recursiveResult.core);
save_mat_artifact(paths.directions_mat, ...
    "full_direction",fullResult.direction, ...
    "recursive_direction",recursiveResult.direction, ...
    "full_components",fullResult.components, ...
    "recursive_components",recursiveResult.components, ...
    "fixed_zero",recursiveResult.fixed_zero);
assert(isstruct(options.Physical)&&isscalar(options.Physical)&& ...
    isfield(options.Physical,"fixed_zero_audit"), ...
    "stageA3:artifacts:PhysicalRecoveryMissing", ...
    "A3 export requires actual compact-to-physical recovery evidence.");
save_mat_artifact(paths.physical_recovery_mat,"physical",options.Physical);
fullResidual=fullResult.kkt.matrix*fullResult.direction-fullResult.kkt.rhs;
recursiveResidual=fullResult.kkt.matrix*recursiveResult.direction- ...
    fullResult.kkt.rhs;
save_mat_artifact(paths.residuals_mat,"audit",audit, ...
    "full_kkt_residual",fullResidual, ...
    "recursive_full_kkt_residual",recursiveResidual, ...
    "recursive_reinsertion",recursiveResult.full_kkt_reinsertion, ...
    "daily_thomas_diagnostics",{recursiveResult.daily_thomas.diagnostics}, ...
    "core_diagnostics",recursiveResult.core.diagnostics);
save_mat_artifact(paths.index_mapping_mat,"index",index);
save_mat_artifact(paths.configuration_mat,"config",config, ...
    "data_metadata",data.meta,"input_hashes",data.hashes, ...
    "environment",options.Environment,"tests",options.Tests, ...
    "a2_regression",options.A2Regression, ...
    "a1_regression",options.A1Regression);

write_table_csv_17g(paths.variable_index,index.variable_index);
write_table_csv_17g(paths.constraint_index,index.constraint_index);
write_table_csv_17g(paths.block_index,index.block_index);
write_table_csv_17g(paths.fixed_zero_map,index.fixed_zero_map);
write_table_csv_17g(paths.permutation_map,index.permutation_map);
write_table_csv_17g(paths.soc_link_map,index.soc_link_map);
indexAudit=validate_canonical_index_framework(index);
write_table_csv_17g(paths.index_audit,indexAudit);

blockDimensions=make_block_dimensions(recursiveResult);
chainDimensions=make_daily_chain_dimensions(recursiveResult);
blockDiagnostics=make_block_diagnostics(recursiveResult,config);
responseSummary=make_daily_response_summary(recursiveResult,config);
aggregationAudit=make_aggregation_audit(recursiveResult,config);
comparison=make_direction_comparison(audit,recursiveResult,config, ...
    linearization,fullResult);
residualSummary=make_residual_summary(fullResult,recursiveResult,config);
socAudit=make_soc_boundary_audit(index,linearization,config);
fixedAudit=make_fixed_zero_recovery_audit(index,recursiveResult,options.Physical);
activity=make_renewable_activity(data,index,config);
write_table_csv_17g(paths.block_dimensions,blockDimensions);
write_table_csv_17g(paths.daily_chain_dimensions,chainDimensions);
write_table_csv_17g(paths.block_diagnostics,blockDiagnostics);
write_table_csv_17g(paths.daily_response_summary,responseSummary);
write_table_csv_17g(paths.daily_aggregation_audit,aggregationAudit);
write_table_csv_17g(paths.direction_comparison,comparison);
write_table_csv_17g(paths.residual_summary,residualSummary);
write_table_csv_17g(paths.soc_boundary_audit,socAudit);
write_table_csv_17g(paths.fixed_zero_recovery_audit,fixedAudit);
write_table_csv_17g(paths.renewable_activity,activity);

if isempty(options.CodeScan)
    codeScan=scan_stage_a3_forbidden_code(string(runContext.project_root),config);
else
    codeScan=options.CodeScan;
end
write_table_csv_17g(paths.code_scan,codeScan);
identityEvidence=make_identity_evidence(linearization,fullResult, ...
    recursiveResult,index,config);
write_json_file(paths.linearization_identity,identityEvidence);

write_sparse_triplets(paths.core_triplets,recursiveResult.core.matrix);
write_sparse_triplets(paths.aggregated_response_triplets, ...
    recursiveResult.aggregation.S_sum);
for k=1:numel(recursiveResult.daily_responses)
    write_sparse_triplets(paths.day_response_triplets(k), ...
        recursiveResult.daily_responses(k).S);
end
matrixManifest=make_matrix_manifest(paths,linearization,fullResult, ...
    recursiveResult);
write_table_csv_17g(paths.matrix_manifest,matrixManifest);

hashTargets=targets(targets~=string(paths.artifact_hashes));
artifactHashes=make_artifact_hashes(runContext.root,hashTargets);
write_table_csv_17g(paths.artifact_hashes,artifactHashes);
exported=struct("paths",paths,"matrix_manifest",matrixManifest, ...
    "block_dimensions",blockDimensions, ...
    "daily_chain_dimensions",chainDimensions, ...
    "block_diagnostics",blockDiagnostics, ...
    "daily_response_summary",responseSummary, ...
    "daily_aggregation_audit",aggregationAudit, ...
    "direction_comparison",comparison,"residual_summary",residualSummary, ...
    "soc_boundary_audit",socAudit, ...
    "fixed_zero_recovery_audit",fixedAudit, ...
    "renewable_activity",activity,"code_scan",codeScan, ...
    "artifact_hashes",artifactHashes, ...
    "linearization_identity",identityEvidence);
end

function validate_inputs(context,index,config,lin,fullResult,recursive,audit)
requiredContext=["root","run_id","stage_id","matrices_dir", ...
    "indices_dir","iterations_dir","project_root"];
assert(all(isfield(context,cellstr(requiredContext)))&&isfolder(context.root), ...
    "stageA3:artifacts:InvalidRunContext","Invalid A3 run context.");
assert(string(context.stage_id)=="stage_A3", ...
    "stageA3:artifacts:StageMismatch","A3 exporter requires stage_A3.");
manifest=jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.run_id)==string(context.run_id)&& ...
    string(manifest.stage_id)=="stage_A3"&&string(manifest.status)=="RUNNING", ...
    "stageA3:artifacts:ManifestIdentity", ...
    "A3 export requires the matching RUNNING manifest.");
requiredIndex=["variable_index","constraint_index","block_index", ...
    "fixed_zero_map","permutation_map","soc_link_map"];
assert(all(isfield(index,cellstr(requiredIndex))), ...
    "stageA3:artifacts:IndexContract", ...
    "Six canonical index tables are required.");
for name=requiredIndex
    assert(istable(index.(name)),"stageA3:artifacts:IndexContract", ...
        "Canonical index field %s must be a table.",name);
end
assert(lin.counts.full_kkt==18836&&fullResult.kkt.dimension==18836&& ...
    isequal(size(fullResult.kkt.matrix),[18836 18836])&& ...
    issparse(fullResult.kkt.matrix), ...
    "stageA3:artifacts:FullKktDimension", ...
    "The complete A3 KKT must be sparse and 18836-by-18836.");
assert(isequal(size(recursive.reduced.W),[3722 3722])&& ...
    isequal(size(recursive.reduced.saddle),[4340 4340])&& ...
    issparse(recursive.reduced.W)&&issparse(recursive.reduced.saddle), ...
    "stageA3:artifacts:ReducedSystemDimension", ...
    "A3 reduced W/saddle must be sparse 3722 and 4340 systems.");
assert(numel(recursive.daily_partitions)==7&& ...
    numel(recursive.daily_thomas)==7&&numel(recursive.daily_responses)==7, ...
    "stageA3:artifacts:DailyCount", ...
    "A3 requires seven partitions, Thomas solves, and day responses.");
for k=1:7
    partition=recursive.daily_partitions(k);
    response=recursive.daily_responses(k);
    assert(double(partition.day_id)==config.days(k)&& ...
        double(response.day_id)==config.days(k)&&numel(partition.hour)==24&& ...
        issparse(partition.M)&&isequal(size(response.S),[14 14])&& ...
        isequal(size(response.c),[14 1])&& ...
        isequal(size(response.beta),[14 1])&& ...
        isequal(size(response.gamma),[14 1]), ...
        "stageA3:artifacts:DailyContract", ...
        "Day %d partition/response contract is invalid.",config.days(k));
end
assert(isequal(double(recursive.aggregation.day_ids_sorted(:).'),config.days)&& ...
    isequal(size(recursive.aggregation.S_sum),[14 14])&& ...
    isequal(size(recursive.aggregation.gamma_sum),[14 1])&& ...
    isequal(size(recursive.core.matrix),[16 16]), ...
    "stageA3:artifacts:CoreDimension", ...
    "A3 aggregation/core dimensions are invalid.");
assert(height(index.fixed_zero_map)==recursive.fixed_zero.count, ...
    "stageA3:artifacts:FixedZeroCount", ...
    "Canonical and recovered fixed-zero counts differ.");
identities=string([lin.identity,fullResult.linearization_identity, ...
    recursive.linearization_identity,audit.linearization_identity]);
assert(isscalar(unique(identities)), ...
    "stageA3:artifacts:LinearizationIdentity", ...
    "Full, recursive, and audit routes must share one identity.");
assert(recursive.no_full_direction_fallback, ...
    "stageA3:artifacts:RecursiveFallback", ...
    "Recursive evidence permits a full-KKT direction fallback.");
assemblyAudit=recursive.partition.assembly_audit;
assert(logical(assemblyAudit.no_cross_day_soc_coupling)&& ...
    double(assemblyAudit.cross_day_hourly_equality_nnz)==0, ...
    "stageA3:artifacts:CrossDaySocCoupling", ...
    "A3 recursive partition contains cross-day hourly/SOC coupling.");
end

function output=make_daily_response_summary(recursive,config)
n=numel(recursive.daily_responses); day=zeros(n,1);
S_rows=zeros(n,1); S_columns=zeros(n,1); c_length=zeros(n,1);
beta_length=zeros(n,1); gamma_length=zeros(n,1); S_nnz=zeros(n,1);
S_norm_fro=zeros(n,1); c_norm_2=zeros(n,1); beta_norm_2=zeros(n,1);
gamma_norm_2=zeros(n,1); gamma_identity_relative_residual=zeros(n,1);
status=strings(n,1);
for k=1:n
    response=recursive.daily_responses(k); day(k)=double(response.day_id);
    [S_rows(k),S_columns(k)]=size(response.S); S_nnz(k)=nnz(response.S);
    c_length(k)=numel(response.c); beta_length(k)=numel(response.beta);
    gamma_length(k)=numel(response.gamma); S_norm_fro(k)=norm(response.S,'fro');
    c_norm_2(k)=norm(response.c,2); beta_norm_2(k)=norm(response.beta,2);
    gamma_norm_2(k)=norm(response.gamma,2);
    identityResidual=response.gamma-(response.c-response.S*response.beta);
    gamma_identity_relative_residual(k)=norm(identityResidual,2)/ ...
        max(1,norm(response.gamma,2));
    passed=day(k)==config.days(k)&&S_rows(k)==14&&S_columns(k)==14&& ...
        c_length(k)==14&&beta_length(k)==14&&gamma_length(k)==14&& ...
        gamma_identity_relative_residual(k)<=config.tolerances.symmetry_relative;
    status(k)=pass_text(passed);
end
output=table(day,S_rows,S_columns,c_length,beta_length,gamma_length, ...
    S_nnz,S_norm_fro,c_norm_2,beta_norm_2,gamma_norm_2, ...
    gamma_identity_relative_residual,status);
end

function output=make_aggregation_audit(recursive,config)
aggregation=recursive.aggregation;
input_order=string(mat2str(double(aggregation.input_order(:).')));
sort_order=string(mat2str(double(aggregation.sort_order(:).')));
day_ids_sorted=string(mat2str(double(aggregation.day_ids_sorted(:).')));
S_rows=size(aggregation.S_sum,1); S_columns=size(aggregation.S_sum,2);
gamma_length=numel(aggregation.gamma_sum);
S_sum_norm_fro=norm(aggregation.S_sum,'fro');
gamma_sum_norm_2=norm(aggregation.gamma_sum,2);
S_order_invariance_relative_error= ...
    double(aggregation.order_invariant_S_relative_error);
gamma_order_invariance_relative_error= ...
    double(aggregation.order_invariant_gamma_relative_error);
sorted_contract=isequal(double(aggregation.day_ids_sorted(:).'),config.days);
status=pass_text(sorted_contract&&logical(aggregation.order_invariant_passed)&& ...
    S_order_invariance_relative_error<=config.tolerances.symmetry_relative&& ...
    gamma_order_invariance_relative_error<=config.tolerances.symmetry_relative);
output=table(input_order,sort_order,day_ids_sorted,S_rows,S_columns, ...
    gamma_length,S_sum_norm_fro,gamma_sum_norm_2, ...
    S_order_invariance_relative_error, ...
    gamma_order_invariance_relative_error,sorted_contract,status);
end

function output=make_direction_comparison(audit,recursive,config,lin,fullResult)
identityMismatch=double(~(string(lin.identity)== ...
    string(fullResult.linearization_identity)&&string(lin.identity)== ...
    string(recursive.linearization_identity)));
fixedValue=max([0;abs(recursive.fixed_zero.value(:))]);
fixedDirection=max([0;abs(recursive.fixed_zero.direction(:))]);
dayChainResiduals=zeros(numel(recursive.daily_thomas),1);
for k=1:numel(recursive.daily_thomas)
    dayChainResiduals(k)=recursive.daily_thomas(k).diagnostics.chain_relative_residual;
end
metric_id=["overall_direction_relative_2norm"; ...
    "xi_direction_relative_2norm";"y_direction_relative_2norm"; ...
    "l_direction_relative_2norm";"z_direction_relative_2norm"; ...
    "fixed_zero_maximum_absolute_value"; ...
    "fixed_zero_maximum_absolute_direction"; ...
    "linearization_identity_mismatch"; ...
    "recursive_full_direction_fallback_used"; ...
    "daily_aggregation_S_order_relative_error"; ...
    "daily_aggregation_gamma_order_relative_error"; ...
    "maximum_daily_chain_relative_residual"; ...
    "global_core_relative_residual"];
actual_value=[audit.direction_relative_error; ...
    audit.component_relative_errors.xi;audit.component_relative_errors.y; ...
    audit.component_relative_errors.l;audit.component_relative_errors.z; ...
    fixedValue;fixedDirection;identityMismatch; ...
    double(~recursive.no_full_direction_fallback); ...
    recursive.aggregation.order_invariant_S_relative_error; ...
    recursive.aggregation.order_invariant_gamma_relative_error; ...
    max(dayChainResiduals);recursive.core.diagnostics.relative_residual];
threshold=[repmat(config.tolerances.direction_relative_2norm,5,1); ...
    0;0;0;0;repmat(config.tolerances.symmetry_relative,2,1); ...
    repmat(config.tolerances.recursive_full_kkt_relative_residual,2,1)];
status=repmat("PASS",numel(actual_value),1);
status(~isfinite(actual_value)|actual_value>threshold)="FAIL";
output=table(metric_id,actual_value,threshold,status);
end

function output=make_residual_summary(fullResult,recursive,config)
K=fullResult.kkt.matrix; b=fullResult.kkt.rhs;
fullResidual=K*fullResult.direction-b;
recursiveResidual=K*recursive.direction-b;
route=["full_kkt_direct_preferred";"full_kkt_direct_hard_limit"; ...
    "recursive_direction_reinserted_in_full_kkt"];
day_id=[NaN;NaN;NaN];
absolute_residual_2norm=[norm(fullResidual,2);norm(fullResidual,2); ...
    norm(recursiveResidual,2)];
rhs_2norm=[norm(b,2);norm(b,2);norm(b,2)];
threshold=[config.tolerances.direct_preferred;config.tolerances.direct_maximum; ...
    config.tolerances.recursive_full_kkt_relative_residual];
for k=1:numel(recursive.daily_partitions)
    partition=recursive.daily_partitions(k); thomas=recursive.daily_thomas(k);
    chainRhs=[partition.r_v,partition.B];
    chainResidual=partition.M*thomas.stacked_solution-chainRhs;
    route(end+1,1)="recursive_day_chain_15_rhs"; %#ok<AGROW>
    day_id(end+1,1)=double(partition.day_id); %#ok<AGROW>
    absolute_residual_2norm(end+1,1)=norm(chainResidual,'fro'); %#ok<AGROW>
    rhs_2norm(end+1,1)=norm(chainRhs,'fro'); %#ok<AGROW>
    threshold(end+1,1)=config.tolerances.recursive_full_kkt_relative_residual; %#ok<AGROW>
end
coreResidual=recursive.core.matrix*recursive.core.solution-recursive.core.rhs;
route(end+1,1)="global_core_16"; day_id(end+1,1)=NaN;
absolute_residual_2norm(end+1,1)=norm(coreResidual,2);
rhs_2norm(end+1,1)=norm(recursive.core.rhs,2);
threshold(end+1,1)=config.tolerances.recursive_full_kkt_relative_residual;
relative_residual_2norm=absolute_residual_2norm./max(1,rhs_2norm);
status=repmat("PASS",numel(route),1);
status(~isfinite(relative_residual_2norm)|relative_residual_2norm>threshold)="FAIL";
output=table(route,day_id,absolute_residual_2norm,rhs_2norm, ...
    relative_residual_2norm,threshold,status);
end

function output=make_soc_boundary_audit(index,lin,config)
links=index.soc_link_map; constraints=index.constraint_index;
check_id=strings(0,1); day=zeros(0,1); hour=zeros(0,1); storage=zeros(0,1);
equation_id=strings(0,1); boundary_role=strings(0,1);
predecessor_day=zeros(0,1); predecessor_hour=zeros(0,1);
predecessor_soc_index=zeros(0,1); current_soc_index=zeros(0,1);
expected=strings(0,1); actual=strings(0,1); status=strings(0,1);
for d=1:numel(config.days)
    dayId=config.days(d);
    for h=config.hours
        for s=1:2
            link=links(links.day==dayId&links.hour==h&links.storage_id==s,:);
            equation=constraints(constraints.day==dayId&constraints.hour==h& ...
                string(constraints.constraint_type)=="equality"& ...
                string(constraints.constraint_name)=="soc_dynamics"& ...
                constraints.asset_id==s,:);
            passed=height(link)==1&&height(equation)==1;
            if passed
                passed=lin.A(equation.global_row, ...
                    link.current_soc_global_index)==1;
            end
            predDay=NaN;
            if ismember("predecessor_day",string(link.Properties.VariableNames))&& ...
                    height(link)==1
                predDay=link.predecessor_day;
            end
            if h==config.hours(1)
                role="initial_fixed_half_energy_no_interday_link";
                if height(link)==1&&height(equation)==1
                    passed=passed&&isnan(link.predecessor_hour)&& ...
                        link.predecessor_soc_global_index==0&& ...
                        link.initial_energy_fraction==0.5&& ...
                        (isnan(predDay)||predDay==0)&& ...
                        lin.A(equation.global_row, ...
                        q_day_index(lin,d,12+s))==-0.5;
                end
                expectedText="fixed 0.5E; no prior day/hour-0 SOC link";
            else
                role="same_day_predecessor";
                if height(link)==1&&height(equation)==1
                    passed=passed&&link.predecessor_hour==h-1&& ...
                        link.predecessor_soc_global_index>0&& ...
                        (isnan(predDay)||predDay==dayId)&& ...
                        predecessor_is_same_day(index.variable_index, ...
                        link.predecessor_soc_global_index,dayId,h-1,s)&& ...
                        lin.A(equation.global_row, ...
                        link.predecessor_soc_global_index)==-1&& ...
                        lin.A(equation.global_row,q_day_index(lin,d,12+s))==0;
                end
                expectedText=sprintf("same-day %d hour predecessor %d",dayId,h-1);
            end
            if height(link)==1
                pred=link.predecessor_hour;
                predIndex=link.predecessor_soc_global_index;
                current=link.current_soc_global_index;
                actualText=sprintf("source=%s; predecessor_hour=%s; predecessor_index=%d", ...
                    string(link.boundary_source),number_or_na(pred),predIndex);
            else
                pred=NaN; predIndex=0; current=0; actualText="MISSING_OR_DUPLICATE";
            end
            if height(equation)==1
                eqId=string(equation.constraint_id);
            else
                eqId="MISSING_OR_DUPLICATE";
            end
            check_id(end+1,1)=sprintf("SOC-D%02d-H%02d-S%02d",dayId,h,s); %#ok<AGROW>
            day(end+1,1)=dayId; hour(end+1,1)=h; storage(end+1,1)=s; %#ok<AGROW>
            equation_id(end+1,1)=eqId; boundary_role(end+1,1)=role; %#ok<AGROW>
            predecessor_day(end+1,1)=predDay; predecessor_hour(end+1,1)=pred; %#ok<AGROW>
            predecessor_soc_index(end+1,1)=predIndex; current_soc_index(end+1,1)=current; %#ok<AGROW>
            expected(end+1,1)=expectedText; actual(end+1,1)=actualText; %#ok<AGROW>
            status(end+1,1)=pass_text(passed); %#ok<AGROW>
        end
    end
    for s=1:2
        h=config.hours(end);
        link=links(links.day==dayId&links.hour==h&links.storage_id==s,:);
        equation=constraints(constraints.day==dayId&constraints.hour==h& ...
            string(constraints.constraint_type)=="equality"& ...
            string(constraints.constraint_name)=="terminal_soc"& ...
            constraints.asset_id==s,:);
        passed=height(link)==1&&height(equation)==1&& ...
            link.terminal_equality&&link.terminal_energy_fraction==0.5;
        if passed
            passed=lin.A(equation.global_row,link.current_soc_global_index)==1&& ...
                lin.A(equation.global_row,q_day_index(lin,d,12+s))==-0.5;
            eqId=string(equation.constraint_id); current=link.current_soc_global_index;
            actualText="hour=24; fraction="+compose("%.17g", ...
                link.terminal_energy_fraction);
        else
            eqId="MISSING_OR_DUPLICATE"; current=0; actualText="MISSING_OR_DUPLICATE";
        end
        check_id(end+1,1)=sprintf("SOC-END-D%02d-H24-S%02d",dayId,s); %#ok<AGROW>
        day(end+1,1)=dayId; hour(end+1,1)=24; storage(end+1,1)=s; %#ok<AGROW>
        equation_id(end+1,1)=eqId; boundary_role(end+1,1)="terminal_fixed_half_energy"; %#ok<AGROW>
        predecessor_day(end+1,1)=dayId; predecessor_hour(end+1,1)=24; %#ok<AGROW>
        predecessor_soc_index(end+1,1)=current; current_soc_index(end+1,1)=current; %#ok<AGROW>
        expected(end+1,1)="SOC(d,s,24)-0.5E(s)=0 in final hour block"; %#ok<AGROW>
        actual(end+1,1)=actualText; status(end+1,1)=pass_text(passed); %#ok<AGROW>
    end
end
output=table(check_id,day,hour,storage,equation_id,boundary_role, ...
    predecessor_day,predecessor_hour,predecessor_soc_index, ...
    current_soc_index,expected,actual,status);
end

function indexValue=q_day_index(lin,dayPosition,capacityPosition)
map=lin.maps.q_day_by_day;
if iscell(map)
    value=map{dayPosition}; indexValue=value(capacityPosition);
elseif size(map,1)==14
    indexValue=map(capacityPosition,dayPosition);
elseif size(map,2)==14
    indexValue=map(dayPosition,capacityPosition);
else
    error("stageA3:artifacts:QDayMapShape", ...
        "linearization.maps.q_day_by_day has an unsupported shape.");
end
end

function passed=predecessor_is_same_day(variables,globalIndex,dayId,hourId,storageId)
row=variables(variables.global_index_start==globalIndex& ...
    variables.global_index_end==globalIndex,:);
passed=height(row)==1&&row.day==dayId&&row.hour==hourId&& ...
    string(row.variable_name)=="SOC"&&row.asset_id==storageId;
end

function output=make_fixed_zero_recovery_audit(index,recursive,physical)
map=index.fixed_zero_map; count=height(map);
assert(count==recursive.fixed_zero.count, ...
    "stageA3:artifacts:FixedZeroCount", ...
    "Canonical and recovered A3 fixed-zero counts differ.");
assert(recursive.fixed_zero.count==count&&recursive.fixed_zero.all_exact_zero, ...
    "stageA3:artifacts:FixedZeroShape", ...
    "Recursive recovery did not report the canonical fixed-zero count.");
assert(physical.fixed_zero_audit.count==count&& ...
    physical.fixed_zero_audit.values_exact_zero&& ...
    physical.fixed_zero_audit.directions_exact_zero&& ...
    physical.fixed_zero_audit.maximum_absolute_value==0&& ...
    physical.fixed_zero_audit.maximum_absolute_direction==0, ...
    "stageA3:artifacts:PhysicalFixedZero", ...
    "Actual physical recovery did not preserve exact fixed zeros.");
recovered_value=zeros(count,1); recovered_direction=zeros(count,1);
recovery_source=strings(count,1);
for row=1:count
    dayPosition=find(double(physical.days)==double(map.day(row)),1);
    hourPosition=find(double(physical.hours)==double(map.hour(row)),1);
    assert(~isempty(dayPosition)&&~isempty(hourPosition), ...
        "stageA3:artifacts:PhysicalFixedZeroLocation", ...
        "Fixed-zero row %d is outside physical recovery arrays.",row);
    if string(map.asset_type(row))=="wind"&& ...
            string(map.variable_name(row))=="PW"
        field="wind";
    elseif string(map.asset_type(row))=="solar"&& ...
            string(map.variable_name(row))=="PP"
        field="solar";
    else
        error("stageA3:artifacts:PhysicalFixedZeroType", ...
            "Unsupported fixed-zero row %d: %s/%s.",row, ...
            map.asset_type(row),map.variable_name(row));
    end
    recovered_value(row)=physical.value.(field)(dayPosition,hourPosition, ...
        map.asset_id(row));
    recovered_direction(row)=physical.direction.(field)(dayPosition,hourPosition, ...
        map.asset_id(row));
    recovery_source(row)="physical."+field+"[day,hour,asset]";
end
status=repmat("PASS",count,1);
passed=map.fixed_value==0&map.fixed_direction_value==0& ...
    recovered_value==0&recovered_direction==0& ...
    string(map.inequality_status)=="NOT_APPLICABLE_BOTH_BOUNDS";
status(~passed)="FAIL";
output=addvars(map,recovered_value,recovered_direction,recovery_source,status, ...
    'NewVariableNames',{'recovered_value','recovered_direction', ...
    'recovery_source','status'});
end

function output=make_renewable_activity(data,index,config)
n=numel(config.days)*numel(config.hours)*10;
day=zeros(n,1); hour=zeros(n,1); asset_type=strings(n,1);
asset_id=zeros(n,1); variable_name=strings(n,1); kappa=zeros(n,1);
exact_zero=false(n,1); active_variable_present=false(n,1);
active_global_index=zeros(n,1); fixed_zero_map_present=false(n,1);
lower_bound_removed=false(n,1); upper_bound_removed=false(n,1);
status=strings(n,1); row=0;
for dayId=config.days
    for h=config.hours
        for kind=["wind","solar"]
            for asset=1:5
                row=row+1; day(row)=dayId; hour(row)=h;
                asset_type(row)=kind; asset_id(row)=asset;
                if kind=="wind"
                    variable_name(row)="PW";
                    kappa(row)=data.timeseries.windAvailability(dayId,h,asset);
                else
                    variable_name(row)="PP";
                    kappa(row)=data.timeseries.solarAvailability(dayId,h,asset);
                end
                exact_zero(row)=kappa(row)==0;
                variable=index.variable_index(index.variable_index.day==dayId& ...
                    index.variable_index.hour==h& ...
                    string(index.variable_index.asset_type)==kind& ...
                    index.variable_index.asset_id==asset& ...
                    string(index.variable_index.variable_name)==variable_name(row),:);
                fixed=index.fixed_zero_map(index.fixed_zero_map.day==dayId& ...
                    index.fixed_zero_map.hour==h& ...
                    string(index.fixed_zero_map.asset_type)==kind& ...
                    index.fixed_zero_map.asset_id==asset& ...
                    string(index.fixed_zero_map.variable_name)==variable_name(row),:);
                active_variable_present(row)=height(variable)==1;
                if height(variable)==1
                    active_global_index(row)=variable.global_index_start;
                end
                fixed_zero_map_present(row)=height(fixed)==1;
                if height(fixed)==1
                    both=string(fixed.inequality_status)== ...
                        "NOT_APPLICABLE_BOTH_BOUNDS";
                    lower_bound_removed(row)=both; upper_bound_removed(row)=both;
                end
                passed=(exact_zero(row)&&~active_variable_present(row)&& ...
                    fixed_zero_map_present(row)&&lower_bound_removed(row)&& ...
                    upper_bound_removed(row))||(~exact_zero(row)&& ...
                    active_variable_present(row)&&~fixed_zero_map_present(row));
                status(row)=pass_text(passed);
            end
        end
    end
end
output=table(day,hour,asset_type,asset_id,variable_name,kappa,exact_zero, ...
    active_variable_present,active_global_index,fixed_zero_map_present, ...
    lower_bound_removed,upper_bound_removed,status);
end

function value=make_identity_evidence(lin,fullResult,recursive,index,config)
dayChainDimensions=zeros(1,numel(recursive.daily_partitions));
fixedByDay=zeros(1,numel(config.days));
for k=1:numel(config.days)
    dayChainDimensions(k)=size(recursive.daily_partitions(k).M,1);
    fixedByDay(k)=nnz(index.fixed_zero_map.day==config.days(k));
end
assemblyAudit=recursive.partition.assembly_audit;
sideEffectFree=arrayfun(@(response) ...
    logical(response.diagnostics.side_effect_free),recursive.daily_responses);
value=struct("linearization_identity",char(string(lin.identity)), ...
    "linearization_version",char(string(lin.version)), ...
    "full_kkt_identity",char(string(fullResult.linearization_identity)), ...
    "recursive_identity",char(string(recursive.linearization_identity)), ...
    "all_identities_equal",string(lin.identity)== ...
        string(fullResult.linearization_identity)&&string(lin.identity)== ...
        string(recursive.linearization_identity), ...
    "shared_linearization_object_count",1,"hessian_nnz",nnz(lin.H), ...
    "full_kkt_dimension",fullResult.kkt.dimension, ...
    "day_ids",config.days,"daily_chain_dimensions",dayChainDimensions, ...
    "daily_response_count",numel(recursive.daily_responses), ...
    "daily_response_dimension",14,"global_core_dimension", ...
        size(recursive.core.matrix,1), ...
    "fixed_zero_count",height(index.fixed_zero_map), ...
    "fixed_zero_count_by_day",fixedByDay, ...
    "index_version",char(string(index.version)), ...
    "time_scope_type",char(string(config.time_scope_type)), ...
    "hours",config.hours,"soc_boundary_mode",char(string(config.soc_boundary_mode)), ...
    "no_interday_soc_links", ...
        logical(assemblyAudit.no_cross_day_soc_coupling)&& ...
        double(assemblyAudit.cross_day_hourly_equality_nnz)==0, ...
    "cross_day_hourly_equality_nnz", ...
        double(assemblyAudit.cross_day_hourly_equality_nnz), ...
    "daily_response_side_effect_free_by_day",sideEffectFree, ...
    "daily_response_function_global_side_effects",~all(sideEffectFree), ...
    "no_automatic_regularization",~config.linear_algebra.automatic_regularization, ...
    "no_automatic_symmetrization",~config.linear_algebra.automatic_symmetrization, ...
    "no_full_kkt_direction_fallback",recursive.no_full_direction_fallback);
end

function write_sparse_triplets(pathValue,matrix)
[row,column,value]=find(sparse(matrix));
write_table_csv_17g(pathValue,table(row,column,value));
end

function output=make_matrix_manifest(paths,lin,fullResult,recursive)
names=["linearization_H";"linearization_A";"linearization_G"; ...
    "full_kkt";"reduced_W";"reduced_saddle"];
values={lin.H;lin.A;lin.G;fullResult.kkt.matrix; ...
    recursive.reduced.W;recursive.reduced.saddle};
artifactPaths=[repmat(string(paths.linearization_mat),3,1); ...
    string(paths.full_kkt_mat);repmat(string(paths.reduced_system_mat),2,1)];
for d=1:numel(recursive.daily_partitions)
    partition=recursive.daily_partitions(d); dayId=double(partition.day_id);
    names(end+1,1)=sprintf("day_%02d_chain_M",dayId); %#ok<AGROW>
    values{end+1,1}=partition.M; %#ok<AGROW>
    artifactPaths(end+1,1)=string(paths.daily_recursive_mat); %#ok<AGROW>
    for h=1:numel(partition.hour)
        block=partition.hour(h); hourId=double(block.hour);
        names=[names;sprintf("day_%02d_hour_%02d_D",dayId,hourId); ...
            sprintf("day_%02d_hour_%02d_E",dayId,hourId); ...
            sprintf("day_%02d_hour_%02d_B",dayId,hourId)]; %#ok<AGROW>
        values=[values;{block.D;block.E;block.B}]; %#ok<AGROW>
        artifactPaths=[artifactPaths; ...
            repmat(string(paths.daily_recursive_mat),3,1)]; %#ok<AGROW>
    end
    names(end+1,1)=sprintf("day_%02d_response_S",dayId); %#ok<AGROW>
    values{end+1,1}=recursive.daily_responses(d).S; %#ok<AGROW>
    artifactPaths(end+1,1)=string(paths.daily_responses_mat); %#ok<AGROW>
end
names=[names;"aggregated_response_S_sum";"global_core"];
values=[values;{recursive.aggregation.S_sum;recursive.core.matrix}];
artifactPaths=[artifactPaths;string(paths.daily_aggregation_mat); ...
    string(paths.daily_aggregation_mat)];
n=numel(values); rows=zeros(n,1); columns=zeros(n,1); nonzero=zeros(n,1);
is_sparse=false(n,1); sha256=strings(n,1); path=strings(n,1);
uniquePaths=unique(artifactPaths,'stable'); uniqueHashes=strings(numel(uniquePaths),1);
for k=1:numel(uniquePaths)
    uniqueHashes(k)=compute_sha256_file(uniquePaths(k));
end
for k=1:n
    [rows(k),columns(k)]=size(values{k}); nonzero(k)=nnz(values{k});
    is_sparse(k)=issparse(values{k});
    sha256(k)=uniqueHashes(find(uniquePaths==artifactPaths(k),1));
    path(k)=relative_path(fileparts(fileparts(paths.linearization_mat)), ...
        artifactPaths(k));
end
matrix_name=string(names);
output=table(matrix_name,rows,columns,nonzero,is_sparse,sha256,path, ...
    'VariableNames',{'matrix_name','rows','columns','nnz','is_sparse','sha256','path'});
end

function output=make_artifact_hashes(runRoot,targets)
n=numel(targets); relative_path_value=strings(n,1); sha256=strings(n,1);
bytes=zeros(n,1); artifact_type=strings(n,1);
for k=1:n
    assert(isfile(targets(k)),"stageA3:artifacts:MissingWrittenTarget", ...
        "Expected A3 artifact was not written: %s",targets(k));
    relative_path_value(k)=relative_path(runRoot,targets(k));
    sha256(k)=compute_sha256_file(targets(k)); info=dir(targets(k));
    bytes(k)=info.bytes; [~,~,extension]=fileparts(targets(k));
    artifact_type(k)=erase(lower(string(extension)),".");
end
scope=repmat("numerical_export",n,1); status=repmat("PASS",n,1);
output=table(relative_path_value,sha256,bytes,artifact_type,scope,status, ...
    'VariableNames',{'relative_path','sha256','bytes','artifact_type','scope','status'});
end

function value=relative_path(root,pathValue)
root=string(char(java.io.File(char(root)).getCanonicalPath()));
pathValue=string(char(java.io.File(char(pathValue)).getCanonicalPath()));
prefix=root+filesep;
assert(startsWith(lower(pathValue),lower(prefix)), ...
    "stageA3:artifacts:PathOutsideRun","Artifact path is outside run root.");
value=replace(extractAfter(pathValue,strlength(prefix)),string(filesep),"/");
end
function value=pass_text(condition)
if condition, value="PASS"; else, value="FAIL"; end
end
function value=number_or_na(number)
if isfinite(number), value=sprintf("%d",number); else, value="NA"; end
end
