function exported = export_stage_a4_3_structural_artifacts( ...
        runContext,data,index,config,runResult, ...
        forbiddenCodeAudit,forbiddenExecutionAudit,dependencyClosure)
%EXPORT_STAGE_A4_3_STRUCTURAL_ARTIFACTS Persist final A4-3 structure.
%
% The final complete KKT is assembled but never solved here.  Every
% accepted iteration has already performed its own independent sparse
% complete-KKT audit inside run_stage_a4_full_ipm.  This exporter therefore
% cannot add an unrecorded Newton direction or become a fallback route.

arguments
    runContext (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    runResult (1,1) struct
    forbiddenCodeAudit table
    forbiddenExecutionAudit table
    dependencyClosure table
end

paths = artifact_paths(runContext);
targets = string(struct2cell(paths));
assert_targets_absent(targets);
ensure_directory(fullfile(runContext.root,"diagnostics"));

linearization = runResult.final_linearization;
kkt = assemble_stage_a_multiday_full_kkt(linearization);
assert(kkt.dimension==config.expected_full_kkt_dimension && ...
    issparse(kkt.matrix) && ...
    string(kkt.linearization_identity)==string(linearization.identity), ...
    "stageA4:a43:StructuralKkt", ...
    "The final structural KKT does not match the frozen shared linearization.");

save_mat_artifact(paths.linearization_mat, ...
    "linearization",linearization);
save_mat_artifact(paths.full_kkt_mat, ...
    "kkt",kkt,"solve_performed",false, ...
    "role","final_structural_snapshot_only");
save_mat_artifact(paths.index_mat,"index",index);
save_mat_artifact(paths.configuration_mat, ...
    "config",config,"data_metadata",data.meta,"input_hashes",data.hashes);

write_table_csv_17g(paths.variable_index,index.variable_index);
write_table_csv_17g(paths.constraint_index,index.constraint_index);
write_table_csv_17g(paths.block_index,index.block_index);
write_table_csv_17g(paths.fixed_zero_map,index.fixed_zero_map);
write_table_csv_17g(paths.soc_link_map,index.soc_link_map);
write_table_csv_17g(paths.permutation_map,index.permutation_map);
write_table_csv_17g(paths.forbidden_code_audit,forbiddenCodeAudit);
write_table_csv_17g(paths.forbidden_execution_audit, ...
    forbiddenExecutionAudit);
write_table_csv_17g(paths.dependency_closure,dependencyClosure);

matrixManifest = make_matrix_manifest( ...
    runContext,linearization,kkt,paths);
write_table_csv_17g(paths.matrix_manifest,matrixManifest);

hashTargets = targets(~endsWith(targets,"artifact_hashes.csv"));
artifactHashes = make_hash_manifest(runContext.root,hashTargets);
write_table_csv_17g(paths.artifact_hashes,artifactHashes);
exported = struct("paths",paths,"matrix_manifest",matrixManifest, ...
    "artifact_hashes",artifactHashes,"kkt_dimension",kkt.dimension, ...
    "kkt_nnz",kkt.nnz,"linearization_identity", ...
    string(linearization.identity),"additional_direction_solve_count",0);
end

function paths = artifact_paths(context)
paths = struct( ...
    "linearization_mat",fullfile(context.matrices_dir, ...
        "final_linearization.mat"), ...
    "full_kkt_mat",fullfile(context.matrices_dir, ...
        "final_full_kkt_structural_snapshot.mat"), ...
    "index_mat",fullfile(context.indices_dir,"canonical_index.mat"), ...
    "configuration_mat",fullfile(context.matrices_dir, ...
        "configuration_and_input_metadata.mat"), ...
    "variable_index",fullfile(context.indices_dir,"variable_index.csv"), ...
    "constraint_index",fullfile(context.indices_dir,"constraint_index.csv"), ...
    "block_index",fullfile(context.indices_dir,"block_index.csv"), ...
    "fixed_zero_map",fullfile(context.indices_dir,"fixed_zero_map.csv"), ...
    "soc_link_map",fullfile(context.indices_dir,"soc_link_map.csv"), ...
    "permutation_map",fullfile(context.indices_dir,"permutation_map.csv"), ...
    "forbidden_code_audit",fullfile(context.root,"diagnostics", ...
        "forbidden_code_audit.csv"), ...
    "forbidden_execution_audit",fullfile(context.root,"diagnostics", ...
        "forbidden_execution_audit.csv"), ...
    "dependency_closure",fullfile(context.root,"diagnostics", ...
        "dependency_closure_sha256.csv"), ...
    "matrix_manifest",context.matrix_manifest_path, ...
    "artifact_hashes",fullfile(context.matrices_dir, ...
        "structural_artifact_hashes.csv"));
end

function output = make_matrix_manifest(context,lin,kkt,paths)
matrix_name = ["H";"A";"G";"complete_primal_dual_kkt"];
rows = [size(lin.H,1);size(lin.A,1);size(lin.G,1);size(kkt.matrix,1)];
columns = [size(lin.H,2);size(lin.A,2); ...
    size(lin.G,2);size(kkt.matrix,2)];
nonzeros = [nnz(lin.H);nnz(lin.A);nnz(lin.G);nnz(kkt.matrix)];
is_sparse = [issparse(lin.H);issparse(lin.A); ...
    issparse(lin.G);issparse(kkt.matrix)];
role = ["zero_hessian";"equality_jacobian"; ...
    "inequality_jacobian";"audit_operator_structural_snapshot"];
solve_performed_by_exporter = false(4,1);
linearization_identity = repmat(string(lin.identity),4,1);
artifact_path = [relative_path(paths.linearization_mat,context.root); ...
    relative_path(paths.linearization_mat,context.root); ...
    relative_path(paths.linearization_mat,context.root); ...
    relative_path(paths.full_kkt_mat,context.root)];
status = repmat("PASS",4,1);
output = table(matrix_name,rows,columns,nonzeros,is_sparse,role, ...
    solve_performed_by_exporter,linearization_identity,artifact_path,status);
end

function output = make_hash_manifest(root,targets)
n = numel(targets);
relative_path_value = strings(n,1);
sha256 = strings(n,1);
bytes = zeros(n,1);
status = repmat("PASS",n,1);
for k = 1:n
    assert(isfile(targets(k)),"stageA4:a43:StructuralArtifactMissing", ...
        "Structural artifact is missing: %s",targets(k));
    relative_path_value(k) = relative_path(targets(k),root);
    sha256(k) = compute_sha256_file(targets(k));
    info = dir(targets(k));
    bytes(k) = info.bytes;
end
output = table(relative_path_value,sha256,bytes,status, ...
    'VariableNames',{'relative_path','sha256','bytes','status'});
end

function value = relative_path(pathValue,root)
pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
root = string(char(java.io.File(char(root)).getCanonicalPath()));
value = replace(extractAfter(pathValue,strlength(root)+1),"\","/");
end

function assert_targets_absent(targets)
for target = targets.'
    assert(~isfile(target)&&~isfolder(target), ...
        "stageA4:a43:StructuralArtifactExists", ...
        "Refusing to overwrite A4-3 structural artifact %s.",target);
end
end

function ensure_directory(pathValue)
if isfolder(pathValue)
    return
end
[created,message] = mkdir(pathValue);
assert(created,"stageA4:a43:StructuralDirectoryCreate","%s",message);
end
