function exported = export_stage_a2_artifacts(runContext,data,index,config, ...
        linearization,fullResult,recursiveResult,audit,options)
%EXPORT_STAGE_A2_ARTIFACTS Persist one formal-day A2 direction comparison.
% Complete KKT and 589-dimensional chain matrices remain sparse MAT data.

arguments
    runContext (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    linearization (1,1) struct
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    audit (1,1) struct
    options.Environment = struct()
    options.Tests = struct()
    options.A1Regression = struct()
    options.CodeScan table = table()
end
validate_inputs(runContext,index,config,linearization,fullResult, ...
    recursiveResult,audit);
paths = artifact_paths(runContext,config.hours);
targets = output_targets(paths);
assert_targets_absent(targets);
ensure_directory(paths.diagnostics_dir);

save_mat_artifact(paths.linearization_mat,"linearization",linearization);
save_mat_artifact(paths.full_kkt_mat,"kkt",fullResult.kkt, ...
    "diagnostics",fullResult.diagnostics, ...
    "linearization_identity",fullResult.linearization_identity);
save_mat_artifact(paths.recursive_blocks_mat, ...
    "reduced",recursiveResult.reduced,"partition",recursiveResult.partition, ...
    "thomas",recursiveResult.thomas,"day_response",recursiveResult.day_response, ...
    "core",recursiveResult.core,"recovery",recursiveResult.recovery, ...
    "linearization_identity",recursiveResult.linearization_identity);
save_mat_artifact(paths.directions_mat, ...
    "full_direction",fullResult.direction, ...
    "recursive_direction",recursiveResult.direction, ...
    "full_components",fullResult.components, ...
    "recursive_components",recursiveResult.components, ...
    "fixed_zero",recursiveResult.fixed_zero);
fullResidual = fullResult.kkt.matrix*fullResult.direction-fullResult.kkt.rhs;
recursiveResidual = fullResult.kkt.matrix*recursiveResult.direction- ...
    fullResult.kkt.rhs;
save_mat_artifact(paths.residuals_mat,"audit",audit, ...
    "full_kkt_residual",fullResidual, ...
    "recursive_full_kkt_residual",recursiveResidual, ...
    "recursive_reinsertion",recursiveResult.full_kkt_reinsertion, ...
    "chain_diagnostics",recursiveResult.thomas.diagnostics, ...
    "core_diagnostics",recursiveResult.core.diagnostics);
save_mat_artifact(paths.index_mapping_mat,"index",index);
save_mat_artifact(paths.configuration_mat,"config",config, ...
    "data_metadata",data.meta,"input_hashes",data.hashes, ...
    "environment",options.Environment,"tests",options.Tests, ...
    "a1_regression",options.A1Regression);

write_table_csv_17g(paths.variable_index,index.variable_index);
write_table_csv_17g(paths.constraint_index,index.constraint_index);
write_table_csv_17g(paths.block_index,index.block_index);
write_table_csv_17g(paths.fixed_zero_map,index.fixed_zero_map);
write_table_csv_17g(paths.permutation_map,index.permutation_map);
write_table_csv_17g(paths.soc_link_map,index.soc_link_map);
indexAudit = validate_canonical_index_framework(index);
write_table_csv_17g(paths.index_audit,indexAudit);

blockDimensions = make_block_dimensions(recursiveResult,config);
blockDiagnostics = make_block_diagnostics(recursiveResult,config);
comparison = make_direction_comparison(audit,recursiveResult,config, ...
    linearization,fullResult);
residualSummary = make_residual_summary(fullResult,recursiveResult,config);
socAudit = make_soc_boundary_audit(index,linearization,config);
fixedAudit = make_fixed_zero_recovery_audit(index,recursiveResult);
activity = make_renewable_activity(data,index,config);
write_table_csv_17g(paths.block_dimensions,blockDimensions);
write_table_csv_17g(paths.block_diagnostics,blockDiagnostics);
write_table_csv_17g(paths.direction_comparison,comparison);
write_table_csv_17g(paths.residual_summary,residualSummary);
write_table_csv_17g(paths.soc_boundary_audit,socAudit);
write_table_csv_17g(paths.fixed_zero_recovery_audit,fixedAudit);
write_table_csv_17g(paths.renewable_activity,activity);

if isempty(options.CodeScan)
    codeScan = scan_stage_a2_forbidden_code(string(runContext.project_root),config);
else
    codeScan = options.CodeScan;
end
write_table_csv_17g(paths.code_scan,codeScan);
identityEvidence = make_identity_evidence(linearization,fullResult, ...
    recursiveResult,index,config);
write_json_file(paths.linearization_identity,identityEvidence);

write_sparse_triplets(paths.core_triplets,recursiveResult.core.matrix);
write_sparse_triplets(paths.day_response_triplets,recursiveResult.day_response.S);
for position = 1:numel(config.hours)
    write_sparse_triplets(paths.hour_D_triplets(position), ...
        recursiveResult.partition.hour(position).D);
end
matrixManifest = make_matrix_manifest(paths,linearization,fullResult, ...
    recursiveResult,config.hours);
write_table_csv_17g(paths.matrix_manifest,matrixManifest);

hashTargets = targets(targets~=string(paths.artifact_hashes));
artifactHashes = make_artifact_hashes(runContext.root,hashTargets);
write_table_csv_17g(paths.artifact_hashes,artifactHashes);
exported = struct("paths",paths,"matrix_manifest",matrixManifest, ...
    "block_dimensions",blockDimensions,"block_diagnostics",blockDiagnostics, ...
    "direction_comparison",comparison,"residual_summary",residualSummary, ...
    "soc_boundary_audit",socAudit,"fixed_zero_recovery_audit",fixedAudit, ...
    "renewable_activity",activity,"code_scan",codeScan, ...
    "artifact_hashes",artifactHashes, ...
    "linearization_identity",identityEvidence);
end

function validate_inputs(context,index,config,lin,fullResult,recursive,audit)
requiredContext = ["root","run_id","stage_id","matrices_dir", ...
    "indices_dir","iterations_dir","project_root"];
assert(all(isfield(context,cellstr(requiredContext))) && isfolder(context.root), ...
    "stageA2:artifacts:InvalidRunContext","Invalid A2 run context.");
assert(string(context.stage_id)=="stage_A2", ...
    "stageA2:artifacts:StageMismatch","A2 exporter requires stage_A2.");
manifest = jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.run_id)==string(context.run_id) && ...
    string(manifest.stage_id)=="stage_A2" && string(manifest.status)=="RUNNING", ...
    "stageA2:artifacts:ManifestIdentity", ...
    "A2 export requires the matching RUNNING manifest.");
requiredIndex = ["variable_index","constraint_index","block_index", ...
    "fixed_zero_map","permutation_map","soc_link_map"];
assert(all(isfield(index,cellstr(requiredIndex))) && ...
    all(cellfun(@istable,struct2cell(rmfield(index, ...
    setdiff(fieldnames(index),cellstr(requiredIndex)))))), ...
    "stageA2:artifacts:IndexContract","Six canonical index tables are required.");
assert(lin.counts.full_kkt==2749 && fullResult.kkt.dimension==2749 && ...
    isequal(size(fullResult.kkt.matrix),[2749 2749]) && ...
    issparse(fullResult.kkt.matrix), ...
    "stageA2:artifacts:FullKktDimension", ...
    "The complete A2 KKT must be sparse and 2749-by-2749.");
blocks = [recursive.partition.hour.dimension];
assert(numel(blocks)==24 && ...
    isequal(blocks,config.expected_hourly_kkt_block_dimensions) && ...
    sum(blocks)==589 && size(recursive.partition.M,1)==589 && ...
    issparse(recursive.partition.M), ...
    "stageA2:artifacts:HourBlockDimension", ...
    "A2 requires the natural 24-block, 589-dimensional sparse chain.");
assert(isequal(size(recursive.day_response.S),[14 14]) && ...
    isequal(size(recursive.core.matrix),[16 16]), ...
    "stageA2:artifacts:CoreDimension", ...
    "A2 day response/core must be 14-by-14 and 16-by-16.");
assert(height(index.fixed_zero_map)==61 && recursive.fixed_zero.count==61, ...
    "stageA2:artifacts:FixedZeroCount", ...
    "A2 fixed-zero mapping must contain the 61 data-derived rows.");
identities = string([lin.identity,fullResult.linearization_identity, ...
    recursive.linearization_identity,audit.linearization_identity]);
assert(isscalar(unique(identities)), ...
    "stageA2:artifacts:LinearizationIdentity", ...
    "Full, recursive, and audit routes must share one linearization identity.");
assert(recursive.no_full_direction_fallback, ...
    "stageA2:artifacts:RecursiveFallback", ...
    "Recursive evidence that permits a full-KKT fallback cannot be exported.");
end

function paths = artifact_paths(context,hours)
paths = struct();
paths.diagnostics_dir=fullfile(context.root,"diagnostics");
paths.linearization_mat=fullfile(context.matrices_dir,"linearization.mat");
paths.full_kkt_mat=fullfile(context.matrices_dir,"full_kkt.mat");
paths.recursive_blocks_mat=fullfile(context.matrices_dir,"recursive_blocks.mat");
paths.directions_mat=fullfile(context.matrices_dir,"directions.mat");
paths.residuals_mat=fullfile(context.matrices_dir,"residuals.mat");
paths.index_mapping_mat=fullfile(context.matrices_dir,"index_mapping.mat");
paths.configuration_mat=fullfile(context.matrices_dir,"configuration.mat");
paths.matrix_manifest=fullfile(context.matrices_dir,"matrix_manifest.csv");
paths.block_dimensions=fullfile(context.matrices_dir,"block_dimensions.csv");
paths.block_diagnostics=fullfile(context.matrices_dir,"hourly_block_diagnostics.csv");
paths.direction_comparison=fullfile(context.iterations_dir,"direction_comparison.csv");
paths.residual_summary=fullfile(context.iterations_dir,"residual_summary.csv");
paths.variable_index=fullfile(context.indices_dir,"variable_index.csv");
paths.constraint_index=fullfile(context.indices_dir,"constraint_index.csv");
paths.block_index=fullfile(context.indices_dir,"block_index.csv");
paths.fixed_zero_map=fullfile(context.indices_dir,"fixed_zero_map.csv");
paths.permutation_map=fullfile(context.indices_dir,"permutation_map.csv");
paths.soc_link_map=fullfile(context.indices_dir,"soc_link_map.csv");
paths.index_audit=fullfile(context.indices_dir,"index_audit.csv");
paths.soc_boundary_audit=fullfile(context.indices_dir,"soc_boundary_audit.csv");
paths.fixed_zero_recovery_audit=fullfile(context.indices_dir, ...
    "fixed_zero_recovery_audit.csv");
paths.renewable_activity=fullfile(context.indices_dir, ...
    "hourly_renewable_activity.csv");
paths.code_scan=fullfile(paths.diagnostics_dir,"code_scan.csv");
paths.linearization_identity=fullfile(paths.diagnostics_dir, ...
    "linearization_identity.json");
paths.core_triplets=fullfile(context.matrices_dir,"global_core_triplets.csv");
paths.day_response_triplets=fullfile(context.matrices_dir, ...
    "day_response_S_triplets.csv");
paths.hour_D_triplets=strings(numel(hours),1);
for k=1:numel(hours)
    paths.hour_D_triplets(k)=fullfile(context.matrices_dir, ...
        sprintf("hour_%02d_D_triplets.csv",hours(k)));
end
paths.artifact_hashes=fullfile(context.matrices_dir, ...
    "numerical_artifact_hashes.csv");
end

function targets = output_targets(paths)
names=fieldnames(paths); targets=strings(0,1);
for k=1:numel(names)
    if names{k}=="diagnostics_dir", continue; end
    targets=[targets;reshape(string(paths.(names{k})),[],1)]; %#ok<AGROW>
end
assert(numel(unique(lower(targets)))==numel(targets), ...
    "stageA2:artifacts:DuplicateTarget","A2 artifact targets are not unique.");
end

function assert_targets_absent(targets)
for target=targets.'
    if isfile(target) || isfolder(target)
        error("stageA2:artifacts:TargetExists", ...
            "A2 artifact target exists and will not be overwritten: %s",target);
    end
end
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
if exist(pathValue,'file'), error("stageA2:artifacts:PathConflict", ...
        "A file exists where a directory is required: %s",pathValue); end
[created,message]=mkdir(pathValue);
assert(created,"stageA2:artifacts:CreateDirectory","%s",message);
end

function output = make_block_dimensions(recursive,config)
blocks=recursive.partition.hour; n=numel(blocks);
hour=reshape([blocks.hour],[],1); n_primal=reshape([blocks.n_primal],[],1);
n_equalities=reshape([blocks.n_equalities],[],1);
kkt_dimension=reshape([blocks.dimension],[],1);
expected_dimension=reshape(config.expected_hourly_kkt_block_dimensions,[],1);
status=repmat("PASS",n,1); status(kkt_dimension~=expected_dimension)="FAIL";
output=table(hour,n_primal,n_equalities,kkt_dimension,expected_dimension,status);
end

function output = make_block_diagnostics(recursive,config)
assert(isfield(recursive.thomas.diagnostics,"hour_block"), ...
    "stageA2:artifacts:HourDiagnosticsMissing", ...
    "The recursive solve did not return 24 hourly block diagnostics.");
value=recursive.thomas.diagnostics.hour_block;
assert(isstruct(value) && numel(value)==24, ...
    "stageA2:artifacts:HourDiagnosticsCount", ...
    "Exactly 24 hourly block diagnostics are required.");
output=struct2table(value(:));
required=["hour","dimension","D_numeric_rank","D_condition_2", ...
    "D_symmetry_relative","schur_numeric_rank","schur_condition_2", ...
    "schur_inertia_positive","schur_inertia_negative", ...
    "schur_inertia_zero","schur_factor_relative_residual","rhs_count"];
assert(all(ismember(required,string(output.Properties.VariableNames))), ...
    "stageA2:artifacts:HourDiagnosticsSchema", ...
    "Hourly diagnostic schema is incomplete.");
passed=output.dimension==reshape(config.expected_hourly_kkt_block_dimensions,[],1) & ...
    output.D_numeric_rank==output.dimension & isfinite(output.D_condition_2) & ...
    output.D_symmetry_relative<=config.tolerances.symmetry_relative & ...
    output.schur_numeric_rank==output.dimension & ...
    isfinite(output.schur_condition_2) & output.schur_inertia_zero==0 & ...
    output.schur_factor_relative_residual<= ...
        config.tolerances.recursive_full_kkt_relative_residual & ...
    output.rhs_count==15;
output.status=repmat("PASS",24,1); output.status(~passed)="FAIL";
end

function output = make_direction_comparison(audit,recursive,config,lin,fullResult)
identityMismatch=double(~(string(lin.identity)== ...
    string(fullResult.linearization_identity) && string(lin.identity)== ...
    string(recursive.linearization_identity)));
fixedValue=max([0;abs(recursive.fixed_zero.value(:))]);
fixedDirection=max([0;abs(recursive.fixed_zero.direction(:))]);
metric_id=["overall_direction_relative_2norm";"xi_direction_relative_2norm"; ...
    "y_direction_relative_2norm";"l_direction_relative_2norm"; ...
    "z_direction_relative_2norm";"fixed_zero_maximum_absolute_value"; ...
    "fixed_zero_maximum_absolute_direction";"linearization_identity_mismatch"; ...
    "recursive_full_direction_fallback_used";"reduced_assembly_relative_error"; ...
    "hour_chain_relative_residual";"global_core_relative_residual"];
actual_value=[audit.direction_relative_error;audit.component_relative_errors.xi; ...
    audit.component_relative_errors.y;audit.component_relative_errors.l; ...
    audit.component_relative_errors.z;fixedValue;fixedDirection;identityMismatch; ...
    double(~recursive.no_full_direction_fallback); ...
    recursive.partition.assembly_audit.matrix_relative_error; ...
    recursive.thomas.diagnostics.chain_relative_residual; ...
    recursive.core.diagnostics.relative_residual];
threshold=[repmat(config.tolerances.direction_relative_2norm,5,1);0;0;0;0; ...
    config.tolerances.symmetry_relative; ...
    config.tolerances.recursive_full_kkt_relative_residual; ...
    config.tolerances.recursive_full_kkt_relative_residual];
status=repmat("PASS",numel(actual_value),1);
status(~isfinite(actual_value) | actual_value>threshold)="FAIL";
output=table(metric_id,actual_value,threshold,status);
end

function output = make_residual_summary(fullResult,recursive,config)
K=fullResult.kkt.matrix; b=fullResult.kkt.rhs;
fullResidual=K*fullResult.direction-b; recursiveResidual=K*recursive.direction-b;
chainRhs=[recursive.partition.r_v,recursive.partition.B];
chainResidual=recursive.partition.M*recursive.thomas.stacked_solution-chainRhs;
coreResidual=recursive.core.matrix*recursive.core.solution-recursive.core.rhs;
route=["full_kkt_direct_preferred";"full_kkt_direct_hard_limit"; ...
    "recursive_direction_reinserted_in_full_kkt"; ...
    "recursive_hour_chain_15_rhs";"global_core_16"];
absolute_residual_2norm=[norm(fullResidual,2);norm(fullResidual,2); ...
    norm(recursiveResidual,2);norm(chainResidual,'fro');norm(coreResidual,2)];
rhs_2norm=[norm(b,2);norm(b,2);norm(b,2);norm(chainRhs,'fro'); ...
    norm(recursive.core.rhs,2)];
relative_residual_2norm=absolute_residual_2norm./max(1,rhs_2norm);
threshold=[config.tolerances.direct_preferred;config.tolerances.direct_maximum; ...
    repmat(config.tolerances.recursive_full_kkt_relative_residual,3,1)];
status=repmat("PASS",5,1);
status(~isfinite(relative_residual_2norm) | relative_residual_2norm>threshold)="FAIL";
output=table(route,absolute_residual_2norm,rhs_2norm, ...
    relative_residual_2norm,threshold,status);
end

function output = make_soc_boundary_audit(index,lin,config)
links=index.soc_link_map; constraints=index.constraint_index;
check_id=strings(0,1); hour=zeros(0,1); storage=zeros(0,1);
equation_id=strings(0,1); boundary_role=strings(0,1);
predecessor_hour=zeros(0,1); predecessor_soc_index=zeros(0,1);
current_soc_index=zeros(0,1); expected=strings(0,1); actual=strings(0,1);
status=strings(0,1);
for h=config.hours
    for s=1:2
        link=links(links.day==config.days(1) & links.hour==h & ...
            links.storage_id==s,:);
        equation=constraints(constraints.day==config.days(1) & ...
            constraints.hour==h & string(constraints.constraint_type)=="equality" & ...
            string(constraints.constraint_name)=="soc_dynamics" & ...
            constraints.asset_id==s,:);
        passed=height(link)==1 && height(equation)==1;
        if passed
            passed=lin.A(equation.global_row,link.current_soc_global_index)==1;
        end
        if h==config.start_hour
            role="initial_fixed_half_energy";
            if height(link)==1 && height(equation)==1
                passed=passed && isnan(link.predecessor_hour) && ...
                    link.predecessor_soc_global_index==0 && ...
                    link.initial_energy_fraction==0.5 && ...
                    lin.A(equation.global_row,lin.maps.q_day(12+s))==-0.5;
                expectedText="SOC(14,s,1)-0.5E(s); no previous-day link";
            else
                expectedText="one initial SOC equation";
            end
        else
            role="same_day_predecessor";
            if height(link)==1 && height(equation)==1
                passed=passed && link.predecessor_hour==h-1 && ...
                    link.predecessor_soc_global_index>0 && ...
                    lin.A(equation.global_row,link.predecessor_soc_global_index)==-1 && ...
                    lin.A(equation.global_row,lin.maps.q_day(12+s))==0;
            end
            expectedText=sprintf("same-day predecessor hour %d",h-1);
        end
        if height(link)==1
            pred=link.predecessor_hour; predIndex=link.predecessor_soc_global_index;
            current=link.current_soc_global_index;
            actualText=sprintf("source=%s; predecessor=%s; predecessor_index=%d", ...
                string(link.boundary_source),number_or_na(pred),predIndex);
        else
            pred=NaN; predIndex=0; current=0; actualText="MISSING_OR_DUPLICATE";
        end
        if height(equation)==1, eqId=string(equation.constraint_id); else, eqId="MISSING_OR_DUPLICATE"; end
        check_id(end+1,1)=sprintf("SOC-DYN-H%02d-S%02d",h,s); %#ok<AGROW>
        hour(end+1,1)=h; storage(end+1,1)=s; equation_id(end+1,1)=eqId;
        boundary_role(end+1,1)=role; predecessor_hour(end+1,1)=pred;
        predecessor_soc_index(end+1,1)=predIndex; current_soc_index(end+1,1)=current;
        expected(end+1,1)=expectedText; actual(end+1,1)=actualText;
        status(end+1,1)=pass_text(passed);
    end
end
for s=1:2
    link=links(links.day==config.days(1) & links.hour==config.terminal_hour & ...
        links.storage_id==s,:);
    equation=constraints(constraints.day==config.days(1) & ...
        constraints.hour==config.terminal_hour & ...
        string(constraints.constraint_type)=="equality" & ...
        string(constraints.constraint_name)=="terminal_soc" & ...
        constraints.asset_id==s,:);
    passed=height(link)==1 && height(equation)==1 && ...
        link.terminal_equality && link.terminal_energy_fraction==0.5;
    if passed
        passed=lin.A(equation.global_row,link.current_soc_global_index)==1 && ...
            lin.A(equation.global_row,lin.maps.q_day(12+s))==-0.5;
        eqId=string(equation.constraint_id); current=link.current_soc_global_index;
        actualText="hour=24; fraction="+compose("%.17g",link.terminal_energy_fraction);
    else
        eqId="MISSING_OR_DUPLICATE"; current=0; actualText="MISSING_OR_DUPLICATE";
    end
    check_id(end+1,1)=sprintf("SOC-END-H24-S%02d",s); hour(end+1,1)=24;
    storage(end+1,1)=s; equation_id(end+1,1)=eqId;
    boundary_role(end+1,1)="terminal_fixed_half_energy";
    predecessor_hour(end+1,1)=24; predecessor_soc_index(end+1,1)=current;
    current_soc_index(end+1,1)=current;
    expected(end+1,1)="SOC(14,s,24)-0.5E(s)=0 in final hour block";
    actual(end+1,1)=actualText; status(end+1,1)=pass_text(passed);
end
output=table(check_id,hour,storage,equation_id,boundary_role, ...
    predecessor_hour,predecessor_soc_index,current_soc_index, ...
    expected,actual,status);
end

function output = make_fixed_zero_recovery_audit(index,recursive)
map=index.fixed_zero_map; count=height(map);
assert(count==recursive.fixed_zero.count && count==61, ...
    "stageA2:artifacts:FixedZeroCount", ...
    "Canonical and recovered A2 fixed-zero counts must both equal 61.");
recovered_value=reshape(double(recursive.fixed_zero.value),[],1);
recovered_direction=reshape(double(recursive.fixed_zero.direction),[],1);
assert(numel(recovered_value)==count && numel(recovered_direction)==count, ...
    "stageA2:artifacts:FixedZeroShape","Fixed-zero recovery shape is invalid.");
status=repmat("PASS",count,1);
passed=map.fixed_value==0 & map.fixed_direction_value==0 & ...
    recovered_value==0 & recovered_direction==0 & ...
    string(map.inequality_status)=="NOT_APPLICABLE_BOTH_BOUNDS";
status(~passed)="FAIL";
output=addvars(map,recovered_value,recovered_direction,status, ...
    'NewVariableNames',{'recovered_value','recovered_direction','status'});
end

function output = make_renewable_activity(data,index,config)
n=numel(config.hours)*10;
day=repmat(config.days(1),n,1); hour=zeros(n,1); asset_type=strings(n,1);
asset_id=zeros(n,1); variable_name=strings(n,1); kappa=zeros(n,1);
exact_zero=false(n,1); active_variable_present=false(n,1);
active_global_index=zeros(n,1); fixed_zero_map_present=false(n,1);
lower_bound_removed=false(n,1); upper_bound_removed=false(n,1);
status=strings(n,1); row=0;
for h=config.hours
    for kind=["wind","solar"]
        for asset=1:5
            row=row+1; hour(row)=h; asset_type(row)=kind; asset_id(row)=asset;
            if kind=="wind"
                variable_name(row)="PW";
                kappa(row)=data.timeseries.windAvailability(config.days(1),h,asset);
            else
                variable_name(row)="PP";
                kappa(row)=data.timeseries.solarAvailability(config.days(1),h,asset);
            end
            exact_zero(row)=kappa(row)==0;
            variable=index.variable_index(index.variable_index.day==config.days(1) & ...
                index.variable_index.hour==h & ...
                string(index.variable_index.asset_type)==kind & ...
                index.variable_index.asset_id==asset & ...
                string(index.variable_index.variable_name)==variable_name(row),:);
            fixed=index.fixed_zero_map(index.fixed_zero_map.day==config.days(1) & ...
                index.fixed_zero_map.hour==h & ...
                string(index.fixed_zero_map.asset_type)==kind & ...
                index.fixed_zero_map.asset_id==asset & ...
                string(index.fixed_zero_map.variable_name)==variable_name(row),:);
            active_variable_present(row)=height(variable)==1;
            if height(variable)==1, active_global_index(row)=variable.global_index_start; end
            fixed_zero_map_present(row)=height(fixed)==1;
            if height(fixed)==1
                both=string(fixed.inequality_status)=="NOT_APPLICABLE_BOTH_BOUNDS";
                lower_bound_removed(row)=both; upper_bound_removed(row)=both;
            end
            passed=(exact_zero(row) && ~active_variable_present(row) && ...
                fixed_zero_map_present(row) && lower_bound_removed(row) && ...
                upper_bound_removed(row)) || (~exact_zero(row) && ...
                active_variable_present(row) && ~fixed_zero_map_present(row));
            status(row)=pass_text(passed);
        end
    end
end
output=table(day,hour,asset_type,asset_id,variable_name,kappa,exact_zero, ...
    active_variable_present,active_global_index,fixed_zero_map_present, ...
    lower_bound_removed,upper_bound_removed,status);
end

function value = make_identity_evidence(lin,fullResult,recursive,index,config)
value=struct("linearization_identity",char(string(lin.identity)), ...
    "linearization_version",char(string(lin.version)), ...
    "full_kkt_identity",char(string(fullResult.linearization_identity)), ...
    "recursive_identity",char(string(recursive.linearization_identity)), ...
    "all_identities_equal",string(lin.identity)== ...
        string(fullResult.linearization_identity) && string(lin.identity)== ...
        string(recursive.linearization_identity), ...
    "shared_linearization_object_count",1,"hessian_nnz",nnz(lin.H), ...
    "full_kkt_dimension",fullResult.kkt.dimension, ...
    "hourly_block_dimensions",[recursive.partition.hour.dimension], ...
    "hourly_chain_dimension",size(recursive.partition.M,1), ...
    "day_response_dimension",size(recursive.day_response.S,1), ...
    "global_core_dimension",size(recursive.core.matrix,1), ...
    "fixed_zero_count",height(index.fixed_zero_map), ...
    "index_version",char(string(index.version)), ...
    "time_scope_type",char(string(config.time_scope_type)), ...
    "day",config.days,"start_hour",config.start_hour, ...
    "terminal_hour",config.terminal_hour, ...
    "soc_boundary_mode",char(string(config.soc_boundary_mode)), ...
    "no_automatic_regularization",~config.linear_algebra.automatic_regularization, ...
    "no_automatic_symmetrization",~config.linear_algebra.automatic_symmetrization, ...
    "no_full_kkt_direction_fallback",recursive.no_full_direction_fallback);
end

function write_sparse_triplets(pathValue,matrix)
[row,column,value]=find(sparse(matrix));
write_table_csv_17g(pathValue,table(row,column,value));
end

function output = make_matrix_manifest(paths,lin,fullResult,recursive,hours)
names=["linearization_H";"linearization_A";"linearization_G"; ...
    "full_kkt";"reduced_W";"reduced_saddle"];
values={lin.H;lin.A;lin.G;fullResult.kkt.matrix;recursive.reduced.W; ...
    recursive.reduced.saddle};
artifactPaths=[repmat(string(paths.linearization_mat),3,1); ...
    string(paths.full_kkt_mat);repmat(string(paths.recursive_blocks_mat),2,1)];
for k=1:numel(hours)
    names=[names;sprintf("hour_%02d_D",hours(k)); ...
        sprintf("hour_%02d_E",hours(k));sprintf("hour_%02d_B",hours(k))]; %#ok<AGROW>
    values=[values;{recursive.partition.hour(k).D; ...
        recursive.partition.hour(k).E;recursive.partition.hour(k).B}]; %#ok<AGROW>
    artifactPaths=[artifactPaths;repmat(string(paths.recursive_blocks_mat),3,1)]; %#ok<AGROW>
end
names=[names;"hour_chain_M";"day_response_S";"global_core"];
values=[values;{recursive.partition.M;recursive.day_response.S;recursive.core.matrix}];
artifactPaths=[artifactPaths;repmat(string(paths.recursive_blocks_mat),3,1)];
n=numel(values); rows=zeros(n,1); columns=zeros(n,1); nonzero=zeros(n,1);
is_sparse=false(n,1); sha256=strings(n,1); path=strings(n,1);
for k=1:n
    [rows(k),columns(k)]=size(values{k}); nonzero(k)=nnz(values{k});
    is_sparse(k)=issparse(values{k}); sha256(k)=compute_sha256_file(artifactPaths(k));
    path(k)=relative_path(fileparts(fileparts(paths.linearization_mat)),artifactPaths(k));
end
matrix_name=string(names);
output=table(matrix_name,rows,columns,nonzero,is_sparse,sha256,path, ...
    'VariableNames',{'matrix_name','rows','columns','nnz','is_sparse','sha256','path'});
end

function output = make_artifact_hashes(runRoot,targets)
n=numel(targets); relative_path_value=strings(n,1); sha256=strings(n,1);
bytes=zeros(n,1); artifact_type=strings(n,1);
for k=1:n
    assert(isfile(targets(k)),"stageA2:artifacts:MissingWrittenTarget", ...
        "Expected A2 artifact was not written: %s",targets(k));
    relative_path_value(k)=relative_path(runRoot,targets(k));
    sha256(k)=compute_sha256_file(targets(k)); info=dir(targets(k)); bytes(k)=info.bytes;
    [~,~,extension]=fileparts(targets(k)); artifact_type(k)=erase(lower(string(extension)),".");
end
scope=repmat("numerical_export",n,1); status=repmat("PASS",n,1);
output=table(relative_path_value,sha256,bytes,artifact_type,scope,status, ...
    'VariableNames',{'relative_path','sha256','bytes','artifact_type','scope','status'});
end

function value = relative_path(root,pathValue)
root=string(char(java.io.File(char(root)).getCanonicalPath()));
pathValue=string(char(java.io.File(char(pathValue)).getCanonicalPath()));
prefix=root+filesep;
assert(startsWith(lower(pathValue),lower(prefix)), ...
    "stageA2:artifacts:PathOutsideRun","Artifact path is outside run root.");
value=replace(extractAfter(pathValue,strlength(prefix)),string(filesep),"/");
end

function value = pass_text(condition)
if condition, value="PASS"; else, value="FAIL"; end
end

function value = number_or_na(number)
if isfinite(number), value=sprintf("%d",number); else, value="NA"; end
end
