function outcome = finalize_stage_a4_3_run(projectRoot,runId,options)
%FINALIZE_STAGE_A4_3_RUN Deterministically terminalize one completed A4-3 run.
%
% This function never solves a Newton system, advances an iterate, changes
% CURRENT_STAGE.md, or enters Stage B.  It consumes only persisted run
% evidence.  The manifest must still be RUNNING and the numerical terminal
% state must already be CONVERGED, MAX_ITERATIONS, or NUMERICAL_FAILURE.
%
% By default the function performs the unique RUNNING -> PASS or
% RUNNING -> FAIL_RETRYABLE transition.  FinalizeManifest=false writes and
% freezes the derived acceptance/log/hash package but deliberately leaves
% the manifest RUNNING for an external review.  A later default call must
% reproduce that package byte-for-byte before terminalization.
%
% Required externally persisted finalization evidence:
%   reports/report_structure_validation.csv
%   reports/report_visual_qa.csv
%   reports/report_sha256.csv
%   tests/test_results.csv
%   tests/test_summary.json
%   tests/static_check_summary.csv
%   tests/a4_3_specialty/{suite_identity.json,test_inventory.csv,
%     test_results.csv,test_results.xml,matlab_test_console.log,
%     test_command.txt,test_summary.json,test_evidence_sha256.csv}

arguments
    projectRoot (1,1) string
    runId (1,1) string
    options.FinalizeManifest (1,1) logical = true
    options.ReportStructureValidationPath (1,1) string = ""
    options.ReportVisualValidationPath (1,1) string = ""
    options.ReportHashManifestPath (1,1) string = ""
    options.TestResultsPath (1,1) string = ""
    options.TestSummaryPath (1,1) string = ""
    options.StaticCheckSummaryPath (1,1) string = ""
    options.A43SpecialtyEvidenceDirectory (1,1) string = ""
end

projectRoot = canonical_directory(projectRoot, ...
    "stageA4:a43:finalizer:ProjectRoot");
assert(~isempty(regexp(char(runId), ...
    "^[A-Za-z0-9][A-Za-z0-9._-]*$","once")), ...
    "stageA4:a43:finalizer:RunId", ...
    "runId contains characters that are unsafe in a run path.");
runRoot = canonical_directory(fullfile(projectRoot,"runs",runId), ...
    "stageA4:a43:finalizer:RunRoot");
context = make_context(projectRoot,runRoot,runId);
manifest = read_json(context.run_manifest_path);
validate_running_manifest(manifest,context);

currentStagePath = fullfile(projectRoot,"CURRENT_STAGE.md");
currentStageHashBefore = compute_sha256_file(currentStagePath);
assert_current_stage_ready(currentStagePath);

paths = resolve_paths(context,options);
assert_all_paths_inside_current_run(paths,context.root);
require_finalization_inputs(paths);
[runResult,iterationEvidence,directionEvidence] = ...
    load_numeric_evidence(context,manifest);
physicalAudit = read_csv(paths.physical_audit);
validate_environment_and_inputs(context,paths,manifest);
historicalAudit = read_json(paths.historical_audit);
historicalPassed = scalar_logical_field( ...
    historicalAudit,"passed","historical_runs_audit.json");
assert(historicalPassed, ...
    "stageA4:a43:finalizer:HistoricalRunsChanged", ...
    "The persisted historical-run preservation audit did not pass.");

reportEvidence = load_report_evidence(context,paths);
acceptance = evaluate_stage_a4_3_acceptance( ...
    projectRoot,runResult,physicalAudit, ...
    "ReportEvidence",reportEvidence);
testAudit = validate_test_evidence( ...
    projectRoot,context,manifest,runResult,paths);
staticAudit = validate_static_evidence( ...
    projectRoot,context,manifest,runResult,paths.static_summary, ...
    paths.forbidden_code,paths.forbidden_execution, ...
    paths.dependency_closure,paths.code_analyzer_results, ...
    paths.git_diff_check,paths.effective_config,paths.stage_snapshot, ...
    paths.code_analyzer_scope,paths.code_analyzer_advisories);
identityAudit = validate_manifest_numeric_identity( ...
    manifest,runResult,iterationEvidence,directionEvidence);

numericalTerminal = string(runResult.run_terminal_state);
assert(ismember(numericalTerminal, ...
    ["CONVERGED","MAX_ITERATIONS","NUMERICAL_FAILURE"]), ...
    "stageA4:a43:finalizer:NumericalState", ...
    "Only a completed A4-3 numerical terminal state can be finalized.");
if numericalTerminal=="MAX_ITERATIONS"
    assert(runResult.iteration_count==100, ...
        "stageA4:a43:finalizer:MaxIterationIdentity", ...
        "MAX_ITERATIONS requires exactly 100 accepted updates.");
end

acceptancePassed = height(acceptance)==7 && ...
    all(string(acceptance.status)=="PASS");
candidatePass = numericalTerminal=="CONVERGED" && ...
    logical(runResult.convergence_achieved) && acceptancePassed && ...
    testAudit.passed && staticAudit.passed && identityAudit.passed && ...
    historicalPassed;
if candidatePass
    finalStatus = "PASS";
else
    finalStatus = "FAIL_RETRYABLE";
end
% Reaching 100 iterations is never success, even if a malformed caller
% supplied superficially small final metrics.
assert(numericalTerminal~="MAX_ITERATIONS" || finalStatus~="PASS", ...
    "stageA4:a43:finalizer:MaxIterationsCannotPass", ...
    "MAX_ITERATIONS must never be terminalized as PASS.");

[issues,decisions] = make_final_logs( ...
    context,runResult,acceptance,testAudit,staticAudit, ...
    identityAudit,historicalPassed,finalStatus);
preserve_pre_finalization_tables(context);
write_derived_table(context.acceptance_results_path,acceptance);
write_derived_table(context.issue_log_path,issues);
write_derived_table(context.decision_log_path,decisions);

evidencePath = fullfile(context.acceptance_dir,"evidence_hashes.csv");
[evidence,reusedEvidence] = materialize_complete_hash_inventory( ...
    context,manifest,evidencePath);
assert(height(evidence)>0 && all(string(evidence.status)=="PASS"), ...
    "stageA4:a43:finalizer:EvidenceInventory", ...
    "The complete A4-3 SHA256 inventory is not valid.");

assert_current_stage_ready(currentStagePath);
currentStageHashAfter = compute_sha256_file(currentStagePath);
assert(lower(string(currentStageHashAfter))== ...
    lower(string(currentStageHashBefore)), ...
    "stageA4:a43:finalizer:CurrentStageChanged", ...
    "CURRENT_STAGE.md changed during finalization.");

updates = make_manifest_updates( ...
    context,runResult,acceptance,issues,testAudit,staticAudit, ...
    reportEvidence,evidence,evidencePath,finalStatus, ...
    currentStageHashAfter,reusedEvidence);
if options.FinalizeManifest
    finalManifest = finalize_run_manifest(context,finalStatus,updates);
    assert_current_stage_ready(currentStagePath);
    assert(lower(string(compute_sha256_file(currentStagePath)))== ...
        lower(string(currentStageHashBefore)), ...
        "stageA4:a43:finalizer:CurrentStageChanged", ...
        "CURRENT_STAGE.md changed during manifest terminalization.");
else
    finalManifest = update_running_run_manifest(context,updates);
end

outcome = struct( ...
    "run_id",string(context.run_id), ...
    "run_root",string(context.root), ...
    "numerical_terminal_state",numericalTerminal, ...
    "candidate_terminal_status",finalStatus, ...
    "manifest_status",string(finalManifest.status), ...
    "manifest_finalized",logical(options.FinalizeManifest), ...
    "acceptance",acceptance, ...
    "issues",issues, ...
    "decisions",decisions, ...
    "test_audit",testAudit, ...
    "static_audit",staticAudit, ...
    "identity_audit",identityAudit, ...
    "evidence_hashes",evidence, ...
    "evidence_hashes_path",string(evidencePath), ...
    "evidence_inventory_reused",reusedEvidence, ...
    "current_stage","stage_A4 / READY", ...
    "stage_b_entered",false);
end

function context = make_context(projectRoot,runRoot,runId)
context = struct( ...
    "project_root",char(projectRoot), ...
    "root",char(runRoot), ...
    "run_id",char(runId), ...
    "stage_id","stage_A4", ...
    "run_manifest_path",char(fullfile(runRoot,"run_manifest.json")), ...
    "acceptance_dir",char(fullfile(runRoot,"acceptance")), ...
    "issues_dir",char(fullfile(runRoot,"issues")), ...
    "reports_dir",char(fullfile(runRoot,"reports")), ...
    "tests_dir",char(fullfile(runRoot,"tests")), ...
    "acceptance_results_path",char(fullfile(runRoot,"acceptance", ...
        "acceptance_results.csv")), ...
    "issue_log_path",char(fullfile(runRoot,"issues","issue_log.csv")), ...
    "decision_log_path",char(fullfile(runRoot,"issues","decision_log.csv")));
end

function paths = resolve_paths(context,options)
paths = struct( ...
    "environment",fullfile(context.root,"environment.csv"), ...
    "input_hashes",fullfile(context.root,"input_hashes.csv"), ...
    "effective_config",fullfile(context.root,"effective_config.yaml"), ...
    "git_state",fullfile(context.root,"git_state.txt"), ...
    "solver_result",fullfile(context.root,"a4_3_solver_result.mat"), ...
    "historical_before",fullfile(context.root,"historical_runs_before.csv"), ...
    "historical_audit",fullfile(context.root,"historical_runs_audit.json"), ...
    "iteration_summary",fullfile(context.root,"iterations", ...
        "iteration_summary.csv"), ...
    "direction_audit",fullfile(context.root,"iterations", ...
        "direction_audit.csv"), ...
    "checkpoint_manifest",fullfile(context.root,"checkpoints", ...
        "checkpoint_manifest.csv"), ...
    "matrix_manifest",fullfile(context.root,"matrices", ...
        "matrix_manifest.csv"), ...
    "physical_audit",fullfile(context.root,"acceptance", ...
        "physical_audit.csv"), ...
    "capacity_results",fullfile(context.root,"results", ...
        "capacity_results.csv"), ...
    "hourly_results",fullfile(context.root,"results", ...
        "hourly_dispatch_results.csv"), ...
    "forbidden_code",fullfile(context.root,"diagnostics", ...
        "forbidden_code_audit.csv"), ...
    "forbidden_execution",fullfile(context.root,"diagnostics", ...
        "forbidden_execution_audit.csv"), ...
    "dependency_closure",fullfile(context.root,"diagnostics", ...
        "dependency_closure_sha256.csv"), ...
    "model_report",fullfile(context.root,"reports", ...
        "阶段A4_模型与优化结果报告.docx"), ...
    "issue_report",fullfile(context.root,"reports", ...
        "阶段A4_问题修复与验收报告.docx"), ...
    "run_summary_report",fullfile(context.root,"reports", ...
        "运行_"+string(context.run_id)+"_结果摘要.docx"), ...
    "report_structure",choose_path( ...
        options.ReportStructureValidationPath,fullfile( ...
        context.root,"reports","report_structure_validation.csv")), ...
    "report_visual",choose_path( ...
        options.ReportVisualValidationPath,fullfile( ...
        context.root,"reports","report_visual_qa.csv")), ...
    "report_hashes",choose_path( ...
        options.ReportHashManifestPath,fullfile( ...
        context.root,"reports","report_sha256.csv")), ...
    "test_results",choose_path(options.TestResultsPath,fullfile( ...
        context.root,"tests","test_results.csv")), ...
    "test_summary",choose_path(options.TestSummaryPath,fullfile( ...
        context.root,"tests","test_summary.json")), ...
    "static_summary",choose_path(options.StaticCheckSummaryPath, ...
        fullfile(context.root,"tests","static_check_summary.csv")), ...
    "code_analyzer_results",fullfile(context.root,"tests", ...
        "code_analyzer_results.csv"), ...
    "code_analyzer_scope",fullfile(context.root,"tests", ...
        "code_analyzer_scope.csv"), ...
    "code_analyzer_advisories",fullfile(context.root,"tests", ...
        "code_analyzer_advisories.csv"), ...
    "git_diff_check",fullfile(context.root,"tests", ...
        "git_diff_check.txt"), ...
    "stage_snapshot",fullfile(context.root,"tests", ...
        "CURRENT_STAGE.md"));
specialtyDirectory = choose_path(options.A43SpecialtyEvidenceDirectory, ...
    fullfile(context.root,"tests","a4_3_specialty"));
paths.a43_suite_identity = fullfile(specialtyDirectory, ...
    "suite_identity.json");
paths.a43_inventory = fullfile(specialtyDirectory, ...
    "test_inventory.csv");
paths.a43_results = fullfile(specialtyDirectory,"test_results.csv");
paths.a43_junit = fullfile(specialtyDirectory,"test_results.xml");
paths.a43_console = fullfile(specialtyDirectory, ...
    "matlab_test_console.log");
paths.a43_command = fullfile(specialtyDirectory,"test_command.txt");
paths.a43_summary = fullfile(specialtyDirectory,"test_summary.json");
paths.a43_hashes = fullfile(specialtyDirectory, ...
    "test_evidence_sha256.csv");
end

function value = choose_path(configured,defaultValue)
if strlength(strip(configured))==0
    value = string(defaultValue);
else
    value = string(configured);
end
end

function require_finalization_inputs(paths)
names = string(fieldnames(paths));
for k = 1:numel(names)
    value = string(paths.(names(k)));
    assert(isfile(value), ...
        "stageA4:a43:finalizer:EvidenceMissing", ...
        "Required A4-3 finalization evidence is missing: %s",value);
end
end

function validate_running_manifest(manifest,context)
required = ["run_id","stage_id","status","started_at","git_commit", ...
    "input_hashes","a4_3_run_terminal_state", ...
    "convergence_achieved","historical_runs_unchanged", ...
    "stage_b_entered"];
assert(all(isfield(manifest,cellstr(required))), ...
    "stageA4:a43:finalizer:ManifestSchema", ...
    "run_manifest.json is missing required A4-3 fields.");
assert(string(manifest.run_id)==string(context.run_id) && ...
    string(manifest.stage_id)=="stage_A4", ...
    "stageA4:a43:finalizer:ManifestIdentity", ...
    "Run context and manifest identity differ.");
assert(string(manifest.status)=="RUNNING", ...
    "stageA4:a43:finalizer:ManifestAlreadyFinal", ...
    "Only a RUNNING A4-3 manifest can be finalized.");
assert(~logical(manifest.stage_b_entered), ...
    "stageA4:a43:finalizer:StageBoundary", ...
    "The A4-3 run must not enter Stage B.");
assert(logical(manifest.historical_runs_unchanged), ...
    "stageA4:a43:finalizer:HistoricalManifest", ...
    "The manifest does not record an unchanged historical-run boundary.");
end

function [runResult,iterationEvidence,directionEvidence] = ...
        load_numeric_evidence(context,manifest)
payload = load(fullfile(context.root,"a4_3_solver_result.mat"));
assert(isfield(payload,"summary") && isstruct(payload.summary) && ...
    isscalar(payload.summary), ...
    "stageA4:a43:finalizer:SolverResult", ...
    "a4_3_solver_result.mat does not contain scalar summary evidence.");
runResult = payload.summary;
required = ["run_terminal_state","convergence_achieved", ...
    "iteration_count","final_metrics","direction_audit", ...
    "iteration_summary","execution_audit","full_kkt_audit_count"];
assert(all(isfield(runResult,cellstr(required))), ...
    "stageA4:a43:finalizer:SolverResult", ...
    "The persisted solver summary is incomplete.");
iterationEvidence = read_csv(fullfile(context.root,"iterations", ...
    "iteration_summary.csv"));
directionEvidence = read_csv(fullfile(context.root,"iterations", ...
    "direction_audit.csv"));
assert(tables_equivalent(runResult.iteration_summary,iterationEvidence), ...
    "stageA4:a43:finalizer:IterationMismatch", ...
    "Persisted iteration CSV differs from the solver MAT summary.");
assert(tables_equivalent(runResult.direction_audit,directionEvidence), ...
    "stageA4:a43:finalizer:DirectionMismatch", ...
    "Persisted direction CSV differs from the solver MAT summary.");
assert(string(manifest.a4_3_run_terminal_state)== ...
    string(runResult.run_terminal_state) && ...
    logical(manifest.convergence_achieved)== ...
    logical(runResult.convergence_achieved), ...
    "stageA4:a43:finalizer:ManifestNumericalMismatch", ...
    "Manifest and solver MAT numerical terminal facts differ.");
end

function reportEvidence = load_report_evidence(context,paths)
reportPaths = struct( ...
    "model_report",char(paths.model_report), ...
    "issue_report",char(paths.issue_report), ...
    "run_summary",char(paths.run_summary_report));
[packagePassed,recomputed] = validate_stage_a4_report_set( ...
    reportPaths,string(context.run_id));
persistedStructure = read_csv(paths.report_structure);
assert(structure_audits_equivalent(persistedStructure,recomputed), ...
    "stageA4:a43:finalizer:ReportStructureMismatch", ...
    "Persisted report structure QA differs from independent validation.");

visual = read_csv(paths.report_visual);
validate_visual_inventory(context,reportPaths,visual);
reportHashes = read_csv(paths.report_hashes);
validate_report_hashes(context,reportPaths,reportHashes);
% A structurally invalid package is a truthful FAIL_RETRYABLE fact rather
% than a reason to fabricate PASS.  Hash/path inconsistency above remains
% a hard evidence error and leaves the manifest RUNNING.
if ~packagePassed
    recomputed.status(:) = "FAIL";
end
reportEvidence = struct( ...
    "run_root",string(context.root), ...
    "report_paths",reportPaths, ...
    "structure_validation",recomputed, ...
    "visual_validation",visual, ...
    "hash_manifest",reportHashes, ...
    "package_passed",packagePassed);
end

function passed = structure_audits_equivalent(left,right)
passed = false;
required = ["report_key","path","sha256","status"];
if ~all(ismember(required,string(left.Properties.VariableNames))) || ...
        height(left)~=3 || height(right)~=3
    return
end
[~,leftOrder] = sort(string(left.report_key));
[~,rightOrder] = sort(string(right.report_key));
left = left(leftOrder,:); right = right(rightOrder,:);
if ~isequal(string(left.report_key),string(right.report_key))
    return
end
for k = 1:height(left)
    if canonical_file(left.path(k), ...
            "stageA4:a43:finalizer:ReportStructurePath")~= ...
            canonical_file(right.path(k), ...
            "stageA4:a43:finalizer:ReportStructurePath") || ...
            lower(string(left.sha256(k)))~=lower(string(right.sha256(k))) || ...
            string(left.status(k))~=string(right.status(k))
        return
    end
end
passed = true;
end

function validate_visual_inventory(context,reportPaths,visual)
required = ["report_path","page_number","page_count","image_path", ...
    "image_sha256","status"];
assert(all(ismember(required,string(visual.Properties.VariableNames))) && ...
    height(visual)>=3, ...
    "stageA4:a43:finalizer:VisualSchema", ...
    "Report visual QA evidence has an invalid schema.");
expected = string(struct2cell(reportPaths));
observedReports = strings(height(visual),1);
for row = 1:height(visual)
    observedReports(row) = canonical_file(visual.report_path(row), ...
        "stageA4:a43:finalizer:VisualReportPath");
    imagePath = canonical_file(visual.image_path(row), ...
        "stageA4:a43:finalizer:VisualImagePath");
    assert(path_is_inside(imagePath,string(context.root)), ...
        "stageA4:a43:finalizer:VisualImageScope", ...
        "Rendered page evidence must be inside the current run.");
    assert(lower(string(compute_sha256_file(imagePath)))== ...
        lower(string(visual.image_sha256(row))), ...
        "stageA4:a43:finalizer:VisualImageHash", ...
        "Rendered page image hash mismatch: %s",imagePath);
    try
        information = imfinfo(imagePath);
    catch exception
        error("stageA4:a43:finalizer:VisualImageFormat", ...
            "Rendered page evidence is not a readable image: %s (%s)", ...
            imagePath,exception.message);
    end
    assert(~isempty(information), ...
        "stageA4:a43:finalizer:VisualImageFormat", ...
        "Rendered page evidence is empty: %s",imagePath);
end
expected = arrayfun(@(value)canonical_file(value, ...
    "stageA4:a43:finalizer:VisualReportPath"),expected);
assert(isequal(sort(unique(observedReports)),sort(expected)), ...
    "stageA4:a43:finalizer:VisualReportSet", ...
    "Visual QA must cover exactly the three required reports.");
for reportPath = expected.'
    rows = visual(observedReports==reportPath,:);
    pageCount = double(rows.page_count);
    pageNumber = double(rows.page_number);
    assert(~isempty(rows) && isscalar(unique(pageCount)) && ...
        unique(pageCount)==height(rows) && ...
        isequal(sort(pageNumber),(1:height(rows)).'), ...
        "stageA4:a43:finalizer:VisualPages", ...
        "Visual QA pages are incomplete for %s.",reportPath);
end
end

function validate_report_hashes(context,reportPaths,hashes)
required = ["relative_path","sha256","status"];
assert(all(ismember(required,string(hashes.Properties.VariableNames))) && ...
    height(hashes)==3 && ...
    numel(unique(string(hashes.relative_path)))==3, ...
    "stageA4:a43:finalizer:ReportHashSchema", ...
    "Report SHA256 manifest must contain exactly three unique rows.");
expected = string(struct2cell(reportPaths));
for pathValue = expected.'
    canonical = canonical_file(pathValue, ...
        "stageA4:a43:finalizer:ReportHashPath");
    assert(path_is_inside(canonical,string(context.root)), ...
        "stageA4:a43:finalizer:ReportScope", ...
        "A report is outside the current run.");
    relative = relative_path(canonical,string(context.root));
    row = hashes(string(hashes.relative_path)==relative,:);
    assert(height(row)==1 && ...
        lower(string(row.sha256))== ...
        lower(string(compute_sha256_file(canonical))), ...
        "stageA4:a43:finalizer:ReportHash", ...
        "Report SHA256 evidence is inconsistent: %s",canonical);
end
end

function audit = validate_test_evidence( ...
        projectRoot,context,manifest,runResult,paths)
results = read_csv(paths.test_results);
summary = read_json(paths.test_summary);
requiredColumns = ["suite_label","test_name","passed","failed","incomplete", ...
    "duration_seconds","details"];
assert(all(ismember(requiredColumns, ...
    string(results.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:TestSchema", ...
    "tests/test_results.csv has an invalid schema.");
requiredSummary = ["test_total","test_passed","test_failed", ...
    "test_incomplete"];
assert(all(isfield(summary,cellstr(requiredSummary))), ...
    "stageA4:a43:finalizer:TestSummary", ...
    "tests/test_summary.json is incomplete.");
passed = logical_column(results.passed);
failed = logical_column(results.failed);
incomplete = logical_column(results.incomplete);
count = height(results);
suiteLabels = string(results.suite_label);
testNames = string(results.test_name);
pairIdentity = suiteLabels+"|"+testNames;
identityPass = count>0 && all(strlength(suiteLabels)>0) && ...
    all(strlength(testNames)>0) && ...
    numel(unique(pairIdentity))==count;
countPass = double(summary.test_total)==count && ...
    double(summary.test_passed)==nnz(passed) && ...
    double(summary.test_failed)==nnz(failed) && ...
    double(summary.test_incomplete)==nnz(incomplete);
executionComplete = true;
if isfield(summary,"execution_status")
    executionComplete = string(summary.execution_status)=="COMPLETE";
end
aggregateOutcomePass = identityPass && countPass && executionComplete && ...
    all(passed) && ~any(failed) && ~any(incomplete);
audit = struct( ...
    "aggregate_passed",aggregateOutcomePass, ...
    "identity_passed",identityPass, ...
    "summary_matches_results",countPass, ...
    "execution_complete",executionComplete, ...
    "test_total",count, ...
    "test_passed",nnz(passed), ...
    "test_failed",nnz(failed), ...
    "test_incomplete",nnz(incomplete), ...
    "results_path",string(paths.test_results), ...
    "summary_path",string(paths.test_summary));

expectedPath = fullfile(projectRoot,"tests", ...
    "stage_A4_3_expected_test_inventory.csv");
expected = read_csv(expectedPath);
inventory = read_csv(paths.a43_inventory);
requiredInventory = ["test_order","test_name","source_file"];
assert(all(ismember(requiredInventory, ...
    string(expected.Properties.VariableNames))) && ...
    all(ismember(requiredInventory, ...
    string(inventory.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:A43InventorySchema", ...
    "The A4-3 specialty inventory schema is invalid.");
expected = expected(:,cellstr(requiredInventory));
inventory = inventory(:,cellstr(requiredInventory));
inventoryIdentity = height(expected)==27 && ...
    tables_equivalent(expected,inventory) && ...
    isequal(double(inventory.test_order),(1:27).') && ...
    numel(unique(string(inventory.test_name)))==27;

specialtyResults = read_csv(paths.a43_results);
specialtySummary = read_json(paths.a43_summary);
requiredResultColumns = ["test_name","passed","failed","incomplete", ...
    "duration_seconds","details"];
assert(all(ismember(requiredResultColumns, ...
    string(specialtyResults.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:A43ResultSchema", ...
    "The A4-3 specialty result schema is invalid.");
specialtyPassed = logical_column(specialtyResults.passed);
specialtyFailed = logical_column(specialtyResults.failed);
specialtyIncomplete = logical_column(specialtyResults.incomplete);
summaryFields = ["execution_status","suite_label","test_total", ...
    "test_passed","test_failed","test_incomplete", ...
    "test_names_unique","expected_inventory_sha256"];
assert(all(isfield(specialtySummary,cellstr(summaryFields))), ...
    "stageA4:a43:finalizer:A43SummarySchema", ...
    "The A4-3 specialty summary is missing identity fields.");
expectedSha = lower(string(compute_sha256_file(expectedPath)));
resultIdentity = inventoryIdentity && ...
    height(specialtyResults)==27 && ...
    isequal(string(specialtyResults.test_name), ...
    string(inventory.test_name)) && ...
    numel(unique(string(specialtyResults.test_name)))==27;
specialtySummaryPass = ...
    string(specialtySummary.execution_status)=="COMPLETE" && ...
    string(specialtySummary.suite_label)=="stage_A4_3" && ...
    double(specialtySummary.test_total)==27 && ...
    double(specialtySummary.test_passed)==27 && ...
    double(specialtySummary.test_failed)==0 && ...
    double(specialtySummary.test_incomplete)==0 && ...
    logical(specialtySummary.test_names_unique) && ...
    lower(string(specialtySummary.expected_inventory_sha256))== ...
    expectedSha;
specialtyOutcomePass = all(specialtyPassed) && ...
    ~any(specialtyFailed) && ~any(specialtyIncomplete);

commandText = strip(string(fileread(paths.a43_command)));
commandPass = strlength(commandText)>0 && ...
    contains(commandText,"run_stage_A4_3_tests") && ...
    contains(commandText,string(context.run_id)) && ...
    contains(replace(commandText,"\","/"), ...
    "tests/a4_3_specialty");
junitPass = validate_junit(paths.a43_junit,27);
specialtyHashPass = validate_fixed_test_hash_manifest( ...
    paths.a43_hashes,fileparts(paths.a43_hashes));
suiteIdentity = read_json(paths.a43_suite_identity);
identityFields = ["run_id","stage_id","git_commit","suite_label", ...
    "expected_inventory_sha256","effective_config_sha256", ...
    "input_hashes_csv_sha256","test_command_sha256"];
assert(all(isfield(suiteIdentity,cellstr(identityFields))), ...
    "stageA4:a43:finalizer:A43SuiteIdentitySchema", ...
    "A4-3 specialty suite_identity.json is incomplete.");
suiteIdentityPass = ...
    string(suiteIdentity.run_id)==string(context.run_id) && ...
    string(suiteIdentity.stage_id)=="stage_A4" && ...
    lower(string(suiteIdentity.git_commit))== ...
        lower(string(manifest.git_commit)) && ...
    string(suiteIdentity.suite_label)=="stage_A4_3" && ...
    lower(string(suiteIdentity.expected_inventory_sha256))==expectedSha && ...
    lower(string(suiteIdentity.effective_config_sha256))== ...
        lower(string(compute_sha256_file(paths.effective_config))) && ...
    lower(string(suiteIdentity.input_hashes_csv_sha256))== ...
        lower(string(compute_sha256_file(paths.input_hashes))) && ...
    lower(string(suiteIdentity.test_command_sha256))== ...
        lower(string(compute_sha256_file(paths.a43_command)));
specialtyGate = inventoryIdentity && resultIdentity && ...
    specialtySummaryPass && specialtyOutcomePass && commandPass && ...
    junitPass && specialtyHashPass && suiteIdentityPass;
numericalTerminal = string(runResult.run_terminal_state);
if numericalTerminal=="CONVERGED"
    expectedSuites = [ ...
        "stage_A4_3","27"
        "stage_A4_RNS_1","17"
        "stage_A4_2D_2A_R1","18"
        "stage_A4_regression_195","195"];
    aggregateCampaignPass = ...
        validate_converged_aggregate_campaign( ...
        projectRoot,results,summary,expectedSuites,expected);
else
    aggregateCampaignPass = ...
        validate_nonconverged_aggregate_campaign(results,summary);
end
audit.passed = aggregateOutcomePass && specialtyGate && ...
    aggregateCampaignPass;
audit.aggregate_campaign_passed = aggregateCampaignPass;
audit.aggregate_expected_total = ...
    double(numericalTerminal=="CONVERGED")*257;
audit.a43_specialty_passed = specialtyGate;
audit.a43_inventory_identity_passed = inventoryIdentity;
audit.a43_result_identity_passed = resultIdentity;
audit.a43_summary_passed = specialtySummaryPass;
audit.a43_command_passed = commandPass;
audit.a43_junit_passed = junitPass;
audit.a43_hash_manifest_passed = specialtyHashPass;
audit.a43_suite_identity_passed = suiteIdentityPass;
audit.a43_expected_inventory_sha256 = expectedSha;
end

function passed = validate_converged_aggregate_campaign( ...
        projectRoot,results,summary,expectedSuites,a43Expected)
passed = false;
requiredSummary = ["execution_status","campaign_mode", ...
    "stage_pass_eligible","test_total","test_passed","test_failed", ...
    "test_incomplete","test_names_unique_within_suite", ...
    "suite_label_test_name_unique","suite_counts"];
if ~all(isfield(summary,cellstr(requiredSummary))) || ...
        string(summary.execution_status)~="COMPLETE" || ...
        string(summary.campaign_mode)~="converged_full_validation" || ...
        ~logical(summary.stage_pass_eligible) || ...
        double(summary.test_total)~=257 || ...
        double(summary.test_passed)~=257 || ...
        double(summary.test_failed)~=0 || ...
        double(summary.test_incomplete)~=0 || ...
        ~logical(summary.test_names_unique_within_suite) || ...
        ~logical(summary.suite_label_test_name_unique)
    return
end
labels = string(results.suite_label);
if height(results)~=257 || ...
        ~isequal(unique(labels,"stable"),expectedSuites(:,1))
    return
end
for row = 1:size(expectedSuites,1)
    label = expectedSuites(row,1);
    expectedCount = str2double(expectedSuites(row,2));
    subset = results(labels==label,:);
    if height(subset)~=expectedCount || ...
            numel(unique(string(subset.test_name)))~=expectedCount
        return
    end
end
if ~aggregate_suite_names_match_inventory(results, ...
        "stage_A4_3",a43Expected) || ...
        ~aggregate_suite_names_match_inventory(results, ...
        "stage_A4_RNS_1",read_csv(fullfile(projectRoot,"tests", ...
        "stage_A4_RNS_1_expected_test_inventory.csv"))) || ...
        ~aggregate_suite_names_match_inventory(results, ...
        "stage_A4_2D_2A_R1",read_csv(fullfile(projectRoot,"tests", ...
        "stage_A4_2D_2A_R1_expected_test_inventory.csv")))
    return
end
passed = validate_suite_count_summary(summary.suite_counts, ...
    expectedSuites);
end

function passed = validate_nonconverged_aggregate_campaign(results,summary)
passed = false;
requiredSummary = ["execution_status","campaign_mode", ...
    "stage_pass_eligible","test_total","test_passed","test_failed", ...
    "test_incomplete","test_names_unique_within_suite", ...
    "suite_label_test_name_unique","suite_counts"];
if ~all(isfield(summary,cellstr(requiredSummary))) || ...
        string(summary.execution_status)~="COMPLETE" || ...
        string(summary.campaign_mode)~="nonconverged_direct_validation" || ...
        logical(summary.stage_pass_eligible) || ...
        ~logical(summary.test_names_unique_within_suite) || ...
        ~logical(summary.suite_label_test_name_unique)
    return
end
labels = unique(string(results.suite_label),"stable");
% A failed numerical candidate runs only the direct A4-3/finalizer checks;
% it must never masquerade as the 257-test Stage-PASS campaign.
expected = ["stage_A4_3","27";"stage_A4_3_finalizer","5"];
if ~isequal(labels,expected(:,1)) || height(results)~=32
    return
end
forbidden = ["stage_A4_RNS_1","stage_A4_2D_2A_R1", ...
    "stage_A4_regression_195"];
if any(ismember(labels,forbidden))
    return
end
for row = 1:numel(labels)
    if nnz(string(results.suite_label)==labels(row))~= ...
            str2double(expected(row,2))
        return
    end
end
passed = validate_suite_count_summary(summary.suite_counts,expected);
end

function passed = aggregate_suite_names_match_inventory( ...
        results,suiteLabel,inventory)
required = "test_name";
passed = all(ismember(required,string(inventory.Properties.VariableNames)));
if ~passed
    return
end
observed = string(results.test_name( ...
    string(results.suite_label)==suiteLabel));
expected = string(inventory.test_name);
passed = isequal(observed,expected);
end

function passed = validate_suite_count_summary(suiteCounts,expected)
passed = false;
if ~isstruct(suiteCounts) || numel(suiteCounts)~=size(expected,1)
    return
end
required = ["suite_label","test_total","test_passed", ...
    "test_failed","test_incomplete","duration_seconds"];
if ~all(isfield(suiteCounts,cellstr(required)))
    return
end
for row = 1:size(expected,1)
    count = str2double(expected(row,2));
    item = suiteCounts(row);
    if string(item.suite_label)~=expected(row,1) || ...
            double(item.test_total)~=count || ...
            double(item.test_passed)~=count || ...
            double(item.test_failed)~=0 || ...
            double(item.test_incomplete)~=0 || ...
            ~isscalar(item.duration_seconds) || ...
            ~isfinite(double(item.duration_seconds)) || ...
            double(item.duration_seconds)<0
        return
    end
end
passed = true;
end

function passed = validate_junit(pathValue,expectedCount)
passed = false;
try
    document = xmlread(pathValue);
    passed = double(document.getElementsByTagName( ...
        "testcase").getLength())==expectedCount;
catch
end
end

function passed = validate_fixed_test_hash_manifest(pathValue,directory)
hashes = read_csv(pathValue);
required = ["names","sha256","bytes","status"];
expectedNames = ["test_inventory.csv";"test_results.csv"; ...
    "test_results.xml";"matlab_test_console.log"; ...
    "test_command.txt";"test_summary.json"];
passed = all(ismember(required,string(hashes.Properties.VariableNames))) && ...
    height(hashes)==6 && ...
    isequal(string(hashes.names),expectedNames) && ...
    all(string(hashes.status)=="PASS");
if ~passed
    return
end
for row = 1:height(hashes)
    target = fullfile(directory,string(hashes.names(row)));
    info = dir(target);
    if ~isfile(target) || ~isscalar(info) || ...
            double(hashes.bytes(row))~=info.bytes || ...
            lower(string(hashes.sha256(row)))~= ...
            lower(string(compute_sha256_file(target)))
        passed = false;
        return
    end
end
end

function audit = validate_static_evidence( ...
        projectRoot,context,manifest,runResult,summaryPath,forbiddenCodePath, ...
        forbiddenExecutionPath,dependencyPath,codeAnalyzerPath, ...
        gitDiffPath,effectiveConfigPath,stageSnapshotPath, ...
        analyzerScopePath,analyzerAdvisoriesPath)
summary = read_csv(summaryPath);
requiredColumns = ["check_id","status","actual_value", ...
    "threshold","evidence_path","details","run_id","git_commit"];
assert(all(ismember(requiredColumns, ...
    string(summary.Properties.VariableNames))) && ...
    numel(unique(string(summary.check_id)))==height(summary), ...
    "stageA4:a43:finalizer:StaticSchema", ...
    "tests/static_check_summary.csv has an invalid schema.");
requiredIds = [ ...
    "A43-STATIC-CODE-ANALYZER"
    "A43-STATIC-FORBIDDEN-CODE"
    "A43-STATIC-FORBIDDEN-EXECUTION"
    "A43-STATIC-GIT-DIFF-CHECK"
    "A43-STATIC-STAGE-GOVERNANCE"];
assert(isequal(string(summary.check_id),requiredIds), ...
    "stageA4:a43:finalizer:StaticIdentity", ...
    "Static evidence must contain exactly five ordered A4-3 checks.");
assert_run_evidence_references( ...
    context.root,string(summary.evidence_path), ...
    "stageA4:a43:finalizer:StaticEvidenceScope");
stageSnapshotPass = lower(string(compute_sha256_file(stageSnapshotPath)))== ...
    lower(string(compute_sha256_file(fullfile(projectRoot,"CURRENT_STAGE.md")))) && ...
    contains(string(fileread(stageSnapshotPath)),"`stage_id`: `stage_A4`") && ...
    contains(string(fileread(stageSnapshotPath)),"`status`: `READY`");

forbiddenCode = read_csv(forbiddenCodePath);
forbiddenExecution = read_csv(forbiddenExecutionPath);
dependency = read_csv(dependencyPath);
assert(all(ismember("status", ...
    string(forbiddenCode.Properties.VariableNames))) && ...
    all(ismember("status", ...
    string(forbiddenExecution.Properties.VariableNames))) && ...
    all(ismember(["relative_path","sha256","bytes","status"], ...
    string(dependency.Properties.VariableNames))) && ...
    ~isempty(forbiddenCode) && ~isempty(forbiddenExecution) && ...
    ~isempty(dependency), ...
    "stageA4:a43:finalizer:StaticDependencySchema", ...
    "Persisted forbidden/dependency evidence is incomplete.");
expectedCodeIds = [ ...
    "A43-NO-INV-PINV-LSQMINNORM"
    "A43-NO-PARALLEL"
    "A43-NO-PREDICTOR-CORRECTOR"
    "A43-NO-LINE-SEARCH"
    "A43-NO-REGULARIZATION"
    "A43-NO-AUTOMATIC-SYMMETRIZATION"
    "A43-NO-NEGATIVE-MATRIX-POWER"
    "A43-NO-RANDOM"
    "A43-NO-DYNAMIC-INVOCATION"
    "A43-NO-LARGE-FULL-CONVERSION"
    "A43-NO-EXTERNAL-OPTIMIZER"
    "A43-INDEPENDENT-STEP-ONLY"
    "A43-STABLE-V2-EXPLICIT"
    "A43-RECURSIVE-CLOSURE-NO-DIRECT-SOLVER"
    "A43-FROZEN-RUNTIME-CONFIG"
    "A43-NO-STAGE-B-DEPENDENCY"];
expectedRuntimeIds = [ ...
    "A43-RUNTIME-NO-COMMON-MIN"
    "A43-RUNTIME-FIXED-SIGMA"
    "A43-RUNTIME-NO-PREDICTOR-CORRECTOR"
    "A43-RUNTIME-NO-LINE-SEARCH"
    "A43-RUNTIME-NO-REGULARIZATION"
    "A43-RUNTIME-NO-AUTOMATIC-SYMMETRIZATION"
    "A43-RUNTIME-NO-PARALLEL"
    "A43-RUNTIME-NO-FULL-DIRECTION-FALLBACK"];
assert(all(ismember("check_id", ...
    string(forbiddenCode.Properties.VariableNames))) && ...
    all(ismember("check_id", ...
    string(forbiddenExecution.Properties.VariableNames))) && ...
    isequal(string(forbiddenCode.check_id),expectedCodeIds) && ...
    isequal(string(forbiddenExecution.check_id),expectedRuntimeIds), ...
    "stageA4:a43:finalizer:StaticAuditIdentity", ...
    "Forbidden code/runtime audit identity or ordering changed.");

originalPath = path;
pathGuard = onCleanup(@()path(originalPath));
addpath(char(projectRoot),"-begin");
addpath(genpath(fullfile(projectRoot,"src")),"-begin");
config = load_stage_a4_3_configuration(projectRoot);
configuredSource = fullfile(projectRoot,"config","stage_A4_3.yaml");
effectiveConfigIdentity = isfile(configuredSource) && ...
    lower(string(compute_sha256_file(configuredSource)))== ...
    lower(string(compute_sha256_file(effectiveConfigPath)));
[rebuiltCode,rebuiltDependency] = ...
    scan_stage_a4_3_forbidden_code(projectRoot,config);
rebuiltExecution = audit_stage_a4_3_forbidden_execution( ...
    runResult,config,rebuiltCode,rebuiltDependency);
codeIdentity = tables_equivalent(forbiddenCode,rebuiltCode);
executionIdentity = tables_equivalent( ...
    forbiddenExecution,rebuiltExecution);
dependencyIdentity = tables_equivalent(dependency,rebuiltDependency);
clear pathGuard

closureIdentity = dependencyIdentity;
scopeEvidence = read_csv(analyzerScopePath);
advisoryEvidence = read_csv(analyzerAdvisoriesPath);
rebuiltScope = get_stage_a4_3_code_analyzer_scope( ...
    projectRoot,rebuiltDependency);
scopeIdentity = tables_equivalent(scopeEvidence,rebuiltScope);
scopeRelative = string(rebuiltScope.relative_path);
codeAnalyzerRebuiltCount = 0;
advisoryCountRebuilt = 0;
nonblockingAnalyzerIds = ["MSNU","SPRIX"];
for row = 1:height(rebuiltDependency)
    source = fullfile(projectRoot,replace( ...
        string(rebuiltDependency.relative_path(row)),"/",filesep));
    if ~isfile(source) || ...
            lower(string(compute_sha256_file(source)))~= ...
            lower(string(rebuiltDependency.sha256(row)))
        closureIdentity = false;
        break
    end
    if endsWith(source,".m","IgnoreCase",true) && ...
            ismember(string(rebuiltDependency.relative_path(row)), ...
            scopeRelative)
        findings = checkcode(source,"-id");
        identifiers = strings(numel(findings),1);
        for j = 1:numel(findings)
            identifiers(j) = string(findings(j).id);
        end
        codeAnalyzerRebuiltCount = codeAnalyzerRebuiltCount+ ...
            nnz(~ismember(identifiers,nonblockingAnalyzerIds));
        advisoryCountRebuilt = advisoryCountRebuilt+ ...
            nnz(ismember(identifiers,nonblockingAnalyzerIds));
    elseif endsWith(source,".m","IgnoreCase",true)
        findings = checkcode(source,"-id");
        advisoryCountRebuilt = advisoryCountRebuilt+numel(findings);
    end
end
allRebuiltFindings = run_code_analyzer_records( ...
    projectRoot,rebuiltDependency);
advisoryMask = ~ismember(string(allRebuiltFindings.file),scopeRelative) | ...
    ismember(string(allRebuiltFindings.identifier), ...
    nonblockingAnalyzerIds);
rebuiltAdvisories = allRebuiltFindings(advisoryMask,:);
advisoryIdentity = advisory_tables_equivalent( ...
    advisoryEvidence,rebuiltAdvisories);
codeAnalyzerEvidence = read_csv(codeAnalyzerPath);
requiredAnalyzerColumns = ["file","line","column","identifier","message"];
assert(all(ismember(requiredAnalyzerColumns, ...
    string(codeAnalyzerEvidence.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:CodeAnalyzerSchema", ...
    "Persisted Code Analyzer evidence has an invalid schema.");
requiredScopeColumns = ["relative_path","scope_reason","sha256", ...
    "bytes","status"];
requiredAdvisoryColumns = ["file","line","column","identifier","message"];
assert(all(ismember(requiredScopeColumns, ...
    string(scopeEvidence.Properties.VariableNames))) && ...
    all(ismember(requiredAdvisoryColumns, ...
    string(advisoryEvidence.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:CodeAnalyzerScopeSchema", ...
    "Code Analyzer scope/advisory evidence has an invalid schema.");
codeAnalyzerPass = isempty(codeAnalyzerEvidence) && ...
    codeAnalyzerRebuiltCount==0 && scopeIdentity && ...
    all(string(scopeEvidence.status)=="PASS") && ...
    advisoryIdentity && height(advisoryEvidence)==advisoryCountRebuilt;
gitDiffText = strip(string(fileread(gitDiffPath)));
gitDiffPass = ~isempty(regexp(char(gitDiffText), ...
    "(^|[\r\n])exit(_code)?=0([\r\n]|$)","once"));
rebuiltCodePass = all(string(rebuiltCode.status)=="PASS");
rebuiltExecutionPass = all(string(rebuiltExecution.status)=="PASS");
diagnosticPass = codeIdentity && executionIdentity && ...
    dependencyIdentity && effectiveConfigIdentity && ...
    rebuiltCodePass && rebuiltExecutionPass && ...
    all(string(rebuiltDependency.status)=="PASS") && closureIdentity && ...
    codeAnalyzerPass && gitDiffPass && stageSnapshotPass;
summaryPass = all(string(summary.status)=="PASS");
summaryIdentity = all(string(summary.run_id)==string(context.run_id)) && ...
    all(lower(string(summary.git_commit))== ...
    lower(string(manifest.git_commit)));
audit = struct( ...
    "passed",summaryPass&&diagnosticPass&&summaryIdentity, ...
    "summary_passed",summaryPass, ...
    "summary_identity_passed",summaryIdentity, ...
    "forbidden_code_passed",codeIdentity&&rebuiltCodePass, ...
    "forbidden_execution_passed", ...
        executionIdentity&&rebuiltExecutionPass, ...
    "dependency_closure_passed", ...
        dependencyIdentity&&all(string(rebuiltDependency.status)=="PASS")&& ...
        closureIdentity, ...
    "effective_config_identity_passed",effectiveConfigIdentity, ...
    "forbidden_code_rebuilt_identity_passed",codeIdentity, ...
    "forbidden_execution_rebuilt_identity_passed",executionIdentity, ...
    "code_analyzer_passed",codeAnalyzerPass, ...
    "code_analyzer_rebuilt_finding_count",codeAnalyzerRebuiltCount, ...
    "code_analyzer_scope_identity_passed",scopeIdentity, ...
    "code_analyzer_advisory_identity_passed",advisoryIdentity, ...
    "code_analyzer_advisory_count",advisoryCountRebuilt, ...
    "git_diff_check_passed",gitDiffPass, ...
    "stage_governance_passed",stageSnapshotPass, ...
    "static_check_count",height(summary), ...
    "dependency_file_count",height(dependency), ...
    "summary_path",string(summaryPath));
end

function audit = validate_manifest_numeric_identity( ...
        manifest,result,iterations,directions)
count = double(result.iteration_count);
sequencePass = height(iterations)==count && ...
    height(directions)==count;
if count>0
    sequencePass = sequencePass && ...
        isequal(double(iterations.iteration),(1:count).') && ...
        isequal(double(directions.iteration),(1:count).');
end
manifestCountPass = true;
fields = ["newton_direction_count","accepted_state_update_count", ...
    "full_kkt_audit_count"];
for field = fields
    if ~isfield(manifest,field) || double(manifest.(field))~=count
        manifestCountPass = false;
    end
end
gitPass = strlength(string(manifest.git_commit))==40 && ...
    ~isempty(regexp(char(manifest.git_commit),"^[0-9a-fA-F]{40}$","once"));
coordinatePass = isfield(manifest,"convergence_coordinate") && ...
    string(manifest.convergence_coordinate)== ...
    "positive_scalar_unitized_kkt";
audit = struct( ...
    "passed",sequencePass&&manifestCountPass&&gitPass&&coordinatePass, ...
    "sequence_passed",sequencePass, ...
    "manifest_counts_passed",manifestCountPass, ...
    "git_identity_passed",gitPass, ...
    "coordinate_passed",coordinatePass);
end

function [issues,decisions] = make_final_logs( ...
        context,result,acceptance,testAudit,staticAudit, ...
        identityAudit,historicalPassed,finalStatus)
issues = empty_issue_log();
numericalTerminal = string(result.run_terminal_state);
if numericalTerminal~="CONVERGED"
    issues = append_issue(issues,context, ...
        "A43-NUMERICAL-"+numericalTerminal,"A4-3-TERMINAL", ...
        numericalTerminal, ...
        "The formal candidate did not reach CONVERGED.", ...
        "The complete trajectory and accepted checkpoints were preserved.", ...
        "Keep stage_A4 / READY and review the persisted trajectory.", ...
        "iterations/iteration_summary.csv");
end
failed = acceptance(string(acceptance.status)~="PASS",:);
for row = 1:height(failed)
    issues = append_issue(issues,context, ...
        "A43-ACCEPTANCE-"+failed.test_id(row),failed.test_id(row), ...
        "acceptance", ...
        "A blocking Stage A4 acceptance item did not pass.", ...
        "The observed value and threshold remain unchanged.", ...
        "Resolve the failed gate without changing the frozen threshold.", ...
        "acceptance/acceptance_results.csv");
end
if ~testAudit.passed
    issues = append_issue(issues,context,"A43-TEST-EVIDENCE", ...
        "A4-3-TESTS","tests", ...
        "The persisted test set is failed, incomplete, or inconsistent.", ...
        "The original test result and summary files were retained.", ...
        "Repair the implementation/evidence and create a new formal run.", ...
        "tests/test_results.csv; tests/test_summary.json");
end
if ~staticAudit.passed
    issues = append_issue(issues,context,"A43-STATIC-EVIDENCE", ...
        "A4-3-STATIC","static", ...
        "One or more persisted static/forbidden checks did not pass.", ...
        "The static summary and dependency closure were retained.", ...
        "Resolve the failed check without changing the algorithm contract.", ...
        "tests/static_check_summary.csv; diagnostics");
end
if ~identityAudit.passed
    issues = append_issue(issues,context,"A43-EVIDENCE-IDENTITY", ...
        "A4-3-IDENTITY","identity", ...
        "Manifest, iteration, direction, or Git identity is inconsistent.", ...
        "Conflicting evidence was retained.", ...
        "Do not interpret or promote this run.", ...
        "run_manifest.json; a4_3_solver_result.mat");
end
if ~historicalPassed
    issues = append_issue(issues,context,"A43-HISTORICAL-RUNS", ...
        "A4-3-HISTORY","history", ...
        "Historical run preservation did not pass.", ...
        "The historical audit was retained.", ...
        "Stop and restore the historical evidence boundary.", ...
        "historical_runs_audit.json");
end
if finalStatus=="PASS"
    assert(isempty(issues), ...
        "stageA4:a43:finalizer:PassWithIssues", ...
        "A PASS candidate cannot contain an open issue.");
end
decisions = table(string(context.run_id),"A4-3", ...
    numericalTerminal,finalStatus, ...
    "CURRENT_STAGE remains stage_A4 / READY; no Stage B transition.", ...
    double(result.iteration_count), ...
    "positive_scalar_unitized_kkt", ...
    "independent alpha_primal/alpha_dual; stable-v2 MaxPasses=3", ...
    "complete persisted evidence; full KKT audit only", ...
    'VariableNames',{'run_id','milestone','numerical_terminal_state', ...
    'manifest_terminal_status','stage_decision', ...
    'accepted_iteration_count','convergence_coordinate', ...
    'algorithm_contract','evidence_basis'});
end

function output = append_issue(input,context,issueId,testId,layer, ...
        symptom,preserved,nextAction,evidencePath)
row = table(string(context.run_id),string(issueId),string(testId), ...
    string(layer),string(symptom),string(preserved),string(nextAction), ...
    "OPEN",string(evidencePath), ...
    'VariableNames',input.Properties.VariableNames);
output = [input;row];
end

function value = empty_issue_log()
value = table(strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer', ...
    'symptom','evidence_preserved','next_action','status', ...
    'evidence_path'});
end

function preserve_pre_finalization_tables(context)
pairs = [ ...
    string(context.acceptance_results_path), ...
        fullfile(context.acceptance_dir, ...
        "acceptance_results.pre_finalization.csv"); ...
    string(context.issue_log_path), ...
        fullfile(context.issues_dir,"issue_log.pre_finalization.csv"); ...
    string(context.decision_log_path), ...
        fullfile(context.issues_dir,"decision_log.pre_finalization.csv")];
for row = 1:size(pairs,1)
    source = pairs(row,1); target = pairs(row,2);
    assert(isfile(source), ...
        "stageA4:a43:finalizer:PreFinalizationEvidence", ...
        "Pre-finalization source is missing: %s",source);
    if isfile(target)
        continue
    end
    temporary = string(tempname(fileparts(target)))+".csv";
    guard = onCleanup(@()delete_if_exists(temporary));
    [copied,message] = copyfile(source,temporary);
    assert(copied,"stageA4:a43:finalizer:PreserveCopy","%s",message);
    sourceHash = compute_sha256_file(source);
    assert(lower(string(compute_sha256_file(temporary)))== ...
        lower(string(sourceHash)), ...
        "stageA4:a43:finalizer:PreserveHash", ...
        "Pre-finalization copy hash mismatch.");
    [moved,message] = movefile(temporary,target);
    assert(moved,"stageA4:a43:finalizer:PreserveMove","%s",message);
    clear guard
end
end

function write_derived_table(pathValue,value)
if isfile(pathValue)
    try
        existing = read_csv(pathValue);
        if tables_equivalent(existing,value)
            return
        end
    catch
        % A malformed mutable pre-finalization table is replaced only after
        % its original bytes have been preserved by the caller.
    end
end
write_table_csv_17g_atomic(pathValue,value);
end

function [evidence,reused] = materialize_complete_hash_inventory( ...
        context,manifest,target)
candidate = build_hash_inventory(context,manifest,target);
if isfile(target)
    existing = read_csv(target);
    assert(hash_inventories_equivalent(existing,candidate), ...
        "stageA4:a43:finalizer:EvidenceInventoryChanged", ...
        "A pre-existing final evidence inventory no longer matches the "+ ...
        "current run.  It is preserved and will not be overwritten.");
    evidence = existing;
    reused = true;
else
    write_table_csv_17g_atomic(target,candidate);
    evidence = read_csv(target);
    if ~hash_inventories_equivalent(evidence,candidate)
        error("stageA4:a43:finalizer:EvidenceInventoryWrite", ...
            "The persisted complete evidence inventory failed read-back: %s", ...
            hash_inventory_difference(evidence,candidate));
    end
    reused = false;
end

function value = hash_inventory_difference(left,right)
value = "left_height="+height(left)+"; right_height="+height(right);
required = ["relative_path","scope","bytes","sha256","status","checked_at"];
if ~all(ismember(required,string(left.Properties.VariableNames)))
    value = value+"; left_columns="+ ...
        strjoin(string(left.Properties.VariableNames),",");
    return
end
if height(left)~=height(right)
    return
end
[~,leftOrder] = sort(string(left.relative_path));
[~,rightOrder] = sort(string(right.relative_path));
left = left(leftOrder,:); right = right(rightOrder,:);
checks = [ ...
    isequal(string(left.relative_path),string(right.relative_path))
    isequal(string(left.scope),string(right.scope))
    isequal(double(left.bytes),double(right.bytes))
    isequal(lower(string(left.sha256)),lower(string(right.sha256)))
    isequal(string(left.status),string(right.status))
    isequal(string(left.checked_at),string(right.checked_at))];
value = value+"; path/scope/bytes/sha/status/time="+ ...
    strjoin(string(double(checks.')),",");
end
end

function evidence = build_hash_inventory(context,manifest,target)
listing = dir(fullfile(context.root,"**","*"));
relative = strings(0,1);
absolute = strings(0,1);
scope = strings(0,1);
targetRelative = relative_path(target,string(context.root));
for k = 1:numel(listing)
    if listing(k).isdir
        continue
    end
    pathValue = string(fullfile(listing(k).folder,listing(k).name));
    currentRelative = relative_path(pathValue,string(context.root));
    if ismember(currentRelative, ...
            ["run_manifest.json",targetRelative,".initializing"])
        continue
    end
    relative(end+1,1) = currentRelative; %#ok<AGROW>
    absolute(end+1,1) = pathValue; %#ok<AGROW>
    first = extractBefore(currentRelative,"/");
    if ismissing(first) || strlength(first)==0
        first = "run_root";
    end
    scope(end+1,1) = first; %#ok<AGROW>
end
[relative,order] = sort(relative);
absolute = absolute(order);
scope = scope(order);
assert(~isempty(relative) && ...
    numel(unique(relative))==numel(relative), ...
    "stageA4:a43:finalizer:EvidenceInventory", ...
    "Complete evidence paths must be nonempty and unique.");
n = numel(relative);
bytes = zeros(n,1);
sha256 = strings(n,1);
status = repmat("PASS",n,1);
checked_at = repmat("manifest_started_at:"+string(manifest.started_at),n,1);
for k = 1:n
    info = dir(absolute(k));
    assert(isscalar(info) && ~info.isdir, ...
        "stageA4:a43:finalizer:EvidenceMissing", ...
        "Evidence disappeared during hashing: %s",absolute(k));
    bytes(k) = info.bytes;
    sha256(k) = lower(string(compute_sha256_file(absolute(k))));
    if strlength(sha256(k))~=64
        status(k) = "FAIL";
    end
end
evidence = table(relative,scope,bytes,sha256,status,checked_at, ...
    'VariableNames',{'relative_path','scope','bytes','sha256', ...
    'status','checked_at'});
end

function passed = hash_inventories_equivalent(left,right)
required = ["relative_path","scope","bytes","sha256","status","checked_at"];
passed = all(ismember(required,string(left.Properties.VariableNames))) && ...
    height(left)==height(right);
if ~passed
    return
end
[~,leftOrder] = sort(string(left.relative_path));
[~,rightOrder] = sort(string(right.relative_path));
left = left(leftOrder,:); right = right(rightOrder,:);
passed = isequal(string(left.relative_path),string(right.relative_path)) && ...
    isequal(string(left.scope),string(right.scope)) && ...
    isequal(double(left.bytes),double(right.bytes)) && ...
    isequal(lower(string(left.sha256)),lower(string(right.sha256))) && ...
    isequal(string(left.status),string(right.status)) && ...
    isequal(string(left.checked_at),string(right.checked_at));
end

function updates = make_manifest_updates( ...
        context,result,acceptance,issues,testAudit,staticAudit, ...
        reportEvidence,evidence,evidencePath,finalStatus, ...
        currentStageHash,reusedEvidence)
reports = struct( ...
    "model_report",relative_path( ...
        string(reportEvidence.report_paths.model_report),context.root), ...
    "issue_report",relative_path( ...
        string(reportEvidence.report_paths.issue_report),context.root), ...
    "run_summary",relative_path( ...
        string(reportEvidence.report_paths.run_summary),context.root));
updates = struct( ...
    "a4_3_finalization_contract","deterministic-evidence-v1", ...
    "a4_3_candidate_terminal_status",char(finalStatus), ...
    "a4_3_numerical_terminal_state",char(result.run_terminal_state), ...
    "a4_3_acceptance_total",height(acceptance), ...
    "a4_3_acceptance_passed",nnz(string(acceptance.status)=="PASS"), ...
    "a4_3_acceptance_all_pass",all(string(acceptance.status)=="PASS"), ...
    "test_total",testAudit.test_total, ...
    "test_passed",testAudit.test_passed, ...
    "test_failed",testAudit.test_failed, ...
    "test_incomplete",testAudit.test_incomplete, ...
    "test_evidence_pass",testAudit.passed, ...
    "static_check_count",staticAudit.static_check_count, ...
    "static_checks_pass",staticAudit.passed, ...
    "forbidden_code_pass",staticAudit.forbidden_code_passed, ...
    "forbidden_execution_pass",staticAudit.forbidden_execution_passed, ...
    "dependency_closure_pass",staticAudit.dependency_closure_passed, ...
    "reports",reports, ...
    "reports_generated",true, ...
    "report_structure_validation_pass", ...
        all(string(reportEvidence.structure_validation.status)=="PASS"), ...
    "report_visual_validation_pass", ...
        all(string(reportEvidence.visual_validation.status)=="PASS"), ...
    "report_hash_manifest_pass", ...
        all(string(reportEvidence.hash_manifest.status)=="PASS"), ...
    "issues_open_count",height(issues), ...
    "evidence_hashes",relative_path(evidencePath,context.root), ...
    "evidence_hashes_sha256",char(compute_sha256_file(evidencePath)), ...
    "evidence_file_count",height(evidence), ...
    "evidence_inventory_reused",reusedEvidence, ...
    "current_stage_sha256",char(currentStageHash), ...
    "current_stage_preserved",true, ...
    "stage_b_entered",false, ...
    "tests_executed",true, ...
    "finalization_pending",false, ...
    "postprocess_phase","COMPLETE", ...
    "postprocessing_executed",true, ...
    "postprocess_completed_at",char(string(datetime("now", ...
        "TimeZone","Asia/Shanghai", ...
        "Format","yyyy-MM-dd'T'HH:mm:ssXXX"))));
end

function validate_environment_and_inputs(context,paths,manifest)
environment = read_csv(paths.environment);
inputs = read_csv(paths.input_hashes);
assert(all(ismember(["blocking","status"], ...
    string(environment.Properties.VariableNames))) && ...
    all(ismember(["expectedSHA256","actualSHA256","status"], ...
    string(inputs.Properties.VariableNames))), ...
    "stageA4:a43:finalizer:EnvironmentSchema", ...
    "Environment or input-hash evidence has an invalid schema.");
blocking = logical_column(environment.blocking);
assert(all(string(environment.status(blocking))=="PASS"), ...
    "stageA4:a43:finalizer:EnvironmentFailed", ...
    "A blocking environment check did not pass.");
assert(height(inputs)==2 && all(string(inputs.status)=="PASS") && ...
    all(lower(string(inputs.expectedSHA256))== ...
    lower(string(inputs.actualSHA256))) && ...
    all(strlength(string(inputs.actualSHA256))==64), ...
    "stageA4:a43:finalizer:InputHashFailed", ...
    "Controlled input SHA256 evidence did not pass.");
assert(isfield(manifest,"input_hashes") && ...
    isfield(manifest.input_hashes,"base_parameters") && ...
    isfield(manifest.input_hashes,"timeseries") && ...
    lower(string(manifest.input_hashes.base_parameters))== ...
        lower(string(inputs.actualSHA256(1))) && ...
    lower(string(manifest.input_hashes.timeseries))== ...
        lower(string(inputs.actualSHA256(2))), ...
    "stageA4:a43:finalizer:InputManifestIdentity", ...
    "run_manifest.json and input_hashes.csv disagree.");
for candidate = [string(paths.environment),string(paths.input_hashes)]
    assert(path_is_inside(canonical_file(candidate, ...
        "stageA4:a43:finalizer:EnvironmentEvidenceScope"), ...
        string(context.root)), ...
        "stageA4:a43:finalizer:EnvironmentEvidenceScope", ...
        "Environment/input evidence must be inside the current run.");
end
end

function findings = run_code_analyzer_records(root,closure)
file = strings(0,1);
line = zeros(0,1);
column = zeros(0,1);
identifier = strings(0,1);
message = strings(0,1);
for k = 1:height(closure)
    relative = string(closure.relative_path(k));
    if ~endsWith(relative,".m","IgnoreCase",true)
        continue
    end
    absolute = fullfile(root,replace(relative,"/",filesep));
    observed = checkcode(absolute,"-id");
    for j = 1:numel(observed)
        file(end+1,1) = relative; %#ok<AGROW>
        line(end+1,1) = double(observed(j).line); %#ok<AGROW>
        currentColumn = observed(j).column;
        if isempty(currentColumn)
            column(end+1,1) = NaN; %#ok<AGROW>
        else
            column(end+1,1) = double(currentColumn(1)); %#ok<AGROW>
        end
        text = string(observed(j).message);
        token = regexp(char(text),"\(([A-Za-z0-9_]+)\)[ \t]*$", ...
            "tokens","once");
        if isempty(token)
            identifier(end+1,1) = string(observed(j).id); %#ok<AGROW>
        else
            identifier(end+1,1) = string(token{1}); %#ok<AGROW>
        end
        message(end+1,1) = text; %#ok<AGROW>
    end
end
findings = table(file,line,column,identifier,message);
end

function assert_all_paths_inside_current_run(paths,runRoot)
names = string(fieldnames(paths));
for k = 1:numel(names)
    value = string(paths.(names(k)));
    canonical = string(char(java.io.File(char(value)).getCanonicalPath()));
    assert(path_is_inside(canonical,string(runRoot)), ...
        "stageA4:a43:finalizer:EvidenceScope", ...
        "Finalization input must be inside the current run: %s",value);
end
end

function assert_current_stage_ready(pathValue)
textValue = string(fileread(pathValue));
assert(~isempty(regexp(char(textValue), ...
    "`stage_id`[ \t]*:[ \t]*`stage_A4`","once")) && ...
    ~isempty(regexp(char(textValue), ...
    "`status`[ \t]*:[ \t]*`READY`","once")), ...
    "stageA4:a43:finalizer:CurrentStage", ...
    "CURRENT_STAGE.md must remain stage_A4 / READY.");
end

function assert_run_evidence_references(runRoot,references,errorId)
for value = references(:).'
    tokens = strip(split(string(value),";"));
    tokens = tokens(strlength(tokens)>0);
    assert(~isempty(tokens),errorId, ...
        "An evidence_path field is empty.");
    for token = tokens(:).'
        assert(~contains(replace(token,"\","/"),"../") && ...
            ~startsWith(replace(token,"\","/"),"/"), ...
            errorId,"Evidence reference escapes the current run: %s",token);
        if is_absolute_path(token)
            candidate = token;
        else
            candidate = fullfile(runRoot,replace(token,"/",filesep));
        end
        canonical = string(char(java.io.File( ...
            char(candidate)).getCanonicalPath()));
        assert(path_is_inside(canonical,string(runRoot)) && ...
            (isfile(canonical)||isfolder(canonical)), ...
            errorId, ...
            "Evidence reference must resolve inside the current run: %s", ...
            token);
    end
end
end

function passed = is_absolute_path(pathValue)
text = char(pathValue);
passed = (~isempty(regexp(text,"^[A-Za-z]:[\\/]","once"))) || ...
    startsWith(string(pathValue),"\\");
end

function value = scalar_logical_field(structValue,fieldName,label)
assert(isfield(structValue,fieldName), ...
    "stageA4:a43:finalizer:JsonSchema", ...
    "%s is missing field %s.",label,fieldName);
value = logical(structValue.(fieldName));
assert(isscalar(value), ...
    "stageA4:a43:finalizer:JsonSchema", ...
    "%s field %s must be scalar.",label,fieldName);
end

function value = logical_column(input)
if islogical(input)
    value = input;
elseif isnumeric(input)
    value = input~=0;
else
    text = lower(strip(string(input)));
    assert(all(ismember(text,["true","false","1","0"])), ...
        "stageA4:a43:finalizer:LogicalColumn", ...
        "A persisted logical column contains an invalid value.");
    value = text=="true" | text=="1";
end
value = value(:);
end

function passed = tables_equivalent(left,right)
passed = istable(left) && istable(right) && ...
    height(left)==height(right) && ...
    isequal(string(left.Properties.VariableNames), ...
    string(right.Properties.VariableNames));
if ~passed
    return
end
for name = string(left.Properties.VariableNames)
    a = left.(name); b = right.(name);
    if (isnumeric(a)||islogical(a)) && (isnumeric(b)||islogical(b))
        equal = isequaln(double(a),double(b));
    else
        aText = string(a);
        bText = string(b);
        aText(ismissing(aText)) = "";
        bText(ismissing(bText)) = "";
        equal = isequal(aText,bText);
    end
    if ~equal
        passed = false;
        return
    end
end
end

function passed = advisory_tables_equivalent(left,right)
% Historical A4-3 static evidence used UNKNOWN when localized checkcode
% messages omitted a trailing "(ID)" token.  Accept that representation
% only when every other field is exact and the independently rebuilt ID is
% one of the two explicitly nonblocking advisory IDs.
if tables_equivalent(left,right)
    passed = true;
    return
end
passed = istable(left) && istable(right) && ...
    height(left)==height(right) && ...
    isequal(string(left.Properties.VariableNames), ...
        string(right.Properties.VariableNames)) && ...
    ismember("identifier",string(left.Properties.VariableNames));
if ~passed
    return
end
leftId = string(left.identifier);
rightId = string(right.identifier);
legacy = leftId=="UNKNOWN" & ismember(rightId,["MSNU","SPRIX"]);
if ~all(leftId==rightId | legacy)
    passed = false;
    return
end
left.identifier = right.identifier;
passed = tables_equivalent(left,right);
end

function value = read_csv(pathValue)
value = readtable(pathValue,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
end

function value = read_json(pathValue)
try
    value = jsondecode(fileread(pathValue));
catch exception
    error("stageA4:a43:finalizer:JsonRead", ...
        "Could not decode %s: %s",pathValue,exception.message);
end
end

function value = canonical_directory(pathValue,errorId)
assert(isfolder(pathValue),errorId, ...
    "Required directory does not exist: %s",pathValue);
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end

function value = canonical_file(pathValue,errorId)
assert(isfile(pathValue),errorId, ...
    "Required file does not exist: %s",pathValue);
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end

function passed = path_is_inside(pathValue,root)
pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
root = string(char(java.io.File(char(root)).getCanonicalPath()));
passed = startsWith(lower(pathValue),lower(root+filesep));
end

function value = relative_path(pathValue,root)
pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
root = string(char(java.io.File(char(root)).getCanonicalPath()));
assert(startsWith(lower(pathValue),lower(root+filesep)), ...
    "stageA4:a43:finalizer:RelativePath", ...
    "Evidence path is outside the current run: %s",pathValue);
value = replace(extractAfter(pathValue,strlength(root)+1),"\","/");
end

function delete_if_exists(pathValue)
if isfile(pathValue)
    delete(pathValue);
end
end
