function [checkpoint,record,audit] = ...
        load_stage_a4_checkpoint(runContext,varargin)
%LOAD_STAGE_A4_CHECKPOINT Load only a validated committed A4 checkpoint.
%
% Name-value options are identical to validate_stage_a4_checkpoint:
% Revision (NaN means latest), ExpectedMetadata, and
% RebuiltLinearizationFingerprint.

audit = validate_stage_a4_checkpoint(runContext,varargin{:});
loaded = load(audit.selected_path,"checkpoint");
assert(isfield(loaded,"checkpoint") && ...
    isstruct(loaded.checkpoint) && isscalar(loaded.checkpoint), ...
    "stageA4:checkpoint:PayloadMissing", ...
    "Validated checkpoint MAT no longer contains checkpoint.");
checkpoint = loaded.checkpoint;
record = audit.selected_record;

% Detect a race or mutation after validation and before load returns.
actualSha = lower(string(compute_sha256_file( ...
    string(audit.selected_path))));
assert(actualSha==audit.selected_sha256, ...
    "stageA4:checkpoint:PostValidationMutation", ...
    "Checkpoint changed after validation.");
actualStateFingerprint = ...
    compute_stage_a4_checkpoint_state_fingerprint(checkpoint.state);
assert(actualStateFingerprint== ...
    lower(string(record.state_fingerprint)), ...
    "stageA4:checkpoint:PostValidationMutation", ...
    "Checkpoint state changed after validation.");
end
