function manifest = mark_stage_a4_full_ipm_execution(runContext)
%MARK_STAGE_A4_FULL_IPM_EXECUTION Record an actual A4-3 solver invocation.
%
% A fresh run starts with immutable execution claims set to false.  This
% narrowly scoped one-way transition is performed immediately before the
% full IPM driver is invoked.  A recoverable resume keeps the true values
% and increments an invocation counter without changing run identity.

arguments
    runContext (1,1) struct
end

pathValue = runContext.run_manifest_path;
assert(isfile(pathValue),"stageA4:a43:ManifestMissing", ...
    "The A4-3 run manifest is missing.");
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A4" && ...
    string(manifest.status)=="RUNNING", ...
    "stageA4:a43:ManifestIdentity", ...
    "Only the matching RUNNING A4 manifest can record execution.");
assert(isfield(manifest,"run_purpose") && ...
    string(manifest.run_purpose)== ...
        "seven_day_full_primal_dual_ipm_convergence_candidate" && ...
    isfield(manifest,"maximum_iterations") && ...
    double(manifest.maximum_iterations)==100 && ...
    isfield(manifest,"parallel_executed") && ...
    ~logical(manifest.parallel_executed), ...
    "stageA4:a43:ExecutionScope", ...
    "The manifest does not authorize the serial A4-3 candidate.");

if ~isfield(manifest,"optimization_executed")
    manifest.optimization_executed = false;
end
if ~isfield(manifest,"full_ipm_executed")
    manifest.full_ipm_executed = false;
end
if ~logical(manifest.optimization_executed) || ...
        ~logical(manifest.full_ipm_executed)
    assert(~logical(manifest.optimization_executed) && ...
        ~logical(manifest.full_ipm_executed), ...
        "stageA4:a43:ExecutionMarkerDrift", ...
        "Optimization and full-IPM execution flags must transition together.");
    manifest.optimization_executed = true;
    manifest.full_ipm_executed = true;
end
if isfield(manifest,"solver_invocation_count")
    invocationCount = double(manifest.solver_invocation_count)+1;
else
    invocationCount = 1;
end
manifest.solver_invocation_started = true;
manifest.solver_invocation_count = invocationCount;
manifest.solver_invocation_started_at = char(datetime("now", ...
    "TimeZone","UTC","Format","yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
write_json_file(pathValue,manifest);
end
