function manifest = mark_stage_a2_solver_execution(runContext)
%MARK_STAGE_A2_SOLVER_EXECUTION Record the sole permitted A2 solve attempt.

arguments
    runContext (1,1) struct
end
pathValue = runContext.run_manifest_path;
assert(isfile(pathValue),"stageA2:artifacts:ManifestMissing", ...
    "Run manifest is missing.");
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A2" && string(manifest.status)=="RUNNING", ...
    "stageA2:artifacts:ManifestIdentity", ...
    "Only the matching RUNNING A2 manifest can record execution.");
assert(isfield(manifest,"a2_solver_executed") && ...
    ~logical(manifest.a2_solver_executed), ...
    "stageA2:artifacts:SolverExecutionAlreadyMarked", ...
    "A2 solver execution was already recorded.");
assert(double(manifest.newton_direction_count)==1 && ...
    ~logical(manifest.full_ipm_executed) && ...
    ~logical(manifest.parallel_executed) && ...
    ~logical(manifest.optimization_executed), ...
    "stageA2:artifacts:ExecutionScope", ...
    "Manifest scope must permit one serial direction and no optimization/IPM.");
manifest.a2_solver_executed = true;
manifest.solver_execution_started_at = char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
write_json_file(pathValue,manifest);
end
