function audit = validate_stage_a4_checkpoint(runContext,varargin)
%VALIDATE_STAGE_A4_CHECKPOINT Validate the committed A4 checkpoint chain.
%
% Name-value options:
%   Revision                         Revision to select; NaN selects latest.
%   ExpectedMetadata                 Any supported identity fields to match.
%   RebuiltLinearizationFingerprint  Independently rebuilt fingerprint.
%
% Only rows committed to checkpoint_manifest.csv are recovery candidates.
% A matching orphan left between the atomic MAT and manifest publications
% is reported but is not silently selected by this validator.

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser,"Revision",NaN,@valid_revision_option);
addParameter(parser,"ExpectedMetadata",struct(), ...
    @(x)isstruct(x)&&isscalar(x));
addParameter(parser,"RebuiltLinearizationFingerprint","", ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
parse(parser,varargin{:});
requestedRevision = double(parser.Results.Revision);
expectedMetadata = parser.Results.ExpectedMetadata;
rebuiltFingerprint = string(parser.Results.RebuiltLinearizationFingerprint);

validate_context(runContext);
manifestPath = char(string(runContext.checkpoint_manifest_path));
assert(isfile(manifestPath), ...
    "stageA4:checkpoint:ManifestMissing", ...
    "Checkpoint manifest does not exist: %s",manifestPath);
manifest = readtable(manifestPath,Delimiter=",",ReadVariableNames=true, ...
    TextType="string",VariableNamingRule="preserve");
requiredColumns = manifest_columns();
assert(all(ismember(requiredColumns, ...
    string(manifest.Properties.VariableNames))), ...
    "stageA4:checkpoint:ManifestSchema", ...
    "checkpoint_manifest.csv is missing an A4-3 checkpoint column.");
manifest = manifest(:,cellstr(requiredColumns));
assert(height(manifest)>0, ...
    "stageA4:checkpoint:ManifestEmpty", ...
    "checkpoint_manifest.csv contains no committed checkpoint.");

iterations = double(manifest.iteration);
revisions = double(manifest.state_revision);
expectedSequence = (0:height(manifest)-1).';
assert(isequal(iterations,expectedSequence) && ...
    isequal(revisions,expectedSequence), ...
    "stageA4:checkpoint:RevisionContinuity", ...
    "Committed checkpoint iterations/revisions must be contiguous from zero.");
assert(all(string(manifest.run_id)==string(runContext.run_id)) && ...
    all(string(manifest.stage_id)=="stage_A4"), ...
    "stageA4:checkpoint:ManifestRunIdentity", ...
    "Checkpoint rows do not match the stage_A4 run context.");
assert(numel(unique(string(manifest.path)))==height(manifest), ...
    "stageA4:checkpoint:ManifestDuplicatePath", ...
    "Checkpoint manifest paths must be unique.");

stableColumns = ["solve_pass","model_contract_version","input_hashes", ...
    "index_contract_version","solver_version","git_commit", ...
    "config_sha256","initial_state_fingerprint", ...
    "recursive_refinement_max_passes"];
for name = stableColumns
    assert(isscalar(unique(string(manifest.(name)))), ...
        "stageA4:checkpoint:ManifestIdentityDrift", ...
        "Checkpoint identity column %s changed within one run.",name);
end
assert(all(double(manifest.recursive_refinement_max_passes)==3), ...
    "stageA4:checkpoint:StableV2Passes", ...
    "Every A4-3 checkpoint must record stable-v2 MaxPasses=3.");

runManifest = validate_run_identity(runContext,manifest);
checkpointRoot = canonical_path(runContext.checkpoints_dir);
previousSha = "GENESIS";
for row = 1:height(manifest)
    expectedName = "stage_A4_checkpoint_"+ ...
        compose("%03d",iterations(row))+".mat";
    expectedRelative = "checkpoints/"+expectedName;
    relativePath = replace(string(manifest.path(row)),"\","/");
    assert(relativePath==expectedRelative, ...
        "stageA4:checkpoint:ManifestPathContract", ...
        "Revision %d checkpoint path is not canonical.",iterations(row));
    absolutePath = fullfile(runContext.root, ...
        strrep(char(relativePath),"/",filesep));
    assert(starts_with_directory(canonical_path(absolutePath),checkpointRoot), ...
        "stageA4:checkpoint:ManifestPathEscape", ...
        "Checkpoint path escapes the run checkpoint directory.");
    assert(isfile(absolutePath), ...
        "stageA4:checkpoint:CheckpointMissing", ...
        "Committed checkpoint file is missing: %s",absolutePath);

    actualSha = lower(string(compute_sha256_file(string(absolutePath))));
    recordedSha = lower(string(manifest.sha256(row)));
    assert(is_sha256(recordedSha) && actualSha==recordedSha, ...
        "stageA4:checkpoint:FileHashMismatch", ...
        "Checkpoint SHA256 mismatch at revision %d.",iterations(row));
    assert(string(manifest.previous_checkpoint_sha256(row))==previousSha, ...
        "stageA4:checkpoint:HashChainMismatch", ...
        "Checkpoint hash chain is broken at revision %d.",iterations(row));

    loaded = load(absolutePath,"checkpoint");
    assert(isfield(loaded,"checkpoint") && ...
        isstruct(loaded.checkpoint) && isscalar(loaded.checkpoint), ...
        "stageA4:checkpoint:PayloadMissing", ...
        "Checkpoint MAT must contain one scalar struct named checkpoint.");
    validate_payload(loaded.checkpoint,manifest(row,:),runContext,previousSha);
    previousSha = recordedSha;
end

if isnan(requestedRevision)
    selectedRevision = iterations(end);
else
    selectedRevision = requestedRevision;
end
selectedPosition = find(iterations==selectedRevision,1);
assert(~isempty(selectedPosition), ...
    "stageA4:checkpoint:RevisionNotFound", ...
    "Requested checkpoint revision %d is not committed.",selectedRevision);
selected = manifest(selectedPosition,:);
validate_expected_metadata(expectedMetadata,manifest,selected);
if strlength(strip(rebuiltFingerprint))>0
    rebuiltFingerprint = normalized_sha256( ...
        rebuiltFingerprint,"RebuiltLinearizationFingerprint");
    assert(lower(string(selected.linearization_fingerprint))== ...
        rebuiltFingerprint, ...
        "stageA4:checkpoint:RebuiltLinearizationMismatch", ...
        "The rebuilt linearization fingerprint does not match revision %d.", ...
        selectedRevision);
end

listedNames = string(extractAfter(replace(string(manifest.path),"\","/"), ...
    "checkpoints/"));
discovered = dir(fullfile(runContext.checkpoints_dir, ...
    "stage_A4_checkpoint_*.mat"));
discoveredNames = string({discovered.name}).';
orphanNames = setdiff(discoveredNames,listedNames,"stable");

audit = struct();
audit.passed = true;
audit.schema_version = "stage_A4_checkpoint_v1.0";
audit.run_id = string(runContext.run_id);
audit.stage_id = "stage_A4";
audit.revision_count = height(manifest);
audit.latest_revision = iterations(end);
audit.selected_revision = selectedRevision;
audit.selected_record = selected;
audit.selected_path = fullfile(runContext.root, ...
    strrep(char(selected.path),"/",filesep));
audit.selected_sha256 = lower(string(selected.sha256));
audit.manifest = manifest;
audit.manifest_path = string(manifestPath);
audit.run_manifest_status = string(runManifest.status);
audit.orphan_file_count = numel(orphanNames);
audit.orphan_file_names = orphanNames;
audit.hash_chain_tip = previousSha;
audit.failure_ledger_audit = validate_failure_ledger(runContext);
end

function validate_payload(checkpoint,row,runContext,previousSha)
required = ["schema_version","run_id","stage_id","metadata","state", ...
    "previous_checkpoint_sha256","created_at"];
assert(all(isfield(checkpoint,cellstr(required))) && ...
    string(checkpoint.schema_version)=="stage_A4_checkpoint_v1.0" && ...
    string(checkpoint.run_id)==string(runContext.run_id) && ...
    string(checkpoint.stage_id)=="stage_A4", ...
    "stageA4:checkpoint:PayloadIdentity", ...
    "Checkpoint payload identity/schema is invalid.");
metadata = normalize_stage_a4_checkpoint_metadata(checkpoint.metadata);
assert(metadata.iteration==double(row.iteration) && ...
    metadata.state_revision==double(row.state_revision) && ...
    metadata.solve_pass==string(row.solve_pass) && ...
    metadata.model_contract_version==string(row.model_contract_version) && ...
    metadata.input_hashes_sha256==lower(string(row.input_hashes)) && ...
    metadata.index_contract_version==string(row.index_contract_version) && ...
    metadata.solver_version==string(row.solver_version) && ...
    metadata.git_commit==lower(string(row.git_commit)) && ...
    metadata.config_sha256==lower(string(row.config_sha256)) && ...
    metadata.initial_state_fingerprint== ...
        lower(string(row.initial_state_fingerprint)) && ...
    metadata.state_fingerprint==lower(string(row.state_fingerprint)) && ...
    metadata.linearization_fingerprint== ...
        lower(string(row.linearization_fingerprint)) && ...
    metadata.iteration_csv_sha256== ...
        string(row.iteration_csv_sha256) && ...
    metadata.direction_csv_sha256== ...
        string(row.direction_csv_sha256) && ...
    metadata.refinement_csv_sha256== ...
        string(row.refinement_csv_sha256) && ...
    metadata.recursive_refinement_max_passes== ...
        double(row.recursive_refinement_max_passes) && ...
    string(checkpoint.created_at)==string(row.created_at), ...
    "stageA4:checkpoint:PayloadMetadataMismatch", ...
    "Checkpoint payload metadata differs from checkpoint_manifest.csv.");
assert(string(checkpoint.previous_checkpoint_sha256)==previousSha, ...
    "stageA4:checkpoint:PayloadHashChainMismatch", ...
    "Checkpoint payload previous hash differs from the manifest chain.");

state = checkpoint.state;
validate_state_revision(state,metadata.iteration);
actualFingerprint = compute_stage_a4_checkpoint_state_fingerprint(state);
assert(actualFingerprint==metadata.state_fingerprint, ...
    "stageA4:checkpoint:PayloadStateFingerprintMismatch", ...
    "Checkpoint state does not match its independently rebuilt fingerprint.");
if metadata.iteration==0
    assert(metadata.state_fingerprint==metadata.initial_state_fingerprint, ...
        "stageA4:checkpoint:InitialStateFingerprintMismatch", ...
        "Revision zero must equal the frozen initial-state fingerprint.");
end
end

function validate_state_revision(state,revision)
assert(isstruct(state)&&isscalar(state)&&isfield(state,"stage_id") && ...
    string(state.stage_id)=="stage_A4", ...
    "stageA4:checkpoint:StateStageIdentity", ...
    "Checkpoint state must identify stage_A4.");
names = ["iteration_index","state_revision", ...
    "newton_direction_number","completed_newton_direction_count"];
for name = names
    assert(isfield(state,name) && isa(state.(name),"double") && ...
        isscalar(state.(name)) && state.(name)==revision, ...
        "stageA4:checkpoint:StateRevisionMismatch", ...
        "state.%s must equal checkpoint revision %d.",name,revision);
end
assert(isfield(state,"l")&&isfield(state,"z") && ...
    all(state.l>0)&&all(state.z>0), ...
    "stageA4:checkpoint:StatePositivity", ...
    "Checkpoint state must preserve strict l/z positivity.");
end

function runManifest = validate_run_identity(runContext,manifest)
assert(isfield(runContext,"run_manifest_path") && ...
    isfile(runContext.run_manifest_path), ...
    "stageA4:checkpoint:RunManifestMissing", ...
    "A4 checkpoint validation requires run_manifest.json.");
try
    runManifest = jsondecode(fileread(runContext.run_manifest_path));
catch exception
    error("stageA4:checkpoint:RunManifestInvalid", ...
        "Could not decode run_manifest.json: %s",exception.message);
end
assert(isfield(runManifest,"run_id")&&isfield(runManifest,"stage_id")&& ...
    isfield(runManifest,"status") && ...
    string(runManifest.run_id)==string(runContext.run_id) && ...
    string(runManifest.stage_id)=="stage_A4", ...
    "stageA4:checkpoint:RunManifestIdentity", ...
    "run_manifest.json does not match the stage_A4 run context.");
if isfield(runManifest,"git_commit")
    assert(lower(string(runManifest.git_commit))== ...
        lower(string(manifest.git_commit(1))), ...
        "stageA4:checkpoint:RunManifestGitMismatch", ...
        "Checkpoint Git identity differs from run_manifest.json.");
end
if isfield(runManifest,"model_contract_version")
    assert(string(runManifest.model_contract_version)== ...
        string(manifest.model_contract_version(1)), ...
        "stageA4:checkpoint:RunManifestModelContractMismatch", ...
        "Checkpoint model contract differs from run_manifest.json.");
end
if isfield(runManifest,"input_hashes")
    [inputFingerprint,~] = ...
        compute_stage_a4_checkpoint_input_fingerprint( ...
        runManifest.input_hashes);
    assert(inputFingerprint==lower(string(manifest.input_hashes(1))), ...
        "stageA4:checkpoint:RunManifestInputMismatch", ...
        "Checkpoint input identity differs from run_manifest.json.");
end
assert(isfield(runContext,"effective_config_path") && ...
    isfile(runContext.effective_config_path), ...
    "stageA4:checkpoint:EffectiveConfigMissing", ...
    "The run effective_config.yaml is missing.");
configSha = lower(string(compute_sha256_file( ...
    string(runContext.effective_config_path))));
assert(configSha==lower(string(manifest.config_sha256(1))), ...
    "stageA4:checkpoint:EffectiveConfigMismatch", ...
    "Checkpoint config identity differs from effective_config.yaml.");
end

function validate_expected_metadata(expected,manifest,selected)
if isempty(fieldnames(expected))
    return
end
supported = ["iteration","state_revision","input_hashes", ...
    "input_hashes_sha256","config_sha256","git_commit", ...
    "linearization_fingerprint","state_fingerprint", ...
    "iteration_csv_sha256","initial_state_fingerprint", ...
    "direction_csv_sha256","refinement_csv_sha256", ...
    "recursive_refinement_max_passes","solve_pass", ...
    "model_contract_version","index_contract_version","solver_version"];
unknown = setdiff(string(fieldnames(expected)),supported);
assert(isempty(unknown), ...
    "stageA4:checkpoint:ExpectedMetadataField", ...
    "Unsupported ExpectedMetadata field: %s", ...
    join(unknown,", "));

if isfield(expected,"input_hashes")
    [value,~] = compute_stage_a4_checkpoint_input_fingerprint( ...
        expected.input_hashes);
    assert(all(lower(string(manifest.input_hashes))==value), ...
        "stageA4:checkpoint:ExpectedIdentityMismatch", ...
        "Expected input hashes do not match the checkpoint chain.");
end
if isfield(expected,"input_hashes_sha256")
    value = normalized_sha256(expected.input_hashes_sha256, ...
        "ExpectedMetadata.input_hashes_sha256");
    assert(all(lower(string(manifest.input_hashes))==value), ...
        "stageA4:checkpoint:ExpectedIdentityMismatch", ...
        "Expected input fingerprint does not match the checkpoint chain.");
end

stableMap = {
    "config_sha256","config_sha256"
    "git_commit","git_commit"
    "initial_state_fingerprint","initial_state_fingerprint"
    "solve_pass","solve_pass"
    "model_contract_version","model_contract_version"
    "index_contract_version","index_contract_version"
    "solver_version","solver_version"
    };
for k = 1:size(stableMap,1)
    field = string(stableMap{k,1});
    column = string(stableMap{k,2});
    if isfield(expected,field)
        value = strip(string(expected.(field)));
        if ismember(field,["config_sha256","initial_state_fingerprint"])
            value = normalized_sha256(value,"ExpectedMetadata."+field);
        elseif field=="git_commit"
            value = lower(value);
        end
        assert(all(string(manifest.(column))==value), ...
            "stageA4:checkpoint:ExpectedIdentityMismatch", ...
            "Expected %s does not match the checkpoint chain.",field);
    end
end

selectedMap = {
    "linearization_fingerprint","linearization_fingerprint"
    "state_fingerprint","state_fingerprint"
    "iteration_csv_sha256","iteration_csv_sha256"
    "direction_csv_sha256","direction_csv_sha256"
    "refinement_csv_sha256","refinement_csv_sha256"
    };
for k = 1:size(selectedMap,1)
    field = string(selectedMap{k,1});
    column = string(selectedMap{k,2});
    if isfield(expected,field)
        value = strip(string(expected.(field)));
        value = normalized_sha256(value,"ExpectedMetadata."+field);
        assert(string(selected.(column))==value, ...
            "stageA4:checkpoint:ExpectedIdentityMismatch", ...
            "Expected %s does not match the selected checkpoint.",field);
    end
end
if isfield(expected,"iteration")
    assert(double(selected.iteration)==double(expected.iteration), ...
        "stageA4:checkpoint:ExpectedIdentityMismatch", ...
        "Expected iteration does not match the selected checkpoint.");
end
if isfield(expected,"state_revision")
    assert(double(selected.state_revision)==double(expected.state_revision), ...
        "stageA4:checkpoint:ExpectedIdentityMismatch", ...
        "Expected state revision does not match the selected checkpoint.");
end
if isfield(expected,"recursive_refinement_max_passes")
    assert(double(expected.recursive_refinement_max_passes)==3 && ...
        all(double(manifest.recursive_refinement_max_passes)==3), ...
        "stageA4:checkpoint:ExpectedIdentityMismatch", ...
        "Expected stable-v2 MaxPasses does not match the checkpoint chain.");
end
end

function columns = manifest_columns()
columns = ["run_id","stage_id","solve_pass","iteration", ...
    "state_revision","model_contract_version","input_hashes", ...
    "index_contract_version","solver_version","git_commit", ...
    "config_sha256","initial_state_fingerprint","state_fingerprint", ...
    "linearization_fingerprint","iteration_csv_sha256", ...
    "direction_csv_sha256","refinement_csv_sha256", ...
    "recursive_refinement_max_passes","previous_checkpoint_sha256", ...
    "path","sha256","created_at"];
end

function validate_context(context)
required = ["root","run_id","stage_id","checkpoints_dir", ...
    "checkpoint_manifest_path"];
assert(isstruct(context)&&isscalar(context)&& ...
    all(isfield(context,cellstr(required))) && ...
    string(context.stage_id)=="stage_A4" && ...
    isfolder(context.root)&&isfolder(context.checkpoints_dir), ...
    "stageA4:checkpoint:RunContext", ...
    "A valid stage_A4 run context and checkpoints directory are required.");
end

function value = canonical_path(pathValue)
value = string(char(java.io.File(char(string(pathValue))).getCanonicalPath()));
end

function passed = starts_with_directory(pathValue,directory)
passed = pathValue==directory || ...
    startsWith(pathValue,directory+string(filesep));
end

function passed = valid_revision_option(value)
passed = isa(value,"double") && isreal(value) && isscalar(value) && ...
    (isnan(value)||(isfinite(value)&&value>=0&&value==fix(value)));
end

function value = normalized_sha256(value,label)
assert(ischar(value)||(isstring(value)&&isscalar(value)), ...
    "stageA4:checkpoint:ExpectedSha256", ...
    "%s must be a text scalar.",label);
value = lower(strip(string(value)));
assert(is_sha256(value), ...
    "stageA4:checkpoint:ExpectedSha256", ...
    "%s must be a 64-character SHA256.",label);
end

function passed = is_sha256(value)
passed = ~isempty(regexp(char(value),"^[0-9a-f]{64}$","once"));
end

function audit = validate_failure_ledger(runContext)
ledgerPath = fullfile(runContext.checkpoints_dir,"failure_ledger.csv");
columns = failure_ledger_columns();
if ~isfile(ledgerPath)
    audit = struct( ...
        "present",false, ...
        "passed",true, ...
        "failure_count",0, ...
        "ledger",empty_failure_ledger(), ...
        "ledger_path",string(ledgerPath), ...
        "orphan_file_count",0, ...
        "orphan_file_names",strings(0,1));
    return
end

options = detectImportOptions(ledgerPath,Delimiter=",", ...
    VariableNamingRule="preserve");
options = setvartype(options,options.VariableNames,"string");
ledger = readtable(ledgerPath,options);
assert(isequal(string(ledger.Properties.VariableNames),columns), ...
    "stageA4:checkpoint:FailureLedgerSchema", ...
    "failure_ledger.csv does not have the canonical column order.");
ledger = normalize_failure_ledger_columns(ledger);
n = height(ledger);
assert(n>0 && isequal(ledger.failure_sequence,(1:n).'), ...
    "stageA4:checkpoint:FailureLedgerSequence", ...
    "Failure ledger sequence numbers must be contiguous from one.");
assert(all(ledger.run_id==string(runContext.run_id)) && ...
    all(ismember(ledger.terminal_state, ...
        ["NUMERICAL_FAILURE","INTERRUPTED_RECOVERABLE"])) && ...
    all(ledger.solver_invocation>=1) && ...
    all(ledger.iteration>=0) && all(ledger.state_revision>=0), ...
    "stageA4:checkpoint:FailureLedgerIdentity", ...
    "Failure ledger identity or terminal-state fields are invalid.");

checkpointRoot = canonical_path(runContext.checkpoints_dir);
listedNames = strings(n,1);
for k = 1:n
    relativePath = replace(ledger.relative_path(k),"\","/");
    expectedPrefix = "checkpoints/"+lower(ledger.terminal_state(k))+ ...
        "_inv";
    assert(startsWith(lower(relativePath),expectedPrefix) && ...
        endsWith(lower(relativePath),".mat"), ...
        "stageA4:checkpoint:FailureEvidencePathContract", ...
        "Failure evidence row %d has a noncanonical relative path.",k);
    absolutePath = fullfile(runContext.root, ...
        strrep(char(relativePath),"/",filesep));
    assert(starts_with_directory(canonical_path(absolutePath), ...
        checkpointRoot) && isfile(absolutePath), ...
        "stageA4:checkpoint:FailureEvidenceMissing", ...
        "Failure evidence row %d is missing or escapes checkpoints/.",k);
    actualSha = lower(string(compute_sha256_file(string(absolutePath))));
    assert(is_sha256(ledger.sha256(k)) && actualSha==ledger.sha256(k), ...
        "stageA4:checkpoint:FailureEvidenceHashMismatch", ...
        "Failure evidence SHA256 mismatch at ledger row %d.",k);
    loaded = load(absolutePath,"state_before_failure","failure");
    assert(isfield(loaded,"state_before_failure") && ...
        isfield(loaded,"failure") && isstruct(loaded.failure) && ...
        isscalar(loaded.failure), ...
        "stageA4:checkpoint:FailureEvidencePayload", ...
        "Failure evidence row %d has an invalid MAT payload.",k);
    stateFingerprint = ...
        compute_stage_a4_checkpoint_state_fingerprint( ...
        loaded.state_before_failure);
    failure = loaded.failure;
    required = ["iteration","state_revision","identifier","message", ...
        "evidence_path","state_fingerprint"];
    assert(all(isfield(failure,cellstr(required))) && ...
        double(failure.iteration)==ledger.iteration(k) && ...
        double(failure.state_revision)==ledger.state_revision(k) && ...
        string(failure.identifier)==ledger.identifier(k) && ...
        string(failure.message)==ledger.message(k) && ...
        replace(string(failure.evidence_path),"\","/")==relativePath && ...
        lower(string(failure.state_fingerprint))==stateFingerprint && ...
        stateFingerprint==ledger.state_fingerprint(k), ...
        "stageA4:checkpoint:FailureEvidencePayloadMismatch", ...
        "Failure evidence payload differs from ledger row %d.",k);
    listedNames(k) = string(extractAfter(relativePath,"checkpoints/"));
end

discovered = [ ...
    dir(fullfile(runContext.checkpoints_dir, ...
        "numerical_failure_inv*.mat")); ...
    dir(fullfile(runContext.checkpoints_dir, ...
        "interrupted_recoverable_inv*.mat"))];
discoveredNames = string({discovered.name}).';
orphanNames = setdiff(discoveredNames,listedNames,"stable");
audit = struct( ...
    "present",true, ...
    "passed",true, ...
    "failure_count",n, ...
    "ledger",ledger, ...
    "ledger_path",string(ledgerPath), ...
    "orphan_file_count",numel(orphanNames), ...
    "orphan_file_names",orphanNames);
end

function value = normalize_failure_ledger_columns(value)
for name = ["failure_sequence","solver_invocation","iteration", ...
        "state_revision"]
    if ~isnumeric(value.(name))
        value.(name) = str2double(string(value.(name)));
    end
    assert(all(isfinite(value.(name))) && ...
        all(value.(name)>=0) && ...
        all(value.(name)==fix(value.(name))), ...
        "stageA4:checkpoint:FailureLedgerInteger", ...
        "Failure ledger column %s must contain nonnegative integers.",name);
end
for name = ["run_id","terminal_state","identifier","message", ...
        "state_fingerprint","relative_path","sha256","recorded_at_utc"]
    value.(name) = string(value.(name));
end
value.state_fingerprint = lower(value.state_fingerprint);
value.sha256 = lower(value.sha256);
assert(all(arrayfun(@is_sha256,value.state_fingerprint)) && ...
    all(arrayfun(@is_sha256,value.sha256)), ...
    "stageA4:checkpoint:FailureLedgerSha256", ...
    "Failure ledger state/evidence hashes must be canonical SHA256.");
end

function value = empty_failure_ledger()
value = table(zeros(0,1),strings(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    'VariableNames',cellstr(failure_ledger_columns()));
end

function columns = failure_ledger_columns()
columns = ["failure_sequence","run_id","solver_invocation", ...
    "iteration","state_revision","terminal_state","identifier", ...
    "message","state_fingerprint","relative_path","sha256", ...
    "recorded_at_utc"];
end
