function moduleResult = moduleResultTemplate(metadata)
%MODULERESULTTEMPLATE Create the canonical manual-validation envelope.
%   The supplied metadata is validated and copied without normalization.
%   Production input/output objects are not inspected or modified here.

rkkt.contracts.validateModuleMetadata(metadata);
moduleResult = struct( ...
    "meta",metadata, ...
    "input",struct(), ...
    "output",struct(), ...
    "intermediate",struct(), ...
    "diagnostics",struct(), ...
    "indexDescription",struct(), ...
    "tableFiles",strings(0,1), ...
    "figureFiles",strings(0,1));
end
