function tests = test_stage_a1_report
%TEST_STAGE_A1_REPORT Verify artifact-backed A1 DOCX generation and guards.
tests = functiontests(localfunctions);
end

function setup(testCase)
repositoryRoot = string(fileparts(fileparts(fileparts(mfilename('fullpath')))));
originalPath = path;
addpath(genpath(fullfile(repositoryRoot,'src')));
testCase.addTeardown(@() path(originalPath));

runRoot = string(tempname(tempdir));
[created,message] = mkdir(runRoot);
testCase.assertTrue(created,message);
testCase.addTeardown(@() remove_test_tree(runRoot));
write_synthetic_run(runRoot);

testCase.TestData.repositoryRoot = repositoryRoot;
testCase.TestData.runRoot = runRoot;
testCase.TestData.context = struct('root',char(runRoot), ...
    'project_root',char(repositoryRoot));
end

function testGeneratesThreeValidatedArtifactBackedReports(testCase)
outputDirectory = fullfile(testCase.TestData.runRoot,'staged_reports');
paths = generate_stage_a1_reports(testCase.TestData.context, ...
    'OutputDirectory',outputDirectory,'FinalStatusCandidate','PASS');

verifyEqual(testCase,string_filename(paths.model_report), ...
    "阶段A1_完整KKT与递推方向等价验收报告.docx");
verifyEqual(testCase,string_filename(paths.issue_report), ...
    "阶段A1_问题修复与验收报告.docx");
verifyEqual(testCase,string_filename(paths.run_summary), ...
    "运行_synthetic_stage_A1_report_结果摘要.docx");

reportFiles = string(struct2cell(paths));
verifyEqual(testCase,numel(reportFiles),3);
verifyTrue(testCase,all(isfile(reportFiles)));
for reportFile = reshape(reportFiles,1,[])
    [valid,validation] = validate_docx_package(reportFile);
    verifyTrue(testCase,valid,strjoin(string(validation.errors),'; '));
end

modelXml = read_document_xml(paths.model_report);
verifyTrue(testCase,contains(modelXml,'依据全部阻断项计算的终态'));
verifyTrue(testCase,contains(modelXml,'PASS'));
verifyTrue(testCase,contains(modelXml,'471 × 471'));
verifyTrue(testCase,contains(modelXml,'27'));
verifyTrue(testCase,contains(modelXml,'29'));
verifyTrue(testCase,contains(modelXml,'16 × 16'));
verifyTrue(testCase,contains(modelXml,'不连接第 7 小时'));
verifyTrue(testCase,contains(modelXml,'不是正式物理日'));

issueXml = read_document_xml(paths.issue_report);
expectedAcceptanceIds = stage_a1_acceptance_ids();
for acceptanceId = reshape(expectedAcceptanceIds,1,[])
    verifyEqual(testCase,count(issueXml,acceptanceId),1, ...
        sprintf('Acceptance row %s was dropped or duplicated.',acceptanceId));
end

summaryXml = read_document_xml(paths.run_summary);
verifyTrue(testCase,contains(summaryXml,'不能解释为正式 24 小时运行'));
manifest = jsondecode(fileread(fullfile(testCase.TestData.runRoot, ...
    'run_manifest.json')));
verifyEqual(testCase,string(manifest.status),"RUNNING");
end

function testExistingReportsAreNeverOverwritten(testCase)
outputDirectory = fullfile(testCase.TestData.runRoot,'staged_reports');
paths = generate_stage_a1_reports(testCase.TestData.context, ...
    'OutputDirectory',outputDirectory,'FinalStatusCandidate','PASS');
beforeHash = compute_sha256_file(string(paths.model_report));

verifyError(testCase,@() generate_stage_a1_reports( ...
    testCase.TestData.context,'OutputDirectory',outputDirectory, ...
    'FinalStatusCandidate','PASS'),'stageA1:report:ArtifactExists');
verifyEqual(testCase,compute_sha256_file(string(paths.model_report)),beforeHash);
end

function testFalsePassCandidateIsRejectedAndFailureCanBeReported(testCase)
acceptancePath = fullfile(testCase.TestData.runRoot,'acceptance', ...
    'acceptance_results.csv');
acceptance = readtable(acceptancePath,'TextType','string', ...
    'VariableNamingRule','preserve');
acceptance.status(1) = "FAIL";
acceptance.actual_value(1) = "synthetic failure";
write_table_csv_17g(acceptancePath,acceptance);

manifestPath = fullfile(testCase.TestData.runRoot,'run_manifest.json');
manifest = jsondecode(fileread(manifestPath));
manifest.newton_direction_count = 0;
manifest.a1_solver_executed = false;
write_json_file(manifestPath,manifest);

outputDirectory = fullfile(testCase.TestData.runRoot,'failure_reports');
verifyError(testCase,@() generate_stage_a1_reports( ...
    testCase.TestData.context,'OutputDirectory',outputDirectory, ...
    'FinalStatusCandidate','PASS'), ...
    'stageA1:report:FinalStatusCandidateMismatch');

paths = generate_stage_a1_reports(testCase.TestData.context, ...
    'OutputDirectory',outputDirectory, ...
    'FinalStatusCandidate','FAIL_RETRYABLE');
verifyTrue(testCase,all(isfile(string(struct2cell(paths)))));
issueXml = read_document_xml(paths.issue_report);
verifyTrue(testCase,contains(issueXml,'FAIL_RETRYABLE'));
end

function testPassReportRejectsInconsistentTestEvidence(testCase)
resultsPath = fullfile(testCase.TestData.runRoot,'tests','test_results.csv');
results = readtable(resultsPath,'TextType','string', ...
    'VariableNamingRule','preserve');
results.passed(1) = "false";
results.failed(1) = "true";
write_table_csv_17g(resultsPath,results);
summaryPath = fullfile(testCase.TestData.runRoot,'tests','test_summary.json');
write_json_file(summaryPath,struct('test_total',2,'test_passed',1, ...
    'test_failed',1,'test_incomplete',0));

verifyError(testCase,@() generate_stage_a1_reports( ...
    testCase.TestData.context,'OutputDirectory', ...
    fullfile(testCase.TestData.runRoot,'inconsistent_reports'), ...
    'FinalStatusCandidate','PASS'),'stageA1:report:FalsePassEvidence');
end

function testFinalizedManifestCannotBeUsedForStaging(testCase)
manifestPath = fullfile(testCase.TestData.runRoot,'run_manifest.json');
manifest = jsondecode(fileread(manifestPath));
manifest.status = 'PASS';
write_json_file(manifestPath,manifest);
verifyError(testCase,@() generate_stage_a1_reports( ...
    testCase.TestData.context,'OutputDirectory', ...
    fullfile(testCase.TestData.runRoot,'late_reports'), ...
    'FinalStatusCandidate','PASS'),'stageA1:report:ManifestNotRunning');
end

function testMinimalFailureReportNeedsNoNumericalArtifacts(testCase)
issues = new_stage_a1_issue_log();
issues(1,:) = {"SA1-ISSUE-001","synthetic_stage_A1_report", ...
    "stage_A1","SA1-EQ-002","inequality_elimination", ...
    "inequality row 17","synthetic injected failure", ...
    "stageA1:test:Injected: synthetic injected failure", ...
    "synthetic root cause","inspect persisted issue evidence", ...
    "0123456789abcdef","","OPEN", ...
    "issues/issue_log.csv","synthetic-time"};
acceptance = readtable(fullfile(testCase.TestData.runRoot,'acceptance', ...
    'acceptance_results.csv'),'TextType','string', ...
    'VariableNamingRule','preserve');
acceptance.status(:) = "NOT_RUN";
acceptance.status(9) = "FAIL";
acceptance.actual_value(:) = "";
acceptance.actual_value(9) = "synthetic injected failure";

try
    error('stageA1:test:Injected','synthetic injected failure');
catch exception
end
reportPath = generate_stage_a1_failure_report( ...
    testCase.TestData.context,exception,issues,acceptance);
verifyEqual(testCase,string_filename(reportPath), ...
    "阶段A1_失败与首层定位报告.docx");
[valid,validation] = validate_docx_package(reportPath);
verifyTrue(testCase,valid,strjoin(string(validation.errors),'; '));
xml = read_document_xml(reportPath);
verifyTrue(testCase,contains(xml,'stageA1:test:Injected'));
verifyTrue(testCase,contains(xml,'inequality_elimination'));
verifyTrue(testCase,contains(xml,'inequality row 17'));
verifyTrue(testCase,contains(xml,'SA1-EQ-002'));
verifyTrue(testCase,contains(xml,'不推断未运行的矩阵维数'));
verifyFalse(testCase,contains(xml,'471'));
verifyError(testCase,@() generate_stage_a1_failure_report( ...
    testCase.TestData.context,exception,issues,acceptance), ...
    'stageA1:failureReport:ArtifactExists');
end

function write_synthetic_run(runRoot)
subdirectories = {'acceptance','matrices','iterations','issues','tests', ...
    'indices','diagnostics'};
for index = 1:numel(subdirectories)
    mkdir(fullfile(runRoot,subdirectories{index}));
end

manifest = struct( ...
    'run_id','synthetic_stage_A1_report', ...
    'stage_id','stage_A1', ...
    'git_commit','0123456789abcdef', ...
    'status','RUNNING', ...
    'window_type','synthetic_closed_test_window', ...
    'start_hour',8, ...
    'terminal_hour',10, ...
    'soc_boundary_mode','fixed_half_energy', ...
    'newton_direction_count',1, ...
    'full_ipm_executed',false, ...
    'parallel_executed',false, ...
    'optimization_executed',false, ...
    'a1_solver_executed',true, ...
    'physical_dispatch_interpretation',false);
write_json_file(fullfile(runRoot,'run_manifest.json'),manifest);

environment = table("MATLAB_RELEASE","MATLAB",true,"R2024a", ...
    "R2024a","PASS",true,"synthetic-time","synthetic fixture", ...
    'VariableNames',{'check_id','component','blocking','expected', ...
    'actual','status','available','checked_at','details'});
write_table_csv_17g(fullfile(runRoot,'environment.csv'),environment);

inputHashes = table( ...
    ["inputs/raw/基础参数.xlsx";"inputs/raw/输入数据.xlsx"], ...
    repmat(string(repmat('A',1,64)),2,1), ...
    repmat(string(repmat('A',1,64)),2,1), ...
    repmat("PASS",2,1), ...
    'VariableNames',{'relative_path','expectedSHA256', ...
    'actualSHA256','status'});
write_table_csv_17g(fullfile(runRoot,'input_hashes.csv'),inputHashes);

ids = stage_a1_acceptance_ids();
rowCount = numel(ids);
acceptance = table(ids,repmat("synthetic requirement",rowCount,1), ...
    repmat("PASS",rowCount,1),repmat("synthetic actual",rowCount,1), ...
    repmat("equal",rowCount,1),repmat("PASS",rowCount,1), ...
    true(rowCount,1),repmat("synthetic/evidence",rowCount,1), ...
    repmat("synthetic-time",rowCount,1), ...
    'VariableNames',{'test_id','requirement','threshold','actual_value', ...
    'comparison','status','blocking','evidence_path','checked_at'});
write_table_csv_17g(fullfile(runRoot,'acceptance', ...
    'acceptance_results.csv'),acceptance);

blocks = table([8;9;10],[24;24;24],[3;3;5],[27;27;29], ...
    [27;27;29],repmat("PASS",3,1), ...
    'VariableNames',{'hour','n_primal','n_equalities','kkt_dimension', ...
    'expected_dimension','status'});
write_table_csv_17g(fullfile(runRoot,'matrices','block_dimensions.csv'),blocks);

matrices = table(["full_kkt";"global_core"],[471;16],[471;16], ...
    [1024;96],true(2,1), ...
    [string(repmat('B',1,64));string(repmat('C',1,64))], ...
    ["matrices/full_kkt.mat";"matrices/recursive_blocks.mat"], ...
    'VariableNames',{'matrix_name','rows','columns','nnz','is_sparse', ...
    'sha256','path'});
write_table_csv_17g(fullfile(runRoot,'matrices','matrix_manifest.csv'),matrices);

comparison = table("overall_direction_relative_2norm",1e-14,1e-10, ...
    "PASS",'VariableNames',{'metric_id','actual_value','threshold','status'});
write_table_csv_17g(fullfile(runRoot,'iterations', ...
    'direction_comparison.csv'),comparison);
residuals = table(["full_kkt_direct_hard_limit"; ...
    "recursive_direction_reinserted_in_full_kkt"],[1e-14;1e-14], ...
    [1;1],[1e-14;1e-14],[1e-10;1e-10],repmat("PASS",2,1), ...
    'VariableNames',{'route','absolute_residual_2norm','rhs_2norm', ...
    'relative_residual_2norm','threshold','status'});
write_table_csv_17g(fullfile(runRoot,'iterations','residual_summary.csv'), ...
    residuals);

issues = new_stage_a1_issue_log();
write_table_csv_17g(fullfile(runRoot,'issues','issue_log.csv'),issues);
inventory = table(uint32([1;2]),["synthetic/test_one"; ...
    "synthetic/test_two"],["a.m";"b.m"], ...
    'VariableNames',{'test_order','test_name','source_file'});
write_table_csv_17g(fullfile(runRoot,'tests','test_inventory.csv'),inventory);
results = table(inventory.test_name,true(2,1),false(2,1),false(2,1), ...
    [0.1;0.2],repmat("",2,1), ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds','details'});
write_table_csv_17g(fullfile(runRoot,'tests','test_results.csv'),results);
write_json_file(fullfile(runRoot,'tests','test_summary.json'),struct( ...
    'test_total',2,'test_passed',2,'test_failed',0,'test_incomplete',0));

soc = table(["SOC-DYN-H08-S01";"SOC-END-H10-S01"],[8;10],[1;1], ...
    ["EQ-START";"EQ-END"],["SOC=0.5E; no hour 7 predecessor"; ...
    "terminal SOC=0.5E equality"],["predecessor=NA"; ...
    "terminal=true"],repmat("PASS",2,1), ...
    'VariableNames',{'check_id','hour','storage','equation_id', ...
    'expected','actual','status'});
write_table_csv_17g(fullfile(runRoot,'indices','soc_boundary_audit.csv'),soc);
fixed = table("A1-FIXED-ZERO-EXACT",0,0,0,true,true,true,"PASS", ...
    "synthetic nonvacuous regression is recorded in test evidence", ...
    'VariableNames',{'check_id','count','maximum_absolute_value', ...
    'maximum_absolute_direction','values_exact_zero', ...
    'directions_exact_zero','vacuous','status','details'});
write_table_csv_17g(fullfile(runRoot,'indices','fixed_zero_audit.csv'),fixed);
scan = table("FORBIDDEN-INV",10,0,"PASS","No forbidden match.", ...
    'VariableNames',{'check_id','files_scanned','match_count','status', ...
    'details'});
write_table_csv_17g(fullfile(runRoot,'diagnostics','code_scan.csv'),scan);
write_json_file(fullfile(runRoot,'diagnostics','linearization_identity.json'), ...
    struct('linearization_identity','synthetic-shared-identity', ...
    'all_identities_equal',true,'shared_linearization_object_count',1));
end

function xml = read_document_xml(docxPath)
extractRoot = string(tempname(tempdir));
[created,message] = mkdir(extractRoot);
assert(created,message);
cleanup = onCleanup(@() remove_test_tree(extractRoot));
unzip(docxPath,extractRoot);
xml = string(fileread(fullfile(extractRoot,'word','document.xml')));
end

function ids = stage_a1_acceptance_ids()
ids = ["SA1-ENV-001";"SA1-DATA-001";"SA1-MAT-001"; ...
    "SA1-MAT-002";"SA1-BLK-001";"SA1-LIN-001"; ...
    "SA1-BND-001";"SA1-EQ-001";"SA1-EQ-002";"SA1-EQ-003"; ...
    "SA1-IDX-001";"SA1-IDX-002";"SA1-NUM-001"; ...
    "SA1-ART-001";"SA1-SCOPE-001"];
end

function name = string_filename(pathValue)
[~,base,extension] = fileparts(char(pathValue));
name = string([base,extension]);
end

function remove_test_tree(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,'s');
end
end
