function tests = test_stage_b2c_90day_day62_delayed_inequality
% Replay checkpoint 12 and isolate the retained legacy expanded-border route.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(genpath(fullfile(root,"src")));
sourceRoot = fullfile(root,"runs", ...
    "B2C_90DAY_GLOBAL_KKT_GATE_FORMAL_20260819_212754");
runtimePath = fullfile(sourceRoot,"diagnostics", ...
    "resolved_runtime_configuration.mat");
cacheSummaryPath = fullfile(sourceRoot,"diagnostics","cache_summary.csv");
checkpointPath = fullfile(sourceRoot,"checkpoints","iteration_012.mat");
assumeTrue(testCase,isfile(runtimePath) && isfile(cacheSummaryPath) && ...
    isfile(checkpointPath), ...
    "The historical checkpoint-12 replay artifacts are unavailable.");

runtime = load(runtimePath,"config");
config = runtime.config;
cacheSummary = readtable(cacheSummaryPath,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
dataPath = cacheSummary.path(cacheSummary.cache_type=="annual_data");
indexPath = cacheSummary.path(cacheSummary.cache_type=="canonical_index");
assumeTrue(testCase,isscalar(dataPath) && isfile(dataPath) && ...
    isscalar(indexPath) && isfile(indexPath), ...
    "The exact data/index caches used by the 90-day run are unavailable.");
dataPayload = load(dataPath,"data");
indexPayload = load(indexPath,"index");
checkpointPayload = load(checkpointPath,"checkpoint");
linearization = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    checkpointPayload.checkpoint.state,dataPayload.data,indexPayload.index, ...
    config,"B-2C-90DAY-DAY62-DELAYED-INEQUALITY-REGRESSION");

runId = "B2C_90DAY_DAY62_DELAYED_INEQUALITY_REGRESSION_"+ ...
    string(datetime("now","Format","yyyyMMdd_HHmmss_SSS"));
artifactRoot = fullfile(root,"runs",runId,"diagnostics");
mkdir(artifactRoot);
testCase.TestData.config = config;
testCase.TestData.linearization = linearization;
testCase.TestData.artifact_root = artifactRoot;
end

function testDay62AutomaticallyUsesEquivalentExpandedBorder(testCase)
config = testCase.TestData.config;
recursive = rkkt.solver.solve_stage_b2c_daily_joint_direction( ...
    testCase.TestData.linearization, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses=config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation=config.compensated_core_accumulation, ...
    JointMicroborderEnabled=false);

diagnostics = recursive.diagnostics;
expanded = diagnostics.adaptive_delayed_inequality;
verifyTrue(testCase, ...
    diagnostics.adaptive_delayed_inequality_elimination_used);
verifyEqual(testCase, ...
    diagnostics.adaptive_delayed_inequality_day_ids,62);
verifyEqual(testCase,expanded.day_ids,62);
verifyEqual(testCase,expanded.problem_day_count,1);
verifyEqual(testCase,expanded.total_delayed_inequality_count,1040);
verifyEqual(testCase,expanded.base_dimension,634);
verifyEqual(testCase,expanded.expanded_dimension,1674);
verifyLessThanOrEqual(testCase,expanded.reduced_matrix_relative_error, ...
    config.reduced_symmetry_tolerance);
verifyLessThanOrEqual(testCase,expanded.reduced_rhs_relative_error, ...
    config.reduced_symmetry_tolerance);
verifyEqual(testCase,expanded.factorization_method, ...
    "equilibrated_sparse_lu");
verifyFalse(testCase,expanded.regularization_used);
verifyFalse(testCase,expanded.pseudoinverse_used);
verifyFalse(testCase,expanded.complete_kkt_solved);

position = find([recursive.responses.day_id]==62,1);
verifyNotEmpty(testCase,position);
verifyGreaterThan(testCase, ...
    recursive.responses(position).factor.maximum_column_relative_residual, ...
    config.local_linear_solve_residual_tolerance);
verifyLessThanOrEqual(testCase, ...
    recursive.core.direct_daily_correction.final_relative_residual, ...
    config.local_linear_solve_residual_tolerance);
verifyLessThanOrEqual(testCase, ...
    diagnostics.candidate_kkt_relative_residual, ...
    config.recursive_full_kkt_residual_tolerance);
verifyTrue(testCase,recursive.core.direct_daily_correction.both_targets_met);
verifyEqual(testCase,recursive.core.factor.method, ...
    "equilibrated_sparse_lu");
verifyEqual(testCase,recursive.core.factor.factorization_count,1);
verifyEqual(testCase, ...
    recursive.core.factor.refinement_additional_factorization_count,0);
verifyFalse(testCase,recursive.full_direction_consumed);
verifyTrue(testCase,recursive.no_full_direction_fallback);

evidence = table(62,expanded.total_delayed_inequality_count, ...
    expanded.base_dimension,expanded.expanded_dimension, ...
    expanded.reduced_matrix_relative_error, ...
    expanded.reduced_rhs_relative_error, ...
    recursive.core.direct_daily_correction.final_relative_residual, ...
    diagnostics.candidate_kkt_relative_residual, ...
    'VariableNames',{'day_id','delayed_inequality_count', ...
    'base_dimension','expanded_dimension', ...
    'reduced_matrix_relative_error','reduced_rhs_relative_error', ...
    'expanded_border_relative_residual','reconstructed_kkt_relative'});
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(testCase.TestData.artifact_root, ...
    "day62_delayed_inequality_regression.csv"),evidence);
end
