function tests = test_stage_b2c_90day_global_kkt_core_correction
% Replay iteration 11 and require the current adaptive formal direction.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(genpath(fullfile(root,"src")));
sourceRoot = fullfile(root,"runs", ...
    "B2C_90DAY_CORE_CONSISTENCY_FORMAL_20260814_214137");
runtimePath = fullfile(sourceRoot,"diagnostics", ...
    "resolved_runtime_configuration.mat");
cacheSummaryPath = fullfile(sourceRoot,"diagnostics","cache_summary.csv");
checkpointPath = fullfile(sourceRoot,"checkpoints","iteration_011.mat");
assumeTrue(testCase,isfile(runtimePath) && isfile(cacheSummaryPath) && ...
    isfile(checkpointPath), ...
    "The historical 90-day checkpoint-11 replay artifacts are unavailable.");

runtime = load(runtimePath,"config");
config = runtime.config;
cacheSummary = readtable(cacheSummaryPath,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
dataPath = cacheSummary.path(cacheSummary.cache_type=="annual_data");
indexPath = cacheSummary.path(cacheSummary.cache_type=="canonical_index");
assumeTrue(testCase,isscalar(dataPath) && isfile(dataPath) && ...
    isscalar(indexPath) && isfile(indexPath), ...
    "The exact data/index caches used by the 90-day run are unavailable.");
dataPayload = load(dataPath,"data");
indexPayload = load(indexPath,"index");
checkpointPayload = load(checkpointPath,"checkpoint");
linearization = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    checkpointPayload.checkpoint.state,dataPayload.data,indexPayload.index, ...
    config,"B-2C-90DAY-GLOBAL-KKT-CORE-REGRESSION");

runId = "B2C_90DAY_GLOBAL_KKT_CORE_REGRESSION_"+ ...
    string(datetime("now","Format","yyyyMMdd_HHmmss_SSS"));
artifactRoot = fullfile(root,"runs",runId,"diagnostics");
mkdir(artifactRoot);
testCase.TestData.config = config;
testCase.TestData.linearization = linearization;
testCase.TestData.artifact_root = artifactRoot;
end

function testAdaptiveBorderSupersedesCoreCorrectionWhenTriggered(testCase)
config = testCase.TestData.config;
recursive = rkkt.solver.solve_stage_b2c_daily_joint_direction( ...
    testCase.TestData.linearization, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses=config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation=config.compensated_core_accumulation);

correction = recursive.core.direct_daily_correction;
verifyLessThanOrEqual(testCase,correction.initial_relative_residual, ...
    config.local_linear_solve_residual_tolerance);
verifyLessThanOrEqual(testCase, ...
    correction.initial_reconstructed_kkt_relative_residual, ...
    config.recursive_full_kkt_residual_tolerance);
verifyFalse(testCase,correction.global_kkt_correction_triggered);
verifyEqual(testCase,correction.passes_applied,0);
verifyTrue(testCase,correction.target_met);
verifyTrue(testCase,correction.both_targets_met);
verifyLessThanOrEqual(testCase,correction.final_relative_residual, ...
    config.local_linear_solve_residual_tolerance);
verifyLessThanOrEqual(testCase, ...
    correction.final_reconstructed_kkt_relative_residual, ...
    config.recursive_full_kkt_residual_tolerance);
verifyEqual(testCase, ...
    correction.final_reconstructed_kkt_relative_residual, ...
    correction.initial_reconstructed_kkt_relative_residual);
verifyTrue(testCase, ...
    recursive.diagnostics.adaptive_delayed_inequality_elimination_used);
verifyTrue(testCase,ismember(62, ...
    recursive.diagnostics.adaptive_delayed_inequality_day_ids));
verifyEqual(testCase,recursive.core.factor.method, ...
    "equilibrated_sparse_lu");
verifyEqual(testCase,correction.daily_additional_factorization_count,0);
verifyEqual(testCase,correction.core_additional_factorization_count,0);
verifyEqual(testCase, ...
    recursive.diagnostics.daily_recovery_additional_factorization_count,0);
verifyFalse(testCase,recursive.full_direction_consumed);
verifyTrue(testCase,recursive.no_full_direction_fallback);

pass = (0:numel(correction.relative_residual_history)-1).';
history = table(pass,correction.relative_residual_history(:), ...
    correction.reconstructed_kkt_relative_residual_history(:), ...
    correction.combined_gate_history(:), ...
    'VariableNames',{'pass','core_relative', ...
    'reconstructed_kkt_relative','combined_gate'});
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(testCase.TestData.artifact_root, ...
    "global_kkt_core_correction_history.csv"),history);
end
