function tests = test_stage_b2c_day60_direct_factor_backsolve
% Replay the stopped 60-day state with the legacy expanded-border route isolated.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(genpath(fullfile(root,"src")));
checkpointPath = fullfile(root,"runs", ...
    "B2C_60DAY_DIRECT_BACKSOLVE_20260813_1843","checkpoints", ...
    "iteration_031.mat");
formalRoot = fullfile(root,"runs", ...
    "B2C_60DAY_CORE_CONSISTENCY_FORMAL_20260814_211705");
runtimePath = fullfile(formalRoot,"diagnostics", ...
    "resolved_runtime_configuration.mat");
cacheSummaryPath = fullfile(formalRoot,"diagnostics","cache_summary.csv");
assumeTrue(testCase,isfile(checkpointPath) && isfile(runtimePath) && ...
    isfile(cacheSummaryPath), ...
    "The historical day-60 replay artifacts are not present.");
runtime = load(runtimePath,"config");
config = runtime.config;
cacheSummary = readtable(cacheSummaryPath,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
dataPath = cacheSummary.path(cacheSummary.cache_type=="annual_data");
indexPath = cacheSummary.path(cacheSummary.cache_type=="canonical_index");
assumeTrue(testCase,isscalar(dataPath) && isfile(dataPath) && ...
    isscalar(indexPath) && isfile(indexPath), ...
    "The exact data/index caches used by the 60-day run are unavailable.");
dataPayload = load(dataPath,"data");
indexPayload = load(indexPath,"index");
data = dataPayload.data;
index = indexPayload.index;
loaded = load(checkpointPath,"checkpoint");
linearization = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    loaded.checkpoint.state,data,index,config,"DAY60-DIRECT-REPLAY");
recursive = rkkt.solver.solve_stage_b2c_daily_joint_direction( ...
    linearization, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses= ...
        config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation= ...
        config.compensated_core_accumulation, ...
    JointMicroborderEnabled=false);
testCase.TestData.config = config;
testCase.TestData.recursive = recursive;
end

function testStoppedDirectionPassesWithAdaptiveExpandedBorder(testCase)
r = testCase.TestData.recursive;
verifyFalse(testCase,r.diagnostics.daily_direct_factor_backsolve_used);
verifyTrue(testCase, ...
    r.diagnostics.adaptive_delayed_inequality_elimination_used);
verifyTrue(testCase,ismember(60, ...
    r.diagnostics.adaptive_delayed_inequality_day_ids));
verifyEqual(testCase, ...
    r.diagnostics.daily_recovery_additional_factorization_count,0);
verifyEqual(testCase, ...
    r.core.direct_daily_correction.daily_additional_factorization_count,0);
verifyEqual(testCase, ...
    r.core.direct_daily_correction.core_additional_factorization_count,0);
verifyTrue(testCase, ...
    r.core.direct_daily_correction.retained_core_factor_reused);
verifyEqual(testCase, ...
    r.core.direct_daily_correction.maximum_passes,10);
verifyEqual(testCase,r.core.direct_daily_correction.passes_applied,0);
verifyTrue(testCase,r.core.direct_daily_correction.target_met);
verifyTrue(testCase, ...
    r.core.direct_daily_correction.compensated_accumulation_used);
verifyLessThanOrEqual(testCase, ...
    r.diagnostics.candidate_kkt_relative_residual, ...
    testCase.TestData.config.recursive_full_kkt_residual_tolerance);
verifyTrue(testCase,r.no_full_direction_fallback);
verifyFalse(testCase,r.full_direction_consumed);
end

function testDay60IsRecoveredInsideExpandedBorder(testCase)
r = testCase.TestData.recursive;
position = find([r.responses.day_id]==60,1);
verifyNotEmpty(testCase,position);
day60 = r.recovery.daily_direct_backsolve(position);
verifyEqual(testCase,day60.day_id,60);
verifyFalse(testCase,day60.retained_factor_reused);
verifyFalse(testCase,day60.direct_final_rhs_solve);
verifyEqual(testCase,day60.additional_factorization_count,0);
verifyGreaterThan(testCase, ...
    r.responses(position).factor.maximum_column_relative_residual, ...
    testCase.TestData.config.local_linear_solve_residual_tolerance);
verifyLessThanOrEqual(testCase, ...
    r.core.direct_daily_correction.final_relative_residual, ...
    testCase.TestData.config.local_linear_solve_residual_tolerance);
verifyEqual(testCase,r.core.factor.method,"equilibrated_sparse_lu");
end
