function tests = test_stage_b2c_recursive_block_equivalence
%TEST_STAGE_B2C_RECURSIVE_BLOCK_EQUIVALENCE Audit block-native operators.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(root,"src"));
settings = rkkt.config.build_stage_b2c_run_settings(root, ...
    DayStart=14,DayEnd=20,AuditMode="recursive_only", ...
    RunOutputMode="lightweight",ParallelEnabled=false,CacheEnabled=true);
[data,~] = rkkt.cache.load_or_build_project_data(root,Enabled=true);
config = rkkt.model.build_stage_b2c_runtime_configuration(root,settings,data);
[index,~] = rkkt.cache.load_or_build_stage_b2c_index( ...
    root,data,config,Enabled=true);
[template,~] = rkkt.cache.load_or_build_stage_b2c_recursive_block_template( ...
    root,data,index,config,Enabled=true);
[state,~] = rkkt.model.initialize_stage_b2c_state( ...
    data,index,config,RecursiveBlockTemplate=template);
testCase.TestData.root = root;
testCase.TestData.data = data;
testCase.TestData.config = config;
testCase.TestData.index = index;
testCase.TestData.template = template;
testCase.TestData.state = state;
end

function testInitialOperatorsAndDirectionMatchFullMatrixRoute(testCase)
data = testCase.TestData.data;
config = testCase.TestData.config;
index = testCase.TestData.index;
template = testCase.TestData.template;
state = testCase.TestData.state;
block = rkkt.model.update_stage_b2c_recursive_block_linearization( ...
    state,template);
legacy = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    state,data,index,config);

verifyFalse(testCase,isfield(block,"H"));
verifyFalse(testCase,isfield(block,"A"));
verifyFalse(testCase,isfield(block,"G"));
verifyFalse(testCase,block.global_matrices_assembled);
verifyEqual(testCase,block.r_eq,legacy.r_eq,"AbsTol",0);
verifyEqual(testCase,block.r_ineq,legacy.r_ineq,"AbsTol",0);
verifyEqual(testCase,block.r_dual,legacy.r_dual,"AbsTol",0);
verifyEqual(testCase,block.r_comp,legacy.r_comp,"AbsTol",0);

rng(1);
x = randn(block.counts.primal,1);
y = randn(block.counts.equalities,1);
z = randn(block.counts.inequalities,1);
verifyEqual(testCase, ...
    rkkt.model.apply_stage_b2c_equality_jacobian(block,x), ...
    legacy.A*x,"AbsTol",0);
verifyEqual(testCase, ...
    rkkt.model.apply_stage_b2c_equality_jacobian( ...
        block,y,Transpose=true),legacy.A.'*y,"AbsTol",0);
verifyEqual(testCase, ...
    rkkt.model.apply_stage_b2c_inequality_jacobian(block,x), ...
    legacy.G*x,"AbsTol",0);
verifyLessThanOrEqual(testCase,norm( ...
    rkkt.model.apply_stage_b2c_inequality_jacobian( ...
        block,z,Transpose=true)-legacy.G.'*z,inf),64*eps(norm(z,inf)));
verifyEqual(testCase, ...
    rkkt.model.apply_stage_b2c_lagrangian_hessian(block,x), ...
    legacy.H*x,"AbsTol",0);

legacyStructure = ...
    rkkt.solver.build_stage_b2c_daily_joint_structure_template(legacy);
legacyDirection = rkkt.solver.solve_stage_b2c_daily_joint_direction( ...
    legacy,DailyJointStructureTemplate=legacyStructure, ...
    JointMicroborderEnabled=false, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses=config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation=config.compensated_core_accumulation);
blockDirection = rkkt.solver.solve_stage_b2c_daily_joint_direction( ...
    block,JointMicroborderEnabled=false, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses=config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation=config.compensated_core_accumulation);
verifyEqual(testCase,blockDirection.direction,legacyDirection.direction, ...
    "AbsTol",0);
verifyLessThanOrEqual(testCase, ...
    blockDirection.diagnostics.candidate_kkt_relative_residual, ...
    config.recursive_full_kkt_residual_tolerance);
for d = 1:numel(block.partition.day)
    verifyEqual(testCase,block.partition.day(d).matrix, ...
        legacyDirection.partition.day(d).matrix,"AbsTol",0);
    verifyEqual(testCase,block.partition.day(d).coupling, ...
        legacyDirection.partition.day(d).coupling,"AbsTol",0);
    verifyEqual(testCase,block.partition.day(d).rhs, ...
        legacyDirection.partition.day(d).rhs,"AbsTol",0);
end
end
