function tests = testA43Finalizer
%TEST_STAGE_A4_3_FINALIZER Verify deterministic A4-3 terminalization.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
originalPath = path;
addpath(root);
addpath(genpath(fullfile(root,"src")));
testCase.addTeardown(@()path(originalPath));
testCase.TestData.root = root;
end

function testPreparedEvidenceIsReusedForUniquePassTerminalization(testCase)
fixture = make_fixture(testCase,"CONVERGED");
stageHash = compute_sha256_file(fullfile(fixture.project,"CURRENT_STAGE.md"));
prepared = finalize_stage_a4_3_run( ...
    fixture.project,fixture.run_id,"FinalizeManifest",false);
verifyFalse(testCase,prepared.manifest_finalized);
verifyEqual(testCase,prepared.manifest_status,"RUNNING");
verifyEqual(testCase,prepared.candidate_terminal_status,"PASS");
verifyFalse(testCase,prepared.evidence_inventory_reused);
inventoryHash = compute_sha256_file(prepared.evidence_hashes_path);

finalized = finalize_stage_a4_3_run(fixture.project,fixture.run_id);
verifyTrue(testCase,finalized.manifest_finalized);
verifyEqual(testCase,finalized.manifest_status,"PASS");
verifyEqual(testCase,finalized.candidate_terminal_status,"PASS");
verifyTrue(testCase,finalized.evidence_inventory_reused);
verifyEqual(testCase,compute_sha256_file( ...
    finalized.evidence_hashes_path),inventoryHash);
verifyEqual(testCase,compute_sha256_file(fullfile( ...
    fixture.project,"CURRENT_STAGE.md")),stageHash);
verifyTrue(testCase,isfile(fullfile(fixture.run_root,"acceptance", ...
    "acceptance_results.pre_finalization.csv")));
verifyTrue(testCase,isfile(fullfile(fixture.run_root,"issues", ...
    "issue_log.pre_finalization.csv")));
verifyTrue(testCase,isfile(fullfile(fixture.run_root,"issues", ...
    "decision_log.pre_finalization.csv")));

manifest = jsondecode(fileread(fullfile( ...
    fixture.run_root,"run_manifest.json")));
verifyEqual(testCase,string(manifest.status),"PASS");
verifyFalse(testCase,manifest.stage_b_entered);
verifyTrue(testCase,manifest.current_stage_preserved);
acceptance = readtable(fullfile(fixture.run_root,"acceptance", ...
    "acceptance_results.csv"),"TextType","string","Delimiter",",");
verifyEqual(testCase,height(acceptance),7);
verifyTrue(testCase,all(acceptance.status=="PASS"));
hashes = readtable(finalized.evidence_hashes_path,"TextType","string", ...
    "Delimiter",",");
verifyFalse(testCase,any(hashes.relative_path=="run_manifest.json"));
verifyFalse(testCase,any(hashes.relative_path== ...
    "acceptance/evidence_hashes.csv"));
verifyTrue(testCase,any(hashes.relative_path== ...
    "reports/report_visual_qa.csv"));
verifyTrue(testCase,any(hashes.relative_path== ...
    "tests/static_check_summary.csv"));
end

function testMaxIterationsCanNeverBecomePass(testCase)
fixture = make_fixture(testCase,"MAX_ITERATIONS");
outcome = finalize_stage_a4_3_run(fixture.project,fixture.run_id);
verifyEqual(testCase,outcome.numerical_terminal_state,"MAX_ITERATIONS");
verifyEqual(testCase,outcome.candidate_terminal_status,"FAIL_RETRYABLE");
verifyEqual(testCase,outcome.manifest_status,"FAIL_RETRYABLE");
verifyGreaterThan(testCase,height(outcome.issues),0);
verifyTrue(testCase,any(contains(outcome.issues.issue_id, ...
    "MAX_ITERATIONS")));
manifest = jsondecode(fileread(fullfile( ...
    fixture.run_root,"run_manifest.json")));
verifyEqual(testCase,string(manifest.status),"FAIL_RETRYABLE");
verifyFalse(testCase,manifest.a4_3_acceptance_all_pass);
end

function testTerminalManifestCannotBeOverwritten(testCase)
fixture = make_fixture(testCase,"CONVERGED");
finalize_stage_a4_3_run(fixture.project,fixture.run_id);
manifestPath = fullfile(fixture.run_root,"run_manifest.json");
before = compute_sha256_file(manifestPath);
verifyError(testCase,@()finalize_stage_a4_3_run( ...
    fixture.project,fixture.run_id), ...
    "stageA4:a43:finalizer:ManifestAlreadyFinal");
verifyEqual(testCase,compute_sha256_file(manifestPath),before);
end

function testChangedEvidenceAfterPreparationIsNotOverwritten(testCase)
fixture = make_fixture(testCase,"CONVERGED");
prepared = finalize_stage_a4_3_run( ...
    fixture.project,fixture.run_id,"FinalizeManifest",false);
inventoryHash = compute_sha256_file(prepared.evidence_hashes_path);
write_text(fullfile(fixture.run_root,"git_state.txt"), ...
    "mutated after evidence freeze");
verifyError(testCase,@()finalize_stage_a4_3_run( ...
    fixture.project,fixture.run_id), ...
    "stageA4:a43:finalizer:EvidenceInventoryChanged");
verifyEqual(testCase,compute_sha256_file( ...
    prepared.evidence_hashes_path),inventoryHash);
manifest = jsondecode(fileread(fullfile( ...
    fixture.run_root,"run_manifest.json")));
verifyEqual(testCase,string(manifest.status),"RUNNING");
end

function testTamperedVisualPageLeavesRunRecoverable(testCase)
fixture = make_fixture(testCase,"CONVERGED");
visualPath = fullfile(fixture.run_root,"reports", ...
    "report_visual_qa.csv");
visual = readtable(visualPath,"TextType","string","Delimiter",",");
write_text(visual.image_path(1),"not a PNG");
verifyError(testCase,@()finalize_stage_a4_3_run( ...
    fixture.project,fixture.run_id), ...
    "stageA4:a43:finalizer:VisualImageHash");
manifest = jsondecode(fileread(fullfile( ...
    fixture.run_root,"run_manifest.json")));
verifyEqual(testCase,string(manifest.status),"RUNNING");
verifyFalse(testCase,isfile(fullfile(fixture.run_root,"acceptance", ...
    "evidence_hashes.csv")));
end

function fixture = make_fixture(testCase,terminalState)
project = string(tempname(tempdir));
mkdir(project);
testCase.addTeardown(@()remove_tree(project));
mkdir(fullfile(project,"runs"));
mkdir(fullfile(project,"stages","stage_A4"));
mkdir(fullfile(project,"tests"));
copyfile(fullfile(testCase.TestData.root,"src"), ...
    fullfile(project,"src"));
copyfile(fullfile(testCase.TestData.root,"config"), ...
    fullfile(project,"config"));
copyfile(fullfile(testCase.TestData.root,"main_stage_A4_3.m"), ...
    fullfile(project,"main_stage_A4_3.m"));
copyfile(fullfile(testCase.TestData.root,"stages","stage_A4", ...
    "阶段A4_验收矩阵.csv"),fullfile(project,"stages","stage_A4", ...
    "阶段A4_验收矩阵.csv"));
copyfile(fullfile(testCase.TestData.root,"tests", ...
    "stage_A4_3_expected_test_inventory.csv"), ...
    fullfile(project,"tests", ...
    "stage_A4_3_expected_test_inventory.csv"));
copyfile(fullfile(testCase.TestData.root,"tests", ...
    "stage_A4_RNS_1_expected_test_inventory.csv"), ...
    fullfile(project,"tests", ...
    "stage_A4_RNS_1_expected_test_inventory.csv"));
copyfile(fullfile(testCase.TestData.root,"tests", ...
    "stage_A4_2D_2A_R1_expected_test_inventory.csv"), ...
    fullfile(project,"tests", ...
    "stage_A4_2D_2A_R1_expected_test_inventory.csv"));
copyfile(fullfile(testCase.TestData.root,"tests", ...
    "stage_A4_3_finalizer_expected_test_inventory.csv"), ...
    fullfile(project,"tests", ...
    "stage_A4_3_finalizer_expected_test_inventory.csv"));
write_text(fullfile(project,"CURRENT_STAGE.md"),strjoin([ ...
    "# 当前阶段状态"
    ""
    "- `stage_id`: `stage_A4`"
    "- `status`: `READY`"
    "- `next_stage_when_passed`: `stage_B`"],newline)+newline);

runId = "A4_3_FINALIZER_"+terminalState;
runRoot = fullfile(project,"runs",runId);
directories = ["iterations","checkpoints","matrices","acceptance", ...
    "results","diagnostics","reports","reports/rendered","tests","issues"];
for directory = directories
    mkdir(fullfile(runRoot,replace(directory,"/",filesep)));
end
count = 1;
converged = terminalState=="CONVERGED";
if terminalState=="MAX_ITERATIONS"
    count = 100;
end
metrics = metrics_fixture(converged);
[iterations,directions] = trajectory_fixture(count,converged);
executionAudit = struct( ...
    "one_full_kkt_audit_per_accepted_iteration",true, ...
    "direction_audits_pass",true, ...
    "no_full_direction_fallback",true, ...
    "forbidden_execution_pass",true);
summary = struct( ...
    "run_terminal_state",terminalState, ...
    "convergence_achieved",converged, ...
    "iteration_count",count, ...
    "full_kkt_audit_count",count, ...
    "final_metrics",metrics, ...
    "direction_audit",directions, ...
    "iteration_summary",iterations, ...
    "execution_audit",executionAudit);
final_state = struct("fixture",true);
save(fullfile(runRoot,"a4_3_solver_result.mat"), ...
    "summary","final_state","-v7");
write_table_csv_17g(fullfile(runRoot,"iterations", ...
    "iteration_summary.csv"),iterations);
write_table_csv_17g(fullfile(runRoot,"iterations", ...
    "direction_audit.csv"),directions);

gitCommit = string(repmat('a',1,40));
manifest = struct( ...
    "run_id",runId,"stage_id","stage_A4","status","RUNNING", ...
    "started_at","2026-07-26T00:00:00+08:00","ended_at",NaN, ...
    "model_contract_version","v1.0","git_commit",gitCommit, ...
    "input_hashes",struct( ...
        "base_parameters",string(repmat('b',1,64)), ...
        "timeseries",string(repmat('c',1,64))), ...
    "a4_3_run_terminal_state",terminalState, ...
    "convergence_achieved",converged, ...
    "historical_runs_unchanged",true, ...
    "stage_b_entered",false, ...
    "convergence_coordinate","positive_scalar_unitized_kkt", ...
    "newton_direction_count",count, ...
    "accepted_state_update_count",count, ...
    "full_kkt_audit_count",count);
write_json_file(fullfile(runRoot,"run_manifest.json"),manifest);
copyfile(fullfile(project,"config","stage_A4_3.yaml"), ...
    fullfile(runRoot,"effective_config.yaml"));
write_text(fullfile(runRoot,"git_state.txt"), ...
    "fixture tracked clean"+newline);
write_table_csv_17g(fullfile(runRoot,"historical_runs_before.csv"), ...
    table("old-run","file",1,string(repmat('d',1,64)), ...
    'VariableNames',{'relativePath','entryType','bytes','sha256'}));
write_json_file(fullfile(runRoot,"historical_runs_audit.json"), ...
    struct("passed",true,"new_run_id",runId));

environment = table(["MATLAB";"SPARSE"],[true;true], ...
    ["PASS";"PASS"], ...
    'VariableNames',{'check_id','blocking','status'});
write_table_csv_17g(fullfile(runRoot,"environment.csv"),environment);
sha = [string(repmat('b',1,64));string(repmat('c',1,64))];
inputs = table(["基础参数.xlsx";"输入数据.xlsx"],sha,sha, ...
    ["PASS";"PASS"], ...
    'VariableNames',{'file_name','expectedSHA256', ...
    'actualSHA256','status'});
write_table_csv_17g(fullfile(runRoot,"input_hashes.csv"),inputs);

checkpoint = table((1:count).',repmat("PASS",count,1), ...
    'VariableNames',{'iteration','status'});
write_table_csv_17g(fullfile(runRoot,"checkpoints", ...
    "checkpoint_manifest.csv"),checkpoint);
matrix = table(["complete_kkt";"global_core"],[18836;16], ...
    [18836;16],["PASS";"PASS"], ...
    'VariableNames',{'matrix_name','rows','columns','status'});
write_table_csv_17g(fullfile(runRoot,"matrices", ...
    "matrix_manifest.csv"),matrix);
physical = physical_fixture();
write_table_csv_17g(fullfile(runRoot,"acceptance", ...
    "physical_audit.csv"),physical);
write_table_csv_17g(fullfile(runRoot,"results", ...
    "capacity_results.csv"),table((1:14).',(101:114).', ...
    'VariableNames',{'capacity_id','value'}));
write_table_csv_17g(fullfile(runRoot,"results", ...
    "hourly_dispatch_results.csv"),table(14,1,"PW",1,0, ...
    'VariableNames',{'day','hour','variable_name','asset_id','value'}));

write_static_evidence(project,runRoot,runId,gitCommit,summary);
write_test_evidence(project,runRoot,terminalState);
write_a43_specialty_evidence(project,runRoot,runId,gitCommit);
write_preliminary_logs(project,runRoot,runId,summary,physical);
write_report_evidence(runRoot,runId,gitCommit);
fixture = struct("project",project,"run_id",runId,"run_root",runRoot);
end

function metrics = metrics_fixture(converged)
if converged
    residual = 1e-12;
else
    residual = 1e-4;
end
metrics = struct( ...
    "r_eq_inf",residual, ...
    "r_ineq_inf",residual, ...
    "r_dual_scaled_inf",residual, ...
    "mean_lz_scaled",residual, ...
    "r_comp_scaled_inf",residual, ...
    "physical_inequality_violation",0);
end

function [iterations,directions] = trajectory_fixture(count,converged)
iteration = (1:count).';
state_revision = iteration;
convergence_passed = false(count,1);
if converged
    convergence_passed(end) = true;
end
iterations = table(iteration,state_revision,convergence_passed);
iterations.step_strategy = repmat("independent",count,1);
iterations.centering_sigma = repmat(0.1,count,1);
iterations.common_step_used = false(count,1);
iterations.dynamic_sigma_used = false(count,1);
iterations.predictor_corrector_used = false(count,1);
iterations.line_search_used = false(count,1);
iterations.regularization_used = false(count,1);
iterations.automatic_symmetrization_used = false(count,1);
iterations.parallel_used = false(count,1);
iterations.full_kkt_direction_fallback_used = false(count,1);
state_revision_before = (0:count-1).';
state_revision_after = (1:count).';
small = repmat(1e-12,count,1);
truth = true(count,1);
directions = table(iteration,state_revision_before,state_revision_after, ...
    small,small,small,small,small,small,small,truth,truth,truth, ...
    'VariableNames',{'iteration','state_revision_before', ...
    'state_revision_after','direction_relative_error', ...
    'xi_relative_error','y_relative_error','l_relative_error', ...
    'z_relative_error','recursive_full_kkt_relative_residual', ...
    'full_kkt_relative_residual','no_full_direction_fallback', ...
    'full_kkt_audit_only','recursive_direction_is_official'});
end

function physical = physical_fixture()
audit_id = [ ...
    "A43-PHY-EQUALITY"
    "A43-PHY-POWER-BALANCE"
    "A43-PHY-SOC-CHAIN"
    "A43-PHY-SOC-TERMINAL"
    "A43-PHY-INEQUALITY"
    "A43-PHY-FIXED-ZERO-VALUE"
    "A43-PHY-FIXED-ZERO-DIRECTION"
    "A43-PHY-NO-INTERDAY-SOC"];
physical = table(audit_id,repmat("fixture",8,1), ...
    repmat("0",8,1),repmat("<=1e-8",8,1), ...
    repmat("PASS",8,1),repmat("fixture",8,1), ...
    'VariableNames',{'audit_id','requirement','actual_value', ...
    'threshold','status','evidence_path'});
end

function write_static_evidence(project,runRoot,runId,gitCommit,runResult)
originalPath = path;
pathGuard = onCleanup(@()path(originalPath));
addpath(char(project),"-begin");
addpath(genpath(fullfile(project,"src")),"-begin");
config = load_stage_a4_3_configuration(project);
[code,dependency] = scan_stage_a4_3_forbidden_code(project,config);
runtime = audit_stage_a4_3_forbidden_execution( ...
    runResult,config,code,dependency);
verify_static_fixture_clean(code,runtime,dependency);
scope = get_stage_a4_3_code_analyzer_scope(project,dependency);
advisories = fixture_analyzer(project,dependency,scope);
write_table_csv_17g(fullfile(runRoot,"tests", ...
    "code_analyzer_results.csv"), ...
    table(strings(0,1),zeros(0,1),zeros(0,1),strings(0,1), ...
    strings(0,1),'VariableNames', ...
    {'file','line','column','identifier','message'}));
write_table_csv_17g(fullfile(runRoot,"tests", ...
    "code_analyzer_scope.csv"),scope);
write_table_csv_17g(fullfile(runRoot,"tests", ...
    "code_analyzer_advisories.csv"),advisories);
write_table_csv_17g(fullfile(runRoot,"diagnostics", ...
    "forbidden_code_audit.csv"),code);
write_table_csv_17g(fullfile(runRoot,"diagnostics", ...
    "forbidden_execution_audit.csv"),runtime);
write_table_csv_17g(fullfile(runRoot,"diagnostics", ...
    "dependency_closure_sha256.csv"),dependency);
copyfile(fullfile(project,"CURRENT_STAGE.md"),fullfile(runRoot,"tests", ...
    "CURRENT_STAGE.md"));
check_id = [ ...
    "A43-STATIC-CODE-ANALYZER"
    "A43-STATIC-FORBIDDEN-CODE"
    "A43-STATIC-FORBIDDEN-EXECUTION"
    "A43-STATIC-GIT-DIFF-CHECK"
    "A43-STATIC-STAGE-GOVERNANCE"];
static = table(check_id,repmat("PASS",5,1), ...
    ["finding_count=0; scope_files="+string(height(scope))+ ...
        "; advisory_count="+string(height(advisories)); ...
        "all PASS";"all PASS";"exit=0";"stage_A4_READY=true"], ...
    ["=0";"PASS";"PASS";"exit=0";"stage_A4 / READY"], ...
    ["tests/code_analyzer_results.csv; tests/code_analyzer_scope.csv; tests/code_analyzer_advisories.csv"; ...
        "diagnostics/forbidden_code_audit.csv"; ...
    "diagnostics/forbidden_execution_audit.csv";"tests/git_diff_check.txt"; ...
    "tests/CURRENT_STAGE.md"], ...
    repmat("independently rebuilt fixture",5,1), ...
    repmat(string(runId),5,1), ...
    repmat(string(gitCommit),5,1), ...
    'VariableNames',{'check_id','status','actual_value','threshold', ...
    'evidence_path','details','run_id','git_commit'});
write_table_csv_17g(fullfile(runRoot,"tests", ...
    "static_check_summary.csv"),static);
analyzer = table(strings(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'file','line','column','identifier','message'});
write_table_csv_17g(fullfile(runRoot,"tests", ...
    "code_analyzer_results.csv"),analyzer);
write_text(fullfile(runRoot,"tests","git_diff_check.txt"), ...
    "exit=0"+newline);
clear pathGuard
end

function advisories = fixture_analyzer(project,dependency,scope)
file = strings(0,1); line = zeros(0,1); column = zeros(0,1);
identifier = strings(0,1); message = strings(0,1);
scopeNames = string(scope.relative_path);
nonblockingIds = ["MSNU","SPRIX"];
for k = 1:height(dependency)
    relative = string(dependency.relative_path(k));
    if endsWith(relative,".m","IgnoreCase",true)
        findings = checkcode(fullfile(project,replace(relative,"/",filesep)), ...
            "-id");
        for j = 1:numel(findings)
            identifierValue = string(findings(j).id);
            if ismember(relative,scopeNames) && ...
                    ~ismember(identifierValue,nonblockingIds)
                continue
            end
            file(end+1,1)=relative; %#ok<AGROW>
            line(end+1,1)=double(findings(j).line); %#ok<AGROW>
            if isempty(findings(j).column)
                column(end+1,1)=NaN; %#ok<AGROW>
            else
                column(end+1,1)=double(findings(j).column(1)); %#ok<AGROW>
            end
            identifier(end+1,1)=identifierValue; %#ok<AGROW>
            message(end+1,1)=string(findings(j).message); %#ok<AGROW>
        end
    end
end
advisories = table(file,line,column,identifier,message);
end

function verify_static_fixture_clean(code,runtime,dependency)
assert(height(code)==16 && all(string(code.status)=="PASS") && ...
    height(runtime)==8 && all(string(runtime.status)=="PASS") && ...
    ~isempty(dependency) && all(string(dependency.status)=="PASS"), ...
    "stageA4:test:FinalizerStaticFixture", ...
    "The independently rebuilt finalizer static fixture is not clean.");
end

function write_a43_specialty_evidence(project,runRoot,runId,gitCommit)
directory = fullfile(runRoot,"tests","a4_3_specialty");
mkdir(directory);
expectedPath = fullfile(project,"tests", ...
    "stage_A4_3_expected_test_inventory.csv");
inventory = readtable(expectedPath,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
write_table_csv_17g(fullfile(directory,"test_inventory.csv"),inventory);
n = height(inventory);
results = table(string(inventory.test_name),true(n,1),false(n,1), ...
    false(n,1),repmat(0.01,n,1),repmat("",n,1), ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds','details'});
write_table_csv_17g(fullfile(directory,"test_results.csv"),results);
write_junit(fullfile(directory,"test_results.xml"),inventory.test_name);
write_text(fullfile(directory,"matlab_test_console.log"), ...
    "stage_A4_3 fixed inventory: 27/27 PASS"+newline);
command = "run_stage_A4_3_tests(EvidenceDirectory='"+ ...
    string(fullfile(runRoot,"tests","a4_3_specialty"))+ ...
    "',CommandText='fixture "+runId+"')";
write_text(fullfile(directory,"test_command.txt"),command+newline);
summary = struct( ...
    "execution_status","COMPLETE","suite_label","stage_A4_3", ...
    "test_total",27,"test_passed",27,"test_failed",0, ...
    "test_incomplete",0,"test_names_unique",true, ...
    "expected_inventory_sha256",compute_sha256_file(expectedPath));
write_json_file(fullfile(directory,"test_summary.json"),summary);

names = ["test_inventory.csv";"test_results.csv";"test_results.xml"; ...
    "matlab_test_console.log";"test_command.txt";"test_summary.json"];
sha256 = strings(6,1);
bytes = zeros(6,1);
status = repmat("PASS",6,1);
for k = 1:6
    target = fullfile(directory,names(k));
    sha256(k) = compute_sha256_file(target);
    information = dir(target);
    bytes(k) = information.bytes;
end
write_table_csv_17g(fullfile(directory,"test_evidence_sha256.csv"), ...
    table(names,sha256,bytes,status));
identity = struct( ...
    "run_id",runId,"stage_id","stage_A4","git_commit",gitCommit, ...
    "suite_label","stage_A4_3", ...
    "expected_inventory_sha256",compute_sha256_file(expectedPath), ...
    "effective_config_sha256",compute_sha256_file( ...
        fullfile(runRoot,"effective_config.yaml")), ...
    "input_hashes_csv_sha256",compute_sha256_file( ...
        fullfile(runRoot,"input_hashes.csv")), ...
    "test_command_sha256",compute_sha256_file( ...
        fullfile(directory,"test_command.txt")));
write_json_file(fullfile(directory,"suite_identity.json"),identity);
end

function write_junit(pathValue,names)
lines = ["<?xml version=""1.0"" encoding=""UTF-8""?>"; ...
    "<testsuites tests="""+string(numel(names))+ ...
    """ failures=""0"" errors=""0"">"; ...
    "<testsuite name=""stage_A4_3"" tests="""+string(numel(names))+ ...
    """ failures=""0"" errors=""0"">"];
for k = 1:numel(names)
    lines(end+1,1) = "<testcase classname=""stage_A4_3"" name="""+ ...
        string(k)+""" time=""0""/>"; %#ok<AGROW>
end
lines = [lines;"</testsuite>";"</testsuites>"];
write_text(pathValue,strjoin(lines,newline)+newline);
end

function write_test_evidence(project,runRoot,terminalState)
a43 = readtable(fullfile(project,"tests", ...
    "stage_A4_3_expected_test_inventory.csv"), ...
    "TextType","string","VariableNamingRule","preserve","Delimiter",",");
if terminalState=="CONVERGED"
    rns = readtable(fullfile(project,"tests", ...
        "stage_A4_RNS_1_expected_test_inventory.csv"), ...
        "TextType","string","VariableNamingRule","preserve","Delimiter",",");
    r1 = readtable(fullfile(project,"tests", ...
        "stage_A4_2D_2A_R1_expected_test_inventory.csv"), ...
        "TextType","string","VariableNamingRule","preserve","Delimiter",",");
    suite_label = [ ...
        repmat("stage_A4_3",27,1)
        repmat("stage_A4_RNS_1",17,1)
        repmat("stage_A4_2D_2A_R1",18,1)
        repmat("stage_A4_regression_195",195,1)];
    test_name = [ ...
        string(a43.test_name)
        string(rns.test_name)
        string(r1.test_name)
        compose("stage_A4_regression_195/test_%03d",(1:195).')];
    campaignMode = "converged_full_validation";
    eligible = true;
    expectedCounts = [ ...
        "stage_A4_3","27"
        "stage_A4_RNS_1","17"
        "stage_A4_2D_2A_R1","18"
        "stage_A4_regression_195","195"];
else
    finalizerInventory = readtable(fullfile(project,"tests", ...
        "stage_A4_3_finalizer_expected_test_inventory.csv"), ...
        "TextType","string","VariableNamingRule","preserve","Delimiter",",");
    suite_label = [repmat("stage_A4_3",27,1); ...
        repmat("stage_A4_3_finalizer",5,1)];
    test_name = [string(a43.test_name);string(finalizerInventory.test_name)];
    campaignMode = "nonconverged_direct_validation";
    eligible = false;
    expectedCounts = ["stage_A4_3","27";"stage_A4_3_finalizer","5"];
end
n = numel(test_name);
results = table(suite_label,test_name,true(n,1),false(n,1), ...
    false(n,1),repmat(0.01,n,1),repmat("",n,1), ...
    'VariableNames',{'suite_label','test_name','passed','failed', ...
    'incomplete','duration_seconds','details'});
write_table_csv_17g(fullfile(runRoot,"tests","test_results.csv"),results);
write_json_file(fullfile(runRoot,"tests","test_summary.json"),struct( ...
    "execution_status","COMPLETE", ...
    "campaign_mode",campaignMode, ...
    "stage_pass_eligible",eligible, ...
    "test_total",n,"test_passed",n, ...
    "test_failed",0,"test_incomplete",0, ...
    "duration_seconds",0.01*n, ...
    "test_names_unique_within_suite",true, ...
    "suite_label_test_name_unique",true, ...
    "suite_counts",make_suite_counts(expectedCounts)));
end

function counts = make_suite_counts(expected)
counts = repmat(struct( ...
    "suite_label","", ...
    "test_total",0, ...
    "test_passed",0, ...
    "test_failed",0, ...
    "test_incomplete",0, ...
    "duration_seconds",0),size(expected,1),1);
for row = 1:size(expected,1)
    n = str2double(expected(row,2));
    counts(row).suite_label = char(expected(row,1));
    counts(row).test_total = n;
    counts(row).test_passed = n;
    counts(row).duration_seconds = 0.01*n;
end
end

function write_preliminary_logs(project,runRoot,runId,summary,physical)
acceptance = evaluate_stage_a4_3_acceptance( ...
    project,summary,physical);
write_table_csv_17g(fullfile(runRoot,"acceptance", ...
    "acceptance_results.csv"),acceptance);
issues = table(strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer', ...
    'symptom','evidence_preserved','next_action','status', ...
    'evidence_path'});
write_table_csv_17g(fullfile(runRoot,"issues","issue_log.csv"),issues);
decision = table(runId,"A4-3",string(summary.run_terminal_state), ...
    "CURRENT_STAGE remains stage_A4 / READY",summary.iteration_count, ...
    'VariableNames',{'run_id','milestone','numerical_terminal_state', ...
    'stage_decision','accepted_iteration_count'});
write_table_csv_17g(fullfile(runRoot,"issues","decision_log.csv"),decision);
end

function write_report_evidence(runRoot,runId,gitCommit)
metadata = struct( ...
    "run_id",runId,"stage_id","stage_A4", ...
    "git_commit",gitCommit,"manifest_status","RUNNING", ...
    "candidate_status","fixture");
block = struct( ...
    "type","table","headers",["字段","值"], ...
    "rows",["run_id",runId;"阶段","Stage A4"], ...
    "widths",[3000,6360]);
reportPaths = struct( ...
    "model_report",fullfile(runRoot,"reports", ...
        "阶段A4_模型与优化结果报告.docx"), ...
    "issue_report",fullfile(runRoot,"reports", ...
        "阶段A4_问题修复与验收报告.docx"), ...
    "run_summary",fullfile(runRoot,"reports", ...
        "运行_"+runId+"_结果摘要.docx"));
write_stage_a4_docx(reportPaths.model_report, ...
    "阶段A4 模型与优化结果报告","fixture",metadata,block);
write_stage_a4_docx(reportPaths.issue_report, ...
    "阶段A4 问题修复与验收报告","fixture",metadata,block);
write_stage_a4_docx(reportPaths.run_summary, ...
    "Stage A4 运行结果摘要","fixture",metadata,block);
[passed,structure] = validate_stage_a4_report_set(reportPaths,runId);
assert(passed);
write_table_csv_17g(fullfile(runRoot,"reports", ...
    "report_structure_validation.csv"),structure);

keys = string(fieldnames(reportPaths));
report_path = strings(3,1);
page_number = ones(3,1);
page_count = ones(3,1);
image_path = strings(3,1);
image_sha256 = strings(3,1);
status = repmat("PASS",3,1);
relative_path = strings(3,1);
report_sha256 = strings(3,1);
for k = 1:3
    reportPath = string(reportPaths.(keys(k)));
    report_path(k) = string(char(java.io.File( ...
        char(reportPath)).getCanonicalPath()));
    imagePath = fullfile(runRoot,"reports","rendered", ...
        keys(k)+"_page_001.png");
    imwrite(zeros(2,2,3,"uint8"),imagePath);
    image_path(k) = string(char(java.io.File( ...
        char(imagePath)).getCanonicalPath()));
    image_sha256(k) = compute_sha256_file(imagePath);
    relative_path(k) = replace(extractAfter(report_path(k), ...
        strlength(string(char(java.io.File( ...
        char(runRoot)).getCanonicalPath())))+1),"\","/");
    report_sha256(k) = compute_sha256_file(reportPath);
end
visual = table(report_path,page_number,page_count,image_path, ...
    image_sha256,status);
write_table_csv_17g(fullfile(runRoot,"reports", ...
    "report_visual_qa.csv"),visual);
hashes = table(relative_path,report_sha256,status, ...
    'VariableNames',{'relative_path','sha256','status'});
write_table_csv_17g(fullfile(runRoot,"reports", ...
    "report_sha256.csv"),hashes);
end

function write_text(pathValue,textValue)
[fileId,message] = fopen(pathValue,"wb","n","UTF-8");
assert(fileId>=0,"stageA4:test:WriteText","%s",message);
guard = onCleanup(@()close_if_open(fileId));
bytes = unicode2native(char(textValue),"UTF-8");
fwrite(fileId,bytes,"uint8");
fclose(fileId);
clear guard
end

function close_if_open(fileId)
try
    if ischar(fopen(fileId))
        fclose(fileId);
    end
catch
end
end

function remove_tree(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,"s");
end
end
