function index = build_stage_a_multiday_index(data,config,options)
%BUILD_STAGE_A_MULTIDAY_INDEX Build and audit a formal multiday Stage-A index.
%
% Every selected date remains a complete, independent 24-hour SOC cycle.
% The canonical framework owns the sole global q block, seven q_d blocks,
% and exact deletion records for renewables whose availability equals zero.

arguments
    data (1,1) struct
    config (1,1) struct
    options.RunId (1,1) string = "STAGE_A_MULTIDAY_INDEX"
end

stageId = string(config.stage_id);
if ~ismember(stageId,["stage_A3","stage_A4"])
    error("stageA:index:StageId", ...
        "The multiday index supports only stage_A3 and stage_A4.");
end
if any(data.base.storage.initialSocFraction ~= 0.5)
    error("stageA:index:SocFractionMismatch", ...
        "Both formal-day storage boundary fractions must equal 0.5.");
end

index = rkkt.indexing.build_canonical_index_framework(data,config.days,config.hours,[], ...
    options.RunId);
index.scope.stage_id = stageId;
index.scope.time_scope_type = config.time_scope_type;
index.scope.run_purpose = config.run_purpose;
index.scope.aggregation_day_order = config.aggregation_day_order;
index.expected = struct( ...
    "full_kkt_dimension",config.expected_full_kkt_dimension, ...
    "day_count",config.expected_day_count, ...
    "day_response_dimension",config.expected_day_response_dimension, ...
    "day_rhs_dimension",config.expected_day_rhs_dimension, ...
    "global_core_dimension",config.expected_global_core_dimension, ...
    "daily_hourly_chain_dimensions", ...
        config.expected_daily_hourly_chain_dimensions, ...
    "total_hourly_chain_dimension", ...
        config.expected_total_hourly_chain_dimension, ...
    "fixed_zero_count",config.expected_fixed_zero_count);

validate_dimensions(index,config);
validate_capacity_structure(index,config);
validate_fixed_zero_structure(index,data,config);
validate_daily_soc_structure(index,data,config);
frameworkAudit = rkkt.indexing.validate_canonical_index_framework(index);
if ~all(frameworkAudit.passed)
    failed = frameworkAudit(frameworkAudit.status == "FAIL",:);
    error("stageA:multidayIndex:CanonicalAudit", ...
        "Canonical multiday Stage-A index audit failed: %s", ...
        strjoin(string(failed.check_id)+"="+string(failed.actual_value),"; "));
end
end

function validate_dimensions(index,config)
if index.counts.full_kkt_dimension ~= config.expected_full_kkt_dimension
    error("stageA:multidayIndex:FullKktDimensionMismatch", ...
        "Expected full KKT dimension %d; built %d.", ...
        config.expected_full_kkt_dimension,index.counts.full_kkt_dimension);
end
if index.counts.fixed_zero ~= config.expected_fixed_zero_count
    error("stageA:multidayIndex:FixedZeroCountMismatch", ...
        "Expected %d fixed-zero variables from controlled data; built %d.", ...
        config.expected_fixed_zero_count,index.counts.fixed_zero);
end

blocks = formal_hour_blocks(index,config);
dailyDimensions = zeros(1,numel(config.days));
for dayPosition = 1:numel(config.days)
    day = config.days(dayPosition);
    rows = blocks(blocks.day == day,:);
    if height(rows) ~= numel(config.hours) || ...
            ~isequal(reshape(rows.hour_start,1,[]),config.hours)
        error("stageA:multidayIndex:HourBlockInventory", ...
            "Day %d does not have the complete ordered 24-hour block inventory.",day);
    end
    dailyDimensions(dayPosition) = sum(rows.kkt_block_dimension);
end
if ~isequal(dailyDimensions, ...
        config.expected_daily_hourly_chain_dimensions) || ...
        sum(dailyDimensions) ~= config.expected_total_hourly_chain_dimension
    error("stageA:multidayIndex:HourlyChainDimensionMismatch", ...
        "Expected daily chain dimensions %s; built %s.", ...
        mat2str(config.expected_daily_hourly_chain_dimensions), ...
        mat2str(dailyDimensions));
end
end

function validate_capacity_structure(index,config)
variables = index.variable_index;
constraints = index.constraint_index;
globalQ = variables(variables.day == 0 & variables.hour == 0,:);
if height(globalQ) ~= 14
    error("stageA:multidayIndex:GlobalCapacityCount", ...
        "The model must contain exactly one 14-dimensional global capacity block.");
end
for day = config.days
    dailyQ = variables(variables.day == day & variables.hour == 0,:);
    bindings = constraints( ...
        string(constraints.constraint_type) == "equality" & ...
        string(constraints.constraint_name) == "daily_capacity_binding" & ...
        constraints.day == day,:);
    if height(dailyQ) ~= 14 || height(bindings) ~= 14 || ...
            ~isequal(reshape(bindings.local_row,1,[]),1:14)
        error("stageA:multidayIndex:DailyCapacityStructure", ...
            "Day %d must have one 14-vector q_d and 14 q_d-q bindings.",day);
    end
end

globalBounds = constraints( ...
    string(constraints.constraint_type) == "inequality" & ...
    constraints.day == 0 & constraints.hour == 0,:);
dailyCapacityBounds = constraints( ...
    string(constraints.constraint_type) == "inequality" & ...
    constraints.day > 0 & constraints.hour == 0,:);
duration = constraints( ...
    string(constraints.constraint_type) == "equality" & ...
    string(constraints.constraint_name) == "storage_duration",:);
if height(globalBounds) ~= 28 || ~isempty(dailyCapacityBounds) || ...
        height(duration) ~= 2
    error("stageA:multidayIndex:GlobalOnlyStructure", ...
        "Capacity bounds and duration rows must exist globally once only.");
end
end

function validate_fixed_zero_structure(index,data,config)
fixed = index.fixed_zero_map;
if isempty(fixed) || height(fixed) ~= config.expected_fixed_zero_count
    error("stageA:multidayIndex:EmptyFixedZeroMap", ...
        "The model requires the nonempty fixed_zero_map from controlled data.");
end
if any(~ismember(fixed.day,config.days)) || ...
        any(fixed.fixed_value ~= 0) || ...
        any(fixed.fixed_direction_value ~= 0) || ...
        any(string(fixed.reason) ~= "zero_availability") || ...
        any(string(fixed.inequality_status) ~= ...
            "NOT_APPLICABLE_BOTH_BOUNDS")
    error("stageA:multidayIndex:FixedZeroMapContract", ...
        "Every fixed-zero row must prescribe exact zero value and direction.");
end

variables = index.variable_index;
inequalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type) == "inequality",:);
for rowNumber = 1:height(fixed)
    row = fixed(rowNumber,:);
    availability = renewable_availability(data,row);
    if availability ~= 0
        error("stageA:multidayIndex:NonzeroAvailabilityRemoved", ...
            "A fixed-zero row was created from availability %.17g.",availability);
    end
    active = variables.day == row.day & variables.hour == row.hour & ...
        string(variables.asset_type) == string(row.asset_type) & ...
        variables.asset_id == row.asset_id & ...
        string(variables.variable_name) == string(row.variable_name);
    bounds = inequalities.day == row.day & ...
        inequalities.hour == row.hour & ...
        string(inequalities.asset_type) == string(row.asset_type) & ...
        inequalities.asset_id == row.asset_id;
    if any(active) || any(bounds)
        error("stageA:multidayIndex:FixedZeroNotDeleted", ...
            "A fixed-zero renewable retained an active variable or bound.");
    end
end

activeRenewables = variables(variables.hour > 0 & ...
    ismember(string(variables.asset_type),["wind","solar"]),:);
for rowNumber = 1:height(activeRenewables)
    row = activeRenewables(rowNumber,:);
    if renewable_availability(data,row) == 0
        error("stageA:multidayIndex:ZeroAvailabilityActive", ...
            "An exact-zero renewable availability retained an active variable.");
    end
end
end

function value = renewable_availability(data,row)
if string(row.asset_type) == "wind"
    value = data.timeseries.windAvailability(row.day,row.hour,row.asset_id);
elseif string(row.asset_type) == "solar"
    value = data.timeseries.solarAvailability(row.day,row.hour,row.asset_id);
else
    error("stageA:multidayIndex:FixedZeroAssetType", ...
        "Only wind and solar may enter the Stage-A fixed_zero_map.");
end
end

function validate_daily_soc_structure(index,data,config)
links = index.soc_link_map;
expectedLinks = numel(config.days)*numel(config.hours)*data.meta.nStorage;
if height(links) ~= expectedLinks
    error("stageA:multidayIndex:SocLinkCount", ...
        "The model must contain two SOC link records per modeled day/hour.");
end
variables = index.variable_index;
for day = config.days
    dayLinks = links(links.day == day,:);
    first = dayLinks(dayLinks.hour == config.start_hour,:);
    if height(first) ~= data.meta.nStorage || ...
            any(~isnan(first.predecessor_hour)) || ...
            any(first.predecessor_soc_global_index ~= 0) || ...
            any(string(first.boundary_source) ~= ...
                "formal_daily_fixed_half_energy") || ...
            any(first.initial_energy_fraction ~= 0.5)
        error("stageA:multidayIndex:InitialSocBoundary", ...
            "Day %d hour 1 must use an independent formal 0.5E boundary.",day);
    end
    for hour = 2:24
        rows = dayLinks(dayLinks.hour == hour,:);
        if height(rows) ~= data.meta.nStorage || ...
                any(rows.predecessor_hour ~= hour-1) || ...
                any(rows.predecessor_soc_global_index <= 0) || ...
                any(string(rows.boundary_source) ~= "previous_physical_hour")
            error("stageA:multidayIndex:InternalSocLink", ...
                "Day %d hour %d does not link only to its preceding hour.", ...
                day,hour);
        end
        predecessorRows = variables(rows.predecessor_soc_global_index,:);
        if any(predecessorRows.day ~= day) || ...
                any(predecessorRows.hour ~= hour-1) || ...
                any(string(predecessorRows.variable_name) ~= "SOC")
            error("stageA:multidayIndex:CrossDaySocLink", ...
                "A day %d SOC row has a cross-day or nonadjacent predecessor.",day);
        end
    end
    terminal = dayLinks(dayLinks.terminal_equality,:);
    if height(terminal) ~= config.terminal_soc_equality_count_per_day || ...
            any(terminal.hour ~= config.terminal_hour) || ...
            any(terminal.terminal_energy_fraction ~= 0.5) || ...
            any(dayLinks.terminal_equality(dayLinks.hour ~= 24))
        error("stageA:multidayIndex:TerminalSocLinks", ...
            "Day %d must have exactly two terminal SOC rows at hour 24.",day);
    end
end

terminalRows = index.constraint_index( ...
    string(index.constraint_index.constraint_type) == "equality" & ...
    string(index.constraint_index.constraint_name) == "terminal_soc",:);
if height(terminalRows) ~= ...
        numel(config.days)*config.terminal_soc_equality_count_per_day || ...
        any(terminalRows.hour ~= 24) || ...
        any(contains(string(terminalRows.constraint_id),"WINDOW"))
    error("stageA:multidayIndex:TerminalSocRows", ...
        "The formal terminal SOC equality inventory is invalid.");
end
end

function blocks = formal_hour_blocks(index,config)
blocks = index.block_index(index.block_index.day > 0 & ...
    index.block_index.hour_start > 0,:);
[~,order] = sortrows([blocks.day,blocks.hour_start],[1,2]);
blocks = blocks(order,:);
expected = numel(config.days)*numel(config.hours);
if height(blocks) ~= expected
    error("stageA:multidayIndex:HourBlockCount", ...
        "Expected %d hourly blocks; built %d.",expected,height(blocks));
end
end
