function index = build_stage_a2_index(data, options)
%BUILD_STAGE_A2_INDEX Build and audit the formal day-14 A2 index.
%
% No artificial window specification is supplied to the canonical index.
% Consequently hour 1 receives the formal daily initial SOC boundary and
% the two terminal SOC equalities are attached only to physical hour 24.

arguments
    data (1,1) struct
    options.ConfigPath (1,1) string = ""
    options.RunId (1,1) string = "STAGE_A2_INDEX"
end

projectRoot = resolve_project_root(data,options.ConfigPath);
stageConfig = rkkt.model.load_stage_a2_configuration(projectRoot);
if strlength(options.ConfigPath) > 0
    expectedPath = string(fullfile(projectRoot,"config","stage_A2.yaml"));
    if ~paths_equal(options.ConfigPath,expectedPath)
        error("stageA2:index:ConfigPathLayout", ...
            "ConfigPath must identify <projectRoot>/config/stage_A2.yaml.");
    end
end

if any(data.base.storage.initialSocFraction ~= 0.5)
    error("stageA2:index:SocFractionMismatch", ...
        "Both formal-day storage boundary fractions must equal 0.5.");
end

% The empty windowSpec is intentional: A2 is a formal physical day.
index = rkkt.indexing.build_canonical_index_framework(data,stageConfig.days, ...
    stageConfig.hours,[],options.RunId);
index.scope.stage_id = "stage_A2";
index.scope.time_scope_type = stageConfig.time_scope_type;
index.scope.run_purpose = stageConfig.run_purpose;
index.expected = struct( ...
    "full_kkt_dimension",stageConfig.expected_full_kkt_dimension, ...
    "hourly_kkt_block_dimensions", ...
        stageConfig.expected_hourly_kkt_block_dimensions, ...
    "hourly_chain_dimension",stageConfig.expected_hourly_chain_dimension, ...
    "fixed_zero_count",stageConfig.expected_fixed_zero_count, ...
    "solar_fixed_zero_count",stageConfig.expected_solar_fixed_zero_count, ...
    "wind_fixed_zero_count",stageConfig.expected_wind_fixed_zero_count, ...
    "day_response_dimension",stageConfig.expected_day_response_dimension, ...
    "global_core_dimension",stageConfig.expected_global_core_dimension);

validate_dimensions(index,stageConfig);
validate_fixed_zero_structure(index,data,stageConfig);
validate_formal_soc_structure(index,data,stageConfig);

frameworkAudit = rkkt.indexing.validate_canonical_index_framework(index);
if ~all(frameworkAudit.passed)
    failed = frameworkAudit(frameworkAudit.status == "FAIL",:);
    error("stageA2:index:CanonicalAudit", ...
        "Canonical A2 index audit failed: %s", ...
        strjoin(string(failed.check_id)+"="+string(failed.actual_value),"; "));
end
end

function validate_dimensions(index,config)
if index.counts.full_kkt_dimension ~= config.expected_full_kkt_dimension
    error("stageA2:index:FullKktDimensionMismatch", ...
        "Expected full KKT dimension %d; built %d.", ...
        config.expected_full_kkt_dimension,index.counts.full_kkt_dimension);
end

hourBlocks = formal_hour_blocks(index,config);
actualBlockDimensions = reshape(hourBlocks.kkt_block_dimension,1,[]);
if ~isequal(actualBlockDimensions, ...
        config.expected_hourly_kkt_block_dimensions)
    error("stageA2:index:HourlyBlockDimensionMismatch", ...
        "Expected A2 hourly KKT blocks %s; built %s.", ...
        mat2str(config.expected_hourly_kkt_block_dimensions), ...
        mat2str(actualBlockDimensions));
end
if sum(actualBlockDimensions) ~= config.expected_hourly_chain_dimension
    error("stageA2:index:HourlyChainDimensionMismatch", ...
        "Expected A2 hourly chain dimension %d; built %d.", ...
        config.expected_hourly_chain_dimension,sum(actualBlockDimensions));
end
if index.counts.fixed_zero ~= config.expected_fixed_zero_count
    error("stageA2:index:FixedZeroCountMismatch", ...
        "Expected %d fixed-zero variables from controlled data; built %d.", ...
        config.expected_fixed_zero_count,index.counts.fixed_zero);
end
end

function validate_fixed_zero_structure(index,data,config)
fixed = index.fixed_zero_map;
if isempty(fixed)
    error("stageA2:index:EmptyFixedZeroMap", ...
        "Stage A2 requires a nonempty fixed_zero_map.");
end
if any(fixed.day ~= config.days(1)) || ...
        any(fixed.fixed_value ~= 0) || ...
        any(fixed.fixed_direction_value ~= 0) || ...
        any(string(fixed.reason) ~= "zero_availability") || ...
        any(string(fixed.inequality_status) ~= ...
            "NOT_APPLICABLE_BOTH_BOUNDS")
    error("stageA2:index:FixedZeroMapContract", ...
        "Every A2 fixed-zero row must prescribe an exact zero value and direction from zero availability.");
end

isSolar = string(fixed.asset_type) == "solar" & ...
    string(fixed.variable_name) == "PP";
isWind = string(fixed.asset_type) == "wind" & ...
    string(fixed.variable_name) == "PW";
if nnz(isSolar) ~= config.expected_solar_fixed_zero_count || ...
        nnz(isWind) ~= config.expected_wind_fixed_zero_count || ...
        any(~(isSolar | isWind))
    error("stageA2:index:FixedZeroComposition", ...
        "A2 fixed-zero rows must contain exactly %d solar and %d wind variables.", ...
        config.expected_solar_fixed_zero_count, ...
        config.expected_wind_fixed_zero_count);
end

expectedNightHours = [1:7,20:24];
for asset = 1:data.meta.nSolar
    rows = fixed(isSolar & fixed.asset_id == asset,:);
    if ~isequal(reshape(sort(rows.hour),1,[]),expectedNightHours)
        error("stageA2:index:SolarZeroHours", ...
            "Solar asset %d fixed-zero hours differ from the exact controlled-data zero set.", ...
            asset);
    end
end
wind = fixed(isWind,:);
if height(wind) ~= 1 || wind.hour ~= 19 || wind.asset_id ~= 3
    error("stageA2:index:WindZeroLocation", ...
        "The sole A2 wind fixed zero must be day 14, hour 19, wind asset 3.");
end

for rowNumber = 1:height(fixed)
    row = fixed(rowNumber,:);
    if string(row.asset_type) == "solar"
        availability = data.timeseries.solarAvailability( ...
            row.day,row.hour,row.asset_id);
    else
        availability = data.timeseries.windAvailability( ...
            row.day,row.hour,row.asset_id);
    end
    if availability ~= 0
        error("stageA2:index:NonzeroAvailabilityRemoved", ...
            "A fixed-zero row was created from availability %.17g rather than exact zero.", ...
            availability);
    end

    active = index.variable_index.day == row.day & ...
        index.variable_index.hour == row.hour & ...
        string(index.variable_index.asset_type) == string(row.asset_type) & ...
        index.variable_index.asset_id == row.asset_id & ...
        string(index.variable_index.variable_name) == string(row.variable_name);
    bounds = index.constraint_index.day == row.day & ...
        index.constraint_index.hour == row.hour & ...
        string(index.constraint_index.constraint_type) == "inequality" & ...
        string(index.constraint_index.asset_type) == string(row.asset_type) & ...
        index.constraint_index.asset_id == row.asset_id;
    if any(active) || any(bounds)
        error("stageA2:index:FixedZeroNotDeleted", ...
            "Fixed-zero %s at day %d hour %d asset %d retained an active variable or bound.", ...
            string(row.variable_name),row.day,row.hour,row.asset_id);
    end
end

variables = index.variable_index;
activeRenewables = variables(variables.day == config.days(1) & ...
    variables.hour > 0 & ismember(string(variables.asset_type), ...
    ["wind","solar"]),:);
for rowNumber = 1:height(activeRenewables)
    row = activeRenewables(rowNumber,:);
    if string(row.asset_type) == "wind"
        availability = data.timeseries.windAvailability( ...
            row.day,row.hour,row.asset_id);
    else
        availability = data.timeseries.solarAvailability( ...
            row.day,row.hour,row.asset_id);
    end
    if availability == 0
        error("stageA2:index:ZeroAvailabilityActive", ...
            "An exact-zero renewable availability retained an active variable.");
    end
end
end

function validate_formal_soc_structure(index,data,config)
links = index.soc_link_map;
if height(links) ~= numel(config.hours)*data.meta.nStorage
    error("stageA2:index:SocLinkCount", ...
        "The A2 formal day must contain two SOC link records per hour.");
end

first = links(links.hour == config.start_hour,:);
if height(first) ~= data.meta.nStorage || ...
        any(~isnan(first.predecessor_hour)) || ...
        any(first.predecessor_soc_global_index ~= 0) || ...
        any(string(first.boundary_source) ~= ...
            "formal_daily_fixed_half_energy") || ...
        any(first.initial_energy_fraction ~= 0.5)
    error("stageA2:index:InitialSocBoundary", ...
        "Hour 1 must use the formal 0.5E boundary without a previous-day SOC variable.");
end

for hour = 2:24
    rows = links(links.hour == hour,:);
    if height(rows) ~= data.meta.nStorage || ...
            any(rows.predecessor_hour ~= hour-1) || ...
            any(rows.predecessor_soc_global_index <= 0) || ...
            any(string(rows.boundary_source) ~= "previous_physical_hour") || ...
            any(isfinite(rows.initial_energy_fraction))
        error("stageA2:index:InternalSocLink", ...
            "Hour %d SOC rows do not connect exactly to hour %d.",hour,hour-1);
    end
end

terminalLinks = links(links.terminal_equality,:);
if height(terminalLinks) ~= config.terminal_soc_equality_count || ...
        any(terminalLinks.hour ~= config.terminal_hour) || ...
        any(terminalLinks.terminal_energy_fraction ~= 0.5) || ...
        any(links.terminal_equality(links.hour ~= config.terminal_hour))
    error("stageA2:index:TerminalSocLinks", ...
        "Exactly two formal terminal SOC equalities must be attached to hour 24.");
end

equalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type) == "equality",:);
terminalRows = equalities(string(equalities.constraint_name) == ...
    "terminal_soc",:);
if height(terminalRows) ~= config.terminal_soc_equality_count || ...
        any(terminalRows.hour ~= config.terminal_hour) || ...
        ~isequal(reshape(sort(terminalRows.asset_id),1,[]),1:2) || ...
        any(contains(string(terminalRows.constraint_id),"WINDOW"))
    error("stageA2:index:TerminalSocRows", ...
        "The two formal terminal SOC constraint rows must occur only at hour 24.");
end
end

function blocks = formal_hour_blocks(index,config)
blocks = index.block_index(index.block_index.day == config.days(1) & ...
    ismember(index.block_index.hour_start,config.hours),:);
[~,order] = sort(blocks.hour_start);
blocks = blocks(order,:);
if height(blocks) ~= numel(config.hours) || ...
        ~isequal(reshape(blocks.hour_start,1,[]),config.hours)
    error("stageA2:index:HourBlockInventory", ...
        "The A2 hour-block inventory is incomplete or out of order.");
end
end

function projectRoot = resolve_project_root(data,configPath)
if strlength(configPath) > 0
    configDirectory = string(fileparts(configPath));
    projectRoot = string(fileparts(configDirectory));
elseif isfield(data,"projectRoot") && ...
        strlength(string(data.projectRoot)) > 0
    projectRoot = string(data.projectRoot);
else
    error("stageA2:index:MissingProjectRoot", ...
        "data.projectRoot is required when ConfigPath is not supplied.");
end
end

function equal = paths_equal(left,right)
left = replace(string(left),"\","/");
right = replace(string(right),"\","/");
equal = strcmpi(left,right);
end
