function index = build(data)
%BUILD Build the formal seven-day canonical index through the legacy entry.
%   INDEX = RKKT.INDEXING.BUILD(DATA) delegates index construction to
%   BUILD_STAGE_A4_INDEX. DATA is the unmodified PKG-2 project-data object.
%   The returned canonical index is checked read-only and returned without
%   wrapping, sorting, deduplication, correction, or added fields.

arguments
    data (1,1) struct
end

rkkt.contracts.requireFields(data, ...
    ["schemaVersion"; "projectRoot"; "meta"; "base"; "timeseries"], ...
    "rkkt.indexing.build input");
if string(data.schemaVersion) ~= "stage0-data-v1.0" || ...
        data.meta.nDays ~= 365 || data.meta.nHours ~= 24
    error("rkkt:indexing:DataContract", ...
        "Input must be the complete 365-day PKG-2 project-data object.");
end

projectRoot = string(data.projectRoot);
legacyIndexDirectory = fullfile(projectRoot, "src", "indexing");
legacyModelDirectory = fullfile(projectRoot, "src", "model");
if ~isfolder(legacyIndexDirectory) || ~isfolder(legacyModelDirectory)
    error("rkkt:indexing:LegacyDirectoryMissing", ...
        "Legacy indexing/model directories are missing under %s.", ...
        projectRoot);
end

originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(legacyModelDirectory, "-begin");
addpath(legacyIndexDirectory, "-begin");

resolved = string(which("build_stage_a4_index"));
expected = fullfile(legacyIndexDirectory, "build_stage_a4_index.m");
if ~same_path(resolved, expected)
    error("rkkt:indexing:ProductionFunctionShadowed", ...
        "Expected build_stage_a4_index at '%s'; MATLAB resolved '%s'.", ...
        expected, resolved);
end

index = build_stage_a4_index(data);
validate_index_contract(index, data);

clear pathGuard
end

function validate_index_contract(index, data)
required = [ ...
    "version"
    "model_contract_version"
    "scope"
    "variable_index"
    "constraint_index"
    "block_index"
    "fixed_zero_map"
    "permutation_map"
    "soc_link_map"
    "counts"
    "expected"];
rkkt.contracts.requireFields(index, required, ...
    "rkkt.indexing.build output");
rkkt.contracts.requireTextScalar(index.version, ...
    "rkkt.indexing.build output.version");
rkkt.contracts.requireTextScalar(index.model_contract_version, ...
    "rkkt.indexing.build output.model_contract_version");
if string(index.model_contract_version) ~= "1.0"
    contract_error("model_contract_version", "1.0", ...
        string(index.model_contract_version));
end

validate_scope(index.scope);
validate_tables(index);
validate_global_numbers(index);
validate_hour_blocks(index);
validate_fixed_zero(index, data);
validate_permutation(index);
validate_soc_links(index, data);
validate_counts(index);
end

function validate_scope(scope)
required = [ ...
    "days"
    "hours"
    "solve_pass"
    "is_explicit_window"
    "window_type"
    "start_hour"
    "terminal_hour"
    "soc_boundary_mode"
    "terminal_soc_equality_count"
    "stage_id"
    "time_scope_type"
    "run_purpose"
    "aggregation_day_order"];
rkkt.contracts.requireFields(scope, required, ...
    "rkkt.indexing.build output.scope");
if ~isequal(scope.days, 14:20) || ...
        ~isequal(scope.hours, 1:24) || ...
        ~isequal(scope.aggregation_day_order, 14:20)
    contract_error("scope day/hour order", ...
        "days 14:20 and hours 1:24 in original order", ...
        "different range or order");
end
if string(scope.stage_id) ~= "stage_A4" || ...
        string(scope.solve_pass) ~= "pass_1" || ...
        logical(scope.is_explicit_window) || ...
        string(scope.time_scope_type) ~= "formal_7_day_scope"
    contract_error("scope identity", ...
        "stage_A4 formal seven-day first-pass scope", ...
        "different stage, pass, or scope");
end
if scope.start_hour ~= 1 || scope.terminal_hour ~= 24 || ...
        scope.terminal_soc_equality_count ~= 2 || ...
        string(scope.soc_boundary_mode) ~= ...
        "formal_daily_fixed_half_energy"
    contract_error("scope SOC boundary", ...
        "hour 1 and hour 24 fixed at 0.5E", ...
        "different boundary semantics");
end
end

function validate_tables(index)
tableContracts = {
    "variable_index", [ ...
        "run_id"; "model_contract_version"; "day"; "hour"; ...
        "asset_type"; "asset_id"; "variable_name"; "active_flag"; ...
        "block_id"; "global_index_start"; "global_index_end"]
    "constraint_index", [ ...
        "run_id"; "constraint_id"; "constraint_type"; "day"; ...
        "hour"; "asset_type"; "asset_id"; "constraint_name"; ...
        "active_flag"; "global_row"]
    "block_index", [ ...
        "run_id"; "block_id"; "day"; "hour_start"; "hour_end"; ...
        "variable_start"; "variable_end"; "equality_start"; ...
        "equality_end"; "n_primal"; "n_equalities"; ...
        "kkt_block_dimension"; "window_position"; ...
        "terminal_equality_count"]
    "fixed_zero_map", [ ...
        "run_id"; "solve_pass"; "day"; "hour"; "asset_type"; ...
        "asset_id"; "variable_name"; "physical_array_index"; ...
        "fixed_value"; "fixed_direction_value"; "reason"; ...
        "inequality_status"]
    "permutation_map", [ ...
        "run_id"; "space_name"; "canonical_index"; ...
        "solver_index"; "object_type"; "object_name"]
    "soc_link_map", [ ...
        "run_id"; "day"; "hour"; "window_position"; ...
        "storage_id"; "current_soc_global_index"; ...
        "predecessor_hour"; "predecessor_soc_global_index"; ...
        "energy_capacity_global_index"; "boundary_source"; ...
        "initial_energy_fraction"; "terminal_equality"; ...
        "terminal_energy_fraction"]};
for k = 1:size(tableContracts, 1)
    name = tableContracts{k, 1};
    value = index.(name);
    if ~istable(value)
        error("rkkt:indexing:ContractViolation", ...
            "[%s] expected table; actual class=%s.", name, class(value));
    end
    actual = string(value.Properties.VariableNames);
    required = tableContracts{k, 2};
    missing = required(~ismember(required, actual));
    if ~isempty(missing)
        error("rkkt:indexing:ContractViolation", ...
            "[%s] missing table variable(s): %s.", ...
            name, strjoin(missing, ", "));
    end
end
end

function validate_global_numbers(index)
variables = index.variable_index;
variableExpected = (1:height(variables)).';
if ~isequal(variables.global_index_start, variableExpected) || ...
        ~isequal(variables.global_index_end, variableExpected) || ...
        numel(unique(variables.global_index_start)) ~= height(variables)
    contract_error("variable global numbering", ...
        "continuous unique 1:N in existing row order", ...
        "gap, overlap, duplicate, or reordered row");
end

constraints = index.constraint_index;
constraintExpected = (1:height(constraints)).';
if ~isequal(constraints.global_row, constraintExpected) || ...
        numel(unique(constraints.global_row)) ~= height(constraints) || ...
        numel(unique(string(constraints.constraint_id))) ~= ...
        height(constraints)
    contract_error("constraint global numbering", ...
        "continuous unique 1:M in existing row order", ...
        "gap, overlap, duplicate, or duplicate identity");
end
end

function validate_hour_blocks(index)
blocks = index.block_index;
hourly = blocks(blocks.day > 0 & blocks.hour_start > 0, :);
expectedDays = repelem((14:20).', 24);
expectedHours = repmat((1:24).', 7, 1);
if height(hourly) ~= 168 || ...
        ~isequal(hourly.day, expectedDays) || ...
        ~isequal(hourly.hour_start, expectedHours) || ...
        ~isequal(hourly.hour_end, expectedHours) || ...
        ~isequal(hourly.window_position, expectedHours)
    contract_error("hour block inventory", ...
        "168 blocks ordered by days 14:20 then hours 1:24", ...
        "different count, date/hour value, or order");
end
if any(hourly.variable_start < 1) || ...
        any(hourly.variable_end < hourly.variable_start) || ...
        any(hourly.equality_start < 1) || ...
        any(hourly.equality_end < hourly.equality_start) || ...
        any(hourly.n_primal ~= ...
        hourly.variable_end - hourly.variable_start + 1) || ...
        any(hourly.n_equalities ~= ...
        hourly.equality_end - hourly.equality_start + 1) || ...
        any(hourly.kkt_block_dimension ~= ...
        hourly.n_primal + hourly.n_equalities)
    contract_error("hour block ranges", ...
        "closed consistent primal/equality ranges", ...
        "invalid range or dimension");
end
end

function validate_fixed_zero(index, data)
fixed = index.fixed_zero_map;
variables = index.variable_index;
inequalities = index.constraint_index( ...
    string(index.constraint_index.constraint_type) == "inequality", :);
if height(fixed) ~= 422 || ...
        any(fixed.fixed_value ~= 0) || ...
        any(fixed.fixed_direction_value ~= 0) || ...
        any(string(fixed.reason) ~= "zero_availability") || ...
        any(string(fixed.inequality_status) ~= ...
        "NOT_APPLICABLE_BOTH_BOUNDS") || ...
        any(~ismember(string(fixed.asset_type), ["wind", "solar"]))
    contract_error("fixed_zero_map", ...
        "422 exact-zero wind/solar deletion records", ...
        "different count, value, reason, or asset type");
end

for k = 1:height(fixed)
    row = fixed(k, :);
    activeMatch = variables.day == row.day & ...
        variables.hour == row.hour & ...
        string(variables.asset_type) == string(row.asset_type) & ...
        variables.asset_id == row.asset_id & ...
        string(variables.variable_name) == string(row.variable_name);
    boundMatch = inequalities.day == row.day & ...
        inequalities.hour == row.hour & ...
        string(inequalities.asset_type) == string(row.asset_type) & ...
        inequalities.asset_id == row.asset_id;
    if any(activeMatch) || any(boundMatch)
        contract_error("fixed-zero deletion", ...
            "no active variable or coincident bounds", ...
            "deleted renewable remains active");
    end
    if string(row.asset_type) == "wind"
        availability = data.timeseries.windAvailability( ...
            row.day, row.hour, row.asset_id);
    else
        availability = data.timeseries.solarAvailability( ...
            row.day, row.hour, row.asset_id);
    end
    if availability ~= 0
        contract_error("fixed-zero availability", "exact zero", ...
            compose("%.17g", availability));
    end
end

renewable = variables(variables.hour > 0 & ...
    ismember(string(variables.asset_type), ["wind", "solar"]), :);
for k = 1:height(renewable)
    row = renewable(k, :);
    if string(row.asset_type) == "wind"
        availability = data.timeseries.windAvailability( ...
            row.day, row.hour, row.asset_id);
    else
        availability = data.timeseries.solarAvailability( ...
            row.day, row.hour, row.asset_id);
    end
    if availability == 0
        contract_error("active renewable availability", ...
            "strictly nonzero", "zero-availability variable is active");
    end
end
end

function validate_permutation(index)
mapping = index.permutation_map;
expectedSpaces = ["variable"; "equality"; "inequality"];
spaces = unique(string(mapping.space_name), "stable");
if ~isequal(spaces, expectedSpaces)
    contract_error("permutation spaces", ...
        strjoin(expectedSpaces, ", "), strjoin(spaces, ", "));
end
for space = expectedSpaces.'
    rows = mapping(string(mapping.space_name) == space, :);
    n = height(rows);
    expected = (1:n).';
    canonical = rows.canonical_index;
    solver = rows.solver_index;
    if ~isequal(canonical, expected) || ...
            any(solver ~= fix(solver)) || any(solver < 1) || ...
            any(solver > n) || numel(unique(solver)) ~= n
        contract_error("permutation_map." + space, ...
            "one-to-one onto 1:N", ...
            "non-bijective or invalid canonical order");
    end
end
end

function validate_soc_links(index, data)
links = index.soc_link_map;
variables = index.variable_index;
expectedDays = repelem((14:20).', 24 * data.meta.nStorage);
expectedHours = repmat(repelem((1:24).', ...
    data.meta.nStorage), 7, 1);
expectedStorage = repmat((1:data.meta.nStorage).', 7 * 24, 1);
if height(links) ~= 7 * 24 * data.meta.nStorage || ...
        ~isequal(links.day, expectedDays) || ...
        ~isequal(links.hour, expectedHours) || ...
        ~isequal(links.storage_id, expectedStorage)
    contract_error("soc_link_map inventory", ...
        "days 14:20, hours 1:24, two storage links per hour", ...
        "different count, identity, or order");
end

for k = 1:height(links)
    row = links(k, :);
    current = variables(row.current_soc_global_index, :);
    if current.day ~= row.day || current.hour ~= row.hour || ...
            current.asset_id ~= row.storage_id || ...
            string(current.variable_name) ~= "SOC"
        contract_error("SOC current index", ...
            "same-day same-hour SOC variable", ...
            "current SOC reference mismatch");
    end
    if row.hour == 1
        if ~isnan(row.predecessor_hour) || ...
                row.predecessor_soc_global_index ~= 0 || ...
                string(row.boundary_source) ~= ...
                "formal_daily_fixed_half_energy" || ...
                row.initial_energy_fraction ~= 0.5
            contract_error("daily initial SOC", ...
                "independent 0.5E boundary", ...
                "predecessor or boundary mismatch");
        end
    else
        if row.predecessor_hour ~= row.hour - 1 || ...
                row.predecessor_soc_global_index < 1 || ...
                string(row.boundary_source) ~= ...
                "previous_physical_hour"
            contract_error("internal SOC predecessor", ...
                "previous hour within the same day", ...
                "invalid predecessor metadata");
        end
        predecessor = variables( ...
            row.predecessor_soc_global_index, :);
        if predecessor.day ~= row.day || ...
                predecessor.hour ~= row.hour - 1 || ...
                predecessor.asset_id ~= row.storage_id || ...
                string(predecessor.variable_name) ~= "SOC"
            contract_error("cross-day SOC", ...
                "no cross-day or nonadjacent predecessor", ...
                "invalid predecessor variable");
        end
    end
    if row.hour == 24
        if ~row.terminal_equality || ...
                row.terminal_energy_fraction ~= 0.5
            contract_error("daily terminal SOC", ...
                "terminal equality at 0.5E", ...
                "terminal boundary mismatch");
        end
    elseif row.terminal_equality
        contract_error("daily terminal SOC hour", ...
            "hour 24 only", "terminal equality before hour 24");
    end
end

terminal = index.constraint_index( ...
    string(index.constraint_index.constraint_type) == "equality" & ...
    string(index.constraint_index.constraint_name) == "terminal_soc", :);
if height(terminal) ~= 14 || any(terminal.hour ~= 24) || ...
        ~isequal(terminal.day, repelem((14:20).', 2))
    contract_error("terminal SOC constraint rows", ...
        "two hour-24 rows per day", ...
        "different count, day, hour, or order");
end
end

function validate_counts(index)
requiredCounts = [ ...
    "variables"; "constraints"; "equalities"; "inequalities"; ...
    "fixed_zero"; "full_kkt_dimension"];
rkkt.contracts.requireFields(index.counts, requiredCounts, ...
    "rkkt.indexing.build output.counts");
requiredExpected = [ ...
    "full_kkt_dimension"; "day_count"; ...
    "daily_hourly_chain_dimensions"; ...
    "total_hourly_chain_dimension"; "fixed_zero_count"];
rkkt.contracts.requireFields(index.expected, requiredExpected, ...
    "rkkt.indexing.build output.expected");

constraintTypes = string(index.constraint_index.constraint_type);
if index.counts.variables ~= height(index.variable_index) || ...
        index.counts.constraints ~= height(index.constraint_index) || ...
        index.counts.equalities ~= nnz(constraintTypes == "equality") || ...
        index.counts.inequalities ~= nnz(constraintTypes == "inequality") || ...
        index.counts.fixed_zero ~= height(index.fixed_zero_map) || ...
        index.counts.full_kkt_dimension ~= 18836 || ...
        index.expected.full_kkt_dimension ~= 18836 || ...
        index.expected.day_count ~= 7 || ...
        index.expected.fixed_zero_count ~= 422 || ...
        index.expected.total_hourly_chain_dimension ~= 4128 || ...
        ~isequal(index.expected.daily_hourly_chain_dimensions, ...
        [589, 590, 589, 590, 590, 590, 590])
    contract_error("index counts", ...
        "controlled A4 dimensions and table closure", ...
        "count mismatch");
end
end

function contract_error(context, expected, actual)
error("rkkt:indexing:ContractViolation", ...
    "[%s] expected=%s; actual=%s.", ...
    context, string(expected), string(actual));
end

function equal = same_path(left, right)
left = replace(string(left), "/", "\");
right = replace(string(right), "/", "\");
if ispc
    equal = strcmpi(left, right);
else
    equal = strcmp(left, right);
end
end
