function aggregate = aggregate_stage_a4_3_test_evidence( ...
        projectRoot,runId,numericalTerminalState)
%AGGREGATE_STAGE_A4_3_TEST_EVIDENCE Aggregate persisted suites, never rerun.

arguments
    projectRoot (1,1) string
    runId (1,1) string
    numericalTerminalState (1,1) string
end
runRoot = fullfile(projectRoot,"runs",runId);
testsRoot = fullfile(runRoot,"tests");
assert(isfolder(testsRoot), ...
    "stageA4:a43:tests:AggregateRun", ...
    "Run tests directory is missing: %s",testsRoot);
plan = plan_stage_a4_3_test_campaign(numericalTerminalState);
targets = aggregate_paths(testsRoot);
assert(~any(isfile(string(struct2cell(targets))) | ...
    isfolder(string(struct2cell(targets)))), ...
    "stageA4:a43:tests:AggregateExists", ...
    "Root aggregate test evidence is immutable and already exists.");

allInventory = table();
allResults = table();
commands = strings(height(plan.suites),1);
logs = strings(height(plan.suites),1);
suiteCounts = repmat(struct( ...
    "suite_label","", ...
    "test_total",0, ...
    "test_passed",0, ...
    "test_failed",0, ...
    "test_incomplete",0, ...
    "duration_seconds",0),height(plan.suites),1);
suiteComplete = true(height(plan.suites),1);
for suiteIndex = 1:height(plan.suites)
    suite = plan.suites(suiteIndex,:);
    directory = fullfile(testsRoot,suite.relative_directory);
    [inventory,results,summary] = read_suite_evidence( ...
        directory,suite.suite_label,suite.expected_count);
    if suite.suite_label=="stage_A4_3"
        validate_specialty_binding(directory,runId);
    end
    n = height(results);
    suiteLabel = repmat(suite.suite_label,n,1);
    suiteTestOrder = uint32((1:n).');
    globalStart = height(allResults);
    globalOrder = uint32((globalStart+1:globalStart+n).');
    inventoryPart = table(globalOrder,suiteLabel,suiteTestOrder, ...
        string(inventory.test_name),string(inventory.source_file), ...
        'VariableNames',{'test_order','suite_label', ...
        'suite_test_order','test_name','source_file'});
    resultPart = table(suiteLabel,string(results.test_name), ...
        logical_column(results.passed),logical_column(results.failed), ...
        logical_column(results.incomplete), ...
        double(results.duration_seconds),string(results.details), ...
        'VariableNames',{'suite_label','test_name','passed','failed', ...
        'incomplete','duration_seconds','details'});
    if suiteIndex==1
        allInventory = inventoryPart;
        allResults = resultPart;
    else
        allInventory = [allInventory;inventoryPart]; %#ok<AGROW>
        allResults = [allResults;resultPart]; %#ok<AGROW>
    end
    commands(suiteIndex) = suite.suite_label+": "+ ...
        strip(string(fileread(fullfile(directory,"test_command.txt"))));
    logs(suiteIndex) = "===== "+suite.suite_label+" ====="+newline+ ...
        string(fileread(fullfile(directory,"matlab_test_console.log")));
    suiteCounts(suiteIndex) = struct( ...
        "suite_label",char(suite.suite_label), ...
        "test_total",n, ...
        "test_passed",nnz(resultPart.passed), ...
        "test_failed",nnz(resultPart.failed), ...
        "test_incomplete",nnz(resultPart.incomplete), ...
        "duration_seconds",sum(resultPart.duration_seconds));
    suiteComplete(suiteIndex) = ...
        string(summary.execution_status)=="COMPLETE";
end

withinSuiteUnique = grouped_names_unique(allResults);
pairKey = allResults.suite_label+"::"+allResults.test_name;
pairUnique = numel(unique(pairKey))==height(allResults);
countExact = height(allResults)==plan.expected_total && ...
    isequal([suiteCounts.test_total].',plan.suites.expected_count);
allPass = countExact && withinSuiteUnique && pairUnique && ...
    all(suiteComplete) && all(allResults.passed) && ...
    ~any(allResults.failed) && ~any(allResults.incomplete);
if all(suiteComplete)
    executionStatus = "COMPLETE";
else
    executionStatus = "INCOMPLETE";
end
if plan.numerical_terminal_state=="CONVERGED"
    campaignMode = "converged_full_validation";
else
    campaignMode = "nonconverged_direct_validation";
end
summary = struct( ...
    "schema_version","stage_A4_3_aggregate_test_summary_v1.0", ...
    "execution_status",char(executionStatus), ...
    "campaign_mode",char(campaignMode), ...
    "numerical_terminal_state", ...
        char(plan.numerical_terminal_state), ...
    "stage_pass_eligible", ...
        logical(plan.stage_pass_eligible && allPass), ...
    "existing_195_executed", ...
        any(allResults.suite_label=="stage_A4_regression_195"), ...
    "test_total",height(allResults), ...
    "test_passed",nnz(allResults.passed), ...
    "test_failed",nnz(allResults.failed), ...
    "test_incomplete",nnz(allResults.incomplete), ...
    "duration_seconds",sum(allResults.duration_seconds), ...
    "test_names_unique_within_suite",withinSuiteUnique, ...
    "suite_label_test_name_unique",pairUnique, ...
    "suite_counts",suiteCounts);

write_table_csv_17g(targets.inventory,allInventory);
write_table_csv_17g(targets.results,allResults);
write_junit(targets.junit,allResults,campaignMode);
write_utf8(targets.command,strjoin(commands,newline)+newline);
write_utf8(targets.console,strjoin(logs,newline)+newline);
write_json_file(targets.summary,summary);
write_hash_manifest(targets);
aggregate = struct( ...
    "plan",plan, ...
    "inventory",allInventory, ...
    "results",allResults, ...
    "summary",summary, ...
    "paths",targets, ...
    "all_pass",allPass);
end

function [inventory,results,summary] = read_suite_evidence( ...
        directory,expectedLabel,expectedCount)
required = [ ...
    "test_inventory.csv"
    "test_results.csv"
    "test_results.xml"
    "matlab_test_console.log"
    "test_command.txt"
    "test_summary.json"
    "test_evidence_sha256.csv"];
paths = fullfile(directory,required);
assert(all(isfile(paths)), ...
    "stageA4:a43:tests:AggregateSuiteMissing", ...
    "Suite evidence is incomplete: %s",directory);
inventory = read_csv_table(paths(1));
results = read_csv_table(paths(2));
summary = jsondecode(fileread(paths(6)));
assert(all(ismember(["test_order","test_name","source_file"], ...
    string(inventory.Properties.VariableNames))) && ...
    all(ismember(["test_name","passed","failed","incomplete", ...
    "duration_seconds","details"], ...
    string(results.Properties.VariableNames))), ...
    "stageA4:a43:tests:AggregateSuiteSchema", ...
    "Suite evidence schema is invalid: %s",directory);
assert(string(summary.suite_label)==expectedLabel && ...
    double(summary.test_total)==expectedCount && ...
    height(inventory)==expectedCount && height(results)==expectedCount && ...
    isequal(string(inventory.test_name),string(results.test_name)) && ...
    numel(unique(string(results.test_name)))==expectedCount && ...
    validate_junit(paths(3),expectedCount) && ...
    validate_hashes(paths(7),directory), ...
    "stageA4:a43:tests:AggregateSuiteIdentity", ...
    "Suite identity/count/hash evidence is invalid: %s",expectedLabel);
end

function validate_specialty_binding(directory,runId)
pathValue = fullfile(directory,"suite_identity.json");
assert(isfile(pathValue), ...
    "stageA4:a43:tests:AggregateSpecialtyBinding", ...
    "A4-3 specialty evidence is not bound to the formal run.");
identity = jsondecode(fileread(pathValue));
assert(string(identity.run_id)==runId && ...
    string(identity.suite_label)=="stage_A4_3" && ...
    double(identity.test_total)==27, ...
    "stageA4:a43:tests:AggregateSpecialtyBinding", ...
    "A4-3 specialty suite identity does not match the formal run.");
end

function passed = grouped_names_unique(results)
labels = unique(results.suite_label,"stable");
passed = true;
for label = labels.'
    names = results.test_name(results.suite_label==label);
    passed = passed && numel(unique(names))==numel(names);
end
end

function value = logical_column(value)
if islogical(value)
    return
end
if isnumeric(value)
    value = logical(value);
    return
end
text = lower(strip(string(value)));
assert(all(ismember(text,["true","false","1","0"])), ...
    "stageA4:a43:tests:AggregateLogical", ...
    "Test result contains an invalid logical value.");
value = text=="true" | text=="1";
end

function passed = validate_junit(pathValue,expectedCount)
passed = false;
try
    document = xmlread(pathValue);
    passed = double(document.getElementsByTagName( ...
        "testcase").getLength())==expectedCount;
catch
end
end

function passed = validate_hashes(pathValue,directory)
passed = false;
hashes = read_csv_table(pathValue);
if ~all(ismember(["names","sha256","bytes","status"], ...
        string(hashes.Properties.VariableNames))) || ...
        height(hashes)~=6 || any(hashes.status~="PASS")
    return
end

for k = 1:height(hashes)
    target = fullfile(directory,hashes.names(k));
    info = dir(target);
    if ~isfile(target) || ~isscalar(info) || ...
            double(hashes.bytes(k))~=info.bytes || ...
            lower(hashes.sha256(k))~= ...
            lower(compute_sha256_file(target))
        return
    end
end
passed = true;
end

function value = read_csv_table(pathValue)
options = detectImportOptions(pathValue,"Delimiter",",", ...
    "TextType","string","VariableNamingRule","preserve");
value = readtable(pathValue,options);
end

function paths = aggregate_paths(directory)
paths = struct( ...
    "inventory",fullfile(directory,"test_inventory.csv"), ...
    "results",fullfile(directory,"test_results.csv"), ...
    "junit",fullfile(directory,"test_results.xml"), ...
    "console",fullfile(directory,"matlab_test_console.log"), ...
    "command",fullfile(directory,"test_command.txt"), ...
    "summary",fullfile(directory,"test_summary.json"), ...
    "hashes",fullfile(directory,"test_evidence_sha256.csv"));
end

function write_junit(pathValue,results,label)
failures = nnz(results.failed);
errors = nnz(results.incomplete);
duration = sum(results.duration_seconds);
lines = ["<?xml version=""1.0"" encoding=""UTF-8""?>"; ...
    "<testsuites name="""+xml_escape(label)+""" tests="""+ ...
    string(height(results))+""" failures="""+string(failures)+ ...
    """ errors="""+string(errors)+""" skipped=""0"" time="""+ ...
    compose("%.17g",duration)+""">"; ...
    "<testsuite name="""+xml_escape(label)+""" tests="""+ ...
    string(height(results))+""" failures="""+string(failures)+ ...
    """ errors="""+string(errors)+""" skipped=""0"" time="""+ ...
    compose("%.17g",duration)+""">"];
for k = 1:height(results)
    name = results.suite_label(k)+"::"+results.test_name(k);
    lines(end+1,1) = "<testcase classname="""+ ...
        xml_escape(results.suite_label(k))+""" name="""+ ...
        xml_escape(name)+""" time="""+ ...
        compose("%.17g",results.duration_seconds(k))+""">"; %#ok<AGROW>
    if results.failed(k)
        lines(end+1,1) = "<failure message=""test failed"">"+ ...
            xml_escape(results.details(k))+"</failure>"; %#ok<AGROW>
    elseif results.incomplete(k)
        lines(end+1,1) = ...
            "<error message=""test incomplete"">"+ ...
            xml_escape(results.details(k))+"</error>"; %#ok<AGROW>
    end
    lines(end+1,1) = "</testcase>"; %#ok<AGROW>
end
lines = [lines;"</testsuite>";"</testsuites>"];
write_utf8(pathValue,strjoin(lines,newline)+newline);
end

function write_hash_manifest(paths)
names = [ ...
    "test_inventory.csv"
    "test_results.csv"
    "test_results.xml"
    "matlab_test_console.log"
    "test_command.txt"
    "test_summary.json"];
targets = [string(paths.inventory);string(paths.results); ...
    string(paths.junit);string(paths.console);string(paths.command); ...
    string(paths.summary)];
sha256 = strings(numel(targets),1);
bytes = zeros(numel(targets),1);
for k = 1:numel(targets)
    sha256(k) = compute_sha256_file(targets(k));
    info = dir(targets(k));
    bytes(k) = info.bytes;
end
status = repmat("PASS",numel(targets),1);
write_table_csv_17g(paths.hashes, ...
    table(names,sha256,bytes,status));
end

function write_utf8(pathValue,textValue)
[fileId,message] = fopen(pathValue,"wb","n","UTF-8");
assert(fileId>=0,"stageA4:a43:tests:AggregateWrite","%s",message);
guard = onCleanup(@()close_file(fileId));
bytes = unicode2native(char(textValue),"UTF-8");
count = fwrite(fileId,bytes,"uint8");
assert(count==numel(bytes), ...
    "stageA4:a43:tests:AggregateWrite", ...
    "Incomplete aggregate evidence write: %s",pathValue);
status = fclose(fileId);
clear guard
assert(status==0,"stageA4:a43:tests:AggregateWrite", ...
    "Could not close aggregate evidence: %s",pathValue);
end

function close_file(fileId)
try
    if ischar(fopen(fileId))
        fclose(fileId);
    end
catch
end
end

function value = xml_escape(value)
value = replace(string(value),"&","&amp;");
value = replace(value,"<","&lt;");
value = replace(value,">","&gt;");
value = replace(value,'"',"&quot;");
value = replace(value,"'","&apos;");
end
