function plan = plan_stage_a4_3_test_campaign(numericalTerminalState)
%PLAN_STAGE_A4_3_TEST_CAMPAIGN Return the fixed post-run test gate.
%
% CONVERGED is the only state that authorizes the one-time 195-test
% regression.  Failure terminals deliberately remain a small, directly
% relevant campaign and can never make Stage A4 eligible for PASS.

arguments
    numericalTerminalState (1,1) string
end
terminal = upper(strip(numericalTerminalState));
assert(ismember(terminal, ...
    ["CONVERGED","MAX_ITERATIONS","NUMERICAL_FAILURE"]), ...
    "stageA4:a43:tests:TerminalState", ...
    "Unsupported completed A4-3 numerical terminal state: %s",terminal);

if terminal=="CONVERGED"
    suiteLabel = [ ...
        "stage_A4_3"
        "stage_A4_RNS_1"
        "stage_A4_2D_2A_R1"
        "stage_A4_regression_195"];
    expectedCount = [27;17;18;195];
    relativeDirectory = [ ...
        "a4_3_specialty"
        "a4_rns_1"
        "a4_2d_2a_r1"
        "regression_195"];
    stagePassEligible = true;
else
    suiteLabel = [ ...
        "stage_A4_3"
        "stage_A4_3_finalizer"];
    expectedCount = [27;5];
    relativeDirectory = [ ...
        "a4_3_specialty"
        "a4_3_finalizer"];
    stagePassEligible = false;
end
suiteOrder = uint32((1:numel(suiteLabel)).');
suites = table(suiteOrder,suiteLabel,expectedCount,relativeDirectory, ...
    'VariableNames',{'suite_order','suite_label','expected_count', ...
    'relative_directory'});
plan = struct( ...
    "schema_version","stage_A4_3_test_campaign_plan_v1.0", ...
    "numerical_terminal_state",terminal, ...
    "suites",suites, ...
    "expected_total",sum(expectedCount), ...
    "stage_pass_eligible",stagePassEligible, ...
    "existing_195_authorized",terminal=="CONVERGED");
if terminal=="CONVERGED"
    assert(plan.expected_total==257 && height(suites)==4, ...
        "stageA4:a43:tests:ConvergedPlan", ...
        "The converged A4-3 campaign must be exactly 257 tests.");
else
    assert(plan.expected_total==32 && ...
        ~any(suites.suite_label=="stage_A4_regression_195"), ...
        "stageA4:a43:tests:FailurePlan", ...
        "A nonconverged A4-3 campaign must exclude the 195-test regression.");
end
end
