function linearization = build_stage_b_multiday_linearization( ...
        state,data,index,config)
%BUILD_STAGE_B_MULTIDAY_LINEARIZATION Build the unique B-2A model view.
%
% The frozen Stage-A prefix and all 56 nonlinear water rows are assembled
% into one residual/Jacobian/Hessian object.  The KKT assembler consumes
% this object directly; no solve or state update occurs here.

arguments
    state (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
end

validate_inputs(state,index,config);
baseIndex = index.stage_a_base_index;
baseConfig = config.stage_a_compatibility;
nBaseInequality = baseIndex.counts.inequalities;
baseState = state;
baseState.stage_id = "stage_A4";
baseState.l = state.l(1:nBaseInequality);
baseState.z = state.z(1:nBaseInequality);
baseLinearization = rkkt.model.build_stage_a_multiday_linearization( ...
    baseState,data,baseIndex,baseConfig,"SlackMode","explicit");
water = rkkt.model.assemble_stage_b_water_linearization(state.xi,data,index,config);

A = baseLinearization.A;
G = [baseLinearization.G;water.G];
equalityOffset = baseLinearization.constraints.eq_offset;
inequalityOffset = [baseLinearization.constraints.ineq_offset;water.offset];
equalityValue = A*state.xi+equalityOffset;
inequalityValue = [baseLinearization.constraints.ineq; ...
    water.constraint_value];
linearizedValue = G*state.xi+inequalityOffset;
identityErrorVector = linearizedValue-inequalityValue;

objectiveGradient = baseLinearization.objective.gradient;
objectiveHessian = baseLinearization.H;
lagrangianHessian = objectiveHessian;
weightedRows = repmat(weighted_record_template(), ...
    numel(water.constraint_hessians),1);
for row = 1:numel(water.constraint_hessians)
    record = water.constraint_hessians(row);
    multiplier = state.z(record.inequality_position);
    contribution = multiplier*record.global_hessian;
    lagrangianHessian = lagrangianHessian+contribution;
    weightedRows(row) = struct( ...
        "constraint_id",record.constraint_id, ...
        "inequality_position",record.inequality_position, ...
        "multiplier",multiplier, ...
        "sign",record.sign, ...
        "contribution_nnz",nnz(contribution), ...
        "contribution_frobenius_norm",norm(contribution,"fro"));
end

l = state.l(:);
z = state.z(:);
gap = mean(l.*z);
mu = config.initialization.centering_sigma*gap;
rEq = equalityValue;
rIneq = inequalityValue+l;
rDual = objectiveGradient+A.'*state.y+G.'*z;
rComp = l.*z-mu;
assert(all(isfinite([rEq;rIneq;rDual;rComp])) && mu>0, ...
    "stageB2A:linearization:FiniteResidual", ...
    "The B-2A structure-audit residual contains a nonfinite value.");

finalState = state;
finalState.mu = mu;
stateFingerprint = rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(finalState);
inputHashes = lower(string(data.hashes.actualSHA256));
identity = "stage-B2A-linearization-v1.0|"+ ...
    strjoin(inputHashes,"|")+"|days"+string(config.days(1))+"-"+ ...
    string(config.days(end))+"|hours1-24|state="+ ...
    stateFingerprint+"|index="+string(index.version);

linearization = struct();
linearization.identity = identity;
linearization.version = "stage-B2A-linearization-v1.0";
linearization.stage_id = "stage_B";
linearization.milestone_id = "B-2A";
linearization.state_fingerprint = stateFingerprint;
linearization.state = finalState;
linearization.objective = struct("value", ...
    baseLinearization.objective.value,"gradient",objectiveGradient, ...
    "hessian",objectiveHessian);
linearization.constraints = struct("eq",equalityValue, ...
    "ineq",inequalityValue,"eq_offset",equalityOffset, ...
    "ineq_offset",inequalityOffset,"water",water);
linearization.jacobian = struct("A",A,"G",G, ...
    "water_G",water.G);
linearization.hessian = struct( ...
    "objective",objectiveHessian, ...
    "constraint_water",water.constraint_hessians, ...
    "constraint_water_weighted",weightedRows, ...
    "lagrangian",lagrangianHessian);
linearization.H = lagrangianHessian;
linearization.A = A;
linearization.G = G;
linearization.r_dual = rDual;
linearization.r_eq = rEq;
linearization.r_ineq = rIneq;
linearization.r_comp = rComp;
linearization.l = l;
linearization.z = z;
linearization.mu = mu;
linearization.implied_slack = -inequalityValue;
linearization.complementarity_gap = gap;
linearization.raw_complementarity = l.'*z;
linearization.linearization_identity_error_vector = identityErrorVector;
linearization.linearization_identity_error = ...
    norm(identityErrorVector,inf);
linearization.lagrangian_hessian_symmetry_relative = ...
    relative_symmetry_error(lagrangianHessian);
linearization.index = index;
linearization.fixed_zero_map = index.fixed_zero_map;
linearization.permutation = index.permutation_map;
linearization.maps = baseLinearization.maps;
linearization.maps.ineq_water = ...
    index.water_constraint_index.inequality_position;
linearization.maps.ineq_water_by_day_hydro = ...
    build_water_map(index.water_constraint_index,config);
linearization.layout = baseLinearization.layout;
linearization.capacity_parameters = baseLinearization.capacity_parameters;
linearization.model_contract_version = "1.0";
linearization.index_version = index.version;
linearization.counts = struct("primal",numel(state.xi), ...
    "equalities",numel(state.y),"inequalities",numel(state.z), ...
    "water_inequalities",height(index.water_constraint_index), ...
    "full_kkt",numel(state.xi)+numel(state.y)+2*numel(state.z), ...
    "stage_a_full_kkt",baseLinearization.counts.full_kkt);
linearization.execution = struct("full_kkt_assembled",false, ...
    "full_kkt_solved",false,"recursive_direction_executed",false, ...
    "newton_direction_count",0,"full_ipm_executed",false, ...
    "optimization_executed",false,"state_update_executed",false, ...
    "parallel_executed",false,"stage_c1_entered",false);
linearization.base_linearization_identity = baseLinearization.identity;

validate_output(linearization,index,config);
end

function validate_inputs(state,index,config)
required = ["xi","y","l","z","iteration_index", ...
    "state_revision","newton_direction_number", ...
    "completed_newton_direction_count"];
assert(all(isfield(state,cellstr(required))) && ...
    string(config.stage_id)=="stage_B" && ...
    string(config.milestone_id)=="B-2A" && ...
    string(index.scope.stage_id)=="stage_B", ...
    "stageB2A:linearization:Contract", ...
    "State, configuration, and index do not identify B-2A.");
assert(numel(state.xi)==index.counts.variables && ...
    numel(state.y)==index.counts.equalities && ...
    numel(state.l)==index.counts.inequalities && ...
    numel(state.z)==index.counts.inequalities && ...
    all(state.l>0) && all(state.z>0), ...
    "stageB2A:linearization:StateDimension", ...
    "The B-2A state dimensions or positivity are invalid.");
end

function validate_output(lin,index,config)
assert(issparse(lin.H) && issparse(lin.A) && issparse(lin.G) && ...
    isequal(size(lin.H),[index.counts.variables,index.counts.variables]) && ...
    isequal(size(lin.A),[index.counts.equalities,index.counts.variables]) && ...
    isequal(size(lin.G),[index.counts.inequalities,index.counts.variables]) && ...
    lin.counts.full_kkt==config.expected_full_kkt_dimension && ...
    lin.counts.water_inequalities==config.expected_water_inequality_count, ...
    "stageB2A:linearization:Dimensions", ...
    "The unified B-2A linearization dimensions are invalid.");
% B-2A's structure fixture deliberately used unequal diagnostic water
% multipliers, so its historical validator required a nonzero weighted H.
% B-2B starts from the shared positive multiplier and may legitimately
% produce a zero water-curvature contribution when upper/lower Hessians
% cancel.  Keep the B-2A gate byte-for-byte for its own identity while
% allowing this mathematically valid B-2B state.
isB2B = isfield(index,"scope") && isfield(index.scope,"milestone_id") && ...
    string(index.scope.milestone_id)=="B-2B";
assert(nnz(lin.objective.hessian)==0 && (nnz(lin.H)>0 || isB2B) && ...
    lin.lagrangian_hessian_symmetry_relative<= ...
        config.lagrangian_hessian_symmetry_tolerance, ...
    "stageB2A:linearization:Hessian", ...
    "Objective and Lagrangian Hessian roles are inconsistent.");
scale = max(1,norm(lin.constraints.ineq,inf));
assert(lin.linearization_identity_error<=64*eps(scale) && ...
    norm(lin.G*lin.state.xi+lin.constraints.ineq_offset- ...
        lin.constraints.ineq,inf)<=64*eps(scale), ...
    "stageB2A:linearization:OffsetIdentity", ...
    "G*x+offset does not reproduce the current nonlinear values.");
assert(isequaln(index.variable_index, ...
        index.stage_a_base_index.variable_index) && ...
    isequaln(index.fixed_zero_map, ...
        index.stage_a_base_index.fixed_zero_map) && ...
    isequaln(index.soc_link_map,index.stage_a_base_index.soc_link_map), ...
    "stageB2A:linearization:StageABaseline", ...
    "The B-2A linearization changed a frozen Stage-A mapping.");
end

function value = build_water_map(waterIndex,config)
value = cell(numel(config.days),numel(config.hydro_ids));
for dayPosition = 1:numel(config.days)
    for hydroPosition = 1:numel(config.hydro_ids)
        rows = waterIndex.day==config.days(dayPosition) & ...
            waterIndex.hydro_id==config.hydro_ids(hydroPosition);
        assert(nnz(rows)==2, ...
            "stageB2A:linearization:WaterMap", ...
            "Each day-hydro pair must map to upper/lower rows.");
        value{dayPosition,hydroPosition} = ...
            waterIndex.inequality_position(rows);
    end
end
end

function value = relative_symmetry_error(matrix)
value = norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro"));
end

function value = weighted_record_template()
value = struct("constraint_id","","inequality_position",0, ...
    "multiplier",0,"sign",0,"contribution_nnz",0, ...
    "contribution_frobenius_norm",0);
end
