function lin = build_stage_b2c_scaled_objective_linearization( ...
        state,data,index,config,chainId)
%BUILD_STAGE_B2C_SCALED_OBJECTIVE_LINEARIZATION Unitize only the objective.

arguments
    state (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    chainId (1,1) string = "B-2C-FORMAL-IPM"
end
base = rkkt.model.build_stage_b2c_multiday_linearization(state,data,index,config);
q = base.maps.q_global(:);
originalGradient = base.objective.gradient;
scaleFactor = max(abs(originalGradient(q)));
assert(numel(q)==14 && numel(unique(q))==14 && ...
    isfinite(scaleFactor) && scaleFactor>0, ...
    "stageB2C:linearization:ObjectiveScale", ...
    "The positive objective scale must come from 14 global capacities.");
outside = true(numel(originalGradient),1);
outside(q) = false;
assert(all(originalGradient(outside)==0), ...
    "stageB2C:linearization:ObjectiveSupport", ...
    "The investment objective must be supported only on global q.");
lin = base;
lin.objective.original_gradient = originalGradient;
lin.objective.original_value = base.objective.value;
lin.objective.gradient = originalGradient/scaleFactor;
lin.objective.value = base.objective.value/scaleFactor;
lin.r_dual = lin.objective.gradient+lin.A.'*lin.state.y+lin.G.'*lin.state.z;
lin.base_identity = base.identity;
lin.identity = base.identity+"|objective_scale=positive_scalar_unitization"+ ...
    "|factor="+string(compose("%.17g",scaleFactor))+"|chain="+chainId;
lin.objective_scale = struct("enabled",true, ...
    "mode","positive_scalar_unitization", ...
    "scale_source","max_abs_global_capacity_gradient", ...
    "factor",scaleFactor,"chain_id",chainId, ...
    "original_gradient",originalGradient, ...
    "scaled_gradient",lin.objective.gradient, ...
    "original_value",lin.objective.original_value, ...
    "scaled_value",lin.objective.value);
lin.residual_definitions = struct( ...
    "r_eq","A*xi+eq_offset", ...
    "r_ineq","G*xi+ineq_offset+l", ...
    "r_dual","scaled_objective_gradient+A'*y+G'*z", ...
    "r_comp","l.*z-sigma*mean(l.*z)");
% The deterministic initial-state metadata intentionally contains NaN for
% quantities that do not exist before the first Newton direction.  Use
% ISEQUALN so those sentinels do not turn this invariance audit into a false
% failure; the numerical operators and residuals are still compared exactly.
assert(isequaln(lin.H,base.H) && isequaln(lin.A,base.A) && ...
    isequaln(lin.G,base.G) && isequaln(lin.r_eq,base.r_eq) && ...
    isequaln(lin.r_ineq,base.r_ineq) && isequaln(lin.r_comp,base.r_comp) && ...
    isequaln(lin.state,base.state), ...
    "stageB2C:linearization:ScaleInvariance", ...
    "Objective unitization changed a frozen state, matrix, or constraint.");
end
