function config = build_stage_b2c_runtime_configuration( ...
        projectRoot,settings,data)
%BUILD_STAGE_B2C_RUNTIME_CONFIGURATION Resolve one contiguous B-2C scope.

arguments
    projectRoot (1,1) string
    settings (1,1) struct
    data (1,1) struct
end
projectRoot = string(java.io.File(char(projectRoot)).getCanonicalPath());
explicitDaySet = isfield(settings,"explicit_day_set") && ...
    isscalar(settings.explicit_day_set) && ...
    logical(settings.explicit_day_set);
contiguousDays = isequal(settings.days,settings.day_start:settings.day_end);
assert((contiguousDays || explicitDaySet) && ...
    isequal(settings.days,unique(settings.days,"stable")) && ...
    issorted(settings.days,"strictascend") && ...
    all(settings.days>=1) && all(settings.days<=data.meta.nDays), ...
    "stageB2C:runtimeConfig:Days", ...
    "Runtime days must be one ascending unique set inside the annual data.");

% Use the already audited B-2C algorithm constants, then replace only the
% explicitly variable horizon, audit route, iteration limit and dimensions.
base = rkkt.model.load_stage_b2c_configuration( ...
    projectRoot,Profile="supplemental_365_day_serial", ...
    CurrentStageExceptionToken= ...
        "B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED");
config = base;
if explicitDaySet
    config.description = compose( ...
        "第%d—%d日显式选定%d日Stage B-2C递推IPM", ...
        settings.day_start,settings.day_end,numel(settings.days));
    config.run_purpose = "stage_B_2C_configured_explicit_day_set";
    config.time_scope_type = "configured_explicit_day_scope";
else
    config.description = compose("第%d—%d日统一入口Stage B-2C递推IPM", ...
        settings.day_start,settings.day_end);
    config.run_purpose = "stage_B_2C_configured_contiguous_range";
    config.time_scope_type = "configured_contiguous_day_scope";
end
config.parent_run_id = "";
config.days = settings.days;
config.hours = 1:24;
config.hydro_ids = 1:4;
config.start_hour = 1;
config.terminal_hour = 24;
config.max_iterations = settings.max_iterations;
config.audit_mode = settings.audit_mode;
config.core_consistency_max_passes = ...
    settings.core_consistency_max_passes;
config.compensated_core_accumulation = ...
    settings.compensated_core_accumulation;
config.full_kkt_enabled = settings.audit_mode=="full_kkt";
config.full_kkt_solve_enabled = config.full_kkt_enabled;
config.full_kkt_audit_enabled = config.full_kkt_enabled;
if config.full_kkt_enabled
    config.full_kkt_role = "audit_only";
    config.recursive_refinement_max_passes = 0;
else
    config.full_kkt_role = "not_executed_configured_recursive_only";
    config.recursive_refinement_max_passes = 3;
end
config.annual_scope_enabled = false;
config.parallel_enabled = settings.parallel_enabled;
config.parallel_worker_count = settings.parallel_worker_count;
config.parallel_pool_auto_resize = settings.parallel_pool_auto_resize;
config.parallel_pool_keep_alive = settings.parallel_pool_keep_alive;
if config.parallel_enabled
    config.parallel_mode = "daily_joint_blocks_processes";
else
    config.parallel_mode = "off";
end

dimensions = derive_dimensions(data,config.days,config.hours);
names = fieldnames(dimensions);
for k = 1:numel(names)
    config.(names{k}) = dimensions.(names{k});
end
config.stage_a_compatibility = synchronize_stage_a(config);
config.source_paths.run_project = settings.config_path;
config.runtime_configuration_version = ...
    "stage-B2C-configured-runtime-v2";
validate_runtime(config,settings,data,explicitDaySet);
end

function value = derive_dimensions(data,days,hours)
nDays = numel(days);
windActive = nnz(data.timeseries.windAvailability(days,hours,:)~=0);
solarActive = nnz(data.timeseries.solarAvailability(days,hours,:)~=0);
thermalActive = nDays*numel(hours)*data.meta.nThermal;
alwaysActive = nDays*numel(hours)*(data.meta.nHydro+3*data.meta.nStorage);
hourlyActive = windActive+solarActive+thermalActive+alwaysActive;
possibleAvailability = nDays*numel(hours)*(data.meta.nWind+ ...
    data.meta.nSolar+data.meta.nThermal);
fixedZero = possibleAvailability-windActive-solarActive-thermalActive;

primal = 14+14*nDays+hourlyActive;
equalities = data.meta.nStorage+14*nDays+ ...
    nDays*numel(hours)*(1+data.meta.nStorage)+ ...
    nDays*data.meta.nStorage;
baseInequalities = 28+2*hourlyActive;
waterInequalities = nDays*data.meta.nHydro*2;
baseFullKkt = primal+equalities+2*baseInequalities;

dailyChain = zeros(1,nDays);
for position = 1:nDays
    day = days(position);
    active = nnz(data.timeseries.windAvailability(day,hours,:)~=0)+ ...
        nnz(data.timeseries.solarAvailability(day,hours,:)~=0)+ ...
        numel(hours)*(data.meta.nHydro+data.meta.nThermal+ ...
        3*data.meta.nStorage);
    dailyEqualities = numel(hours)*(1+data.meta.nStorage)+ ...
        data.meta.nStorage;
    dailyChain(position) = active+dailyEqualities;
end

value = struct( ...
    "expected_nonzero_water_hessian_nnz",96*nDays, ...
    "expected_stage_a_primal_dimension",primal, ...
    "expected_stage_a_equality_dimension",equalities, ...
    "expected_stage_a_inequality_dimension",baseInequalities, ...
    "expected_stage_a_full_kkt_dimension",baseFullKkt, ...
    "expected_stage_a_daily_hourly_chain_dimensions",dailyChain, ...
    "expected_stage_a_total_hourly_chain_dimension",sum(dailyChain), ...
    "expected_stage_a_fixed_zero_count",fixedZero, ...
    "expected_water_inequality_count",waterInequalities, ...
    "expected_water_border_dimension_per_day",0, ...
    "expected_day_response_dimension",14, ...
    "expected_global_core_dimension",16, ...
    "expected_daily_joint_dimensions",dailyChain+28, ...
    "expected_full_kkt_dimension",baseFullKkt+2*waterInequalities, ...
    "expected_final_water_audit_rows",nDays*data.meta.nHydro, ...
    "expected_rhs_per_day",15);
end

function value = synchronize_stage_a(config)
value = config.stage_a_compatibility;
value.stage_id = "stage_A4";
value.days = config.days;
value.hours = config.hours;
value.aggregation_day_order = config.days;
value.start_hour = config.start_hour;
value.terminal_hour = config.terminal_hour;
value.soc_boundary_mode = config.soc_boundary_mode;
value.time_scope_type = config.time_scope_type;
value.run_purpose = config.run_purpose+"_stage_a_view";
value.expected_full_kkt_dimension = ...
    config.expected_stage_a_full_kkt_dimension;
value.expected_daily_hourly_chain_dimensions = ...
    config.expected_stage_a_daily_hourly_chain_dimensions;
value.expected_total_hourly_chain_dimension = ...
    config.expected_stage_a_total_hourly_chain_dimension;
value.expected_fixed_zero_count = config.expected_stage_a_fixed_zero_count;
end

function validate_runtime(config,settings,data,explicitDaySet)
assert(config.stage_id=="stage_B" && config.milestone_id=="B-2C" && ...
    isequal(config.days,settings.days) && ...
    (explicitDaySet || ...
        isequal(config.days,settings.day_start:settings.day_end)) && ...
    isequal(config.hours,1:24) && isequal(config.hydro_ids,1:4) && ...
    config.soc_boundary_mode=="formal_daily_fixed_half_energy" && ...
    all(data.base.storage.initialSocFraction==0.5), ...
    "stageB2C:runtimeConfig:Scope", ...
    "The configured runtime must preserve complete independent formal days.");
assert(config.parallel_enabled==settings.parallel_enabled && ...
    (~config.parallel_enabled || settings.audit_mode=="recursive_only") && ...
    ~config.annual_scope_enabled && ...
    ~config.thermal_second_pass_enabled && ~config.stage_c1_implemented && ...
    config.recursive_direction_enabled && config.ipm_enabled && ...
    config.optimization_enabled && config.state_update_enabled && ...
    config.checkpoint_after_each_accepted_update && ...
    ~config.full_kkt_direction_fallback_enabled, ...
    "stageB2C:runtimeConfig:ExecutionBoundary", ...
    "The configured run changed a frozen Stage B execution boundary.");
assert(config.core_consistency_max_passes>=1 && ...
    config.core_consistency_max_passes<=10 && ...
    config.core_consistency_max_passes==fix( ...
        config.core_consistency_max_passes) && ...
    islogical(config.compensated_core_accumulation) && ...
    isscalar(config.compensated_core_accumulation), ...
    "stageB2C:runtimeConfig:CoreConsistency", ...
    "The configured core-consistency controls are invalid.");
if settings.audit_mode=="full_kkt"
    assert(numel(config.days)==7 && config.full_kkt_enabled && ...
        config.full_kkt_solve_enabled && config.full_kkt_audit_enabled && ...
        config.recursive_refinement_max_passes==0, ...
        "stageB2C:runtimeConfig:FullKkt", ...
        "Seven-day full-KKT audit configuration is inconsistent.");
else
    assert(~config.full_kkt_enabled && ~config.full_kkt_solve_enabled && ...
        ~config.full_kkt_audit_enabled && ...
        config.recursive_refinement_max_passes==3, ...
        "stageB2C:runtimeConfig:Recursive", ...
        "Recursive-only configuration must not enable a full KKT route.");
end
end
