function structure = build_stage_b2c_recursive_structure( ...
        data,config,topologyFingerprint)
%BUILD_STAGE_B2C_RECURSIVE_STRUCTURE Build compact maps without an index.

% This production structural builder emits the frozen canonical ordering
% directly from integer cursors.  It does not construct variable/constraint
% tables and never calls a canonical-index builder.

arguments
    data (1,1) struct
    config (1,1) struct
    topologyFingerprint (1,1) struct
end
days = reshape(double(config.days),1,[]);
hours = reshape(double(config.hours),1,[]);
nDays = numel(days);
nHours = numel(hours);
assert(isequal(hours,1:24) && string(config.milestone_id)=="B-2C" && ...
    string(topologyFingerprint.version)== ...
        "stage-B2C-structural-topology-fingerprint-v1.0", ...
    "stageB2C:recursiveStructure:Scope", ...
    "The compact structural builder requires complete B-2C days.");

nx = config.expected_stage_a_primal_dimension;
neq = config.expected_stage_a_equality_dimension;
nBase = config.expected_stage_a_inequality_dimension;
nWater = config.expected_water_inequality_count;
nineq = nBase+nWater;
qGlobal = uint32((1:14).');
yDuration = uint32((1:2).');
qDayMatrix = reshape(uint32(15:14+14*nDays),14,nDays);

physical = struct( ...
    "days",days,"hours",hours, ...
    "global_capacity_positions",qGlobal, ...
    "daily_capacity_positions",qDayMatrix.', ...
    "wind_positions",zeros(nDays,nHours,data.meta.nWind,"uint32"), ...
    "solar_positions",zeros(nDays,nHours,data.meta.nSolar,"uint32"), ...
    "hydro_positions",zeros(nDays,nHours,data.meta.nHydro,"uint32"), ...
    "thermal_positions",zeros(nDays,nHours,data.meta.nThermal,"uint32"), ...
    "charge_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"), ...
    "discharge_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"), ...
    "soc_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"));

qDayByDay = cell(nDays,1);
yBindingByDay = cell(nDays,1);
xByDayHour = cell(nDays,nHours);
yByDayHour = cell(nDays,nHours);
ineqByDayHour = cell(nDays,nHours);
waterByDay = cell(nDays,1);
dayCells = cell(nDays,1);
dailyChainDimensions = zeros(1,nDays);

variableCursor = 14+14*nDays;
equalityCursor = 2;
inequalityCursor = 28;
for d = 1:nDays
    dayId = days(d);
    qDay = qDayMatrix(:,d);
    qDayByDay{d} = double(qDay);
    yBinding = uint32(equalityCursor+(1:14).');
    equalityCursor = equalityCursor+14;
    yBindingByDay{d} = double(yBinding);

    xCells = cell(nHours,1);
    yCells = cell(nHours,1);
    ineqCells = cell(nHours,1);
    typeCells = cell(nHours,1);
    assetCells = cell(nHours,1);
    variableCells = cell(nHours,1);
    hourCells = cell(nHours,1);
    for t = 1:nHours
        hourId = hours(t);
        [assetType,assetId,variableCode] = hour_descriptor( ...
            data,dayId,hourId);
        count = numel(assetType);
        positions = uint32(variableCursor+(1:count).');
        variableCursor = variableCursor+count;
        equalityCount = 3+2*double(hourId==24);
        equalityPositions = uint32(equalityCursor+(1:equalityCount).');
        equalityCursor = equalityCursor+equalityCount;
        inequalityPositions = uint32(inequalityCursor+(1:2*count).');
        inequalityCursor = inequalityCursor+2*count;

        xCells{t} = positions;
        yCells{t} = equalityPositions;
        ineqCells{t} = inequalityPositions;
        typeCells{t} = assetType;
        assetCells{t} = assetId;
        variableCells{t} = variableCode;
        hourCells{t} = repmat(uint8(hourId),count,1);
        xByDayHour{d,t} = double(positions);
        yByDayHour{d,t} = double(equalityPositions);
        ineqByDayHour{d,t} = double(inequalityPositions);
        physical = assign_physical_positions(physical,d,t,positions, ...
            assetType,assetId,variableCode);
    end

    xDay = vertcat(xCells{:});
    yHour = vertcat(yCells{:});
    baseRows = vertcat(ineqCells{:});
    assetType = vertcat(typeCells{:});
    assetId = vertcat(assetCells{:});
    variableCode = vertcat(variableCells{:});
    hourCode = vertcat(hourCells{:});
    primalIndices = [qDay;xDay];
    equalityIndices = [yBinding;yHour];
    nxLocal = numel(primalIndices);

    waterRows = uint32(nBase+(d-1)*2*data.meta.nHydro+ ...
        (1:2*data.meta.nHydro).');
    waterByDay{d} = double(waterRows);
    waterGlobalColumns = zeros(2*data.meta.nHydro,nHours,"uint32");
    waterLocalColumns = zeros(2*data.meta.nHydro,nHours,"uint32");
    for hydro = 1:data.meta.nHydro
        rowPair = 2*(hydro-1)+(1:2);
        for t = 1:nHours
            localMask = typeCells{t}==3 & assetCells{t}==hydro & ...
                variableCells{t}==3;
            position = xCells{t}(localMask);
            assert(isscalar(position), ...
                "stageB2C:recursiveStructure:HydroPosition", ...
                "Each hydro must have one active position per hour.");
            waterGlobalColumns(rowPair,t) = position;
            waterLocalColumns(rowPair,t) = ...
                uint32(14+double(position-xDay(1))+1);
        end
    end

    localPermutationCells = cell(2+2*nHours,1);
    localPermutationCells{1} = uint32((1:14).');
    localPermutationCells{2} = uint32(nxLocal+(1:14).');
    primalCursor = 14;
    localEqualityCursor = 14;
    position = 2;
    for t = 1:nHours
        position = position+1;
        localPermutationCells{position} = uint32( ...
            primalCursor+(1:numel(xCells{t})).');
        primalCursor = primalCursor+numel(xCells{t});
        position = position+1;
        localPermutationCells{position} = uint32( ...
            nxLocal+localEqualityCursor+(1:numel(yCells{t})).');
        localEqualityCursor = localEqualityCursor+numel(yCells{t});
    end
    localPermutation = vertcat(localPermutationCells{:});
    canonicalReduced = [qDay;uint32(nx)+yBinding];
    for t = 1:nHours
        canonicalReduced = [canonicalReduced;xCells{t}; ...
            uint32(nx)+yCells{t}]; %#ok<AGROW>
    end
    coupling = sparse(15:28,1:14,-ones(14,1), ...
        numel(localPermutation),16,14);
    dayCells{d} = struct( ...
        "day_id",uint16(dayId), ...
        "primal_indices",primalIndices, ...
        "equality_indices",equalityIndices, ...
        "base_inequality_rows",baseRows, ...
        "water_rows",waterRows, ...
        "x_by_hour",{xCells},"y_by_hour",{yCells}, ...
        "ineq_by_hour",{ineqCells}, ...
        "hourly_asset_type",assetType, ...
        "hourly_asset_id",assetId, ...
        "hourly_variable_code",variableCode, ...
        "hourly_hour",hourCode, ...
        "water_local_columns",waterLocalColumns, ...
        "water_global_columns",waterGlobalColumns, ...
        "local_reduced_permutation",localPermutation, ...
        "canonical_reduced_indices",canonicalReduced, ...
        "coupling",coupling, ...
        "q_day_local_positions",uint32((1:14).'), ...
        "pi_day_local_positions",uint32((15:28).'), ...
        "hourly_local_positions",uint32((29:numel(localPermutation)).'), ...
        "hourly_dimension",uint32(numel(localPermutation)-28), ...
        "dimension",uint32(numel(localPermutation)));
    dailyChainDimensions(d) = numel(localPermutation)-28;
end

assert(variableCursor==nx && equalityCursor==neq && ...
    inequalityCursor==nBase, ...
    "stageB2C:recursiveStructure:Cursors", ...
    "The direct structural cursors do not match configured dimensions.");

waterRows = uint32(nBase+(1:nWater).');
maps = struct( ...
    "days",days,"hours",hours,"q_global",double(qGlobal), ...
    "q_day",double(qDayMatrix),"q_day_by_day",{qDayByDay}, ...
    "y_duration",double(yDuration), ...
    "y_binding_by_day",{yBindingByDay}, ...
    "y_binding",vertcat(yBindingByDay{:}), ...
    "x_by_day_hour",{xByDayHour}, ...
    "y_by_day_hour",{yByDayHour}, ...
    "ineq_global",(1:28).', ...
    "ineq_by_day_hour",{ineqByDayHour}, ...
    "water_by_day",{waterByDay},"ineq_water",double(waterRows));
maps.direction = struct( ...
    "xi",uint32((1:nx).'), ...
    "y",uint32(nx+(1:neq).'), ...
    "l",uint32(nx+neq+(1:nineq).'), ...
    "z",uint32(nx+neq+nineq+(1:nineq).'));

counts = struct("variables",nx,"equalities",neq, ...
    "base_inequalities",nBase,"water_inequalities",nWater, ...
    "inequalities",nineq,"full_kkt_dimension", ...
        config.expected_full_kkt_dimension, ...
    "fixed_zero",config.expected_stage_a_fixed_zero_count);
runtime = build_runtime_maps(data,config,maps,physical,counts,dayCells);
structure = struct( ...
    "version","stage-B2C-recursive-structure-v1.0", ...
    "schema","stage-b2c-recursive-structure-cache-v1", ...
    "topology_fingerprint",string(topologyFingerprint.sha256), ...
    "topology_descriptor",topologyFingerprint.descriptor, ...
    "scope",runtime.scope,"counts",counts, ...
    "index_version","stage-B2C-water-index-v1.0", ...
    "model_contract_version","1.0", ...
    "maps",maps,"layout",struct("days",days,"hours",hours, ...
        "daily_chain_dimensions",dailyChainDimensions, ...
        "total_hourly_chain_dimension",sum(dailyChainDimensions)), ...
    "day",vertcat(dayCells{:}),"runtime",runtime);

assert(isequal(dailyChainDimensions, ...
        config.expected_stage_a_daily_hourly_chain_dimensions) && ...
    structure.counts.full_kkt_dimension== ...
        config.expected_full_kkt_dimension && ...
    structure.counts.fixed_zero==config.expected_stage_a_fixed_zero_count, ...
    "stageB2C:recursiveStructure:Contract", ...
    "The compact direct structure failed the configured dimension contract.");
end

function [assetType,assetId,variableCode] = hour_descriptor(data,day,hour)
wind = find(reshape(data.timeseries.windAvailability(day,hour,:),[],1)~=0);
solar = find(reshape(data.timeseries.solarAvailability(day,hour,:),[],1)~=0);
assetType = uint8([ones(numel(wind),1);2*ones(numel(solar),1); ...
    3*ones(data.meta.nHydro,1);4*ones(data.meta.nThermal,1); ...
    5*ones(3*data.meta.nStorage,1)]);
assetId = uint8([wind;solar;(1:data.meta.nHydro).'; ...
    (1:data.meta.nThermal).';repmat((1:data.meta.nStorage).',3,1)]);
variableCode = uint8([ones(numel(wind),1);2*ones(numel(solar),1); ...
    3*ones(data.meta.nHydro,1);4*ones(data.meta.nThermal,1); ...
    5*ones(data.meta.nStorage,1);6*ones(data.meta.nStorage,1); ...
    7*ones(data.meta.nStorage,1)]);
end

function physical = assign_physical_positions(physical,d,t,positions, ...
        assetType,assetId,variableCode)
for k = 1:numel(positions)
    asset = double(assetId(k));
    if assetType(k)==1
        physical.wind_positions(d,t,asset) = positions(k);
    elseif assetType(k)==2
        physical.solar_positions(d,t,asset) = positions(k);
    elseif assetType(k)==3
        physical.hydro_positions(d,t,asset) = positions(k);
    elseif assetType(k)==4
        physical.thermal_positions(d,t,asset) = positions(k);
    elseif variableCode(k)==5
        physical.charge_positions(d,t,asset) = positions(k);
    elseif variableCode(k)==6
        physical.discharge_positions(d,t,asset) = positions(k);
    else
        physical.soc_positions(d,t,asset) = positions(k);
    end
end
end

function runtime = build_runtime_maps(data,config,maps,physical,counts,days)
nDays = numel(config.days);
nineq = counts.inequalities;
constraint = struct( ...
    "kind",zeros(nineq,1,"uint8"), ...
    "bound_side",zeros(nineq,1,"uint8"), ...
    "day",zeros(nineq,1,"uint16"), ...
    "hour",zeros(nineq,1,"uint8"), ...
    "asset_type",zeros(nineq,1,"uint8"), ...
    "asset_id",zeros(nineq,1,"uint8"), ...
    "variable",zeros(nineq,1,"uint8"), ...
    "capacity",zeros(nineq,1,"uint8"));
constraint.kind(1:28) = 1;
constraint.bound_side(1:28) = repmat(uint8([1;2]),14,1);
constraint.capacity(1:28) = repelem(uint8((1:14).'),2,1);
constraint.asset_id(1:28) = repelem(uint8([1:5,1:5,1:2,1:2].'),2,1);
constraint.asset_type(1:28) = repelem(uint8([6*ones(1,5), ...
    7*ones(1,5),8*ones(1,2),9*ones(1,2)].'),2,1);

for d = 1:nDays
    fixed = days{d};
    cursor = 0;
    for t = 1:24
        rows = double(fixed.ineq_by_hour{t});
        count = numel(rows)/2;
        local = cursor+(1:count);
        constraint.kind(rows) = 2;
        constraint.bound_side(rows) = repmat(uint8([1;2]),count,1);
        constraint.day(rows) = uint16(config.days(d));
        constraint.hour(rows) = uint8(t);
        constraint.asset_type(rows) = repelem( ...
            fixed.hourly_asset_type(local),2,1);
        constraint.asset_id(rows) = repelem( ...
            fixed.hourly_asset_id(local),2,1);
        constraint.variable(rows) = repelem( ...
            fixed.hourly_variable_code(local),2,1);
        cursor = cursor+count;
    end
    rows = double(fixed.water_rows);
    constraint.kind(rows) = 3;
    constraint.bound_side(rows) = repmat(uint8([2;1]),data.meta.nHydro,1);
    constraint.day(rows) = uint16(config.days(d));
    constraint.asset_type(rows) = 3;
    constraint.asset_id(rows) = repelem(uint8((1:data.meta.nHydro).'),2,1);
    constraint.variable(rows) = 3;
end

balance = zeros(24*nDays,1,"uint32");
soc = zeros((48+2)*nDays,1,"uint32");
terminal = zeros(2*nDays,1,"uint32");
b = 0; s = 0; e = 0;
for d = 1:nDays
    for t = 1:24
        rows = uint32(maps.y_by_day_hour{d,t});
        b = b+1; balance(b) = rows(1);
        soc(s+(1:2)) = rows(2:3); s = s+2;
        if t==24
            terminal(e+(1:2)) = rows(4:5); e = e+2;
            soc(s+(1:2)) = rows(4:5); s = s+2;
        end
    end
end
waterRows = uint32(maps.ineq_water(:));
water = struct( ...
    "inequality_position",waterRows, ...
    "day",repelem(uint16(config.days(:)),2*data.meta.nHydro,1), ...
    "hydro_id",repmat(repelem(uint8((1:data.meta.nHydro).'),2,1), ...
        nDays,1), ...
    "bound_side",repmat(uint8([2;1]),nDays*data.meta.nHydro,1));
runtime = struct( ...
    "version","stage-B2C-compact-recursive-runtime-v2.0", ...
    "index_version","stage-B2C-water-index-v1.0", ...
    "scope",struct("days",double(config.days),"hours",double(config.hours), ...
        "milestone_id","B-2C","soc_boundary_mode", ...
        string(config.soc_boundary_mode),"time_scope_type", ...
        string(config.time_scope_type)), ...
    "counts",counts,"physical_map",physical,"water_map",water, ...
    "constraint_map",constraint, ...
    "equality_map",struct("power_balance_rows",balance, ...
        "soc_rows",soc,"terminal_soc_rows",terminal), ...
    "fixed_zero_runtime",struct("count",counts.fixed_zero, ...
        "all_exact_zero",true), ...
    "soc_boundary",struct("no_interday",true, ...
        "first_hour_row_count",repmat(uint8(2),nDays,1), ...
        "terminal_row_count",repmat(uint8(2),nDays,1), ...
        "initial_fraction",0.5,"terminal_fraction",0.5));
end
