function water = evaluate_stage_b2c_recursive_water_template(xi,template)
%EVALUATE_STAGE_B2C_RECURSIVE_WATER_TEMPLATE Evaluate water rows by day.

arguments
    xi (:,1) double
    template (1,1) struct
end
assert(string(template.version)== ...
    "stage-B2C-recursive-block-template-v1.0" && ...
    numel(xi)==template.n_primal, ...
    "stageB2C:recursiveWater:Input", ...
    "The primal vector does not match the direct recursive template.");

fixed = template.water;
power = xi(fixed.columns);
waterValue = sum(fixed.water_a.*power.^2+ ...
    fixed.water_b.*power+fixed.water_c,2);
gradient = fixed.sign.*(2.*fixed.water_a.*power+fixed.water_b);
constraintValue = fixed.sign.*(waterValue-fixed.bound_value);
offset = constraintValue-sum(gradient.*power,2);
dayG = cell(numel(template.day),1);
for d = 1:numel(template.day)
    rows = template.day(d).water_rows-template.n_base_inequalities;
    columns = template.day(d).water_local_columns;
    dayG{d} = sparse(repmat((1:8).',1,24),columns,gradient(rows,:), ...
        8,numel(template.day(d).primal_indices),192);
end
water = struct("constraint_value",constraintValue, ...
    "water_value",waterValue,"bound_value",fixed.bound_value, ...
    "sign",fixed.sign,"offset",offset,"gradient",gradient, ...
    "columns",fixed.columns,"day_G",{dayG},"maximum_identity_error", ...
    max(abs(sum(gradient.*power,2)+offset-constraintValue)), ...
    "counts",struct("rows",template.n_water_inequalities, ...
        "jacobian_nnz",24*template.n_water_inequalities, ...
        "hessian_triplets",24*template.n_water_inequalities));
assert(all(isfinite([constraintValue;offset;gradient(:)])), ...
    "stageB2C:recursiveWater:Finite", ...
    "The direct daily water evaluation produced NaN or Inf.");
end
