function water = evaluate_stage_b2c_water_template(xi,template)
%EVALUATE_STAGE_B2C_WATER_TEMPLATE Update nonlinear water rows in bulk.

arguments
    xi (:,1) double
    template (1,1) struct
end
assert(string(template.version)== ...
    "stage-B2C-linearization-template-v1.0" && ...
    numel(xi)==template.n_primal, ...
    "stageB2C:template:WaterInput", ...
    "The primal vector does not match the B-2C fixed template.");
fixed = template.water;
power = xi(fixed.columns);
waterValue = sum(fixed.water_a.*power.^2+ ...
    fixed.water_b.*power+fixed.water_c,2);
gradient = fixed.sign.*(2.*fixed.water_a.*power+fixed.water_b);
constraintValue = fixed.sign.*(waterValue-fixed.bound_value);
linearTerm = sum(gradient.*power,2);
offset = constraintValue-linearTerm;
identityError = abs(linearTerm+offset-constraintValue);
G = sparse(fixed.row_numbers(:),fixed.columns(:),gradient(:), ...
    template.n_water_inequalities,template.n_primal, ...
    24*template.n_water_inequalities);
rowAudit = fixed.row_audit;
rowAudit.constraint_value = constraintValue;
rowAudit.water_value = waterValue;
rowAudit.bound_value = fixed.bound_value;
rowAudit.sign = fixed.sign;
rowAudit.jacobian_nnz = sum(gradient~=0,2);
rowAudit.hessian_nnz = fixed.hessian_nnz;
rowAudit.hessian_symmetry_relative = ...
    zeros(template.n_water_inequalities,1);
rowAudit.linearization_identity_error = identityError;
water = struct("G",G,"offset",offset, ...
    "constraint_value",constraintValue,"water_value",waterValue, ...
    "bound_value",fixed.bound_value,"sign",fixed.sign, ...
    "identity_error",identityError, ...
    "constraint_hessians",fixed.constraint_hessians, ...
    "hessian_triplets",fixed.hessian_triplets,"row_audit",rowAudit, ...
    "counts",fixed.counts,"maximum_identity_error",max(identityError), ...
    "maximum_hessian_symmetry_relative", ...
        fixed.maximum_hessian_symmetry_relative);
assert(nnz(G)==24*template.n_water_inequalities && ...
    all(isfinite([constraintValue;offset;nonzeros(G)])), ...
    "stageB2C:template:WaterOutput", ...
    "The bulk water update produced an invalid Jacobian or value.");
end
