function state = initialize_stage_b2c_runtime_state(data,runtimePackage,config)
%INITIALIZE_STAGE_B2C_RUNTIME_STATE Build the interior from compact maps.

arguments
    data (1,1) struct
    runtimePackage (1,1) struct
    config (1,1) struct
end
assert(ismember(string(runtimePackage.version),[ ...
    "stage-B2C-recursive-runtime-package-v1.0", ...
    "stage-B2C-recursive-numerical-payload-v1.0"]), ...
    "stageB2C:runtimeState:Package", ...
    "The recursive runtime initializer requires the compact package.");
template = runtimePackage.template;
runtime = runtimePackage.runtime;
map = runtime.physical_map;
parameters = template.capacity_parameters;
q = (parameters.lower+parameters.upper)/2;
xi = zeros(template.n_primal,1);
xi(double(map.global_capacity_positions)) = q;
dailyPositions = double(map.daily_capacity_positions);
dailyValues = repmat(q.',numel(config.days),1);
xi(dailyPositions(:)) = dailyValues(:);

days = double(map.days);
windUpper = data.timeseries.windAvailability(days,:,:).* ...
    reshape(q(1:5),1,1,5);
solarUpper = data.timeseries.solarAvailability(days,:,:).* ...
    reshape(q(6:10),1,1,5);
xi = assign_active(xi,map.wind_positions, ...
    config.initialization.active_wind_solar_fraction_of_upper*windUpper);
xi = assign_active(xi,map.solar_positions, ...
    config.initialization.active_wind_solar_fraction_of_upper*solarUpper);
xi = assign_active(xi,map.hydro_positions, ...
    config.initialization.hydro_thermal_fraction_of_upper*repmat( ...
        reshape(double(data.base.hydro.maxOutputMW),1,1,[]), ...
        numel(days),24,1));
xi = assign_active(xi,map.thermal_positions, ...
    config.initialization.hydro_thermal_fraction_of_upper*repmat( ...
        reshape(double(data.base.thermal.maxOutputMW),1,1,[]), ...
        numel(days),24,1));
xi = assign_active(xi,map.charge_positions, ...
    config.initialization.charge_discharge_fraction_of_power_capacity* ...
        repmat(reshape(q(11:12),1,1,[]),numel(days),24,1));
xi = assign_active(xi,map.discharge_positions, ...
    config.initialization.charge_discharge_fraction_of_power_capacity* ...
        repmat(reshape(q(11:12),1,1,[]),numel(days),24,1));
xi = assign_active(xi,map.soc_positions, ...
    config.initialization.soc_fraction_of_energy_capacity* ...
        repmat(reshape(q(13:14),1,1,[]),numel(days),24,1));
assert(all(isfinite(xi)) && all(xi>0), ...
    "stageB2C:runtimeState:Primal", ...
    "The compact runtime primal initialization is incomplete.");

state = struct("xi",xi, ...
    "y",repmat(config.initialization.equality_multipliers, ...
        template.n_equalities,1), ...
    "l",zeros(0,1), ...
    "z",repmat(config.initialization.inequality_multiplier, ...
        template.n_inequalities,1), ...
    "mu",NaN,"capacity_midpoint",q,"stage_id","stage_B", ...
    "initialization_version","stage-B2C-formal-interior-v1.0", ...
    "newton_direction_number",0,"iteration_index",0, ...
    "state_revision",0,"completed_newton_direction_count",0, ...
    "fixed_zero_values",zeros(runtime.counts.fixed_zero,1), ...
    "fixed_zero_directions",zeros(runtime.counts.fixed_zero,1), ...
    "milestone_id","B-2C","water_slack_rule","max(1,-g_current)", ...
    "water_multiplier_rule","shared_positive_inequality_multiplier", ...
    "nonzero_hessian_gate_state",false,"optimization_state",true);

baseInequality = zeros(template.n_base_inequalities,1);
globalBlock = template.global_block;
baseInequality(globalBlock.inequality_rows) = ...
    globalBlock.G*state.xi(globalBlock.q_indices)+ ...
    globalBlock.inequality_offset;
for d = 1:numel(template.day)
    block = template.day(d);
    baseInequality(block.base_inequality_rows) = ...
        block.base_G*state.xi(block.primal_indices)+ ...
        block.base_inequality_offset;
end
baseSlack = -baseInequality;
assert(all(isfinite(baseSlack)) && all(baseSlack>0), ...
    "stageB2C:runtimeState:BaseSlack", ...
    "The compact runtime base slack is not strictly interior.");
water = rkkt.model.evaluate_stage_b2c_recursive_water_template( ...
    state.xi,template);
waterSlack = max(ones(template.n_water_inequalities,1), ...
    -water.constraint_value);
state.l = [baseSlack;waterSlack];
assert(numel(state.xi)==runtime.counts.variables && ...
    numel(state.y)==runtime.counts.equalities && ...
    numel(state.l)==runtime.counts.inequalities && ...
    numel(state.z)==runtime.counts.inequalities && ...
    all(isfinite([state.xi;state.y;state.l;state.z])) && ...
    all(state.l>0) && all(state.z>0), ...
    "stageB2C:runtimeState:StrictInterior", ...
    "The compact runtime state failed the formal interior contract.");
end

function xi = assign_active(xi,positions,values)
mask = positions>0;
xi(double(positions(mask))) = values(mask);
end
