function view = jacobianView(linearization)
%JACOBIANVIEW Read the Jacobian representations from one linearization.
%   This function performs no model assembly or Jacobian recomputation.

arguments
    linearization (1,1) struct
end

rkkt.contracts.requireFields(linearization, ...
    ["identity";"jacobian";"A";"G"], ...
    "rkkt.model.jacobianView linearization");
rkkt.contracts.requireFields(linearization.jacobian,["A";"G"], ...
    "rkkt.model.jacobianView linearization.jacobian");

view = struct( ...
    "identity",linearization.identity, ...
    "jacobian",linearization.jacobian, ...
    "A",linearization.A, ...
    "G",linearization.G);
end
