function config = load_stage_b2a_configuration(projectRoot,options)
%LOAD_STAGE_B2A_CONFIGURATION Read the frozen B-2A structure-audit scope.

arguments
    projectRoot (1,1) string = default_project_root()
    options.CurrentStageExceptionToken (1,1) string = ""
end

stagePath = fullfile(projectRoot,"config","stage_B.yaml");
solverPath = fullfile(projectRoot,"config","solver.yaml");
currentPath = fullfile(projectRoot,"CURRENT_STAGE.md");
require_file(stagePath,"stageB2A:config:StageConfigMissing");
require_file(solverPath,"stageB2A:config:SolverConfigMissing");
require_file(currentPath,"stageB2A:config:CurrentStageMissing");
stageText = string(fileread(stagePath));
solverText = string(fileread(solverPath));
currentText = string(fileread(currentPath));

config = struct();
textKeys = ["stage_id","status","milestone_id","description", ...
    "run_purpose","time_scope_type","soc_boundary_mode", ...
    "water_bound_order","parallel_mode"];
for key = textKeys
    config.(key) = read_text(stageText,key);
end
config.days = read_number_array(stageText,"days");
config.hours = read_number_array(stageText,"hours");
config.hydro_ids = read_number_array(stageText,"hydro_ids");
numberKeys = ["start_hour","terminal_hour", ...
    "terminal_soc_equality_count_per_day", ...
    "derivative_relative_error_threshold", ...
    "lagrangian_hessian_symmetry_tolerance", ...
    "expected_stage_a_primal_dimension", ...
    "expected_stage_a_equality_dimension", ...
    "expected_stage_a_inequality_dimension", ...
    "expected_stage_a_full_kkt_dimension", ...
    "expected_stage_a_total_hourly_chain_dimension", ...
    "expected_stage_a_fixed_zero_count", ...
    "expected_water_inequality_count","expected_full_kkt_dimension", ...
    "diagnostic_water_upper_multiplier", ...
    "diagnostic_water_lower_multiplier"];
for key = numberKeys
    config.(key) = read_number(stageText,key);
end
config.expected_stage_a_daily_hourly_chain_dimensions = ...
    read_number_array(stageText, ...
    "expected_stage_a_daily_hourly_chain_dimensions");
booleanKeys = ["water_constraints_enabled", ...
    "thermal_second_pass_enabled","annual_scope_enabled", ...
    "full_kkt_enabled","full_kkt_assemble_only", ...
    "full_kkt_solve_enabled","recursive_direction_enabled", ...
    "ipm_enabled"];
for key = booleanKeys
    config.(key) = read_boolean(stageText,key);
end

config.initialization = struct( ...
    "global_capacity",read_text(solverText,"global_capacity"), ...
    "daily_capacity_copy_equals_global",read_boolean( ...
        solverText,"daily_capacity_copy_equals_global"), ...
    "active_wind_solar_fraction_of_upper",read_number( ...
        solverText,"active_wind_solar_fraction_of_upper"), ...
    "hydro_thermal_fraction_of_upper",read_number( ...
        solverText,"hydro_thermal_fraction_of_upper"), ...
    "charge_discharge_fraction_of_power_capacity",read_number( ...
        solverText,"charge_discharge_fraction_of_power_capacity"), ...
    "soc_fraction_of_energy_capacity",read_number( ...
        solverText,"soc_fraction_of_energy_capacity"), ...
    "equality_multipliers",read_number( ...
        solverText,"equality_multipliers"), ...
    "inequality_multiplier",read_number( ...
        solverText,"inequality_multiplier"), ...
    "centering_sigma",read_number(solverText,"centering_sigma"));
config.current_stage = struct( ...
    "stage_id",read_markdown_field(currentText,"stage_id"), ...
    "status",read_markdown_field(currentText,"status"));
config.source_paths = struct("stage",stagePath,"solver",solverPath, ...
    "current_stage",currentPath);
config.stage_a_compatibility = stage_a_compatibility(config);

validate_configuration(config,options.CurrentStageExceptionToken);
end

function value = stage_a_compatibility(config)
value = struct();
value.stage_id = "stage_A4";
value.days = config.days;
value.hours = config.hours;
value.aggregation_day_order = config.days;
value.time_scope_type = config.time_scope_type;
value.start_hour = config.start_hour;
value.terminal_hour = config.terminal_hour;
value.soc_boundary_mode = config.soc_boundary_mode;
value.expected_full_kkt_dimension = ...
    config.expected_stage_a_full_kkt_dimension;
value.expected_daily_hourly_chain_dimensions = ...
    config.expected_stage_a_daily_hourly_chain_dimensions;
value.expected_total_hourly_chain_dimension = ...
    config.expected_stage_a_total_hourly_chain_dimension;
value.expected_fixed_zero_count = config.expected_stage_a_fixed_zero_count;
value.initialization = config.initialization;
end

function validate_configuration(config,exceptionToken)
assert(config.stage_id=="stage_B" && config.status=="READY" && ...
    config.milestone_id=="B-2A", ...
    "stageB2A:config:StageGate", ...
    "Stage B-2A configuration must remain READY with milestone_id B-2A.");
if strlength(exceptionToken)==0
    assert(config.current_stage.stage_id=="stage_B" && ...
        config.current_stage.status=="READY", ...
        "stageB2A:config:StageGate", ...
        "Stage B-2A requires CURRENT_STAGE stage_B / READY.");
else
    assert(ismember(exceptionToken,[ ...
        "B-2C-365-SERIAL-RESUMABLE-AUTHORIZED", ...
        "B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED"]) && ...
        config.current_stage.stage_id=="stage_D1" && ...
        config.current_stage.status=="READY" && ...
        contains(string(fileread(config.source_paths.current_stage)), ...
            exceptionToken), ...
        "stageB2A:config:StageException", ...
        "The requested Stage-B configuration exception is not authorized.");
end
assert(isequal(config.days,14:20) && isequal(config.hours,1:24) && ...
    isequal(config.hydro_ids,1:4) && config.start_hour==1 && ...
    config.terminal_hour==24 && ...
    config.time_scope_type=="formal_7_day_scope" && ...
    config.soc_boundary_mode=="formal_daily_fixed_half_energy" && ...
    config.terminal_soc_equality_count_per_day==2, ...
    "stageB2A:config:Scope", ...
    "B-2A must use formal days 14:20 and complete hours 1:24.");
assert(config.water_constraints_enabled && ...
    config.full_kkt_enabled && config.full_kkt_assemble_only && ...
    ~config.full_kkt_solve_enabled && ...
    ~config.recursive_direction_enabled && ~config.ipm_enabled && ...
    ~config.thermal_second_pass_enabled && ...
    ~config.annual_scope_enabled && config.parallel_mode=="off", ...
    "stageB2A:config:ExecutionBoundary", ...
    "B-2A permits sparse KKT assembly only, with all solvers disabled.");
assert(config.water_bound_order=="upper_then_lower" && ...
    config.expected_water_inequality_count==56 && ...
    config.expected_stage_a_primal_dimension==3722 && ...
    config.expected_stage_a_equality_dimension==618 && ...
    config.expected_stage_a_inequality_dimension==7248 && ...
    config.expected_stage_a_full_kkt_dimension==18836 && ...
    config.expected_full_kkt_dimension==18948 && ...
    isequal(config.expected_stage_a_daily_hourly_chain_dimensions, ...
        [589,590,589,590,590,590,590]) && ...
    config.expected_stage_a_total_hourly_chain_dimension==4128 && ...
    config.expected_stage_a_fixed_zero_count==422, ...
    "stageB2A:config:ControlledDimensions", ...
    "The frozen Stage-A baseline or B-2A water-row count changed.");
assert(config.derivative_relative_error_threshold==1e-7 && ...
    config.lagrangian_hessian_symmetry_tolerance==1e-12 && ...
    config.diagnostic_water_upper_multiplier>0 && ...
    config.diagnostic_water_lower_multiplier>0 && ...
    config.diagnostic_water_upper_multiplier~= ...
        config.diagnostic_water_lower_multiplier, ...
    "stageB2A:config:Diagnostics", ...
    "B-2A diagnostic tolerances or water multipliers are invalid.");
assert(config.initialization.global_capacity=="midpoint" && ...
    config.initialization.daily_capacity_copy_equals_global && ...
    config.initialization.active_wind_solar_fraction_of_upper==0.5 && ...
    config.initialization.hydro_thermal_fraction_of_upper==0.5 && ...
    config.initialization.charge_discharge_fraction_of_power_capacity==0.5 && ...
    config.initialization.soc_fraction_of_energy_capacity==0.5 && ...
    config.initialization.equality_multipliers==0 && ...
    config.initialization.inequality_multiplier==1 && ...
    config.initialization.centering_sigma==0.1, ...
    "stageB2A:config:Initialization", ...
    "B-2A must reuse the frozen deterministic Stage-A point.");
end

function require_file(pathValue,identifier)
if ~isfile(pathValue)
    error(identifier,"Required file is missing: %s",pathValue);
end
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if (startsWith(raw,'"') && endsWith(raw,'"')) || ...
        (startsWith(raw,"'") && endsWith(raw,"'"))
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value)>0,"stageB2A:config:EmptyText", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
value = str2double(read_raw_value(document,key));
assert(isscalar(value)&&isfinite(value),"stageB2A:config:Number", ...
    "Configuration key %s must be a finite scalar.",key);
end

function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[")&&endsWith(raw,"]"), ...
    "stageB2A:config:NumberArray", ...
    "Configuration key %s must use an inline sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
values = str2double(strip(split(body,","))).';
assert(all(isfinite(values)),"stageB2A:config:NumberArray", ...
    "Configuration key %s contains a nonnumeric item.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageB2A:config:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw=="true";
end

function raw = read_raw_value(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
if isempty(tokens)
    error("stageB2A:config:MissingKey", ...
        "Configuration key %s is missing.",key);
elseif numel(tokens)~=1
    error("stageB2A:config:DuplicateKey", ...
        "Configuration key %s must occur exactly once.",key);
end
raw = strip(string(tokens{1}{1}));
end

function value = read_markdown_field(document,key)
pattern = ['(?m)^-[ \t]*`',regexptranslate('escape',char(key)), ...
    '`[ \t]*:[ \t]*`([^`]+)`[ \t\r]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens),"stageB2A:config:CurrentStageField", ...
    "CURRENT_STAGE field %s must occur exactly once.",key);
value = string(tokens{1}{1});
end

function projectRoot = default_project_root()
projectRoot = rkkt.projectRoot();
end
