function config = load_stage_b2b_configuration(projectRoot,options)
%LOAD_STAGE_B2B_CONFIGURATION Read the isolated B-2B direction-test scope.

arguments
    projectRoot (1,1) string = default_project_root()
    options.CurrentStageExceptionToken (1,1) string = ""
end

% Reuse the already-audited Stage-B/solver parsing for the frozen Stage-A
% compatibility fields, then overlay only B-2B execution fields from its
% own config.  The B-2A source config and entry point remain unchanged.
config = rkkt.model.load_stage_b2a_configuration( ...
    projectRoot,CurrentStageExceptionToken=options.CurrentStageExceptionToken);
pathValue = fullfile(projectRoot,"config","stage_B_2B.yaml");
assert(isfile(pathValue),"stageB2B:config:Missing", ...
    "B-2B configuration is missing: %s",pathValue);
document = string(fileread(pathValue));

textKeys = ["stage_id","status","description","milestone_id", ...
    "run_purpose","time_scope_type","soc_boundary_mode", ...
    "full_kkt_role","water_bound_order","water_border_assembly", ...
    "water_multiplier_initialization","parallel_mode"];
for key = textKeys
    config.(key) = read_text(document,key);
end
config.days = read_number_array(document,"days");
config.hours = read_number_array(document,"hours");
config.hydro_ids = read_number_array(document,"hydro_ids");
numberKeys = ["start_hour","terminal_hour", ...
    "terminal_soc_equality_count_per_day", ...
    "direction_relative_error_tolerance", ...
    "recursive_full_kkt_residual_tolerance", ...
    "full_kkt_residual_tolerance","reduced_symmetry_tolerance", ...
    "border_symmetry_tolerance", ...
    "lagrangian_hessian_symmetry_tolerance", ...
    "stationarity_finite_difference_tolerance", ...
    "expected_stage_a_primal_dimension", ...
    "expected_stage_a_equality_dimension", ...
    "expected_stage_a_inequality_dimension", ...
    "expected_stage_a_full_kkt_dimension", ...
    "expected_stage_a_total_hourly_chain_dimension", ...
    "expected_stage_a_fixed_zero_count", ...
    "expected_water_inequality_count", ...
    "expected_water_border_dimension_per_day", ...
    "expected_day_response_dimension","expected_global_core_dimension", ...
    "expected_full_kkt_dimension","recursive_refinement_max_passes"];
for key = numberKeys
    config.(key) = read_number(document,key);
end
config.expected_stage_a_daily_hourly_chain_dimensions = ...
    read_number_array(document,"expected_stage_a_daily_hourly_chain_dimensions");
booleanKeys = ["water_constraints_enabled", ...
    "thermal_second_pass_enabled","annual_scope_enabled", ...
    "full_kkt_enabled","full_kkt_assemble_only", ...
    "full_kkt_solve_enabled","recursive_direction_enabled", ...
    "ipm_enabled","optimization_enabled","state_update_enabled", ...
    "parallel_enabled","stage_c1_enabled"];
for key = booleanKeys
    config.(key) = read_boolean(document,key);
end
config.source_paths.stage = pathValue;
config.stage_a_compatibility = stage_a_compatibility(config);
validate_configuration(config,options.CurrentStageExceptionToken);
end

function value = stage_a_compatibility(config)
value = struct("stage_id","stage_A4","days",config.days, ...
    "hours",config.hours,"aggregation_day_order",config.days, ...
    "time_scope_type",config.time_scope_type, ...
    "start_hour",config.start_hour,"terminal_hour",config.terminal_hour, ...
    "soc_boundary_mode",config.soc_boundary_mode, ...
    "expected_full_kkt_dimension",config.expected_stage_a_full_kkt_dimension, ...
    "expected_daily_hourly_chain_dimensions", ...
        config.expected_stage_a_daily_hourly_chain_dimensions, ...
    "expected_total_hourly_chain_dimension", ...
        config.expected_stage_a_total_hourly_chain_dimension, ...
    "expected_fixed_zero_count",config.expected_stage_a_fixed_zero_count, ...
    "initialization",config.initialization);
end

function validate_configuration(config,exceptionToken)
assert(config.stage_id=="stage_B" && config.status=="READY" && ...
    config.milestone_id=="B-2B", ...
    "stageB2B:config:StageGate", ...
    "B-2B configuration must remain READY with milestone_id B-2B.");
if strlength(exceptionToken)==0
    assert(config.current_stage.stage_id=="stage_B" && ...
        config.current_stage.status=="READY", ...
        "stageB2B:config:StageGate", ...
        "B-2B requires CURRENT_STAGE stage_B / READY.");
else
    assert(ismember(exceptionToken,[ ...
        "B-2C-365-SERIAL-RESUMABLE-AUTHORIZED", ...
        "B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED"]) && ...
        config.current_stage.stage_id=="stage_D1" && ...
        config.current_stage.status=="READY" && ...
        contains(string(fileread(config.source_paths.current_stage)), ...
            exceptionToken), ...
        "stageB2B:config:StageException", ...
        "The requested Stage-B configuration exception is not authorized.");
end
assert(isequal(config.days,14:20) && isequal(config.hours,1:24) && ...
    isequal(config.hydro_ids,1:4) && config.start_hour==1 && ...
    config.terminal_hour==24 && ...
    config.soc_boundary_mode=="formal_daily_fixed_half_energy", ...
    "stageB2B:config:Scope", ...
    "B-2B must use formal days 14:20 and full hours 1:24.");
assert(config.water_constraints_enabled && config.full_kkt_enabled && ...
    ~config.full_kkt_assemble_only && config.full_kkt_solve_enabled && ...
    config.full_kkt_role=="independent_audit_only" && ...
    config.recursive_direction_enabled && ~config.ipm_enabled && ...
    ~config.optimization_enabled && ~config.state_update_enabled && ...
    ~config.parallel_enabled && ~config.stage_c1_enabled && ...
    ~config.thermal_second_pass_enabled && ~config.annual_scope_enabled, ...
    "stageB2B:config:ExecutionBoundary", ...
    "B-2B permits exactly one recursive direction plus independent full-KKT audit.");
assert(config.expected_stage_a_primal_dimension==3722 && ...
    config.expected_stage_a_equality_dimension==618 && ...
    config.expected_stage_a_inequality_dimension==7248 && ...
    config.expected_water_inequality_count==56 && ...
    config.expected_water_border_dimension_per_day==8 && ...
    config.expected_day_response_dimension==14 && ...
    config.expected_global_core_dimension==16 && ...
    config.expected_full_kkt_dimension==18948 && ...
    isequal(config.expected_stage_a_daily_hourly_chain_dimensions, ...
        [589,590,589,590,590,590,590]), ...
    "stageB2B:config:Dimensions","B-2B controlled dimensions changed.");
assert(config.direction_relative_error_tolerance==1e-10 && ...
    config.recursive_full_kkt_residual_tolerance==1e-10 && ...
    config.full_kkt_residual_tolerance==1e-10 && ...
    config.reduced_symmetry_tolerance==1e-12 && ...
    config.border_symmetry_tolerance==1e-12 && ...
    config.recursive_refinement_max_passes==0, ...
    "stageB2B:config:Tolerances", ...
    "B-2B thresholds or the one-direction solver route changed.");
assert(config.water_border_assembly== ...
    "daily_augmented_border_low_rank_update" && ...
    config.water_multiplier_initialization== ...
    "shared_positive_inequality_multiplier", ...
    "stageB2B:config:WaterRoute", ...
    "B-2B must use the approved daily bordered route and dynamic state multipliers.");
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if (startsWith(raw,'"') && endsWith(raw,'"')) || ...
        (startsWith(raw,"'") && endsWith(raw,"'"))
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
end
function value = read_number(document,key)
value = str2double(read_raw_value(document,key));
assert(isscalar(value)&&isfinite(value),"stageB2B:config:Number", ...
    "Configuration key %s must be finite.",key);
end
function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[")&&endsWith(raw,"]"), ...
    "stageB2B:config:Array","Configuration key %s must be inline.",key);
body = extractBetween(raw,2,strlength(raw)-1);
values = str2double(strip(split(body,","))).';
assert(all(isfinite(values)),"stageB2B:config:Array", ...
    "Configuration key %s contains invalid values.",key);
end
function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageB2B:config:Boolean", ...
    "Configuration key %s must be boolean.",key);
value = raw=="true";
end
function raw = read_raw_value(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens),"stageB2B:config:Key", ...
    "Configuration key %s must occur exactly once.",key);
raw = strip(string(tokens{1}{1}));
end
function root = default_project_root()
root = rkkt.projectRoot();
end
