function config = load_stage_b2c_configuration(projectRoot,options)
%LOAD_STAGE_B2C_CONFIGURATION Load the isolated B-2C formal IPM contract.

arguments
    projectRoot (1,1) string = default_project_root()
    options.Profile (1,1) string {mustBeMember(options.Profile, ...
        ["formal_7_day","experimental_30_day", ...
        "supplemental_365_day_serial"])} = "formal_7_day"
    options.CurrentStageExceptionToken (1,1) string = ""
end

supplemental365 = options.Profile=="supplemental_365_day_serial";
exceptionToken = options.CurrentStageExceptionToken;
if supplemental365 && strlength(exceptionToken)==0
    exceptionToken = "B-2C-365-SERIAL-RESUMABLE-AUTHORIZED";
end
config = rkkt.model.load_stage_b2b_configuration( ...
    projectRoot,CurrentStageExceptionToken=exceptionToken);
switch options.Profile
    case "formal_7_day"
        fileName = "stage_B_2C.yaml";
    case "experimental_30_day"
        fileName = "stage_B_2C_30_day_experiment.yaml";
    case "supplemental_365_day_serial"
        fileName = "stage_B_2C_365_day_serial_experiment.yaml";
end
pathValue = fullfile(projectRoot,"config",fileName);
assert(isfile(pathValue),"stageB2C:config:Missing", ...
    "B-2C configuration is missing: %s",pathValue);
document = string(fileread(pathValue));

textKeys = ["stage_id","status","description","milestone_id", ...
    "run_purpose","parent_run_id","time_scope_type", ...
    "soc_boundary_mode","convergence_coordinate", ...
    "objective_scale_mode","objective_scale_source","recursive_route", ...
    "step_strategy","water_bound_order","water_border_assembly", ...
    "local_response_residual_policy","direction_acceptance_policy", ...
    "full_kkt_role","parallel_mode"];
for key = textKeys
    config.(key) = read_text(document,key);
end
config.days = read_number_array(document,"days");
config.hours = read_number_array(document,"hours");
config.hydro_ids = read_number_array(document,"hydro_ids");
numberKeys = ["start_hour","terminal_hour", ...
    "terminal_soc_equality_count_per_day", ...
    "recursive_refinement_max_passes","core_consistency_max_passes", ...
    "equilibration_passes", ...
    "centering_sigma","fraction_to_boundary","max_iterations", ...
    "primal_equality_inf_tolerance", ...
    "primal_inequality_inf_tolerance","dual_scaled_inf_tolerance", ...
    "mean_lz_scaled_tolerance","water_physical_violation_tolerance", ...
    "stage_a_physical_violation_tolerance", ...
    "direction_relative_error_tolerance", ...
    "local_linear_solve_residual_tolerance", ...
    "recursive_full_kkt_residual_tolerance", ...
    "full_kkt_residual_tolerance","reduced_symmetry_tolerance", ...
    "border_symmetry_tolerance", ...
    "lagrangian_hessian_symmetry_tolerance", ...
    "stationarity_finite_difference_tolerance", ...
    "nonzero_gate_water_upper_multiplier", ...
    "nonzero_gate_water_lower_multiplier", ...
    "expected_nonzero_water_hessian_nnz", ...
    "expected_stage_a_primal_dimension", ...
    "expected_stage_a_equality_dimension", ...
    "expected_stage_a_inequality_dimension", ...
    "expected_stage_a_full_kkt_dimension", ...
    "expected_stage_a_total_hourly_chain_dimension", ...
    "expected_stage_a_fixed_zero_count","expected_water_inequality_count", ...
    "expected_water_border_dimension_per_day", ...
    "expected_day_response_dimension","expected_global_core_dimension", ...
    "expected_full_kkt_dimension","expected_final_water_audit_rows", ...
    "expected_rhs_per_day"];
for key = numberKeys
    config.(key) = read_number(document,key);
end
config.expected_stage_a_daily_hourly_chain_dimensions = ...
    read_number_array(document,"expected_stage_a_daily_hourly_chain_dimensions");
config.expected_daily_joint_dimensions = ...
    read_number_array(document,"expected_daily_joint_dimensions");
booleanKeys = ["recursive_congruence_scaling_enabled", ...
    "compensated_core_accumulation", ...
    "water_constraints_enabled","full_kkt_enabled", ...
    "full_kkt_solve_enabled","full_kkt_audit_enabled", ...
    "recursive_direction_enabled", ...
    "ipm_enabled","optimization_enabled","state_update_enabled", ...
    "checkpoint_after_each_accepted_update","common_step_enabled", ...
    "dynamic_sigma_enabled","predictor_corrector_enabled", ...
    "line_search_enabled","regularization_enabled", ...
    "automatic_symmetrization_enabled", ...
    "full_kkt_direction_fallback_enabled","parallel_enabled", ...
    "annual_scope_enabled","thermal_second_pass_enabled", ...
    "stage_c1_implemented"];
for key = booleanKeys
    config.(key) = read_boolean(document,key);
end
config.source_paths.stage_b2c = pathValue;
config.stage_a_compatibility = synchronize_stage_a_compatibility(config);
validate_configuration(config,options.Profile,exceptionToken);
end

function validate_configuration(config,profile,exceptionToken)
assert(config.stage_id=="stage_B" && config.status=="READY" && ...
    config.milestone_id=="B-2C", ...
    "stageB2C:config:StageGate", ...
    "B-2C configuration must remain READY with milestone_id B-2C.");
formalScope = profile=="formal_7_day";
expectedDays = 14:20;
expectedScope = "formal_7_day_scope";
if profile=="experimental_30_day"
    expectedDays = 1:30;
    expectedScope = "experimental_30_day_scope";
elseif profile=="supplemental_365_day_serial"
    expectedDays = 1:365;
    expectedScope = "supplemental_365_day_serial_scope";
    assert(config.current_stage.stage_id=="stage_D1" && ...
        config.current_stage.status=="READY", ...
        "stageB2C:day365:StageException", ...
        "The authorized 365-day supplement requires CURRENT_STAGE stage_D1 / READY.");
    exceptionPath = config.source_paths.current_stage;
    currentText = string(fileread(exceptionPath));
    assert(contains(currentText,exceptionToken), ...
        "stageB2C:day365:StageException", ...
        "The 365-day supplemental execution exception is not authorized.");
else
    if strlength(exceptionToken)==0
        assert(config.current_stage.stage_id=="stage_B" && ...
            config.current_stage.status=="READY", ...
            "stageB2C:config:StageGate", ...
            "B-2C requires CURRENT_STAGE stage_B / READY.");
    else
        assert(exceptionToken== ...
            "B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED" && ...
            config.current_stage.stage_id=="stage_D1" && ...
            config.current_stage.status=="READY" && ...
            contains(string(fileread(config.source_paths.current_stage)), ...
                exceptionToken), ...
            "stageB2C:config:StageException", ...
            "The unified Stage-B runner exception is not authorized.");
    end
end
assert(isequal(config.days,expectedDays) && ...
    config.time_scope_type==expectedScope && isequal(config.hours,1:24) && ...
    isequal(config.hydro_ids,1:4) && config.start_hour==1 && ...
    config.terminal_hour==24 && ...
    config.soc_boundary_mode=="formal_daily_fixed_half_energy", ...
    "stageB2C:config:Scope", ...
    "B-2C profile %s has an invalid day/hour scope.",profile);
assert(config.convergence_coordinate=="positive_scalar_unitized_kkt" && ...
    config.objective_scale_mode=="positive_scalar_unitization" && ...
    config.objective_scale_source=="max_abs_global_capacity_gradient" && ...
    config.recursive_route== ...
        "all_inequality_daily_joint_final_kkt_residual_gate" && ...
    config.recursive_refinement_max_passes==3*double(~formalScope) && ...
    config.core_consistency_max_passes==10 && ...
    config.compensated_core_accumulation && ...
    config.recursive_congruence_scaling_enabled && ...
    config.equilibration_passes==0 && ...
    config.local_response_residual_policy=="diagnostic_nonblocking" && ...
    config.direction_acceptance_policy== ...
        "final_reconstructed_kkt_residual" && ...
    config.step_strategy=="independent" && ...
    config.centering_sigma==0.1 && config.fraction_to_boundary==0.9995, ...
    "stageB2C:config:Algorithm", ...
    "B-2C daily-joint route, scaling, sigma, tau, or step policy changed.");
assert(config.max_iterations==100 && ...
    config.primal_equality_inf_tolerance==1e-6 && ...
    config.primal_inequality_inf_tolerance==1e-6 && ...
    config.dual_scaled_inf_tolerance==1e-6 && ...
    config.mean_lz_scaled_tolerance==1e-6 && ...
    config.water_physical_violation_tolerance==1e-8 && ...
    config.direction_relative_error_tolerance==1e-10 && ...
    config.local_linear_solve_residual_tolerance==1e-10 && ...
    config.recursive_full_kkt_residual_tolerance==1e-8 && ...
    config.full_kkt_residual_tolerance==1e-10 && ...
    config.reduced_symmetry_tolerance==1e-8 && ...
    config.border_symmetry_tolerance==1e-8 && ...
    config.lagrangian_hessian_symmetry_tolerance==1e-8, ...
    "stageB2C:config:Tolerances", ...
    "B-2C convergence, direction, physical, or symmetry thresholds changed.");
assert(config.water_constraints_enabled && config.recursive_direction_enabled && ...
    config.ipm_enabled && config.optimization_enabled && ...
    config.state_update_enabled && config.checkpoint_after_each_accepted_update && ...
    ~config.common_step_enabled && ~config.dynamic_sigma_enabled && ...
    ~config.predictor_corrector_enabled && ~config.line_search_enabled && ...
    ~config.regularization_enabled && ...
    ~config.automatic_symmetrization_enabled && ...
    ~config.full_kkt_direction_fallback_enabled && ...
    ~config.parallel_enabled && ~config.annual_scope_enabled && ...
    ~config.thermal_second_pass_enabled && ~config.stage_c1_implemented, ...
    "stageB2C:config:ExecutionBoundary", ...
    "A forbidden B-2C algorithm, stage, or execution factor is enabled.");
if formalScope
    assert(config.full_kkt_enabled && config.full_kkt_solve_enabled && ...
        config.full_kkt_audit_enabled && config.full_kkt_role=="audit_only", ...
        "stageB2C:config:FormalAudit", ...
        "The formal seven-day profile must execute one full-KKT audit per iteration.");
    assert(config.expected_stage_a_primal_dimension==3722 && ...
    config.expected_stage_a_equality_dimension==618 && ...
    config.expected_stage_a_inequality_dimension==7248 && ...
    config.expected_water_inequality_count==56 && ...
    config.expected_water_border_dimension_per_day==0 && ...
    config.expected_day_response_dimension==14 && ...
    config.expected_global_core_dimension==16 && ...
    config.expected_full_kkt_dimension==18948 && ...
    config.expected_nonzero_water_hessian_nnz==672 && ...
    config.expected_final_water_audit_rows==28 && ...
    config.expected_rhs_per_day==15 && ...
    isequal(config.expected_daily_joint_dimensions, ...
        [617,618,617,618,618,618,618]) && ...
    isequal(config.expected_stage_a_daily_hourly_chain_dimensions, ...
        [589,590,589,590,590,590,590]), ...
        "stageB2C:config:Dimensions","B-2C controlled dimensions changed.");
elseif profile=="experimental_30_day"
    assert(~config.full_kkt_enabled && ~config.full_kkt_solve_enabled && ...
        ~config.full_kkt_audit_enabled && ...
        config.full_kkt_role=="not_executed_30_day_experiment", ...
        "stageB2C:config:ExperimentAudit", ...
        "The 30-day experiment must not assemble or solve the full KKT audit route.");
    assert(config.expected_stage_a_primal_dimension==15910 && ...
        config.expected_stage_a_equality_dimension==2642 && ...
        config.expected_stage_a_inequality_dimension==30980 && ...
        config.expected_stage_a_full_kkt_dimension==80512 && ...
        config.expected_stage_a_fixed_zero_count==1804 && ...
        config.expected_water_inequality_count==240 && ...
        config.expected_final_water_audit_rows==120 && ...
        config.expected_nonzero_water_hessian_nnz==2880 && ...
        config.expected_full_kkt_dimension==80992 && ...
        numel(config.expected_daily_joint_dimensions)==30 && ...
        numel(config.expected_stage_a_daily_hourly_chain_dimensions)==30 && ...
        config.expected_stage_a_total_hourly_chain_dimension==17696, ...
        "stageB2C:config:ExperimentDimensions", ...
        "The controlled 30-day experimental dimensions changed.");
else
    assert(~config.full_kkt_enabled && ~config.full_kkt_solve_enabled && ...
        ~config.full_kkt_audit_enabled && ...
        config.full_kkt_role=="not_executed_365_day_serial_experiment", ...
        "stageB2C:day365:ExperimentAudit", ...
        "The 365-day serial experiment must not assemble or solve full KKT.");
    assert(config.expected_stage_a_primal_dimension==193431 && ...
        config.expected_stage_a_equality_dimension==32122 && ...
        config.expected_stage_a_inequality_dimension==376642 && ...
        config.expected_stage_a_full_kkt_dimension==978837 && ...
        config.expected_stage_a_fixed_zero_count==21933 && ...
        config.expected_water_inequality_count==2920 && ...
        config.expected_final_water_audit_rows==1460 && ...
        config.expected_nonzero_water_hessian_nnz==35040 && ...
        config.expected_full_kkt_dimension==984677 && ...
        numel(config.expected_daily_joint_dimensions)==365 && ...
        numel(config.expected_stage_a_daily_hourly_chain_dimensions)==365 && ...
        config.expected_stage_a_total_hourly_chain_dimension==215317, ...
        "stageB2C:day365:ExperimentDimensions", ...
        "The controlled 365-day experimental dimensions changed.");
end
assert(config.nonzero_gate_water_upper_multiplier==1.25 && ...
    config.nonzero_gate_water_lower_multiplier==0.75 && ...
    config.water_border_assembly== ...
        "fully_eliminated_no_explicit_water_border", ...
    "stageB2C:config:WaterGate", ...
    "The approved nonzero-Hessian diagnostic or daily-joint route changed.");
end

function value = synchronize_stage_a_compatibility(config)
value = config.stage_a_compatibility;
value.days = config.days;
value.hours = config.hours;
value.aggregation_day_order = config.days;
value.start_hour = config.start_hour;
value.terminal_hour = config.terminal_hour;
value.soc_boundary_mode = config.soc_boundary_mode;
value.time_scope_type = config.time_scope_type;
value.run_purpose = config.run_purpose+"_stage_a_view";
value.expected_full_kkt_dimension = ...
    config.expected_stage_a_full_kkt_dimension;
value.expected_daily_hourly_chain_dimensions = ...
    config.expected_stage_a_daily_hourly_chain_dimensions;
value.expected_total_hourly_chain_dimension = ...
    config.expected_stage_a_total_hourly_chain_dimension;
value.expected_fixed_zero_count = config.expected_stage_a_fixed_zero_count;
end

function value = read_text(document,key)
raw = read_raw(document,key);
if (startsWith(raw,'"') && endsWith(raw,'"')) || ...
        (startsWith(raw,"'") && endsWith(raw,"'"))
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value)>0,"stageB2C:config:Text", ...
    "Configuration key %s must not be empty.",key);
end
function value = read_number(document,key)
value = str2double(read_raw(document,key));
assert(isscalar(value)&&isfinite(value),"stageB2C:config:Number", ...
    "Configuration key %s must be finite.",key);
end
function values = read_number_array(document,key)
raw = read_raw(document,key);
assert(startsWith(raw,"[")&&endsWith(raw,"]"), ...
    "stageB2C:config:Array","Configuration key %s must be inline.",key);
body = extractBetween(raw,2,strlength(raw)-1);
values = str2double(strip(split(body,","))).';
assert(all(isfinite(values)),"stageB2C:config:Array", ...
    "Configuration key %s contains invalid values.",key);
end
function value = read_boolean(document,key)
raw = lower(read_raw(document,key));
assert(ismember(raw,["true","false"]),"stageB2C:config:Boolean", ...
    "Configuration key %s must be boolean.",key);
value = raw=="true";
end
function raw = read_raw(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens),"stageB2C:config:Key", ...
    "Configuration key %s must occur exactly once.",key);
raw = strip(string(tokens{1}{1}));
end
function root = default_project_root()
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
