function config = load_stage_a1_configuration(projectRoot)
%LOAD_STAGE_A1_CONFIGURATION Read and validate the explicit A1 test fixture.
%
% The configured three-hour window is an algorithmic fixture.  This loader
% deliberately requires its start, terminal hour, and SOC boundary mode;
% none of those values is inferred from the 24-hour physical-day horizon.

arguments
    projectRoot (1,1) string = default_project_root()
end

stagePath = fullfile(projectRoot,"config","stage_A1.yaml");
solverPath = fullfile(projectRoot,"config","solver.yaml");
if ~isfile(stagePath)
    error("stageA1:config:StageConfigMissing", ...
        "Stage A1 configuration is missing: %s",stagePath);
end
if ~isfile(solverPath)
    error("stageA1:config:SolverConfigMissing", ...
        "Solver configuration is missing: %s",solverPath);
end

stageText = string(fileread(stagePath));
solverText = string(fileread(solverPath));

config = struct();
config.stage_id = read_text(stageText,"stage_id");
config.status = read_text(stageText,"status");
config.days = read_number_array(stageText,"days");
config.hours = read_number_array(stageText,"hours");
config.window_type = read_text(stageText,"window_type");
config.start_hour = read_number(stageText,"start_hour");
config.terminal_hour = read_number(stageText,"terminal_hour");
config.soc_boundary_mode = read_text(stageText,"soc_boundary_mode");
config.terminal_soc_equality_count = read_number( ...
    stageText,"terminal_soc_equality_count");
config.window_purpose = read_text(stageText,"window_purpose");
config.expected_full_kkt_dimension = read_number( ...
    stageText,"expected_full_kkt_dimension");
config.expected_hourly_kkt_block_dimensions = read_number_array( ...
    stageText,"expected_hourly_kkt_block_dimensions");
config.expected_global_core_dimension = read_number( ...
    stageText,"expected_global_core_dimension");
config.direction_relative_tolerance = read_number( ...
    stageText,"direction_relative_tolerance");
config.recursive_full_kkt_residual_tolerance = read_number( ...
    stageText,"recursive_full_kkt_residual_tolerance");
config.newton_direction_count = read_number(stageText,"newton_direction_count");
config.run_full_ipm = read_boolean(stageText,"run_full_ipm");
config.physical_dispatch_interpretation = read_boolean( ...
    stageText,"physical_dispatch_interpretation");
config.artifact_mode = read_text(stageText,"artifact_mode");
config.parallel_mode = read_text(stageText,"parallel_mode");
config.full_kkt_direct_residual_preferred = read_number( ...
    stageText,"full_kkt_direct_residual_preferred");
config.full_kkt_direct_residual_maximum = read_number( ...
    stageText,"full_kkt_direct_residual_maximum");
config.symmetry_relative_tolerance = read_number( ...
    stageText,"symmetry_relative_tolerance");

config.initialization = struct( ...
    "global_capacity",read_text(solverText,"global_capacity"), ...
    "daily_capacity_copy_equals_global",read_boolean( ...
        solverText,"daily_capacity_copy_equals_global"), ...
    "active_wind_solar_fraction_of_upper",read_number( ...
        solverText,"active_wind_solar_fraction_of_upper"), ...
    "hydro_thermal_fraction_of_upper",read_number( ...
        solverText,"hydro_thermal_fraction_of_upper"), ...
    "charge_discharge_fraction_of_power_capacity",read_number( ...
        solverText,"charge_discharge_fraction_of_power_capacity"), ...
    "soc_fraction_of_energy_capacity",read_number( ...
        solverText,"soc_fraction_of_energy_capacity"), ...
    "equality_multipliers",read_number(solverText,"equality_multipliers"), ...
    "inequality_multiplier",read_number(solverText,"inequality_multiplier"), ...
    "centering_sigma",read_number(solverText,"centering_sigma"));
% Archived A1 acceptance remains governed by stage_A1.yaml.
config.tolerances = struct( ...
    "direction_relative_2norm",config.direction_relative_tolerance, ...
    "recursive_full_kkt_relative_residual", ...
        config.recursive_full_kkt_residual_tolerance, ...
    "direct_preferred",config.full_kkt_direct_residual_preferred, ...
    "direct_maximum",config.full_kkt_direct_residual_maximum, ...
    "symmetry_relative",config.symmetry_relative_tolerance);
config.linear_algebra = struct( ...
    "local_factorization",read_text(solverText,"local_factorization"), ...
    "global_core_factorization",read_text( ...
        solverText,"global_core_factorization"), ...
    "multiple_rhs",read_boolean(solverText,"multiple_rhs"), ...
    "explicit_inverse",read_boolean(solverText,"explicit_inverse"), ...
    "pseudoinverse",read_boolean(solverText,"pseudoinverse"), ...
    "least_norm_fallback",read_boolean(solverText,"least_norm_fallback"), ...
    "recursive_fallback_to_full_kkt",read_boolean( ...
        solverText,"recursive_fallback_to_full_kkt"), ...
    "automatic_regularization",read_boolean( ...
        solverText,"automatic_regularization"), ...
    "automatic_symmetrization",read_boolean( ...
        solverText,"automatic_symmetrization"));
config.source_paths = struct("stage",stagePath,"solver",solverPath);

validate_configuration(config);
end

function validate_configuration(config)
assert(config.stage_id == "stage_A1","stageA1:config:StageId", ...
    "stage_id must be stage_A1.");
assert(ismember(config.status,["READY","PASS"]), ...
    "stageA1:config:StageStatus", ...
    "Stage A1 configuration must be READY or archived PASS.");
assert(isequal(config.days,1),"stageA1:config:Days", ...
    "Stage A1 must use only day 1.");
assert(config.window_type == "synthetic_closed_test_window", ...
    "stageA1:config:WindowType", ...
    "window_type must be synthetic_closed_test_window.");
assert(config.soc_boundary_mode == "fixed_half_energy", ...
    "stageA1:config:SocBoundaryMode", ...
    "soc_boundary_mode must be fixed_half_energy.");
assert(isequal(config.hours,config.start_hour:config.terminal_hour), ...
    "stageA1:config:Hours", ...
    "hours must be the explicit ordered interval start_hour:terminal_hour.");
assert(config.start_hour == 8 && config.terminal_hour == 10, ...
    "stageA1:config:Window", ...
    "The frozen A1 fixture is day 1, hours 8 through 10.");
assert(config.terminal_soc_equality_count == 2, ...
    "stageA1:config:TerminalSocCount", ...
    "The A1 fixture requires exactly two terminal SOC equalities.");
assert(config.window_purpose == "algorithmic_direction_equivalence_only", ...
    "stageA1:config:WindowPurpose", ...
    "The A1 window may only be used for direction equivalence.");
assert(config.expected_full_kkt_dimension == 471, ...
    "stageA1:config:FullDimension", ...
    "The frozen A1 complete KKT dimension is 471.");
assert(isequal(config.expected_hourly_kkt_block_dimensions,[27 27 29]), ...
    "stageA1:config:BlockDimensions", ...
    "The frozen A1 hourly block dimensions are 27, 27, and 29.");
assert(config.expected_global_core_dimension == 16, ...
    "stageA1:config:CoreDimension", ...
    "The Stage A global core must be 16 dimensional.");
assert(config.newton_direction_count == 1 && ~config.run_full_ipm, ...
    "stageA1:config:ExecutionScope", ...
    "Stage A1 permits one Newton direction and forbids a full IPM run.");
assert(~config.physical_dispatch_interpretation && ...
    config.parallel_mode == "off", ...
    "stageA1:config:ForbiddenScope", ...
    "Stage A1 forbids dispatch interpretation and parallel execution.");
assert(config.artifact_mode == "unique_run_directory", ...
    "stageA1:config:ArtifactMode", ...
    "Stage A1 artifacts must use a unique run directory.");
assert(config.tolerances.direction_relative_2norm == 1e-10 && ...
    config.tolerances.recursive_full_kkt_relative_residual == 1e-10, ...
    "stageA1:config:EquivalenceTolerance", ...
    "The two equivalence tolerances must remain 1e-10.");
assert(config.direction_relative_tolerance == ...
    config.tolerances.direction_relative_2norm && ...
    config.recursive_full_kkt_residual_tolerance == ...
    config.tolerances.recursive_full_kkt_relative_residual, ...
    "stageA1:config:StageSolverToleranceMismatch", ...
    "Stage A1 and solver equivalence tolerances must agree exactly.");
assert(config.tolerances.direct_preferred == 1e-12 && ...
    config.tolerances.direct_maximum == 1e-10, ...
    "stageA1:config:DirectResidualTolerance", ...
    "Direct KKT residual targets must be 1e-12 preferred and 1e-10 maximum.");
assert(config.initialization.global_capacity == "midpoint" && ...
    config.initialization.daily_capacity_copy_equals_global, ...
    "stageA1:config:Initialization", ...
    "Stage A1 requires midpoint capacities and identical daily copies.");
assert(config.initialization.centering_sigma > 0 && ...
    config.initialization.centering_sigma < 1, ...
    "stageA1:config:CenteringSigma", ...
    "centering_sigma must lie strictly between zero and one.");
assert(config.linear_algebra.local_factorization == "ldl_vector" && ...
    config.linear_algebra.global_core_factorization == "ldl_vector" && ...
    config.linear_algebra.multiple_rhs, ...
    "stageA1:config:LinearAlgebra", ...
    "Stage A1 requires vector-permuted LDL with multiple right hand sides.");
assert(~config.linear_algebra.explicit_inverse && ...
    ~config.linear_algebra.pseudoinverse && ...
    ~config.linear_algebra.least_norm_fallback && ...
    ~config.linear_algebra.recursive_fallback_to_full_kkt && ...
    ~config.linear_algebra.automatic_regularization && ...
    ~config.linear_algebra.automatic_symmetrization, ...
    "stageA1:config:ForbiddenLinearAlgebra", ...
    "Forbidden fallback, regularization, or symmetrization is enabled.");
end

function value = read_text(document,key)
raw = read_raw_value(document,key);
if startsWith(raw,'"') && endsWith(raw,'"')
    raw = extractBetween(raw,2,strlength(raw)-1);
elseif startsWith(raw,"'") && endsWith(raw,"'")
    raw = extractBetween(raw,2,strlength(raw)-1);
end
value = string(raw);
assert(strlength(value) > 0,"stageA1:config:EmptyText", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_number(document,key)
raw = read_raw_value(document,key);
value = str2double(raw);
assert(isscalar(value) && isfinite(value),"stageA1:config:Number", ...
    "Configuration key %s must be a finite scalar number.",key);
end

function values = read_number_array(document,key)
raw = read_raw_value(document,key);
assert(startsWith(raw,"[") && endsWith(raw,"]"), ...
    "stageA1:config:NumberArray", ...
    "Configuration key %s must use an explicit YAML flow sequence.",key);
body = extractBetween(raw,2,strlength(raw)-1);
if strlength(strip(body)) == 0
    values = zeros(1,0);
    return;
end
parts = split(body,",");
values = str2double(strip(parts)).';
assert(all(isfinite(values)),"stageA1:config:NumberArray", ...
    "Configuration key %s contains a nonnumeric value.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw_value(document,key));
assert(ismember(raw,["true","false"]),"stageA1:config:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw == "true";
end

function raw = read_raw_value(document,key)
escapedKey = regexptranslate('escape',char(key));
pattern = ['(?m)^[ \t]*',escapedKey,'[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
if isempty(tokens)
    error("stageA1:config:MissingKey", ...
        "Configuration key %s is missing.",key);
end
if numel(tokens) ~= 1
    error("stageA1:config:DuplicateKey", ...
        "Configuration key %s is not unique.",key);
end
raw = strip(string(tokens{1}{1}));
end

function projectRoot = default_project_root()
projectRoot = rkkt.projectRoot();
end
