function physical = recover_stage_b2c_runtime_physical_arrays( ...
        xi,deltaXi,runtimePackage,data)
%RECOVER_STAGE_B2C_RUNTIME_PHYSICAL_ARRAYS Restore via compact positions.

arguments
    xi (:,1) double
    deltaXi (:,1) double
    runtimePackage (1,1) struct
    data (1,1) struct
end
runtime = runtimePackage.runtime;
map = runtime.physical_map;
assert(numel(xi)==runtime.counts.variables && ...
    numel(deltaXi)==runtime.counts.variables, ...
    "stageB2C:runtimeRecovery:Dimension", ...
    "The compact state or direction has an invalid dimension.");
nDays = numel(map.days); nHours = numel(map.hours);
physical = struct("days",double(map.days),"hours",double(map.hours), ...
    "value",allocate_arrays(nDays,nHours,data), ...
    "direction",allocate_arrays(nDays,nHours,data));
physical.value.global_capacity = xi(double(map.global_capacity_positions));
physical.direction.global_capacity = ...
    deltaXi(double(map.global_capacity_positions));
daily = double(map.daily_capacity_positions);
physical.value.daily_capacity = reshape(xi(daily(:)),size(daily));
physical.direction.daily_capacity = ...
    reshape(deltaXi(daily(:)),size(daily));
fields = ["wind","solar","hydro","thermal","charge","discharge","soc"];
positionFields = fields+"_positions";
for k = 1:numel(fields)
    positions = map.(positionFields(k));
    mask = positions>0;
    values = physical.value.(fields(k));
    directions = physical.direction.(fields(k));
    values(mask) = xi(double(positions(mask)));
    directions(mask) = deltaXi(double(positions(mask)));
    physical.value.(fields(k)) = values;
    physical.direction.(fields(k)) = directions;
end
physical.fixed_zero_audit = struct( ...
    "count",runtime.counts.fixed_zero, ...
    "maximum_absolute_value",0,"maximum_absolute_direction",0, ...
    "values_exact_zero",true,"directions_exact_zero",true, ...
    "removed_bound_direction_status","NOT_APPLICABLE_BOTH_BOUNDS");
end

function arrays = allocate_arrays(nDays,nHours,data)
arrays = struct( ...
    "wind",zeros(nDays,nHours,data.meta.nWind), ...
    "solar",zeros(nDays,nHours,data.meta.nSolar), ...
    "hydro",zeros(nDays,nHours,data.meta.nHydro), ...
    "thermal",zeros(nDays,nHours,data.meta.nThermal), ...
    "charge",zeros(nDays,nHours,data.meta.nStorage), ...
    "discharge",zeros(nDays,nHours,data.meta.nStorage), ...
    "soc",zeros(nDays,nHours,data.meta.nStorage));
end
