function view = residualView(linearization)
%RESIDUALVIEW Read residual components from one existing linearization.
%   This function performs no model assembly.

arguments
    linearization (1,1) struct
end

required = [ ...
    "identity"
    "r_dual"
    "r_eq"
    "r_ineq"
    "r_comp"
    "l"
    "z"
    "mu"];
rkkt.contracts.requireFields(linearization,required, ...
    "rkkt.model.residualView linearization");

norms = struct( ...
    "r_dual_2",norm(linearization.r_dual,2), ...
    "r_dual_inf",norm(linearization.r_dual,inf), ...
    "r_eq_2",norm(linearization.r_eq,2), ...
    "r_eq_inf",norm(linearization.r_eq,inf), ...
    "r_ineq_2",norm(linearization.r_ineq,2), ...
    "r_ineq_inf",norm(linearization.r_ineq,inf), ...
    "r_comp_2",norm(linearization.r_comp,2), ...
    "r_comp_inf",norm(linearization.r_comp,inf), ...
    "l_2",norm(linearization.l,2), ...
    "l_inf",norm(linearization.l,inf), ...
    "z_2",norm(linearization.z,2), ...
    "z_inf",norm(linearization.z,inf), ...
    "mu_absolute",abs(linearization.mu));

view = struct( ...
    "identity",linearization.identity, ...
    "r_dual",linearization.r_dual, ...
    "r_eq",linearization.r_eq, ...
    "r_ineq",linearization.r_ineq, ...
    "r_comp",linearization.r_comp, ...
    "l",linearization.l, ...
    "z",linearization.z, ...
    "mu",linearization.mu, ...
    "norms",norms);
end
