function lin = update_stage_b2c_recursive_block_linearization( ...
        state,template,options)
%UPDATE_STAGE_B2C_RECURSIVE_BLOCK_LINEARIZATION Refresh daily block numerics.

arguments
    state (1,1) struct
    template (1,1) struct
    options.PrecomputedWater (1,1) struct = struct()
    options.ChainId (1,1) string = "B-2C-FORMAL-IPM"
end
assert(string(template.version)== ...
    "stage-B2C-recursive-block-template-v1.0" && ...
    string(state.milestone_id)=="B-2C" && ...
    numel(state.xi)==template.n_primal && ...
    numel(state.y)==template.n_equalities && ...
    numel(state.l)==template.n_inequalities && ...
    numel(state.z)==template.n_inequalities && ...
    all(state.l>0) && all(state.z>0), ...
    "stageB2C:recursiveLinearization:Input", ...
    "The positive B-2C state does not match the direct block template.");
if isempty(fieldnames(options.PrecomputedWater))
    water = rkkt.model.evaluate_stage_b2c_recursive_water_template( ...
        state.xi,template);
else
    water = options.PrecomputedWater;
end

nx = template.n_primal;
neq = template.n_equalities;
nineq = template.n_inequalities;
nBase = template.n_base_inequalities;
q = template.maps.q_global;
yDuration = template.maps.y_duration;
rEq = zeros(neq,1);
ineqValue = zeros(nineq,1);
ineqOffset = zeros(nineq,1);
rDual = template.objective_scaled_gradient;

globalBlock = template.global_block;
rEq(yDuration) = globalBlock.A*state.xi(q);
ineqValue(globalBlock.inequality_rows) = ...
    globalBlock.G*state.xi(q)+globalBlock.inequality_offset;
ineqOffset(globalBlock.inequality_rows) = globalBlock.inequality_offset;
rDual(q) = rDual(q)+globalBlock.A.'*state.y(yDuration)+ ...
    globalBlock.G.'*state.z(globalBlock.inequality_rows);

dynamicDays = cell(numel(template.day),1);
for d = 1:numel(template.day)
    fixed = template.day(d);
    p = fixed.primal_indices;
    e = fixed.equality_indices;
    b = fixed.base_inequality_rows;
    w = fixed.water_rows;
    localXi = state.xi(p);
    rEq(e) = fixed.A_local*localXi+ ...
        fixed.A_global*state.xi(q)+fixed.equality_offset;
    ineqValue(b) = fixed.base_G*localXi+fixed.base_inequality_offset;
    ineqOffset(b) = fixed.base_inequality_offset;
    waterPosition = w-nBase;
    ineqValue(w) = water.constraint_value(waterPosition);
    ineqOffset(w) = water.offset(waterPosition);
    waterG = water.day_G{d};
    rDual(p) = rDual(p)+fixed.A_local.'*state.y(e)+ ...
        fixed.base_G.'*state.z(b)+waterG.'*state.z(w);
    rDual(q) = rDual(q)+fixed.A_global.'*state.y(e);

    hessianValues = repmat(state.z(w).* ...
        template.water.hessian_coefficient(waterPosition),1,24);
    localH = sparse(fixed.water_local_columns(:), ...
        fixed.water_local_columns(:),hessianValues(:), ...
        numel(p),numel(p));
    dynamicDays{d} = struct("day_id",fixed.day_id, ...
        "primal_indices",p,"equality_indices",e, ...
        "base_inequality_rows",b,"water_rows",w, ...
        "A_local",fixed.A_local,"A_global",fixed.A_global, ...
        "G_base",fixed.base_G,"G_water",waterG,"H",localH, ...
        "equality_offset",fixed.equality_offset, ...
        "base_inequality_offset",fixed.base_inequality_offset, ...
        "water_inequality_offset",water.offset(waterPosition));
end

l = state.l(:); z = state.z(:);
gap = mean(l.*z);
mu = template.config.initialization.centering_sigma*gap;
rIneq = ineqValue+l;
rComp = l.*z-mu;
assert(all(isfinite([rEq;rIneq;rDual;rComp])) && mu>0, ...
    "stageB2C:recursiveLinearization:Finite", ...
    "The direct block residual update produced NaN or Inf.");

contract = make_contract(template,state,rDual,rEq,rIneq,rComp);
[partition,reduced] = build_partition( ...
    template,vertcat(dynamicDays{:}),contract);

stateWithMu = state;
stateWithMu.mu = mu;
stateFingerprint = ...
    rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(stateWithMu);
baseIdentity = "stage-B2C-recursive-block-linearization-v1.0|"+ ...
    strjoin(template.input_hashes,"|")+"|days"+ ...
    string(template.days(1))+"-"+string(template.days(end))+ ...
    "|hours1-24|state="+stateFingerprint+"|index="+ ...
    template.index_version;
rawObjectiveValue = template.capacity_parameters.cost.'*state.xi(q);
scaleFactor = template.objective_scale_factor;

lin = struct();
lin.identity = baseIdentity+ ...
    "|objective_scale=positive_scalar_unitization|factor="+ ...
    string(compose("%.17g",scaleFactor))+"|chain="+options.ChainId;
partition.linearization_identity = lin.identity;
partition.contract.identity = lin.identity;
partition.global.linearization_identity = lin.identity;
for d = 1:numel(partition.day)
    partition.day(d).linearization_identity = lin.identity;
end
reduced.linearization_identity = lin.identity;
lin.base_identity = baseIdentity;
lin.version = "stage-B2C-recursive-block-linearization-v1.0";
lin.storage_mode = "recursive_daily_blocks";
lin.global_matrices_assembled = false;
lin.stage_id = "stage_B"; lin.milestone_id = "B-2C";
lin.state_fingerprint = stateFingerprint;
lin.state = stateWithMu;
lin.objective = struct("value",rawObjectiveValue/scaleFactor, ...
    "gradient",template.objective_scaled_gradient, ...
    "original_gradient",template.objective_original_gradient, ...
    "original_value",rawObjectiveValue,"hessian_nnz",0);
lin.constraints = struct("eq",rEq,"ineq",ineqValue, ...
    "eq_offset",equality_offsets(template), ...
    "ineq_offset",ineqOffset,"water",water);
lin.blocks = struct("global_block",struct( ...
    "A",globalBlock.A,"G",globalBlock.G, ...
    "H",sparse(14,14),"q_indices",q, ...
    "equality_indices",yDuration, ...
    "inequality_rows",globalBlock.inequality_rows), ...
    "day",vertcat(dynamicDays{:}));
lin.partition = partition;
lin.reduced = reduced;
lin.r_dual = rDual; lin.r_eq = rEq; lin.r_ineq = rIneq;
lin.r_comp = rComp; lin.l = l; lin.z = z; lin.mu = mu;
lin.implied_slack = -ineqValue;
lin.complementarity_gap = gap; lin.raw_complementarity = l.'*z;
lin.linearization_identity_error_vector = zeros(nineq,1);
lin.linearization_identity_error = water.maximum_identity_error;
lin.lagrangian_hessian_symmetry_relative = 0;
lin.index = template.index; lin.fixed_zero_map = template.fixed_zero_map;
lin.permutation = template.permutation; lin.maps = template.maps;
lin.layout = template.layout;
lin.capacity_parameters = template.capacity_parameters;
lin.model_contract_version = template.model_contract_version;
lin.index_version = template.index_version; lin.counts = template.counts;
lin.config = template.config;
lin.base_linearization_identity = baseIdentity;
lin.water_multiplier_source = "current_formal_positive_state_z";
lin.water_hessian_rebuilt_from_current_state = true;
lin.objective_scale = struct("enabled",true, ...
    "mode","positive_scalar_unitization", ...
    "scale_source","max_abs_global_capacity_gradient", ...
    "factor",scaleFactor,"chain_id",options.ChainId, ...
    "original_gradient",template.objective_original_gradient, ...
    "scaled_gradient",template.objective_scaled_gradient, ...
    "original_value",rawObjectiveValue, ...
    "scaled_value",rawObjectiveValue/scaleFactor);
lin.execution = struct("full_kkt_assembled",false, ...
    "full_kkt_solved",false,"full_kkt_role",template.config.full_kkt_role, ...
    "recursive_direction_executed",false,"newton_direction_count",0, ...
    "full_ipm_executed",logical(state.optimization_state), ...
    "optimization_executed",logical(state.optimization_state), ...
    "state_update_executed",state.state_revision>0, ...
    "parallel_executed",false,"stage_c1_entered",false, ...
    "fallback_used",false);
lin.residual_definitions = struct( ...
    "r_eq","block_A*xi+eq_offset", ...
    "r_ineq","block_G*xi+ineq_offset+l", ...
    "r_dual","scaled_objective_gradient+block_A'*y+block_G'*z", ...
    "r_comp","l.*z-sigma*mean(l.*z)");
assert(nx==template.counts.primal && neq==template.counts.equalities && ...
    nineq==template.counts.inequalities && ...
    ~isfield(lin,"H") && ~isfield(lin,"A") && ~isfield(lin,"G"), ...
    "stageB2C:recursiveLinearization:Storage", ...
    "The recursive-only object must not contain global H, A, or G.");
end

function contract = make_contract(template,state,rDual,rEq,rIneq,rComp)
maps = template.maps;
contract = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "identity","","nx",template.n_primal,"neq",template.n_equalities, ...
    "nineq",template.n_inequalities, ...
    "n_base_inequality",template.n_base_inequalities, ...
    "n_water_inequality",template.n_water_inequalities, ...
    "days",template.days,"hours",template.hours, ...
    "n_days",numel(template.days),"n_hours",numel(template.hours), ...
    "base_inequality",(1:template.n_base_inequalities).', ...
    "water_inequality",template.water.rows, ...
    "q_global",maps.q_global,"q_day_by_day",{maps.q_day_by_day}, ...
    "y_duration",maps.y_duration, ...
    "y_binding_by_day",{maps.y_binding_by_day}, ...
    "x_by_day_hour",{maps.x_by_day_hour}, ...
    "y_by_day_hour",{maps.y_by_day_hour}, ...
    "ineq_global",maps.ineq_global, ...
    "ineq_by_day_hour",{maps.ineq_by_day_hour}, ...
    "water_by_day",{maps.water_by_day},"maps",maps, ...
    "index",template.index,"r_dual",rDual,"r_eq",rEq, ...
    "r_ineq",rIneq,"r_comp",rComp,"l",state.l(:), ...
    "z",state.z(:),"xi",state.xi(:));
contract.l_water = contract.l(contract.water_inequality);
contract.z_water = contract.z(contract.water_inequality);
contract.l_base = contract.l(contract.base_inequality);
contract.z_base = contract.z(contract.base_inequality);
contract.r_ineq_water = contract.r_ineq(contract.water_inequality);
contract.r_comp_water = contract.r_comp(contract.water_inequality);
contract.r_ineq_base = contract.r_ineq(contract.base_inequality);
contract.r_comp_base = contract.r_comp(contract.base_inequality);
end

function [partition,reduced] = build_partition(template,dynamicDays,contract)
nx = contract.nx;
globalRows = template.global_block.inequality_rows;
thetaGlobal = contract.z(globalRows)./contract.l(globalRows);
phiGlobal = (contract.r_comp(globalRows)- ...
    contract.z(globalRows).*contract.r_ineq(globalRows))./ ...
    contract.l(globalRows);
Wglobal = template.global_block.G.'* ...
    (spdiags(thetaGlobal,0,28,28)*template.global_block.G);
bGlobal = -contract.r_dual(template.maps.q_global)+ ...
    template.global_block.G.'*phiGlobal;
globalMatrix = [Wglobal,template.global_block.A.'; ...
    template.global_block.A,sparse(2,2)];
globalRhs = [bGlobal;-contract.r_eq(template.maps.y_duration)];

dayCells = cell(numel(template.day),1);
maximumSymmetry = 0;
for d = 1:numel(template.day)
    fixed = template.day(d);
    dynamic = dynamicDays(d);
    baseRows = fixed.base_inequality_rows;
    waterRows = fixed.water_rows;
    thetaBase = contract.z(baseRows)./contract.l(baseRows);
    thetaWater = contract.z(waterRows)./contract.l(waterRows);
    phiBase = (contract.r_comp(baseRows)- ...
        contract.z(baseRows).*contract.r_ineq(baseRows))./contract.l(baseRows);
    phiWater = (contract.r_comp(waterRows)- ...
        contract.z(waterRows).*contract.r_ineq(waterRows))./contract.l(waterRows);
    W = dynamic.H+dynamic.G_base.'* ...
        (spdiags(thetaBase,0,numel(baseRows),numel(baseRows))* ...
            dynamic.G_base)+dynamic.G_water.'* ...
        (spdiags(thetaWater,0,numel(waterRows),numel(waterRows))* ...
            dynamic.G_water);
    b = -contract.r_dual(fixed.primal_indices)+ ...
        dynamic.G_base.'*phiBase+dynamic.G_water.'*phiWater;
    saddle = [W,fixed.A_local.';fixed.A_local, ...
        sparse(numel(fixed.equality_indices), ...
            numel(fixed.equality_indices))];
    rhs = [b;-contract.r_eq(fixed.equality_indices)];
    permutation = fixed.local_reduced_permutation;
    matrix = sparse(saddle(permutation,permutation));
    rhs = rhs(permutation);
    symmetry = norm(matrix-matrix.',"fro")/max(1,norm(matrix,"fro"));
    maximumSymmetry = max(maximumSymmetry,symmetry);
    waterRatio = contract.l(waterRows)./contract.z(waterRows);
    dayCells{d} = struct("day_id",fixed.day_id, ...
        "linearization_identity","", ...
        "canonical_reduced_indices",fixed.canonical_reduced_indices, ...
        "matrix",matrix,"coupling",fixed.coupling, ...
        "capacity_coupling",fixed.coupling(:,1:14),"rhs",rhs, ...
        "dimension",fixed.dimension,"nnz",nnz(matrix), ...
        "q_day_local_positions",fixed.q_day_local_positions, ...
        "pi_day_local_positions",fixed.pi_day_local_positions, ...
        "hourly_local_positions",fixed.hourly_local_positions, ...
        "hourly_dimension",fixed.hourly_dimension, ...
        "rho_coupling_nnz",0,"symmetry_relative",symmetry, ...
        "water_rows",waterRows, ...
        "maximum_water_l_over_z",max(waterRatio), ...
        "minimum_water_z_over_l",min(1./waterRatio), ...
        "water_eta_dimension",0);
end
days = vertcat(dayCells{:});
globalIndices = [template.maps.q_global;nx+template.maps.y_duration];
dayIndices = vertcat(template.day.canonical_reduced_indices);
permutation = [globalIndices;dayIndices];
partition = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "linearization_identity","","contract",contract, ...
    "global",struct("canonical_reduced_indices",globalIndices, ...
        "matrix",sparse(globalMatrix),"rhs",globalRhs,"dimension",16, ...
        "symmetry_relative",norm(globalMatrix-globalMatrix.',"fro")/ ...
            max(1,norm(globalMatrix,"fro"))), ...
    "day",days,"days",template.days,"permutation",permutation, ...
    "permutation_is_bijection",isequal(sort(permutation), ...
        (1:contract.nx+contract.neq).'), ...
    "cross_day_nnz",0,"total_daily_dimension",sum([days.dimension]), ...
    "canonical_reduced_dimension",contract.nx+contract.neq, ...
    "water_eta_dimension",0,"full_inequality_elimination",true, ...
    "structure_template_reused",true, ...
    "structure_template_version","direct_recursive_daily_blocks_v1");
reduced = struct("stage_id","stage_B", ...
    "milestone_id","B-2C-DIRECT-DAILY-BLOCKS", ...
    "linearization_identity","","nx",contract.nx,"neq",contract.neq, ...
    "nineq",contract.nineq,"symmetry_relative",maximumSymmetry, ...
    "water_rows",contract.water_inequality, ...
    "water_theta",contract.z_water./contract.l_water, ...
    "water_l_over_z",contract.l_water./contract.z_water, ...
    "global_matrix_assembled",false,"daily_block_count",numel(days), ...
    "recovery_contract","dl=-r_ineq-G*dx; dz=(-r_comp-z.*dl)./l", ...
    "water_border_retained",false,"water_eta_retained",false, ...
    "regularization_used",false,"full_direction_consumed",false);
end

function value = equality_offsets(template)
value = zeros(template.n_equalities,1);
for d = 1:numel(template.day)
    value(template.day(d).equality_indices) = ...
        template.day(d).equality_offset;
end
end
