function lin = update_stage_b2c_scaled_objective_linearization( ...
        state,template,options)
%UPDATE_STAGE_B2C_SCALED_OBJECTIVE_LINEARIZATION Update dynamic values only.

arguments
    state (1,1) struct
    template (1,1) struct
    options.PrecomputedWater (1,1) struct = struct()
    options.ChainId (1,1) string = "B-2C-FORMAL-IPM"
end
assert(string(template.version)== ...
    "stage-B2C-linearization-template-v1.0" && ...
    string(state.milestone_id)=="B-2C" && ...
    numel(state.xi)==template.n_primal && ...
    numel(state.y)==template.n_equalities && ...
    numel(state.l)==template.n_inequalities && ...
    numel(state.z)==template.n_inequalities && ...
    all(state.l>0) && all(state.z>0), ...
    "stageB2C:template:UpdateInput", ...
    "The current positive state does not match the fixed B-2C template.");
if isempty(fieldnames(options.PrecomputedWater))
    water = rkkt.model.evaluate_stage_b2c_water_template(state.xi,template);
else
    water = options.PrecomputedWater;
end
assert(isequal(size(water.G), ...
        [template.n_water_inequalities,template.n_primal]) && ...
    numel(water.constraint_value)==template.n_water_inequalities, ...
    "stageB2C:template:PrecomputedWater", ...
    "The precomputed water update does not match the fixed template.");

A = template.A;
G = [template.base_G;water.G];
equalityOffset = template.equality_offset;
inequalityOffset = [template.base_inequality_offset;water.offset];
equalityValue = A*state.xi+equalityOffset;
baseInequalityValue = template.base_G*state.xi+ ...
    template.base_inequality_offset;
inequalityValue = [baseInequalityValue;water.constraint_value];
linearizedValue = G*state.xi+inequalityOffset;
identityErrorVector = linearizedValue-inequalityValue;

waterMultiplier = state.z(template.water.rows);
hessianValues = repmat( ...
    waterMultiplier.*template.water.hessian_coefficient,1,24);
waterHessian = sparse(template.water.columns(:), ...
    template.water.columns(:),hessianValues(:), ...
    template.n_primal,template.n_primal);
lagrangianHessian = template.objective_hessian+waterHessian;
weightedRows = repmat(weighted_record_template(), ...
    template.n_water_inequalities,1);
for row = 1:template.n_water_inequalities
    record = template.water.constraint_hessians(row);
    weightedRows(row) = struct( ...
        "constraint_id",record.constraint_id, ...
        "inequality_position",record.inequality_position, ...
        "multiplier",waterMultiplier(row),"sign",record.sign, ...
        "contribution_nnz",template.water.hessian_nnz(row), ...
        "contribution_frobenius_norm", ...
            abs(waterMultiplier(row))* ...
            template.water.hessian_frobenius(row));
end

l = state.l(:);
z = state.z(:);
gap = mean(l.*z);
mu = template.config.initialization.centering_sigma*gap;
scaledGradient = template.scaled_objective_gradient;
originalGradient = template.original_objective_gradient;
rEq = equalityValue;
rIneq = inequalityValue+l;
rDual = scaledGradient+A.'*state.y+G.'*z;
rComp = l.*z-mu;
assert(all(isfinite([rEq;rIneq;rDual;rComp])) && mu>0, ...
    "stageB2C:template:FiniteResidual", ...
    "The cached B-2C numeric update produced a nonfinite residual.");

finalState = state;
finalState.mu = mu;
stateFingerprint = ...
    rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(finalState);
baseIdentity = "stage-B2C-linearization-v1.0|"+ ...
    strjoin(template.input_hashes,"|")+"|days"+ ...
    string(template.days(1))+"-"+string(template.days(end))+ ...
    "|hours1-24|state="+stateFingerprint+"|index="+ ...
    template.index_version;
scaleFactor = template.objective_scale_factor;
rawObjectiveValue = template.capacity_parameters.cost.'* ...
    state.xi(template.maps.q_global);
scaledObjectiveValue = rawObjectiveValue/scaleFactor;
stageABaseIdentity = template.stage_a_base_identity;
if strlength(template.stage_a_base_identity_prefix)>0
    stageABaseIdentity = template.stage_a_base_identity_prefix+ ...
        "|iteration"+string(state.iteration_index)+ ...
        "|revision"+string(state.state_revision);
end
execution = struct("full_kkt_assembled",false, ...
    "full_kkt_solved",false,"full_kkt_role", ...
        template.config.full_kkt_role, ...
    "recursive_direction_executed",false,"newton_direction_count",0, ...
    "full_ipm_executed",logical(state.optimization_state), ...
    "optimization_executed",logical(state.optimization_state), ...
    "state_update_executed",state.state_revision>0, ...
    "parallel_executed",false,"stage_c1_entered",false, ...
    "fallback_used",false);

lin = struct();
lin.identity = baseIdentity+ ...
    "|objective_scale=positive_scalar_unitization|factor="+ ...
    string(compose("%.17g",scaleFactor))+"|chain="+options.ChainId;
lin.version = "stage-B2C-linearization-v1.0";
lin.stage_id = "stage_B";
lin.milestone_id = "B-2C";
lin.state_fingerprint = stateFingerprint;
lin.state = state;
lin.objective = struct("value",scaledObjectiveValue, ...
    "gradient",scaledGradient,"hessian",template.objective_hessian, ...
    "original_gradient",originalGradient, ...
    "original_value",rawObjectiveValue);
lin.constraints = struct("eq",equalityValue,"ineq",inequalityValue, ...
    "eq_offset",equalityOffset,"ineq_offset",inequalityOffset, ...
    "water",water);
lin.jacobian = struct("A",A,"G",G,"water_G",water.G);
lin.hessian = struct("objective",template.objective_hessian, ...
    "constraint_water",template.water.constraint_hessians, ...
    "constraint_water_weighted",weightedRows, ...
    "lagrangian",lagrangianHessian);
lin.H = lagrangianHessian;
lin.A = A;
lin.G = G;
lin.r_dual = rDual;
lin.r_eq = rEq;
lin.r_ineq = rIneq;
lin.r_comp = rComp;
lin.l = l;
lin.z = z;
lin.mu = mu;
lin.implied_slack = -inequalityValue;
lin.complementarity_gap = gap;
lin.raw_complementarity = l.'*z;
lin.linearization_identity_error_vector = identityErrorVector;
lin.linearization_identity_error = norm(identityErrorVector,inf);
lin.lagrangian_hessian_symmetry_relative = 0;
lin.index = template.index;
lin.fixed_zero_map = template.fixed_zero_map;
lin.permutation = template.permutation;
lin.maps = template.maps;
lin.layout = template.layout;
lin.capacity_parameters = template.capacity_parameters;
lin.model_contract_version = template.model_contract_version;
lin.index_version = template.index_version;
lin.counts = template.counts;
lin.execution = execution;
lin.base_linearization_identity = stageABaseIdentity;
lin.water_multiplier_source = "current_formal_positive_state_z";
lin.water_hessian_rebuilt_from_current_state = true;
lin.config = template.config;
lin.base_identity = baseIdentity;
lin.objective_scale = struct("enabled",true, ...
    "mode","positive_scalar_unitization", ...
    "scale_source","max_abs_global_capacity_gradient", ...
    "factor",scaleFactor,"chain_id",options.ChainId, ...
    "original_gradient",originalGradient, ...
    "scaled_gradient",scaledGradient, ...
    "original_value",rawObjectiveValue, ...
    "scaled_value",scaledObjectiveValue);
lin.residual_definitions = struct( ...
    "r_eq","A*xi+eq_offset", ...
    "r_ineq","G*xi+ineq_offset+l", ...
    "r_dual","scaled_objective_gradient+A'*y+G'*z", ...
    "r_comp","l.*z-sigma*mean(l.*z)");
scale = max(1,norm(inequalityValue,inf));
assert(issparse(lin.H) && issparse(lin.A) && issparse(lin.G) && ...
    lin.linearization_identity_error<=64*eps(scale) && ...
    lin.counts.full_kkt==template.config.expected_full_kkt_dimension, ...
    "stageB2C:template:UpdateOutput", ...
    "The cached B-2C numeric update violated its matrix contract.");
end

function value = weighted_record_template()
value = struct("constraint_id","","inequality_position",0, ...
    "multiplier",0,"sign",0,"contribution_nnz",0, ...
    "contribution_frobenius_norm",0);
end
