function exported = export_stage_a4_iteration24_scaling_stress( ...
        context,result,options)
%EXPORT_STAGE_A4_ITERATION24_SCALING_STRESS Persist stress-test evidence.

arguments
    context (1,1) struct
    result (1,1) struct
    options.CommandText (1,1) string = ...
        "matlab -batch ""result="+ ...
        "main_stage_A4_iteration24_scaling_stress(); "+ ...
        "assert(strcmp(result.stress_status,'PASS'));"""
end

requiredContext = ["root","run_id","matrices_dir", ...
    "matrix_manifest_path","acceptance_results_path", ...
    "issue_log_path","decision_log_path"];
assert(all(isfield(context,cellstr(requiredContext))), ...
    "stageA4:scaleStress:ContextSchema", ...
    "The stress exporter received an incomplete run context.");
assert(result.stage_id=="stage_A4" && ...
    result.milestone=="A4-ITER24-SCALE-STRESS", ...
    "stageA4:scaleStress:ResultIdentity", ...
    "The stress exporter received the wrong result identity.");

diagnosticsDirectory = fullfile(context.root,"diagnostics");
ensure_directory(diagnosticsDirectory);
commandPath = fullfile(diagnosticsDirectory,"generation_command.txt");
write_text(commandPath,options.CommandText);

hourlyPath = fullfile(diagnosticsDirectory,"hourly_factor_audit.csv");
refinementPath = fullfile(diagnosticsDirectory,"refinement_audit.csv");
directionPath = fullfile(diagnosticsDirectory,"direction_audit.csv");
determinismPath = fullfile(diagnosticsDirectory,"determinism_audit.csv");
corePath = fullfile(diagnosticsDirectory,"core16_audit.csv");
forbiddenPath = fullfile(diagnosticsDirectory, ...
    "forbidden_execution_audit.csv");
closurePath = fullfile(diagnosticsDirectory, ...
    "dependency_closure.csv");
modelScopePath = fullfile(diagnosticsDirectory, ...
    "model_scope_audit.csv");
rkkt.artifacts.write_table_csv_17g_atomic(hourlyPath,result.hourly_factor_audit);
rkkt.artifacts.write_table_csv_17g_atomic(refinementPath,result.refinement_audit);
rkkt.artifacts.write_table_csv_17g_atomic(directionPath,direction_table(result));
rkkt.artifacts.write_table_csv_17g_atomic(determinismPath,determinism_table(result));
rkkt.artifacts.write_table_csv_17g_atomic(corePath,struct2table(result.core_audit));
rkkt.artifacts.write_table_csv_17g_atomic(forbiddenPath,result.forbidden_execution.results);
rkkt.artifacts.write_table_csv_17g_atomic(closurePath,result.forbidden_execution.dependency_closure);
rkkt.artifacts.write_table_csv_17g_atomic(modelScopePath,model_scope_table());

hour3 = result.hourly_factor_audit( ...
    result.hourly_factor_audit.day==14 & ...
    result.hourly_factor_audit.hour==3,:);
assert(height(hour3)==1,"stageA4:scaleStress:Hour3Audit", ...
    "Exactly one day-14/hour-3 audit row is required.");
summary = struct( ...
    "stress_status",char(result.status), ...
    "stage_a4_status","READY", ...
    "stage_a4_pass_claimed",false, ...
    "authority_run_id",char(result.authority_run_id), ...
    "authority_commit",char(result.authority_commit), ...
    "authority_manifest_sha256",char(result.authority_manifest_sha256), ...
    "state_revision",result.state_revision, ...
    "state_fingerprint",char(result.state_fingerprint_before), ...
    "linearization_fingerprint", ...
        char(result.linearization_fingerprint), ...
    "unscaled_failure_identifier", ...
        char(result.unscaled_failure.identifier), ...
    "unscaled_failure_layer","day_14_block_ldl_thomas", ...
    "hour3_original_rank",hour3.original_numeric_rank, ...
    "hour3_scaled_rank",hour3.scaled_numeric_rank, ...
    "hour3_dimension",hour3.dimension, ...
    "hour3_original_condition_2",hour3.original_condition_2, ...
    "hour3_scaled_condition_2",hour3.scaled_condition_2, ...
    "hour3_condition_reduction_factor", ...
        hour3.condition_reduction_factor, ...
    "direction_relative_error", ...
        result.equivalence.direction_relative_error, ...
    "xi_direction_relative_error", ...
        result.equivalence.component_relative_errors.xi, ...
    "y_direction_relative_error", ...
        result.equivalence.component_relative_errors.y, ...
    "l_direction_relative_error", ...
        result.equivalence.component_relative_errors.l, ...
    "z_direction_relative_error", ...
        result.equivalence.component_relative_errors.z, ...
    "recursive_full_kkt_relative_residual", ...
        result.equivalence.recursive_kkt_relative_residual, ...
    "full_kkt_audit_relative_residual", ...
        result.equivalence.full_kkt_relative_residual, ...
    "maximum_day_response_symmetry_relative", ...
        result.maximum_day_response_symmetry_relative, ...
    "factor_count",result.factor_operator_audit.factor_count, ...
    "maximum_congruence_reconstruction_relative", ...
        result.factor_operator_audit. ...
        maximum_congruence_reconstruction_relative, ...
    "maximum_factor_reconstruction_relative", ...
        result.factor_operator_audit. ...
        maximum_factor_reconstruction_relative, ...
    "maximum_original_factorized_operator_relative", ...
        result.factor_operator_audit. ...
        maximum_original_factorized_operator_relative, ...
    "forbidden_execution_check_count", ...
        result.forbidden_execution.check_count, ...
    "forbidden_execution_all_pass", ...
        result.forbidden_execution.all_pass, ...
    "dependency_closure_file_count", ...
        result.forbidden_execution.dependency_file_count, ...
    "deterministic_repeat_exact", ...
        result.determinism.direction_exact, ...
    "direction_fingerprint", ...
        char(result.determinism.first_direction_fingerprint), ...
    "state_update_count",0, ...
    "execution_ledger",result.execution_ledger, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "automatic_symmetrization_used",false, ...
    "regularization_used",false, ...
    "full_kkt_direction_fallback_used",false, ...
    "full_kkt_role","independent_audit_only", ...
    "formal_a4_run_created",false, ...
    "current_stage","stage_A4 / READY");
summaryPath = fullfile(diagnosticsDirectory,"stress_summary.json");
rkkt.artifacts.write_json_file(summaryPath,summary);
identity = struct( ...
    "schema_version",result.schema_version, ...
    "run_id",string(context.run_id), ...
    "run_purpose",result.run_purpose, ...
    "milestone",result.milestone, ...
    "authority_run_id",result.authority_run_id, ...
    "authority_commit",result.authority_commit, ...
    "authority_manifest_path",result.authority_manifest_path, ...
    "authority_manifest_sha256",result.authority_manifest_sha256, ...
    "failure_evidence_path",result.failure_evidence_path, ...
    "failure_evidence_sha256",result.failure_evidence_sha256, ...
    "state_revision",result.state_revision, ...
    "state_fingerprint_before",result.state_fingerprint_before, ...
    "state_fingerprint_after",result.state_fingerprint_after, ...
    "linearization_fingerprint",result.linearization_fingerprint, ...
    "linearization_identity",result.linearization_identity, ...
    "effective_config_sha256",result.effective_config.sha256, ...
    "git_commit",result.git.commit, ...
    "git_branch",result.git.branch, ...
    "actual_command",options.CommandText);
identityPath = fullfile(diagnosticsDirectory,"stress_identity.json");
rkkt.artifacts.write_json_file(identityPath,identity);

resultPath = fullfile(diagnosticsDirectory,"scaling_stress_result.mat");
matrixPath = fullfile(context.matrices_dir, ...
    "iteration24_scaling_stress_matrices.mat");
assert(~isfile(resultPath)&&~isfile(matrixPath), ...
    "stageA4:scaleStress:ArtifactExists", ...
    "Refusing to overwrite stress MAT evidence.");
persisted = result;
persisted = rmfield(persisted, ...
    ["linearization","recursive","full_audit"]);
save(resultPath,"persisted","-v7.3");
linearization_identity = result.linearization.identity;
linearization_fingerprint = result.linearization_fingerprint;
H = result.linearization.H;
A = result.linearization.A;
G = result.linearization.G;
full_kkt_matrix = result.full_audit.kkt.matrix;
full_kkt_rhs = result.full_audit.kkt.rhs;
recursive_direction = result.recursive.direction;
full_audit_direction = result.full_audit.direction;
day14_hour3_original = ...
    result.recursive.daily_thomas(1).factors{3}.matrix;
day14_hour3_scaled = ...
    result.recursive.daily_thomas(1).factors{3}. ...
    factorization_matrix;
day14_hour3_scale = ...
    result.recursive.daily_thomas(1).factors{3}. ...
    congruence_scale;
core16_original = result.recursive.core.factor.matrix;
core16_scaled = ...
    result.recursive.core.factor.factorization_matrix;
daily_responses = result.recursive.daily_responses;
save(matrixPath,"linearization_identity", ...
    "linearization_fingerprint","H","A","G", ...
    "full_kkt_matrix","full_kkt_rhs", ...
    "recursive_direction","full_audit_direction", ...
    "day14_hour3_original","day14_hour3_scaled", ...
    "day14_hour3_scale","core16_original","core16_scaled", ...
    "daily_responses","-v7.3");

matrixManifest = table( ...
    ["linearization_H";"linearization_A";"linearization_G"; ...
        "complete_sparse_kkt";"day14_hour3_original_schur"; ...
        "day14_hour3_scaled_schur";"global_core16_original"; ...
        "global_core16_scaled";"recursive_direction"; ...
        "full_audit_direction"], ...
    [size(H,1);size(A,1);size(G,1);size(full_kkt_matrix,1); ...
        size(day14_hour3_original,1);size(day14_hour3_scaled,1); ...
        size(core16_original,1);size(core16_scaled,1); ...
        numel(recursive_direction);numel(full_audit_direction)], ...
    [size(H,2);size(A,2);size(G,2);size(full_kkt_matrix,2); ...
        size(day14_hour3_original,2);size(day14_hour3_scaled,2); ...
        size(core16_original,2);size(core16_scaled,2); ...
        1;1], ...
    [nnz(H);nnz(A);nnz(G);nnz(full_kkt_matrix); ...
        nnz(day14_hour3_original);nnz(day14_hour3_scaled); ...
        nnz(core16_original);nnz(core16_scaled); ...
        nnz(recursive_direction);nnz(full_audit_direction)], ...
    repmat("matrices/iteration24_scaling_stress_matrices.mat",10,1), ...
    ["original_model_operator";"original_model_operator"; ...
        "original_model_operator";"complete_kkt_audit_only"; ...
        "original_residual_operator"; ...
        "factorization_operator_DMD"; ...
        "original_residual_operator"; ...
        "factorization_operator_DMD"; ...
        "formal_recursive_stress_direction"; ...
        "independent_complete_kkt_audit_direction"], ...
    'VariableNames',{'matrix_id','rows','columns','nnz', ...
    'relative_path','role'});
rkkt.artifacts.write_table_csv_17g_atomic(context.matrix_manifest_path,matrixManifest);

acceptance = acceptance_table(context,result);
rkkt.artifacts.write_table_csv_17g_atomic(context.acceptance_results_path,acceptance);
issueLog = table( ...
    string(context.run_id),"A4-SCALE-STRESS-NOT-STAGE-PASS","NOTICE", ...
    "OPEN",false, ...
    "压力测试PASS只证明冻结第24轮方向的数值稳定性；"+ ...
        "Stage A4仍为READY，未执行完整IPM或正式收敛运行。", ...
    "等待用户审阅；不得自动恢复正式A4或进入Stage B。", ...
    'VariableNames',{'run_id','issue_id','severity','status', ...
    'blocking','description','next_action'});
rkkt.artifacts.write_table_csv_17g_atomic(context.issue_log_path,issueLog);
decisionLog = table( ...
    string(context.run_id), ...
    "A4-ITER24-SCALE-STRESS", ...
    "采用局部对称对角合同尺度化与stable-v2保留因子精化，"+ ...
        "仅用于独立压力测试。", ...
    "保留原算子残差审计；完整KKT只做独立方向审计；不更新状态。", ...
    "stage_A4 / READY", ...
    'VariableNames',{'run_id','decision_id','decision', ...
    'evidence_boundary','stage_state'});
rkkt.artifacts.write_table_csv_17g_atomic(context.decision_log_path,decisionLog);

exported = struct( ...
    "summary",summary, ...
    "summary_path",string(summaryPath), ...
    "identity_path",string(identityPath), ...
    "result_path",string(resultPath), ...
    "matrix_path",string(matrixPath), ...
    "hourly_path",string(hourlyPath), ...
    "forbidden_execution_path",string(forbiddenPath), ...
    "dependency_closure_path",string(closurePath), ...
    "model_scope_path",string(modelScopePath), ...
    "direction_path",string(directionPath), ...
    "acceptance",acceptance, ...
    "all_blocking_pass",all(acceptance.status=="PASS"));
end

function tableValue = direction_table(result)
metric = [ ...
    "direction_relative_error"; ...
    "xi_direction_relative_error"; ...
    "y_direction_relative_error"; ...
    "l_direction_relative_error"; ...
    "z_direction_relative_error"; ...
    "recursive_full_kkt_relative_residual"; ...
    "full_kkt_audit_relative_residual"; ...
    "maximum_day_response_symmetry_relative"];
value = [ ...
    result.equivalence.direction_relative_error; ...
    result.equivalence.component_relative_errors.xi; ...
    result.equivalence.component_relative_errors.y; ...
    result.equivalence.component_relative_errors.l; ...
    result.equivalence.component_relative_errors.z; ...
    result.equivalence.recursive_kkt_relative_residual; ...
    result.equivalence.full_kkt_relative_residual; ...
    result.maximum_day_response_symmetry_relative];
threshold = [ ...
    repmat(result.options.direction_tolerance,5,1); ...
    result.options.recursive_residual_tolerance; ...
    result.options.full_residual_tolerance; ...
    result.options.symmetry_tolerance];
status = repmat("PASS",numel(metric),1);
status(value>threshold) = "FAIL";
tableValue = table(metric,value,threshold,status);
end

function tableValue = determinism_table(result)
tableValue = table( ...
    ["direction_exact";"maximum_absolute_difference"; ...
        "first_direction_fingerprint"; ...
        "second_direction_fingerprint"], ...
    [string(result.determinism.direction_exact); ...
        string(sprintf("%.17g", ...
            result.determinism.maximum_absolute_difference)); ...
        result.determinism.first_direction_fingerprint; ...
        result.determinism.second_direction_fingerprint], ...
    ["true";"0";result.determinism.first_direction_fingerprint; ...
        result.determinism.first_direction_fingerprint], ...
    repmat("PASS",4,1), ...
    'VariableNames',{'metric','actual','expected','status'});
end

function tableValue = model_scope_table()
%MODEL_SCOPE_TABLE Persist the enabled/disabled model-contract boundary.
%
% These rows are configuration facts, not computed dispatch or economic
% conclusions.  Keeping them beside the numerical evidence makes the
% report auditable without silently implying that disabled model features
% were exercised by this one-direction stress test.
scope = [ ...
    "enabled";"enabled";"enabled";"enabled";"enabled";"enabled"; ...
    "disabled";"disabled";"disabled";"disabled";"disabled";"disabled"; ...
    "disabled";"disabled"];
item = [ ...
    "容量投资目标（单一全局容量目标）"; ...
    "第14--20日完整24小时功率平衡与设备边界"; ...
    "每日SOC初末0.5E、日期之间无SOC连接"; ...
    "Pch/Pdis独立连续变量（无互斥状态）"; ...
    "火电第一阶段边界 0 <= PF <= Pmax"; ...
    "风光零可用率变量及重合界的精确删除/恢复"; ...
    "完整内点迭代"; ...
    "优化求解与容量规划解释"; ...
    "并行执行"; ...
    "水电日用水约束"; ...
    "火电第二阶段Pmin/开停机处理"; ...
    "最小开停机时间、启动成本、停机成本"; ...
    "年度365日运行"; ...
    "调度、经济性或物理运行结论"];
reason = [ ...
    "沿用冻结A4线性化目标，仅计算一次方向"; ...
    "从权威第23轮状态重建的压力输入"; ...
    "沿用阶段A模型合同"; ...
    "沿用阶段A模型合同"; ...
    "沿用阶段A模型合同"; ...
    "用于自然变维递推块审计"; ...
    "本里程碑只做单次Newton方向"; ...
    "本里程碑不更新状态"; ...
    "阶段A4治理边界"; ...
    "当前模型合同未启用"; ...
    "当前模型合同未启用"; ...
    "保留FUTURE-UC，当前未实现"; ...
    "本压力点只覆盖7日窗口"; ...
    "本压力测试不生成运行结论"];
tableValue = table(scope,item,reason, ...
    'VariableNames',{'state','model_item','evidence_boundary'});
end

function tableValue = acceptance_table(context,result)
hour3 = result.hourly_factor_audit( ...
    result.hourly_factor_audit.day==14 & ...
    result.hourly_factor_audit.hour==3,:);
ids = [ ...
    "A4-SS-AUTH-001";"A4-SS-BASE-001";"A4-SS-RANK-001"; ...
    "A4-SS-EQ-001";"A4-SS-EQ-002";"A4-SS-FULL-001"; ...
    "A4-SS-SYM-001";"A4-SS-DET-001";"A4-SS-OP-001"; ...
    "A4-SS-REF-001";"A4-SS-NOFALLBACK-001"; ...
    "A4-SS-FORBIDDEN-001";"A4-SS-GOV-001"];
names = [ ...
    "权威状态与linearization精确重建"; ...
    "未尺度化失败签名复现"; ...
    "day14/hour3尺度化恢复满秩"; ...
    "完整与递推方向等价"; ...
    "递推方向代回完整KKT"; ...
    "完整KKT独立审计残差"; ...
    "日响应与因子对称审计"; ...
    "同一压力输入连续两次确定性"; ...
    "实际分解算子与原算子合同闭合"; ...
    "stable-v2有界精化且最多3次"; ...
    "无完整KKT方向回退"; ...
    "禁止执行项与真实依赖闭包审计"; ...
    "无状态更新且阶段保持READY"];
passed = [ ...
    result.state_unchanged && result.input_hashes_pass; ...
    result.unscaled_failure.present; ...
    hour3.scaled_numeric_rank==hour3.dimension; ...
    result.equivalence.direction_relative_error<= ...
        result.options.direction_tolerance && ...
        all([result.equivalence.component_relative_errors.xi, ...
        result.equivalence.component_relative_errors.y, ...
        result.equivalence.component_relative_errors.l, ...
        result.equivalence.component_relative_errors.z]<= ...
        result.options.direction_tolerance); ...
    result.equivalence.recursive_kkt_relative_residual<= ...
        result.options.recursive_residual_tolerance; ...
    result.equivalence.full_kkt_relative_residual<= ...
        result.options.full_residual_tolerance; ...
    result.maximum_day_response_symmetry_relative<= ...
        result.options.symmetry_tolerance; ...
    result.determinism.direction_exact && ...
        result.determinism.maximum_absolute_difference==0; ...
    result.factor_operator_audit.all_pass; ...
    all(result.refinement_audit.maximum_passes==3) && ...
        all(result.refinement_audit.correction_count<=3); ...
    result.no_full_direction_fallback; ...
    result.forbidden_execution.all_pass; ...
    result.state_update_count==0 && ...
        result.stage_status=="READY" && ...
        ~result.stage_a4_pass_claimed];
actual = [ ...
    result.state_fingerprint_before+" / "+ ...
        result.linearization_fingerprint; ...
    result.unscaled_failure.identifier+" @ day14/hour3"; ...
    "rank="+string(hour3.original_numeric_rank)+" -> "+ ...
        string(hour3.scaled_numeric_rank); ...
    "relative_error="+string(sprintf("%.17g", ...
        result.equivalence.direction_relative_error)); ...
    "relative_residual="+string(sprintf("%.17g", ...
        result.equivalence.recursive_kkt_relative_residual)); ...
    "relative_residual="+string(sprintf("%.17g", ...
        result.equivalence.full_kkt_relative_residual)); ...
    "symmetry_relative="+string(sprintf("%.17g", ...
        result.maximum_day_response_symmetry_relative)); ...
    string(result.determinism.direction_exact)+ ...
        ", maxdiff="+string(sprintf("%.17g", ...
        result.determinism.maximum_absolute_difference)); ...
    "relative_error="+string(sprintf("%.17g", ...
        result.factor_operator_audit. ...
        maximum_congruence_reconstruction_relative)); ...
    "max corrections="+string(max( ...
        result.refinement_audit.correction_count)); ...
    string(result.no_full_direction_fallback); ...
    string(result.forbidden_execution.check_count)+"项独立检查，"+ ...
        string(result.forbidden_execution.dependency_file_count)+ ...
        "个依赖文件"; ...
    "updates=0; stage_A4 / READY"];
contract = [ ...
    "authority hashes exact"; ...
    "rank=17 at day14/hour3"; ...
    "scaled rank=22"; ...
    "<=1e-10, including xi/y/l/z"; ...
    "<=1e-10"; ...
    "<=1e-10"; ...
    "<=1e-12"; ...
    "zero-tolerance repeat"; ...
    "<=64*eps"; ...
    "maximum 3 passes"; ...
    "全部独立检查PASS"; ...
    "no forbidden execution"; ...
    "no update; no stage pass"];
status = repmat("FAIL",numel(ids),1);
status(passed) = "PASS";
tableValue = table( ...
    repmat(string(context.run_id),numel(ids),1),ids,names, ...
    true(numel(ids),1),contract,actual,status, ...
    'VariableNames',{'run_id','acceptance_id','name','blocking', ...
    'contract','actual','status'});
end

function write_text(pathValue,textValue)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA4:scaleStress:TextExists", ...
    "Refusing to overwrite %s.",pathValue);
fileId = fopen(pathValue,"w","n","UTF-8");
assert(fileId>=0,"stageA4:scaleStress:TextOpen", ...
    "Could not create %s.",pathValue);
guard = onCleanup(@()fclose(fileId));
fprintf(fileId,"%s\n",char(textValue));
clear guard
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message] = mkdir(pathValue);
assert(created,"stageA4:scaleStress:DirectoryCreate", ...
    "Could not create %s: %s",pathValue,message);
end
