function exported = export_stage_a4_iteration24_rank_replay( ...
        runContext,result,options)
%EXPORT_STAGE_A4_ITERATION24_RANK_REPLAY Persist diagnostic-only evidence.
%
% All numerical values are taken from RESULT, which is rebuilt from the
% immutable revision-23 failure state.  This exporter does not update a
% solver state, overwrite a historical run, or create a Stage-A4 PASS
% claim.

arguments
    runContext (1,1) struct
    result (1,1) struct
    options.CommandText (1,1) string = ...
        "matlab -batch ""result="+ ...
        "main_stage_A4_iteration24_rank_replay();"""
end

assert(result.pass && result.no_state_update && ...
    result.no_stage_a4_pass_claim, ...
    "stageA4:iter24:ExportGate", ...
    "Only a completed diagnostic replay may be exported.");
diagnosticsDirectory = fullfile(runContext.root,"diagnostics");
ensure_directory(diagnosticsDirectory);

paths = struct();
paths.command = fullfile(diagnosticsDirectory,"replay_command.txt");
paths.identity = fullfile(diagnosticsDirectory,"replay_identity.json");
paths.summary = fullfile(diagnosticsDirectory,"diagnostic_summary.json");
paths.block_summary = fullfile(diagnosticsDirectory,"block_summary.csv");
paths.singular_values = fullfile(diagnosticsDirectory,"singular_values.csv");
paths.near_null = fullfile(diagnosticsDirectory,"near_null_components.csv");
paths.curvature = fullfile(diagnosticsDirectory,"curvature_sources.csv");
paths.scaling_trace = fullfile(diagnosticsDirectory,"scaling_trace.csv");
paths.coordinate_scaling = fullfile(diagnosticsDirectory, ...
    "diagnostic_coordinate_scaling.csv");
paths.factor_comparison = fullfile(diagnosticsDirectory, ...
    "factor_solve_comparison.csv");
paths.protected = fullfile(diagnosticsDirectory, ...
    "protected_file_audit.csv");
paths.result_mat = fullfile(diagnosticsDirectory, ...
    "iteration24_rank_replay_result.mat");
paths.matrix_mat = fullfile(runContext.matrices_dir, ...
    "iteration24_local_pivots_and_full_audit.mat");
paths.matrix_manifest = runContext.matrix_manifest_path;
paths.acceptance = runContext.acceptance_results_path;
paths.issue_log = runContext.issue_log_path;

assert_targets_absent(string(struct2cell(paths)));
write_text(paths.command,options.CommandText+newline);
rkkt.artifacts.write_table_csv_17g_atomic(paths.block_summary,result.block_summary);
rkkt.artifacts.write_table_csv_17g_atomic(paths.singular_values,result.singular_values);
rkkt.artifacts.write_table_csv_17g_atomic(paths.near_null,result.near_null_components);
rkkt.artifacts.write_table_csv_17g_atomic(paths.curvature,result.curvature_sources);
rkkt.artifacts.write_table_csv_17g_atomic(paths.scaling_trace,result.scaling_trace);
rkkt.artifacts.write_table_csv_17g_atomic(paths.coordinate_scaling, ...
    result.coordinate_scaling);
rkkt.artifacts.write_table_csv_17g_atomic(paths.factor_comparison, ...
    result.factor_solve_comparison);
rkkt.artifacts.write_table_csv_17g_atomic(paths.protected, ...
    result.protected_file_audit.table);

identity = make_identity(result,runContext);
summary = make_summary(result,runContext);
rkkt.artifacts.write_json_file(paths.identity,identity);
rkkt.artifacts.write_json_file(paths.summary,summary);

persisted = result;
matrixData = persisted.matrix_data;
persisted = rmfield(persisted,"matrix_data");
if isfield(persisted.high_precision,"solution_double")
    persisted.high_precision = rmfield( ...
        persisted.high_precision,"solution_double");
end
save(paths.result_mat,"persisted","-v7.3");
save(paths.matrix_mat,"matrixData","-v7.3");

matrixManifest = make_matrix_manifest( ...
    runContext.root,paths.matrix_mat,matrixData);
rkkt.artifacts.write_table_csv_17g_atomic(paths.matrix_manifest,matrixManifest);
acceptance = make_acceptance(result,runContext);
rkkt.artifacts.write_table_csv_17g_atomic(paths.acceptance,acceptance);
issues = make_issue_log(result,runContext);
rkkt.artifacts.write_table_csv_17g_atomic(paths.issue_log,issues);

exported = struct("paths",paths,"identity",identity, ...
    "summary",summary,"matrix_manifest",matrixManifest, ...
    "acceptance",acceptance,"issues",issues);
end

function identity = make_identity(result,context)
identity = struct( ...
    "run_id",string(context.run_id), ...
    "stage_id","stage_A4", ...
    "stage_status","READY", ...
    "milestone",result.milestone, ...
    "run_purpose",result.run_purpose, ...
    "authority_run_id",result.authority_run_id, ...
    "authority_commit",result.authority_commit, ...
    "current_commit",result.current_commit, ...
    "current_branch",result.current_branch, ...
    "state_revision",result.state_revision, ...
    "attempted_iteration",24, ...
    "state_fingerprint",result.state_fingerprint, ...
    "linearization_fingerprint",result.linearization_fingerprint, ...
    "failure_evidence_sha256",result.failure_evidence_sha256, ...
    "state_update_count",0, ...
    "newton_direction_count_attempted",1, ...
    "newton_direction_count_completed",0, ...
    "formal_a4_run_created",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "stage_b_entered",false, ...
    "complete_kkt_role","independent_audit_only", ...
    "full_kkt_direction_consumed",false, ...
    "full_direction_fallback_used",false, ...
    "automatic_symmetrization_used",false, ...
    "regularization_used",false);
end

function summary = make_summary(result,context)
h2 = result.block_summary(result.block_summary.hour==2,:);
h3 = result.block_summary(result.block_summary.hour==3,:);
scaled = result.scaling_trace(end,:);
summary = struct( ...
    "run_id",string(context.run_id), ...
    "diagnostic_status","PASS", ...
    "stage_a4_status","READY", ...
    "stage_a4_pass_claimed",false, ...
    "root_cause_classification", ...
        result.root_cause.classification, ...
    "root_cause_title",result.root_cause.title, ...
    "production_failure_reproduced", ...
        result.root_cause.production_failure_reproduced, ...
    "structural_rank_deficiency_rejected", ...
        result.root_cause.structural_rank_deficiency_rejected, ...
    "hour2_numeric_rank",h2.schur_rank, ...
    "hour2_condition_2",h2.schur_condition_2, ...
    "hour2_smin_to_rank_tolerance", ...
        h2.schur_smin/h2.rank_tolerance, ...
    "hour3_numeric_rank",h3.schur_rank, ...
    "hour3_dimension",h3.dimension, ...
    "hour3_condition_2",h3.schur_condition_2, ...
    "hour3_smax",h3.schur_smax, ...
    "hour3_smin",h3.schur_smin, ...
    "hour3_rank_tolerance",h3.rank_tolerance, ...
    "hour3_singular_values_below_rank_tolerance", ...
        h3.singular_values_below_rank_tolerance, ...
    "hour3_inertia_zero_by_current_gate",h3.inertia_zero, ...
    "high_precision_digits",result.high_precision.digits, ...
    "high_precision_s3_smin",result.high_precision.s3_smin, ...
    "high_precision_s3_condition_2", ...
        result.high_precision.s3_condition_2, ...
    "high_precision_full_rank", ...
        result.high_precision.s3_high_precision_full_rank, ...
    "scaled_counterfactual_passes",scaled.pass, ...
    "scaled_counterfactual_rank",scaled.numeric_rank, ...
    "scaled_counterfactual_condition_2",scaled.condition_2, ...
    "condition_reduction_factor", ...
        result.root_cause.condition_reduction_factor, ...
    "full_kkt_dimension",result.full_kkt_audit.dimension, ...
    "full_kkt_relative_residual", ...
        result.full_kkt_audit.relative_residual, ...
    "full_kkt_direction_consumed", ...
        result.full_kkt_audit.direction_consumed, ...
    "state_update_count",0, ...
    "repair_applied",false, ...
    "recommended_next_milestone", ...
        "A4 local symmetric diagonal congruence factorization stress gate");
end

function manifest = make_matrix_manifest(root,pathValue,matrixData)
names = string(fieldnames(matrixData));
sha = string(rkkt.data.compute_sha256_file(pathValue));
rows = zeros(numel(names),1);
columns = zeros(numel(names),1);
nonzeros = zeros(numel(names),1);
for k=1:numel(names)
    value = matrixData.(names(k));
    rows(k)=size(value,1);
    columns(k)=size(value,2);
    nonzeros(k)=nnz(value);
end
relative = replace(string(pathValue),string(root)+filesep,"");
manifest = table(names,repmat(relative,numel(names),1), ...
    rows,columns,nonzeros,repmat(sha,numel(names),1), ...
    repmat("diagnostic_only_not_consumed_by_formal_solver", ...
        numel(names),1), ...
    'VariableNames',{'matrix_name','relative_path','rows','columns', ...
        'nnz','sha256','role'});
end

function acceptance = make_acceptance(result,context)
h3 = result.block_summary(result.block_summary.hour==3,:);
scaled = result.scaling_trace(end,:);
ids = [ ...
    "A4-I24-ID-001"; ...
    "A4-I24-REPLAY-001"; ...
    "A4-I24-RANK-001"; ...
    "A4-I24-SCALE-001"; ...
    "A4-I24-GOV-001"];
names = [ ...
    "权威状态和线性化指纹复现"; ...
    "第24轮day14/hour3生产失败复现"; ...
    "80位重算排除冻结系数上的结构真奇异"; ...
    "只读合同尺度反事实恢复22维数值秩"; ...
    "无状态更新、无回退且冻结资料不变"];
actual = [ ...
    result.state_fingerprint+" / "+result.linearization_fingerprint; ...
    result.replay_failure.layer+" rank="+result.replay_failure.rank; ...
    "smin="+format_number(result.high_precision.s3_smin); ...
    "rank="+scaled.numeric_rank+" cond2="+ ...
        format_number(scaled.condition_2); ...
    "state_update_count=0; protected="+ ...
        string(result.protected_file_audit.all_pass)];
contracts = [ ...
    "逐位等于权威checkpoint"; ...
    "layer=day_14_block_ldl_thomas, rank=17"; ...
    "80位最小绝对特征值明确非零"; ...
    "rank=22，且只读诊断不进入正式方向"; ...
    "CURRENT_STAGE=stage_A4/READY，无正式A4 run"];
status = repmat("PASS",5,1);
blocking = true(5,1);
evidence = [ ...
    "diagnostics/replay_identity.json"; ...
    "diagnostics/block_summary.csv"; ...
    "diagnostics/diagnostic_summary.json"; ...
    "diagnostics/scaling_trace.csv"; ...
    "diagnostics/protected_file_audit.csv"];
acceptance = table( ...
    repmat(string(context.run_id),5,1),ids,names,blocking, ...
    status,actual,contracts,evidence, ...
    'VariableNames',{'run_id','test_id','test_name','blocking', ...
        'status','actual','contract','evidence'});
assert(all(acceptance.status=="PASS") && height(acceptance)==5 && ...
    h3.schur_rank==17, ...
    "stageA4:iter24:AcceptanceConstruction", ...
    "The diagnostic acceptance facts are inconsistent.");
end

function issues = make_issue_log(result,context)
issues = table( ...
    string(context.run_id), ...
    "A4-I24-NUMERIC-001", ...
    "OPEN",true, ...
    "recursive_linear_algebra", ...
    "day_14_block_ldl_thomas/hour_3_schur_pivot", ...
    "22维主元高精度满秩，但未尺度化双精度谱宽约4.07e14，"+ ...
        "默认rank和零主元阈值分别将5个及3个非零方向判零。", ...
    result.root_cause.recommendation, ...
    "该问题继续阻断Stage A4；本次只完成根因判定，未实施修复。", ...
    'VariableNames',{'run_id','issue_id','status','blocks_stage_a4', ...
        'category','first_failure_layer','description', ...
        'recommended_action','boundary'});
end

function value = format_number(number)
value = string(sprintf("%.17g",number));
end

function assert_targets_absent(paths)
for k=1:numel(paths)
    assert(~isfile(paths(k)) && ~isfolder(paths(k)), ...
        "stageA4:iter24:ArtifactExists", ...
        "Refusing to overwrite diagnostic artifact %s.",paths(k));
end
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message]=mkdir(pathValue);
assert(created,"stageA4:iter24:DirectoryCreate", ...
    "Could not create %s: %s",pathValue,message);
end

function write_text(pathValue,textValue)
fid=fopen(pathValue,"wb");
assert(fid>=0,"stageA4:iter24:TextOpen", ...
    "Could not open %s for writing.",pathValue);
guard=onCleanup(@()close_if_open(fid));
bytes=unicode2native(char(string(textValue)),"UTF-8");
count=fwrite(fid,bytes,"uint8");
assert(count==numel(bytes),"stageA4:iter24:TextWrite", ...
    "Incomplete write to %s.",pathValue);
clear guard;
end

function close_if_open(fid)
fclose(fid);
end
