function [checkpoint,record] = load_stage_b2c_checkpoint(context,revision,options)
%LOAD_STAGE_B2C_CHECKPOINT Load and independently validate one checkpoint.

arguments
    context (1,1) struct
    revision (1,1) double = NaN
    options.ExpectedMetadata (1,1) struct = struct()
    options.RebuiltLinearizationFingerprint (1,1) string = ""
end
assert(isnan(revision) || (revision>=0 && revision==fix(revision)), ...
    "stageB2C:checkpoint:Revision", ...
    "Checkpoint revision must be a nonnegative integer or NaN for latest.");
assert(isfile(context.checkpoint_manifest_path), ...
    "stageB2C:checkpoint:ManifestMissing", ...
    "The B-2C checkpoint manifest is missing.");
manifest = readtable(context.checkpoint_manifest_path, ...
    "TextType","string","VariableNamingRule","preserve");
assert(~isempty(manifest) && ...
    isequal(double(manifest.iteration),(0:height(manifest)-1).'), ...
    "stageB2C:checkpoint:ManifestSequence", ...
    "The B-2C checkpoint manifest is not contiguous.");
if isnan(revision)
    revision = double(manifest.iteration(end));
end
validate_manifest_chain(context,manifest,revision);
row = find(double(manifest.iteration)==revision,1);
assert(~isempty(row),"stageB2C:checkpoint:RevisionMissing", ...
    "Checkpoint revision %d is not recorded.",revision);
record = manifest(row,:);
pathValue = fullfile(context.checkpoints_dir,record.relative_path);
assert(isfile(pathValue) && ...
    lower(string(rkkt.data.compute_sha256_file(pathValue)))== ...
        lower(string(record.sha256)), ...
    "stageB2C:checkpoint:Hash", ...
    "Checkpoint revision %d is missing or failed SHA256.",revision);
loaded = load(pathValue,"checkpoint");
assert(isfield(loaded,"checkpoint") && ...
    isfield(loaded.checkpoint,"state") && ...
    isfield(loaded.checkpoint,"metadata"), ...
    "stageB2C:checkpoint:Schema", ...
    "Checkpoint revision %d has an invalid schema.",revision);
checkpoint = loaded.checkpoint;
actualState = rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint( ...
    checkpoint.state);
assert(actualState==string(record.state_fingerprint) && ...
    string(checkpoint.metadata.state_fingerprint)==actualState && ...
    double(checkpoint.state.state_revision)==revision && ...
    double(checkpoint.metadata.iteration)==revision, ...
    "stageB2C:checkpoint:State", ...
    "Checkpoint revision %d state identity failed.",revision);
if revision==0
    expectedPrevious = "GENESIS";
else
    expectedPrevious = string(manifest.sha256(row-1));
end
assert(string(record.previous_checkpoint_sha256)==expectedPrevious && ...
    string(checkpoint.metadata.previous_checkpoint_sha256)== ...
        expectedPrevious, ...
    "stageB2C:checkpoint:Chain", ...
    "Checkpoint revision %d hash-chain predecessor failed.",revision);
validate_expected_metadata(checkpoint.metadata,record, ...
    options.ExpectedMetadata,revision);
if strlength(options.RebuiltLinearizationFingerprint)>0
    assert(lower(string(record.linearization_fingerprint))== ...
        lower(options.RebuiltLinearizationFingerprint) && ...
        lower(string(checkpoint.metadata.linearization_fingerprint))== ...
        lower(options.RebuiltLinearizationFingerprint), ...
        "stageB2C:checkpoint:RebuiltLinearization", ...
        "Checkpoint revision %d does not match the rebuilt linearization.", ...
        revision);
end
end

function validate_manifest_chain(context,manifest,revision)
previous = "GENESIS";
for row = 1:revision+1
    pathValue = fullfile(context.checkpoints_dir,manifest.relative_path(row));
    assert(isfile(pathValue) && ...
        lower(string(rkkt.data.compute_sha256_file(pathValue)))== ...
            lower(string(manifest.sha256(row))), ...
        "stageB2C:checkpoint:Hash", ...
        "Checkpoint revision %d is missing or failed SHA256.",row-1);
    assert(string(manifest.previous_checkpoint_sha256(row))==previous, ...
        "stageB2C:checkpoint:Chain", ...
        "Checkpoint revision %d has an invalid predecessor.",row-1);
    loaded = load(pathValue,"checkpoint");
    assert(isfield(loaded,"checkpoint") && ...
        isfield(loaded.checkpoint,"state") && ...
        isfield(loaded.checkpoint,"metadata"), ...
        "stageB2C:checkpoint:Schema", ...
        "Checkpoint revision %d has an invalid schema.",row-1);
    assert(isfield(loaded.checkpoint.metadata, ...
        "linearization_fingerprint"), ...
        "stageB2C:checkpoint:Schema", ...
        "Checkpoint revision %d is missing its linearization identity.", ...
        row-1);
    checkpointLinearization = string( ...
        loaded.checkpoint.metadata.linearization_fingerprint);
    assert(lower(string(manifest.linearization_fingerprint(row)))== ...
        lower(checkpointLinearization), ...
        "stageB2C:checkpoint:Linearization", ...
        "Checkpoint revision %d failed its recorded linearization identity.", ...
        row-1);
    stateFingerprint = ...
        rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint( ...
        loaded.checkpoint.state);
    assert(double(loaded.checkpoint.state.state_revision)==row-1 && ...
        double(loaded.checkpoint.metadata.iteration)==row-1 && ...
        lower(string(manifest.state_fingerprint(row)))== ...
            lower(stateFingerprint) && ...
        lower(string(loaded.checkpoint.metadata.state_fingerprint))== ...
            lower(stateFingerprint) && ...
        string(loaded.checkpoint.metadata.previous_checkpoint_sha256)== ...
            previous, ...
        "stageB2C:checkpoint:State", ...
        "Checkpoint revision %d failed its recorded state identity.",row-1);
    previous = string(manifest.sha256(row));
end
end

function validate_expected_metadata(metadata,record,expected,revision)
if isempty(fieldnames(expected))
    return
end
names = string(fieldnames(expected));
for name = names.'
    assert(isfield(metadata,char(name)), ...
        "stageB2C:checkpoint:ExpectedMetadata", ...
        "Checkpoint revision %d is missing expected metadata %s.", ...
        revision,name);
    actual = string(metadata.(name));
    target = string(expected.(name));
    assert(isequal(lower(actual),lower(target)), ...
        "stageB2C:checkpoint:ExpectedMetadata", ...
        "Checkpoint revision %d metadata %s does not match.",revision,name);
end
for name = ["git_commit","config_sha256","input_hash_fingerprint"]
    if isfield(expected,char(name))
        assert(lower(string(record.(name)))==lower(string(expected.(name))), ...
            "stageB2C:checkpoint:ExpectedMetadata", ...
            "Checkpoint manifest metadata %s does not match.",name);
    end
end
end
