function manifest = mark_stage_a1_solver_execution(runContext)
%MARK_STAGE_A1_SOLVER_EXECUTION Record the one permitted solver attempt.
% This is a one-way RUNNING-state transition from false to true. It exists
% because execution truth is not known when the immutable run identity is
% initialized.

arguments
    runContext (1,1) struct
end
pathValue = runContext.run_manifest_path;
assert(isfile(pathValue),"stageA1:artifacts:ManifestMissing", ...
    "Run manifest is missing.");
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A1" && string(manifest.status)=="RUNNING", ...
    "stageA1:artifacts:ManifestIdentity", ...
    "Only the matching RUNNING Stage A1 manifest can record execution.");
assert(isfield(manifest,"a1_solver_executed") && ...
    ~logical(manifest.a1_solver_executed), ...
    "stageA1:artifacts:SolverExecutionAlreadyMarked", ...
    "Stage A1 solver execution was already recorded.");
assert(isfield(manifest,"newton_direction_count") && ...
    double(manifest.newton_direction_count)==1 && ...
    ~logical(manifest.full_ipm_executed) && ...
    ~logical(manifest.parallel_executed), ...
    "stageA1:artifacts:ExecutionScope", ...
    "Manifest scope must permit one serial direction and no full IPM.");
manifest.a1_solver_executed = true;
manifest.solver_execution_started_at = char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
rkkt.artifacts.write_json_file(pathValue,manifest);
end
