function metadata = normalize_stage_a4_checkpoint_metadata(value)
%NORMALIZE_STAGE_A4_CHECKPOINT_METADATA Validate the immutable payload.

required = ["iteration","state_revision","input_hashes", ...
    "config_sha256","git_commit","linearization_fingerprint", ...
    "state_fingerprint","iteration_csv_sha256", ...
    "direction_csv_sha256","refinement_csv_sha256", ...
    "initial_state_fingerprint","recursive_refinement_max_passes"];
assert(isstruct(value) && isscalar(value) && ...
    all(isfield(value,cellstr(required))), ...
    "stageA4:checkpoint:MetadataFields", ...
    "Checkpoint metadata is missing one or more required identity fields.");

metadata = struct();
metadata.iteration = integer_scalar(value.iteration,"iteration");
metadata.state_revision = integer_scalar( ...
    value.state_revision,"state_revision");
assert(metadata.iteration==metadata.state_revision, ...
    "stageA4:checkpoint:MetadataRevisionMismatch", ...
    "metadata.iteration and metadata.state_revision must be identical.");
[metadata.input_hashes_sha256,metadata.input_hashes] = ...
    rkkt.artifacts.compute_stage_a4_checkpoint_input_fingerprint(value.input_hashes);
metadata.config_sha256 = sha256_text(value.config_sha256,"config_sha256");
metadata.git_commit = git_commit_text(value.git_commit);
metadata.linearization_fingerprint = sha256_text( ...
    value.linearization_fingerprint,"linearization_fingerprint");
metadata.state_fingerprint = sha256_text( ...
    value.state_fingerprint,"state_fingerprint");
metadata.initial_state_fingerprint = sha256_text( ...
    value.initial_state_fingerprint,"initial_state_fingerprint");
metadata.recursive_refinement_max_passes = integer_scalar( ...
    value.recursive_refinement_max_passes, ...
    "recursive_refinement_max_passes");
assert(metadata.recursive_refinement_max_passes==3, ...
    "stageA4:checkpoint:StableV2Passes", ...
    "A4-3 checkpoints require stable-v2 MaxPasses=3.");

metadata.iteration_csv_sha256 = sha256_text( ...
    value.iteration_csv_sha256,"iteration_csv_sha256");
metadata.direction_csv_sha256 = sha256_text( ...
    value.direction_csv_sha256,"direction_csv_sha256");
metadata.refinement_csv_sha256 = sha256_text( ...
    value.refinement_csv_sha256,"refinement_csv_sha256");

metadata.solve_pass = optional_text(value,"solve_pass","first");
metadata.model_contract_version = optional_text( ...
    value,"model_contract_version","v1.0");
metadata.index_contract_version = optional_text( ...
    value,"index_contract_version","NOT_PROVIDED");
metadata.solver_version = optional_text( ...
    value,"solver_version","stable-v2-maxpasses-3");
end

function value = integer_scalar(value,label)
assert(isa(value,"double") && isreal(value) && isscalar(value) && ...
    isfinite(value) && value>=0 && value==fix(value), ...
    "stageA4:checkpoint:MetadataInteger", ...
    "metadata.%s must be a finite nonnegative integer double.",label);
end

function value = sha256_text(value,label)
value = lower(strip(text_scalar(value,label)));
assert(~isempty(regexp(char(value),"^[0-9a-f]{64}$","once")), ... %#ok<RGXP1>
    "stageA4:checkpoint:MetadataSha256", ...
    "metadata.%s must be a 64-character SHA256 value.",label);
end

function value = git_commit_text(value)
value = lower(strip(text_scalar(value,"git_commit")));
assert(~isempty(regexp(char(value),"^[0-9a-f]{40}$","once")), ... %#ok<RGXP1>
    "stageA4:checkpoint:GitCommit", ...
    "metadata.git_commit must be a full 40-character Git commit.");
end

function value = optional_text(source,name,defaultValue)
if isfield(source,name)
    value = strip(text_scalar(source.(name),name));
else
    value = string(defaultValue);
end
end

function value = text_scalar(value,label)
assert(ischar(value) || (isstring(value) && isscalar(value)), ...
    "stageA4:checkpoint:MetadataText", ...
    "metadata.%s must be a text scalar.",label);
value = string(value);
assert(strlength(strip(value))>0, ...
    "stageA4:checkpoint:MetadataText", ...
    "metadata.%s must not be empty.",label);
end
