function [context,manifest] = open_existing_run_context( ...
        projectRoot,runDirectory,expectedStageId)
%OPEN_EXISTING_RUN_CONTEXT Open one explicitly named active run directory.

arguments
    projectRoot (1,1) string
    runDirectory (1,1) string
    expectedStageId (1,1) string
end
projectRoot = canonical_path(projectRoot);
runsRoot = canonical_path(fullfile(projectRoot,"runs"));
assert(isfolder(runsRoot),"rkkt:runs:ResumeDirectoryMissing", ...
    "The project runs directory does not exist: %s",runsRoot);
assert(isfolder(runDirectory),"rkkt:runs:ResumeDirectoryMissing", ...
    "The explicitly supplied run directory does not exist: %s",runDirectory);
runRoot = canonical_path(runDirectory);
[parent,runId] = fileparts(runRoot);
assert(strcmpi(char(canonical_path(parent)),char(runsRoot)), ...
    "rkkt:runs:ResumeDirectoryScope", ...
    "ResumeRunDirectory must be one direct runs/<run_id> directory.");

context = build_context(projectRoot,runsRoot,runRoot,string(runId), ...
    expectedStageId);
requiredDirectories = string({context.iterations_dir;context.indices_dir; ...
    context.matrices_dir;context.checkpoints_dir;context.tests_dir; ...
    context.issues_dir;context.acceptance_dir;context.reports_dir});
assert(all(arrayfun(@(pathValue)isfolder(pathValue),requiredDirectories)), ...
    "rkkt:runs:ResumeDirectorySchema", ...
    "The supplied run directory is missing a standard artifact directory.");
assert(isfile(context.run_manifest_path) && ...
    isfile(context.effective_config_path), ...
    "rkkt:runs:ResumeIdentityMissing", ...
    "The supplied run directory is missing its manifest or effective config.");
manifest = jsondecode(fileread(context.run_manifest_path));
assert(isfield(manifest,"run_id") && ...
    string(manifest.run_id)==string(runId) && ...
    isfield(manifest,"stage_id") && ...
    string(manifest.stage_id)==expectedStageId, ...
    "rkkt:runs:ResumeIdentityMismatch", ...
    "The supplied run directory does not match its persisted run identity.");
assert(isfield(manifest,"status") && string(manifest.status)=="RUNNING", ...
    "rkkt:runs:ResumeRunNotActive", ...
    "Only the original RUNNING run can be resumed.");
end

function context = build_context(projectRoot,runsRoot,runRoot,runId,stageId)
context = struct();
context.project_root = char(projectRoot);
context.runs_root = char(runsRoot);
context.root = char(runRoot);
context.run_dir = char(runRoot);
context.run_id = char(runId);
context.stage_id = char(stageId);
context.iterations_dir = fullfile(runRoot,"iterations");
context.indices_dir = fullfile(runRoot,"indices");
context.matrices_dir = fullfile(runRoot,"matrices");
context.checkpoints_dir = fullfile(runRoot,"checkpoints");
context.tests_dir = fullfile(runRoot,"tests");
context.issues_dir = fullfile(runRoot,"issues");
context.acceptance_dir = fullfile(runRoot,"acceptance");
context.reports_dir = fullfile(runRoot,"reports");
context.run_manifest_path = fullfile(runRoot,"run_manifest.json");
context.environment_csv_path = fullfile(runRoot,"environment.csv");
context.input_hashes_csv_path = fullfile(runRoot,"input_hashes.csv");
context.effective_config_path = fullfile(runRoot,"effective_config.yaml");
context.git_state_path = fullfile(runRoot,"git_state.txt");
context.matrix_manifest_path = fullfile(context.matrices_dir, ...
    "matrix_manifest.csv");
context.checkpoint_manifest_path = fullfile(context.checkpoints_dir, ...
    "checkpoint_manifest.csv");
context.test_inventory_path = fullfile(context.tests_dir,"test_inventory.csv");
context.test_results_csv_path = fullfile(context.tests_dir,"test_results.csv");
context.test_results_xml_path = fullfile(context.tests_dir,"test_results.xml");
context.test_console_log_path = fullfile(context.tests_dir, ...
    "matlab_test_console.log");
context.test_command_path = fullfile(context.tests_dir,"test_command.txt");
context.test_summary_path = fullfile(context.tests_dir,"test_summary.json");
context.test_evidence_manifest_path = fullfile(context.tests_dir, ...
    "test_evidence_manifest.csv");
context.issue_log_path = fullfile(context.issues_dir,"issue_log.csv");
context.decision_log_path = fullfile(context.issues_dir,"decision_log.csv");
context.acceptance_results_path = fullfile(context.acceptance_dir, ...
    "acceptance_results.csv");
context.paths = struct("run_manifest",context.run_manifest_path, ...
    "environment",context.environment_csv_path, ...
    "input_hashes",context.input_hashes_csv_path, ...
    "effective_config",context.effective_config_path, ...
    "git_state",context.git_state_path,"iterations",context.iterations_dir, ...
    "indices",context.indices_dir,"matrices",context.matrices_dir, ...
    "checkpoints",context.checkpoints_dir,"tests",context.tests_dir, ...
    "issues",context.issues_dir,"acceptance",context.acceptance_dir, ...
    "reports",context.reports_dir);
end

function value = canonical_path(pathValue)
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end
