function persist_stage_b2c_recursive_structure_artifacts( ...
        context,structure,numericalPayload)
%PERSIST_STAGE_B2C_RECURSIVE_STRUCTURE_ARTIFACTS Save compact route evidence.

arguments
    context (1,1) struct
    structure (1,1) struct
    numericalPayload (1,1) struct
end

summary = struct( ...
    "structure_version",char(structure.version), ...
    "numerical_payload_version",char(numericalPayload.version), ...
    "runtime_version",char(structure.runtime.version), ...
    "topology_fingerprint",char(structure.topology_fingerprint), ...
    "days",double(structure.scope.days), ...
    "hours",double(structure.scope.hours), ...
    "counts",structure.counts, ...
    "canonical_index_embedded",false, ...
    "variable_index_embedded",false, ...
    "constraint_index_embedded",false, ...
    "stage_a_base_index_embedded",false, ...
    "numerical_payload_cached",false);
rkkt.artifacts.write_json_file(fullfile(context.indices_dir, ...
    "recursive_structure_summary.json"),summary);
runtime = structure.runtime;
rkkt.artifacts.save_mat_artifact(fullfile(context.indices_dir, ...
    "recursive_structure_maps.mat"),"runtime",runtime);
end
