function persist_stage_b2c_recursive_runtime_artifacts(context,runtimePackage)
%PERSIST_STAGE_B2C_RECURSIVE_RUNTIME_ARTIFACTS Save compact index evidence.

arguments
    context (1,1) struct
    runtimePackage (1,1) struct
end
runtime = runtimePackage.runtime;
summary = struct("version",char(runtimePackage.version), ...
    "runtime_version",char(runtime.version), ...
    "days",double(runtime.scope.days),"hours",double(runtime.scope.hours), ...
    "counts",runtime.counts,"canonical_index_embedded",false, ...
    "variable_index_embedded",false,"constraint_index_embedded",false, ...
    "stage_a_base_index_embedded",false);
rkkt.artifacts.write_json_file(fullfile(context.indices_dir, ...
    "recursive_runtime_summary.json"),summary);
rkkt.artifacts.save_mat_artifact(fullfile(context.indices_dir, ...
    "recursive_runtime_maps.mat"),"runtime",runtime);
end
