function [context,manifest,resumed] = prepare_stage_b2c_configured_run( ...
        projectRoot,settings,config,inputHashes,codeSignature,options)
%PREPARE_STAGE_B2C_CONFIGURED_RUN Create or reopen one unified run.

arguments
    projectRoot (1,1) string
    settings (1,1) struct
    config (1,1) struct
    inputHashes table
    codeSignature (1,1) string
    options.RunId (1,1) string = ""
    options.ResumeRunDirectory (1,1) string = ""
    options.ActualTestCommand (1,1) string = "RUN_PROJECT.m"
end
resumed = strlength(strip(options.ResumeRunDirectory))>0;
explicitDaySet = isfield(settings,"explicit_day_set") && ...
    isscalar(settings.explicit_day_set) && ...
    logical(settings.explicit_day_set);
inputObject = input_hash_object(inputHashes);
if ~resumed
    metadata = struct( ...
        "run_purpose",char(config.run_purpose), ...
        "milestone","B-2C-CONFIGURED-RANGE", ...
        "actual_test_command",char(options.ActualTestCommand), ...
        "optimization_executed",true,"a1_solver_executed",false, ...
        "day_scope",char(settings.day_scope), ...
        "day_start",settings.day_start,"day_end",settings.day_end, ...
        "day_count",numel(settings.days), ...
        "day_sequence",settings.days, ...
        "excluded_days",settings.excluded_days, ...
        "explicit_day_set",explicitDaySet, ...
        "max_iterations",settings.max_iterations, ...
        "require_convergence",settings.require_convergence, ...
        "audit_mode",char(settings.audit_mode), ...
        "core_consistency_max_passes", ...
            settings.core_consistency_max_passes, ...
        "compensated_core_accumulation", ...
            settings.compensated_core_accumulation, ...
        "full_kkt_role",char(config.full_kkt_role), ...
        "full_kkt_audit_executed",false, ...
        "recursive_direction_executed",true, ...
        "reconstructed_kkt_residual_gate_enabled",true, ...
        "checkpoint_after_each_accepted_update",true, ...
        "checkpoint_solver_code_signature",char(codeSignature), ...
        "resume_supported",settings.audit_mode=="recursive_only", ...
        "resume_count",0,"parallel_executed",false, ...
        "thermal_second_pass_executed",false, ...
        "stage_c1_implemented",false,"stage_c1_entered",false, ...
        "formal_stage_b_acceptance_unchanged",true, ...
        "milestone_status","RUNNING");
    context = rkkt.artifacts.create_run_context(projectRoot,"stage_B", ...
        "RunId",options.RunId,"ModelContractVersion","v1.0", ...
        "InputHashes",inputObject, ...
        "EffectiveConfigPath",settings.config_path, ...
        "ManifestMetadata",metadata);
    manifest = jsondecode(fileread(context.run_manifest_path));
    return
end

assert(settings.audit_mode=="recursive_only", ...
    "stageB2C:configured:ResumeMode", ...
    "Only recursive_only configured runs can be resumed.");
[context,manifest] = rkkt.artifacts.open_existing_run_context( ...
    projectRoot,options.ResumeRunDirectory,"stage_B");
required = ["milestone","day_start","day_end","audit_mode", ...
    "max_iterations","require_convergence", ...
    "core_consistency_max_passes", ...
    "compensated_core_accumulation", ...
    "checkpoint_solver_code_signature","resume_supported"];
identityMatches = all(isfield(manifest,cellstr(required))) && ...
    string(manifest.milestone)=="B-2C-CONFIGURED-RANGE" && ...
    double(manifest.day_start)==settings.day_start && ...
    double(manifest.day_end)==settings.day_end && ...
    (~explicitDaySet || ...
        (isfield(manifest,"explicit_day_set") && ...
        logical(manifest.explicit_day_set) && ...
        isfield(manifest,"day_sequence") && ...
        isequal(reshape(double(manifest.day_sequence),1,[]), ...
            settings.days))) && ...
    double(manifest.max_iterations)==settings.max_iterations && ...
    logical(manifest.require_convergence)==settings.require_convergence && ...
    string(manifest.audit_mode)==settings.audit_mode && ...
    double(manifest.core_consistency_max_passes)== ...
        settings.core_consistency_max_passes && ...
    logical(manifest.compensated_core_accumulation)== ...
        settings.compensated_core_accumulation && ...
    lower(string(manifest.checkpoint_solver_code_signature))== ...
        lower(codeSignature) && logical(manifest.resume_supported) && ...
    isequal(manifest.input_hashes,inputObject);
assert(identityMatches,"stageB2C:configured:ResumeIdentity", ...
    "The selected RUNNING directory is not the same configured numerical run.");
assert(isfile(context.checkpoint_manifest_path), ...
    "stageB2C:configured:ResumeCheckpoint", ...
    "The selected run has no accepted-state checkpoint chain.");
end

function value = input_hash_object(hashes)
base = hashes.fileName=="基础参数.xlsx";
series = hashes.fileName=="输入数据.xlsx";
assert(nnz(base)==1 && nnz(series)==1, ...
    "stageB2C:configured:InputHashRows", ...
    "Both controlled input rows are required.");
value = struct("base_parameters",char(hashes.actualSHA256(base)), ...
    "timeseries",char(hashes.actualSHA256(series)));
end
