function [context,manifest,resumed] = prepare_stage_b2c_365day_run( ...
        projectRoot,config,inputHashes,codeSignature,options)
%PREPARE_STAGE_B2C_365DAY_RUN Create or validate one resumable 365-day run.

arguments
    projectRoot (1,1) string
    config (1,1) struct
    inputHashes table
    codeSignature (1,1) string
    options.RunId (1,1) string = ""
    options.ResumeRunDirectory (1,1) string = ""
    options.RequireConvergence (1,1) logical = true
end
resumeDirectory = strip(options.ResumeRunDirectory);
resumed = strlength(resumeDirectory)>0;
assert(~resumed || strlength(strip(options.RunId))==0, ...
    "stageB2C:day365:ResumeRunIdConflict", ...
    "Do not supply RunId when resuming an explicitly named run directory.");
configPath = fullfile(projectRoot,"config", ...
    "stage_B_2C_365_day_serial_experiment.yaml");
inputObject = input_hash_object(inputHashes);
mode = "convergence_run";
if ~options.RequireConvergence
    mode = "bounded_smoke_run";
end

if ~resumed
    metadata = struct( ...
        "run_purpose",char(config.run_purpose), ...
        "milestone","B-2C-365-DAY-SERIAL-SUPPLEMENT", ...
        "parent_run_id",char(config.parent_run_id), ...
        "actual_test_command", ...
            "rkkt.workflows.stageB2C365DaySerialExperiment", ...
        "experiment_mode",char(mode), ...
        "checkpoint_solver_code_signature",char(codeSignature), ...
        "optimization_executed",true,"a1_solver_executed",false, ...
        "full_ipm_executed",true,"convergence_evaluated",true, ...
        "convergence_required",options.RequireConvergence, ...
        "convergence_achieved",false, ...
        "time_scope","days_1_to_365_full_24_hours", ...
        "full_kkt_role",char(config.full_kkt_role), ...
        "full_kkt_assembled",false,"full_kkt_solved",false, ...
        "full_kkt_audit_executed",false, ...
        "recursive_direction_executed",true, ...
        "reconstructed_kkt_residual_gate_enabled",true, ...
        "recursive_refinement_max_passes", ...
            config.recursive_refinement_max_passes, ...
        "water_slack_second_order_correction_enabled",true, ...
        "water_slack_second_order_correction_scope_count", ...
            config.expected_water_inequality_count, ...
        "no_full_direction_fallback",true, ...
        "checkpoint_after_each_accepted_update",true, ...
        "resume_supported",true,"resume_count",0, ...
        "parallel_executed",false,"annual_aggregate_executed",false, ...
        "thermal_second_pass_executed",false, ...
        "stage_c1_implemented",false,"stage_c1_entered",false, ...
        "formal_stage_b_acceptance_unchanged",true, ...
        "expected_primal_dimension",config.expected_stage_a_primal_dimension, ...
        "expected_equality_dimension", ...
            config.expected_stage_a_equality_dimension, ...
        "expected_inequality_dimension", ...
            config.expected_stage_a_inequality_dimension+ ...
            config.expected_water_inequality_count, ...
        "expected_reconstructed_full_kkt_dimension", ...
            config.expected_full_kkt_dimension, ...
        "milestone_status","RUNNING");
    context = rkkt.artifacts.create_run_context(projectRoot,"stage_B", ...
        "RunId",options.RunId,"ModelContractVersion","v1.0", ...
        "InputHashes",inputObject,"EffectiveConfigPath",configPath, ...
        "ManifestMetadata",metadata);
    manifest = jsondecode(fileread(context.run_manifest_path));
    return
end

[context,manifest] = rkkt.artifacts.open_existing_run_context( ...
    projectRoot,resumeDirectory,"stage_B");
required = ["run_purpose","milestone","checkpoint_solver_code_signature", ...
    "time_scope","full_kkt_role","resume_supported", ...
    "experiment_mode","convergence_required"];
identityMatches = all(isfield(manifest,cellstr(required))) && ...
    string(manifest.run_purpose)==config.run_purpose && ...
    string(manifest.milestone)=="B-2C-365-DAY-SERIAL-SUPPLEMENT" && ...
    lower(string(manifest.checkpoint_solver_code_signature))==lower(codeSignature) && ...
    string(manifest.time_scope)=="days_1_to_365_full_24_hours" && ...
    string(manifest.full_kkt_role)==config.full_kkt_role && ...
    logical(manifest.resume_supported) && ...
    string(manifest.experiment_mode)==mode && ...
    logical(manifest.convergence_required)==options.RequireConvergence;
if ~identityMatches
    error('stageB2C:day365:ResumeIdentity', ...
        'The supplied active run is not the same 365-day numerical workflow.');
end
configMatches = lower(string(rkkt.data.compute_sha256_file( ...
        context.effective_config_path)))==lower(string( ...
        rkkt.data.compute_sha256_file(configPath)));
if ~configMatches
    error('stageB2C:day365:ResumeConfig', ...
        'The original run effective configuration does not match current config.');
end
persistedInput = jsonencode(manifest.input_hashes);
if ~isequal(jsondecode(persistedInput),inputObject)
    error('stageB2C:day365:ResumeInput', ...
        'The controlled inputs do not match the original run identity.');
end
if ~isfile(context.checkpoint_manifest_path)
    error('stageB2C:day365:ResumeCheckpoint', ...
        'The original run has no accepted-state checkpoint chain.');
end
end

function value = input_hash_object(hashes)
base = hashes.fileName=="基础参数.xlsx";
series = hashes.fileName=="输入数据.xlsx";
assert(nnz(base)==1 && nnz(series)==1, ...
    "stageB2C:day365:InputHashRows", ...
    "Both controlled input rows are required.");
value = struct("base_parameters",char(hashes.actualSHA256(base)), ...
    "timeseries",char(hashes.actualSHA256(series)));
end
