function manifest = record_stage_a1_test_command(runContext,testCommand)
%RECORD_STAGE_A1_TEST_COMMAND Replace the one A1 run-context placeholder.

arguments
    runContext (1,1) struct
    testCommand (1,1) string
end
assert(strlength(strip(testCommand))>0, ...
    "stageA1:artifacts:EmptyTestCommand", ...
    "The actual Stage A1 test command must not be empty.");
pathValue = runContext.run_manifest_path;
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A1" && string(manifest.status)=="RUNNING", ...
    "stageA1:artifacts:ManifestIdentity", ...
    "Only the matching RUNNING Stage A1 manifest can record a test command.");
assert(isfield(manifest,"actual_test_command") && ...
    string(manifest.actual_test_command)=="NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK", ...
    "stageA1:artifacts:TestCommandAlreadyRecorded", ...
    "The actual Stage A1 test command was already recorded.");
manifest.actual_test_command = char(testCommand);
manifest.test_command_recorded_at = char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
rkkt.artifacts.write_json_file(pathValue,manifest);
end
