function manifest = record_stage_a2_test_command(runContext,a2Command,a1Command)
%RECORD_STAGE_A2_TEST_COMMAND Persist both actually executed fixed commands.

arguments
    runContext (1,1) struct
    a2Command (1,1) string
    a1Command (1,1) string
end
assert(strlength(strip(a2Command))>0 && strlength(strip(a1Command))>0, ...
    "stageA2:artifacts:EmptyTestCommand", ...
    "A2 and A1-regression test commands must both be nonempty.");
pathValue = runContext.run_manifest_path;
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A2" && string(manifest.status)=="RUNNING", ...
    "stageA2:artifacts:ManifestIdentity", ...
    "Only the matching RUNNING A2 manifest can record test commands.");
isInitial=isfield(manifest,"actual_test_command") && ...
    (ischar(manifest.actual_test_command) || ...
    (isstring(manifest.actual_test_command) && isscalar(manifest.actual_test_command))) && ...
    string(manifest.actual_test_command)=="NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK";
assert(isInitial, ...
    "stageA2:artifacts:TestCommandAlreadyRecorded", ...
    "A2 test commands were already recorded.");
manifest.actual_test_command = struct( ...
    "stage_a2",char(a2Command),"stage_a1_regression",char(a1Command));
manifest.test_command_recorded_at = char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
rkkt.artifacts.write_json_file(pathValue,manifest);
end
