function manifest = record_stage_a3_test_command(runContext,a3Command, ...
        a2Command,a1Command)
%RECORD_STAGE_A3_TEST_COMMAND Persist the three actually executed commands.

arguments
    runContext (1,1) struct
    a3Command (1,1) string
    a2Command (1,1) string
    a1Command (1,1) string
end
assert(all(strlength(strip([a3Command,a2Command,a1Command]))>0), ...
    "stageA3:artifacts:EmptyTestCommand", ...
    "A3, A2-regression, and A1-regression commands must be nonempty.");
pathValue=runContext.run_manifest_path;
manifest=jsondecode(fileread(pathValue));
assert(string(manifest.run_id)==string(runContext.run_id) && ...
    string(manifest.stage_id)=="stage_A3" && string(manifest.status)=="RUNNING", ...
    "stageA3:artifacts:ManifestIdentity", ...
    "Only the matching RUNNING A3 manifest can record test commands.");
isInitial=isfield(manifest,"actual_test_command") && ...
    (ischar(manifest.actual_test_command) || ...
    (isstring(manifest.actual_test_command) && isscalar(manifest.actual_test_command))) && ...
    string(manifest.actual_test_command)=="NOT_EXECUTED_EXTERNAL_OR_PRETEST_BLOCK";
assert(isInitial,"stageA3:artifacts:TestCommandAlreadyRecorded", ...
    "A3 test commands were already recorded.");
manifest.actual_test_command=struct("stage_a3",char(a3Command), ...
    "stage_a2_regression",char(a2Command), ...
    "stage_a1_regression",char(a1Command));
manifest.test_command_recorded_at=char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
rkkt.artifacts.write_json_file(pathValue,manifest);
end
