function record = write_stage_b2c_checkpoint( ...
        context,state,linearization,metadata)
%WRITE_STAGE_B2C_CHECKPOINT Persist one immutable accepted B-2C state.

arguments
    context (1,1) struct
    state (1,1) struct
    linearization (1,1) struct
    metadata (1,1) struct
end
assert(isfield(context,"checkpoints_dir") && ...
    isfield(context,"checkpoint_manifest_path") && ...
    isfolder(context.checkpoints_dir), ...
    "stageB2C:checkpoint:Context", ...
    "A valid B-2C checkpoint directory is required.");
if isfield(context,"run_manifest_path")
    manifestIdentity = jsondecode(fileread(context.run_manifest_path));
    assert(isfield(manifestIdentity,"status") && ...
        string(manifestIdentity.status)=="RUNNING", ...
        "stageB2C:checkpoint:RunNotRunning", ...
        "B-2C checkpoints can only be appended to a RUNNING run.");
end
revision = double(state.state_revision);
assert(revision>=0 && revision==fix(revision) && ...
    double(metadata.iteration)==revision, ...
    "stageB2C:checkpoint:Revision", ...
    "Checkpoint revision and metadata iteration must agree.");
stateFingerprint = rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(state);
linearizationFingerprint = rkkt.diagnostics.compute_stage_a4_rns1_fingerprint( ...
    linearization,"linearization");
fileName = "iteration_"+compose("%03d",revision)+".mat";
pathValue = fullfile(context.checkpoints_dir,fileName);

if isfile(context.checkpoint_manifest_path)
    manifest = readtable(context.checkpoint_manifest_path, ...
        "TextType","string","VariableNamingRule","preserve");
    assert(height(manifest)==revision && ...
        isequal(double(manifest.iteration),(0:revision-1).'), ...
        "stageB2C:checkpoint:ManifestSequence", ...
        "The existing checkpoint chain is not contiguous.");
    previousSha = string(manifest.sha256(end));
else
    assert(revision==0,"stageB2C:checkpoint:InitialMissing", ...
        "Checkpoint revision zero must start the chain.");
    manifest = empty_manifest();
    previousSha = "GENESIS";
end
metadata.state_fingerprint = char(stateFingerprint);
metadata.linearization_fingerprint = char(linearizationFingerprint);
metadata.previous_checkpoint_sha256 = char(previousSha);
metadata.stage_id = "stage_B";
metadata.milestone = "B-2C";
metadata.linearization_storage = "fingerprint_only_rebuild_on_resume";
checkpoint = struct("state",state,"metadata",metadata);
assert(~isfolder(pathValue), ...
    "stageB2C:checkpoint:RefuseOverwrite", ...
    "Refusing to overwrite B-2C checkpoint %s.",pathValue);
if isfile(pathValue)
    orphan = load(pathValue,"checkpoint");
    assert(isfield(orphan,"checkpoint") && ...
        isequaln(orphan.checkpoint,checkpoint), ...
        "stageB2C:checkpoint:OrphanMismatch", ...
        "The uncommitted checkpoint revision %d differs from recomputation.", ...
        revision);
else
    rkkt.artifacts.save_mat_artifact(pathValue,"checkpoint",checkpoint);
end
sha256 = rkkt.data.compute_sha256_file(pathValue);
record = table(revision,string(fileName),string(sha256), ...
    string(stateFingerprint),string(linearizationFingerprint),previousSha, ...
    string(metadata.git_commit),string(metadata.config_sha256), ...
    string(metadata.input_hash_fingerprint), ...
    string(datetime("now","TimeZone","UTC", ...
        "Format","yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
    'VariableNames',{'iteration','relative_path','sha256', ...
    'state_fingerprint','linearization_fingerprint', ...
    'previous_checkpoint_sha256','git_commit','config_sha256', ...
    'input_hash_fingerprint','recorded_at_utc'});
manifest = [manifest;record];
rkkt.artifacts.write_table_csv_17g_atomic(context.checkpoint_manifest_path,manifest);
end

function value = empty_manifest()
value = table(zeros(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'iteration','relative_path','sha256', ...
    'state_fingerprint','linearization_fingerprint', ...
    'previous_checkpoint_sha256','git_commit','config_sha256', ...
    'input_hash_fingerprint','recorded_at_utc'});
end
