function record = write_stage_a4_checkpoint(runContext,state,metadata)
%WRITE_STAGE_A4_CHECKPOINT Atomically commit one contiguous A4 state.
%
% record = rkkt.artifacts.write_stage_a4_checkpoint(runContext,state,metadata) refuses
% overwrite, independently rebuilds the canonical state fingerprint, writes
% one v7.3 MAT through a same-directory atomic rename, hashes it, and then
% atomically advances checkpoint_manifest.csv.  A matching orphan produced
% after the MAT rename but before manifest publication can be adopted; it is
% never overwritten.
%
% Required metadata fields:
%   iteration, state_revision, input_hashes, config_sha256, git_commit,
%   linearization_fingerprint, state_fingerprint, iteration_csv_sha256,
%   direction_csv_sha256, refinement_csv_sha256,
%   initial_state_fingerprint, recursive_refinement_max_passes (=3).
% Revision zero binds the actual empty cumulative CSV files; no synthetic
% "not applicable" hash token is accepted.

validate_context(runContext);
metadata = rkkt.artifacts.normalize_stage_a4_checkpoint_metadata(metadata);
assert_running_run(runContext,metadata);
validate_state(state,metadata);

manifestExists = isfile(runContext.checkpoint_manifest_path);
if manifestExists
    stableExpected = struct( ...
        "input_hashes",metadata.input_hashes, ...
        "config_sha256",metadata.config_sha256, ...
        "git_commit",metadata.git_commit, ...
        "initial_state_fingerprint",metadata.initial_state_fingerprint, ...
        "recursive_refinement_max_passes", ...
            metadata.recursive_refinement_max_passes, ...
        "solve_pass",metadata.solve_pass, ...
        "model_contract_version",metadata.model_contract_version, ...
        "index_contract_version",metadata.index_contract_version, ...
        "solver_version",metadata.solver_version);
    priorAudit = rkkt.artifacts.validate_stage_a4_checkpoint(runContext, ...
        "ExpectedMetadata",stableExpected);
    manifest = priorAudit.manifest;
    expectedRevision = priorAudit.latest_revision+1;
    previousSha = priorAudit.hash_chain_tip;
else
    manifest = table();
    expectedRevision = 0;
    previousSha = "GENESIS";
end
assert(metadata.iteration==expectedRevision && ...
    metadata.state_revision==expectedRevision, ...
    "stageA4:checkpoint:NoncontiguousRevision", ...
    "Checkpoint revision must be %d; received %d.", ...
    expectedRevision,metadata.iteration);

fileName = "stage_A4_checkpoint_"+ ...
    compose("%03d",metadata.iteration)+".mat";
relativePath = "checkpoints/"+fileName;
targetPath = fullfile(runContext.checkpoints_dir,fileName);
createdAt = string(rkkt.artifacts.current_utc_iso8601());
checkpoint = struct( ...
    "schema_version","stage_A4_checkpoint_v1.0", ...
    "run_id",string(runContext.run_id), ...
    "stage_id","stage_A4", ...
    "metadata",metadata, ...
    "state",state, ...
    "previous_checkpoint_sha256",previousSha, ...
    "created_at",createdAt);

if isfile(targetPath)
    % A crash may leave the immutable MAT published but not yet listed.
    % Adopt it only when every payload/state identity is exactly the same.
    loaded = load(targetPath,"checkpoint");
    assert(isfield(loaded,"checkpoint") && ...
        checkpoint_payload_equal(loaded.checkpoint,checkpoint), ...
        "stageA4:checkpoint:RefuseOverwrite", ...
        "Existing checkpoint differs from the requested revision: %s", ...
        targetPath);
    checkpoint = loaded.checkpoint;
    createdAt = string(checkpoint.created_at);
else
    assert(~isfolder(targetPath), ...
        "stageA4:checkpoint:RefuseOverwrite", ...
        "A directory exists at the checkpoint target: %s",targetPath);
    stagingPath = [tempname(runContext.checkpoints_dir),'.pending.mat'];
    cleanupGuard = onCleanup(@()rkkt.artifacts.delete_file_if_exists(stagingPath));
    rkkt.artifacts.save_mat_artifact(stagingPath,"checkpoint",checkpoint);
    assert(~isfile(targetPath)&&~isfolder(targetPath), ...
        "stageA4:checkpoint:RefuseOverwrite", ...
        "Checkpoint target appeared during publication: %s",targetPath);
    [moved,message] = movefile(stagingPath,targetPath);
    assert(moved,"stageA4:checkpoint:AtomicMatMove", ...
        "Could not atomically publish %s: %s",targetPath,message);
    clear cleanupGuard
end

checkpointSha = lower(string(rkkt.data.compute_sha256_file(string(targetPath))));
record = table( ...
    string(runContext.run_id),"stage_A4",metadata.solve_pass, ...
    metadata.iteration,metadata.state_revision, ...
    metadata.model_contract_version,metadata.input_hashes_sha256, ...
    metadata.index_contract_version,metadata.solver_version, ...
    metadata.git_commit,metadata.config_sha256, ...
    metadata.initial_state_fingerprint,metadata.state_fingerprint, ...
    metadata.linearization_fingerprint,metadata.iteration_csv_sha256, ...
    metadata.direction_csv_sha256,metadata.refinement_csv_sha256, ...
    metadata.recursive_refinement_max_passes,previousSha,relativePath, ...
    checkpointSha,createdAt, ...
    'VariableNames',cellstr(manifest_columns()));
if isempty(manifest)
    updatedManifest = record;
else
    assert(isequal(string(manifest.Properties.VariableNames), ...
        manifest_columns()), ...
        "stageA4:checkpoint:ManifestSchema", ...
        "Existing checkpoint manifest column order changed.");
    updatedManifest = [manifest;record];
end
rkkt.artifacts.write_stage_a4_checkpoint_manifest_atomic( ...
    runContext.checkpoint_manifest_path,updatedManifest);

fullExpected = metadata;
fullExpected.input_hashes = metadata.input_hashes;
fullExpected = rmfield(fullExpected,"input_hashes_sha256");
audit = rkkt.artifacts.validate_stage_a4_checkpoint(runContext, ...
    "Revision",metadata.iteration, ...
    "ExpectedMetadata",fullExpected, ...
    "RebuiltLinearizationFingerprint", ...
        metadata.linearization_fingerprint);
assert(audit.passed && audit.selected_revision==metadata.iteration, ...
    "stageA4:checkpoint:PostWriteValidation", ...
    "The newly committed checkpoint failed independent validation.");
end

function validate_state(state,metadata)
assert(isstruct(state)&&isscalar(state)&&isfield(state,"stage_id") && ...
    string(state.stage_id)=="stage_A4", ...
    "stageA4:checkpoint:StateStageIdentity", ...
    "Checkpoint state must identify stage_A4.");
names = ["iteration_index","state_revision", ...
    "newton_direction_number","completed_newton_direction_count"];
for name = names
    assert(isfield(state,name) && isa(state.(name),"double") && ...
        isscalar(state.(name)) && ...
        state.(name)==metadata.state_revision, ...
        "stageA4:checkpoint:StateRevisionMismatch", ...
        "state.%s must equal checkpoint revision %d.", ...
        name,metadata.state_revision);
end
assert(isfield(state,"l")&&isfield(state,"z") && ...
    all(state.l>0)&&all(state.z>0), ...
    "stageA4:checkpoint:StatePositivity", ...
    "Checkpoint state must preserve strict l/z positivity.");
actualFingerprint = rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(state);
assert(actualFingerprint==metadata.state_fingerprint, ...
    "stageA4:checkpoint:StateFingerprintMismatch", ...
    "metadata.state_fingerprint does not match the supplied state.");
if metadata.iteration==0
    assert(actualFingerprint==metadata.initial_state_fingerprint, ...
        "stageA4:checkpoint:InitialStateFingerprintMismatch", ...
        "Revision zero must be the frozen initial state.");
end
end

function assert_running_run(context,metadata)
assert(isfield(context,"run_manifest_path") && ...
    isfile(context.run_manifest_path), ...
    "stageA4:checkpoint:RunManifestMissing", ...
    "Checkpoint writes require run_manifest.json.");
try
    manifest = jsondecode(fileread(context.run_manifest_path));
catch exception
    error("stageA4:checkpoint:RunManifestInvalid", ...
        "Could not decode run_manifest.json: %s",exception.message);
end
assert(isfield(manifest,"status")&&string(manifest.status)=="RUNNING" && ...
    isfield(manifest,"run_id")&& ...
    string(manifest.run_id)==string(context.run_id) && ...
    isfield(manifest,"stage_id")&&string(manifest.stage_id)=="stage_A4", ...
    "stageA4:checkpoint:RunNotRunning", ...
    "Checkpoint writes require the matching RUNNING stage_A4 manifest.");
assert(isfield(manifest,"git_commit") && ...
    lower(string(manifest.git_commit))==metadata.git_commit, ...
    "stageA4:checkpoint:RunManifestGitMismatch", ...
    "Checkpoint Git identity differs from run_manifest.json.");
if isfield(manifest,"model_contract_version")
    assert(string(manifest.model_contract_version)== ...
        metadata.model_contract_version, ...
        "stageA4:checkpoint:RunManifestModelContractMismatch", ...
        "Checkpoint model contract differs from run_manifest.json.");
end
assert(isfield(manifest,"input_hashes"), ...
    "stageA4:checkpoint:RunManifestInputMissing", ...
    "run_manifest.json must contain controlled input hashes.");
[manifestInputFingerprint,~] = ...
    rkkt.artifacts.compute_stage_a4_checkpoint_input_fingerprint(manifest.input_hashes);
assert(manifestInputFingerprint==metadata.input_hashes_sha256, ...
    "stageA4:checkpoint:RunManifestInputMismatch", ...
    "Checkpoint input identity differs from run_manifest.json.");
assert(isfield(context,"effective_config_path") && ...
    isfile(context.effective_config_path), ...
    "stageA4:checkpoint:EffectiveConfigMissing", ...
    "Checkpoint writes require effective_config.yaml.");
actualConfigSha = lower(string(rkkt.data.compute_sha256_file( ...
    string(context.effective_config_path))));
assert(actualConfigSha==metadata.config_sha256, ...
    "stageA4:checkpoint:EffectiveConfigMismatch", ...
    "metadata.config_sha256 differs from effective_config.yaml.");
end

function equal = checkpoint_payload_equal(actual,expected)
equal = isstruct(actual)&&isscalar(actual)&& ...
    all(isfield(actual,cellstr(["schema_version","run_id","stage_id", ...
        "metadata","state","previous_checkpoint_sha256","created_at"]))) && ...
    string(actual.schema_version)==string(expected.schema_version) && ...
    string(actual.run_id)==string(expected.run_id) && ...
    string(actual.stage_id)==string(expected.stage_id) && ...
    string(actual.previous_checkpoint_sha256)== ...
        string(expected.previous_checkpoint_sha256) && ...
    isequaln(rkkt.artifacts.normalize_stage_a4_checkpoint_metadata(actual.metadata), ...
        rkkt.artifacts.normalize_stage_a4_checkpoint_metadata(expected.metadata)) && ...
    isequaln(actual.state,expected.state);
end

function validate_context(context)
required = ["root","run_id","stage_id","checkpoints_dir", ...
    "checkpoint_manifest_path"];
assert(isstruct(context)&&isscalar(context)&& ...
    all(isfield(context,cellstr(required))) && ...
    string(context.stage_id)=="stage_A4" && ...
    isfolder(context.root)&&isfolder(context.checkpoints_dir), ...
    "stageA4:checkpoint:RunContext", ...
    "A valid stage_A4 run context and checkpoints directory are required.");
end

function columns = manifest_columns()
columns = ["run_id","stage_id","solve_pass","iteration", ...
    "state_revision","model_contract_version","input_hashes", ...
    "index_contract_version","solver_version","git_commit", ...
    "config_sha256","initial_state_fingerprint","state_fingerprint", ...
    "linearization_fingerprint","iteration_csv_sha256", ...
    "direction_csv_sha256","refinement_csv_sha256", ...
    "recursive_refinement_max_passes","previous_checkpoint_sha256", ...
    "path","sha256","created_at"];
end
