function value = metadata(interfaceName,productionFunction, ...
        inputArtifact,outputFile,moduleName,iteration,revision, ...
        interactive,writeArtifacts)
%METADATA Build shared manual-validation metadata.

arguments
    interfaceName (1,1) string
    productionFunction (1,1) string
    inputArtifact (1,1) string
    outputFile (1,1) string
    moduleName (1,1) string
    iteration
    revision
    interactive (1,1) logical
    writeArtifacts (1,1) logical
end

value = struct( ...
    "interface_name",interfaceName, ...
    "production_function",productionFunction, ...
    "input_artifact",inputArtifact, ...
    "input_sha256",rkkt.validation.sha256(inputArtifact), ...
    "git_commit",rkkt.validation.gitCommit(), ...
    "stage_id","stage_A4", ...
    "day",14:20, ...
    "hour",1:24, ...
    "iteration",iteration, ...
    "revision",revision, ...
    "matlab_version",string(version), ...
    "generated_at",rkkt.validation.nowText(), ...
    "contract_version",rkkt.contracts.version(), ...
    "module_name",moduleName, ...
    "output_file",outputFile, ...
    "interactive_figures",interactive, ...
    "artifacts_requested",writeArtifacts);
end
