function result = solve(state,data,index,config)
%SOLVE Run the complete seven-day primal-dual interior-point loop.

arguments
    state (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
end

a43 = config.a4_3;
chainId = "A4-3-FORMAL-CANDIDATE";
initialStateRevision = state.state_revision;
linearization = rkkt.model.build_stage_a4_scaled_objective_linearization( ...
    state,data,index,config,chainId);
metrics = rkkt.ipm.compute_stage_a4_unitized_metrics(linearization);
equalityReferenceScale = max(1,norm(linearization.r_eq,inf));
dualReferenceScale = max(1,norm(linearization.r_dual,inf));

maximumIterations = a43.max_iterations;
iteration = zeros(maximumIterations,1);
rEqInf = zeros(maximumIterations,1);
rIneqInf = zeros(maximumIterations,1);
rDualInf = zeros(maximumIterations,1);
meanLz = zeros(maximumIterations,1);
physicalViolation = zeros(maximumIterations,1);
alphaPrimal = zeros(maximumIterations,1);
alphaDual = zeros(maximumIterations,1);
directionError = zeros(maximumIterations,1);
recursiveResidual = zeros(maximumIterations,1);
fullResidual = zeros(maximumIterations,1);
elapsedSeconds = zeros(maximumIterations,1);

lastStep = struct();
completed = 0;
timer = tic;
while completed < maximumIterations && ~converged(metrics,a43)
    lastStep = rkkt.ipm.step( ...
        state,data,index,config, ...
        StepStrategy="independent", ...
        ObjectiveScaleMode="positive_scalar_unitization", ...
        DiagnosticObjectiveChainId=chainId, ...
        EqualityResidualReferenceScale=equalityReferenceScale, ...
        DualResidualReferenceScale=dualReferenceScale, ...
        RecursiveRefinementMaxPasses= ...
            a43.recursive_refinement_max_passes, ...
        UseCongruenceScaling= ...
            a43.recursive_congruence_scaling_enabled, ...
        EquilibrationPasses=a43.equilibration_passes);

    state = lastStep.state_after;
    linearization = lastStep.linearization_after;
    metrics = rkkt.ipm.compute_stage_a4_unitized_metrics(linearization);
    completed = completed+1;

    iteration(completed) = completed;
    rEqInf(completed) = metrics.r_eq_inf;
    rIneqInf(completed) = metrics.r_ineq_inf;
    rDualInf(completed) = metrics.r_dual_scaled_inf;
    meanLz(completed) = metrics.mean_lz_scaled;
    physicalViolation(completed) = ...
        metrics.physical_inequality_violation;
    alphaPrimal(completed) = ...
        lastStep.applied_step.applied_alpha_primal;
    alphaDual(completed) = ...
        lastStep.applied_step.applied_alpha_dual;
    directionError(completed) = ...
        lastStep.direction_audit.direction_relative_error;
    recursiveResidual(completed) = ...
        lastStep.direction_audit.recursive_kkt_relative_residual;
    fullResidual(completed) = ...
        lastStep.direction_audit.full_kkt_relative_residual;
    elapsedSeconds(completed) = toc(timer);
end

selection = 1:completed;
history = table( ...
    iteration(selection),rEqInf(selection),rIneqInf(selection), ...
    rDualInf(selection),meanLz(selection), ...
    physicalViolation(selection),alphaPrimal(selection), ...
    alphaDual(selection),directionError(selection), ...
    recursiveResidual(selection),fullResidual(selection), ...
    elapsedSeconds(selection), ...
    VariableNames=["iteration","r_eq_inf","r_ineq_inf", ...
        "r_dual_scaled_inf","mean_lz_scaled", ...
        "physical_inequality_violation","alpha_primal", ...
        "alpha_dual","direction_relative_error", ...
        "recursive_kkt_relative_residual", ...
        "full_kkt_relative_residual","elapsed_seconds"]);

convergenceAchieved = converged(metrics,a43);
if convergenceAchieved
    status = "CONVERGED";
else
    status = "MAX_ITERATIONS";
end

result = struct( ...
    "status",status, ...
    "convergence_achieved",convergenceAchieved, ...
    "iteration_count",completed, ...
    "initial_state_revision",initialStateRevision, ...
    "final_state",state, ...
    "final_linearization",linearization, ...
    "final_metrics",metrics, ...
    "iteration_history",history, ...
    "last_step",lastStep, ...
    "elapsed_seconds",toc(timer));
end

function value = converged(metrics,config)
value = metrics.r_eq_inf<=config.primal_equality_inf_tolerance && ...
    metrics.r_ineq_inf<=config.primal_inequality_inf_tolerance && ...
    metrics.r_dual_scaled_inf<=config.dual_scaled_inf_tolerance && ...
    metrics.mean_lz_scaled<=config.mean_lz_scaled_tolerance && ...
    metrics.physical_inequality_violation<= ...
        config.physical_violation_tolerance;
end
