function result = step(stateBefore,data,index,config,options)
%STEP Execute one explicit-state A4 primal-dual transition.

arguments
    stateBefore (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.StepStrategy (1,1) string {mustBeMember( ...
        options.StepStrategy,["independent","common_min"])} = "independent"
    options.ObjectiveScaleMode (1,1) string {mustBeMember( ...
        options.ObjectiveScaleMode, ...
        ["unscaled","positive_scalar_unitization"])} = "unscaled"
    options.DiagnosticObjectiveChainId (1,1) string = ""
    options.EqualityResidualReferenceScale (1,1) double = NaN
    options.DualResidualReferenceScale (1,1) double = NaN
    options.RecursiveRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.UseCongruenceScaling (1,1) logical = false
    options.EquilibrationPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 8
end

result = rkkt.ipm.execute_stage_a4_iteration( ...
    stateBefore,data,index,config, ...
    StepStrategy=options.StepStrategy, ...
    ObjectiveScaleMode=options.ObjectiveScaleMode, ...
    DiagnosticObjectiveChainId=options.DiagnosticObjectiveChainId, ...
    EqualityResidualReferenceScale= ...
        options.EqualityResidualReferenceScale, ...
    DualResidualReferenceScale=options.DualResidualReferenceScale, ...
    RecursiveRefinementMaxPasses= ...
        options.RecursiveRefinementMaxPasses, ...
    UseCongruenceScaling=options.UseCongruenceScaling, ...
    EquilibrationPasses=options.EquilibrationPasses);
end
