function assembly = assemble_stage_a3_full_kkt(lin)
%ASSEMBLE_STAGE_A3_FULL_KKT Assemble the canonical sparse A3 audit KKT.

arguments
    lin (1,1) struct
end

contract = stage_a3_linearization_contract(lin);
nx = contract.nx;
neq = contract.neq;
ni = contract.nineq;
matrix = [sparse(lin.H),sparse(lin.A.'),sparse(nx,ni),sparse(lin.G.'); ...
    sparse(lin.A),sparse(neq,neq),sparse(neq,ni),sparse(neq,ni); ...
    sparse(lin.G),sparse(ni,neq),speye(ni),sparse(ni,ni); ...
    sparse(ni,nx),sparse(ni,neq),spdiags(contract.z,0,ni,ni), ...
    spdiags(contract.l,0,ni,ni)];
rhs = [-contract.r_dual;-contract.r_eq;-contract.r_ineq;-contract.r_comp];
dimension = nx+neq+2*ni;
assert(isequal(size(matrix),[dimension,dimension]) && ...
    numel(rhs)==dimension,"stageA3:solver:FullKktShape", ...
    "A3 full KKT shape does not match the canonical direction dimension.");
assert(issparse(matrix) && all(isfinite(nonzeros(matrix))) && ...
    all(isfinite(rhs)),"stageA3:solver:FullKktNonfinite", ...
    "A3 full KKT must remain sparse and finite.");

assembly = struct();
assembly.linearization_identity = contract.identity;
assembly.matrix = matrix;
assembly.rhs = rhs;
assembly.dimension = dimension;
assembly.nnz = nnz(matrix);
assembly.slices = struct( ...
    "xi",(1:nx).',"y",(nx+(1:neq)).', ...
    "l",(nx+neq+(1:ni)).',"z",(nx+neq+ni+(1:ni)).', ...
    "stationarity_rows",(1:nx).', ...
    "equality_rows",(nx+(1:neq)).', ...
    "slack_rows",(nx+neq+(1:ni)).', ...
    "complementarity_rows",(nx+neq+ni+(1:ni)).');
end
