function recovery = recover_stage_a3_recursive_direction( ...
        lin,partition,responses,core)
%RECOVER_STAGE_A3_RECURSIVE_DIRECTION Strict reverse canonical recovery.

arguments
    lin (1,1) struct
    partition (1,1) struct
    responses (:,1) struct
    core (1,1) struct
end

contract = stage_a3_linearization_contract(lin);
assert(isequal(contract.identity,partition.linearization_identity) && ...
    isequal(contract.identity,core.linearization_identity), ...
    "stageA3:solver:LinearizationIdentityMismatch", ...
    "A3 recovery inputs do not share one linearization identity.");
assert(numel(responses)==contract.n_days, ...
    "stageA3:solver:DailyResponseCount", ...
    "A3 recovery requires exactly seven daily responses.");

deltaQ = core.delta_q;
deltaRho = core.delta_rho;
deltaXi = zeros(contract.nx,1);
deltaY = zeros(contract.neq,1);
deltaXi(contract.q_global) = deltaQ;
deltaY(contract.y_duration) = deltaRho;
deltaQDay = cell(1,contract.n_days);
deltaPi = cell(1,contract.n_days);
vByDayHour = cell(contract.n_days,contract.n_hours);

for d = contract.n_days:-1:1
    responseIndex = find([responses.day_id]==contract.days(d),1,"first");
    assert(~isempty(responseIndex),"stageA3:solver:MissingDayResponse", ...
        "No daily response exists for day %d.",contract.days(d));
    response = responses(responseIndex);
    assert(isequal(response.linearization_identity,contract.identity), ...
        "stageA3:solver:LinearizationIdentityMismatch", ...
        "Day %d response identity differs during recovery.",contract.days(d));
    deltaQDay{d} = deltaQ+response.beta;
    deltaPi{d} = response.c-response.S*deltaQDay{d};
    deltaXi(contract.q_day_by_day{d}) = deltaQDay{d};
    deltaY(contract.y_binding_by_day{d}) = deltaPi{d};
    for t = contract.n_hours:-1:1
        v = response.a_by_hour{t}- ...
            response.U_by_hour{t}*deltaQDay{d};
        nxHour = numel(contract.x_by_day_hour{d,t});
        neqHour = numel(contract.y_by_day_hour{d,t});
        assert(numel(v)==nxHour+neqHour, ...
            "stageA3:solver:HourlyRecoveryDimension", ...
            "Day %d hour %d recovery dimension is inconsistent.", ...
            contract.days(d),contract.hours(t));
        deltaXi(contract.x_by_day_hour{d,t}) = v(1:nxHour);
        deltaY(contract.y_by_day_hour{d,t}) = v(nxHour+1:end);
        vByDayHour{d,t} = v;
    end
end

gDelta = sparse(lin.G)*deltaXi;
deltaL = -contract.r_ineq-gDelta;
deltaZ = (-contract.r_comp+contract.z.*contract.r_ineq+ ...
    contract.z.*gDelta)./contract.l;
assert(all(isfinite(deltaXi)) && all(isfinite(deltaY)) && ...
    all(isfinite(deltaL)) && all(isfinite(deltaZ)), ...
    "stageA3:solver:RecoveryNonfinite", ...
    "A3 strict reverse recovery produced NaN or Inf.");

qDayMatrix = horzcat(deltaQDay{:});
piMatrix = horzcat(deltaPi{:});
fixed = stage_a3_fixed_zero_evidence(lin.index);
recovery = struct();
recovery.linearization_identity = contract.identity;
recovery.direction = [deltaXi;deltaY;deltaL;deltaZ];
recovery.components = struct( ...
    "xi",deltaXi,"y",deltaY,"l",deltaL,"z",deltaZ, ...
    "q",deltaQ,"rho",deltaRho, ...
    "q_day_by_day",{deltaQDay},"pi_by_day",{deltaPi}, ...
    "q_day_matrix",qDayMatrix,"pi_matrix",piMatrix, ...
    "v_by_day_hour",{vByDayHour});
recovery.fixed_zero = fixed;
recovery.diagnostics = struct( ...
    "delta_l_formula_residual", ...
        norm(deltaL+contract.r_ineq+gDelta,2), ...
    "delta_z_formula_residual", ...
        norm(contract.l.*deltaZ+contract.r_comp- ...
        contract.z.*contract.r_ineq-contract.z.*gDelta,2), ...
    "reverse_day_order",contract.days(end:-1:1), ...
    "reverse_hour_order",contract.hours(end:-1:1), ...
    "strict_reverse_recovery",true);
end
