function result = run_stage_a4_full_ipm( ...
        data,index,config,runContext,options)
%RUN_STAGE_A4_FULL_IPM Execute the checkpointed A4-3 candidate chain.
%
% The official direction always comes from the stable-v2 recursive
% LDL/Thomas route.  A complete sparse KKT direction is solved once per
% attempted iteration and is consumed only by the independent audit.
% Cumulative evidence is persisted after every accepted update.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    runContext (1,1) struct
    options.Resume (1,1) logical = false
end

a43 = config.a4_3;
assert(a43.max_iterations==100 && ...
    a43.recursive_refinement_max_passes==3 && ...
    a43.step_strategy=="independent" && ...
    a43.convergence_coordinate=="positive_scalar_unitized_kkt", ...
    "stageA4:a43:SolverContract", ...
    "The formal A4-3 iteration contract is not frozen.");
require_run_context(runContext);
mark_stage_a4_full_ipm_execution(runContext);

iterationPath = fullfile(runContext.iterations_dir, ...
    "iteration_summary.csv");
directionPath = fullfile(runContext.iterations_dir, ...
    "direction_audit.csv");
refinementPath = fullfile(runContext.iterations_dir, ...
    "recursive_refinement.csv");
initialMetricsPath = fullfile(runContext.iterations_dir, ...
    "initial_metrics.json");

manifest = jsondecode(fileread(runContext.run_manifest_path));
solverInvocationCount = double(manifest.solver_invocation_count);
gitCommit = string(manifest.git_commit);
inputHashes = manifest.input_hashes;
configSha256 = compute_sha256_file(runContext.effective_config_path);
chainId = "A4-3-FORMAL-CANDIDATE";

seed = initialize_stage_a4_state(data,index,config);
initialStateFingerprint = ...
    compute_stage_a4_checkpoint_state_fingerprint(seed);
expectedInitialFingerprint = ...
    "7277a250e33e3a1cfa310b4581faa7232a2c3cb99ff6d7cc6b4602e40970c3aa";
assert(initialStateFingerprint==expectedInitialFingerprint, ...
    "stageA4:a43:InitialStateFingerprint", ...
    "The deterministic A4 initial state differs from the frozen R1 state.");
initialLinearization = build_stage_a4_scaled_objective_linearization( ...
    seed,data,index,config,chainId);
initialMetrics = compute_stage_a4_unitized_metrics(initialLinearization);
lastAcceptedLinearization = initialLinearization;
lastAcceptedMetrics = initialMetrics;
equalityReferenceScale = max(1,norm(initialLinearization.r_eq,inf));
dualReferenceScale = max(1,norm(initialLinearization.r_dual,inf));
objectiveScaleFactor = initialLinearization.objective_scale.factor;

capacityNames = string(initialLinearization.capacity_parameters.names(:));
assert(numel(capacityNames)==14 && numel(unique(capacityNames))==14, ...
    "stageA4:a43:CapacityNames", ...
    "A4-3 requires 14 unique global capacity names.");

if options.Resume
    recover_initial_checkpoint_transaction(runContext,seed, ...
        initialMetrics,initialLinearization,gitCommit,inputHashes, ...
        configSha256,initialStateFingerprint,capacityNames, ...
        a43.recursive_refinement_max_passes);
    expected = identity_metadata(gitCommit,inputHashes,configSha256, ...
        initialStateFingerprint,a43.recursive_refinement_max_passes);
    [checkpoint,checkpointRecord,loadAudit] = load_stage_a4_checkpoint( ...
        runContext,"ExpectedMetadata",expected);
    state = checkpoint.state;
    currentLinearization = ...
        build_stage_a4_scaled_objective_linearization( ...
            state,data,index,config,chainId);
    rebuiltFingerprint = compute_stage_a4_rns1_fingerprint( ...
        currentLinearization,"linearization");
    validation = validate_stage_a4_checkpoint(runContext, ...
        "ExpectedMetadata",expected, ...
        "Revision",state.state_revision, ...
        "RebuiltLinearizationFingerprint",rebuiltFingerprint);
    assert(loadAudit.passed && validation.passed, ...
        "stageA4:a43:ResumeCheckpoint", ...
        "The latest A4-3 checkpoint did not pass identity validation.");
    orphanAudit = reconcile_stage_a4_uncommitted_transactions( ...
        runContext,state.state_revision);
    repair_cumulative_evidence_from_snapshot(runContext, ...
        state.state_revision,checkpointRecord, ...
        iterationPath,directionPath,refinementPath);
    iterationTable = readtable(iterationPath,"TextType","string", ...
        "VariableNamingRule","preserve");
    directionTable = readtable(directionPath,"TextType","string", ...
        "VariableNamingRule","preserve");
    refinementTable = readtable(refinementPath,"TextType","string", ...
        "VariableNamingRule","preserve");
    [iterationTable,directionTable,refinementTable] = ...
        normalize_persisted_tables(iterationTable,directionTable, ...
            refinementTable,capacityNames);
    assert(height(iterationTable)==state.state_revision && ...
        height(directionTable)==state.state_revision && ...
        height(refinementTable)==8*state.state_revision, ...
        "stageA4:a43:ResumeEvidenceCount", ...
        "Cumulative iteration evidence does not match the checkpoint.");
    replayAudit = replay_last_accepted_iteration( ...
        runContext,state,data,index,config,chainId, ...
        equalityReferenceScale,dualReferenceScale, ...
        iterationTable,directionTable,expected);
    resumedMetrics = compute_stage_a4_unitized_metrics(currentLinearization);
    lastAcceptedLinearization = currentLinearization;
    lastAcceptedMetrics = resumedMetrics;
    resumedAtConvergence = convergence_passed(resumedMetrics,a43);
    if resumedAtConvergence || state.state_revision>=a43.max_iterations
        startIteration = a43.max_iterations+1;
    else
        startIteration = state.state_revision+1;
    end
else
    state = seed;
    iterationTable = empty_iteration_table(capacityNames);
    directionTable = empty_direction_table();
    refinementTable = empty_refinement_table();
    assert(~isfile(iterationPath)&&~isfile(directionPath)&& ...
        ~isfile(refinementPath)&&~isfile(initialMetricsPath), ...
        "stageA4:a43:FreshEvidenceExists", ...
        "A fresh A4-3 run may not overwrite iteration evidence.");
    write_table_csv_17g_atomic(iterationPath,iterationTable);
    write_table_csv_17g_atomic(directionPath,directionTable);
    write_table_csv_17g_atomic(refinementPath,refinementTable);
    initialSnapshot = write_revision_snapshot(runContext,0,iterationTable, ...
        directionTable,refinementTable);
    write_json_file(initialMetricsPath,initialMetrics);
    metadata = checkpoint_metadata(0,gitCommit,inputHashes, ...
        configSha256,initialStateFingerprint, ...
        compute_stage_a4_rns1_fingerprint( ...
            initialLinearization,"linearization"), ...
        initialSnapshot.iteration_summary_sha256, ...
        initialSnapshot.direction_audit_sha256, ...
        initialSnapshot.recursive_refinement_sha256, ...
        a43.recursive_refinement_max_passes);
    metadata.state_fingerprint = initialStateFingerprint;
    write_stage_a4_checkpoint(runContext,state,metadata);
    replayAudit = struct("performed",false,"passed",true, ...
        "reason","fresh_initial_state", ...
        "full_kkt_audit_performed",false, ...
        "full_kkt_direction_solve_count",0);
    orphanAudit = struct("orphan_count",0, ...
        "orphan_revisions",zeros(0,1), ...
        "quarantine_paths",strings(0,1), ...
        "artifact_types",strings(0,1),"passed",true);
    startIteration = 1;
    resumedAtConvergence = false;
end

if resumedAtConvergence
    terminalState = "CONVERGED";
else
    terminalState = "MAX_ITERATIONS";
end
failure = struct("present",false,"iteration",0,"identifier","", ...
    "message","","state_revision",state.state_revision, ...
    "evidence_path","");
acceptedCount = state.state_revision;
lastAttemptedIteration = state.state_revision;
attemptedIterationCountCurrentInvocation = 0;
resumeReplayFullKktAuditCount = double(replayAudit.performed);
currentInvocationCompletedEvaluationCount = ...
    resumeReplayFullKktAuditCount;
runTimer = tic;
cumulativeOffset = cumulative_time_from_table(iterationTable);

for iteration = startIteration:a43.max_iterations
    lastAttemptedIteration = iteration;
    attemptedIterationCountCurrentInvocation = ...
        attemptedIterationCountCurrentInvocation+1;
    try
        step = execute_stage_a4_iteration(state,data,index,config, ...
            "StepStrategy","independent", ...
            "ObjectiveScaleMode","positive_scalar_unitization", ...
            "DiagnosticObjectiveChainId",chainId, ...
            "RecursiveRefinementMaxPasses", ...
                a43.recursive_refinement_max_passes, ...
            "EqualityResidualReferenceScale",equalityReferenceScale, ...
            "DualResidualReferenceScale",dualReferenceScale);
        currentInvocationCompletedEvaluationCount = ...
            currentInvocationCompletedEvaluationCount+1;
        metrics = compute_stage_a4_unitized_metrics( ...
            step.linearization_after);
        convergencePassed = convergence_passed(metrics,a43);
        refinement = summarize_stage_a4_recursive_refinement( ...
            step.recursive);
        iterationRow = make_iteration_row(step,metrics,iteration, ...
            cumulativeOffset+toc(runTimer),convergencePassed, ...
            capacityNames,a43);
        directionRow = make_direction_row(step,iteration);
        refinementRows = add_refinement_identity( ...
            refinement,iteration,step.state_after.state_revision);
    catch cause
        terminalState = "NUMERICAL_FAILURE";
        failure = make_failure(cause,iteration,state);
        failure = save_failure_evidence(runContext, ...
            "NUMERICAL_FAILURE",solverInvocationCount,state,failure);
        break
    end

    candidateIterations = [iterationTable;iterationRow];
    candidateDirections = [directionTable;directionRow];
    candidateRefinement = [refinementTable;refinementRows];
    try
        snapshot = write_revision_snapshot(runContext,iteration, ...
            candidateIterations,candidateDirections,candidateRefinement);
        nextState = step.state_after;
        linearizationFingerprint = ...
            compute_stage_a4_rns1_fingerprint( ...
                step.linearization_after,"linearization");
        stateFingerprint = ...
            compute_stage_a4_checkpoint_state_fingerprint(nextState);
        metadata = checkpoint_metadata(iteration,gitCommit,inputHashes, ...
            configSha256,initialStateFingerprint, ...
            linearizationFingerprint, ...
            snapshot.iteration_summary_sha256, ...
            snapshot.direction_audit_sha256, ...
            snapshot.recursive_refinement_sha256, ...
            a43.recursive_refinement_max_passes);
        metadata.state_fingerprint = stateFingerprint;
        checkpointRecord = write_stage_a4_checkpoint( ...
            runContext,nextState,metadata);
    catch cause
        terminalState = "INTERRUPTED_RECOVERABLE";
        failure = make_failure(cause,iteration,state);
        failure = save_failure_evidence(runContext, ...
            "INTERRUPTED_RECOVERABLE",solverInvocationCount,state,failure);
        break
    end

    iterationTable = candidateIterations;
    directionTable = candidateDirections;
    refinementTable = candidateRefinement;
    state = nextState;
    lastAcceptedLinearization = step.linearization_after;
    lastAcceptedMetrics = metrics;
    acceptedCount = iteration;
    try
        publish_revision_snapshot(snapshot,iterationPath, ...
            directionPath,refinementPath);
        update_running_run_manifest(runContext,struct( ...
            "a4_3_run_terminal_state","RUNNING", ...
            "last_accepted_iteration",iteration, ...
            "last_state_revision",state.state_revision, ...
            "last_checkpoint_sha256", ...
                char(string(checkpointRecord.sha256)), ...
            "objective_scale_factor",objectiveScaleFactor, ...
            "convergence_coordinate", ...
                "positive_scalar_unitized_kkt"));
    catch cause
        terminalState = "INTERRUPTED_RECOVERABLE";
        failure = make_failure(cause,iteration,state);
        failure = save_failure_evidence(runContext, ...
            "INTERRUPTED_RECOVERABLE",solverInvocationCount,state,failure);
        break
    end
    clear step
    if convergencePassed
        terminalState = "CONVERGED";
        break
    end
end

if acceptedCount==a43.max_iterations && terminalState~="CONVERGED"
    terminalState = "MAX_ITERATIONS";
end
finalLinearization = lastAcceptedLinearization;
finalMetrics = lastAcceptedMetrics;
executionAudit = make_execution_audit(iterationTable,directionTable, ...
    refinementTable,config,a43,acceptedCount, ...
    currentInvocationCompletedEvaluationCount, ...
    resumeReplayFullKktAuditCount);
if terminalState~="INTERRUPTED_RECOVERABLE" && ...
        acceptedCount>0 && ~executionAudit.all_pass
    terminalState = "NUMERICAL_FAILURE";
    failure = struct("present",true,"iteration",acceptedCount, ...
        "identifier","stageA4:a43:ExecutionAudit", ...
        "message","A blocking per-iteration execution audit failed.", ...
        "state_revision",state.state_revision, ...
        "evidence_path","", ...
        "report","The persisted execution audit did not pass.");
    failure = save_failure_evidence(runContext, ...
        "NUMERICAL_FAILURE",solverInvocationCount,state,failure);
end
update_running_run_manifest(runContext,struct( ...
    "a4_3_run_terminal_state",char(terminalState), ...
    "last_accepted_iteration",acceptedCount, ...
    "last_state_revision",state.state_revision, ...
    "last_attempted_iteration",lastAttemptedIteration, ...
    "attempted_iteration_count_current_invocation", ...
        attemptedIterationCountCurrentInvocation, ...
    "accepted_iteration_full_kkt_audit_count",height(directionTable), ...
    "resume_replay_full_kkt_audit_count", ...
        resumeReplayFullKktAuditCount, ...
    "persisted_or_replayed_full_kkt_direction_solve_count", ...
        height(directionTable)+resumeReplayFullKktAuditCount, ...
    "completed_iteration_evaluation_count_current_invocation", ...
        currentInvocationCompletedEvaluationCount, ...
    "convergence_achieved",terminalState=="CONVERGED", ...
    "convergence_coordinate","positive_scalar_unitized_kkt", ...
    "objective_scale_factor",objectiveScaleFactor, ...
    "recursive_refinement_max_passes", ...
        a43.recursive_refinement_max_passes, ...
    "no_full_direction_fallback", ...
        all(directionTable.no_full_direction_fallback), ...
    "full_kkt_role","audit_only"));

result = struct( ...
    "stage_id","stage_A4", ...
    "milestone","A4-3", ...
    "run_id",string(runContext.run_id), ...
    "run_path",string(runContext.root), ...
    "run_terminal_state",terminalState, ...
    "convergence_achieved",terminalState=="CONVERGED", ...
    "iteration_count",acceptedCount, ...
    "last_attempted_iteration",lastAttemptedIteration, ...
    "attempted_iteration_count_current_invocation", ...
        attemptedIterationCountCurrentInvocation, ...
    "full_kkt_audit_count",height(directionTable)+ ...
        resumeReplayFullKktAuditCount, ...
    "accepted_iteration_full_kkt_audit_count",height(directionTable), ...
    "resume_replay_full_kkt_audit_count", ...
        resumeReplayFullKktAuditCount, ...
    "persisted_or_replayed_full_kkt_direction_solve_count", ...
        height(directionTable)+resumeReplayFullKktAuditCount, ...
    "completed_iteration_evaluation_count_current_invocation", ...
        currentInvocationCompletedEvaluationCount, ...
    "initial_state_fingerprint",initialStateFingerprint, ...
    "objective_scale_factor",objectiveScaleFactor, ...
    "initial_metrics",initialMetrics, ...
    "final_metrics",finalMetrics, ...
    "final_state",state, ...
    "final_linearization",finalLinearization, ...
    "iteration_summary",iterationTable, ...
    "direction_audit",directionTable, ...
    "recursive_refinement",refinementTable, ...
    "execution_audit",executionAudit, ...
    "resume_replay_audit",replayAudit, ...
    "orphan_revision_audit",orphanAudit, ...
    "failure",failure, ...
    "timing",struct("solver_seconds",cumulativeOffset+toc(runTimer)), ...
    "execution",struct( ...
        "recursive_direction_is_official",true, ...
        "full_kkt_role","audit_only", ...
        "full_kkt_direction_consumed",false, ...
        "complete_kkt_direction_fallback_used",false, ...
        "parallel_executed",false, ...
        "step_strategy","independent", ...
        "recursive_refinement_max_passes",3));
end

function row = make_iteration_row( ...
        step,m,iteration,cumulative,passed,names,a43)
refinement = summarize_stage_a4_recursive_refinement(step.recursive);
rowValue = struct( ...
    "iteration",iteration, ...
    "state_revision",step.state_after.state_revision, ...
    "objective_scaled",m.objective_scaled, ...
    "objective_original",m.objective_original, ...
    "r_eq_inf",m.r_eq_inf, ...
    "r_ineq_inf",m.r_ineq_inf, ...
    "physical_inequality_violation", ...
        m.physical_inequality_violation, ...
    "r_dual_scaled_inf",m.r_dual_scaled_inf, ...
    "r_dual_original_mapped_inf",m.r_dual_original_mapped_inf, ...
    "r_comp_scaled_inf",m.r_comp_scaled_inf, ...
    "mean_lz_scaled",m.mean_lz_scaled, ...
    "ltz_scaled",m.ltz_scaled, ...
    "mean_lz_original_mapped",m.mean_lz_original_mapped, ...
    "gap_original_mapped",m.gap_original_mapped, ...
    "ltz_original_mapped",m.ltz_original_mapped, ...
    "mapped_y_inf",m.mapped_y_inf, ...
    "mapped_z_inf",m.mapped_z_inf, ...
    "eta_eq",m.eta_eq, ...
    "eta_dual",m.eta_dual, ...
    "eta_gap",m.eta_gap, ...
    "candidate_alpha_primal",step.primal_step.alpha, ...
    "applied_alpha_primal", ...
        step.applied_step.applied_alpha_primal, ...
    "candidate_alpha_dual",step.dual_step.alpha, ...
    "applied_alpha_dual",step.applied_step.applied_alpha_dual, ...
    "primal_limiter",string(step.primal_step.limiting_constraint_id), ...
    "dual_limiter",string(step.dual_step.limiting_constraint_id), ...
    "centering_sigma",a43.centering_sigma, ...
    "fraction_to_boundary_tau",a43.fraction_to_boundary, ...
    "step_strategy",string(step.applied_step.strategy), ...
    "objective_scale_mode", ...
        string(step.linearization_before.objective_scale.mode), ...
    "recursive_refinement_max_passes", ...
        a43.recursive_refinement_max_passes, ...
    "common_step_used",false, ...
    "dynamic_sigma_used",false, ...
    "predictor_corrector_used",false, ...
    "line_search_used",false, ...
    "regularization_used",false, ...
    "automatic_symmetrization_used",false, ...
    "parallel_used",false, ...
    "full_kkt_direction_fallback_used", ...
        ~(step.recursive.no_full_direction_fallback && ...
        ~step.recursive.full_direction_consumed), ...
    "fixed_zero_count",step.fixed_zero.count, ...
    "fixed_zero_maximum_absolute_value", ...
        step.fixed_zero.maximum_absolute_value_after, ...
    "fixed_zero_maximum_absolute_direction", ...
        step.fixed_zero.maximum_absolute_direction, ...
    "fixed_zero_exact", ...
        step.fixed_zero.values_exact_zero_before && ...
        step.fixed_zero.values_exact_zero_after && ...
        step.fixed_zero.directions_exact_zero, ...
    "min_l",m.min_l, ...
    "min_z",m.min_z, ...
    "recursive_refinement_selected_pass_max", ...
        max(refinement.selected_pass), ...
    "recursive_refinement_selected_pass_total", ...
        sum(refinement.selected_pass), ...
    "recursive_refinement_passes_attempted_total", ...
        sum(refinement.passes_attempted), ...
    "iteration_seconds",step.timing.total_seconds, ...
    "cumulative_seconds",cumulative, ...
    "convergence_passed",logical(passed));
q = step.state_after.xi(step.linearization_after.maps.q_global);
for k = 1:numel(names)
    rowValue.(matlab.lang.makeValidName(char(names(k)))) = q(k);
end
row = struct2table(rowValue,"AsArray",true);
end

function row = make_direction_row(step,iteration)
audit = step.direction_audit;
components = audit.component_relative_errors;
noFallback = step.recursive.no_full_direction_fallback && ...
    ~step.recursive.full_direction_consumed && ...
    audit.passed.no_full_direction_fallback;
rowValue = struct( ...
    "iteration",iteration, ...
    "state_revision_before",step.state_before.state_revision, ...
    "state_revision_after",step.state_after.state_revision, ...
    "direction_relative_error",audit.direction_relative_error, ...
    "xi_relative_error",components.xi, ...
    "y_relative_error",components.y, ...
    "l_relative_error",components.l, ...
    "z_relative_error",components.z, ...
    "recursive_full_kkt_relative_residual", ...
        audit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual",audit.full_kkt_relative_residual, ...
    "maximum_direction_difference", ...
        audit.maximum_direction_difference.absolute_value, ...
    "maximum_direction_index", ...
        audit.maximum_direction_difference.canonical_index, ...
    "maximum_error_location", ...
        string(jsonencode(audit.maximum_direction_difference.location)), ...
    "maximum_recursive_residual", ...
        audit.maximum_recursive_residual.absolute_value, ...
    "maximum_recursive_residual_row", ...
        audit.maximum_recursive_residual.row, ...
    "maximum_full_residual", ...
        audit.maximum_full_residual.absolute_value, ...
    "maximum_full_residual_row",audit.maximum_full_residual.row, ...
    "no_full_direction_fallback",logical(noFallback), ...
    "full_kkt_audit_only",true, ...
    "recursive_direction_is_official",true, ...
    "full_kkt_dimension",step.direct_audit.kkt.dimension, ...
    "linearization_identity",string(audit.linearization_identity));
row = struct2table(rowValue,"AsArray",true);
end

function rows = add_refinement_identity(value,iteration,revision)
n = height(value);
rows = addvars(value,repmat(iteration,n,1), ...
    repmat(revision,n,1),'Before',1, ...
    'NewVariableNames',{'iteration','state_revision'});
end

function value = convergence_passed(m,a43)
value = m.r_eq_inf<=a43.primal_equality_inf_tolerance && ...
    m.r_ineq_inf<=a43.primal_inequality_inf_tolerance && ...
    m.r_dual_scaled_inf<=a43.dual_scaled_inf_tolerance && ...
    m.mean_lz_scaled<=a43.mean_lz_scaled_tolerance && ...
    m.physical_inequality_violation<= ...
        a43.physical_violation_tolerance;
end

function audit = make_execution_audit(iterations,directions,refinement, ...
        config,a43,acceptedCount,currentInvocationCompletedCount,replayCount)
if isempty(directions)
    directionPass = false;
    positivityPass = false;
    noFallback = false;
else
    directionPass = all(directions.direction_relative_error<=1e-10) && ...
        all(directions.xi_relative_error<=1e-10) && ...
        all(directions.y_relative_error<=1e-10) && ...
        all(directions.l_relative_error<=1e-10) && ...
        all(directions.z_relative_error<=1e-10) && ...
        all(directions.recursive_full_kkt_relative_residual<=1e-10) && ...
        all(directions.full_kkt_relative_residual<=1e-10);
    positivityPass = all(iterations.min_l>0) && all(iterations.min_z>0);
    noFallback = all(directions.no_full_direction_fallback) && ...
        all(directions.full_kkt_audit_only);
end
forbiddenPass = a43.step_strategy=="independent" && ...
    ~a43.common_step_enabled && ~a43.dynamic_sigma_enabled && ...
    ~a43.predictor_corrector_enabled && ~a43.line_search_enabled && ...
    ~a43.regularization_enabled && ...
    ~a43.automatic_symmetrization_enabled && ...
    a43.parallel_mode=="off" && ...
    ~a43.full_kkt_direction_fallback_enabled && ...
    config.initialization.centering_sigma==0.1 && ...
    config.fraction_to_boundary==0.9995 && ...
    height(iterations)==acceptedCount && ...
    all(iterations.centering_sigma==0.1) && ...
    all(iterations.fraction_to_boundary_tau==0.9995) && ...
    all(iterations.step_strategy=="independent") && ...
    all(iterations.objective_scale_mode== ...
        "positive_scalar_unitization") && ...
    all(iterations.recursive_refinement_max_passes==3) && ...
    ~any(iterations.common_step_used) && ...
    ~any(iterations.dynamic_sigma_used) && ...
    ~any(iterations.predictor_corrector_used) && ...
    ~any(iterations.line_search_used) && ...
    ~any(iterations.regularization_used) && ...
    ~any(iterations.automatic_symmetrization_used) && ...
    ~any(iterations.parallel_used) && ...
    ~any(iterations.full_kkt_direction_fallback_used);
refinementPass = height(refinement)==8*acceptedCount && ...
    all(refinement.maximum_passes==3) && ...
    all(refinement.selected_pass<=3) && ...
    all(refinement.additional_factorization_count==0) && ...
    ~any(refinement.full_kkt_direction_consumed);
audit = struct( ...
    "accepted_iteration_count",acceptedCount, ...
    "accepted_iteration_full_kkt_audit_count",height(directions), ...
    "resume_replay_full_kkt_audit_count",replayCount, ...
    "persisted_or_replayed_full_kkt_direction_solve_count", ...
        height(directions)+replayCount, ...
    "completed_iteration_evaluation_count_current_invocation", ...
        currentInvocationCompletedCount, ...
    "one_full_kkt_audit_per_accepted_iteration", ...
        height(directions)==acceptedCount, ...
    "direction_audits_pass",directionPass, ...
    "strict_positivity_pass",positivityPass, ...
    "no_full_direction_fallback",noFallback, ...
    "forbidden_execution_pass",forbiddenPass, ...
    "runtime_factor_trace_complete",forbiddenPass, ...
    "stable_v2_refinement_pass",refinementPass, ...
    "all_pass",acceptedCount>0 && height(directions)==acceptedCount && ...
        directionPass && positivityPass && noFallback && ...
        forbiddenPass && refinementPass);
end

function metadata = checkpoint_metadata(iteration,gitCommit,inputHashes, ...
        configSha,initialFingerprint,linearizationFingerprint,csvSha, ...
        directionSha,refinementSha,maxPasses)
metadata = struct( ...
    "iteration",iteration, ...
    "state_revision",iteration, ...
    "input_hashes",inputHashes, ...
    "config_sha256",char(configSha), ...
    "git_commit",char(gitCommit), ...
    "linearization_fingerprint",char(linearizationFingerprint), ...
    "state_fingerprint","", ...
    "iteration_csv_sha256",char(csvSha), ...
    "direction_csv_sha256",char(directionSha), ...
    "refinement_csv_sha256",char(refinementSha), ...
    "initial_state_fingerprint",char(initialFingerprint), ...
    "recursive_refinement_max_passes",maxPasses);
end

function value = identity_metadata(gitCommit,inputHashes,configSha, ...
        initialFingerprint,maxPasses)
value = struct( ...
    "git_commit",char(gitCommit), ...
    "input_hashes",inputHashes, ...
    "config_sha256",char(configSha), ...
    "initial_state_fingerprint",char(initialFingerprint), ...
    "recursive_refinement_max_passes",maxPasses);
end

function audit = replay_last_accepted_iteration(runContext,state,data,index, ...
        config,chainId,eqScale,dualScale,iterationTable,directionTable,expected)
revision = state.state_revision;
if revision==0
    audit = struct("performed",false,"passed",true, ...
        "reason","initial_checkpoint", ...
        "full_kkt_audit_performed",false, ...
        "full_kkt_direction_solve_count",0);
    return
end
[previous,~,previousAudit] = load_stage_a4_checkpoint(runContext, ...
    "Revision",revision-1,"ExpectedMetadata",expected);
replayed = execute_stage_a4_iteration(previous.state,data,index,config, ...
    "StepStrategy","independent", ...
    "ObjectiveScaleMode","positive_scalar_unitization", ...
    "DiagnosticObjectiveChainId",chainId, ...
    "RecursiveRefinementMaxPasses",3, ...
    "EqualityResidualReferenceScale",eqScale, ...
    "DualResidualReferenceScale",dualScale);
stateExact = canonical_state_equal(replayed.state_after,state);
row = directionTable(revision,:);
directionExact = ...
    replayed.direction_audit.direction_relative_error== ...
        row.direction_relative_error && ...
    replayed.direction_audit.recursive_kkt_relative_residual== ...
        row.recursive_full_kkt_relative_residual && ...
    replayed.direction_audit.full_kkt_relative_residual== ...
        row.full_kkt_relative_residual;
iterationExact = iterationTable.iteration(revision)==revision && ...
    iterationTable.state_revision(revision)==revision;
audit = struct( ...
    "performed",true, ...
    "revision",revision, ...
    "previous_checkpoint_passed",previousAudit.passed, ...
    "state_exact",stateExact, ...
    "direction_audit_exact",directionExact, ...
    "iteration_identity_exact",iterationExact, ...
    "full_kkt_audit_performed",true, ...
    "full_kkt_direction_solve_count",1, ...
    "passed",previousAudit.passed && stateExact && ...
        directionExact && iterationExact);
assert(audit.passed,"stageA4:a43:ResumeReplay", ...
    "The last accepted A4-3 transition did not replay exactly.");
end

function exact = canonical_state_equal(left,right)
names = ["xi","y","l","z","iteration_index","state_revision", ...
    "newton_direction_number","completed_newton_direction_count"];
exact = all(isfield(left,names)) && all(isfield(right,names));
for name = names
    exact = exact && isequal(left.(name),right.(name));
end
end

function [iterations,directions,refinement] = normalize_persisted_tables( ...
        iterations,directions,refinement,capacityNames)
iterations = normalize_numeric_columns(iterations, ...
    ["iteration","state_revision","objective_scaled", ...
    "objective_original","r_eq_inf","r_ineq_inf", ...
    "physical_inequality_violation","r_dual_scaled_inf", ...
    "r_dual_original_mapped_inf","r_comp_scaled_inf", ...
    "mean_lz_scaled","ltz_scaled","mean_lz_original_mapped", ...
    "gap_original_mapped","ltz_original_mapped", ...
    "mapped_y_inf","mapped_z_inf", ...
    "eta_eq","eta_dual","eta_gap", ...
    "candidate_alpha_primal","applied_alpha_primal", ...
    "candidate_alpha_dual","applied_alpha_dual","min_l","min_z", ...
    "centering_sigma","fraction_to_boundary_tau", ...
    "recursive_refinement_max_passes", ...
    "recursive_refinement_selected_pass_max", ...
    "recursive_refinement_selected_pass_total", ...
    "recursive_refinement_passes_attempted_total", ...
    "fixed_zero_count","fixed_zero_maximum_absolute_value", ...
    "fixed_zero_maximum_absolute_direction", ...
    "iteration_seconds","cumulative_seconds",capacityNames.']);
directions = normalize_numeric_columns(directions, ...
    ["iteration","state_revision_before","state_revision_after", ...
    "direction_relative_error","xi_relative_error","y_relative_error", ...
    "l_relative_error","z_relative_error", ...
    "recursive_full_kkt_relative_residual", ...
    "full_kkt_relative_residual","maximum_direction_difference", ...
    "maximum_direction_index","maximum_recursive_residual", ...
    "maximum_recursive_residual_row","maximum_full_residual", ...
    "maximum_full_residual_row","full_kkt_dimension"]);
refinement = normalize_numeric_columns(refinement, ...
    ["iteration","state_revision","day_id","maximum_passes", ...
    "selected_pass","passes_attempted", ...
    "initial_maximum_column_relative", ...
    "final_maximum_column_relative","residual_reduction_ratio", ...
    "rhs_count","additional_factorization_count"]);
iterations = normalize_text_columns(iterations, ...
    ["primal_limiter","dual_limiter","step_strategy", ...
    "objective_scale_mode"]);
directions = normalize_text_columns(directions, ...
    ["maximum_error_location","linearization_identity"]);
refinement = normalize_text_columns(refinement, ...
    ["object_type","stop_reason"]);
for name = ["convergence_passed","common_step_used", ...
        "dynamic_sigma_used","predictor_corrector_used", ...
        "line_search_used","regularization_used", ...
        "automatic_symmetrization_used","parallel_used", ...
        "full_kkt_direction_fallback_used","fixed_zero_exact"]
    iterations.(name) = to_logical_column(iterations.(name));
end
for name = ["no_full_direction_fallback","full_kkt_audit_only", ...
        "recursive_direction_is_official"]
    directions.(name) = to_logical_column(directions.(name));
end
for name = ["full_kkt_direction_consumed", ...
        "residual_operator_exact_original","factor_context_unchanged"]
    refinement.(name) = to_logical_column(refinement.(name));
end
end

function value = normalize_text_columns(value,names)
available = string(value.Properties.VariableNames);
for name = intersect(names,available,"stable")
    value.(name) = string(value.(name));
end
end

function value = normalize_numeric_columns(value,names)
available = string(value.Properties.VariableNames);
for name = intersect(names,available,"stable")
    if ~isnumeric(value.(name))
        value.(name) = str2double(string(value.(name)));
    end
end
end

function value = to_logical_column(value)
if islogical(value)
    return
end
text = lower(string(value));
assert(all(ismember(text,["true","false"])), ...
    "stageA4:a43:PersistedLogical", ...
    "A persisted logical evidence column contains an invalid value.");
value = text=="true";
end

function value = empty_iteration_table(names)
template = make_iteration_row_template();
value = struct2table(template,"AsArray",true);
value = value([],:);
for name = names.'
    value.(matlab.lang.makeValidName(char(name))) = zeros(0,1);
end
end

function value = make_iteration_row_template()
value = struct( ...
    "iteration",0,"state_revision",0, ...
    "objective_scaled",0,"objective_original",0, ...
    "r_eq_inf",0,"r_ineq_inf",0, ...
    "physical_inequality_violation",0, ...
    "r_dual_scaled_inf",0,"r_dual_original_mapped_inf",0, ...
    "r_comp_scaled_inf",0,"mean_lz_scaled",0,"ltz_scaled",0, ...
    "mean_lz_original_mapped",0,"gap_original_mapped",0, ...
    "ltz_original_mapped",0, ...
    "mapped_y_inf",0,"mapped_z_inf",0, ...
    "eta_eq",0,"eta_dual",0,"eta_gap",0, ...
    "candidate_alpha_primal",0,"applied_alpha_primal",0, ...
    "candidate_alpha_dual",0,"applied_alpha_dual",0, ...
    "primal_limiter","","dual_limiter","", ...
    "centering_sigma",0,"fraction_to_boundary_tau",0, ...
    "step_strategy","","objective_scale_mode","", ...
    "recursive_refinement_max_passes",0, ...
    "common_step_used",false,"dynamic_sigma_used",false, ...
    "predictor_corrector_used",false,"line_search_used",false, ...
    "regularization_used",false, ...
    "automatic_symmetrization_used",false, ...
    "parallel_used",false, ...
    "full_kkt_direction_fallback_used",false, ...
    "fixed_zero_count",0, ...
    "fixed_zero_maximum_absolute_value",0, ...
    "fixed_zero_maximum_absolute_direction",0, ...
    "fixed_zero_exact",false, ...
    "min_l",0,"min_z",0, ...
    "recursive_refinement_selected_pass_max",0, ...
    "recursive_refinement_selected_pass_total",0, ...
    "recursive_refinement_passes_attempted_total",0, ...
    "iteration_seconds",0,"cumulative_seconds",0, ...
    "convergence_passed",false);
end

function value = empty_direction_table()
template = struct( ...
    "iteration",0,"state_revision_before",0, ...
    "state_revision_after",0,"direction_relative_error",0, ...
    "xi_relative_error",0,"y_relative_error",0, ...
    "l_relative_error",0,"z_relative_error",0, ...
    "recursive_full_kkt_relative_residual",0, ...
    "full_kkt_relative_residual",0, ...
    "maximum_direction_difference",0,"maximum_direction_index",0, ...
    "maximum_error_location","", ...
    "maximum_recursive_residual",0, ...
    "maximum_recursive_residual_row",0, ...
    "maximum_full_residual",0,"maximum_full_residual_row",0, ...
    "no_full_direction_fallback",false, ...
    "full_kkt_audit_only",false, ...
    "recursive_direction_is_official",false, ...
    "full_kkt_dimension",0,"linearization_identity","");
value = struct2table(template,"AsArray",true);
value = value([],:);
end

function value = empty_refinement_table()
value = table(zeros(0,1),zeros(0,1),strings(0,1),nan(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),strings(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    false(0,1),false(0,1), ...
    'VariableNames',{'iteration','state_revision','object_type','day_id', ...
    'maximum_passes','selected_pass','passes_attempted', ...
    'initial_maximum_column_relative', ...
    'final_maximum_column_relative','residual_reduction_ratio', ...
    'stop_reason','rhs_count','additional_factorization_count', ...
    'full_kkt_direction_consumed','residual_operator_exact_original', ...
    'factor_context_unchanged'});
end

function value = cumulative_time_from_table(tableValue)
if isempty(tableValue)
    value = 0;
else
    value = tableValue.cumulative_seconds(end);
end
end

function recover_initial_checkpoint_transaction(context,state,metrics, ...
        linearization,gitCommit,inputHashes,configSha,initialFingerprint, ...
        capacityNames,maxPasses)
if isfile(context.checkpoint_manifest_path)
    return
end
iterations = empty_iteration_table(capacityNames);
directions = empty_direction_table();
refinement = empty_refinement_table();
iterationPath = fullfile(context.iterations_dir,"iteration_summary.csv");
directionPath = fullfile(context.iterations_dir,"direction_audit.csv");
refinementPath = fullfile(context.iterations_dir,"recursive_refinement.csv");
metricsPath = fullfile(context.iterations_dir,"initial_metrics.json");
archiveRoot = fullfile(context.iterations_dir, ...
    "orphaned_initial_transaction", ...
    string(datetime("now","TimeZone","UTC", ...
    "Format","yyyyMMdd_HHmmss_SSS")));
ensure_exact_or_archive_table(iterationPath,iterations,archiveRoot);
ensure_exact_or_archive_table(directionPath,directions,archiveRoot);
ensure_exact_or_archive_table(refinementPath,refinement,archiveRoot);
revisionRoot = fullfile(context.iterations_dir,"revisions","revision_000");
snapshotPassed = false;
snapshot = struct();
if isfolder(revisionRoot)
    try
        snapshot = load_validated_revision_snapshot(context,0);
        snapshotPassed = true;
    catch
        snapshotPassed = false;
    end
    if ~snapshotPassed
        ensure_directory(archiveRoot);
        target = fullfile(archiveRoot,"revision_000_incomplete");
        [moved,message] = movefile(revisionRoot,target);
        assert(moved,"stageA4:a43:InitialTransactionArchive","%s",message);
    end
end
if ~snapshotPassed
    snapshot = write_revision_snapshot( ...
        context,0,iterations,directions,refinement);
end
if isfile(metricsPath)
    persistedMetrics = jsondecode(fileread(metricsPath));
    metricsPassed = string(persistedMetrics.convergence_coordinate)== ...
        string(metrics.convergence_coordinate) && ...
        double(persistedMetrics.objective_scale_factor)== ...
        double(metrics.objective_scale_factor);
    if ~metricsPassed
        ensure_directory(archiveRoot);
        [moved,message] = movefile(metricsPath, ...
            fullfile(archiveRoot,"initial_metrics_inconsistent.json"));
        assert(moved,"stageA4:a43:InitialTransactionArchive","%s",message);
    end
end
if ~isfile(metricsPath)
    write_json_file(metricsPath,metrics);
end
metadata = checkpoint_metadata(0,gitCommit,inputHashes,configSha, ...
    initialFingerprint,compute_stage_a4_rns1_fingerprint( ...
    linearization,"linearization"), ...
    snapshot.iteration_summary_sha256, ...
    snapshot.direction_audit_sha256, ...
    snapshot.recursive_refinement_sha256,maxPasses);
metadata.state_fingerprint = initialFingerprint;
write_stage_a4_checkpoint(context,state,metadata);
end

function ensure_exact_or_archive_table(pathValue,expected,archiveRoot)
temporary = string(tempname(tempdir))+".csv";
guard = onCleanup(@()delete_if_present(temporary));
write_table_csv_17g(temporary,expected);
expectedHash = compute_sha256_file(temporary);
if isfile(pathValue)
    if lower(string(compute_sha256_file(pathValue)))==lower(string(expectedHash))
        clear guard
        return
    end
    ensure_directory(archiveRoot);
    [~,base,extension] = fileparts(pathValue);
    target = fullfile(archiveRoot,string(base)+string(extension));
    [moved,message] = movefile(pathValue,target);
    assert(moved,"stageA4:a43:InitialTransactionArchive","%s",message);
end
write_table_csv_17g_atomic(pathValue,expected);
clear guard
end

function ensure_directory(pathValue)
if isfolder(pathValue)
    return
end
[created,message] = mkdir(pathValue);
assert(created,"stageA4:a43:RecoveryDirectory","%s",message);
end

function delete_if_present(pathValue)
if isfile(pathValue)
    delete(pathValue);
end
end

function snapshot = write_revision_snapshot(context,revision, ...
        iterations,directions,refinement)
revisionRoot = fullfile(context.iterations_dir,"revisions", ...
    "revision_"+compose("%03d",revision));
assert(~isfile(revisionRoot)&&~isfolder(revisionRoot), ...
    "stageA4:a43:RevisionSnapshotExists", ...
    "Refusing to overwrite revision snapshot %s.",revisionRoot);
[created,message] = mkdir(revisionRoot);
assert(created,"stageA4:a43:RevisionSnapshotCreate","%s",message);
iterationPath = fullfile(revisionRoot,"iteration_summary.csv");
directionPath = fullfile(revisionRoot,"direction_audit.csv");
refinementPath = fullfile(revisionRoot,"recursive_refinement.csv");
write_table_csv_17g(iterationPath,iterations);
write_table_csv_17g(directionPath,directions);
write_table_csv_17g(refinementPath,refinement);
snapshot = struct( ...
    "revision",revision, ...
    "root",string(revisionRoot), ...
    "iteration_summary_path",string(iterationPath), ...
    "direction_audit_path",string(directionPath), ...
    "recursive_refinement_path",string(refinementPath), ...
    "iteration_summary_sha256",compute_sha256_file(iterationPath), ...
    "direction_audit_sha256",compute_sha256_file(directionPath), ...
    "recursive_refinement_sha256",compute_sha256_file(refinementPath));
write_json_file(fullfile(revisionRoot,"snapshot_manifest.json"),snapshot);
snapshot = load_validated_revision_snapshot(context,revision);
end

function publish_revision_snapshot(snapshot,iterationTarget, ...
        directionTarget,refinementTarget)
publish_csv(snapshot.iteration_summary_path,iterationTarget);
publish_csv(snapshot.direction_audit_path,directionTarget);
publish_csv(snapshot.recursive_refinement_path,refinementTarget);
end

function publish_csv(source,target)
source = char(string(source));
target = char(string(target));
ensure_parent_directory(target);
temporary = [tempname(fileparts(target)),'.csv.pending'];
cleanup = onCleanup(@()delete_if_present(temporary));
[copied,message] = copyfile(source,temporary);
assert(copied,"stageA4:a43:RevisionSnapshotPublish","%s",message);
[moved,message] = movefile(temporary,target,"f");
assert(moved,"stageA4:a43:RevisionSnapshotPublish","%s",message);
clear cleanup
assert(lower(string(compute_sha256_file(target)))== ...
    lower(string(compute_sha256_file(source))), ...
    "stageA4:a43:RevisionSnapshotPublish", ...
    "Published cumulative CSV differs from its immutable snapshot.");
end

function snapshot = load_validated_revision_snapshot(context,revision)
revisionRoot = fullfile(context.iterations_dir,"revisions", ...
    "revision_"+compose("%03d",revision));
manifestPath = fullfile(revisionRoot,"snapshot_manifest.json");
assert(isfolder(revisionRoot) && isfile(manifestPath), ...
    "stageA4:a43:RevisionSnapshotMissing", ...
    "Revision %d snapshot or manifest is missing.",revision);
snapshot = jsondecode(fileread(manifestPath));
required = ["revision","root","iteration_summary_path", ...
    "direction_audit_path","recursive_refinement_path", ...
    "iteration_summary_sha256","direction_audit_sha256", ...
    "recursive_refinement_sha256"];
assert(isstruct(snapshot)&&isscalar(snapshot) && ...
    all(isfield(snapshot,cellstr(required))) && ...
    double(snapshot.revision)==revision, ...
    "stageA4:a43:RevisionSnapshotSchema", ...
    "Revision %d snapshot manifest is invalid.",revision);

expectedPaths = [ ...
    string(revisionRoot)
    fullfile(revisionRoot,"iteration_summary.csv")
    fullfile(revisionRoot,"direction_audit.csv")
    fullfile(revisionRoot,"recursive_refinement.csv")];
recordedPaths = [string(snapshot.root)
    string(snapshot.iteration_summary_path)
    string(snapshot.direction_audit_path)
    string(snapshot.recursive_refinement_path)];
for k = 1:numel(expectedPaths)
    assert(same_canonical_path(recordedPaths(k),expectedPaths(k)), ...
        "stageA4:a43:RevisionSnapshotPath", ...
        "Revision %d snapshot path %d is not canonical.",revision,k);
end

hashFields = ["iteration_summary_sha256","direction_audit_sha256", ...
    "recursive_refinement_sha256"];
for k = 1:numel(hashFields)
    recordedHash = lower(strip(string(snapshot.(hashFields(k)))));
    assert(is_sha256_text(recordedHash) && ...
        isfile(expectedPaths(k+1)) && ...
        lower(string(compute_sha256_file(expectedPaths(k+1))))== ...
            recordedHash, ...
        "stageA4:a43:RevisionSnapshotHash", ...
        "Revision %d %s hash is invalid.",revision,hashFields(k));
    snapshot.(hashFields(k)) = recordedHash;
end
snapshot.root = expectedPaths(1);
snapshot.iteration_summary_path = expectedPaths(2);
snapshot.direction_audit_path = expectedPaths(3);
snapshot.recursive_refinement_path = expectedPaths(4);
end

function passed = same_canonical_path(left,right)
left = string(char(java.io.File( ...
    char(string(left))).getCanonicalPath()));
right = string(char(java.io.File( ...
    char(string(right))).getCanonicalPath()));
if ispc
    passed = strcmpi(left,right);
else
    passed = left==right;
end
end

function passed = is_sha256_text(value)
passed = isscalar(value) && ...
    ~isempty(regexp(char(value),"^[0-9a-f]{64}$","once"));
end

function repair_cumulative_evidence_from_snapshot(context,revision, ...
        checkpointRecord,iterationTarget,directionTarget,refinementTarget)
snapshot = load_validated_revision_snapshot(context,revision);
iterationSnapshotHash = lower(string(snapshot.iteration_summary_sha256));
checkpointIterationHashPassed = iterationSnapshotHash== ...
    lower(string(checkpointRecord.iteration_csv_sha256));
assert(double(snapshot.revision)==revision && ...
    checkpointIterationHashPassed && ...
        lower(string(checkpointRecord.direction_csv_sha256))== ...
        lower(string(snapshot.direction_audit_sha256)) && ...
        lower(string(checkpointRecord.refinement_csv_sha256))== ...
        lower(string(snapshot.recursive_refinement_sha256)) && ...
    iterationSnapshotHash== ...
        lower(string(snapshot.iteration_summary_sha256)) && ...
    lower(string(compute_sha256_file( ...
        snapshot.direction_audit_path)))== ...
        lower(string(snapshot.direction_audit_sha256)) && ...
    lower(string(compute_sha256_file( ...
        snapshot.recursive_refinement_path)))== ...
        lower(string(snapshot.recursive_refinement_sha256)), ...
    "stageA4:a43:ResumeSnapshotHash", ...
    "The selected checkpoint revision snapshot failed SHA256 validation.");
if ~isfile(iterationTarget) || ...
        lower(string(compute_sha256_file(iterationTarget)))~= ...
        lower(string(snapshot.iteration_summary_sha256)) || ...
        ~isfile(directionTarget) || ...
        lower(string(compute_sha256_file(directionTarget)))~= ...
        lower(string(snapshot.direction_audit_sha256)) || ...
        ~isfile(refinementTarget) || ...
        lower(string(compute_sha256_file(refinementTarget)))~= ...
        lower(string(snapshot.recursive_refinement_sha256))
    publish_revision_snapshot(snapshot,iterationTarget, ...
        directionTarget,refinementTarget);
end
end

function failure = make_failure(cause,iteration,state)
failure = struct("present",true,"iteration",iteration, ...
    "identifier",string(cause.identifier), ...
    "message",string(cause.message), ...
    "state_revision",state.state_revision, ...
    "evidence_path","", ...
    "report",string(getReport(cause,"extended","hyperlinks","off")));
end

function failure = save_failure_evidence( ...
        context,kind,invocation,state,failure)
timestamp = string(datetime("now","TimeZone","UTC", ...
    "Format","yyyyMMdd_HHmmss_SSS"));
baseName = lower(string(kind))+"_inv"+compose("%03d",invocation)+ ...
    "_iter"+compose("%03d",failure.iteration)+"_rev"+ ...
    compose("%03d",failure.state_revision)+"_"+timestamp+".mat";
pathValue = fullfile(context.checkpoints_dir,baseName);
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageA4:a43:FailureEvidenceExists", ...
    "Refusing to overwrite A4-3 failure evidence.");
relativePath = "checkpoints/"+baseName;
failure.evidence_path = relativePath;
failure.state_fingerprint = ...
    compute_stage_a4_checkpoint_state_fingerprint(state);
save_mat_artifact(pathValue,"state_before_failure",state, ...
    "failure",failure);
sha256 = compute_sha256_file(pathValue);
ledgerPath = fullfile(context.checkpoints_dir,"failure_ledger.csv");
if isfile(ledgerPath)
    checkpointAudit = validate_stage_a4_checkpoint(context);
    assert(checkpointAudit.failure_ledger_audit.passed, ...
        "stageA4:a43:FailureLedgerPriorAudit", ...
        "Existing failure ledger did not pass independent validation.");
    ledger = checkpointAudit.failure_ledger_audit.ledger;
else
    ledger = empty_failure_ledger();
end
sequence = height(ledger)+1;
row = table(sequence,string(context.run_id),invocation, ...
    double(failure.iteration),double(failure.state_revision),string(kind), ...
    string(failure.identifier),string(failure.message), ...
    string(failure.state_fingerprint),relativePath,string(sha256),timestamp, ...
    'VariableNames',{'failure_sequence','run_id','solver_invocation', ...
    'iteration','state_revision','terminal_state','identifier','message', ...
    'state_fingerprint','relative_path','sha256','recorded_at_utc'});
ledger = [ledger;row];
write_table_csv_17g_atomic(ledgerPath,ledger);
checkpointAudit = validate_stage_a4_checkpoint(context);
assert(checkpointAudit.failure_ledger_audit.passed && ...
    checkpointAudit.failure_ledger_audit.failure_count==sequence, ...
    "stageA4:a43:FailureLedgerPostWriteAudit", ...
    "New failure evidence did not pass independent ledger validation.");
end

function value = empty_failure_ledger()
value = table(zeros(0,1),strings(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    'VariableNames',{'failure_sequence','run_id','solver_invocation', ...
    'iteration','state_revision','terminal_state','identifier','message', ...
    'state_fingerprint','relative_path','sha256','recorded_at_utc'});
end

function require_run_context(context)
required = ["root","run_id","run_manifest_path","effective_config_path", ...
    "iterations_dir","checkpoints_dir"];
assert(all(isfield(context,required)) && isfolder(context.root) && ...
    isfile(context.run_manifest_path), ...
    "stageA4:a43:RunContext","A valid unique run context is required.");
manifest = jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.stage_id)=="stage_A4" && ...
    string(manifest.status)=="RUNNING", ...
    "stageA4:a43:RunManifest", ...
    "A4-3 requires a RUNNING stage_A4 manifest.");
end
