function result = solve_stage_a_multiday_diagnostic_rhs_responses( ...
        lin,recursive)
%SOLVE_STAGE_A_MULTIDAY_DIAGNOSTIC_RHS_RESPONSES Split one Newton RHS.
%
% This read-only diagnostic reuses the already computed hourly Thomas
% factors, daily responses, and 16-dimensional core factor.  It solves
% four simultaneous response columns (equality, inequality,
% complementarity, and dual residual sources) without another
% factorization, state update, complete-KKT solve, or complete-direction
% input.

arguments
    lin (1,1) struct
    recursive (1,1) struct
end

contract = stage_a_multiday_linearization_contract(lin);
assert(contract.stage_id=="stage_A4" && ...
    isequal(contract.identity,recursive.linearization_identity) && ...
    recursive.no_full_direction_fallback && ...
    ~recursive.full_direction_consumed, ...
    "stageA4:a42d1r:DiagnosticResponseContext", ...
    "The diagnostic responses require the retained official A4 "+ ...
    "recursive factorization with no complete-direction fallback.");
assert(numel(recursive.daily_thomas)==contract.n_days && ...
    numel(recursive.daily_responses)==contract.n_days && ...
    isfield(recursive.core,"factor"), ...
    "stageA4:a42d1r:RetainedFactorization", ...
    "The retained recursive result is missing daily or core factors.");

sourceNames = ["equality";"inequality";"complementarity";"dual"];
sourceCount = numel(sourceNames);
bXi = zeros(contract.nx,sourceCount);
bEq = zeros(contract.neq,sourceCount);
bEq(:,1) = -contract.r_eq;
bXi(:,2) = -sparse(lin.G.')*((contract.z./contract.l).* ...
    contract.r_ineq);
bXi(:,3) = sparse(lin.G.')*(contract.r_comp./contract.l);
bXi(:,4) = -contract.r_dual;
reducedRhs = [bXi;bEq];

assembly = assemble_stage_a_multiday_full_kkt(lin);
fullRhs = zeros(assembly.dimension,sourceCount);
fullRhs(assembly.slices.equality_rows,1) = -contract.r_eq;
fullRhs(assembly.slices.slack_rows,2) = -contract.r_ineq;
fullRhs(assembly.slices.complementarity_rows,3) = -contract.r_comp;
fullRhs(assembly.slices.stationarity_rows,4) = -contract.r_dual;

fullRhsRebuildScaled = scaled_sum_error(fullRhs,assembly.rhs);
reducedRhsRebuildScaled = scaled_sum_error( ...
    reducedRhs,recursive.reduced.rhs);

dayWork = repmat(empty_day_work(sourceCount),contract.n_days,1);
for d = 1:contract.n_days
    day = recursive.partition.day(d);
    responsePosition = find( ...
        [recursive.daily_responses.day_id]==contract.days(d),1,"first");
    assert(~isempty(responsePosition) && day.day_id==contract.days(d), ...
        "stageA4:a42d1r:DailyResponseIdentity", ...
        "No retained daily response exists for day %d.", ...
        contract.days(d));
    response = recursive.daily_responses(responsePosition);
    rhsV = zeros(day.hourly_chain_dimension,sourceCount);
    for t = 1:contract.n_hours
        rows = day.block_offsets.start_index(t): ...
            day.block_offsets.end_index(t);
        x = contract.x_by_day_hour{d,t};
        y = contract.y_by_day_hour{d,t};
        rhsV(rows,:) = [bXi(x,:);bEq(y,:)];
    end
    [a,daySolve] = solve_day_rhs_with_retained_factors( ...
        day,recursive.daily_thomas(d),rhsV);
    c = bXi(contract.q_day_by_day{d},:)-day.B.'*a;
    beta = bEq(contract.y_binding_by_day{d},:);
    gamma = c-response.S*beta;

    dayWork(d).day_id = contract.days(d);
    dayWork(d).a = a;
    dayWork(d).c = c;
    dayWork(d).beta = beta;
    dayWork(d).gamma = gamma;
    dayWork(d).S = response.S;
    dayWork(d).U = response.U;
    dayWork(d).rhs_v = rhsV;
    dayWork(d).solve = daySolve;
end

[dayIdsSorted,sortOrder] = sort([dayWork.day_id]);
assert(isequal(dayIdsSorted,contract.days), ...
    "stageA4:a42d1r:DaySort", ...
    "Diagnostic daily responses must sort to days 14 through 20.");
gammaSum = zeros(14,sourceCount);
for position = sortOrder
    gammaSum = gammaSum+dayWork(position).gamma;
end
coreRhs = [bXi(contract.q_global,:)+gammaSum; ...
    bEq(contract.y_duration,:)];
[coreSolution,coreSolve] = solve_with_ldl_factor( ...
    recursive.core.factor,coreRhs, ...
    "stage_A4_A4_2D_1R_four_source_core_rhs");

deltaXi = zeros(contract.nx,sourceCount);
deltaY = zeros(contract.neq,sourceCount);
deltaXi(contract.q_global,:) = coreSolution(1:14,:);
deltaY(contract.y_duration,:) = coreSolution(15:16,:);
for d = contract.n_days:-1:1
    work = dayWork(d);
    deltaQDay = coreSolution(1:14,:)+work.beta;
    deltaPi = work.c-work.S*deltaQDay;
    deltaXi(contract.q_day_by_day{d},:) = deltaQDay;
    deltaY(contract.y_binding_by_day{d},:) = deltaPi;
    v = work.a-work.U*deltaQDay;
    for t = contract.n_hours:-1:1
        rows = recursive.partition.day(d).block_offsets.start_index(t): ...
            recursive.partition.day(d).block_offsets.end_index(t);
        block = recursive.partition.day(d).hour(t);
        local = v(rows,:);
        deltaXi(contract.x_by_day_hour{d,t},:) = ...
            local(1:block.n_primal,:);
        deltaY(contract.y_by_day_hour{d,t},:) = ...
            local(block.n_primal+(1:block.n_equalities),:);
    end
    dayWork(d).delta_q_day = deltaQDay;
    dayWork(d).delta_pi = deltaPi;
end

bIneq = zeros(contract.nineq,sourceCount);
bComp = zeros(contract.nineq,sourceCount);
bIneq(:,2) = -contract.r_ineq;
bComp(:,3) = -contract.r_comp;
gDelta = sparse(lin.G)*deltaXi;
deltaL = bIneq-gDelta;
deltaZ = (bComp-contract.z.*deltaL)./contract.l;
directions = [deltaXi;deltaY;deltaL;deltaZ];
assert(all(isfinite(directions),"all"), ...
    "stageA4:a42d1r:DiagnosticResponseNonfinite", ...
    "The four diagnostic response columns contain NaN or Inf.");

fullResidual = assembly.matrix*directions-fullRhs;
fullResidualScale = max(ones(size(fullResidual)), ...
    abs(assembly.matrix)*abs(directions)+abs(fullRhs));
sourceKktScaled = max(abs(fullResidual)./fullResidualScale,[],1).';
directionRebuildScaled = scaled_sum_error( ...
    directions,recursive.direction);
componentRebuildScaled = [ ...
    scaled_sum_error(deltaXi,recursive.components.xi)
    scaled_sum_error(deltaY,recursive.components.y)
    scaled_sum_error(deltaL,recursive.components.l)
    scaled_sum_error(deltaZ,recursive.components.z)];
threshold = 2048*eps;

result = struct();
result.stage_id = contract.stage_id;
result.linearization_identity = contract.identity;
result.source_names = sourceNames;
result.full_rhs_by_source = fullRhs;
result.reduced_rhs_by_source = reducedRhs;
result.direction_by_source = directions;
result.components = struct( ...
    "xi",deltaXi,"y",deltaY,"l",deltaL,"z",deltaZ);
result.day = dayWork;
result.day_ids_sorted = dayIdsSorted;
result.core_rhs_by_source = coreRhs;
result.core_solution_by_source = coreSolution;
result.audit = struct( ...
    "diagnostic_rhs_count",sourceCount, ...
    "retained_hourly_factorization_reused",true, ...
    "retained_core_factorization_reused",true, ...
    "additional_hourly_factorization_count",0, ...
    "additional_core_factorization_count",0, ...
    "additional_state_update_count",0, ...
    "additional_complete_kkt_solve_count",0, ...
    "complete_direction_consumed",false, ...
    "full_direction_fallback",false, ...
    "full_rhs_reconstruction_scaled_error", ...
        fullRhsRebuildScaled, ...
    "reduced_rhs_reconstruction_scaled_error", ...
        reducedRhsRebuildScaled, ...
    "source_complete_kkt_scaled_residual",sourceKktScaled, ...
    "maximum_source_complete_kkt_scaled_residual", ...
        max(sourceKktScaled), ...
    "direction_reconstruction_scaled_error", ...
        directionRebuildScaled, ...
    "component_reconstruction_scaled_error", ...
        componentRebuildScaled, ...
    "threshold",threshold, ...
    "passed",fullRhsRebuildScaled<=threshold && ...
        reducedRhsRebuildScaled<=threshold && ...
        max(sourceKktScaled)<=threshold && ...
        directionRebuildScaled<=threshold && ...
        max(componentRebuildScaled)<=threshold);
result.solve_diagnostics = struct( ...
    "day",{reshape([dayWork.solve],[],1)}, ...
    "core",coreSolve);
end

function [solution,diagnostics] = solve_day_rhs_with_retained_factors( ...
        day,thomas,rhs)
nHours = numel(day.hour);
assert(thomas.rhs_count==15 && ...
    numel(thomas.factors)==nHours && ...
    numel(thomas.elimination_multipliers)==nHours && ...
    size(rhs,2)==4, ...
    "stageA4:a42d1r:RetainedThomasContext", ...
    "The retained Thomas context or diagnostic RHS count is invalid.");

forward = cell(nHours,1);
byHour = cell(nHours,1);
solveAudit = cell(nHours,1);
for t = 1:nHours
    rows = day.block_offsets.start_index(t): ...
        day.block_offsets.end_index(t);
    current = rhs(rows,:);
    if t==1
        forward{t} = current;
    else
        forward{t} = current- ...
            thomas.elimination_multipliers{t}*forward{t-1};
    end
end
for t = nHours:-1:1
    current = forward{t};
    if t<nHours
        current = current-day.hour(t+1).E.'*byHour{t+1};
    end
    [byHour{t},solveAudit{t}] = solve_with_ldl_factor( ...
        thomas.factors{t},current, ...
        sprintf("stage_A4_A4_2D_1R_day_%d_hour_%d_four_rhs", ...
        day.day_id,day.hour(t).hour));
end
solution = vertcat(byHour{:});
residual = day.M*solution-rhs;
scale = max(ones(size(residual)), ...
    abs(day.M)*abs(solution)+abs(rhs));
diagnostics = struct( ...
    "day_id",day.day_id, ...
    "rhs_count",size(rhs,2), ...
    "additional_factorization_count",0, ...
    "maximum_scaled_residual",max(abs(residual)./scale,[],"all"), ...
    "back_solve",{solveAudit});
end

function value = scaled_sum_error(parts,actual)
difference = sum(parts,2)-actual;
scale = max(ones(size(actual)),sum(abs(parts),2)+abs(actual));
value = max(abs(difference)./scale);
end

function value = empty_day_work(sourceCount)
value = struct( ...
    "day_id",0, ...
    "a",zeros(0,sourceCount), ...
    "c",zeros(0,sourceCount), ...
    "beta",zeros(0,sourceCount), ...
    "gamma",zeros(0,sourceCount), ...
    "S",sparse(0,0), ...
    "U",zeros(0,0), ...
    "rhs_v",zeros(0,sourceCount), ...
    "delta_q_day",zeros(0,sourceCount), ...
    "delta_pi",zeros(0,sourceCount), ...
    "solve",struct());
end
