function result = solve_stage_b2b_recursive_direction(lin,options)
%SOLVE_STAGE_B2B_RECURSIVE_DIRECTION Compute exactly one recursive direction.
%
% The full-KKT audit direction is deliberately not an input or fallback.  A
% single shared linearization is consumed by elimination, daily borders,
% responses, the 16-D core, and strict reverse recovery.
arguments
    lin (1,1) struct
    options.SymmetryTolerance (1,1) double = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double = 0
    options.UseCongruenceScaling (1,1) logical = false
end
contract=stage_b2b_linearization_contract(lin);
reduced=eliminate_stage_b2b_inequality_directions(lin);
partition=partition_stage_b2b_recursive_system(lin,reduced, ...
    "AssemblyTolerance",1e-12);
for d=1:contract.n_days
    solved=solve_stage_b2b_day_border(partition.day(d),lin,reduced, ...
        "SymmetryTolerance",options.SymmetryTolerance, ...
        "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
        "UseCongruenceScaling",options.UseCongruenceScaling);
    response=form_stage_b2b_day_response(partition.day(d),solved,lin,reduced);
    if d==1
        responses=response;
    else
        responses(d,1)=response;
    end
end
aggregation=aggregate_stage_b2b_day_responses(responses,contract.days);
core=solve_stage_b2b_core16_ldl(partition,aggregation, ...
    "SymmetryTolerance",options.SymmetryTolerance, ...
    "ResidualRefinementMaxPasses",options.ResidualRefinementMaxPasses, ...
    "UseCongruenceScaling",options.UseCongruenceScaling);
recovery=recover_stage_b2b_recursive_direction(lin,partition,responses,core);
result=struct("stage_id","stage_B","milestone_id","B-2B", ...
    "linearization_identity",contract.identity,"direction",recovery.direction, ...
    "components",recovery.components,"reduced",reduced,"partition",partition, ...
    "responses",responses,"daily_responses",responses, ...
    "aggregation",aggregation,"core",core,"recovery",recovery, ...
    "fixed_zero",recovery.fixed_zero, ...
    "no_full_direction_fallback",true,"full_direction_consumed",false, ...
    "recursive_direction_executed",true,"full_ipm_executed",false, ...
    "optimization_executed",false,"parallel_executed",false, ...
    "diagnostics",struct("daily_response_count",numel(responses), ...
        "daily_response_dimension",14,"global_core_dimension",16, ...
        "total_chain_dimension",partition.total_hourly_chain_dimension, ...
        "total_augmented_chain_dimension",partition.total_augmented_chain_dimension));
end
