function core = solve_stage_a3_core16_ldl(partition,aggregation,options)
%SOLVE_STAGE_A3_CORE16_LDL Backward-compatible A3 core wrapper.
arguments
    partition (1,1) struct
    aggregation (1,1) struct
    options.SymmetryTolerance (1,1) double {mustBeNonnegative,mustBeFinite} = 1e-12
    options.ResidualRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
assert(string(partition.stage_id)=="stage_A3", ...
    "stageA3:solver:StageId", ...
    "The stage_A3 core wrapper requires a stage_A3 partition.");
core = solve_stage_a_multiday_core16_ldl(partition,aggregation, ...
    SymmetryTolerance=options.SymmetryTolerance, ...
    ResidualRefinementMaxPasses= ...
        options.ResidualRefinementMaxPasses);
end
