function result = solve_stage_a_multiday_full_kkt_direction(lin)
%SOLVE_STAGE_A_MULTIDAY_FULL_KKT_DIRECTION Solve the sparse audit system.

arguments
    lin (1,1) struct
end

assembly = assemble_stage_a_multiday_full_kkt(lin);
lastwarn("");
direction = assembly.matrix\assembly.rhs;
[warningMessage,warningId] = lastwarn;
if strlength(string(warningId))>0 || strlength(string(warningMessage))>0
    error("stageAMultiday:solver:FullKktSolveWarning", ...
        "%s sparse audit solve emitted warning %s: %s", ...
        assembly.stage_id,string(warningId),string(warningMessage));
end
assert(all(isfinite(direction)),"stageAMultiday:solver:FullDirectionNonfinite", ...
    "Formal multi-day sparse audit direction contains NaN or Inf.");
residual = assembly.matrix*direction-assembly.rhs;

result = struct();
result.stage_id = assembly.stage_id;
result.method = "sparse_backslash_audit";
result.linearization_identity = assembly.linearization_identity;
result.direction = direction;
result.components = struct( ...
    "xi",direction(assembly.slices.xi), ...
    "y",direction(assembly.slices.y), ...
    "l",direction(assembly.slices.l), ...
    "z",direction(assembly.slices.z));
result.kkt = assembly;
result.diagnostics = struct( ...
    "relative_residual",norm(residual,2)/max(1,norm(assembly.rhs,2)), ...
    "max_absolute_residual",max(abs(residual)), ...
    "max_residual_row",find(abs(residual)==max(abs(residual)),1,"first"), ...
    "warning_id",string(warningId), ...
    "warning_message",string(warningMessage), ...
    "warning_present",false);
end
