function audit = verify_stage_a3_direction_equivalence( ...
        fullResult,recursiveResult,lin,thresholds)
%VERIFY_STAGE_A3_DIRECTION_EQUIVALENCE Backward-compatible A3 wrapper.
arguments
    fullResult (1,1) struct
    recursiveResult (1,1) struct
    lin (1,1) struct
    thresholds.DirectionRelative (1,1) double {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.RecursiveResidual (1,1) double {mustBeNonnegative,mustBeFinite} = 1e-10
    thresholds.FullResidualPreferred (1,1) double {mustBeNonnegative,mustBeFinite} = 1e-12
    thresholds.FullResidualMaximum (1,1) double {mustBeNonnegative,mustBeFinite} = 1e-10
end
assert(string(lin.stage_id)=="stage_A3","stageA3:solver:StageId", ...
    "The stage_A3 verification wrapper requires a stage_A3 linearization.");
audit = verify_stage_a_multiday_direction_equivalence( ...
    fullResult,recursiveResult,lin, ...
    DirectionRelative=thresholds.DirectionRelative, ...
    RecursiveResidual=thresholds.RecursiveResidual, ...
    FullResidualPreferred=thresholds.FullResidualPreferred, ...
    FullResidualMaximum=thresholds.FullResidualMaximum);
end
