function runtime = build_stage_b2c_legacy_runtime_audit_maps( ...
        data,index,template,config)
%BUILD_STAGE_B2C_LEGACY_RUNTIME_AUDIT_MAPS Compress canonical audit maps.

arguments
    data (1,1) struct
    index (1,1) struct
    template (1,1) struct
    config (1,1) struct
end
assert(isfield(index,"variable_index") && ...
    isfield(index,"constraint_index") && ...
    isfield(index,"stage_a_base_index") && ...
    string(index.scope.milestone_id)=="B-2C", ...
    "stageB2C:legacyRuntimeAuditMaps:CanonicalIndex", ...
    "Legacy runtime audit maps require the full B-2C canonical index.");

days = reshape(double(config.days),1,[]);
hours = reshape(double(config.hours),1,[]);
nDays = numel(days);
nHours = numel(hours);
variables = index.variable_index;
types = string(variables.asset_type);
names = string(variables.variable_name);
dayPosition = zeros(height(variables),1);
for d = 1:nDays
    dayPosition(variables.day==days(d)) = d;
end

physical = struct( ...
    "days",days,"hours",hours, ...
    "global_capacity_positions",uint32(template.maps.q_global(:)), ...
    "daily_capacity_positions",uint32(template.maps.q_day.'), ...
    "wind_positions",zeros(nDays,nHours,data.meta.nWind,"uint32"), ...
    "solar_positions",zeros(nDays,nHours,data.meta.nSolar,"uint32"), ...
    "hydro_positions",zeros(nDays,nHours,data.meta.nHydro,"uint32"), ...
    "thermal_positions",zeros(nDays,nHours,data.meta.nThermal,"uint32"), ...
    "charge_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"), ...
    "discharge_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"), ...
    "soc_positions",zeros(nDays,nHours,data.meta.nStorage,"uint32"));
physical.wind_positions = assign_positions(physical.wind_positions, ...
    variables,dayPosition,types=="wind" & names=="PW");
physical.solar_positions = assign_positions(physical.solar_positions, ...
    variables,dayPosition,types=="solar" & names=="PP");
physical.hydro_positions = assign_positions(physical.hydro_positions, ...
    variables,dayPosition,types=="hydro" & names=="PH");
physical.thermal_positions = assign_positions(physical.thermal_positions, ...
    variables,dayPosition,types=="thermal" & names=="PF");
physical.charge_positions = assign_positions(physical.charge_positions, ...
    variables,dayPosition,types=="storage" & names=="Pch");
physical.discharge_positions = assign_positions(physical.discharge_positions, ...
    variables,dayPosition,types=="storage" & names=="Pdis");
physical.soc_positions = assign_positions(physical.soc_positions, ...
    variables,dayPosition,types=="storage" & names=="SOC");

waterCanonical = index.water_constraint_index;
water = struct( ...
    "inequality_position",uint32(waterCanonical.inequality_position(:)), ...
    "day",uint16(waterCanonical.day(:)), ...
    "hydro_id",uint8(waterCanonical.hydro_id(:)), ...
    "bound_side",uint8(1+(string(waterCanonical.bound_type(:))=="upper")));

constraint = build_inequality_map(variables,types,names,water,template);
equality = build_equality_map(template);
fixedCount = height(index.fixed_zero_map);
assert(fixedCount==config.expected_stage_a_fixed_zero_count && ...
    all(index.fixed_zero_map.fixed_value==0) && ...
    all(index.fixed_zero_map.fixed_direction_value==0), ...
    "stageB2C:legacyRuntimeAuditMaps:FixedZero", ...
    "The legacy runtime audit fixed-zero contract changed.");

links = index.soc_link_map;
noInterday = ~any(links.predecessor_hour==24 & links.hour==1);
firstCount = zeros(nDays,1);
terminalCount = zeros(nDays,1);
for d = 1:nDays
    first = links(links.day==days(d) & links.hour==1,:);
    terminal = links(links.day==days(d) & links.terminal_equality,:);
    firstCount(d) = height(first);
    terminalCount(d) = height(terminal);
    noInterday = noInterday && height(first)==2 && ...
        all(isnan(first.predecessor_hour)) && ...
        all(first.predecessor_soc_global_index==0) && ...
        all(first.initial_energy_fraction==0.5) && ...
        height(terminal)==2 && all(terminal.hour==24) && ...
        all(terminal.terminal_energy_fraction==0.5);
end

runtime = struct( ...
    "version","stage-B2C-legacy-runtime-audit-maps-v1.0", ...
    "index_version",string(index.version), ...
    "scope",struct("days",days,"hours",hours, ...
        "milestone_id","B-2C","soc_boundary_mode", ...
        string(config.soc_boundary_mode),"time_scope_type", ...
        string(config.time_scope_type)), ...
    "counts",struct("variables",template.n_primal, ...
        "equalities",template.n_equalities, ...
        "base_inequalities",template.n_base_inequalities, ...
        "water_inequalities",template.n_water_inequalities, ...
        "inequalities",template.n_inequalities, ...
        "full_kkt_dimension",template.counts.full_kkt, ...
        "fixed_zero",fixedCount), ...
    "physical_map",physical,"water_map",water, ...
    "constraint_map",constraint,"equality_map",equality, ...
    "fixed_zero_runtime",struct("count",fixedCount, ...
        "all_exact_zero",true), ...
    "soc_boundary",struct("no_interday",logical(noInterday), ...
        "first_hour_row_count",uint8(firstCount), ...
        "terminal_row_count",uint8(terminalCount), ...
        "initial_fraction",0.5,"terminal_fraction",0.5));

assert(runtime.counts.variables==config.expected_stage_a_primal_dimension && ...
    runtime.counts.equalities==config.expected_stage_a_equality_dimension && ...
    runtime.counts.base_inequalities== ...
        config.expected_stage_a_inequality_dimension && ...
    runtime.counts.water_inequalities== ...
        config.expected_water_inequality_count && ...
    runtime.counts.full_kkt_dimension==config.expected_full_kkt_dimension && ...
    numel(runtime.constraint_map.kind)==runtime.counts.inequalities && ...
    runtime.soc_boundary.no_interday, ...
    "stageB2C:legacyRuntimeAuditMaps:Contract", ...
    "The legacy runtime audit maps failed the frozen model contract.");
end

function target = assign_positions(target,variables,dayPosition,mask)
mask = mask & variables.hour>0;
rows = find(mask);
if isempty(rows), return; end
linear = sub2ind(size(target),dayPosition(rows), ...
    double(variables.hour(rows)),double(variables.asset_id(rows)));
target(linear) = uint32(variables.global_index_start(rows));
end

function value = build_equality_map(template)
nDays = numel(template.days);
balance = zeros(24*nDays,1,"uint32");
soc = zeros(48*nDays+2*nDays,1,"uint32");
terminal = zeros(2*nDays,1,"uint32");
b = 0; s = 0; e = 0;
for d = 1:nDays
    for t = 1:24
        rows = template.maps.y_by_day_hour{d,t};
        b = b+1; balance(b) = uint32(rows(1));
        soc(s+(1:2)) = uint32(rows(2:3)); s = s+2;
        if t==24
            terminal(e+(1:2)) = uint32(rows(4:5)); e = e+2;
            soc(s+(1:2)) = uint32(rows(4:5)); s = s+2;
        end
    end
end
value = struct("power_balance_rows",balance, ...
    "soc_rows",soc(1:s),"terminal_soc_rows",terminal);
end

function value = build_inequality_map(variables,types,names,water,template)
n = template.n_inequalities;
value = struct("kind",zeros(n,1,"uint8"), ...
    "bound_side",zeros(n,1,"uint8"), ...
    "day",zeros(n,1,"uint16"),"hour",zeros(n,1,"uint8"), ...
    "asset_type",zeros(n,1,"uint8"), ...
    "asset_id",zeros(n,1,"uint8"), ...
    "variable",zeros(n,1,"uint8"), ...
    "capacity",zeros(n,1,"uint8"));
value.kind(1:28) = 1;
value.bound_side(1:28) = repmat(uint8([1;2]),14,1);
value.capacity(1:28) = repelem(uint8((1:14).'),2,1);
value.asset_id(1:28) = repelem(uint8([1:5,1:5,1:2,1:2].'),2,1);
value.asset_type(1:28) = repelem(uint8([6*ones(1,5),7*ones(1,5), ...
    8*ones(1,2),9*ones(1,2)].'),2,1);

hourly = find(variables.hour>0);
baseRows = 29:template.n_base_inequalities;
assert(numel(baseRows)==2*numel(hourly), ...
    "stageB2C:legacyRuntimeAuditMaps:BaseInequalityOrder", ...
    "The lower/upper hourly inequality order changed.");
value.kind(baseRows) = 2;
value.bound_side(baseRows) = repmat(uint8([1;2]),numel(hourly),1);
value.day(baseRows) = repelem(uint16(variables.day(hourly)),2,1);
value.hour(baseRows) = repelem(uint8(variables.hour(hourly)),2,1);
value.asset_id(baseRows) = repelem(uint8(variables.asset_id(hourly)),2,1);
value.asset_type(baseRows) = repelem(asset_type_code(types(hourly)),2,1);
value.variable(baseRows) = repelem(variable_code(names(hourly)),2,1);

waterRows = double(water.inequality_position);
value.kind(waterRows) = 3;
value.bound_side(waterRows) = water.bound_side;
value.day(waterRows) = water.day;
value.asset_type(waterRows) = 3;
value.asset_id(waterRows) = water.hydro_id;
value.variable(waterRows) = 3;
assert(all(value.kind>0) && all(value.bound_side>0), ...
    "stageB2C:legacyRuntimeAuditMaps:InequalityCoverage", ...
    "The legacy inequality descriptor does not cover every canonical row.");
end

function value = asset_type_code(types)
value = zeros(size(types),"uint8");
labels = ["wind","solar","hydro","thermal","storage"];
for k = 1:numel(labels), value(types==labels(k))=uint8(k); end
assert(all(value>0),"stageB2C:legacyRuntimeAuditMaps:AssetType", ...
    "A legacy runtime audit asset type is unsupported.");
end

function value = variable_code(names)
value = zeros(size(names),"uint8");
labels = ["PW","PP","PH","PF","Pch","Pdis","SOC"];
for k = 1:numel(labels), value(names==labels(k))=uint8(k); end
assert(all(value>0),"stageB2C:legacyRuntimeAuditMaps:Variable", ...
    "A legacy runtime audit variable name is unsupported.");
end
