function moduleResult = runStep(options)
%RUNSTEP Validate default and formal-option A4 step delegation.

arguments
    options.EquivalenceArtifact (1,1) string = ...
        rkkt.validation.packageArtifact( ...
        "solver","方向等价性模块输出.mat")
    options.RecoveryArtifact (1,1) string = ...
        rkkt.validation.packageArtifact( ...
        "solver","局部回代模块输出.mat")
    options.LinearizationArtifact (1,1) string = ...
        rkkt.validation.packageArtifact( ...
        "model","统一线性化模块输出.mat")
    options.IndexArtifact (1,1) string = ...
        rkkt.validation.packageArtifact( ...
        "indexing","索引模块输出.mat")
    options.DataArtifact (1,1) string = ...
        rkkt.validation.packageArtifact( ...
        "data","数据导入模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("ipm")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
[modules,objects] = load_inputs(options);
stateBefore = objects.linearization.state;

legacyDefault = rkkt.ipm.execute_stage_a4_iteration( ...
    stateBefore,objects.data,objects.index,objects.config);
facadeDefault = rkkt.ipm.step( ...
    stateBefore,objects.data,objects.index,objects.config);
defaultExact = rkkt.validation.deterministicEqual( ...
    legacyDefault,facadeDefault);
defaultTimingValid = rkkt.validation.timingValid(legacyDefault.timing) && ...
    rkkt.validation.timingValid(facadeDefault.timing);

[formalConfig,equalityReferenceScale,dualReferenceScale] = ...
    formal_inputs(stateBefore,objects);
legacyFormal = rkkt.ipm.execute_stage_a4_iteration( ...
    stateBefore,objects.data,objects.index,formalConfig, ...
    "StepStrategy","independent", ...
    "ObjectiveScaleMode","positive_scalar_unitization", ...
    "DiagnosticObjectiveChainId","A4-3-FORMAL-CANDIDATE", ...
    "EqualityResidualReferenceScale",equalityReferenceScale, ...
    "DualResidualReferenceScale",dualReferenceScale, ...
    "RecursiveRefinementMaxPasses",3);
facadeFormal = rkkt.ipm.step( ...
    stateBefore,objects.data,objects.index,formalConfig, ...
    StepStrategy="independent", ...
    ObjectiveScaleMode="positive_scalar_unitization", ...
    DiagnosticObjectiveChainId="A4-3-FORMAL-CANDIDATE", ...
    EqualityResidualReferenceScale=equalityReferenceScale, ...
    DualResidualReferenceScale=dualReferenceScale, ...
    RecursiveRefinementMaxPasses=3);
formalExact = rkkt.validation.deterministicEqual(legacyFormal,facadeFormal);
formalTimingValid = rkkt.validation.timingValid(legacyFormal.timing) && ...
    rkkt.validation.timingValid(facadeFormal.timing);

facts = step_facts(facadeDefault,objects,defaultExact, ...
    defaultTimingValid,facadeFormal,formalExact,formalTimingValid, ...
    formalConfig);
if ~all(structfun(@(value)logical(value),facts))
    error("rkkt:ipm:validation:StepFacts", ...
        "One or more objective PKG-7 step facts are false.");
end

stateSummary = state_change_summary(facadeDefault);
residualSummary = residual_step_summary(facadeDefault);
formalSummary = formal_option_summary( ...
    facadeFormal,formalExact,formalTimingValid, ...
    equalityReferenceScale,dualReferenceScale);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "IPM单步输出.mat", ...
    ["IPM单步状态变化.csv";"IPM单步残差与步长.csv"], ...
    "IPM单步状态更新",options.WriteArtifacts);
metadata = rkkt.validation.metadata("rkkt.ipm.step", ...
    "execute_stage_a4_iteration",options.EquivalenceArtifact, ...
    outputFile,"IPM单步模块",stateBefore.iteration_index, ...
    stateBefore.state_revision,options.Interactive, ...
    options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = input_references( ...
    options,modules,objects.linearization.identity, ...
    equalityReferenceScale,dualReferenceScale);
moduleResult.output = compact_step_output( ...
    facadeDefault,formalSummary);
moduleResult.intermediate = struct( ...
    "stateSummary",stateSummary, ...
    "residualSummary",residualSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "default_deterministic_fields_exact",defaultExact, ...
    "formal_option_deterministic_fields_exact",formalExact, ...
    "default_timing_finite_nonnegative",defaultTimingValid, ...
    "formal_timing_finite_nonnegative",formalTimingValid, ...
    "pkg6_direction_exact",facts.pkg6_direction_exact, ...
    "state_before_fingerprint", ...
        rkkt.validation.stateFingerprint(facadeDefault.state_before), ...
    "state_after_fingerprint", ...
        rkkt.validation.stateFingerprint(facadeDefault.state_after), ...
    "alpha_primal",facadeDefault.applied_step.applied_alpha_primal, ...
    "alpha_dual",facadeDefault.applied_step.applied_alpha_dual, ...
    "gap_before", ...
        facadeDefault.residuals.before.complementarity_gap, ...
    "gap_after",facadeDefault.residuals.after.complementarity_gap, ...
    "minimum_l_after",min(facadeDefault.state_after.l), ...
    "minimum_z_after",min(facadeDefault.state_after.z), ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "state_order","xi/y/l/z canonical state", ...
    "step_policy","xi,l use alphaPrimal; y,z use alphaDual", ...
    "official_direction","recursive reduction", ...
    "full_kkt_role","independent audit only");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(stateSummary,tableFiles(1));
    rkkt.validation.writeTable17(residualSummary,tableFiles(2));
    fig = step_figure(stateSummary,residualSummary, ...
        options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：IPM单步模块\n");
fprintf("默认/正式选项确定性字段严格相同：%d/%d\n", ...
    defaultExact,formalExact);
fprintf("alphaPrimal/alphaDual/gapAfter：%.17g/%.17g/%.17g\n", ...
    facadeDefault.applied_step.applied_alpha_primal, ...
    facadeDefault.applied_step.applied_alpha_dual, ...
    facadeDefault.residuals.after.complementarity_gap);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function [modules,objects] = load_inputs(options)
modules = struct();
modules.equivalence = rkkt.validation.loadResult( ...
    options.EquivalenceArtifact,"runStep equivalence", ...
    "rkkt.solver.verifyEquivalence");
modules.recovery = rkkt.validation.loadResult( ...
    options.RecoveryArtifact,"runStep recovery", ...
    "rkkt.solver.recoverDirection");
modules.linearization = rkkt.validation.loadResult( ...
    options.LinearizationArtifact,"runStep linearization", ...
    "rkkt.model.linearize");
modules.index = rkkt.validation.loadResult( ...
    options.IndexArtifact,"runStep index","rkkt.indexing.build");
modules.data = rkkt.validation.loadResult( ...
    options.DataArtifact,"runStep data","rkkt.data.load");
rkkt.contracts.requireFields(modules.equivalence.output,"audit", ...
    "runStep equivalence output");
rkkt.contracts.requireFields(modules.recovery.output,"recovery", ...
    "runStep recovery output");
rkkt.contracts.requireFields(modules.linearization.output, ...
    "linearization","runStep linearization output");
rkkt.contracts.requireFields(modules.linearization.input, ...
    ["projectData";"index";"config"],"runStep linearization input");
rkkt.contracts.requireFields(modules.index.output,"index", ...
    "runStep index output");
rkkt.contracts.requireFields(modules.data.output,"projectData", ...
    "runStep data output");
objects = struct( ...
    "audit",modules.equivalence.output.audit, ...
    "recovery",modules.recovery.output.recovery, ...
    "linearization",modules.linearization.output.linearization, ...
    "index",modules.index.output.index, ...
    "data",modules.data.output.projectData, ...
    "config",modules.linearization.input.config);
if ~isequaln(modules.linearization.input.projectData,objects.data) || ...
        ~isequaln(modules.linearization.input.index,objects.index)
    error("rkkt:ipm:validation:UpstreamObjectMismatch", ...
        "Linearization data/index differ from the fixed PKG-2/3 MATs.");
end
end

function [config,equalityScale,dualScale] = ...
        formal_inputs(stateBefore,objects)
config = rkkt.model.load_stage_a4_3_configuration(rkkt.projectRoot());
scaled = rkkt.model.build_stage_a4_scaled_objective_linearization( ...
    stateBefore,objects.data,objects.index,config, ...
    "A4-3-FORMAL-CANDIDATE");
equalityScale = max(1,norm(scaled.r_eq,inf));
dualScale = max(1,norm(scaled.r_dual,inf));
end

function facts = step_facts(step,objects,defaultExact,timingValid, ...
        formal,formalExact,formalTimingValid,formalConfig)
before = step.state_before;
after = step.state_after;
direction = step.recursive.components;
alphaP = step.applied_step.applied_alpha_primal;
alphaD = step.applied_step.applied_alpha_dual;
facts = struct( ...
    "default_deterministic_exact",defaultExact, ...
    "default_timing_valid",timingValid, ...
    "pkg6_direction_exact", ...
        isequaln(step.recursive.direction, ...
            objects.recovery.direction) && ...
        isequaln(step.recursive.components, ...
            objects.recovery.components), ...
    "linearization_identity_exact", ...
        isequaln(step.linearization_before.identity, ...
            objects.linearization.identity) && ...
        isequaln(step.recursive.linearization_identity, ...
            objects.recovery.linearization_identity) && ...
        isequaln(step.direction_audit.linearization_identity, ...
            objects.audit.linearization_identity), ...
    "state_before_exact", ...
        isequaln(before,objects.linearization.state), ...
    "state_updates_exact", ...
        isequaln(after.xi,before.xi+alphaP*direction.xi) && ...
        isequaln(after.l,before.l+alphaP*direction.l) && ...
        isequaln(after.y,before.y+alphaD*direction.y) && ...
        isequaln(after.z,before.z+alphaD*direction.z), ...
    "independent_steps_exact", ...
        step.primal_step.alpha==alphaP && ...
        step.dual_step.alpha==alphaD && ...
        step.applied_step.strategy=="independent" && ...
        ~step.applied_step.experimental && ...
        ~step.applied_step.all_four_groups_use_common_step, ...
    "strict_positivity",all(after.l>0) && all(after.z>0), ...
    "counters_increment_once", ...
        after.iteration_index==before.iteration_index+1 && ...
        after.state_revision==before.state_revision+1 && ...
        after.newton_direction_number== ...
            before.newton_direction_number+1 && ...
        after.completed_newton_direction_count== ...
            before.completed_newton_direction_count+1, ...
    "identity_changed", ...
        step.linearization_before.identity~= ...
        step.linearization_after.identity, ...
    "fixed_zero_exact", ...
        step.fixed_zero.count==422 && ...
        step.fixed_zero.values_exact_zero_before && ...
        step.fixed_zero.values_exact_zero_after && ...
        step.fixed_zero.directions_exact_zero, ...
    "soc_contract_exact", ...
        step.soc.passed && ...
        step.soc.initial_half_energy_link_count==14 && ...
        step.soc.terminal_half_energy_link_count==14 && ...
        step.soc.cross_day_or_nonadjacent_link_count==0, ...
    "official_recursive_direction_only", ...
        step.recursive.no_full_direction_fallback && ...
        ~step.recursive.full_direction_consumed && ...
        step.checks.recursive_no_full_direction_fallback, ...
    "all_checks_pass",step.all_pass && ...
        all(structfun(@(value)isequal(value,true),step.checks)), ...
    "frozen_sigma_tau", ...
        objects.config.initialization.centering_sigma==0.1 && ...
        objects.config.fraction_to_boundary==0.9995, ...
    "formal_deterministic_exact",formalExact, ...
    "formal_timing_valid",formalTimingValid, ...
    "formal_options_exact", ...
        formal.objective_scale_mode== ...
            "positive_scalar_unitization" && ...
        formal.diagnostic_objective_chain_id== ...
            "A4-3-FORMAL-CANDIDATE" && ...
        formal.recursive_refinement_max_passes==3 && ...
        formal.applied_step.strategy=="independent" && ...
        formalConfig.a4_3.recursive_refinement_max_passes==3 && ...
        formal.all_pass);
end

function value = compact_step_output(step,formalSummary)
components = step.recursive.components;
officialDirection = struct( ...
    "linearization_identity", ...
        string(step.recursive.linearization_identity), ...
    "xi",components.xi,"y",components.y, ...
    "l",components.l,"z",components.z, ...
    "is_official",true, ...
    "no_full_direction_fallback", ...
        step.recursive.no_full_direction_fallback, ...
    "full_direction_consumed", ...
        step.recursive.full_direction_consumed);
value = struct( ...
    "state_before",step.state_before, ...
    "state_after",step.state_after, ...
    "state_before_fingerprint", ...
        rkkt.validation.stateFingerprint(step.state_before), ...
    "state_after_fingerprint", ...
        rkkt.validation.stateFingerprint(step.state_after), ...
    "linearization_identity_before", ...
        string(step.linearization_before.identity), ...
    "linearization_identity_after", ...
        string(step.linearization_after.identity), ...
    "official_recursive_direction",officialDirection, ...
    "primal_step",step.primal_step, ...
    "dual_step",step.dual_step, ...
    "applied_step",step.applied_step, ...
    "residuals",struct("before",step.residuals.before, ...
        "after",step.residuals.after), ...
    "direction_audit",step.direction_audit, ...
    "fixed_zero",step.fixed_zero, ...
    "soc",step.soc, ...
    "permutation",step.permutation, ...
    "checks",step.checks, ...
    "all_pass",step.all_pass, ...
    "formal_option_comparison",formalSummary);
end

function value = formal_option_summary( ...
        step,exact,timingValid,equalityScale,dualScale)
value = struct( ...
    "deterministic_fields_exact",exact, ...
    "timing_finite_nonnegative",timingValid, ...
    "step_strategy",string(step.applied_step.strategy), ...
    "objective_scale_mode",string(step.objective_scale_mode), ...
    "diagnostic_objective_chain_id", ...
        string(step.diagnostic_objective_chain_id), ...
    "recursive_refinement_max_passes", ...
        step.recursive_refinement_max_passes, ...
    "equality_residual_reference_scale",equalityScale, ...
    "dual_residual_reference_scale",dualScale, ...
    "linearization_identity_before", ...
        string(step.linearization_before.identity), ...
    "linearization_identity_after", ...
        string(step.linearization_after.identity), ...
    "state_after_fingerprint", ...
        rkkt.validation.stateFingerprint(step.state_after), ...
    "alpha_primal",step.applied_step.applied_alpha_primal, ...
    "alpha_dual",step.applied_step.applied_alpha_dual, ...
    "gap_before",step.residuals.before.complementarity_gap, ...
    "gap_after",step.residuals.after.complementarity_gap, ...
    "all_pass",step.all_pass, ...
    "no_full_direction_fallback", ...
        step.recursive.no_full_direction_fallback, ...
    "full_direction_consumed", ...
        step.recursive.full_direction_consumed);
end

function value = input_references( ...
        options,modules,identity,equalityScale,dualScale)
value = struct( ...
    "equivalenceArtifact",rkkt.validation.artifactReference( ...
        options.EquivalenceArtifact,identity, ...
        modules.equivalence.meta.interface_name), ...
    "recoveryArtifact",rkkt.validation.artifactReference( ...
        options.RecoveryArtifact,identity, ...
        modules.recovery.meta.interface_name), ...
    "linearizationArtifact",rkkt.validation.artifactReference( ...
        options.LinearizationArtifact,identity, ...
        modules.linearization.meta.interface_name), ...
    "indexArtifact",rkkt.validation.artifactReference( ...
        options.IndexArtifact,identity,modules.index.meta.interface_name), ...
    "dataArtifact",rkkt.validation.artifactReference( ...
        options.DataArtifact,identity,modules.data.meta.interface_name), ...
    "linearizationIdentity",string(identity), ...
    "defaultOptions",struct( ...
        "StepStrategy","independent", ...
        "ObjectiveScaleMode","unscaled", ...
        "DiagnosticObjectiveChainId","", ...
        "EqualityResidualReferenceScale",NaN, ...
        "DualResidualReferenceScale",NaN, ...
        "RecursiveRefinementMaxPasses",0), ...
    "formalOptions",struct( ...
        "StepStrategy","independent", ...
        "ObjectiveScaleMode","positive_scalar_unitization", ...
        "DiagnosticObjectiveChainId","A4-3-FORMAL-CANDIDATE", ...
        "EqualityResidualReferenceScale",equalityScale, ...
        "DualResidualReferenceScale",dualScale, ...
        "RecursiveRefinementMaxPasses",3));
end

function value = state_change_summary(step)
names = ["xi";"y";"l";"z"];
before = {step.state_before.xi;step.state_before.y; ...
    step.state_before.l;step.state_before.z};
after = {step.state_after.xi;step.state_after.y; ...
    step.state_after.l;step.state_after.z};
direction = {step.recursive.components.xi; ...
    step.recursive.components.y;step.recursive.components.l; ...
    step.recursive.components.z};
alpha = [ ...
    step.applied_step.applied_alpha_primal; ...
    step.applied_step.applied_alpha_dual; ...
    step.applied_step.applied_alpha_primal; ...
    step.applied_step.applied_alpha_dual];
dimension = reshape(cellfun(@numel,before),[],1);
normBefore = reshape(cellfun(@(item)norm(item,2),before),[],1);
normAfter = reshape(cellfun(@(item)norm(item,2),after),[],1);
deltaNorm = reshape(cellfun(@(left,right) ...
    norm(right-left,2),before,after),[],1);
maximumAbsoluteDelta = reshape(cellfun(@(left,right) ...
    max(abs(right-left)),before,after),[],1);
updateExact = false(4,1);
for k = 1:4
    updateExact(k) = isequaln(after{k}, ...
        before{k}+alpha(k)*direction{k});
end
value = table(names,dimension,normBefore,normAfter,deltaNorm, ...
    maximumAbsoluteDelta,alpha,updateExact, ...
    'VariableNames',{'component','dimension','normBefore', ...
    'normAfter','deltaNorm','maximumAbsoluteDelta','alpha', ...
    'updateExact'});
end

function value = residual_step_summary(step)
phase = ["before";"after"];
before = step.residuals.before;
after = step.residuals.after;
equalityInf = [before.equality_inf;after.equality_inf];
slackEqualityInf = [ ...
    before.slack_equality_inf;after.slack_equality_inf];
dualInf = [before.dual_inf;after.dual_inf];
complementarityInf = [ ...
    before.complementarity_inf;after.complementarity_inf];
complementarityGap = [ ...
    before.complementarity_gap;after.complementarity_gap];
minimumL = [before.minimum_l;after.minimum_l];
minimumZ = [before.minimum_z;after.minimum_z];
alphaPrimal = repmat( ...
    step.applied_step.applied_alpha_primal,2,1);
alphaDual = repmat( ...
    step.applied_step.applied_alpha_dual,2,1);
directionRelativeError = repmat( ...
    step.direction_audit.direction_relative_error,2,1);
recursiveKktRelativeResidual = repmat( ...
    step.direction_audit.recursive_kkt_relative_residual,2,1);
allPass = repmat(step.all_pass,2,1);
value = table(phase,equalityInf,slackEqualityInf,dualInf, ...
    complementarityInf,complementarityGap,minimumL,minimumZ, ...
    alphaPrimal,alphaDual,directionRelativeError, ...
    recursiveKktRelativeResidual,allPass);
end

function fig = step_figure(stateSummary,residualSummary,interactive)
fig = rkkt.validation.newFigure( ...
    "IPM单步状态更新",interactive);
layout = tiledlayout(fig,1,2,"TileSpacing","compact", ...
    "Padding","compact");
nexttile(layout);
semilogy(1:height(stateSummary), ...
    max(stateSummary.deltaNorm,realmin),"-o","LineWidth",1.4);
xticks(1:height(stateSummary));
xticklabels(stateSummary.component);
ylabel("状态变化二范数");
title("独立原始/对偶步长更新");
grid on;
nexttile(layout);
metrics = [residualSummary.equalityInf, ...
    residualSummary.dualInf, ...
    residualSummary.complementarityInf, ...
    residualSummary.complementarityGap];
semilogy(1:2,max(metrics,realmin),"-o","LineWidth",1.2);
xticks(1:2);
xticklabels(residualSummary.phase);
ylabel("残差或间隙");
title("单步前后残差摘要");
legend(["r_{eq}","r_{dual}","r_{comp}","mean(lz)"], ...
    "Location","best");
grid on;
end
