function moduleResult = runSolve(options)
%RUNSOLVE Validate a three-step preview and the deferred solve contract.

arguments
    options.StepArtifact (1,1) string = ...
        rkkt.ipm.validation.ValidationSupport.packageArtifact( ...
        "ipm","IPM单步输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.ipm.validation.ValidationSupport.outputDirectory()
end

support = rkkt.ipm.validation.ValidationSupport;
support.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
[stepModule,objects,references] = load_inputs( ...
    support,options.StepArtifact);
stateAfter = stepModule.output.state_after;

trajectory = run_controlled_trajectory( ...
    support,stateAfter,objects.data,objects.index,objects.config);
formalConfig = support.callProduction( ...
    "model","load_stage_a4_3_configuration", ...
    support.repositoryRoot());
solveProbe = probe_solve_contract(support,formalConfig);
solveStatus = make_solve_status(solveProbe,height(trajectory));
solveContractTable = make_solve_contract_table( ...
    formalConfig,solveStatus);

if ~all(trajectory.deterministicFieldsExact) || ...
        ~all(trajectory.stateBeforeExact) || ...
        ~all(trajectory.stateAfterExact) || ...
        ~all(trajectory.stateFingerprintExact) || ...
        ~all(trajectory.recursiveDirectionExact) || ...
        ~all(trajectory.alphaExact) || ...
        ~all(trajectory.residualSummaryExact) || ...
        ~all(trajectory.complementarityGapExact) || ...
        ~all(trajectory.directionAuditExact) || ...
        ~all(trajectory.counterTrajectoryExact) || ...
        ~all(trajectory.strictPositivity) || ...
        ~all(trajectory.noFullDirectionFallback) || ...
        ~all(trajectory.fullKktAuditOnly) || ...
        ~all(trajectory.allPass) || ...
        ~all(trajectory.timingFiniteNonnegative)
    error("rkkt:ipm:validation:ControlledTrajectory", ...
        "The controlled three-step legacy/facade trajectory differs.");
end
if ~solveProbe.all_contract_facts
    error("rkkt:ipm:validation:SolveContract", ...
        "The deferred full-solve interface contract is inconsistent.");
end

[outputFile,tableFiles,figureFiles,figureIndex] = ...
    support.outputPaths(options.OutputDirectory, ...
    "IPM受控轨迹输出.mat", ...
    ["IPM受控轨迹.csv";"IPM完整求解接口合同.csv"], ...
    "IPM受控轨迹",options.WriteArtifacts);
metadata = support.metadata("rkkt.ipm.solve", ...
    "run_stage_a4_full_ipm",options.StepArtifact,outputFile, ...
    "IPM受控轨迹模块",stateAfter.iteration_index, ...
    stateAfter.state_revision,options.Interactive, ...
    options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "stepArtifact",support.artifactReference( ...
        options.StepArtifact, ...
        stepModule.output.linearization_identity_after, ...
        stepModule.meta.interface_name), ...
    "referencedArtifacts",references, ...
    "startStateFingerprint",support.stateFingerprint(stateAfter), ...
    "previewOptions",struct( ...
        "StepStrategy","independent", ...
        "ObjectiveScaleMode","unscaled", ...
        "DiagnosticObjectiveChainId","", ...
        "EqualityResidualReferenceScale",NaN, ...
        "DualResidualReferenceScale",NaN, ...
        "RecursiveRefinementMaxPasses",0));
moduleResult.output = struct( ...
    "controlledTrajectory",struct( ...
        "controlled_preview_iteration_count",height(trajectory), ...
        "initial_state_fingerprint", ...
            string(trajectory.stateBeforeFingerprint(1)), ...
        "final_state_fingerprint", ...
            string(trajectory.stateAfterFingerprint(end)), ...
        "state_trajectory_legacy_exact", ...
            all(trajectory.deterministicFieldsExact), ...
        "rounds",trajectory), ...
    "solveContract",solveStatus);
moduleResult.intermediate = struct( ...
    "solveContractTable",solveContractTable, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "controlled_preview_iteration_count", ...
        solveStatus.controlled_preview_iteration_count, ...
    "state_trajectory_legacy_exact", ...
        all(trajectory.deterministicFieldsExact), ...
    "legacy_solve_error_identifier", ...
        solveProbe.legacy_error_identifier, ...
    "facade_solve_error_identifier", ...
        solveProbe.facade_error_identifier, ...
    "solve_error_identifier_exact", ...
        solveProbe.error_identifier_exact, ...
    "runs_snapshot_unchanged", ...
        solveProbe.runs_snapshot_unchanged, ...
    "full_ipm_executed",solveStatus.full_ipm_executed, ...
    "formal_run_context_created", ...
        solveStatus.formal_run_context_created, ...
    "convergence_evaluated",solveStatus.convergence_evaluated, ...
    "convergence_claimed",solveStatus.convergence_claimed, ...
    "solve_runtime_status",solveStatus.solve_runtime_status, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "trajectory_order","three consecutive accepted state transitions", ...
    "chain_isolation","legacy and facade consume only their own prior state", ...
    "timing_comparison","excluded; finite and nonnegative only", ...
    "full_solve_status","DEFERRED_UNTIL_FORMAL_RUN");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    support.writeTable17(trajectory,tableFiles(1));
    support.writeTable17(solveContractTable,tableFiles(2));
    fig = trajectory_figure(trajectory,options.Interactive);
    support.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    support.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：IPM受控轨迹模块\n");
fprintf("三轮旧入口/门面确定性字段逐轮严格相同：%d\n", ...
    all(trajectory.deterministicFieldsExact));
fprintf("完整IPM执行/收敛评价/收敛声明：0/0/0\n");
fprintf("完整求解运行状态：DEFERRED_UNTIL_FORMAL_RUN\n");
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function [stepModule,objects,references] = load_inputs( ...
        support,stepArtifact)
stepModule = support.loadResult( ...
    stepArtifact,"runSolve step","rkkt.ipm.step");
rkkt.contracts.requireFields(stepModule.output, ...
    ["state_after";"linearization_identity_after"], ...
    "runSolve step output");
rkkt.contracts.requireFields(stepModule.input, ...
    ["dataArtifact";"indexArtifact";"linearizationArtifact"], ...
    "runSolve step input references");

dataReference = validate_reference( ...
    support,stepModule.input.dataArtifact,"runSolve data reference");
indexReference = validate_reference( ...
    support,stepModule.input.indexArtifact,"runSolve index reference");
linearizationReference = validate_reference( ...
    support,stepModule.input.linearizationArtifact, ...
    "runSolve linearization reference");
dataModule = support.loadResult(dataReference.path, ...
    "runSolve referenced data",dataReference.interface_name);
indexModule = support.loadResult(indexReference.path, ...
    "runSolve referenced index",indexReference.interface_name);
linearizationModule = support.loadResult( ...
    linearizationReference.path,"runSolve referenced linearization", ...
    linearizationReference.interface_name);
rkkt.contracts.requireFields(dataModule.output,"projectData", ...
    "runSolve data output");
rkkt.contracts.requireFields(indexModule.output,"index", ...
    "runSolve index output");
rkkt.contracts.requireFields(linearizationModule.input, ...
    ["projectData";"index";"config"], ...
    "runSolve linearization input");

objects = struct( ...
    "data",dataModule.output.projectData, ...
    "index",indexModule.output.index, ...
    "config",linearizationModule.input.config);
if ~isequaln(linearizationModule.input.projectData,objects.data) || ...
        ~isequaln(linearizationModule.input.index,objects.index)
    error("rkkt:ipm:validation:ReferencedObjectMismatch", ...
        "Referenced linearization data/index are not the fixed objects.");
end
references = struct( ...
    "dataArtifact",dataReference, ...
    "indexArtifact",indexReference, ...
    "linearizationArtifact",linearizationReference);
end

function reference = validate_reference(support,reference,context)
rkkt.contracts.requireFields(reference, ...
    ["path";"sha256";"identity";"interface_name"],context);
if ~isfile(reference.path)
    error("rkkt:ipm:validation:ReferencedArtifactMissing", ...
        "[%s] referenced artifact is missing: %s", ...
        context,reference.path);
end
actual = support.artifactReference( ...
    reference.path,reference.identity,reference.interface_name);
if lower(string(actual.sha256))~=lower(string(reference.sha256))
    error("rkkt:ipm:validation:ReferencedArtifactHash", ...
        "[%s] referenced artifact SHA256 changed.",context);
end
reference.path = string(reference.path);
reference.sha256 = lower(string(reference.sha256));
reference.identity = string(reference.identity);
reference.interface_name = string(reference.interface_name);
end

function trajectory = run_controlled_trajectory( ...
        support,startState,data,index,config)
count = 3;
previewIteration = (1:count).';
iterationIndexBefore = zeros(count,1);
iterationIndexAfter = zeros(count,1);
stateRevisionBefore = zeros(count,1);
stateRevisionAfter = zeros(count,1);
stateBeforeFingerprint = strings(count,1);
stateAfterFingerprint = strings(count,1);
alphaPrimal = zeros(count,1);
alphaDual = zeros(count,1);
gapBefore = zeros(count,1);
gapAfter = zeros(count,1);
equalityInfAfter = zeros(count,1);
dualInfAfter = zeros(count,1);
complementarityInfAfter = zeros(count,1);
minimumL = zeros(count,1);
minimumZ = zeros(count,1);
deterministicFieldsExact = false(count,1);
stateBeforeExact = false(count,1);
stateAfterExact = false(count,1);
stateFingerprintExact = false(count,1);
recursiveDirectionExact = false(count,1);
alphaExact = false(count,1);
residualSummaryExact = false(count,1);
complementarityGapExact = false(count,1);
directionAuditExact = false(count,1);
counterTrajectoryExact = false(count,1);
strictPositivity = false(count,1);
noFullDirectionFallback = false(count,1);
fullKktAuditOnly = false(count,1);
allPass = false(count,1);
timingFiniteNonnegative = false(count,1);

legacyState = startState;
facadeState = startState;
for roundIndex = 1:count
    legacyStep = support.callProduction( ...
        "diagnostics","execute_stage_a4_iteration", ...
        legacyState,data,index,config, ...
        "StepStrategy","independent", ...
        "ObjectiveScaleMode","unscaled", ...
        "RecursiveRefinementMaxPasses",0);
    facadeStep = rkkt.ipm.step( ...
        facadeState,data,index,config, ...
        StepStrategy="independent", ...
        ObjectiveScaleMode="unscaled", ...
        RecursiveRefinementMaxPasses=0);

    legacyBeforeFingerprint = ...
        support.stateFingerprint(legacyStep.state_before);
    facadeBeforeFingerprint = ...
        support.stateFingerprint(facadeStep.state_before);
    legacyAfterFingerprint = ...
        support.stateFingerprint(legacyStep.state_after);
    facadeAfterFingerprint = ...
        support.stateFingerprint(facadeStep.state_after);
    deterministicFieldsExact(roundIndex) = ...
        support.deterministicEqual(legacyStep,facadeStep);
    stateBeforeExact(roundIndex) = ...
        isequaln(legacyStep.state_before,facadeStep.state_before);
    stateAfterExact(roundIndex) = ...
        isequaln(legacyStep.state_after,facadeStep.state_after);
    stateFingerprintExact(roundIndex) = ...
        legacyBeforeFingerprint==facadeBeforeFingerprint && ...
        legacyAfterFingerprint==facadeAfterFingerprint;
    recursiveDirectionExact(roundIndex) = ...
        isequaln(legacyStep.recursive.direction, ...
            facadeStep.recursive.direction) && ...
        isequaln(legacyStep.recursive.components, ...
            facadeStep.recursive.components);
    alphaExact(roundIndex) = ...
        legacyStep.applied_step.applied_alpha_primal== ...
            facadeStep.applied_step.applied_alpha_primal && ...
        legacyStep.applied_step.applied_alpha_dual== ...
            facadeStep.applied_step.applied_alpha_dual;
    residualSummaryExact(roundIndex) = ...
        isequaln(legacyStep.residuals,facadeStep.residuals);
    complementarityGapExact(roundIndex) = ...
        legacyStep.residuals.before.complementarity_gap== ...
            facadeStep.residuals.before.complementarity_gap && ...
        legacyStep.residuals.after.complementarity_gap== ...
            facadeStep.residuals.after.complementarity_gap;
    directionAuditExact(roundIndex) = ...
        isequaln(legacyStep.direction_audit, ...
            facadeStep.direction_audit);
    counterTrajectoryExact(roundIndex) = ...
        counters_exact(legacyStep) && ...
        counters_exact(facadeStep) && ...
        counters_match(legacyStep,facadeStep);
    strictPositivity(roundIndex) = ...
        all(legacyStep.state_after.l>0) && ...
        all(legacyStep.state_after.z>0) && ...
        all(facadeStep.state_after.l>0) && ...
        all(facadeStep.state_after.z>0);
    noFullDirectionFallback(roundIndex) = ...
        legacyStep.recursive.no_full_direction_fallback && ...
        ~legacyStep.recursive.full_direction_consumed && ...
        facadeStep.recursive.no_full_direction_fallback && ...
        ~facadeStep.recursive.full_direction_consumed;
    fullKktAuditOnly(roundIndex) = ...
        noFullDirectionFallback(roundIndex) && ...
        legacyStep.direct_audit.method=="sparse_backslash_audit" && ...
        facadeStep.direct_audit.method=="sparse_backslash_audit" && ...
        isequaln(legacyStep.recursive.linearization_identity, ...
            legacyStep.direct_audit.linearization_identity) && ...
        isequaln(legacyStep.recursive.linearization_identity, ...
            legacyStep.direction_audit.linearization_identity) && ...
        isequaln(facadeStep.recursive.linearization_identity, ...
            facadeStep.direct_audit.linearization_identity) && ...
        isequaln(facadeStep.recursive.linearization_identity, ...
            facadeStep.direction_audit.linearization_identity) && ...
        legacyStep.direction_audit.passed. ...
            no_full_direction_fallback && ...
        facadeStep.direction_audit.passed. ...
            no_full_direction_fallback;
    allPass(roundIndex) = legacyStep.all_pass && facadeStep.all_pass;
    timingFiniteNonnegative(roundIndex) = ...
        support.timingValid(legacyStep.timing) && ...
        support.timingValid(facadeStep.timing);

    iterationIndexBefore(roundIndex) = ...
        facadeStep.state_before.iteration_index;
    iterationIndexAfter(roundIndex) = ...
        facadeStep.state_after.iteration_index;
    stateRevisionBefore(roundIndex) = ...
        facadeStep.state_before.state_revision;
    stateRevisionAfter(roundIndex) = ...
        facadeStep.state_after.state_revision;
    stateBeforeFingerprint(roundIndex) = facadeBeforeFingerprint;
    stateAfterFingerprint(roundIndex) = facadeAfterFingerprint;
    alphaPrimal(roundIndex) = ...
        facadeStep.applied_step.applied_alpha_primal;
    alphaDual(roundIndex) = ...
        facadeStep.applied_step.applied_alpha_dual;
    gapBefore(roundIndex) = ...
        facadeStep.residuals.before.complementarity_gap;
    gapAfter(roundIndex) = ...
        facadeStep.residuals.after.complementarity_gap;
    equalityInfAfter(roundIndex) = ...
        facadeStep.residuals.after.equality_inf;
    dualInfAfter(roundIndex) = ...
        facadeStep.residuals.after.dual_inf;
    complementarityInfAfter(roundIndex) = ...
        facadeStep.residuals.after.complementarity_inf;
    minimumL(roundIndex) = min(facadeStep.state_after.l);
    minimumZ(roundIndex) = min(facadeStep.state_after.z);

    legacyState = legacyStep.state_after;
    facadeState = facadeStep.state_after;
end

trajectory = table(previewIteration,iterationIndexBefore, ...
    iterationIndexAfter,stateRevisionBefore,stateRevisionAfter, ...
    stateBeforeFingerprint,stateAfterFingerprint,alphaPrimal, ...
    alphaDual,gapBefore,gapAfter,equalityInfAfter,dualInfAfter, ...
    complementarityInfAfter,minimumL,minimumZ, ...
    deterministicFieldsExact,stateBeforeExact,stateAfterExact, ...
    stateFingerprintExact,recursiveDirectionExact,alphaExact, ...
    residualSummaryExact,complementarityGapExact, ...
    directionAuditExact,counterTrajectoryExact,strictPositivity, ...
    noFullDirectionFallback,fullKktAuditOnly,allPass, ...
    timingFiniteNonnegative);
end

function value = counters_exact(step)
before = step.state_before;
after = step.state_after;
value = ...
    after.iteration_index==before.iteration_index+1 && ...
    after.state_revision==before.state_revision+1 && ...
    after.newton_direction_number== ...
        before.newton_direction_number+1 && ...
    after.completed_newton_direction_count== ...
        before.completed_newton_direction_count+1;
end

function value = counters_match(left,right)
names = ["iteration_index";"state_revision"; ...
    "newton_direction_number";"completed_newton_direction_count"];
value = true;
for name = names.'
    value = value && ...
        left.state_before.(name)==right.state_before.(name) && ...
        left.state_after.(name)==right.state_after.(name);
end
end

function probe = probe_solve_contract(support,formalConfig)
runsRoot = fullfile(support.repositoryRoot(),"runs");
before = snapshot_tree(support,runsRoot);
invalidRunContext = struct( ...
    "contract_probe","PKG-7_NO_PATH_RUN_CONTEXT");
legacyIdentifier = capture_error(@() support.callProduction( ...
    "solver","run_stage_a4_full_ipm", ...
    struct(),struct(),formalConfig,invalidRunContext, ...
    "Resume",false));
afterLegacy = snapshot_tree(support,runsRoot);
facadeIdentifier = capture_error(@() rkkt.ipm.solve( ...
    struct(),struct(),formalConfig,invalidRunContext,Resume=false));
afterFacade = snapshot_tree(support,runsRoot);

expectedIdentifier = "stageA4:a43:RunContext";
identifierExact = legacyIdentifier==expectedIdentifier && ...
    facadeIdentifier==expectedIdentifier && ...
    legacyIdentifier==facadeIdentifier;
runsUnchanged = isequaln(before,afterLegacy) && ...
    isequaln(before,afterFacade);
noPathFields = ~any(contains(lower(string(fieldnames( ...
    invalidRunContext))),["path";"root";"dir"]));
probe = struct( ...
    "invalid_run_context_has_no_path_fields",noPathFields, ...
    "legacy_error_identifier",legacyIdentifier, ...
    "facade_error_identifier",facadeIdentifier, ...
    "expected_error_identifier",expectedIdentifier, ...
    "error_identifier_exact",identifierExact, ...
    "runs_snapshot_unchanged",runsUnchanged, ...
    "full_ipm_executed",false, ...
    "formal_run_context_created",false, ...
    "ipm_iteration_count",0, ...
    "convergence_evaluated",false, ...
    "convergence_claimed",false, ...
    "solve_runtime_status","DEFERRED_UNTIL_FORMAL_RUN", ...
    "all_contract_facts", ...
        noPathFields && identifierExact && runsUnchanged);
end

function identifier = capture_error(callable)
try
    callable();
catch cause
    identifier = string(cause.identifier);
    return
end
error("rkkt:ipm:validation:ExpectedContractError", ...
    "The invalid runContext did not fail.");
end

function value = snapshot_tree(support,root)
variableNames = {'relativePath','isDirectory','bytes', ...
    'modifiedTime','sha256'};
if ~isfolder(root)
    value = table(strings(0,1),false(0,1),zeros(0,1), ...
        zeros(0,1),strings(0,1),'VariableNames',variableNames);
    return
end
listing = dir(fullfile(root,"**","*"));
count = numel(listing);
relativePath = strings(count,1);
isDirectory = false(count,1);
bytes = zeros(count,1);
modifiedTime = zeros(count,1);
sha256 = strings(count,1);
prefix = string(root)+filesep;
for itemIndex = 1:count
    absolutePath = fullfile( ...
        string(listing(itemIndex).folder), ...
        string(listing(itemIndex).name));
    relativePath(itemIndex) = erase(absolutePath,prefix);
    isDirectory(itemIndex) = listing(itemIndex).isdir;
    bytes(itemIndex) = listing(itemIndex).bytes;
    modifiedTime(itemIndex) = listing(itemIndex).datenum;
    if ~listing(itemIndex).isdir
        sha256(itemIndex) = ...
            rkkt.model.validation.ValidationSupport.sha256( ...
                absolutePath,support.repositoryRoot());
    end
end
value = sortrows(table(relativePath,isDirectory,bytes, ...
    modifiedTime,sha256),["relativePath";"isDirectory"]);
end

function value = make_solve_status(probe,previewCount)
value = struct( ...
    "controlled_preview_iteration_count",previewCount, ...
    "full_ipm_executed",false, ...
    "full_ipm_iteration_count",0, ...
    "formal_run_context_created",false, ...
    "convergence_evaluated",false, ...
    "convergence_claimed",false, ...
    "solve_runtime_status","DEFERRED_UNTIL_FORMAL_RUN", ...
    "invalid_run_context_identifier", ...
        probe.expected_error_identifier, ...
    "legacy_facade_error_identifier_exact", ...
        probe.error_identifier_exact, ...
    "runs_snapshot_unchanged",probe.runs_snapshot_unchanged);
end

function value = make_solve_contract_table(config,status)
a43 = config.a4_3;
field = [ ...
    "controlled_preview_iteration_count"
    "full_ipm_executed"
    "full_ipm_iteration_count"
    "formal_run_context_created"
    "convergence_evaluated"
    "convergence_claimed"
    "solve_runtime_status"
    "invalid_run_context_identifier"
    "legacy_facade_error_identifier_exact"
    "runs_snapshot_unchanged"
    "a4_3_configuration_path"
    "max_iterations"
    "convergence_coordinate"
    "primal_equality_inf_tolerance"
    "primal_inequality_inf_tolerance"
    "dual_scaled_inf_tolerance"
    "mean_lz_scaled_tolerance"
    "physical_violation_tolerance"
    "centering_sigma"
    "fraction_to_boundary"
    "step_strategy"
    "recursive_refinement_max_passes"
    "full_kkt_role"
    "parallel_mode"];
contractValue = [ ...
    string(status.controlled_preview_iteration_count)
    logical_text(status.full_ipm_executed)
    string(status.full_ipm_iteration_count)
    logical_text(status.formal_run_context_created)
    logical_text(status.convergence_evaluated)
    logical_text(status.convergence_claimed)
    status.solve_runtime_status
    status.invalid_run_context_identifier
    logical_text(status.legacy_facade_error_identifier_exact)
    logical_text(status.runs_snapshot_unchanged)
    string(config.source_paths.a4_3)
    string(a43.max_iterations)
    string(a43.convergence_coordinate)
    numeric_text(a43.primal_equality_inf_tolerance)
    numeric_text(a43.primal_inequality_inf_tolerance)
    numeric_text(a43.dual_scaled_inf_tolerance)
    numeric_text(a43.mean_lz_scaled_tolerance)
    numeric_text(a43.physical_violation_tolerance)
    numeric_text(a43.centering_sigma)
    numeric_text(a43.fraction_to_boundary)
    string(a43.step_strategy)
    string(a43.recursive_refinement_max_passes)
    string(a43.full_kkt_role)
    string(a43.parallel_mode)];
source = [ ...
    repmat("PKG-7 controlled preview",10,1)
    "config.source_paths.a4_3"
    repmat("config.a4_3 contract; not executed",13,1)];
runtimeStatus = repmat( ...
    "DEFERRED_UNTIL_FORMAL_RUN",numel(field),1);
value = table(field,contractValue,source,runtimeStatus, ...
    'VariableNames',{'contractField','contractValue', ...
    'source','runtimeStatus'});
end

function value = logical_text(input)
if input
    value = "true";
else
    value = "false";
end
end

function value = numeric_text(input)
value = string(compose("%.17g",input));
end

function fig = trajectory_figure(trajectory,interactive)
fig = rkkt.ipm.validation.ValidationSupport.newFigure( ...
    "IPM受控轨迹",interactive);
layout = tiledlayout(fig,1,2,"TileSpacing","compact", ...
    "Padding","compact");
nexttile(layout);
semilogy(trajectory.previewIteration,trajectory.alphaPrimal, ...
    "-o","LineWidth",1.2);
hold on;
semilogy(trajectory.previewIteration,trajectory.alphaDual, ...
    "-s","LineWidth",1.2);
hold off;
xticks(trajectory.previewIteration);
xlabel("受控预览轮次");
ylabel("步长（对数轴）");
title("独立原始与对偶步长");
legend(["alphaPrimal","alphaDual"],"Location","best");
grid on;
nexttile(layout);
semilogy(trajectory.previewIteration, ...
    max(trajectory.gapAfter,realmin),"-o","LineWidth",1.2);
xticks(trajectory.previewIteration);
xlabel("受控预览轮次");
ylabel("更新后 complementarity gap");
title("三轮状态轨迹预览（非收敛结论）");
grid on;
end
