function moduleResult = runSolve(options)
%RUNSOLVE Validate one bounded iteration through the complete IPM entry.

arguments
    options.StepArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("ipm","IPM单步输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("ipm")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
stepModule = rkkt.validation.loadResult(options.StepArtifact, ...
    "runSolve step","rkkt.ipm.step");
dataModule = load_reference(stepModule.input.dataArtifact, ...
    "runSolve data","rkkt.data.load");
indexModule = load_reference(stepModule.input.indexArtifact, ...
    "runSolve index","rkkt.indexing.build");

data = dataModule.output.projectData;
index = indexModule.output.index;
state = stepModule.output.state_after;
config = rkkt.model.load_stage_a4_3_configuration(rkkt.projectRoot());
config.a4_3.max_iterations = 1;
solution = rkkt.ipm.solve(state,data,index,config);

facts = struct( ...
    "one_iteration",solution.iteration_count==1, ...
    "initial_revision_exact", ...
        solution.initial_state_revision==state.state_revision, ...
    "revision_advanced", ...
        solution.final_state.state_revision==state.state_revision+1, ...
    "strict_positivity",all(solution.final_state.l>0) && ...
        all(solution.final_state.z>0), ...
    "no_full_direction_fallback", ...
        solution.last_step.recursive.no_full_direction_fallback, ...
    "full_direction_not_consumed", ...
        ~solution.last_step.recursive.full_direction_consumed, ...
    "step_checks_pass",solution.last_step.all_pass, ...
    "history_row_exact",height(solution.iteration_history)==1);
assert(all(structfun(@logical,facts)), ...
    "rkkt:ipm:validation:SolveFacts", ...
    "The bounded complete-IPM validation facts are inconsistent.");

history = solution.iteration_history;
contract = struct2table(facts,"AsArray",true);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "IPM受控轨迹输出.mat", ...
    ["IPM受控轨迹.csv";"IPM完整求解接口合同.csv"], ...
    "IPM受控轨迹",options.WriteArtifacts);
metadata = rkkt.validation.metadata("rkkt.ipm.solve", ...
    "rkkt.ipm.solve",options.StepArtifact,outputFile, ...
    "IPM受控轨迹模块",state.iteration_index,state.state_revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "stepArtifact",rkkt.validation.artifactReference( ...
        options.StepArtifact, ...
        stepModule.output.linearization_identity_after, ...
        stepModule.meta.interface_name), ...
    "maximumIterations",1, ...
    "initialStateFingerprint",rkkt.validation.stateFingerprint(state));
moduleResult.output = struct( ...
    "status",solution.status, ...
    "convergenceAchieved",solution.convergence_achieved, ...
    "iterationCount",solution.iteration_count, ...
    "finalState",solution.final_state, ...
    "finalStateFingerprint", ...
        rkkt.validation.stateFingerprint(solution.final_state), ...
    "iterationHistory",history);
moduleResult.intermediate = struct( ...
    "contract",contract,"figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "state_order","xi/y/l/z canonical state", ...
    "official_direction","recursive reduction", ...
    "full_kkt_role","independent audit only");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(history,tableFiles(1));
    rkkt.validation.writeTable17(contract,tableFiles(2));
    fig = make_figure(history,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：完整IPM入口单轮验证\n");
fprintf("状态/迭代数：%s/%d\n", ...
    solution.status,solution.iteration_count);
fprintf("方向误差/递推残差/完整KKT残差：%.17g/%.17g/%.17g\n", ...
    history.direction_relative_error, ...
    history.recursive_kkt_relative_residual, ...
    history.full_kkt_relative_residual);
end

function module = load_reference(reference,context,interfaceName)
assert(rkkt.validation.sha256(reference.path)== ...
    lower(string(reference.sha256)), ...
    "rkkt:ipm:validation:ReferenceHash", ...
    "[%s] upstream artifact hash changed: %s",context,reference.path);
module = rkkt.validation.loadResult( ...
    reference.path,context,interfaceName);
end

function fig = make_figure(history,interactive)
fig = rkkt.validation.newFigure("IPM受控轨迹",interactive);
values = [history.r_eq_inf,history.r_ineq_inf, ...
    history.r_dual_scaled_inf,history.mean_lz_scaled];
bar(log10(max(values,realmin)));
xticklabels(["r_{eq}","r_{ineq}","r_{dual}","mean(lz)"]);
ylabel("log_{10} 范数");
title("完整IPM入口单轮残差");
grid on;
end
