function [index,info] = load_or_build_stage_b2c_index( ...
        projectRoot,data,config,options)
%LOAD_OR_BUILD_STAGE_B2C_INDEX Reuse one contiguous-range canonical index.

arguments
    projectRoot (1,1) string
    data (1,1) struct
    config (1,1) struct
    options.Enabled (1,1) logical = true
    options.ForceRebuild (1,1) logical = false
end
projectRoot = canonical_path(projectRoot);
builderFiles = [ ...
    fullfile(projectRoot,"src","+rkkt","+indexing", ...
        "build_canonical_index_framework.m")
    fullfile(projectRoot,"src","+rkkt","+indexing", ...
        "validate_canonical_index_framework.m")
    fullfile(projectRoot,"src","+rkkt","+indexing", ...
        "build_stage_b_index.m")
    fullfile(projectRoot,"src","+rkkt","+indexing", ...
        "build_stage_b2b_index.m")
    fullfile(projectRoot,"src","+rkkt","+indexing", ...
        "build_stage_b2c_index.m")];
builderHashes = strings(numel(builderFiles),1);
for k = 1:numel(builderFiles)
    builderHashes(k) = rkkt.data.compute_sha256_file(builderFiles(k));
end
identity = struct( ...
    "schema","stage-b2c-contiguous-index-cache-v1", ...
    "days",config.days,"hours",config.hours, ...
    "soc_boundary_mode",char(config.soc_boundary_mode), ...
    "time_scope_type",char(config.time_scope_type), ...
    "thermal_pass","pass_1", ...
    "water_constraints_enabled",config.water_constraints_enabled, ...
    "input_hashes",char(strjoin(lower(string( ...
        data.hashes.actualSHA256)),"|")), ...
    "builder_hashes",cellstr(builderHashes));
key = hash_text(jsonencode(identity));
rangeName = compose("days_%03d_%03d",config.days(1),config.days(end));
cachePath = fullfile(projectRoot,"cache","index",rangeName+"_"+ ...
    extractBefore(key,17)+".mat");
info = new_info(options.Enabled,options.ForceRebuild,key,cachePath);

timer = tic;
if options.Enabled && ~options.ForceRebuild && isfile(cachePath)
    loaded = load(cachePath,"index","identity");
    assert(isfield(loaded,"index") && isfield(loaded,"identity") && ...
        isequaln(loaded.identity,identity), ...
        "rkkt:cache:IndexIdentity", ...
        "The range index cache does not match its file identity.");
    index = loaded.index;
    validate_index(index,config);
    info.hit = true;
    info.status = "HIT";
    info.load_seconds = toc(timer);
    return
end

cacheRunId = "CACHE_"+upper(extractBefore(key,13));
index = rkkt.indexing.build_stage_b2c_index( ...
    data,config,"RunId",cacheRunId);
validate_index(index,config);
info.build_seconds = toc(timer);
if options.Enabled
    writeTimer = tic;
    rkkt.artifacts.save_mat_artifact(cachePath, ...
        "index",index,"identity",identity);
    info.write_seconds = toc(writeTimer);
    info.status = "BUILT";
else
    info.status = "DISABLED";
end
end

function validate_index(index,config)
assert(isequal(reshape(index.scope.days,1,[]),config.days) && ...
    isequal(reshape(index.scope.hours,1,[]),config.hours) && ...
    index.counts.variables==config.expected_stage_a_primal_dimension && ...
    index.counts.equalities==config.expected_stage_a_equality_dimension && ...
    index.counts.water_inequalities==config.expected_water_inequality_count && ...
    index.counts.full_kkt_dimension==config.expected_full_kkt_dimension && ...
    height(index.fixed_zero_map)==config.expected_stage_a_fixed_zero_count, ...
    "rkkt:cache:IndexPayload", ...
    "The cached index payload failed its configured range identity check.");
end

function info = new_info(enabled,force,key,pathValue)
info = struct("cache_type","canonical_index","enabled",enabled, ...
    "force_rebuild",force,"hit",false,"status","MISS", ...
    "key",string(key),"path",string(pathValue), ...
    "load_seconds",0,"build_seconds",0,"write_seconds",0);
end

function value = hash_text(textValue)
engine = java.security.MessageDigest.getInstance("SHA-256");
engine.update(unicode2native(char(textValue),"UTF-8"));
bytes = mod(double(engine.digest()),256);
value = lower(string(reshape(dec2hex(bytes,2).',1,[])));
end

function value = canonical_path(pathValue)
value = string(java.io.File(char(pathValue)).getCanonicalPath());
end
