function settings = build_stage_b2c_run_settings(projectRoot,options)
%BUILD_STAGE_B2C_RUN_SETTINGS Build one configured Stage B-2C day scope.

arguments
    projectRoot (1,1) string
    options.DayStart (1,1) double {mustBeInteger,mustBePositive}
    options.DayEnd (1,1) double {mustBeInteger,mustBePositive}
    options.DayScope (1,1) string {mustBeMember(options.DayScope, ...
        ["continuous","screened_307"])} = "continuous"
    options.MaxIterations (1,1) double ...
        {mustBeInteger,mustBePositive} = 100
    options.RequireConvergence (1,1) logical = true
    options.AuditMode (1,1) string {mustBeMember(options.AuditMode, ...
        ["full_kkt","recursive_only"])} = "recursive_only"
    options.RunOutputMode (1,1) string {mustBeMember( ...
        options.RunOutputMode,["lightweight","full_evidence"])} = ...
        "lightweight"
    options.CoreConsistencyMaximumPasses (1,1) double ...
        {mustBeInteger,mustBePositive} = 10
    options.CompensatedCoreAccumulation (1,1) logical = true
    options.ParallelEnabled (1,1) logical = false
    options.ParallelWorkerCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.ParallelPoolAutoResize (1,1) logical = true
    options.ParallelPoolKeepAlive (1,1) logical = true
    options.CacheEnabled (1,1) logical = true
    options.ForceRebuildDataCache (1,1) logical = false
    options.ForceRebuildIndexCache (1,1) logical = false
    options.ForceRebuildRecursiveTemplateCache (1,1) logical = false
    options.RunId (1,1) string = ""
    options.ResumeRunDirectory (1,1) string = ""
    options.ConfigPath (1,1) string = ""
end
root = string(java.io.File(char(projectRoot)).getCanonicalPath());
scope = rkkt.config.resolve_stage_b2c_day_scope( ...
    options.DayScope,options.DayStart,options.DayEnd);
days = scope.days;
assert(options.AuditMode~="full_kkt" || numel(days)==7, ...
    "rkkt:runConfig:FullKktScope", ...
    "full_kkt audit is allowed only for exactly seven contiguous days.");
assert(~options.ParallelEnabled || options.AuditMode=="recursive_only", ...
    "rkkt:runConfig:ParallelAuditMode", ...
    "Parallel day blocks require audit_mode=recursive_only.");
assert(options.AuditMode=="recursive_only" || ...
    options.RunOutputMode=="full_evidence", ...
    "rkkt:runConfig:LightweightRecursiveOnly", ...
    "run_output_mode=lightweight is available only for recursive_only runs.");
assert(options.CoreConsistencyMaximumPasses<=10, ...
    "rkkt:runConfig:CoreConsistencyPassLimit", ...
    "CoreConsistencyMaximumPasses must be inside 1:10.");
assert(strlength(options.RunId)==0 || ...
    strlength(options.ResumeRunDirectory)==0, ...
    "rkkt:runConfig:ResumeRunId", ...
    "RunId and ResumeRunDirectory cannot both be set.");
assert(options.AuditMode=="recursive_only" || ...
    strlength(options.ResumeRunDirectory)==0, ...
    "rkkt:runConfig:FullKktResume", ...
    "Checkpoint resume is available only for recursive_only runs.");
assert(strlength(options.ResumeRunDirectory)==0 || ...
    options.RunOutputMode=="full_evidence", ...
    "rkkt:runConfig:LightweightResume", ...
    "run_output_mode=lightweight does not create resumable checkpoints.");
assert(options.CacheEnabled || ...
    ~(options.ForceRebuildDataCache || options.ForceRebuildIndexCache || ...
        options.ForceRebuildRecursiveTemplateCache), ...
    "rkkt:runConfig:Cache", ...
    "A force-rebuild switch requires CacheEnabled=true.");
configPath = options.ConfigPath;
if strlength(strip(configPath))==0
    configPath = fullfile(root,"config","RUN_PROJECT.yaml");
end
settings = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "day_scope",scope.day_scope, ...
    "day_start",scope.day_start,"day_end",scope.day_end,"days",days, ...
    "explicit_day_set",scope.explicit_day_set, ...
    "excluded_days",scope.excluded_days, ...
    "physical_infeasible_days",scope.physical_infeasible_days, ...
    "numerically_pathological_days", ...
        scope.numerically_pathological_days, ...
    "max_iterations",options.MaxIterations, ...
    "require_convergence",options.RequireConvergence, ...
    "audit_mode",options.AuditMode, ...
    "run_output_mode",options.RunOutputMode, ...
    "core_consistency_max_passes", ...
        options.CoreConsistencyMaximumPasses, ...
    "compensated_core_accumulation", ...
        options.CompensatedCoreAccumulation, ...
    "parallel_enabled",options.ParallelEnabled, ...
    "parallel_worker_count",options.ParallelWorkerCount, ...
    "parallel_pool_auto_resize",options.ParallelPoolAutoResize, ...
    "parallel_pool_keep_alive",options.ParallelPoolKeepAlive, ...
    "cache_enabled",options.CacheEnabled, ...
    "force_rebuild_data_cache",options.ForceRebuildDataCache, ...
    "force_rebuild_index_cache",options.ForceRebuildIndexCache, ...
    "force_rebuild_recursive_template_cache", ...
        options.ForceRebuildRecursiveTemplateCache, ...
    "run_id",options.RunId, ...
    "resume_run_directory",options.ResumeRunDirectory, ...
    "config_path",string(java.io.File(char(configPath)).getCanonicalPath()), ...
    "project_root",root);
end
