function settings = read_run_project_configuration(projectRoot,options)
%READ_RUN_PROJECT_CONFIGURATION Read the editable top-level run controls.

arguments
    projectRoot (1,1) string = rkkt.projectRoot()
    options.ConfigPath (1,1) string = ""
end
projectRoot = canonical_path(projectRoot);
pathValue = options.ConfigPath;
if strlength(strip(pathValue))==0
    pathValue = fullfile(projectRoot,"config","RUN_PROJECT.yaml");
end
pathValue = canonical_path(pathValue);
assert(isfile(pathValue),"rkkt:runConfig:Missing", ...
    "RUN_PROJECT configuration is missing: %s",pathValue);
document = string(fileread(pathValue));

stageId = read_text(document,"stage_id");
milestoneId = read_text(document,"milestone_id");
assert(stageId=="stage_B" && milestoneId=="B-2C", ...
    "rkkt:runConfig:Stage", ...
    "The unified runner is restricted to Stage B-2C.");
settings = rkkt.config.build_stage_b2c_run_settings(projectRoot, ...
    DayScope=read_text(document,"day_scope"), ...
    DayStart=read_integer(document,"day_start"), ...
    DayEnd=read_integer(document,"day_end"), ...
    MaxIterations=read_integer(document,"max_iterations"), ...
    RequireConvergence=read_boolean(document,"require_convergence"), ...
    AuditMode=read_text(document,"audit_mode"), ...
    RunOutputMode=read_text(document,"run_output_mode"), ...
    CoreConsistencyMaximumPasses=read_integer( ...
        document,"core_consistency_max_passes"), ...
    CompensatedCoreAccumulation=read_boolean( ...
        document,"compensated_core_accumulation"), ...
    ParallelEnabled=read_boolean(document,"parallel_enabled"), ...
    ParallelWorkerCount=read_integer(document,"parallel_worker_count"), ...
    ParallelPoolAutoResize=read_boolean( ...
        document,"parallel_pool_auto_resize"), ...
    ParallelPoolKeepAlive=read_boolean( ...
        document,"parallel_pool_keep_alive"), ...
    CacheEnabled=read_boolean(document,"cache_enabled"), ...
    ForceRebuildDataCache=read_boolean( ...
        document,"force_rebuild_data_cache"), ...
    ForceRebuildIndexCache=read_boolean( ...
        document,"force_rebuild_index_cache"), ...
    ForceRebuildRecursiveStructureCache=read_boolean( ...
        document,"force_rebuild_recursive_structure_cache"), ...
    LoadCorrectionEnabled=read_boolean( ...
        document,"load_correction_enabled"), ...
    LoadCorrectionPath=resolve_project_path(projectRoot, ...
        read_optional_text(document,"load_correction_file")), ...
    RunId=read_optional_text(document,"run_id"), ...
    ResumeRunDirectory=read_optional_text( ...
        document,"resume_run_directory"),ConfigPath=pathValue);
end

function value = read_text(document,key)
value = unquote(read_raw(document,key));
assert(strlength(value)>0,"rkkt:runConfig:Text", ...
    "Configuration key %s must not be empty.",key);
end

function value = read_optional_text(document,key)
value = unquote(read_raw(document,key));
end

function value = read_integer(document,key)
value = str2double(read_raw(document,key));
assert(isscalar(value) && isfinite(value) && value==fix(value), ...
    "rkkt:runConfig:Integer", ...
    "Configuration key %s must be an integer.",key);
end

function value = read_boolean(document,key)
raw = lower(read_raw(document,key));
assert(ismember(raw,["true","false"]), ...
    "rkkt:runConfig:Boolean", ...
    "Configuration key %s must be true or false.",key);
value = raw=="true";
end

function value = unquote(value)
if strlength(value)>=2 && ((startsWith(value,'"') && endsWith(value,'"')) || ...
        (startsWith(value,"'") && endsWith(value,"'")))
    value = extractBetween(value,2,strlength(value)-1);
end
value = string(value);
end

function raw = read_raw(document,key)
pattern = ['(?m)^[ \t]*',regexptranslate('escape',char(key)), ...
    '[ \t]*:[ \t]*(.*?)[ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens),"rkkt:runConfig:Key", ...
    "Configuration key %s must occur exactly once.",key);
raw = strip(string(tokens{1}{1}));
comment = strfind(raw," #");
if ~isempty(comment)
    raw = strip(extractBefore(raw,comment(1)));
end
end

function value = canonical_path(pathValue)
value = string(java.io.File(char(pathValue)).getCanonicalPath());
end

function value = resolve_project_path(projectRoot,pathValue)
if strlength(strip(pathValue))==0
    value = "";
elseif java.io.File(char(pathValue)).isAbsolute()
    value = canonical_path(pathValue);
else
    value = canonical_path(fullfile(projectRoot,pathValue));
end
end
