function moduleResult = runDayAggregation(options)
%RUNDAYAGGREGATION Validate fixed-order aggregation of seven day responses.

arguments
    options.InputArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "日响应模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("solver")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
responseModule = rkkt.validation.loadResult( ...
    options.InputArtifact,"runDayAggregation day responses", ...
    "rkkt.solver.buildDayResponse");
rkkt.contracts.requireFields(responseModule.output,"dailyResponses", ...
    "runDayAggregation response output");
rkkt.contracts.requireFields(responseModule.input, ...
    ["linearizationIdentity";"dayIds";"iteration";"revision"], ...
    "runDayAggregation response input");
dailyResponses = responseModule.output.dailyResponses;
expectedDays = 14:20;
shuffleOrder = [7,3,1,6,2,5,4];

legacyForward = rkkt.solver.aggregate_stage_a_multiday_day_responses( ...
    dailyResponses,expectedDays);
aggregation = rkkt.solver.aggregateDayResponses( ...
    dailyResponses,expectedDays);
forwardExact = isequaln(legacyForward,aggregation);

shuffledResponses = dailyResponses(shuffleOrder(:));
legacyShuffled = rkkt.solver.aggregate_stage_a_multiday_day_responses( ...
    shuffledResponses,expectedDays);
shuffledAggregation = rkkt.solver.aggregateDayResponses( ...
    shuffledResponses,expectedDays);
shuffledExact = isequaln(legacyShuffled,shuffledAggregation);

facts = aggregation_facts(aggregation,shuffledAggregation, ...
    dailyResponses,expectedDays,shuffleOrder, ...
    forwardExact,shuffledExact);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:DayAggregationFacts", ...
        "One or more objective day-aggregation observations are false.");
end

orderSummary = order_summary(aggregation,shuffledAggregation);
sumSummary = sum_summary(aggregation);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "七日响应汇总输出.mat", ...
    ["日响应汇总顺序.csv";"S_sum与gamma_sum.csv"], ...
    "七日响应汇总",options.WriteArtifacts);
metadata = rkkt.validation.metadata( ...
    "rkkt.solver.aggregateDayResponses", ...
    "aggregate_stage_a_multiday_day_responses", ...
    options.InputArtifact,outputFile,"七日响应汇总模块", ...
    responseModule.input.iteration,responseModule.input.revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "dayResponseArtifact",rkkt.validation.artifactReference( ...
        options.InputArtifact,aggregation.linearization_identity, ...
        responseModule.meta.interface_name), ...
    "linearizationIdentity", ...
        string(aggregation.linearization_identity), ...
    "upstreamDayIds",reshape(responseModule.input.dayIds,[],1), ...
    "expectedDays",expectedDays, ...
    "shuffleOrder",shuffleOrder, ...
    "iteration",responseModule.input.iteration, ...
    "revision",responseModule.input.revision);
moduleResult.output = struct("aggregation",aggregation);
moduleResult.intermediate = struct( ...
    "orderSummary",orderSummary, ...
    "sumSummary",sumSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "forward_legacy_facade_exact_equal",forwardExact, ...
    "shuffled_legacy_facade_exact_equal",shuffledExact, ...
    "forward_shuffled_S_sum_exact_equal", ...
        isequaln(aggregation.S_sum,shuffledAggregation.S_sum), ...
    "forward_shuffled_gamma_sum_exact_equal", ...
        isequaln(aggregation.gamma_sum, ...
            shuffledAggregation.gamma_sum), ...
    "forward_order_invariant_S_relative_error", ...
        aggregation.order_invariant_S_relative_error, ...
    "forward_order_invariant_gamma_relative_error", ...
        aggregation.order_invariant_gamma_relative_error, ...
    "shuffled_order_invariant_S_relative_error", ...
        shuffledAggregation.order_invariant_S_relative_error, ...
    "shuffled_order_invariant_gamma_relative_error", ...
        shuffledAggregation.order_invariant_gamma_relative_error, ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "input_order",aggregation.input_order, ...
    "shuffled_input_order",shuffledAggregation.input_order, ...
    "accumulation_order",aggregation.day_ids_sorted, ...
    "accumulation_contract",aggregation.accumulation_contract);
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(orderSummary,tableFiles(1));
    rkkt.validation.writeTable17(sumSummary,tableFiles(2));
    fig = aggregation_figure(aggregation,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：七日响应汇总模块\n");
fprintf("正序/打乱输入的新旧结果严格相同：%d/%d\n", ...
    forwardExact,shuffledExact);
fprintf("正序与打乱输入的S_sum/gamma_sum严格相同：%d/%d\n", ...
    isequaln(aggregation.S_sum,shuffledAggregation.S_sum), ...
    isequaln(aggregation.gamma_sum,shuffledAggregation.gamma_sum));
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function facts = aggregation_facts( ...
        aggregation,shuffled,dailyResponses,expectedDays, ...
        shuffleOrder,forwardExact,shuffledExact)
inputDays = reshape([dailyResponses.day_id],1,[]);
sharedIdentity = aggregation.linearization_identity;
identitiesExact = all(arrayfun(@(item)isequaln( ...
    item.linearization_identity,sharedIdentity),dailyResponses));
facts = struct( ...
    "seven_days_exact",numel(dailyResponses)==7, ...
    "stage_exact",string(aggregation.stage_id)=="stage_A4", ...
    "input_order_exact",isequal(inputDays,expectedDays), ...
    "shuffled_input_order_exact",isequal( ...
        shuffled.input_order,expectedDays(shuffleOrder)), ...
    "forward_sorted_days_exact",isequal( ...
        aggregation.day_ids_sorted,expectedDays), ...
    "shuffled_sorted_days_exact",isequal( ...
        shuffled.day_ids_sorted,expectedDays), ...
    "shared_identity_exact",identitiesExact && isequaln( ...
        shuffled.linearization_identity,sharedIdentity), ...
    "forward_legacy_facade_exact_equal",forwardExact, ...
    "shuffled_legacy_facade_exact_equal",shuffledExact, ...
    "S_sum_order_exact",isequaln( ...
        aggregation.S_sum,shuffled.S_sum), ...
    "gamma_sum_order_exact",isequaln( ...
        aggregation.gamma_sum,shuffled.gamma_sum), ...
    "forward_order_invariant_zero", ...
        aggregation.order_invariant_passed && ...
        aggregation.order_invariant_S_relative_error==0 && ...
        aggregation.order_invariant_gamma_relative_error==0, ...
    "shuffled_order_invariant_zero", ...
        shuffled.order_invariant_passed && ...
        shuffled.order_invariant_S_relative_error==0 && ...
        shuffled.order_invariant_gamma_relative_error==0, ...
    "sum_dimensions_exact", ...
        isequal(size(aggregation.S_sum),[14,14]) && ...
        numel(aggregation.gamma_sum)==14);
end

function value = order_summary(forward,shuffled)
position = (1:7).';
forwardInputDayId = forward.input_order(:);
forwardSortPosition = forward.sort_order(:);
forwardSortedDayId = forward.day_ids_sorted(:);
shuffledInputDayId = shuffled.input_order(:);
shuffledSortPosition = shuffled.sort_order(:);
shuffledSortedDayId = shuffled.day_ids_sorted(:);
value = table(position,forwardInputDayId,forwardSortPosition, ...
    forwardSortedDayId,shuffledInputDayId, ...
    shuffledSortPosition,shuffledSortedDayId);
end

function value = sum_summary(aggregation)
sSum = rkkt.validation.smallDense( ...
    aggregation.S_sum,16);
responseIndex = (1:14).';
gammaSum = aggregation.gamma_sum(:);
names = ["responseIndex","gammaSum", ...
    compose("S_sum_column_%02d",1:14)];
value = array2table([responseIndex,gammaSum,sSum], ...
    "VariableNames",cellstr(names));
end

function fig = aggregation_figure(aggregation,interactive)
fig = rkkt.validation.newFigure( ...
    "七日响应汇总",interactive);
layout = tiledlayout(fig,2,1,"TileSpacing","compact");
nexttile(layout);
imagesc(rkkt.validation.smallDense( ...
    aggregation.S_sum,16));
axis tight;
colorbar;
xlabel("列");
ylabel("行");
title("S\_sum（14×14）");
nexttile(layout);
bar(1:14,aggregation.gamma_sum);
xlabel("容量方向");
ylabel("汇总值");
title("gamma\_sum（14×1）");
grid on;
end
