function moduleResult = runDayResponse(options)
%RUNDAYRESPONSE Validate seven side-effect-free daily responses.

arguments
    options.PartitionArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "递推分区模块输出.mat")
    options.DayChainArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "小时链求解模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("solver")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
partitionModule = rkkt.validation.loadResult( ...
    options.PartitionArtifact,"runDayResponse partition", ...
    "rkkt.solver.partitionRecursiveSystem");
dayChainModule = rkkt.validation.loadResult( ...
    options.DayChainArtifact,"runDayResponse day chain", ...
    "rkkt.solver.solveDayChain");
rkkt.contracts.requireFields(partitionModule.output,"partition", ...
    "runDayResponse partition output");
rkkt.contracts.requireFields(dayChainModule.output,"dailyThomas", ...
    "runDayResponse day-chain output");
rkkt.contracts.requireFields(dayChainModule.input, ...
    ["dayIds";"symmetryTolerance";"iteration";"revision"], ...
    "runDayResponse day-chain input");
partition = partitionModule.output.partition;
dailyThomas = dayChainModule.output.dailyThomas;
thomasDayIds = reshape(dayChainModule.input.dayIds,[],1);
symmetryTolerance = dayChainModule.input.symmetryTolerance;

nDays = numel(partition.day);
exactByDay = false(nDays,1);
for d = 1:nDays
    dayId = partition.day(d).day_id;
    thomasPosition = find(thomasDayIds==dayId);
    if numel(thomasPosition) ~= 1
        error("rkkt:solver:validation:DayThomasPairing", ...
            "Day %d must have exactly one Thomas result.",dayId);
    end
    thomas = dailyThomas(thomasPosition);
    legacy = rkkt.solver.form_stage_a_multiday_day_response( ...
        partition.day(d),thomas);
    response = rkkt.solver.buildDayResponse( ...
        partition.day(d),thomas);
    exactByDay(d) = isequaln(legacy,response);
    if d == 1
        dailyResponses = response;
    else
        dailyResponses(d,1) = response;
    end
end

[facts,metrics] = response_facts( ...
    partition,dailyResponses,exactByDay,symmetryTolerance);
facts.production_side_effect_tokens_absent = ...
    production_side_effect_tokens_absent();
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:DayResponseFacts", ...
        "One or more objective daily-response observations are false.");
end

responseSummary = response_summary(partition,dailyResponses,metrics);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "日响应模块输出.mat","七日日响应摘要.csv", ...
    "日响应对称误差",options.WriteArtifacts);
metadata = rkkt.validation.metadata("rkkt.solver.buildDayResponse", ...
    "form_stage_a_multiday_day_response", ...
    options.DayChainArtifact,outputFile,"日响应模块", ...
    dayChainModule.input.iteration,dayChainModule.input.revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "partitionArtifact",rkkt.validation.artifactReference( ...
        options.PartitionArtifact,partition.linearization_identity, ...
        partitionModule.meta.interface_name), ...
    "dayChainArtifact",rkkt.validation.artifactReference( ...
        options.DayChainArtifact,partition.linearization_identity, ...
        dayChainModule.meta.interface_name), ...
    "linearizationIdentity",string(partition.linearization_identity), ...
    "dayIds",reshape([dailyResponses.day_id],[],1), ...
    "symmetryTolerance",symmetryTolerance, ...
    "chainResidualThreshold",1e-10, ...
    "formulaRelativeThreshold",1e-14, ...
    "iteration",dayChainModule.input.iteration, ...
    "revision",dayChainModule.input.revision);
moduleResult.output = struct("dailyResponses",dailyResponses);
moduleResult.intermediate = struct( ...
    "responseSummary",responseSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal_by_day",exactByDay, ...
    "legacy_facade_all_exact_equal",all(exactByDay), ...
    "maximum_symmetry_relative",max(metrics.symmetryRelative), ...
    "maximum_a_equation_relative",max(metrics.aEquationRelative), ...
    "maximum_U_equation_relative",max(metrics.uEquationRelative), ...
    "maximum_S_formula_relative",max(metrics.sFormulaRelative), ...
    "maximum_c_formula_relative",max(metrics.cFormulaRelative), ...
    "maximum_gamma_formula_relative",max(metrics.gammaFormulaRelative), ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "day_order",reshape([dailyResponses.day_id],[],1), ...
    "response_dimension",14, ...
    "response_contract","v_d=a_d-U_d*Delta_q_d");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(responseSummary,tableFiles(1));
    fig = symmetry_figure(responseSummary,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：日响应模块\n");
fprintf("7组新旧日响应严格相同：%d\n",all(exactByDay));
fprintf("最大日响应对称误差：%.17g\n", ...
    max(metrics.symmetryRelative));
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function [facts,metrics] = response_facts( ...
        partition,responses,exactByDay,symmetryTolerance)
nDays = numel(responses);
metrics = struct( ...
    "aEquationRelative",zeros(nDays,1), ...
    "uEquationRelative",zeros(nDays,1), ...
    "sFormulaRelative",zeros(nDays,1), ...
    "cFormulaRelative",zeros(nDays,1), ...
    "gammaFormulaRelative",zeros(nDays,1), ...
    "symmetryRelative",zeros(nDays,1));
identityExact = true;
dimensionsExact = true;
betaExact = true;
contractsDeclared = true;
for d = 1:nDays
    day = partition.day(d);
    response = responses(d);
    metrics.aEquationRelative(d) = ...
        norm(day.M*response.a-day.r_v,2)/max(1,norm(day.r_v,2));
    metrics.uEquationRelative(d) = ...
        norm(day.M*response.U-day.B,"fro")/ ...
        max(1,norm(day.B,"fro"));
    metrics.sFormulaRelative(d) = ...
        norm(response.S-(day.C-day.B.'*response.U),"fro")/ ...
        max(1,norm(response.S,"fro"));
    metrics.cFormulaRelative(d) = ...
        norm(response.c-(day.r_q_day-day.B.'*response.a),2)/ ...
        max(1,norm(response.c,2));
    metrics.gammaFormulaRelative(d) = ...
        norm(response.gamma-(response.c-response.S*response.beta),2)/ ...
        max(1,norm(response.gamma,2));
    metrics.symmetryRelative(d) = response.diagnostics.symmetry_relative;
    identityExact = identityExact && isequaln( ...
        response.linearization_identity,partition.linearization_identity);
    dimensionsExact = dimensionsExact && ...
        isequal(size(response.S),[14,14]) && ...
        isequal(size(response.c),[14,1]) && ...
        isequal(size(response.beta),[14,1]) && ...
        isequal(size(response.gamma),[14,1]);
    betaExact = betaExact && isequaln(response.beta,-day.r_binding);
    contractsDeclared = contractsDeclared && ...
        response.diagnostics.side_effect_free && ...
        response.diagnostics.c_gamma_distinct_formula;
end
facts = struct( ...
    "seven_responses_exact",nDays==7 && ...
        isequal(reshape([responses.day_id],1,[]),14:20), ...
    "legacy_facade_all_exact_equal",all(exactByDay), ...
    "identity_exact",identityExact, ...
    "dimensions_exact",dimensionsExact, ...
    "a_chain_equations_within_threshold", ...
        all(metrics.aEquationRelative<=1e-10), ...
    "U_chain_equations_within_threshold", ...
        all(metrics.uEquationRelative<=1e-10), ...
    "S_formula_within_threshold", ...
        all(metrics.sFormulaRelative<=1e-14), ...
    "c_formula_within_threshold", ...
        all(metrics.cFormulaRelative<=1e-14), ...
    "gamma_formula_within_threshold", ...
        all(metrics.gammaFormulaRelative<=1e-14), ...
    "beta_formula_exact",betaExact, ...
    "symmetry_within_threshold", ...
        all(metrics.symmetryRelative<=symmetryTolerance), ...
    "distinct_contracts_declared",contractsDeclared);
end

function value = production_side_effect_tokens_absent()
root = rkkt.projectRoot();
source = lower(string(fileread(fullfile(root,"src","+rkkt","+solver", ...
    "form_stage_a_multiday_day_response.m"))));
tokens = ["global ";"persistent ";"assignin("; ...
    "evalin(";"save(";"writetable(";"fopen("];
value = ~any(arrayfun(@(token)contains(source,token),tokens));
end

function value = response_summary(partition,responses,metrics)
dayId = reshape([responses.day_id],[],1);
chainDimension = reshape([partition.day.hourly_chain_dimension],[],1);
rhsCount = reshape(arrayfun( ...
    @(item)item.diagnostics.rhs_count,responses),[],1);
symmetryRelative = metrics.symmetryRelative;
aEquationRelative = metrics.aEquationRelative;
uEquationRelative = metrics.uEquationRelative;
sFormulaRelative = metrics.sFormulaRelative;
cFormulaRelative = metrics.cFormulaRelative;
gammaFormulaRelative = metrics.gammaFormulaRelative;
value = table(dayId,chainDimension,rhsCount,symmetryRelative, ...
    aEquationRelative,uEquationRelative,sFormulaRelative, ...
    cFormulaRelative,gammaFormulaRelative);
end

function fig = symmetry_figure(summary,interactive)
fig = rkkt.validation.newFigure( ...
    "七日日响应对称误差",interactive);
semilogy(summary.dayId,max(summary.symmetryRelative,realmin), ...
    "-o","LineWidth",1.4);
xlabel("日期");
ylabel("S对称相对误差");
title("第14—20日日响应对称性");
grid on;
end
