function moduleResult = runDayChain(options)
%RUNDAYCHAIN Validate seven serial 24-hour block-Thomas solves.

arguments
    options.PartitionArtifact (1,1) string = ...
        rkkt.solver.validation.ValidationSupport.solverArtifact( ...
        "递推分区模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.solver.validation.ValidationSupport.outputDirectory()
end

support = rkkt.solver.validation.ValidationSupport;
support.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
partitionModule = support.loadResult( ...
    options.PartitionArtifact,"runDayChain partition", ...
    "rkkt.solver.partitionRecursiveSystem");
rkkt.contracts.requireFields(partitionModule.output,"partition", ...
    "runDayChain partition output");
rkkt.contracts.requireFields(partitionModule.input, ...
    ["symmetryTolerance";"residualRefinementMaxPasses"; ...
    "iteration";"revision"],"runDayChain partition input");
partition = partitionModule.output.partition;
symmetryTolerance = partitionModule.input.symmetryTolerance;
maximumPasses = partitionModule.input.residualRefinementMaxPasses;
if maximumPasses ~= 0
    error("rkkt:solver:validation:RefinementMustRemainDisabled", ...
        "PKG-6 requires ResidualRefinementMaxPasses=0.");
end

nDays = numel(partition.day);
exactByDay = false(nDays,1);
for d = 1:nDays
    legacy = support.callProduction("solve_block_thomas_ldl", ...
        partition.day(d),"SymmetryTolerance",symmetryTolerance, ...
        "ResidualRefinementMaxPasses",maximumPasses);
    thomas = rkkt.solver.solveDayChain(partition.day(d), ...
        SymmetryTolerance=symmetryTolerance, ...
        ResidualRefinementMaxPasses=maximumPasses);
    exactByDay(d) = isequaln(legacy,thomas);
    if d == 1
        dailyThomas = thomas;
    else
        dailyThomas(d,1) = thomas;
    end
end
dayIds = reshape([partition.day.day_id],[],1);
facts = day_chain_facts( ...
    partition,dailyThomas,exactByDay,maximumPasses);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:DayChainFacts", ...
        "One or more objective day-chain observations are false.");
end

dailySummary = daily_summary(partition,dailyThomas);
hourlySummary = hourly_summary(dayIds,dailyThomas);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    support.outputPaths(options.OutputDirectory, ...
    "小时链求解模块输出.mat", ...
    ["Thomas逐日残差.csv";"小时LDL诊断.csv"], ...
    "Thomas残差",options.WriteArtifacts);
metadata = support.metadata("rkkt.solver.solveDayChain", ...
    "solve_block_thomas_ldl",options.PartitionArtifact, ...
    outputFile,"小时链求解模块", ...
    partitionModule.input.iteration,partitionModule.input.revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "partitionArtifact",support.artifactReference( ...
        options.PartitionArtifact,partition.linearization_identity, ...
        partitionModule.meta.interface_name), ...
    "linearizationIdentity",string(partition.linearization_identity), ...
    "dayIds",dayIds, ...
    "symmetryTolerance",symmetryTolerance, ...
    "chainResidualThreshold",1e-10, ...
    "residualRefinementMaxPasses",maximumPasses, ...
    "iteration",partitionModule.input.iteration, ...
    "revision",partitionModule.input.revision);
moduleResult.output = struct("dailyThomas",dailyThomas);
moduleResult.intermediate = struct( ...
    "dailySummary",dailySummary, ...
    "hourlySummary",hourlySummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal_by_day",exactByDay, ...
    "legacy_facade_all_exact_equal",all(exactByDay), ...
    "maximum_chain_relative_residual", ...
        max(dailySummary.chainRelativeResidual), ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "day_order",dayIds, ...
    "hour_order",(1:24).', ...
    "rhs_order","[物理右端,14个容量右端]", ...
    "factorization_contract","每小时块一次LDL分解，统一求解15个RHS");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    support.writeTable17(dailySummary,tableFiles(1));
    support.writeTable17(hourlySummary,tableFiles(2));
    fig = residual_figure(dailySummary,options.Interactive);
    support.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    support.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：小时链求解模块\n");
fprintf("7日新旧Thomas结果严格相同：%d\n",all(exactByDay));
fprintf("最大Thomas相对残差：%.17g\n", ...
    max(dailySummary.chainRelativeResidual));
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function facts = day_chain_facts( ...
        partition,dailyThomas,exactByDay,maximumPasses)
identityExact = true;
factorCountExact = true;
rhsExact = true;
residualWithin = true;
inertiaExact = true;
refinementDisabled = maximumPasses==0;
for d = 1:7
    item = dailyThomas(d);
    identityExact = identityExact && isequaln( ...
        item.linearization_identity,partition.linearization_identity);
    factorCountExact = factorCountExact && ...
        numel(item.factors)==24 && ...
        numel(item.diagnostics.hour_block)==24;
    rhsExact = rhsExact && item.rhs_count==15 && ...
        all([item.diagnostics.hour_block.rhs_count]==15);
    residualWithin = residualWithin && ...
        item.diagnostics.chain_relative_residual<=1e-10;
    inertiaExact = inertiaExact && ...
        all([item.diagnostics.hour_block.schur_inertia_zero]==0);
    refinement = item.diagnostics.residual_refinement;
    refinementDisabled = refinementDisabled && ...
        ~refinement.enabled && refinement.maximum_passes==0 && ...
        refinement.additional_factorization_count==0 && ...
        ~refinement.direct_chain_backslash_used;
end
facts = struct( ...
    "seven_days_exact",numel(dailyThomas)==7 && ...
        isequal(reshape([partition.day.day_id],1,[]),14:20), ...
    "legacy_facade_all_exact_equal",all(exactByDay), ...
    "identity_exact",identityExact, ...
    "twenty_four_factors_each",factorCountExact, ...
    "fifteen_rhs_each",rhsExact, ...
    "chain_residual_within_threshold",residualWithin, ...
    "zero_inertia_absent",inertiaExact, ...
    "residual_refinement_disabled",refinementDisabled);
end

function value = daily_summary(partition,dailyThomas)
dayId = reshape([partition.day.day_id],[],1);
chainDimension = reshape([partition.day.hourly_chain_dimension],[],1);
nDays = numel(dailyThomas);
factorCount = zeros(nDays,1);
rhsCount = zeros(nDays,1);
chainRelativeResidual = zeros(nDays,1);
chainMaximumAbsoluteResidual = zeros(nDays,1);
maximumInertiaZero = zeros(nDays,1);
for d = 1:nDays
    factorCount(d) = numel(dailyThomas(d).factors);
    rhsCount(d) = dailyThomas(d).rhs_count;
    chainRelativeResidual(d) = ...
        dailyThomas(d).diagnostics.chain_relative_residual;
    chainMaximumAbsoluteResidual(d) = ...
        dailyThomas(d).diagnostics.chain_max_absolute_residual;
    maximumInertiaZero(d) = max( ...
        [dailyThomas(d).diagnostics.hour_block.schur_inertia_zero]);
end
value = table(dayId,chainDimension,factorCount,rhsCount, ...
    chainRelativeResidual,chainMaximumAbsoluteResidual, ...
    maximumInertiaZero);
end

function value = hourly_summary(dayIds,dailyThomas)
n = numel(dailyThomas)*24;
dayId = zeros(n,1);
hour = zeros(n,1);
dimension = zeros(n,1);
rhsCount = zeros(n,1);
schurNnz = zeros(n,1);
schurSymmetryRelative = zeros(n,1);
schurInertiaPositive = zeros(n,1);
schurInertiaNegative = zeros(n,1);
schurInertiaZero = zeros(n,1);
schurFactorRelativeResidual = zeros(n,1);
row = 0;
for d = 1:numel(dailyThomas)
    diagnostics = dailyThomas(d).diagnostics.hour_block;
    for t = 1:numel(diagnostics)
        row = row+1;
        item = diagnostics(t);
        dayId(row) = dayIds(d);
        hour(row) = item.hour;
        dimension(row) = item.dimension;
        rhsCount(row) = item.rhs_count;
        schurNnz(row) = item.schur_nnz;
        schurSymmetryRelative(row) = item.schur_symmetry_relative;
        schurInertiaPositive(row) = item.schur_inertia_positive;
        schurInertiaNegative(row) = item.schur_inertia_negative;
        schurInertiaZero(row) = item.schur_inertia_zero;
        schurFactorRelativeResidual(row) = ...
            item.schur_factor_relative_residual;
    end
end
value = table(dayId,hour,dimension,rhsCount,schurNnz, ...
    schurSymmetryRelative,schurInertiaPositive, ...
    schurInertiaNegative,schurInertiaZero, ...
    schurFactorRelativeResidual);
end

function fig = residual_figure(summary,interactive)
fig = rkkt.solver.validation.ValidationSupport.newFigure( ...
    "Thomas逐日残差",interactive);
semilogy(summary.dayId,summary.chainRelativeResidual, ...
    "-o","LineWidth",1.4);
xlabel("日期");
ylabel("链相对残差");
title("第14—20日块Thomas残差");
grid on;
end
