function moduleResult = runFullKKT(options)
%RUNFULLKKT Validate formal full-KKT assembly and sparse audit direction.
%   The only numerical input is the existing shared-linearization MAT.

arguments
    options.InputArtifact (1,1) string = default_input_artifact()
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = default_output_directory()
end

inputArtifact = string(options.InputArtifact);
outputDirectory = string(options.OutputDirectory);
rkkt.model.validation.ValidationSupport.requireOutputDirectory( ...
    outputDirectory,options.WriteArtifacts);
upstream = rkkt.model.validation.ValidationSupport.loadResult( ...
    inputArtifact,"runFullKKT");
if string(upstream.meta.interface_name) ~= "rkkt.model.linearize"
    error("rkkt:solver:validation:FullKktUpstreamInterface", ...
        "runFullKKT requires the shared linearization artifact.");
end
rkkt.contracts.requireFields(upstream.input, ...
    ["projectData";"config"],"runFullKKT upstream.input");
rkkt.contracts.requireFields(upstream.output,"linearization", ...
    "runFullKKT upstream.output");
linearization = upstream.output.linearization;
config = upstream.input.config;
projectRoot = string(upstream.input.projectData.projectRoot);

legacyAssembly = call_legacy_assembly(linearization);
assembly = rkkt.solver.assembleFullKKT(linearization);
legacyFullResult = call_legacy_solve(linearization);
fullResult = rkkt.solver.solveFullKKT(linearization);
assemblyExact = isequaln(legacyAssembly,assembly);
fullResultExact = isequaln(legacyFullResult,fullResult);
assemblyInsideResultExact = isequaln(assembly,fullResult.kkt);
facts = inspect_full_kkt(assembly,fullResult,linearization, ...
    config,assemblyExact,fullResultExact,assemblyInsideResultExact);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:FullKktFacts", ...
        "One or more objective full-KKT observations are false.");
end

dimensionSummary = dimension_summary(fullResult);
residualSummary = residual_summary(fullResult,config);
blockSummary = block_summary(fullResult.kkt.slices);
[outputFile,tableFiles,figureFiles,figureIndex] = output_paths( ...
    outputDirectory,options.WriteArtifacts);
metadata = rkkt.model.validation.ValidationSupport.metadata( ...
    "rkkt.solver.solveFullKKT", ...
    "solve_stage_a_multiday_full_kkt_direction", ...
    inputArtifact,projectRoot,outputFile,"完整KKT模块", ...
    linearization.state.iteration_index, ...
    linearization.state.state_revision, ...
    options.Interactive,options.WriteArtifacts);
metadata.assembly_interface = "rkkt.solver.assembleFullKKT";
metadata.assembly_production_function = ...
    "assemble_stage_a_multiday_full_kkt";
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "linearizationArtifact",inputArtifact, ...
    "linearizationSha256",metadata.input_sha256, ...
    "linearizationIdentity",string(linearization.identity), ...
    "stageId",string(linearization.stage_id), ...
    "counts",linearization.counts, ...
    "directResidualThreshold",config.tolerances.direct_maximum, ...
    "upstreamInterface",string(upstream.meta.interface_name));
moduleResult.output = struct("fullResult",fullResult);
moduleResult.intermediate = struct( ...
    "dimensionSummary",dimensionSummary, ...
    "residualSummary",residualSummary, ...
    "blockSummary",blockSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "assembly_legacy_facade_exact_equal",assemblyExact, ...
    "solve_legacy_facade_exact_equal",fullResultExact, ...
    "assembly_inside_result_exact_equal", ...
        assemblyInsideResultExact, ...
    "linearization_identity",string(fullResult.linearization_identity), ...
    "dimension",fullResult.kkt.dimension, ...
    "matrix_nonzeros",fullResult.kkt.nnz, ...
    "relative_residual",fullResult.diagnostics.relative_residual, ...
    "max_absolute_residual", ...
        fullResult.diagnostics.max_absolute_residual, ...
    "warning_present",fullResult.diagnostics.warning_present, ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "direction_order","[dxi;dy;dl;dz]", ...
    "matrix_order","stationarity/equality/slack/complementarity", ...
    "role","完整方向仅作审计基准，不更新状态", ...
    "matrix_storage","完整稀疏矩阵仅存在于fullResult.kkt");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.model.validation.ValidationSupport.writeTable17( ...
        dimensionSummary,tableFiles(1));
    rkkt.model.validation.ValidationSupport.writeTable17( ...
        residualSummary,tableFiles(2));
    rkkt.model.validation.ValidationSupport.writeTable17( ...
        blockSummary,tableFiles(3));
    fig = full_kkt_figure(fullResult,options.Interactive);
    rkkt.model.validation.ValidationSupport.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.model.validation.ValidationSupport.saveResult( ...
        outputFile,moduleResult);
end

fprintf("当前模块：完整KKT模块\n");
fprintf("公共接口：rkkt.solver.assembleFullKKT / solveFullKKT\n");
fprintf("装配/求解新旧结果严格相同：%d/%d\n", ...
    assemblyExact,fullResultExact);
fprintf("维数/nnz/相对残差：%d/%d/%.17g\n", ...
    fullResult.kkt.dimension,fullResult.kkt.nnz, ...
    fullResult.diagnostics.relative_residual);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function value = call_legacy_assembly(linearization)
[solverDirectory,productionFile] = production_location( ...
    "assemble_stage_a_multiday_full_kkt.m");
originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(solverDirectory,"-begin");
resolved = string(which("assemble_stage_a_multiday_full_kkt"));
if ~same_path(resolved,productionFile)
    error("rkkt:solver:validation:AssemblyFunctionShadowed", ...
        "Expected assembly function at '%s'; resolved '%s'.", ...
        productionFile,resolved);
end
value = assemble_stage_a_multiday_full_kkt(linearization);
clear pathGuard
end

function value = call_legacy_solve(linearization)
[solverDirectory,productionFile] = production_location( ...
    "solve_stage_a_multiday_full_kkt_direction.m");
originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(solverDirectory,"-begin");
resolved = string(which( ...
    "solve_stage_a_multiday_full_kkt_direction"));
if ~same_path(resolved,productionFile)
    error("rkkt:solver:validation:SolveFunctionShadowed", ...
        "Expected solve function at '%s'; resolved '%s'.", ...
        productionFile,resolved);
end
value = solve_stage_a_multiday_full_kkt_direction(linearization);
clear pathGuard
end

function facts = inspect_full_kkt(assembly,fullResult, ...
        linearization,config,assemblyExact,fullResultExact, ...
        assemblyInsideResultExact)
facts = struct( ...
    "assembly_legacy_facade_exact_equal",assemblyExact, ...
    "solve_legacy_facade_exact_equal",fullResultExact, ...
    "assembly_inside_result_exact_equal",assemblyInsideResultExact, ...
    "stage_exact", ...
        string(linearization.stage_id) == "stage_A4" && ...
        string(assembly.stage_id) == "stage_A4" && ...
        string(fullResult.stage_id) == "stage_A4", ...
    "identities_exact", ...
        isequaln(assembly.linearization_identity, ...
            linearization.identity) && ...
        isequaln(fullResult.linearization_identity, ...
            linearization.identity), ...
    "matrix_sparse", ...
        issparse(assembly.matrix) && ...
        issparse(fullResult.kkt.matrix), ...
    "controlled_dimension",fullResult.kkt.dimension == 18836 && ...
        isequal(size(fullResult.kkt.matrix),[18836,18836]) && ...
        isequal(size(fullResult.kkt.rhs),[18836,1]), ...
    "controlled_slices",controlled_slices(fullResult.kkt.slices), ...
    "direction_dimensions", ...
        numel(fullResult.direction) == 18836 && ...
        numel(fullResult.components.xi) == 3722 && ...
        numel(fullResult.components.y) == 618 && ...
        numel(fullResult.components.l) == 7248 && ...
        numel(fullResult.components.z) == 7248, ...
    "direction_components_exact", ...
        components_match_direction(fullResult), ...
    "relative_residual_within_threshold", ...
        fullResult.diagnostics.relative_residual <= ...
            config.tolerances.direct_maximum, ...
    "no_solve_warning", ...
        ~fullResult.diagnostics.warning_present && ...
        strlength(fullResult.diagnostics.warning_id) == 0 && ...
        strlength(fullResult.diagnostics.warning_message) == 0, ...
    "audit_method_exact", ...
        string(fullResult.method) == "sparse_backslash_audit");
end

function value = controlled_slices(slices)
value = ...
    isequal(slices.xi,(1:3722).') && ...
    isequal(slices.y,(3723:4340).') && ...
    isequal(slices.l,(4341:11588).') && ...
    isequal(slices.z,(11589:18836).') && ...
    isequal(slices.stationarity_rows,(1:3722).') && ...
    isequal(slices.equality_rows,(3723:4340).') && ...
    isequal(slices.slack_rows,(4341:11588).') && ...
    isequal(slices.complementarity_rows,(11589:18836).');
end

function value = components_match_direction(fullResult)
slices = fullResult.kkt.slices;
value = ...
    isequaln(fullResult.components.xi, ...
        fullResult.direction(slices.xi)) && ...
    isequaln(fullResult.components.y, ...
        fullResult.direction(slices.y)) && ...
    isequaln(fullResult.components.l, ...
        fullResult.direction(slices.l)) && ...
    isequaln(fullResult.components.z, ...
        fullResult.direction(slices.z));
end

function value = dimension_summary(fullResult)
matrixName = "complete_primal_dual_KKT";
rowCount = size(fullResult.kkt.matrix,1);
columnCount = size(fullResult.kkt.matrix,2);
nonzeroCount = nnz(fullResult.kkt.matrix);
density = nonzeroCount/(rowCount*columnCount);
sparseStorage = issparse(fullResult.kkt.matrix);
directionCount = numel(fullResult.direction);
value = table(matrixName,rowCount,columnCount,nonzeroCount, ...
    density,sparseStorage,directionCount);
end

function value = residual_summary(fullResult,config)
method = string(fullResult.method);
relativeResidual = fullResult.diagnostics.relative_residual;
relativeThreshold = config.tolerances.direct_maximum;
maxAbsoluteResidual = fullResult.diagnostics.max_absolute_residual;
maxResidualRow = fullResult.diagnostics.max_residual_row;
warningPresent = fullResult.diagnostics.warning_present;
warningId = string(fullResult.diagnostics.warning_id);
warningMessage = string(fullResult.diagnostics.warning_message);
value = table(method,relativeResidual,relativeThreshold, ...
    maxAbsoluteResidual,maxResidualRow,warningPresent, ...
    warningId,warningMessage);
end

function value = block_summary(slices)
objectKind = [repmat("direction",4,1);repmat("equation_row",4,1)];
blockName = ["xi";"y";"l";"z";"stationarity"; ...
    "equality";"slack";"complementarity"];
vectors = {slices.xi;slices.y;slices.l;slices.z; ...
    slices.stationarity_rows;slices.equality_rows; ...
    slices.slack_rows;slices.complementarity_rows};
n = numel(vectors);
startIndex = zeros(n,1);
endIndex = zeros(n,1);
elementCount = zeros(n,1);
for k = 1:n
    startIndex(k) = vectors{k}(1);
    endIndex(k) = vectors{k}(end);
    elementCount(k) = numel(vectors{k});
end
value = table(objectKind,blockName,startIndex,endIndex,elementCount);
end

function fig = full_kkt_figure(fullResult,interactive)
visibility = "off";
if interactive
    visibility = "on";
end
fig = figure("Name","完整KKT：稀疏结构", ...
    "NumberTitle","off","Color","w","Visible",visibility, ...
    "Position",[100,100,920,720]);
spy(fullResult.kkt.matrix);
title(compose("完整KKT：%d×%d，nnz=%d", ...
    fullResult.kkt.dimension,fullResult.kkt.dimension, ...
    fullResult.kkt.nnz));
end

function [outputFile,tableFiles,figureFiles,index] = ...
        output_paths(outputDirectory,writeArtifacts)
if writeArtifacts
    outputFile = fullfile(outputDirectory,"完整KKT模块输出.mat");
    tableFiles = [ ...
        fullfile(outputDirectory,"完整KKT维数与稀疏性.csv")
        fullfile(outputDirectory,"完整KKT方向残差.csv")
        fullfile(outputDirectory,"完整KKT分块范围.csv")];
    figPath = fullfile(outputDirectory,"完整KKT稀疏结构.fig");
    pngPath = fullfile(outputDirectory,"完整KKT稀疏结构.png");
    figureFiles = [figPath;pngPath];
else
    outputFile = "";
    tableFiles = strings(0,1);
    figPath = "";
    pngPath = "";
    figureFiles = strings(0,1);
end
tableFiles = reshape(string(tableFiles),[],1);
figureFiles = reshape(string(figureFiles),[],1);
index = struct("figPath",string(figPath),"pngPath",string(pngPath));
end

function [directory,file] = production_location(fileName)
validationDirectory = string(fileparts(mfilename("fullpath")));
packageDirectory = string(fileparts(validationDirectory));
rkktDirectory = string(fileparts(packageDirectory));
sourceDirectory = string(fileparts(rkktDirectory));
directory = fullfile(sourceDirectory,"solver");
file = fullfile(directory,fileName);
end

function value = default_input_artifact()
validationDirectory = string(fileparts(mfilename("fullpath")));
solverDirectory = string(fileparts(validationDirectory));
rkktDirectory = string(fileparts(solverDirectory));
value = fullfile(rkktDirectory,"+model","+validation", ...
    "统一线性化模块输出.mat");
end

function value = default_output_directory()
value = string(fileparts(mfilename("fullpath")));
end

function value = same_path(left,right)
left = replace(string(left),"/","\");
right = replace(string(right),"/","\");
if ispc
    value = strcmpi(left,right);
else
    value = strcmp(left,right);
end
end
