function moduleResult = runGlobalCore(options)
%RUNGLOBALCORE Validate the retained 16-dimensional global LDL core.

arguments
    options.PartitionArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "递推分区模块输出.mat")
    options.AggregationArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "七日响应汇总输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("solver")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
partitionModule = rkkt.validation.loadResult( ...
    options.PartitionArtifact,"runGlobalCore partition", ...
    "rkkt.solver.partitionRecursiveSystem");
aggregationModule = rkkt.validation.loadResult( ...
    options.AggregationArtifact,"runGlobalCore aggregation", ...
    "rkkt.solver.aggregateDayResponses");
rkkt.contracts.requireFields(partitionModule.output,"partition", ...
    "runGlobalCore partition output");
rkkt.contracts.requireFields(aggregationModule.output,"aggregation", ...
    "runGlobalCore aggregation output");
rkkt.contracts.requireFields(partitionModule.input, ...
    ["symmetryTolerance";"residualRefinementMaxPasses"; ...
    "iteration";"revision"],"runGlobalCore partition input");
partition = partitionModule.output.partition;
aggregation = aggregationModule.output.aggregation;
symmetryTolerance = partitionModule.input.symmetryTolerance;
maximumPasses = partitionModule.input.residualRefinementMaxPasses;
if maximumPasses ~= 0
    error("rkkt:solver:validation:RefinementMustRemainDisabled", ...
        "PKG-6 requires ResidualRefinementMaxPasses=0.");
end

legacy = rkkt.solver.solve_stage_a_multiday_core16_ldl( ...
    partition,aggregation, ...
    "SymmetryTolerance",symmetryTolerance, ...
    "ResidualRefinementMaxPasses",maximumPasses);
core = rkkt.solver.solveGlobalCore(partition,aggregation, ...
    SymmetryTolerance=symmetryTolerance, ...
    ResidualRefinementMaxPasses=maximumPasses);
legacyFacadeExact = isequaln(legacy,core);
facts = core_facts(partition,aggregation,core, ...
    legacyFacadeExact,symmetryTolerance,maximumPasses);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:GlobalCoreFacts", ...
        "One or more objective global-core observations are false.");
end

matrixSummary = rkkt.validation.matrixTable(core.matrix,"rowIndex");
rhsSolutionSummary = rhs_solution_summary(core);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "16维全局核心模块输出.mat", ...
    ["16维核心矩阵.csv";"16维核心RHS与解.csv"], ...
    "16维全局核心",options.WriteArtifacts);
metadata = rkkt.validation.metadata("rkkt.solver.solveGlobalCore", ...
    "solve_stage_a_multiday_core16_ldl", ...
    options.AggregationArtifact,outputFile,"16维全局核心模块", ...
    partitionModule.input.iteration,partitionModule.input.revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "partitionArtifact",rkkt.validation.artifactReference( ...
        options.PartitionArtifact,partition.linearization_identity, ...
        partitionModule.meta.interface_name), ...
    "aggregationArtifact",rkkt.validation.artifactReference( ...
        options.AggregationArtifact,aggregation.linearization_identity, ...
        aggregationModule.meta.interface_name), ...
    "linearizationIdentity",string(partition.linearization_identity), ...
    "symmetryTolerance",symmetryTolerance, ...
    "coreResidualThreshold",1e-10, ...
    "residualRefinementMaxPasses",maximumPasses, ...
    "iteration",partitionModule.input.iteration, ...
    "revision",partitionModule.input.revision);
moduleResult.output = struct("core",core);
moduleResult.intermediate = struct( ...
    "matrixSummary",matrixSummary, ...
    "rhsSolutionSummary",rhsSolutionSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "linearization_identity",string(core.linearization_identity), ...
    "dimension",size(core.matrix,1), ...
    "matrix_nonzeros",nnz(core.matrix), ...
    "relative_residual",core.diagnostics.relative_residual, ...
    "maximum_absolute_residual", ...
        core.diagnostics.max_absolute_residual, ...
    "inertia_zero",core.diagnostics.factor.inertia_zero, ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "solution_order","[delta_q(14);delta_rho(2)]", ...
    "day_order",aggregation.day_ids_sorted, ...
    "core_dimension",16, ...
    "factorization","现有LDL，一次分解，无残差精化");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(matrixSummary,tableFiles(1));
    rkkt.validation.writeTable17(rhsSolutionSummary,tableFiles(2));
    fig = core_figure(core,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：16维全局核心模块\n");
fprintf("新旧全局核心结果严格相同：%d\n",legacyFacadeExact);
fprintf("核心维数/nnz/相对残差：%d/%d/%.17g\n", ...
    size(core.matrix,1),nnz(core.matrix), ...
    core.diagnostics.relative_residual);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function facts = core_facts(partition,aggregation,core, ...
        legacyFacadeExact,symmetryTolerance,maximumPasses)
expectedMatrix = [ ...
    partition.global.Q+aggregation.S_sum,partition.global.R.'; ...
    partition.global.R,sparse(2,2)];
expectedRhs = [ ...
    partition.global.b_q+aggregation.gamma_sum; ...
    -partition.global.r_duration];
refinement = core.diagnostics.residual_refinement;
facts = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "stage_exact",string(core.stage_id)=="stage_A4", ...
    "identity_exact", ...
        isequaln(core.linearization_identity, ...
            partition.linearization_identity) && ...
        isequaln(core.linearization_identity, ...
            aggregation.linearization_identity), ...
    "matrix_formula_exact",isequaln(core.matrix,expectedMatrix), ...
    "rhs_formula_exact",isequaln(core.rhs,expectedRhs), ...
    "dimensions_exact", ...
        isequal(size(core.matrix),[16,16]) && ...
        isequal(size(core.rhs),[16,1]) && ...
        isequal(size(core.solution),[16,1]) && ...
        isequal(size(core.delta_q),[14,1]) && ...
        isequal(size(core.delta_rho),[2,1]), ...
    "matrix_sparse",issparse(core.matrix), ...
    "solution_slices_exact", ...
        isequaln(core.delta_q,core.solution(1:14)) && ...
        isequaln(core.delta_rho,core.solution(15:16)), ...
    "symmetry_within_threshold", ...
        norm(core.matrix-core.matrix.',"fro")/ ...
            max(1,norm(core.matrix,"fro"))<=symmetryTolerance, ...
    "residual_within_threshold", ...
        core.diagnostics.relative_residual<=1e-10, ...
    "zero_inertia_absent", ...
        core.diagnostics.factor.inertia_zero==0, ...
    "aggregation_order_exact", ...
        isequal(aggregation.day_ids_sorted,14:20) && ...
        aggregation.order_invariant_passed, ...
    "residual_refinement_disabled", ...
        maximumPasses==0 && ~refinement.enabled && ...
        refinement.maximum_passes==0 && ...
        refinement.additional_factorization_count==0 && ...
        ~refinement.direct_matrix_backslash_used);
end

function value = rhs_solution_summary(core)
rowIndex = (1:16).';
component = [repmat("delta_q",14,1); ...
    repmat("delta_rho",2,1)];
rhs = core.rhs;
solution = core.solution;
absoluteResidual = abs(core.matrix*solution-rhs);
value = table(rowIndex,component,rhs,solution,absoluteResidual);
end

function fig = core_figure(core,interactive)
fig = rkkt.validation.newFigure("16维全局核心",interactive);
tiledlayout(fig,1,2,"TileSpacing","compact", ...
    "Padding","compact");
nexttile;
imagesc(rkkt.validation.smallDense(core.matrix,16));
axis image;
colorbar;
xlabel("列");
ylabel("行");
title("16维核心矩阵");
nexttile;
bar(1:16,core.solution);
xlabel("分量");
ylabel("方向值");
title(sprintf("核心解（相对残差 %.3e）", ...
    core.diagnostics.relative_residual));
grid on;
end
