function moduleResult = runPartition(options)
%RUNPARTITION Validate the formal seven-day recursive partition.

arguments
    options.LinearizationArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("model", ...
        "统一线性化模块输出.mat")
    options.ReducedArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "既约KKT模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("solver")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
linearizationModule = rkkt.validation.loadResult( ...
    options.LinearizationArtifact,"runPartition linearization", ...
    "rkkt.model.linearize");
reducedModule = rkkt.validation.loadResult( ...
    options.ReducedArtifact,"runPartition reduced KKT", ...
    "rkkt.solver.eliminateInequalities");
rkkt.contracts.requireFields(linearizationModule.input,"config", ...
    "runPartition linearization input");
rkkt.contracts.requireFields(linearizationModule.output, ...
    "linearization","runPartition linearization output");
rkkt.contracts.requireFields(reducedModule.output,"reduced", ...
    "runPartition reduced output");
linearization = linearizationModule.output.linearization;
reduced = reducedModule.output.reduced;
config = linearizationModule.input.config;
tolerance = config.tolerances.symmetry_relative;

legacy = rkkt.solver.partition_stage_a_multiday_recursive_system( ...
    linearization,reduced,"AssemblyTolerance",tolerance);
partition = rkkt.solver.partitionRecursiveSystem( ...
    linearization,reduced,AssemblyTolerance=tolerance);
legacyFacadeExact = isequaln(legacy,partition);
facts = partition_facts(partition,reduced,legacyFacadeExact);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:PartitionFacts", ...
        "One or more objective partition observations are false.");
end

daySummary = day_summary(partition);
hourSummary = hour_summary(partition);
permutationSummary = permutation_summary(partition);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "递推分区模块输出.mat", ...
    ["七日日链维数.csv";"小时块维数.csv";"递推排列摘要.csv"], ...
    "七日日链维数",options.WriteArtifacts);
metadata = rkkt.validation.metadata( ...
    "rkkt.solver.partitionRecursiveSystem", ...
    "partition_stage_a_multiday_recursive_system", ...
    options.ReducedArtifact,outputFile,"递推分区模块", ...
    linearization.state.iteration_index, ...
    linearization.state.state_revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "linearizationArtifact",rkkt.validation.artifactReference( ...
        options.LinearizationArtifact,linearization.identity, ...
        linearizationModule.meta.interface_name), ...
    "reducedArtifact",rkkt.validation.artifactReference( ...
        options.ReducedArtifact,reduced.linearization_identity, ...
        reducedModule.meta.interface_name), ...
    "linearizationIdentity",string(linearization.identity), ...
    "assemblyTolerance",tolerance, ...
    "symmetryTolerance",config.tolerances.symmetry_relative, ...
    "residualRefinementMaxPasses",0, ...
    "iteration",linearization.state.iteration_index, ...
    "revision",linearization.state.state_revision, ...
    "expectedDays",14:20, ...
    "expectedHours",1:24);
moduleResult.output = struct("partition",partition);
moduleResult.intermediate = struct( ...
    "daySummary",daySummary, ...
    "hourSummary",hourSummary, ...
    "permutationSummary",permutationSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "linearization_identity",string(partition.linearization_identity), ...
    "daily_chain_dimensions", ...
        reshape([partition.day.hourly_chain_dimension],[],1), ...
    "assembly_audit",struct( ...
        "matrix_difference_nnz", ...
            partition.assembly_audit.matrix_difference_nnz, ...
        "rhs_relative_error", ...
            partition.assembly_audit.rhs_relative_error, ...
        "canonical_matrix_difference_nnz", ...
            partition.assembly_audit.canonical_matrix_difference_nnz, ...
        "canonical_rhs_difference_nnz", ...
            partition.assembly_audit.canonical_rhs_difference_nnz), ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "recursive_order","16维全局边框后接第14—20日日链", ...
    "permutation_dimension",partition.permutation.dimension, ...
    "day_order",partition.days, ...
    "hour_order",partition.hours);
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(daySummary,tableFiles(1));
    rkkt.validation.writeTable17(hourSummary,tableFiles(2));
    rkkt.validation.writeTable17(permutationSummary,tableFiles(3));
    fig = partition_figure(daySummary,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：递推分区模块\n");
fprintf("新旧分区结果严格相同：%d\n",legacyFacadeExact);
fprintf("七日日链维数：%s\n", ...
    mat2str(reshape([partition.day.hourly_chain_dimension],1,[])));
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function facts = partition_facts(partition,reduced,legacyFacadeExact)
expectedDayDimensions = [589;590;589;590;590;590;590];
expectedAssemblyDimensions = [16;617;618;617;618;618;618;618];
permutation = partition.permutation;
n = 4340;
identityOrder = (1:n).';
dayDimensions = reshape([partition.day.hourly_chain_dimension],[],1);
dailyStructure = true;
for d = 1:7
    day = partition.day(d);
    dailyStructure = dailyStructure && numel(day.hour)==24 && ...
        isempty(day.hour(1).E) && ...
        all(arrayfun(@(item) nnz(item.E)==2,day.hour(2:24))) && ...
        day.hour(24).n_equalities==5;
end
audit = partition.assembly_audit;
facts = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "stage_exact",string(partition.stage_id)=="stage_A4", ...
    "identity_exact",isequaln( ...
        partition.linearization_identity,reduced.linearization_identity), ...
    "days_hours_exact", ...
        isequal(partition.days,14:20) && ...
        isequal(partition.hours,1:24), ...
    "daily_dimensions_exact", ...
        isequal(dayDimensions,expectedDayDimensions) && ...
        sum(dayDimensions)==4128, ...
    "assembly_dimensions_exact", ...
        isequal(permutation.assembly_map.dimension, ...
            expectedAssemblyDimensions), ...
    "permutation_nonidentity_bijection", ...
        permutation.dimension==n && permutation.is_bijection && ...
        permutation.is_nonidentity && ...
        isequal(sort(permutation.forward_recursive_to_canonical), ...
            identityOrder), ...
    "permutation_compositions_exact", ...
        permutation.forward_inverse_composition_exact && ...
        permutation.inverse_forward_composition_exact && ...
        isequal(permutation.inverse_canonical_to_recursive( ...
            permutation.forward_recursive_to_canonical),identityOrder), ...
    "recursive_matrix_rhs_exact", ...
        audit.matrix_difference_nnz==0 && ...
        isequaln(audit.permuted_rhs,audit.expected_rhs), ...
    "canonical_matrix_rhs_exact", ...
        audit.canonical_matrix_difference_nnz==0 && ...
        audit.canonical_rhs_difference_nnz==0 && ...
        isequaln(audit.reconstructed_canonical_matrix,reduced.saddle) && ...
        isequaln(audit.reconstructed_canonical_rhs,reduced.rhs), ...
    "no_cross_day_soc", ...
        audit.cross_day_hourly_equality_nnz==0 && ...
        audit.no_cross_day_soc_coupling, ...
    "daily_hour_structure_exact",dailyStructure);
end

function value = day_summary(partition)
dayId = reshape([partition.day.day_id],[],1);
hourCount = reshape(arrayfun( ...
    @(item)numel(item.hour),partition.day),[],1);
hourlyChainDimension = ...
    reshape([partition.day.hourly_chain_dimension],[],1);
assembly = partition.permutation.assembly_map(2:end,:);
recursiveStartIndex = assembly.recursive_start_index;
recursiveEndIndex = assembly.recursive_end_index;
recursiveBlockDimension = assembly.dimension;
value = table(dayId,hourCount,hourlyChainDimension, ...
    recursiveStartIndex,recursiveEndIndex,recursiveBlockDimension);
end

function value = hour_summary(partition)
n = 7*24;
dayId = zeros(n,1);
hour = zeros(n,1);
dimension = zeros(n,1);
nPrimal = zeros(n,1);
nEqualities = zeros(n,1);
nnzD = zeros(n,1);
nnzE = zeros(n,1);
nnzB = zeros(n,1);
row = 0;
for d = 1:7
    for t = 1:24
        row = row+1;
        block = partition.day(d).hour(t);
        dayId(row) = block.day_id;
        hour(row) = block.hour;
        dimension(row) = block.dimension;
        nPrimal(row) = block.n_primal;
        nEqualities(row) = block.n_equalities;
        nnzD(row) = nnz(block.D);
        nnzE(row) = nnz(block.E);
        nnzB(row) = nnz(block.B);
    end
end
value = table(dayId,hour,dimension,nPrimal,nEqualities, ...
    nnzD,nnzE,nnzB);
end

function value = permutation_summary(partition)
permutationDimension = partition.permutation.dimension;
isBijection = partition.permutation.is_bijection;
isNonidentity = partition.permutation.is_nonidentity;
forwardInverseExact = ...
    partition.permutation.forward_inverse_composition_exact;
inverseForwardExact = ...
    partition.permutation.inverse_forward_composition_exact;
matrixDifferenceNnz = ...
    partition.assembly_audit.matrix_difference_nnz;
rhsRelativeError = partition.assembly_audit.rhs_relative_error;
canonicalMatrixDifferenceNnz = ...
    partition.assembly_audit.canonical_matrix_difference_nnz;
canonicalRhsDifferenceNnz = ...
    partition.assembly_audit.canonical_rhs_difference_nnz;
crossDaySocNnz = ...
    partition.assembly_audit.cross_day_hourly_equality_nnz;
value = table(permutationDimension,isBijection,isNonidentity, ...
    forwardInverseExact,inverseForwardExact,matrixDifferenceNnz, ...
    rhsRelativeError,canonicalMatrixDifferenceNnz, ...
    canonicalRhsDifferenceNnz,crossDaySocNnz);
end

function fig = partition_figure(summary,interactive)
fig = rkkt.validation.newFigure( ...
    "七日日链维数",interactive);
bar(summary.dayId,summary.hourlyChainDimension);
xlabel("日期");
ylabel("小时链维数");
title("第14—20日日链自然维数");
grid on;
end
