function moduleResult = runRecovery(options)
%RUNRECOVERY Validate strict reverse-order canonical direction recovery.

arguments
    options.LinearizationArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("model", ...
        "统一线性化模块输出.mat")
    options.PartitionArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "递推分区模块输出.mat")
    options.DayResponseArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "日响应模块输出.mat")
    options.CoreArtifact (1,1) string = ...
        rkkt.validation.packageArtifact("solver", ...
        "16维全局核心模块输出.mat")
    options.Interactive (1,1) logical = true
    options.WriteArtifacts (1,1) logical = true
    options.OutputDirectory (1,1) string = ...
        rkkt.validation.outputDirectory("solver")
end

rkkt.validation.requireOutputDirectory( ...
    options.OutputDirectory,options.WriteArtifacts);
linearizationModule = rkkt.validation.loadResult( ...
    options.LinearizationArtifact,"runRecovery linearization", ...
    "rkkt.model.linearize");
partitionModule = rkkt.validation.loadResult( ...
    options.PartitionArtifact,"runRecovery partition", ...
    "rkkt.solver.partitionRecursiveSystem");
responseModule = rkkt.validation.loadResult( ...
    options.DayResponseArtifact,"runRecovery day response", ...
    "rkkt.solver.buildDayResponse");
coreModule = rkkt.validation.loadResult( ...
    options.CoreArtifact,"runRecovery global core", ...
    "rkkt.solver.solveGlobalCore");
rkkt.contracts.requireFields(linearizationModule.output, ...
    "linearization","runRecovery linearization output");
rkkt.contracts.requireFields(partitionModule.output,"partition", ...
    "runRecovery partition output");
rkkt.contracts.requireFields(responseModule.output, ...
    "dailyResponses","runRecovery day-response output");
rkkt.contracts.requireFields(coreModule.output,"core", ...
    "runRecovery core output");
rkkt.contracts.requireFields(partitionModule.input, ...
    ["iteration";"revision"],"runRecovery partition input");
linearization = linearizationModule.output.linearization;
partition = partitionModule.output.partition;
dailyResponses = responseModule.output.dailyResponses;
core = coreModule.output.core;

legacy = rkkt.solver.recover_stage_a_multiday_recursive_direction( ...
    linearization,partition,dailyResponses,core);
recovery = rkkt.solver.recoverDirection( ...
    linearization,partition,dailyResponses,core);
legacyFacadeExact = isequaln(legacy,recovery);
[facts,metrics] = recovery_facts( ...
    linearization,partition,dailyResponses,core,recovery, ...
    legacyFacadeExact);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:RecoveryFacts", ...
        "One or more objective recovery observations are false.");
end

directionSummary = direction_summary(recovery);
fixedSummary = fixed_summary(recovery);
[outputFile,tableFiles,figureFiles,figureIndex] = ...
    rkkt.validation.outputPaths(options.OutputDirectory, ...
    "局部回代模块输出.mat", ...
    ["回代方向分量摘要.csv";"固定零恢复摘要.csv"], ...
    "回代方向摘要",options.WriteArtifacts);
metadata = rkkt.validation.metadata("rkkt.solver.recoverDirection", ...
    "recover_stage_a_multiday_recursive_direction", ...
    options.CoreArtifact,outputFile,"局部回代模块", ...
    partitionModule.input.iteration,partitionModule.input.revision, ...
    options.Interactive,options.WriteArtifacts);
moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "linearizationArtifact",rkkt.validation.artifactReference( ...
        options.LinearizationArtifact,linearization.identity, ...
        linearizationModule.meta.interface_name), ...
    "partitionArtifact",rkkt.validation.artifactReference( ...
        options.PartitionArtifact,partition.linearization_identity, ...
        partitionModule.meta.interface_name), ...
    "dayResponseArtifact",rkkt.validation.artifactReference( ...
        options.DayResponseArtifact,partition.linearization_identity, ...
        responseModule.meta.interface_name), ...
    "coreArtifact",rkkt.validation.artifactReference( ...
        options.CoreArtifact,core.linearization_identity, ...
        coreModule.meta.interface_name), ...
    "linearizationIdentity",string(linearization.identity), ...
    "formulaResidualThreshold",1e-10, ...
    "iteration",partitionModule.input.iteration, ...
    "revision",partitionModule.input.revision);
moduleResult.output = struct("recovery",recovery);
moduleResult.intermediate = struct( ...
    "directionSummary",directionSummary, ...
    "fixedSummary",fixedSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "linearization_identity",string(recovery.linearization_identity), ...
    "direction_dimension",numel(recovery.direction), ...
    "delta_l_formula_relative",metrics.deltaLFormulaRelative, ...
    "delta_z_formula_relative",metrics.deltaZFormulaRelative, ...
    "fixed_zero_count",recovery.fixed_zero.count, ...
    "fixed_zero_all_exact",recovery.fixed_zero.all_exact_zero, ...
    "objective_facts",facts, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "direction_order","[xi;y;l;z]", ...
    "reverse_day_order",recovery.diagnostics.reverse_day_order, ...
    "reverse_hour_order",recovery.diagnostics.reverse_hour_order, ...
    "recovery_contract", ...
        "全局容量→日容量/绑定乘子→日期20至14→小时24至1→l/z");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    rkkt.validation.writeTable17(directionSummary,tableFiles(1));
    rkkt.validation.writeTable17(fixedSummary,tableFiles(2));
    fig = recovery_figure(directionSummary,options.Interactive);
    rkkt.validation.saveFigurePair( ...
        fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    rkkt.validation.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：局部回代模块\n");
fprintf("新旧回代结果严格相同：%d\n",legacyFacadeExact);
fprintf("方向维数/fixed_zero：%d/%d\n", ...
    numel(recovery.direction),recovery.fixed_zero.count);
fprintf("delta_l/delta_z公式相对残差：%.17g/%.17g\n", ...
    metrics.deltaLFormulaRelative,metrics.deltaZFormulaRelative);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function [facts,metrics] = recovery_facts( ...
        linearization,partition,responses,core,recovery, ...
        legacyFacadeExact)
components = recovery.components;
gDelta = sparse(linearization.G)*components.xi;
deltaLFormulaResidual = ...
    components.l+linearization.r_ineq+gDelta;
deltaZFormulaResidual = ...
    linearization.l.*components.z+linearization.r_comp- ...
    linearization.z.*linearization.r_ineq- ...
    linearization.z.*gDelta;
metrics = struct( ...
    "deltaLFormulaRelative", ...
        norm(deltaLFormulaResidual,2)/max([ ...
            1,norm(components.l,2),norm(linearization.r_ineq,2), ...
            norm(gDelta,2)]), ...
    "deltaZFormulaRelative", ...
        norm(deltaZFormulaResidual,2)/max([ ...
            1,norm(linearization.l.*components.z,2), ...
            norm(linearization.r_comp,2), ...
            norm(linearization.z.*linearization.r_ineq,2), ...
            norm(linearization.z.*gDelta,2)]));
responseIdentities = arrayfun(@(item)isequaln( ...
    item.linearization_identity,linearization.identity),responses);
hourValuesPresent = all(cellfun( ...
    @(value)~isempty(value),components.v_by_day_hour),"all");
facts = struct( ...
    "legacy_facade_exact_equal",legacyFacadeExact, ...
    "stage_exact",string(recovery.stage_id)=="stage_A4", ...
    "identity_exact", ...
        isequaln(recovery.linearization_identity, ...
            linearization.identity) && ...
        isequaln(partition.linearization_identity, ...
            linearization.identity) && ...
        isequaln(core.linearization_identity, ...
            linearization.identity) && ...
        all(responseIdentities), ...
    "direction_dimension_exact", ...
        numel(recovery.direction)==18836 && ...
        numel(components.xi)==3722 && ...
        numel(components.y)==618 && ...
        numel(components.l)==7248 && ...
        numel(components.z)==7248, ...
    "canonical_concatenation_exact", ...
        isequaln(recovery.direction, ...
            [components.xi;components.y;components.l;components.z]), ...
    "capacity_dimensions_exact", ...
        isequal(size(components.q),[14,1]) && ...
        isequal(size(components.rho),[2,1]) && ...
        isequal(size(components.q_day_matrix),[14,7]) && ...
        isequal(size(components.pi_matrix),[14,7]), ...
    "day_hour_recovery_complete", ...
        isequal(size(components.v_by_day_hour),[7,24]) && ...
        hourValuesPresent, ...
    "strict_reverse_order_exact", ...
        recovery.diagnostics.strict_reverse_recovery && ...
        isequal(recovery.diagnostics.reverse_day_order,20:-1:14) && ...
        isequal(recovery.diagnostics.reverse_hour_order,24:-1:1), ...
    "delta_l_formula_within_threshold", ...
        metrics.deltaLFormulaRelative<=1e-10 && ...
        recovery.diagnostics.delta_l_formula_residual== ...
            norm(deltaLFormulaResidual,2), ...
    "delta_z_formula_within_threshold", ...
        metrics.deltaZFormulaRelative<=1e-10 && ...
        recovery.diagnostics.delta_z_formula_residual== ...
            norm(deltaZFormulaResidual,2), ...
    "all_components_finite", ...
        all(isfinite(recovery.direction)), ...
    "fixed_zero_exact", ...
        recovery.fixed_zero.count==422 && ...
        recovery.fixed_zero.all_exact_zero && ...
        numel(recovery.fixed_zero.value)==422 && ...
        numel(recovery.fixed_zero.direction)==422 && ...
        all(recovery.fixed_zero.value==0) && ...
        all(recovery.fixed_zero.direction==0));
end

function value = direction_summary(recovery)
names = ["xi";"y";"l";"z";"q";"rho"];
vectors = {recovery.components.xi;recovery.components.y; ...
    recovery.components.l;recovery.components.z; ...
    recovery.components.q;recovery.components.rho};
dimension = reshape(cellfun(@numel,vectors),[],1);
norm2 = reshape(cellfun(@(item)norm(item,2),vectors),[],1);
maximumAbsolute = reshape( ...
    cellfun(@(item)max(abs(item)),vectors),[],1);
allFinite = reshape( ...
    cellfun(@(item)all(isfinite(item)),vectors),[],1);
value = table(names,dimension,norm2,maximumAbsolute,allFinite, ...
    'VariableNames', ...
    {'component','dimension','norm2','maximumAbsolute','allFinite'});
end

function value = fixed_summary(recovery)
count = recovery.fixed_zero.count;
valueExactZero = all(recovery.fixed_zero.value==0);
directionExactZero = all(recovery.fixed_zero.direction==0);
maximumAbsoluteValue = max([0;abs(recovery.fixed_zero.value(:))]);
maximumAbsoluteDirection = ...
    max([0;abs(recovery.fixed_zero.direction(:))]);
allExactZero = recovery.fixed_zero.all_exact_zero;
value = table(count,valueExactZero,directionExactZero, ...
    maximumAbsoluteValue,maximumAbsoluteDirection,allExactZero);
end

function fig = recovery_figure(summary,interactive)
fig = rkkt.validation.newFigure( ...
    "回代方向摘要",interactive);
bar(categorical(summary.component), ...
    max(summary.norm2,realmin));
set(gca,"YScale","log");
ylabel("二范数（对数轴）");
title("严格逆序回代方向分量");
grid on;
end
