function moduleResult = runStageB2B(options)
%RUNSTAGEB2B Validate one Stage B-2B recursive/audit direction pair.
%   The entry builds one explicit Stage B-2B data-to-linearization chain,
%   computes exactly one recursive direction and one independent full-KKT
%   audit direction, and compares them through the public Stage B facade.
%   It never runs an IPM, updates a state, optimizes, or enables parallelism.

arguments
    options.ProjectRoot (1,1) string = default_project_root()
    options.Interactive (1,1) logical = false
    options.WriteArtifacts (1,1) logical = false
    options.OutputDirectory (1,1) string = ...
        rkkt.solver.validation.ValidationSupport.outputDirectory()
end

projectRoot = strip(options.ProjectRoot);
outputDirectory = strip(options.OutputDirectory);
if ~isfolder(projectRoot)
    error("rkkt:solver:validation:StageB2BProjectRoot", ...
        "ProjectRoot does not exist: %s",projectRoot);
end

support = rkkt.solver.validation.ValidationSupport;
support.requireOutputDirectory(outputDirectory,options.WriteArtifacts);
config = load_stage_b2b_config(projectRoot);
configPath = fullfile(projectRoot,"config","stage_B_2B.yaml");

data = rkkt.data.load(projectRoot);
index = rkkt.indexing.buildStageB2B( ...
    data,config,RunId="PKG9_STAGE_B2B_VALIDATION");
state = rkkt.model.initializeStageB2B(data,index,config);
linearization = rkkt.model.linearizeStageB2B( ...
    state,data,index,config);

recursiveResult = rkkt.solver.solveStageB2BRecursiveDirection( ...
    linearization, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    ResidualRefinementMaxPasses= ...
        config.recursive_refinement_max_passes, ...
    UseCongruenceScaling=false);
fullAuditResult = rkkt.solver.solveStageB2BFullKKTDirection( ...
    linearization);
equivalenceAudit = ...
    rkkt.solver.verifyStageB2BDirectionEquivalence( ...
        fullAuditResult,recursiveResult,linearization, ...
        DirectionRelative= ...
            config.direction_relative_error_tolerance, ...
        RecursiveResidual= ...
            config.recursive_full_kkt_residual_tolerance, ...
        FullResidual=config.full_kkt_residual_tolerance);

dailySummary = build_daily_summary(recursiveResult);
metricSummary = build_metric_summary( ...
    recursiveResult,fullAuditResult,equivalenceAudit,config);
facts = validate_results(index,linearization,recursiveResult, ...
    fullAuditResult,equivalenceAudit,dailySummary,config);
if ~all(structfun(@(value) logical(value),facts))
    error("rkkt:solver:validation:StageB2BFacts", ...
        "One or more Stage B-2B validation facts are false.");
end

[outputFile,tableFiles,figureFiles,figureIndex] = ...
    support.outputPaths(outputDirectory, ...
        "Stage_B2B求解器验证输出.mat", ...
        ["Stage_B2B每日边框与响应维数.csv"; ...
         "Stage_B2B方向误差与KKT残差.csv"], ...
        "Stage_B2B_16维核心稀疏结构",options.WriteArtifacts);

metadata = support.metadata( ...
    "rkkt.solver.solveStageB2BRecursiveDirection", ...
    "solve_stage_b2b_recursive_direction",configPath,outputFile, ...
    "Stage B-2B求解器验证",state.iteration_index, ...
    state.state_revision,options.Interactive,options.WriteArtifacts);
metadata.stage_id = "stage_B";
metadata.milestone_id = "B-2B";
metadata.full_audit_interface = ...
    "rkkt.solver.solveStageB2BFullKKTDirection";
metadata.full_audit_production_function = ...
    "solve_stage_b2b_full_kkt_direction";
metadata.equivalence_interface = ...
    "rkkt.solver.verifyStageB2BDirectionEquivalence";
metadata.equivalence_production_function = ...
    "verify_stage_b2b_direction_equivalence";

moduleResult = rkkt.contracts.moduleResultTemplate(metadata);
moduleResult.input = struct( ...
    "project_root",projectRoot, ...
    "configuration_artifact",configPath, ...
    "configuration_milestone",string(config.milestone_id), ...
    "index_version",string(index.version), ...
    "linearization_identity",string(linearization.identity));
% Store each large object once. In particular, the complete sparse KKT is
% present only inside fullAuditResult.kkt and is not copied elsewhere.
moduleResult.output = struct( ...
    "recursiveResult",recursiveResult, ...
    "fullAuditResult",fullAuditResult, ...
    "equivalenceAudit",equivalenceAudit);
moduleResult.intermediate = struct( ...
    "dailySummary",dailySummary, ...
    "metricSummary",metricSummary, ...
    "figureIndex",figureIndex);
moduleResult.diagnostics = struct( ...
    "objective_facts",facts, ...
    "linearization_identity",string(linearization.identity), ...
    "direction_relative_error", ...
        equivalenceAudit.direction_relative_error, ...
    "recursive_kkt_relative_residual", ...
        equivalenceAudit.recursive_kkt_relative_residual, ...
    "full_kkt_relative_residual", ...
        equivalenceAudit.full_kkt_relative_residual, ...
    "fixed_zero_count",recursiveResult.fixed_zero.count, ...
    "fixed_zero_exact",recursiveResult.fixed_zero.all_exact_zero, ...
    "no_full_direction_fallback", ...
        recursiveResult.no_full_direction_fallback, ...
    "full_direction_consumed", ...
        recursiveResult.full_direction_consumed, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "state_update_executed",false, ...
    "parallel_executed",false, ...
    "artifacts_written",options.WriteArtifacts);
moduleResult.indexDescription = struct( ...
    "day_order","第14日至第20日", ...
    "hourly_chain_dimensions", ...
        reshape(dailySummary.hourly_chain_dimension,1,[]), ...
    "water_border_dimension_per_day",8, ...
    "daily_response_dimension",14, ...
    "global_core_dimension",16, ...
    "full_kkt_role","独立审计，不向递推方向提供输入或回退");
moduleResult.tableFiles = tableFiles;
moduleResult.figureFiles = figureFiles;
rkkt.contracts.validateModuleResult(moduleResult);

if options.WriteArtifacts
    support.writeTable17(dailySummary,tableFiles(1));
    support.writeTable17(metricSummary,tableFiles(2));
    fig = core_sparsity_figure( ...
        recursiveResult.core.matrix,options.Interactive);
    support.saveFigurePair(fig,figureIndex.figPath,figureIndex.pngPath);
    if ~options.Interactive
        close(fig);
    end
    support.saveResult(outputFile,moduleResult);
end

fprintf("当前模块：Stage B-2B求解器验证\n");
fprintf("递推/完整方向各执行一次：1/1\n");
fprintf("方向相对误差：%.17g\n", ...
    equivalenceAudit.direction_relative_error);
fprintf("递推/完整KKT相对残差：%.17g / %.17g\n", ...
    equivalenceAudit.recursive_kkt_relative_residual, ...
    equivalenceAudit.full_kkt_relative_residual);
fprintf("fixed_zero精确零：%d项，状态=%d\n", ...
    recursiveResult.fixed_zero.count, ...
    recursiveResult.fixed_zero.all_exact_zero);
if options.WriteArtifacts
    fprintf("固定人工验证输出：%s\n",outputFile);
end
end

function config = load_stage_b2b_config(projectRoot)
modelDirectory = fullfile(projectRoot,"src","model");
productionFile = fullfile(modelDirectory, ...
    "load_stage_b2b_configuration.m");
if ~isfile(productionFile)
    error("rkkt:solver:validation:StageB2BConfigMissing", ...
        "Production configuration loader is missing: %s", ...
        productionFile);
end
originalPath = path;
pathGuard = onCleanup(@() path(originalPath));
addpath(modelDirectory,"-begin");
resolved = string(which("load_stage_b2b_configuration"));
if ~same_path(resolved,productionFile)
    error("rkkt:solver:validation:StageB2BConfigShadowed", ...
        "Expected load_stage_b2b_configuration at '%s'; resolved '%s'.", ...
        productionFile,resolved);
end
config = load_stage_b2b_configuration(projectRoot);
clear pathGuard
end

function value = build_daily_summary(recursiveResult)
days = recursiveResult.partition.day;
responses = recursiveResult.daily_responses;
nDays = numel(days);
day = zeros(nDays,1);
hourly_chain_dimension = zeros(nDays,1);
water_border_dimension = zeros(nDays,1);
augmented_chain_dimension = zeros(nDays,1);
daily_response_dimension = zeros(nDays,1);
global_core_dimension = repmat( ...
    size(recursiveResult.core.matrix,1),nDays,1);
for k = 1:nDays
    day(k) = days(k).day_id;
    hourly_chain_dimension(k) = hourly_dimension(days(k));
    water_border_dimension(k) = border_dimension(days(k).water);
    augmented_chain_dimension(k) = ...
        augmented_dimension(days(k),water_border_dimension(k));
    daily_response_dimension(k) = size(responses(k).S,1);
end
expectedChain = [589;590;589;590;590;590;590];
status = repmat("PASS",nDays,1);
status(day~=(14:20).' | ...
    hourly_chain_dimension~=expectedChain | ...
    water_border_dimension~=8 | ...
    daily_response_dimension~=14 | ...
    global_core_dimension~=16) = "FAIL";
value = table(day,hourly_chain_dimension,water_border_dimension, ...
    augmented_chain_dimension,daily_response_dimension, ...
    global_core_dimension,status);
end

function value = build_metric_summary( ...
        recursiveResult,fullAuditResult,audit,config)
component = audit.component_relative_errors;
metric_name = [ ...
    "direction_relative_error"
    "xi_direction_relative_error"
    "y_direction_relative_error"
    "l_direction_relative_error"
    "z_direction_relative_error"
    "recursive_kkt_relative_residual"
    "full_kkt_relative_residual"
    "full_solver_relative_residual"
    "fixed_zero_count"
    "fixed_zero_exact"
    "no_full_direction_fallback"
    "full_direction_consumed"];
actual_value = [ ...
    audit.direction_relative_error
    component.xi
    component.y
    component.l
    component.z
    audit.recursive_kkt_relative_residual
    audit.full_kkt_relative_residual
    fullAuditResult.diagnostics.relative_residual
    recursiveResult.fixed_zero.count
    double(recursiveResult.fixed_zero.all_exact_zero)
    double(recursiveResult.no_full_direction_fallback)
    double(recursiveResult.full_direction_consumed)];
threshold = [ ...
    repmat(config.direction_relative_error_tolerance,5,1)
    config.recursive_full_kkt_residual_tolerance
    config.full_kkt_residual_tolerance
    config.full_kkt_residual_tolerance
    422
    1
    1
    0];
comparison = [repmat("<=",8,1);"==";"==";"==";"=="];
passed = [ ...
    actual_value(1:5)<=threshold(1:5)
    actual_value(6)<=threshold(6)
    actual_value(7)<=threshold(7)
    actual_value(8)<=threshold(8)
    actual_value(9)==threshold(9)
    actual_value(10)==threshold(10)
    actual_value(11)==threshold(11)
    actual_value(12)==threshold(12)];
value = table(metric_name,actual_value,threshold,comparison,passed);
end

function facts = validate_results(index,linearization,recursiveResult, ...
        fullAuditResult,audit,dailySummary,config)
identity = string(linearization.identity);
facts = struct( ...
    "stage_b2b_exact",string(config.stage_id)=="stage_B" && ...
        string(config.milestone_id)=="B-2B", ...
    "controlled_dimensions_exact", ...
        index.counts.variables==3722 && ...
        index.counts.equalities==618 && ...
        index.counts.inequalities==7304 && ...
        index.counts.full_kkt_dimension==18948, ...
    "shared_linearization_identity", ...
        string(recursiveResult.linearization_identity)==identity && ...
        string(fullAuditResult.linearization_identity)==identity && ...
        string(audit.linearization_identity)==identity, ...
    "daily_contract_exact",all(dailySummary.status=="PASS"), ...
    "direction_audit_passed",logical(audit.all_pass), ...
    "fixed_zero_exact",recursiveResult.fixed_zero.count==422 && ...
        recursiveResult.fixed_zero.all_exact_zero, ...
    "no_full_direction_fallback", ...
        recursiveResult.no_full_direction_fallback, ...
    "full_direction_not_consumed", ...
        ~recursiveResult.full_direction_consumed, ...
    "full_direction_is_audit_only",fullAuditResult.audit_only && ...
        ~fullAuditResult.recursive_direction_consumed && ...
        ~fullAuditResult.execution.fallback_used, ...
    "forbidden_execution_absent", ...
        ~recursiveResult.full_ipm_executed && ...
        ~recursiveResult.optimization_executed && ...
        ~recursiveResult.parallel_executed && ...
        ~fullAuditResult.full_ipm_executed && ...
        ~fullAuditResult.optimization_executed && ...
        ~fullAuditResult.parallel_executed && ...
        ~config.ipm_enabled && ~config.optimization_enabled && ...
        ~config.state_update_enabled && ~config.parallel_enabled);
end

function value = hourly_dimension(day)
if isfield(day,"hourly_chain_dimension")
    value = day.hourly_chain_dimension;
else
    value = size(day.M,1);
end
end

function value = border_dimension(water)
value = scalar_field(water,["border_dimension","dimension","row_count"]);
end

function value = augmented_dimension(day,borderDimension)
if isfield(day,"augmented_dimension")
    value = day.augmented_dimension;
elseif isfield(day,"water") && ...
        isfield(day.water,"augmented_dimension")
    value = day.water.augmented_dimension;
else
    value = hourly_dimension(day)+borderDimension;
end
end

function value = scalar_field(object,names)
value = [];
for name = names
    if isfield(object,name)
        value = object.(name);
        break
    end
end
if isempty(value) || ~isnumeric(value) || ~isscalar(value) || ...
        ~isfinite(value)
    error("rkkt:solver:validation:StageB2BDimension", ...
        "A required finite scalar dimension is missing.");
end
end

function fig = core_sparsity_figure(coreMatrix,interactive)
fig = rkkt.solver.validation.ValidationSupport.newFigure( ...
    "Stage B-2B 16维全局核心稀疏结构",interactive);
spy(coreMatrix);
xlabel("列索引");
ylabel("行索引");
title("Stage B-2B 16维全局核心稀疏结构");
end

function value = default_project_root()
value = rkkt.solver.validation.ValidationSupport.repositoryRoot();
end

function value = same_path(left,right)
left = replace(string(left),"/","\");
right = replace(string(right),"/","\");
if ispc
    value = strcmpi(left,right);
else
    value = strcmp(left,right);
end
end
