function project = completePackageClosureA4(numerical)
%COMPLETEPACKAGECLOSUREA4 Finish tests, reports, manifest and run index.

arguments
    numerical (1,1) struct
end

root = rkkt.projectRoot();
context = run_context(root,string(numerical.run_id));
manifest = jsondecode(fileread(context.run_manifest_path));
assert(string(manifest.status)=="RUNNING" && ...
    string(manifest.stage_id)=="stage_A4" && ...
    string(manifest.execution_profile)=="package_closure", ...
    "rkkt:closure:ManifestIdentity", ...
    "Package closure requires its matching RUNNING A4 manifest.");

testCommand = "RUN_PROJECT.m -> run_package_closure_tests("+ ...
    "EvidenceDirectory='"+string(context.tests_dir)+"')";
tests = run_package_closure_tests( ...
    "EvidenceDirectory",string(context.tests_dir), ...
    "CommandText",testCommand);
static = persist_static_evidence(root,context);

[reportPaths,structure] = rkkt.reporting.generate( ...
    context,"ReportGateMode","preflight", ...
    "FinalStatusCandidate","PASS");
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.reports_dir,"report_structure_validation.csv"), ...
    structure);
reportHashes = report_hashes(context,reportPaths);
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.reports_dir,"report_sha256.csv"),reportHashes);
render = rkkt.reporting.render_stage_a4_reports_with_word( ...
    reportPaths,fullfile(context.reports_dir,"rendered_pdf"));
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.reports_dir,"report_render_qa.csv"),render);

acceptance = readtable(context.acceptance_results_path, ...
    "TextType","string","VariableNamingRule","preserve", ...
    "Delimiter",",");
reportRow = acceptance.test_id=="SA4-RPT-001";
assert(nnz(reportRow)==1,"rkkt:closure:ReportAcceptance", ...
    "SA4-RPT-001 must occur exactly once.");
reportPassed = all(string(structure.status)=="PASS") && ...
    all(render.status=="PASS") && all(reportHashes.status=="PASS");
if reportPassed
    acceptance.status(reportRow) = "PASS";
else
    acceptance.status(reportRow) = "FAIL";
end
acceptance.actual_value(reportRow) = ...
    "three DOCX structure checks and Word PDF renders passed="+ ...
    string(reportPassed);
rkkt.artifacts.write_table_csv_17g_atomic( ...
    context.acceptance_results_path,acceptance);

numericPassed = numerical.run_terminal_state=="CONVERGED" && ...
    numerical.convergence_achieved && ...
    all(acceptance.status(~reportRow)=="PASS");
allPassed = numericPassed && tests.all_pass && static.all_pass && ...
    reportPassed && all(acceptance.status=="PASS");
if allPassed
    finalStatus = "PASS";
else
    finalStatus = "FAIL_RETRYABLE";
end

solver = load(fullfile(context.root,"a4_3_solver_result.mat"),"summary");
updates = struct( ...
    "iteration_count",double(solver.summary.iteration_count), ...
    "elapsed_seconds",double(solver.summary.timing.solver_seconds), ...
    "tests_executed",true, ...
    "package_closure_test_total",double(tests.summary.test_total), ...
    "package_closure_test_passed",double(tests.summary.test_passed), ...
    "package_closure_static_pass",logical(static.all_pass), ...
    "reports_generated",true, ...
    "report_structure_pass",all(string(structure.status)=="PASS"), ...
    "report_word_render_pass",all(render.status=="PASS"), ...
    "postprocess_phase","COMPLETE", ...
    "postprocessing_executed",true, ...
    "postprocess_completed_at",char(rkkt.artifacts.current_utc_iso8601()), ...
    "finalization_pending",false, ...
    "package_closure_complete",logical(allPassed), ...
    "current_project_stage_unchanged","stage_B / READY");
finalManifest = rkkt.artifacts.finalize_run_manifest( ...
    context,finalStatus,updates);
rkkt.artifacts.update_run_index(context,finalManifest);

project = struct( ...
    "root",root, ...
    "run_id",string(context.run_id), ...
    "run_path",string(context.root), ...
    "status",string(finalManifest.status), ...
    "solution",numerical, ...
    "acceptance",acceptance, ...
    "tests",tests.summary, ...
    "static",static.summary, ...
    "reports",reportPaths, ...
    "report_render",render, ...
    "manifest",finalManifest);
end

function context = run_context(root,runId)
runRoot = fullfile(root,"runs",runId);
assert(isfolder(runRoot),"rkkt:closure:RunMissing", ...
    "The numerical run directory is missing: %s",runRoot);
context = struct( ...
    "project_root",char(root), ...
    "runs_root",char(fullfile(root,"runs")), ...
    "root",char(runRoot), ...
    "run_dir",char(runRoot), ...
    "run_id",char(runId), ...
    "stage_id","stage_A4", ...
    "iterations_dir",char(fullfile(runRoot,"iterations")), ...
    "indices_dir",char(fullfile(runRoot,"indices")), ...
    "matrices_dir",char(fullfile(runRoot,"matrices")), ...
    "checkpoints_dir",char(fullfile(runRoot,"checkpoints")), ...
    "tests_dir",char(fullfile(runRoot,"tests")), ...
    "issues_dir",char(fullfile(runRoot,"issues")), ...
    "acceptance_dir",char(fullfile(runRoot,"acceptance")), ...
    "reports_dir",char(fullfile(runRoot,"reports")), ...
    "run_manifest_path",char(fullfile(runRoot,"run_manifest.json")), ...
    "effective_config_path",char(fullfile(runRoot,"effective_config.yaml")), ...
    "acceptance_results_path",char(fullfile(runRoot,"acceptance", ...
        "acceptance_results.csv")));
end

function evidence = persist_static_evidence(root,context)
scope = [ ...
    "RUN_PROJECT.m"
    "src/+rkkt/run.m"
    "src/+rkkt/+diagnostics/assert_package_closure_a4_preflight.m"
    "src/+rkkt/+artifacts/update_run_index.m"
    "src/+rkkt/+workflows/completePackageClosureA4.m"
    "src/+rkkt/+reporting/render_stage_a4_reports_with_word.m"];
file = strings(0,1);
line = zeros(0,1);
column = zeros(0,1);
identifier = strings(0,1);
message = strings(0,1);
for k = 1:numel(scope)
    absolute = fullfile(root,replace(scope(k),"/",filesep));
    findings = checkcode(absolute,"-id");
    for j = 1:numel(findings)
        file(end+1,1) = scope(k); %#ok<AGROW>
        line(end+1,1) = double(findings(j).line); %#ok<AGROW>
        if isempty(findings(j).column)
            column(end+1,1) = NaN; %#ok<AGROW>
        else
            column(end+1,1) = double(findings(j).column(1)); %#ok<AGROW>
        end
        identifier(end+1,1) = string(findings(j).id); %#ok<AGROW>
        message(end+1,1) = string(findings(j).message); %#ok<AGROW>
    end
end
analyzer = table(file,line,column,identifier,message);
scopeTable = table(scope,'VariableNames',{'relative_path'});
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.tests_dir,"code_analyzer_scope.csv"),scopeTable);
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.tests_dir,"code_analyzer_results.csv"),analyzer);

safe = replace(root,"\","/");
quotedSafe = '"'+replace(safe,'"','\"')+'"';
quotedRoot = '"'+replace(root,'"','\"')+'"';
command = "git -c safe.directory="+quotedSafe+" -C "+quotedRoot+ ...
    " diff --check";
[gitExit,gitText] = system(char(command));
rkkt.artifacts.write_text_utf8( ...
    fullfile(context.tests_dir,"git_diff_check.txt"), ...
    "exit_code="+string(gitExit)+newline+string(gitText));

check_id = ["PACKAGE-CLOSURE-CODE-ANALYZER"; ...
    "PACKAGE-CLOSURE-GIT-DIFF-CHECK"];
passed = [isempty(analyzer);gitExit==0];
status = repmat("FAIL",2,1); status(passed) = "PASS";
actual_value = ["finding_count="+string(height(analyzer)); ...
    "exit_code="+string(gitExit)];
threshold = ["0 findings";"exit_code=0"];
evidence_path = ["tests/code_analyzer_results.csv"; ...
    "tests/git_diff_check.txt"];
summary = table(check_id,status,actual_value,threshold,evidence_path);
rkkt.artifacts.write_table_csv_17g( ...
    fullfile(context.tests_dir,"static_check_summary.csv"),summary);
evidence = struct("scope",scopeTable,"analyzer",analyzer, ...
    "summary",summary,"all_pass",all(passed));
end

function value = report_hashes(context,paths)
keys = string(fieldnames(paths));
relative_path = strings(numel(keys),1);
sha256 = strings(numel(keys),1);
status = repmat("PASS",numel(keys),1);
for k = 1:numel(keys)
    pathValue = string(paths.(keys(k)));
    relative_path(k) = replace(extractAfter(pathValue, ...
        string(context.root)+filesep),"\","/");
    sha256(k) = rkkt.data.compute_sha256_file(pathValue);
end
value = table(relative_path,sha256,status);
end
