function result = stageB2C(options)
%STAGEB2C Run the formal seven-day daily-joint recursive Stage B IPM.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
end
root=options.ProjectRoot;
if strlength(strip(root))==0
    root=rkkt.projectRoot();
end
root=string(java.io.File(char(root)).getCanonicalPath());
addpath(fullfile(root,"tests"));
config=rkkt.model.load_stage_b2c_configuration(root);
[inputHashes,inputPass]=rkkt.data.verify_input_hashes(root);
assert(inputPass,"stageB2C:InputHashMismatch", ...
    "Controlled input SHA256 verification failed.");
commit=git_commit(root); shortCommit=extractBefore(commit,9);
runId=choose_run_id(root,options.RunId,shortCommit);
actualCommand="RUN_PROJECT.m";
metadata=struct("run_purpose",char(config.run_purpose), ...
    "milestone","B-2C","implementation_commit",char(commit), ...
    "parent_run_id",char(config.parent_run_id), ...
    "historical_baseline_commit", ...
        "90bf33cca0611154231588ac5d7ee09fd0e9c089", ...
    "actual_test_command",char(actualCommand), ...
    "optimization_executed",true,"a1_solver_executed",false, ...
    "full_ipm_executed",false,"convergence_evaluated",false, ...
    "convergence_achieved",false,"full_kkt_role","audit_only", ...
    "recursive_direction_executed",false, ...
    "recursive_direction_is_formal",true, ...
    "water_slack_second_order_correction_enabled",true, ...
    "water_slack_second_order_correction_scope_count",56, ...
    "water_slack_second_order_correction_formula", ...
        "l_corrected=l_trial-beta*(g_after-g_before-alpha*G*dx)", ...
    "water_correction_fraction_rule", ...
        "beta=1_if_l_exact_ge_sigma_l_trial_else_tau_times_centrality_boundary", ...
    "no_full_direction_fallback",true, ...
    "full_direction_consumed_by_recursive",false, ...
    "parallel_executed",false,"annual_scope_executed",false, ...
    "thermal_second_pass_executed",false, ...
    "stage_c1_implemented",false,"stage_c1_entered",false, ...
    "water_constraints_enabled",true,"milestone_status","RUNNING");
context=rkkt.artifacts.create_run_context(root,"stage_B","RunId",runId, ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",fullfile(root,"config","stage_B_2C.yaml"), ...
    "ManifestMetadata",metadata);
diagnosticsDir=fullfile(context.root,"diagnostics");
resultsDir=fullfile(context.root,"results");
ensure_directory(diagnosticsDir); ensure_directory(resultsDir);
result=struct("run_id",string(context.run_id), ...
    "run_path",string(context.root),"status","RUNNING", ...
    "manifest",struct(),"report_path","","error_identifier","", ...
    "error_message","");
try
    environment=rkkt.diagnostics.inspect_stage_b2b_environment();
    environment=addvars(environment,repmat(string(context.run_id), ...
        height(environment),1),'Before',1,'NewVariableNames','run_id');
    write_new_table(context.environment_csv_path,environment);
    assert(all(environment.status(logical(environment.blocking))=="PASS"), ...
        "stageB2C:Environment", ...
        "A blocking MATLAB environment check failed.");
    write_new_table(context.input_hashes_csv_path, ...
        input_hash_table(inputHashes,context.run_id));

    data=rkkt.data.load_project_data(root);
    waterInput=rkkt.diagnostics.build_stage_b1_water_input_audit(data,context.run_id);
    write_new_table(fullfile(diagnosticsDir,"water_input_audit.csv"), ...
        waterInput);
    assert(height(waterInput)==28 && all(waterInput.status=="PASS"), ...
        "stageB2C:WaterInput", ...
        "The controlled 28-row water-input audit failed.");
    index=rkkt.indexing.build_stage_b2c_index(data,config,"RunId",string(context.run_id));
    persist_index_artifacts(context,index);

    gate=rkkt.diagnostics.run_stage_b2c_nonzero_hessian_gate(data,index,config, ...
        DiagnosticsDirectory=string(diagnosticsDir));
    assert(gate.passed,"stageB2C:NonzeroHessianGate", ...
        "The mandatory nonzero-water-Hessian gate failed.");
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "nonzero_water_hessian_gate_passed",true, ...
        "nonzero_water_hessian_nnz",gate.water_hessian_nnz, ...
        "nonzero_water_hessian_fro_norm",gate.water_hessian_fro_norm, ...
        "nonzero_water_hessian_direction_relative_error", ...
            gate.comparison.direction_relative_error, ...
        "nonzero_water_hessian_recursive_kkt_residual", ...
            gate.comparison.recursive_kkt_relative_residual, ...
        "nonzero_water_hessian_full_kkt_residual", ...
            gate.comparison.full_kkt_relative_residual));
    clear gate

    ipm=rkkt.solver.run_stage_b2c_full_ipm(data,index,config,context);
    if ~(ipm.convergence_achieved && ...
            string(ipm.run_terminal_state)=="CONVERGED")
        if ipm.failure.present
            throw(MException(char(ipm.failure.identifier), ...
                "%s",char(ipm.failure.message)));
        end
        error("stageB2C:Convergence", ...
            "The formal seven-day B-2C IPM did not converge within 100 iterations.");
    end
    assert(ipm.execution_audit.water_slack_second_order_correction_pass, ...
        "stageB2C:WaterCorrection", ...
        "The formal 56-row water-slack correction audit failed.");
    physical=rkkt.diagnostics.evaluate_stage_b2c_physical_audit(ipm,index,data,config);
    write_new_table(fullfile(diagnosticsDir, ...
        "final_daily_water_constraint_audit.csv"),physical.water);
    write_new_table(fullfile(context.acceptance_dir,"physical_audit.csv"), ...
        physical.stage_a);
    assert(physical.passed,"stageB2C:PhysicalAcceptance", ...
        "SB-PHY-001 or a Stage-A physical regression failed.");

    [capacityResults,hourlyResults]=build_physical_results( ...
        context,ipm,index,data,physical.physical);
    write_new_table(fullfile(resultsDir,"capacity_results.csv"), ...
        capacityResults);
    write_new_table(fullfile(resultsDir,"hourly_dispatch_results.csv"), ...
        hourlyResults);
    rkkt.artifacts.save_mat_artifact(fullfile(resultsDir,"final_state_and_physical.mat"), ...
        "final_state",ipm.final_state,"physical",physical.physical, ...
        "final_metrics",ipm.final_metrics);
    persist_final_matrix_artifacts(context,ipm);

    acceptance=make_acceptance(context,ipm,physical,waterInput,config);
    write_new_table(context.acceptance_results_path,acceptance);
    assert(all(acceptance.status=="PASS"), ...
        "stageB2C:Acceptance","A blocking Stage-B acceptance item failed.");
    issues=empty_issue_log(); write_new_table(context.issue_log_path,issues);
    decision=table(string(context.run_id),"B-2C","PASS", ...
        "Nonzero Hessian gate, formal water-slack correction, seven-day convergence, direction audits, and 28 water rows passed.", ...
        "Stage B may close; switch only the stage gate to Stage C1 / READY without implementing C1.", ...
        'VariableNames',{'run_id','milestone','status','conclusion','next_action'});
    write_new_table(context.decision_log_path,decision);

    suites=run_test_and_static_evidence(context,root);
    assert(suites.all_pass,"stageB2C:Tests", ...
        "A B-2C, regression, static, or forbidden-item suite failed.");
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "tests_executed",true,"test_total",suites.total, ...
        "test_passed",suites.passed,"test_failed",0, ...
        "test_incomplete",0, ...
        "code_analyzer_blocking_findings",0, ...
        "forbidden_execution_audit","PASS", ...
        "SB_DATA_001_status","PASS","SB_DER_001_status","PASS", ...
        "SB_EQ_001_status","PASS","SB_PHY_001_status","PASS", ...
        "fixed_zero_count",422,"final_maximum_water_violation", ...
            physical.maximum_water_violation,"stage_b_complete",true, ...
        "water_slack_second_order_correction_enabled",true, ...
        "water_slack_second_order_correction_passed",true, ...
        "minimum_water_slack_correction_fraction", ...
            ipm.execution_audit.minimum_water_slack_correction_fraction, ...
        "final_water_slack_correction_fraction", ...
            ipm.execution_audit.final_water_slack_correction_fraction, ...
        "centrality_limited_water_correction_iteration_count", ...
            ipm.execution_audit. ...
            centrality_limited_water_correction_iteration_count, ...
        "maximum_water_slack_correction_closure_error", ...
            ipm.execution_audit. ...
            maximum_water_slack_correction_closure_error, ...
        "minimum_corrected_water_slack", ...
            ipm.execution_audit.minimum_corrected_water_slack, ...
        "milestone_status","PASS"));

    report=rkkt.reporting.generate_stage_b2c_report(context.root);
    [reportValid,reportDetails]=rkkt.reporting.validate_stage_b2c_report(context.root);
    structure=table(string(context.run_id), ...
        "stage_B_2C_formal_convergence_and_water_physical_acceptance", ...
        string(report.path),reportValid,conditional_status(reportValid), ...
        string(reportDetails.message),string(report.design_preset), ...
        string(report.header_pattern), ...
        'VariableNames',{'run_id','report_id','path','valid','status', ...
        'details','design_preset','header_pattern'});
    write_new_table(fullfile(context.reports_dir, ...
        "report_structure_validation.csv"),structure);
    assert(reportValid,"stageB2C:Report", ...
        "The B-2C Chinese report failed OOXML validation: %s", ...
        reportDetails.message);
    visual=rkkt.reporting.render_stage_b2c_report_external(context.root,report.path);
    write_new_table(fullfile(context.reports_dir,"report_visual_qa.csv"), ...
        visual);
    assert(visual.status=="PASS" || startsWith(visual.status,"NOT_RUN"), ...
        "stageB2C:ReportRender", ...
        "The available DOCX render engine failed for a non-availability reason.");
    reportHash=table( ...
        "reports/阶段B-2C_七日递推IPM收敛与水量物理验收报告.docx", ...
        rkkt.data.compute_sha256_file(report.path),string(context.run_id),"PASS", ...
        'VariableNames',{'relative_path','sha256','run_id','status'});
    write_new_table(fullfile(context.reports_dir,"report_sha256.csv"), ...
        reportHash);

    evidence=write_evidence_hashes(context.root, ...
        fullfile(context.acceptance_dir,"evidence_hashes.csv"));
    manifest=rkkt.artifacts.finalize_run_manifest(context,"PASS",struct( ...
        "milestone_status","PASS","stage_b_complete",true, ...
        "stage_c1_implemented",false,"stage_c1_entered",false, ...
        "reports_generated",true,"report_structure_validated",true, ...
        "report_visual_qa_status",char(visual.status), ...
        "report_relative_path",char(reportHash.relative_path), ...
        "report_sha256",char(reportHash.sha256), ...
        "evidence_hashes","acceptance/evidence_hashes.csv", ...
        "evidence_hashes_sha256",char(rkkt.data.compute_sha256_file( ...
            fullfile(context.acceptance_dir,"evidence_hashes.csv"))), ...
        "evidence_file_count",height(evidence)));
    result.status=string(manifest.status); result.manifest=manifest;
    result.report_path=string(report.path); result.acceptance=acceptance;
    result.ipm=ipm; result.physical=physical; result.tests=suites;
catch cause
    try
        if ~isfile(context.issue_log_path)
            rkkt.artifacts.write_table_csv_17g_atomic(string(context.issue_log_path), ...
                failure_issue(context,cause));
        end
    catch
    end
    finalStatus="FAIL_RETRYABLE";
    if contains(string(cause.identifier),["Environment","InputHash"])
        finalStatus="BLOCKED_EXTERNAL";
    elseif contains(string(cause.identifier),"ModelDecision")
        finalStatus="NEEDS_MODEL_DECISION";
    end
    try
        manifest=jsondecode(fileread(context.run_manifest_path));
        if string(manifest.status)=="RUNNING"
            manifest=rkkt.artifacts.finalize_run_manifest(context,finalStatus,struct( ...
                "milestone_status",char(finalStatus), ...
                "stage_b_complete",false,"stage_c1_implemented",false, ...
                "stage_c1_entered",false, ...
                "failure_identifier",char(string(cause.identifier)), ...
                "failure_message",char(string(cause.message))));
        end
    catch
        manifest=struct();
    end
    result.status=finalStatus; result.manifest=manifest;
    result.error_identifier=string(cause.identifier);
    result.error_message=string(cause.message);
end
end

function persist_index_artifacts(context,index)
write_new_table(fullfile(context.indices_dir,"variable_index.csv"), ...
    index.variable_index);
write_new_table(fullfile(context.indices_dir,"constraint_index.csv"), ...
    index.constraint_index);
write_new_table(fullfile(context.indices_dir,"block_index.csv"), ...
    index.block_index);
write_new_table(fullfile(context.indices_dir,"fixed_zero_map.csv"), ...
    index.fixed_zero_map);
write_new_table(fullfile(context.indices_dir,"permutation_map.csv"), ...
    index.permutation_map);
write_new_table(fullfile(context.indices_dir,"soc_link_map.csv"), ...
    index.soc_link_map);
write_new_table(fullfile(context.indices_dir,"water_constraint_index.csv"), ...
    index.water_constraint_index);
end

function persist_final_matrix_artifacts(context,ipm)
lin=ipm.final_linearization; step=ipm.last_step;
linPath=fullfile(context.matrices_dir,"final_linearization.mat");
auditPath=fullfile(context.matrices_dir,"final_direction_audit.mat");
rkkt.artifacts.save_mat_artifact(linPath,"linearization",lin);
rkkt.artifacts.save_mat_artifact(auditPath, ...
    "full_kkt_matrix",step.full_audit.kkt.matrix, ...
    "full_kkt_rhs",step.full_audit.kkt.rhs, ...
    "recursive_direction",step.recursive.direction, ...
    "full_kkt_audit_direction",step.full_audit.direction, ...
    "direction_audit",step.direction_audit);
matrix_name=["H_L";"A";"G";"full_KKT_audit";"global_core_16"];
matrices={lin.H;lin.A;lin.G;step.full_audit.kkt.matrix; ...
    step.recursive.core.matrix};
row_count=zeros(5,1); column_count=zeros(5,1); nonzero_count=zeros(5,1);
for k=1:5
    [row_count(k),column_count(k)]=size(matrices{k});
    nonzero_count(k)=nnz(matrices{k});
end
artifact_path=[repmat("matrices/final_linearization.mat",3,1); ...
    repmat("matrices/final_direction_audit.mat",2,1)];
sha256=[repmat(rkkt.data.compute_sha256_file(linPath),3,1); ...
    repmat(rkkt.data.compute_sha256_file(auditPath),2,1)];
role=["shared_lagrangian_hessian";"shared_equality_jacobian"; ...
    "shared_inequality_jacobian";"independent_audit_only"; ...
    "recursive_formal"];
manifest=table(repmat(string(context.run_id),5,1),matrix_name,role, ...
    row_count,column_count,nonzero_count,true(5,1),artifact_path,sha256, ...
    repmat(string(lin.identity),5,1),repmat("PASS",5,1), ...
    'VariableNames',{'run_id','matrix_name','role','row_count', ...
    'column_count','nonzero_count','is_sparse','artifact_path','sha256', ...
    'linearization_identity','status'});
write_new_table(context.matrix_manifest_path,manifest);
end

function [capacity,hourly]=build_physical_results( ...
        context,ipm,index,data,physical)
names=string(ipm.final_linearization.capacity_parameters.names(:));
values=ipm.final_state.xi(ipm.final_linearization.maps.q_global);
capacity=table(repmat(string(context.run_id),14,1),(1:14).', ...
    names,values,'VariableNames',{'run_id','capacity_index', ...
    'capacity_name','value'});
n=7*24; day=zeros(n,1); hour=zeros(n,1); row=0;
arrays=cell(1,24);
for k=1:24, arrays{k}=zeros(n,1); end
for d=1:7
    for t=1:24
        row=row+1; day(row)=physical.days(d); hour(row)=physical.hours(t);
        valuesAtHour=[reshape(physical.value.wind(d,t,:),1,[]), ...
            reshape(physical.value.solar(d,t,:),1,[]), ...
            reshape(physical.value.hydro(d,t,:),1,[]), ...
            reshape(physical.value.thermal(d,t,:),1,[]), ...
            reshape(physical.value.charge(d,t,:),1,[]), ...
            reshape(physical.value.discharge(d,t,:),1,[]), ...
            reshape(physical.value.soc(d,t,:),1,[])];
        for k=1:24, arrays{k}(row)=valuesAtHour(k); end
    end
end
variableNames=["PW_1","PW_2","PW_3","PW_4","PW_5", ...
    "PP_1","PP_2","PP_3","PP_4","PP_5", ...
    "PH_1","PH_2","PH_3","PH_4", ...
    "PF_1","PF_2","PF_3","PF_4", ...
    "Pch_1","Pch_2","Pdis_1","Pdis_2","SOC_1","SOC_2"];
hourly=table(repmat(string(context.run_id),n,1),day,hour, ...
    'VariableNames',{'run_id','day','hour'});
for k=1:numel(variableNames), hourly.(variableNames(k))=arrays{k}; end
assert(height(hourly)==168 && width(hourly)==27 && ...
    isscalar(data.meta.nHydro) && height(index.variable_index)==3722, ...
    "stageB2C:Results","The canonical physical result table is incomplete.");
end

function value=make_acceptance(context,ipm,physical,waterInput,config)
directions=ipm.direction_audit_history;
test_id=["SB-DATA-001";"SB-DER-001";"SB-EQ-001";"SB-PHY-001"];
category=["数据";"导数";"方向等价";"物理"];
requirement=["第14—20日28组水量上下限数据有效"; ...
    "非零水量Hessian及56行精确余项中心性限幅校正通过"; ...
    "每轮递推与完整KKT方向及残差<=1e-10"; ...
    "最终28项水量与Stage-A物理审计通过"];
status=repmat("PASS",4,1);
actual_value=["28/28 input rows PASS"; ...
    compose("H_water nnz=672; min_beta=%.17g; final_beta=%.17g; max_closure=%.17g; min_l=%.17g", ...
        ipm.execution_audit.minimum_water_slack_correction_fraction, ...
        ipm.execution_audit.final_water_slack_correction_fraction, ...
        ipm.execution_audit. ...
            maximum_water_slack_correction_closure_error, ...
        ipm.execution_audit.minimum_corrected_water_slack); ...
    compose("worst_direction=%.17g; worst_recursive_residual=%.17g", ...
        max(directions.direction_relative_error), ...
        max(directions.recursive_full_kkt_relative_residual)); ...
    compose("28/28; maximum_violation=%.17g", ...
        physical.maximum_water_violation)];
evidence_path=["diagnostics/water_input_audit.csv"; ...
    "diagnostics/nonzero_water_hessian_gate.csv"; ...
    "diagnostics/direction_audit_history.csv"; ...
    "diagnostics/final_daily_water_constraint_audit.csv"];
passed=[height(waterInput)==28&&all(waterInput.status=="PASS"); ...
    ipm.execution_audit.water_slack_second_order_correction_pass; ...
    all(directions.direction_relative_error<= ...
        config.direction_relative_error_tolerance) && ...
    all(directions.recursive_full_kkt_relative_residual<= ...
        config.recursive_full_kkt_residual_tolerance) && ...
    all(directions.full_kkt_relative_residual<= ...
        config.full_kkt_residual_tolerance);physical.passed];
status(~passed)="FAIL";
value=table(repmat(string(context.run_id),4,1),test_id,category, ...
    requirement,true(4,1),status,actual_value,evidence_path, ...
    repmat("B-2C",4,1),'VariableNames',{'run_id','test_id','category', ...
    'requirement','blocking','status','actual_value','evidence_path', ...
    'milestone'});
end

function suites=run_test_and_static_evidence(context,root)
b2c=run_stage_B_2C_tests("EvidenceDirectory",string(context.tests_dir), ...
    "CommandText","run_stage_B_2C_tests() [formal B-2C evidence]");
b2b=run_stage_B_2B_tests("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"b2b_regression")), ...
    "CommandText","run_stage_B_2B_tests() [B-2C regression]");
b2a=run_stage_B_2A_tests("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"b2a_regression")), ...
    "CommandText","run_stage_B_2A_tests() [B-2C regression]");
b1=run_stage_B_1_tests("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"b1_regression")), ...
    "CommandText","run_stage_B_1_tests() [B-2C regression]");
b1Affected=run_stage_B_1_affected_regressions("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"b1_affected")), ...
    "CommandText","run_stage_B_1_affected_regressions() [B-2C]");
stageA=run_stage_B_2A_stage_A_regressions("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"stage_a_structure")), ...
    "CommandText","run_stage_B_2A_stage_A_regressions() [B-2C]");
a43=run_stage_B_2C_A4_3_affected_regressions("EvidenceDirectory", ...
    string(fullfile(context.tests_dir,"a4_3_affected")), ...
    "CommandText", ...
    "run_stage_B_2C_A4_3_affected_regressions() [B-2C]");
allPass=b2c.all_pass&&b2b.all_pass&&b2a.all_pass&&b1.all_pass&& ...
    b1Affected.all_pass&&stageA.all_pass&&a43.all_pass;
counts=[b2c.summary.test_total,b2b.summary.test_total, ...
    b2a.summary.test_total,b1.summary.test_total, ...
    b1Affected.summary.test_total,stageA.summary.test_total, ...
    a43.summary.test_total];
passedCounts=[b2c.summary.test_passed,b2b.summary.test_passed, ...
    b2a.summary.test_passed,b1.summary.test_passed, ...
    b1Affected.summary.test_passed,stageA.summary.test_passed, ...
    a43.summary.test_passed];
static=rkkt.diagnostics.run_stage_b2c_static_checks(root);
write_new_table(fullfile(context.tests_dir,"static_check_summary.csv"), ...
    static.code_analyzer);
write_new_table(fullfile(context.tests_dir,"forbidden_code_audit.csv"), ...
    static.forbidden_execution);
write_new_table(fullfile(context.tests_dir, ...
    "dependency_closure_audit.csv"),static.dependency_closure);
write_new_table(fullfile(context.tests_dir, ...
    "forbidden_execution_audit.csv"),static.runtime_boundary);
diffScope=[ ...
    "src/+rkkt/+workflows/stageB2C.m"; ...
    "src/+rkkt/+solver/compute_stage_b2c_water_slack_second_order_correction.m"; ...
    "src/+rkkt/+solver/run_stage_b2c_full_ipm.m"; ...
    "src/+rkkt/+diagnostics/execute_stage_b2c_iteration.m"; ...
    "src/+rkkt/+diagnostics/execute_stage_b2c_water_corrected_iteration.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b2c_static_checks.m"; ...
    "src/+rkkt/+reporting/generate_stage_b2c_report.m"; ...
    "src/+rkkt/+reporting/validate_stage_b2c_report.m"; ...
    "tests/integration/test_stage_b2c_formal_ipm.m"; ...
    "tests/unit/test_stage_b2c_water_slack_second_order_correction.m"];
diffCommand="diff --check -- "+strjoin(diffScope," ");
[diffCode,diffOutput]=system(git_command(root,diffCommand));
rkkt.artifacts.write_text_utf8(fullfile(context.tests_dir,"git_diff_check.txt"), ...
    "scope="+strjoin(diffScope,"|")+newline+ ...
    "exit_code="+string(diffCode)+newline+string(diffOutput));
suites=struct("b2c",b2c.summary,"b2b",b2b.summary, ...
    "b2a",b2a.summary,"b1",b1.summary, ...
    "b1_affected",b1Affected.summary,"stage_a",stageA.summary, ...
    "a4_3",a43.summary,"static",static, ...
    "total",sum(counts),"passed",sum(passedCounts), ...
    "all_pass",allPass&&static.all_pass&&diffCode==0);
end

function value=empty_issue_log()
value=table(strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end
function value=failure_issue(context,cause)
testId="SB-PHY-001";
if contains(string(cause.identifier), ...
        ["solver","retained","day","Kkt","Direction"])
    testId="SB-EQ-001";
end
value=table(string(context.run_id),"B2C-EXECUTION",testId, ...
    "execution",string(cause.message), ...
    "Unique failed run and all completed artifacts were preserved.", ...
    "Repair the first failed layer without changing model or thresholds.", ...
    "OPEN","run_manifest.json", ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end

function value=write_evidence_hashes(runRoot,pathValue)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB2C:EvidenceHashExists","Refusing to overwrite hash evidence.");
listing=dir(fullfile(runRoot,"**","*")); listing=listing(~[listing.isdir]);
relative_path=strings(0,1); sha256=strings(0,1); bytes=zeros(0,1);
for k=1:numel(listing)
    absolute=string(fullfile(listing(k).folder,listing(k).name));
    relative=replace(extractAfter(absolute,string(runRoot)+filesep), ...
        filesep,"/");
    if relative=="acceptance/evidence_hashes.csv" || ...
            relative=="run_manifest.json"
        continue
    end
    relative_path(end+1,1)=relative; %#ok<AGROW>
    sha256(end+1,1)=rkkt.data.compute_sha256_file(absolute); %#ok<AGROW>
    bytes(end+1,1)=listing(k).bytes; %#ok<AGROW>
end
[relative_path,order]=sort(relative_path);
sha256=sha256(order); bytes=bytes(order);
value=table(relative_path,sha256,bytes,repmat("PASS",numel(bytes),1), ...
    'VariableNames',{'relative_path','sha256','bytes','status'});
write_new_table(pathValue,value);
end

function value=input_hash_object(hashes)
base=hashes.fileName=="基础参数.xlsx";
series=hashes.fileName=="输入数据.xlsx";
assert(nnz(base)==1&&nnz(series)==1,"stageB2C:InputHashRows", ...
    "Both controlled input rows are required.");
value=struct("base_parameters",char(hashes.actualSHA256(base)), ...
    "timeseries",char(hashes.actualSHA256(series)));
end
function value=input_hash_table(hashes,runId)
n=height(hashes);
value=table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status'});
end
function value=git_commit(root)
[code,output]=system(git_command(root,"rev-parse HEAD"));
value=lower(strip(string(output)));
assert(code==0&&~isempty(regexp(value,"^[0-9a-f]{40}$","once")), ...
    "stageB2C:GitCommit","Could not resolve implementation commit.");
end
function value=git_command(root,arguments)
safe=replace(char(root),'\','/');
value=string(sprintf('git -c safe.directory=%s %s',safe,char(arguments)));
end
function runId=choose_run_id(root,requested,shortCommit)
if strlength(strip(requested))>0
    runId=requested;
    assert(~contains(runId,["/","\"]),"stageB2C:RunId", ...
        "Run id must be a leaf name.");
else
    timestamp=string(datetime("now","TimeZone","UTC", ...
        "Format","yyyyMMdd_HHmmss"));
    runId=timestamp+"_stage_B_2C_"+shortCommit;
end
assert(~isfile(fullfile(root,"runs",runId))&& ...
    ~isfolder(fullfile(root,"runs",runId)),"stageB2C:RunExists", ...
    "Run path already exists: %s",runId);
end
function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message]=mkdir(pathValue);
assert(created,"stageB2C:Directory","%s",message);
end
function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB2C:ArtifactExists","Refusing to overwrite %s.",pathValue);
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end
function value=conditional_status(passed)
if passed, value="PASS"; else, value="FAIL"; end
end
