function result = stageB2CInitial30DayBlockScan(options)
%STAGEB2CINITIAL30DAYBLOCKSCAN Scan initialization day-block LDL pivots.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
end

root = options.ProjectRoot;
if strlength(strip(root))==0
    root = rkkt.projectRoot();
end
root = string(java.io.File(char(root)).getCanonicalPath());
days = 1:30;
dataPath = fullfile(root,"src","+rkkt","+data","+validation", ...
    "数据导入模块输出.mat");
configPath = fullfile(root,"config", ...
    "stage_B_2C_initial_30_day_block_scan.yaml");
assert(isfile(dataPath),"stageB2C:initialScan:DataModule", ...
    "PKG-2 data module output is missing: %s",dataPath);

loaded = load(dataPath,"moduleResult");
data = loaded.moduleResult.output.projectData;
referenceConfig = rkkt.model.load_stage_b2c_configuration(root);
dataModuleHash = rkkt.data.compute_sha256_file(dataPath);
tests = run_targeted_test(root);
analyzer = run_code_analyzer(root);
assert(tests.all_pass && all(analyzer.status=="PASS"), ...
    "stageB2C:initialScan:DevelopmentChecks", ...
    "The targeted test or Code Analyzer check failed.");
inputHashes = struct();
inputHashes.data_module_mat_sha256 = ...
    char(lower(string(dataModuleHash)));
inputHashes.controlled_source_sha256 = ...
    cellstr(lower(string(data.hashes.actualSHA256)));
metadata = struct( ...
    "run_purpose","stage_B_2C_initial_point_daily_joint_block_prevalence_scan", ...
    "milestone","B-2C-INITIAL-30-DAY-BLOCK-SCAN", ...
    "actual_test_command", ...
        "runtests tests/unit/test_stage_b2c_initial_day_pivot_scan.m", ...
    "optimization_executed",false,"a1_solver_executed",false, ...
    "full_ipm_executed",false,"state_update_executed",false, ...
    "convergence_evaluated",false,"convergence_claimed",false, ...
    "full_kkt_executed",false,"newton_direction_count",0, ...
    "recursive_direction_executed",false, ...
    "daily_joint_direction_executed",false, ...
    "numerical_zero_gate_bypassed_for_diagnostic",true, ...
    "production_gate_changed",false,"formal_stage_b2c_modified",false, ...
    "milestone_status","RUNNING");
context = rkkt.artifacts.create_run_context(root,"stage_B", ...
    "RunId",options.RunId,"ModelContractVersion","v1.0", ...
    "InputHashes",inputHashes,"EffectiveConfigPath",configPath, ...
    "ManifestMetadata",metadata);
diagnosticsDir = fullfile(context.root,"diagnostics");
resultsDir = fullfile(context.root,"results");
ensure_directory(diagnosticsDir);
ensure_directory(resultsDir);

result = struct("run_id",string(context.run_id), ...
    "run_path",string(context.root),"status","RUNNING", ...
    "manifest",struct(),"report_path","", ...
    "error_identifier","","error_message","");
runTimer = tic;
try
    environment = rkkt.diagnostics.inspect_stage_b2b_environment();
    environment = addvars(environment,repmat(string(context.run_id), ...
        height(environment),1),'Before',1,'NewVariableNames','run_id');
    write_new_table(context.environment_csv_path,environment);
    assert(all(environment.status(logical(environment.blocking))=="PASS"), ...
        "stageB2C:initialScan:Environment", ...
        "A blocking MATLAB environment check failed.");
    write_new_table(context.input_hashes_csv_path, ...
        input_hash_table(context,dataPath,dataModuleHash,data));
    persist_targeted_test(context,tests);
    write_new_table(fullfile(context.tests_dir,"code_analyzer.csv"),analyzer);

    equivalence = formal_representation_equivalence( ...
        data,referenceConfig,context.run_id);
    equivalence = addvars(equivalence,repmat(string(context.run_id), ...
        height(equivalence),1),'Before',1,'NewVariableNames','run_id');
    write_new_table(fullfile(diagnosticsDir, ...
        "正式七日日块表示一致性.csv"),equivalence);

    fixture = rkkt.diagnostics.build_stage_b2c_initial_day_scan_fixture( ...
        data,days,referenceConfig,string(context.run_id));
    scan = rkkt.diagnostics.scan_stage_b2c_initial_day_pivots(fixture.day);
    scan = addvars(scan,repmat(string(context.run_id),height(scan),1), ...
        'Before',1,'NewVariableNames','run_id');
    write_new_table(fullfile(diagnosticsDir,"初始化30日日块扫描.csv"),scan);
    summary = scan_summary(context,fixture,scan);
    write_new_table(fullfile(diagnosticsDir, ...
        "初始化30日日块扫描摘要.csv"),summary);

    [weakestPosition,weakestDay] = weakest_day(scan);
    weakestBlockPath = fullfile(context.matrices_dir, ...
        "最弱初始化日块.mat");
    rkkt.artifacts.save_mat_artifact(weakestBlockPath, ...
        "matrix",fixture.day(weakestPosition).matrix, ...
        "day",weakestDay,"scan_row",scan(weakestPosition,:));
    matrixManifest = table(string(context.run_id), ...
        "weakest_initial_daily_joint_block",weakestDay, ...
        fixture.day(weakestPosition).dimension, ...
        fixture.day(weakestPosition).nnz,true, ...
        "matrices/最弱初始化日块.mat", ...
        string(rkkt.data.compute_sha256_file(weakestBlockPath)), ...
        'VariableNames',{'run_id','matrix_name','day','dimension', ...
        'nnz','is_sparse','relative_path','sha256'});
    write_new_table(context.matrix_manifest_path,matrixManifest);

    resultPath = fullfile(resultsDir,"初始化30日日块扫描结果.mat");
    scope = struct("days",days,"hours",1:24, ...
        "observation_point","deterministic_initialization", ...
        "full_kkt_executed",false,"newton_direction_executed",false, ...
        "full_ipm_executed",false,"state_update_executed",false);
    counts = fixture.counts;
    rkkt.artifacts.save_mat_artifact(resultPath,"scan",scan, ...
        "summary",summary,"formal_equivalence",equivalence, ...
        "scope",scope,"counts",counts);

    acceptance = acceptance_table(context,fixture,scan,equivalence, ...
        tests,analyzer);
    write_new_table(context.acceptance_results_path,acceptance);
    issues = issue_table(context,scan);
    write_new_table(context.issue_log_path,issues);
    terminalStatus = terminal_status(scan,equivalence);
    decision = decision_table(context,terminalStatus,scan);
    write_new_table(context.decision_log_path,decision);

    elapsedSeconds = toc(runTimer);
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "tests_executed",true,"test_total",tests.test_total, ...
        "test_passed",tests.test_passed,"test_failed",tests.test_failed, ...
        "code_analyzer_findings",sum(analyzer.finding_count), ...
        "scan_day_count",30,"daily_joint_block_factorization_count",30, ...
        "numerical_weak_day_count",nnz(scan.would_trigger_current_gate), ...
        "structural_rank_failure_count",nnz( ...
            scan.status=="STRUCTURAL_RANK_DEFICIENT"), ...
        "factor_warning_or_failure_count",nnz(ismember(scan.status, ...
            ["FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"])), ...
        "formal_7day_representation_isequaln", ...
            all(equivalence.matrix_isequaln), ...
        "full_kkt_executed",false,"newton_direction_count",0, ...
        "recursive_direction_executed",false, ...
        "daily_joint_direction_executed",false, ...
        "full_ipm_executed",false,"state_update_executed",false, ...
        "convergence_evaluated",false,"convergence_claimed",false, ...
        "elapsed_seconds",elapsedSeconds, ...
        "milestone_status",char(terminalStatus)));

    report = rkkt.reporting.generate_stage_b2c_initial_30_day_scan_report( ...
        context.root);
    [reportValid,reportValidation] = ...
        rkkt.reporting.validate_docx_package(report.path);
    reportStructure = table(string(context.run_id),string(report.path), ...
        reportValid,conditional_status(reportValid), ...
        strjoin(string(reportValidation.errors),"; "), ...
        'VariableNames',{'run_id','path','valid','status','details'});
    write_new_table(fullfile(context.reports_dir, ...
        "report_structure_validation.csv"),reportStructure);
    assert(reportValid,"stageB2C:initialScan:Report", ...
        "The Chinese scan report failed DOCX structure validation.");
    visual = rkkt.reporting.render_stage_b2c_report_external( ...
        context.root,report.path);
    write_new_table(fullfile(context.reports_dir,"report_visual_qa.csv"), ...
        visual);
    reportHash = rkkt.data.compute_sha256_file(report.path);
    write_new_table(fullfile(context.reports_dir,"report_sha256.csv"), ...
        table(string(context.run_id), ...
        "reports/阶段B-2C_初始化30日日块弱主元扫描报告.docx", ...
        string(reportHash),"PASS", ...
        'VariableNames',{'run_id','relative_path','sha256','status'}));

    manifest = rkkt.artifacts.finalize_run_manifest( ...
        context,terminalStatus,struct( ...
        "milestone_status",char(terminalStatus), ...
        "daily_joint_block_factorization_count",30, ...
        "numerical_weak_day_count",nnz(scan.would_trigger_current_gate), ...
        "full_kkt_executed",false,"newton_direction_count",0, ...
        "recursive_direction_executed",false, ...
        "daily_joint_direction_executed",false, ...
        "full_ipm_executed",false,"state_update_executed",false, ...
        "convergence_evaluated",false,"convergence_claimed",false, ...
        "production_gate_changed",false, ...
        "formal_stage_b2c_modified",false, ...
        "reports_generated",true,"report_structure_validated",true, ...
        "report_visual_qa_status",char(string(visual.status)), ...
        "report_relative_path", ...
            "reports/阶段B-2C_初始化30日日块弱主元扫描报告.docx", ...
        "report_sha256",char(reportHash),"elapsed_seconds",elapsedSeconds));
    rkkt.artifacts.update_run_index(context,manifest);
    result.status = terminalStatus;
    result.manifest = manifest;
    result.report_path = string(report.path);
    result.scan = scan;
    result.summary = summary;
    result.formal_equivalence = equivalence;
catch cause
    finalStatus = "FAIL_RETRYABLE";
    if contains(string(cause.identifier),"ModelDecision")
        finalStatus = "NEEDS_MODEL_DECISION";
    elseif contains(string(cause.identifier),["Environment","DataModule"])
        finalStatus = "BLOCKED_EXTERNAL";
    end
    ensure_failure_artifacts(context,cause,finalStatus);
    manifest = jsondecode(fileread(context.run_manifest_path));
    if string(manifest.status)=="RUNNING"
        manifest = rkkt.artifacts.finalize_run_manifest( ...
            context,finalStatus,struct( ...
            "milestone_status",char(finalStatus), ...
            "full_kkt_executed",false,"newton_direction_count",0, ...
            "recursive_direction_executed",false, ...
            "daily_joint_direction_executed",false, ...
            "full_ipm_executed",false,"state_update_executed",false, ...
            "convergence_evaluated",false,"convergence_claimed",false, ...
            "production_gate_changed",false, ...
            "formal_stage_b2c_modified",false, ...
            "failure_identifier",char(string(cause.identifier)), ...
            "failure_message",char(string(cause.message)), ...
            "elapsed_seconds",toc(runTimer)));
        rkkt.artifacts.update_run_index(context,manifest);
    end
    result.status = finalStatus;
    result.manifest = manifest;
    result.error_identifier = string(cause.identifier);
    result.error_message = string(cause.message);
end
end

function equivalence = formal_representation_equivalence(data,config,runId)
formalIndex = rkkt.indexing.build_stage_b2c_index( ...
    data,config,"RunId",string(runId)+"_FORMAL_7DAY");
formalState = rkkt.model.initialize_stage_b2c_state( ...
    data,formalIndex,config);
formalLinearization = rkkt.model.build_stage_b2c_multiday_linearization( ...
    formalState,data,formalIndex,config);
formalReduced = rkkt.solver.eliminate_stage_b2c_all_inequality_directions( ...
    formalLinearization);
formalPartition = rkkt.solver.partition_stage_b2c_daily_joint_system( ...
    formalLinearization,formalReduced);
diagnostic = rkkt.diagnostics.build_stage_b2c_initial_day_scan_fixture( ...
    data,14:20,config,string(runId)+"_DIAGNOSTIC_7DAY");

day = (14:20).';
diagnosticDimension = reshape([diagnostic.day.dimension],[],1);
formalDimension = reshape([formalPartition.day.dimension],[],1);
indexExactEqual = false(7,1);
matrixIsequaln = false(7,1);
matrixRelativeError = zeros(7,1);
for position = 1:7
    indexExactEqual(position) = isequal( ...
        diagnostic.day(position).canonical_reduced_indices, ...
        formalPartition.day(position).canonical_reduced_indices);
    matrixIsequaln(position) = isequaln( ...
        diagnostic.day(position).matrix,formalPartition.day(position).matrix);
    difference = diagnostic.day(position).matrix- ...
        formalPartition.day(position).matrix;
    matrixRelativeError(position) = norm(difference,"fro")/ ...
        max(1,norm(formalPartition.day(position).matrix,"fro"));
end
equivalence = table(day,diagnosticDimension,formalDimension, ...
    indexExactEqual,matrixIsequaln,matrixRelativeError, ...
    'VariableNames',{'day','diagnostic_dimension','formal_dimension', ...
    'index_exact_equal','matrix_isequaln','matrix_relative_error'});
end

function tests = run_targeted_test(root)
relativePath = "tests/unit/test_stage_b2c_initial_day_pivot_scan.m";
suite = matlab.unittest.TestSuite.fromFile(fullfile(root,relativePath));
testResult = run(suite);
names = string({testResult.Name}).';
passed = reshape([testResult.Passed],[],1);
failed = reshape([testResult.Failed],[],1);
incomplete = reshape([testResult.Incomplete],[],1);
duration = reshape([testResult.Duration],[],1);
status = repmat("FAIL",numel(testResult),1);
status(passed) = "PASS";
results = table(names,passed,failed,incomplete,duration,status, ...
    'VariableNames',{'test_name','passed','failed','incomplete', ...
    'duration_seconds','status'});
tests = struct("test_total",numel(testResult), ...
    "test_passed",nnz(passed),"test_failed",nnz(~passed), ...
    "all_pass",all(passed),"results",results);
end

function persist_targeted_test(context,tests)
results = addvars(tests.results,repmat(string(context.run_id), ...
    height(tests.results),1),'Before',1,'NewVariableNames','run_id');
write_new_table(context.test_results_csv_path,results);
inventory = table("B2C-INITIAL-SCAN-001", ...
    "tests/unit/test_stage_b2c_initial_day_pivot_scan.m", ...
    "records numerical weak pivot and continues to later day blocks", ...
    'VariableNames',{'test_id','test_file','purpose'});
write_new_table(context.test_inventory_path,inventory);
rkkt.artifacts.write_text_utf8(context.test_command_path, ...
    "runtests tests/unit/test_stage_b2c_initial_day_pivot_scan.m");
summary = rmfield(tests,"results");
rkkt.artifacts.write_json_file(context.test_summary_path,summary);
end

function value = run_code_analyzer(root)
relativeFiles = [ ...
    "src/+rkkt/+diagnostics/build_stage_b2c_initial_day_scan_fixture.m"
    "src/+rkkt/+diagnostics/scan_stage_b2c_initial_day_pivots.m"
    "src/+rkkt/+reporting/generate_stage_b2c_initial_30_day_scan_report.m"
    "src/+rkkt/+workflows/stageB2CInitial30DayBlockScan.m"
    "tests/unit/test_stage_b2c_initial_day_pivot_scan.m"];
findingCount = zeros(numel(relativeFiles),1);
status = strings(numel(relativeFiles),1);
for position = 1:numel(relativeFiles)
    findings = checkcode(fullfile(root,relativeFiles(position)),"-id");
    findingCount(position) = numel(findings);
    status(position) = conditional_status(isempty(findings));
end
value = table(relativeFiles,findingCount,status, ...
    'VariableNames',{'file','finding_count','status'});
end

function value = input_hash_table(context,dataPath,dataModuleHash,data)
source = ["PKG-2 data module MAT";string(data.hashes.fileName)];
path = [string(dataPath);string(data.hashes.filePath)];
sha256 = [string(dataModuleHash);string(data.hashes.actualSHA256)];
status = ["PASS";string(data.hashes.status)];
value = table(repmat(string(context.run_id),numel(source),1), ...
    source,path,lower(sha256),status, ...
    'VariableNames',{'run_id','source','path','sha256','status'});
end

function value = scan_summary(context,fixture,scan)
[~,weakestDay] = weakest_day(scan);
weakRows = scan.would_trigger_current_gate;
metrics = [ ...
    "扫描日期";"每日小时数";"日块数量";"数值弱主元日期数"; ...
    "数值弱主元日期";"弱主元日期比例";"最弱日期";"最小绝对主元"; ...
    "对应参考阈值";"结构秩亏日期数";"分解警告或失败日期数"; ...
    "跨日直接耦合nnz";"约化排列为双射";"日块分解总秒数"];
values = [ ...
    "1—30";"24";string(height(scan));string(nnz(weakRows)); ...
    weak_day_text(scan);compose("%.17g",nnz(weakRows)/height(scan)); ...
    string(weakestDay);compose("%.17g",min(scan.minimum_absolute_pivot, ...
        [],"omitnan")); ...
    compose("%.17g",scan.pivot_reference_tolerance(scan.day==weakestDay)); ...
    string(nnz(scan.status=="STRUCTURAL_RANK_DEFICIENT")); ...
    string(nnz(ismember(scan.status, ...
        ["FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"]))); ...
    string(fixture.cross_day_nnz);string(fixture.permutation_is_bijection); ...
    compose("%.17g",sum(scan.factor_seconds,"omitnan"))];
value = table(repmat(string(context.run_id),numel(metrics),1), ...
    metrics,values,'VariableNames',{'run_id','metric','value'});
end

function [position,day] = weakest_day(scan)
finite = find(isfinite(scan.minimum_absolute_pivot));
[~,local] = min(scan.minimum_absolute_pivot(finite));
position = finite(local);
day = scan.day(position);
end

function value = weak_day_text(scan)
days = scan.day(scan.would_trigger_current_gate);
if isempty(days)
    value = "无";
else
    value = strjoin(string(days),"、");
end
end

function value = acceptance_table(context,fixture,scan,equivalence,tests,analyzer)
checkId = [ ...
    "formal_7day_representation_exact";"scan_day_count"; ...
    "daily_24_hour_scope";"cross_day_coupling"; ...
    "reduced_permutation";"structural_rank";"factor_warning"; ...
    "targeted_test";"code_analyzer";"execution_boundary"];
actualValue = [ ...
    string(all(equivalence.matrix_isequaln & equivalence.index_exact_equal)); ...
    string(height(scan));"24";string(fixture.cross_day_nnz); ...
    string(fixture.permutation_is_bijection); ...
    string(nnz(scan.status=="STRUCTURAL_RANK_DEFICIENT")); ...
    string(nnz(ismember(scan.status, ...
        ["FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"]))); ...
    string(tests.test_passed)+"/"+string(tests.test_total); ...
    string(sum(analyzer.finding_count)); ...
    "no full KKT, direction, IPM, or state update"];
requirement = ["true";"30";"24";"0";"true";"0";"0"; ...
    string(tests.test_total)+"/"+string(tests.test_total);"0"; ...
    "diagnostic factorization only"];
passed = [ ...
    all(equivalence.matrix_isequaln & equivalence.index_exact_equal); ...
    height(scan)==30;true;fixture.cross_day_nnz==0; ...
    fixture.permutation_is_bijection; ...
    ~any(scan.status=="STRUCTURAL_RANK_DEFICIENT"); ...
    ~any(ismember(scan.status, ...
        ["FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"])); ...
    tests.all_pass;all(analyzer.status=="PASS");true];
status = repmat("FAIL",numel(checkId),1);
status(passed) = "PASS";
value = table(repmat(string(context.run_id),numel(checkId),1), ...
    checkId,actualValue,requirement,status, ...
    'VariableNames',{'run_id','check_id','actual_value','requirement','status'});
end

function value = issue_table(context,scan)
selected = scan.would_trigger_current_gate | scan.status~= ...
    "PASS";
rows = scan(selected,:);
if isempty(rows)
    value = table(strings(0,1),strings(0,1),strings(0,1), ...
        strings(0,1),strings(0,1),strings(0,1), ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    return
end
issueId = "INITIAL_DAY_"+compose("%02d",rows.day)+"_"+rows.status;
severity = repmat("OBSERVATION",height(rows),1);
severity(ismember(rows.status,["STRUCTURAL_RANK_DEFICIENT", ...
    "FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"])) = "BLOCKING";
description = "day="+string(rows.day)+", min_pivot="+ ...
    compose("%.17g",rows.minimum_absolute_pivot)+", tolerance="+ ...
    compose("%.17g",rows.pivot_reference_tolerance)+", status="+rows.status;
nextAction = repmat("retain production gate; assess prevalence before model decision", ...
    height(rows),1);
value = table(repmat(string(context.run_id),height(rows),1), ...
    issueId,severity,rows.status,description,nextAction, ...
    'VariableNames',{'run_id','issue_id','severity','status', ...
    'description','next_action'});
end

function value = decision_table(context,status,scan)
conclusion = "Initialization scan completed; numerical weak pivots were recorded without changing the production gate.";
nextAction = "USER_REVIEW_30_DAY_PREVALENCE_BEFORE_ANY_MODEL_CHANGE";
value = table(string(context.run_id), ...
    "B-2C-INITIAL-30-DAY-BLOCK-SCAN",status,conclusion,nextAction, ...
    nnz(scan.would_trigger_current_gate),false,false,false, ...
    'VariableNames',{'run_id','milestone','status','conclusion', ...
    'next_action','numerical_weak_day_count','full_kkt_executed', ...
    'newton_direction_executed','full_ipm_executed'});
end

function status = terminal_status(scan,equivalence)
if any(scan.status=="STRUCTURAL_RANK_DEFICIENT") || ...
        any(ismember(scan.status, ...
        ["FACTOR_WARNING_RECORDED","FACTORIZATION_FAILED"]))
    status = "NEEDS_MODEL_DECISION";
elseif ~all(equivalence.matrix_isequaln & equivalence.index_exact_equal)
    status = "FAIL_RETRYABLE";
else
    status = "PASS";
end
end

function ensure_failure_artifacts(context,cause,status)
if ~isfile(context.issue_log_path)
    issue = table(string(context.run_id),"WORKFLOW_FAILURE","BLOCKING", ...
        status,string(cause.identifier)+": "+string(cause.message), ...
        "FIX_AND_RERUN_UNIQUE_DIAGNOSTIC", ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    write_new_table(context.issue_log_path,issue);
end
if ~isfile(context.acceptance_results_path)
    acceptance = table(string(context.run_id),"workflow_completed", ...
        string(cause.identifier),"no exception","FAIL", ...
        'VariableNames',{'run_id','check_id','actual_value', ...
        'requirement','status'});
    write_new_table(context.acceptance_results_path,acceptance);
end
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB2C:initialScan:ArtifactExists", ...
    "Refusing to overwrite %s.",pathValue);
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end

function ensure_directory(pathValue)
if ~isfolder(pathValue)
    [created,message] = mkdir(pathValue);
    assert(created,"stageB2C:initialScan:Directory","%s",message);
end
end

function value = conditional_status(condition)
if condition
    value = "PASS";
else
    value = "FAIL";
end
end
