function result = stageB2C30DayExperiment(options)
%STAGEB2C30DAYEXPERIMENT Run the 30-day recursive-only preset.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
    options.MaxIterations (1,1) double ...
        {mustBeInteger,mustBePositive} = 100
    options.RequireConvergence (1,1) logical = true
end
root = options.ProjectRoot;
if strlength(strip(root))==0
    root = rkkt.projectRoot();
end
settings = rkkt.config.build_stage_b2c_run_settings(root, ...
    DayStart=1,DayEnd=30,MaxIterations=options.MaxIterations, ...
    RequireConvergence=options.RequireConvergence, ...
    AuditMode="recursive_only",RunId=options.RunId, ...
    ConfigPath=fullfile(root,"config", ...
        "stage_B_2C_30_day_experiment.yaml"));
result = rkkt.workflows.stageB2CConfigured( ...
    settings,ProjectRoot=root,RunId=options.RunId);
end
