function result = stageB1(options)
%STAGEB1 Run the Stage B-1 water-data/derivative baseline only.
%
% This entry point deliberately stops at the data and analytic-derivative
% milestone. It does not assemble KKT, calculate a Newton direction, invoke
% an IPM, or connect water constraints to a solver.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
end

projectRoot = options.ProjectRoot;
if strlength(strtrim(projectRoot)) == 0
    projectRoot = rkkt.projectRoot();
end
projectRoot = string(java.io.File(char(projectRoot)).getCanonicalPath());
addpath(fullfile(projectRoot,"tests"));

assert_stage_b1_preflight(projectRoot);
[inputHashes,inputHashesPass] = rkkt.data.verify_input_hashes(projectRoot);
assert(inputHashesPass,"stageB1:InputHashMismatch", ...
    "Controlled input SHA256 verification failed.");

shortCommit = git_short_commit(projectRoot);
runId = choose_run_id(projectRoot,options.RunId,shortCommit);
metadata = struct( ...
    "run_purpose","stage_B_1_water_data_derivative_baseline", ...
    "milestone","B-1", ...
    "historical_baseline_commit", ...
        "fcccf11d7fa150820aa9f238a0f42c33f5efe11b", ...
    "data_window_days",(14:20), ...
    "data_window_hours",(1:24), ...
    "hydro_ids",(1:4), ...
    "water_formula","sum_t=1:24(a*P^2+b*P+c)", ...
    "water_units","m3/day", ...
    "power_units","MW", ...
    "derivative_threshold",1e-7, ...
    "optimization_executed",false, ...
    "a1_solver_executed",false, ...
    "full_ipm_executed",false, ...
    "full_kkt_executed",false, ...
    "recursive_direction_executed",false, ...
    "newton_direction_count",0, ...
    "parallel_executed",false, ...
    "stage_b_complete",false, ...
    "stage_c1_entered",false, ...
    "annual_scope_executed",false, ...
    "thermal_second_pass_enabled",false, ...
    "water_constraints_connected_to_kkt",false, ...
    "stage_b1_data_derivative_executed",false);

configPath = fullfile(projectRoot,"config","stage_B.yaml");
context = rkkt.artifacts.create_run_context(projectRoot,"stage_B", ...
    "RunId",runId, ...
    "ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",configPath, ...
    "ManifestMetadata",metadata);
diagnosticsDir = fullfile(context.root,"diagnostics");
ensure_directory(diagnosticsDir);

result = struct("run_id",string(context.run_id), ...
    "run_path",string(context.root),"status","RUNNING", ...
    "acceptance",table(),"issues",table(),"checks",table(), ...
    "audit",table(),"report_path","","error_identifier","");

try
    environment = rkkt.diagnostics.inspect_stage_b1_environment();
    environment = addvars(environment, ...
        repmat(string(context.run_id),height(environment),1), ...
        'Before',1,'NewVariableNames','run_id');
    write_new_table(context.environment_csv_path,environment);
    write_new_table(context.input_hashes_csv_path, ...
        input_hash_table(inputHashes,context.run_id));
    environmentPass = all(string(environment.status( ...
        logical(environment.blocking)))=="PASS");
    if ~environmentPass
        error("stageB1:ExternalPreflight", ...
            "A blocking B-1 environment capability is unavailable; " + ...
            "no derivative check was run.");
    end

    data = rkkt.data.load_project_data(projectRoot);
    audit = rkkt.diagnostics.build_stage_b1_water_input_audit(data,context.run_id);
    assert(height(audit)==28 && all(audit.status=="PASS"), ...
        "stageB1:WaterAuditFailed", ...
        "The authoritative 28 day-hydro water audit did not pass.");
    [checks,details] = rkkt.diagnostics.run_stage_b1_derivative_checks(data);
    assert(height(checks)==112 && all(checks.status=="PASS") && ...
        max(checks.gradient_relative_error)<=1e-7 && ...
        max(checks.hessian_relative_error)<=1e-7, ...
        "stageB1:DerivativeAuditFailed", ...
        "Independent gradient/Hessian checks did not satisfy 1e-7.");

    write_new_table(fullfile(diagnosticsDir,"water_input_audit.csv"),audit);
    write_new_table(fullfile(diagnosticsDir,"derivative_check.csv"),checks);
    matPath = fullfile(diagnosticsDir, ...
        "water_data_derivative_result.mat");
    assert(~isfile(matPath)&&~isfolder(matPath), ...
        "stageB1:ArtifactExists", ...
        "Refusing to overwrite the B-1 MAT artifact.");
    rkkt.artifacts.save_mat_artifact(matPath, ...
        "water_input_audit",audit, ...
        "derivative_check",checks, ...
        "derivative_details",details, ...
        "source_input_hashes",inputHashes);

    acceptance = make_acceptance(context,audit,checks);
    write_new_table(context.acceptance_results_path,acceptance);
    issues = empty_issue_log();
    write_new_table(context.issue_log_path,issues);
    decision = table(string(context.run_id),"B-1", ...
        "PASS", ...
        "Data and derivative baseline passed; Stage B remains READY.", ...
        "B-2: extend linearization/KKT/recursive day response", ...
        'VariableNames',{'run_id','milestone','status','conclusion', ...
        'next_action'});
    write_new_table(context.decision_log_path,decision);

    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "stage_b1_data_derivative_executed",true, ...
        "water_input_row_count",height(audit), ...
        "derivative_sample_count",height(checks), ...
        "derivative_max_gradient_relative_error", ...
            max(checks.gradient_relative_error), ...
        "derivative_max_hessian_relative_error", ...
            max(checks.hessian_relative_error), ...
        "blocking_acceptance_total",2, ...
        "blocking_acceptance_pass",2, ...
        "stage_b1_status","PASS", ...
        "stage_b_complete",false, ...
        "stage_c1_entered",false));

    testCommand = "run_stage_B_1_tests(""EvidenceDirectory"",""" + ...
        replace(string(context.tests_dir),'"','""') + """)";
    testEvidence = run_stage_B_1_tests( ...
        "EvidenceDirectory",string(context.tests_dir), ...
        "CommandText",testCommand);
    assert(testEvidence.all_pass && ...
        testEvidence.summary.test_total==14 && ...
        testEvidence.summary.test_failed==0 && ...
        testEvidence.summary.test_incomplete==0, ...
        "stageB1:TestsFailed", ...
        "The exact fourteen B-1 tests must pass.");

    regressionDirectory = fullfile(context.tests_dir, ...
        "affected_data_index_regression");
    regressionCommand = ...
        "run_stage_B_1_affected_regressions(""EvidenceDirectory"",""" + ...
        replace(string(regressionDirectory),'"','""') + """)";
    regressionEvidence = run_stage_B_1_affected_regressions( ...
        "EvidenceDirectory",string(regressionDirectory), ...
        "CommandText",regressionCommand);
    assert(regressionEvidence.all_pass && ...
        regressionEvidence.summary.test_total==5, ...
        "stageB1:AffectedRegressionFailed", ...
        "The affected data/index regression must be 5/5 PASS.");

    staticSummary = run_static_checks(projectRoot,context.root);
    write_new_table(fullfile(context.tests_dir, ...
        "static_check_summary.csv"),staticSummary);
    assert(all(staticSummary.status=="PASS"), ...
        "stageB1:StaticCheckFailed", ...
        "A new MATLAB file has Code Analyzer findings.");
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "tests_executed",true, ...
        "test_total",testEvidence.summary.test_total, ...
        "test_passed",testEvidence.summary.test_passed, ...
        "test_failed",testEvidence.summary.test_failed, ...
        "test_incomplete",testEvidence.summary.test_incomplete, ...
        "affected_regression_total", ...
            regressionEvidence.summary.test_total, ...
        "affected_regression_passed", ...
            regressionEvidence.summary.test_passed, ...
        "static_check_blocking_findings",sum(staticSummary.finding_count), ...
        "forbidden_execution_pass",true));

    reportResult = rkkt.reporting.generate_stage_b1_report(context.root);
    reportPath = resolve_report_path(reportResult,context.root);
    [reportValid,reportDetails] = rkkt.reporting.validate_stage_b1_report(context.root);
    validation = table(string(context.run_id),"stage_B-1", ...
        reportValid,"PASS if B-1 package and semantics are valid", ...
        string(reportDetails.message), ...
        'VariableNames',{'run_id','report_id','status','threshold', ...
        'message'});
    write_new_table(fullfile(context.reports_dir, ...
        "report_structure_validation.csv"),validation);
    assert(reportValid,"stageB1:ReportInvalid", ...
        "The B-1 Chinese report failed structural/semantic validation.");
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "reports_generated",true, ...
        "report_structure_validated",true, ...
        "report_relative_path",relative_run_path(reportPath,context.root)));

    evidenceHashes = write_evidence_hashes(context.root, ...
        fullfile(context.acceptance_dir,"evidence_hashes.csv"));
    manifest = rkkt.artifacts.finalize_run_manifest(context,"PASS",struct( ...
        "milestone","B-1", ...
        "stage_b1_status","PASS", ...
        "stage_b_complete",false, ...
        "stage_c1_entered",false, ...
        "blocking_acceptance_total",2, ...
        "blocking_acceptance_pass",2, ...
        "not_run_acceptance_ids",["SB-EQ-001","SB-PHY-001"], ...
        "evidence_hashes","acceptance/evidence_hashes.csv", ...
        "evidence_hashes_sha256",rkkt.data.compute_sha256_file( ...
            fullfile(context.acceptance_dir,"evidence_hashes.csv")), ...
        "evidence_file_count",height(evidenceHashes)));
    result.status = string(manifest.status);
    result.manifest = manifest;
    result.acceptance = acceptance;
    result.issues = issues;
    result.checks = checks;
    result.audit = audit;
    result.report_path = string(reportPath);
catch cause
    issue = failure_issue(context,cause);
    try
        rkkt.artifacts.write_table_csv_17g(context.issue_log_path,issue);
    catch
    end
    finalStatus = "FAIL_RETRYABLE";
    if contains(string(cause.identifier),"ExternalPreflight")
        finalStatus = "BLOCKED_EXTERNAL";
    end
    try
        manifest = jsondecode(fileread(context.run_manifest_path));
        if string(manifest.status)=="RUNNING"
            manifest = rkkt.artifacts.finalize_run_manifest(context,finalStatus,struct( ...
                "milestone","B-1", ...
                "stage_b1_status",char(finalStatus), ...
                "stage_b_complete",false, ...
                "stage_c1_entered",false, ...
                "failure_identifier",char(string(cause.identifier)), ...
                "failure_message",char(string(cause.message))));
        end
    catch
        manifest = struct();
    end
    result.status = finalStatus;
    result.manifest = manifest;
    result.issues = issue;
    result.error_identifier = string(cause.identifier);
    result.error_message = string(cause.message);
end
end


function assert_stage_b1_preflight(root)
current = string(fileread(fullfile(root,"CURRENT_STAGE.md")));
assert(~isempty(regexp(current, ...
    "(?m)^\s*-\s*[^A-Za-z0-9_]*stage_id[^A-Za-z0-9_]+stage_B","once")), ...
    "stageB1:StageGate","CURRENT_STAGE must be stage_B.");
assert(~isempty(regexp(current, ...
    "(?m)^\s*-\s*[^A-Za-z0-9_]*status[^A-Za-z0-9_]+READY","once")), ...
    "stageB1:StageGate","CURRENT_STAGE must be READY.");
assert(~isempty(regexp(current, ...
    "(?m)^\s*-\s*[^A-Za-z0-9_]*next_stage_when_passed[^A-Za-z0-9_]+stage_C1","once")), ...
    "stageB1:StageGate","CURRENT_STAGE next stage must be stage_C1.");
config = string(fileread(fullfile(root,"config","stage_B.yaml")));
required = ["stage_id: ""stage_B""","status: ""READY""", ...
    "water_constraints_enabled: true", ...
    "thermal_second_pass_enabled: false", ...
    "annual_scope_enabled: false","parallel_mode: ""off"""];
for k = 1:numel(required)
    assert(contains(config,required(k)),"stageB1:ConfigGate", ...
        "Missing B-1 configuration field: %s",required(k));
end
end

function value = git_short_commit(root)
gitEntry = fullfile(root,".git");
if isfile(gitEntry)
    pointer = strip(string(fileread(gitEntry)));
    assert(startsWith(pointer,"gitdir:"),"stageB1:GitIdentity", ...
        "The .git pointer file is invalid.");
    gitDirectory = strip(extractAfter(pointer,"gitdir:"));
    if ~isfolder(gitDirectory)
        gitDirectory = fullfile(root,gitDirectory);
    end
else
    gitDirectory = gitEntry;
end
head = strip(string(fileread(fullfile(gitDirectory,"HEAD"))));
if startsWith(head,"ref:")
    reference = strip(extractAfter(head,"ref:"));
    referencePath = fullfile(gitDirectory,replace(reference,"/",filesep));
    if isfile(referencePath)
        commit = strip(string(fileread(referencePath)));
    else
        packed = splitlines(string(fileread( ...
            fullfile(gitDirectory,"packed-refs"))));
        matching = packed(endsWith(strip(packed)," "+reference));
        assert(isscalar(matching),"stageB1:GitIdentity", ...
            "The current Git reference is not uniquely resolvable.");
        commit = extractBefore(strip(matching)," ");
    end
else
    commit = head;
end
assert(~isempty(regexp(commit,"^[0-9a-fA-F]{40}$","once")), ...
    "stageB1:GitIdentity","The current Git commit is invalid.");
value = extractBefore(lower(commit),9);
end

function runId = choose_run_id(root,requested,shortCommit)
if strlength(strtrim(requested))>0
    runId = requested;
    assert(~contains(runId,["/","\"]),"stageB1:RunId", ...
        "Requested run id must be a leaf name.");
    assert(~isfolder(fullfile(root,"runs",runId)) && ...
        ~isfile(fullfile(root,"runs",runId)), ...
        "stageB1:RunExists","Requested B-1 run already exists.");
    return
end
timestamp = string(datetime("now","TimeZone","UTC", ...
    "Format","yyyyMMdd_HHmmss"));
base = timestamp+"_stage_B_1_"+shortCommit;
runId = base;
suffix = 1;
while isfolder(fullfile(root,"runs",runId)) || ...
        isfile(fullfile(root,"runs",runId))
    suffix = suffix+1;
    runId = base+"_"+compose("%03d",suffix);
end
end

function value = input_hash_object(hashes)
baseRow = hashes.fileName=="基础参数.xlsx";
seriesRow = hashes.fileName=="输入数据.xlsx";
assert(nnz(baseRow)==1 && nnz(seriesRow)==1,"stageB1:InputHashRows", ...
    "Both controlled input hash rows are required.");
value = struct( ...
    "base_parameters",char(hashes.actualSHA256(baseRow)), ...
    "timeseries",char(hashes.actualSHA256(seriesRow)));
end

function value = input_hash_table(hashes,runId)
n = height(hashes);
value = table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    'VariableNames',{'run_id','file_name','relative_path', ...
    'expected_bytes','actual_bytes','expectedSHA256','actualSHA256', ...
    'status'});
end

function value = make_acceptance(context,audit,checks)
testId = ["SB-DATA-001";"SB-DER-001";"SB-EQ-001";"SB-PHY-001"];
category = ["数据";"导数";"等价";"物理"];
requirement = ["28 day-plant rows";"relative error <= 1e-7"; ...
    "extended model direction equivalence"; ...
    "optimized daily-water physical violation"];
blocking = true(4,1);
status = ["PASS";"PASS";"NOT_RUN";"NOT_RUN"];
actual = [compose("%d day-plant rows",height(audit)); ...
    compose("gradient=%.17g; hessian=%.17g", ...
        max(checks.gradient_relative_error), ...
        max(checks.hessian_relative_error)); ...
    "KKT and recursive direction not executed in B-1"; ...
    "optimization and physical-water audit not executed in B-1"];
evidence = ["diagnostics/water_input_audit.csv"; ...
    "diagnostics/derivative_check.csv";"NOT_RUN";"NOT_RUN"];
value = table(repmat(string(context.run_id),4,1),testId,category, ...
    requirement,blocking,status,actual,evidence, ...
    'VariableNames',{'run_id','test_id','category','requirement', ...
    'blocking','status','actual_value','evidence_path'});
end

function value = empty_issue_log()
value = table(strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end

function value = failure_issue(context,cause)
value = table(string(context.run_id),"B1-EXECUTION","B-1", ...
    "execution",string(cause.message), ...
    "Run directory and partial artifacts were preserved.", ...
    "Inspect the first failed layer and retry without changing contract.", ...
    "OPEN","run_manifest.json", ...
    'VariableNames',{'run_id','issue_id','test_id','layer','symptom', ...
    'evidence_preserved','next_action','status','evidence_path'});
end

function summary = run_static_checks(root,runRoot)
relative = ["src/+rkkt/+workflows/stageB1.m"; ...
    "src/+rkkt/+model/evaluate_stage_b_daily_hydro_water.m"; ...
    "src/+rkkt/+diagnostics/build_stage_b1_water_input_audit.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b1_derivative_checks.m"; ...
    "src/+rkkt/+diagnostics/inspect_stage_b1_environment.m"; ...
    "src/+rkkt/+reporting/generate_stage_b1_report.m"; ...
    "src/+rkkt/+reporting/write_stage_b1_docx.m"; ...
    "src/+rkkt/+reporting/validate_stage_b1_report.m"; ...
    "tests/run_stage_B_1_tests.m"; ...
    "tests/run_stage_B_1_affected_regressions.m"; ...
    "tests/integration/test_stage_b1_data_baseline.m"; ...
    "tests/integration/test_stage_b1_report.m"; ...
    "tests/unit/test_stage_b_daily_hydro_water.m"];
relative = relative(arrayfun(@(x)isfile(fullfile(root, ...
    replace(x,"/",filesep))),relative));
n = numel(relative);
file = relative;
finding_count = zeros(n,1);
status = repmat("PASS",n,1);
details = strings(n,1);
for k = 1:n
    absolute = fullfile(root,replace(relative(k),"/",filesep));
    try
        findings = checkcode(absolute,"-id");
        finding_count(k) = numel(findings);
        if finding_count(k)>0
            status(k) = "FAIL";
            details(k) = strjoin(string({findings.message})," | ");
        else
            details(k) = "0 Code Analyzer findings";
        end
    catch cause
        status(k) = "FAIL";
        details(k) = string(cause.identifier)+": "+string(cause.message);
    end
end
summary = table(file,finding_count,status,details, ...
    repmat(relative_run_path(fullfile(runRoot,"tests"),runRoot),n,1), ...
    'VariableNames',{'file','finding_count','status','details', ...
    'evidence_path'});
end

function reportPath = resolve_report_path(reportResult,runRoot)
if isstruct(reportResult) && isfield(reportResult,"path")
    reportPath = char(string(reportResult.path));
elseif isstruct(reportResult) && isfield(reportResult,"report_path")
    reportPath = char(string(reportResult.report_path));
else
    reportPath = char(string(reportResult));
end
assert(isfile(reportPath),"stageB1:ReportMissing", ...
    "B-1 report generator did not create a DOCX: %s",reportPath);
canonicalReport = string(java.io.File(reportPath).getCanonicalPath());
canonicalRun = string(java.io.File(runRoot).getCanonicalPath());
assert(startsWith(canonicalReport,canonicalRun+filesep), ...
    "stageB1:ReportOutsideRun","Report must be inside the current run.");
end

function value = write_evidence_hashes(runRoot,pathValue)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB1:EvidenceHashExists", ...
    "Refusing to overwrite evidence hash list.");
listing = dir(fullfile(runRoot,"**","*"));
listing = listing(~[listing.isdir]);
relative = strings(0,1);
sha256 = strings(0,1);
bytes = zeros(0,1);
for k = 1:numel(listing)
    absolute = string(fullfile(listing(k).folder,listing(k).name));
    current = relative_run_path(absolute,runRoot);
    if current=="acceptance/evidence_hashes.csv" || ...
            current=="run_manifest.json"
        continue
    end
    relative(end+1,1) = current; %#ok<AGROW>
    sha256(end+1,1) = rkkt.data.compute_sha256_file(absolute); %#ok<AGROW>
    bytes(end+1,1) = double(listing(k).bytes); %#ok<AGROW>
end
[relative,order] = sort(relative);
sha256 = sha256(order);
bytes = bytes(order);
value = table(relative,sha256,bytes, ...
    repmat("PASS",numel(relative),1), ...
    'VariableNames',{'relative_path','sha256','bytes','status'});
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end

function value = relative_run_path(pathValue,root)
pathValue = string(java.io.File(char(pathValue)).getCanonicalPath());
root = string(java.io.File(char(root)).getCanonicalPath());
value = erase(pathValue,root+filesep);
value = replace(value,"\","/");
end

function ensure_directory(pathValue)
if isfolder(pathValue)
    return
end
[created,message] = mkdir(pathValue);
assert(created,"stageB1:Directory", ...
    "Could not create %s: %s",pathValue,message);
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue)&&~isfolder(pathValue), ...
    "stageB1:ArtifactExists","Refusing to overwrite %s",pathValue);
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end
