function result = stageB2CConfigured(settings,options)
%STAGEB2CCONFIGURED Run one configured contiguous Stage B-2C range.

arguments
    settings (1,1) struct
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
    options.ResumeRunDirectory (1,1) string = ""
    options.ExplicitDaySet (1,1) logical = false
    options.DayResponseExecutionMode (1,1) string {mustBeMember( ...
        options.DayResponseExecutionMode,["","serial","parallel_processes"])} = ...
        ""
    options.ParallelWorkerCount (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.JointMicroborderScanEnabled (1,1) logical = false
    options.ActualTestCommand (1,1) string = "RUN_PROJECT.m"
end
workflowTimer = tic;
root = options.ProjectRoot;
if strlength(strip(root))==0, root = settings.project_root; end
root = string(java.io.File(char(root)).getCanonicalPath());
configuredExplicitDaySet = isfield(settings,"explicit_day_set") && ...
    isscalar(settings.explicit_day_set) && ...
    logical(settings.explicit_day_set);
settings.explicit_day_set = configuredExplicitDaySet || ...
    options.ExplicitDaySet;
validate_settings(settings,root);
lightweight = settings.run_output_mode=="lightweight";
executionMode = options.DayResponseExecutionMode;
if strlength(executionMode)==0
    if settings.parallel_enabled
        executionMode = "parallel_processes";
    else
        executionMode = "serial";
    end
end
parallelWorkerCount = options.ParallelWorkerCount;
if executionMode=="parallel_processes" && parallelWorkerCount==0
    parallelWorkerCount = settings.parallel_worker_count;
end
assert((executionMode=="parallel_processes")==settings.parallel_enabled, ...
    "stageB2C:configured:ParallelMode", ...
    "The execution mode must match the resolved RUN_PROJECT setting.");
assert((executionMode=="parallel_processes" && ...
        parallelWorkerCount==settings.parallel_worker_count) || ...
    (executionMode=="serial" && parallelWorkerCount==0), ...
    "stageB2C:configured:ParallelWorkerCount", ...
    "The execution worker count must match the resolved RUN_PROJECT setting.");
runId = options.RunId;
if strlength(strip(runId))==0, runId = settings.run_id; end
resumeDirectory = options.ResumeRunDirectory;
if strlength(strip(resumeDirectory))==0
    resumeDirectory = settings.resume_run_directory;
end

[inputHashes,inputPass] = rkkt.data.verify_input_hashes(root);
assert(inputPass,"stageB2C:configured:InputHash", ...
    "Controlled input hashes do not match their authority values.");
codeSignature = rkkt.artifacts.compute_package_code_signature(root);
[data,dataCache] = rkkt.cache.load_or_build_project_data(root, ...
    Enabled=settings.cache_enabled, ...
    ForceRebuild=settings.force_rebuild_data_cache, ...
    LoadCorrectionPath=enabled_correction_path(settings));
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    root,settings,data);
index = struct();
runtimePackage = struct();
structureCache = unused_structure_cache();
numericalPayloadBuildSeconds = 0;
if settings.audit_mode=="recursive_only"
    [recursiveStructure,structureCache] = ...
        rkkt.cache.load_or_build_stage_b2c_recursive_structure( ...
            root,data,config,Enabled=settings.cache_enabled, ...
            ForceRebuild=settings.force_rebuild_recursive_structure_cache);
    numericalTimer = tic;
    runtimePackage = ...
        rkkt.model.build_stage_b2c_recursive_numerical_payload( ...
            data,recursiveStructure,config);
    numericalPayloadBuildSeconds = toc(numericalTimer);
    modelIndex = runtimePackage;
    indexCache = unused_index_cache();
else
    [index,indexCache] = rkkt.cache.load_or_build_stage_b2c_index( ...
        root,data,config,Enabled=settings.cache_enabled, ...
        ForceRebuild=settings.force_rebuild_index_cache);
    modelIndex = index;
end
[context,~,resumed] = rkkt.artifacts.prepare_stage_b2c_configured_run( ...
    root,settings,config,inputHashes,codeSignature,RunId=runId, ...
    ResumeRunDirectory=resumeDirectory, ...
    LoadCorrectionInfo=data.load_correction, ...
    ActualTestCommand=options.ActualTestCommand);

diagnosticsDir = fullfile(context.root,"diagnostics");
resultsDir = fullfile(context.root,"results");
ensure_directory(diagnosticsDir); ensure_directory(resultsDir);
result = struct("run_id",string(context.run_id), ...
    "run_path",string(context.root),"status","RUNNING", ...
    "settings",settings,"config",config,"data_cache",dataCache, ...
    "index_cache",indexCache,"resumed",resumed, ...
    "recursive_structure_cache",structureCache, ...
    "numerical_payload_build_seconds",numericalPayloadBuildSeconds, ...
    "run_output_mode",settings.run_output_mode, ...
    "convergence_achieved",false,"accepted_iteration_count",0, ...
    "recursive_ipm_seconds",NaN,"report_path","", ...
    "error_identifier","","error_message","","ipm",struct());

try
    preparationTimer = tic;
    poolInfo = rkkt.solver.prepare_stage_b2c_parallel_pool(settings);
    result.parallel_pool = poolInfo;
    if poolInfo.close_after_run
        poolCleanup = onCleanup(@() ...
            rkkt.solver.close_stage_b2c_parallel_pool());
    end
    waterInput = table();
    if ~resumed && ~lightweight
        rkkt.artifacts.write_json_file(fullfile(diagnosticsDir, ...
            "resolved_run_settings.json"),settings);
        rkkt.artifacts.save_mat_artifact(fullfile(diagnosticsDir, ...
            "resolved_runtime_configuration.mat"), ...
            "settings",settings,"config",config);
        environment = rkkt.diagnostics.inspect_stage_b2b_environment();
        parallelRow = environment.check_id=="PARALLEL_EXECUTION";
        environment.expected(parallelRow) = executionMode;
        environment.actual(parallelRow) = executionMode;
        environment.details(parallelRow) = compose( ...
            "pool_action=%s; workers=%d", ...
            poolInfo.action,parallelWorkerCount);
        environment = addvars(environment,repmat(string(context.run_id), ...
            height(environment),1),'Before',1,'NewVariableNames','run_id');
        write_new_table(context.environment_csv_path,environment);
        assert(all(environment.status(logical(environment.blocking))=="PASS"), ...
            "stageB2C:configured:Environment", ...
            "A blocking MATLAB environment check failed.");
        write_new_table(context.input_hashes_csv_path, ...
            input_hash_table(inputHashes,context.run_id));
        waterInput = rkkt.diagnostics.build_stage_b2c_water_input_audit( ...
            data,config,string(context.run_id));
        write_new_table(fullfile(diagnosticsDir,"water_input_audit.csv"), ...
            waterInput);
        assert(height(waterInput)==config.expected_final_water_audit_rows && ...
            all(waterInput.status=="PASS"), ...
            "stageB2C:configured:WaterInput", ...
            "The configured water-input audit failed.");
        if settings.audit_mode=="full_kkt"
            rkkt.artifacts.persist_stage_b2c_index_artifacts(context,index);
        else
            rkkt.artifacts.persist_stage_b2c_recursive_structure_artifacts( ...
                context,recursiveStructure,runtimePackage);
        end
        write_new_table(fullfile(diagnosticsDir,"cache_summary.csv"), ...
            cache_summary(context,dataCache,indexCache,structureCache, ...
                numericalPayloadBuildSeconds));
        write_new_table(fullfile(diagnosticsDir,"dimension_summary.csv"), ...
            dimension_summary(context,modelIndex,config,dataCache,indexCache, ...
                structureCache,numericalPayloadBuildSeconds));
    elseif resumed
        waterInput = readtable(fullfile(diagnosticsDir, ...
            "water_input_audit.csv"),"TextType","string", ...
            "VariableNamingRule","preserve");
    end
    preparationSeconds = toc(preparationTimer)+ ...
        dataCache.load_seconds+dataCache.build_seconds+ ...
        dataCache.write_seconds+preparation_cache_access_seconds( ...
            settings,indexCache,structureCache,numericalPayloadBuildSeconds);
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "data_cache_status",char(dataCache.status), ...
        "data_cache_key",char(dataCache.key), ...
        "load_correction_enabled",data.load_correction.enabled, ...
        "load_correction_sha256",char(data.load_correction.sha256), ...
        "load_correction_row_count",data.load_correction.row_count, ...
        "load_correction_day_count",data.load_correction.day_count, ...
        "load_correction_total_reduction_mwh", ...
            data.load_correction.total_reduction_mwh, ...
        "index_cache_status",char(indexCache.status), ...
        "index_cache_key",char(indexCache.key), ...
        "canonical_index_loaded",canonical_index_loaded( ...
            settings,indexCache), ...
        "canonical_index_load_seconds",canonical_load_seconds( ...
            settings,indexCache), ...
        "canonical_index_built",canonical_index_built( ...
            settings,indexCache), ...
        "recursive_structural_cache_status",char(structureCache.status), ...
        "recursive_structural_cache_key",char(structureCache.key), ...
        "recursive_structural_cache_load_seconds", ...
            structureCache.load_seconds, ...
        "recursive_structural_cache_build_seconds", ...
            structureCache.build_seconds, ...
        "recursive_structural_cache_write_seconds", ...
            structureCache.write_seconds, ...
        "recursive_structural_cache_bytes",structureCache.bytes, ...
        "topology_fingerprint",char(structureCache.topology_fingerprint), ...
        "numerical_payload_build_seconds",numericalPayloadBuildSeconds, ...
        "preparation_seconds",preparationSeconds, ...
        "local_linear_solve_residual_tolerance", ...
            config.local_linear_solve_residual_tolerance, ...
        "recursive_full_kkt_residual_tolerance", ...
            config.recursive_full_kkt_residual_tolerance, ...
        "core_consistency_max_passes", ...
            config.core_consistency_max_passes, ...
        "compensated_core_accumulation", ...
            config.compensated_core_accumulation, ...
        "reduced_symmetry_tolerance", ...
            config.reduced_symmetry_tolerance, ...
        "border_symmetry_tolerance", ...
            config.border_symmetry_tolerance, ...
        "lagrangian_hessian_symmetry_tolerance", ...
            config.lagrangian_hessian_symmetry_tolerance, ...
        "day_response_execution_mode",char(executionMode), ...
        "parallel_worker_count",parallelWorkerCount, ...
        "parallel_requested", ...
            executionMode=="parallel_processes", ...
        "parallel_pool_action",char(poolInfo.action), ...
        "parallel_pool_startup_seconds",poolInfo.startup_seconds, ...
        "joint_microborder_scan_enabled", ...
            options.JointMicroborderScanEnabled, ...
        "solver_code_signature",char(codeSignature)));

    if settings.audit_mode=="full_kkt"
        gate = rkkt.diagnostics.run_stage_b2c_nonzero_hessian_gate( ...
            data,index,config,DiagnosticsDirectory=string(diagnosticsDir));
        assert(gate.passed,"stageB2C:configured:NonzeroHessianGate", ...
            "The seven-day nonzero-water-Hessian gate failed.");
        clear gate
        ipm = rkkt.solver.run_stage_b2c_full_ipm( ...
            data,index,config,context, ...
            IterationLimit=settings.max_iterations, ...
            RequireConvergence=settings.require_convergence);
    else
        ipm = rkkt.solver.run_stage_b2c_365day_serial_ipm( ...
            data,runtimePackage,config,context, ...
            MaxIterations=settings.max_iterations,Resume=resumed, ...
            SolverCodeSignature=codeSignature, ...
            DayResponseExecutionMode=executionMode, ...
            ParallelWorkerCount=parallelWorkerCount, ...
            JointMicroborderScanEnabled= ...
                options.JointMicroborderScanEnabled, ...
            CheckpointEnabled=~lightweight);
    end
    parallelExecuted = false;
    dailyResponseComputeSeconds = NaN;
    if isfield(ipm,"parallel_executed")
        parallelExecuted = logical(ipm.parallel_executed);
    end
    if isfield(ipm,"daily_response_compute_seconds")
        dailyResponseComputeSeconds = ipm.daily_response_compute_seconds;
    end
    pureIpmSeconds = sum(ipm.timing_history.total_seconds);
    rkkt.artifacts.write_json_file(fullfile(diagnosticsDir, ...
        "final_metrics.json"),ipm.final_metrics);
    if settings.audit_mode=="recursive_only"
        physicalArrays = rkkt.model.recover_stage_b2c_runtime_physical_arrays( ...
            ipm.final_state.xi,zeros(size(ipm.final_state.xi)), ...
            runtimePackage,data);
    else
        physicalArrays = rkkt.model.recover_stage_a_physical_arrays( ...
            ipm.final_state.xi,zeros(size(ipm.final_state.xi)),index,data);
    end
    [capacity,hourly,daily] = rkkt.model.build_stage_b2c_physical_results( ...
        string(context.run_id),ipm,modelIndex,physicalArrays);
    write_replace_table(fullfile(resultsDir,"capacity_results.csv"),capacity);
    write_replace_table(fullfile(resultsDir, ...
        "hourly_dispatch_results.csv"),hourly);
    write_replace_table(fullfile(resultsDir, ...
        "daily_generation_summary.csv"),daily);
    rkkt.artifacts.save_mat_artifact(fullfile(resultsDir, ...
        "final_state_and_physical.mat"),"final_state",ipm.final_state, ...
        "physical",physicalArrays,"final_metrics",ipm.final_metrics);
    if ~lightweight
        rkkt.artifacts.persist_stage_b2c_final_matrix_artifacts( ...
            context,ipm,settings.audit_mode);
    end

    physical = struct("passed",false,"maximum_water_violation",NaN);
    if ipm.convergence_achieved
        physical = rkkt.diagnostics.evaluate_stage_b2c_physical_audit( ...
            ipm,modelIndex,data,config);
        write_replace_table(fullfile(diagnosticsDir, ...
            "final_daily_water_constraint_audit.csv"),physical.water);
        write_replace_table(fullfile(context.acceptance_dir, ...
            "physical_audit.csv"),physical.stage_a);
    end
    if lightweight
        acceptance = make_lightweight_acceptance( ...
            context,ipm,physical,config,settings);
    else
        acceptance = make_acceptance(context,ipm,physical,waterInput, ...
            modelIndex,config,settings);
    end
    write_replace_table(context.acceptance_results_path,acceptance);
    terminalStatus = "FAIL_RETRYABLE";
    if all(acceptance.status=="PASS"), terminalStatus = "PASS"; end
    if ~lightweight
        write_replace_table(context.issue_log_path, ...
            make_issue_log(context,terminalStatus,ipm,settings));
        write_replace_table(context.decision_log_path, ...
            make_decision(context,terminalStatus,ipm,settings));
        persist_runtime_test_evidence(context,acceptance);
    end
    worstResidual = worst_recursive_residual(ipm,settings.audit_mode);
    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "milestone_status",char(terminalStatus), ...
        "experiment_completed",true, ...
        "experiment_passed",terminalStatus=="PASS", ...
        "b2c_serial_solver_terminal_state",char(ipm.run_terminal_state), ...
        "convergence_achieved",ipm.convergence_achieved, ...
        "accepted_iteration_count",ipm.accepted_iteration_count, ...
        "recursive_ipm_seconds",pureIpmSeconds, ...
        "recursive_ipm_compute_seconds",pureIpmSeconds, ...
        "iteration_loop_wall_seconds",solver_wall_seconds(ipm), ...
        "run_output_mode",char(settings.run_output_mode), ...
        "checkpoint_after_each_accepted_update",~lightweight, ...
        "resume_supported",~lightweight && ...
            settings.audit_mode=="recursive_only", ...
        "full_kkt_assembled",settings.audit_mode=="full_kkt", ...
        "full_kkt_solved",settings.audit_mode=="full_kkt", ...
        "full_kkt_audit_executed",settings.audit_mode=="full_kkt", ...
        "parallel_executed",parallelExecuted, ...
        "day_response_execution_mode",char(executionMode), ...
        "parallel_worker_count",parallelWorkerCount, ...
        "parallel_pool_auto_resize",settings.parallel_pool_auto_resize, ...
        "parallel_pool_keep_alive",settings.parallel_pool_keep_alive, ...
        "parallel_pool_action",char(poolInfo.action), ...
        "parallel_pool_startup_seconds",poolInfo.startup_seconds, ...
        "joint_microborder_scan_enabled", ...
            options.JointMicroborderScanEnabled, ...
        "daily_response_compute_seconds",dailyResponseComputeSeconds, ...
        "recursive_final_kkt_relative_residual",worstResidual, ...
        "final_primal_equality_inf",ipm.final_metrics.primal_equality_inf, ...
        "final_primal_inequality_inf", ...
            ipm.final_metrics.primal_inequality_inf, ...
        "final_dual_scaled_inf",ipm.final_metrics.dual_scaled_inf, ...
        "final_mean_lz_scaled",ipm.final_metrics.mean_lz_scaled, ...
        "final_physical_audit_executed",ipm.convergence_achieved, ...
        "final_physical_audit_passed", ...
            ipm.convergence_achieved && physical.passed));

    if lightweight
        manifestUpdates = struct("reports_generated",false, ...
            "matrix_artifacts_generated",false, ...
            "iteration_checkpoints_generated",false, ...
            "iteration_count",ipm.accepted_iteration_count, ...
            "elapsed_seconds",solver_wall_seconds(ipm), ...
            "workflow_wall_seconds",toc(workflowTimer));
        result.report_path = "";
    else
        report = rkkt.reporting.generate_stage_b2c_configured_report( ...
            context.root);
        [reportValid,reportDetails] = ...
            rkkt.reporting.validate_docx_package(report.path);
        reportValidation = table(string(context.run_id),string(report.path), ...
            reportValid,conditional_status(reportValid), ...
            strjoin(string(reportDetails.errors)," | "), ...
            'VariableNames',{'run_id','path','package_valid','status','details'});
        write_replace_table(fullfile(context.reports_dir, ...
            "report_structure_validation.csv"),reportValidation);
        assert(reportValid,"stageB2C:configured:Report", ...
            "The configured Chinese report failed DOCX validation.");
        manifestUpdates = struct("reports_generated",true, ...
            "report_structure_validated",true, ...
            "report_relative_path",char(erase(string(report.path), ...
                string(context.root)+filesep)), ...
            "report_sha256",char(rkkt.data.compute_sha256_file(report.path)), ...
            "iteration_count",ipm.accepted_iteration_count, ...
            "elapsed_seconds",solver_wall_seconds(ipm), ...
            "workflow_wall_seconds",toc(workflowTimer));
        result.report_path = string(report.path);
    end
    result.convergence_achieved = ipm.convergence_achieved;
    result.accepted_iteration_count = ipm.accepted_iteration_count;
    result.recursive_ipm_seconds = pureIpmSeconds;
    result.workflow_wall_seconds = toc(workflowTimer);
    result.ipm = ipm;
catch cause
    terminalStatus = "FAIL_RETRYABLE";
    if contains(string(cause.identifier),["Environment","InputHash"])
        terminalStatus = "BLOCKED_EXTERNAL";
    elseif contains(string(cause.identifier),"ModelDecision")
        terminalStatus = "NEEDS_MODEL_DECISION";
    end
    preserve_failure_artifacts(context,cause,terminalStatus);
    manifestUpdates = struct("milestone_status",char(terminalStatus), ...
        "experiment_completed",false,"experiment_passed",false, ...
        "failure_identifier",char(string(cause.identifier)), ...
        "failure_message",char(string(cause.message)));
    result.error_identifier = string(cause.identifier);
    result.error_message = string(cause.message);
    result.ipm = partial_ipm(context);
end
manifest = rkkt.artifacts.finalize_run_manifest( ...
    context,terminalStatus,manifestUpdates);
rkkt.artifacts.update_run_index(context,manifest);
result.status = string(manifest.status);
end

function validate_settings(settings,root)
required = ["stage_id","milestone_id","day_start","day_end","days", ...
    "day_scope","excluded_days", ...
    "max_iterations","require_convergence","audit_mode", ...
    "run_output_mode", ...
    "cache_enabled","force_rebuild_data_cache", ...
    "force_rebuild_index_cache", ...
    "force_rebuild_recursive_structure_cache", ...
    "load_correction_enabled","load_correction_path", ...
    "run_id","resume_run_directory", ...
    "parallel_enabled","parallel_worker_count", ...
    "parallel_pool_auto_resize","parallel_pool_keep_alive", ...
    "config_path","project_root"];
assert(all(isfield(settings,cellstr(required))) && ...
    settings.stage_id=="stage_B" && settings.milestone_id=="B-2C" && ...
    isfield(settings,"explicit_day_set") && ...
    isscalar(settings.explicit_day_set) && ...
    (logical(settings.explicit_day_set) || ...
        isequal(settings.days,settings.day_start:settings.day_end)) && ...
    isequal(settings.days,unique(settings.days,"stable")) && ...
    issorted(settings.days,"strictascend") && ...
    settings.day_start>=1 && settings.day_end<=365 && ...
    settings.max_iterations>=1 && ...
    settings.max_iterations==fix(settings.max_iterations) && ...
    ismember(settings.audit_mode,["full_kkt","recursive_only"]) && ...
    ismember(settings.run_output_mode,["lightweight","full_evidence"]), ...
    "stageB2C:configured:Settings", ...
    "The configured Stage B-2C day-set request is invalid.");
assert(settings.audit_mode~="full_kkt" || numel(settings.days)==7, ...
    "stageB2C:configured:FullKktScope", ...
    "full_kkt audit is allowed only for exactly seven contiguous days.");
assert(settings.audit_mode=="recursive_only" || ...
    settings.run_output_mode=="full_evidence", ...
    "stageB2C:configured:LightweightRecursiveOnly", ...
    "Lightweight output is available only for recursive-only runs.");
assert(strlength(settings.resume_run_directory)==0 || ...
    settings.run_output_mode=="full_evidence", ...
    "stageB2C:configured:LightweightResume", ...
    "Lightweight output does not support checkpoint resume.");
if settings.day_scope=="screened_307"
    assert(settings.explicit_day_set && settings.day_start==1 && ...
        settings.day_end==365 && numel(settings.days)==307 && ...
        numel(settings.excluded_days)==58, ...
        "stageB2C:configured:Screened307", ...
        "The screened_307 preset does not match its frozen annual scope.");
end
assert(isfile(settings.config_path) && ...
    string(java.io.File(char(settings.project_root)).getCanonicalPath())==root, ...
    "stageB2C:configured:SettingsPath", ...
    "The configured project or effective configuration path is invalid.");
end

function value = enabled_correction_path(settings)
if settings.load_correction_enabled
    value = settings.load_correction_path;
else
    value = "";
end
end

function value = partial_ipm(context)
value = struct();
pathValue = fullfile(context.checkpoints_dir,"checkpoint_manifest.csv");
if ~isfile(pathValue), return; end
manifest = readtable(pathValue,"TextType","string", ...
    "VariableNamingRule","preserve");
if isempty(manifest), return; end
revision = double(manifest.iteration(end));
try
    [checkpoint,~] = rkkt.artifacts.load_stage_b2c_checkpoint( ...
        context,revision);
    value = struct("run_terminal_state","NUMERICAL_FAILURE", ...
        "accepted_iteration_count",revision, ...
        "final_state",checkpoint.state);
catch
    value = struct("run_terminal_state","NUMERICAL_FAILURE", ...
        "accepted_iteration_count",revision);
end
end

function value = cache_summary( ...
        context,dataInfo,indexInfo,structureInfo,numericalSeconds)
cache_type = ["annual_data";"canonical_index"; ...
    "recursive_structure";"numerical_payload"];
enabled = [dataInfo.enabled;indexInfo.enabled;structureInfo.enabled;false];
force_rebuild = [dataInfo.force_rebuild;indexInfo.force_rebuild; ...
    structureInfo.force_rebuild;false];
hit = [dataInfo.hit;indexInfo.hit;structureInfo.hit;false];
status = [string(dataInfo.status);string(indexInfo.status); ...
    string(structureInfo.status);"REFRESHED"];
key = [dataInfo.key;indexInfo.key;structureInfo.key;""];
path = [dataInfo.path;indexInfo.path;structureInfo.path;""];
load_seconds = [dataInfo.load_seconds;indexInfo.load_seconds; ...
    structureInfo.load_seconds;0];
build_seconds = [dataInfo.build_seconds;indexInfo.build_seconds; ...
    structureInfo.build_seconds;numericalSeconds];
write_seconds = [dataInfo.write_seconds;indexInfo.write_seconds; ...
    structureInfo.write_seconds;0];
value = table(repmat(string(context.run_id),4,1),cache_type,enabled, ...
    force_rebuild,hit,status,key,path,load_seconds,build_seconds, ...
    write_seconds,'VariableNames',{'run_id','cache_type','enabled', ...
    'force_rebuild','hit','status','key','path','load_seconds', ...
    'build_seconds','write_seconds'});
end

function value = dimension_summary( ...
        context,modelIndex,config,dataCache,indexCache,structureCache, ...
        numericalPayloadBuildSeconds)
counts = model_counts(modelIndex);
metric = ["days";"hours_per_day";"primal_variables";"equalities"; ...
    "base_inequalities";"water_inequalities";"total_inequalities"; ...
    "reconstructed_full_kkt_dimension";"daily_joint_block_count"; ...
    "base_global_core_dimension";"fixed_zero_count"; ...
    "data_cache_access_seconds";"index_cache_access_seconds"; ...
    "recursive_structure_cache_access_seconds"; ...
    "numerical_payload_build_seconds"];
actual_value = [numel(config.days);numel(config.hours); ...
    counts.variables;counts.equalities; ...
    config.expected_stage_a_inequality_dimension; ...
    counts.water_inequalities;counts.inequalities; ...
    counts.full_kkt_dimension;numel(config.days); ...
    config.expected_global_core_dimension;counts.fixed_zero; ...
    dataCache.load_seconds+dataCache.build_seconds+dataCache.write_seconds; ...
    indexCache.load_seconds+indexCache.build_seconds+indexCache.write_seconds; ...
    structureCache.load_seconds+structureCache.build_seconds+ ...
        structureCache.write_seconds; ...
    numericalPayloadBuildSeconds];
value = table(repmat(string(context.run_id),numel(metric),1), ...
    metric,actual_value,'VariableNames',{'run_id','metric','actual_value'});
end

function value = unused_structure_cache()
value = struct("cache_type","recursive_structure", ...
    "enabled",false,"force_rebuild",false,"hit",false, ...
    "status","NOT_USED_FULL_KKT","key","","path","", ...
    "load_seconds",0,"build_seconds",0,"write_seconds",0,"bytes",0, ...
    "topology_fingerprint","", ...
    "canonical_index_loaded",false,"canonical_index_load_seconds",0, ...
    "canonical_index_built",false,"canonical_index_build_seconds",0);
end

function value = unused_index_cache()
value = struct("cache_type","canonical_index", ...
    "enabled",false,"force_rebuild",false,"hit",false, ...
    "status","NOT_ACCESSED","key","","path","", ...
    "load_seconds",0,"build_seconds",0,"write_seconds",0);
end

function value = canonical_index_loaded(settings,indexInfo)
value = settings.audit_mode=="full_kkt" && indexInfo.status~="NOT_ACCESSED";
end

function value = canonical_load_seconds(settings,indexInfo)
if settings.audit_mode=="recursive_only"
    value = 0;
else
    value = indexInfo.load_seconds;
end
end

function value = canonical_index_built(settings,indexInfo)
value = settings.audit_mode=="full_kkt" && indexInfo.status=="BUILT";
end

function value = preparation_cache_access_seconds( ...
        settings,indexInfo,structureInfo,numericalPayloadBuildSeconds)
if settings.audit_mode=="recursive_only"
    value = structureInfo.load_seconds+structureInfo.build_seconds+ ...
        structureInfo.write_seconds+numericalPayloadBuildSeconds;
else
    value = indexInfo.load_seconds+indexInfo.build_seconds+ ...
        indexInfo.write_seconds;
end
end

function counts = model_counts(modelIndex)
if isfield(modelIndex,"version") && ismember(string(modelIndex.version),[ ...
        "stage-B2C-recursive-runtime-package-v1.0", ...
        "stage-B2C-recursive-numerical-payload-v1.0"])
    counts = modelIndex.counts;
else
    counts = modelIndex.counts;
    counts.fixed_zero = height(modelIndex.fixed_zero_map);
    if ~isfield(counts,"base_inequalities")
        counts.base_inequalities = counts.inequalities-counts.water_inequalities;
    end
end
end

function value = make_acceptance(context,ipm,physical,waterInput,index, ...
        config,settings)
counts = model_counts(index);
accepted = ipm.accepted_iteration_count;
recursiveResidual = worst_recursive_residual(ipm,settings.audit_mode);
routePass = accepted>0 && recursiveResidual<= ...
    config.recursive_full_kkt_residual_tolerance;
if settings.audit_mode=="full_kkt"
    routePass = routePass && ipm.execution_audit.direction_audits_pass && ...
        ipm.execution_audit.one_full_kkt_audit_per_accepted_iteration;
    factors = ipm.daily_joint_factorization_history;
    correction = ipm.water_slack_second_order_correction_history;
    correctionPass = height(correction)== ...
        accepted*config.expected_water_inequality_count && ...
        all(correction.strictly_positive);
    fixedPass = all(ipm.iteration_history.fixed_zero_count== ...
        config.expected_stage_a_fixed_zero_count) && ...
        all(ipm.iteration_history.fixed_zero_exact);
else
    routePass = routePass && isfield(ipm,"parallel_executed") && ...
        logical(ipm.parallel_executed)==logical(settings.parallel_enabled);
    factors = ipm.factorization_history;
    correction = ipm.water_correction_history;
    correctionPass = height(correction)== ...
        accepted*config.expected_water_inequality_count && ...
        all(correction.strictly_positive);
    fixedPass = all(ipm.iteration_history.fixed_zero_count== ...
        config.expected_stage_a_fixed_zero_count) && ...
        all(ipm.iteration_history.fixed_zero_exact);
end

factorPass = height(factors)==accepted*(numel(config.days)+1) && ...
    all(factors.factorization_count==1) && ...
    all(~factors.blocking_warning_present) && all(factors.solution_finite);
convergencePass = ~settings.require_convergence || ipm.convergence_achieved;
physicalPass = ~ipm.convergence_achieved || physical.passed;
test_id = ["RUN-DATA";"RUN-INDEX";"RUN-ROUTE";"RUN-FACTORS"; ...
    "RUN-WATER-CORRECTION";"RUN-FIXED-ZERO";"RUN-CONVERGENCE"; ...
    "RUN-PHYSICAL"];
requirement = [compose("%d water-input rows pass", ...
        config.expected_final_water_audit_rows); ...
        "dimensions match the selected day set"; ...
    "configured audit/parallel route and reconstructed KKT residual pass"; ...
    compose("%d daily factors plus one 16-D base or confirmed 17-D micro-border core per iteration", ...
        numel(config.days)); ...
    compose("%d exact water-slack corrections per iteration", ...
        config.expected_water_inequality_count); ...
    compose("%d removed renewable entries remain exact zero", ...
        config.expected_stage_a_fixed_zero_count); ...
    conditional_text(settings.require_convergence, ...
        "four stopping metrics <= 1e-6","bounded run completed"); ...
    "if converged, final water and Stage-A physical audit passes"];
    actual_value = [string(height(waterInput))+" rows"; ...
    compose("%d/%d/%d; reconstructed=%d",counts.variables, ...
        counts.equalities,counts.inequalities, ...
        counts.full_kkt_dimension); ...
    compose("mode=%s; parallel=%s; worst residual=%.17g", ...
        settings.audit_mode,string(settings.parallel_enabled), ...
        recursiveResidual); ...
    string(height(factors))+" factor records; cores="+ ...
        strjoin(unique(factors.object_type( ...
        factors.object_type~="daily_joint")),"|"); ...
    string(height(correction))+" correction records"; ...
    string(config.expected_stage_a_fixed_zero_count)+" exact zeros"; ...
    compose("converged=%s; iterations=%d", ...
        string(ipm.convergence_achieved),accepted); ...
    conditional_text(ipm.convergence_achieved, ...
        compose("passed=%s; max water violation=%.17g", ...
            string(physical.passed),physical.maximum_water_violation), ...
        "not executed before convergence")];
dimensionPass = counts.variables== ...
    config.expected_stage_a_primal_dimension && ...
    counts.equalities==config.expected_stage_a_equality_dimension && ...
    counts.inequalities==config.expected_stage_a_inequality_dimension+ ...
        config.expected_water_inequality_count && ...
    counts.full_kkt_dimension==config.expected_full_kkt_dimension;
passed = [height(waterInput)==config.expected_final_water_audit_rows && ...
        all(waterInput.status=="PASS");dimensionPass;routePass;factorPass; ...
        correctionPass;fixedPass;convergencePass;physicalPass];
status = repmat("FAIL",numel(test_id),1); status(passed) = "PASS";
value = table(repmat(string(context.run_id),numel(test_id),1), ...
    test_id,requirement,actual_value,true(numel(test_id),1),status, ...
    'VariableNames',{'run_id','test_id','requirement','actual_value', ...
    'blocking','status'});
end

function value = make_lightweight_acceptance( ...
        context,ipm,physical,config,settings)
recursiveResidual = worst_recursive_residual(ipm,settings.audit_mode);
convergencePass = ~settings.require_convergence || ipm.convergence_achieved;
kktPass = isfinite(recursiveResidual) && recursiveResidual<= ...
    config.recursive_full_kkt_residual_tolerance;
physicalPass = ipm.convergence_achieved && physical.passed;
test_id = ["LIGHT-CONVERGENCE";"LIGHT-RECONSTRUCTED-KKT"; ...
    "LIGHT-FINAL-PHYSICAL"];
requirement = ["configured stopping metrics pass"; ...
    compose("all reconstructed KKT relative residuals <= %.17g", ...
        config.recursive_full_kkt_residual_tolerance); ...
    "final Stage-A and daily water physical audit passes"];
actual_value = [compose("converged=%s; iterations=%d", ...
        string(ipm.convergence_achieved),ipm.accepted_iteration_count); ...
    compose("worst residual=%.17g",recursiveResidual); ...
    compose("passed=%s; max water violation=%.17g", ...
        string(physicalPass),physical.maximum_water_violation)];
passed = [convergencePass;kktPass;physicalPass];
status = repmat("FAIL",numel(test_id),1);
status(passed) = "PASS";
value = table(repmat(string(context.run_id),numel(test_id),1), ...
    test_id,requirement,actual_value,true(numel(test_id),1),status, ...
    'VariableNames',{'run_id','test_id','requirement','actual_value', ...
    'blocking','status'});
end

function value = worst_recursive_residual(ipm,auditMode)
value = NaN;
if auditMode=="full_kkt" && ~isempty(ipm.direction_audit_history)
    value = max(ipm.direction_audit_history. ...
        recursive_full_kkt_relative_residual);
elseif auditMode=="recursive_only" && ~isempty(ipm.iteration_history)
    value = max(ipm.iteration_history. ...
        recursive_final_kkt_relative_residual);
end
end

function value = solver_wall_seconds(ipm)
if isfield(ipm,"elapsed_seconds"), value = ipm.elapsed_seconds;
else, value = ipm.solver_seconds; end
end

function value = make_issue_log(context,status,ipm,settings)
if status=="PASS"
    value = table(strings(0,1),strings(0,1),strings(0,1), ...
        strings(0,1),strings(0,1),strings(0,1), ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    return
end
description = "The configured day-set run did not pass all checks.";
if settings.require_convergence && ~ipm.convergence_achieved
    description = "The four stopping metrics did not all pass within the iteration limit.";
end
value = table(string(context.run_id),"CONFIGURED_RANGE","BLOCKING", ...
    status,description,"Inspect iteration and factor histories.", ...
    'VariableNames',{'run_id','issue_id','severity','status', ...
    'description','next_action'});
end

function value = make_decision(context,status,ipm,settings)
conclusion = compose( ...
    "Configured %d-day set inside day %d-%d completed; convergence=%s.", ...
    numel(settings.days),settings.day_start,settings.day_end, ...
    string(ipm.convergence_achieved));
value = table(string(context.run_id),"B-2C-CONFIGURED-RANGE",status, ...
    conclusion,"Review configured run artifacts.", ...
    settings.audit_mode=="full_kkt",false,false, ...
    'VariableNames',{'run_id','milestone','status','conclusion', ...
    'next_action','full_kkt_audit_executed','formal_stage_changed', ...
    'stage_c1_entered'});
end

function persist_runtime_test_evidence(context,acceptance)
inventory = table("B2C-CONFIGURED-RUNTIME", ...
    "src/+rkkt/+workflows/stageB2CConfigured.m", ...
    "configured range, cache, route, water correction and convergence", ...
    'VariableNames',{'test_id','test_file','purpose'});
write_replace_table(context.test_inventory_path,inventory);
results = acceptance(:,["run_id","test_id","status"]);
results.passed = results.status=="PASS";
write_replace_table(context.test_results_csv_path,results);
summary = struct("test_total",height(results), ...
    "test_passed",nnz(results.passed),"test_failed",nnz(~results.passed), ...
    "all_pass",all(results.passed));
rkkt.artifacts.write_json_file(context.test_summary_path,summary);
rkkt.artifacts.write_text_utf8(context.test_command_path, ...
    "RUN_PROJECT.m (configured runtime evidence)");
end

function preserve_failure_artifacts(context,cause,status)
if ~isfile(context.issue_log_path)
    issue = table(string(context.run_id),"WORKFLOW_FAILURE","BLOCKING", ...
        status,string(cause.identifier)+": "+string(cause.message), ...
        "Repair the first failed layer and create a new unique run.", ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    rkkt.artifacts.write_table_csv_17g_atomic(context.issue_log_path,issue);
end
if ~isfile(context.acceptance_results_path)
    acceptance = table(string(context.run_id),"workflow_completed", ...
        "no exception",string(cause.identifier),"FAIL", ...
        'VariableNames',{'run_id','test_id','requirement', ...
        'actual_value','status'});
    rkkt.artifacts.write_table_csv_17g_atomic( ...
        context.acceptance_results_path,acceptance);
end
end

function value = input_hash_table(hashes,runId)
n = height(hashes);
value = table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status'});
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message] = mkdir(pathValue);
assert(created,"stageB2C:configured:Directory","%s",message);
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue) && ~isfolder(pathValue), ...
    "stageB2C:configured:ArtifactExists", ...
    "Refusing to overwrite %s.",pathValue);
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end

function write_replace_table(pathValue,value)
rkkt.artifacts.write_table_csv_17g_atomic(pathValue,value);
end

function value = conditional_status(passed)
if passed, value = "PASS"; else, value = "FAIL"; end
end

function value = conditional_text(condition,whenTrue,whenFalse)
if condition, value = string(whenTrue); else, value = string(whenFalse); end
end
