function result = stageB2C30DayExperiment(options)
%STAGEB2C30DAYEXPERIMENT Run the day-1-to-30 recursive-only IPM experiment.

arguments
    options.ProjectRoot (1,1) string = ""
    options.RunId (1,1) string = ""
    options.MaxIterations (1,1) double {mustBeInteger,mustBePositive} = 100
    options.RequireConvergence (1,1) logical = true
end

root = options.ProjectRoot;
if strlength(strip(root))==0
    root = rkkt.projectRoot();
end
root = string(java.io.File(char(root)).getCanonicalPath());
config = rkkt.model.load_stage_b2c_configuration( ...
    root,Profile="experimental_30_day");
[inputHashes,inputPass] = rkkt.data.verify_input_hashes(root);
assert(inputPass,"stageB2C:30day:InputHash", ...
    "Controlled input hashes do not match their authority values.");

mode = "convergence_run";
if ~options.RequireConvergence
    mode = "bounded_smoke_run";
end
metadata = struct( ...
    "run_purpose",char(config.run_purpose), ...
    "milestone","B-2C-30-DAY-EXPERIMENT", ...
    "parent_run_id",char(config.parent_run_id), ...
    "actual_test_command","rkkt.workflows.stageB2C30DayExperiment", ...
    "experiment_mode",char(mode), ...
    "optimization_executed",true,"a1_solver_executed",false, ...
    "full_ipm_executed",true,"convergence_evaluated",true, ...
    "convergence_required",options.RequireConvergence, ...
    "convergence_achieved",false, ...
    "time_scope","days_1_to_30_full_24_hours", ...
    "full_kkt_role",char(config.full_kkt_role), ...
    "full_kkt_assembled",false,"full_kkt_solved",false, ...
    "full_kkt_audit_executed",false, ...
    "recursive_direction_executed",true, ...
    "recursive_direction_is_formal_for_experiment",true, ...
    "reconstructed_kkt_residual_gate_enabled",true, ...
    "recursive_refinement_max_passes", ...
        config.recursive_refinement_max_passes, ...
    "water_slack_second_order_correction_enabled",true, ...
    "water_slack_second_order_correction_scope_count", ...
        config.expected_water_inequality_count, ...
    "no_full_direction_fallback",true, ...
    "parallel_executed",false,"annual_scope_executed",false, ...
    "thermal_second_pass_executed",false, ...
    "stage_c1_implemented",false,"stage_c1_entered",false, ...
    "formal_stage_b_acceptance_unchanged",true, ...
    "expected_primal_dimension",config.expected_stage_a_primal_dimension, ...
    "expected_equality_dimension", ...
        config.expected_stage_a_equality_dimension, ...
    "expected_inequality_dimension", ...
        config.expected_stage_a_inequality_dimension+ ...
        config.expected_water_inequality_count, ...
    "expected_reconstructed_full_kkt_dimension", ...
        config.expected_full_kkt_dimension, ...
    "milestone_status","RUNNING");
context = rkkt.artifacts.create_run_context(root,"stage_B", ...
    "RunId",options.RunId,"ModelContractVersion","v1.0", ...
    "InputHashes",input_hash_object(inputHashes), ...
    "EffectiveConfigPath",fullfile(root,"config", ...
        "stage_B_2C_30_day_experiment.yaml"), ...
    "ManifestMetadata",metadata);
diagnosticsDir = fullfile(context.root,"diagnostics");
resultsDir = fullfile(context.root,"results");
ensure_directory(diagnosticsDir);
ensure_directory(resultsDir);

result = struct("run_id",string(context.run_id), ...
    "run_path",string(context.root),"status","RUNNING", ...
    "convergence_achieved",false,"accepted_iteration_count",0, ...
    "recursive_ipm_seconds",NaN,"report_path","", ...
    "error_identifier","","error_message","");

try
    preparationTimer = tic;
    environment = rkkt.diagnostics.inspect_stage_b2b_environment();
    environment = addvars(environment,repmat(string(context.run_id), ...
        height(environment),1),'Before',1,'NewVariableNames','run_id');
    write_new_table(context.environment_csv_path,environment);
    assert(all(environment.status(logical(environment.blocking))=="PASS"), ...
        "stageB2C:30day:Environment", ...
        "A blocking MATLAB environment check failed.");
    write_new_table(context.input_hashes_csv_path, ...
        input_hash_table(inputHashes,context.run_id));

    data = rkkt.data.load_project_data(root);
    waterInput = build_water_input_audit(data,config,context.run_id);
    write_new_table(fullfile(diagnosticsDir,"water_input_audit.csv"), ...
        waterInput);
    assert(height(waterInput)==config.expected_final_water_audit_rows && ...
        all(waterInput.status=="PASS"), ...
        "stageB2C:30day:WaterInput", ...
        "The configured 30-day water-input audit failed.");

    indexTimer = tic;
    index = rkkt.indexing.build_stage_b2c_index( ...
        data,config,"RunId",string(context.run_id));
    indexSeconds = toc(indexTimer);
    persist_index_artifacts(context,index);
    preparationSeconds = toc(preparationTimer);
    dimensionSummary = build_dimension_summary( ...
        context,index,config,indexSeconds,preparationSeconds);
    write_new_table(fullfile(diagnosticsDir,"dimension_summary.csv"), ...
        dimensionSummary);

    ipm = rkkt.solver.run_stage_b2c_30day_ipm( ...
        data,index,config,context,MaxIterations=options.MaxIterations);
    pureIpmComputeSeconds = sum(ipm.timing_history.total_seconds);
    iterationEvidenceSeconds = ipm.elapsed_seconds-pureIpmComputeSeconds;
    rkkt.artifacts.write_json_file(fullfile(diagnosticsDir, ...
        "final_metrics.json"),ipm.final_metrics);

    physicalArrays = rkkt.model.recover_stage_a_physical_arrays( ...
        ipm.final_state.xi,zeros(size(ipm.final_state.xi)),index,data);
    [capacityResults,hourlyResults,dailyResults] = ...
        build_physical_results(context,ipm,index,physicalArrays);
    write_new_table(fullfile(resultsDir,"capacity_results.csv"), ...
        capacityResults);
    write_new_table(fullfile(resultsDir,"hourly_dispatch_results.csv"), ...
        hourlyResults);
    write_new_table(fullfile(resultsDir,"daily_generation_summary.csv"), ...
        dailyResults);
    rkkt.artifacts.save_mat_artifact(fullfile(resultsDir, ...
        "final_state_and_physical.mat"), ...
        "final_state",ipm.final_state,"physical",physicalArrays, ...
        "final_metrics",ipm.final_metrics);
    persist_final_matrix_artifacts(context,ipm);

    physical = struct("passed",false,"maximum_water_violation",NaN);
    if ipm.convergence_achieved
        physical = rkkt.diagnostics.evaluate_stage_b2c_physical_audit( ...
            ipm,index,data,config);
        write_new_table(fullfile(diagnosticsDir, ...
            "final_daily_water_constraint_audit.csv"),physical.water);
        write_new_table(fullfile(context.acceptance_dir, ...
            "physical_audit.csv"),physical.stage_a);
    end

    acceptance = make_acceptance(context,ipm,physical,waterInput, ...
        index,config,options.RequireConvergence);
    write_new_table(context.acceptance_results_path,acceptance);
    experimentPassed = all(acceptance.status=="PASS");
    terminalStatus = "FAIL_RETRYABLE";
    if experimentPassed
        terminalStatus = "PASS";
    end
    issues = make_issue_log(context,terminalStatus,ipm, ...
        options.RequireConvergence);
    write_new_table(context.issue_log_path,issues);
    decision = make_decision(context,terminalStatus,ipm, ...
        options.RequireConvergence);
    write_new_table(context.decision_log_path,decision);
    persist_runtime_test_evidence(context,acceptance);

    rkkt.artifacts.update_running_run_manifest(context,struct( ...
        "milestone_status",char(terminalStatus), ...
        "experiment_completed",true, ...
        "experiment_passed",experimentPassed, ...
        "convergence_achieved",ipm.convergence_achieved, ...
        "accepted_iteration_count",ipm.accepted_iteration_count, ...
        "recursive_ipm_seconds",pureIpmComputeSeconds, ...
        "recursive_ipm_compute_seconds",pureIpmComputeSeconds, ...
        "iteration_loop_wall_seconds",ipm.elapsed_seconds, ...
        "iteration_evidence_io_seconds",iterationEvidenceSeconds, ...
        "index_build_seconds",indexSeconds, ...
        "preparation_seconds",preparationSeconds, ...
        "full_kkt_assembled",false,"full_kkt_solved",false, ...
        "full_kkt_audit_executed",false, ...
        "recursive_final_kkt_relative_residual", ...
            max(ipm.iteration_history. ...
                recursive_final_kkt_relative_residual), ...
        "final_primal_equality_inf", ...
            ipm.final_metrics.primal_equality_inf, ...
        "final_primal_inequality_inf", ...
            ipm.final_metrics.primal_inequality_inf, ...
        "final_dual_scaled_inf",ipm.final_metrics.dual_scaled_inf, ...
        "final_mean_lz_scaled",ipm.final_metrics.mean_lz_scaled, ...
        "final_physical_audit_executed",ipm.convergence_achieved, ...
        "final_physical_audit_passed", ...
            ipm.convergence_achieved && physical.passed));

    report = rkkt.reporting.generate_stage_b2c_30day_experiment_report( ...
        context.root);
    [reportValid,reportDetails] = ...
        rkkt.reporting.validate_docx_package(report.path);
    reportValidation = table(string(context.run_id),string(report.path), ...
        reportValid,conditional_status(reportValid), ...
        strjoin(string(reportDetails.errors)," | "), ...
        'VariableNames',{'run_id','path','package_valid','status','details'});
    write_new_table(fullfile(context.reports_dir, ...
        "report_structure_validation.csv"),reportValidation);
    assert(reportValid,"stageB2C:30day:Report", ...
        "The Chinese experiment report failed DOCX package validation.");

    manifest = rkkt.artifacts.finalize_run_manifest( ...
        context,terminalStatus,struct( ...
        "reports_generated",true,"report_structure_validated",true, ...
        "report_relative_path",char(erase(string(report.path), ...
            string(context.root)+filesep)), ...
        "report_sha256",char(rkkt.data.compute_sha256_file(report.path))));
    result.status = string(manifest.status);
    result.convergence_achieved = ipm.convergence_achieved;
    result.accepted_iteration_count = ipm.accepted_iteration_count;
    result.recursive_ipm_seconds = pureIpmComputeSeconds;
    result.report_path = string(report.path);
catch cause
    finalStatus = "FAIL_RETRYABLE";
    if contains(string(cause.identifier),["Environment","InputHash"])
        finalStatus = "BLOCKED_EXTERNAL";
    elseif contains(string(cause.identifier),"ModelDecision")
        finalStatus = "NEEDS_MODEL_DECISION";
    end
    preserve_failure_artifacts(context,cause,finalStatus);
    try
        manifest = jsondecode(fileread(context.run_manifest_path));
        if string(manifest.status)=="RUNNING"
            rkkt.artifacts.finalize_run_manifest(context,finalStatus,struct( ...
                "milestone_status",char(finalStatus), ...
                "experiment_completed",false, ...
                "experiment_passed",false, ...
                "failure_identifier",char(string(cause.identifier)), ...
                "failure_message",char(string(cause.message))));
        end
    catch
    end
    result.status = finalStatus;
    result.error_identifier = string(cause.identifier);
    result.error_message = string(cause.message);
end
end

function value = build_water_input_audit(data,config,runId)
n = numel(config.days)*numel(config.hydro_ids);
run_id = repmat(string(runId),n,1);
day = repelem(config.days(:),numel(config.hydro_ids));
hydro_id = repmat(config.hydro_ids(:),numel(config.days),1);
water_a = zeros(n,1); water_b = zeros(n,1); water_c = zeros(n,1);
water_min_m3 = zeros(n,1); water_max_m3 = zeros(n,1);
max_output_mw = zeros(n,1); all_finite = false(n,1);
min_not_above_max = false(n,1); nonnegative_bounds = false(n,1);
status = repmat("FAIL",n,1);
for row = 1:n
    h = hydro_id(row); d = day(row);
    water_a(row) = data.base.hydro.waterA(h);
    water_b(row) = data.base.hydro.waterB(h);
    water_c(row) = data.base.hydro.waterC(h);
    max_output_mw(row) = data.base.hydro.maxOutputMW(h);
    water_min_m3(row) = data.timeseries.hydroWaterMin(d,h);
    water_max_m3(row) = data.timeseries.hydroWaterMax(d,h);
    all_finite(row) = all(isfinite([water_a(row),water_b(row), ...
        water_c(row),max_output_mw(row),water_min_m3(row), ...
        water_max_m3(row)]));
    min_not_above_max(row) = water_min_m3(row)<=water_max_m3(row);
    nonnegative_bounds(row) = water_min_m3(row)>=0 && ...
        water_max_m3(row)>=0 && max_output_mw(row)>0;
    if all_finite(row) && min_not_above_max(row) && ...
            nonnegative_bounds(row)
        status(row) = "PASS";
    end
end
value = table(run_id,day,hydro_id,water_a,water_b,water_c, ...
    water_min_m3,water_max_m3,max_output_mw,all_finite, ...
    min_not_above_max,nonnegative_bounds,status);
end

function value = build_dimension_summary(context,index,config,indexSeconds,prepSeconds)
metric = ["days";"hours_per_day";"primal_variables";"equalities"; ...
    "base_inequalities";"water_inequalities";"total_inequalities"; ...
    "reconstructed_full_kkt_dimension";"daily_joint_block_count"; ...
    "global_core_dimension";"fixed_zero_count";"index_build_seconds"; ...
    "preparation_seconds"];
actual_value = [numel(config.days);numel(config.hours); ...
    index.counts.variables;index.counts.equalities; ...
    config.expected_stage_a_inequality_dimension; ...
    index.counts.water_inequalities;index.counts.inequalities; ...
    index.counts.full_kkt_dimension;numel(config.days); ...
    config.expected_global_core_dimension;height(index.fixed_zero_map); ...
    indexSeconds;prepSeconds];
value = table(repmat(string(context.run_id),numel(metric),1), ...
    metric,actual_value,'VariableNames',{'run_id','metric','actual_value'});
end

function persist_index_artifacts(context,index)
write_new_table(fullfile(context.indices_dir,"variable_index.csv"), ...
    index.variable_index);
write_new_table(fullfile(context.indices_dir,"constraint_index.csv"), ...
    index.constraint_index);
write_new_table(fullfile(context.indices_dir,"block_index.csv"), ...
    index.block_index);
write_new_table(fullfile(context.indices_dir,"fixed_zero_map.csv"), ...
    index.fixed_zero_map);
write_new_table(fullfile(context.indices_dir,"permutation_map.csv"), ...
    index.permutation_map);
write_new_table(fullfile(context.indices_dir,"soc_link_map.csv"), ...
    index.soc_link_map);
write_new_table(fullfile(context.indices_dir,"water_constraint_index.csv"), ...
    index.water_constraint_index);
end

function [capacity,hourly,daily] = build_physical_results( ...
        context,ipm,index,physical)
names = string(ipm.final_linearization.capacity_parameters.names(:));
values = ipm.final_state.xi(ipm.final_linearization.maps.q_global);
capacity = table(repmat(string(context.run_id),14,1),(1:14).', ...
    names,values,'VariableNames',{'run_id','capacity_index', ...
    'capacity_name','value'});

nDays = numel(physical.days); nHours = numel(physical.hours);
n = nDays*nHours; day = zeros(n,1); hour = zeros(n,1);
arrays = cell(1,24);
for k = 1:24
    arrays{k} = zeros(n,1);
end
row = 0;
for d = 1:nDays
    for t = 1:nHours
        row = row+1; day(row) = physical.days(d); hour(row) = physical.hours(t);
        atHour = [reshape(physical.value.wind(d,t,:),1,[]), ...
            reshape(physical.value.solar(d,t,:),1,[]), ...
            reshape(physical.value.hydro(d,t,:),1,[]), ...
            reshape(physical.value.thermal(d,t,:),1,[]), ...
            reshape(physical.value.charge(d,t,:),1,[]), ...
            reshape(physical.value.discharge(d,t,:),1,[]), ...
            reshape(physical.value.soc(d,t,:),1,[])];
        for k = 1:24
            arrays{k}(row) = atHour(k);
        end
    end
end
variableNames = ["PW_1","PW_2","PW_3","PW_4","PW_5", ...
    "PP_1","PP_2","PP_3","PP_4","PP_5", ...
    "PH_1","PH_2","PH_3","PH_4", ...
    "PF_1","PF_2","PF_3","PF_4", ...
    "Pch_1","Pch_2","Pdis_1","Pdis_2","SOC_1","SOC_2"];
hourly = table(repmat(string(context.run_id),n,1),day,hour, ...
    'VariableNames',{'run_id','day','hour'});
for k = 1:numel(variableNames)
    hourly.(variableNames(k)) = arrays{k};
end
assert(height(hourly)==n && width(hourly)==27 && ...
    height(index.variable_index)==ipm.final_linearization.counts.primal, ...
    "stageB2C:30day:Results", ...
    "The configured physical result table is incomplete.");

wind_mwh = squeeze(sum(physical.value.wind,[2,3]));
solar_mwh = squeeze(sum(physical.value.solar,[2,3]));
hydro_mwh = squeeze(sum(physical.value.hydro,[2,3]));
thermal_mwh = squeeze(sum(physical.value.thermal,[2,3]));
charge_mwh = squeeze(sum(physical.value.charge,[2,3]));
discharge_mwh = squeeze(sum(physical.value.discharge,[2,3]));
total_generation_mwh = wind_mwh+solar_mwh+hydro_mwh+thermal_mwh;
net_storage_supply_mwh = discharge_mwh-charge_mwh;
daily = table(repmat(string(context.run_id),nDays,1), ...
    physical.days(:),wind_mwh,solar_mwh,hydro_mwh,thermal_mwh, ...
    charge_mwh,discharge_mwh,net_storage_supply_mwh, ...
    total_generation_mwh, ...
    'VariableNames',{'run_id','day','wind_mwh','solar_mwh', ...
    'hydro_mwh','thermal_mwh','storage_charge_mwh', ...
    'storage_discharge_mwh','net_storage_supply_mwh', ...
    'total_generation_mwh'});
end

function persist_final_matrix_artifacts(context,ipm)
pathValue = fullfile(context.matrices_dir,"final_recursive_operators.mat");
lin = ipm.final_linearization;
core = ipm.last_core;
rkkt.artifacts.save_mat_artifact(pathValue,"H",lin.H,"A",lin.A, ...
    "G",lin.G,"global_core_matrix",core.matrix, ...
    "global_core_rhs",core.rhs,"global_core_solution",core.solution, ...
    "linearization_identity",lin.identity);
matrix_name = ["H_L";"A";"G";"global_core_16"];
matrices = {lin.H;lin.A;lin.G;core.matrix};
row_count = zeros(4,1); column_count = zeros(4,1);
nonzero_count = zeros(4,1);
for k = 1:4
    [row_count(k),column_count(k)] = size(matrices{k});
    nonzero_count(k) = nnz(matrices{k});
end
manifest = table(repmat(string(context.run_id),4,1),matrix_name, ...
    ["recursive_shared";"recursive_shared";"recursive_shared"; ...
    "recursive_formal"],row_count,column_count,nonzero_count, ...
    true(4,1),repmat("matrices/final_recursive_operators.mat",4,1), ...
    repmat(rkkt.data.compute_sha256_file(pathValue),4,1), ...
    repmat(string(lin.identity),4,1),repmat("PASS",4,1), ...
    'VariableNames',{'run_id','matrix_name','role','row_count', ...
    'column_count','nonzero_count','is_sparse','artifact_path','sha256', ...
    'linearization_identity','status'});
write_new_table(context.matrix_manifest_path,manifest);
end

function value = make_acceptance(context,ipm,physical,waterInput,index, ...
        config,requireConvergence)
iterations = ipm.iteration_history;
factors = ipm.factorization_history;
correction = ipm.water_correction_history;
accepted = ipm.accepted_iteration_count;
routePass = accepted>0 && all(~iterations.full_kkt_audit_executed) && ...
    all(iterations.recursive_final_kkt_relative_residual<= ...
        config.recursive_full_kkt_residual_tolerance);
factorPass = height(factors)==accepted*(numel(config.days)+1) && ...
    all(factors.factorization_count==1) && ...
    all(factors.refinement_additional_factorization_count==0) && ...
    all(~factors.blocking_warning_present) && all(factors.solution_finite);
correctionPass = height(correction)== ...
    accepted*config.expected_water_inequality_count && ...
    all(correction.strictly_positive);
fixedPass = all(iterations.fixed_zero_count== ...
    config.expected_stage_a_fixed_zero_count) && ...
    all(iterations.fixed_zero_exact);
convergencePass = ~requireConvergence || ipm.convergence_achieved;
physicalPass = ~ipm.convergence_achieved || physical.passed;
test_id = ["EXP-DATA";"EXP-INDEX";"EXP-ROUTE";"EXP-FACTORS"; ...
    "EXP-WATER-CORRECTION";"EXP-FIXED-ZERO";"EXP-CONVERGENCE"; ...
    "EXP-PHYSICAL"];
requirement = ["120 water-input rows pass"; ...
    "15910/2642/31220 and reconstructed dimension 80992"; ...
    "recursive direction only; reconstructed KKT residual <= 1e-10"; ...
    "30 daily LDL solves plus one 16-D core solve per iteration; no refactorization during residual correction"; ...
    "240 exact second-order water-slack corrections per iteration"; ...
    "1804 removed renewable entries remain exact zero"; ...
    conditional_text(requireConvergence, ...
        "four stopping metrics <= 1e-6","bounded smoke update completed"); ...
    "if converged, final water and Stage-A physical audit passes"];
actual_value = [string(height(waterInput))+" rows"; ...
    compose("%d/%d/%d; reconstructed=%d",index.counts.variables, ...
        index.counts.equalities,index.counts.inequalities, ...
        index.counts.full_kkt_dimension); ...
    compose("audit=false; worst residual=%.17g", ...
        max(iterations.recursive_final_kkt_relative_residual)); ...
    string(height(factors))+" factor records; refinement triggers="+ ...
        string(nnz(factors.refinement_triggered)); ...
    string(height(correction))+" correction records"; ...
    string(max(iterations.fixed_zero_count))+" exact zeros"; ...
    compose("converged=%s; iterations=%d", ...
        string(ipm.convergence_achieved),accepted); ...
    conditional_text(ipm.convergence_achieved, ...
        compose("passed=%s; max water violation=%.17g", ...
            string(physical.passed),physical.maximum_water_violation), ...
        "not executed before convergence")];
passed = [height(waterInput)==config.expected_final_water_audit_rows && ...
        all(waterInput.status=="PASS"); ...
    index.counts.variables==config.expected_stage_a_primal_dimension && ...
        index.counts.equalities==config.expected_stage_a_equality_dimension && ...
        index.counts.inequalities==config.expected_stage_a_inequality_dimension+ ...
            config.expected_water_inequality_count && ...
        index.counts.full_kkt_dimension==config.expected_full_kkt_dimension; ...
    routePass;factorPass;correctionPass;fixedPass; ...
    convergencePass;physicalPass];
status = repmat("FAIL",numel(test_id),1); status(passed) = "PASS";
value = table(repmat(string(context.run_id),numel(test_id),1), ...
    test_id,requirement,actual_value,true(numel(test_id),1),status, ...
    'VariableNames',{'run_id','test_id','requirement','actual_value', ...
    'blocking','status'});
end

function value = make_issue_log(context,status,ipm,requireConvergence)
if status=="PASS"
    value = table(strings(0,1),strings(0,1),strings(0,1), ...
        strings(0,1),strings(0,1),strings(0,1), ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    return
end
description = "30-day recursive experiment did not satisfy all checks.";
if requireConvergence && ~ipm.convergence_achieved
    description = "The four stopping metrics did not all pass within the iteration limit.";
end
value = table(string(context.run_id),"30DAY_EXPERIMENT", ...
    "BLOCKING",status,description,"Inspect iteration and factor histories.", ...
    'VariableNames',{'run_id','issue_id','severity','status', ...
    'description','next_action'});
end

function value = make_decision(context,status,ipm,requireConvergence)
conclusion = "The bounded 30-day recursive smoke update completed.";
nextAction = "Run the convergence experiment without changing the formal seven-day flow.";
if requireConvergence
    conclusion = "The 30-day recursive IPM experiment completed; convergence="+ ...
        string(ipm.convergence_achieved)+".";
    nextAction = "Review capacities and daily dispatch; formal Stage-B acceptance remains unchanged.";
end
value = table(string(context.run_id),"B-2C-30-DAY-EXPERIMENT", ...
    status,conclusion,nextAction,false,false,false, ...
    'VariableNames',{'run_id','milestone','status','conclusion', ...
    'next_action','full_kkt_audit_executed','formal_stage_changed', ...
    'stage_c1_entered'});
end

function persist_runtime_test_evidence(context,acceptance)
inventory = table("B2C-30DAY-RUNTIME", ...
    "src/+rkkt/+workflows/stageB2C30DayExperiment.m", ...
    "dynamic dimensions, recursive route, water correction and convergence", ...
    'VariableNames',{'test_id','test_file','purpose'});
write_new_table(context.test_inventory_path,inventory);
results = acceptance(:,["run_id","test_id","status"]);
results.passed = results.status=="PASS";
write_new_table(context.test_results_csv_path,results);
summary = struct("test_total",height(results), ...
    "test_passed",nnz(results.passed), ...
    "test_failed",nnz(~results.passed), ...
    "all_pass",all(results.passed));
rkkt.artifacts.write_json_file(context.test_summary_path,summary);
rkkt.artifacts.write_text_utf8(context.test_command_path, ...
    "rkkt.workflows.stageB2C30DayExperiment (runtime evidence)");
end

function preserve_failure_artifacts(context,cause,status)
if ~isfile(context.issue_log_path)
    issue = table(string(context.run_id),"WORKFLOW_FAILURE","BLOCKING", ...
        status,string(cause.identifier)+": "+string(cause.message), ...
        "Repair the first failed layer and create a new unique run.", ...
        'VariableNames',{'run_id','issue_id','severity','status', ...
        'description','next_action'});
    rkkt.artifacts.write_table_csv_17g_atomic(context.issue_log_path,issue);
end
if ~isfile(context.acceptance_results_path)
    acceptance = table(string(context.run_id),"workflow_completed", ...
        "no exception",string(cause.identifier),"FAIL", ...
        'VariableNames',{'run_id','test_id','requirement', ...
        'actual_value','status'});
    rkkt.artifacts.write_table_csv_17g_atomic( ...
        context.acceptance_results_path,acceptance);
end
end

function value = input_hash_object(hashes)
base = hashes.fileName=="基础参数.xlsx";
series = hashes.fileName=="输入数据.xlsx";
assert(nnz(base)==1 && nnz(series)==1,"stageB2C:30day:InputHashRows", ...
    "Both controlled input rows are required.");
value = struct("base_parameters",char(hashes.actualSHA256(base)), ...
    "timeseries",char(hashes.actualSHA256(series)));
end

function value = input_hash_table(hashes,runId)
n = height(hashes);
value = table(repmat(string(runId),n,1),string(hashes.fileName), ...
    "inputs/raw/"+string(hashes.fileName),double(hashes.expectedBytes), ...
    double(hashes.actualBytes),string(hashes.expectedSHA256), ...
    string(hashes.actualSHA256),string(hashes.status), ...
    'VariableNames',{'run_id','file_name','relative_path','expected_bytes', ...
    'actual_bytes','expectedSHA256','actualSHA256','status'});
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
[created,message] = mkdir(pathValue);
assert(created,"stageB2C:30day:Directory","%s",message);
end

function write_new_table(pathValue,value)
assert(~isfile(pathValue) && ~isfolder(pathValue), ...
    "stageB2C:30day:ArtifactExists","Refusing to overwrite %s.",pathValue);
rkkt.artifacts.write_table_csv_17g(pathValue,value);
end

function value = conditional_status(passed)
if passed, value = "PASS"; else, value = "FAIL"; end
end

function value = conditional_text(condition,whenTrue,whenFalse)
if condition, value = string(whenTrue); else, value = string(whenFalse); end
end
