function [solution,byHour,diagnostics] = refine_block_thomas_solution( ...
        partition,factors,multipliers,initialSolution,options)
%REFINE_BLOCK_THOMAS_SOLUTION Bounded raw-residual defect correction.

arguments
    partition (1,1) struct
    factors (:,1) cell
    multipliers (:,1) cell
    initialSolution {mustBeNumeric,mustBeReal}
    options.MaxPasses (1,1) double {mustBeInteger,mustBeNonnegative} = 0
    options.TargetRelative (1,1) double ...
        {mustBePositive,mustBeFinite} = 64*eps
end
assert(options.MaxPasses<=3, ...
    "stageA:RNS1:RefinementPassLimit", ...
    "A4-RNS-1 permits at most three retained-factor corrections.");

rawOperator = partition.M;
rhs = [partition.r_v,partition.B];
assert(isequal(size(initialSolution),size(rhs)) && size(rhs,2)==15, ...
    "stageA:RNS1:OfficialRhsShape", ...
    "The official Stage-A Thomas solve must contain all 15 RHS columns.");
factorsBefore = factors;
multipliersBefore = multipliers;

history = repmat(empty_history_row(size(rhs,2)), ...
    options.MaxPasses+1,1);
current = initialSolution;
currentMetrics = compute_retained_residual_metrics( ...
    rawOperator,current,rhs);
history(1) = make_history_row(0,currentMetrics,true);
selectedPass = 0;
attemptedPasses = 0;
correctionDiagnostics = cell(options.MaxPasses,1);

if options.MaxPasses==0
    stopReason = "disabled";
elseif currentMetrics.maximum_column_relative<=options.TargetRelative
    stopReason = "target_met_initial";
else
    stopReason = "maximum_passes_reached";
    for pass = 1:options.MaxPasses
        attemptedPasses = pass;
        [correction,~,correctionDiagnostics{pass}] = ...
            apply_retained_block_thomas_once( ...
            partition,factors,multipliers,currentMetrics.residual, ...
            "RNS1_raw_chain_correction_"+string(pass));
        candidate = current+correction;
        candidateMetrics = compute_retained_residual_metrics( ...
            rawOperator,candidate,rhs);
        improved = lexicographically_better( ...
            candidateMetrics,currentMetrics);
        history(pass+1) = make_history_row( ...
            pass,candidateMetrics,improved);
        if ~improved
            stopReason = "residual_no_longer_decreased";
            break
        end
        current = candidate;
        currentMetrics = candidateMetrics;
        selectedPass = pass;
        if currentMetrics.maximum_column_relative<=options.TargetRelative
            stopReason = "target_met";
            break
        end
    end
end
history = history(1:attemptedPasses+1);
solution = current;
byHour = split_by_hour(partition,solution);
assert(isequaln(factors,factorsBefore) && ...
    isequaln(multipliers,multipliersBefore), ...
    "stageA:RNS1:RetainedThomasMutation", ...
    "Residual refinement changed the retained factor context.");
finalMetrics = compute_retained_residual_metrics( ...
    rawOperator,solution,rhs);
initialMetric = history(1).maximum_column_relative;
if initialMetric==0
    reductionRatio = 0;
else
    reductionRatio = ...
        finalMetrics.maximum_column_relative/initialMetric;
end

diagnostics = struct( ...
    "enabled",options.MaxPasses>0, ...
    "triggered",options.MaxPasses>0 && ...
        history(1).maximum_column_relative>options.TargetRelative, ...
    "maximum_passes",options.MaxPasses, ...
    "target_relative",options.TargetRelative, ...
    "passes_attempted",attemptedPasses, ...
    "correction_count",selectedPass, ...
    "selected_pass",selectedPass, ...
    "stop_reason",stopReason, ...
    "target_met", ...
        finalMetrics.maximum_column_relative<=options.TargetRelative, ...
    "initial_maximum_column_relative", ...
        history(1).maximum_column_relative, ...
    "final_maximum_column_relative", ...
        finalMetrics.maximum_column_relative, ...
    "residual_reduction_ratio",reductionRatio, ...
    "history",history, ...
    "correction_solve",{correctionDiagnostics(1:attemptedPasses)}, ...
    "rhs_count",size(rhs,2), ...
    "all_rhs_share_selected_pass",true, ...
    "residual_operator","original_partition_M", ...
    "residual_operator_exact_original",isequal(rawOperator,partition.M), ...
    "correction_operator","retained_thomas_inverse_map", ...
    "correction_operator_claimed_equal_original",false, ...
    "factor_context_unchanged",true, ...
    "additional_factorization_count",0, ...
    "direct_chain_backslash_used",false, ...
    "full_kkt_direction_consumed",false);
end

function result = lexicographically_better(candidate,current)
result = candidate.maximum_column_relative< ...
    current.maximum_column_relative || ...
    (candidate.maximum_column_relative== ...
    current.maximum_column_relative && ...
    candidate.frobenius_relative<current.frobenius_relative);
end

function byHour = split_by_hour(partition,solution)
nHours = numel(partition.hour);
byHour = cell(nHours,1);
for t = 1:nHours
    rows = partition.block_offsets.start_index(t): ...
        partition.block_offsets.end_index(t);
    byHour{t} = solution(rows,:);
end
end

function row = make_history_row(pass,metrics,accepted)
row = struct( ...
    "pass",pass, ...
    "maximum_column_relative",metrics.maximum_column_relative, ...
    "column_relative",metrics.column_relative, ...
    "frobenius_relative",metrics.frobenius_relative, ...
    "componentwise_backward_error", ...
        metrics.componentwise_backward_error, ...
    "maximum_absolute",metrics.maximum_absolute, ...
    "accepted",accepted);
end

function row = empty_history_row(rhsCount)
row = struct( ...
    "pass",0, ...
    "maximum_column_relative",NaN, ...
    "column_relative",nan(1,rhsCount), ...
    "frobenius_relative",NaN, ...
    "componentwise_backward_error",NaN, ...
    "maximum_absolute",NaN, ...
    "accepted",false);
end
