function audit = assert_package_closure_a4_preflight(projectRoot)
%ASSERT_PACKAGE_CLOSURE_A4_PREFLIGHT Freeze the package-closure run boundary.

arguments
    projectRoot (1,1) string
end

currentPath = fullfile(projectRoot,"CURRENT_STAGE.md");
assert(isfile(currentPath),"rkkt:closure:CurrentStageMissing", ...
    "CURRENT_STAGE.md is missing.");
current = string(fileread(currentPath));
stagePassed = contains(current,"`stage_id`: `stage_B`") && ...
    contains(current,"`status`: `READY`");
assert(stagePassed,"rkkt:closure:CurrentStage", ...
    "Package closure requires CURRENT_STAGE stage_B / READY.");

[branchStatus,branchText] = git_command(projectRoot,"branch --show-current");
branch = strip(string(branchText));
assert(branchStatus==0 && branch=="refactor/pkg-interface", ...
    "rkkt:closure:Branch", ...
    "Package closure requires branch refactor/pkg-interface.");

[headStatus,headText] = git_command(projectRoot,"rev-parse HEAD");
head = lower(strip(string(headText)));
assert(headStatus==0 && ...
    ~isempty(regexp(char(head),"^[0-9a-f]{40}$","once")), ...
    "rkkt:closure:Head","Could not resolve the full Git HEAD.");

[trackedStatus,trackedText] = git_command( ...
    projectRoot,"status --porcelain --untracked-files=no");
trackedClean = trackedStatus==0 && ...
    strlength(strip(string(trackedText)))==0;
assert(trackedClean,"rkkt:closure:TrackedChanges", ...
    "Package closure requires a clean tracked worktree.");

[statusCode,statusText] = git_command( ...
    projectRoot,"status --porcelain --untracked-files=normal");
assert(statusCode==0,"rkkt:closure:GitStatus", ...
    "Could not inspect the full Git status.");
lines = strip(splitlines(string(statusText)));
lines = lines(strlength(lines)>0);
unknown = lines(~startsWith(lines,"?? runs/"));
assert(isempty(unknown),"rkkt:closure:UnknownUntracked", ...
    "Only preserved run evidence may be untracked: %s", ...
    strjoin(unknown,"; "));

audit = struct( ...
    "stage_id","stage_B", ...
    "stage_status","READY", ...
    "model_regression_stage","stage_A4", ...
    "branch",branch, ...
    "git_commit",head, ...
    "authority_starting_head",head, ...
    "tracked_worktree_clean",trackedClean, ...
    "untracked_entries",lines, ...
    "untracked_entries_all_under_runs",isempty(unknown), ...
    "passed",stagePassed && trackedClean && isempty(unknown));
end

function [status,output] = git_command(root,arguments)
safe = replace(string(root),"\","/");
quotedSafe = '"'+replace(safe,'"','\"')+'"';
quotedRoot = '"'+replace(string(root),'"','\"')+'"';
command = "git -c safe.directory="+quotedSafe+" -C "+quotedRoot+" "+ ...
    "-c core.quotepath=false "+arguments;
[status,output] = system(char(command));
end
