function metrics = compute_stage_b2c_unitized_metrics(lin)
%COMPUTE_STAGE_B2C_UNITIZED_METRICS Rebuild formal B-2C stopping metrics.

arguments
    lin (1,1) struct
end
assert(isfield(lin,"objective_scale") && lin.objective_scale.enabled && ...
    string(lin.objective_scale.mode)=="positive_scalar_unitization", ...
    "stageB2C:metrics:Coordinate", ...
    "B-2C metrics require the positive-scalar-unitized KKT coordinate.");
scale = lin.objective_scale.factor;
mappedY = scale*lin.state.y;
mappedZ = scale*lin.state.z;
mappedDual = scale*lin.r_dual;
rebuiltMappedDual = lin.objective.original_gradient+ ...
    lin.A.'*mappedY+lin.G.'*mappedZ;
physical = lin.G*lin.state.xi+lin.constraints.ineq_offset;
waterRows = lin.maps.ineq_water(:);
meanScaled = mean(lin.state.l.*lin.state.z);
ltzScaled = lin.state.l.'*lin.state.z;
eqScale = max(1,norm(lin.A*lin.state.xi,inf)+ ...
    norm(lin.constraints.eq_offset,inf));
dualScale = max(1,norm(lin.objective.gradient,inf)+ ...
    norm(lin.A.'*lin.state.y,inf)+norm(lin.G.'*lin.state.z,inf));
metrics = struct( ...
    "convergence_coordinate","positive_scalar_unitized_kkt", ...
    "objective_scale_factor",scale, ...
    "objective_scaled",lin.objective.value, ...
    "objective_raw",lin.objective.original_value, ...
    "primal_equality_inf",norm(lin.r_eq,inf), ...
    "primal_inequality_inf",norm(lin.r_ineq,inf), ...
    "dual_scaled_inf",norm(lin.r_dual,inf), ...
    "dual_raw_inf",norm(mappedDual,inf), ...
    "r_comp_scaled_inf",norm(lin.r_comp,inf), ...
    "mean_lz_scaled",meanScaled, ...
    "mean_lz_raw",scale*meanScaled, ...
    "ltz_scaled",ltzScaled,"ltz_raw",scale*ltzScaled, ...
    "eta_eq",norm(lin.r_eq,inf)/eqScale, ...
    "eta_dual",norm(lin.r_dual,inf)/dualScale, ...
    "eta_gap",ltzScaled/max(1,abs(lin.objective.value)), ...
    "physical_inequality_violation",max(max(physical,0)), ...
    "maximum_water_violation",max(max(physical(waterRows),0)), ...
    "min_l",min(lin.state.l),"min_z",min(lin.state.z), ...
    "dual_mapping_rebuild_relative_error", ...
        norm(mappedDual-rebuiltMappedDual,inf)/ ...
        max([1,norm(mappedDual,inf),norm(rebuiltMappedDual,inf)]), ...
    "all_finite",all(isfinite([lin.state.xi;lin.state.y;lin.state.l; ...
        lin.state.z;lin.r_eq;lin.r_ineq;lin.r_dual;lin.r_comp])));
assert(scale>0 && metrics.mean_lz_scaled>0 && ...
    metrics.ltz_scaled>0 && metrics.all_finite, ...
    "stageB2C:metrics:Finite", ...
    "B-2C unitized metrics are nonfinite or nonpositive.");
end
