function audit = compare_stage_a4_historical_runs( ...
        projectRoot,before,newRunId)
%COMPARE_STAGE_A4_HISTORICAL_RUNS Prove old run paths stayed unchanged.

arguments
    projectRoot (1,1) string
    before table
    newRunId (1,1) string
end
after = rkkt.diagnostics.snapshot_stage_a4_historical_runs(projectRoot);
newPrefix = newRunId+"/";
after = after(after.relativePath~=newRunId & ...
    ~startsWith(after.relativePath,newPrefix),:);
missing = setdiff(before.relativePath,after.relativePath,"stable");
extra = setdiff(after.relativePath,before.relativePath,"stable");
common = intersect(before.relativePath,after.relativePath,"stable");
changed = strings(0,1);
for pathValue = common.'
    left = before(before.relativePath==pathValue,:);
    right = after(after.relativePath==pathValue,:);
    exact = left.entryType==right.entryType && ...
        left.bytes==right.bytes && ...
        left.modifiedDatenum==right.modifiedDatenum && ...
        left.sha256==right.sha256;
    if ~exact
        changed(end+1,1) = pathValue; %#ok<AGROW>
    end
end
audit = struct( ...
    "before_count",height(before), ...
    "after_historical_count",height(after), ...
    "missing_paths",missing, ...
    "unexpected_historical_paths",extra, ...
    "changed_paths",changed, ...
    "new_run_id",newRunId, ...
    "passed",isempty(missing)&&isempty(extra)&&isempty(changed));
assert(audit.passed,"stageA4:a43:HistoricalRunsChanged", ...
    "A historical run path was added, removed, or changed.");
end
