function gate = evaluate_stage_a4_scaled_five_round_gate(chain)
%EVALUATE_STAGE_A4_SCALED_FIVE_ROUND_GATE Authorize the fresh 20-round run.

assert(isstruct(chain) && isfield(chain,"iterations"), ...
    "stageA4:a42d2a:GateInput", ...
    "The five-round gate requires a scaled-chain result.");
items = chain.iterations;
countExact = chain.iteration_count==5 && numel(items)==5;
structurePassed = chain.structural_audit.all_pass;
directionPassed = countExact && all( ...
    [items.direction_relative_error]<=1e-10) && ...
    all([items.recursive_kkt_relative_residual]<=1e-10) && ...
    all([items.full_kkt_relative_residual]<=1e-10);
positiveFinite = countExact && all(arrayfun(@(x) ...
    x.metrics_before.all_finite && x.metrics_after.all_finite && ...
    x.metrics_after.minimum_l>0 && x.metrics_after.minimum_z>0,items));
physicalPassed = countExact && all(arrayfun(@(x) ...
    x.metrics_after.physical_inequality_violation<= ...
    x.physical_violation_threshold,items));
noFallback = countExact && all([items.no_full_direction_fallback]) && ...
    ~any([items.full_direction_consumed]);
sameIdentity = countExact && all( ...
    [items.same_scaled_linearization_identity]);
scalePassed = chain.objective_scale.enabled && ...
    chain.objective_scale.mode=="positive_scalar_unitization" && ...
    isfinite(chain.objective_scale.factor) && ...
    chain.objective_scale.factor>0 && ...
    all([items.objective_scale_factor]==chain.objective_scale.factor);
stepAndProductsPassed = countExact && all(arrayfun(@(x) ...
    x.state_update_consumed_recursive_only && ...
    x.r_eq_product_scaled_error<=2048*eps && ...
    x.r_dual_product_scaled_error<=2048*eps && ...
    x.budget_product_absolute_error<=2048*eps,items));

checks = struct( ...
    "iteration_count_exact",countExact, ...
    "structure_preserved",structurePassed, ...
    "directions_and_kkt_audits_passed",directionPassed, ...
    "finite_strictly_positive_state",positiveFinite, ...
    "physical_inequality_within_frozen_threshold",physicalPassed, ...
    "no_complete_direction_fallback",noFallback, ...
    "shared_scaled_linearization_identity",sameIdentity, ...
    "single_positive_scale_preserved",scalePassed, ...
    "recursive_updates_and_residual_products_passed", ...
        stepAndProductsPassed);
values = struct2cell(checks);
passed = all(cellfun(@(x)isequal(x,true),values));
checkNames = string(fieldnames(checks));
gate = struct( ...
    "checks",checks, ...
    "passed",passed, ...
    "permission_to_start_twenty_round_chain",passed, ...
    "evaluated_after_scaled_five_completed",true, ...
    "failed_checks",checkNames( ...
        ~cellfun(@(x)isequal(x,true),values)));
end
