function audit = evaluate_stage_b2c_physical_audit( ...
        runResult,modelIndex,data,config)
%EVALUATE_STAGE_B2C_PHYSICAL_AUDIT Rebuild water and Stage-A feasibility.

arguments
    runResult (1,1) struct
    modelIndex (1,1) struct
    data (1,1) struct
    config (1,1) struct
end
assert(runResult.convergence_achieved && ...
    string(runResult.run_terminal_state)=="CONVERGED", ...
    "stageB2C:physical:BeforeConvergence", ...
    "SB-PHY-001 may run only after formal B-2C convergence.");
state = runResult.final_state;
lin = runResult.final_linearization;
runtimeRoute = isfield(modelIndex,"version") && ...
    ismember(string(modelIndex.version),[ ...
        "stage-B2C-recursive-runtime-package-v1.0", ...
        "stage-B2C-recursive-numerical-payload-v1.0"]);
if runtimeRoute
    physical = rkkt.model.recover_stage_b2c_runtime_physical_arrays( ...
        state.xi,zeros(size(state.xi)),modelIndex,data);
else
    physical = rkkt.model.recover_stage_a_physical_arrays( ...
        state.xi,zeros(size(state.xi)),modelIndex,data);
end

nWaterAudit = numel(config.days)*numel(config.hydro_ids);
day = zeros(nWaterAudit,1); hydro_id = zeros(nWaterAudit,1);
Wmin = zeros(nWaterAudit,1); W = zeros(nWaterAudit,1);
Wmax = zeros(nWaterAudit,1);
lower_margin = zeros(nWaterAudit,1); upper_margin = zeros(nWaterAudit,1);
lower_violation = zeros(nWaterAudit,1); upper_violation = zeros(nWaterAudit,1);
maximum_violation = zeros(nWaterAudit,1); status = strings(nWaterAudit,1);
physical_source = repmat("final_unscaled_PH",nWaterAudit,1);
independent_daily_scope = true(nWaterAudit,1);
row = 0;
for d = 1:numel(config.days)
    for h = config.hydro_ids
        row = row+1;
        day(row) = config.days(d);
        hydro_id(row) = h;
        power = reshape(physical.value.hydro(d,:,h),[],1);
        evaluated = rkkt.model.evaluate_stage_b_daily_hydro_water(power, ...
            data.base.hydro.waterA(h),data.base.hydro.waterB(h), ...
            data.base.hydro.waterC(h));
        Wmin(row) = data.timeseries.hydroWaterMin(day(row),h);
        W(row) = evaluated.value;
        Wmax(row) = data.timeseries.hydroWaterMax(day(row),h);
        lower_margin(row) = W(row)-Wmin(row);
        upper_margin(row) = Wmax(row)-W(row);
        lower_violation(row) = max(0,Wmin(row)-W(row));
        upper_violation(row) = max(0,W(row)-Wmax(row));
        maximum_violation(row) = max( ...
            lower_violation(row),upper_violation(row));
        if isfinite(W(row)) && maximum_violation(row)<= ...
                config.water_physical_violation_tolerance
            status(row) = "PASS";
        else
            status(row) = "FAIL";
        end
    end
end
water = table(day,hydro_id,Wmin,W,Wmax,lower_margin,upper_margin, ...
    lower_violation,upper_violation,maximum_violation,status, ...
    physical_source,independent_daily_scope);
assert(height(water)==config.expected_final_water_audit_rows && ...
    height(water)==nWaterAudit && ...
    isequal(water.day,repelem(config.days(:),numel(config.hydro_ids))) && ...
    isequal(water.hydro_id,repmat(config.hydro_ids(:),numel(config.days),1)), ...
    "stageB2C:physical:WaterRows", ...
    "The final water audit has an invalid ordered day-station inventory.");

if runtimeRoute
    equality = modelIndex.runtime.equality_map;
    balance = false(runResult.final_linearization.counts.equalities,1);
    terminal = balance; soc = balance;
    balance(double(equality.power_balance_rows)) = true;
    terminal(double(equality.terminal_soc_rows)) = true;
    soc(double(equality.soc_rows)) = true;
else
    constraintIndex = modelIndex.constraint_index;
    eqIndex = constraintIndex( ...
        string(constraintIndex.constraint_type)=="equality",:);
    names = string(eqIndex.constraint_name);
    balance = names=="hourly_power_balance";
    terminal = names=="terminal_soc";
    soc = names=="soc_dynamics" | terminal;
end
baseRows = (1:config.expected_stage_a_inequality_dimension).';
allPhysical = rkkt.model.apply_stage_b2c_inequality_jacobian( ...
    lin,state.xi)+lin.constraints.ineq_offset;
basePhysical = allPhysical(baseRows);
if runtimeRoute
    boundary = modelIndex.runtime.soc_boundary;
    noInterday = boundary.no_interday && ...
        all(boundary.first_hour_row_count==2) && ...
        all(boundary.terminal_row_count==2) && ...
        boundary.initial_fraction==0.5 && boundary.terminal_fraction==0.5;
else
    links = modelIndex.soc_link_map;
    noInterday = ~any(links.predecessor_hour==24 & links.hour==1);
    dailySoc = true;
    for actualDay = config.days
        first = links(links.day==actualDay & links.hour==1,:);
        last = links(links.day==actualDay & links.terminal_equality,:);
        dailySoc = dailySoc && height(first)==2 && ...
            all(isnan(first.predecessor_hour)) && ...
            all(first.predecessor_soc_global_index==0) && ...
            all(first.initial_energy_fraction==0.5) && ...
            height(last)==2 && all(last.hour==24) && ...
            all(last.terminal_energy_fraction==0.5);
    end
    noInterday = noInterday && dailySoc;
end
fixedDirection = max(runResult.iteration_history. ...
    fixed_zero_maximum_absolute_direction);
values = [norm(lin.r_eq,inf);max_abs(lin.r_eq,balance); ...
    max_abs(lin.r_eq,soc);max_abs(lin.r_eq,terminal); ...
    max(max(basePhysical,0)); ...
    physical.fixed_zero_audit.maximum_absolute_value; ...
    fixedDirection;double(~noInterday)];
threshold = [repmat(config.stage_a_physical_violation_tolerance,5,1); ...
    0;0;0];
audit_id = ["B2C-PHY-EQUALITY";"B2C-PHY-POWER-BALANCE"; ...
    "B2C-PHY-SOC-CHAIN";"B2C-PHY-SOC-TERMINAL"; ...
    "B2C-PHY-BASE-INEQUALITY";"B2C-PHY-FIXED-ZERO-VALUE"; ...
    "B2C-PHY-FIXED-ZERO-DIRECTION";"B2C-PHY-NO-INTERDAY-SOC"];
fixedCount = config.expected_stage_a_fixed_zero_count;
requirement = ["all configured equality residuals"; ...
    "hourly power-balance residuals";"daily SOC-chain residuals"; ...
    string(2*numel(config.days))+" terminal SOC equalities"; ...
    "Stage-A physical inequality feasibility"; ...
    string(fixedCount)+" fixed-zero physical values"; ...
    string(fixedCount)+" fixed-zero directions"; ...
    "daily SOC chains have no cross-day predecessor"];
stageStatus = repmat("FAIL",8,1); stageStatus(values<=threshold)="PASS";
stage_a = table(audit_id,requirement,values,threshold,stageStatus, ...
    'VariableNames',{'audit_id','requirement','actual_value', ...
    'threshold','status'});
maximumWater = max(water.maximum_violation);
audit = struct("water",water,"stage_a",stage_a, ...
    "physical",physical,"maximum_water_violation",maximumWater, ...
    "water_row_count",height(water), ...
    "water_pass",height(water)==config.expected_final_water_audit_rows && ...
        all(water.status=="PASS") && ...
        all(isfinite(water.W)) && ...
        maximumWater<=config.water_physical_violation_tolerance, ...
    "stage_a_pass",all(stage_a.status=="PASS"), ...
    "no_cross_day_water_accumulation",all(water.independent_daily_scope), ...
    "passed",all(water.status=="PASS") && ...
        all(stage_a.status=="PASS"));
end

function value = max_abs(vector,mask)
if any(mask), value=max(abs(vector(mask))); else, value=Inf; end
end
