function acceptance = evaluate_stage_a1_acceptance_facts(projectRoot, ...
        environment,inputHashes,data,index,verification,codeScan,testAudit)
%EVALUATE_STAGE_A1_ACCEPTANCE_FACTS Evaluate every non-report A1 gate.
% SA1-ART-001 intentionally remains NOT_RUN until staged DOCX validation
% and the complete artifact hash audit have succeeded.

arguments
    projectRoot (1,1) string
    environment table
    inputHashes table
    data (1,1) struct
    index (1,1) struct
    verification (1,1) struct
    codeScan table
    testAudit (1,1) struct
end
acceptance = rkkt.diagnostics.initialize_stage_a1_acceptance(projectRoot);
result = verification;
lin = result.linearization;

blockingEnvironment = logical(environment.blocking);
environmentPassed = nnz(blockingEnvironment) > 0 && ...
    all(string(environment.status(blockingEnvironment)) == "PASS");
acceptance = set_boolean_result(acceptance,"SA1-ENV-001", ...
    environmentPassed,"checks="+height(environment)+ ...
    "; blocking_pass="+nnz(string(environment.status(blockingEnvironment))=="PASS"), ...
    "MATLAB R2024a, sparse solve, sparse LDL, and serial execution", ...
    "environment.csv");

hashPassed = height(inputHashes) == 2 && ...
    all(string(inputHashes.status) == "PASS") && ...
    all(lower(string(inputHashes.expectedSHA256)) == ...
    lower(string(inputHashes.actualSHA256)));
realSlicePassed = data.meta.nDays == 365 && data.meta.nHours == 24 && ...
    isequal(size(data.timeseries.planMW(1,8:10)),[1 3]) && ...
    all(isfinite(data.timeseries.planMW(1,8:10))) && ...
    all(isfinite(data.timeseries.windAvailability(1,8:10,:)),"all") && ...
    all(isfinite(data.timeseries.solarAvailability(1,8:10,:)),"all");
acceptance = set_boolean_result(acceptance,"SA1-DATA-001", ...
    hashPassed && realSlicePassed, ...
    "hashes="+strjoin(string(inputHashes.actualSHA256),";")+ ...
    "; plan_mw="+mat2str(data.timeseries.planMW(1,8:10),17), ...
    "two controlled SHA256 values match; real day 1 hours 8-10 loaded", ...
    "input_hashes.csv");

acceptance = set_numeric_max(acceptance,"SA1-MAT-001", ...
    result.direct.kkt.dimension,471,"matrices/matrix_manifest.csv");
coreDimension = size(result.recursive.core.matrix,1);
acceptance = set_numeric_max(acceptance,"SA1-MAT-002", ...
    coreDimension,16,"matrices/matrix_manifest.csv");
blocks = [result.recursive.partition.hour.dimension];
acceptance = set_boolean_result(acceptance,"SA1-BLK-001", ...
    isequal(blocks,[27 27 29]),mat2str(blocks),"equals [27 27 29]", ...
    "matrices/block_dimensions.csv");

identities = [string(lin.identity), ...
    string(result.direct.linearization_identity), ...
    string(result.recursive.linearization_identity)];
acceptance = set_boolean_result(acceptance,"SA1-LIN-001", ...
    isscalar(unique(identities)),identities(1), ...
    "direct and recursive routes share one identity", ...
    "diagnostics/linearization_identity.json");

boundaryPassed = boundary_contract_passes(index,lin);
acceptance = set_boolean_result(acceptance,"SA1-BND-001", ...
    boundaryPassed,"start_hour=8; predecessor_indices=[0 0]; "+ ...
    "terminal_equalities=2; terminal_hour=10", ...
    "no hour-7 link and two fixed-half-energy terminal equalities", ...
    "indices/soc_boundary_audit.csv");

acceptance = set_numeric_threshold(acceptance,"SA1-EQ-001", ...
    result.audit.direction_relative_error, ...
    result.audit.thresholds.DirectionRelative, ...
    "iterations/direction_comparison.csv");
acceptance = set_numeric_threshold(acceptance,"SA1-EQ-002", ...
    result.audit.recursive_kkt_relative_residual, ...
    result.audit.thresholds.RecursiveResidual, ...
    "iterations/residual_summary.csv");
directResidual = result.audit.full_kkt_relative_residual;
directHard = result.audit.thresholds.FullResidualMaximum;
directPreferred = result.audit.thresholds.FullResidualPreferred;
preferredText = "preferred_met=" + string(directResidual <= directPreferred) + ...
    "; preferred=" + compose("%.17g",directPreferred) + ...
    "; hard_maximum=" + compose("%.17g",directHard);
acceptance = set_boolean_result(acceptance,"SA1-EQ-003", ...
    directResidual <= directHard,compose("%.17g",directResidual), ...
    preferredText,"iterations/residual_summary.csv");

indexAudit = rkkt.indexing.validate_canonical_index_framework(index);
indexPassed = all(logical(indexAudit.passed)) && testAudit.all_pass;
acceptance = set_boolean_result(acceptance,"SA1-IDX-001",indexPassed, ...
    "index_checks="+height(indexAudit)+"; tests_passed="+testAudit.passed, ...
    "canonical maps reversible and A1 tests pass","indices/index_audit.csv; tests");
fixedRegression = logical(testAudit.fixed_zero_regression_pass);
fixedAudit = result.physical.fixed_zero_audit;
fixedPassed = fixedAudit.values_exact_zero && ...
    fixedAudit.directions_exact_zero && fixedRegression;
acceptance = set_boolean_result(acceptance,"SA1-IDX-002",fixedPassed, ...
    "window_fixed_zero_count="+fixedAudit.count+ ...
    "; exact_values="+string(fixedAudit.values_exact_zero)+ ...
    "; exact_directions="+string(fixedAudit.directions_exact_zero)+ ...
    "; synthetic_regression="+string(fixedRegression), ...
    "exact zero; count=0 is vacuous for real window and regression is nonvacuous", ...
    "indices/fixed_zero_audit.csv; tests/test_results.csv");

warningsAbsent = ~result.direct.diagnostics.warning_present && ...
    solver_warnings_absent(result.recursive);
numericPassed = all(string(codeScan.status) == "PASS") && warningsAbsent;
acceptance = set_boolean_result(acceptance,"SA1-NUM-001",numericPassed, ...
    "code_scan_pass="+sum(string(codeScan.status)=="PASS")+ ...
    "/"+height(codeScan)+"; warnings_absent="+string(warningsAbsent), ...
    "no prohibited call, automatic modification, warning, or fallback", ...
    "diagnostics/code_scan.csv");

execution = result.execution;
scopePassed = execution.newton_direction_count == 1 && ...
    ~execution.full_ipm_executed && ~execution.parallel_executed && ...
    ~execution.optimization_executed && execution.a1_solver_executed && ...
    ~execution.physical_dispatch_interpretation;
acceptance = set_boolean_result(acceptance,"SA1-SCOPE-001",scopePassed, ...
    "newton_directions=1; full_ipm=false; parallel=false; "+ ...
    "optimization=false; physical_interpretation=false", ...
    "matches the frozen A1 algorithm-test scope","run_manifest.json");
end

function passed = boundary_contract_passes(index,lin)
links = index.soc_link_map;
start = links.hour == 8;
terminal = links.hour == 10;
passed = nnz(start) == 2 && ...
    all(isnan(links.predecessor_hour(start))) && ...
    all(links.predecessor_soc_global_index(start) == 0) && ...
    all(links.initial_energy_fraction(start) == 0.5) && ...
    nnz(terminal & links.terminal_equality) == 2 && ...
    all(links.terminal_energy_fraction(terminal) == 0.5);
eq = index.constraint_index( ...
    string(index.constraint_index.constraint_type)=="equality",:);
terminalRows = find(eq.hour==10 & string(eq.constraint_name)=="terminal_soc");
startRows = find(eq.hour==8 & string(eq.constraint_name)=="soc_dynamics");
passed = passed && numel(startRows)==2 && numel(terminalRows)==2 && ...
    nnz(lin.A(startRows,lin.maps.q_day(13:14)) + 0.5*speye(2))==0 && ...
    nnz(lin.A(terminalRows,lin.maps.q_day(13:14)) + 0.5*speye(2))==0;
end

function passed = solver_warnings_absent(recursive)
passed = true;
for factor = recursive.thomas.factors.'
    passed = passed && ~factor{1}.warning_present;
end
passed = passed && ~recursive.core.factor.warning_present;
end

function acceptance = set_numeric_threshold(acceptance,id,value,limit,evidence)
acceptance = set_boolean_result(acceptance,id,value<=limit, ...
    compose("%.17g",value),"<= "+compose("%.17g",limit),evidence);
end

function acceptance = set_numeric_max(acceptance,id,value,expected,evidence)
acceptance = set_boolean_result(acceptance,id,value==expected,string(value), ...
    "equals "+string(expected),evidence);
end

function acceptance = set_boolean_result(acceptance,id,passed,actual,comparison,evidence)
if passed, status = "PASS"; else, status = "FAIL"; end
acceptance = rkkt.diagnostics.set_stage_a1_acceptance_result(acceptance,id,status, ...
    actual,comparison,evidence);
end
