function step = execute_stage_b2c_iteration( ...
        stateBefore,data,index,config,options)
%EXECUTE_STAGE_B2C_ITERATION Execute one formal daily-joint recursive update.

arguments
    stateBefore (1,1) struct
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.PreviousLinearizationIdentity (1,1) string = ""
    options.FullKktAuditEnabled (1,1) logical = true
    options.PrecomputedLinearization (1,1) struct = struct()
    options.LinearizationTemplate (1,1) struct = struct()
    options.DailyJointStructureTemplate (1,1) struct = struct()
    options.LinearizationUpdateMode (1,1) string {mustBeMember( ...
        options.LinearizationUpdateMode, ...
        ["recursive_blocks","cached_numeric","full_rebuild"])} = ...
        "cached_numeric"
    options.DayResponseExecutionMode (1,1) string {mustBeMember( ...
        options.DayResponseExecutionMode,["serial","parallel_processes"])} = ...
        "serial"
    options.ParallelWorkerCount (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
    options.JointMicroborderScanEnabled (1,1) logical = true
end
assert(string(stateBefore.milestone_id)=="B-2C" && ...
    all(stateBefore.l>0) && all(stateBefore.z>0), ...
    "stageB2C:iteration:State","B-2C requires an explicit positive state.");
totalTimer = tic;
timer = tic;
if isempty(fieldnames(options.PrecomputedLinearization))
    if options.LinearizationUpdateMode=="recursive_blocks"
        assert(~isempty(fieldnames(options.LinearizationTemplate)), ...
            "stageB2C:iteration:RecursiveTemplate", ...
            "The recursive-block route requires its direct template.");
        before = rkkt.model.update_stage_b2c_recursive_block_linearization( ...
            stateBefore,options.LinearizationTemplate, ...
            ChainId="B-2C-FORMAL-IPM");
    else
        before = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
            stateBefore,data,index,config,"B-2C-FORMAL-IPM");
    end
else
    before = options.PrecomputedLinearization;
    assert(string(before.milestone_id)=="B-2C" && ...
        isequal(before.state.xi,stateBefore.xi) && ...
        isequal(before.state.y,stateBefore.y) && ...
        isequal(before.state.l,stateBefore.l) && ...
        isequal(before.state.z,stateBefore.z), ...
        "stageB2C:iteration:PrecomputedLinearization", ...
        "The supplied linearization does not represent the current state.");
end
timing.linearization_before_seconds = toc(timer);
linearizationTemplate = options.LinearizationTemplate;
if options.LinearizationUpdateMode=="cached_numeric" && ...
        isempty(fieldnames(linearizationTemplate))
    linearizationTemplate = ...
        rkkt.model.build_stage_b2c_linearization_template( ...
        before,data,index,config);
end
if strlength(options.PreviousLinearizationIdentity)>0
    assert(before.identity~=options.PreviousLinearizationIdentity, ...
        "stageB2C:iteration:StaleLinearization", ...
        "Each B-2C iteration must rebuild a distinct linearization.");
end
timer = tic;
recursive = rkkt.solver.solve_stage_b2c_daily_joint_direction(before, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance= ...
        config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses= ...
        config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation= ...
        config.compensated_core_accumulation, ...
    DailyJointStructureTemplate=options.DailyJointStructureTemplate, ...
    JointMicroborderEnabled=options.JointMicroborderScanEnabled, ...
    DayResponseExecutionMode=options.DayResponseExecutionMode, ...
    ParallelWorkerCount=options.ParallelWorkerCount);
timing.recursive_seconds = toc(timer);
highLowStateUpdateRequired = recursive.diagnostics. ...
    high_low_state_update_required;
assert(~highLowStateUpdateRequired || ~options.FullKktAuditEnabled, ...
    "stageB2C:iteration:HighLowFullAudit", ...
    "A joint high/low micro-border direction requires the recursive-only audit route.");
if options.FullKktAuditEnabled
    timer = tic;
    fullAudit = rkkt.solver.solve_stage_b2b_full_kkt_direction(before);
    timing.full_kkt_audit_seconds = toc(timer);
else
    fullAudit = skipped_full_audit(before);
    timing.full_kkt_audit_seconds = 0;
end
if options.FullKktAuditEnabled
    comparison = rkkt.solver.verify_stage_b2b_direction_equivalence( ...
        fullAudit,recursive,before, ...
        DirectionRelative=config.direction_relative_error_tolerance, ...
        RecursiveResidual=config.recursive_full_kkt_residual_tolerance, ...
        FullResidual=config.full_kkt_residual_tolerance);
    assert(comparison.all_pass, ...
        "stageB2C:iteration:DirectionAudit", ...
        "The formal recursive direction failed its independent full-KKT audit.");
else
    comparison = skipped_direction_audit(before,recursive);
end
assert(recursive.no_full_direction_fallback && ...
    ~recursive.full_direction_consumed, ...
    "stageB2C:iteration:DirectionRoute", ...
    "The recursive route consumed or fell back to a full-KKT direction.");

timer = tic;
if highLowStateUpdateRequired
    primalStep = rkkt.solver.compute_fraction_to_boundary_step_high_low( ...
        before.l,recursive.components_high.l, ...
        recursive.components_low.l,config.fraction_to_boundary);
    dualStep = rkkt.solver.compute_fraction_to_boundary_step_high_low( ...
        before.z,recursive.components_high.z, ...
        recursive.components_low.z,config.fraction_to_boundary);
else
    primalStep = rkkt.solver.compute_fraction_to_boundary_step( ...
        before.l,recursive.components.l,config.fraction_to_boundary);
    dualStep = rkkt.solver.compute_fraction_to_boundary_step( ...
        before.z,recursive.components.z,config.fraction_to_boundary);
end
primalStep = annotate_limiter(primalStep,index);
dualStep = annotate_limiter(dualStep,index);
if highLowStateUpdateRequired
    [ordinaryStateAfter,stateUpdateAudit,stateDisplacementHigh, ...
        stateDisplacementLow] = ...
        rkkt.solver.update_primal_dual_state_high_low( ...
        before.state,recursive.components_high,recursive.components_low, ...
        primalStep.alpha,dualStep.alpha);
else
    ordinaryStateAfter = rkkt.solver.update_primal_dual_state( ...
        before.state,recursive.components, ...
        primalStep.alpha,dualStep.alpha);
    stateUpdateAudit = struct( ...
        "method","binary64_direction_update", ...
        "high_low_direction_consumed",false, ...
        "maximum_relative_difference_from_naive",0);
    stateDisplacementHigh = struct();
    stateDisplacementLow = struct();
end
waterAfter = struct();
if options.LinearizationUpdateMode=="cached_numeric"
    waterAfter = rkkt.model.evaluate_stage_b2c_water_template( ...
        ordinaryStateAfter.xi,linearizationTemplate);
elseif options.LinearizationUpdateMode=="recursive_blocks"
    waterAfter = rkkt.model.evaluate_stage_b2c_recursive_water_template( ...
        ordinaryStateAfter.xi,linearizationTemplate);
end
if highLowStateUpdateRequired
    [waterCorrection,waterAfter] = ...
        rkkt.solver.compute_stage_b2c_water_slack_second_order_correction( ...
        before,recursive.components.xi,primalStep.alpha, ...
        ordinaryStateAfter,data,index,config, ...
        PrecomputedWaterAfter=waterAfter, ...
        AcceptedPrimalDisplacementHigh=stateDisplacementHigh.xi, ...
        AcceptedPrimalDisplacementLow=stateDisplacementLow.xi);
else
    [waterCorrection,waterAfter] = ...
        rkkt.solver.compute_stage_b2c_water_slack_second_order_correction( ...
        before,recursive.components.xi,primalStep.alpha, ...
        ordinaryStateAfter,data,index,config, ...
        PrecomputedWaterAfter=waterAfter);
end
waterRows = waterCorrection.water_rows;
nonwaterRows = true(numel(ordinaryStateAfter.l),1);
nonwaterRows(waterRows) = false;
stateAfter = ordinaryStateAfter;
stateAfter.l(waterRows) = waterCorrection.corrected_l;
assert(isequal(stateAfter.xi,ordinaryStateAfter.xi) && ...
    isequal(stateAfter.y,ordinaryStateAfter.y) && ...
    isequal(stateAfter.z,ordinaryStateAfter.z) && ...
    isequal(stateAfter.l(nonwaterRows),ordinaryStateAfter.l(nonwaterRows)), ...
    "stageB2C:iteration:WaterCorrectionScope", ...
    "The correction changed a component outside the configured water slacks.");
revision = stateBefore.state_revision+1;
stateAfter.iteration_index = revision;
stateAfter.state_revision = revision;
stateAfter.newton_direction_number = revision;
stateAfter.completed_newton_direction_count = revision;
stateAfter.stage_id = "stage_B";
stateAfter.milestone_id = "B-2C";
stateAfter.nonzero_hessian_gate_state = false;
stateAfter.optimization_state = true;
timing.step_and_state_update_seconds = toc(timer);
assert(all(isfinite([stateAfter.xi;stateAfter.y;stateAfter.l;stateAfter.z])) && ...
    all(stateAfter.l>0) && all(stateAfter.z>0), ...
    "stageB2C:iteration:Positivity", ...
    "The accepted B-2C state is nonfinite or not strictly positive.");
timer = tic;
if options.LinearizationUpdateMode=="cached_numeric"
    after = rkkt.model.update_stage_b2c_scaled_objective_linearization( ...
        stateAfter,linearizationTemplate, ...
        PrecomputedWater=waterAfter,ChainId="B-2C-FORMAL-IPM");
elseif options.LinearizationUpdateMode=="recursive_blocks"
    after = rkkt.model.update_stage_b2c_recursive_block_linearization( ...
        stateAfter,linearizationTemplate, ...
        PrecomputedWater=waterAfter,ChainId="B-2C-FORMAL-IPM");
else
    after = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
        stateAfter,data,index,config,"B-2C-FORMAL-IPM");
end
metricsBefore = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(before);
metricsAfter = rkkt.diagnostics.compute_stage_b2c_unitized_metrics(after);
timing.linearization_after_seconds = toc(timer);

ordinaryBaseResidual = ...
    rkkt.model.apply_stage_b2c_inequality_jacobian( ...
        before,ordinaryStateAfter.xi);
ordinaryBaseResidual = ordinaryBaseResidual(nonwaterRows)+ ...
    before.constraints.ineq_offset(nonwaterRows)+ ...
    ordinaryStateAfter.l(nonwaterRows);
uncorrectedMetricsAfter = struct("primal_inequality_inf",max( ...
    norm(ordinaryBaseResidual,inf), ...
    waterCorrection.maximum_trial_residual));
waterResidualRebuildClosure = norm(after.r_ineq(waterRows)- ...
    waterCorrection.expected_corrected_residual,inf);
assert(waterResidualRebuildClosure<= ...
    max(waterCorrection.audit.closure_tolerance), ...
    "stageB2C:iteration:WaterCorrectionRebuild", ...
    "The rebuilt formal water residual lost the correction identity.");

ordinaryUpdateErrors = [ ...
    relative_error(ordinaryStateAfter.xi,stateBefore.xi+ ...
        primalStep.alpha*recursive.components.xi)
    relative_error(ordinaryStateAfter.l,stateBefore.l+ ...
        primalStep.alpha*recursive.components.l)
    relative_error(ordinaryStateAfter.y,stateBefore.y+ ...
        dualStep.alpha*recursive.components.y)
    relative_error(ordinaryStateAfter.z,stateBefore.z+ ...
        dualStep.alpha*recursive.components.z)];
expectedCorrectedL = ordinaryStateAfter.l;
expectedCorrectedL(waterRows) = waterCorrection.corrected_l;
updateErrors = [ ...
    relative_error(stateAfter.xi,ordinaryStateAfter.xi)
    relative_error(stateAfter.l,expectedCorrectedL)
    relative_error(stateAfter.y,ordinaryStateAfter.y)
    relative_error(stateAfter.z,ordinaryStateAfter.z)];
ordinaryUpdatePass = max(ordinaryUpdateErrors)<=16*eps;
if highLowStateUpdateRequired
    ordinaryUpdatePass = stateUpdateAudit.high_low_direction_consumed;
end
assert(ordinaryUpdatePass && max(updateErrors)<=16*eps, ...
    "stageB2C:iteration:UpdateClosure", ...
    "The configured ordinary or water-corrected state update is inconsistent.");
fixed = recursive.fixed_zero;
assert(fixed.count==config.expected_stage_a_fixed_zero_count && ...
    fixed.all_exact_zero && ...
    fixed.maximum_absolute_value==0 && ...
    fixed.maximum_absolute_direction==0, ...
    "stageB2C:iteration:FixedZero", ...
    "All configured fixed-zero values/directions must remain exact zero.");
if isfield(before,"storage_mode") && ...
        before.storage_mode=="recursive_daily_blocks"
    waterHessianNnz = sum(arrayfun(@(value)nnz(value.H),before.blocks.day));
    waterHessianFroNorm = sqrt(sum(arrayfun( ...
        @(value)norm(value.H,"fro")^2,before.blocks.day)));
    waterHessianSymmetry = max(arrayfun(@(value) ...
        norm(value.H-value.H.',"fro")/max(1,norm(value.H,"fro")), ...
        before.blocks.day));
else
    waterHessian = before.H-before.objective.hessian;
    waterHessianNnz = nnz(waterHessian);
    waterHessianFroNorm = norm(waterHessian,"fro");
    waterHessianSymmetry = norm(waterHessian-waterHessian.',"fro")/ ...
        max(1,norm(waterHessian,"fro"));
end
timing.total_seconds = toc(totalTimer);
step = struct("state_before",stateBefore,"state_after",stateAfter, ...
    "linearization_before",before,"linearization_after",after, ...
    "metrics_before",metricsBefore,"metrics_after",metricsAfter, ...
    "uncorrected_metrics_after",uncorrectedMetricsAfter, ...
    "recursive",recursive,"full_audit",fullAudit, ...
    "direction_audit",comparison,"primal_step",primalStep, ...
    "dual_step",dualStep,"update_relative_errors",updateErrors, ...
    "ordinary_state_update_relative_errors",ordinaryUpdateErrors, ...
    "water_slack_second_order_correction",waterCorrection, ...
    "water_residual_rebuild_closure",waterResidualRebuildClosure, ...
    "water_slack_second_order_correction_applied",true, ...
    "water_slack_second_order_correction_scope_count",numel(waterRows), ...
    "only_water_slacks_corrected",true, ...
    "fixed_zero",fixed,"water_hessian_nnz",waterHessianNnz, ...
    "water_hessian_fro_norm",waterHessianFroNorm, ...
    "water_hessian_symmetry_relative",waterHessianSymmetry, ...
    "factorization_scope_identity",before.identity, ...
    "factor_reused_across_iterations",false, ...
    "high_low_state_update_required",highLowStateUpdateRequired, ...
    "high_low_state_update_used", ...
        stateUpdateAudit.high_low_direction_consumed, ...
    "state_update_audit",stateUpdateAudit, ...
    "full_kkt_audit_executed",options.FullKktAuditEnabled, ...
    "recursive_direction_is_formal",true, ...
    "no_full_direction_fallback",true, ...
    "full_direction_consumed_by_recursive",false, ...
    "linearization_update_mode",options.LinearizationUpdateMode, ...
    "fixed_linearization_structure_reused", ...
        ismember(options.LinearizationUpdateMode, ...
            ["cached_numeric","recursive_blocks"]), ...
    "timing",timing);
end

function audit = skipped_full_audit(lin)
audit = struct("executed",false,"role","not_executed", ...
    "linearization_identity",lin.identity,"direction",zeros(0,1), ...
    "kkt",struct("dimension",lin.counts.full_kkt));
end

function comparison = skipped_direction_audit(lin,recursive)
nanComponents = struct("xi",NaN,"y",NaN,"l",NaN,"z",NaN);
comparison = struct("executed",false,"all_pass",true, ...
    "direction_relative_error",NaN, ...
    "component_relative_errors",nanComponents, ...
    "recursive_kkt_relative_residual", ...
        recursive.diagnostics.candidate_kkt_relative_residual, ...
    "full_kkt_relative_residual",NaN, ...
    "linearization_identity",lin.identity, ...
    "reason","disabled_for_30_day_recursive_experiment");
end

function step = annotate_limiter(step,index)
if isfield(index,"version") && ...
        ismember(string(index.version),[ ...
            "stage-B2C-recursive-runtime-package-v1.0", ...
            "stage-B2C-recursive-numerical-payload-v1.0"])
    description = rkkt.model.describe_stage_b2c_runtime_inequality( ...
        index.runtime,step.limiting_index);
    step.limiting_constraint_id = description.constraint_id;
    step.limiting_day = description.day;
    step.limiting_hour = description.hour;
    step.limiting_asset_type = description.asset_type;
    step.limiting_asset_id = description.asset_id;
    return
end
rows = index.constraint_index( ...
    string(index.constraint_index.constraint_type)=="inequality",:);
if step.limiting_index==0
    step.limiting_constraint_id = "";
    step.limiting_day = NaN;
    step.limiting_hour = NaN;
    step.limiting_asset_type = "";
    step.limiting_asset_id = NaN;
    return
end
row = rows(step.limiting_index,:);
step.limiting_constraint_id = string(row.constraint_id);
step.limiting_day = row.day;
step.limiting_hour = row.hour;
step.limiting_asset_type = string(row.asset_type);
step.limiting_asset_id = row.asset_id;
end

function value = relative_error(actual,expected)
value = norm(actual-expected,inf)/ ...
    max([1,norm(actual,inf),norm(expected,inf)]);
end
