function evidence = export_stage_a4_rns1_stable_v2_evidence( ...
        projectRoot,outputDirectory,options)
%EXPORT_STAGE_A4_RNS1_STABLE_V2_EVIDENCE Persist the stable stress result.
%
% This is a versioned test fixture, not a formal A4 run.  It consumes the
% immutable authority-v1 round-19 input and the committed RNS solver,
% performs no state update, and refuses to overwrite an existing fixture.

arguments
    projectRoot (1,1) string
    outputDirectory (1,1) string
    options.ImplementationCommit (1,1) string
    options.ToolingCommit (1,1) string
end
assert(strlength(options.ImplementationCommit)==40 && ...
    strlength(options.ToolingCommit)==40, ...
    "stageA4:rns1:StableEvidenceCommit", ...
    "Stable-v2 evidence requires full implementation and tooling commits.");
projectRoot = canonical_folder(projectRoot);
outputDirectory = string(outputDirectory);
expectedOutput = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_RNS_1_stable_v2");
assert(canonical_candidate(outputDirectory)== ...
    canonical_candidate(expectedOutput), ...
    "stageA4:rns1:StableEvidencePath", ...
    "Stable-v2 evidence must use its controlled fixture directory.");
assert(~isfolder(outputDirectory), ...
    "stageA4:rns1:StableEvidenceOverwrite", ...
    "Refusing to overwrite stable-v2 evidence: %s",outputDirectory);
stagingDirectory = outputDirectory+".building";
assert(~isfolder(stagingDirectory), ...
    "stageA4:rns1:StableEvidenceStaging", ...
    "Stable-v2 staging already exists: %s",stagingDirectory);
[created,message] = mkdir(stagingDirectory);
assert(created,"stageA4:rns1:StableEvidenceDirectory", ...
    "Unable to create stable-v2 staging %s: %s", ...
    stagingDirectory,message);
cleanup = onCleanup(@()cleanup_staging( ...
    stagingDirectory,outputDirectory));

result = main_stage_A4_RNS_1();
assert(result.milestone_status=="PASS" && ...
    result.all_blocking_pass && result.stage_status=="READY" && ...
    result.execution.state_update_count==0 && ...
    result.execution.full_kkt_direction_solve_count==0 && ...
    ~result.execution.formal_a4_run_created && ...
    ~result.execution.d2a_rerun_executed, ...
    "stageA4:rns1:StableEvidenceResult", ...
    "Only a passing isolated RNS result may become stable-v2 evidence.");

authorityRoot = fullfile(projectRoot,"tests","fixtures", ...
    "stage_A4_RNS_1_authority_v1");
authorityManifest = fullfile(authorityRoot, ...
    "stage_A4_RNS_1_authority_artifact_sha256.csv");
authorityMat = fullfile(authorityRoot, ...
    "stage_A4_RNS_1_round19_authority_v1.mat");
authorityManifestSha256 = rkkt.data.compute_sha256_file(authorityManifest);
authorityMatSha256 = rkkt.data.compute_sha256_file(authorityMat);
assert(authorityManifestSha256== ...
    "391517925f12d5654d2cc46de187e8807420e5761a8bba203e2010686e076fd5" && ...
    authorityMatSha256== ...
    "14c5501a17fc317a5653b8d55ac29f6b103ddcfb3004aef807acff6bde4e62b3", ...
    "stageA4:rns1:StableEvidenceAuthority", ...
    "Authority-v1 roots changed before stable-v2 export.");

paths = stable_paths(stagingDirectory);
stableDirection = result.first.direction;
stableComponents = result.first.components;
actual = result.actual;
blocking = result.blocking;
operatorAudit = result.operator_audit;
determinism = result.determinism;
refinementSummary = result.refinement;
refinementDetail = collect_refinement_detail(result.first);
dayIds = reshape([result.first.daily_responses.day_id],[],1);
day17Position = find(dayIds==17);
assert(isscalar(day17Position), ...
    "stageA4:rns1:StableEvidenceDay17", ...
    "Stable evidence requires exactly one day-17 response.");
day17Response = result.first.daily_responses(day17Position);
coreEvidence = struct( ...
    "matrix",result.first.core.matrix, ...
    "rhs",result.first.core.rhs, ...
    "solution",result.first.core.solution, ...
    "diagnostics",result.first.core.diagnostics);
save(paths.mat,"stableDirection","stableComponents","actual", ...
    "blocking","operatorAudit","determinism","refinementSummary", ...
    "refinementDetail","day17Response","coreEvidence","-v7");
rkkt.artifacts.write_table_csv_17g(paths.refinement,refinementSummary);
metricTable = make_metric_table(result);
rkkt.artifacts.write_table_csv_17g(paths.metrics,metricTable);

generationCommand = ...
    "powershell -NoProfile -ExecutionPolicy Bypass -File "+ ...
    "scripts/export_stage_A4_RNS_1_stable_v2.ps1 "+ ...
    "-ImplementationCommit "+options.ImplementationCommit;
write_text(paths.command,generationCommand+newline);
metadata = struct( ...
    "milestone","A4-RNS-1", ...
    "fixture_version","stable-v2", ...
    "authority_source_commit", ...
        "58b2b3645b79c71460ff0de1a03033c319829cd6", ...
    "authority_manifest_sha256",authorityManifestSha256, ...
    "authority_mat_sha256",authorityMatSha256, ...
    "implementation_commit",options.ImplementationCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "generation_command",generationCommand, ...
    "stage_id","stage_A4", ...
    "stage_status","READY", ...
    "d2a_original_status","FAIL_RETRYABLE", ...
    "day17_response_symmetry_relative", ...
        actual.day17_response_symmetry_relative, ...
    "direction_relative_error",actual.direction_relative_error, ...
    "xi_relative_error",actual.xi_relative_error, ...
    "y_relative_error",actual.y_relative_error, ...
    "l_relative_error",actual.l_relative_error, ...
    "z_relative_error",actual.z_relative_error, ...
    "recursive_full_kkt_relative_residual", ...
        actual.recursive_full_kkt_relative_residual, ...
    "direct_full_kkt_relative_residual", ...
        actual.direct_full_kkt_relative_residual, ...
    "engineering_target",actual.engineering_target, ...
    "numerical_margin_status",actual.numerical_margin_status, ...
    "minimum_l",actual.minimum_l, ...
    "minimum_z",actual.minimum_z, ...
    "recursive_direction_repeats",2, ...
    "state_update_count",0, ...
    "full_kkt_direction_solve_count",0, ...
    "complete_kkt_direction_fallback_used",false, ...
    "formal_a4_run_created",false, ...
    "d2a_rerun_executed",false, ...
    "hundred_round_run_executed",false, ...
    "full_ipm_executed",false, ...
    "optimization_executed",false, ...
    "parallel_executed",false, ...
    "stage_b_entered",false);
metadata.mat_file = leaf(paths.mat);
metadata.mat_sha256 = rkkt.data.compute_sha256_file(paths.mat);
metadata.refinement_file = leaf(paths.refinement);
metadata.refinement_sha256 = rkkt.data.compute_sha256_file(paths.refinement);
metadata.metrics_file = leaf(paths.metrics);
metadata.metrics_sha256 = rkkt.data.compute_sha256_file(paths.metrics);
metadata.command_file = leaf(paths.command);
metadata.command_sha256 = rkkt.data.compute_sha256_file(paths.command);
write_text(paths.metadata,string(jsonencode( ...
    metadata,PrettyPrint=true))+newline);

artifactPath = [leaf(paths.mat);leaf(paths.refinement); ...
    leaf(paths.metrics);leaf(paths.command);leaf(paths.metadata)];
sha256 = strings(numel(artifactPath),1);
for k = 1:numel(artifactPath)
    sha256(k) = rkkt.data.compute_sha256_file( ...
        fullfile(stagingDirectory,artifactPath(k)));
end
manifest = table(artifactPath,sha256, ...
    'VariableNames',{'artifact_path','sha256'});
rkkt.artifacts.write_table_csv_17g(paths.manifest,manifest);
[moved,message] = movefile(stagingDirectory,outputDirectory);
assert(moved,"stageA4:rns1:StableEvidenceFinalize", ...
    "Unable to finalize stable-v2 fixture %s: %s", ...
    outputDirectory,message);
finalAudit = verify_final(outputDirectory,manifest);
evidence = struct( ...
    "output_directory",outputDirectory, ...
    "implementation_commit",options.ImplementationCommit, ...
    "tooling_commit",options.ToolingCommit, ...
    "manifest",manifest, ...
    "final_audit",finalAudit, ...
    "all_pass",finalAudit.all_pass);
clear cleanup
end

function detail = collect_refinement_detail(recursive)
detail = repmat(struct("object_type","","day_id",0,"diagnostics", ...
    struct()),numel(recursive.daily_thomas)+1,1);
for d = 1:numel(recursive.daily_thomas)
    detail(d).object_type = "day_chain";
    detail(d).day_id = recursive.daily_responses(d).day_id;
    detail(d).diagnostics = recursive.daily_thomas(d).diagnostics. ...
        residual_refinement;
end
detail(end).object_type = "global_core";
detail(end).day_id = 0;
detail(end).diagnostics = recursive.core.diagnostics. ...
    residual_refinement;
end

function result = make_metric_table(audit)
checkId = [ ...
    "day17_response_symmetry"
    "overall_direction_relative_error"
    "xi_direction_relative_error"
    "y_direction_relative_error"
    "l_direction_relative_error"
    "z_direction_relative_error"
    "recursive_full_kkt_relative_residual"
    "direct_full_kkt_relative_residual"
    "minimum_l"
    "minimum_z"
    "no_full_direction_fallback"
    "deterministic_repeat"];
actual = [ ...
    audit.actual.day17_response_symmetry_relative
    audit.actual.direction_relative_error
    audit.actual.xi_relative_error
    audit.actual.y_relative_error
    audit.actual.l_relative_error
    audit.actual.z_relative_error
    audit.actual.recursive_full_kkt_relative_residual
    audit.actual.direct_full_kkt_relative_residual
    audit.actual.minimum_l
    audit.actual.minimum_z
    double(audit.blocking.no_full_direction_fallback)
    double(audit.blocking.deterministic_repeat)];
threshold = [1e-12;repmat(1e-10,7,1);0;0;1;1];
comparison = [repmat("<=",8,1);">";">";"==";"=="];
passed = [actual(1:8)<=threshold(1:8); ...
    actual(9:10)>0;actual(11:12)==1];
result = table(checkId,actual,threshold,comparison,passed, ...
    'VariableNames',{'check_id','actual','threshold', ...
    'comparison','passed'});
end

function paths = stable_paths(root)
paths = struct( ...
    "mat",fullfile(root,"stage_A4_RNS_1_stable_v2.mat"), ...
    "refinement",fullfile(root, ...
        "stage_A4_RNS_1_stable_v2_refinement.csv"), ...
    "metrics",fullfile(root, ...
        "stage_A4_RNS_1_stable_v2_metrics.csv"), ...
    "command",fullfile(root, ...
        "stage_A4_RNS_1_stable_v2_generation_command.txt"), ...
    "metadata",fullfile(root, ...
        "stage_A4_RNS_1_stable_v2.metadata.json"), ...
    "manifest",fullfile(root, ...
        "stage_A4_RNS_1_stable_v2_artifact_sha256.csv"));
end

function audit = verify_final(root,manifest)
artifactPath = string(manifest.artifact_path);
expectedSha256 = lower(string(manifest.sha256));
actualSha256 = strings(numel(artifactPath),1);
exists = false(numel(artifactPath),1);
for k = 1:numel(artifactPath)
    pathValue = fullfile(root,artifactPath(k));
    exists(k) = isfile(pathValue);
    if exists(k)
        actualSha256(k) = rkkt.data.compute_sha256_file(pathValue);
    end
end
paths = stable_paths(root);
variables = whos("-file",paths.mat);
schema = sort(string({variables.name}).');
expectedSchema = sort([ ...
    "actual"
    "blocking"
    "coreEvidence"
    "day17Response"
    "determinism"
    "operatorAudit"
    "refinementDetail"
    "refinementSummary"
    "stableComponents"
    "stableDirection"]);
audit = struct( ...
    "all_files_exist",all(exists), ...
    "all_hashes_exact",all(actualSha256==expectedSha256), ...
    "mat_schema_exact",isequal(schema,expectedSchema));
audit.all_pass = audit.all_files_exist && audit.all_hashes_exact && ...
    audit.mat_schema_exact;
end

function cleanup_staging(stagingDirectory,outputDirectory)
if ~isfolder(stagingDirectory)
    return
end
stagingDirectory = canonical_candidate(stagingDirectory);
outputDirectory = canonical_candidate(outputDirectory);
[stagingParent,stagingName,stagingExtension] = ...
    fileparts(stagingDirectory);
[outputParent,outputName,outputExtension] = ...
    fileparts(outputDirectory);
safe = stagingParent==outputParent && ...
    stagingName+stagingExtension== ...
        outputName+outputExtension+".building" && ...
    endsWith(stagingDirectory,".building");
if safe
    rmdir(stagingDirectory,"s");
end
end

function root = canonical_folder(root)
assert(isfolder(root),"stageA4:rns1:StableEvidenceRoot", ...
    "Project root does not exist: %s",root);
root = string(char(java.io.File(char(root)).getCanonicalPath()));
end

function value = canonical_candidate(value)
value = string(char(java.io.File(char(value)).getCanonicalPath()));
end

function value = leaf(pathValue)
[~,name,extension] = fileparts(pathValue);
value = string(name)+string(extension);
end

function write_text(pathValue,text)
[fileId,message] = fopen(pathValue,"w","n","UTF-8");
assert(fileId>=0,"stageA4:rns1:StableEvidenceWrite", ...
    "Unable to open %s: %s",pathValue,message);
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,"%s",text);
clear cleanup
end
