function environment = inspect_stage_b1_environment()
%INSPECT_STAGE_B1_ENVIRONMENT Probe the non-solver Stage B-1 environment.
%
% The checks are deliberately limited to facilities consumed by B-1:
% MATLAB R2024a, spreadsheet/data I/O, sparse diagonal construction, and
% deterministic OOXML packaging.  No KKT system, Newton direction, IPM,
% parallel pool, or optimization is assembled or executed here.

rows = repmat(empty_row(),0,1);
checkedAt = now_text();

releaseName = string(version("-release"));
rows(end+1) = make_row("MATLAB_RELEASE","MATLAB",true,"R2024a", ...
    sprintf("%s (%s)",string(version),releaseName), ...
    releaseName=="2024a",checkedAt,sprintf("arch=%s",computer("arch")));

spreadsheetFunctions = ["readcell","readtable","detectImportOptions"];
spreadsheetAvailable = all(arrayfun(@(name) ...
    exist(char(name),"file")==2 || exist(char(name),"builtin")==5, ...
    spreadsheetFunctions));
rows(end+1) = make_row("SPREADSHEET_IO", ...
    "受控 Excel 标签式读取依赖",true, ...
    "readcell/readtable/detectImportOptions available", ...
    strjoin(spreadsheetFunctions+"="+ ...
        string(arrayfun(@(name)exist(char(name),"file")>0 || ...
        exist(char(name),"builtin")>0,spreadsheetFunctions)),"; "), ...
    spreadsheetAvailable,checkedAt, ...
    "Only capability metadata is inspected; no workbook is modified.");

try
    diagonal = (1:24).';
    matrix = spdiags(diagonal,0,24,24);
    sparsePassed = issparse(matrix) && nnz(matrix)==24 && ...
        isequal(full(diag(matrix)),diagonal);
    rows(end+1) = make_row("SPARSE_DIAGONAL", ...
        "解析 Hessian 稀疏对角表示",true, ...
        "24-by-24 sparse diagonal with 24 nonzeros", ...
        sprintf("rows=%d; columns=%d; nnz=%d; sparse=%d", ...
        size(matrix,1),size(matrix,2),nnz(matrix),issparse(matrix)), ...
        sparsePassed,checkedAt, ...
        "Construction audit only; no factorization or solve is performed.");
catch cause
    rows(end+1) = make_row("SPARSE_DIAGONAL", ...
        "解析 Hessian 稀疏对角表示",true,"available","error",false, ...
        checkedAt,string(cause.identifier)+": "+string(cause.message));
end

packageFunctions = ["zip","unzip","xmlread"];
packageAvailable = all(arrayfun(@(name) ...
    exist(char(name),"file")==2 || exist(char(name),"builtin")==5, ...
    packageFunctions));
rows(end+1) = make_row("OOXML_PACKAGE", ...
    "中文 DOCX 打包与结构验证依赖",true, ...
    "zip/unzip/xmlread available", ...
    strjoin(packageFunctions+"="+ ...
        string(arrayfun(@(name)exist(char(name),"file")>0 || ...
        exist(char(name),"builtin")>0,packageFunctions)),"; "), ...
    packageAvailable,checkedAt, ...
    "Capability metadata only; formal report generation is a later step.");

rows(end+1) = make_row("SOLVER_EXECUTION", ...
    "KKT、递推方向与 IPM",true,"not executed","not executed",true, ...
    checkedAt,"Stage B-1 is a data and analytic-derivative baseline only.");
rows(end+1) = make_row("PARALLEL_EXECUTION", ...
    "并行执行",true,"not executed","not executed",true,checkedAt, ...
    "No parpool, parfor, or parallel task is started by B-1.");

environment = struct2table(rows);
end

function row = empty_row()
row = struct("check_id","","component","","blocking",true, ...
    "expected","","actual","","status","FAIL","available",false, ...
    "checked_at","","details","");
end

function row = make_row(id,component,blocking,expected,actual, ...
        available,checkedAt,details)
row = empty_row();
row.check_id = char(id);
row.component = char(component);
row.blocking = logical(blocking);
row.expected = char(expected);
row.actual = char(actual);
row.available = logical(available);
row.checked_at = char(checkedAt);
row.details = char(details);
if row.available
    row.status = "PASS";
elseif ~row.blocking
    row.status = "NOT_APPLICABLE";
end
end

function value = now_text()
value = string(datetime("now","TimeZone","Asia/Shanghai", ...
    "Format","yyyy-MM-dd'T'HH:mm:ssXXX"));
end
