function frozen = load_stage_b2c_daily_joint_frozen_points( ...
        projectRoot,sourceRunId)
%LOAD_STAGE_B2C_DAILY_JOINT_FROZEN_POINTS Rebuild directions 34 and 35.
%
% Project data, canonical index, configuration, and checkpoint states are
% loaded only from existing MAT/run evidence.  The two rebuilt
% linearizations must reproduce the historical checkpoint fingerprints.

arguments
    projectRoot (1,1) string
    sourceRunId (1,1) string = ...
        "20260807_145804_stage_B_2C_4168a6e9"
end

sourceRoot = fullfile(projectRoot,"runs",sourceRunId);
dataPath = fullfile(projectRoot,"src","+rkkt","+data", ...
    "+validation","数据导入模块输出.mat");
gatePath = fullfile(sourceRoot,"diagnostics", ...
    "nonzero_water_hessian_gate.mat");
failurePath = fullfile(sourceRoot,"checkpoints", ...
    "failure_iteration_035.mat");
assert(isfolder(sourceRoot) && isfile(dataPath) && isfile(gatePath) && ...
    isfile(failurePath), ...
    "stageB2C:dailyJoint:FrozenEvidenceMissing", ...
    "One or more frozen B-2C evidence paths are missing.");

sourceManifest = jsondecode(fileread(fullfile(sourceRoot,"run_manifest.json")));
assert(string(sourceManifest.run_id)==sourceRunId && ...
    string(sourceManifest.status)=="FAIL_RETRYABLE" && ...
    double(sourceManifest.accepted_iteration_count)==34, ...
    "stageB2C:dailyJoint:SourceManifest", ...
    "The source run is not the controlled 34-update failure run.");

loadedData = load(dataPath,"moduleResult");
assert(isfield(loadedData,"moduleResult") && ...
    isfield(loadedData.moduleResult,"output") && ...
    isfield(loadedData.moduleResult.output,"projectData"), ...
    "stageB2C:dailyJoint:DataModule", ...
    "The PKG data-module MAT does not contain projectData.");
data = loadedData.moduleResult.output.projectData;
clear loadedData

loadedGate = load(gatePath,"gate");
assert(isfield(loadedGate,"gate") && ...
    isfield(loadedGate.gate,"linearization"), ...
    "stageB2C:dailyJoint:Gate", ...
    "The source gate MAT does not contain its linearization.");
index = loadedGate.gate.linearization.index;
config = loadedGate.gate.linearization.config;
clear loadedGate

sourceContext = struct( ...
    "checkpoints_dir",fullfile(sourceRoot,"checkpoints"), ...
    "checkpoint_manifest_path",fullfile(sourceRoot,"checkpoints", ...
        "checkpoint_manifest.csv"));
[controlCheckpoint,controlRecord] = ...
    rkkt.artifacts.load_stage_b2c_checkpoint(sourceContext,33);
[stressCheckpoint,stressRecord] = ...
    rkkt.artifacts.load_stage_b2c_checkpoint(sourceContext,34);

failureLoaded = load(failurePath,"state_before_failure","failure");
failureFingerprint = ...
    rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint( ...
        failureLoaded.state_before_failure);
assert(failureFingerprint==string(stressRecord.state_fingerprint) && ...
    string(failureLoaded.failure.identifier)== ...
        "stageB2C:iteration:DirectionAudit", ...
    "stageB2C:dailyJoint:FailureState", ...
    "The failure state is not the state stored by checkpoint revision 34.");

controlLin = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    controlCheckpoint.state,data,index,config,"B-2C-FORMAL-IPM");
stressLin = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    stressCheckpoint.state,data,index,config,"B-2C-FORMAL-IPM");
controlFingerprint = rkkt.diagnostics.compute_stage_a4_rns1_fingerprint( ...
    controlLin,"linearization");
stressFingerprint = rkkt.diagnostics.compute_stage_a4_rns1_fingerprint( ...
    stressLin,"linearization");
assert(controlFingerprint==string(controlRecord.linearization_fingerprint) && ...
    stressFingerprint==string(stressRecord.linearization_fingerprint), ...
    "stageB2C:dailyJoint:LinearizationFingerprint", ...
    "A rebuilt frozen linearization differs from its checkpoint fingerprint.");

frozen = struct();
frozen.source_run_id = sourceRunId;
frozen.source_run_root = string(sourceRoot);
frozen.source_manifest = sourceManifest;
frozen.data_path = string(dataPath);
frozen.gate_path = string(gatePath);
frozen.failure_path = string(failurePath);
frozen.data_path_sha256 = rkkt.data.compute_sha256_file(dataPath);
frozen.gate_path_sha256 = rkkt.data.compute_sha256_file(gatePath);
frozen.failure_path_sha256 = rkkt.data.compute_sha256_file(failurePath);
frozen.data = data;
frozen.index = index;
frozen.config = config;
frozen.control = make_point("control",33,34,controlCheckpoint, ...
    controlRecord,controlLin,controlFingerprint);
frozen.stress = make_point("stress",34,35,stressCheckpoint, ...
    stressRecord,stressLin,stressFingerprint);
frozen.failure = failureLoaded.failure;
end

function point = make_point(name,revision,directionNumber,checkpoint, ...
        record,linearization,fingerprint)
point = struct("name",name,"checkpoint_revision",revision, ...
    "direction_number",directionNumber,"checkpoint",checkpoint, ...
    "checkpoint_record",record,"state",checkpoint.state, ...
    "linearization",linearization, ...
    "state_fingerprint",string(record.state_fingerprint), ...
    "stored_linearization_fingerprint", ...
        string(record.linearization_fingerprint), ...
    "rebuilt_linearization_fingerprint",fingerprint, ...
    "fingerprint_match", ...
        fingerprint==string(record.linearization_fingerprint));
end
