function issues = new_stage_a2_issue_log()
%NEW_STAGE_A2_ISSUE_LOG Create the A2 failure-evidence schema.

names = {'issue_id','run_id','stage_id','test_id','elimination_layer', ...
    'variable_or_equation','symptom','error_message','root_cause', ...
    'proposed_solution','git_commit','regression_test','status', ...
    'evidence_path','recorded_at'};
issues = table('Size',[0,numel(names)], ...
    'VariableTypes',repmat({'string'},1,numel(names)), ...
    'VariableNames',names);
end
