function result = run_stage_b2b_static_checks(projectRoot)
%RUN_STAGE_B2B_STATIC_CHECKS Analyze the B-2B production dependency set.

arguments
    projectRoot (1,1) string
end
relative = ["src/+rkkt/+workflows/stageB2B.m"; ...
    "src/+rkkt/+indexing/build_stage_b2b_index.m"; ...
    "src/+rkkt/+model/load_stage_b2b_configuration.m"; ...
    "src/+rkkt/+model/initialize_stage_b2b_state.m"; ...
    "src/+rkkt/+model/build_stage_b2b_multiday_linearization.m"; ...
    "src/+rkkt/+solver/stage_b2b_linearization_contract.m"; ...
    "src/+rkkt/+solver/eliminate_stage_b2b_inequality_directions.m"; ...
    "src/+rkkt/+solver/partition_stage_b2b_recursive_system.m"; ...
    "src/+rkkt/+solver/apply_stage_b2b_retained_chain_rhs.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_day_border.m"; ...
    "src/+rkkt/+solver/form_stage_b2b_day_response.m"; ...
    "src/+rkkt/+solver/aggregate_stage_b2b_day_responses.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_core16_ldl.m"; ...
    "src/+rkkt/+solver/recover_stage_b2b_recursive_direction.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_recursive_direction.m"; ...
    "src/+rkkt/+solver/assemble_stage_b2b_full_kkt.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_full_kkt_direction.m"; ...
    "src/+rkkt/+solver/verify_stage_b2b_direction_equivalence.m"; ...
    "src/+rkkt/+diagnostics/inspect_stage_b2b_environment.m"; ...
    "src/+rkkt/+diagnostics/build_stage_b2b_audits.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b2b_static_checks.m"; ...
    "src/+rkkt/+reporting/generate_stage_b2b_report.m"; ...
    "src/+rkkt/+reporting/write_stage_b2b_docx.m"; ...
    "src/+rkkt/+reporting/validate_stage_b2b_report.m"; ...
    "tests/run_stage_B_2B_tests.m"; ...
    "tests/equivalence/test_stage_b2b_direction_equivalence.m"];
relative=relative(arrayfun(@(path)isfile(fullfile(projectRoot, ...
    replace(path,"/",filesep))),relative));
file=relative; finding_count=zeros(numel(file),1); ...
    status=repmat("PASS",numel(file),1); details=strings(numel(file),1);
for k=1:numel(file)
    findings=checkcode(fullfile(projectRoot,replace(file(k),"/",filesep)),"-id");
    finding_count(k)=numel(findings);
    if isempty(findings)
        details(k)="0 Code Analyzer findings";
    else
        status(k)="FAIL";
        details(k)=strjoin(string({findings.id})+":"+string({findings.message})," | ");
    end
end
codeAnalyzer=table(file,finding_count,status,details);

rule_id=["NO_INV";"NO_PINV";"NO_LSQMINNORM";"NO_PARFOR"; ...
    "NO_PARPOOL";"NO_REGULARIZATION";"NO_DIRECT_LDL"; ...
    "NO_AUTOMATIC_SYMMETRIZATION"];
pattern=["(?i)\binv\s*\(";"(?i)\bpinv\s*\("; ...
    "(?i)\blsqminnorm\s*\(";"(?i)\bparfor\b"; ...
    "(?i)\bparpool\s*\(";"(?i)\bregulari[sz]\w*\s*\("; ...
    "(?i)(?<!factor_symmetric_)\bldl\s*\("; ...
    "\([^\r\n]+\+[^\r\n]+\.'\)\s*/\s*2"];
forbidden=repmat(struct("rule_id","","pattern","", ...
    "matching_files","","match_count",0,"status","FAIL"),numel(rule_id),1);
production=file(startsWith(file,"src/"));
for r=1:numel(rule_id)
    matches=strings(0,1);
    for k=1:numel(production)
        source=strip_comments(string(fileread(fullfile(projectRoot, ...
            replace(production(k),"/",filesep)))));
        if ~isempty(regexp(char(source),char(pattern(r)),"once"))
            matches(end+1,1)=production(k); %#ok<AGROW>
        end
    end
    forbidden(r).rule_id=char(rule_id(r)); forbidden(r).pattern=char(pattern(r));
    forbidden(r).matching_files=char(strjoin(matches,"|"));
    forbidden(r).match_count=numel(matches);
    if isempty(matches), forbidden(r).status="PASS"; end
end
forbiddenExecution=struct2table(forbidden);
role=["recursive_production";"independent_full_kkt_audit"];
entry_file=["src/+rkkt/+solver/solve_stage_b2b_recursive_direction.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_full_kkt_direction.m"];
full_direction_consumed=[false;false]; fallback_available=[false;false];
audit_only=[false;true]; closure_status=repmat("PASS",2,1);
dependencyClosure=table(role,entry_file,full_direction_consumed, ...
    fallback_available,audit_only,closure_status);
result=struct("code_analyzer",codeAnalyzer, ...
    "forbidden_execution",forbiddenExecution, ...
    "dependency_closure",dependencyClosure, ...
    "all_pass",all(codeAnalyzer.status=="PASS") && ...
        all(string(forbiddenExecution.status)=="PASS") && ...
        all(dependencyClosure.closure_status=="PASS"), ...
    "blocking_findings",sum(codeAnalyzer.finding_count), ...
    "forbidden_failures",sum(string(forbiddenExecution.status)~="PASS"));
end

function value=strip_comments(source)
lines=splitlines(source);
for k=1:numel(lines)
    position=regexp(char(lines(k)),'(?<!'')%(?!'')','once');
    if ~isempty(position), lines(k)=extractBefore(lines(k),position); end
end
value=strjoin(lines,newline);
end
