function result = run_stage_a4_iteration24_scaling_stress( ...
        projectRoot,options)
%RUN_STAGE_A4_ITERATION24_SCALING_STRESS Replay the frozen rank failure.
%
% This is an independent, single-direction numerical-stability stress
% route.  It rebuilds the accepted revision-23 state, proves that the
% unscaled production gate still stops at day 14/hour 3, and then solves
% the same untouched linearization twice using:
%   1) local symmetric diagonal congruence scaling; and
%   2) stable-v2 retained-factor residual refinement (maximum 3 passes).
%
% The complete sparse KKT direction is computed once and used only as an
% independent audit.  No IPM state update is performed.

arguments
    projectRoot (1,1) string = default_project_root()
    options.AuthorityRunId (1,1) string = ...
        "20260728_112548_stage_A4_1f3836ca"
    options.FailureEvidencePath (1,1) string = ""
    options.ExpectedStateRevision (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 23
    options.EquilibrationPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 8
    options.ResidualRefinementMaxPasses (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 3
    options.DirectionTolerance (1,1) double ...
        {mustBePositive,mustBeFinite} = 1e-10
    options.RecursiveResidualTolerance (1,1) double ...
        {mustBePositive,mustBeFinite} = 1e-10
    options.FullResidualTolerance (1,1) double ...
        {mustBePositive,mustBeFinite} = 1e-10
    options.SymmetryTolerance (1,1) double ...
        {mustBePositive,mustBeFinite} = 1e-12
end

assert(options.EquilibrationPasses==8 && ...
    options.ResidualRefinementMaxPasses==3, ...
    "stageA4:scaleStress:FrozenRoute", ...
    "The stress route is frozen to eight equilibration passes and "+ ...
    "three retained-factor refinement passes.");
projectRoot = canonical_root(projectRoot);
addpath(projectRoot);
addpath(genpath(fullfile(projectRoot,"src")));
stressConfig = ...
    rkkt.diagnostics.load_stage_a4_iteration24_scaling_stress_configuration(projectRoot);
assert(options.AuthorityRunId==stressConfig.authority_run_id && ...
    options.ExpectedStateRevision== ...
        stressConfig.authority_state_revision && ...
    options.EquilibrationPasses==stressConfig.equilibration_passes && ...
    options.ResidualRefinementMaxPasses== ...
        stressConfig.recursive_refinement_max_passes && ...
    options.DirectionTolerance== ...
        stressConfig.direction_relative_engineering_tolerance && ...
    options.RecursiveResidualTolerance== ...
        stressConfig. ...
        recursive_full_kkt_residual_engineering_tolerance && ...
    options.FullResidualTolerance== ...
        stressConfig.full_kkt_audit_residual_tolerance && ...
    options.SymmetryTolerance== ...
        stressConfig.symmetry_relative_tolerance, ...
    "stageA4:scaleStress:EffectiveConfigBinding", ...
    "Runtime options do not exactly match the frozen stress YAML.");

currentStage = string(fileread(fullfile(projectRoot,"CURRENT_STAGE.md")));
assert(contains(currentStage,"`stage_id`: `stage_A4`") && ...
    contains(currentStage,"`status`: `READY`"), ...
    "stageA4:scaleStress:StageGate", ...
    "The scaling stress test requires stage_A4 / READY.");
config = rkkt.model.load_stage_a4_3_configuration(projectRoot);
assert(string(config.stage_id)=="stage_A4" && ...
    string(config.status)=="READY", ...
    "stageA4:scaleStress:ConfigGate", ...
    "The A4-3 model configuration must remain stage_A4 / READY.");

failurePath = resolve_failure_path(projectRoot,options);
[authorityManifest,authorityManifestPath] = ...
    load_authority_manifest(projectRoot,options.AuthorityRunId);
[inputHashes,inputHashesPass] = rkkt.data.verify_input_hashes(projectRoot);
assert(inputHashesPass,"stageA4:scaleStress:InputHashes", ...
    "The controlled Excel input hashes do not pass.");
failureSha256 = string(rkkt.data.compute_sha256_file(failurePath));
payload = load(failurePath);
assert(isfield(payload,"failure") && ...
    isfield(payload,"state_before_failure"), ...
    "stageA4:scaleStress:FailureSchema", ...
    "The authority failure evidence has no frozen state.");
state = payload.state_before_failure;
failure = payload.failure;
assert(state.state_revision==options.ExpectedStateRevision && ...
    state.iteration_index==options.ExpectedStateRevision && ...
    state.completed_newton_direction_count== ...
        options.ExpectedStateRevision, ...
    "stageA4:scaleStress:StateRevision", ...
    "The authority state is not accepted revision 23.");
stateFingerprintBefore = string( ...
    rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(state));
assert(stateFingerprintBefore==string(failure.state_fingerprint), ...
    "stageA4:scaleStress:StateFingerprint", ...
    "The frozen authority state fingerprint does not rebuild.");

data = rkkt.data.load_project_data(projectRoot);
index = rkkt.indexing.build_stage_a4_index( ...
    data,config,"RunId","A4_ITER24_SCALE_STRESS");
linearization = rkkt.model.build_stage_a4_scaled_objective_linearization( ...
    state,data,index,config,"A4-3-FORMAL-CANDIDATE");
linearizationFingerprint = string(rkkt.diagnostics.compute_stage_a4_rns1_fingerprint( ...
    linearization,"linearization"));
assert_authority_linearization(projectRoot,options.AuthorityRunId, ...
    options.ExpectedStateRevision,linearizationFingerprint);

unscaledFailure = reproduce_unscaled_failure( ...
    linearization,options.SymmetryTolerance, ...
    options.ResidualRefinementMaxPasses);
assert(unscaledFailure.present && ...
    unscaledFailure.identifier== ...
        "stageAMultiday:solver:RecursiveLayerFailure" && ...
    contains(unscaledFailure.message,"day_14_block_ldl_thomas") && ...
    contains(unscaledFailure.message,"rank=17"), ...
    "stageA4:scaleStress:FailureSignature", ...
    "The frozen unscaled iteration-24 failure did not reproduce.");

solveArguments = { ...
    "AssemblyTolerance",1e-12, ...
    "SymmetryTolerance",options.SymmetryTolerance, ...
    "ResidualRefinementMaxPasses", ...
        options.ResidualRefinementMaxPasses, ...
    "UseCongruenceScaling",true, ...
    "EquilibrationPasses",options.EquilibrationPasses};
firstStart = tic;
first = rkkt.solver.solve_stage_a_multiday_recursive_direction( ...
    linearization,solveArguments{:});
firstSeconds = toc(firstStart);
secondStart = tic;
second = rkkt.solver.solve_stage_a_multiday_recursive_direction( ...
    linearization,solveArguments{:});
secondSeconds = toc(secondStart);
fullStart = tic;
fullAudit = rkkt.solver.solve_stage_a_multiday_full_kkt_direction(linearization);
fullSeconds = toc(fullStart);

equivalence = rkkt.solver.verify_stage_a_multiday_direction_equivalence( ...
    fullAudit,first,linearization, ...
    DirectionRelative=options.DirectionTolerance, ...
    RecursiveResidual=options.RecursiveResidualTolerance, ...
    FullResidualPreferred=1e-12, ...
    FullResidualMaximum=options.FullResidualTolerance);
repeatEquivalence = rkkt.solver.verify_stage_a_multiday_direction_equivalence( ...
    fullAudit,second,linearization, ...
    DirectionRelative=options.DirectionTolerance, ...
    RecursiveResidual=options.RecursiveResidualTolerance, ...
    FullResidualPreferred=1e-12, ...
    FullResidualMaximum=options.FullResidualTolerance);

directionExact = isequaln(first.direction,second.direction);
directionMaxAbsoluteDifference = ...
    max(abs(first.direction-second.direction));
firstFingerprint = numeric_fingerprint(first.direction);
secondFingerprint = numeric_fingerprint(second.direction);
hourlyAudit = build_hourly_audit(first);
coreAudit = build_core_audit(first);
refinementAudit = build_refinement_audit(first);
factorAudit = audit_factor_operator_contract(first);
stateFingerprintAfter = string( ...
    rkkt.artifacts.compute_stage_a4_checkpoint_state_fingerprint(state));
stateUnchanged = stateFingerprintAfter==stateFingerprintBefore;
positiveState = min(state.l)>0 && min(state.z)>0;
maximumResponseSymmetry = max( ...
    arrayfun(@(item)item.diagnostics.symmetry_relative, ...
    first.daily_responses));

componentValues = struct2array(equivalence.component_relative_errors);
componentRepeatValues = ...
    struct2array(repeatEquivalence.component_relative_errors);
executionLedger = struct( ...
    "recursive_direction_solves",2, ...
    "full_kkt_audit_direction_solves",1, ...
    "state_update_calls",0, ...
    "full_ipm_calls",0, ...
    "optimization_calls",0, ...
    "parallel_calls",0, ...
    "regularization_calls",0, ...
    "automatic_symmetrization_calls",0, ...
    "full_direction_fallback_calls",0);
numericPass = ...
    unscaledFailure.present && ...
    stateUnchanged && positiveState && ...
    directionExact && directionMaxAbsoluteDifference==0 && ...
    firstFingerprint==secondFingerprint && ...
    equivalence.direction_relative_error<=options.DirectionTolerance && ...
    all(componentValues<=options.DirectionTolerance) && ...
    repeatEquivalence.direction_relative_error<= ...
        options.DirectionTolerance && ...
    all(componentRepeatValues<=options.DirectionTolerance) && ...
    repeatEquivalence.recursive_kkt_relative_residual<= ...
        options.RecursiveResidualTolerance && ...
    repeatEquivalence.full_kkt_relative_residual<= ...
        options.FullResidualTolerance && ...
    equivalence.recursive_kkt_relative_residual<= ...
        options.RecursiveResidualTolerance && ...
    equivalence.full_kkt_relative_residual<= ...
        options.FullResidualTolerance && ...
    maximumResponseSymmetry<=options.SymmetryTolerance && ...
    all(hourlyAudit.scaling_used) && ...
    all(hourlyAudit.scaled_numeric_rank==hourlyAudit.dimension) && ...
    coreAudit.scaling_used && coreAudit.scaled_numeric_rank==16 && ...
    factorAudit.all_pass && ...
    first.no_full_direction_fallback && ...
    ~first.full_direction_consumed && ...
    execution_ledger_pass(executionLedger);

git = capture_git(projectRoot);
result = struct();
result.schema_version = ...
    "stage_A4_iteration24_scaling_stress_v1.0";
result.stage_id = "stage_A4";
result.stage_status = "READY";
result.milestone = "A4-ITER24-SCALE-STRESS";
result.run_purpose = ...
    "iteration24_local_congruence_scaling_numerical_stability_stress_test";
result.authority_run_id = string(options.AuthorityRunId);
result.authority_commit = string(authorityManifest.git_commit);
result.authority_manifest_path = string(authorityManifestPath);
result.authority_manifest_sha256 = ...
    string(rkkt.data.compute_sha256_file(authorityManifestPath));
result.failure_evidence_path = string(failurePath);
result.failure_evidence_sha256 = failureSha256;
result.state_revision = state.state_revision;
result.state_fingerprint_before = stateFingerprintBefore;
result.state_fingerprint_after = stateFingerprintAfter;
result.state_unchanged = stateUnchanged;
result.linearization_fingerprint = linearizationFingerprint;
result.linearization_identity = linearization.identity;
result.input_hashes = inputHashes;
result.input_hashes_pass = inputHashesPass;
result.effective_config = stressConfig;
result.unscaled_failure = unscaledFailure;
result.options = struct( ...
    "equilibration_passes",options.EquilibrationPasses, ...
    "residual_refinement_max_passes", ...
        options.ResidualRefinementMaxPasses, ...
    "direction_tolerance",options.DirectionTolerance, ...
    "recursive_residual_tolerance", ...
        options.RecursiveResidualTolerance, ...
    "full_residual_tolerance",options.FullResidualTolerance, ...
    "symmetry_tolerance",options.SymmetryTolerance);
result.timings = struct( ...
    "first_recursive_seconds",firstSeconds, ...
    "second_recursive_seconds",secondSeconds, ...
    "full_kkt_audit_seconds",fullSeconds, ...
    "total_direction_seconds", ...
        firstSeconds+secondSeconds+fullSeconds);
result.determinism = struct( ...
    "direction_exact",directionExact, ...
    "maximum_absolute_difference",directionMaxAbsoluteDifference, ...
    "first_direction_fingerprint",firstFingerprint, ...
    "second_direction_fingerprint",secondFingerprint, ...
    "first_seconds",firstSeconds, ...
    "second_seconds",secondSeconds);
result.equivalence = equivalence;
result.repeat_equivalence = repeatEquivalence;
result.hourly_factor_audit = hourlyAudit;
result.core_audit = coreAudit;
result.refinement_audit = refinementAudit;
result.factor_operator_audit = factorAudit;
result.maximum_day_response_symmetry_relative = ...
    maximumResponseSymmetry;
result.positive_state = positiveState;
result.execution_ledger = executionLedger;
result.no_full_direction_fallback = ...
    first.no_full_direction_fallback && ...
    second.no_full_direction_fallback && ...
    ~first.full_direction_consumed && ...
    ~second.full_direction_consumed;
result.state_update_count = executionLedger.state_update_calls;
result.full_ipm_executed = executionLedger.full_ipm_calls>0;
result.optimization_executed = executionLedger.optimization_calls>0;
result.parallel_executed = executionLedger.parallel_calls>0;
result.automatic_symmetrization_used = ...
    executionLedger.automatic_symmetrization_calls>0;
result.regularization_used = executionLedger.regularization_calls>0;
result.full_kkt_role = "independent_audit_only";
result.formal_a4_run_created = false;
result.stage_a4_pass_claimed = false;
result.git = git;
result.linearization = linearization;
result.recursive = first;
result.full_audit = fullAudit;
% The forbidden-execution gate is intentionally evaluated after all runtime
% facts are assembled.  It follows the actual dependency closures and
% consumes independent runtime fields; it is not derived from the single
% no-full-direction-fallback boolean.
forbiddenExecution = ...
    rkkt.diagnostics.scan_stage_a4_iteration24_scaling_stress_forbidden_execution( ...
    projectRoot,result);
result.forbidden_execution = forbiddenExecution;
result.numeric_pass = numericPass;
result.pass = numericPass && forbiddenExecution.all_pass;
result.status = ternary(result.pass,"PASS","FAIL_RETRYABLE");
end

function failurePath = resolve_failure_path(root,options)
if strlength(strip(options.FailureEvidencePath))==0
    failurePath = fullfile(root,"runs",options.AuthorityRunId, ...
        "checkpoints", ...
        "numerical_failure_inv001_iter024_rev023_20260728_113512_963.mat");
else
    failurePath = string(options.FailureEvidencePath);
    if ~isfile(failurePath)
        failurePath = fullfile(root,failurePath);
    end
end
failurePath = string(failurePath);
assert(isfile(failurePath),"stageA4:scaleStress:FailureEvidenceMissing", ...
    "The authority iteration-24 failure evidence is missing: %s", ...
    failurePath);
end

function [manifest,pathValue] = load_authority_manifest(root,runId)
pathValue = fullfile(root,"runs",runId,"run_manifest.json");
assert(isfile(pathValue),"stageA4:scaleStress:AuthorityManifestMissing", ...
    "The authority run manifest is missing: %s",pathValue);
manifest = jsondecode(fileread(pathValue));
assert(string(manifest.status)=="FAIL_RETRYABLE" && ...
    string(manifest.stage_id)=="stage_A4" && ...
    isfield(manifest,"git_commit"), ...
    "stageA4:scaleStress:AuthorityManifestContract", ...
    "The authority manifest is not the frozen A4 failure run.");
end

function assert_authority_linearization(root,runId,revision,fingerprint)
pathValue = fullfile(root,"runs",runId,"checkpoints", ...
    "checkpoint_manifest.csv");
tableValue = readtable(pathValue,"TextType","string", ...
    "VariableNamingRule","preserve");
row = tableValue(double(tableValue.state_revision)==revision,:);
assert(height(row)==1 && ...
    lower(string(row.linearization_fingerprint))==fingerprint, ...
    "stageA4:scaleStress:LinearizationFingerprint", ...
    "The rebuilt linearization does not match the authority checkpoint.");
end

function failure = reproduce_unscaled_failure(lin,symmetryTolerance,passes)
failure = struct( ...
    "present",false,"identifier","","message","", ...
    "cause_identifier","","cause_message","");
try
    rkkt.solver.solve_stage_a_multiday_recursive_direction(lin, ...
        AssemblyTolerance=1e-12, ...
        SymmetryTolerance=symmetryTolerance, ...
        ResidualRefinementMaxPasses=passes, ...
        UseCongruenceScaling=false);
catch cause
    failure.present = true;
    failure.identifier = string(cause.identifier);
    failure.message = string(cause.message);
    nested = cause;
    while ~isempty(nested.cause)
        nested = nested.cause{1};
    end
    failure.cause_identifier = string(nested.identifier);
    failure.cause_message = string(nested.message);
end
end

function tableValue = build_hourly_audit(recursive)
rows = repmat(empty_hour_row(),0,1);
for d = 1:numel(recursive.daily_thomas)
    thomas = recursive.daily_thomas(d);
    dayId = recursive.daily_partitions(d).day_id;
    for t = 1:numel(thomas.factors)
        factor = thomas.factors{t};
        trace = factor.scaling_trace;
        solveDiagnostics = thomas.diagnostics.back_solve{t};
        row = empty_hour_row();
        row.day = dayId;
        row.hour = recursive.daily_partitions(d).hour(t).hour;
        row.dimension = factor.dimension;
        row.original_numeric_rank = factor.original_numeric_rank;
        row.scaled_numeric_rank = factor.numeric_rank;
        row.original_condition_2 = factor.original_condition_2;
        row.scaled_condition_2 = factor.condition_2;
        row.condition_reduction_factor = ...
            factor.original_condition_2/factor.condition_2;
        row.original_smin = factor.original_smin;
        row.scaled_smin = trace.smin(end);
        row.symmetry_relative_original = factor.symmetry_relative;
        row.symmetry_relative_scaled = ...
            factor.factorization_matrix_symmetry_relative;
        row.scaling_used = factor.scaling_used;
        row.equilibration_passes = factor.equilibration_passes;
        row.scale_min = min(factor.congruence_scale);
        row.scale_max = max(factor.congruence_scale);
        row.scale_ratio = row.scale_max/row.scale_min;
        row.factor_relative_residual = factor.factor_relative_residual;
        row.solve_original_operator_relative_residual = ...
            solveDiagnostics.raw_operator_relative_residual;
        row.solve_factorized_operator_relative_residual = ...
            solveDiagnostics.factorized_operator_relative_residual;
        row.chain_relative_residual = ...
            thomas.diagnostics.chain_relative_residual;
        rows(end+1,1) = row; %#ok<AGROW>
    end
end
tableValue = struct2table(rows);
end

function row = empty_hour_row()
row = struct( ...
    "day",0,"hour",0,"dimension",0, ...
    "original_numeric_rank",0,"scaled_numeric_rank",0, ...
    "original_condition_2",NaN,"scaled_condition_2",NaN, ...
    "condition_reduction_factor",NaN, ...
    "original_smin",NaN,"scaled_smin",NaN, ...
    "symmetry_relative_original",NaN, ...
    "symmetry_relative_scaled",NaN, ...
    "scaling_used",false,"equilibration_passes",0, ...
    "scale_min",NaN,"scale_max",NaN,"scale_ratio",NaN, ...
    "factor_relative_residual",NaN, ...
    "solve_original_operator_relative_residual",NaN, ...
    "solve_factorized_operator_relative_residual",NaN, ...
    "chain_relative_residual",NaN);
end

function audit = build_core_audit(recursive)
factor = recursive.core.factor;
trace = factor.scaling_trace;
audit = struct( ...
    "dimension",factor.dimension, ...
    "scaling_used",factor.scaling_used, ...
    "equilibration_passes",factor.equilibration_passes, ...
    "original_numeric_rank",factor.original_numeric_rank, ...
    "scaled_numeric_rank",factor.numeric_rank, ...
    "original_condition_2",factor.original_condition_2, ...
    "scaled_condition_2",factor.condition_2, ...
    "condition_reduction_factor", ...
        factor.original_condition_2/factor.condition_2, ...
    "original_smin",factor.original_smin, ...
    "scaled_smin",trace.smin(end), ...
    "symmetry_relative_original",factor.symmetry_relative, ...
    "symmetry_relative_scaled", ...
        factor.factorization_matrix_symmetry_relative, ...
    "relative_residual",recursive.core.diagnostics.relative_residual, ...
    "refinement_correction_count", ...
        recursive.core.diagnostics.residual_refinement.correction_count, ...
    "refinement_stop_reason", ...
        recursive.core.diagnostics.residual_refinement.stop_reason);
end

function tableValue = build_refinement_audit(recursive)
nDays = numel(recursive.daily_thomas);
component = strings(nDays+1,1);
day = nan(nDays+1,1);
maximumPasses = zeros(nDays+1,1);
passesAttempted = zeros(nDays+1,1);
correctionCount = zeros(nDays+1,1);
initialResidual = nan(nDays+1,1);
finalResidual = nan(nDays+1,1);
stopReason = strings(nDays+1,1);
for d = 1:nDays
    item = recursive.daily_thomas(d).diagnostics.residual_refinement;
    component(d) = "day_chain";
    day(d) = recursive.daily_partitions(d).day_id;
    maximumPasses(d) = item.maximum_passes;
    passesAttempted(d) = item.passes_attempted;
    correctionCount(d) = item.correction_count;
    initialResidual(d) = item.initial_maximum_column_relative;
    finalResidual(d) = item.final_maximum_column_relative;
    stopReason(d) = item.stop_reason;
end
item = recursive.core.diagnostics.residual_refinement;
component(end) = "global_core_16";
maximumPasses(end) = item.maximum_passes;
passesAttempted(end) = item.passes_attempted;
correctionCount(end) = item.correction_count;
initialResidual(end) = item.initial_maximum_column_relative;
finalResidual(end) = item.final_maximum_column_relative;
stopReason(end) = item.stop_reason;
tableValue = table(component,day,maximumPasses,passesAttempted, ...
    correctionCount,initialResidual,finalResidual,stopReason, ...
    'VariableNames',{'component','day','maximum_passes', ...
    'passes_attempted','correction_count', ...
    'initial_maximum_column_relative', ...
    'final_maximum_column_relative','stop_reason'});
end

function audit = audit_factor_operator_contract(recursive)
factorCount = 0;
allScaled = true;
allOriginalRetained = true;
maximumCongruenceRelative = 0;
maximumFactorResidual = 0;
maximumOriginalOperatorMismatch = 0;
for d = 1:numel(recursive.daily_thomas)
    for t = 1:numel(recursive.daily_thomas(d).factors)
        factor = recursive.daily_thomas(d).factors{t};
        [allScaled,allOriginalRetained,maximumCongruenceRelative, ...
            maximumFactorResidual,maximumOriginalOperatorMismatch, ...
            factorCount] = accumulate_factor( ...
            factor,allScaled,allOriginalRetained, ...
            maximumCongruenceRelative,maximumFactorResidual, ...
            maximumOriginalOperatorMismatch,factorCount);
    end
end
[allScaled,allOriginalRetained,maximumCongruenceRelative, ...
    maximumFactorResidual,maximumOriginalOperatorMismatch,factorCount] = ...
    accumulate_factor( ...
    recursive.core.factor,allScaled,allOriginalRetained, ...
    maximumCongruenceRelative,maximumFactorResidual, ...
    maximumOriginalOperatorMismatch,factorCount);
audit = struct( ...
    "factor_count",factorCount, ...
    "all_scaled",allScaled, ...
    "all_original_operators_retained",allOriginalRetained, ...
    "maximum_congruence_reconstruction_relative", ...
        maximumCongruenceRelative, ...
    "maximum_factor_reconstruction_relative", ...
        maximumFactorResidual, ...
    "maximum_original_factorized_operator_relative", ...
        maximumOriginalOperatorMismatch, ...
    "automatic_symmetrization_used",false, ...
    "regularization_used",false, ...
    "full_kkt_direction_consumed",false, ...
    "all_pass",allScaled && allOriginalRetained && ...
        maximumCongruenceRelative<=64*eps && ...
        maximumFactorResidual<=1e-12 && ...
        maximumOriginalOperatorMismatch<=1e-12);
end

function [allScaled,allOriginalRetained,maxCongruence,maxFactor, ...
        maxOriginalMismatch,count] = ...
        accumulate_factor(factor,allScaled,allOriginalRetained, ...
        maxCongruence,maxFactor,maxOriginalMismatch,count)
count = count+1;
allScaled = allScaled && factor.scaling_used;
scale = spdiags(factor.congruence_scale,0, ...
    factor.dimension,factor.dimension);
rebuilt = scale*factor.matrix*scale;
relative = norm(rebuilt-factor.factorization_matrix,"fro") / ...
    max(1,norm(factor.factorization_matrix,"fro"));
allOriginalRetained = allOriginalRetained && ...
    isequal(size(factor.matrix),size(factor.factorization_matrix)) && ...
    isfinite(relative);
maxCongruence = max(maxCongruence,relative);
maxFactor = max(maxFactor,factor.factor_relative_residual);
maxOriginalMismatch = max(maxOriginalMismatch, ...
    factor.raw_to_factorized_operator_relative);
end

function digest = numeric_fingerprint(value)
messageDigest = java.security.MessageDigest.getInstance("SHA-256");
shape = uint64(size(value));
messageDigest.update(typecast(shape(:),"int8"));
bytes = typecast(double(value(:)),"uint8");
messageDigest.update(typecast(bytes(:),"int8"));
digestBytes = mod(double(messageDigest.digest()),256);
digest = lower(join(compose("%02x",digestBytes),""));
digest = reshape(digest,1,1);
end

function git = capture_git(root)
[headStatus,headText] = git_command(root,"rev-parse HEAD");
[branchStatus,branchText] = git_command(root,"branch --show-current");
[statusCode,statusText] = git_command( ...
    root,"status --porcelain --untracked-files=normal");
git = struct( ...
    "commit",lower(strip(string(headText))), ...
    "branch",strip(string(branchText)), ...
    "status_text",string(statusText), ...
    "head_resolved",headStatus==0, ...
    "branch_resolved",branchStatus==0, ...
    "status_resolved",statusCode==0);
end

function [status,output] = git_command(root,argumentsValue)
safe = replace(string(root),"\","/");
quotedSafe = '"'+replace(safe,'"','\"')+'"';
quotedRoot = '"'+replace(string(root),'"','\"')+'"';
command = "git -c safe.directory="+quotedSafe+" -C "+quotedRoot+" "+ ...
    argumentsValue;
[status,output] = system(char(command));
end

function root = canonical_root(value)
root = string(java.io.File(value).getCanonicalPath());
assert(isfolder(root),"stageA4:scaleStress:ProjectRoot", ...
    "Project root does not exist: %s",root);
end

function root = default_project_root()
root = rkkt.projectRoot();
end

function value = ternary(condition,yesValue,noValue)
if condition
    value = yesValue;
else
    value = noValue;
end
end

function passed = execution_ledger_pass(ledger)
passed = ledger.recursive_direction_solves==2 && ...
    ledger.full_kkt_audit_direction_solves==1 && ...
    ledger.state_update_calls==0 && ...
    ledger.full_ipm_calls==0 && ...
    ledger.optimization_calls==0 && ...
    ledger.parallel_calls==0 && ...
    ledger.regularization_calls==0 && ...
    ledger.automatic_symmetrization_calls==0 && ...
    ledger.full_direction_fallback_calls==0;
end
