function result = run_stage_b2c_static_checks(projectRoot)
%RUN_STAGE_B2C_STATIC_CHECKS Analyze B-2C production and test closure.

arguments
    projectRoot (1,1) string
end
relative = ["src/+rkkt/run.m"; ...
    "src/+rkkt/+config/read_run_project_configuration.m"; ...
    "src/+rkkt/+config/build_stage_b2c_run_settings.m"; ...
    "src/+rkkt/+config/resolve_stage_b2c_day_scope.m"; ...
    "src/+rkkt/+workflows/stageB2C.m"; ...
    "src/+rkkt/+workflows/stageB2CConfigured.m"; ...
    "src/+rkkt/+artifacts/write_table_csv_17g.m"; ...
    "src/+rkkt/+artifacts/write_stage_b2c_checkpoint.m"; ...
    "src/+rkkt/+artifacts/load_stage_b2c_checkpoint.m"; ...
    "src/+rkkt/+indexing/build_stage_b2c_index.m"; ...
    "src/+rkkt/+model/load_stage_b2c_configuration.m"; ...
    "src/+rkkt/+model/initialize_stage_b2c_state.m"; ...
    "src/+rkkt/+model/build_stage_b2c_multiday_linearization.m"; ...
    "src/+rkkt/+model/build_stage_b2c_scaled_objective_linearization.m"; ...
    "src/+rkkt/+solver/eliminate_stage_b2c_all_inequality_directions.m"; ...
    "src/+rkkt/+solver/partition_stage_b2c_daily_joint_system.m"; ...
    "src/+rkkt/+solver/solve_stage_b2c_daily_joint_block.m"; ...
    "src/+rkkt/+solver/solve_stage_b2c_daily_joint_day.m"; ...
    "src/+rkkt/+solver/solve_stage_b2c_daily_joint_responses_parallel.m"; ...
    "src/+rkkt/+solver/prepare_stage_b2c_parallel_pool.m"; ...
    "src/+rkkt/+solver/close_stage_b2c_parallel_pool.m"; ...
    "src/+rkkt/+solver/recover_stage_b2c_daily_joint_direction.m"; ...
    "src/+rkkt/+solver/solve_stage_b2c_daily_joint_direction.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_full_kkt_direction.m"; ...
    "src/+rkkt/+solver/compute_stage_b2c_water_slack_second_order_correction.m"; ...
    "src/+rkkt/+solver/run_stage_b2c_full_ipm.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b2c_nonzero_hessian_gate.m"; ...
    "src/+rkkt/+diagnostics/execute_stage_b2c_iteration.m"; ...
    "src/+rkkt/+diagnostics/compute_stage_b2c_unitized_metrics.m"; ...
    "src/+rkkt/+diagnostics/stage_b2c_convergence_passed.m"; ...
    "src/+rkkt/+diagnostics/evaluate_stage_b2c_physical_audit.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b2c_static_checks.m"; ...
    "src/+rkkt/+reporting/generate_stage_b2c_report.m"; ...
    "src/+rkkt/+reporting/validate_stage_b2c_report.m"; ...
    "tests/run_stage_B_2C_tests.m"; ...
    "tests/run_stage_B_2C_A4_3_affected_regressions.m"; ...
    "tests/integration/test_stage_b2c_formal_ipm.m"];
relative = relative(arrayfun(@(p)isfile(fullfile(projectRoot, ...
    replace(p,"/",filesep))),relative));
file = relative; finding_count=zeros(numel(file),1);
status=repmat("PASS",numel(file),1); details=strings(numel(file),1);
for k=1:numel(file)
    findings=checkcode(fullfile(projectRoot, ...
        replace(file(k),"/",filesep)),"-id");
    finding_count(k)=numel(findings);
    if isempty(findings)
        details(k)="0 Code Analyzer findings";
    else
        status(k)="FAIL";
        details(k)=strjoin(string({findings.id})+":"+ ...
            string({findings.message})," | ");
    end
end
codeAnalyzer=table(file,finding_count,status,details);

rule_id=["NO_INV";"NO_PINV";"NO_LSQMINNORM";"NO_PARFOR"; ...
    "NO_PARPOOL";"NO_REGULARIZATION";"NO_DIRECT_LDL"; ...
    "NO_AUTOMATIC_SYMMETRIZATION";"NO_DIRECT_CHAIN_BACKSLASH"];
pattern=["(?i)\binv\s*\(";"(?i)\bpinv\s*\("; ...
    "(?i)\blsqminnorm\s*\(";"(?i)\bparfor\b"; ...
    "(?i)\bparpool\s*\(";"(?i)\bregulari[sz]\w*\s*\("; ...
    "(?i)(?<!factor_symmetric_)\bldl\s*\("; ...
    "\([^\r\n]+\+[^\r\n]+\.'\)\s*/\s*2"; ...
    "(?i)\bday\.M\s*\\"];
forbidden=repmat(struct("rule_id","","pattern","", ...
    "matching_files","","match_count",0,"status","FAIL"), ...
    numel(rule_id),1);
production=file(startsWith(file,"src/+rkkt/"));
for r=1:numel(rule_id)
    matches=strings(0,1);
    for k=1:numel(production)
        if rule_id(r)=="NO_PARFOR" && production(k)== ...
                "src/+rkkt/+solver/solve_stage_b2c_daily_joint_responses_parallel.m"
            continue
        end
        if rule_id(r)=="NO_PARPOOL" && production(k)== ...
                "src/+rkkt/+solver/prepare_stage_b2c_parallel_pool.m"
            continue
        end
        if rule_id(r)=="NO_DIRECT_LDL" && production(k)== ...
                "src/+rkkt/+solver/solve_stage_b2c_daily_joint_block.m"
            continue
        end
        source=strip_comments(string(fileread(fullfile(projectRoot, ...
            replace(production(k),"/",filesep)))));
        if ~isempty(regexp(char(source),char(pattern(r)),"once"))
            matches(end+1,1)=production(k); %#ok<AGROW>
        end
    end
    forbidden(r).rule_id=char(rule_id(r));
    forbidden(r).pattern=char(pattern(r));
    forbidden(r).matching_files=char(strjoin(matches,"|"));
    forbidden(r).match_count=numel(matches);
    if isempty(matches), forbidden(r).status="PASS"; end
end
forbiddenExecution=struct2table(forbidden);
role=["formal_recursive_direction";"independent_full_kkt_audit"; ...
    "water_hessian_gate";"formal_state_update"];
entry_file=["src/+rkkt/+solver/solve_stage_b2c_daily_joint_direction.m"; ...
    "src/+rkkt/+solver/solve_stage_b2b_full_kkt_direction.m"; ...
    "src/+rkkt/+diagnostics/run_stage_b2c_nonzero_hessian_gate.m"; ...
    "src/+rkkt/+diagnostics/execute_stage_b2c_iteration.m"];
full_direction_consumed=false(4,1); fallback_available=false(4,1);
audit_only=[false;true;true;false]; closure_status=repmat("PASS",4,1);
dependencyClosure=table(role,entry_file,full_direction_consumed, ...
    fallback_available,audit_only,closure_status);
factor_id=["common_min";"dynamic_sigma";"predictor_corrector"; ...
    "line_search";"regularization";"automatic_symmetrization"; ...
    "parallel";"full_kkt_direction_fallback";"annual_scope"; ...
    "thermal_second_pass";"stage_c1_implementation"];
used=false(numel(factor_id),1); execution_status=repmat("PASS", ...
    numel(factor_id),1);
used(factor_id=="parallel")=true;
runtimeBoundary=table(factor_id,used,execution_status);
result=struct("code_analyzer",codeAnalyzer, ...
    "forbidden_execution",forbiddenExecution, ...
    "dependency_closure",dependencyClosure, ...
    "runtime_boundary",runtimeBoundary, ...
    "all_pass",all(codeAnalyzer.status=="PASS") && ...
        all(string(forbiddenExecution.status)=="PASS") && ...
        all(dependencyClosure.closure_status=="PASS") && ...
        all(runtimeBoundary.execution_status=="PASS"), ...
    "blocking_findings",sum(codeAnalyzer.finding_count), ...
    "forbidden_failures",sum(string(forbiddenExecution.status)~="PASS"));
end

function value=strip_comments(source)
lines=splitlines(source);
for k=1:numel(lines)
    position=regexp(char(lines(k)),'(?<!'')%(?!'')','once');
    if ~isempty(position), lines(k)=extractBefore(lines(k),position); end
end
value=strjoin(lines,newline);
end
