function result = run_stage_a2_direction_verification(data,index,config)
%RUN_STAGE_A2_DIRECTION_VERIFICATION Execute exactly one serial A2 direction.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
end
totalTimer = tic;
timer = tic;
state = rkkt.model.initialize_stage_a_state(data,index,config);
linearization = rkkt.model.build_stage_a_linearization(state,data,index,config);
timing.linearization_seconds = toc(timer);
timer = tic;
direct = rkkt.solver.solve_full_kkt_direction(linearization);
timing.full_kkt_direct_seconds = toc(timer);
timer = tic;
recursive = rkkt.solver.solve_recursive_direction(linearization, ...
    AssemblyTolerance=config.tolerances.symmetry_relative, ...
    SymmetryTolerance=config.tolerances.symmetry_relative);
timing.recursive_seconds = toc(timer);
timer = tic;
audit = rkkt.solver.verify_direction_equivalence(direct,recursive,linearization, ...
    DirectionRelative=config.tolerances.direction_relative_2norm, ...
    RecursiveResidual=config.tolerances.recursive_full_kkt_relative_residual, ...
    FullResidualPreferred=config.tolerances.direct_preferred, ...
    FullResidualMaximum=config.tolerances.direct_maximum);
physical = rkkt.model.recover_stage_a_physical_arrays(linearization.state.xi, ...
    recursive.components.xi,index,data);
timing.verification_seconds = toc(timer);
timing.total_seconds = toc(totalTimer);

assert(linearization.counts.full_kkt==config.expected_full_kkt_dimension, ...
    "stageA2:verification:FullKktDimension", ...
    "The complete A2 KKT dimension differs from the configured expectation.");
actualBlocks = [recursive.partition.hour.dimension];
assert(isequal(actualBlocks,config.expected_hourly_kkt_block_dimensions), ...
    "stageA2:verification:HourBlockDimension", ...
    "The natural 24-hour block dimensions differ from the configured expectation.");
assert(sum(actualBlocks)==config.expected_hourly_chain_dimension, ...
    "stageA2:verification:HourChainDimension", ...
    "The A2 hourly chain dimension differs from the configured expectation.");
assert(isequal(size(recursive.day_response.S),[14 14]), ...
    "stageA2:verification:DayResponseDimension", ...
    "The Stage A day response must remain 14-by-14.");
assert(isequal(size(recursive.core.matrix), ...
    [config.expected_global_core_dimension config.expected_global_core_dimension]), ...
    "stageA2:verification:CoreDimension","The A2 core must be 16-by-16.");
assert(recursive.no_full_direction_fallback, ...
    "stageA2:verification:RecursiveFallback", ...
    "Recursive output does not prove the no-fallback contract.");
assert(physical.fixed_zero_audit.count==config.expected_fixed_zero_count && ...
    physical.fixed_zero_audit.values_exact_zero && ...
    physical.fixed_zero_audit.directions_exact_zero, ...
    "stageA2:verification:FixedZero", ...
    "A2 fixed-zero removal/recovery did not match the exact contract.");

result = struct("state",state,"linearization",linearization, ...
    "direct",direct,"recursive",recursive,"audit",audit, ...
    "physical",physical,"timing",timing,"execution",struct( ...
    "newton_direction_count",1,"full_ipm_executed",false, ...
    "parallel_executed",false,"optimization_executed",false, ...
    "a2_solver_executed",true,"physical_dispatch_interpretation",false));
end
