function gate = run_stage_b2c_nonzero_hessian_gate( ...
        data,index,config,options)
%RUN_STAGE_B2C_NONZERO_HESSIAN_GATE Audit the mandatory unequal-dual state.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
    options.DiagnosticsDirectory (1,1) string = ""
end
state = rkkt.model.initialize_stage_b2c_state(data,index,config);
water = index.water_constraint_index;
waterRows = water.inequality_position(:);
upper = string(water.bound_type)=="upper";
lower = string(water.bound_type)=="lower";
state.z(waterRows(upper)) = config.nonzero_gate_water_upper_multiplier;
state.z(waterRows(lower)) = config.nonzero_gate_water_lower_multiplier;
state.nonzero_hessian_gate_state = true;
state.optimization_state = false;
state.initialization_version = "stage-B2C-nonzero-water-Hessian-gate-v1.0";

lin = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    state,data,index,config,"B-2C-NONZERO-HESSIAN-GATE");
[waterHessian,support] = rebuild_water_hessian(lin,index,data,config);
recursive = rkkt.solver.solve_stage_b2c_daily_joint_direction(lin, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance= ...
        config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    RefinementPasses=config.recursive_refinement_max_passes, ...
    CoreConsistencyMaximumPasses= ...
        config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation= ...
        config.compensated_core_accumulation);
fullAudit = rkkt.solver.solve_stage_b2b_full_kkt_direction(lin);
comparison = rkkt.solver.verify_stage_b2b_direction_equivalence( ...
    fullAudit,recursive,lin, ...
    DirectionRelative=config.direction_relative_error_tolerance, ...
    RecursiveResidual=config.recursive_full_kkt_residual_tolerance, ...
    FullResidual=config.full_kkt_residual_tolerance);

symmetry = norm(waterHessian-waterHessian.',"fro")/ ...
    max(1,norm(waterHessian,"fro"));
checks = [ ...
    "WATER_HESSIAN_NNZ"
    "WATER_HESSIAN_NONZERO_FROBENIUS"
    "WATER_HESSIAN_SYMMETRY"
    "UPPER_LOWER_HESSIAN_SIGN"
    "SAME_DAY_SAME_HYDRO_SUPPORT"
    "DIRECTION_OVERALL"
    "DIRECTION_XI"
    "DIRECTION_Y"
    "DIRECTION_L"
    "DIRECTION_Z"
    "RECURSIVE_FULL_KKT_RESIDUAL"
    "FULL_KKT_AUDIT_RESIDUAL"
    "FIXED_ZERO_COUNT"
    "FIXED_ZERO_VALUE_AND_DIRECTION"
    "NO_FULL_DIRECTION_FALLBACK"
    "FULL_DIRECTION_NOT_CONSUMED"];
actual = [nnz(waterHessian);norm(waterHessian,"fro");symmetry; ...
    double(support.sign_correct);double(support.support_correct); ...
    comparison.direction_relative_error; ...
    comparison.component_relative_errors.xi; ...
    comparison.component_relative_errors.y; ...
    comparison.component_relative_errors.l; ...
    comparison.component_relative_errors.z; ...
    comparison.recursive_kkt_relative_residual; ...
    comparison.full_kkt_relative_residual;recursive.fixed_zero.count; ...
    double(recursive.fixed_zero.all_exact_zero); ...
    double(recursive.no_full_direction_fallback); ...
    double(~recursive.full_direction_consumed)];
threshold = [config.expected_nonzero_water_hessian_nnz;0; ...
    config.lagrangian_hessian_symmetry_tolerance;1;1; ...
    repmat(config.direction_relative_error_tolerance,5,1); ...
    config.recursive_full_kkt_residual_tolerance; ...
    config.full_kkt_residual_tolerance; ...
    config.expected_stage_a_fixed_zero_count;1;1;1];
operator = ["==";">";"<=";"==";"==";repmat("<=",7,1); ...
    "==";"==";"==";"=="];
passed = [actual(1)==threshold(1);actual(2)>threshold(2); ...
    actual(3)<=threshold(3);actual(4)==1;actual(5)==1; ...
    actual(6:12)<=threshold(6:12);actual(13)==threshold(13); ...
    actual(14:16)==1];
status = repmat("PASS",numel(checks),1);
status(~passed) = "FAIL";
gateTable = table(checks,actual,operator,threshold,status, ...
    'VariableNames',{'check_id','actual_value','operator','threshold','status'});

component = ["overall";"xi";"y";"l";"z"; ...
    "recursive_full_kkt_residual";"full_kkt_audit_residual"];
directionValue = actual(6:12);
directionThreshold = threshold(6:12);
directionStatus = status(6:12);
directionTable = table(component,directionValue,directionThreshold, ...
    directionStatus,'VariableNames', ...
    {'component','actual_value','threshold','status'});
matrixTable = table(["H_water";"H_L";"A";"G";"full_KKT"], ...
    [size(waterHessian,1);size(lin.H,1);size(lin.A,1); ...
        size(lin.G,1);fullAudit.kkt.dimension], ...
    [size(waterHessian,2);size(lin.H,2);size(lin.A,2); ...
        size(lin.G,2);fullAudit.kkt.dimension], ...
    [nnz(waterHessian);nnz(lin.H);nnz(lin.A);nnz(lin.G); ...
        fullAudit.kkt.nnz], ...
    [symmetry;lin.lagrangian_hessian_symmetry_relative;NaN;NaN;NaN], ...
    ["mandatory_nonzero_gate";"shared_linearization"; ...
        "shared_linearization";"shared_linearization";"independent_audit_only"], ...
    repmat(string(lin.identity),5,1), ...
    'VariableNames',{'matrix_name','row_count','column_count', ...
    'nonzero_count','symmetry_relative','role','linearization_identity'});

gate = struct("passed",all(passed) && comparison.all_pass, ...
    "state",state,"linearization",lin,"water_hessian",waterHessian, ...
    "recursive",recursive,"full_audit",fullAudit,"comparison",comparison, ...
    "support_audit",support,"gate_table",gateTable, ...
    "direction_table",directionTable,"matrix_manifest",matrixTable, ...
    "water_hessian_nnz",nnz(waterHessian), ...
    "water_hessian_fro_norm",norm(waterHessian,"fro"), ...
    "water_hessian_symmetry_relative",symmetry, ...
    "no_full_direction_fallback",recursive.no_full_direction_fallback, ...
    "full_direction_consumed_by_recursive",recursive.full_direction_consumed);
if strlength(strip(options.DiagnosticsDirectory))>0
    persist_gate(gate,options.DiagnosticsDirectory);
end
assert(gate.passed,"stageB2C:gate:Failed", ...
    "The mandatory nonzero-water-Hessian direction gate failed.");
end

function [H,audit] = rebuild_water_hessian(lin,index,data,config)
dimension = index.counts.variables;
H = sparse(dimension,dimension);
records = lin.constraints.water.constraint_hessians;
signCorrect = true;
supportCorrect = true;
for k = 1:numel(records)
    record = records(k);
    multiplier = lin.z(record.inequality_position);
    H = H+multiplier*record.global_hessian;
    diagonal = diag(record.local_hessian);
    expectedSign = 1;
    if string(record.bound_type)=="lower", expectedSign = -1; end
    signCorrect = signCorrect && record.sign==expectedSign && ...
        all(sign(diagonal)==expectedSign) && ...
        all(abs(diagonal)==2*data.base.hydro.waterA(record.hydro_id));
    variables = index.variable_index(record.variable_indices,:);
    supportCorrect = supportCorrect && height(variables)==24 && ...
        all(variables.day==record.day) && ...
        all(variables.asset_id==record.hydro_id) && ...
        all(string(variables.variable_name)=="PH") && ...
        isequal(sort(variables.hour),(1:24).');
end
expected = sparse(dimension,dimension);
for d = config.days
    for h = config.hydro_ids
        mask = index.variable_index.day==d & ...
            string(index.variable_index.variable_name)=="PH" & ...
            index.variable_index.asset_id==h;
        columns = index.variable_index.global_index_start(mask);
        expected = expected+sparse(columns,columns, ...
            repmat(data.base.hydro.waterA(h),24,1),dimension,dimension);
    end
end
audit = struct("sign_correct",signCorrect, ...
    "support_correct",supportCorrect && isequal(H,expected), ...
    "expected_difference_nnz",nnz(H-expected), ...
    "expected_difference_fro_norm",norm(H-expected,"fro"));
end

function persist_gate(gate,directory)
if ~isfolder(directory)
    [created,message] = mkdir(directory);
    assert(created,"stageB2C:gate:Directory","%s",message);
end
paths = [ ...
    fullfile(directory,"nonzero_water_hessian_gate.csv")
    fullfile(directory,"nonzero_water_hessian_direction_comparison.csv")
    fullfile(directory,"nonzero_water_hessian_matrix_manifest.csv")
    fullfile(directory,"nonzero_water_hessian_gate.mat")];
assert(~any(isfile(paths)) && ~any(isfolder(paths)), ...
    "stageB2C:gate:RefuseOverwrite", ...
    "The nonzero-Hessian gate refuses to overwrite existing evidence.");
rkkt.artifacts.write_table_csv_17g(paths(1),gate.gate_table);
rkkt.artifacts.write_table_csv_17g(paths(2),gate.direction_table);
rkkt.artifacts.write_table_csv_17g(paths(3),gate.matrix_manifest);
rkkt.artifacts.save_mat_artifact(paths(4),"gate",gate);
end
