function result = run_stage_a3_direction_verification(data,index,config)
%RUN_STAGE_A3_DIRECTION_VERIFICATION Execute exactly one serial A3 direction.

arguments
    data (1,1) struct
    index (1,1) struct
    config (1,1) struct
end
totalTimer=tic;
timer=tic; state=rkkt.model.initialize_stage_a3_state(data,index,config);
linearization=rkkt.model.build_stage_a3_linearization(state,data,index,config);
timing.linearization_seconds=toc(timer);
timer=tic; direct=rkkt.solver.solve_stage_a3_full_kkt_direction(linearization);
timing.full_kkt_direct_seconds=toc(timer);
timer=tic;
recursive=rkkt.solver.solve_stage_a3_recursive_direction(linearization, ...
    AssemblyTolerance=config.tolerances.symmetry_relative, ...
    SymmetryTolerance=config.tolerances.symmetry_relative);
timing.recursive_seconds=toc(timer);
timer=tic;
audit=rkkt.solver.verify_stage_a3_direction_equivalence(direct,recursive,linearization, ...
    DirectionRelative=config.tolerances.direction_relative_2norm, ...
    RecursiveResidual=config.tolerances.recursive_full_kkt_relative_residual, ...
    FullResidualPreferred=config.tolerances.direct_preferred, ...
    FullResidualMaximum=config.tolerances.direct_maximum);
physical=rkkt.model.recover_stage_a_physical_arrays(linearization.state.xi, ...
    recursive.components.xi,index,data);
timing.verification_seconds=toc(timer); timing.total_seconds=toc(totalTimer);

assert(linearization.counts.full_kkt==config.expected_full_kkt_dimension&& ...
    direct.kkt.dimension==config.expected_full_kkt_dimension, ...
    "stageA3:verification:FullKktDimension", ...
    "The complete A3 KKT dimension differs from the configured expectation.");
assert(numel(recursive.daily_partitions)==config.expected_day_count&& ...
    numel(recursive.daily_responses)==config.expected_day_count&& ...
    numel(recursive.daily_thomas)==config.expected_day_count, ...
    "stageA3:verification:DailyCount","A3 requires seven daily results.");
actualChains=zeros(1,config.expected_day_count);
for k=1:config.expected_day_count
    actualChains(k)=size(recursive.daily_partitions(k).M,1);
    response=recursive.daily_responses(k);
    assert(double(response.day_id)==config.days(k)&& ...
        isequal(size(response.S),[14 14])&& ...
        isequal(size(response.c),[14 1])&& ...
        isequal(size(response.beta),[14 1])&& ...
        isequal(size(response.gamma),[14 1]), ...
        "stageA3:verification:DayResponseDimension", ...
        "Day %d response dimensions are invalid.",config.days(k));
end
assert(isequal(actualChains,config.expected_daily_hourly_chain_dimensions), ...
    "stageA3:verification:DailyChainDimension", ...
    "A3 daily chain dimensions differ from the data-derived contract.");
assert(isequal(size(recursive.core.matrix), ...
    [config.expected_global_core_dimension config.expected_global_core_dimension]), ...
    "stageA3:verification:CoreDimension","The A3 core must be 16-by-16.");
assert(isequal(double(recursive.aggregation.day_ids_sorted(:).'),config.days)&& ...
    recursive.aggregation.order_invariant_passed, ...
    "stageA3:verification:SortedAggregation", ...
    "A3 day responses were not deterministically sorted and aggregated.");
assert(recursive.no_full_direction_fallback&&~recursive.full_direction_consumed, ...
    "stageA3:verification:RecursiveFallback", ...
    "Recursive output does not prove the no-fallback contract.");
assert(physical.fixed_zero_audit.count==config.expected_fixed_zero_count&& ...
    physical.fixed_zero_audit.values_exact_zero&& ...
    physical.fixed_zero_audit.directions_exact_zero&& ...
    recursive.fixed_zero.all_exact_zero, ...
    "stageA3:verification:FixedZero", ...
    "A3 fixed-zero deletion/recovery did not match the exact contract.");

result=struct("state",state,"linearization",linearization, ...
    "direct",direct,"recursive",recursive,"audit",audit, ...
    "physical",physical,"timing",timing,"execution",struct( ...
    "newton_direction_count",1,"full_ipm_executed",false, ...
    "parallel_executed",false,"optimization_executed",false, ...
    "a3_solver_executed",true,"physical_dispatch_interpretation",false, ...
    "capacity_planning_interpretation",false, ...
    "economic_interpretation",false));
end
