function passed = stage_b2c_convergence_passed(metrics,config)
%STAGE_B2C_CONVERGENCE_PASSED Apply exactly the four frozen B-2C stops.

arguments
    metrics (1,1) struct
    config (1,1) struct
end
required = ["primal_equality_inf","primal_inequality_inf", ...
    "dual_scaled_inf","mean_lz_scaled"];
assert(all(isfield(metrics,cellstr(required))), ...
    "stageB2C:convergence:Metrics", ...
    "The four formal B-2C stopping metrics are required.");
passed = metrics.primal_equality_inf<= ...
        config.primal_equality_inf_tolerance && ...
    metrics.primal_inequality_inf<= ...
        config.primal_inequality_inf_tolerance && ...
    metrics.dual_scaled_inf<=config.dual_scaled_inf_tolerance && ...
    metrics.mean_lz_scaled<=config.mean_lz_scaled_tolerance;
passed = logical(passed);
end
