function audit = validate_stage_a3_test_inventory_contract(actual,projectRoot)
%VALIDATE_STAGE_A3_TEST_INVENTORY_CONTRACT Enforce the versioned A3 test set.

assert(istable(actual)&&isscalar(string(projectRoot)), ...
    "stageA3:tests:InventoryContractInput", ...
    "An actual inventory table and scalar project root are required.");
relativePath = "tests/stage_A3_expected_test_inventory.csv";
expectedPath = fullfile(string(projectRoot),strrep(relativePath,'/',filesep));
assert(isfile(expectedPath),"stageA3:tests:ExpectedInventoryMissing", ...
    "The version-controlled A3 expected test inventory is missing: %s", ...
    expectedPath);
expected = readtable(expectedPath,'Delimiter',',','ReadVariableNames',true, ...
    'TextType','string','VariableNamingRule','preserve');
required = ["test_order","test_name","source_file"];
expectedVariables=string(expected.Properties.VariableNames);
actualVariables=string(actual.Properties.VariableNames);
if ~all(ismember(required,expectedVariables))|| ...
        ~all(ismember(required,actualVariables))
    error("stageA3:tests:ExpectedInventorySchema", ...
        "Expected and actual A3 inventories require test_order, test_name, "+ ...
        "and source_file. expected_columns=[%s] actual_columns=[%s]", ...
        strjoin(expectedVariables,','),strjoin(actualVariables,','));
end
expected = expected(:,cellstr(required));
actual = actual(:,cellstr(required));

expectedNames = strip(string(expected.test_name));
actualNames = strip(string(actual.test_name));
expectedSources = replace(strip(string(expected.source_file)),'\','/');
actualSources = replace(strip(string(actual.source_file)),'\','/');
expectedOrder = double(expected.test_order);
actualOrder = double(actual.test_order);
assert(height(expected)>0&&all(strlength(expectedNames)>0)&& ...
    numel(unique(expectedNames))==height(expected)&& ...
    isequal(expectedOrder,(1:height(expected)).'), ...
    "stageA3:tests:ExpectedInventoryInvalid", ...
    "The controlled A3 inventory must be nonempty, unique, and consecutively ordered.");
assert(all(startsWith(expectedSources,"tests/")& ...
    contains(lower(expectedSources),"stage_a3")), ...
    "stageA3:tests:ExpectedInventorySource", ...
    "Every controlled A3 test must come from an explicit stage_a3 test file.");
assert(all(strlength(actualNames)>0)&& ...
    numel(unique(actualNames))==height(actual)&& ...
    isequal(actualOrder,(1:height(actual)).'), ...
    "stageA3:tests:ActualInventoryInvalid", ...
    "The discovered A3 inventory is empty, duplicated, or not consecutively ordered.");

missing = setdiff(expectedNames,actualNames,'stable');
unexpected = setdiff(actualNames,expectedNames,'stable');
orderMatches = isequal(actualNames,expectedNames);
sourceMatches = orderMatches&&isequal(actualSources,expectedSources);
if height(actual)~=height(expected)||~isempty(missing)|| ...
        ~isempty(unexpected)||~orderMatches||~sourceMatches
    error("stageA3:tests:ExpectedInventoryMismatch", ...
        "Discovered A3 tests differ from the controlled inventory. "+ ...
        "expected=%d actual=%d missing=[%s] unexpected=[%s] "+ ...
        "order_matches=%d source_matches=%d", ...
        height(expected),height(actual),strjoin(missing,','), ...
        strjoin(unexpected,','),orderMatches,sourceMatches);
end

audit = struct( ...
    "matches_expected",true, ...
    "expected_count",height(expected), ...
    "actual_count",height(actual), ...
    "expected_inventory_relative_path",char(relativePath), ...
    "expected_inventory_sha256",char(lower(string( ...
        rkkt.data.compute_sha256_file(expectedPath)))), ...
    "test_names_unique",numel(unique(actualNames))==height(actual), ...
    "missing_count",0,"unexpected_count",0, ...
    "order_matches",true,"source_files_match",true);
end
