function reportPaths = generate_stage_a3_reports(runContext,varargin)
%GENERATE_STAGE_A3_REPORTS Build three Chinese reports from persisted facts.

parser=inputParser; parser.FunctionName=mfilename;
addParameter(parser,'OutputDirectory',"",@is_text_scalar);
addParameter(parser,'FinalStatusCandidate',"",@is_text_scalar);
parse(parser,varargin{:});
assert(isstruct(runContext)&&isscalar(runContext)&&isfield(runContext,'root'), ...
    'stageA3:report:InvalidRunContext','runContext.root is required.');
runRoot=string(char(java.io.File(char(string(runContext.root))).getCanonicalPath()));
assert(isfolder(runRoot),'stageA3:report:MissingRunRoot','Run root is missing.');
facts=load_facts(runRoot); candidate=upper(strip(string( ...
    parser.Results.FinalStatusCandidate)));
if strlength(candidate)==0, candidate="PASS"; end
validate_facts(facts,candidate); facts.candidateStatus=candidate;
outputDirectory=strip(string(parser.Results.OutputDirectory));
if strlength(outputDirectory)==0, outputDirectory=fullfile(runRoot,'reports'); end
ensure_directory(outputDirectory);
reportPaths=struct( ...
    'model_report',fullfile(outputDirectory, ...
        '阶段A3_7日日响应汇总与方向等价报告.docx'), ...
    'issue_report',fullfile(outputDirectory,'阶段A3_问题修复与验收报告.docx'), ...
    'run_summary',fullfile(outputDirectory, ...
        "运行_"+safe_filename(facts.runId)+"_结果摘要.docx"));
targets=string(struct2cell(reportPaths)); assert_targets_absent(targets);
staging=string(tempname(tempdir)); mkdir(staging); guard=onCleanup(@()remove_tree(staging));
staged=[fullfile(staging,"model.docx");fullfile(staging,"issues.docx"); ...
    fullfile(staging,"summary.docx")];
metadata=struct("run_id",facts.runId,"stage_id",facts.stageId, ...
    "git_commit",facts.gitCommit,"manifest_status",facts.manifestStatus, ...
    "candidate_status",facts.candidateStatus);
write_stage_a3_docx(staged(1),'阶段A3_7日日响应汇总与方向等价报告', ...
    '第14—20日真实数据 · 7个独立正式日 · 单次 Newton 方向算法验收', ...
    metadata,build_model_blocks(facts));
write_stage_a3_docx(staged(2),'阶段A3_问题修复与验收报告', ...
    '六项阻断门禁、自动测试、问题证据与范围边界', ...
    metadata,build_issue_blocks(facts));
write_stage_a3_docx(staged(3),'阶段 A3 单次运行结果摘要', ...
    '7日日响应串行汇总证据（不构成优化、调度或经济结论）', ...
    metadata,build_summary_blocks(facts));
for k=1:numel(staged)
    [valid,details]=validate_docx_package(staged(k));
    assert(valid,'stageA3:report:InvalidDocxPackage','%s', ...
        strjoin(string(details.errors),'; '));
end
assert_targets_absent(targets);
names=fieldnames(reportPaths);
for k=1:numel(targets)
    [moved,message]=movefile(staged(k),targets(k));
    assert(moved,'stageA3:report:PublishFailed','%s',message);
    reportPaths.(names{k})=char(targets(k));
end
clear guard;
end

function facts=load_facts(root)
facts=struct(); facts.root=root;
facts.manifest=read_json(required(root,'run_manifest.json'));
facts.environment=read_csv(required(root,'environment.csv'));
facts.inputHashes=read_csv(required(root,'input_hashes.csv'));
facts.acceptance=read_csv(required(root,fullfile('acceptance','acceptance_results.csv')));
facts.issues=read_csv(required(root,fullfile('issues','issue_log.csv')));
facts.blocks=read_csv(required(root,fullfile('matrices','block_dimensions.csv')));
facts.chains=read_csv(required(root,fullfile('matrices','daily_chain_dimensions.csv')));
facts.responses=read_csv(required(root,fullfile('matrices','daily_response_summary.csv')));
facts.aggregation=read_csv(required(root,fullfile('matrices','daily_aggregation_audit.csv')));
facts.matrices=read_csv(required(root,fullfile('matrices','matrix_manifest.csv')));
facts.comparison=read_csv(required(root,fullfile('iterations','direction_comparison.csv')));
facts.residuals=read_csv(required(root,fullfile('iterations','residual_summary.csv')));
facts.fixed=read_csv(required(root,fullfile('indices','fixed_zero_map.csv')));
facts.fixedRecovery=read_csv(required(root, ...
    fullfile('indices','fixed_zero_recovery_audit.csv')));
facts.soc=read_csv(required(root,fullfile('indices','soc_boundary_audit.csv')));
facts.codeScan=read_csv(required(root,fullfile('diagnostics','code_scan.csv')));
facts.identity=read_json(required(root, ...
    fullfile('diagnostics','linearization_identity.json')));
facts.a3Inventory=read_csv(required(root,fullfile('tests','test_inventory.csv')));
facts.a3Results=read_csv(required(root,fullfile('tests','test_results.csv')));
facts.a3Summary=read_json(required(root,fullfile('tests','test_summary.json')));
facts.a2Inventory=read_csv(required(root, ...
    fullfile('tests','a2_regression','test_inventory.csv')));
facts.a2Results=read_csv(required(root, ...
    fullfile('tests','a2_regression','test_results.csv')));
facts.a2Summary=read_json(required(root, ...
    fullfile('tests','a2_regression','test_summary.json')));
facts.a1Inventory=read_csv(required(root, ...
    fullfile('tests','a1_regression','test_inventory.csv')));
facts.a1Results=read_csv(required(root, ...
    fullfile('tests','a1_regression','test_results.csv')));
facts.a1Summary=read_json(required(root, ...
    fullfile('tests','a1_regression','test_summary.json')));
facts.runId=required_manifest_text(facts.manifest,'run_id');
facts.stageId=required_manifest_text(facts.manifest,'stage_id');
facts.gitCommit=required_manifest_text(facts.manifest,'git_commit');
facts.manifestStatus=required_manifest_text(facts.manifest,'status');
end

function validate_facts(facts,candidate)
assert(facts.stageId=="stage_A3"&&facts.manifestStatus=="RUNNING", ...
    'stageA3:report:ManifestIdentity', ...
    'Reports require the matching RUNNING stage_A3 manifest.');
assert(candidate=="PASS",'stageA3:report:CandidateStatus', ...
    'Formal three-report generation requires PASS as the fact-derived candidate.');
blocking=to_logical(facts.environment.blocking);
assert(any(blocking)&&all(string(facts.environment.status(blocking))=="PASS"), ...
    'stageA3:report:EnvironmentEvidence', ...
    'Blocking environment evidence must be persisted PASS.');
assert(height(facts.inputHashes)==2&&all(string(facts.inputHashes.status)=="PASS")&& ...
    all(lower(string(facts.inputHashes.expectedSHA256))== ...
    lower(string(facts.inputHashes.actualSHA256))), ...
    'stageA3:report:InputHashEvidence', ...
    'Both controlled input SHA256 comparisons must be persisted PASS.');
expected=["SA3-MAT-001";"SA3-DAY-001";"SA3-CORE-001"; ...
    "SA3-EQ-001";"SA3-EQ-002";"SA3-SUM-001"];
acceptancePassed=height(facts.acceptance)==6&& ...
    isequal(string(facts.acceptance.test_id),expected)&& ...
    all(string(facts.acceptance.status)=="PASS");
if ~acceptancePassed
    error('stageA3:report:AcceptanceMismatch', ...
        'Expected six PASS rows; ids=%s; status=%s.', ...
        strjoin(string(facts.acceptance.test_id),','), ...
        strjoin(string(facts.acceptance.status),','));
end
assert(height(facts.issues)==0,'stageA3:report:UnresolvedIssues', ...
    'Formal PASS reports require an empty persisted issue_log.csv.');
assert(all_tests_pass(facts.a3Inventory,facts.a3Results,facts.a3Summary), ...
    'stageA3:report:A3Tests','Persisted A3 test evidence is inconsistent.');
assert(all_tests_pass(facts.a2Inventory,facts.a2Results,facts.a2Summary), ...
    'stageA3:report:A2Regression','Persisted A2 regression is inconsistent.');
assert(height(facts.a1Inventory)==37&& ...
    all_tests_pass(facts.a1Inventory,facts.a1Results,facts.a1Summary), ...
    'stageA3:report:A1Regression','All 37 A1 regression tests must pass.');
assert(height(facts.blocks)==168&&all(string(facts.blocks.status)=="PASS")&& ...
    height(facts.chains)==7&&all(string(facts.chains.status)=="PASS")&& ...
    height(facts.responses)==7&&all(string(facts.responses.status)=="PASS")&& ...
    height(facts.aggregation)==1&&string(facts.aggregation.status)=="PASS", ...
    'stageA3:report:DailyEvidence','Daily block/response evidence is invalid.');
assert(height(facts.soc)==350&&all(string(facts.soc.status)=="PASS"), ...
    'stageA3:report:SocEvidence','Seven-day SOC evidence is invalid.');
assert(all(double(facts.fixed.fixed_value)==0)&& ...
    all(double(facts.fixed.fixed_direction_value)==0)&& ...
    all(double(facts.fixedRecovery.recovered_value)==0)&& ...
    all(double(facts.fixedRecovery.recovered_direction)==0), ...
    'stageA3:report:FixedZeroEvidence','Fixed-zero evidence is invalid.');
assert(all(string(facts.codeScan.status)=="PASS")&& ...
    logical(facts.identity.all_identities_equal)&& ...
    logical(facts.identity.no_full_kkt_direction_fallback), ...
    'stageA3:report:ImplementationEvidence', ...
    'Code scan or shared-linearization identity evidence did not pass.');
assert(~logical(facts.manifest.parallel_executed)&& ...
    ~logical(facts.manifest.full_ipm_executed)&& ...
    ~logical(facts.manifest.optimization_executed)&& ...
    double(facts.manifest.newton_direction_count)==1&& ...
    logical(facts.manifest.a3_solver_executed), ...
    'stageA3:report:ScopeMismatch','Manifest execution scope is invalid.');
end

function passed=all_tests_pass(inventory,results,summary)
passed=height(inventory)==height(results)&&height(results)>0&& ...
    isequal(string(inventory.test_name),string(results.test_name))&& ...
    all(to_logical(results.passed))&&~any(to_logical(results.failed))&& ...
    ~any(to_logical(results.incomplete))&& ...
    double(summary.test_total)==height(results)&& ...
    double(summary.test_passed)==height(results)&& ...
    double(summary.test_failed)==0&&double(summary.test_incomplete)==0;
end

function blocks=build_model_blocks(facts)
blocks=empty_blocks();
blocks(end+1)=callout_block('验收结论', ...
    '六项阻断验收均为 PASS；本报告只记录一次 Newton 方向的算法等价证据。');
blocks(end+1)=heading_block('一、运行身份与冻结范围',1);
blocks(end+1)=table_block(["字段","实际值"],[ ...
    "真实数据窗口",display_text(facts.manifest.day_ids)+"，每日1—24小时"; ...
    "SOC边界",display_text(facts.manifest.soc_boundary_mode); ...
    "完整IPM / 优化 / 并行","未执行 / 未执行 / 未执行"; ...
    "Newton方向次数",display_text(facts.manifest.newton_direction_count)], ...
    [2700 6660]);
blocks(end+1)=paragraph_block(scope_text(facts));
blocks(end+1)=heading_block('受控输入 SHA256',2);
blocks(end+1)=selected_table_block(facts.inputHashes, ...
    ["file_name","actualSHA256","status"],[2400 5260 1700]);
blocks(end+1)=heading_block('二、六项阻断验收',1);
blocks(end+1)=selected_table_block(facts.acceptance, ...
    ["test_id","requirement","actual_value","status"], ...
    [1600 2500 3860 1400]);
blocks(end+1)=heading_block('三、7个日链与日响应',1);
daily=join(facts.chains(:,["day","chain_rows","block_count"]), ...
    facts.responses(:,["day","S_rows","S_columns", ...
    "gamma_identity_relative_residual","status"]),'Keys','day');
daily.response_dimension=string(daily.S_rows)+"x"+string(daily.S_columns);
blocks(end+1)=selected_table_block(daily, ...
    ["day","chain_rows","block_count","response_dimension", ...
    "gamma_identity_relative_residual","status"], ...
    [900 1300 1200 1600 2760 1600]);
blocks(end+1)=paragraph_block( ...
    '每日日响应分别保存 a_d、U_d、S_d、c_d、beta_d、gamma_d；c_d 与 gamma_d 独立持久化并验证 gamma_d=c_d-S_d*beta_d。');
blocks(end+1)=heading_block('四、排序汇总与16维核心',1);
blocks(end+1)=selected_table_block(facts.aggregation, ...
    ["input_order","day_ids_sorted","S_order_invariance_relative_error", ...
    "gamma_order_invariance_relative_error","status"], ...
    [2100 1900 2150 2210 1000]);
blocks(end+1)=table_block(["矩阵","实际维数"],[ ...
    "完整原始—对偶KKT",matrix_dimension(facts.matrices,"full_kkt"); ...
    "不等式消元后W",matrix_dimension(facts.matrices,"reduced_W"); ...
    "既约鞍点系统",matrix_dimension(facts.matrices,"reduced_saddle"); ...
    "汇总日响应S_sum",matrix_dimension(facts.matrices,"aggregated_response_S_sum"); ...
    "全局核心",matrix_dimension(facts.matrices,"global_core")],[4300 5060]);
blocks(end+1)=heading_block('五、方向误差与完整KKT残差',1);
blocks(end+1)=selected_table_block(facts.comparison, ...
    ["metric_id","actual_value","threshold","status"], ...
    [4000 1900 1800 1660]);
keyResidual=facts.residuals(isnan(double(facts.residuals.day_id)),:);
blocks(end+1)=selected_table_block(keyResidual, ...
    ["route","relative_residual_2norm","threshold","status"], ...
    [4400 2100 1600 1260]);
blocks(end+1)=heading_block('六、正式每日SOC与固定零恢复',1);
blocks(end+1)=table_block(["审计项","实际值"],[ ...
    "SOC审计行数",string(height(facts.soc)); ...
    "SOC审计PASS",string(nnz(string(facts.soc.status)=="PASS")); ...
    "跨日SOC连接","0（逐行回查索引）"; ...
    "fixed_zero_map",string(height(facts.fixed)); ...
    "固定值最大绝对值",format_number(max(abs(double(facts.fixedRecovery.recovered_value)))); ...
    "固定方向最大绝对值",format_number(max(abs(double(facts.fixedRecovery.recovered_direction))))], ...
    [3900 5460]);
blocks(end+1)=callout_block('解释边界', ...
    '未执行完整IPM、优化、容量规划、水电日用水约束、第二次火电处理或并行；不输出调度、经济性或物理运行结论。');
end

function blocks=build_issue_blocks(facts)
blocks=empty_blocks();
blocks(end+1)=callout_block('门禁状态', ...
    '六项阻断验收和三套测试均已通过；任何未记录事实均不得从本报告推断。');
blocks(end+1)=heading_block('一、问题日志',1);
if height(facts.issues)==0
    blocks(end+1)=paragraph_block('本次 issue_log.csv 无问题记录；没有未解释阻断项。');
else
    blocks(end+1)=selected_table_block(facts.issues, ...
        ["issue_id","test_id","elimination_layer","status","evidence_path"], ...
        [1600 1500 2300 1300 2660]);
end
blocks(end+1)=heading_block('二、验收闭环',1);
blocks(end+1)=selected_table_block(facts.acceptance, ...
    ["test_id","actual_value","comparison","status"], ...
    [1700 3000 3260 1400]);
blocks(end+1)=heading_block('三、自动测试与回归',1);
blocks(end+1)=test_summary_block(facts);
blocks(end+1)=heading_block('四、禁用方法扫描',1);
blocks(end+1)=selected_table_block(facts.codeScan, ...
    ["check_id","actual","status","evidence"],[3200 1200 1400 3560]);
blocks(end+1)=heading_block('五、结论与未解决项',1);
blocks(end+1)=paragraph_block( ...
    '当前真实工件没有记录未解决阻断项。本结论只适用于第14—20日、串行、单次Newton方向算法验收；A4尚未执行。');
blocks(end+1)=paragraph_block(scope_text(facts));
end

function blocks=build_summary_blocks(facts)
blocks=empty_blocks();
blocks(end+1)=callout_block('结果摘要', ...
    'Stage A3 六项阻断验收全部通过，事实推导候选终态为 PASS。');
blocks(end+1)=heading_block('关键事实',1);
blocks(end+1)=table_block(["指标","实际值"],[ ...
    "完整KKT",matrix_dimension(facts.matrices,"full_kkt"); ...
    "既约系统",matrix_dimension(facts.matrices,"reduced_saddle"); ...
    "7个日链",strjoin(string(facts.chains.chain_rows).',", "); ...
    "日响应",string(height(facts.responses))+"组，均14x14"; ...
    "全局核心",matrix_dimension(facts.matrices,"global_core"); ...
    "fixed_zero_map",string(height(facts.fixed)); ...
    "总体方向相对误差",metric_value(facts.comparison, ...
        "overall_direction_relative_2norm"); ...
    "递推方向代回完整KKT",residual_value(facts.residuals, ...
        "recursive_direction_reinserted_in_full_kkt",NaN); ...
    "完整KKT直接求解残差",residual_value(facts.residuals, ...
        "full_kkt_direct_hard_limit",NaN); ...
    "A3 / A2 / A1测试",facts.a3Summary.test_passed+"/"+ ...
        facts.a3Summary.test_total+"；"+facts.a2Summary.test_passed+"/"+ ...
        facts.a2Summary.test_total+"；"+facts.a1Summary.test_passed+"/"+ ...
        facts.a1Summary.test_total],[3900 5460]);
blocks(end+1)=heading_block('六项阻断验收',1);
blocks(end+1)=selected_table_block(facts.acceptance, ...
    ["test_id","actual_value","status"],[2100 5460 1800]);
blocks(end+1)=heading_block('边界声明',1);
blocks(end+1)=paragraph_block( ...
    '本次只验证7个完整正式日的一次Newton方向。未执行A4、完整IPM、优化或并行，也不生成容量规划、调度、经济性或物理运行结论。');
end

function block=test_summary_block(facts)
rows=[ ...
    "A3固定测试",string(facts.a3Summary.test_total), ...
        string(facts.a3Summary.test_passed),string(facts.a3Summary.test_failed), ...
        string(facts.a3Summary.test_incomplete); ...
    "A2回归",string(facts.a2Summary.test_total), ...
        string(facts.a2Summary.test_passed),string(facts.a2Summary.test_failed), ...
        string(facts.a2Summary.test_incomplete); ...
    "A1回归",string(facts.a1Summary.test_total), ...
        string(facts.a1Summary.test_passed),string(facts.a1Summary.test_failed), ...
        string(facts.a1Summary.test_incomplete)];
block=table_block(["测试集","总数","通过","失败","不完整"],rows, ...
    [2800 1500 1700 1600 1760]);
end

function blocks=empty_blocks()
blocks=repmat(block_template(),0,1);
end
function value=block_template()
value=struct("type","","level",0,"title","","text","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end
function block=heading_block(textValue,level)
block=block_template(); block.type="heading"; block.text=string(textValue);
block.level=level;
end
function block=paragraph_block(textValue)
block=block_template(); block.type="paragraph"; block.text=string(textValue);
end
function block=callout_block(titleText,textValue)
block=block_template(); block.type="callout"; block.title=string(titleText);
block.text=string(textValue);
end
function block=table_block(headers,rows,widths)
block=block_template(); block.type="table"; block.headers=string(headers);
block.rows=string(rows); block.widths=double(widths);
end
function block=selected_table_block(tableValue,columns,widths)
assert(all(ismember(columns,string(tableValue.Properties.VariableNames))), ...
    'stageA3:report:MissingColumn','Report evidence table is missing a column.');
rows=strings(height(tableValue),numel(columns));
for c=1:numel(columns)
    raw=tableValue.(columns(c));
    for r=1:height(tableValue), rows(r,c)=display_text(raw(r,:)); end
end
block=table_block(display_headers(columns),rows,widths);
end
function headers=display_headers(columns)
headers=replace(columns,"_"," ");
end
function value=matrix_dimension(matrix,name)
row=matrix(string(matrix.matrix_name)==string(name),:);
assert(height(row)==1,'stageA3:report:MatrixIdentity', ...
    'Missing or duplicate matrix evidence %s.',name);
value=string(row.rows)+"x"+string(row.columns);
end
function value=metric_value(tableValue,id)
row=tableValue(string(tableValue.metric_id)==string(id),:);
assert(height(row)==1,'stageA3:report:MetricIdentity','Missing metric %s.',id);
value=format_number(double(row.actual_value));
end
function value=residual_value(tableValue,route,dayId)
mask=string(tableValue.route)==string(route);
if isnan(dayId), mask=mask&isnan(double(tableValue.day_id)); ...
else, mask=mask&double(tableValue.day_id)==dayId; end
row=tableValue(mask,:);
assert(height(row)==1,'stageA3:report:ResidualIdentity', ...
    'Missing residual route %s.',route);
value=format_number(double(row.relative_residual_2norm));
end
function value=scope_text(facts)
value="实际启用：全局14维容量q、两个储能时长约束、一次容量投资目标与全局容量界；"+ ...
    "每日14维q_d及绑定、24小时自然变维块、日内SOC链和日末闭合。"+ ...
    "未启用：日用水、第二次火电、完整IPM、优化和并行。";
if isfield(facts.manifest,"enabled_components")
    value=value+" Manifest启用组件="+display_text(facts.manifest.enabled_components)+"。";
end
end
function pathValue=required(root,relative)
pathValue=fullfile(root,relative);
assert(isfile(pathValue),'stageA3:report:MissingArtifact', ...
    'Required persisted artifact is missing: %s',pathValue);
end
function value=read_json(pathValue)
try
    value=jsondecode(fileread(pathValue));
catch exception
    error('stageA3:report:InvalidJson','%s: %s',pathValue,exception.message);
end
end
function value=read_csv(pathValue)
try
    options=detectImportOptions(pathValue,'Encoding','UTF-8','Delimiter',',', ...
        'VariableNamingRule','preserve');
    options.VariableNamesLine=1; options.DataLines=[2 Inf];
    value=readtable(pathValue,options);
catch exception
    error('stageA3:report:InvalidCsv','%s: %s',pathValue,exception.message);
end
end
function value=required_manifest_text(manifest,name)
assert(isfield(manifest,name),'stageA3:report:ManifestField', ...
    'Manifest field %s is missing.',name);
value=string(manifest.(name));
assert(isscalar(value)&&strlength(strip(value))>0, ...
    'stageA3:report:ManifestField','Manifest field %s is invalid.',name);
end
function values=to_logical(raw)
if islogical(raw), values=raw; return; end
if isnumeric(raw), values=raw~=0; return; end
values=lower(strip(string(raw)))=="true"|strip(string(raw))=="1";
end
function textValue=display_text(value)
if iscell(value), value=value{1}; end
if isstring(value)||ischar(value)
    textValue=strjoin(string(value(:).'),", ");
elseif islogical(value)
    textValue=string(value);
elseif isnumeric(value)
    if isscalar(value), textValue=format_number(double(value)); ...
    else, textValue=string(mat2str(double(value))); end
else
    try
        textValue=string(jsonencode(value));
    catch
        textValue=string(value);
    end
end
end
function value=format_number(number)
if isnan(number), value="NaN"; elseif isinf(number), value=string(number); ...
else, value=compose("%.17g",number); end
end
function ensure_directory(pathValue)
if isfolder(pathValue), return; end
if isfile(pathValue), error('stageA3:report:PathConflict', ...
        'A file exists where reports/ is required: %s',pathValue); end
[created,message]=mkdir(pathValue);
assert(created,'stageA3:report:CreateDirectoryFailed','%s',message);
end
function assert_targets_absent(targets)
for target=targets.'
    if isfile(target)||isfolder(target)
        error('stageA3:report:ArtifactExists', ...
            'Refusing to overwrite existing report: %s',target);
    end
end
end
function name=safe_filename(value)
name=regexprep(string(value),'[^A-Za-z0-9._-]','_');
assert(strlength(name)>0,'stageA3:report:UnsafeFilename','Invalid run id.');
end
function remove_tree(pathValue)
if isfolder(pathValue), rmdir(pathValue,'s'); end
end
function tf=is_text_scalar(value)
tf=ischar(value)||(isstring(value)&&isscalar(value));
end
