function [reportPaths,validation] = generate_stage_a4_reports( ...
        runContext,options)
%GENERATE_STAGE_A4_REPORTS Build three Chinese reports from persisted facts.
%
% No solver result is accepted as a direct function argument.  Every number
% displayed in the reports is re-read from the current run's CSV/JSON
% evidence.  ReportGateMode="preflight" supports the first half of the
% circular SA4-RPT-001 gate.  A PASS candidate is gated strictly; a failed
% run is still reportable and its failed evidence remains visible.

arguments
    runContext (1,1) struct
    options.OutputDirectory (1,1) string = ""
    options.FinalStatusCandidate (1,1) string = "PASS"
    options.ReportGateMode (1,1) string {mustBeMember( ...
        options.ReportGateMode,["preflight","final"])} = "final"
end
assert(isfield(runContext,"root")&&isfield(runContext,"project_root"), ...
    "stageA4:report:InvalidRunContext", ...
    "runContext.root and runContext.project_root are required.");
runRoot = canonical_path(runContext.root);
assert(isfolder(runRoot),"stageA4:report:MissingRunRoot", ...
    "Run root is missing.");
facts = load_facts(runRoot);
facts.projectRoot = string(runContext.project_root);
facts.gateMode = options.ReportGateMode;
facts.candidateStatus = upper(strip(options.FinalStatusCandidate));
validate_facts(facts);

outputDirectory = strip(options.OutputDirectory);
if strlength(outputDirectory)==0
    outputDirectory = fullfile(runRoot,"reports");
end
ensure_directory(outputDirectory);
reportPaths = struct( ...
    "model_report",fullfile(outputDirectory, ...
        "阶段A4_模型与优化结果报告.docx"), ...
    "issue_report",fullfile(outputDirectory, ...
        "阶段A4_问题修复与验收报告.docx"), ...
    "run_summary",fullfile(outputDirectory, ...
        "运行_"+safe_filename(facts.runId)+"_结果摘要.docx"));
targets = string(struct2cell(reportPaths));
assert_targets_absent(targets);

staging = string(tempname(tempdir)); mkdir(staging);
guard = onCleanup(@()remove_tree(staging));
staged = [fullfile(staging,"model.docx"); ...
    fullfile(staging,"issues.docx");fullfile(staging,"summary.docx")];
metadata = struct( ...
    "run_id",facts.runId,"stage_id",facts.stageId, ...
    "git_commit",facts.gitCommit, ...
    "manifest_status",facts.manifestStatus, ...
    "candidate_status",metadata_candidate(facts));
write_stage_a4_docx(staged(1), ...
    "阶段A4 模型与优化结果报告", ...
    "第14—20日真实数据 · 7个独立正式日 · 完整原始—对偶内点迭代", ...
    metadata,build_model_blocks(facts));
write_stage_a4_docx(staged(2), ...
    "阶段A4 问题修复与验收报告", ...
    "收敛、逐轮方向审计、物理验收、测试与报告门禁", ...
    metadata,build_issue_blocks(facts));
write_stage_a4_docx(staged(3), ...
    "阶段 A4 单次运行结果摘要", ...
    "真实工件驱动的容量与小时运行结果", ...
    metadata,build_summary_blocks(facts));

stagedPaths = struct("model_report",char(staged(1)), ...
    "issue_report",char(staged(2)),"run_summary",char(staged(3)));
[valid,validation] = validate_stage_a4_report_set(stagedPaths,facts.runId);
assert(valid,"stageA4:report:InvalidDocxSet", ...
    "A4 report structural validation failed: %s", ...
    failed_validation_text(validation));

assert_targets_absent(targets);
names = fieldnames(reportPaths);
for k = 1:numel(targets)
    sourceHash = compute_sha256_file(staged(k));
    [moved,message] = movefile(staged(k),targets(k));
    assert(moved,"stageA4:report:PublishFailed","%s",message);
    assert(lower(string(compute_sha256_file(targets(k))))== ...
        lower(string(sourceHash)), ...
        "stageA4:report:PublishedHash", ...
        "Published A4 report hash changed.");
    reportPaths.(names{k}) = char(targets(k));
end
[valid,validation] = validate_stage_a4_report_set(reportPaths,facts.runId);
assert(valid,"stageA4:report:InstalledDocxSet", ...
    "Installed A4 report validation failed: %s", ...
    failed_validation_text(validation));
clear guard;
end

function facts = load_facts(root)
facts = struct(); facts.root = root;
facts.manifest = read_json(required(root,"run_manifest.json"));
facts.environment = read_csv(required(root,"environment.csv"));
facts.inputHashes = read_csv(required(root,"input_hashes.csv"));
facts.acceptance = read_csv(required(root, ...
    fullfile("acceptance","acceptance_results.csv")));
facts.physicalAudit = read_csv(required(root, ...
    fullfile("acceptance","physical_audit.csv")));
facts.issues = read_csv(required(root,fullfile("issues","issue_log.csv")));
facts.iterations = read_csv(required(root, ...
    fullfile("iterations","iteration_summary.csv")));
facts.direction = read_csv(required(root, ...
    fullfile("iterations","direction_audit.csv")));
facts.capacity = read_csv(required(root, ...
    fullfile("results","capacity_results.csv")));
facts.hourly = read_csv(required(root, ...
    fullfile("results","hourly_dispatch_results.csv")));
facts.resultHashes = read_csv(required(root, ...
    fullfile("results","result_artifact_hashes.csv")));
facts.matrices = read_csv(required(root, ...
    fullfile("matrices","matrix_manifest.csv")));
facts.checkpoints = read_csv(required(root, ...
    fullfile("checkpoints","checkpoint_manifest.csv")));
facts.testSummary = read_json(required(root, ...
    fullfile("tests","test_summary.json")));
facts.runId = required_manifest_text(facts.manifest,"run_id");
facts.stageId = required_manifest_text(facts.manifest,"stage_id");
facts.gitCommit = required_manifest_text(facts.manifest,"git_commit");
facts.manifestStatus = required_manifest_text(facts.manifest,"status");
end

function validate_facts(facts)
assert(facts.stageId=="stage_A4"&&facts.manifestStatus=="RUNNING", ...
    "stageA4:report:ManifestIdentity", ...
    "Reports require the matching RUNNING stage_A4 manifest.");
allowedCandidates = ["PASS","FAIL_RETRYABLE","BLOCKED_EXTERNAL", ...
    "NEEDS_MODEL_DECISION","MAX_ITERATIONS","NUMERICAL_FAILURE"];
assert(ismember(facts.candidateStatus,allowedCandidates), ...
    "stageA4:report:CandidateStatus", ...
    "Unsupported A4 report status candidate: %s.",facts.candidateStatus);
strictPass = facts.candidateStatus=="PASS";
validate_environment_and_inputs(facts,strictPass);
validate_acceptance(facts);
validate_execution_scope(facts.manifest,strictPass);
validate_iteration_evidence(facts.iterations,strictPass);
validate_direction_evidence(facts.direction,strictPass);
validate_result_evidence(facts,strictPass);
validate_issue_and_test_evidence(facts,strictPass);
if strictPass
    assert(height(facts.matrices)>0&&height(facts.checkpoints)>0, ...
        "stageA4:report:MatrixCheckpointEvidence", ...
        "PASS requires nonempty matrix and checkpoint manifests.");
end
end

function validate_environment_and_inputs(facts,strictPass)
requiredEnvironment = ["blocking","status"];
requiredInputs = ["file_name","expectedSHA256","actualSHA256","status"];
assert(all(ismember(requiredEnvironment, ...
    string(facts.environment.Properties.VariableNames)))&& ...
    all(ismember(requiredInputs, ...
    string(facts.inputHashes.Properties.VariableNames)))&& ...
    height(facts.inputHashes)==2, ...
    "stageA4:report:EnvironmentInputSchema", ...
    "Environment or controlled-input evidence is incomplete.");
blocking = to_logical(column(facts.environment,"blocking"));
status = upper(strip(string(column(facts.environment,"status"))));
inputStatus = upper(strip(string(column(facts.inputHashes,"status"))));
expected = lower(string(column(facts.inputHashes,"expectedSHA256")));
actual = lower(string(column(facts.inputHashes,"actualSHA256")));
assert(all(ismember(status,reportable_gate_statuses()))&& ...
    all(ismember(inputStatus,reportable_gate_statuses())), ...
    "stageA4:report:EnvironmentInputStatus", ...
    "Environment or input evidence contains an unsupported status.");
if strictPass
    assert(any(blocking)&&all(status(blocking)=="PASS"), ...
        "stageA4:report:EnvironmentEvidence", ...
        "Blocking environment evidence must be persisted PASS.");
    assert(all(inputStatus=="PASS")&&all(expected==actual), ...
        "stageA4:report:InputHashEvidence", ...
        "Both controlled input SHA256 comparisons must be persisted PASS.");
end
end

function validate_acceptance(facts)
expected = ["SA4-CONV-001";"SA4-CONV-002";"SA4-CONV-003"; ...
    "SA4-CONV-004";"SA4-EQ-001";"SA4-PHY-001";"SA4-RPT-001"];
ids = string(column(facts.acceptance,"test_id"));
status = upper(string(column(facts.acceptance,"status")));
assert(height(facts.acceptance)==7&&isequal(ids,expected)&& ...
    all(ismember(status,reportable_gate_statuses())), ...
    "stageA4:report:AcceptanceMismatch", ...
    "A4 acceptance rows must use canonical IDs and reportable statuses.");
if facts.candidateStatus=="PASS"
    assert(all(status(1:6)=="PASS"), ...
        "stageA4:report:AcceptanceMismatch", ...
        "A PASS candidate requires the six numerical A4 gates PASS.");
    if facts.gateMode=="final"
        assert(status(7)=="PASS", ...
            "stageA4:report:ReportGateNotPassed", ...
            "Final PASS reports require SA4-RPT-001=PASS.");
    else
        assert(ismember(status(7),["NOT_RUN","PASS"]), ...
            "stageA4:report:ReportGatePreflight", ...
            "PASS preflight requires SA4-RPT-001=NOT_RUN or PASS.");
    end
else
    assert(any(status~="PASS"), ...
        "stageA4:report:FailedCandidateWithoutFailedGate", ...
        "A non-PASS candidate must retain at least one failed or unrun gate.");
end
end

function validate_execution_scope(manifest,strictPass)
required = ["optimization_executed","full_ipm_executed", ...
    "physical_dispatch_interpretation","capacity_planning_interpretation", ...
    "parallel_executed","newton_direction_count", ...
    "enabled_components","disabled_components"];
assert(all(isfield(manifest,cellstr(required))), ...
    "stageA4:report:ExecutionScope", ...
    "Manifest execution scope is incomplete.");
assert(~logical(manifest.parallel_executed)&& ...
    double(manifest.newton_direction_count)>=0, ...
    "stageA4:report:ExecutionScope", ...
    "A4-3 reports require serial scope and a nonnegative direction count.");
if strictPass
    assert(logical(manifest.optimization_executed)&& ...
        logical(manifest.full_ipm_executed)&& ...
        logical(manifest.physical_dispatch_interpretation)&& ...
        logical(manifest.capacity_planning_interpretation)&& ...
        double(manifest.newton_direction_count)>0, ...
        "stageA4:report:ExecutionScope", ...
        "PASS requires a completed serial A4 optimization.");
end
end

function validate_iteration_evidence(value,strictPass)
requiredColumns = ["iteration","state_revision","objective_scaled", ...
    "objective_original","r_eq_inf","r_ineq_inf", ...
    "physical_inequality_violation","r_dual_scaled_inf", ...
    "r_dual_original_mapped_inf","r_comp_scaled_inf", ...
    "mean_lz_scaled","ltz_scaled","gap_original_mapped", ...
    "eta_eq","eta_dual","eta_gap","candidate_alpha_primal", ...
    "applied_alpha_primal","candidate_alpha_dual", ...
    "applied_alpha_dual","min_l","min_z","convergence_passed"];
assert(height(value)>0&& ...
    all(ismember(requiredColumns,string(value.Properties.VariableNames))), ...
    "stageA4:report:IterationSchema", ...
    "iteration_summary.csv is incomplete.");
iteration = numeric_column(value,"iteration");
assert(all(isfinite(iteration))&&all(diff(iteration)>0), ...
    "stageA4:report:IterationOrder", ...
    "Iteration identifiers must be finite and strictly increasing.");
if strictPass
    final = height(value);
    threshold = 1.0e-8;
    assert(numeric_at(value,"r_eq_inf",final)<=threshold&& ...
        numeric_at(value,"r_ineq_inf",final)<=threshold&& ...
        numeric_at(value,"r_dual_scaled_inf",final)<=threshold&& ...
        numeric_at(value,"mean_lz_scaled",final)<=threshold&& ...
        numeric_at(value,"physical_inequality_violation",final)<=threshold&& ...
        to_logical(column(value,"convergence_passed",final))&& ...
        isfinite(numeric_at(value,"objective_original",final)), ...
        "stageA4:report:ConvergenceEvidence", ...
        "The final persisted iteration does not meet all frozen thresholds.");
end
end

function validate_direction_evidence(value,strictPass)
requiredColumns = ["iteration","direction_relative_error", ...
    "xi_relative_error","y_relative_error", ...
    "l_relative_error","z_relative_error", ...
    "recursive_full_kkt_relative_residual", ...
    "full_kkt_relative_residual","no_full_direction_fallback", ...
    "full_kkt_audit_only","recursive_direction_is_official"];
assert(height(value)>0&& ...
    all(ismember(requiredColumns,string(value.Properties.VariableNames))), ...
    "stageA4:report:DirectionSchema", ...
    "direction_audit.csv is incomplete.");
metrics = requiredColumns(2:8);
for name = metrics
    numbers = numeric_column(value,name);
    if strictPass
        assert(all(isfinite(numbers))&&all(numbers<=1.0e-10), ...
            "stageA4:report:DirectionThreshold", ...
            "Persisted direction metric %s exceeds 1e-10.",name);
    end
end
if strictPass
    assert(all(to_logical(column(value,"no_full_direction_fallback")))&& ...
        all(to_logical(column(value,"full_kkt_audit_only")))&& ...
        all(to_logical(column(value,"recursive_direction_is_official"))), ...
        "stageA4:report:DirectionRole", ...
        "Every accepted direction must be recursive and independently audited.");
end
end

function validate_result_evidence(facts,strictPass)
assert(height(facts.capacity)==14&& ...
    isequal(string(column(facts.capacity,"capacity_name")), ...
        ["QW1";"QW2";"QW3";"QW4";"QW5"; ...
         "QP1";"QP2";"QP3";"QP4";"QP5"; ...
         "QS1";"QS2";"ES1";"ES2"]), ...
    "stageA4:report:CapacityEvidence", ...
    "capacity_results.csv must contain the 14 canonical rows.");
capacityStatus = upper(strip(string(column(facts.capacity,"status"))));
assert(all(ismember(capacityStatus,reportable_gate_statuses())), ...
    "stageA4:report:CapacityEvidence", ...
    "Capacity evidence contains an unsupported status.");
day = numeric_column(facts.hourly,"day");
hour = numeric_column(facts.hourly,"hour");
assert(height(facts.hourly)==4032&& ...
    isequal(unique(day,'stable'),(14:20).')&& ...
    isequal(unique(hour,'stable'),(1:24).')&& ...
    complete_day_hour_coverage(day,hour,24), ...
    "stageA4:report:HourlyEvidence", ...
    "hourly_dispatch_results.csv must contain exactly one complete 7x24 result scope.");
hourlyStatus = upper(strip(string(column(facts.hourly,"status"))));
assert(all(ismember(hourlyStatus,reportable_gate_statuses())), ...
    "stageA4:report:HourlyEvidence", ...
    "Hourly evidence contains an unsupported status.");
fixed = to_logical(column(facts.hourly,"fixed_zero"));
fixedExact = to_logical(column(facts.hourly,"fixed_zero_exact"));
hourlyValue = numeric_column(facts.hourly,"value");
assert(all(fixedExact)&&all(hourlyValue(fixed)==0), ...
    "stageA4:report:FixedZeroEvidence", ...
    "Persisted fixed-zero hourly results are not exact zeros.");
physicalStatus = upper(strip(string(column(facts.physicalAudit,"status"))));
assert(height(facts.physicalAudit)>0&& ...
    all(ismember(physicalStatus,reportable_gate_statuses())), ...
    "stageA4:report:PhysicalEvidence", ...
    "Physical evidence is empty or contains an unsupported status.");
assert(height(facts.resultHashes)>=4&& ...
    all(upper(string(column(facts.resultHashes,"status")))=="PASS"), ...
    "stageA4:report:ResultHashes", ...
    "Final result artifact hashes are missing or failed.");
if strictPass
    assert(all(capacityStatus=="PASS"), ...
        "stageA4:report:CapacityEvidence", ...
        "PASS requires 14 canonical capacity rows PASS.");
    assert(all(hourlyStatus=="PASS"), ...
        "stageA4:report:HourlyEvidence", ...
        "PASS requires every hourly result row PASS.");
    assert(all(physicalStatus=="PASS"), ...
        "stageA4:report:PhysicalEvidence", ...
        "PASS requires every physical audit row PASS.");
end

function passed = complete_day_hour_coverage(day,hour,rowsPerHour)
%COMPLETE_DAY_HOUR_COVERAGE Ensure every modeled day/hour appears exactly
% once per physical variable row; unique day/hour sets alone are insufficient.
if numel(day)~=numel(hour) || any(~isfinite(day)) || any(~isfinite(hour)) || ...
        any(day~=fix(day)) || any(hour~=fix(hour))
    passed = false;
    return
end
[dayGrid,hourGrid] = ndgrid(14:20,1:24);
expected = string(dayGrid(:))+"|"+string(hourGrid(:));
observed = string(day)+"|"+string(hour);
[expectedUnique,~,~] = unique(expected);
[observedUnique,~,observedGroup] = unique(observed);
if ~isequal(sort(expectedUnique),sort(observedUnique))
    passed = false;
    return
end
observedCounts = accumarray(observedGroup,1);
passed = all(observedCounts==rowsPerHour);
end
end

function validate_issue_and_test_evidence(facts,strictPass)
if strictPass&&height(facts.issues)>0
    issueStatus = upper(string(column(facts.issues,"status")));
    assert(~any(ismember(issueStatus,["OPEN","BLOCKED"])), ...
        "stageA4:report:UnresolvedIssues", ...
        "Final PASS reports cannot contain OPEN or BLOCKED issues.");
end
summary = facts.testSummary;
required = ["test_total","test_passed","test_failed","test_incomplete"];
assert(all(isfield(summary,cellstr(required)))&& ...
    all(isfinite(double([summary.test_total,summary.test_passed, ...
    summary.test_failed,summary.test_incomplete])))&& ...
    all(double([summary.test_total,summary.test_passed, ...
    summary.test_failed,summary.test_incomplete])>=0), ...
    "stageA4:report:TestEvidence", ...
    "Persisted A4 test summary is incomplete or invalid.");
if strictPass
    assert(double(summary.test_total)>0&& ...
        double(summary.test_passed)==double(summary.test_total)&& ...
        double(summary.test_failed)==0&&double(summary.test_incomplete)==0, ...
    "stageA4:report:TestEvidence", ...
    "Persisted A4 test summary is incomplete or not all PASS.");
end
end

function blocks = build_model_blocks(facts)
blocks = empty_blocks();
if facts.candidateStatus~="PASS"
    conclusion = "候选状态为 "+facts.candidateStatus+ ...
        "；本报告如实保留当前 run 的失败、未运行及通过证据，不作 PASS 解释。";
elseif facts.gateMode=="final"
    conclusion = "七项阻断验收均为 PASS；本报告只引用当前 run 已持久化工件。";
else
    conclusion = "六项数值阻断验收为 PASS；SA4-RPT-001 正在执行隔离报告预检。";
end
blocks(end+1) = callout_block("工件结论",conclusion);
blocks(end+1) = heading_block("一、运行身份与模型范围",1);
blocks(end+1) = table_block(["字段","实际值"],[ ...
    "真实数据窗口",display_text(facts.manifest.day_ids)+"，每日1—24小时"; ...
    "完整IPM / 优化 / 并行", ...
        execution_scope_text(facts.manifest); ...
    "火电口径",display_text(facts.manifest.thermal_pass); ...
    "Newton方向次数",display_text(facts.manifest.newton_direction_count)], ...
    [2700 6660]);
blocks(end+1) = table_block(["范围","组件"],[ ...
    "实际启用",display_text(facts.manifest.enabled_components); ...
    "明确未启用",display_text(facts.manifest.disabled_components)], ...
    [2100 7260]);
blocks(end+1) = heading_block("受控输入 SHA256",2);
blocks(end+1) = selected_table_block(facts.inputHashes, ...
    ["file_name","actualSHA256","status"],[2200 5660 1500]);

blocks(end+1) = heading_block("二、完整迭代与收敛",1);
trajectory = compact_iteration_display(facts.iterations);
blocks(end+1) = selected_table_block(trajectory, ...
    ["iteration","objective_original","r_eq_inf","r_ineq_inf", ...
    "r_dual_scaled_inf","mean_lz_scaled","convergence_passed"], ...
    [900 1700 1250 1250 1250 1510 1500]);
blocks(end+1) = paragraph_block( ...
    "完整逐轮数据见 iterations/iteration_summary.csv；上表只压缩显示首轮、每10轮及末轮。");
finalRow = height(facts.iterations);
blocks(end+1) = heading_block("末轮三种数值口径",2);
blocks(end+1) = table_block(["口径","指标","实际值"],[ ...
    "缩放KKT","r_eq / r_ineq", ...
        format_number(numeric_at(facts.iterations,"r_eq_inf",finalRow))+ ...
        " / "+format_number(numeric_at( ...
        facts.iterations,"r_ineq_inf",finalRow)); ...
    "缩放KKT","r_dual / r_comp", ...
        format_number(numeric_at(facts.iterations, ...
        "r_dual_scaled_inf",finalRow))+" / "+ ...
        format_number(numeric_at(facts.iterations, ...
        "r_comp_scaled_inf",finalRow)); ...
    "缩放KKT","mean(l.*z) / l'*z", ...
        format_number(numeric_at(facts.iterations, ...
        "mean_lz_scaled",finalRow))+" / "+ ...
        format_number(numeric_at(facts.iterations, ...
        "ltz_scaled",finalRow)); ...
    "原目标尺度映射","r_dual / gap", ...
        format_number(numeric_at(facts.iterations, ...
        "r_dual_original_mapped_inf",finalRow))+" / "+ ...
        format_number(numeric_at(facts.iterations, ...
        "gap_original_mapped",finalRow)); ...
    "无量纲审计","eta_eq / eta_dual / eta_gap", ...
        format_number(numeric_at(facts.iterations,"eta_eq",finalRow))+ ...
        " / "+format_number(numeric_at(facts.iterations, ...
        "eta_dual",finalRow))+" / "+ ...
        format_number(numeric_at(facts.iterations,"eta_gap",finalRow))], ...
    [1800 3000 4560]);
blocks(end+1) = paragraph_block( ...
    "停止条件只在 positive_scalar_unitized_kkt 坐标中判定；原目标尺度映射不套用相同绝对阈值。mean(l.*z) 是缩放KKT坐标中的互补均值，不是真正无量纲指标。");

blocks(end+1) = heading_block("三、14维容量优化结果",1);
blocks(end+1) = selected_table_block(facts.capacity, ...
    ["capacity_name","unit","value","lower_bound","upper_bound", ...
    "investment_cost_yuan","status"], ...
    [1300 700 1250 1250 1250 2160 1450]);
blocks(end+1) = table_block(["目标口径","实际值"],[ ...
    "容量分项投资合计（元）", ...
        format_number(sum(numeric_column( ...
        facts.capacity,"investment_cost_yuan"))); ...
    "末轮 iteration_summary 目标值", ...
        format_number(numeric_at(facts.iterations, ...
        "objective_original",height(facts.iterations)))],[4200 5160]);

blocks(end+1) = heading_block("四、小时运行结果",1);
blocks(end+1) = table_block(["审计项","实际值"],[ ...
    "完整长表路径","results/hourly_dispatch_results.csv"; ...
    "小时结果行数",string(height(facts.hourly)); ...
    "日/小时覆盖","第14—20日；每日日1—24小时"; ...
    "固定零行数",string(nnz(to_logical( ...
        column(facts.hourly,"fixed_zero")))); ...
    "固定零最大绝对值",format_number(max_fixed_value(facts.hourly))], ...
    [3300 6060]);
daily = daily_dispatch_summary(facts.hourly);
blocks(end+1) = selected_table_block(daily, ...
    ["day","wind_mwh","solar_mwh","hydro_mwh","thermal_mwh", ...
    "charge_mwh","discharge_mwh"], ...
    [600 1460 1460 1460 1460 1460 1460]);
soc = daily_soc_summary(facts.hourly);
blocks(end+1) = selected_table_block(soc, ...
    ["day","soc_min_mwh","soc_max_mwh"],[1200 4080 4080]);

blocks(end+1) = heading_block("五、逐轮方向与完整KKT审计",1);
blocks(end+1) = table_block(["审计量","逐轮最大值"],[ ...
    "总体方向相对误差",max_metric(facts.direction, ...
        "direction_relative_error"); ...
    "xi / y / l / z 分量误差最大值", ...
        max_component_metric(facts.direction); ...
    "递推方向代回完整KKT",max_metric(facts.direction, ...
        "recursive_full_kkt_relative_residual"); ...
    "完整KKT直接方向残差",max_metric(facts.direction, ...
        "full_kkt_relative_residual")],[4800 4560]);
blocks(end+1) = heading_block("六、物理验收",1);
blocks(end+1) = selected_table_block(facts.physicalAudit, ...
    ["audit_id","requirement","actual_value","threshold","status"], ...
    [1500 3100 1700 1600 1460]);
blocks(end+1) = heading_block("七、边界声明",1);
blocks(end+1) = paragraph_block( ...
    "本次启用阶段A投资目标、第一次火电0至Pmax、小时功率平衡、正式每日SOC闭合及连续储能变量。未启用水电日用水、第二次火电掩码、并行、最小开停机时间、启动/停机成本和年度多目标。");
end

function blocks = build_issue_blocks(facts)
blocks = empty_blocks();
if facts.candidateStatus~="PASS"
    gateText = "候选状态为 "+facts.candidateStatus+"；当前验收表中 PASS / FAIL / NOT_RUN 为 "+ ...
        acceptance_count_text(facts.acceptance)+"。";
elseif facts.gateMode=="final"
    gateText = "七项阻断验收均已由当前 run 工件闭环；没有 OPEN/BLOCKED 问题。";
else
    gateText = "数值与物理门禁已闭环；报告文件门禁处于隔离预检。";
end
blocks(end+1) = callout_block("门禁状态",gateText);
blocks(end+1) = heading_block("一、问题日志与修复",1);
if height(facts.issues)==0
    blocks(end+1) = paragraph_block( ...
        "本次 issue_log.csv 无问题记录；没有未解释的阻断问题。");
else
    issueColumns = intersect( ...
        ["issue_id","test_id","symptom","root_cause", ...
         "implemented_change","regression_test","status"], ...
        string(facts.issues.Properties.VariableNames),'stable');
    blocks(end+1) = issue_detail_table_block( ...
        facts.issues,issueColumns);
end
blocks(end+1) = heading_block("二、七项阻断验收",1);
acceptanceReport = facts.acceptance;
if ismember("threshold",string(acceptanceReport.Properties.VariableNames))
    thresholdText = string(acceptanceReport.threshold);
    thresholdText(thresholdText=="all physical audit rows PASS") = ...
        "物理审计均通过";
    thresholdText(thresholdText== ...
        "three artifact-backed Chinese DOCX reports validated") = ...
        "三份中文报告已验证";
    acceptanceReport.threshold = thresholdText;
end
if ismember("actual_value",string(acceptanceReport.Properties.VariableNames))
    actualText = string(acceptanceReport.actual_value);
    actualText(actualText=="report_evidence_not_provided") = ...
        "报告证据尚未提供";
    acceptanceReport.actual_value = actualText;
end
blocks(end+1) = selected_table_block(acceptanceReport, ...
    ["test_id","requirement","actual_value","threshold","status"], ...
    [1800 2500 2100 1500 1460]);
blocks(end+1) = heading_block("三、逐轮方向审计闭环",1);
blocks(end+1) = table_block(["项目","实际值"],[ ...
    "已审计迭代数",string(height(facts.direction)); ...
    "总体方向最大误差",max_metric(facts.direction, ...
        "direction_relative_error"); ...
    "递推完整KKT最大残差",max_metric(facts.direction, ...
        "recursive_full_kkt_relative_residual"); ...
    "完整KKT直接最大残差",max_metric(facts.direction, ...
        "full_kkt_relative_residual")],[4600 4760]);
blocks(end+1) = heading_block("四、自动测试与检查点",1);
blocks(end+1) = table_block(["证据","实际值"],[ ...
    "测试总数 / 通过 / 失败 / 不完整", ...
        display_text(facts.testSummary.test_total)+" / "+ ...
        display_text(facts.testSummary.test_passed)+" / "+ ...
        display_text(facts.testSummary.test_failed)+" / "+ ...
        display_text(facts.testSummary.test_incomplete); ...
    "检查点清单行数",string(height(facts.checkpoints)); ...
    "矩阵清单行数",string(height(facts.matrices)); ...
    "结果哈希清单行数",string(height(facts.resultHashes))], ...
    [4600 4760]);
blocks(end+1) = heading_block("五、报告结构与视觉门禁",1);
blocks(end+1) = paragraph_block( ...
    "三份DOCX必须先通过OOXML包、固定表格几何、中文字体、页眉页脚、表格行不可跨页和占位符检查；随后还必须经外部DOCX到逐页PNG渲染并逐页检查。结构通过不得替代视觉通过。");
blocks(end+1) = heading_block("六、未解决项",1);
blocks(end+1) = paragraph_block(unresolved_text(facts));
end

function blocks = build_summary_blocks(facts)
blocks = empty_blocks();
if facts.candidateStatus~="PASS"
    resultText = "Stage A4 候选状态为 "+facts.candidateStatus+ ...
        "；失败报告已生成，未将未通过门禁改写为 PASS。";
elseif facts.gateMode=="final"
    resultText = "Stage A4 七项阻断验收全部通过，事实推导候选终态为 PASS。";
else
    resultText = "Stage A4 六项数值阻断验收通过；报告门禁仍待最终安装复核。";
end
blocks(end+1) = callout_block("结果摘要",resultText);
finalRow = height(facts.iterations);
blocks(end+1) = heading_block("关键事实",1);
blocks(end+1) = table_block(["指标","实际值"],[ ...
    "迭代末轮",display_text(column(facts.iterations,"iteration",finalRow)); ...
    "目标值",format_number(numeric_at( ...
        facts.iterations,"objective_original",finalRow)); ...
    "原始等式残差",format_number(numeric_at( ...
        facts.iterations,"r_eq_inf",finalRow)); ...
    "不等式违反量",format_number(numeric_at( ...
        facts.iterations,"r_ineq_inf",finalRow)); ...
    "缩放KKT对偶残差",format_number(numeric_at( ...
        facts.iterations,"r_dual_scaled_inf",finalRow)); ...
    "缩放KKT mean(l.*z)",format_number(numeric_at( ...
        facts.iterations,"mean_lz_scaled",finalRow)); ...
    "缩放KKT l'*z",format_number(numeric_at( ...
        facts.iterations,"ltz_scaled",finalRow)); ...
    "原目标尺度映射 gap",format_number(numeric_at( ...
        facts.iterations,"gap_original_mapped",finalRow)); ...
    "无量纲 eta_eq / eta_dual / eta_gap", ...
        format_number(numeric_at(facts.iterations,"eta_eq",finalRow))+ ...
        " / "+format_number(numeric_at(facts.iterations, ...
        "eta_dual",finalRow))+" / "+ ...
        format_number(numeric_at(facts.iterations,"eta_gap",finalRow)); ...
    "总体方向最大误差",max_metric(facts.direction, ...
        "direction_relative_error"); ...
    "容量结果","14项；results/capacity_results.csv"; ...
    "小时结果",string(height(facts.hourly))+ ...
        "行；results/hourly_dispatch_results.csv"; ...
    "固定零",string(nnz(to_logical( ...
        column(facts.hourly,"fixed_zero"))))+"行，值精确为0"; ...
    "测试",display_text(facts.testSummary.test_passed)+"/"+ ...
        display_text(facts.testSummary.test_total)],[3900 5460]);
blocks(end+1) = heading_block("14维容量",1);
blocks(end+1) = selected_table_block(facts.capacity, ...
    ["capacity_name","unit","value","status"],[2200 1200 3900 2060]);
blocks(end+1) = heading_block("七项阻断验收",1);
blocks(end+1) = selected_table_block(facts.acceptance, ...
    ["test_id","actual_value","status"],[2100 5460 1800]);
blocks(end+1) = heading_block("边界声明",1);
blocks(end+1) = paragraph_block( ...
    "本摘要只陈述当前run已落盘的阶段A4七日连续优化结果。停止条件采用正标量单位化坐标；互补均值不是无量纲量，原尺度映射值不套用相同绝对1e-8阈值。未启用的约束与目标不得从本结果推断；完整小时明细以CSV和MAT工件为准。");
end

function value = compact_iteration_display(input)
iteration = numeric_column(input,"iteration");
mask = false(height(input),1);
mask(1) = true; mask(end) = true;
mask = mask|mod(iteration,10)==0;
value = input(mask,:);
end

function output = daily_dispatch_summary(hourly)
days = unique(numeric_column(hourly,"day"),'stable');
n = numel(days);
day = days; wind_mwh = zeros(n,1); solar_mwh = zeros(n,1);
hydro_mwh = zeros(n,1); thermal_mwh = zeros(n,1);
charge_mwh = zeros(n,1); discharge_mwh = zeros(n,1);
names = ["PW","PP","PH","PF","Pch","Pdis"];
targets = {wind_mwh,solar_mwh,hydro_mwh,thermal_mwh, ...
    charge_mwh,discharge_mwh};
variable = string(column(hourly,"variable_name"));
energy = numeric_column(hourly,"energy_mwh");
allDays = numeric_column(hourly,"day");
for k = 1:numel(names)
    values = zeros(n,1);
    for d = 1:n
        mask = allDays==days(d)&variable==names(k);
        values(d) = sum(energy(mask));
    end
    targets{k} = values;
end
wind_mwh = targets{1}; solar_mwh = targets{2};
hydro_mwh = targets{3}; thermal_mwh = targets{4};
charge_mwh = targets{5}; discharge_mwh = targets{6};
output = table(day,wind_mwh,solar_mwh,hydro_mwh,thermal_mwh, ...
    charge_mwh,discharge_mwh);
end

function output = daily_soc_summary(hourly)
days = unique(numeric_column(hourly,"day"),'stable');
day = days; soc_min_mwh = zeros(numel(days),1);
soc_max_mwh = zeros(numel(days),1);
allDays = numeric_column(hourly,"day");
variable = string(column(hourly,"variable_name"));
values = numeric_column(hourly,"value");
for d = 1:numel(days)
    mask = allDays==days(d)&variable=="SOC";
    soc_min_mwh(d) = min(values(mask));
    soc_max_mwh(d) = max(values(mask));
end
output = table(day,soc_min_mwh,soc_max_mwh);
end

function value = max_fixed_value(hourly)
fixed = to_logical(column(hourly,"fixed_zero"));
numbers = numeric_column(hourly,"value");
if any(fixed), value=max(abs(numbers(fixed))); else, value=0; end
end

function value = max_metric(tableValue,name)
value = format_number(max(numeric_column(tableValue,name)));
end

function value = max_component_metric(tableValue)
names = ["xi_relative_error","y_relative_error", ...
    "l_relative_error","z_relative_error"];
values = zeros(numel(names),1);
for k = 1:numel(names)
    values(k) = max(numeric_column(tableValue,names(k)));
end
value = strjoin(compose("%.17g",values).'," / ");
end

function value = unresolved_text(facts)
if height(facts.issues)==0
    if facts.candidateStatus=="PASS"
        value = "当前工件没有未解决问题；本结论不扩展到未启用模型组件。";
    else
        value = "issue_log.csv 没有问题行；非PASS原因仍以验收表、迭代及物理审计工件为准。";
    end
else
    issueStatus = upper(strip(string(column(facts.issues,"status"))));
    unresolved = nnz(ismember(issueStatus,["OPEN","BLOCKED"]));
    value = "issue_log.csv 共 "+string(height(facts.issues))+ ...
        " 行，其中 OPEN/BLOCKED "+string(unresolved)+" 行；逐项事实见上表。";
end
end

function blocks = empty_blocks()
blocks = repmat(block_template(),0,1);
end

function value = block_template()
value = struct("type","","level",0,"title","","text","", ...
    "headers",strings(1,0),"rows",strings(0,0), ...
    "widths",zeros(1,0));
end

function block = heading_block(textValue,level)
block = block_template(); block.type="heading";
block.text = string(textValue); block.level=level;
end

function block = paragraph_block(textValue)
block = block_template(); block.type="paragraph";
block.text = string(textValue);
end

function block = callout_block(titleText,textValue)
block = block_template(); block.type="callout";
block.title = string(titleText); block.text=string(textValue);
end

function block = table_block(headers,rows,widths)
block = block_template(); block.type="table";
block.headers = string(headers); block.rows=string(rows);
block.widths = double(widths);
end

function block = selected_table_block(tableValue,columns,widths)
assert(all(ismember(columns,string(tableValue.Properties.VariableNames))), ...
    "stageA4:report:MissingColumn", ...
    "Report evidence table is missing a requested column.");
rows = strings(height(tableValue),numel(columns));
for c = 1:numel(columns)
    raw = tableValue.(columns(c));
    for r = 1:height(tableValue)
        rows(r,c) = display_text(extract_row(raw,r));
    end
end
block = table_block(replace(columns,"_"," "),rows,widths);
end

function block = issue_detail_table_block(tableValue,columns)
labels = containers.Map( ...
    {'issue_id','test_id','symptom','root_cause', ...
     'implemented_change','regression_test','status'}, ...
    {'问题编号','关联验收','症状','根因', ...
     '已实施修改','回归测试','状态'});
rows = strings(height(tableValue)*numel(columns),2);
index = 0;
for r = 1:height(tableValue)
    for c = 1:numel(columns)
        index = index+1;
        field = char(columns(c));
        label = string(labels(field));
        if height(tableValue)>1
            label = "问题"+string(r)+" · "+label;
        end
        rows(index,:) = [label, ...
            display_text(extract_row(tableValue.(columns(c)),r))];
    end
end
block = table_block(["字段","工件原值"],rows,[2200 7160]);
end

function pathValue = required(root,relative)
pathValue = fullfile(root,relative);
assert(isfile(pathValue),"stageA4:report:MissingArtifact", ...
    "Required persisted artifact is missing: %s",pathValue);
end

function value = read_json(pathValue)
try
    value = jsondecode(fileread(pathValue));
catch exception
    error("stageA4:report:InvalidJson","%s: %s", ...
        pathValue,exception.message);
end
end

function value = read_csv(pathValue)
try
    options = detectImportOptions(pathValue,'Encoding','UTF-8', ...
        'Delimiter',',','VariableNamingRule','preserve');
    options.VariableNamesLine = 1; options.DataLines = [2 Inf];
    options = setvartype(options,options.VariableNames,'string');
    value = readtable(pathValue,options);
catch exception
    error("stageA4:report:InvalidCsv","%s: %s", ...
        pathValue,exception.message);
end
end

function value = required_manifest_text(manifest,name)
assert(isfield(manifest,name),"stageA4:report:ManifestField", ...
    "Manifest field %s is missing.",name);
value = string(manifest.(name));
assert(isscalar(value)&&strlength(strip(value))>0, ...
    "stageA4:report:ManifestField", ...
    "Manifest field %s is invalid.",name);
end

function value = column(tableValue,name,varargin)
assert(ismember(name,string(tableValue.Properties.VariableNames)), ...
    "stageA4:report:MissingColumn", ...
    "Persisted table is missing column %s.",name);
value = tableValue.(name);
if ~isempty(varargin)
    value = extract_row(value,varargin{1});
end
end

function value = extract_row(columnValue,row)
if iscell(columnValue)
    value = columnValue{row,:};
elseif ischar(columnValue)
    value = columnValue(row,:);
else
    value = columnValue(row,:);
end
end

function value = numeric_column(tableValue,name)
raw = column(tableValue,name);
if isnumeric(raw)
    value=double(raw);
else
    tokens = strip(string(raw));
    value=str2double(tokens);
    invalid = isnan(value)&~strcmpi(tokens,"NaN");
    assert(~any(invalid), ...
        "stageA4:report:InvalidNumericEvidence", ...
        "Persisted numeric column %s contains a nonnumeric token.",name);
end
value = reshape(value,[],1);
end

function value = numeric_at(tableValue,name,row)
values = numeric_column(tableValue,name); value=values(row);
end

function values = to_logical(raw)
if islogical(raw), values=raw; return; end
if isnumeric(raw), values=raw~=0; return; end
values = lower(strip(string(raw)))=="true"|strip(string(raw))=="1";
end

function textValue = display_text(value)
tokens = display_tokens(value);
textValue = strjoin(tokens.',", ");
end

function tokens = display_tokens(value)
if iscell(value)
    if isempty(value), tokens="[]"; return; end
    tokens = strings(0,1);
    for k = 1:numel(value)
        tokens = [tokens;display_tokens(value{k})]; %#ok<AGROW>
    end
elseif isstring(value)
    if isempty(value), tokens="[]"; return; end
    tokens = value(:); tokens(ismissing(tokens))="<missing>";
elseif ischar(value)
    if isempty(value)
        tokens = "[]";
    elseif isrow(value)
        tokens = string(value);
    else
        tokens = string(cellstr(value));
    end
elseif islogical(value)
    tokens = repmat("false",numel(value),1); tokens(value(:))="true";
elseif isnumeric(value)
    tokens = strings(numel(value),1);
    for k = 1:numel(value), tokens(k)=format_number(double(value(k))); end
else
    try
        tokens = string(jsonencode(value));
    catch
        tokens = string(value);
    end
end
end

function value = format_number(number)
if isnan(number), value="NaN";
elseif isinf(number), value=string(number);
else, value=compose("%.17g",number);
end
end

function value = metadata_candidate(facts)
if facts.candidateStatus~="PASS"
    value = facts.candidateStatus;
elseif facts.gateMode=="final"
    value=facts.candidateStatus;
else
    value="PENDING_REPORT_GATE";
end
end

function values = reportable_gate_statuses()
values = ["PASS","FAIL","NOT_RUN","NOT_APPLICABLE"];
end

function value = execution_scope_text(manifest)
value = executed_text(manifest.full_ipm_executed)+" / "+ ...
    executed_text(manifest.optimization_executed)+" / "+ ...
    executed_text(manifest.parallel_executed);
end

function value = executed_text(flag)
if logical(flag), value="已执行"; else, value="未执行"; end
end

function value = acceptance_count_text(acceptance)
status = upper(strip(string(column(acceptance,"status"))));
value = string(nnz(status=="PASS"))+" / "+ ...
    string(nnz(status=="FAIL"))+" / "+string(nnz(status=="NOT_RUN"));
end

function value = failed_validation_text(validation)
failed = validation(validation.status~="PASS",:);
if isempty(failed), value="none"; return; end
value = strjoin(failed.report_key+": "+failed.error_text,"; ");
end

function ensure_directory(pathValue)
if isfolder(pathValue), return; end
if isfile(pathValue)
    error("stageA4:report:PathConflict", ...
        "A file exists where reports/ is required: %s",pathValue);
end
[created,message] = mkdir(pathValue);
assert(created,"stageA4:report:CreateDirectoryFailed","%s",message);
end

function assert_targets_absent(targets)
for target = targets.'
    if isfile(target)||isfolder(target)
        error("stageA4:report:ArtifactExists", ...
            "Refusing to overwrite existing report: %s",target);
    end
end
end

function name = safe_filename(value)
name = regexprep(string(value),'[^A-Za-z0-9._-]','_');
assert(strlength(name)>0,"stageA4:report:UnsafeFilename", ...
    "Invalid run id.");
end

function pathValue = canonical_path(pathValue)
pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end

function remove_tree(pathValue)
if isfolder(pathValue), rmdir(pathValue,'s'); end
end
