function report = generate_stage_b1_report(runRoot)
%GENERATE_STAGE_B1_REPORT Build the Chinese B-1 report from run artifacts.
%
% No in-memory numerical result is accepted. Every reported fact is reread
% from the persisted run directory.

arguments
    runRoot (1,1) string
end
runRoot = string(java.io.File(char(runRoot)).getCanonicalPath());
manifest = read_json(required(runRoot,"run_manifest.json"));
water = read_csv(required(runRoot, ...
    fullfile("diagnostics","water_input_audit.csv")));
derivatives = read_csv(required(runRoot, ...
    fullfile("diagnostics","derivative_check.csv")));
acceptance = read_csv(required(runRoot, ...
    fullfile("acceptance","acceptance_results.csv")));
testSummary = read_json(required(runRoot, ...
    fullfile("tests","test_summary.json")));
inputHashes = read_csv(required(runRoot,"input_hashes.csv"));
environment = read_csv(required(runRoot,"environment.csv"));
issueLog = read_csv(required(runRoot, ...
    fullfile("issues","issue_log.csv")));

assert(height(water)==28 && all(string(water.status)=="PASS"), ...
    "stageB1:report:WaterEvidence", ...
    "Report requires exactly 28 passing water-input rows.");
assert(height(derivatives)==112 && ...
    all(string(derivatives.status)=="PASS"), ...
    "stageB1:report:DerivativeEvidence", ...
    "Report requires 112 passing derivative samples.");
assert(height(acceptance)==4 && ...
    all(string(acceptance.status(1:2))=="PASS") && ...
    all(string(acceptance.status(3:4))=="NOT_RUN"), ...
    "stageB1:report:AcceptanceEvidence", ...
    "B-1 acceptance must be PASS/PASS/NOT_RUN/NOT_RUN.");
assert(testSummary.test_total==14 && testSummary.test_passed==14 && ...
    testSummary.test_failed==0 && testSummary.test_incomplete==0, ...
    "stageB1:report:TestEvidence", ...
    "Report requires the exact 14/14 B-1 fixed test evidence.");
blockingMask = logical_column(environment.blocking);
assert(all(string(inputHashes.status)=="PASS") && ...
    all(string(environment.status(blockingMask))=="PASS"), ...
    "stageB1:report:IdentityEvidence", ...
    "Input hashes and blocking environment checks must pass.");
assert(isempty(issueLog),"stageB1:report:IssueEvidence", ...
    "A passing B-1 report requires no open issue rows.");

maxGradient = max(derivatives.gradient_relative_error);
maxHessian = max(derivatives.hessian_relative_error);
candidate = "B-1 PASS / Stage B READY";
metadata = struct( ...
    "run_id",string(manifest.run_id), ...
    "stage_id","stage_B / B-1", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status",string(manifest.status), ...
    "candidate_status",candidate, ...
    "report_kicker","STAGE B-1 · 水量数据与解析导数基线", ...
    "header_label","STAGE B-1 · 数据与导数只读证据");

blocks = repmat(block_template(),0,1);
blocks(end+1) = callout_block("结论边界", ...
    "本报告仅确认第14—20日四座水电站的28条日用水上下限数据，以及单站单日水耗函数的解析梯度和Hessian。B-1里程碑通过不等于Stage B整体通过。");
blocks(end+1) = heading_block(1,"1. 里程碑结论");
acceptanceRows = [ ...
    "SB-DATA-001","28条日—电站记录","PASS", ...
        compose("%d行",height(water)); ...
    "SB-DER-001","梯度/Hessian相对误差 <= 1e-7","PASS", ...
        compose("grad=%.3e; Hess=%.3e",maxGradient,maxHessian); ...
    "SB-EQ-001","扩展模型方向等价","NOT_RUN","B-1未执行"; ...
    "SB-PHY-001","优化后每日水量违反量","NOT_RUN","B-1未执行"];
blocks(end+1) = table_block( ...
    ["验收ID","要求","状态","实际证据"], ...
    acceptanceRows,[1500,2800,1400,3660]);
blocks(end+1) = paragraph_block( ...
    "固定B-1测试为14/14 PASS；失败0，不完整0。问题日志无记录。CURRENT_STAGE仍为stage_B / READY。");

blocks(end+1) = heading_block(1,"2. 数据来源与数学口径");
blocks(end+1) = paragraph_block( ...
    "唯一Excel读取路线为src/data/load_project_data.m。输入哈希来自input_hashes.csv；未建立第二套Excel解析代码。");
blocks(end+1) = paragraph_block( ...
    "冻结公式：W(d,u)=sum_{t=1}^{24}[a(u)·PH(d,u,t)^2+b(u)·PH(d,u,t)+c(u)]。24项直接求和，不乘小时长度、3600或额外比例。PH单位为MW，W及上下限单位为m3/day；常数c每日累计24次。");
blocks(end+1) = heading_block(2,"2.1 四台水电机组系数");
coefficientRows = strings(4,5);
for hydro = 1:4
    row = find(water.hydro_id==hydro,1,"first");
    coefficientRows(hydro,:) = [string(hydro), ...
        concise_text(water.water_a(row)), ...
        concise_text(water.water_b(row)), ...
        concise_text(water.water_c(row)), ...
        compose("%.0f",water.max_output_mw(row))];
end
blocks(end+1) = table_block( ...
    ["水电站","a","b","c","Pmax (MW)"], ...
    coefficientRows,[1200,1800,1800,2200,2360]);

blocks(end+1) = heading_block(2,"2.2 第14—20日28条权威上下限");
waterRows = strings(28,5);
for row = 1:28
    waterRows(row,:) = [number_text(water.day(row)), ...
        number_text(water.hydro_id(row)), ...
        compose("%.2f",water.water_min_m3(row)), ...
        compose("%.2f",water.water_max_m3(row)), ...
        string(water.status(row))];
end
blocks(end+1) = table_block( ...
    ["日","水电站","Wmin (m3/day)","Wmax (m3/day)","状态"], ...
    waterRows,[900,1200,2700,2700,1860]);

blocks(end+1) = heading_block(1,"3. 解析导数与独立有限差分");
blocks(end+1) = paragraph_block( ...
    "对同一日同一水电站的24维出力P：gradient_W=2aP+b，Hessian_W=2a·I_24。上界g_upper=W-Wmax的导数取正号；下界g_lower=Wmin-W的导数取负号。不同小时Hessian非对角元精确为0，不同日期和水电站无导数耦合。");
summaryRows = [ ...
    "确定性样本数",number_text(height(derivatives)),"112"; ...
    "最大梯度相对误差",compose("%.8e",maxGradient),"<=1e-7"; ...
    "最大Hessian相对误差",compose("%.8e",maxHessian),"<=1e-7"; ...
    "上/下界符号","全部PASS","必须PASS"; ...
    "跨小时/跨资产","全部PASS","必须PASS"];
blocks(end+1) = table_block( ...
    ["指标","实际值","阈值"],summaryRows,[3000,3360,3000]);
blocks(end+1) = paragraph_block( ...
    "数值参考由独立标量循环、中心差分梯度及数值梯度中心差分Hessian构造；四类确定性点覆盖内部非均匀、接近零和接近Pmax出力。有限差分步长已逐样本持久化于derivative_check.csv和MAT工件。");

blocks(end+1) = heading_block(1,"4. 输入、环境与证据");
hashRows = strings(height(inputHashes),3);
for row = 1:height(inputHashes)
    hashRows(row,:) = [string(inputHashes.file_name(row)), ...
        string(inputHashes.actualSHA256(row)),string(inputHashes.status(row))];
end
blocks(end+1) = table_block( ...
    ["输入文件","实际SHA256","状态"],hashRows,[2200,5360,1800]);
blocks(end+1) = paragraph_block( ...
    "MAT工件保存28条权威数据、112个测试点、解析/数值梯度与Hessian、逐变量差分步长和汇总；CSV浮点数按至少17位有效数字输出。报告中的数值全部由本run工件重读。");

blocks(end+1) = heading_block(1,"5. 明确未执行内容");
blocks(end+1) = callout_block("停止边界", ...
    "本次未装配完整KKT，未建立递推日响应，未求Newton方向，未运行IPM或优化，未验证最终物理水量可行性，未修改LDL/Thomas，未执行火电第二次、并行、30日、365日或Stage C1。SB-EQ-001与SB-PHY-001保持NOT_RUN。");
blocks(end+1) = paragraph_block( ...
    "下一动作仅为B-2：在另行授权后扩展linearization、完整KKT与递推日响应；本报告不提供容量规划、调度、经济性或物理运行结论。");

outputPath = fullfile(runRoot,"reports", ...
    "阶段B-1_水量数据与导数基线报告.docx");
write_stage_b1_docx(outputPath, ...
    "阶段B-1：水量数据与解析导数基线报告", ...
    "第14—20日 · 4座水电站 · 28条数据 · 112个确定性导数样本", ...
    metadata,blocks);
[valid,details] = validate_stage_b1_report(runRoot);
assert(valid,"stageB1:report:Validation", ...
    "Generated B-1 report is invalid: %s",details.message);
report = struct("path",string(outputPath), ...
    "run_id",string(manifest.run_id), ...
    "maximum_gradient_relative_error",maxGradient, ...
    "maximum_hessian_relative_error",maxHessian, ...
    "structure_valid",valid);
end

function value = required(root,relative)
value = fullfile(root,relative);
assert(isfile(value),"stageB1:report:MissingArtifact", ...
    "Required B-1 artifact is missing: %s",value);
end

function value = read_csv(pathValue)
options = detectImportOptions(pathValue,"Delimiter",",", ...
    "TextType","string","VariableNamingRule","preserve");
value = readtable(pathValue,options);
end

function value = read_json(pathValue)
value = jsondecode(fileread(pathValue));
end

function value = logical_column(raw)
if islogical(raw)
    value = raw;
elseif isnumeric(raw)
    value = raw~=0;
else
    textValue = lower(strip(string(raw)));
    assert(all(ismember(textValue,["true","false","1","0"])), ...
        "stageB1:report:LogicalColumn", ...
        "Environment blocking column is not logical.");
    value = textValue=="true" | textValue=="1";
end
value = value(:);
end

function value = number_text(number)
if ~isnumeric(number)
    number = double(number);
end
value = compose("%.17g",number);
end

function value = concise_text(number)
value = compose("%.6g",double(number));
end

function value = block_template()
value = struct("type","","level",0,"text","","title","", ...
    "headers",strings(1,0),"rows",strings(0,0),"widths",zeros(1,0));
end

function value = heading_block(level,textValue)
value = block_template();
value.type = "heading";
value.level = level;
value.text = string(textValue);
end

function value = paragraph_block(textValue)
value = block_template();
value.type = "paragraph";
value.text = string(textValue);
end

function value = callout_block(titleValue,textValue)
value = block_template();
value.type = "callout";
value.title = string(titleValue);
value.text = string(textValue);
end

function value = table_block(headers,rows,widths)
value = block_template();
value.type = "table";
value.headers = reshape(string(headers),1,[]);
value.rows = string(rows);
value.widths = reshape(double(widths),1,[]);
assert(size(value.rows,2)==numel(value.headers) && ...
    numel(value.widths)==numel(value.headers) && ...
    sum(value.widths)==9360,"stageB1:report:TableShape", ...
    "Every B-1 table must use exact 9360-DXA geometry.");
end
