function [reportPath,validation] = ...
        generate_stage_a4_iteration24_scaling_stress_report(context)
%GENERATE_STAGE_A4_ITERATION24_SCALING_STRESS_REPORT Build artifact report.
%
% Every numerical value is read back from the current unique stress run.
% The report never treats a single frozen-direction PASS as Stage A4 PASS.

arguments
    context (1,1) struct
end

root = string(context.root);
diagnostics = fullfile(root,"diagnostics");
manifest = read_json(fullfile(root,"run_manifest.json"));
summary = read_json(fullfile(diagnostics,"stress_summary.json"));
identity = read_json(fullfile(diagnostics,"stress_identity.json"));
hourly = read_csv(fullfile(diagnostics,"hourly_factor_audit.csv"));
direction = read_csv(fullfile(diagnostics,"direction_audit.csv"));
refinement = read_csv(fullfile(diagnostics,"refinement_audit.csv"));
forbidden = read_csv(fullfile(diagnostics,"forbidden_execution_audit.csv"));
modelScope = read_csv(fullfile(diagnostics,"model_scope_audit.csv"));
acceptance = read_csv(fullfile(root,"acceptance","acceptance_results.csv"));
issues = read_csv(fullfile(root,"issues","issue_log.csv"));
inputHashes = read_csv(fullfile(root,"input_hashes.csv"));
testSummary = read_json(fullfile(root,"tests","test_summary.json"));
historicalAudit = read_json(fullfile(root,"historical_runs_audit.json"));
assert(string(manifest.status)=="RUNNING" && ...
    string(manifest.stage_id)=="stage_A4" && ...
    string(summary.stress_status)=="PASS" && ...
    ~logical(summary.stage_a4_pass_claimed) && ...
    logical(historicalAudit.passed), ...
    "stageA4:scaleStress:ReportFacts", ...
    "Persisted scaling-stress facts are inconsistent.");

reportPath = fullfile(root,"reports", ...
    "阶段A4_第24轮数值稳定性修复压力测试报告.docx");
metadata = struct( ...
    "run_id",string(context.run_id), ...
    "stage_id","stage_A4", ...
    "git_commit",string(manifest.git_commit), ...
    "manifest_status","RUNNING", ...
    "manifest_status_note", ...
        "报告生成时manifest为RUNNING；主入口最终化后以run_manifest.json为准", ...
    "candidate_status","压力测试PASS；Stage A4仍为READY", ...
    "report_kicker","STAGE A4 · 冻结第24轮数值稳定性压力测试", ...
    "header_label","STAGE A4 · 局部合同尺度化＋stable-v2");
blocks = build_blocks(summary,identity,hourly,direction, ...
    refinement,forbidden,modelScope,acceptance,issues,inputHashes, ...
    testSummary,manifest,historicalAudit);
write_stage_a4_docx(reportPath, ...
    "阶段A4 第24轮数值稳定性修复压力测试报告", ...
    "权威第23轮状态 · 单次Newton方向 · 无状态更新", ...
    metadata,blocks);
[valid,validation] = validate_docx_package(reportPath);
required = [ ...
    "局部对称对角合同尺度化"; ...
    "原始未尺度化算子"; ...
    "完整KKT仅用于独立审计"; ...
    "没有执行状态更新"; ...
    "Stage A4仍为READY"; ...
    "不代表Stage A4通过"; ...
    "报告生成时manifest为RUNNING"; ...
    "最终终态以run_manifest.json为准"; ...
    "已启用目标和约束"; ...
    "未启用目标和约束"; ...
    "原始历史runs未修改"];
for k=1:numel(required)
    if ~contains(validation.document_text,required(k))
        valid = false;
        validation.errors(end+1) = ...
            "Missing required report statement: "+required(k);
    end
end
assert(valid,"stageA4:scaleStress:ReportValidation", ...
    "Scaling-stress DOCX validation failed: %s", ...
    strjoin(validation.errors,"; "));
end

function blocks = build_blocks(summary,identity,hourly,direction, ...
        refinement,forbidden,modelScope,acceptance,issues,inputHashes, ...
        testSummary,manifest,historicalAudit)
blocks = empty_blocks();
blocks(end+1) = callout_block("结论边界", ...
    "冻结的第24轮压力输入已通过局部对称对角合同尺度化与stable-v2"+ ...
    "保留因子残差精化：递推方向与完整稀疏KKT审计方向满足1e-10工程"+ ...
    "门槛。本次没有执行状态更新、完整IPM、优化或并行；压力测试PASS"+ ...
    "不代表Stage A4通过，Stage A4仍为READY。");

blocks(end+1) = heading_block("一、权威输入与冻结边界",1);
blocks(end+1) = table_block(["项目","持久化事实"],[ ...
    "父运行",string(identity.authority_run_id); ...
    "权威状态修订 / 尝试轮次", ...
        string(identity.state_revision)+" / 24"; ...
    "状态指纹",string(identity.state_fingerprint_before); ...
    "linearization指纹", ...
        string(identity.linearization_fingerprint); ...
    "失败证据SHA256", ...
        string(identity.failure_evidence_sha256); ...
    "权威manifest SHA256", ...
        string(identity.authority_manifest_sha256); ...
    "effective_config SHA256", ...
        string(identity.effective_config_sha256); ...
    "当前代码提交",string(identity.git_commit); ...
    "实际命令",string(identity.actual_command)], ...
    [3000 6360]);
blocks(end+1) = paragraph_block( ...
    "模型、输入Excel、初始化、sigma、tau、独立原始/对偶步长和"+ ...
    "Newton方程均未改变。尺度化只作用于小型小时Schur主元与16维核心"+ ...
    "的数值因子坐标；残差仍由原始未尺度化算子计算。");
inputRows = strings(height(inputHashes),3);
for k=1:height(inputHashes)
    inputRows(k,:) = [string(inputHashes.fileName(k)), ...
        string(inputHashes.actualSHA256(k)), ...
        string(inputHashes.status(k))];
end
blocks(end+1) = heading_block("受控输入SHA256",2);
blocks(end+1) = table_block(["文件","实际SHA256","状态"], ...
    inputRows,[2100 5600 1660]);
blocks(end+1) = heading_block("模型启用与未启用边界",2);
scopeRows = strings(height(modelScope),3);
for k=1:height(modelScope)
    scopeRows(k,:) = [string(modelScope.state(k)), ...
        string(modelScope.model_item(k)), ...
        string(modelScope.evidence_boundary(k))];
end
blocks(end+1) = table_block( ...
    ["状态","目标/约束","证据边界"],scopeRows,[1200 4700 3460]);
blocks(end+1) = paragraph_block( ...
    "已启用目标和约束、未启用目标和约束均从本次真实工件的"+ ...
    "model_scope_audit.csv读取；报告生成时manifest为RUNNING；最终终态"+ ...
    "以run_manifest.json为准。");

blocks(end+1) = heading_block("二、已知失败点的尺度修复",1);
hour3 = hourly(hourly.day==14 & hourly.hour==3,:);
blocks(end+1) = table_block(["指标","未尺度化","尺度化因子坐标"],[ ...
    "数值秩",string(hour3.original_numeric_rank), ...
        string(hour3.scaled_numeric_rank); ...
    "矩阵维数",string(hour3.dimension),string(hour3.dimension); ...
    "cond2",f(hour3.original_condition_2), ...
        f(hour3.scaled_condition_2); ...
    "最小奇异值",f(hour3.original_smin),f(hour3.scaled_smin); ...
    "对称相对误差",f(hour3.symmetry_relative_original), ...
        f(hour3.symmetry_relative_scaled)], ...
    [3100 3130 3130]);
blocks(end+1) = paragraph_block( ...
    "未尺度化路线仍精确复现day 14/hour 3的17/22数值秩门禁失败。"+ ...
    "八遍局部对称对角合同尺度化把该主元恢复为22/22，cond2降低约"+ ...
    f(hour3.condition_reduction_factor)+"倍；没有加入正则化、自动"+ ...
    "对称化或完整KKT方向回退。");

blocks(end+1) = heading_block("三、方向与原算子残差审计",1);
directionRows = strings(height(direction),4);
for k=1:height(direction)
    directionRows(k,:) = [string(direction.metric(k)), ...
        f(direction.value(k)),f(direction.threshold(k)), ...
        string(direction.status(k))];
end
blocks(end+1) = table_block( ...
    ["审计指标","实际值","阈值","结果"], ...
    directionRows,[3900 2100 1900 1460]);
blocks(end+1) = paragraph_block( ...
    "递推路线和完整路线消费同一个linearization。完整KKT仅用于独立"+ ...
    "审计，未向递推路线提供方向或修正量；递推方向代回完整原始KKT的"+ ...
    "相对残差为"+f(summary.recursive_full_kkt_relative_residual)+ ...
    "。实际被分解的D·M·D与记录的尺度向量闭合误差为"+ ...
    f(summary.maximum_congruence_reconstruction_relative)+"。");
blocks(end+1) = heading_block("禁止项与依赖闭包审计",2);
forbiddenRows = strings(height(forbidden),4);
for k=1:height(forbidden)
    forbiddenRows(k,:) = [string(forbidden.check_id(k)), ...
        string(forbidden.evidence_type(k)), ...
        string(forbidden.match_count(k)), ...
        string(forbidden.status(k))];
end
blocks(end+1) = table_block( ...
    ["检查ID","证据类型","匹配数/失败数","结果"], ...
    forbiddenRows,[2700 2600 1800 2260]);
blocks(end+1) = paragraph_block( ...
    "禁止项门禁由真实运行字段和递归依赖闭包独立计算，共"+ ...
    string(height(forbidden))+"项；不得用单一"+ ...
    "no_full_direction_fallback布尔值替代其他禁止项证据。");

blocks(end+1) = heading_block("四、有界精化与确定性",1);
refinementRows = strings(height(refinement),6);
for k=1:height(refinement)
    dayText = "核心";
    if isfinite(refinement.day(k)), dayText=string(refinement.day(k)); end
    refinementRows(k,:) = [string(refinement.component(k)),dayText, ...
        string(refinement.maximum_passes(k)), ...
        string(refinement.correction_count(k)), ...
        f(refinement.initial_maximum_column_relative(k)), ...
        f(refinement.final_maximum_column_relative(k))];
end
blocks(end+1) = table_block( ...
    ["组件","日","上限","修正次数","初始残差","最终残差"], ...
    refinementRows,[1900 800 800 1100 2380 2380]);
blocks(end+1) = paragraph_block( ...
    "所有日链和16维核心统一使用最多3次的stable-v2保留因子精化；"+ ...
    "残差不再下降时立即停止。相同压力输入连续运行两次的完整方向逐位"+ ...
    "一致，最大绝对差为0，方向指纹均为"+ ...
    string(summary.direction_fingerprint)+"。");

blocks(end+1) = heading_block("五、验收、问题与停止边界",1);
blocks(end+1) = table_block(["项目","结果"],[ ...
    "专项测试",string(testSummary.test_passed)+"/"+ ...
        string(testSummary.test_total)+" PASS"; ...
    "阻断验收",string(nnz(string(acceptance.status)=="PASS"))+"/"+ ...
        string(height(acceptance))+" PASS"; ...
    "说明性问题记录",string(height(issues))+"项"; ...
    "状态更新次数","0"; ...
    "阶段状态","stage_A4 / READY"],[3300 6060]);
blocks(end+1) = paragraph_block( ...
    "原始历史runs未修改：历史目录快照比较PASS，共"+ ...
    string(historicalAudit.before_count)+"个历史条目保持字节、时间和SHA256一致。");
blocks(end+1) = paragraph_block( ...
    "本报告在正式工件最终化前生成，因此报告内manifest状态记录为"+ ...
    string(manifest.status)+"；主入口完成全部证据哈希后会将run_manifest.json"+ ...
    "最终化，最终终态只能以该文件为准（本压力测试预期为PASS）。");
blocks(end+1) = callout_block("不得外推", ...
    "该结果仅覆盖权威第24轮冻结压力点的一次Newton方向。它证明批准的"+ ...
    "数值稳定路线在此压力点有效，但尚未重新执行后续完整迭代、正式A4"+ ...
    "收敛候选run或365日扩展；不代表Stage A4通过，也不得进入Stage B。");
end

function blocks = empty_blocks()
blocks = repmat(block_template(),0,1);
end

function value = block_template()
value = struct("type","","level",0,"title","","text","", ...
    "headers",strings(1,0),"rows",strings(0,0), ...
    "widths",zeros(1,0));
end

function block = heading_block(textValue,level)
block=block_template(); block.type="heading";
block.text=string(textValue); block.level=level;
end

function block = paragraph_block(textValue)
block=block_template(); block.type="paragraph";
block.text=string(textValue);
end

function block = callout_block(titleText,textValue)
block=block_template(); block.type="callout";
block.title=string(titleText); block.text=string(textValue);
end

function block = table_block(headers,rows,widths)
block=block_template(); block.type="table";
block.headers=string(headers); block.rows=string(rows);
block.widths=double(widths);
assert(sum(block.widths)==9360, ...
    "stageA4:scaleStress:ReportTableWidth", ...
    "Report table widths must total 9360 DXA.");
end

function value = f(number)
if isnan(double(number))
    value="不适用";
else
    value=string(sprintf("%.17g",double(number)));
end
end

function value = read_json(pathValue)
assert(isfile(pathValue),"stageA4:scaleStress:ReportInput", ...
    "Missing report input %s.",pathValue);
value=jsondecode(fileread(pathValue));
end

function value = read_csv(pathValue)
assert(isfile(pathValue),"stageA4:scaleStress:ReportInput", ...
    "Missing report input %s.",pathValue);
options=detectImportOptions(pathValue,"Delimiter",",", ...
    "TextType","string","VariableNamingRule","preserve");
options.Delimiter=",";
options.DataLines=[2 Inf];
value=readtable(pathValue,options);
end
