function tests = test_stage_b2c_unified_runner
%TEST_STAGE_B2C_UNIFIED_RUNNER Verify configuration, dimensions and caches.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(fullfile(root,"src"));
testCase.TestData.root = root;
[data,~] = rkkt.cache.load_or_build_project_data(root);
testCase.TestData.data = data;
end

function testDefaultRunProjectConfiguration(testCase)
settings = rkkt.config.read_run_project_configuration( ...
    testCase.TestData.root);
verifyEqual(testCase,settings.day_scope,"screened_307");
verifyEqual(testCase,[settings.day_start,settings.day_end],[1,365]);
verifyTrue(testCase,settings.explicit_day_set);
verifyEqual(testCase,numel(settings.days),307);
verifyEqual(testCase,numel(settings.excluded_days),58);
verifyEmpty(testCase,intersect(settings.days,settings.excluded_days));
verifyEqual(testCase,numel(settings.physical_infeasible_days),41);
verifyEqual(testCase,numel(settings.numerically_pathological_days),17);
frozenPreset = string(fileread(fullfile(testCase.TestData.root,"config", ...
    "stage_B_2C_full365_screened_307day_experiment.yaml")));
verifyEqual(testCase,settings.excluded_days, ...
    read_yaml_integer_array(frozenPreset,"excluded_days"));
verifyEqual(testCase,settings.physical_infeasible_days, ...
    read_yaml_integer_array(frozenPreset,"physical_infeasible_days"));
verifyEqual(testCase,settings.numerically_pathological_days, ...
    read_yaml_integer_array(frozenPreset,"numerically_pathological_days"));
verifyTrue(testCase,ismember(settings.audit_mode, ...
    ["full_kkt","recursive_only"]));
verifyTrue(testCase,settings.audit_mode~="full_kkt" || ...
    numel(settings.days)==7);
verifyEqual(testCase,settings.max_iterations,100);
verifyEqual(testCase,settings.core_consistency_max_passes,10);
verifyTrue(testCase,settings.compensated_core_accumulation);
verifyTrue(testCase,settings.cache_enabled);
verifyFalse(testCase,settings.parallel_enabled);
verifyEqual(testCase,settings.parallel_worker_count,4);
verifyTrue(testCase,settings.parallel_pool_auto_resize);
verifyTrue(testCase,settings.parallel_pool_keep_alive);
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    testCase.TestData.root,settings,testCase.TestData.data);
verifyFalse(testCase,config.parallel_enabled);
verifyEqual(testCase,config.parallel_worker_count,4);
verifyEqual(testCase,config.parallel_mode,"off");
verifyEqual(testCase,config.time_scope_type, ...
    "configured_explicit_day_scope");
verifyEqual(testCase,[config.expected_stage_a_primal_dimension, ...
    config.expected_stage_a_equality_dimension, ...
    config.expected_stage_a_inequality_dimension, ...
    config.expected_stage_a_fixed_zero_count, ...
    config.expected_full_kkt_dimension], ...
    [162696,27018,316796,18448,828218]);
end

function testKnownRuntimeDimensions(testCase)
cases = [14,20;1,30;1,365];
expected = [3722,618,7248,422,18948; ...
    15910,2642,30980,1804,80992; ...
    193431,32122,376642,21933,984677];
for row = 1:size(cases,1)
    settings = make_settings(testCase.TestData.root, ...
        cases(row,1),cases(row,2),"recursive_only");
    config = rkkt.model.build_stage_b2c_runtime_configuration( ...
        testCase.TestData.root,settings,testCase.TestData.data);
    actual = [config.expected_stage_a_primal_dimension, ...
        config.expected_stage_a_equality_dimension, ...
        config.expected_stage_a_inequality_dimension, ...
        config.expected_stage_a_fixed_zero_count, ...
        config.expected_full_kkt_dimension];
    verifyEqual(testCase,actual,expected(row,:));
    verifyEqual(testCase,config.local_linear_solve_residual_tolerance, ...
        1e-10,"AbsTol",0);
    verifyEqual(testCase,config.recursive_full_kkt_residual_tolerance, ...
        1e-8,"AbsTol",0);
    verifyEqual(testCase,config.reduced_symmetry_tolerance,1e-8, ...
        "AbsTol",0);
    verifyEqual(testCase,config.border_symmetry_tolerance,1e-8, ...
        "AbsTol",0);
    verifyEqual(testCase,config.lagrangian_hessian_symmetry_tolerance, ...
        1e-8,"AbsTol",0);
    verifyEqual(testCase,config.core_consistency_max_passes,10);
    verifyTrue(testCase,config.compensated_core_accumulation);
end
end

function testExplicitDaySetExcludesDay62(testCase)
settings = make_settings(testCase.TestData.root,1,90,"recursive_only");
settings.days = [1:61,63:90];
settings.explicit_day_set = true;
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    testCase.TestData.root,settings,testCase.TestData.data);
verifyEqual(testCase,config.days,settings.days);
verifyFalse(testCase,ismember(62,config.days));
verifyEqual(testCase,numel(config.days),89);
verifyEqual(testCase,config.time_scope_type, ...
    "configured_explicit_day_scope");
verifyEqual(testCase,config.expected_water_inequality_count,712);
end

function testAllB2CProfilesUseAuthorizedResidualGate(testCase)
root = testCase.TestData.root;
profiles = ["formal_7_day","experimental_30_day", ...
    "supplemental_365_day_serial"];
tokens = ["B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED", ...
    "B-2C-UNIFIED-RUNNER-REFACTOR-AUTHORIZED", ...
    "B-2C-365-SERIAL-RESUMABLE-AUTHORIZED"];
for k = 1:numel(profiles)
    config = rkkt.model.load_stage_b2c_configuration(root, ...
        Profile=profiles(k),CurrentStageExceptionToken=tokens(k));
    verifyEqual(testCase,config.local_linear_solve_residual_tolerance, ...
        1e-10,"AbsTol",0);
    verifyEqual(testCase,config.recursive_full_kkt_residual_tolerance, ...
        1e-8,"AbsTol",0);
    verifyEqual(testCase,config.direction_relative_error_tolerance, ...
        1e-10,"AbsTol",0);
    verifyEqual(testCase,config.full_kkt_residual_tolerance, ...
        1e-10,"AbsTol",0);
    verifyEqual(testCase,config.reduced_symmetry_tolerance,1e-8, ...
        "AbsTol",0);
    verifyEqual(testCase,config.border_symmetry_tolerance,1e-8, ...
        "AbsTol",0);
    verifyEqual(testCase,config.lagrangian_hessian_symmetry_tolerance, ...
        1e-8,"AbsTol",0);
    verifyEqual(testCase,config.core_consistency_max_passes,10);
    verifyTrue(testCase,config.compensated_core_accumulation);
end
end

function testCacheHitAndRunIdRetag(testCase)
settings = make_settings(testCase.TestData.root,14,20,"recursive_only");
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    testCase.TestData.root,settings,testCase.TestData.data);
[first,firstInfo] = rkkt.cache.load_or_build_stage_b2c_index( ...
    testCase.TestData.root,testCase.TestData.data,config);
[second,secondInfo] = rkkt.cache.load_or_build_stage_b2c_index( ...
    testCase.TestData.root,testCase.TestData.data,config);
verifyTrue(testCase,secondInfo.hit);
verifyEqual(testCase,first.counts,second.counts);
tagged = rkkt.artifacts.retag_index_run_id(second,"TEST_RUN_ID");
verifyTrue(testCase,all(string(tagged.variable_index.run_id)=="TEST_RUN_ID"));
verifyTrue(testCase,all(string(tagged.stage_a_base_index. ...
    constraint_index.run_id)=="TEST_RUN_ID"));
verifyEqual(testCase,tagged.variable_index.global_index_start, ...
    second.variable_index.global_index_start);
verifyNotEmpty(testCase,firstInfo.key);
end

function testProgrammaticSettingsUseTheirOwnEvidenceSource(testCase)
root = testCase.TestData.root;
settings = rkkt.config.build_stage_b2c_run_settings(root, ...
    DayStart=1,DayEnd=30,MaxIterations=12, ...
    RequireConvergence=false,AuditMode="recursive_only", ...
    ConfigPath=fullfile(root,"config", ...
        "stage_B_2C_30_day_experiment.yaml"));
verifyEqual(testCase,settings.days,1:30);
verifyEqual(testCase,settings.max_iterations,12);
verifyFalse(testCase,settings.require_convergence);
verifyEqual(testCase,settings.audit_mode,"recursive_only");
verifyEqual(testCase,settings.day_scope,"continuous");
verifyFalse(testCase,settings.explicit_day_set);
verifyEqual(testCase,settings.core_consistency_max_passes,10);
verifyTrue(testCase,settings.compensated_core_accumulation);
verifyFalse(testCase,settings.parallel_enabled);
verifyEqual(testCase,settings.parallel_worker_count,4);
verifyTrue(testCase,endsWith(settings.config_path, ...
    "stage_B_2C_30_day_experiment.yaml"));
end

function testAcceptedHistoryResumesWithLogicalColumns(testCase)
root = testCase.TestData.root;
temporary = string(tempname);
guard = onCleanup(@()remove_temporary_directory(temporary));
context = make_temporary_context(temporary,root);
settings = rkkt.config.build_stage_b2c_run_settings(root, ...
    DayStart=14,DayEnd=20,MaxIterations=2, ...
    RequireConvergence=false,AuditMode="recursive_only", ...
    ConfigPath=fullfile(root,"config","RUN_PROJECT.yaml"));
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    root,settings,testCase.TestData.data);
[index,~] = rkkt.cache.load_or_build_stage_b2c_index( ...
    root,testCase.TestData.data,config);
signature = rkkt.artifacts.compute_package_code_signature(root);
first = rkkt.solver.run_stage_b2c_365day_serial_ipm( ...
    testCase.TestData.data,index,config,context, ...
    MaxIterations=1,SolverCodeSignature=signature);
verifyEqual(testCase,first.accepted_iteration_count,1);
resumed = rkkt.solver.run_stage_b2c_365day_serial_ipm( ...
    testCase.TestData.data,index,config,context, ...
    MaxIterations=2,Resume=true,SolverCodeSignature=signature);
verifyEqual(testCase,resumed.accepted_iteration_count,2);
verifyTrue(testCase,islogical(resumed.iteration_history.converged));
verifyTrue(testCase,islogical( ...
    resumed.factorization_history.solution_finite));
verifyTrue(testCase,islogical( ...
    resumed.water_correction_history.strictly_positive));
verifyTrue(testCase,all( ...
    resumed.water_correction_history.strictly_positive));
clear guard
remove_temporary_directory(temporary);
end

function testResumeIdentityAllowsOperationalYamlChanges(testCase)
temporary = string(tempname);
guard = onCleanup(@()remove_temporary_directory(temporary));
project = fullfile(temporary,"project");
mkdir(fullfile(project,"src","+rkkt"));
mkdir(fullfile(project,"config"));
rkkt.artifacts.write_text_utf8(fullfile(project,"src","+rkkt", ...
    "dummy.m"),"function dummy"+newline+"end"+newline);
configPath = fullfile(project,"config","RUN_PROJECT.yaml");
write_minimal_run_yaml(configPath,"");
settings = rkkt.config.read_run_project_configuration(project);
config = struct("run_purpose","resume_identity_test", ...
    "full_kkt_role","not_executed_configured_recursive_only");
hashes = fake_input_hashes();
signature = string(repmat('3',1,64));
[context,~,resumed] = rkkt.artifacts.prepare_stage_b2c_configured_run( ...
    project,settings,config,hashes,signature,RunId="RESUME_IDENTITY_TEST");
verifyFalse(testCase,resumed);
rkkt.artifacts.write_text_utf8(context.checkpoint_manifest_path, ...
    "iteration"+newline);
write_minimal_run_yaml(configPath,string(context.root));
resumedSettings = rkkt.config.read_run_project_configuration(project);
[actual,~,resumed] = rkkt.artifacts.prepare_stage_b2c_configured_run( ...
    project,resumedSettings,config,hashes,signature, ...
    ResumeRunDirectory=string(context.root));
verifyTrue(testCase,resumed);
verifyEqual(testCase,string(actual.run_id),"RESUME_IDENTITY_TEST");
clear guard
remove_temporary_directory(temporary);
end

function testRunProjectAndStandalone307UseDifferentScanRoutes(testCase)
root = testCase.TestData.root;
mainSource = string(fileread(fullfile(root,"src","+rkkt","run.m")));
sideSource = string(fileread(fullfile(root,"runtime_logs", ...
    "run_307day_full365_screened.m")));
verifyTrue(testCase,contains(mainSource, ...
    "JointMicroborderScanEnabled=false"));
verifyTrue(testCase,contains(sideSource, ...
    "JointMicroborderScanEnabled=true"));
end

function testDailyJointStructureTemplateIsReusedWithScanDisabled(testCase)
root = testCase.TestData.root;
settings = make_settings(root,14,20,"recursive_only");
config = rkkt.model.build_stage_b2c_runtime_configuration( ...
    root,settings,testCase.TestData.data);
[index,~] = rkkt.cache.load_or_build_stage_b2c_index( ...
    root,testCase.TestData.data,config);
state = rkkt.model.initialize_stage_b2c_state( ...
    testCase.TestData.data,index,config);
lin = rkkt.model.build_stage_b2c_scaled_objective_linearization( ...
    state,testCase.TestData.data,index,config,"B-2C-STRUCTURE-UNIT-TEST");
template = rkkt.solver.build_stage_b2c_daily_joint_structure_template(lin);
direction = rkkt.solver.solve_stage_b2c_daily_joint_direction(lin, ...
    SymmetryTolerance=config.reduced_symmetry_tolerance, ...
    LocalResidualTolerance=config.local_linear_solve_residual_tolerance, ...
    ReconstructedKktResidualTolerance= ...
        config.recursive_full_kkt_residual_tolerance, ...
    CoreConsistencyMaximumPasses=config.core_consistency_max_passes, ...
    CompensatedCoreAccumulation=config.compensated_core_accumulation, ...
    DailyJointStructureTemplate=template,JointMicroborderEnabled=false);
verifyTrue(testCase,direction.partition.structure_template_reused);
verifyEqual(testCase,direction.partition.cross_day_nnz,0);
verifyFalse(testCase,direction.diagnostics.joint_microborder_scan_executed);
verifyEqual(testCase,direction.timing.joint_microborder_detection_seconds,0);
verifyEqual(testCase,direction.diagnostics.joint_microborder_detection. ...
    stop_reason,"scan_disabled");
verifyEqual(testCase, ...
    direction.recovery.diagnostics.certified_residual_day_count,7);
verifyEqual(testCase, ...
    direction.recovery.diagnostics.extended_residual_fallback_day_count,0);
verifyTrue(testCase,all( ...
    [direction.recovery.daily_direct_backsolve.certified_residual_used]));
verifyLessThanOrEqual(testCase, ...
    direction.diagnostics.candidate_kkt_relative_residual, ...
    config.recursive_full_kkt_residual_tolerance);
end

function settings = make_settings(root,dayStart,dayEnd,auditMode)
settings = struct("stage_id","stage_B","milestone_id","B-2C", ...
    "day_scope","continuous","day_start",dayStart,"day_end",dayEnd, ...
    "days",dayStart:dayEnd,"explicit_day_set",false, ...
    "excluded_days",zeros(1,0), ...
    "max_iterations",100,"require_convergence",true, ...
    "audit_mode",auditMode,"cache_enabled",true, ...
    "core_consistency_max_passes",10, ...
    "compensated_core_accumulation",true, ...
    "parallel_enabled",false,"parallel_worker_count",4, ...
    "parallel_pool_auto_resize",true, ...
    "parallel_pool_keep_alive",true, ...
    "force_rebuild_data_cache",false, ...
    "force_rebuild_index_cache",false,"run_id","", ...
    "resume_run_directory","", ...
    "config_path",fullfile(root,"config","RUN_PROJECT.yaml"), ...
    "project_root",root);
end

function context = make_temporary_context(temporary,root)
mkdir(temporary);
diagnostics = fullfile(temporary,"diagnostics");
checkpoints = fullfile(temporary,"checkpoints");
mkdir(diagnostics); mkdir(checkpoints);
effectiveConfig = fullfile(temporary,"effective_config.yaml");
copyfile(fullfile(root,"config","RUN_PROJECT.yaml"),effectiveConfig);
[hashes,passed] = rkkt.data.verify_input_hashes(root);
assert(passed);
base = hashes.fileName=="基础参数.xlsx";
series = hashes.fileName=="输入数据.xlsx";
manifest = struct("run_id","RESUME_LOGICAL_TYPE_TEST", ...
    "stage_id","stage_B","status","RUNNING", ...
    "git_commit","TEST_COMMIT", ...
    "input_hashes",struct( ...
        "base_parameters",char(hashes.actualSHA256(base)), ...
        "timeseries",char(hashes.actualSHA256(series))));
manifestPath = fullfile(temporary,"run_manifest.json");
rkkt.artifacts.write_json_file(manifestPath,manifest);
context = struct("root",char(temporary),"project_root",char(root), ...
    "run_id","RESUME_LOGICAL_TYPE_TEST","stage_id","stage_B", ...
    "run_manifest_path",char(manifestPath), ...
    "effective_config_path",char(effectiveConfig), ...
    "checkpoints_dir",char(checkpoints), ...
    "checkpoint_manifest_path",char(fullfile(checkpoints, ...
        "checkpoint_manifest.csv")));
end

function remove_temporary_directory(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,"s");
end
end


function write_minimal_run_yaml(pathValue,resumeDirectory)
document = [ ...
    "stage_id: ""stage_B"""
    "milestone_id: ""B-2C"""
    "day_scope: ""continuous"""
    "day_start: 14"
    "day_end: 20"
    "max_iterations: 2"
    "require_convergence: false"
    "audit_mode: ""recursive_only"""
    "core_consistency_max_passes: 10"
    "compensated_core_accumulation: true"
    "parallel_enabled: false"
    "parallel_worker_count: 4"
    "parallel_pool_auto_resize: true"
    "parallel_pool_keep_alive: true"
    "cache_enabled: true"
    "force_rebuild_data_cache: false"
    "force_rebuild_index_cache: false"
    "run_id: """""
    "resume_run_directory: """+replace(resumeDirectory,"\","/")+""""];
rkkt.artifacts.write_text_utf8(pathValue,strjoin(document,newline)+newline);
end

function value = fake_input_hashes()
hash = [string(repmat('1',1,64));string(repmat('2',1,64))];
value = table(["基础参数.xlsx";"输入数据.xlsx"],hash, ...
    'VariableNames',{'fileName','actualSHA256'});
end

function value = read_yaml_integer_array(document,key)
pattern = ['(?m)^',regexptranslate('escape',char(key)), ...
    ':[ \t]*\[(.*?)\][ \t]*$'];
tokens = regexp(char(document),pattern,'tokens');
assert(isscalar(tokens));
value = reshape(str2double(split(string(tokens{1}{1}),",")),1,[]);
end
