function tests = test_stage_b2c_365day_resume
%TEST_STAGE_B2C_365DAY_RESUME Fast tests for explicit same-run recovery.
tests = functiontests(localfunctions);
end

function setup(testCase)
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
addpath(genpath(fullfile(root,"src")));
temporary = string(tempname);
project = fullfile(temporary,"project");
runRoot = fullfile(project,"runs","B2C_365_RESUME_TEST");
for directory = ["iterations","indices","matrices","checkpoints", ...
        "tests","issues","acceptance","reports"]
    mkdir(fullfile(runRoot,directory));
end
context = make_context(project,runRoot,"B2C_365_RESUME_TEST");
rkkt.artifacts.write_text_utf8(context.effective_config_path, ...
    "stage_id: ""stage_B"""+newline);
manifest = struct("run_id",context.run_id,"stage_id","stage_B", ...
    "status","RUNNING");
rkkt.artifacts.write_json_file(context.run_manifest_path,manifest);
testCase.TestData.temporary = temporary;
testCase.TestData.project = project;
testCase.TestData.context = context;
testCase.TestData.repository = root;
end

function teardown(testCase)
if isfolder(testCase.TestData.temporary)
    rmdir(testCase.TestData.temporary,"s");
end
end

function testExplicitExistingRunDirectoryKeepsIdentity(testCase)
[actual,manifest] = rkkt.artifacts.open_existing_run_context( ...
    testCase.TestData.project,testCase.TestData.context.root,"stage_B");
verifyEqual(testCase,string(actual.run_id),"B2C_365_RESUME_TEST");
verifyEqual(testCase,string(actual.root), ...
    string(testCase.TestData.context.root));
verifyEqual(testCase,string(manifest.status),"RUNNING");
end

function testRunIdOrNestedDirectoryCannotImpersonateExplicitRun(testCase)
verifyError(testCase,@()rkkt.artifacts.open_existing_run_context( ...
    testCase.TestData.project,"B2C_365_RESUME_TEST","stage_B"), ...
    "rkkt:runs:ResumeDirectoryMissing");
nested = fullfile(testCase.TestData.context.root,"checkpoints");
verifyError(testCase,@()rkkt.artifacts.open_existing_run_context( ...
    testCase.TestData.project,nested,"stage_B"), ...
    "rkkt:runs:ResumeDirectoryScope");
end

function testTerminalRunCannotResume(testCase)
manifest = jsondecode(fileread(testCase.TestData.context.run_manifest_path));
manifest.status = "FAIL_RETRYABLE";
rkkt.artifacts.write_json_file( ...
    testCase.TestData.context.run_manifest_path,manifest);
verifyError(testCase,@()rkkt.artifacts.open_existing_run_context( ...
    testCase.TestData.project,testCase.TestData.context.root,"stage_B"), ...
    "rkkt:runs:ResumeRunNotActive");
end

function testAuthorized365ConfigurationIsRecursiveSerialOnly(testCase)
config = rkkt.model.load_stage_b2c_configuration( ...
    testCase.TestData.repository,Profile="supplemental_365_day_serial");
verifyEqual(testCase,config.days,1:365);
verifyEqual(testCase,config.expected_stage_a_primal_dimension,193431);
verifyEqual(testCase,config.expected_stage_a_equality_dimension,32122);
verifyEqual(testCase,config.expected_stage_a_inequality_dimension,376642);
verifyEqual(testCase,config.expected_water_inequality_count,2920);
verifyEqual(testCase,config.expected_full_kkt_dimension,984677);
verifyEqual(testCase,config.local_linear_solve_residual_tolerance, ...
    1e-10,"AbsTol",0);
verifyEqual(testCase,config.recursive_full_kkt_residual_tolerance, ...
    1e-8,"AbsTol",0);
verifyFalse(testCase,config.parallel_enabled);
verifyFalse(testCase,config.annual_scope_enabled);
verifyFalse(testCase,config.full_kkt_enabled);
verifyFalse(testCase,config.thermal_second_pass_enabled);
end

function testResumePreparationBindsConfigInputAndCode(testCase)
context = testCase.TestData.context;
sourceConfig = fullfile(testCase.TestData.project,"config", ...
    "stage_B_2C_365_day_serial_experiment.yaml");
mkdir(fileparts(sourceConfig));
rkkt.artifacts.write_text_utf8(sourceConfig, ...
    "stage_id: ""stage_B"""+newline);
copyfile(sourceConfig,context.effective_config_path,"f");
baseHash = string(repmat('1',1,64));
seriesHash = string(repmat('2',1,64));
inputHashes = table(["基础参数.xlsx";"输入数据.xlsx"], ...
    [baseHash;seriesHash], ...
    'VariableNames',{'fileName','actualSHA256'});
signature = string(repmat('3',1,64));
manifest = jsondecode(fileread(context.run_manifest_path));
manifest.run_purpose = "stage_B_2C_365_day_serial_recursive_ipm_experiment";
manifest.milestone = "B-2C-365-DAY-SERIAL-SUPPLEMENT";
manifest.checkpoint_solver_code_signature = signature;
manifest.time_scope = "days_1_to_365_full_24_hours";
manifest.full_kkt_role = "not_executed_365_day_serial_experiment";
manifest.resume_supported = true;
manifest.experiment_mode = "convergence_run";
manifest.convergence_required = true;
manifest.input_hashes = struct("base_parameters",char(baseHash), ...
    "timeseries",char(seriesHash));
rkkt.artifacts.write_json_file(context.run_manifest_path,manifest);
rkkt.artifacts.write_text_utf8(context.checkpoint_manifest_path,"iteration"+newline);
config = struct("run_purpose",string(manifest.run_purpose), ...
    "full_kkt_role",string(manifest.full_kkt_role));
[actual,~,resumed] = rkkt.artifacts.prepare_stage_b2c_365day_run( ...
    testCase.TestData.project,config,inputHashes,signature, ...
    ResumeRunDirectory=context.root);
verifyTrue(testCase,resumed);
verifyEqual(testCase,string(actual.run_id),string(context.run_id));
verifyError(testCase,@()rkkt.artifacts.prepare_stage_b2c_365day_run( ...
    testCase.TestData.project,config,inputHashes,string(repmat('4',1,64)), ...
    ResumeRunDirectory=context.root), ...
    "stageB2C:day365:ResumeIdentity");
end

function testCheckpointChainMetadataAndRebuiltFingerprint(testCase)
context = testCase.TestData.context;
state0 = make_state(0);
linearization0 = make_linearization(state0,"L0");
metadata0 = make_metadata(0);
record0 = rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state0,linearization0,metadata0);
state1 = make_state(1);
linearization1 = make_linearization(state1,"L1");
metadata1 = make_metadata(1);
record1 = rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state1,linearization1,metadata1);
verifyEqual(testCase,string(record1.previous_checkpoint_sha256), ...
    string(record0.sha256));
expected = rmfield(metadata1,"iteration");
rebuilt = rkkt.diagnostics.compute_stage_a4_rns1_fingerprint( ...
    linearization1,"linearization");
[checkpoint,selected] = rkkt.artifacts.load_stage_b2c_checkpoint( ...
    context,NaN,ExpectedMetadata=expected, ...
    RebuiltLinearizationFingerprint=rebuilt);
verifyEqual(testCase,double(selected.iteration),1);
verifyEqual(testCase,checkpoint.state,state1);

wrong = expected; wrong.solver_code_signature = repmat('0',1,64);
verifyError(testCase,@()rkkt.artifacts.load_stage_b2c_checkpoint( ...
    context,NaN,ExpectedMetadata=wrong), ...
    "stageB2C:checkpoint:ExpectedMetadata");
verifyError(testCase,@()rkkt.artifacts.load_stage_b2c_checkpoint( ...
    context,NaN,RebuiltLinearizationFingerprint=string(repmat('f',1,64))), ...
    "stageB2C:checkpoint:RebuiltLinearization");
end

function testCheckpointManifestTamperBreaksWholeChain(testCase)
context = testCase.TestData.context;
state = make_state(0);
rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state,make_linearization(state,"L0"),make_metadata(0));
manifest = readtable(context.checkpoint_manifest_path, ...
    TextType="string",VariableNamingRule="preserve");
manifest.sha256(1) = string(repmat('0',1,64));
rkkt.artifacts.write_table_csv_17g_atomic( ...
    context.checkpoint_manifest_path,manifest);
verifyError(testCase,@()rkkt.artifacts.load_stage_b2c_checkpoint(context), ...
    "stageB2C:checkpoint:Hash");
end

function testB2CCheckpointWriterRejectsTerminalRun(testCase)
context = testCase.TestData.context;
manifest = jsondecode(fileread(context.run_manifest_path));
manifest.status = "PASS";
rkkt.artifacts.write_json_file(context.run_manifest_path,manifest);
state = make_state(0);
verifyError(testCase,@()rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state,make_linearization(state,"L0"),make_metadata(0)), ...
    "stageB2C:checkpoint:RunNotRunning");
end

function testMatchingOrphanCheckpointIsAdoptedWithoutOverwrite(testCase)
context = testCase.TestData.context;
state = make_state(0);
linearization = make_linearization(state,"L0");
metadata = make_metadata(0);
record = rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state,linearization,metadata);
pathValue = fullfile(context.checkpoints_dir,"iteration_000.mat");
before = rkkt.data.compute_sha256_file(pathValue);
delete(context.checkpoint_manifest_path);
adopted = rkkt.artifacts.write_stage_b2c_checkpoint( ...
    context,state,linearization,metadata);
after = rkkt.data.compute_sha256_file(pathValue);
verifyEqual(testCase,after,before);
verifyEqual(testCase,string(adopted.sha256),string(record.sha256));
end

function context = make_context(projectRoot,runRoot,runId)
context = struct("project_root",char(projectRoot), ...
    "runs_root",char(fullfile(projectRoot,"runs")), ...
    "root",char(runRoot),"run_dir",char(runRoot), ...
    "run_id",char(runId),"stage_id","stage_B", ...
    "iterations_dir",char(fullfile(runRoot,"iterations")), ...
    "indices_dir",char(fullfile(runRoot,"indices")), ...
    "matrices_dir",char(fullfile(runRoot,"matrices")), ...
    "checkpoints_dir",char(fullfile(runRoot,"checkpoints")), ...
    "tests_dir",char(fullfile(runRoot,"tests")), ...
    "issues_dir",char(fullfile(runRoot,"issues")), ...
    "acceptance_dir",char(fullfile(runRoot,"acceptance")), ...
    "reports_dir",char(fullfile(runRoot,"reports")), ...
    "run_manifest_path",char(fullfile(runRoot,"run_manifest.json")), ...
    "effective_config_path",char(fullfile(runRoot,"effective_config.yaml")), ...
    "checkpoint_manifest_path",char(fullfile(runRoot,"checkpoints", ...
        "checkpoint_manifest.csv")));
end

function value = make_state(revision)
value = struct("xi",[1;2]+revision,"y",[3;4]+revision, ...
    "l",[5;6]+revision,"z",[7;8]+revision, ...
    "iteration_index",double(revision), ...
    "state_revision",double(revision), ...
    "newton_direction_number",double(revision+1), ...
    "completed_newton_direction_count",double(revision));
end

function value = make_linearization(state,identity)
value = struct("identity",string(identity),"H",sparse(eye(2)), ...
    "A",sparse([1,0]),"G",sparse([0,1]), ...
    "r_eq",0,"r_ineq",0,"r_dual",[0;0],"r_comp",0, ...
    "l",state.l(1),"z",state.z(1),"mu",state.l(1)*state.z(1), ...
    "state",state,"objective",struct("gradient",[1;1]), ...
    "constraints",struct("eq_offset",0,"ineq_offset",0));
end

function value = make_metadata(iteration)
value = struct("iteration",double(iteration), ...
    "git_commit",repmat('a',1,40), ...
    "config_sha256",repmat('b',1,64), ...
    "input_hash_fingerprint",repmat('c',1,64), ...
    "solver_code_signature",repmat('d',1,64), ...
    "recursive_route","all_inequality_daily_joint_final_kkt_residual_gate", ...
    "full_kkt_role","not_executed_365_day_serial_experiment", ...
    "time_scope_type","supplemental_365_day_serial_scope");
end
