function identity = bind_stage_a4_3_specialty_test_evidence( ...
        projectRoot,runId,evidenceDirectory)
%BIND_STAGE_A4_3_SPECIALTY_TEST_EVIDENCE Bind exact tests to one formal run.
%
% The fixed-suite runner is reusable in temporary directories.  This
% binder is the production-only step that proves the persisted specialty
% evidence belongs to the current A4-3 run, code commit, effective
% configuration, controlled input-hash artifact, and actual command.

arguments
    projectRoot (1,1) string
    runId (1,1) string
    evidenceDirectory (1,1) string
end
runRoot = fullfile(projectRoot,"runs",runId);
manifestPath = fullfile(runRoot,"run_manifest.json");
effectiveConfigPath = fullfile(runRoot,"effective_config.yaml");
inputHashesPath = fullfile(runRoot,"input_hashes.csv");
expectedDirectory = fullfile(runRoot,"tests","a4_3_specialty");
assert(isfolder(runRoot) && isfile(manifestPath) && ...
    canonical_path(evidenceDirectory)==canonical_path(expectedDirectory), ...
    "stageA4:tests:SuiteRunBinding", ...
    "Formal A4-3 specialty evidence must be inside its current run.");
manifest = jsondecode(fileread(manifestPath));
assert(string(manifest.run_id)==runId && ...
    string(manifest.stage_id)=="stage_A4" && ...
    string(manifest.status)=="RUNNING" && ...
    isfield(manifest,"postprocess_phase") && ...
    ismember(string(manifest.postprocess_phase),["IN_PROGRESS","COMPLETE"]), ...
    "stageA4:tests:SuiteRunIdentity", ...
    "A4-3 specialty evidence requires the matching postprocessed RUNNING run.");

requiredNames = [ ...
    "test_inventory.csv"
    "test_results.csv"
    "test_results.xml"
    "matlab_test_console.log"
    "test_command.txt"
    "test_summary.json"
    "test_evidence_sha256.csv"];
requiredPaths = fullfile(evidenceDirectory,requiredNames);
assert(all(isfile(requiredPaths)) && ...
    isfile(effectiveConfigPath) && isfile(inputHashesPath), ...
    "stageA4:tests:SuiteEvidenceMissing", ...
    "Formal A4-3 specialty evidence is incomplete.");

expectedInventoryPath = fullfile(projectRoot,"tests", ...
    "stage_A4_3_expected_test_inventory.csv");
inventory = readtable(requiredPaths(1),"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
expected = readtable(expectedInventoryPath,"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
results = readtable(requiredPaths(2),"TextType","string", ...
    "VariableNamingRule","preserve","Delimiter",",");
summary = jsondecode(fileread(requiredPaths(6)));
assert(height(expected)==27 && isequal(inventory,expected) && ...
    height(results)==27 && ...
    isequal(string(results.test_name),string(expected.test_name)) && ...
    string(summary.execution_status)=="COMPLETE" && ...
    string(summary.suite_label)=="stage_A4_3" && ...
    double(summary.test_total)==27 && double(summary.test_passed)==27 && ...
    double(summary.test_failed)==0 && double(summary.test_incomplete)==0, ...
    "stageA4:tests:SuiteEvidenceIdentity", ...
    "Formal A4-3 specialty evidence differs from the fixed 27-test suite.");
commandText = strip(string(fileread(requiredPaths(5))));
assert(contains(commandText,"run_stage_A4_3_tests") && ...
    contains(commandText,runId) && ...
    contains(replace(commandText,"\","/"),"tests/a4_3_specialty"), ...
    "stageA4:tests:SuiteCommandIdentity", ...
    "The persisted A4-3 specialty command is not bound to this run.");

identity = struct( ...
    "schema_version","stage_A4_3_specialty_identity_v1.0", ...
    "run_id",char(runId), ...
    "stage_id","stage_A4", ...
    "git_commit",char(string(manifest.git_commit)), ...
    "suite_label","stage_A4_3", ...
    "test_total",27, ...
    "expected_inventory_sha256",char(rkkt.data.compute_sha256_file( ...
        expectedInventoryPath)), ...
    "effective_config_sha256",char(rkkt.data.compute_sha256_file( ...
        effectiveConfigPath)), ...
    "input_hashes_csv_sha256",char(rkkt.data.compute_sha256_file( ...
        inputHashesPath)), ...
    "test_command_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(5))), ...
    "test_inventory_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(1))), ...
    "test_results_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(2))), ...
    "test_junit_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(3))), ...
    "test_console_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(4))), ...
    "test_summary_sha256",char(rkkt.data.compute_sha256_file(requiredPaths(6))), ...
    "test_evidence_manifest_sha256",char(rkkt.data.compute_sha256_file( ...
        requiredPaths(7))));
identityPath = fullfile(evidenceDirectory,"suite_identity.json");
if isfile(identityPath)
    observed = jsondecode(fileread(identityPath));
    assert(isequaln(orderfields(observed),orderfields(identity)), ...
        "stageA4:tests:SuiteIdentityConflict", ...
        "Existing suite_identity.json differs from rebuilt run facts.");
    return
end
assert(~isfolder(identityPath), ...
    "stageA4:tests:SuiteIdentityConflict", ...
    "A directory exists at suite_identity.json.");
temporary = string(tempname(evidenceDirectory))+".json";
cleanup = onCleanup(@()delete_if_present(temporary));
rkkt.artifacts.write_json_file(temporary,identity);
[moved,message] = movefile(temporary,identityPath);
assert(moved,"stageA4:tests:SuiteIdentityPublish","%s",message);
clear cleanup
end

function value = canonical_path(pathValue)
value = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end

function delete_if_present(pathValue)
if isfile(pathValue)
    delete(pathValue);
end
end
